<a href="https://colab.research.google.com/github/Deminalla/TNM-G-classification/blob/main/TNM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install bitsandbytes
!pip install accelerate
!pip install --upgrade transformers

In [ ]:
import transformers
print(transformers.__version__)

In [46]:
import pandas as pd
from sklearn.model_selection import train_test_split
from huggingface_hub import login
from transformers import AutoTokenizer, AutoModelForCausalLM
import warnings

warnings.filterwarnings("ignore")

file_path = 'dataset.xlsx'
sheet1 = pd.read_excel(file_path, sheet_name='Sheet1')

# Shuffle the dataset
data = sheet1.sample(frac=1, random_state=42).reset_index(drop=True)
data = data.dropna(subset=['pTNM'])

# i dont think grades such as 4 or 9 should exist. I dont know why those were classified as such
data = data[~data['G'].isin([4, 9])]

# combined data
selected_columns = data[['HistoApibudinimas', 'MakroAprasymas', 'PatologijosDiag', 'MikroAprasymas', 'IHCAprasymas']]
combined_column = selected_columns.apply(lambda row: '. '.join(row.astype(str)), axis=1)
data['input'] = combined_column

# Split into training (70%), validation (10%), and test (20%) sets
train, temp = train_test_split(data, test_size=0.3, random_state=42)
val, test = train_test_split(temp, test_size=(2/3), random_state=42)

# Reset the index for all splits
train = train.reset_index(drop=True)
val = val.reset_index(drop=True)
test = test.reset_index(drop=True)

# Prompt generation

In [ ]:
# for accessing models
login(token="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")

# "microsoft/Phi-4-mini-instruct"
# "google/gemma-2-2b"
# "meta-llama/Llama-3.2-3B"
model = "meta-llama/Llama-3.2-3B"

tokenizer = AutoTokenizer.from_pretrained(model)
model = AutoModelForCausalLM.from_pretrained(model, device_map="auto",
                                             load_in_8bit=True)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def evaluateWeighted(y_true, y_pred):
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='weighted')
    recall = recall_score(y_true, y_pred, average='weighted')
    f1 = f1_score(y_true, y_pred, average='weighted')

    print(f"Accuracy: {accuracy}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")

In [ ]:
classification_labels_T = ["x", "0", "is", "1", "1mi", "1a", "1b", "1c", "2", "3", "4", "4a", "4b", "4c", "4d"]
classification_labels_N = ["x", "0", "1", "1mi", "1a", "1b", "1c", "2", "2a", "2b", "3", "3a", "3b", "3c"]
classification_labels_G = ["x", "0", "1", "2", "3"]

##Tumor (T)

In [ ]:
t_labels = train["Tumor (T)"].tolist()

testT = test
trainT = train
valT = val

In [ ]:
def generate_prompt_T(data_point):
    return f"""
            **Naviko klasifikacijos žymės ir paaiškinimai**:
            x – naviko nustatyti neįmanoma;
            0 – naviko nėra;
            is – carcinoma in situ: intraduktalinė karcinoma ar lobulinė karcinoma in situ, ar spenelio Pedžeto liga nesant naviko;
            1 – navikas, kurio matmuo yra 2 cm arba mažesnis;
            1mi – mikroinvazija, kurios matmuo ne didesnis kaip 0,1cm;
            1a – navikas, kurio matmuo nuo 0,1 iki 0,5 cm;
            1b – navikas, kuris  didesnis negu 0,5 cm, bet neviršija 1 cm;
            1c – navikas, kuris didesnis negu 1 cm, bet neviršija 2 cm;
            2 – navikas, kuris didesnis negu 2 cm, bet neviršija 5 cm;
            3 – navikas didesnis negu 5 cm;
            4 – bet kokio dydžio navikas, tiesiogiai infiltravęs krūtinės ląstos sieną ar odą;
            4a – krūtinės sienos infiltracija;
            4b – krūties odos edema, išopėjimas ar satelitiniai odos mazgeliai toje pačioje krūtyje;
            4c – T4a ir T4b požymiai;
            4d – uždegiminė karcinoma;

            **Pavyzdžiai**:
            - Įvestis: 1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 10 mm ilgio. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma. Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių. Her2 imuninė reakcija: neigiama 1+. Ki67+ 15%. Krūties audinį infiltruoja pavienės duktalinės struktūros, juostos ir trabekulės iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių neiddentifikuota. Navikas Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių. Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių. Ki67+ 15.
            - Rezultatas: 1

            - Įvestis: Paimti 5 biopsiniai stulpeliai. 5 biopsiniai stulpeliai: I - 16 mm; II - 8 mm; III - 13 mm; IV - 7 mm, V - 9 mm. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma. --- Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100%. Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 80%. Her2 imunohistocheminė reakcija neigiama (0 balų). Ki67: 35%. Solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne blyškiai-saikingai eozinofiline citoplazma, vidutinio kalibro apvalios formos saikingai netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 25 / 10 DPRL. Navikas (1 blokas): Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100%. Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 80%. HER2: nusidažiusių naviko ląstelių nėra.  Ki67: 35%. CK5(-); PanCK(+++)(citoplazminė r-ja), 10
            - Rezultatas: 2

            - Įvestis: 1 ėminio aprašas: 3 bioptatai 12G 22 mm adata iš darinio su mkk. 3 biopsiniai stulpeliai: I - 16 mm; II - 12 mm; III - 14 mm. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 35%. Krūties audinį infiltruoja negausios duktalinės struktūros, smulkūs solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 12/10 DPRL.Navikas Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių. Her2 imuninė reakcija: stiprus visos membranos nusidažymas 80% naviko ląstelių. Ki67+ 35%.
            - Rezultatas: 3

            - Įvestis: 1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 14 mm. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių. Her2 imuninė reakcija: neigiama 0+. Ki67+ 8%. Krūties audinį infiltruoja netaisyklingi kribroziniai/solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių. K.
            - Rezultatas: 4b

            - Įvestis: 3 bioptatai 22 mm 14 G adata, dviejuose - kalcinatai. 3 fragmentuoti biopsiniai stulpeliai: I - 15 mm; II - 17 mm; III - 16 mm.Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 95% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 2% naviko ląstelių. Her2 imuninė reakcija: teigiama 3+. Ki67+ 25%. Krūties audinį infiltruoja negausūs smulkūs solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL. Navikas Estrogenų receptoriai: vidutinis branduolių nusidažymas 95% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 2% naviko ląstelių. Her2 imuninė reakcija: stiprus visos membranos nusidažymas 80% naviko ląstelių. Ki67+ 25%.
            - Rezultatas: is

            - Įvestis: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 10 mm; II - 12 mm. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma. Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių. Her2 imuninė reakcija: neigiama 1+. Ki67+ 20%. Krūties audinį infiltruoja pavienės duktalinės struktūros, netaisyklingi kribroziniai/solidiniai kompleksai ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL. Navikas Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių. Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių. Ki67+ 20%.
            - Rezultatas: 1c

            **Užduotis**:
            Išanalizuokite šią įvestį ir padarykite naviko klasifikaciją pagal duotas žymes. Jau gydytojas padarė klinikinę diagnozę ir klasifikavo kaip {data_point["cT"]}.
            Tačiau nauji duomenys gali pateikti papildomos informacijos ir keisti ankstesnį vertinimą. Taigi, prašau padaryti teisingą ir klasifikaciją pagal šią įvestį.

            [{data_point["input"]}] = """

In [ ]:
X_test = pd.DataFrame(testT.apply(generate_prompt_T, axis=1), columns=["input"])
X_train = pd.DataFrame(trainT.apply(generate_prompt_T, axis=1), columns=["input"])
X_val = pd.DataFrame(valT.apply(generate_prompt_T, axis=1), columns=["input"])

In [ ]:
from tqdm import tqdm
from transformers import pipeline

def predictT(model, tokenizer):
    t_pred = []
    pipe = pipeline(task="text-generation",
                model=model,
                tokenizer=tokenizer,
                max_new_tokens = 2,
                do_sample=False
                )

    for i in tqdm(range(len(X_train))):
        prompt = X_train.iloc[i]["input"]
        result = pipe(prompt)
        print("result ", result)
        answer = result[0]['generated_text'].split("=")[-1].strip()
        print("input: ", trainT.iloc[i]["input"])
        answer = str(answer).lower()
        print("answer: ", answer)
        if answer in classification_labels_T:
            t_pred.append(answer)
        else:
            t_pred.append("-1")

    return t_pred

In [ ]:
t_pred = predictT(model, tokenizer)

In [ ]:
evaluateWeighted(t_labels, t_pred)

## Node (N)

In [ ]:
def generate_prompt_N(data_point):
    return f"""
            **Metastazės sritiniuose limfmazgiuose klasifikacijos ir jų paaiškinimai**:
            x – metastazių sritiniuose limfmazgiuose neįmanoma įvertinti (limfmazgiai nepašalinti arba pašalinti anksčiau);
            0 – metastazių sritiniuose limfmazgiuose nėra;
            1 – yra paslankių metastazių tos pačios pusės pažasties limfmazgiuose;
            1mi – yra tik mikrometastazių (nuo 0,2 mm ir ne didesnių kaip 0,2 cm);
            1a – nuo 1 iki 3 limfinių mazgų metastazių pažasties limfiniuose mazguose;
            1b – yra metastazių vidiniuose limfmazgiuose su mikroskopine liga, nustatoma po sarginio limfinio mazgo pašalinimo;
            1c – yra 1–3 metastazės pažasties limfmazgiuose ir mikroskopinė liga vidiniuose limfmazgiuose, nustatytos po sarginio limfinio mazgo pašalinimo;
            2 – yra metastazių nuo 4 iki 9 pažasties limfiniuose mazguose ar kliniškai aiškios vidinės krūties limfinių mazgų metastazės, nesant pažasties limfmazgių metastazių;
            2a – yra metastazių nuo 4 iki 9 limfinių mazgų (naviko dydis turi būti didesnis nei 2,0 mm);
            2b – kliniškai aiškios metastazės vidiniuose krūties limfmazgiuose, nesant pažasties limfinių mazgų pažeidimo;
            3 – yra daugiau kaip 10 metastazių tos pačios pusės pažasties limfiniuose mazguose, ar poraktikauliniuose limfiniuose mazguose, ar kliniškai aiškūs tos pačios pusės vidiniai limfiniai mazgai su 1 ar daugiau metastatiniais pažasties limfiniais mazgais, ar daugiau nei 3 pažasties limfinių mazgų metastazės su kliniškai negatyviomis mikroskopinėmis metastazėmis tos pačios pusės vidiniuose krūties limfmazgiuose; viršraktikauliniai limfiniai mazgai;
            3a – metastazės daugiau kaip 10 pažasties limfinių mazgų ar metastazės poraktikauliniame (-iuose) limfiniame (-iuose) mazge (-uose);
            3b – kliniškai neabejotinos metastazės tos pačios pusės vidiniuose limfiniuose mazguose su daugiau kaip 1 metastaze pažasties limfiniuose mazguose; ar daugiau kaip 3 metastazės pažasties limfiniuose mazguose ir mikroskopinės metastazės vidiniuose tos pačios pusės limfiniuose mazguose;
            3c - metastazės virš raktikaulių esančiuose limfmazgiuose;

            **Pavyzdžiai**:
            - Įvestis: 1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 10 mm; II - 10 mm; III - 10 mm. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) mucininė karcinoma. Imunofenotipas: Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių. Progesterono receptoriai: vidutinė reakcija 95% naviko ląstelių. Her2 imuninė reakcija: neigiama (0). Ki67 proliferacinis aktyvumas 5%. Fragmentuotuose bioptatuose (1/3) - ekstraląsteliniuose mucinuose negausios trabekulinės, kribriforminės naviko struktūros, suformuotos ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio-smulkaus kalibro, ovalaus kontūro branduoliais; mitozių 0/10 DPRL. Navikas:   Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (++)(brand. r-ja) 95%. HER2: nusidažiusių ląstelių nėra. Ki67 proliferacinis aktyvumas 5%.
            - Rezultatas: 1a

            - Įvestis: 1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 13 mm ilgio. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma. Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Her2 imuninė reakcija: neigiama 1+. Ki67+ 15%, vietomis 20%. Krūties audinį infiltruoja duktalinės struktūros ir nedideli netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 1/10 DPRL. Navikas Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių. Ki67+ 1.
            - Rezultatai: 1mi

            - Įvestis: 1 ėminio aprašas: biopsijos iš kairės krūties. 2 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 8 mm. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Her2 imuninė reakcija: neigiama 0+. Ki67+ 4%. Krūties audinį infiltruoja susiliejantys kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
            - Rezultatas: 2

            - Įvestis: 1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 10 mm. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Her2 imuninė reakcija: neigiama 1+. Ki67+ 35-40%. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 30/10 DPRL. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 12% naviko ląstelių. Ki67+ 35.
            -Rezultatas: x

            - Įvestis: 1 ėminio aprašas: 1 but. 1 biopsinis stulpelis i š dešinės pažasties l lygio l/m. 2 but. 1 biopsinis stulpelis iš dešinės krūties BI-RADS 5 darinio. 1. Biopsinis stulpelis 7 mm ilgio. 2. Biopsinis stulpelis 14 mm ilgio. 1. Duktalinės karcinomos metastazė limfmazgyje. 2. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma. Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių. Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama (1+). Ki67+ 10%. 1. Limfmazgio bioptate plinta žemiau aprašyto naviko struktūros. 2. Krūties audinį infiltruoja duktalinės struktūros (20%), netaisyklingi kribroziniai kompleksai ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL. Blokas 2:  Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių branduoliuose. Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių branduoliuose. HER2: silpna (+) necirkuliari reakcija, 3%  naviko ląstelių membranoje. Ki.
            - Rezultatas: 3a

            - Įvestis: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 10 mm; II - 12 mm. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma. Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių. Her2 imuninė reakcija: neigiama 1+. Ki67+ 20%. Krūties audinį infiltruoja pavienės duktalinės struktūros, netaisyklingi kribroziniai/solidiniai kompleksai ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių. Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių. Ki67+ 20%
            - Rezultatas: 0

            **Užduotis**:
            Išanalizuokite šį tekstą ir padarykite metastazės sritiniuose limfmazgiuose klasifikaciją pagal duotas žymes. Jau gydytojas padarė klinikinę diagnozę ir klasifikavo kaip {data_point["cN"]}.
            Tačiau nauji duomenys gali pateikti papildomos informacijos ir keisti ankstesnį vertinimą. Taigi, prašau padaryti teisingą ir klasifikaciją pagal šią įvestį.

            [{data_point["input"]}] = """

In [ ]:
n_labels = [label.lower() for label in train["Node (N)"].tolist()]

testN = test
trainN = train
valN = val

X_test = pd.DataFrame(testN.apply(generate_prompt_N, axis=1), columns=["input"])
X_train = pd.DataFrame(trainN.apply(generate_prompt_N, axis=1), columns=["input"])
X_val = pd.DataFrame(valN.apply(generate_prompt_N, axis=1), columns=["input"])

In [ ]:
from tqdm import tqdm
from transformers import pipeline

def predictN(model, tokenizer):
    n_pred = []
    pipe = pipeline(task="text-generation",
                model=model,
                tokenizer=tokenizer,
                max_new_tokens = 2,
                do_sample=False
                )

    for i in tqdm(range(len(X_train))):
        prompt = X_train.iloc[i]["input"]
        result = pipe(prompt)
        answer = result[0]['generated_text'].split("=")[-1].strip()
        print("input: ", trainN.iloc[i]["input"])
        answer = str(answer).lower()
        print("answer: ", answer)
        if answer in classification_labels_N:
            n_pred.append(answer)
        else:
            n_pred.append("-1")

    return n_pred

In [ ]:
n_pred = predictN(model, tokenizer)

Device set to use cuda:0
  0%|          | 0/661 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 1/661 [00:01<21:00,  1.91s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 - viršutinis kraštas- extra  2 - apatinis kraštas -extra  3 - sarginiai l/m - extra  4 - kvadrantas - planiniam tyrimui. 4. Krūties sektorius 6,5x6,5x2 cm su odos lopu 5x1,5 cm, žymėtas viela ir siūlais: 2 trumpi siūlai sektoriaus krašte (žalia spalva), kita pusė - be žymėjimo (juoda spalva). Vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 15x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,5 cm.. 1(3)(Extra). Reaktyvi limfadenopatija (1 l/m).  2(1)(Extra). Krūties audinys.  3(2)(Extra). Krūties audinys. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT(m)1c(2 naviko židiniai: 12 mm ir 1,7 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Krūties žemo laipsnio duktalinė karcinoma in situ (DIN1c/DCIS)(kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. 1(3)(Extra). 1 limfmazgis su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze.  2(1)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  3(2)Extra). Krūties audinyje, fibrozuotoje stromoje - negausūs vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu. 1 limfmazgis su fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze.  4. Krūties audinyje - 2 naviko židiniai (mikroskopiškai 12 mm ir 1,7 mm), suformuoti fibrozuotoje stromoje infiltratyviai grandinėlėmis, smulkiomis grupelėmis ar pabirai plintančių ląstelių saikinga švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, apvaliais/ovaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 1/10 DPRL. Šalia yra kanaliukų, užpildytų analogiškomis navikui ląstelėmis (LCIS) bei dilatuotų kanaliukų su kribriforminiais intraduktaliniais neryškiai polimorfiškų ląstelių proliferatais (DCIS), negausūs kanaliukai su epitelio hiperplazija ar su stulpiniu ląstelių pokyčiu su apikalinės sekrecijos požymiais (CCAPSS); pavieniai smulkūs kalcifikatai, makrofagų židiniai, smulkios hemoragijos ir židininė MMN infiltracija.. 1. Navikas (15 blokas):  E-Cadherin(-).  Navikas (16 blokas):   E-Cadherin(-).  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.
answer:  1.

  0%|          | 2/661 [00:03<19:21,  1.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu  3(2). Kairės pažasties sarginiai limfmazgiai, skubu  4(3). Kairės krūties sektorius, planinis. 4. Krūties sektorius 6x2,7x5 cm su oda 3,5x1,6 cm, žymėtas viela. Krūties audinyje, kvadrante - pilkšvas, standus, neaiškių ribų navikas 12x8x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2 cm.. 1(1a). Fibrocistiniai krūties pokyčiai.  2(1b). Krūties audinys.  3(2). Reaktyvi limfadenopatija (2 l/m).  4(3). Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, TNM: pT1b(navikas 8,5 mm), pN0sn)(0/2 l/m), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).. 1(1a). Krūties audinyje gausūs dilatuoti latakai, kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.   2(1b). Krūties audinyje židininė fibrozė ir smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  3(2). Du limfmazgiai su sinusų histiocitoze ir šerdies lipomatoze.  4(3). Krūties audinyje - navikas (8,5 mm mikroskopiškai), suformuotas tubulinių struktūrų iš vidutinio kalibro eozinofiline citoplazma ląstelių, nežymiai polimorfiškais, smulkiai grūdėtu chromatinu branduoliais; mitozių 4/10 DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Krūties audinyje greta naviko negausūs dilatuoti latakai, kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.. Blokas 16:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

  0%|          | 3/661 [00:05<19:02,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)- kraštas - (extra)- be naviko   2(N2b)- kraštas - (extra)- be naviko   3(N3) -  sarginis l/m (extra)-  be naviko   4(1)- pašalintas sektorius( planinis tyrimas) Skubus Ro- -navikas pašalintas. Krūties sektorius 10x6x5 cm su oda 10x5,5 cm, žymėtas dviejomis vielomis, viena iš jų kiaurai perveria sektorių. Tarp vielų - balkšvas, standus, neaiškių ribų, netaisyklingos formos navikas 35x30x35 mm, nuo sektoriaus rezekcijos krašto (mėlyna spalva) nutolęs 0,1 cm, nuo odos - 2 cm.. 1. Riebalinis audinys.  2. Krūties audinys.  3. Reaktyvi limfadenopatija (1 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) lobulinė karcinoma, TNM: pT2(40 mm naviko židinys), LVI0(neidentifikuota), pN0(sn)(0/1 l/m). Krūties lobulinė karcinoma in situ (LCIS). HER2:reakcijos nėra (0). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.. 1. Riebalinis audinys su fibrozinėmis septomis.  2. Krūties audinys us pavieniais smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Vienas limfmazgis su sinusų histiocitoze.  4. Krūties audinyje - navikas (40 mm mikroskopiškai), suformuotas trabekulinių/juostinių struktūrų iš vidutinio kalibro eozinofiline citoplazma ląstelių, vidutiniškai polimorfiškais branduoliais su pavieniais paryškėjusiais branduolėliais; mitozių 2/10 DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Navikas nuo artimiausio krūties sektoriaus rezekcijos krašto nutolęs per 1 mm. Greta naviko gausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Aplinkiniame fibrozuotame krūties audinyje gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar metaplastišku apokrininiu epiteliu.. Blokas 7:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

  1%|          | 4/661 [00:07<19:10,  1.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 1a- viršutinis kraštas - extra;  2. 1b- apatinis kraštas - extra.  3(2). sarginiai limfmazgiai - extra;  4(3). Deš. krūties sektorius - planinis.. 4. Krūties sektorius 6,5x5x3,8 cm, su odos lopu 6,5x4 cm ir skersaruožio raumens fragmentu 2x1,5x0,4 cm. Krūties audinyje balkšvas, standus neaiškių ribų infiltratyviai plintantis navikas 2,7x1,8x2,7 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, įtraukia odą, siekia skersaruožius raumenis. Rezekcijos kraštas dažytas mėlynu tušu.. 1(Extra). Krūties audinys.  2(Extra). Riebalinis audinys.  3(Extra). Duktalinės karcinomos metastazės 2/4 limfmazgiuose (9 mm ir 1,8 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(22 mm) N(sn)1a(mts 2/4 l/m: 9 mm ir 1,8 mm), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).. 1(Extra). Krūties audinyje, neryškiai fibrozuotoje stromoje - negausūs smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 2 iš 4 limfmazgių - žemiau aprašyto naviko metastazės (9 mm ir 1,8 mm).  4. Krūties audinyje, dermoje ir fokaliai tarp skersaruožių miocitų - navikas (mikroskopiškai 22 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių lizdinių, trabekulinių ir negausių (<10%) smulkių tubulinių struktūrų bei fokaliai grandinėlėmis ar pabirai besidėstančių ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, ovaliais, neryškiai polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 7/10 DPRL. Limfovaskulinė smulkių šakų ir perineurinė invazija.. 1. Navikas (24 blokas):  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  E-Cadherin(+++)(membr. r-ja), 100%
answer:  100%.

  1%|          | 5/661 [00:08<18:31,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 10 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi nedideli šakoti kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 10%.
answer:  1a

  1%|          | 6/661 [00:10<18:01,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 16 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 10%.. Bioptate - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio-stambaus kalibro, nereguliaraus kontūro branduoliais eozinofiliškomis nukleolėmis; mitozių 0/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67 proliferacinis aktyvumas 10%.
answer:  1a

  1%|          | 7/661 [00:12<18:36,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštas - extra - be naviko  2(N2b). kraštas - extra - be naviko  3(N1). pašalintas sektorius - planinis tyrimas.. 3. Krūties sektorius 13,5x6,5x5,5 cm su oda 12,5x6 cm. Krūties audinyje, pilkšvas, standus navikas 2,2x16x16 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 1,3 cm, nuo odos - 2 cm. 1(ekstra). Krūties audinys. Naviko plitimo nėra.   2(ekstra). Krūties audinys. Naviko plitimo nėra.   3. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) mišri duktalinė - mikropapilinė karcinoma. SUMINIS TNM: pT2 (22 mm navikas) NX(l/m nešalinti) LVI-2 (limfovaskulinė invazija smulkiose gyslose). Radikalus pašalinimas (R0).    Naviko imunotipas biopsijoje:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. 1(N2a, ekstra). Krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   2(N2b, ekstra). Krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   3(N1).  Krūties audinyje - infiltratyviu frontu plintantis, 22 mm dydžio (mikroskopiškai) navikas, suformuotas mikropapilinių struktūrų(50%), tubulių (<10%), kribriforminių struktūrų, trabekulių ir lizdų. Naviko ląstelės su gausoka, ryškia eozinofiliška citoplazma, vidutinio kalibro ar stambiais, ovoidiškais, vidutiniškai ar fokaliai ryškiai polimorfiškais branduoliais su blyškiu chromatinu ir makronukleolėmis. Mitozių navike iki 8/10DPRL. Naviko centre stambi hipoląstelinga kolagenizuotos fibrozės zona.  Naviko plitimas endotelizuotuose spindžiuose.. Blokas 11:  EMA: silpna/vidutinė (+/++) membraninė reakcija naviko mikropapilinių struktūrų išorėje.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.
answer:  1(n

  1%|          | 8/661 [00:13<18:36,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1. Sektoriaus kraštai. N2. Sektoriaus kraštai. N3. Deš.krūties sektorius . 4.  pažasties limfmazgiai.. 3. Krūties sektorius 15,5x6x4,5 cm su odos lopu 15x2,5 cm. Pjūvyje balkšvas, standus, gan aiškių ribų navikas 2,1x1,9x1,1 cm, nuo odos nutolęs 1,5 cm, nuo artimiausio rezekcijos krašto - 2cm.  4. Riebalinio audinio fragmentai, bendras dysis 11x7,5x2 cm. Rasta 14 limfmazgių iki 1,4 cm.. 1. Riebalinis (krūties) audinys.  2. Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT2(2,1 cm) pN1a(1/14 l/m, mts 0,25 cm). LVI0(limfovaskulinės invazijos nėra).  4. Duktalinės adenokarcinomos metastazė 1/14 l/m.    Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2 imuninė reakcija neigiama (1+).  Ki67: 8%.. 1. Brandūs lipocitai, negausus fibrozinis audinys.  2. Krūties audinyje - negausūs smulkūs fibrozės židiniai su smulkiais kanaliukais, išklotais dvisluoksniu epiteliu.  3. Krūties audinyje - navikas: Solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 5 / 10 DPRL.   4. Aukščiau aprašyto naviko metastazė 1/14 limfmazgyje (0,25 cm).. nan
answer:  1.

  1%|▏         | 9/661 [00:15<20:05,  1.85s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1-2. pjūvio kraštai, ekstra. 3. sektorius, planinis. 4. pažasties l/m, planinis. 3. Krūties sektorius 9x8x2,5 cm su odos lopu 6x3,8 cm. Pjūvyje - balkšvas, standus, neaiškių ribų navikas 3x2x1,8 cm, nuo artimiausio rezekcijos krašto (mėlyna) nutolęs 0,1 cm, nuo odos – 1,5 cm. Navikas sudėtas visas, serijiniais pjūviais.  4. Riebalinio audinio fragmentai, bendras dydis 7,5x5x3,5 cm. Rastas 21 limfmazgiai iki 3 cm. Viename (II) limfmazgyje visą parenchimą apima balkšvas židinys 2,5 cm.. 1(ekstra). Kraštai. Krūties audinys be patologinių pokyčių.    2(ekstra). Kraštai. Krūties audinys be patologinių pokyčių.    3. Kairės krūties sektorius.   Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham sistemą) duktalinė karcinoma,   suminis TNM: pT2(30 mm makroskopiškai) pN1a (2/21 l/m su mts iki 25mm) pLVI-0.   Naviko struktūros siekia sektoriaus rezekcijos kraštą, žr. pastabą.  Naviko imunofenotipas (priešoperacinės biopsijos tyrime):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.   Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.   Her2 imuninė reakcija: neigiama 0.   Ki67+ 10%.  Her2 karcinomos metastazės limfmazgyje: HER2:reakcijos nėra (0).    4. Pažasties l/m. Krūties duktalinės karcinomos (iki 25 mm) metastazės 2/21 limfmazgių.. 1(ekstra). Kraštai. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Kraštai. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.    3. Kairės krūties sektorius.  Krūties audinyje - infiltratyviu frontu plintantis navikas, suformuotas tubulių (80%), pavienių grandinėlių, lizdų ir kribriforminių struktūrų su negausiais kalcifikatais. Naviko ląstelės negausia ar vidutinio gausumo, eozinofiliška citoplazma, vidutinio kalibro ar keliais stambiais, ovoidiškais ar netaisyklingo kontūro, vidutiniškai polimorfiškais branduoliais su negausiu, smulkiai grūdėtu chromatinu ir pavienėmis nukleolėmis. Mitozių navike iki 6/10DPRL. Naviko intravaskulinio plitimo nestebima.    4. Pažasties l/m. 2/21 limfmazgių - aukščiau (nr.3) aprašyto naviko metastazės, didžiausia 25 mm.. 2(ekstra). Kraštai. 2 blokas: CK14+ mioepitelis. Invazyvaus naviko struktūrų neidentifikuota.   1(ekstra). Kraštai. 3 blokas: CK14+ mioepitelis. Invazyvaus naviko struktūrų neidentifikuota.   3. Navikas (11 blokas): E-cadherin(+++)(membr.r-ja)100%.   4. N
answer:  21 lim

  2%|▏         | 10/661 [00:17<19:39,  1.81s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta dešinė krūtis - planinis tyrimas. Krūtis 1701 gramų svorio 31x22x7 cm. Krūties centrinėje dalyje prasidedantis pilkšvas, standus navikas (I) 9x9x3 cm, odoje išopėjęs 8,5x7 cm plote, nuo giliojo rezekcijos krašto navikas nutolęs 3 cm. Nuo naviko, 3 cm atstumu pilkšvas, ribotas, standus navikas (II) 1,5x1,2x1 cm, nuo giliojo rezekcijos krašto nutolęs 4,5 cm.. Blogai diferencijuota (G3, 9 b. pgl Nottingham) metaplastinė (matriksą produkuojanti) krūties karcinoma;   pT(m)4b(90 mm, 15mm su odos išopėjimu), pLVI-0, pR0.  Imunotipas (nustatytas priešoperaciniame naviko biopsijos tyrime):  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.   Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.   Her2 imuninė reakcija: neigiama 0+.   Ki67+ 90%.. Krūties audinyje 2-jų gausiai nekrozuojančių (apie 80 proc. navikų ploto) navikų netaisyklingas trabekulines struktūras sudaro smulkios ryškiai polimorfiškos ląstelės, stroma vietomis chondroidinė, mitozių iki 20/10 DPRL.. nan
answer:  3b

  2%|▏         | 11/661 [00:19<19:18,  1.78s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštai - extra - be naviko   2(N2b). kraštai - extra - be naviko   3(N3). sarg. l/m - extra - be naviko   4(N1). sektorius, planiškai. 4(N1). Krūties sektorius 10x5x4,5 cm, su odos lopu 9x3,5 cm. Pjūvyje balkšvas, standus neaiškių ribų navikas 2,1x1,7x1,2 cm, nuo artimiausio rezekcijos krašto nutolęs 0,4 cm, nuo odos 1 cm.. 1(N2a). Fokalinė krūties audinio fibrozė.  2(N2b). Fokalinė krūties audinio fibrozė.  3(N3). Reaktyvi limfadenopatija (2 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma, TNM (Nr.1-Nr.4): pT2(2,1 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės invazijos nėra).   ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 20%.. 1(N2a). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2(N2b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N3). Sinusų histiocitozė dviejuose (2) limfmazgiuose.  4(N1). Krūties audinyje - navikas (grandinėlėmis, trabekulėmis besidėstančios ląstelės su negausia ar kiek gausesne blyškiai eozinofiline citoplazma, vidutinio kalibro apvaliais-ovaliais ar kampuotais, dalis ląstelės periferijoje lokalizuotais be nukleolių branduoliais; mitozių navike iki 5 / 10 DPRL).. nan
answer:  1(n

  2%|▏         | 12/661 [00:20<18:40,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pašalintas kairė krūtis - planinis tyrimas ir kairės pažasties I ir II lygio limfmazgiai. Krūtis 1768 gramų svorio, 32x27x6,5 cm. Krūties audinyje, užspenelinėje srityje, labiau medialiai, balkšvas, standus, neaiškių ribų navikas 46x37x35 mm, nuo giliojo rezekcijos krašto nutolęs 3 cm, nuo odos  - 1 cm.  Aureolė stambiai gruoblėta 3x2,5 cm. Atskirai tame pačiame inde riebalinio audinio fragmentai, bendras dydis 9x8x3 cm. Rasta 10 limfmazgių iki 3,5 cm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2 (46mm) pN2a (7 iš 10 l/m) LVI 1.. Krūties audinyje ir odoje 46mm navikas: netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 30/10 DPRL.  Intravskulinis naviko plitimas.  Iš rastų 10 limfmagzių 7 su metastazėmis iki 35mm.  Operacinis pjūvis be naviko.. nan
answer:  3b

  2%|▏         | 13/661 [00:22<18:10,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis ~9×8 mm dydžio darinys kairiojoje krūtyje ties 5 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 fragmentuoti biopsiniai stulpeliai: I - 11 mm; II - 11 mm; III - 7 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 20%.. Krūties audinį infiltruoja pavienės duktalinės struktūros, nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67+ 15
answer:  1b

  2%|▏         | 14/661 [00:24<17:37,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2  biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 11 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja netaisyklingi kribroziniai/solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 10%.  ECAD+.
answer:  1a

  2%|▏         | 15/661 [00:25<17:07,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. 1 nefragmentuotas biopsinisi stulpelis: I - 12 mm;. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ %.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 10%.  ECAD+.
answer:  0

  2%|▏         | 16/661 [00:27<17:55,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštas - skubus tyrimas- be naviko  2 ėminio aprašas: N2b kraštas - skubus tyrimas- be naviko   3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko  4 ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 9,5x6,5x4 cm, su odos lopu 8x4 cm. Pjūvyje pilkšvas, standus, neaiškių ribų navikas 24x18x18 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2 cm. Nuo naviko 0,5 cm atstumu rusvas, standus darinys 10x5x5 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos  -2,8 cm. Sekančiame pjūvyje galimai darinys susilieja su naviku. Nuo naviko 1 cm atstumu pilkšvas židinys 3x3x2 mm.. PAPILDYTAS ATSAKYMAS (žr. Molekuliniai/FISH/CISH):    1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi mišri vidutiniškai diferencijuota (G2; 7 b. pgl. Nottingham) lobulinė (40%) ir duktalinė karcinoma (60%), suminis TNM: pT2(m)(navikai 30 mm ir 2,5 mm), pN0(sn)(0/3 l/m), LVI2(limfovaskulinis plitimas). Perineurinis naviko plitimas. Gausi perinavikinė limfocitų infiltracija. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.    HER2 geno amplifikacija nenustatyta, tačiau FISH tyrimo rezultatas yra artimas teigiamam, todėl turi būti interpretuojamas įvertinus HER2 IHC tyrimą (žr. molekulinio tyrimo aprašymą ir pastabas).. 1(2a). Krūties audinys su negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(2b). Krūties audinys su negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Trys limfmazgiai su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.  4. Krūties audinyje - hialinizuotoje stromoje 2 naviko židiniai (30 mm ir 2,5 mm mikroskopiškai) infiltratyviu augimo frontu, suformuoti 2 komponentų: a) trabekulinių, juostinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, vidutiniškai polimorfiškais, hiperchromiškais branduoliais; b) smulkių lizdinių, trabekulinių ir pavienių struktūrų su spindžių formacija, suformuotų kiek gausesne eozinofiline citoplazma ląstelių su vidutiniškai polimorfiškais, hiperchromiškais branduoliais. Gausi perinavikinė limfocitų infiltracija. Mitozių navike iki 17/10DPRL. Limfovaskulinė naviko invazija (LVI2). Perineurinis naviko plitimas.. Blokas 15:  E-Cadherin: (++)membran.r-ja 15%;  HER2: vidutinė (++) necirkuliari reakcija, 15%  naviko ląstelių membranoje.
answer:  2.

  3%|▎         | 17/661 [00:28<17:21,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 stulpeliai. 2 biopsiniai stulpeliai: I - 17 mm; II - 12 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 75% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 4% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 35%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai/solidiniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 75% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 4% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 80% naviko ląstelių.  Ki67+ 35%
answer:  3b

  3%|▎         | 18/661 [00:30<16:55,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. Gauta 2 bioptatai iki 0,01 cm, gleivės - citoblokas.. Mucininė karcinoma (smulkūs naviko fragmentai be aplinkinio audinio).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija paribinė (2+); ŽR.PASTABĄ.  Ki67: proliferacinis indeksas 10%.. Negausūs AB+ mucinų apsupti naviko fragmentai, iš lizdais ar papilinėmis struktūromis besidėstančių ląstelių eozinofiliška citoplazma, vidutinio kalibro, ovaliais, hiperchromiškais branduoliais.. Blokas 1:  CK14: reakcijos naviko ląstelėse nėra (-).  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) cirkuliari reakcija, 15% naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko lą
answer:  1a

  3%|▎         | 19/661 [00:32<17:30,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta kairė krūtis - planinis tyrimas. Krūtis, 1163 g svorio, 25,5x19,5x7 cm, spenelis įtrauktas. Centrinėje krūties dalyje, pilkšvas, neaiškių ribų iš susiliejančių židinių sudarytas plotas 22x20 mm, giliojo rezekcijos krašto nutolęs 1,6 cm, nuo odos - 2,3 cm. Krūties audinyje, smulkūs vietomis susiliejantys židiniai.. Vidutinio ir aukšto laipsnio intraduktalinė krūties karcinoma (DCIS/DIN2-3): 22mm plotas, papilinis ir komedo tipas.  ---------------  Du invaziniai navikai:  1. Vidutinės diferenciacijos (G2; 7 balai pgl Nottingham) invazinė duktalinė karcinoma; 1,1mm navikas.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.  Androgenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.    2. Vidutinės diferenciacijos (G2; 6 balai pgl Nottingham) invazinė duktalinė karcinoma; 3,0mm navikas.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 3%.  Androgenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  ---------------  Suminis TNM pT1a(m).. Krūties audinyje 22mm plotas ir atskiri mažesni židiniai visame krūties plote su dilatuotais kanaliukais su intraduktaliniais kribriforminiais vidutiniškai ar ryškiai polimorfiškų ląstelių, vietomis su centrinėmis nekrozėmis.  Šiame 22mm plote invazijos židinys 1,1mm: pabiros polimorfiškos ląstelės ir smulkūs solidiniai kompleksai, mitozių iki 3/DPRL.  Atskiras 3,0mm invazinis naviko židinys krūties audinyje: kribroziniai kompleksai vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  Rezekcijos kraštas be naviko.. nan
answer:  1a

  3%|▎         | 20/661 [00:33<17:39,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta kairė krūtis  - planinis tyrimas  2 ėminio aprašas: N2: kairės pažasties sarginiai limfmazgiai planinis tyrimas. 1. Krūtis, 622 g svorio, 24x15x4 cm. Lateralinių kvadrantų riboje, neaiškių ribų, standus, skiltėtos struktūros plotas 6,5x4,5x4,5  mm, nuo giliojo rezekcijos krašto nutolęs 1,5 cm, nuo odos- 1 cm.  2. Riebalinio audinio fragmentas 2,5x1,5x1 cm. Rastas 1 limfmazgis iki 0,6 cm. v/m. N1: Gerai diferencijuota invazinė duktalinė karcinoma pT1mi(m) (daugybiniai smulkūs invazinės karcinomos židiniai, didžiausias 0,7mm).  Invaziniame navike:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigimia (branduolių nusidažymas 2% naviko ląstelių).  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.  Vidutinio laipsnio intraduktalinė krūties Carcinoma in situ (Din2/DCIS; solidinis/kribriforminis tipas; pakitimai 65mm plote).  N2: Limfmazgis be naviko židinių; pN0(sn).. N1: Krūties audinyje 65mm plote gausūs intraduktaliniai solidiniai ir kribroziniai neryškiai ar vidutiniškai polimorfiškų ląstelių proliferatai.  Daugybiniai mikroskopiniai invazijos židiniai stromoje, didžiausias 0,7mm: solidiniai kompleksai minimaliai polimorfiškų ląstelių, vietomis mucininėje stromoje.  Rezekcijos kraštas be naviko.  N2: Limfmazgis be naviko židinių.. nan
answer:  0,

  3%|▎         | 21/661 [00:35<18:15,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 2a kraštas - extra - be naviko    2. 2b kraštas - extra - be naviko    3. limgmagis - extra - be naviko    4. N1- sektorius- planinis patologinis tyrimas N1- skubus rentgeninis tyrimas - navikas pašalintas. 4(1). Krūties sektorius 8,5x5,5x2,5 cm su odos lopu 7,5x2,3 cm, žymėtas viela. Vielos projekcijoje, balkšvas, standus neaiškių ribų navikas 0,9x0,7x0,6 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos – 3,5 cm.. 1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija); be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su skersaruožiu raumeniu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(1). Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 6 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).   Pavienės naviko struktūros siekia sektoriaus koaguliacijos zoną.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ir hiperplastišku epiteliu su apokrinine metaplazija; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu, skersaruožio raumens skaidulos; be naviko.   3(ekstra). "Sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4(1). NAVIKAS (6 mm skersmens): krūties audinyje, fibrozuotoje-elastozinėje, desmoplastiškoje stromoje, infiltratyviai plinta smulkios duktalinės, trabekulinės, nedidelės lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 1/10 DPRL.   APLINKA: aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   SEKTORIAUS REZEKCIJOS KRAŠTAS: pavienės naviko struktūros siekia koaguliacijos zoną.. 4(1). Navikas (blokas 13):  HER2: silpna (+) necirkuliari reakcija, 80% naviko ląstelių membranoje.
answer:  0

  3%|▎         | 22/661 [00:37<17:44,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 11 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma   (plitimas 2/2 biopsiniuose stulpeliuose, iki 8,8 mm ilgyje).  Naviko imunofenotipas:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 50% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 15%.. Krūties audinyje (2/2 biopsiniuose stulpeliuose, iki 8,8 mm ilgyje) - lizdinės ir solidinės struktūros, suformuotos ląstelių su vidutinio gausumo, eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, hiperchromšikais, vesikuolizuotais, vidutiniškai polimorfiškais branduoliais. Mitozių navike iki 1/10DPRL. Kalcifikatų, intravaskulinio plitimo nestebima.. Blokas 1:  CD31: vidutinis (++)  dažymasis 30% naviko ląstelių membranoje. CD31+ endotelis (intravaskulinio naviko plitimo nėra).  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) cirkuliari reakcija,
answer:  50%

  3%|▎         | 23/661 [00:38<17:02,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 . 1a- viršutinis kraštas, skubu  2. 1b- apatinis kraštas, skubu  3. (2). deš. pažasties sarginiai limfmazgiai, skubu  4. (3). Deš. krūties sektorius, planinis. 4. Krūties sektorius 4x3x1,2 cm be odos. Pjūvyje pilkšvas ribotas navikas 9x8x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm.. N1ab: Krūties audinys be naviko.  N2: Limfmazgiai (3 l/m) be naviko; pN0(sn).  N3: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (9mm).. N1ab: Krūties audinys be naviko.  N2: Limfmazgiai (3 l/m) be naviko.  N3: Krūties audinyje 9mm navikas: kampuotos duktalinės struktūros, negausūs kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. nan
answer:  0,

  4%|▎         | 24/661 [00:40<16:35,  1.56s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Vidutiniškai diferencijuota (G2, 7balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 25%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 80% naviko ląstelių.  Ki67+ 25%.
answer:  3b

  4%|▍         | 25/661 [00:41<16:17,  1.54s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 15 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma.     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.. Solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne švelniai eozinofiline citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 6 / 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 5% naviko ląstelių.  Prolifer
answer:  5%

  4%|▍         | 26/661 [00:43<16:11,  1.53s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 7 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.. Bioptatuose (2/2) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, lizdais ir trabekulėmis besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, ryškiai polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 3/10 DPRL. Gausi perinavikinė limfoplazmocitinė infiltracija.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 95%.  HER2: silpnas dalies membranos nusidažymas 1% naviko ląstelių.  Ki67 proliferacinis aktyvumas 20%.  E-cadherin(+++) membr r-ja 100%. Synaptophysi
answer:  0.

  4%|▍         | 27/661 [00:44<16:02,  1.52s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 12 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 60% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 6%.. Krūties audinį infiltruoja duktalinės struktūros (25%), netaisyklingi kribroziniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: vidutinė (++) reakcija, 60% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 70%  naviko ląstelių membranoje; vi
answer:  1.

  4%|▍         | 28/661 [00:46<17:04,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2). Kairės pažasties sarginiai limfmazgiai, skubu  4(3). Kairės krūties sektorius, planinis. 4(3). Krūties sektorius 8x3,5x7,5 cm be odos, žymėtas viela. Vielos projekcijoje pilkšvas, neaiškių ribų navikas 11x9x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm. Nuo naviko 2,3 cm atstumu rusvas sustandėjimas 9x8x6 mm plote, nuo giliojo rezekcijos krašto nutolęs 0,1 cm.. 1(1a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(1b, ekstra). "Kraštai": fibrozuotas krūties audinys; kalcifikatai; be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   4(3). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 7 mm) N0(sn) (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, sklerozuojanti ir mikroglandulinė adenozė,   stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).. 1(1a, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(1b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; keli smulkūs kalcifikatai; be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4(3). NAVIKAS (mikroskopiškai naviko židinys - 7 mm; aplink naviką kompaktiškas fibrozinis audinys): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios kribriforminės ir lizdinės, naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, negausia ar vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozės pavienės sunkiai identifikuojamos.   APLINKA: aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti, kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  SEKTORIAUS REZEKCIJOS KRAŠTAS: aukščiau aprašyti fibrocistiniai pokyčiai; be naviko.. Navikas (blokas 17):  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.
answer:  1(

  4%|▍         | 29/661 [00:48<17:09,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sarginiai l/m , ekstra;  2. deš krūtis, planinis.. 2. Krūtis 261 gramų svorio, 12,5x9,5x4,5 cm. Krūties audinyje, pospenelinėje zonoje - pilkšvai rusvas, standus, aiškių ribų navikas 2,4x2x2,4 cm, nuo odos nutolęs <0,1 cm, nuo artimiausio rezekcijos krašto - 2,3 cm.. 1. Reaktyvi limfadenopatija (2 l/m).  2. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 24mm) pN0(sn)(0/2 l/m); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse). Rezekcijos kraštas be naviko.  Estrogenų receptoriai: reakcija teigiama (vidutinė/stipri branduolių r-ja, 90% naviko ląstelių);   Progesterono receptoriai: reakcija teigiama (stipri branduolių r-ja, 85% naviko ląstelių);  HER2: reakcija neigiama (0+).  Androgenų receptoriai(++/+++), brand. r-ja, 60%;   Ki67 proliferacinis aktyvumas ~10%, fokaliai iki 20%;. 1. Du(2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  2. Krūties riebaliniame/fibroziniame audinyje, spenelio dermoje - navikas, formuojamas besieliejančių solidinių, fokaliai kribriforminių, pavienių papilinių struktūrų, smulkių agregatų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais; navike iki 7 mitozių/10 DPRL; Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse. Rezekcijos kraštas be naviko.. Navikas:  Estrogenų receptoriai: vidutinė/stipri branduolių r-ja, 90% naviko ląstelių;   Progesterono receptoriai: stipri branduolių r-ja, 85% naviko ląstelių;  HER2: nusidažiusių naviko ląstelių membranų nėra.  Androgenų receptoriai(++/+++), brand. r-ja,
answer:  60%;

  5%|▍         | 30/661 [00:49<17:13,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N3): kairės pažasties sarginis limfmazgis - skubus tyrimas - 2l/m be naviko  4(N1): pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 12x4,5x10 cm su oda 10x2,5 cm. Krūties audinyje, kvadrante - pilkšvas, standus, aiškių ribų navikas  25x16x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 1,8 cm.. 1. Krūties audinys.  2. Krūties audinys.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi, vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 25mm) pN0(sn)(0/2 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC/FISH reakcijos atliktos VPC:B23-19184 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcja neigiama, branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 35%.  HER2(FISH): NUSTATYTA HER2 GENO AMPLIFIKACIJA"  Stulpinis ląstelių pokytis su apikaline sekrecija.. 1. Riebalinis audinys su fibrozinėmis septomis, pavieniais latakėliais, klotais dvisluoksniu epiteliu.  2. Riebalinis audinys su fibrozinėmis septomis, pavieniais latakėliais, klotais dvisluoksniu epiteliu.  3. Du(2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze, lipomatoze.  4. Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas solidinių/lizdinių, trabekulinių, netaisyklingų liaukinių, kribriforminių struktūrų (~70% naviko) struktūrų iš vidutinio/stambaus kalibro ląstelių, vidutiniškai, vietomis ryškiai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 10 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su stulpiniu ląstelių pokyčiu ir apikaline sekrecija.. nan
answer:  1a

  5%|▍         | 31/661 [00:51<16:37,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 10 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 12%.. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 100% naviko ląstelių.  Ki67+ 12
answer:  1b

  5%|▍         | 32/661 [00:53<18:46,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas (DCIS įtarimas viename krašte)  2(N2b) kraštai - skubus tyrimas (DCIS įtarimas viename krašte)  3(N3): kairės pažasties markiruotas limfmazgis  - skubus tyrimas 2l/m makromts  4(N4): papildomas kraštas - planinis tyrimas  5(N1): pašalintas markiruotas kairės krūties kvadrantas - planinis tyrimas. 4. Riebalinio audinio fragmentas 2x1,2x0,6 cm.   5. Krūties sektorius 12,5x5,5x4,5 cm, su odos fragmentu 11x3,5 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 17x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,2 cm.. PAPILDYTAS ATSAKYMAS HER2 FISH TYRIMO REZULTATU:   1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(2b, ekstra). "Kraštai": krūties žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS: plokščias tipas). Krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė). Kalcifikatai.  3(ekstra). "Sarginiai limfmazgiai": lobulinės karcinomos metastazės dviejuose limfmazgiuose (mts 2/2 l/m; iki 12 mm skersmens).  4. "Papildomas kraštas": fibrozuotas riebalinis audinys; be naviko.     5(1). Krūties invazyvi mišri karcinoma:   vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma (~70%) ir   gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma (~30%),  SUMINIS TNM:   pT1c (navikas 17 mm) N1a(sn) (lobulinės karcinomos mts 2/2 l/m; iki 12 mm skersmens),   LVI-0 (definityvios limfovaskulinė invazija neidentifikuota).   Kalcifikatai.     Imunofenotipas:   Duktalinėje karcinomoje:   Estrogenų receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.   Progesterono receptoriai: vidutinė (++) reakcija, 20% naviko ląstelių.  HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.  Ki67: proliferacinis indeksas 1-2%.     Molekuliniai tyrimai:   HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Lobulinėje karcinomoje: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: plokščias, kribriforminis tipai).   Krūties lobulinė intraepitelinė neoplazija (LCIS).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(2b, ekstra). "Kraštai": keli intraduktaliniai plokščios konfigūracijos proliferatai, sudaryti saikingai polimorfiškų ląstelių ir CK14(+) atenuoto mioepitelinio sl.; fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu, hiperplastišku ir fokaliai atipiniu epiteliu epiteliu, nedidelės suspaustų kanaliukų zonos, židininė MMN infiltracija, pavieniai kalcifikatai; gausūs koaguliaciniai artefaktai.   3(ekstra). "Sarginiai limfmazgiai"(2): dviejuose (2) limfmazgiuose žemiau, punkte Nr.5, aprašyto naviko (lobulinio komponento) metastazės, iki 12 mm skersmens, su minimaliu ekstranodaliniu plitimu.   4. "Papildomas kraštas": fibrozuotas brandžių lipocitų suformuotas audinys; be naviko.     5(1). NAVIKAS: viename židinyje dvi išsiskiriančios zonos:   1) židinio centre (~30% ploto) - krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta minimaliai besiliejančios ir kiek netaisyklingos duktalinės naviko struktūros, suformuotos saikingai polimorfiškų ląstelių, negausia šviesia citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su  smulkiomis nukleolėmis; mitozės retos sunkiai vizualizuojamos. Pavieniai mikrokalcifikatai. Tarp naviko struktūrų gausūs dilatuoti latakai su kribriforminiais intraduktaliniai naviko ląstelių proliferatais;   2) daugiau židinio periferijoje (~70% ploto) - krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", nedidelės solidinės naviko struktūros, suformuotos mažai kohezyvių vidutiniškai polimorfiškų ląstelių, vidutinio gausumo eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 6/10 DPRL. Zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais.   APLINKA: aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti, kloti dvisluoksniu epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: žemo laipsnio in situ komponentas nutolęs 0,13 mm.. 2(2b, ekstra). "Kraštai" (blokas 4):  CK14(+) atenuotas mioepitelis sluoksnis.      5(1). Navikas (blokas 28):  CK14(+) mioepitelinis sl. neišlikęs invazyviame komponente.     Duktaliniame komponente:   E-Cadherin(+++)(membr.r-ja)100%;   Estrogenų recepto
answer:  1+

  5%|▍         | 33/661 [00:55<17:52,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas:  2 fragmentuoti biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 15 mm; II - 3 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G1; 5 b. pgl. Nottingham sist.) išlikusiame 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija teigiama (3+);   Ki67: proliferacinis indeksas 15%.. Kompaktišką fibrozinį audinį audinį išlikusiame 1-me bioptate infiltruoja iki 13 mm :   - duktalinės pavienės struktūros, pabiros ląstelės ir jų paviencės juostos ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: stipri (+++) cirkuliari reakcija, 80% naviko ląstelių memb
answer:  0

  5%|▌         | 34/661 [00:56<17:12,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 7 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja pavienės duktalinės struktūros ir smulkūs netaisyklingi kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  1a

  5%|▌         | 35/661 [00:58<17:18,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)-kraštas - extra tyrimas be naviko  2(N2b)-kraštas - extra tyrimas be naviko  3(N3)- sarginiai l/m - extra  tyrimas be naviko  4(N1) - pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 13x6,5x4,5 cm su oda 12x5 cm. Krūties audinyje, kvadrante - pilkšvas standus, neaiškių ribų navikas 26x12x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1 cm.. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties lobulinė karcinoma in situ (LCIS).  3(ekstra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(30 mm navikas) pN0(sn)(0/2 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir papilinis tipai).      Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu. Keletas dilatuotų latakų su intraduktaliniais monomorfiškų ląstelių proliferatais.  3(ekstra). 2 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (30 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, trabekulinėmis struktūromis, grandinėlėmis ir pabirai besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais stambiais, vidutiniškai polimorfiškais, nereguliaraus kontūro, branduoliais; mitozių 3/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš ląstelių polimorfiškais branduoliais.. 2. 10 blokas: CK14+ mioepitelis.  Navikas(18 blokas):  HER2: neigiama r-ja.   Ki67 proliferacinis aktyvumas 5%.  Ecadherin(-);
answer:  0

  5%|▌         | 36/661 [00:59<16:49,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 16 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6 mm);  (G2; 6 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 5%. Karštame taške 8%.. Krūties audinį 1-me bioptate infiltruoja iki 6 mm :   - solidiniai mazginiai kompleksai;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  eozinofilinėje citoplazmoje;   - su mitozėmis iki 2/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Androgenų receptoriai: stipri  teigiama (+++) branduolių reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija
answer:  1b

  6%|▌         | 37/661 [01:01<17:07,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu   3(2). Kairės krūties sektorius su limfmazgiais, planinis. 3. Krūties sektorius 7x6,5x3 cm be odos, žymėtas 2 vielomis, atstumas tarp vielų - 1,5 cm. I vielos projekcijoje, krūties audinyje - pilkšvas, standus, neaiškių ribų navikas 18x15x10 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm. II vielos projekcijoje hemoragija 2,5x1,7 cm plote. Atskirai tame pačiame inde pažasties narveliena 11x6,5x2 cm. Rasti 14 limfmazgiai iki 4 cm.. 1(1a) - viršutinis kraštas. Riebalinis audinys be patologinių pokyčių.  2(1b) - apatinis kraštas. Krūties audinys be patologinių pokyčių.  3(2). Kairės krūties sektorius su limfmazgiais.  Krūtyje invazinė duktalinė karcinoma G2(7 b. pgl. Nottingham sist.);    pT(m)1c, pLVI-0 pN1a pR0.   Estrogenų receptoriai: stipri (+++)  reakcija, 90% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%.    Vidutinio laipsnio intraduktalinė karcinoma, DCIS/DIN2.. 1(1a) - viršutinis kraštas. Riebalinis audinys be patologinių pokyčių.  2(1b) - apatinis kraštas. Krūties audinys be patologinių pokyčių.  3(2). Kairės krūties sektorius su limfmazgiais.  Naviko (mikroskopiškai 16 mm) ir atsitiktinio židinio (1,8 mm) histologinės diferenciacijos suminis laipsniavimas (pagal Nottingham sistemą):   tubulių nestebima, dominuoja trabekulinės struktūros (3 b.) + ląstelių branduolių polimorfizmas vidutinis(2 b.) + mitozių  8-12/10DPRL (2 b.).  Analogiškų ląstelių intraduktalinės struktūros be nekrozės, apima <25% naviko ploto ir plinta už invazyvaus naviko ribų.  Intralimfatinis / Intravaskulinis plitimas nestebimas.  Limfmazgiai: 3-se l/m iš 14 l/m karcinomos plitimas iki 14 mm, kapsulės peraugimas nestebimas.. Blokas 8:  E-Cadherin: stipri teigiama (+++)  cirkuliari (išorinė) membraninė reakcija 100 proc. atipinėse struktūrose  Estrogenų receptoriai: stipri (+++) reakcija, 90% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki6
answer:  30%.

  6%|▌         | 38/661 [01:03<16:50,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta kairė krūtis  - planinis tyrimas  2 ėminio aprašas: N2: kairės pažasties sarginiai limfmazgiai planinis tyrimas. 1. Krūtis, 622 g svorio, 24x15x4 cm. Lateralinių kvadrantų riboje, neaiškių ribų, standus, skiltėtos struktūros plotas 6,5x4,5x4,5  mm, nuo giliojo rezekcijos krašto nutolęs 1,5 cm, nuo odos- 1 cm.  2. Riebalinio audinio fragmentas 2,5x1,5x1 cm. Rastas 1 limfmazgis iki 0,6 cm. v/m. N1: Gerai diferencijuota invazinė duktalinė karcinoma pT1mi(m) (daugybiniai smulkūs invazinės karcinomos židiniai, didžiausias 0,7mm).  Invaziniame navike:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigimia (branduolių nusidažymas 2% naviko ląstelių).  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.  Vidutinio laipsnio intraduktalinė krūties Carcinoma in situ (Din2/DCIS; solidinis/kribriforminis tipas; pakitimai 65mm plote).  N2: Limfmazgis be naviko židinių; pN0(sn).. N1: Krūties audinyje 65mm plote gausūs intraduktaliniai solidiniai ir kribroziniai neryškiai ar vidutiniškai polimorfiškų ląstelių proliferatai.  Daugybiniai mikroskopiniai invazijos židiniai stromoje, didžiausias 0,7mm: solidiniai kompleksai minimaliai polimorfiškų ląstelių, vietomis mucininėje stromoje.  Rezekcijos kraštas be naviko.  N2: Limfmazgis be naviko židinių.. nan
answer:  0,

  6%|▌         | 39/661 [01:04<16:21,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 14 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.. Krūties audinį infiltruoja negausios duktalinės struktūros, nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 20% naviko ląstel
answer:  1b

  6%|▌         | 40/661 [01:06<16:20,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Pašalinta dešinė krūtis ir pažasties narveliena.. Krūtis 825 g svorio, 22,5x17,5x4 cm, su pažasties narveliena 9x6,5x2,5 cm. Krūties audinyje balkšvas, standus, gan aiškių ribų navikas 20x14x18 mm, esantis 4,5 cm nuo giliojo rezekcijos pjūvio, siekia odą, bet jos neperauga. Naviko projekcijoje, odoje - sustandėjimas 1,3x1 cm plote. Pažasties narvelienoje rasta 16 limfmazgių, didžiausias 1,7 cm.. Krūties invazyvi gerai diferencijuota (G1,5b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(19,5 mm navikas) pN1a(1/16 l/m MTS 2,1 mm) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 60% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 6%.. Spenelis normali histologinė struktūra.  Krūtyje - navikas (19,5 mm) infiltratyviu ir ekspansyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais stambiais, vidutiniškai polimorfiškais, nereguliaraus kontūro ir ovaliais branduoliais ryškiomis nukleolėmis; mitozių 3/10 DPRL. Limfovaskulinė invazija.  Navikas epidermio neinfiltruoja.  Aplinkinis krūties audinys fibrozuotas su negausiais latakais.. nan
answer:  1a

  6%|▌         | 41/661 [01:07<16:49,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - viršutinis kraštas - extra  2 - apatinis kraštas - extra  3- sarginiai l/m - extra  4 - kvadrantas - planiniam tyrimui. 4. Krūties sektorius 6,5x4x4 cm, su odos lopu 5x2 cm. Pjūvyje gelsvas, standus, ribotas navikas 10x10x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 1,8 cm.. 1. Fibrocistiniai krūties pokyčiai.   2. Fibrocistiniai krūties pokyčiai.   3. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/2 l/m, 2,75 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 11 mm), pN1a(sn)(1/2 l/m), LVI2 (limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime (klinikiniai duomenys). HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).. 1. Krūties audinyje, fibrozuotoje stromoje, gausios sklerozuotos lobulės bei dilatuoti kanaliukai, kloti dvisluoksniu epiteliu bei keli nežymiai dilatuoti kanaliukai, kloti hiperplastišku epiteliu. Židininė apokrininė epitelio metaplazija.  2. Krūties audinyje, fibrozuotoje stromoje, gausios sklerozuotos lobulės bei dilatuoti kanaliukai, kloti dvisluoksniu epiteliu bei keli nežymiai dilatuoti kanaliukai, kloti epiteliu su apokrinine metaplazija. Fibroziniame audinyje židininė limfocitų ir putotų makrofagų infiltracija.  3. PO FIKSACIJOS: Viename limfmazgyje iš dviejų žemiau aprašyto naviko metastazė iki 2,75 mm.  4. Krūties audinyje, hialinizuotoje stromoje plinta navikas (mikroskopiškai 11 mm) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių, trabekulinių ir negausių tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su vidutiniškai polimorfiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 6/10DPRL. Limfovaskulinis plitimas smulkiose limfagyslėse/kraujagyslėse(LVI2). Greta naviko gausūs dilatuoti kanaliukai užpildyti kribriforminių proliferatų iš analogiškų navikui ląstelių. Aplinkiniame krūties audinyje, fibrozuotoje stromoje, gausios sklerozuotos lobulės bei dilatuoti kanaliukai, kloti dvisluoksniu epiteliu bei keli nežymiai dilatuoti kanaliukai, kloti hiperplastišku epiteliu. Židininė apokrininė epitelio metaplazija.. Blokas 15:  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.
answer:  0

  6%|▋         | 42/661 [01:09<16:25,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1  biopsinis stulpelis.. Biopsinis stulpelis 9 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: vidutinis ir silpnas branduolių nusidažymas 20% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis ir silpnas branduolių nusidažymas 20% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas
answer:  1

  7%|▋         | 43/661 [01:10<16:16,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 16 mm; II - 13 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 15 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.. Krūties audinį 2-se bioptatuose infiltruoja iki 15 mm :   - duktalinės struktūros (10% viso naviko), netaisyklingi kribroziniai kompleksai;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje citoplazmoje;   - su mitozėmis iki 3/10 DPRL.   Mikrokalcifikatai. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono receptoriai: stipri (+
answer:  100%

  7%|▋         | 44/661 [01:12<16:37,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai. - ekstra  2(2b). Kraštai. - ekstra  3. Sarginiai l/m. - ekstra.  4(1). N1- pašalintas sektorius - planinis patologinis tyrimas. 4(1). Krūties sektorius 15x6,5x4 cm su odos lopu 14x14 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 11x10x8 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 3 cm.. 1. Krūties fibrocistiniai pokyčiai.   2. Krūties radialinis randas.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma,   pT1c (11 mm) pN0(sn) (0/2 l/m); LVI0 (limfovaskulinės naviko invazijos neidentifikuota).   Lobulinės karcinomos imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-27803, žr. pastabą.   Žemo laipsnio duktalinė karcinoma in situ (DCIS; kribriforminė, mikropapilinė).. 1. Krūties audinyje - netolygi stromos fibrozė, kelios grupės latakų su apokrinine epitelio metaplazija, intraduktaliniai mikrokalcifikatai.    2. Krūties audinyje - "žvaigždiškas" darinys su centrine fibroze ir smulkiais, vidutinio dydžio bei cistiškai dilatuotais latakais, klotais mioepitelinėmis ląstelėmis ir stulpiniu epiteliu su apikalinės sekrecijos požymiais, intraduktaline epitelio hiperplazija.   3. Limfmazgiai (3) su ryškia lipomatoze, nedideliais antriniais folikulais, be naviko plitimo.  4. Krūties audinyje - navikas, formuojamas infiltratyviai plintančių, glaudžiai besidėstančių grandinėlių, trabekulinių struktūrų, smulkių grupių, sudarytų iš nedidelių-vidutinio dydžio poligonalinių ląstelių šviesiai eozinofiliška citoplazma, nežymiai ar vidutiniškai polimorfiškais ovaliais ar skeltais branduoliais su vezikulizuotu chromatinu, smulkiomis nukleolėmis. Gausios pabirai-difuziškai plintančios naviko ląstelės. Navike iki 1 mitozės/ 10 DPRL. Limfovaskulinės invazijos neidentifikuota.   Aplinkiniame krūties audinyje - grupė latakų su intraduktaliniais kribriforminiais proliferatais iš duktalinio tipo ląstelių su nežymiu branduolių polimorfizmu, pavienis latakas su intraduktalinėmis mikropapilinėmis analogiško epitelio struktūromis.. nan
answer:  0,

  7%|▋         | 45/661 [01:14<17:06,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)- kraštai - skubus tyrimas LCIS viename krašte  2(N2b) - kraštai - skubus tyrimas LCIS viename krašte  3(N3) - kairės pažasties sarginis limfmazgis - skubus tyrimas - 2l/m be naviko  4(N1) - pašalintas kairės krūties kvadrantas su speneliu (atskirai) - planinis tyrimas. 4. Krūties sektorius 15x6,5x6 cm su oda 13,5x2,5 cm. Krūties audinyje, pilkšvas standus neaiškių ribų navikas 30x30x22 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 2,2 cm. Atskirai tame pačiame inde spenelis su aplinkine oda 4,5x3x1,8 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties lobulinė karcinoma in situ (LCIS).   3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(31 mm) N(sn)0(0/2 l/m), LVI-2(limfovaskulinė invazija). Perineurinė invazija. Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties lobulinė karcinoma in situ (LCIS).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Krūties intraduktalinės papilomos ir fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  3(Extra). 2 limfmazgiai su fokaline parakortekso hiperplazija, sinusų histiocitoze ir lipomatoze.  4. KRŪTIS: krūties audinyje - ribotas navikas (mikroskopiškai 31 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių trabekulinių ir lizdinių struktūrų bei grandinėlėmis, smulkiomis grupėmis ir pabirai besidėstančių ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais/apvaliais ir nereguliariais, kiek polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 3/10 DPRL. Perineurinė ir limfovaskulinė invazija. Negausūs smulkūs kalcifikatai. LCIS šalia.  Aplink yra dilatuotų kanaliukų su kribriforminiais intraduktaliniais vidutiniškai polimorfiškų ląstelių proliferatais, kanaliukų su intraduktalinėmis papilinėmis struktūromis, klotomis dvisluoksniu stulpiniu epiteliu bei kanaliukų su epitelio hiperplazija.  SPENELIS: normali histologinė struktūra.. 4. Navikas (15 blokas):  Lobulinė karcinoma E-Cadherin(-); DCIS struktūrose E-Cadherin(+).
answer:  0.

  7%|▋         | 46/661 [01:16<17:07,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 . 3 sarginiai l/m - skubi patologija - be naviko   2. (N1)- pašalinta krūtis - planinis tyrimas. 2. Krūtis 600 gramų svorio, 22x15,5x5 cm. Krūties audinyje, viršutiniame medialiniame kvadrante, balkšvas, standus, neaiškių ribų navikas 4,5x3,5x3 cm, siekia odą, ją įtraukia 1,7x0,6 cm plote, nuo giliojo rezekcijos krašto nutolęs 0,5 cm.   Viršutiniame lateraliniame kvadrante balkšvas, standus, gana aiškių ribų darinys 1,5x1,5x0,7 cm, nuo odos nutolęs 4 cm, nuo giliojo rezekcijos krašto - 0,4 cm, nuo naviko - 8 cm.. 1(N2)-sarginiai l/m-extra: limfmazgiai (3) be karcinomos ląstelių plitimo; pN0.    2(N1)- pašalinta dešinė krūtis.   Invazinė duktalinė (kitaip neklasifikuojama) karcinoma;  (G2; 7 b. pgl. Nottingham sist.);  pT2 pLVI-0 pR0 (<1 mm).  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija teigiama (3+);   Ki67: proliferacinis indeksas 15%.    Krūties fibrocistiniai pokyčiai.. 1(N2)-sarginiai l/m-extra: limfmazgiai (3) be karcinomos ląstelių plitimo.  2(N1)- pašalinta dešinė krūtis. Kompaktišką fibrozinį audinį audinį netaisyklingų ribų navikas infiltruoja iki 45mm :   - duktalinės pavienės struktūros, pabiros ląstelės ir jų paviencės juostos ir trabekulės;  - epitelinių smulkių  ir vidutinio dydžio ląstelių su visutiniškai polimorfiškais branduoliais gausioje eozinofilinėje citoplazmoje;   - mitozių iki 12 / 10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.  Navikas 1 mm nuo operacinio krašto.  Atskirai esančio darinio fibrozuotame audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu, fokaliai apokrininė metaplazija.. nan
answer:  0.

  7%|▋         | 47/661 [01:17<16:29,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stlpeliai. 3 biopsiniai stulpeliai: I - 10 mm; II - 7 mm; III - 8 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo  nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo  nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 15%.
answer:  1a

  7%|▋         | 48/661 [01:19<16:44,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N3) dešinės pažasties sarginis limfmazgis  skubus tyrimas - 3l/m be naviko  4(N1): pašalintas dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 5x3,7x2,5 cm su odos lopu 4,5x2 cm. Pjūvyje pilkšvas, standus, aiškių ribų navikas 19x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 1,2 cm.. 1(N2a) kraštai. Krūties audinys be patologinių pokyčių.    2(N2b) kraštai. Krūties audinys be patologinių pokyčių.    3(N3) dešinės pažasties sarginis limfmazgis. Limfmazgiai (3) be karcinomos ląstelių.    4(N1) dešinės krūties kvadrantas.  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma;(G3; 8 b. pgl. Nottingham sist.).  pT1c pN(sn)0(0/3) pLVI-0 pR0.  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stipri (+++)  reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%.    Intraduktalinė vidutinio laipsnio karcinoma (DCIS, DIN2 solidinio ir komedo tipo).. 1(N2a) kraštai. Krūties audinys be patologinių pokyčių.  2(N2b) kraštai. Krūties audinys be patologinių pokyčių.  3(N3) dešinės pažasties sarginis limfmazgis. Limfmazgiai (3) be karcinomos ląstelių.  4(N1) dešinės krūties kvadrantas. Krūties audinį infiltruoja aiškių ribų navikas, suformuotas trabekules sudarančių epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje su mitozėmis iki 20/10 DPRL. Intravaskulinės invazijos nėra.  Gretimai analogiškų ląstelių solidinės inraduktalinės struktūros, židiniškai su centrinėmis nekrozėmis. Intraduktalinės ir invazinės struktūros nuo žymėto operacinio krašto 0,6 mm.. nan
answer:  1(n

  7%|▋         | 49/661 [01:21<17:25,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. kraštai - extra  2. kraštai - extra  3. sektorius su limfmazgiais, planinis.. 3. Krūties sektorius 13x9x6 cm su odos lopu 10x5 cm ir pažasties narveliena 12x9x4 cm. Rezekcijos kraštas dažytas mėlynu tušu. Pjūvyje gausus liaukinis audinys 10x9x6 cm zonoje ir pilkšvas, netolygių kontūrų, neaiškių ribų navikas 6,5x5,5x2 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos - 2 cm. Pažasties narvelienoje rasti 22 limfmazgiai iki 3,5 cm su židiniais iki 3 cm skersmens.. 1(ekstra). Krūties fibrocistiniai pokyčiai, stulpinis ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija. Adenozė.   2(ekstra). Krūties intraduktalinė papiloma. Fibrocistiniai pokyčiai, stulpinis ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija.   3. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma (su morfologiniais lobulinės karcinomos požymiais).   SUMINIS TNM: pT3(65 mm navikas) N3a(12/22 l/m MTS iki 3 cm) LVI-2 (limfovaskulinė invazija). Naviko struktūros plinta sektoriaus rezekcijos krašte.   Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis tipas).. 1(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais, kompaktiškais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Dalyje kanaliukų apokrininė metaplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).    2(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Dalyje kanaliukų apokrininė metaplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Darinys suformuotas šakotų papilinių struktūrų iš fibrozinės stromos, klotos dvisluoksniu epiteliu.  3. Krūties audinyje - fibrozinėje stromoje, infiltratyviu frontu plintantis navikas, suformuotas trabekulių, grandinėlių ir smulkių lizdų. Naviko ląstelės su negausia, blyškia citoplazma, vidutinio kalibro, apvaliais ar netolygaus kontūro, vidutiniškai polimorfiškais branduoliais. Mitozių navike iki 4/10DPRL. Naviko plitimas endotelizuotuose spindžiuose.  Šalia naviko dilatuoti kanaliukai su intraduktaliniais solidiniais proliferatais iš analogiškų navikui ląstelių.  Limfmazgiai (22): 12/22 limfmazgių - aukščiau aprašyto naviko metastazės (iki 3 cm makroskopiškai).. 3. 17 blokas(navikas): E-cadherin(+++)(membr.r-ja)100%;  p120(+++)(membr.r-ja)(su silpna fonine citoplazmine r-ja)100%; Beta-Catenin(+++)(membr.r-ja)100%.
answer:  3.

  8%|▊         | 50/661 [01:22<16:46,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3  biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 11 mm; III - 8 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 45%, vietomis iki 60%.. Krūties audinį infiltruoja solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 45%,
answer:  3b

  8%|▊         | 51/661 [01:24<16:27,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 13 mm; II - 10 mm; III - 14 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.. Krūties audinį 3-se bioptatuose infiltruoja iki 11 mm :   - solidiniai kompleksai, juostos ir trabekulės;  - epitelinių vidutinio dydžio / stambių ląstelių su vidutiniškai polimorfiškais branduoliais negausioje citoplazmoje;   - su mitozėmis iki 5/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  100%

  8%|▊         | 52/661 [01:26<17:57,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). kraštai, skubu  2(N2). kraštai, skubu  3(N3). sarginiai l/m  4(N4). Deš.krūties kvadrantas.. 4. Krūties sektorius 13,5x3,5x8,5 cm su oda 10x2 cm, žymėtas 2 vielomis:  - I vielos projekcijoje, pilkšvas, standus, neaiškių ribų navikas 12x10x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 5,3 cm.  - II vielos projekcijoje, gelsvas, neaiškių ribų židinys 4x4x4 mm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 3,2 cm.. 1(Extra). Krūties audinys.  2(Extra). Riebalinis audinys.  3(Extra). Reaktyvi limfadenopatija (5 l/m).  4. A) Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(8,5 mm) N(sn)0(0/5 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus/vidutinis branduolių nusidažymas 50% naviko ląstelių.  HER2 imuninė reakcija: neigiama (0).  Ki67: 10% (hot-spot 15%).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).     B) Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1a(1,3 mm) N(sn)0(0/5 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  HER2 imuninė reakcija: neigiama (1+).  Ki67: 1%.   Lobulinė karcinoma in situ (LCIS).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - negausūs vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Brandus riebalinis audinys su negausiomis kraujagyslėmis.  3(Extra). 5 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.  4. Krūties audinyje (ties I viela) - ribotas navikas (mikroskopiškai 8,5 mm), suformuotas fibrozuotoje stromoje plintančių lizdinių ir tubulinių bei kribriforminių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 9/10 DPRL. Šalia negausūs dilatuoti kanaliukai su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais.  Ties II viela, fibrozuotoje stromoje - dilatuoti kanaliukai su solidiniais intraduktaliniais proliferatais, fokaliai su komedo nekrozėmis centre, suformuotais analogiškų navikui ląstelių.  Atokiau - smulkus (1,3 mm) židinys, suformuotas smulkiomis grupėmis besidėstančių ląstelių saikinga, šviesiai eozinofiliška citoplazma, smulkiais ir vidutinio kalibro, apvaliais, gan monomorfiškais, su smulkia nukleole branduoliais; mitozių neidentifikuota. Aplink dilatuoti kanaliukai, užpildyti monomorfiškomis ląstelėmis (LCIS).. 4. Navikas/duktalinė karcinoma (19 blokas):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus/vidutinis branduolių nusidažymas 50% naviko ląstelių.  HER2 imuninė reakcija: nusidažiusių naviko l
answer:  100%

  8%|▊         | 53/661 [01:27<17:32,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 10 mm; II - 12 mm; III - 12 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 15/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląs
answer:  3b

  8%|▊         | 54/661 [01:29<16:46,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 10 mm ilgio.. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.. Bioptate - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 5/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 5% naviko ląstelių.  Ki67 proliferacinis aktyvumas 5%.
answer:  1a

  8%|▊         | 55/661 [01:31<17:36,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Ca mammae sin cT1Nx..I st. Ca mammae dex pT1Na(SN)... I st. (2015 m.). - extra.  1. Sektoriaus kraštai - extra;  2. Sektoriaus kraštai - extra;  3. Sarginiai lifmazgiai - extra;  4(5). Papildomas kraštas - extra.  5(4). Krūties sektorius - planinis.. 5. Krūties sektorius 9x8x3 cm odos lopu 8,5x2,3 cm. Pjūvyje balkšvas, standus, kiek neaiškių ribų navikas 1,9x1,6x1,5 cm, nuo odos nutolęs 2,6 cm, nuo artimiausio rezekcijos krašto - 0,8 cm. 1. Sektoriaus kraštai.   Krūties žemo laipsnio duktalinė karcinoma in situ (DCIS,DIN1).   Intraduktalinė papiloma. Židininė intraduktalinė hiperplazija.    2. Sektoriaus kraštai. Krūties audinys be patologinių pokyčių.    3. Sarginiai limfmazgiai. Karcinomos plitimas iki 4,5 mm 1-me/9 limfmazgių; stebimas ekstranodalinis plitimas.    4(5). Papildomas kraštas. Krūties audinys be patologinių pokyčių.    5(4). Krūties sektorius.   Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma;   pT1c(15 mm mikroskopiškai) pN1a (1/9; 4,5 mm) pR0.   Imunofenotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.   Progesterono receptoriai: (+++)(brand. r-ja) 100%.   HER2 imuninės reakcijos nėra (0).  Ki67 proliferacinis aktyvumas iki 10%.    Krūties žemo laipsnio duktalinė karcinoma in situ (DCIS,DIN1).   Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija,   sklerozuojanti adenozė.. 1. Sektoriaus kraštai. Negausūs kiek išplėsti kanaliukai su tinkliniais intraduktaliniais ląstelių proliferatais su eozinofiliška citoplazma, vidutinio kalibro ir nežymiai polimorfiškais branduoliais. Cista su tubulo- papilinėmis aukšto epitelio struktūromis su kiek stratifikuotais pailgais branduoliais bei mioepiteliu. išplėstas kanaliukas hiperplastiniu duktaliniu epiteliu be atipijos.  2. Sektoriaus kraštai. Krūties audinys be patologinių pokyčių.  3. Sarginiai limfmazgiai. Karcinomos duktalinės ir tinklinės struktūros plinta iki 4,5 mm 1-me/9 limfmazgių; stebimas ekstranodalinis plitimas.  4(5). Papildomas kraštas. Krūties audinys be patologinių pokyčių.  5(4). Krūties sektorius. Krūties audinyje, fibrozinėje stromoje, plinta mikroskopiškai iki 15 mm infiltratyvios tubulinės (apie 40 proc.), trabekulinės bei pavienės kribriforminės naviko struktūros, suformuotos ląstelių vidutinio gausumo eozinofiliška citoplazma, nežymiai ar vidutiniškai polimorfiškais, hiperchromiškais, ovoidinias ar kiek nereguliaraus kontūro branduoliais; mitozių iki 3/10 DPRL.  Intravaskulinio plitimo nestebima.  Operaciniame krašte -židiniškai stebimi išplėsti kanaliukai su tinkliniais intraduktaliniais ląstelių proliferatais su eozinofiliška citoplazma, vidutinio kalibro ir nežymiai polimorfiškais branduoliais.  Aplink naviką - fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, smulkių kanaliukų proliferacijos zonos, apokrininė metaplazija.. p63: neigiamas(-) branduolinis dažymasis .   CD56 : neigiamas(-) membraninis dažymasis naviko ląstelėse.   Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100% naviko ląstelėse.   Progesterono receptoriai: vidutinis(++) branduolinis dažymasis 1
answer:  100%

  8%|▊         | 56/661 [01:33<17:32,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta dešinė krūtis ir dešinės pažasties limfmazgiai. Krūtis 812 g svorio, 22x16x5 cm, su pažasties narveliena ir atskiru riebalinio audinio fragmentu, bendras dydis 10x12x4 cm.   Krūties audinyje pilkšvas, standus, aiškių ribų navikas 30x25x24 mm, esantis 0,7 mm nuo artimiausio/giliojo rezekcijos pjūvio, nuo odos 2 cm. Pažasties narvelienoje rasta 12 limfmazgių, didžiausias 3,8 cm su pilkšvu židiniu 3,3 cm.. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT2(30 mm navikas) pN1a(1/12 l/m su mts 33mm) pLVI0 (limfovaskulinė invazija neidentifikuota) pR0(radikalus pašalinimas).  Naviko imunotipas:  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 80%.    Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis, kribriforminis tipai).. Krūties audinyje - navikas, suformuotas solidinių kompleksų ir lizdų, iš ląstelių su negausia amfofiliška citoplazma, vidutinio kalibro ar stambiais, ovoidiškais, ryškiai polimorfiškais branduoliais su  smulkiomis nukleolėmis. Mitozių navike iki 77/10DPRL.   Naviko nekrozė ~30%.   Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių.  Limfmazgiai (12): 1-me/12 limfmazgių - aukščiau aprašyto naviko metastazės iki 3,3 cm (makroskopiškai).. Blokas 7(navikas):  CD31: endotelis+ (limfovaskulinė invazija neidentifikuota);  CK5(+)(citopl.r-ja)15%; GATA3(++)(brand.r-ja)80%; Synaptophysin(-);  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių mem
answer:  0.

  9%|▊         | 57/661 [01:35<19:09,  1.90s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Kairė krūtis su limfmazgiais, planinis. Krūtis 1535 g svorio, 19x19x8 cm. Krūties audinyje, apatinių kvadrantų ribose, multižidininis navikas, kurių bendras dydis 4,5x3x2,8 cm, nuo rezekcijos krašto nutolęs 2,5 cm, nuo odos 1 cm.   - rusvas, su cistinėmis ertmėmis, užpildytomis hemoragišku turiniu ir trapiomis masėmis I navikas 4,2x3,8x2,7 nuo artimiausio rezekcijos krašto nutolęs 2 cm, nuo odos - 0,8 cm.  - 0,5 cm, medialiau - balkšvas, standus, netolygių kraštų II navikas 1,4x0,7x1 cm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos 1,5 cm.  - 2,5 cm virš I naviko - balkšvas, standus, neaiškių ribų III navikas 0,7x0,4x0,5 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 2 cm, nuo odos - 5 cm.  - 1 cm virš I naviko - 4 ovalūs, pilkšvi, aiškių ribų židiniai nuo 0,3 cm iki 0,7 cm skersmens.  - viršutiniame lateraliniame kvadrante, pilkšva, standi, neaiškių ribų, fibrozės zona 2,5x2,5x2 cm, nuo I židinio nutolęs 4 cm, nuo artimiausio rezekcijos krašto nutolęs 1,5 cm, nuo odos - 3 cm.  Atskirai tame pačiame inde - pažasties narveliena (12x11x4 cm), su 31 limfmazgiu (didžiausias 4 cm; dviejuose limfmazgiuose - makroskopiškai vizualizuojami balkšvi židiniai, 2 cm ir 2 cm).. A) Krūties invazyvi multicentrinė karcinoma:  - invazyvi duktalinė adenokarcinoma (vidutiniškai diferencijuota/G2/6 balai pagal Nottingham) (4,2 cm naviko židinys; intraduktalinės papilinės, solidinės papilinės karcinomos fone),  - invazyvi lobulinė karcinoma (vidutiniškai diferencijuota/G2/6 balai pagal Nottingham) (1,4 cm naviko židinys).   B) Dauginės intraduktalinės papilomos.  C) Lobulinė karcinoma in situ (LCIS).  D) Krūties fibrocistiniai pokyčiai.  ---  Piktybinių navikų (karcinomų) "suminis" kategorizavimas pagal TNM: pT2(m)(iki 4,2 cm duktalinės karcinomos + iki 1,4 cm lobulinės karcinomos židiniai) pN2a(duktalinės adenokarcinomos mts 5/31 l/m, didžiausia metastazė 2,0 cm, nežymus ekstranodalinis plitimas). LVI2(duktalinės adenokarcinomos limfovaskulinė naviko invazija, smulkiose struktūrose). R0(radikalus navikų pašalinimas).   ---  Krūties invazyvios duktalinės adenokarcinomos imunofenotipas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.  ---  Krūties invazyvios lobulinės karcinomos imunofenotipas  Estrogenų receptoriai: stiprus-vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.. KRŪTIES SPENELIS: Be patologijos.  KRŪTIS: Krūties audinyje - dauginiai skirtingi "pažeidimai":  A) Invazyvios karcinomos:  - Invazyvi duktalinė adenokarcinoma (iki 4,2 cm; intraduktalinės papilinės, solidinės papilinės karcinomos fone): trabekulines, pavienes smulkias duktalines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne šviesia citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 6 / 10 DPRL; gausios susiliejančios papilinės, negausios solidinės struktūros, suformuotos ląstelių su kiek netaisyklingais branduoliais.  - Invazyvi lobulinė karcinoma (iki 1,4 cm naviko židinys): grandinėlėmis, trabekulėmis ar pabirai besidėstančios ląstelės su negausia ar kiek gausesne blyškiai eozinofiline citoplazma, vidutinio kalibro apvaliais-ovaliais ar kampuotais, dalis ląstelės periferijoje lokalizuotais be nukleolių branduoliais; mitozių navike iki 3 / 10 DPRL).    B) dauginės intraduktalinės papilomos (zonos su susiliejančiomis žemu stulpiniu, stulpiniu, kubiniu epiteliu išklotomis papilinėmis struktūromis kanaliukų spindžiuose),  C) Lobulinė karcinoma in situ (LCIS): kanaliukai su monotoniškais solidiniais smulkių ląstelių proliferatais spindžiuose.  D) Įvairių formų "fibrocistiniai pokyčiai": fibrozinėje stromoje - smulkūs ar kiek stambesnio kalibro, fokaliai dilatuoti kanaliukai, iškloti dvisluoksniu epiteliu; apokrininės metaplazijos, intraduktalinės hiperplazijos židiniai.  PAŽASTIES NARVELIENA: Aukščiau aprašyto naviko (duktalinės adenokarcinomos) metastazės limfmazgiuose (penkiuose (5) iš trisdešimt vieno (31), didžiausia metastazė 2,0 cm, nežymus ekstranodalinis plitimas).. Navikas (lobulinė karcinoma; 16 blokas):  Estrogenų receptoriai: stiprus-vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: nusidažiusių naviko ląst
answer:  0%.

  9%|▉         | 58/661 [01:37<18:42,  1.86s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 2a kraštas - extra - be naviko  2. 2b kraštas - extra - be naviko  3. sarginiai l/m - extra - (3) be naviko  4 ėminio aprašas:  N1 - pašalintas sekorius su sukietėjimu- planinis paologinis tyrimas (Skubus N1- rentgeninis tyrimas - navikas 13 mm ir intramammarinis l/m - pašalinti. 4. Krūties sektorius 12,8x8,5x6 cm su odos lopu 12x6 cm. Pjūvyje  pilkšvas, standus, ribotas 14x12x10 mm navikas, pereinantis į fibrozę. Nuo giliojo rezekcijos krašto nutolę 0,6 cm, nuo odos - 2,4 cm.. 1. Krūties audinys.  2. Riebalinis audinys be patologijos.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi blogai diferencijuota (G3; 8 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 13,5 mm), pN0(sn)(0/3 l/m), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS). HER2:reakcijos nėra (0).  Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija.. 1. Krūties audinyje smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2. Riebalinis audinys su plonomis fibrozinėmis septomis ir smulkiomis kraujagyslėmis.  3. Trys limfmazgiai (3 l/m) su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.   4. Krūties audinyje, hialinizuotoje stromoje plinta navikas (13,5 mm mikroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių, trabekulinių ir negausių struktūrų su spindžių formacija. Naviko ląstelės negausia eozinofiline citoplazma su ryškiai polimorfiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 16/10DPRL. Limfovaskulinis plitimas smulkiose limfagyslėse/kraujagyslėse(LVI2). Navikas nuo artimiausio rezekcijos krašto nutolęs per 7 mm. Greta naviko negausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Krūties audinyje, fibrozuotoje stromoje dilatuoti kanaliukai, kloti dvisluoksniu epiteliu bei keli nežymiai dilatuoti kanaliukai, kloti hiperplastišku epiteliu.. Blokas 19:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  3b

  9%|▉         | 59/661 [01:38<17:46,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 9 mm; II - 10 mm; III - 3 mm.. Papildyta HER2 FISH.  Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma. Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+).  Ki67 proliferacinis aktyvumas 15%.  HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).. Fragmentuotuose bioptatuose (3/3) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos tubulėmis, kribriforminėmis str. ir lizdais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio kalibro, nereguliaraus kontūro - ovaliais branduoliais; mitozių 2/10 DPRL. gausūs dilatuoti latakai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: vidutinis visos membranos nusidažymas 60% naviko ląstelių.  Ki67 proliferacinis aktyvumas 15%.
answer:  1a

  9%|▉         | 60/661 [01:40<16:52,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm ilgio.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 15%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 10% naviko ląstelių.  Ki67+ 15%
answer:  2b

  9%|▉         | 61/661 [01:42<17:27,  1.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.  2(2b). Kraštai - skubus tyrimas - be naviko.  3(1). Pašalintas kairės krūties kvadrantas - planinis tyrimas.  4(3). Kairės pažasties limfmazgiai - planinis tyrimas.. 3(1). Krūties sektorius 10,5x6x4,5 cm. Krūties audinyje, pjūvyje pilkšvas, standus, aiškių ribų 15x13x8 mm navikas, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1,6 cm.   4(3). Riebalinio audinio fragmentai, bendras dydis 7,5x4,5x2 cm. Rasta 10 limfmazgių, didžiausias 4,5 cm.. 1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   2(2b, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko  3(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (I - 14 mm; II - 4 mm) N2a (mts 6/10 l/m; iki 45 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.     Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: solidinis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   4(3). "Kairės pažasties limfmazgiai": duktalinės karcinomos metastazė šešiuose limfmazgiuose (mts 6/10 l/m; iki 45 mm skersmens; su ekstranodaliniu plitimu).. 1(2a, ekstra). "Kraštai": fokaliai fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar nežymiai hiperplastišku epiteliu; be naviko.   2(2b, ekstra). "Kraštai": fokaliai fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar nežymiai hiperplastišku epiteliu; be naviko.   3(1). NAVIKAS(du izoliuoti 4 mm atstumu nutolę naviko židiniai: I - 14 mm; II - 4 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės (~15%), kribriforminės, trabekulinės, nedidelės lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, negausia ar vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki 9/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Negausi perinavikinė limfocitinė infiltracija.     APLINKA: šalia naviko - solidiniai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su apokrinės metaplazijos zonomis.   SEKTORIAUS REZEKCIJOS KRAŠTAS: fibrozuotas brandus riebalinis audinys; be naviko.   4(3). "Kairės pažasties limfmazgiai"(10): šešiuose (6) limfmazgiuose aukščiau, punkte Nr.3, aprašyto naviko metastazės, iki 45 mm skersmens, su ekstranodaliniu plitimu.. nan
answer:  1(

  9%|▉         | 62/661 [01:43<16:40,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 55% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacijos FISH tyrimo rezultatas teigiamas (žr. molekulinio tyrimo aprašymą ir pastabas).  Ki67+ 25%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 7/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 55% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos ir netolygus stiprus membranos nusidažymas 60% navik
answer:  3b

 10%|▉         | 63/661 [01:45<16:17,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 15 mm; II - 12 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Krūties audinį infiltruoja duktalinės struktūros, netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko lą
answer:  1b

 10%|▉         | 64/661 [01:46<16:23,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 18 G automatine biopsine adata punktuotas ~4x5 mm dydžio neaiškių ribų deformacijos židinys (atitinkantis MR tyrime BIRADS 4 k/m kaupiantį židinį) dešiniojoje krūtyje ties 12-1 val. vidurinėje/ periferinėje dalyje, paimti trys biopsiniai stulpeliai histologijai (I buteliukas).   2 ėminio aprašas: 2. 18 G automatine biopsine adata punktuotas ~7x9 mm dydžio neaiškių ribų deformacijos židinys (atitinkantis MR tyrime BIRADS 4 k/m kaupiantį židinį) dešiniojoje krūtyje ties 1 val. vidurinėje/ periferinėje dalyje, paimti keturi biopsiniai stulpeliai histologijai (II buteliukas).. 1. 3 biopsiniai stulpeliai: I - 7 mm; II - 10 mm; III - 12 mm.  2. 4 biopsiniai stulpeliai: I - 7 mm; II - 9 mm; III - 6 mm; IV - 6 mm.. N1: Krūties audinio fibrozė.  N2: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.. N1: Krūties audinio fibrozė, pavieniai normalios struktūros kanaliukai.  N2: Krūties audinį infiltruoja pabiros ląstelės ir juostos iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 2%.
answer:  0

 10%|▉         | 65/661 [01:48<15:55,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 10 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros, negausūs smulkūs kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 8
answer:  1b

 10%|▉         | 66/661 [01:49<15:33,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. Krūties audinį infiltruoja smulkios duktalinės struktūros, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 12%
answer:  1b

 10%|█         | 67/661 [01:51<15:26,  1.56s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 4 biopsiniai stulpeliai. 4 biopsiniai stulpeliai: I - 7 mm; II - 6 mm; III - 4 mm, IV - 3 mm.. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 90% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 1%.. Bioptatuose (4/4) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos trabekulėmis ir pabirai besidėstančių ląstelių negausia šviesia eozinofiliška citoplazma, nežymiai polimorfiškais, vidutinio kalibro, ovaliais branduoliais; mitozių 1/10 DPRL. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 90%.  HER2: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67 proliferacinis aktyvumas 1%.  E-cadherin(+) trūkinėjanti membr. r-ja <5%.
answer:  1b

 10%|█         | 68/661 [01:52<15:21,  1.55s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 14 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 8%. Karštame taške 15%.. Krūties audinį 2-se bioptatuose infiltruoja iki 9 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 3/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 8% naviko ląstelių. Karštame taške 15%.  Progesterono receptoriai: stipri (+++) r
answer:  0.

 10%|█         | 69/661 [01:54<15:52,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, planinis.  2. pjūvio kraštai, planinis.   3. sarginiai l/m, planinis.   4. sektorius, planinis.. 1. Riebalinio audinio fragmentas 2,2x2x1,2 cm. v/m  2. Riebalinio audinio fragmentas 2x1,5x1,2 cm. v/m  3. Riebalinio audinio fragmentas 3x2,5x1,5 cm. Rasti 3 limfmazgiai iki 2,2 cm.   4. Krūties sektorius 7,5x3,5x3 cm su oda 7x2 cm. Odoje rusvas, gruoblėtas, elastingas, kiek iškilęs darinys 1,5x0,3x0,1 cm, nuo odos rezekcijos krašto nutolęs 0,1 cm. Krūties audinyje balkšvas, standus, gerai ribotas navikas 18x15x11 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 0,8 cm, nuo odos darinio - 1,3 cm.. 1. Krūties fibrocistiniai pokyčiai.  2. Nežymi fokalinė krūties audinio fibrozė.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,8 cm) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės naviko invazijos nėra). Seborėjinė keratozė.     Estrogenų receptoriai: stipri (+++)  reakcija, 90% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 15%.. 1. Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2. Krūties audinyje - negausūs smulkūs fibrozės židiniai su smulkiais kanaliukais, išklotais dvisluoksniu epiteliu.  3. Nežymi sinusų histiocitozė trijuose (3) limfmazgiuose.  4. Krūties audinyje - navikas: solidines naviko struktūras formuoja ląstelės su gan gausia eozinofiline citoplazma, vidutinio kalibro ar kiek stambesniais apvalios formos netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 27 / 10 DPRL. Krūties odoje - epidermio darinys, išklotas hiperplastišku, akantotišku, vietomis papiliarizuotu, hiperkeratotišku daugiasluoksniu plokščiu epiteliu, suformuotu iš bazaloidinių ląstelių su raginėmis cistomis, bazalinio epidermio sluoksnio hiperpigmentacija.. 4. Navikas (10 blokas):  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 3% naviko ląstelių.
answer:  0.

 11%|█         | 70/661 [01:56<16:06,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas,   3(2)- Kairės pažasties sarginiai limfmazgiai, skubu  4(3)- Kairės krūties sektorius, planinis. 4. Krūties sektorius 7x4,5x5 cm su oda 6,5x4,5 cm, su įdubusiu speneliu. Krūties audinyje, pilkšvas standus neaiškių ribų navikas 18x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 2 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi blogai diferencijuota (G3; 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(20 mm) N(sn)0(0/4 l/m), LVI-2(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS)(solidinė, kribriforminė, komedo).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 4 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.  4. SPENELIS: be patologijos.  NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai 20 mm), suformuotas fibrozuotoje stromoje ir tarp lipocitų infiltratyviai plintančių solidinių, lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 39/10 DPRL. Šalia yra dilatuotų kanaliukų su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais, fokaliai su komedo nekroze centre; negausūs kanaliukai su apokrinine metaplazija.. 4. Navikas (16 blokas):  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  D2-40+ ir CD34+ endotelizuotose ertmėse naviko plitimo neidentifikuota.
answer:  1(

 11%|█         | 71/661 [01:58<16:18,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). Sektoriaus kraštai.   2(N2). Sektoriaus kraštai.   3(N3). Sarginiai l/n.   4(N4). Deš.krūties sektorius su naviku.. 4. Krūties sektorius 9x5,7x4,5 cm su odos lopu 7x2 cm, žymėtas viela. Pjūvyje, vielos projekcijoje balkšvas, kiek neaiškių ribų navikas 18x18x10 mm, nuo artimiausio rezekcijos krašto nutolęs 0,7 cm, nuo odos - 1,6 cm.. 1. Krūties fibrocistiniai pokyčiai: stulpinis epitelio pokytis, paprasta intraduktalinė hiperplazija.   2. Krūties audinys be patologinių pokyčių.   3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2/ 6 b. pagal Nottingham s.) duktalinė karcinoma, suminis Nr. 1 - 4 pTNM:   pT1c (18 mm) pN0(sn) (0/3 l/m), LVI0 (limfovaskulinės naviko invazijos neidentifikuota).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-19395, žr. pastabą.. 1. Krūties audinyje - minimali stromos fibrozė, yra latakų su stulpiniu epitelio pokyčiu, keli latakai su ryškia intraduktaline epitelio ir mioepitelinių ląstelių hiperplazija.   2. Krūties audinyje - minimali stromos fibrozė.   3. Limfmazgiai (3) su tušuota architektūra, negausiais pirminiais folikulais, makrofagų reakcija parakortekse, nežymia stromos fibroze.  4. Krūties audinyje - infiltratyviai plintantis navikas, formuojamas solidinių, trabekulinių, negausių kompleksinių ar blogai suformuotų liaukinių struktūrų, sudarytų iš vidutinio dydžio stulpinių bei poligonalinių ląstelių gausia šviesiai eozinofiliška citoplazma, vidutiniškai polimorfiškais, kiek nelygaus kontūro ovoidiniais branduoliais su vezikulizuotu chromatinu ir smulkiomis ryškiomis nukleolėmis. Navike iki 3 mitozių/ 10 DPRL.. nan
answer:  1a

 11%|█         | 72/661 [01:59<15:48,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 8 mm.. PAPILDYTA  Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 1%.. Bioptatuose (2/2) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, nežymiai polimorfiškais, vidutinio kalibro, ovalaus kontūro branduoliais; mitozių 1/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: neigiama reakcija.  HER2: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67 proliferacinis aktyvumas 1%.  E-cadherin(+++) membr. r-ja 100%.
answer:  1b

 11%|█         | 73/661 [02:01<17:28,  1.78s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta dešinė krūtis ir dešinės pažasties limfmazgiai. Krūtis, 1232 g svorio, 23x16,5x5 cm. Spenelis įtrauktas. Lateralinių kvadrantų riboje - pilkšvas standus navikas 56x43x35 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, peraugantis ir išopėjęs odoje. Pažasties narveliena 8x7x3,5 cm. Rasti 12 limfmazgių iki 1,6 cm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham sistemą) duktalinė karcinoma, pT4b (56 mm, odoje išopėjęs navikas) pN2a (4/11 l/m su mts iki 10mm) LVI-0 (limfovaskulinė invazija neidentifikuota).  Radikalus pašalinimas.. Krūties audinyje - desmoplastiškoje stromoje, infiltratyviu frontu plintantis, odoje išopėjęs navikas, suformuotas lizdų, solidinių kompleksų, trabekulių, pavienių tubulių (<10%).  Naviko ląstelės su vidutinio gausumo, eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar ovoidiškais, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių navike iki 14/10DPRL.  Aplinkiniame krūties audinyje latakai su židinine apokrinine metaplazija.   4/11 limfmazgių - aukščiau aprašyto naviko metastazės iki 10 mm.. nan
answer:  1a

 11%|█         | 74/661 [02:03<17:54,  1.83s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2) - dešinės pažasties sarginis limfmazgis  - skubus tyrimas dviejose iš trijų limfmazgių metastazės  2(N1) - pašalinta dešinė krūtis - planinis tyrimas. 2(1). Krūtis 1835 gramų svorio, 30x22x7,5 cm, žymėtas viela. Vielos projekcijoje, lateralinių kvadrantų riboje, balkšvas, standus, neaiškių ribų navikas 3,4x2x1,3 cm, nuo giliojo rezekcijos krašto nutolęs 3 cm, nuo odos - 2,5 cm. Viršutinių kvadrantų riboje balkšvas, standus, gana aiškių ribų darinys 1,5x1x0,8 cm, nuo giliojo rezekcijos krašto nutolęs 2,5 cm, nuo odos - 5 cm.. 1(ekstra). "Dešinės pažasties sarginiai limfmazgiai":   lobulinės karcinomos metastazė limfmazgiuose (mts 2/3 l/m; iki 18 mm skersmens).    2(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT2(m) (navikai: I - 34 mm; II - 7 mm) N1a(sn) (mts 2/3 l/m; iki 18 mm skersmens),    LVI-2 (limfovaskulinė invazija smulkiose šakose). Perineurinis plitimas.   Imunofenotipas:   Estrogenų receptoriai: vidutinė-stipri (++/+++) reakcija, 99% naviko ląstelių.  Progesterono receptoriai: vidutinė-stipri (++/+++) reakcija, 99% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%. Karštame taške 10%.    Krūties lobulinė intraepitelinė neoplazija (LCIS).  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Krūties rezekcijos kraštas be naviko.. 1(ekstra). "Dešinės pažasties sarginiai limfmazgiai"(3): dviejuose (2) limfmazgiuose žemiau, punkte Nr.2, aprašyto naviko metastazės, iki 18 mm skersmens, su ekstranodaliniu plitimu.   2(1). SPENELIS: normalios histologinės struktūros.   NAVIKAS (du navikai: I - 34 mm; II - 7 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", solidinės naviko struktūros, suformuotos mažai kohezyvių vidutiniškai ar ryškiai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 7/10 DPRL.   Limfovaskulinė naviko invazija smulkiose šakose. Perineurinis naviko plitimas. Fokaliai negausi perinavikinė limfocitinė infiltracija, fibrozės židiniai su hemosiderofagais, fibroadenomatoziniai stromos pokyčiai, pavieniai mikrokalcifikatai.   APLINKA: zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais. Šalia II naviko - kribriforminiai intraduktaliniai polimorfiškų kohezyvių naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   GILUSIS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 2(1). Navikas (blokas 25):  Estrogenų receptoriai: vidutinė-stipri (++/+++) reakcija, 99% naviko ląstelių branduolių.  Progesterono receptoriai: vidutinė-stipri (++/+++) reakcija, 99% naviko ląstelių branduolių.   HER2: silpna (+) necirkuliari reakcija, 4
answer:  3%

 11%|█▏        | 75/661 [02:05<16:51,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis iš 16 mm dominuojančio darinio. Biopsinis stulpelis 13 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 12
answer:  1b

 11%|█▏        | 76/661 [02:06<16:06,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsiniai stulpeliai. Biopsinis stulpelis 13 mm ilgio.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 85%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 12/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 85%.
answer:  3

 12%|█▏        | 77/661 [02:08<16:03,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2 - deš. pažasties sarginis l/m   -  skubus tyrimas dviejose iš trijų limfmazgiu markometastazės  2 ėminio aprašas: N1 - pašalinta deš krūtis - planinis ištyrimas. 2. Krūtis 427 g svorio, 18x15x4 cm. Krūties audinyje, viršutinių lateraliniame kvadrante - balkšvas, standus, neaiškių ribų navikas 34x22x12 mm, nuo odos nutolęs 1,5 cm, nuo artimiausio rezekcijos krašto - 0,6 cm. 1,9 cm atstumu nuo naviko balkšvas, standus židinys 0,5x0,4x0,3 cm.. 1(ekstra). Duktalinės karcinomos metastazės limfmazgiuose (3/3 l/m iki 7 mm).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(m)(34 mm ir 4 mm navikai) pN1a(sn)(3/3 l/m MTS iki 7 mm) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija).(DCIS/DIN3 DIN1 DIN2, kribriforminis ir papilinis tipai).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis iki 20%.. 1(ekstra). 3/3 limfmazgių aprašyto naviko metastazės iki 7 mm.  2. Krūtyje - navikas (34 mm ir 4 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, trabekulinėmis struktūromis, lizdais, grandinėlėmis ir pabirai besidėstančių ląstelių negausia - vidutinio gausumo blyškia eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais - apvaliais, vezikulizuotais branduoliais ryškiomis nukleolėmis; mitozių 3/10 DPRL. Limfovaskulinė invazija.. NAvikas (16 blokas): E-cadherin(+++) membr. r-ja 100%; p120_catenin(+++) membr. r-ja 100%;
answer:  0.

 12%|█▏        | 78/661 [02:10<16:42,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinia kraštas, skubu  3(2). Kairės pažasties sarginiai limfmazgiai, skubu  4(3). Kairės krūties kvadrantas, planinis. 4. Krūties sektorius 20x10,5x7,5 cm su odos lopu 16,5x7 cm, su speneliu, žymėtas vielomis. I vielos projekcijoje pilkšvas standus darinys 10x6x5 mm, nuo giliojo rezekcijos krašto nutolęs 3 cm, nuo odos - 3,7 cm. Atstumas tarp vielų 8 cm.  II vielos projekcijoje neaiškių ribų darinys 16x6x6 mm, nuo odos rezekcijos krašto nutolęs 2 cm, nuo giliojo - 2,6 cm.  Spenelio projekcijoje pilkšvas, skiltėtas navikas 40x35x30 mm, nuo giliojo rezekcijos krašto nutolęs 3 cm, infiltruoja odą.  Dariniai sudėti visi. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (4 l/m).    4. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(m)(16 mm, 10 mm navikai) pN0(sn)(0/4 l/m) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija). Aukšto laipsnio duktalinė karcinoma in situ (DIN3 solidinis tipas).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 95% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 70% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 25%.. 1(1a). Krūties audinyje - fibrozės zonos su fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu.  2(1b). Krūties audinyje - fibrozės zonos su fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu. 2,35  3(2). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (16 mm, 10 mm židiniai) ekspansyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais - stambiais, ryškiai polimorfiškais,  nereguliaraus kontūro ir ovaliais branduoliais ryškiomis nukleolėmis; mitozių 13/10 DPRL. Limfovaskulinė invazija.  Greta dilatuoti kanaliukai su solidiniais proliferatais iš analogiškų navikui ląstelių.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 95%.  Progesterono receptoriai: (+++)(brand. r-ja) 70%.  HER2: nusidažiusių membranų nėra.  Ki67 proliferacinis aktyvums 25%.  CK14(-); Synaptophysin+ <1%.
answer:  0

 12%|█▏        | 79/661 [02:11<16:00,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 14 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 60%.. Bioptate - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis lizdais ir trabekulėmis besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 5/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 95%.  HER2: nusidažiusių naviko ląstelių nėra.  Ki67 proliferacinis aktyvumas 60%.
answer:  1b

 12%|█▏        | 80/661 [02:13<15:26,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 40%.. Krūties audinį infiltruoja smulkūs netaisyklingi solidiniai kompleksai ir trumpos juostos iš vidutiniškai, vietomis ryškiai, polimorfiškų ląstelių, mitozių neidentifikuota.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: vidutinis dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+
answer:  40%

 12%|█▏        | 81/661 [02:14<15:37,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. Pjūvio kraštai, ekstra.   3. Sarginiai l/m, ekstra.   4. Sektorius, planinis.. 4. Krūties sektorius 9,5x7x3,5 cm su oda 7x2,5 cm. Krūties audinys fibrozuotas visame plote, fibrozėje gelsvas standus, neaiškių ribų navikas 30x25x20 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 1 cm.. 1. Pjūvio kraštai - sklerozuojanti adenozė su gestacijai/laktacijai būdingais pokyčiais.  2. Pjūvio kraštai - sklerozuojanti adenozė su gestacijai/laktacijai būdingais pokyčiais.    3. Sarginiai l/m - limfmazgiai (3) be patologinių pokyčių.    4. Krūties sektorius.   Blogai diferencijuota krūties invazinė duktalinė  karcinoma(su medulinės karcinomos struktūra ir gausiais naviką infiltruojančiais limfocitais);   (G3, 9 balai pgl Nottingham),   pT2 pLVI-0 pN0 pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: reakcija neigiama.  Progesterono receptoriai: vidutinis branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 60%.    Sklerozuojanti adenozė.. 1. Pjūvio kraštai - Kompaktiška liaukų hiperplazija fibrozuotoje stromoje, sudarytų iš sekrecinio tipo epitelinio, mioepitelinio ląstelių sluoksnio ir bazinės membranos.     2. Pjūvio kraštai - Kompaktiška liaukų hiperplazija fibrozuotoje stromoje, sudarytų iš sekrecinio tipo epitelinio, mioepitelinio ląstelių sluoksnio ir bazinės membranos.     3. Sarginiai l/m - limfmazgiai (3) be patologinių pokyčių.    4. Krūties sektorius. Krūties audinį infiltruoja dalinai riboto, bet netaisyklingų kraštų naviko solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių >35/10 DPRL; gausi intranavikinė limfocitų infiltracija. Navikas 1 mm nuo artimiausio giliojo krašto. Plitimo kraujagyslėse nestebima.. nan
answer:  3b

 12%|█▏        | 82/661 [02:16<16:15,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2: dešinės pažasties sarginis limfmazgis - skubus tyrimas 2l/m be naviko  2 ėminio aprašas: N1: pašalinta dešinė krūtis - planinis tyrimas. 2. Krūtis gramų 363 svorio, 17,5x12x3 cm. Apatiniame lateraliniame kvadrante, balkšvas, standus, neaiškių ribų navikas 1,2x1x0,8 cm (sudėtas visas), nuo odos nutolęs 2,5 cm, nuo giliojo rezekcijos krašto - 0,5 cm. Odoje randas 6,5 cm ilgio.. 1(2, ekstra). "Dešinės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).   2(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 12 mm) N0(sn) (0/2 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS). Randiniai pokyčiai odoje.   Gilusis krūties rezekcijos kraštas be naviko.. 1(2, ekstra). "Dešinės pažasties sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2(1). SPENELIS: normalios histologinės struktūros.   RANDAS: dermoje ryškios kolageninės fibrozės židinys su vertikalai orientuotomis, kiek dilatuotomis kraujagyslėmis.   NAVIKAS (mikroskopiškai bent 11 mm skersmens): krūties audinyje, ryškiai fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retos duktalinės ir kribriforminės bei dominuojančios trabekulinės ir nedidelės lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio kiek nelygaus kontūro ovaliais/apvaliais branduoliais su retomis smulkiomis nukleolėmis; mitozių iki 2/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija, pavieniai hemosiderofagai. Pavieniai mikrokalcifikatai.   APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   GILUSIS REZEKCIJOS KRAŠTAS: fibrozuotas brandžių lipocitų suformuotas audinys; be naviko.. 2(1). Navikas (blokas 12):  HER2: silpna (+) necirkuliari reakcija, 15% naviko ląstelių membranoje.
answer:  1.

 13%|█▎        | 83/661 [02:18<16:37,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštas, ekstra.  2. pjūvio kraštas, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 11,5x4,5x5,5 cm, su odos fragmentu 10,5x2,5 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 10x10x7 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 3 cm.. 1(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija); be naviko.   2(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 9 mm) N0(sn) (0/3 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis tipas).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).. 1(ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, apokrinės metaplazijos zonomis; be naviko.   2(ekstra). "Kraštai": vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS (mikroskopiškai 9 mm skersmens): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės, kribriforminės, trabekulinės, nedidelės lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomisnukleolėmis; mitozių iki 6/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija, pavieniai hemosiderofagai. Pavieniai mikrokalcifikatai.  APLINKA: šalia naviko - kribriforminiai intraduktaliniai naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 4. Navikas (blokas 36):  HER2: silpna (+) necirkuliari reakcija, 1% naviko ląstelių membranoje.
answer:  0

 13%|█▎        | 84/661 [02:19<15:51,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Deš. krūtis su limfmazgiais, planinis. Krūtis 1100 g svorio, 25x20x4  cm, spenelis įtrauktas, su pažasties narveliena 13x9x4 cm. Krūties audinyje pilkšvas standus netaisyklingų kontūrų navikas 2,8x1,7x2,2 cm, nuo artimiausio rezekcijos krašto(dažyta mėlynu tušu) 2,5 cm, nuo odos 1,5 cm. Pažasties narvelienoje rasta 16 limfmazgių, didžiausias 3,4 cm.. Krūties mikropapilinė karcinoma (G2, 6 balai pgl Nottingham) pT2(28mm); pN2a (iš 16 l/m).. Krūties audinyje 28mm navikas: smulkūs solidiniai kompleksai, vietomis su spindžiu centre ir su stromos prašviesėjimu aplink, sudaryti iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.  Iš rastų 16 limfmazgių 8 su metastazėmis iki 34mm.  Rezkecijos kraštas be naviko.. nan
answer:  0,

 13%|█▎        | 85/661 [02:21<15:27,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 15 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 35%, vietomis iki 60%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 20/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  Ki67+ 35%,
answer:  3b

 13%|█▎        | 86/661 [02:22<15:07,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 8 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 80%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 20/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 95% naviko ląstelių.  Ki67+ 80%.
answer:  3b

 13%|█▎        | 87/661 [02:24<14:46,  1.54s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 14 mm; II - 14 mm; III - 10 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%, fokaliai iki 20%.. Krūties audinį infiltruoja smulkūs kribroziniai/solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  1.

 13%|█▎        | 88/661 [02:25<14:31,  1.52s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 8 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20%.. Krūties audinį infiltruoja netaisyklingi kribroziniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: vidutinis dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 20%.
answer:  0

 13%|█▎        | 89/661 [02:27<15:26,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.(N2a). kraštai - extra;  2(N2b). kraštai - extra.  3(N1). Pašalintas kairės krūties kvadrantas ir kairės pažasties limfmazgiai.-planinis. 3. Krūties sektorius 12x7x5,5 cm su oda 11,5x3,5 cm. Krūties audinyje, balkšvas standus, neaiškių ribų I navikas 18x14x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 4,5 cm. Šalia I naviko, balkšvas standus, aiškių ribų II navikas 12x10x8 cm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos 4 cm, nuo I naviko 0,1 cm. Nuo I naviko 0,3 cm atstumu, balkšvas, standus, aiškių ribų III navikas 10x8x8 cm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos 3 cm. Bendras navikų dydis 25x23x20 mm. Rastas vienas intramamarinis limfmazgis, 0,5 cm. Atskirai riebalinio audinio fragmentai, bendras dydis 7x4x,5x2,5 cm. Rasti 9 limfmazgiai iki 3,3 cm.. 1(2a)(Extra). Krūties audinys.  2(2b)(Extra). Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT(m)1c(3 naviko židiniai: 15 mm, 13 mm ir 9 mm) N2a(mts 5/10 l/m; didžiausia 33 mm, su ekstranodaliniu plitimu), LVI-2(limfovaskulinė invazija). Didžiausias (I) navikas siekia markiruotą rezekcijos kraštą.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Androgenų receptoriai: vidutinis branduolių nusidažymas 70% naviko ląstelių.  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).. 1(2a)(Extra). Krūties audinyje, neryškiai fibrozuotoje stromoje - pavieniai smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(2b)(Extra). Krūties audinyje, neryškiai fibrozuotoje stromoje - pavieniai smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(1). NAVIKAS: krūties audinyje - 3 identiškos histologinės struktūros riboti navikai (mikroskopiškai 15 mm, 13 mm ir 9 mm), suformuotas fibrozuotoje stromoje plintančių fokaliai besiliejančių vidutinių ir smulkių lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo "tamsia" eozinofiliška citoplazma, vidutinio kalibro, apvaliais/ovaliais, kiek polimorfiškais, dalis su aiškia nukleole branduoliais. Mitozių iki 9/10 DPRL. Šalia naviko kiek dilatuoti kanaliukai su solidiniais ir negausiais kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais, fokaliai su centrine komedo nekroze.  LIMFMAZGIAI: 5 iš 10 limfmazgių - naviko metastazės (didžiausia 33 mm, su ekstranodaliniu plitimu). Limfovaskulinė invazija šalia.. 1. Navikas (7 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Androgenų receptoriai: vidutinis branduolių nusidažymas 70% naviko ląstelių.  Synaptophysin(-).
answer:  1(

 14%|█▎        | 90/661 [02:29<15:24,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N3). Sarg. l/m - skubus - be naviko  2(N2a). kraštai - skubus - be naviko  3(N2b). kraštai - skubus - be naviko  4(N1)- sektorius - planinis patologinis tyrimas. 4. Krūties sektorius 8x4,5x5 cm su odos lopu 6,5x2,5 cm ir speneliu. Spenelio projekcijoje pilkšvas, standus neaiškių ribų navikas 25x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 2 cm, infiltruoja spenelį.. 1. Krūties audinys.  2. Krūties audinys.   3. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi, gerai diferencijuota (G1, 4 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 25mm) pN0(sn)(0/1 l/m); LVI-0 (Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-19397 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.". 1. Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  2. Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  3. Vienas(1) limfmazgis be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4. Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas duktalinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais; navike - iki 2 mitozių/10 DPRL; naviko plitimas dermoje (spenelio projekcijoje).. nan
answer:  0.

 14%|█▍        | 91/661 [02:31<15:47,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2). Deš. pažasties sarginiai limfmazgiai, skubu  4(3). Deš. krūties sektorius, planinis. 3. Krūties sektorius 5x4x2,2 cm, be odos, žymėtas viela. Vielos projekcijoje pilkšvas, neaiškių ribų židinys 6x5x5 mm, nuo giliojo rezekcijos krašto nutolęs 1,5 cm. (židinys sudėtas visas). 1. Krūties atipinė lobulinė hiperplazija.   2. Krūties fibrocistiniai pokyčiai.    3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2/ 6 b. pagal Nottingham s.) duktalinė karcinoma,   pT1b (6 mm) pN0(sn) (0/3 l/m), LVI0 (limfovaskulinės naviko invazijos neidentifikuota).   Imunofenotipas:   estrogenų receptorių (ER) reakcija teigiama: stiprus/ vidutinis branduolių nusidažymas 100% naviko ląstelių,   progesterono receptorių (PR) reakcija teigiama: stiprus/ vidutinis branduolių nusidažymas 10% naviko ląstelių,   HER2 reakcija neigiama (0),   Ki67 prolif. indeksas ~5%.   Žemo laipsnio duktalinė karcinoma in situ (DCIS).. 1. Krūties audinys su labai negausiais smulkiais normalios struktūros kanaliukais ir keliais smulkiais kanaliukais su "intraepitelinėmis" diskohezyviomis ląstelėmis eozinofiliška citoplazma, ekscentriškais, nežymiai polimorfiškais branduoliais.   2. Krūties audinys netolygiai fibrozuota stroma, su negausiais cistiškai pakitusiais ir smulkiais latakais.   3. Limfmazgiai(3) su negausiais antriniais folikulais, sinusų histiocitoze, be naviko plitimo.   4. Krūties audinyje - infiltratyviai plintantis navikas, formuojamas negausių tubulinių, kompleksinių ar blogai suformuotų liaukinių bei smulkių solidinių struktūrų, sudarytų iš vidutinio dydžio stulpinių bei poligonalinių ląstelių gausia šviesiai eozinofiliška citoplazma, nežymiai ar vidutiniškai polimorfiškais, kiek nelygaus kontūro ovoidiniais branduoliais su smulkiomis ryškiomis nukleolėmis. Navike iki 2 mitozių/ 10 DPRL.   Naviko periferijoje - grupės latakų su intraduktaliniais kribriforminiais proliferatais iš duktalinio tipo stambių ląstelių nežymiai polimorfiškais branduoliais.. 1. ALH ląstelės e-cadherin(-).   4. Navikas (15 blokas):   ER: stiprus/ vidutinis branduolių nusidažymas 100% naviko ląstelių,   PR: stiprus/ vidutinis branduolių nusidažymas 10% naviko ląstelių,   HER2: silpnas dalies membranos nusidažymas <10% naviko lą
answer:  1+

 14%|█▍        | 92/661 [02:32<16:03,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštas  - skubus tyrimas  2 ėminio aprašas: N2b kraštas  - skubus tyrimas  3 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas  4 ėminio aprašas: N1: pašalintas dešinės krūties kvadrantas su vielute - planinis tyrimas  5 ėminio aprašas: N4: papildomas kraštas - planinis tyrimas. 4. Krūties sektorius 3x1x6,5 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 6x4x4 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,5 cm.  5. Riebalinio audinio fragmentas 2x1,3x0,4 cm. v/m. 1(N2a) kraštas - riebalinis audinys be patologinių pokyčių.  2 (N2b) kraštas - riebalinis audinys be patologinių pokyčių.    3 (N3) dešinės pažasties sarginis limfmazgis: limfmazgiai(3) be patologinių pokyčių.    4 (N1) - dešinės krūties kvadrantas.   Invazinė lobulinė karcinoma  (G1; 5 b. pgl. Nottingham sist.);  pT1b pN0 pLVI-0 pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    5 (N4) - papildomas kraštas. Riebalinio audinio fragmentas be patologinių pokyčių.. 1(N2a) kraštas - riebalinis audinys be patologinių pokyčių.  2 (N2b) kraštas - riebalinis audinys be patologinių pokyčių.  3 (N3) dešinės pažasties sarginis limfmazgis: limfmazgiai(3) be patologinių pokyčių.  4 (N1) - dešinės krūties kvadrantas. Riebalinį audinį infiltruoja iki 6,5 mm :   - juostos ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais negausioje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.  5 (N4) - papildomas kraštas. Riebalinio audinio fragmentas be patologinių pokyčių.. nan
answer:  0

 14%|█▍        | 93/661 [02:34<15:36,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Pašalinta kairė krūtis planinis tyrimas. Krūtis, 454 g svorio, 14,5x10,5x6 cm su raumens fragmentu 6x3x1 cm, spenelis įtrauktas. Raumens projekcijoje pilkšvas, standus, aiškių ribų navikas 8x5,5x4,5 cm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, išopėjęs odoje.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b (8cm navikas; išopėjimas).. Krūties audinyje išopėjęs 8cm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 15/10 DPRL.  Operacinis pjūvis be naviko.. nan
answer:  3c

 14%|█▍        | 94/661 [02:35<15:07,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 10 mm; II - 13 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%, vietomis 15%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 4%, vietomis
answer:  0

 14%|█▍        | 95/661 [02:37<15:47,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 11,5x6,5x4 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 18x12x11 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos - 2,8 cm. Šalia naviko fibrozės zona 5,5x2,5x1,5 cm.. 1(kraštai). Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.     2(kraštai). Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.     3(sarginiai l/m). Duktalinės karcinomos mikrometastazės (iki 1 mm skersmens) 1-me/3 limfmazgių.    4(krūties sektorius).   Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT1c (18 mm) pN1mi(1/3 l/m iki 1mm) pLVI-2 (limfovaskulinė invazija smulkiose gyslose) pR0(radikalus pašalinimas).  Naviko imunotipas nustatytas priešoperaciniame biopsijos tyrime (žr. pastabą).   Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis, kribriforminis, komedo tipai).  Krūties fibrocistiniai pokyčiai:   paprastoji intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija. Adenozė.. 1(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais ar cistiškai dilatuotais kanaliukais, klotais dvisluoksniu ar hiperplastišku epiteliu, su židinine apokrinine metaplazija.  2(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais ar cistiškai dilatuotais kanaliukais, klotais dvisluoksniu ar hiperplastišku epiteliu, su židinine apokrinine metaplazija.  3(ekstra). 1/3 limfmazgių trys žemiau aprašyto naviko židiniai iki 1 mm skersmens;   4. NAVIKAS. Krūties audinyje - desmoplastiškoje stromoje, infiltratyviu frontu plintantis navikas, suformuotas lizdų, trabekulių, kribriforminių struktūrų ir tubulių (<10 %). Naviko ląstelės su negausia ar vidutinio gausumo, amfofiliška citoplazma, vidutinio kalibro ar stambiais, apvaliais ar ovoidiškais, vesikuolizuotais, ryškiai polimorfiškais branduoliais su aiškiomis nukleolėmis. Mitozių navike iki 9/10DPRL.  Navikas nuo sektoriaus rezekcijos krašto nutolęs 1,5 mm. Naviko plitimas endotelizuotuose spindžiuose.  Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių, siekiantys rezekcijos kraštą. Stromoje yra  zonų su cholesterolio kristalais, apsuptais makrofagų ir svetimkūnio tipo daugiabranduolių gigantinių ląstelių.  FIBROZĖ. Krūties audinys su fibrozės zonomis, smulkiomis ar stambiomis lobulėmis su smulkiais latakais, klotais dvisluoksniu epiteliu. Yra latakų su cistine dilatacija, apokrinine metaplazija, stulpinių ląstelių pokyčiu su apikaline sekrecija, įprastine duktaline hiperplazija.. nan
answer:  1a

 15%|█▍        | 96/661 [02:39<15:45,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu   3(2). Kairės pažasties sarginiai limfmazgiai, skubu  4(3). Kairės krūties sektorius, planinis. 4. Krūties sektorius 9x4,5x4 cm su oda 8x3 cm. Krūties audinys visame plote fibrozuotas. Fibrozėje - rusvas, standus, neaiškių ribų navikas 17x17x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1,6 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi blogai diferencijuota (G3; 8 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 17 mm), pN0(sn)(0/2), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).. 1. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.   2. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.   3. Du limfmazgiai (2 l/m) su sinusų histiocitoze.  4. Krūties audinyje navikas (17 mm mairoskopiškai), infiltratyviu augimo frontu, suformuotas solidinių, trabekulių ir negausių kribriforminių struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, polimorfiškais, hiperchromiškais branduoliais su ryškiais branduolėliais. Mitozių navike 30/10DPRL. Limfovaskulinė naviko invazija (LVI2). Navikas nuo rezekcijos krašto nutolęs per 4 mm. Krūties audinyje greta naviko gausūs latakai užpildyti kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, hiperchromiškais, polimorfiškais branduoliais. Aplinkiame audinyje gausūs dilatuoti latakai, kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.. nan
answer:  0,

 15%|█▍        | 97/661 [02:41<16:39,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). Sarginiai l/n - extra.   2(N2). Deš.krūtis su navikais.. 2. Krūtis 585 gramų svorio, 19x10,5x4,5 cm. Krūties audinyje - du balkšvi standūs naviko židiniai:   - I - centrinėje dalyje, 9x8x7 mm dydžio, nuo odos nutolęs 3 cm, nuo giliojo rezekcijos krašto - 1,5 cm;   - II - medialiniame viršutiniame kvadrante, 12x11x7 mm dyžio, nuo I naviko nutolęs 2,5 cm, nuo odos - 2 cm, nuo artimiausio rezekcijos krašto - 0,2 cm. Navikai sudėti visi.. 1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     2. Krūties multižidininė vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) invazyvi duktalinė (12 mm) ir lobulinė (9 mm) karcinoma, SUMINIS TNM:   pT1c(m) (I - 9 mm; II - 12 mm) N0(sn) (0/3 l/m),    LVI-0 (limfovaskulinė invazija neidentifikuota).   Perineurinis plitimas. Kalcifikatai.     Imunofenotipas (šiame tyrime):  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 20% naviko ląstelių.   HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%. Karštame taške 10%.  ŽR. PASTABĄ.     Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis tipas).   Krūties lobulinė intraepitelinė neoplazija (LCIS).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   Gilusis rezekcijos kraštas normalios histologinės struktūros.. 1(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.     2. SPENELIS: reaktyvi epidermio akantozė su bazinio sl. hiperpigmentacija, nežymi perivaskulinė limfocitinė infiltracija papilinėje dermoje.      I NAVIKAS (9 mm židinys): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", solidinės naviko struktūros, suformuotos mažai kohezyvių vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 3/10 DPRL.     II NAVIKAS (12 mm židinys): krūties audinyje, fibrozuotoje-elastozinėje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retokos duktalinės, kribriforminės, gausesnės trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 5/10 DPRL. Ryškios centrinės fibrozės zonos. Pavieniai mikrokalcifikatai. Perineurinis naviko plitimas. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija.     APLINKA: nedidelės zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais. Šalia II naviko - keli kribriforminiai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su apokrinės metaplazijos zonomis.   GILUSIS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 2. I NAVIKAS (blokas 13):  E-Cadherin: (+/++)(trūkinėjanti membr.citopl.r-ja)20%;   p120-catenin: (+++)(citopl.r-ja)100%;   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.   Progesterono receptoriai: stipri (+++) reakcija
answer:  100%

 15%|█▍        | 98/661 [02:43<16:45,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštas - skubus tyrimas - be naviko   2 ėminio aprašas: N2b kraštas - skubus tyrimas - be naviko   3 ėminio aprašas: N1: pašalintas dešinės krūties kvadrantas su vielute - planinis tyrimas  4 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - planinis tyrimas - pašalinti apie 6-7 kietoki, limfmazgiai, su įtrauktais aplinkiniais audiniais. 3. Krūties sektorius 8x5x4 cm su odos lopu 7,5x3,5 cm ir raumens fragmentu 1,8x1,5x0,2 cm,  žymėtas viela. Krūties audinyje pilkšvas, standus, spikulinių kraštų navikas 2x1,8x1,8 cm, nuo rezekcijos krašto(dažytas mėlynai)-(ties raumens fragmentu) nutolęs mažiau nei 0,1 cm, nuo odos 1,5 cm.    4. Riebalinio audinio fragmentai, bendras dydis 6x6x2 cm su 9 limfmazgiais iki 1 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 20 mm), pN2a(6/9 l/m), LVI2 (limfovaskulinis plitimas). Perineurinis naviko plitimas. Navikas nuo skersaruožio raumens rezekcijos krašto nutolęs per 1,2 mm. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).   4. Krūties duktalinės karcinomos metastazės šešiuose limfmazgiuose (6/9 l/m, 9,5 mm, ekstranodalinis plitimas).. 1. Krūties audinyje židininė fibrozė su negausiais dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.   2. Krūties audinys su negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Krūties audinyje, hialinizuotoje stromoje plinta navikas (20 mm mikroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių, trabekulinių ir tubulinių (15%) naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su vidutiniškai polimorfiškais, hiperchromiškais branduoliais su pavieniais paryškėjusiais branduolėliais. Mitozių navike iki 12/10DPRL. Limfovaskulinis plitimas smulkiose limfagyslėse/kraujagyslėse(LVI2). pPrineurinis naviko plitimas. Navikas nuo skersaruožio raumens rezekcijos krašto nutolęs per 1,2 mm. Krūties audinyje dilatuoti kanaliukai užpildyti solidinių ir kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais.   4. Šešiuose limfmazgiuose iš devynių (6/9 l/m) aukščiau aprašyto naviko metastazės iki 9,5 mm su ekstranodaliniu plitimu.. Blokas 10:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 15%|█▍        | 99/661 [02:44<16:29,  1.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 3 biopsiniai stulpeliai iš ploto su mkk dešinėje krūtyje  2 but. 2 biopsiniai stulpeliai iš spikulinės deformacijos židinio prasiplėtusiais latakais kairėje krūtyje, BI-RADS 4c. 1. 3 biopsiniai stulpeliai: I - 19 mm; II - 14 mm; III - 16 mm.  2. 2 biopsiniai stulpeliai: I - 10 mm; II - 12 mm.. Dešinė  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.  Aukšto laipsnio intraduktalinė karcinoma (DCIS; solidinė ir komedo).  --------------  Kairė  N2: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%, vietomis iki 30%.. Dešinė  N1: Krūties audinyje dilatuoti kanaliukai su intraduktaliniais solidiniais polimorfiškų ląstelių proliferatais, vietomis su centrinėmis nekrozėmis. Invazinis solidinis tokių pačių polimorfiškų ląstelių židinys stromoje, mitozių 2/10 DPRL.  --------------  Kairė  N2: Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi solidiniai/kribroziniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. nan
answer:  3a

 15%|█▌        | 100/661 [02:46<15:51,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 7 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.. Bioptate fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos lizdais besidėstančių ląstelių negausia-vidutinio gausumo eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 2/10 DPRL.. Navikas:  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  HER2: silpnas dalies membranos nusidažymas pavienėse ląstelėse.  Ki67 proliferacinis aktyvumas 10%.
answer:  1a

 15%|█▌        | 101/661 [02:48<16:40,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. Pjūvio kraštai, ekstra.   3. Sarginiai l/m, planinis.   4. Sektorius, planinis.. 3. Riebalinio audinio fragmentai, bendras dydis 5x3x1 cm. Rasti 3 limfmazgiai iki 2,5 cm.  4. Krūties sektorius 13x9x6 cm su oda 9x2 cm, žymėtas viela. Vielos projekcijoje, pjūvyje balkšvas, standus, neaiškių ribų navikas 0,6x0,5x0,5 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 1,3 cm, nuo odos – 3,5 cm.. 1(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); kalcifikatai; be naviko.   2(ekstra). "Kraštai": krūties lobulinė intraepitelinė neoplazija (LCIS).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 6 mm) N0(sn) (0/3 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    Krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: plokščias, papilinis tipai).  Krūties lobulinė intraepitelinė neoplazija (LCIS). Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).. 1(ekstra). "Kraštai": fokaliai nežymiai fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu; kalcifikatai; be naviko.   2(ekstra). "Kraštai": fokaliai nežymiai fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, apokrininės metaplazijos zonos. Zona su keletu dilatuotų lobulių, užpildytų nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais.   3(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retos duktalinės, dominuojančios trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo tamsoka citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki 5/10 DPRL. Pavieniai mikrokalcifikatai.   APLINKA: aplink naviką - keli dilatuoti kanaliukai su plokščiais ar kiek papiliarizuotais naviko ląstelių prolifetais; zonos su keletu dilatuotų lobulių, užpildytų nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).    SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 2(2b, ekstra). "Kraštai": E-Cadherin(-) intraduktaliniuose proliferatuose.  4. Navikas (34 blokas):   E-Cadherin(+) membraninė r-ja navike.   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stip
answer:  100%

 15%|█▌        | 102/661 [02:50<16:04,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 3 biopsiniai stulpeliai iš cistinio solidinio darinio  praplėstų latakų fone   2 but. 3 biopsiniai stulpeliai iš  izoechogeninio solidinio darinio šalia. 1. 3 biopsiniai stulpeliai: I - 9 mm; II - 8 mm; III - 9 mm.  2. 3 biopsiniai stulpeliai: I - 6 mm; II - 8 mm; III - 6 mm.. N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus ar vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.  N2: Krūties fibroadenoma.. N1: Krūties audinį infiltruoja juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozės pavienės.  Aplink naviką gausūs intraduktaliniai monomorfiškų ECAD negatyvių ląstelių proliferacijos židiniai (LIN/LCIS židiniai).  N2: Krūties audinyje mazgas iš fibroblastų stromos, suspaustų kanaliukų, išklotų dvieiliu epiteliu.. Navikas  Estrogenų receptoriai: stiprus ar vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas xx% naviko ląste
answer:  4%.

 16%|█▌        | 103/661 [02:51<16:16,  1.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1. Sarginiai l/n. - extra  N2. Kairė krūtis su naviku.. 2. Krūtis 836 gramų svorio, 20x16,5x8 cm, spenelio centras balkšvos spalvos. Krūties audinyje, viršutiniame lateraliniame kvadrante - pilkšvas, standus, neaiškių ribų navikas 22x20x18 mm, nuo odos nutolęs 1,9 cm, nuo giliojo rezekcijos krašto - 1 cm. Spenelio projekcijoje krūties audinys fibrozuotas 5x1,6 cm plote, kuris nuo giliojo rezekcijos krašto nutolęs 3 cm.. 1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).   2. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT2 (navikas 22 mm) N0(sn) (0/2 l/m), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcijos nėra (0).  Androgenų receptoriai: vidutinis branduolių nusidažymas 100% naviko ląstelių.    Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS: solidinis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta ir papilinė intraduktalinė hiperplazija, apokrininė metaplazija).   Krūties rezekcijos kraštas normalios histologinės struktūros.. 1(ekstra). "Sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2. SPENELIS: su nežymia reaktyvia epidermio hiperplazija ir akantoze, bazinio sluoksnio hiperpigmentacija.   NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta besiliejančios lizdinės ir solidinės, retos kribriforminės naviko struktūros, suformuotos ryškiai polimorfiškų ląstelių, vidutinio gausumo tamsoka citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro lobulizuotais ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki 30/10 DPRL. Naviko centre ryški fibrozė, hidropiniai pokyčiai, nedideli nekrozės židiniai. Limfovaskulinė naviko invazija smulkiose šakose.    APLINKA: šalia naviko - solidiniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su papilinių proliferatų formacija, apokrinės metaplazijos zonomis.   GILUSIS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 2. NAVIKAS (blokas 11):  HER2: reakcijos naviko ląstelių membranoje nėra.  Androgenų receptoriai: vidutinis branduolių nusidažymas 100% naviko ląstelių.  GATA3(+++)(brand.r-ja)100%; SOX-10(-); Synaptophysin(+++)(citopl.r-ja)3%.
answer:  0

 16%|█▌        | 104/661 [02:53<15:31,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: biopsijos iš kairės krūties. 2 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 8 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.. Krūties audinį infiltruoja susiliejantys kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  1a

 16%|█▌        | 105/661 [02:55<15:37,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra;  2(2b). Kraštai - extra;  3. Dešinės krūties sarginis l/m - extra;  4(1). Dešinės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 12x6x4,5 cm su oda 11x1,5 cm, žymėtas dažais. Krūties audinyje, kvadrante - pilkšvas, standus, neaiškių ribų navikas 20x16x12 mm, pereinantis į fibrozę nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 0,2 cm.. 1(2a) kraštai-ekstra: krūties fibrocistiniai pokyčiai. Naviko plitmo nėra.     2(2b) kraštai-ekstra: krūties fibrocistiniai pokyčiai. Naviko plitimo nėra.     3 sarginis l/m. Limfmazgis su sinusų histiocitoze, lipomatoze.     4(1) dešinės krūties kvadrantas.  Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma;  pT1c(16 mm) pN(sn)0 (0/1 l/m) pLVI-0 pR0.   Imunofenotipas (nustatytas priešoperaciniame biopsijos tyrime):   Estrogenų receptoriai: reakcija teigiama (stiprus branduolių nusidažymas 100% naviko ląstelių).  Progesterono receptoriai: reakcija teigiama (stiprus branduolių nusidažymas 100% naviko ląstelių).  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, solidinis tipas).. 1(2a) kraštai-ekstra: krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitmo nėra.   2(2b) kraštai-ekstra: krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   3 sarginis l/m. Limfmazgis (1) su sinusų histiocitoze, lipomatoze.   4(1) dešinės krūties kvadrantas.  Krūties audinyje, desmoplastiškoje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis grandinėlėmis, gausiomis trabekulinėmis struktūromis besidėstančių ląstelių negausia eozinofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių iki 18/10 DPRL.   Greta naviko gausūs dilatuoti latakai su intraduktalinėmis solidinėmis struktūromis iš analogiškų navikui ląstelių.. nan
answer:  1(

 16%|█▌        | 106/661 [02:56<15:51,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)-retroareoliariai - kraštai - be naviko   2(N2b)-retroareoliariai - kraštai - be naviko   3(N2c)-retroareoliariai - kraštai - be naviko   4(N1) - sektorius- planinis  patologinis tyrimas. N1- skubus rentgenis N1tyrimas- Mikrokalcinatai -17 mm plote  pašalinti. 4. Krūties sektorius 5,5x5,5x3,5 cm be odos. Krūties audinys fibrozuotas visame plote, fibrozėje neaiškių ribų pilkšvas, standus navikas 20x12x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm.. PAPILDYTA (HER2 FISH TYRIMAS):  1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Krūties audinys.  4. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(16 mm) pNX(limfmazgiai nešalinti, LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).  HER2 imuninė reakcija: ribinė (2+).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).   Krūties vidutinio ir žemo laipsnio duktalinė karcinoma in situ (DIN1c/DIN2/DCIS)(kribriforminė).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai bei lobulės, kloti dvisluoksniu epiteliu; fokalinis sekrecinis pokytis.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai bei lobulės, kloti dvisluoksniu epiteliu.  3(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai bei lobulės, kloti dvisluoksniu epiteliu.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 16 mm), suformuotas fibrozuotoje desmoplastiškoje stromoje plintančių kribriforminių ir besiliejančių liaukinių struktūrų, klotų ląstelėmis vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, skeltais, dalis su smulkia nukleole branduoliais. Mitozių iki 1/10 DPRL. Negausūs smulkūs mikrokalcifikatai. Aplink gan gausūs dilatuoti kanaliukai su kribriforminiais analogiškų navikui ląstelių proliferatais.. 4. Navikas (8 ir 10 blokai): invazyvios karcinomos struktūros be CK14+ mioepitelinio sl.; DCIS struktūrose išlaikytas mioepitelinis sl.  10 blokas: HER2 imuninė reakcija: silpnas/vidutinis dalies membranos nusidažymas 70% naviko ląstelių.
answer:  0

 16%|█▌        | 107/661 [02:58<16:09,  1.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. sektoriaus kraštai - extra;  2. sektoriaus kraštai - extra;  3. sarginiai l/m - extra.  4. Deš.krūties sektorius su naviku.. 4. Krūties sektorius 9,5x7x4 cm su oda 7x1,3 cm, žymėtas viela. Vielos projekcijoje - pilkšvas standus, neaiškių ribų navikas 24x16x14 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 5,2 cm.. 1(ekstra). Sektoriaus kraštai. Riebalinis fibrozinis audinys, be naviko plitimo.   2(ekstra). Sektoriaus kraštai. Krūties audinys be naviko plitimo.     3(ekstra). Sarginiai l/m. Reaktyvi limfadenopatija (1 l/m).     4. Dešinės krūties sektorius.   Krūties invazyvi vidutiniškai diferencijuota (G2, 6 b. pagal Nottingham sist.) duktalinė karcinoma,   pT2 (24 mm) pN0(sn)(0/1 l/m) pLVI-2 (invazija smulkiose gyslose) pR0(radikalus pašalinimas).   Naviko imunotipas nustatytas biopsiniame tyrime (B23-13987):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis, kribriforminis tipas).  Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija, apokrininė metaplazija.. 1(ekstra). Sektoriaus kraštai. Riebalinis fibrozinis audinys, be naviko plitimo.   2(ekstra). Sektoriaus kraštai. Riebalinis fibrozinis audinys su smulkiais latakėliais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   3(ekstra). Sarginiai l/m: 1 limfmazgis su I/II folikulais, sinusų histiocitoze, lipomatoze.  4. Deš.krūties sektorius. Krūties audinyje - 24 mm dydžio (mikroskopiškai) navikas, suformuotas lizdų, trabekulių, pavienių tubulių (<10%). Naviko ląstelės su vidutinio gausumo, šviesiai eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais fokaliai su smulkiomis nukleolėmis. Mitozių navike iki 2/10DPRL.   Naviko plitimas endotelizuotuose spindžiuose.   Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių, vietomis su komedonekroze spindžiuose.  Kituose kanaliukuose cistinė dilatacija, paprastoji intraduktalinė hiperplazija, apokrininė metaplazija.. nan
answer:  0,

 16%|█▋        | 108/661 [03:00<16:04,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1.dešinė krūtis, planinis. 2. sarginiai l/m, planinis.. 1. Krūtis 905 gramų svorio, 23x18x4,2 cm. Krūties audinyje, apatiniame lateraliniame kvadrante pilkšvas, neaiškių ribų, standus navikas 29x23x19 mm, esantis 0,5 cm nuo artimiausio rezekcijos krašto.   2. Riebalinio audinio fragmentas 4x3,5x1,2 cm. Rastas limfmazgis 1,4 cm.. N1: Krūties audinyje 29mm navikas iš trijų komponentų:  Intracistinė papilinė karcinoma (14mm, traktuojama kaip In situ karcinoma);  Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS, solidinė ir kribrozinė; 13mm);  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma (trys invazijos židiniai, didžiausias 6mm); pT1b.  Invazinis navikas:  estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių;  progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių;  Her2 imuninė reakcija: neigiama 1+;  Ki67+ 15%.  N2: Limfmazgis be naviko metastazių; pN0(sn).. N1: Krūties audinį gana aiškių ribų 14mm cistinis darinys su gausiomis papilinėmis struktūromis išklotomis neryškiai polimorfišku cilindriniu epitleiu be mioepitelinio sluoksnio nei papilinėse struktūrose, nei darinio periferijoje.  Aplink darinį 13mm ilgyje gausūs dilatuoti kanaliukai su intraduktaliniais solidiniais/kribroziniais neryškiai polimorfiškų ląstelių proliferatais.  Pirmajame navike ir jo periferijoje trys invazinio naviko židiniai (didžiausias 6mm): duktalinės struktūros, nedideli kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.  Operacinis pjūvis be naviko.  N2: Limfmazgis su reaktyviais pokyčiais, be naviko metastazių.. Invazinis navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių;  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių;  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.
answer:  3b

 16%|█▋        | 109/661 [03:02<15:54,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - skubus patologinis tyrimas- kraštai be naviko  2(N2B) - skubus patologinis tyrimas- kraštai be naviko  3(N3)- l/m-skubus  4(N1) - sektorius patologinis planinis   N1- skubus rentgeninis tyrimas - navikas pašalintas. 4. Krūties sektorius 9x4,5x4 cm su oda 8x3 cm, žymėtas viela. Vielos projekcijoje - pilkšvas, neaiškių ribų navikas 9x9x6 mm(sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 2 cm.. 1(Extra). Riebalinis audinys.  2(Extra). Riebalinis audinys.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma (g.b. iš solidinės papilinės karcinomos), SUMINIS TNM: pT1b(8 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).. 1(Extra). Brandus riebalinis audinys.  2(Extra). Brandus riebalinis audinys su neryškia fibroze.  3(Extra). 2 limfmazgiai su neryškia parakortekso hiperplazija ir sinusų histiocitoze.  4. Krūties audinyje, fibrozuotoje stromoje - ribotas navikas (mikroskopiškai 8 mm), suformuotas stambių lizdinių struktūrų (su smulkiomis fibrovaskulinėmis septomis) ir į periferiją plintančių smulkesnių lizdinių ir trabekulinių struktūrų iš ląstelių saikinga ar vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, smulkiais ir vidutinio kalibro, apvaliais/ovaliais, gan monomorfiškais, dalis skeltais ar su smulkia nukleole branduoliais. Mitozių iki 2/10 DPRL. Naviko atstumas nuo rezekcijos krašto 3 mm. Šalia zona su fibroze, makrofagais, siderofagais ir daugiabranduolėmis gigantinėmis ląstelėmis (biopsijos vieta?).. 4. Navikas (12 blokas): CK14+ mioepitelinio sluoksnio nėra.  Navikas (13 blokas): CK14+/SMA+ mioepitelinio sluoksnio nėra; Synaptophysin(+/+++)(citopl. r-ja), 5%; Chromogranin A(-).
answer:  1a

 17%|█▋        | 110/661 [03:03<15:37,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 16 G automatine biopsine adata punktuotas ~11x27 mm dydžio, netolygiai, iki ~3,8 mm akcentuotu žieviniu sluoksniu l/m dešiniosios pažasties I zonoje, paimti trys biopsiniai stulpeliai  histologijai (I buteliukas).   2 ėminio aprašas: 2. 16 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis (>50 mm), deformuoto liaukinio audinio plotas (atitinkantis MR tyrime k/m kiek labiau pakaupiantį plotą)  dešiniojoje krūtyje ties 10-11 val. vidurinėje/periferinėje dalyje daugiau prie krūtinės ląstos sienos, paimti keturi biopsiniai stulpeliai histologijai (II buteliukas).. 1. 3 biopsiniai stulpeliai: I - 15 mm; II - 8 mm; III - 10 mm.  2. 4 biopsiniai stulpeliai: I - 18 mm; II - 18 mm; III - 11 mm; IV - 12 mm.. N1: Duktalinės karcinomos metastazė limfmazgyje.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 30%.. N1: Žemiau aprašyto naviko metastazė limfmazgyje.  N2: Krūties audinį infiltruoja smulkūs solidiniai kompleksai, juostos iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.. Navikas (vertinta metastazės audinyje)  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% navik
answer:  0

 17%|█▋        | 111/661 [03:05<15:18,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas BI RADS 5 darinys kairėje krūtyje, paimti 3 biopsiniai stulpeliai medžiagos histologiniam ištyrimui  2 ėminio aprašas: punktuotas kair. pažasties l/m sustorėjusiu žieviniu sluoksniu, paimti 2 biopsiniai stulpeliai medžiagos histologiniam ištyrimui. 1. 3 biopsiniai stulpeliai: I - 10 mm; II - 12 mm; III - 11 mm.  2. 2 biopsiniai stulpeliai: I - 5 mm; II - 7 mm.. N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.  N2: Duktalinės karcinomos metastazės (navikinio audinio bioptatai, limfmazgio audinio nėra).. N1: Krūties audinį infiltruoja juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  N2: Aukščiau aprašyto navikinio audinio bioptatai (limfmazgio audinio gautoje medžiagoje nėra).. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 12
answer:  1.

 17%|█▋        | 112/661 [03:06<14:44,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 75% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros (20%), netaisyklingi kribroziniai ir solidiniai kompleksai bei trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 75% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 70%  naviko ląstelių membranoje.  Ki
answer:  1a

 17%|█▋        | 113/661 [03:08<14:38,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~16×18 mm dydžio darinys dešiniojoje krūtyje ties 12 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 15 mm; II - 12 mm; III - 11 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 30%.. Krūties audinį 3-se bioptatuose infiltruoja iki 12 mm :   - solidiniai kompleksai ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) necirkuliari reakcija, 20%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 30% naviko ląstelių.  Progesterono receptoriai: reakci
answer:  0.

 17%|█▋        | 114/661 [03:09<14:26,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 6 mm; III - 12 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė karcinoma, tikėtina duktalinė (navikas ECAD+).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja siauri šakoti solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ECAD pozityvių smulkių ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 2%.
answer:  1a

 17%|█▋        | 115/661 [03:11<14:40,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a) - viršutinis kraštas, skubu;  2(1b) - apatinis kraštas, skubu;  3(2) - sarginiai limfmazgiai, skubu;  4(3)- dex. sektorius, planinis.. 4(3). Krūties sektorius 5,5x4x2,5 cm, be odos, žymėtas viela. Pjūvyje, vielos projekcijoje - balkšvas, standus, neaiškių ribų navikas 16x10x9 mm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm.. 1(1a). Krūties audinys.  2(1b). Krūties fibrocistiniai pokyčiai. Intraduktalinė papiloma (0,3 cm).  3(2). Reaktyvi limfadenopatija (2 l/m).  4(3). Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,6 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės invazijos nėra). Krūties intraduktalinė papiloma (0,3 cm).     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.. 1(1a). Negausūs smulkūs kanaliukai riebaliniame audinyje.  2(1b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; kanaliukas su susiliejančiomis žemu stulpiniu, stulpiniu epiteliu išklotomis papilinėmis struktūromis spindyje (0,3 cm).  3(2). Nežymi sinusų histiocitozė dviejuose (2) limfmazgiuose.  4(3). Krūties audinyje - navikas: smulkias solidines, negausias kribrozines ar smulkias tubulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 3 / 10 DPRL.. 4(3). Navikas (17 blokas): Her2 nusidažiusių naviko ląstelių nėra; Ki67 5%.
answer:  0

 18%|█▊        | 116/661 [03:13<14:17,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 1-2%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 1-
answer:  1b

 18%|█▊        | 117/661 [03:14<14:00,  1.55s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 4 mm; II - 4 mm; III - 4 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 16%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai su pavieniais spindžiais iš ryškiai polimorfiškų ląstelių, mitozių iki 0-1/DPRL (navikinis židinys tik du regėjimo laukai).. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 40% naviko ląstel
answer:  3b

 18%|█▊        | 118/661 [03:16<14:00,  1.55s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 10 mm; III - 11 mm.. Invazinė duktalinė (kitaip neklasifikuojama)  karcinoma (mažiausiai iki 9 mm);  (G2; 6 b. pgl. Nottingham sist.) 2/3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 20%.. Krūties audinį 2/3-se bioptatuose infiltruoja iki 9 mm :   - solidiniai kompleksai;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 2/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 40%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 20% naviko ląstelių.  Progesterono receptoriai: stipri (+
answer:  90%

 18%|█▊        | 119/661 [03:17<14:33,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta dešinė krūtis planinis tyrimas  2 ėminio aprašas: N2: pašalintas dešinės krūties sarginis limfmazgis - planinis tyrimas. 1. Krūtis 1490 gramų svorio, 26x22x6 cm. Krūties audinyje:  - Apatiniame lateraliniame kvadrante pilkšvas, standus, neaiškių ribų I navikas 23x22x21 mm, nuo giliojo rezekcijos krašto nutolęs 4 cm, nuo odos - 1,7 cm;  - Medialiau pilkšvas, standus, neaiškių ribų II navikas 9x6x5 mm, nuo I naviko nutolęs 0,5 cm;  - Viršutinių kvadrantų riboje pilkšvas, standus, neaiškių ribų III navikas 11x7x5 mm, nuo giliojo rezekcijos krašto nutolęs 4,5 cm, nuo odos - 2,5 cm.   - Viršutiniame lateraliniame kvadrante pilkšvas, standus IV židinys 7x6x4 mm.  - Pilkšvas, standus, neaiškių ribų V navikas 4x4x3 mm.    Aplink navikus fibrozės zona 12x7x6 cm. 3,6 bloke zona virš I naviko žymėta juodais dažais, virš II naviko - mėlynais.    2. Riebalinio audinio fragmentai, bendras dydis 5x3,5x1 cm. Rasti 3 limfmazgiai, didžiausias 2,5 cm.. 1. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.2): pT2m(iki 4 naviko židinių, didžiausias 2,3 cm) pN1a(1/1 intramamarinis l/m + 1/3 sarginis l/m, didžiausia mts 0,6 cm). LVI2(limfovaskulinė naviko invazija, smulkiose struktūrose). R0(radikalus naviko pašalinimas).  2. Duktalinės adenokarcinomos mts 1/3 l/m (mts 0,5 cm).  ---  Estrogenų receptoriai: stipri branduolinė r-ja 100% naviko ląstelių.  Progesterono receptoriai: stipri branduolinė r-ja 100% naviko ląstelių.  HER2: silpnas dalies membranos nusidažymas 5% naviko ląstelių.  Ki67: iki 15%.. 1. KRŪTIES SPENELIS: Be patologijos.  KRŪTIS: Krūties audinyje - A) panašios histologinės ir citologinės išvaizdos keturi (4) naviko židiniai (trabekulines, kribrozines, susiliejančias tubulines naviko struktūras formuoja ląstelės su kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 12 / 10 DPRL), B) intramamarinis limfmazgis su aukščiau aprašyto naviko metastaze (iki 0,6 cm).  2. Aukščiau aprašyto naviko metastazė (iki 0,5 cm) viename (1) iš trijų (3) limfmazgyje.. nan
answer:  1a

 18%|█▊        | 120/661 [03:19<14:09,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinias stulpelis. Biopsinis stulpelis 15 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja pavienės duktalinės struktūros, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  1.

 18%|█▊        | 121/661 [03:21<14:34,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.   2(2b). Kraštai - skubus tyrimas - be naviko.  3. Dešinės pažasties sarginis limfmazgis - skubus tyrimas 2 l/m be naviko.  4(1). Pašalintas dešinės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 12x6x4 cm su odos lopu 9,5x2 cm. Pjūvyje balkšvas, standus, neaiškių ribų navikas 9x8x8 mm, nuo artimiausio rezekcijos krašto nutolęs 1,3 cm, nuo odos – 2 cm. Šalia naviko - fibrozės zona 4x4x2,5 cm, siekianti rezekcijos kraštą, nuo odos nutolusi 2,2 cm.. 1(2a). Fibrocistiniai krūties pokyčiai.  2(2b). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (2 l/m).  4(1). Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 11 mm), pN0(sn)(0/2 l/n), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).. 1(2a). Fibrozuotame krūties audinyje gausūs smulkūs bei dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar epiteliu su apokrinine epitelio metaplazija.  2(2b). Fibrozuotame krūties audinyje gausūs smulkūs bei dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  3. Du limfmazgiai su sinusų histiocitoze ir šerdies lipomatoze.  4(1). Krūties audinyje - navikas (11 mm mikroskopiškai), suformuotas tubulinių ir kribriforminių struktūrų iš vidutinio kalibro eozinofiline citoplazma ląstelių, nežymiai polimorfiškais, smulkiai grūdėtu chromatinu branduoliais; mitozių 3/10 DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Greta naviko negausūs dilatuoti kanaliukai su kribriformine proliferacija iš monomorfiškų, negausia šviesiai eozinofiline citoplazma ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta nežymiai dilatuoti kanaliukai kloti fokaliai hiperplastišku epiteliu.. Blokas 12:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 18%|█▊        | 122/661 [03:22<14:22,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. Kairė krūtis su limfmazgiais, planinis. Krūtis 885 g svorio, 20x18x5 cm, su pažasties narveliena 12x7x3 cm. Krūties audinyje, viršutiniame medialiniame kvadrante - pilkšvas gana aiškių ribų navikas 25x18x15 mm, esantis 2,5 cm nuo artimiausio/giliojo rezekcijos pjūvio, nuo odos 2 cm. Krūties audinyje fibrozės židiniai, kitųas navikinis židinys 1,1cm. Pažasties narvelienoje rasti 23 limfmazgiai, didžiausias 2,5 cm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2(m) (11mm ir 25mm); pN1a (1 iš 23 l/m; 25mm).. Krūties audinyje du navikiniai židiniai (11mm ir 25mm): nedideli solidiniai kompleksai ir trabekulės iš ryškiai polimorfiškų ląstelių, mitozių iki 18/10 DPRL. Nekrozės židiniai navike.  Iš rastų 23 limfmazgių vienas (1) su 25mm metastaze.. nan
answer:  1.

 19%|█▊        | 123/661 [03:24<14:02,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 fraqgmenituoti biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 10 mm; II - 6 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma su apokrininės diferenciacijos požymiais.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 8% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 20%.. Krūties audinį infiltruoja susiliejantys kribroziniai ir solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 14/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 8% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67+ 15%, v
answer:  0.

 19%|█▉        | 124/661 [03:25<14:33,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N3) dešinės pažasties sarginis limfmazgis - skubus tyrimas - 3 l/m be naviko  4(N1) pašalintas dešinės krūties kvadrantas planinis tyrimas. 4. Krūties sektorius 7x4x4 cm su odos lopu 5,5x2,2 cm. Krūties audinyje, pjūvyje pilkšvas, standus, neaiškių ribų navikas 17x15x15 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 1 cm.. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Krūties karcinomos mikrometastazė limfmazgyje (microMTS 1/3 l/m 1,6 mm)    4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma su mikropapilinės karcinomos komponentu,   SUMINIS TNM: pT1c(17 mm navikas) pN1mi(sn)(microMTS 1/3 l/m 1,6 mm) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija).  Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 kribriforminis ir papilinis tipai).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 60% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 40%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 1 iš 3 limfmazgių aprašyto naviko mikrometastazė 1,6 mm.     4. Krūtyje - navikas (17 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis struktūromis, lizdais ir mikropapilomis besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai - ryškiai polimorfiškais, nereguliaraus kontūro, ovaliais apvaliais, vezikulizuotais branduoliais ryškiomis nukleolėmis; mitozių 18/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių. Limfovaskulinė invazija.  Navikas, nuo sektoriaus rezekcijos krašto nutolęs 0,25 mm.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) ---- %.  Progesterono receptoriai: (+++)(brand. r-ja) ---- %.  HER2: silpnas/vidutinis/stiprus dalies/visos membranos nusidažymas xx% naviko ląstelių.  Ki67 proliferacinis aktyvumas ---- %.  CK5+ išlaiky
answer:  0%.

 19%|█▉        | 125/661 [03:27<14:31,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. punktuotas deš. krūties ties 12val. esantis židinys, paimti 3 stulpeliai medžiagos histologiniam ištyrimui (Nr. 1).   @#@#2. punktuotas kair. krūties ties 2-3val. esantis kalcifikuotas darinys, paimti 3 stulpeliai medžiagos histologiniam ištyrimui (Nr. 2).. 1. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 7 mm; III - 7 mm.  3. 3 fragmentuoti biopsiniai stulpeliai: I - 5 mm; II - 3 mm; III - 7 mm.. N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.  Krūties fibroadenoma.  N2: Krūties fibroadenoma.. N1: Krūties audinyje mazgas iš proliferuojančių fibroblastų stromos, suspaustų kanaliukų, išklotų dvieiliu epiteliu, vietomis su intrakanalikuliniais stromos proliferatais. Viename fragmente krūties audinį infiltruoja smulkios duktalinės struktūros, smulkūs netaisyklingi kribroziniai kompleksai ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  N1: Krūties audinyje mazgas iš proliferuojančių fibroblastų stromos, suspaustų kanaliukų, išklotų dvieiliu epiteliu, vietomis su intrakanalikuliniais stromos proliferatais. N1 navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67
answer:  15%.

 19%|█▉        | 126/661 [03:29<14:41,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas dešinės krūties žymėtas kvadrantas - planinis tyrimas  2 ėminio aprašas: N2a kraštai planinis tyrimas  3 ėminio aprašas: N2b kraštai - planinis tyrimas  4 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - planinis tyrimas. 1. Krūties sektorius 10,5x7x3,5 cm su odos lopu 9x4 cm, žymėtas viela. Vielos projekcijoje - pilkšvas, standus, neaiškių ribų navikas 13x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 1,2 cm, nuo odos - 1 cm.  2. Riebalinio audinio fragmentas 1,6x1,2x0,4 cm. v/m  3. Riebalinio audinio fragmentas 1x1x0,4 cm. v/m  4. Riebalinio audinio fragmentas 3x2,5x1 cm. Rasti 4 limfmazgiai iki 1 cm. v/m. 1. Krūties gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: T1c(14 mm navikas) pN1a(sn)(1/5 l/m MTS 4,4 mm) LVI-2(limfovaskulinė invazija).  R0(radikali rezekcija).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.    2. Krūties audinio fibrozė.  3. Krūties audinio fibrozė.  4. Duktalinės karcinomos metastazė limfmazgyje (1/4 l/m MTS 4,4 mm).. 1. Krūtyje - navikas (14 mm) infiltratyviu augimo frontu, suformuotas tubulinėmis, trabekulinėmis struktūromis ir pabirai besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais apvaliais; mitozių 3/10 DPRL.  Aplinkinis krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2. Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Riebalinis fibrozinis audinys.  4. 1 iš 4 limfmazgių aprašyto naviko metastazė 4,4 mm.. Navikas (11 blokas): Ecadherin(+++) membr. r-ja 90%; p120(+++) membr. r-ja 90%;
answer:  0.

 19%|█▉        | 127/661 [03:30<14:51,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 18 G automatine biopsine adata punktuotas hipoechogeninis ~10×8 mm dydžio deformacijos plotaskairiojoje krūtyje ties 2 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai (I buteliukas).   2 ėminio aprašas: 2. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais ~8×4 mm dydžio darinys kairiojoje krūtyje ties 1 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai (II buteliukas).   3 ėminio aprašas: 3. 18 G automatine biopsine adata punktuotas hipoechogeninis, gana aiškiomis ribomis su spikulėmis ~12×9 mm dydžio darinys dešiniojoje krūtyje ties 1 val. vidurinėje-periferinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai (III buteliukas).. 1. 3 biopsiniai stulpeliai: I -5 mm; II - 10 mm; III - 6 mm.  2. 3 biopsiniai stulpeliai: I - 11 mm; II - 9 mm; III - 7 mm.  3. 3 biopsiniai stulpeliai: I - 11 mm; II - 10 mm; III - 6 mm.. Kairė  N1-2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.  ----------  Dešinė  N3: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Kairė  N1-2: Krūties audinį infiltruoja duktalinės struktūros ir kribroziniai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL. Navikas visuose 6iuose biopsiniuose stulpeliuose.  ----------  Dešinė  N3: Krūties audinį infiltruoja duktalinės struktūros ir negausūs kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL. Navikas visuose 3uose biopsiniuose stulpeliuose. nan
answer:  1a

 19%|█▉        | 128/661 [03:32<14:26,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a   2. ėminio aprašas N2b kraštai  - skubus tyrimas be naviko   3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - skubus tyrimas 1 mts  4. (1) ėminio aprašas: pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 12x5,5x6 cm su oda 11x3 cm. Krūties audinyje, pilkšvas, neaiškių ribų standus navikas 17x15x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,5 cm.. N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(17mm).  N2ab: Krūties audinys be naviko.  N3: Limfmazgis (1 iš 2 l/m) su metastaze 4mm; pN1a(sn).. N1: Krūties audinyje 17mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.  N2ab: Krūties audinys be naviko.  N3: Limfmazgis (1 iš 2 l/m) su metastaze 4mm.. nan
answer:  0.

 20%|█▉        | 129/661 [03:34<15:04,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  ca mammae dex - extra  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4(3). pap. prie nr. 3 - ekstra  5(4). sektorius, planinis.   6(5). papildomas kraštas, planinis.. 5. Krūties sektorius 13,5x7,5x5,5 cm su oda 11,5x3 cm. Krūties audinyje - pilkšvas, standus, aiškių ribų navikas 25x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,2 cm. Rasti 4 limfmazgiai iki 1,3 cm.  6. Riebalinio audinio fragmentas 2,5x2x0,6 cm. v/m. 1. Krūties fibrocistiniai pokyčiai.   2. Krūties intraduktalinė papiloma. Atipinė duktalinė hiperplazija, fibrocistiniai pokyčiai.   3. Reaktyvi limfadenopatija (1 l/m).   4. Reaktyvi limfadenopatija (1 l/m).   5. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma su minimaliu(~5%) mikropapilinės karcinomos komponentu,   suminis Nr. 1 - 4 pTNM:   pT2 (25 mm) pN1mi(sn) (3/6 l/m, metastazės iki 1,2 mm); LVI2 (limfovaskulinė naviko invazija smulkiose kraujagyslėse/limfagyslėse).   Fibroadenoma.   6. Riebalinis audinys be patologinių pokyčių.. 1. Krūties audinio stroma ryškiai fibrozuota, su atrofiškomis lobulėmis, cistiškai dilatuotais latakais.   2. Krūties audinyje - grupė latakų su keliomis smulkiomis intraduktalinėmis papilinėmis struktūromis klotomis mioepitelinėmis ir duktalinėmis ląstelėmis, su ryškia netolygia hiperplazija, aplinkiniai latakai su stulpiniu epitelio pokyčiu ir apikalinės sekrecijos požymiais bei epitelio hiperplazija. Pora latakų su pavieniais, kiek monotoniškais kribriforminiais epitelio proliferatais dalyje latako spindžio.    3. Limfmazgis (1) tušuota architektūra, sinusų histiocitoze, stromos lipomatoze ir nežymia fibroze.  4. Limfmazgis (1) tušuota architektūra, sinusų histiocitoze, stromos lipomatoze ir nežymia fibroze.  5. Krūties audinyje - infiltratyviai plintantis navikas, formuojamas kompleksinių ir kribriforminių liaukinių, tubulinių, solidinių ir labai negausių mikropapilinių(~5%) struktūrų, sudarytų iš vidutinio dydžio kampuotų ląstelių šviesiai eozinofiliška citoplazma, vidutiniškai polimorfiškais ovoidiniais branduoliais su smulkiai grūdėtu chromatinu, ryškiomis nedidelėmis nukleolėmis. Navike iki 4 mitozių/ 10 DPRL. Limfovaskulinė naviko invazija smulkiose kraujagyslėse/limfagyslėse (LVI2).   Limfmazgiuose (3 iš 4) - aukščiau aprašyto naviko metastazės iki 1,2 mm.   Krūties audinyje - nedidelis aiškių ribų navikas, formuojamas kolagenizuotos stromos ir suspaustų kanaliukų.   6. Riebalinis audinys be patologinių pokyčių.. nan
answer:  0.

 20%|█▉        | 130/661 [03:35<14:40,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 4 biopsiniai stulpeliai. 4 biopsiniai stulpeliai: I - 15 mm; II - 11 mm; III - 12 mm; IV - 7 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G2; 6 b. pgl. Nottingham sist.) 4-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 10%.. Krūties audinį 4-se bioptatuose infiltruoja iki 13 mm :   - solidiniai kompleksai ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko
answer:  3b

 20%|█▉        | 131/661 [03:37<14:32,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. pjūvio kraštai, ekstra.   3. Sarginiai l/m, ekstra.   4. Sektorius, planinis.. 4. Krūties sektorius 14,5x9x5 cm su odos lopu 14x2 cm, su speneliu, pjūvyje užspenelinėje srityje balkšvas, standus, aiškių ribų navikas 2,4x1,7x1,2 cm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos – 3,2 cm.. 1. Kraštai. Krūties audinys be patologinių pokyčių.  2. Kraštai. Krūties audinys be patologinių pokyčių.  3. Sarginiai limfmazgiai: Limfmazgiai (4) be karcinomos ląstelių; pN0.  4. Kairės krūties sektorius.   Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT2(24 mm) pLVI-0 pR0.  Imunotipas nsutatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%. 1. Kraštai. Krūties audinys be patologinių pokyčių.  2. Kraštai. Krūties audinys be patologinių pokyčių.  3. Sarginiai limfmazgiai: Limfmazgiai (4) be karcinomos ląstelių.  4. Kairės krūties sektorius. Krūties audinį infiltruoja naviko susiliejančios duktalinės struktūros ir netaisyklingi kribroziniai/solidiniai  bei smulkūs pseudopapiliniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 14/10 DPRL.  Plitimo operaciniuose kraštuose ar kraujagyslėse nestebima.. EMA: vidutinis(++)/stiprus(+++) citoplazminis dažymasis 100% .
answer:  0

 20%|█▉        | 132/661 [03:39<15:02,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a kraštai - skubus tyrimas - be naviko  2. N2b kraštai - skubus tyrimas - be naviko   3. N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas - 3 l/m be naviko  4. N1. pašalintas dešinės krūties kvadrantas  - planinis tyrimas. 4. Krūties sektorius 11x5,5x6 cm, su odos lopu 10,5x3 cm. Krūties audinyje pilkšvas, ribotas, standus navikas 23x23x20 mm, nuo giliojo rezekcijos krato nutolęs 1,6 cm, nuo odos - 2,2 cm.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties-riebalinis audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties-riebalinis audinys su lėtine nespecifine uždegimine infiltracija; be naviko.   3(ekstra). "Dešinės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   4(1). Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT2 (navikas 23 mm) N0(sn) (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Naviko nekrozė iki 40%.   Imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcijos nėra (0).  Ki67: proliferacinis indeksas 50%.   GATA3(+)30%; SOX-10(+)99%.   Krūties sektoriaus rezekcijos kraštas normalios histologinės struktūros.. 1(2a, ekstra). "Kraštai": brandžių lipocitų suformuotas audinys su židinine fibroze, fokaliai retais kanaliukais, klotais dvisluoksniu epiteliu.   2(2b, ekstra). "Kraštai": brandžių lipocitų suformuotas audinys su židinine fibroze ir MMN infiltracija, fokaliai retais kanaliukais, klotais dvisluoksniu epiteliu.   3(ekstra). "Dešinės pažasties sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4(1). NAVIKAS: krūties audinyje - fibrozinio audinio juosta apribotas navikas, kurį sudaro besiliejančios lizdinės ir solidinės naviko struktūros su retais nedideliais spindžiais, suformuotos ryškiai polimorfiškų ląstelių, vidutinio gausumo tamsoka citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki ~30/10 DPRL. Naviko struktūrų centrinėse dalyse gausios nekrozės zonos (~40%) su PMN ("komedo" tipo piešinys). Naviko stroma infiltruota MMN.   APLINKA: visame krūties audinyje nedideli MMN suformuoti agregatai.   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 4(1). Navikas (blokas 15):   GATA3(+)(brand.r-ja)30%; SOX-10(+/+++)(brand.r-ja)99%.  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląst
answer:  0.

 20%|██        | 133/661 [03:41<14:57,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pašalinta  kairė krūtis - planinis tyrimas. Krūtis, 2023 gramų svorio, 20x20x7 cm dydžio. Odoje areolės srityje ir aplinkinėje odoje - 9x4 cm plote hematoma ir rusvos neaiškių ribų dėmės iki 0,4 cm. Krūties audinyje:  - centrinėje dalyje - balkšvas standus, neaiškių ribų I židinys 0,7x0,4x0,5 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 4 cm, nuo odos 1,5 cm.  - pilkšvas, neaiškių ribų II židinys 1,9x0,8x1,4 cm (sudėtas visas), nuo I židinio nutolęs 3 cm, nuo artimiausio rezekcijos krašto(dažytas mėlynu tušu) nutolęs 5 cm, nuo odos 1 cm.. Krūties vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma, pT1b (9 mm navikas) pLVI-2 (limfovaskulinė invazija smulkiose gyslose).   Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis, kribriforminis tipai). Paprastoji duktalinė hiperplazija. Intraduktalinė papiloma.  Radikalus pašalinimas.. Krūties audinyje du židiniai:    I židinys: Krūties audinyje - 9 mm dydžio (mikroskopiškai) navikas, suformuotas netaisyklingų solidinių kompleksų, iš ląstelių su gausia, šviesiai eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar ovoidiškais, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių navike iki 3/10DPRL. Šalia naviko stambūs kanaliukai su intraduktaliniais solidiniais ir kribriforminiais proliferatais iš analogiškų navikui ląstelių. Stromoje hemosiderofagai, putoti makrofagai, cholesterolio kristalus apsupančios svetimkūnio tipo daugiabranduolės gigantinės ląstelės, židininė fibrozė su suspaustais deformuotais kanaliukais, klotais dvisluoksniu epiteliu.    II židinys: krūties audinio fibrozė, stambūs latakai su intraduktaliniais solidiniais ir kribriforminiais proliferatais iš analogiškų I židinyje esantiems latakams ląstelių. Yra latakų su papiliniais ir kribriforminiais intraduktaliniais proliferatais, klotais dvisluoksniu epiteliu.. nan
answer:  1a

 20%|██        | 134/661 [03:42<14:20,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 bioptatai. 3 fragmentuoti biopsiniai stulpeliai: I - 15 mm; II - 17 mm; III - 13 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis iki 15%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 10
answer:  3b

 20%|██        | 135/661 [03:43<13:53,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 8 mm; II - 7 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.. Krūties audinį infiltruoja smulkios duktalinės struktūros, nedideli kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 2%.
answer:  1a

 21%|██        | 136/661 [03:45<13:52,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais policikliniais kontūrais, su UG fiksuojama kraujotaka, ~ 19x11 mm dydžio darinys dešiniojoje krūtyje ties 7 val. vidurinėje-periferinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 12 mm; II - 8 mm; III - 12 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+
answer:  30%

 21%|██        | 137/661 [03:47<13:46,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsy cores: I - 14 mm; II - 13 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja juostos iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 2%.
answer:  1a

 21%|██        | 138/661 [03:48<14:26,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)-kraštas-extra- DCIS   2.(N2b)-kraštas-extra - be naviko  3.(N2c)-nuo spenelio-extra - be naviko  4.(N3)- Sarginiai l/m(3)- be naviko   5.pap.kraštas-extra- be naviko  6.(N1) - pašalinas sektorius. -planinis patologinis tyrimas N1-skubus Ro tyrimas- navikas pašalintas.. 6. Krūties sektorius 6,5x6x4 cm, su odos lopu 6x3 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje tamsiai rudas, standus, ribotas navikas 16x15x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 2 cm. Visas sektorius žymėtas tušu.. 1(2a). Krūties žemo ir vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis, kribriforminis tipai).  2(2b). Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis tipas).  3(2c). Krūties audinys.    4. Reaktyvi limfadenopatija (4 l/m).  5(pap.). Krūties audinys.  6. Krūties invazyvi, vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham sis) karcinoma (kilusi iš solidinės papilinės karcinomos) su mucininės karcinomos diferenciacijos zonomis (~70% naviko), suminis tyrimo TNM: pT1c(navikas - 16mm) pN0(sn)(0/4 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).   IHC reakcijos atliktos VPC:B23-34296 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  Proliferacinis aktyvumas (Ki67+++, branduolinė r-ja): 5%.  CK5(-), CK14(-), Synaptophysin(++/+++)(citoplazminė r-ja), 90%."  Krūties žemo ir vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis, kribriforminis tipai).. 1(2a). Krūties audinyje - dilatuoti latakai su solidiniais ir kribriforminiais atipinių ląstelių (su žemo ir vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS).  2(2b). Krūties audinyje - pavieniai dilatuoti latakai su solidiniais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS).   3(2c). Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.    4. Keturi(4) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  5(pap.). Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  6. Krūties audinyje - navikas, formuojamas solidinių struktūrų su plonomis fibrovaskulinėmis septomis, ekstraląstelinių mucinų zonos su solidiniai naviko kompleksiais iš vidutinio kalibro ląstelių eozinofiliška/amfofiliška citoplazma, vidutiniškai polimorfiškais, hiperchromiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 10 mitozių/10 DPRL; aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais ir kribriforminiais atipinių ląstelių (su žemo ir vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS).. nan
answer:  1(

 21%|██        | 139/661 [03:50<14:06,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 14 mm.. Invazinė duktalinė (su apokrinine diferenciacija) karcinoma (mažiausiai iki 11 mm);  (G2; 7 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija paribinė (2+); nustatyta HER2 geno amplifikacija (žr. molekulinio tyrimo aprašymą).  Ki67: proliferacinis indeksas 20%.. Krūties audinį 1-me bioptate infiltruoja iki 11 mm :   - trabekulės;  - epitelinių vidutinio dydžio ir stambių ląstelių su vidutiniškai ir ryškiai polimorfiškais branduoliais su ryškiu branduolėliu gausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Androgenų receptoriai: stipri  teigiama (+++) branduolių reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: silpna (+) cirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67:
answer:  20%

 21%|██        | 140/661 [03:51<13:40,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 11 mm; II - 11 mm; III - 10 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) adenokarcinoma, tikėtina duktalinė.  Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 90%.  Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 80%.   HER2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 8%.. Smulkias solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 5 / 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 90%.  Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 80%.   HER2: nusidažiusių naviko ląstelių nėra.   Ki67: 8%.
answer:  3a

 21%|██▏       | 141/661 [03:53<14:15,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sarginiai l/m - extra;  2. Poareolinės zonos audiniai - extra;  3. Kairė krūtis, planinis.. 3. Krūties liauka 12,5x9,5x2 cm su 3 odos lopais, didžiausias 3x2 cm, žymėtas tušu. Krūties audinyje, didžiausio odos lopo projekcijoje - pilkšvas, standus, aiškių ribų I navikas 22x22x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 0,3 cm. Apatiniame lateraliniame kvadrante 1,5 cm atstumu nuo I naviko 17x15x10 mm nutolęs II pilkšvas standus navikas, nuo giliojo rezekcijos krašto 0,1 cm, nuo poodinio rezekcijos krašto 0,1 cm. Visas krūties audinys fibrozuotas su cistinėmis ertmėmis. Paruošti pjūviai Prosigna.  1(ekstra). Reaktyvi limfadenopatija (1 l/m).  2(ekstra). Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai pokyčiai: parastoji intraduktalinė hiperplazija.  3. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(m)(25 mm, 10 mm navikai) pN0(sn)(0/1 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).  Lobulinė karcinoma in situ (LCIS).     Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%.. 1(ekstra). 1 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu ir hiperplastišku epiteliu su apokrinine metaplazija. Dilatuoti latakai ir lobulės su intraduktaliniais solidiniais proliferatais iš ląstelių monomorfiškais branduoliais.    3. Krūtyje - navikas (25 mm, 10 mm) infiltratyviu ekspansyviu augimo frontu,trabekulinėmis struktūromis, lizdais, grandinėlėmis ir pabirai besidėstančių ląstelių negausia eozinofiliška citoplazma, vidutiniais - stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 5/10 DPRL.  navikas nuo giliojo rezekcijos krašto nutolęs 1 mm.  Greta dilatuoti kanaliukai su intraduktaliniais solidiniais proliferatais iš analogiškų navikui ląstelių.  Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaus kanaliukų zonos.. nan
answer:  3.

 21%|██▏       | 142/661 [03:55<14:12,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu  3(2). Deš. pažasties sarginiai limfmazgiai, skubu  4(3). Deš. krūties sektorius, planinis. 4. Krūties sektorius 9x5x5,5 cm su odos lopu 8x3 cm. Krūties audinyje, pjūvyje pilkšvas, standus, neaiškių ribų navikas 20x18x15 mm, nuo gilijo rezekcijos krašto nutolęs 0,9 cm, nuo odos - 1 cm.. 1(Extra). Krūties audinys.  2(Extra). Riebalinis audinys.  3(Extra). Krūties duktalinės karcinomos metastazė 1/3 l/m (4,5 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(20 mm) N(sn)1a(mts 1/3 l/m: 4,5 mm), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - įvairaus kalibro ir kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu; negausi židininė MMN infiltracija.  2(Extra). Brandus riebalinis audinys su neryškia fibroze.  3(Extra). 1 iš 3 limfmazgių - žemiau (Nr.4) aprašyto naviko metastazė (4,5 mm).  4. Krūties audinyje - navikas (mikroskopiškai 20 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių lizdinių, trabekulinių ir pavienių (iki 5%) tubulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 5/10 DPRL. Limfovaskulinė invazija.  Žymėtas rezekcijos kraštas - be naviko plitimo.. 1. 1 blokas: kanaliukai su CK14+ mioepiteliniu sluoksniu, ER+ luminalinis sluoksnis.
answer:  1(

 22%|██▏       | 143/661 [03:56<13:54,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: stiklai peržiūrai. Konsultacijai gauta:  - 1 parafino blokas (žymėtas H4090-23);  - 6 histologiniai preparatai (žymėti analogišku numeriu, dažyti HE; E-CAD; PRG ; ER; Her2; Ki-67, xx, xx, xx metodais).    stiklai peržiūrai. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 5%.. Bioptatuose (4/4) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, grandinėlėmis ir pabirai besidėstančių ląstelių negausia eozinofiliška citoplazma, nežymiai polimorfiškais, vidutinio kalibro, ovalaus kontūro branduoliais; mitozių 1/10 DPRL.. VPC imunohistocheminiai dažymai:  HER2: silpnas dalies membranos nusidažymas 10% naviko ląstelių.    KMUK/LSMU imunohistocheminiai dažymai:  Estrogenų receptoriai: (+++) brand. r-ja 100%.  Progesterono receptoriai: (+++) brand. r-ja 100%.  Her2: silpnas d
answer:  10%

 22%|██▏       | 144/661 [03:58<14:16,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštai - skubus tyrimas  2 ėminio aprašas: N2b kraštai - skubus tyrimas  3 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas  4 ėminio aprašas: N1: pašalintas dešinės krūties kvadrantas - planinis tyrimas  5 ėminio aprašas: N3: papildomai įtartini limfmazgiai - planinis tyrimas. 4. Krūties sektorius 13,5x9x5,5 cm su oda 12,5x5 cm. Krūties audinyje, pilkšvas, standus, skiltėtas navikas 32x30x26 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,2 cm.   5. Riebalinio audinio fragmentas 3x3x1,5 cm. Rasti 2 limfmazgiai iki 1,5 cm. v/m. 1(2a)(Extra). Riebalinis audinys.  2(2b)(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi blogai diferencijuota (G3; 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(32 mm) N(sn)0(0/3 l/m), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas (naviko atstumas nuo rezekcijos krašto 0,6 mm).  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   5. Reaktyvi limfadenopatija (2 l/m).. 1(2a)(Extra). Brandus riebalinis audinys su neryškia fibroze.  2(2b)(Extra). Krūties audinyje - negausūs vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 1 limfmazgis su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze.  4. Krūties audinyje - ribotas navikas, suformuotas fibrozuotoje stromoje plintančių lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais ir nereguliariais, gan polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 35/10 DPRL. Perinavikinė limfocitų infiltracija. Limfovaskulinė invazija smulkiose šakose. Mažiausias naviko atstumas nuo rezekcijos krašto 0,6 mm.  5. 2 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.. nan
answer:  0

 22%|██▏       | 145/661 [04:00<13:48,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros ir smulkūs solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67+ 8%
answer:  1b

 22%|██▏       | 146/661 [04:02<14:46,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. Kairė krūtis su limfmazgaiais, planinis. Krūtis 1430 g svorio, 22x19,5x6 cm, su pažasties narveliena 14x13x4,5 cm. Krūties audinyje:  - medialiniame viršutiniame kvadrante balkšvas standus neaiškių ribų I navikas 18x13x12 mm, esantis 3 cm nuo giliojo rezekcijos pjūvio, nuo odos 4 cm.   - 0,5 cm atstumu balkšvas, standus, aiškių ribų II navikas 7x5x4 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 4,5 cm, nuo odos 3,5 cm.   - Nuo I naviko 11 cm atstumu balkšvas standus neaiškių ribų III navikas 15x13x9 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 4,5 cm, nuo odos - 2 cm.   Bendrai pirmi trys navikai išsidėsto 4,5x3x3 cm plote.   - Lateraliniame apatiniame kvadrante pilkšvas, standus IV navikas 21x11x10 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 4,5 cm.   - Lateraliniame viršutiniame kvadrante fibrozės zona 2,5x1,5x3,3 cm su paryškėjusiu aplinkiniu audiniu.   Pažasties narvelienoje rasta 16 limfmazgių, didžiausias 3,5 cm.. Krūties multižidininė duktalinė karcinoma su dviem morfologiniais variantais:   A. I, II, III židiniai:   Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma (kitaip neklasifikuotina).   Naviko imunotipas nustatytas biopsijoje (B23-4490):   Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 12%.    B. IV-tas židinys:   krūties invazyvi vidutiniškai diferencijuota (G2, 7 b. pgl. Nottingham sist.) duktalinė karcinoma (šviesių ląstelių variantas).  Naviko imunotipas:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacijos FISH tyrimo rezultatas laikytinas TEIGIAMU (interpretuojamas HER2 IHC tyrimo kontekste; žr. molekulinio tyrimo aprašymą ir pastabas).    Suminis TNM:   pT(m)2 (21 mm, 18 mm, 15 mm, 7mm naviko židiniai)   pN1a(1/16 l/m su mts iki 8,3 mm)   pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pR0(radikalus pašalinimas).. Spenelis: be patologijos.    Krūties audinyje - trys (I-III) morfologiškai panašūs naviko židiniai ir vienas (IV-as) morfologiškai išsiskiriantis navikas:   I, II, III naviko židiniai suformuoti lizdų, trabekulių, grandinėlių ir pabirų ląstelių. Naviko ląstelės su vidutinio gausumo tamsia eozinofiliška citoplazma, vidutinio kalibro ar stambiais, ryškiai polimorfiškais branduoliais su smulkiai grūdėtu chromatinu ir ryškiomis nukleolėmis. Mitozių I navike iki 16/10DPRL. II navike - iki 10/10DPRL, III navike - iki 23/10DPRL. Naviko plitimas endotelizuotuose spindžiuose (šalia I ir II židinių).     IV navikas: solidinės struktūros ir lizdai iš ląstelių gausoka šviesia citoplazma su PAS+ granulėmis, apvaliais, vidutiniškai polimorfiškais branduoliais smulkiai grūdėtu chromatinu ir aiškiomis nukleolėmis. Mitozių navike iki  9/10 DPRL. Šalia yra latakų su solidiniais intraduktaliniais proliferatais iš IV navikui analogiškų ląstelių.    Aplinkiniuose latakuose cistinė dilatacija, apokrininė metaplazija, įprastinė duktalinė hiperplazija.    Limfmazgiai: 1-me/16 limfmazgių - I/II/III navikams analogiškos struktūros iki 8,3 mm; ekstranodulinio plitimo nestebima.. Blokas 12:  CK14: mioepitelinio išklojimo invazyviose naviko struktūrose nėra.  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) cirkuliari reakcija, 40%  naviko ląstelių membranoje.  Synaptophysin: neigi
answer:  0.

 22%|██▏       | 147/661 [04:03<14:38,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.  2(2b). Kraštai - skubus tyrimas - be naviko.  3. Dešinės pažasties sarginis limfmazgis - skubus tyrimas 3 l/m be naviko.  4(1). Pašalintas dešinės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 7,5x3,5x3,5 cm su oda 6x3 cm. Krūties audinyje, kvadrante - pilkšvas, standus, aiškių ribų navikas 22x18x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 1 cm.. 1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (3 l/m).  4(1). Krūties invazyvi blogai diferencijuota (G3; 9 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 18 mm), pN0(sn)(0/3 l/m), LVI2(limfovaskulinis plitimas). Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS). R0(radikali rezekcija). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).. 1(2a). Krūties audinyje smulkūs ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  2(2b). Krūties audinyje gausios lobulės, klotos dvisluoksniu epiteliu.  3. Trys limfmazgiai su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.  4(1). Krūties audinyje, hialinizuotoje stromoje plinta navikas (18 mm) infiltratyviu augimo frontu. Navikas suformuotas solidinių, trabekulinių ir negausių tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su ryškiai polimorfiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 44/10DPRL. Limfovaskulinis plitimas smulkiose limfagyslėse/kraujagyslėse(LVI2). Greta naviko gausūs dilatuoti kanaliukai užpildyti solidinių ir kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais; dalies proliferatų centruose - nekrozės zonos.. Blokas 12:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 22%|██▏       | 148/661 [04:05<14:00,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas:   1-2. pjūvio kraštai, ekstra.  3. sarginiai l/m, ekstra.  4. sektorius. ekstra. 4. Krūties sektorius 11,5x5,5x6,5 cm su oda 10x2,5 cm. Krūties audinyje, pilkšvas, standus, aiškių ribų navikas 20x15x15 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 1,5 cm.. N1-2: Krūties audinys be naviko.  N3: Limfmazgiai (2 l/m) be naviko; pN0(sn).  N4: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pN1c(20mm).. N1-2: Krūties audinys be naviko.  N3: Limfmazgiai (2 l/m) be naviko.  N4: Krūties audinyje 20mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. nan
answer:  1.

 23%|██▎       | 149/661 [04:06<13:33,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 8 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10-12%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  1a

 23%|██▎       | 150/661 [04:08<14:33,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2) - retroareoliarinė sritis- be naviko   2(N3) - sarginai - be naviko (3)   3(N1) - pašalinta krūtis  - planinis patologinis tyrimas N1 - skubus rentgeninis tyrimas- navikas pašalintas. 3. Krūtis liauka 535 svorio, 19,5x16,5x3 cm su odos lopu 10,5x6 cm. Pjūvyje 2 balkšvi, standūs naviko židiniai: I - 1,1x1x1 cm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 2,3 cm, II - 0,9x0,6x0,5 cm, nuo I-ojo židinio nutolęs 1,5 cm, nuo giliojo rezekcijos krašto - 1 cm, nuo odos - 2,5 cm.. 1. Atipinė lobulinė hiperplazija (ALH; intraduktalinis plitimas). Fibrocistiniai krūties pokyčiai.  2. Reaktyvi limfadenopatija (3 l/m).  3. Multižidininė krūties karcinoma: invazyvi, vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham sis) duktalinė karcinoma (židinys - 10,9mm) ir invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham sis) lobulinė karcinomos (židinys - 12,2mm), suminis tyrimo TNM: pT1c(m)(du naviko židiniai: 10,9mm ir 12,2mm); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).   Duktalinė krūties karcinoma:  Estrogenų receptoriai: reakcija teigiama (stipri branduolių r-ja, 100% naviko ląstelių).   Progesterono receptoriai: reakcija teigiama (vidutinė/stipri branduolių r-ja, 95% naviko ląstelių).   HER2: žema imunohistocheminė raiška (1+).   Ki67 proliferacinis aktyvumas ~10%.  Lobulinė krūties karcinoma (IHC reakcijos atliktos VPC:B23-44687 tyrime):   "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 5%, vietomis iki 10%."  Lobulinė krūties karcinoma in situ (LCIS). Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; kribriforminis, solidinis tipas; -komedo tipo nekrozės). Rezekcijos kraštas be naviko.. 1. Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu; pavieniai latakėliai su negausiu pedžetoidiniu smulkių, monotoniškų (E-cadherin(-)) ląstelių plitimu.  2. Trys(3) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  3. Krūties audinyje - du naviko židiniai: I) (mikro: 12,2mm)formuojamas difuziškai bei trabekulėmis besidėstančių vidutinio kalibro ląstelių, eozinofiliška citoplazma, nežymiai polimorfiškais branduoliais su fokaliai išryškėjusiomis nukleolėmis; navike iki 5 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS). Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse. II) (mikro: 10,9mm) formuojamas solidinių/lizdinių, trabekulinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai, vietomis ryškiai polimorfiškais, hiperchromiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 2 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais ir kribriforminiais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS). Rezekcijos kraštas be naviko.. Blokas 1:  ALH: E-Cadherin(-).   Blokas 19:  II navikas:  Estrogenų receptoriai: stipri branduolių r-ja, 100% naviko ląstelių.   Progesterono receptoriai: vidutinė/stipri branduolių r-ja, 95% naviko ląstelių.   HER2: silpna/vidutinė dalies membranos reakc
answer:  1+

 23%|██▎       | 151/661 [04:10<14:02,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm ilgio.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.. Krūties audinį infiltruoja netaisyklingi kribroziniai kompleksai iš vidutiniškai ir ryškiai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis visos membranos nusidažymas 20% naviko ląstel
answer:  2b

 23%|██▎       | 152/661 [04:11<13:44,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 bioptatai 22 mm 14 G adata, kalcinatų juose nematyti. 3 fragmentuoti biopsiniai stulpeliai: I - 17 mm; II - 8 mm; III - 7 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė tubulinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 98% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 4%.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).. Krūties audinį infiltruoja duktalinės struktūros (100%) iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.  Šalia naviko latakai su kribriforminiais proliferatais iš navikui analogiškų ląstelių.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 98% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 90%  naviko ląstelių membranoje (pamatinėse dalyse).  Ki67: reakcija branduoliuose, 4% naviko ląstelių.  Progesterono rece
answer:  100%

 23%|██▎       | 153/661 [04:13<13:20,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biospiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 11 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 5%.. Krūties audinį infiltruoja juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 30% naviko ląstelių.  Ki67+
answer:  5%

 23%|██▎       | 154/661 [04:14<13:03,  1.55s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 9 mm; II - 8 mm; III - 9 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai/solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+ 12
answer:  1b

 23%|██▎       | 155/661 [04:16<12:50,  1.52s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 10 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%.. Krūties audinį infiltruoja nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai ir vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67+ 25
answer:  2b

 24%|██▎       | 156/661 [04:18<13:18,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sarginiai limfmazgiai - extra.   2. Dešinė krūtis su navikais - planinis tyrimas.. 2. Krūtis 581 gramų svorio, 19x17,5x7 cm. Krūties audinyje, vidurinėje dalyje pilkšvas, standus, neaiškių ribų navikas 10x9x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 0,8 cm. Krūties krašte audinys fibrozuotas 6,5x2,5 cm plote. Fibrozėje rusvas, neaiškių ribų židinys 9x9x4 mm, nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo odos - 1,4 cm. Spenelio projekcijoje neaiškių ribų, sustandėjimai iki 6 mm.. 1(Extra). Reaktyvi limfadenopatija (4 l/m).  2. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(10 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Židininė krūties audinio fibrozė ir fibrocistiniai pokyčiai: stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. 1(Extra). 4 limfmazgiai su fokaline parakortekso hiperplazija, sinusų histiocitoze ir neryškia lipomatoze.  2. SPENELIS: normali histologinė struktūra.  NAVIKAS: krūties audinyje - navikas (mikroskopiškai 10 mm), suformuotas fibrozuotoje stromoje ir tarp lipocitų infiltratyviai plintančių lizdinių ir trabekulinių struktūrų bei pabirai ar grandinėlėmis besidėstančių ląstelių saikinga ar vidutinio gausumo švelniai eozinofiliška citoplazma, smulkiais ir vidutinio kalibro, apvaliais/ovaliais, gan monomorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 2/10 DPRL. Šalia kiek dilatuoti kanaliukai su analogiškomis navikui ląstelėmis.  Aplink plačios mažai ląstelingos fibrozės zonos su dilatuotais kanaliukais, klotais suplokštėjusiu epiteliu, ar su stulpiniu ląstelių pokyčiu su apikalinės sekrecijos požymiais (CCAPSS); yra zonų su hemoragijomis, MMN ir makrofagų ar siderofagų židiniais (biopsijos vieta).. nan
answer:  1a

 24%|██▍       | 157/661 [04:19<13:41,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas kairės krūties kvadrnatas - planinis tyrimas  2 ėminio aprašas: N2a kraštai  3 ėminio aprašas: N2b kraštai   4 ėminio aprašas: N3: kairės pažasties sarginiai limfmazgiai  5 ėminio aprašas: N4: papildomas kraštas - planinis tyrimas. 1. Krūties sektorius 7,5x5,5x4,2 cm be odos. Pjūvyje neaiškių ribų, rusvas, standus navikas 22x20x18 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm.  2. Riebalinio audinio fragmentas 2x2x0,5 cm. v/m  3. Riebalinio audinio fragmentas 2x1x0,5 cm. v/m  4. Riebalinio audinio fragmentai, bendras dydis 3,5x3,5x1 cm. Rasti 4 limfmazgiai iki 1,4 cm. v/m  5. Riebalinio audinio fragmentas 1,6x1,6x0,6 cm. v/m. 1. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma;   pT2(28 mm) pLVI-0 pN0(0/4).  Imunotipas (pirminis, pagal klinikinius duomenis):  ER imuninė reakcija neigiama.   PR imuninė reakcija teigiama (silpnas branduolių nusidažymas apie 3% navikinių ląstelių).   Reakcija su HER2 neigiama (1+).    Pakartotas/papildytas (operacinėje medžiagoje):  Estrogenų receptoriai: reakcijos nėra.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 50%.    2. Krūties audinys be patologinių pokyčių.  3. Krūties audinys be patologinių pokyčių.  4. Limfmazgiai(4) be patologinių pokyčių.  5. Krūties audinys be patologinių pokyčių.. 1. Solidines, tinklines ir gausias pseudoliaukines (be spindžių) naviko struktūras formuoja ląstelės su negausia saikingai eozinofiline citoplazma, vidutinio dydžio apvalios formos vidutiniškai polimorfiškais branduoliais; mitozių navike >30 / 10 DPRL. Navikas ties giliuoju operaciniu kraštu.  Intravaskulinio plitimo nestebima.  2. Krūties audinys be patologinių pokyčių.  3. Krūties audinys be patologinių pokyčių.  4. Limfmazgiai(4) be patologinių pokyčių.  5. Krūties audinys be patologinių pokyčių.. Blokas 2:  CD117: neigiama (-) atipinėse struktūrose  CK5: neigiama (-) atipinių ląstelių membranoje  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  GATA3: vidutinė ir stipri reakcija 100 proc. atipinių ląstelių branduoliuose  HER2:
answer:  1+

 24%|██▍       | 158/661 [04:21<13:34,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~27x20 mm dydžio darinys kairiojoje krūtyje ties 11-2 val. centrinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 11 mm; II - 15 mm; III - 17 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.  .  Progesterono receptoriai: stipri reakcija 90% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.. Bioptatuose (3/3) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos lizdais, grandinėlėmis ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 5/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 90%.  HER2: nusidažiusių naviko ląstelių nėra.  Ki67 proliferacinis aktyvumas 20%.  E-cadherin(+++) membr. r-ja 100%.
answer:  1 �

 24%|██▍       | 159/661 [04:23<15:34,  1.86s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Tyrimo Nr. XXIIIBO-2930. Sarginio limfmazgio biopsija + quadrantectomia. Krūties navikas. Makroskopinis aprašymas: Krūties audinio 6x4,8x3,6 cm, iš vienos pusės žymėta tušu. Pjūvyje riebalinis, fibrozinis audinys. Fibrozinis audinys netaisyklingos formos, susiliejantis.  (1,2,3,4),(5,6,7,8) - pjūvis, (9,10),(11,12) - šoniniai kraštai, 13 - iš židinio.. Konsultacijai gauta:  - 4 parafino blokai (žymėti "XXIIIBO-2907"  1-4);  - 7 histologiniai preparatai (žymėti "XXIIIBO-2907", dažyti HE metodu).  - 1 parafino blokas (žymėtas "XXIIIBO 2416");  - 5 histologiniai preparatai, žymėti "XXIIIBO 2416", dažyti HE; ER; PR; Her2; Ki-67 metodais;  - 13 parafino blokų, žymėtų "XXIIIBO-2930" (nuo 1 iki 13);  - 17 histologinių preparatų, žymėtų "XXIIIBO-2930" (nuo 1 iki 13), dažytų HE; PR; ER; Ki-67; Her2 metodais.  Pilnai konsultacijai.. PAPILDYTA  "XXIIIBO-2907" (keturi blokai; limfmazgiai)  Reaktyvi limfadenopatija (galimai 3 l/m).  "XXIIIBO-2416" (vienas blokas; krūties naviko biopsija)  Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma.  "XXIIIBO-2930" (trylika blokų; krūties sektorius)  Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma, ne mažiau kaip pT1c(ne mažiau kaip 1,8 cm) pN(sn)0 (0/3 l/m). LVI2(limfovaskulinė naviko invazija, pavienėse smulkiose struktūrose).  Her2 imunohistocheminė reakcija ribinė (2+).     Nustatyta HER2 geno amplifikacija navike (žr. molekulinio tyrimo aprašymą).. XXIIIBO-2907 (keturi blokai; limfmazgiai)  Nežymi sinusų histiocitozė, minimali lipomatozė limfmazgiuose (galimai trijuose).  "XXIIIBO-2416" (vienas blokas; krūties naviko biopsija)  Krūties audinyje - navikas (smulkias solidines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne blyškiai eozinofiline ar amfofiline  citoplazma, vidutinio kalibro apvalios formos netaisyklingais/polimorfiškais branduoliais; mitozių navike ne mažiau 18 / 10 DPRL.  "XXIIIBO-2930" (trylika blokų; krūties sektorius)  Krūties audinyje - navikas (smulkias ar stambesnes solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne blyškiai eozinofiline ar amfofiline  citoplazma, vidutinio kalibro apvalios formos netaisyklingais/polimorfiškais branduoliais; negausios zonos su pabirai plintančiomis ląstelėmis; mitozių navike iki 22 / 10 DPRL; vidutinio kalibro ar stambūs kanaliukai (su solidiniais analogiškų atipinių ląstelių proliferatais spindžiuose, nekrotinis detritas dalies kanaliukų spindžiuose) navike; naviko struktūros dalyje koaguliuotų kraštų; didžiausias naviko matmuo parafino blokuose: iki 1,8 cm (bendras naviko skersmuo tikėtina didesnis: derinti su makroskopiniu tyrimu); kelios smulkios kraujagyslės/limfagyslės su naviko struktūromis spindžiuose.. XXIIIBO-2416 ( krūties naviko biopsija)  Originalūs stiklai  Estrogenų receptoriai: stiprus-vidutinis branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus-vidutinis branduolių nusidažymas 70% naviko ląstelių.  Her2 imuninė reakci
answer:  1+

 24%|██▍       | 160/661 [04:25<14:57,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 9 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6 mm);  (G2; 6 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 8%.. Navikinį audinį 1-me bioptate infiltruoja iki 6 mm :   - netaisyklingi kribroziniai kompleksai ir trabekulės;  - epitelinių smulkių ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 8% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  100%

 24%|██▍       | 161/661 [04:27<14:42,  1.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 13 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G1 ; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: vidutinė (++) reakcija, 30% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija paribinė (2+); nustatyta HER2 geno amplifikacija (žr. molekulinio tyrimo aprašymą).  Ki67: proliferacinis indeksas 10%. Karštame taške 30%.  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas).. Krūties audinį 2-se bioptatuose infiltruoja iki 11 mm :   - duktalinės struktūros (30% viso naviko), netaisyklingos kribriforminės struktūros, trabekulės;  - epitelinių vidutinio dydžio ląstelių su netolygaus kontūro, hiperchromiškais, vidutiniškai polimorfiškais branduoliais su pavienėmis nukleolėmis negausioje amfofiliškoje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.  Šalia - kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių, su mikrokalcifikatais ir nekrotiniu detritu spindžiuose.. Blokas 1:  CK14: silpna (+), galimai foninė reakcija 100% naviko ląstelių citoplazmoje. CK14+ mioepitelinis sluoksnis išlaikytas DCIS struktūrose.  Estrogenų receptoriai: vidutinė (++) reakcija, 30% naviko ląstelių branduoliuose.  HER2: vidutinė (++) neci
answer:  30%

 25%|██▍       | 162/661 [04:28<14:36,  1.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1  - sarginiai l/m (ekstra)  2 - deš.krūtis (planiškai). 2. Krūtis 1099 gramų svorio, 27x21x6,5 cm.  Krūties audinyje, apatiniame lateraliniame kvadrante balkšvas, standus, neaiškių ribų  navikas 45x29x25 mm, nuo odos nutolęs 1 cm, nuo giliojo rezekcijos krašto - 1,7 cm.. 1. Reaktyvi limfadenopatija (3 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma, TNM (Nr.1-Nr.2): pT2(~4 cm, mikroskopiškai) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės invazijos nėra). R0(radikalus naviko pašalinimas).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5%.. 1. Nežymi sinusų histiocitozė trijuose (3) limfmazgiuose.  2. KRŪTIES SPENELIS: Be patologijos.  KRŪTIS: Krūties audinyje - navikas (grandinėlėmis, trabekulėmis besidėstančios ląstelės su negausia ar kiek gausesne blyškiai eozinofiline citoplazma, vidutinio kalibro apvaliais-ovaliais ar kampuotais, dalis ląstelės periferijoje lokalizuotais be nukleolių branduoliais; mitozių navike iki 3 / 10 DPRL).. 2. Navikas (10 blokas):   Progesterono receptoriai: silpnas branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Proliferacinis aktyvumas (Ki67+++, branduolinė r-ja): 5%.
answer:  1a

 25%|██▍       | 163/661 [04:30<14:19,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. sarginiai l/m, planinis.  2. deš krūtis planinis. 1. Riebalinio audinio fragmentai, bendras dydis 5x3x1,5 cm. Rasti 2 limfmazgiai iki 1,5 cm.  2. Krūtis, 603 g svorio, 20x12x8 cm. Odoje pilkšvas, smulkiai gruoblėtas darinys 0,9x0,8x0,1 cm, nuo odos rezekcijos krašto nutolęs 0,4 cm. Krūties audinyje - balkšvi, standūs, neaiškių, spikulinių ribų naviko židiniai:   - I židinys 2,8x1,2x1,8 cm, nuo artimiausio rezekcijos krašto nutolęs 3 cm, nuo odos - 2 cm.  - II židinys 0,4x0,4x0,4 cm (sudėtas visas), nuo I-ojo židinio nutolęs 2 cm, nuo artimiausio rezekcijos krašto - 2,5 cm, nuo odos - 5,5 cm.  - III židinys 0,2x0,2x0,1 cm (sudėtas visas), nuo I-ojo židinio nutolęs 4,5 cm, nuo artimiausio rezekcijos krašto - 3 cm, nuo odos  - 3 cm.. N1: Limfmazgiai (2 l/m) be naviko židinių; pN0(sn).  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2(28mm).. N1: Limfmazgiai (2 l/m) su reaktyviais pokyčiais, be naviko židinių.  N2: Krūties audinyje 28mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.  Krūties audinyje šalia naviko dvi intraduktalinės papilomos 4mm ir 2mm.  Operacinis pjūvis be naviko.  Odoje seborėjinė keratozė.. nan
answer:  1a

 25%|██▍       | 164/661 [04:32<13:53,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 bioptatai, vienas kietas.. 3 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 5 mm; III - 5 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja trumpos juostos iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 2%.
answer:  1a

 25%|██▍       | 165/661 [04:33<13:55,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 2 biopsiniai stulpeliai iš kairės krūties  BI-RADS 4c darinio   2 but. 1 biopsinis stulpelis iš dešinės krūties BI-RADS 5 darinio. 1. 2 biopsiniai stulpeliai: I - 8 mm; II - 11 mm.  2. Biopsinis stulpelis 13 mm.. Kairė  N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ar vidutinis branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.  ------------------  Dešinė  N2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Kairė  N1: Krūties audinį infiltruoja nedideli kribroziniai/solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ECAD negatyvių ląstelių, mitozių mažiau 1/10 DPRL.  ------------------  Dešinė  N2: Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. nan
answer:  1a

 25%|██▌       | 166/661 [04:35<15:06,  1.83s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Ca mammae sin cT1NxMo I st. 2 kl. - extra  1. kvadranto kraštas - extra  2. kvadranto kraštas - extra  3. sarginai l/m - extra  4. K.krūties kvadrantas.. 4. Krūties sektorius 8x5x2,5 cm, be odos, žymėtas viela. Vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 10x9x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma (8,3 mm židinys), TNM: pT1b(8,3 mm naviko židinys), LVI0(neidentifikuota), pN0(sn)(0/2 l/m). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).  Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai.. 1. Krūties audinyje židininė fibrozė bei sklerozuotos krūties lobulės ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  2. Krūties audinyje židininė fibrozė bei sklerozuotos krūties lobulės ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  3. Du limfmazgiai (2 l/m) su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.  4.  Krūties audinyje - hialinizuotoje stromoje navikas (8,3 mm mikroskopiškai) infiltratyviu augimo frontu, suformuotas trabekulinių ir juostinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, vidutiniškai polimorfiškais, hiperchromiškais branduoliais, nežymiai paryškėjusiais branduolėliais. Mitozių navike iki 3/10DPRL. Limfovaskulinė naviko invazija neidentifikuota( LVI0). Aplinkiniame fibrozuotame krūties audinyje gausūs nežymiai dilatuoti kanaliukaibei lobulės užpildyti solidinių proliferatų iš monomorfiškų ląstelių su apvaliais, kiek ekscentriškais branduoliais. Likusiame krūties audinyje židininė fibrozė, gausūs dilatuoti kanaliukai kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.. Blokas 12:  E-Cadherin: neigiama r-ja invazyviame komponente;  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0.

 25%|██▌       | 167/661 [04:37<15:21,  1.87s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas-be naviko   2(N2b) - kraštas - skubus tyrimas-be naviko  3(N3) - dešinės pažasties sarginis limfmazgis - skubus tyrimas - 4 l/m be naviko  4(N1)- pašalintas dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 10x6,5x3,5 cm su oda 9x4 cm. Krūties audinyje, pilkšvas, standus, neaiškių ribų navikas 16x15x12 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 1,2 cm.. 1(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  2(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  3(Extra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(16 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu, fokaliai hiperplastišku epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu, fokaliai hiperplastišku epiteliu.  3(Extra). 4 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze bei lipomatoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 16 mm), suformuotas fibrozuotoje stromoje ir fokaliai tarp lipocitų infiltratyviai plintančių dominuojančių tubulinių ir negausių kribriforminių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, ovaliais/apvaliais, vidutiniškai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 4/10 DPRL. Šalia yra dilatuotų kanaliukų su kribriforminiais intraduktaliniais analogiškų navikui proliferatais.  Aplink yra dilatuotų kanaliukų, klotų suplokštėjusiu ar kiek hiperplastišku epiteliu, fokaliai su stulpiniu ląstelių pokyčiu su apikalinės sekrecijos požymiais (CCAPSS) bei kanaliukų su apokrinine metaplazija.. 1. Navikas (18 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 1% naviko ląstelių.
answer:  1(n

 25%|██▌       | 168/661 [04:39<15:37,  1.90s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta kairė krūtis - planinis tyrimas. Krūtis, 510 g svorio, 20x18x5 cm. Krūties audinys fibrozuotas 6x4x2 cm plote, nuo artimiausio rezekcijos krašto nutolusi 1cm, nuo odos 2,5 cm. Fibrozės zonoje neaiškių ribų sustandėjimas 0,5x0,5x0,4 cm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos - 5 cm.. PAPILDYTAS ATSAKYMAS, ATLIKTI PAPILDOMI HISTOLOGINIAI PJŪVIAI IR IHC REAKCIJOS:  šalia didžiausio DCIS židinio išryškėjo 2,3mm invazijos židinys: gerai diferencijuota (G1; 4 balai pagal Nottinghma) invazinė duktalinė karcinoma; pT1a.  --------------------  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma; pT1c(m) (du naviko židiniai 2,7mm ir 13mm).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ mažiau 1%.  Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS; kribriforminio ir solidinio tipo; trys židiniai 5,5mm; 10mm ir 17mm).. Krūties audinyje trys židiniai (5,5mm; 10mm ir 17mm) su gausiais dilatuotais kanaliukais su intraduktaliniais kribroziniais ir solidiniais proliferatais iš vidutiniškai atipinių ląstelių.  Krūties audinyje 2,7mm ir 13mm invaziniai navikai: smulkūs solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  Rezekcijos kraštas be naviko.. Invazinis navikas ECAD-.
answer:  1a

 26%|██▌       | 169/661 [04:41<15:37,  1.91s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 10,5x5,5x7 cm, su odos lopu 6x1,3 cm ir speneliu. Krūties audinyje pilkšvas, standus navikas 13x10x10 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 0,8 cm.. 1(ekstra). Krūties audinys.  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (5 l/m).    4. Krūties (kairės) invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(13 mm navikas) pN0(sn)(0/5 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija, navikas nuo sektoriaus rezekcijos krašto nutolęs 0,1 mm).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 20%.. 1(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 5 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.    4. Krūtyje - navikas (13 mm) ekspansyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, trabekulinėmis struktūromis, lizdais  besidėstančių ląstelių vidutinio gausumo šviesia eozinofiliška citoplazma, vidutiniais stambiais, vidutiniškai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 16/10 DPRL. Navikas nuo sektoriaus rezekcijos krašto nutolęs 0,1 mm.. Navikas: Synaptophysin/Chromogranin(-).
answer:  1.

 26%|██▌       | 170/661 [04:43<16:17,  1.99s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(1c)- užspenelinė zona, skubu  4(2). sarginiai limfmazgiai, skubu  5(3). Deš. krūties kvadrantas, planinis  6(4a) - viršutinis kraštas, papildomas  7(5a) - apatinis kraštas, papildomas. 5. Krūties sektorius 16x14x6 cm su odos lopu 15x9 cm, žymėtas viela. Vielos projekcijoje, pjūvyje fibrozės zona 6x5x3,5 cm. Krūties vienas kraštas žymėtas metaline kabute. Fibrozės zonoje balkšvas, standus neaiškių ribų navikas 15x12x10 mm, nuo viela žymėto rezekcijos krašto nutolęs 2,5 cm, nuo kabute žymėto krašto 0,6 cm, nuo odos – 2 cm.  6. Riebalinio audinio fragmentas 2,7x1x0,4 cm. v/m  7. Riebalinio audinio fragmentas 3x1,2x0,4 cm. v/m. 1(1a). Krūties paprasta intraduktalinė hiperplazija, stulpinis epitelio pokytis.   2(1b). Krūties fibrocistiniai pokyčiai.   3(1c). Krūties fibrocistiniai pokyčiai.   4(2). Krūties duktalinės karcinomos metastazė (1-ame iš 5 l/m, metastazė 5,5 mm).  5. Krūties invazyvi vidutiniškai diferencijuota (G2/ 7 b. pagal Nottingham) duktalinė karcinoma,   pT1c (15 mm) pN1a(sn) (1 iš 5 l/m; metastazė 5,5 mm); LVI2 (limfovaskulinė naviko invazija smulkiose kraujagyslėse/ limfagyslėse).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-96091, žr. pastabą.   6. Krūties fibrocistiniai pokyčiai.   7. Krūties audinys be patologinių pokyčių.. 1. Krūties audinyje - nežymi stromos fibrozė, grupės latakų su stulpiniu epitelio pokyčiu, fokaline intraduktaline epitelio ir mioepitelinių ląstelių hiperplazija.   2. Krūties audinyje - stromos fibrozė, cistiškai dilatuoti latakai, apokrininė epitelio metaplazija.   3. Krūties audinyje - stromos fibrozė, cistiškai dilatuoti latakai.   4. Limfmazgyje (1-ame iš 5) - žemiau aprašyto naviko metastazė 5,5 mm.   5. Krūties audinyje - histologiškai iš dalies heterogeniškas navikas, formuojamas 2 komponentų:   1) blogai suformuotos liaukinės ir solidinės naviko struktūros, sudarytos iš vidutinio dydžio ir stambių poligonalinių bei stulpinių ląstelių gausia eozinofiliška citoplazma, gana stambiais, ovoidiniais, vidutiniškai polimorfiškais branduoliais su grūdėtu chromatinu, ryškiomis centrinėmis nukleolėmis,   2) trabekulinės struktūros ir grandinėlės, sudarytos iš vidutinio dydžio poligonalinių ląstelių negausia citoplazma, branduoliais, analogiškais aukščiau aprašytam komponentui.   Navike iki 9 mitozių/ 10 DPRL. Limfovaskulinė naviko invazija smulkiose kraujagyslėse/ limfagyslėse.   Krūties audinyje - stromos fibrozė, cistiškai dilatuoti latakai, apokrininė epitelio metaplazija, grupės latakų su stulpiniu epitelio pokyčiu ir intraduktaliniais kalcifikatais.   6. Krūties audinys nežymiai fibrozuotas, su negausiais cistiškai pakitusiais latakais.   7. Krūties audinys be patologinių pokyčių.. 5. Navikas:   e-cadherin(+++)(membr. r-ja) 100%.
answer:  1.

 26%|██▌       | 171/661 [04:45<15:14,  1.87s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 2 biopsiniai stulpeliai iš kairės krūties BI-RADS 5 darinio  2 but. 2 biopsiniai stulpeliai iš dešinės krūties riboto darinio. 1. 2 biopsiniai stulpeliai: I - 18 mm; II - 15 mm.  2. 2 biopsiniai stulpeliai: I - 9 mm; II - 5 mm.. Kairė  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 20-25%.  ------  Dešinė  N2: Krūties fibrocistiniai pokyčiai, paprastoji intraduktalinė epitelio hiperplazija.. Kairė  N1: Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 7/10 DPRL.  ------  Dešinė  N2: Krūties audinio fibrozė, smulkių kanaliukų proliferacijos židiniai, cistinė kanaliukų dilatacija, kanaliukų epitelio apokrininė metaplazija, vietomis intraduktaliniai epitelio ir mioepitelio proliferatai be atipijos.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0.

 26%|██▌       | 172/661 [04:47<14:24,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%, vietomis iki 15%.. Krūties audinį infiltruoja pavienės duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+
answer:  12%

 26%|██▌       | 173/661 [04:48<13:44,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozės pavienės.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ %.
answer:  1a

 26%|██▋       | 174/661 [04:50<13:10,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 10 mm ilgio.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 35%.. Krūties audinį nedideli netaisyklingi solidiniai kompleksai ir trabekulės iš ryškiai polimorfiškų ląstelių, mitozių iki 2-3/1 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis visos membranos nusidažymas 15% naviko ląsteli
answer:  3b

 26%|██▋       | 175/661 [04:51<13:01,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2A - extra  2. extreaN2B- kraštai - be naviko  3. N3- sarginiai - be naviko -extra  4. N1- sektorius -planinis patologinis tyrimas N1- skubus Ro tyrimas - MK pašalinti. 4. Krūties sektorius 8x4,5x5,5 cm, su odos lopu 8x2,5 cm, žymėtas dvejomis vielomis. Tarp vielų neaiškių ribų standus fibrozės plotas 3x2,2 cm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 2,8 cm.. N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (invazinis navikas 5,2mm).  Aukšto laipsnio intraduktalinė karcinoma (DCIS/DIN3; solidinis ir komedo tipas; pakitimai 10mm plote aplink invazinį naviką).  N2ab: Krūties audinys be naviko, paprasta intraduktalinė epitelio hiperplazija.  N3: Limfmazgiai (2 l/m) be naviko; pN0(sn).. N1: Krūties audinyje 10mm plote intraduktaliniai solidiniai/kribroziniai polimorfiškų ląstelių kompleksai ir 5,2mm invazinis navikas iš nedidelių kribrozinių/solidinių kompleksų vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.  N2a: Krūties audinys be naviko.  N2b: Krūties audinyje intraduktaliniai kribroziniai epitelio ir mioepitelio proliferatai, navikinio augimo nėra.  N3: Limfmazgiai (2 l/m) be naviko.. nan
answer:  1.

 27%|██▋       | 176/661 [04:53<12:50,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 but. 1 biopsinis stulpelis iš kairės pažasties  l/m  2 but. 1 biopsinis stulpelis iš kairės krūties BI-RADS 5 darinio. 1. Biopsinis stulpelis 7 mm ilgio.  2. Biopsinis stulpelis 10 mm ilgio.. N1: Krūties duktalinės karcinomos metastazė limfmazgyje.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%, vietomis iki 20%.. N1: Limfmazgio bioptatas su žemiau aprašytu naviku.  N2: Krūties audinį infiltruoja negausios duktalinės struktūros, smulkūs netaisyklingi kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  1

 27%|██▋       | 177/661 [04:55<13:22,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas   2(N2b) - kraštas - skubus tyrimas (invazyvus navikas krašte  3(N3) - dešinės pažasties sarginis limfmazgis skubus tyrimas - 3l/m be naviko  4(N4) - papildomas kraštas - planinis tyrimas  5(N1) - pašalintas dešinės krūties kvadrantas  - planinis tyrimas. 4. Riebalinio audinio fragmentai, bendras dydis 3x1,6x1 cm.  5. Krūties sektorius 12x6,5x8,5 cm su oda 10x4,5 cm, žymėtas viela. Krūties audinys fibrozuotas 8x5,5 cm plote, fibrozėje pilkšvas, standus, neaiškių ribų navikas 15x13x10 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 3,2 cm. Rastas intramamarinis limfmazgis 0,6 cm.. 1(Extra). Krūties lobulinė karcinoma (2,5 mm židinys). Lobulinė karcinoma in situ (LCIS).  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (3 l/m).  4. Riebalinis audinys.  5. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1c(16 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).  HER2 imuninė reakcija: neigiama (1+).   Lobulinė karcinoma in situ (LCIS).  Reaktyvi limfadenopatija (1 intramamarinis l/m).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - 2,5 mm židinys, suformuotas infiltratyvių smulkių trabekulinių žemiau (Nr.5) aprašyto naviko struktūrų. LCIS šalia.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu; keli kanaliukai su apokrinine metaplazija; pavieniai smulkūs kalcifikatai.  3(Extra). 3 limfmazgiai su fokaline parakortekso hiperplazija, sinusų histiocitoze ir keliais smulkiais histiocitų agregatais; neryški lipomatozė.  4. Brandus riebalinis audinys su negausiomis kraujagyslėmis.  5. Krūties audinyje - ribotas navikas (mikroskopiškai 16 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių trabekulinių struktūrų, grandinėlėmis, smulkiomis grupėmis ar pabirai besidėstančių ląstelių saikinga švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 1/10 DPRL. Aplink dilatuoti kanaliukai, užpildyti analogiškomis navikui ląstelėmis (LCIS).  LIMFMAZGIS: fokalinė parakortekso hiperplazija ir neryški sinusų histiocitozė.. 1. Navikas (24 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.
answer:  1(n

 27%|██▋       | 178/661 [04:56<12:57,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stulpeliai. 3 biopsiniai stulpeliai: I - 15 mm; II - 12 mm; III - 13 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) metaplastinė (matriksą produkuojanti) krūties karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 90%.. Krūties audinį infiltruoja smulkios ryškiai polimorfiškos ląstelės, stroma vietomis chondroidinė, mitozių iki 20/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 90%.
answer:  3

 27%|██▋       | 179/661 [04:58<13:04,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1  biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 8 mm);  (G2; 7 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 80% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 20%.. Krūties audinį 1-me bioptate infiltruoja iki 8 mm :   - solidiniai kompleksai;  - epitelinių vidutinio dydžio ląstelių su ryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - su mitozėmis iki 5/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  CD31: stipri teigiama (+) membraninė reakcija kraujagyslių endotelyje be atipinių struktūrų spindyje  Estrogenų receptoriai: stipri (+++) reakcija, 80% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reak
answer:  20%.

 27%|██▋       | 180/661 [05:00<13:34,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 11 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 40%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai, juostos ir trabekulės iš ryškiai polimorfiškų ląstelių, mitozių iki 14/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 40%.
answer:  3b

 27%|██▋       | 181/661 [05:01<13:40,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 10 mm; II - 12 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 20/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 60%.
answer:  3b

 28%|██▊       | 182/661 [05:03<13:54,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a - kraštai skubus tyrimas  2. N2b - kraštai skubus tyrimas   3. N1 pašalintas markiruotas mikrokalcinatų plotas - planas. 1. Krūties sektorius 10,5x10,5x4 cm su oda 10x2,5 cm, žymėtas 3 vielomis.   - plote tarp I ir II vielų, besitęsiantis - neaiškių ribų, pilkšvas spikulinis židinys su aplinkine riebalinio audinio reakcija 4,5x1x1,3 cm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 3,5 cm.  - III vielos projekcija be makroskopinių pokyčių.. Paruošti pjūviai Prosigna.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Riebalinis - fibrozinis audinys.   3. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(m)(7 mm ir 6 židiniai ~ 1mm) NX(l/m nešalinti) LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis, komedo tipai), židiniai 4,5 cm plote. R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Riebalinis - fibrozinis audinys.   3. Krūtyje - navikas (7 mm ir 6 židiniai ~ 1mm) infiltratyviu augimo frontu, suformuotas trabekulinėmis struktūromis, lizdais besidėstančių ląstelių negausia vidutinio gausumo eozinofiliška citoplazma, smulkiais vidutiniais stambiais, vidutiniškai ryškiai polimorfiškais,  nereguliaraus kontūro, ovaliais apvaliais, vezikulizuotais branduoliais ryškiomis nukleolėmis; mitozių 7/10 DPRL.    Greta gausūs dilatuoti kanaliukai su intraduktaliniais solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.. 3. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas/vidutinis/stiprus dalies/visos membranos nusidažymas xx% naviko ląstelių.  Ki67 proliferacinis aktyvumas 20%.
answer:  3b

 28%|██▊       | 183/661 [05:05<13:38,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 4 biopsiniai stulpeliai.. 4 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 12 mm; III - 6 mm; IV - 6 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.. Krūties audinį infiltruoja nedideli netaisyklingi kribroziniai ir solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ %.
answer:  0

 28%|██▊       | 184/661 [05:06<13:18,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 14 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja smulkios duktalinės struktūros ir kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas.  Ki67+ 8%.
answer:  1a

 28%|██▊       | 185/661 [05:08<13:03,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm ilgio.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20%, vietomis iki 35%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 20
answer:  2b

 28%|██▊       | 186/661 [05:10<13:02,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas ~40x20 mm neaiškių ribų deformuoto liaukinio audinio plotas atitinkantis mamogramose matomus pakitimus dešiniojoje krūtyje ties 1-2 val. vidurinėje/periferinėje dalyse, paimti keturi biopsiniai stulpeliai histologijai.. 4 biopsiniai stulpeliai: I - 7 mm; II - 12 mm; III - 9 mm; IV - 14 mm.. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) galimai lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 1%.. Bioptatuose (4/4) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos grandinėlėmis ir pabirai besidėstančių ląstelių negausia eozinofiliška citoplazma, nežymiai polimorfiškais, smulkaus kalibro, ovalais branduoliais; mitozės neidentifikuotos.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas pavienėse ląstelėse.  Ki67 proliferacinis aktyvumas 1%.  E-cadherin(+++) membr. r-ja 100%; p120_caten
answer:  100%

 28%|██▊       | 187/661 [05:11<12:54,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1  biopsinis  stulpelis. Biopsinis stulpelis 12 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė karcinoma, galimai metaplastinė.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 25%, vietomis iki 40%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, vietomis su plokščialąstelinės diferenciacijos požymiais, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 25%, vietomis iki 40%.
answer:  3

 28%|██▊       | 188/661 [05:13<13:51,  1.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 stulpeliai. Gautas 1 biopsinis stulpelis 17 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.. Krūties audinį infiltruoja solidiniai kompleksai, juostos, trabekulės, pavienės tubulės (<10%) iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Blokas 1:  CK14: mioepitelinio išklojimo navike nėra.   Estrogenų receptoriai: stipri (+++) reakcija, 90% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari re
answer:  0

 29%|██▊       | 189/661 [05:15<13:39,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas dešinės krūties kvadrantas  - planinis tyrimas  2 ėminio aprašas: N2a ir N2b kraštai - planinis tyrimas. 1. Krūties sektorius 8x6x4 cm, su odos lopu 6,5x3,5 cm. Pjūvyje pilkšvas, elastingas miksoidinis navikas 2,4x2,2x1,9 cm, nuo artimiausio  rezekcijos krašto nutolęs 0,1 cm, nuo odos -  3 cm.  2(2a). Riebalinio audinio fragmentas 2,5x2x0,8 cm. v/m  3(2b). Riebalinio audinio fragmentas 3x2,5x1,2 cm. v/m. N1: Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham); pT2 (24mm).  N2ab: Krūties ir riebalinis audinys be naviko.. N1: Krūties audinyje 24mm navikas: mucininėje stromoje aiškių ribų netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  N2ab: Krūties ir riebalinis audinys be naviko.. nan
answer:  1a

 29%|██▊       | 190/661 [05:17<13:26,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 7 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 5% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+, HER2 geno amplifikacija nenustatyta.  Ki67+ 20%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 5% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos ar stiprus dalies membranos nusidažymas 20% naviko ląstel
answer:  3b

 29%|██▉       | 191/661 [05:18<12:59,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 9 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 8%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 10% naviko ląstelių.  Ki67+
answer:  8%

 29%|██▉       | 192/661 [05:20<12:32,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 bioptatai 12 G 22 mm iš ~2 cm kieto darinio. 2 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 15 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 12% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Krūties audinį infiltruoja netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 12% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+ 5%
answer:  1a

 29%|██▉       | 193/661 [05:21<13:14,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1a pašalintas pagrindinis čiuopiamas navikas kartu su markiruotu naviku ties 9/10 valanda su vielute - planinis tyrimas  2 ėminio aprašas: N1b: pašalintas markiruotas navikas su vielute ties 3 val - planinis tyrimas  3 ėminio aprašas: N2a ir N2b kraštai - planinis tyrimas  4 ėminio aprašas: N2a ir N2b kraštai - planinis tyrimas  5 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - planinis tyrimas. 1. Krūties sektorius 7,5x4x3 cm su oda 4x2,2 cm, kraštas be odos žymėtas viela. Vielos projekcijoje - krūties audinys fibrozuotas visame plote (fibrozės plotas sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 4,2 cm. Odos lopo projekcijoje pilkšvas, standus, neaiškių ribų navikas 16x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos 0,9 cm.  2. Riebalinio fibrozinio audinio fragmentas 2,2x1,6x1,3 cm, žymėtas viela. Vielos projekcijoje krūties audinys fibrozuotas visame plote, su cistine ertme 0,3 cm. v/m  3. Riebalinio audinio fragmentas 1x0,6x0,3 cm. v/m  4. Riebalinio audinio fragmentas 0,7x0,7x0,4 cm. v/m  5. Riebalinio audinio fragmentai, bendras dydis 3,3x2,7x1,2 cm. Rasti 2 limfmazgiai iki 1,4 cm. v/m. 1(1a - pagrindinis navikas).  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma;   pT1c(16 mm) pLVI-0 pR0.   Imunofenotipas (nustatytas priešoperaciniame biopsijos tyrime):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 5%.  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).     2(1b - markiruotas navikas).   Krūties fibrocistiniai pokyčiai: atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė.    3(2a - kraštai). Riebalinis audinys be patologinių pokyčių.  4(2b - kraštai). Riebalinis audinys be patologinių pokyčių.    5(sarginis limfmazgis). Limfmazgiai (2) be patologinių pokyčių; pN(sn)0.. 1(1a - pagrindinis navikas). Krūties audinio desmoplastiškoje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, gausiomis tinklinėmis struktūromis besidėstančių ląstelių negausia eozinofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 5/10 DPRL. Greta gausūs dilatuoti latakai su intraduktalinėmis kribriforminėmis ir solidinėmis struktūromis iš analogiškų navikui ląstelių. Atipiniai epitelio pokyčiai 1 mm nuo krašto. Intravaskulinio plitimo nestebima.  2(1b - markiruotas navikas). Fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku ne=ymiai atipiniu epiteliu, smulkių kanaliukų poliferacijos zonos, =idininiai intraduktaliniai stromos proliferatai.  3(2a - kraštai). Riebalinis audinys be patologinių pokyčių.  4(2b - kraštai). Riebalinis audinys be patologinių pokyčių.  5(sarginis limfmazgis). Limfmazgiai (2) be patologinių pokyčių.    apokrininė metaplazija,  smulkūs kalcifikatai spindžiuose.. nan
answer:  0.

 29%|██▉       | 194/661 [05:24<14:23,  1.85s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - k. pažasties sarginiai l/m (ekstra)  2 - k. krutis su speneliu, planiniam tyrimui  3 - deš. krūties liauka po NSM, planiniam tyrimui. 2. Krūtis 344 gramų svorio 18x15x4 cm su odos lopu 12x1,5 cm. Krūties audinyje - neaiškių ribų, nehomogeniška, lobulizuota standi balkšvai gelsvų nedidelių 1 mm atstumu besidėstančių mazgų suformuota zona 24x15x15 mm su nuo odos nutolusi 0,7 cm, nuo giliojo rezekcijos krašto - 0,3 cm. Aplinkiniame krūties audinyje 2 elastingos pilkšvos fibrozės zonos: I - 8x6x2,5 cm, II - 7x3,5x2 cm. Rastas 1 limfmazgis 0,5 cm.  3. Krūties sektorius 13x10x3 cm su balšvos elastingos ar kiek standokos fibrozės zona 7,5x5,5x3 cm.. 1(ekstra). "K. pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).   2. "K. krūtis su speneliu": krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1a(m) (naviko židiniai: I - 4,5 mm; II - 1,5 mm; III - 1,5 mm; IV - 1 mm) N0 (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%.    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis ir komedo tipai; pokyčių zona ~25 mm skersmens).     Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Incidentinė krūties fibroadenoma (0,6 mm).     3. "Deš. krūties liauka po NSM": ryški krūties audinio fibrozė (g.b. post-terapiniai pokyčiai).   SUMINIS TNM: ypT0 (vitalinio naviko neidentifikuota) N0 (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Krūties fibrocistiniai pokyčiai (sklerozuojanti ir mikroglandulinė adenozė).. 1(ekstra). "K. pažasties sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2. "K. krūtis su speneliu":   SPENELIS: normali histologinė struktūra.   "PAKITUSI ZONA" (~25 mm skersmens): krūties audinyje su gausiu perifokaliniu limfocitiniu infiltratu ir tretinių limfoidinių struktūrų formavimusi dėstosi įvairaus dydžio solidiniai, kribriformoniai intraduktaliniai žemiau aprašytos išvaizdos naviko ląstelių kompleksai su centrinėmis komedo tipo nekrozėmis ir kalcifikatais. Fokaliai nuo intraduktalinių kompleksų prasideda nedideli izoliuoti invazyvaus naviko židiniai (žr. aprašymą žemiau).   NAVIKAI (mikroskopiškai identifikuoti - atskiri židiniai: I - 4,5 mm; II - 1,5 mm; III - 1,5 mm; IV - 1 mm):  krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios trabekulinės,  nereguliaraus kontūro, įvairaus dydžio lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo eozinofiline citoplazma, vidutinio dydžio kiek nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 25/10 DPRL.   APLINKA: fokaliai krūties audinys ryškiai fibrozuotas su vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu. Atskiras nedidelis židinys, kurį sudaro proliferuojančių fibroblastų stroma ir suspausti kanaliukai, kloti dvisluoksniu epiteliu.   INTRAMAMARINIS LIMFMAZGIS(1): su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais.   GILUSIS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.  3. "Deš. krūties liauka po NSM": ryškiai fibrozuotas krūties audinys su homogeniškos fibrozės zonomis, kanaliukais, klotais dvisluoksniu epiteliu. Fokaliai suspausti ar kiek dilatuoti kanaliukai formuoja nedidelius židinius.. 2. Navikas (blokas 7):   Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 30% nav
answer:  1.

 30%|██▉       | 195/661 [05:26<15:52,  2.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2). Kairės pažasties sarginiai limfmazgiai, skubu  4(3). Kairės krūties kvadrantas, planinis. 4. Krūties sektorius 9x6x3 cm su odos lopu 9x2 cm, žymėtas viela. Pjūvyje 3 balkšvi standūs, naviko židiniai:  - I židinys 25x14x12 mm, nuo artimiausio rezekcijos krašto nutolęs 0,5 cm, nuo odos – 1,5 cm, nuo vielos - 4,5 cm;  - II židinys 4x4x3 mm (sudėtas visas),nuo artimiausio rezekcijos krašto nutolęs <0,1 cm, nuo odos – 2,5 cm, nuo vielos - 1 cm, nuo I židinio - 3 cm;  - III židinys 5x5x4 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,6 cm, nuo odos – 3 cm, nuo vielos - 3 cm, nuo I naviko - 3 cm, nuo II naviko - 3,5 cm.  Rezekcijos kraštas dažytas mėlynu tušu.. 1(Extra). Krūties audinys.  2(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT(m)1c(3 naviko židiniai: 13 mm, 4,7 mm ir 3 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). II naviko struktūros <0,1 mm nuo rezekcijos krašto.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu; grupė kiek dilatuotų kanaliukų, klotų kiek hiperplastišku epiteliu.  3(Extra). 2 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  4. Krūties audinyje - 3 riboti identiškos struktūros navikai (mikroskopiškai 13 mm, 4,7 mm ir 3 mm), suformuoti fibrozuotoje stromoje su fokaline elastoze plintančių dominuojančių tubulinių ir kribriforminių bei negausių trabekulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, smulkiais ir vidutinio kalibro, ovaliais, gan monomorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 2/10 DPRL. Pavieniai smulkūs kalcifikatai. Perineurinė invazija. Negausūs dilatuoti kanaliukai su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais bei grupė kanaliukų, klotų hiperplastišku epiteliu. Židininė PMN infiltracija. II naviko struktūros <0,1 mm nuo rezekcijos krašto.. 4. Navikas I (11 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 5% naviko ląstelių.   nusidažiusių naviko ląstelių nėra.  Navikas II: CK5(-).
answer:  1(

 30%|██▉       | 196/661 [05:28<14:48,  1.91s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 3 biopsiniai stulpeliai.. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 9 mm; III - 10 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 1-2%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstel
answer:  1a

 30%|██▉       | 197/661 [05:30<14:28,  1.87s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  ca mammae sin - extra  1. pjūvio kraštai, ekstra.   2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 10x6x5 cm su oda 8x3 cm. Krūties audinyje, pilkšvas, standus, neaiškių ribų navikas 22x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 1,2 cm.. 1-2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma. SUMINIS TNM: pT2(22 mm navikas) N0(sn)(1 l/m) LVI-4 (limfovaskulinė invazija smulkiose gyslose ir venose). Radikalus pašalinimas. Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis ir kribriforminis tipai).  Imunofenotipas:  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 40%.. 1-2(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 1 limfmazgis su I/II folikulais, sinusų histiocitoze.  4. Krūties audinyje - 22 mm dydžio (mikroskopiškai) navikas, suformuotas solidinių kompleksų, trabekulių, lizdų bei pavienių tubulių. Naviko ląstelės su vidutinio gausumo, amfofiliška citoplazma, stambiais, netolygaus kontūro, ryškiai polimorfiškais branduoliais su makronukleolėmis. Mitozių navike iki 27/10DPRL. Naviko desmoplastiškoje stromoje gausi monomorfonuklearų infiltracija. Navikas plinta latakų spindžiuose, endotelizuotuose spindžiuose ir stambiose venose.   Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių.. Blokas 12:  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 40% naviko ląstelių.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.
answer:  0

 30%|██▉       | 198/661 [05:32<15:29,  2.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. Deš. pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: 2. Kairės pažasties sarginiai limfmazgiai, skubu  3 ėminio aprašas: 3. Deš. krūtis, planinis  4 ėminio aprašas: 4. Kairė krūtis, planinis. 3. Dex. Krūtis 2118 gramų svorio , 23x21x9,5 cm. Krūties viršutinių kvadrantų riboje -  skiltėtas, rusvas, standus  navikas 2,7x2,3x2,5 cm, nuo rezekcijos krašto nutolęs 1,4 cm, nuo odos - 2,5 cm. Krūties auidinyje viršutiniame lateraliniame kvadrante - balkšva, standi , aiškių ribų (I) zona 1,3x0,7x0,4 cm, nuo rezekcijos krašto nutolusi 2,4 cm, nuo odos - 2 cm, nuo naviko - 2,5 cm. Krūties audinyje , centrinėje dalyje balkšva, elastinga (II) fibrozės zona 9x7x5,5cm, nuo rezekcijos krašto nutolusi 0,5 cm, nuo odos - 1,5 cm.  4. SIN. Krūtis 2025 gramų svorio , 22x21x9 cm. Krūties viršutiniame medialiniame kvadrante - pilkšvas, standus, gerai ribotas  (I) navikas 3,5x3,5x2,3 cm, nuo rezekcijos krašto nutolęs 3 cm, nuo odos - 2 cm. Krūties auidinyje viršutiniame medialiniame kvadrante - balkšvas, standus, neaiškių ribų (II) navikas  0,9x0,7x0,6cm, nuo rezekcijos krašto nutolęs 1,8 cm, nuo odos - 5,5 cm, nuo (I)naviko - 0,5 cm. Krūties audinyje , viršutiniame lateraliniame kvadrante  zona  9x5x5 cm su dilatuotais, standžiais latakais iki 0,8 cm skersmens, didžiausias latakas nuo rezekcijos krašto nutolęs 1,4 cm.. 1(ekstra). DEŠINĖ. Duktalinės karcinomos mikrometastazė limfmazgyje (1/4 l/m, 0,4mm). Limfovaskulinė invazija.   2(extra). KAIRĖ. Reaktyvi limfadenopatija (3 l/m).    3. DEŠINĖ. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma su daline neuroendokrinine diferenciacija, SUMINIS TNM: pT2(27 mm) pN1a(sn)(1/4 l/m, 0,4mm). LVI-2(limfovaskulinė invazija). Vidutinio žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas), gausūs židiniai iki 1 cm.    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    4. KAIRĖ. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma neuroendokrinine diferenciacija, SUMINIS TNM: pT2(m)(35 mm ir 7 mm navikai) pN0(sn)(0/3 l/m). LVI-2(limfovaskulinė invazija). Vidutinio žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas).  Židininiai fibrocistiniai pokyčiai.    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.. 1(ekstra). 1 iš 4 limfmazgių aprašyto naviko metasatzė 0,4 mm. Limfovaskulinė invazija.  2(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  3. Spenelis: normali histologinė struktūra.   Krūtyje - navikas ekspansyviu augimo frontu, suformuotas lizdais ir solidiniais plotais besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 19/10 DPRL. Limfovaskulinė invazija.  Aplinkiniame krūties dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaustų kanaliukų zonos.    4. Spenelis: normali histologinė struktūra.   Krūtyje - navikas (35 mm ir 7 mm navikas) ekspansyviu augimo frontu, suformuotas lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 5/10 DPRL. Limfovaskulinė invazija.  Aplinkiniame krūties dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.. 3. Navikas (17 blokas): Synaptophysin(+++) citopl. r-ja 10%;  HER2 silpnas dalies membranų nusidažymas <5%.  4. Navikas (39 blokas): Synaptophysin(+++) citopl. r-ja 100%;  HER2 silpnas dalies membranų nusidažymas <5%.
answer:  0

 30%|███       | 199/661 [05:34<14:58,  1.94s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas - be naviko   2(N2b) - kraštas - skubus tyrimas - be naviko  3(N3) - kairės pažasties sarginis limfmazgis - skubus tyrimas - 2 l/m be naviko  4(N1) - pašalintas markiruotas kairės krūties kvadrantas planinis tyrimas. 4(N1). Viela žymėtas krūties sektorius 9,5x4,5x3 cm su odos lopu 8x1,8 cm. Vielos projekcijoje, pjūvyje balkšvas, gan aiškių ribų navikas 9x6x5 mm, nuo artimiausio rezekcijos krašto nutolęs 0,6 cm, nuo odos – 2,2 cm.. 1(2a). Riebalinis audinys.  2(2b). Krūties audinys; intraduktaliniai mikrokalcifikatai.  3. Reaktyvi limfadenopatija (2 l/m).  4(1). Krūties invazyvi, gerai diferencijuota (G1; 4 balai pagal Nottingham sis) duktalinė karcinoma, pT1b(navikas - 9mm) pN0(sn)(0/2 l/m).  IHC reakcijos atliktos VPC:B23-43418 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%."  Krūties fibrocistiniai pokyčiai.. 1(2a). Riebalinis audinys su fibrovaskulinėmis septomis.  2(2b). Riebalinis audinys su fibrozės zonomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu; intraduktalinių mikrokalcifikatų židiniais.  3. Du(2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4(1). Krūties fibroziniame audinyje - navikas, formuojamas netaisyklingų duktalinių, pavienių kribriforminių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, nežymiai, vietomis vidutiniškai polimorfiškais branduoliais; navike iki 2 mitozių/10 DPRL. Aplinkiniame krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu.. nan
answer:  1(

 30%|███       | 200/661 [05:35<14:33,  1.90s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2A)- kraštas -skubi histologija - be naviko  2(N2b)- kraštas -skubi histologija - be naviko  3(N3)- pašalinti sarginis l/m - skubi patologija - be naviko  4(N1)-pašalintas sektorius - planinis tyrimas. 4. Krūties sektorius 11x8,5x6 cm su oda 10x6 cm, odoje, krūties audinyje injekuotas metileno mėlis. Krūties audinyje - pilkšvas, standus, mucininis navikas 48x32x46 mm, nuo giliojo rezekcijos krašto (dažyto mėlynu tušu) nutolęs 0,1 cm, nuo odos - 2 cm. Sektoriuje rastas suriebėjęs limfmazgis 1,7 cm (sudėtas visas).. 1. Fibrocistiniai krūties pokyčiai: paprastoji intraduktalinė hiperplazija.  2. Riebalinis audinys be naviko plitimo.   3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) mucininė karcinoma, TNM: pT2(navikas 48 mm), pN0(sn)(0/3 l/n), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).. 1(2a). Krūties audinyje gausios lobulės ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu bei keli nežymiai dilatuoti kanaliukai, kloti hiperplastišku epiteliu..   2(2b). Riebalinio audinio fragmentas su fibrozinėmis septomis ir kraujagyslėmis.  3. Du limfmazgiai (2 l/m) su sinusų histiocitoze.  4. Krūties audinyje navikas (48 mm makroskopiškai), suformuotas gausiuose ekstraląsteliniuose mucinuose besidėstančių smulkių solidinių, tubulinių ir negausių mikropapilinių struktūrų. Naviko ląstelės vidutinio gausumo eozinofiline citoplazma, vidutiniškai polimorfiškais branduoliais su negausiomis smulkiomis nukleolėmis. Mitozių navike iki 5/10 DPRL. Limfovaskulinis naviko plitimas neidentifikuotas. Navikas nuo sektoriaus rezekcijos krašto nutolęs per 0,4 mm. Krūties audinyje identifikuotas limfmazgis su sinusų histiocitoze ir pavieniais antriniais limfiniais folikulais.. Blokas 15:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 30%|███       | 201/661 [05:37<14:37,  1.91s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.  4. krūties sektorius, planinis.. 4. Krūties sektorius 7x5,5x4 cm su oda 6,5x4,5 cm. Krūties audinyje - pilkšvas standus, spikulinių kraštų navikas 1,8x1,5x1,8 cm, nuo giliojo rezekcijos krašto nutolęs mažiau 0,1 cm, nuo odos - 1,3 cm.. Paruošti pjūviai Prosigna tyrimui.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Krūties duktalinės karcinomos mikrometastazė limfmazgyje (1/3 0,4 mm).  4. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(17 mm navikas) pN1mi(sn)(1/3 l/m mikro MTS 0,4 mm) LVI-0(limfovaskulinė invazija neidentifikuota). Perineurinis plitimas. R0(navikas nuo sektoriaus rezekcijos krašto nutolęs <0,1 mm).     Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 1 iš 3 limfmazgių aprašyto naviko mikrometastazė 0,4 mm.  4. Krūtyje - navikas (17 mm) infiltratyviu ekspansyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, ovaliais apvaliais, vezikulizuotais branduoliais ryškiomis nukleolėmis;  mitozių 24/10 DPRL.  Perineurinis plitimas.. 2. 3 blokas: CK5/CK14+ mioepitelis; E-cadherin(+++) membr. r-ja 100%  3. Navikas (13 blokas):  HER2: nusidažiusių naviko ląstelių nėra.
answer:  1.

 31%|███       | 202/661 [05:40<15:16,  2.00s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštai  - skubus tyrimas - be naviko  2(N2b). kraštai  - skubus tyrimas - be naviko  3(N3). kairės pažasties sarginis limfmazgis - skubus tyrimas -  2l/m be naviko  4(N1): pašalintas kairės krūties kvadrantas - planinis tyrimas. 4(N1). Krūties sektorius 9x5,5x5 cm su odos lopu 6,3x3 cm žymėtas viela. Vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 11x10x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos 1,8 cm. Navikas histologiniam ištyrimui sudėtas visas.. 1(N2a). Krūties audinys.  2(N2b). Krūties audinys.  3(N3). Reaktyvi limfadenopatija (2 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,1 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės naviko invazijos nėra).    Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 12% (hot spot 15%).. 1(N2a). Krūties audinyje - pavieniai smulkūs fibrozės židiniai su negausiais smulkiais kanaliukais, išklotais dvisluoksniu epiteliu.  2(N2b). Krūties audinyje - pavieniai smulkūs fibrozės židiniai su negausiais smulkiais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N3). Sinusų histiocitozė dviejuose (2) limfmazgiuose.  4(N1). Krūties audinyje - navikas: Solidines, trabekulines, pavienes smulkias tubulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne amfofiline citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 3 / 10 DPRL.. 4(N1). Navikas (12 blokas):  Her2 nusidažiusių ląstelių nėra; Synaptophysin(-).
answer:  0.

 31%|███       | 203/661 [05:42<15:59,  2.09s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas  2(N2b) kraštai - skubus tyrimas -(N2B krašte invazyvus židinys)  3(N3): kairės pažasties sarginis limfmazgis - skubus tyrimas 2l/m be naviko  4(N5a) - kraštai  - skubus tyrimas be naviko  5(N5b) - kraštai  - skubus tyrimas be naviko  6(N1): pašalintas žymėtas kairės krūties verifikuotas navikas - planinis tyrimas  7(N4): dešinės krūties markiruotas plotas - planinis tyrimas  8(N6) - papildomas kraštas  iš kairės krūties. 6(N1). Krūties sektorius 8x7x3 cm su odos lopu 5x1,5 cm, žymėtas dviem vielomis. Tarp vielų pilkšvas, neaiškių ribų navikas 0,7x0,5x0,6 cm (sudėtas visas). Makroskopiškai siekiantis rezekcijos kraštą 4 mm ilgyje, nuo odos nutolęs 3,5 cm. Krūties sektorius fibrozuotas 6,5x3,5x2 cm plote, fibrozė siekia rezekcijos kraštą, nuo odos nutolusi 1,5 cm. Fibrozės zonoje standus plotas su paryškėjusios spalvos riebaliniu audiniu (II naviko židinys?) 0,8x0,7x0,8 cm, makroskopiškai siekiantis rezekcijos kraštą, nuo naviko nutolęs 1,8 cm (sudėtas visas)  7(N4). Krūties sektorius 11x8x6 cm su odos lopu 11x4,5 cm, žymėtas trim vielomis. Tarp vielų balkšva, elastinga fibrozės zona 9x5x5 cm, makroskopiškai siekianti rezekcijos kraštą, nuo odos nutolusi 1 cm. Sudėtas kas antras fibrozės pjūvis. Atokiau nuo vielų, krūties audinyje pilkšvas, apvalus židinys 0,9x0,7x0,0,7 cm (sudėtas visas), nuo rezekcijos krašto nutolęs 0,7 cm.  8(N6). Riebalinio audinio fragmentas 1,5x1,2x0,5 cm. v/m. 1(N2a). Krūties fibrocistiniai pokyčiai.   2(N2b). Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, kribriforminė).   3(N3). Krūties duktalinės karcinomos metastazė limfmazgyje (1 iš 3 l/m, metastazė 1,6 mm).   4(N5a). Krūties fibrocistiniai pokyčiai, paprasta intraduktalinė hiperplazija.  5(N5b). Krūties fibrocistiniai pokyčiai, stulpinis epitelio pokytis.  6(N1). Krūties invazyvi daugiažidininė blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma,   pT1b(m) (2 naviko židiniai 6,5 mm ir 4 mm) pN1mi (1 iš 3 l/m, metastazė 1,6 mm); LVI2 (limfovaskulinė naviko invazija smulkiose limfagyslėse/ kraujagyslėse).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-17740, žr. pastabą.   Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, kribriforminė, plokščia, solidinė su comedo nekroze).   7(N4). Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS/ DIN1c - DIN2, kribriforminė ir mikropapilinė), pTis.   Intraduktalinės papilomos.   8(N6). Krūties audinio fibrozė.. 1. Krūties audinyje - nežymi stromos fibrozė, reti kanaliukai ir atrofiškos lobulės, pavieniai cistiškai dilatuoti latakai su apokrinine epitelio metaplazija.   2. Krūties audinyje - nežymi stromos fibrozė, kelios grupės latakų su intraduktaliniais kribriforminiais proliferatais, formuojamais vidutinio dydžio ir stambių ląstelių su vidutiniškai ar ryškiai polimorfiškais, hiperchromiškais branduoliais.   3. Limfmazgyje (1-ame iš 3, "poekstriniame" pjūvyje) - žemiau aprašyto naviko metastazė 1,6 mm.   4. Krūties audinyje - stromos fibrozė, cistiškai pakitę latakai su apokrinine epitelio metaplazija, keli kanaliukai su intraduktaline epitelinių ir mioepitelinių ląstelių hiperplazija.   5. Krūties audinyje - stromos fibrozė, cistiškai pakitę latakai, stulpinis epitelio pokytis su apikalinės sekrecijos požymiais latakuose ir kanaliukuose.   6. Krūties audinyje - 2 invazyvaus naviko židiniai 6,5 mm ir 4 mm, formuojami trabekulinių, smulkių solidinių grupių ir pavienių liaukinių struktūrų, sudarytų iš vidutinio dydžio ir stambių ląstelių eozinfiliška citoplazma, ryškiai polimorfiškais ovoidiniais branduoliais su stambiomis nukleolėmis, grūdėtu chromatinu.   Limfovaskulinė naviko invazija smulkiose limfagyslėse/ kraujagyslėse.   Aplinkiniame krūties audinyje - grupės latakų su intraduktaliniais kribriforminiais, solidiniais ir plokščiais proliferatais su comedo tipo nekroze, formuojamais vidutinio dydžio ir stambių ląstelių su ryškiai polimorfiškais branduoliais su ryškiomis nukleolėmis, netolygiai grūdėtu chromatinu.    7. Krūties audinyje - kelios grupės latakų ir pavieniai latakai su intraduktaliniais kribriforminiais proliferatais, sudarytais iš vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais su ryškiomis nedidelėmis nukleolėmis. Keli latakai kloti aukštu stulpiniu epiteliu ir pavienėmis mikropapilinėmis struktūromis, su santykinai monotoniškais pailgais, hiperchromiškais branduoliais. Intraduktaliniuose epiteliniuose proliferatuose yra smulkių kalcifikatų.   Keli nežymiai dilatuoti latakai su minimaliai šakotomis smulkiomis papilinėmis struktūromis, klotomis mioepitelinėmis ir epitelinėmis ląstelėmis.   8. Krūties audinyje - židininė kolagenizuota stromos fibrozė.. nan
answer:  1(n

 31%|███       | 204/661 [05:44<15:04,  1.98s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 18 G automatine biopsine adata punktuotas ~6x12 mm dydžio cistinis su izoechogenišku intracistiniu komponentu darinys labiausiai panašus į papilomą dešiniojoje krūtyje ties 8 val. vidurinėje dalyje, paimti trys biopsiniai stulpeliai histologijai (I buteliukas).   2. 18 G automatine biopsine adata punktuotas ~35 mm ilgyje plėstas latakėlis su izoechogenišku turiniu (labiausiai panašu į papilomą) dešiniojoje krūtyje ties 12 val. centrinėje dalyje areolės srityje, paimti trys biopsiniai stulpeliai histologijai (II buteliukas).  3. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~21x26 mm dydžio navikas dešiniojoje krūtyje ties 1-2 val. vidurinėje dalyje, paimti trys biopsiniai stulpeliai histologijai (III buteliukas).. 1. 3 fragmentuoti biopsiniai stulpeliai: I - 5 mm; II - 4 mm; III - 4 mm.  2. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 5 mm; III - 5 mm.  3. Gauti 2 biopsiniai stulpeliai: I - 6 mm; II - 4 mm ir bioptatas 0,1 cm.. N1: Intraduktalinė krūties papiloma.  N2: Krūties cista.  N3: Gerai diferencijuota (G1, 4balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. N1: Krūties audinyje dilatuotame kanalėlyje šakotos intraduktalinės papilinės struktūros iš fibrozinės stromos, išklotos dvisluoksniu epiteliu.  N2: Krūties audinyje cista, išklota suplokštėjusiu epiteliu. Papilomos komponentų nėra.  N3: Krūties audinį infiltruoja duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 12
answer:  1.

 31%|███       | 205/661 [05:46<14:50,  1.95s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Kairės pažasties sarginiai limfmazgiai, skubu  2. Kairė krūtis - planinis. 2. Krūtis 682 gramų svorio, 19,5x15,5x4,5 cm. Krūties audinyje balkšvi standūs neaiškių ribų naviko židiniai:    - I - viršutinių kvadrantų riboje, 2,7x2x2,3 cm skersmens, nuo odos nutolęs 1,8 cm, nuo artimiausio rezekcijos krašto - 0,9 cm;   - II - 1,1 cm nuo I židinio, 1x0,7x0,7 cm skersmens, nuo odos nutolęs 4 cm, nuo artimiausio rezekcijos krašto - 1 cm;   - III - 1 cm nuo I židinio, 0,5x0,5x0,5 cm skersmens, nuo odos nutolęs 2,5 cm, nuo artimiausio rezekcijos krašto - 3,5 cm;   - IV - 1 cm nuo I židinio, 0,3x0,2x0,3 cm, nuo odos nutolęs 3,5 cm, nuo artimiausio rezekcijos krašto - 1,5 cm.   Krūties audinyje smulkios cistos iki 0,4 cm.. 1(ekstra). "Kairės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT2(m) (navikai: I - 27 mm; II - 10 mm; III - 5 mm; IV - 3 mm) N0(sn) (0/3 l/m),   LVI-0 (definityvios limfovaskulinės invazijos neidentifikuota).     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties lobulinė intraepitelinė neoplazija (LCIS).  Krūties žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS: solidinis ir kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   Krūties gilusis rezekcijos kraštas be naviko.. 1(ekstra). "Kairės pažasties sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2. SPENELIS: normalios histologinės struktūros.   NAVIKO ŽIDINIAI (I - 27 mm; II - 10 mm; III - 5 mm; IV - 3 mm):   krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės, nedideli lizdai struktūros, trumpos "grandinėlės", solidinės naviko struktūros, suformuotos mažai kohezyvių vidutiniškai polimorfiškų ląstelių, vidutinio gausumo eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su  smulkiomis nukleolėmis; mitozių iki 5/10 DPRL.   APLINKA: zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais. Keli nedideli solidiniai ir kribriforminiai intraduktaliniai nežymiai polimorfiškų kohezyvių naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, apokrinės metaplazijos zonomis.   GILUSIS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 2. Navikas (blokas 12):  HER2: silpna (+) necirkuliari reakcija, 10% naviko ląstelių membranoje.
answer:  0

 31%|███       | 206/661 [05:47<13:44,  1.81s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 3 mm; III - 5 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja smulkūs solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 8%.
answer:  1a

 31%|███▏      | 207/661 [05:49<13:06,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 14 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 3%.. Krūties audinį 2-se bioptatuose infiltruoja iki 12 mm :   - pavienės duktalinės struktūros, juostos ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++) membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki
answer:  3%

 31%|███▏      | 208/661 [05:50<13:22,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. (2a) kraštai - skubus tyrimas - be naviko;  2. (2b) kraštai - skubus tyrimas - be naviko;   3. (N3) Kairės pažasties limfmazgis - skubus tyrimas 3 l/m  - viename iš trijų limfmazgių makrometastazė.  4. (N1) pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 5x4x2,5 cm be odos, žymėtas viela. Vielos projekcijoje - pilkšvas, neaiškių ribų židinys 9x9x6 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm.. PAPILDYTA (HER2 FISH tyrimas):  1(Extra). Krūties audinio fibrozė.  2(Extra). Krūties audinio fibrozė.  3(Extra). Duktalinės karcinomos metastazė 1/3 limfmazgyje (5,7 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(8 mm) N(sn)1a(mts 1/3 l/m; 5,7 mm), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Her2 imuninė reakcija: ribinė (2+).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, plokščia).  Krūties intraduktalinės papilomos (dalis su vidutinio laipsnio DCIS).. 1(2a)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(2b)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). Viename iš 3 limfmazgių - žemiau (Nr.4) aprašyto naviko metastazė (5,7 mm).  4. Krūties audinyje - ribotas navikas (mikroskopiškai 8 mm), suformuotas fibrozuotoje stromoje plintančių lizdinių ir trabekulinių, pavienių tubulinių ir kribriforminių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 3/10 DPRL. Negausūs smulkūs kalcifikatai. Šalia naviko ir fokaliai atokiau yra dilatuotų ir kiek smulkesnių kanaliukų su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais bei grupė dilatuotų latakų su papilinėmis intraduktalinėmis struktūromis, klotomis dvisluoksniu epiteliu, fokaliai su DCIS plitimu.. 1. Navikas (11 blokas): HER2 imuninė reakcija: vidutinis dalies ir visos, fokaliai stiprus dalies membranos nusidažymas 80% naviko ląstelių.  14 blokas: CK14+ negausios mioepitelinės ląstelėse papilomose su DCIS.  18 blokas: DCIS su išlaikytu CK14+ mioepi
answer:  1/

 32%|███▏      | 209/661 [05:52<13:00,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Kairė krūtis, planinis. Krūtis, 133,5 gramų svorio, 14x10x3 cm. Pjūvyje fibrozės zona 4x2x1,5 cm, nuo giliojo rezekcijos krašto nutolusi 0,1 cm, nuo odos - 1,5 cm. Krūties audinys difuziškai fibrozuotas.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1a (daugybiniai invazijos židiniai, didžiausias 1,5mm).  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 12%.  Krūties aukšto laipsnio intraduktalinė karcinoma (DIN3/DCIS, kribriforminis ir komedo tipas; du navikiniai židiniai - 40mm plote ir 9mm plote).  Rezkecijos kraštas be naviko.. Krūties audinyje 40mm plote intraduktaliniai solidiniai ir kribroziniai polimorfiškų ląstelių proliferatai, vietomis su nekrozės židiniais spindyje. Daugybiniai mikroskopiniai invazijos židiniai iki 1,5mm: solidiniai/kribroziniai kompleksai vidutinio ar ryškaus polimorfizmo ląstelių, mitozių  mažiau 1/10 DPRL.   Tokios pačios struktūros 9mm DCIS židinys aplinkiniame krūties audinyje.  Rezekcijos kraštas be naviko.. Invazinis navikas:  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 60% naviko ląstelių.  Ki67+ 1
answer:  0.

 32%|███▏      | 210/661 [05:54<13:22,  1.78s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). Sektoriaus krašai.-extra   2(N2). Sektoriaus kraštai.-extra   3(N3). Sarginiai l/n. -extra  4(N5). Papildomas kraštas - LCIS įtarimas.-extra  5(N4). K.krūties sektorius su naviku.. 5. Krūties sektorius 10x7x4 cm su oda 9x2,5 cm, žymėtas viela ir metileno mėliu viename sektoriaus krašte. Viela kiaurai perveria sektorių. Krūties audinyje šalia vielos - balkšvas, standus, spikulinių kraštų navikas 16x12x15 mm, nuo giliojo rezekcijos krašto (dažyta mėlynu tušu) nutolęs 0,3 cm, nuo odos - 5,5 cm. Ties viela, 2,5 cm nuo naviko krūties riebalinis audinys standus, su nekrozės zonomis ir hemoragijomis 1,3x1x1 cm plote, pakitusi zona nuo rezekcijos krašto nutolusi 0,5 cm, nuo odos - 1 cm.. 1. Krūties žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS). Krūties lobulinė karcinoma in situ (LCIS).   2. Krūties audinys.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties lobulinė karcinoma in situ (LCIS). Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija.  5. Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 12 mm), pN0(sn)(0/2 l/n), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.HER2:reakcijos nėra (0).  Žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS). Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai: paprastoji intraduktalinė hiperplazija, apokrinine metaplazija.. 1. Krūties audinyje pavieniai dilatuoti kanaliukai užpildyti kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Šalia gausūs nežymiai dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.   2. Krūties audinyje smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  3. Du limfmazgiai (2 l/m) su sinusų histiocitoze.  4. Krūties audinyje gausūs nežymiai dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta nežymiai dilatuoti kanaliukai kloti fokaliai hiperplastišku epiteliu ar epiteliu su apokrinine metaplazija.  5. Krūties audinyje - navikas (12 mm mikroskopiškai), suformuotas tubulinių, kribriforminių bei trabekulinių struktūrų iš vidutinio kalibro eozinofiline citoplazma ląstelių, nežymiai polimorfiškais, smulkiai grūdėtu chromatinu branduoliais; mitozių 1/10 DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Greta naviko negausūs dilatuoti kanaliukai su kribriformine proliferacija iš monomorfiškų, negausia šviesiai eozinofiline citoplazma ląstelių apvaliais, kiek hiperchromiškais branduoliais. Krūties audinyje gausūs nežymiai dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta nežymiai dilatuoti kanaliukai kloti fokaliai hiperplastišku epiteliu ar epiteliu su apokrinine metaplazija. Fokaliai krūties audinyje - histiocitų, svetimkūnio tipo gigantinių daugiabranduolių ląstelių ir limfocitų infiltracija.. Blokas 20:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 32%|███▏      | 211/661 [05:56<13:39,  1.82s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1. 1 - sarginiai l/m - extra  N2. Kairė krūtis su navikais.. 2. Krūtis 690 gramų svorio, 22x16x8 cm. Visas krūties audinys balkšvas, fibrozuotas.  Periferijoje, fibrozėje, rusvas, neaiškių ribų sustandėjimas 14x10 mm plote, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos 1,7 cm.   Nuo sustandėjimo 3 cm atstumu, pilkšvas, neaiškių ribų židinys 12x10x6 mm, nuo giliojo rezekcijos krašto nutolęs 2,5 cm, nuo odos - 2 cm.. 1(ekstra). Sarginiai l/m. Reaktyvi limfadenopatija (2 l/m).    2. Krūties invazinė duktalinė karcinoma,   pT1c(m) (naviko židiniai iki 10,4 mm)   pN0(sn)(2 l/m)    pLVI-0 (limfovaskulinė invazija neidentifikuota)   pR0(radikalus pašalinimas).  Diferenciacijos laipsniai navikuose:   I navike (9,6 mm) - blogai diferencijuota (G3, 9 balai pagal Nottingham),   II navike (10,4 mm) - gerai diferencijuota (G1, 3 balai pagal Nottingham),   III navike (5,4 mm) - vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham).       I naviko imunotipas nustatytas priešoperacinėje biopsijoje (B23-6714):  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 80%.    II naviko imunotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.    Lobulinė karcinoma in situ (LCIS).. 1(ekstra). Sarginiai l/m. 2 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.    2. Krūties audinyje - trys morfologiškai skirtingi navikai:  I navikas (9,7 mm dydžio mikroskopiškai): gausios limfocitų infiltracijos apsupsti solidiniai kompleksai iš ląstelių gausia eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais branduoliais su stambiomis nukleolėmis. Mitozių navike iki 20/10DPRL.  II navikas (10,4 mm dydžio mikroskopiškai): desmoplastiškoje stromoje plintančios infiltratyvios tubulinės (90%) ir kribriforminės struktūros, iš stulpinių ląstelių eozinofiliška citoplazma, smulkiais, ovoidiškais, gan monotoniškais branduoliais su pavienėmis smulkiomis nukleolėmis. Mitozių navike <1/10DPRL.    III navikas (5,4 mm dydžio mikroskopiškai): fibrozinėje stromoje plintančios infiltratyvios trabekulės ir lizdai, suformuoti ląstelių negausia tamsiai eozinofiliška citoplazma, ovoidiškais, vidutiniškai polimorfiškais, vesikuolizuotais branduoliais. Mitozių navike iki 2/10DPLR.      Aplinkiniame krūties audinyje gausūs latakėliai su solidiniais proliferatais iš ląstelių apvaliais, hiperchromiškais, gan monotoniškais branduoliais, plintantys mažiausiai 11 mm už invazyvaus naviko ribų.  Atokiau stambesnės lobulės su tankiai išsidėsčiusiais kanalėliais (adenozės židiniai), apokrininė metaplazija.. Blokas 13: CD31+ endotelis ir naviko stroma; naviko limfovaskulinė invazija neidentifikuota).  II navikas (Blokas 15):  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 70%  naviko
answer:  lą

 32%|███▏      | 212/661 [05:58<13:14,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra (be naviko);  2(2b). Kraštai - extra (be naviko);  3. Sarginiai l/m - extra (be naviko);  4(1). Sektorius skubus rentgeninis tyrimas, navikas pašalintas - planinis tyrimas.. 4. Krūties sektorius 11x4x4,5 cm su oda 9x2,5 cm, žymėtas viela. Krūties audinyje, kvadrante - pilkšvas, neaiškių ribų sustandėjimas 6x6x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,5 cm.. 1(2a). Kraštai - krūties audinys be patologinių pokyčių.  2(2b). Kraštai - krūties audinys be patologinių pokyčių.  3. Sarginiai l/m - limfmazgis (1) be patologinių pokyčių.    4. Krūties sektorius.   Invazinė duktalinė (kitaip neklasifikuojama) karcinoma;   (G1; 3 b. pgl. Nottingham sist.);   pT1b pN0 pLVI-0 pR0.  Imunotipas (priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 4%.. 1(2a). Kraštai - krūties audinys be patologinių pokyčių.  2(2b). Kraštai - krūties audinys be patologinių pokyčių.  3. Sarginiai l/m - limfmazgis (1) be patologinių pokyčių.  4. Krūties sektorius. Krūties audinį infiltruoja navikas (mikroskopiškai 5 mm) , kurį sudaro:   - duktalinės netaisyklingos struktūros (95% viso naviko);  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. nan
answer:  0.

 32%|███▏      | 213/661 [05:59<12:54,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 biopsinis stulpelis iš kairės krūties BI-RADS 5 darinio   2 but. 3 biopsiniai stulpeliai iš latakų su kalcinatais bei riboto darinio dešinėje krūtyje.. 1. 1 biopsinis stulpelis 15 mm ilgio.   2. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 9 mm.. 1. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 10%. Karštame taške 20%.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.    2. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 10%.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.. 1.Krūties audinį infiltruoja netaisyklingi kribroziniai kompleksai ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.  2. Krūties audinį infiltruoja duktalinės struktūros (<10%), netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. 1. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) cirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių. Karštame taške 20%.  Progesteron
answer:  1.

 32%|███▏      | 214/661 [06:01<12:27,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas švelniai hipoechogeninis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~21×15 mm dydžio darinys dešiniojoje krūtyje ties 11 val. periferinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 16 mm; II - 14 mm; III - 14 mm.. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma.   Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.   Her2 imuninės r-ja: neigiama (0).   Ki67 proliferacinis aktyvumas iki 10%.. 3 bioptatai: krūties audinyje plinta netaisyklingos tubulinės ir kribriforminės struktūros, suformuotos ląstelių eozinofiline citoplazma, ovoidiniais, su neryškiu polimorfizmu, stratifikuotais branduoliais. Mitozių 2/10 DPRL.. Navikas:   CK14+ mioepitelinio sl. nėra.   Synaptophysin(-);  Estrogenų receptoriai: (++++)(brand. r-ja) 100%.   Progesterono receptoriai: (++++)(brand. r-ja) 100%.  HER2: nusidažiusių naviko ląstelių membranų nėra.  Ki67 proliferacinis aktyvumas iki 10%.
answer:  1a

 33%|███▎      | 215/661 [06:03<12:54,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- Deš. krūties sektorius, planinis. 3(2). Riebalinio audinio fragmentas 9x6x5 cm, be odos lopo, žymėtas 3 vielomis. Pjūvyje, neaiškių ribų, balkšvi susiliejantys židiniai iki 3,5x3x2 cm, bendras židinių dydis 5,5x4x2,5 cm. Vietomis židiniai siekia rezekcijos kraštą. Juoda spalva dažytas gilusis kraštas, poodinis kraštas dažytas raudonai, medialinis kraštas - mėlynai, lateralinis kraštas dažytas žalia spalva. Pjūviai imti nuo viršaus į apačią.. 1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, pT1a(1,6 mm) NX(limfmazgiai nešalinti), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Imunofenotipas:   Estrogenų receptoriai: vidutinis branduolių nusidažymas 70% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  HER2 imuninė reakcija: neigiama (0).  Ki67: 10%.  Krūties aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DIN3/DCIS)(solidinė, kribriforminė, komedo).  DCIS struktūros siekia medialinį rezekcijos kraštą, 0,15 mm nuo poodinio rezekcijos krašto, 0,5 mm nuo giliojo krašto.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  3. Krūties audinyje - fibrozės zona su gausiais dilatuotais kanaliukais su solidiniais ir kribriforminiais intraduktaliniais proliferatais (fokaliai su komedo nekrozėmis ir kalcifikatais), suformuotais ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutinio ir kiek stambesnio kalibro, ovaliais/apvaliais, polimorfiškais, su nukleole branduoliais. Šalia - ribotas navikas (mikroskopiškai 1,6 mm), suformuotas fibrozuotoje stromoje plintančių solidinių, lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 1/10 DPRL.  DCIS struktūros siekia medialinį rezekcijos kraštą, 0,15 mm nuo poodinio rezekcijos krašto, 0,5 mm nuo giliojo krašto.. 1. 17 blokas:  INVAZYVI KARCINOMA:   Estrogenų receptoriai: vidutinis branduolių nusidažymas 70% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  Pr
answer:  10%.

 33%|███▎      | 216/661 [06:04<12:55,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- deš. pažasties sarginiai limfmazgiai, skubu  4(3)- deš. krūties sektorius, planinis. 4(3). Krūties sektorius 6,5x5x2,5 cm, su odos lopu 4x2 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 13x11x10 mm (sudėtas visas), nnuo artimiausio rezekcijos krašto 0,2 cm, nuo odos 2,5 cm.. 1(1a). Viršutinis kraštas. Krūties audinys be patologinių pokyčių.    2(1b). Apatinis kraštas. Krūties audinys be patologinių pokyčių.    3(2). Deš. pažasties sarginiai limfmazgiai. Reaktyvi limfadenopatija (3 l/m).     4(3). Deš. krūties sektorius. Krūties invazyvi duktalinė karcinoma,    vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą),   pT1c (13 mm navikas)   pN0(sn)(3 l/m)   pLVI-0 (limfovaskulinė invazija neidentifikuota)   pR0(radikalus pašalinimas).   Naviko imunotipas nustatytas biopsijoje (B23-15090):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.    Krūties fibrocistiniai pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).. 1(1a). Viršutinis kraštas. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2(1b). Apatinis kraštas. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(2). Deš. pažasties sarginiai limfmazgiai. limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.  4(3). Deš. krūties sektorius.  Krūties audinyje - navikas, suformuotas lizdų, trabekulių, kribriforminių ir solidinių struktūrų. Naviko ląstelės su negausia, eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais, fokaliai su smulkiomis nukleolėmis. Mitozių navike iki 6/10DPRL.  Aplinkiniame krūties audinyje smulkūs, dalis ektatiški latakai, kloti dvisluoksniu epiteliu, su periduktaline limfocitine infiltracija. Dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. nan
answer:  0,

 33%|███▎      | 217/661 [06:06<12:51,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas kairės krūties kvadrantas  - planinis tyrimas  2 ėminio aprašas: N2a kraštai  3 ėminio aprašas: N2b kraštai  4 ėminio aprašas: N3: kairės pažasties sarginiai limfmazgiai  5 ėminio aprašas: N4: papildomas kraštas. 1. Krūties sektorius 4,5x4x3 cm, be odos, žymėtas viela. Vielos projekcijoje neaiškių ribų, gelsvai pilkšvas, standokas židinys 10x10x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, žymėtas metaliniu spaustuku.  2. Riebalinio/fibrozinio audinio fragmentas 1,5x1x0,7 cm. v/m  3. Riebalinio/fibrozinio audinio fragmentas 1,2x1x0,6 cm. v/m  4. Riebalinio audinio fragmentai, bendras dydis 3x2,5x0,6 cm. Rasti 3 limfmazgiai iki 1,2 cm. v/m  5. Riebalinio audinio fragmentas 1,5x1x0,4 cm. v/m. 1. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė tubulinė karcinoma;   pT1b(10 mm) pLVI-0 pN0(0/4) pR0.  Naviko imunotipas (priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 98% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 4%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).    2. Riebalinio audinio fragmentas be patologinių pokyčių.  3. Riebalinio audinio fragmentas be patologinių pokyčių.  4. Limfmazgiai(3) be patologinių pokyčių.  5. Riebalinio audinio fragmentas be patologinių pokyčių.. 1. Krūties audinį infiltruoja duktalinės struktūros (100%) iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.  Šalia naviko latakai su kribriforminiais proliferatais iš navikui analogiškų ląstelių. Invazyvios struktūros židiniškai 1 mm nuo operacinio krašto.  Intravaskulinio plitimo nestebima.  2. Riebalinio audinio fragmentas be patologinių pokyčių.  3. Riebalinio audinio fragmentas be patologinių pokyčių.  4. Limfmazgiai(3) be patologinių pokyčių.  5. Riebalinio audinio fragmentas be patologinių pokyčių.. nan
answer:  1a

 33%|███▎      | 218/661 [06:08<12:54,  1.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.deš krūtis, planinis.   2. deš pažasties sarginiai l/m, planinis.. 1. Krūtis, 1068 g svorio, 28x11,5x5 cm. Krūties audinyje pilkšvas, standus, aiškių ribų, kiek mucininis I navikas 12x12x10 mm (krašte pereina į skiltėta struktūrą), esantis 3 cm nuo giliojo rezekcijos pjūvio, nuo odos - 1,2 cm. Šalia naviko 0,3 cm atstumu, pilkšvas, ribotas židinys 6x5x4 mm. Spenelio projekcijoje - pilkšvas, standus II navikas 20x20x12 mm, esantis 1,6 cm nuo giliojo rezekcijos pjūvio, nuo odos - 2,6 cm.  2. Riebalinio audinio fragmentai, bendras dydis 3,5x3x0,8 cm. Rasti 3 limfmazgiai iki 2,4 cm.. Paruošti pjūviai Prosigna.  1. Krūties invazyvi blogai diferencijuota (G3, 8. pagal Nottingham) multižidininė karcinoma: mucininė karcinoma (6,5 mm, 13 mm židiniai) ir mišri mucininė-duktalinė karcinoma (20,5 mm židinys).  SUMINIS TNM: pT2(m)(6,5 mm, 13 mm, 20,5 mm navikai) pN0(sn)(0/3) LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis, komedo tipai). R0(radikali rezekcija).    Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 75% naviko ląstelių.  HER2: neigiama (1+)  Ki67: proliferacinis indeksas 15%.    2. Sarginiai limfmazgiai. Reaktyvi limfadenopatija (3 l/m).. 1. SPENELIS: normalios histologinės struktūros.   NAVIKAS (6,5 mm, 13 mm, 20,5 mm) ekspansyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais ir solidiniais plotais mucinuose besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 13/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.   2. 3 limfmazgiai su sinusų histiocitoze antriniais folikulais ir lipomatoze.. 1. Navikas (14 blokas):   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 75% naviko ląstelių branduoliuose.  HER2: silpnas - vidutinė necirkuliari reakcija, 10%  naviko l
answer:  ąst

 33%|███▎      | 219/661 [06:09<12:41,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2). Kairės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko - extra.  2(1). Pašalinta kairė krūtis - planinis tyrimas.. 2. Krūtis 859 gramų svorio, 20x14x5 cm dydžio. Krūties audinyje, lateralinių kvadrantų riboje, rusvas, gleivėtas, elastingas navikas 5,5x4,2x3,5 cm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos - 0,2 cm. Oda naviko projekcijoje be makroskopinių pokyčių.. 1(ekstra). Reaktyvi limfadenopatija (3 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mišri duktalinė - mucininė karcinoma, SUMINIS TNM: pT3(55 mm navikas) pN(sn)(0/3 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis tipas).    Imunofenotipas(biopsijoje):   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 5% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.. 1(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  2. Krūtyje - navikas (55 mm) infiltratyviu ir ekspansyviu augimo frontu, suformuotas trabekulinėmis struktūromis, lizdais ir solidiniais plotais ir mikropapilinėmis struktūromis, fokaliai ekstraląsteliniuose mucinuose(~50% ploto) besidėstančių ląstelių vidutinio gausumo ryškia eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 7/10 DPRL. Greta dilatuoti kanaliukai su intraduktaliniais solidiniais proliferatais iš analogiškų navikui ląstelių.. HER2: silpna-vidutinė r-ja <10% naviko ląstelių.
answer:  3.

 33%|███▎      | 220/661 [06:11<12:51,  1.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.N2a kraštai  - skubus tyrimas - be naviko   2.N2b kraštai  - skubus tyrimas - be naviko  3.N1 pašalintas kairės krūties kvadrantas - planinis tyrimas  4.N3 kairės pažasties sarginiai limfmazgiai - planinis tyrimas. 3(N1). Krūties sektorius 9x6x3,6 cm su odos lopu 7,5x1,9cm. Pjūvyje balkšvas, stansu, aiškių ribų navikas 1,4x1,4x1,1 mm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos – 1,9cm. Greta naviko - du atskiri balkšvi standūs židiniai:  I - 0,3x0,3x0,3x, nuo naviko nutolęs 0,6 cm, nuo artimiausio rezekcijos krašto - 2 cm.  II - 0,3x0,3x0,3x, nuo naviko nutolęs 2 cm, nuo I židinio - 0,7cm, nuo artimiausio rezekcijos krašto - 1 cm.  4(N3). Riebalinio audinio fragmentas 10,5x7,5x3 cm (Pažasties narveliena cm). Rasta 16 limfmazgių iki 1,5 cm.. 1(N2a). Krūties audinys.  2(N2b). Krūties audinys.  3(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(m) (1,4 cm, 0,3 cm ir 0,3 cm židiniai) pN1a(2/16 l/m, mts 0,2 cm ir 0,7 cm; ekstranodalinis plitimas). LVI2(limfovaskulinė naviko invazija, smulkiose struktūrose).  4(N3). Duktalinės adenokarcinomos metastazės 2/16 limfmazgiuose (mts 0,2 cm ir 0,7 cm; ekstranodalinis plitimas).. 1(N2a). Krūties audinyje - negausūs smulkūs fibrozės židiniai su negausiais smulkiais ar kiek stambesnio kalibro kanaliukais, išklotais dvisluoksniu epiteliu.  2(N2b). Krūties audinyje - negausūs smulkūs fibrozės židiniai su negausiais smulkiais ar kiek stambesnio kalibro kanaliukais, išklotais dvisluoksniu epiteliu.  3(N1). Krūties audinyje - trys panašios architektūrinės ir citologinės išvaizdos naviko židiniai: solidines, trabekulines, smulkias tubulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navikuose iki 12 / 10 DPRL.   4(N3). Aukščiau aprašyto naviko metastazės 2/16 limfmazgiuose (mts 0,2 cm ir 0,7 cm; ekstranodalinis plitimas).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 25%.. 3(N1). HER2: silpnas(+) membraninis dažymasis 20% naviko ląstelių.
answer:  3(n

 33%|███▎      | 221/661 [06:13<12:22,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais spikuliuotais kontūrais, su UG fiksuojama kraujotaka, ~10x12 mm dydžio navikas dešiniojoje krūtyje už spenelio/spenelyje, paimti trys biopsiniai stulpeliai histologijai.. 3 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 13 mm; III - 14 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja duktalinės struktūros, smulkūs kribroziniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 2%.
answer:  0

 34%|███▎      | 222/661 [06:14<12:07,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Papildyta HER2 FISH.  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+).  Ki67 proliferacinis aktyvumas 3%.  HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).. Bioptate krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais besidėstančių ląstelių negausia-vidutinio gausumo eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 2/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: vidutinis visos membranos nusidažymas 15% naviko ląstelių.  Ki67 proliferacinis aktyvumas 3%.
answer:  1b

 34%|███▎      | 223/661 [06:16<12:14,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. deš krūtis su pažasties l/m, planinis.. Krūtis 960 g svorio, 21x17x6 cm su raumens fragmentu 3x1,7x0,5 cm. Krūties audinyje daugybiniai, balkšvi standūs navikai:  I - 1,7x1,4x1 cm, makroskopiškai infiltruojantis raumeninį audinį, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos 2,5 cm;   II - 1,1x0,9x0,7 cm, nuo I naviko nutolęs 1 cm, nuo artimiausio rezekcijos krašto nutolęs mažiau 0,1 cm, nuo odos - 1,3 cm;   III - 1x0,5x0,7 cm, nuo I naviko nutolęs 1,5 cm, nuo artimiausio rezekcijos krašto nutolęs 2,2 cm, nuo odos - 3 cm;  IV - 3,3x2,2x3 cm, nuo III naviko nutolęs 1 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos - 3,5 cm;  V - 2,5x1x1,5 cm, nuo IV naviko nutolęs 2 cm, nuo artimiausio rezekcijos krašto nutolęs 3,7 cm, nuo odos - 1,2 cm;  VI - 0,6x0,4x0,4 cm, nuo V naviko nutolęs - 4 cm, artimiausio rezekcijos krašto nutolęs 4 cm, nuo odos - 2,5 cm;  VII - 1,5x1,2x1,2 cm, nuo VI naviko nutolęs - 2 cm, artimiausio rezekcijos krašto nutolęs 1,7 cm, nuo odos - 2 cm;  VIII (intramamarinis limfmazgis) - 1,1x0,6x0,5 cm, nuo VII naviko nutolęs - 1 cm, artimiausio rezekcijos krašto nutolęs 2 cm, nuo odos - 2 cm;  Atskirai tame pačiame inde pažastie narveliena 9x5x2 cm. Rasta 20 limfmazgių iki 1 cm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma su mikropapiliniu komponentu; pT2(m) (7 navikiniai židiniai nuo 6mm iki 33mm); pN3a (16 iš 20 l/m).. Krūties audinyje 7 navikiniai židiniai (nuo 6mmm iki 33mm): negausios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 3/10 DPRL. Visuose navikiniuose židiniuose yra daugiau ar mažiau išreikštas mikropapilinis augimo komponentas.  Iš rastų 20 limfmazgių 16 su metastazėmis iki 10mm.  Naviko židiniai giliajame rezekcijos krašte.. nan
answer:  0,

 34%|███▍      | 224/661 [06:18<11:58,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but.  1  biopsinis  stulpelis   2 but.  2 biopsiniai stulpeliai. 1. Biopsinis stulpelis 7 mm ilgio.   2. 2 biopsiniai stulpeliai: I - 5 mm; II - 6 mm.. 1. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma.   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%. Karštame taške 20%.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.    2. Krūties fibrocistiniai pokyčiai, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).. 1. Krūties audinyje - navikas: trabekulės, smulkūs lizdai, solidiniai kompleksai ir pavienės tubulės, suformuotos ląstelių su negausia eozinofiliška citoplazma, vidutinio kalibro, netaisyklingo kontūro, hiperchromiškais, vidutiniškai polimorfiškais branduoliais. Mitozių navike neidentifikuota. Navike ryškūs koaguliaciniai artefaktai.   2. Fibrozuotas krūties audinys su smulkiais latakais, klotais dvisluoksniu ar hiperplastišku epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).. Blokas 1:  CK5: (-).   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių. Karštame taške 20%.  Pro
answer:  0

 34%|███▍      | 225/661 [06:20<12:23,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1a- viršutinis kraštas, skubu  2 ėminio aprašas: 1b- apatinis kraštas, skubu  3 ėminio aprašas: Krūties kvadrantas - planinis  4 ėminio aprašas: kairės pažasties limfmazgiai - planiškai  5 ėminio aprašas: papildomas apatinis kraštas - planiškai. 3. Krūties sektorius 9x6x3,5 cm su odos lopu 8x4 cm (rezekcijos kraštas dažytas mėlynu tušu). Krūties audinyje - balkšvas, standus, gan aiškių ribų navikas 2,5x2x2,2 cm, nuo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 0,5 cm.  4. Riebalinio audinio fragmentas  8x7x2,5 cm. Rasta 17 limfmazgių iki 1 cm.  5.Riebalinio audinio fragmentas  1,7x0,8x0,5 cm. v/m. 1. Fibrocistiniai krūties pokyčiai: paprasta epitelio hiperplazija, apokrininė epitelio metaplazija.   2. Krūties lobulinė karcinoma in situ (LCIS).  3. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) lobulinė karcinoma, TNM: pT2(23 mm naviko židinys), LVI0(neidentifikuota), pN0(0/15 l/m). Krūties lobulinė karcinoma in situ (LCIS). HER2:reakcijos nėra (0). Progesterono receptoriai: reakcijos nėra. Fibrocistiniai krūties pokyčiai.  4. Reaktyvi limfadenopatija (15 l/m).  5. Krūties lobulinė karcinoma in situ (LCIS).. 1. Krūties audinyje gausūs nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu su fokalia apokrinine epitelio metaplazija ir nežymiai dilatuoti kanaliukai, kloti hiperplastišku epiteliu.   2. Krūties audinyje gausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.   3. Krūties audinyje - hialinizuotoje stromoje navikas (23 mm mikroskopiškai) infiltratyviu augimo frontu, suformuotas trabekulinių, juostinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, ekscentriškais, vidutiniškai polimorfiškais, hiperchromiškais branduoliais, nežymiai paryškėjusiais branduolėliais. Mitozių navike iki 3/10DPRL. Limfovaskulinė naviko invazija neidentifkuota (LVI0). Perineurinis naviko plitimas. Invazyvus navikas nuo artimiausio rezekcijos krašto nutolęs per 3 mm. Greta naviko negausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta daugybiniai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.  4. Penkiolika limfmazgių (15 l/m) su sinusų histiocitoze ir gausiais antriniais limfiniais folikulais.  5. Krūties audinyje gausūkeli smulkūs kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.. Blokas 5:  HER2: reakcijos naviko ląstelių membranoje nėra.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.
answer:  0

 34%|███▍      | 226/661 [06:22<12:59,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2A) - kraštas-extra - be naviko    2(N2B) - kraštas-extra - be naviko    3(N3) - l/m-extra - be naviko    4(N1) - sektorius - planinis tyrimas. 4. Krūties sektorius 10x4,5x6 cm, su odos fragmentu 9,5x3 cm, žymėtas dviem vielom (atstumas tarp vielų - 5,5 cm). Krūties audinyje, vienos vielos projekcijoje - neaiškių ribų, fibrozės plotas 2x1,6 cm, žymėtas metaliniu spaustuku, nuo giliojo rezekcijos krašto nutolęs 0,3 cm. Krūties audinyje, kitos vielos projekcijoje neaiškių ribų židinys 1x1 cm plote, nuo giliojo rezekcijos krašto nutolęs 0,3 cm. Pakitimai sudėti visi.. 1(2a, ekstra). "Kraštai":   dažais žymėtame krašte - fibrozuotas riebalinis audinys; be naviko.   Planinio tyrimo metu tirtoje, dažais nežymėtoje medžiagoje - krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: kribriforminis tipas; 3,2 mm židinys).  2(2b, ekstra). "Kraštai":   dažais žymėtame krašte - fibrozuotas riebalinis audinys; be naviko.  Planinio tyrimo metu tirtoje, dažais nežymėtoje medžiagoje - fibrozuotas krūties audinys su koaguliaciniais artefaktais.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (1 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (du naviko židiniai: I - 9 mm; II - 4 mm) N0(sn) (0/1 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.     Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   DCIS komponentas nuo sektoriaus rezekcijos krašto nutolęs - 0,1 mm.. 1(2a, ekstra). "Kraštai": dažais žymėtame krašte - fibrozuotas brandžių lipocitų suformuotas audinys be naviko.   Planinio tyrimo metu tirtoje likusioje medžiagoje - 3,2 mm židinys su intraduktaliniais kribriformiais, žemiau, punkte Nr.4, aprašyto naviko proliferatais.   2(2b, ekstra). "Kraštai": dažais žymėtame krašte - fibrozuotas brandžių lipocitų suformuotas audinys be naviko.   Planinio tyrimo metu tirtoje likusioje medžiagoje - fibrozuotas krūties audinys su gausiais koaguliaciniais artefaktais.    3(ekstra). "Sarginiai limfmazgiai": vienas (1) limfmazgis su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS (du židiniai: I - 9 mm (su aplinkine fibroze ir in situ komponentu ~15 mm židinys); II - 4 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios kai kur netaisyklingos duktalinės, retos kribriforminės ir smulkios trabekulinės bei lizdinės naviko struktūros ir kai kur pabiros saikingai ar vidutiniškai polimorfiškos ląstelės, negausia ir vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 3/10 DPRL. I židinyje tubulės retos, II tubulės dominuoja. Gausūs mikrokalcifikatai. Pirmame židinyje - fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija, ryškesnė fibrozė, eritrocitų ekstravazija, hemosiderofagai (g.b. ankstesnės biopsijos vieta).   APLINKA: šalia naviko - gausūs solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: in situ komponentas nutolęs - 0,1 mm.. nan
answer:  1(

 34%|███▍      | 227/661 [06:23<12:23,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G1; 5 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 10% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.. Krūties audinį 1-me bioptate infiltruoja iki 11 mm :   - pavienės duktalinės struktūros ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono receptoriai: stipri (+
answer:  10%

 34%|███▍      | 228/661 [06:25<12:55,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.   5. papildomas kraštas, planinis.. 4. Krūties sektorius 8,5x6x4 cm su odos lopu 5x3 cm. Pjūvyje balkšvas, standus, neaiškių ribų navikas 1,4x1,2x0,8 cm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos 2 cm.  5. Riebalinio audinio fragmentas 2,3x2x 0,6 cm. Sudėtas visas.. Atsakymas papildytas HER2 FISH tyrimo rezultatu (HER2 geno amplifikacija nenustatyta):   1(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).    2(ekstra). "Kraštai": krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis tipas).   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 19,5 mm) N0(sn) (0/3 l/m),    LVI-2 (limfovaskulinė invazija smulkiose šakose).   Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).   5. "Papildomas kraštas": fibrozuotas krūties audinys; be naviko.. 1(ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   2(ekstra). "Kraštai": keli dilatuoti latakai su intraduktaliniais kribriforminiai vidutiniškai polimorfiškų ląstelių proliferatai, vienas nedidelis nekrozės židinys. ----  3(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS (mikroskopiškai ~19,5 mm skersmens): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retos duktalinės, dominuojančios kribriforminės, besiliejančios trabekulinės ir nedidelės lizdinės naviko struktūros, suformuotos vidutiniškai ar fokaliai ryškiau polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki 5/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Pavieniai mikrokalcifikatai.   Fokaliai kiek gausesnė židininė limfocitinė infiltracija bei fibrozė (g.b. ankstesnės biopsijos vieta).   APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.  5. "Papildomas kraštas": fibrozuotas krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.. 4. Navikas (blokas 28):  HER2: vidutinė (++) necirkuliari reakcija, 10% naviko ląstelių membranoje.
answer:  1.

 35%|███▍      | 229/661 [06:27<12:43,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sarginiai l/m - extra;  2. Kairė krūtis - planinis.. 2. Krūtis 760 gramų svorio, 21x16,5x4,5 cm. Pjūvyje, centrinėje dalyje - balkšvas, standus, gan aiškių ribų navikas 8x4x7 mm, nuo odos nutolęs 2,8 cm, nuo artimiausio rezekcijos krašto - 0,3 cm. 1,5 cm nuo naviko - balkšvas, standus, židinys 1x0,8x0,8 cm, nuo artimiausio rezekcijos krašto nutolęs 1,3 cm, nuo odos - 1,5 cm. 7,5 cm nuo naviko - riebalinis inkapsuliuotas plotas 5x4x2,5 cm.. 1. Reaktyvi limfadenopatija (4 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.2): pT1b(m) (0,8 cm ir 0,9 cm naviko židiniai) pN(sn)0 (0/4 l/m). LVI0(limfovaskulinės naviko invazijos nėra). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribrozinis tipas).  ---  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: Neigamas (imunohistocheminė reakcija ribinė (2+), HER2 geno amplifikacija (FISH) nenustatyta).  Ki67: 20%.. 1. Sinusų histiocitozė keturiuose (4) limfmazgiuose.  2. KRŪTIES SPENELIS: Be patologijos.  KRŪTIS: Krūties audinyje - du (2) panašios histologinės ir citologinės išvaizdos naviko židiniai (0,8 cm ir 0,9 cm): kribrozines, susiliejančias tubulines naviko struktūras formuoja ląstelės su gan gausia eozinofiline citoplazma, vidutinio kalibro ar stambesniais kiek netaisyklingais/polimorfiškais, su nukleole branduoliais; mitozių navike iki 5 / 10 DPRL. Gan gausūs vidutinio kalibro kanaliukai su solidiniais, kribroziniais intraduktaliniais ląstelių su eozinofiliška citoplazma, vidutinio kalibro ir stambiais, polimorfiškais branduoliais proliferatais spindžiuose.. nan
answer:  1a

 35%|███▍      | 230/661 [06:28<12:07,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 9 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%, vietomis iki 80%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 60%, vietomis iki 80%.
answer:  3

 35%|███▍      | 231/661 [06:30<12:04,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b) - apatinis kraštas, skubu  3(2) - Kairės pažasties sarginiai limfmazgiai, skubu  4(3) - Kairės krūties sektorius, planinis. 4(3). Krūties sektorius 9x8,5x2 cm, su odos lopu 8,5x2 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 8x7x5 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2 cm.. 1(1a). Riebalinis audinys.  2(1b). Krūties audinys.  3(2). Reaktyvi limfadenopatija (2 l/m).  4(3). Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1b(navikas 6,25 mm), pN0(sn)(0/2 l/m), LVI0. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).   HER2: reakcija neigiama (1+).. 1(1a). Riebalinis audinys su plonomis fibrozinėmis septomis ir smulkiomis kraujagyslėmis.  2(1b). Riebalinis audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(2). Du limfmazgiai su sinusų histiocitoze ir pavieniais antriniais limfiniais folikulais.  4(3).Krūties audinyje, hialinizuotoje stromoje plinta navikas (6,25 mm mikroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių ir tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su vidutiniškai polimorfiškais, hiperchromiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 12/10DPRL. Limfovaskulinio plitimo neidentifikuota (LVI0). Navikas nuo artimiausio rezekcijos krašto nutolęs per 4mm. Krūties audinyje gausūs dilatuoti kanaliukai užpildyti kribrifominių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais.. Blokas 12:  HER2: silpna (+) necirkuliari reakcija, 15%  naviko ląstelių membranoje.
answer:  0

 35%|███▌      | 232/661 [06:32<12:23,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko    2(N2b) kraštai - skubus tyrimas - be naviko    3(N3): dešinės pažasties sarginis limfmazgis - skubus tyrimas - be naviko- (2l/m)  4(N1): pašalintas markiruotas dešinės krūties plotas su vielute  - planinis histologinis tyrimas. 4. Krūties sektorius 13x11x6 cm su odos lopu 9x2,5 cm, žymėtas viela. Vielos projekcijoje, pjūvyje balkšvas, standus, neaiškių ribų navikas 20x12x20 mm, nuo artimiausio rezekcijos krašto (dažyto mėlynu tušu) nutolęs 1,5 cm, nuo odos – 4 cm. Naviką apsupa balkšvas, standi, neaiškių ribų fibrozės zona 5,2x4,4x4,5 cm, nuo artimiausio rezekcijos krašto nutolusi 0,2 cm, nuo odos - 3 cm.. 1(N2a, ekstra) kraštai. Krūties audinys su židinine apokrinine metaplazija ir įprastine duktaline hiperplazija.     2(N2b, ekstra) kraštai. Krūties audinys be patologinių pokyčių.     3(N3, ekstra) dešinės pažasties sarginis limfmazgis. Reaktyvi limfadenopatija (2 l/m).    4(N1). Dešinės krūties plotas.  Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham sistemą) lobulinė karcinoma, suminis TNM:   pT3 (52 mm navikas)    pN0(sn)(0/2 l/m)    pLVI-0(limfovaskulinė invazija neidentifikuota)    pR0(radikalus pašalinimas).   Imunotipas priešoperaciname biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.    Krūties lobulinė karcinoma in situ (LCIS).. 1(N2a, ekstra) kraštai. Krūties audinys su smulkiais ir vidutinio kalibro kanaliukais, klotais dvisluoksniu epiteliu, su židinine apokrinine metaplazija ir įprastine duktaline hiperplazija.   2(N2b, ekstra) kraštai. Krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu  3(N3, ekstra) dešinės pažasties sarginis limfmazgis. 2 limfmazgiai su sinusų histiocitoze, lipomatoze.  4(N1). Dešinės krūties plotas. Krūties audinyje - infiltratyviu frontu plintantis, 52 mm dydžio (mikroskopiškai) navikas, suformuotas trabekulių, grandinėlių, smulkias tubulių. Naviko ląstelės su vidutinio gausumo, blyškia eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar kiek netaisyklingo kontūro, vidutiniškai, vietomis ryškiai polimorfiškais branduoliais su aiškiomis nukleolėmis. Mitozių navike iki 3/10DPRL.  Šalia naviko - dilatuoti kanaliukai su solidiniais ar kribriforminiais proloferatais iš analogiškų navikui ląstelių.. 3. Limfmazgiai:   Blokas 4: Cam5,2: dendritinės ląstelės +.   Blokas 16: Cam5,2: dendritinės ląstelės +.   Blokas 17: Cam5,2: dendritinės ląstelės +.   4. Navikas:   Blokas 25: CK14: mioepitelis aplink normalius latakus ir LCIS; navikas CK14(-).   E-cadhe
answer:  100%

 35%|███▌      | 233/661 [06:34<13:30,  1.89s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pašalintas kairės krūties sektorius - extra  2(N2). Deš. pažasties sarginiai l/m - Extra  3. Kair. pažasties sarginiai l/m - Extra  4(N4). Deš.krūtis.   5(N5). Kairė krūtis.. 4. Krūtis 1000 gramų svorio, 26x20x5 cm. Krūties audinyje, lateralinių kvadrantų riboje - balkšvas, standus, neaiškių ribų I navikas 23x21x15 mm, nuo odos nutolęs 3,5 cm, nuo giliojo rezekcijos krašto - 2,5 cm. Medialiau, balkšvas, standus, neaiškių ribų II navikas 24x13x11 mm, nuo odos nutolęs 2 cm, nuo giliojo rezekcijos krašto - 4 cm, nuo I naviko - 0,3 cm. 26-32 kasetėse- riba tarp navikų, pjūvis per I naviką žymėtas mėlyna spalva, pusė link II naviko- juoda. Krūtis fibrozuota 13x12x3 cm plote.  5. Krūtis 780 gramų svorio, 23x18x6 cm su defektu odoje 7x6 cm plote (šalinto sektoriaus vieta). Krūties audinyje, fibrozės zona 12x6x3,5 cm, vietomis siekia rezekcijos kraštą, nuo odos nutolęs 1 cm. Makroskopiškai navikas neidentifikuojamas.. 1(Extra). Krūties (kairiosios) invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(25 mm) N(sn)1mi(mikromts 1/4 l/m), LVI-2(limfovaskulinė invazija).   Imunofenotipas:   Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  HER2 imuninė reakcija: neigiama (1+).  Ki67: 5%.  2(Extra)(Deš. pažasties sarginiai l/m). Reaktyvi limfadenopatija (2 l/m).  3(Extra)(Kair. pažasties sarginiai l/m). Duktalinės karcinomos mikrometastazė 1/4 limfmazgyje (0,45 mm).   4. Krūties (dešiniosios) invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT(m)2(2 naviko židiniai: 23 mm ir 24 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).  5. Lobulinė karcinoma in situ (LCIS). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. 1(Extra). Krūties audinyje - ribotas navikas (mikroskopiškai 25 mm), suformuotas fibrozuotoje stromoje plintančių lizdinių, trabekulinių ir fokaliai besiliejančių liaukinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia, fokaliai PASD+ grūdėta ar vakuolizuota citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 6/10 DPRL. Pavieniai smulkūs kalcifikatai. Limfovaskulinė invazija smulkioje šakoje.  2(Extra). 2 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze.  3(Extra). 4 limfmazgiai su pirminiais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze. Papildomuose (ne extra) pjūviuose, viename limfmazgyje (limfoidiniame audinyje ir kapsulėje) atsiranda smulkūs (iki 0,45 mm) lizdai, suformuoti tubulinių ir lizdinių naviko struktūrų iš ląstelių eozinofiliška citoplazma, vidutinio kalibro, kiek polimorfiškais, su nukleole branduoliais.  4. Krūties audinyje - 2 navikai (mikroskopiškai 23 mm ir 24 mm), suformuoti fibrozuotoje stromoje plintančių trabekulinių struktūrų, grandinėlių, smulkių grupių ir pabirų ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 2/10 DPRL. Pavieniai smulkūs kalcifikatai, negausūs makrofagų židiniai. Aplink yra dilatuotų kanaliukų, užpildytų analogiškomis navikui ląstelėmis bei keli dilatuoti kanaliukai su kribriforminiais intraduktaliniais proliferatais, suformuotais ląstelių vidutiniškai polimorfiškais branduoliais; negausūs kanaliukai su apokrinine metaplazija ar su epitelio hiperplazija bei stulpiniu ląstelių pokyčiu su apikaline sekrecija.  5. Krūties audinyje, fibrozuotoje stromoje vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu; yra dilatuotų kanaliukų, klotų suplokštėjusiu epiteliu, kanaliukų su epitelio hiperplazija ar su apokrinine metaplazija. Yra kanaliukų, užpildytų ląstelėmis gan monomorfiškais branduoliais (LCIS).. 1. Navikas/duktalinė karcinoma (10 blokas):  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  HER2 imuninė
answer:  1+.

 35%|███▌      | 234/661 [06:36<12:35,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 20%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis visos membranos nusidažymas 12% naviko ląstelių
answer:  3b

 36%|███▌      | 235/661 [06:37<12:18,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštai - skubus tyrimas - be naviko  2 ėminio aprašas: N2b -b be naviko  3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - skubus tyrimas 1l/m be navimo  4. (1) ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas. 4(1). Krūties sektorius 8x7x4 cm su odos lopu 7x3 cm, žymėtas viela. Krūties audinyje balkšvas, standus navikas 28x22x27 mm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos – 2,5cm.. 1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (1 l/m).  4(1). Krūties invazyvi, blogai diferencijuota (G3; 9 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 28mm) pN0(sn)(0/1 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-3406:  "Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 35%, vietomis iki 60%.". 1(2a). Krūties audinys su įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  2(2b). Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  3. Vienas(1) limfmazgis be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4(1). Krūties audinyje - navikas, formuojamas solidinių, trabekulinių, kribriforminių struktūrų iš vidutinio/stambaus kalibro ląstelių, eozinofiliška citoplazma, ryškiai polimorfiškais, hiperchromiškais branduoliais; navike - iki 59 mitozių/10 DPRL. Rezekcijos kraštas be naviko.. nan
answer:  1a

 36%|███▌      | 236/661 [06:39<12:14,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2): kairės pažasties sarginis limfmazgis - skubus tyrimas  2(N1): pašalitna kairė krūtis - planinis tyrimas. 2(N1). Krūtis gramų 498 svorio, 23x15x4,5 cm. Krūties audinyje, viršutiniame lateraliniame kvadrante pilkšvas, standus, neaiškių ribų navikas 35x30x22 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 1,5 cm, nuo odos - 1,7 cm.. 1(ekstra). Krūties lobulinės karcinomos metastazė (1/5 l/m 5,5 mm).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(m)(40 mm, 2,3 mm, 1,2 mm navikai) pN1a(sn) (1/5 l/m MTS 5,5 mm) LVI-0(limfovaskulinė invazija neidentifikuota). R0(navikas nuo rez. krašto nutolęs 1,3 mm). Lobulinė karcinoma in situ.    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. 1(ekstra). 1 iš 5 limfmazgių aprašyto naviko metastazė 5,5 mm.  2. Spenelis: Spenelis: latakuose naviko ląstelių intraepitelinis plitimas.  Krūtyje - navikas (40 mm, 2,3 mm, 1,2 mm) infiltratyviu augimo frontu, suformuotas grandinėlėmis, pabirai, trabekulinėmis struktūromis, lizdais besidėstančių ląstelių  negausia - vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, nereguliaraus kontūro ir ovaliais branduoliais ryškiomis nukleolėmis; mitozių 3/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais solidiniais proliferatais iš analogiškų navikui ląstelių.. 2. Navikas(24 blokas): E-cadherin(+++) membr. r-ja 100%; p120-catenin(+++) citopl/ r-ja 100%.
answer:  1(n

 36%|███▌      | 237/661 [06:41<12:13,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai  - skubus tyrimas - be naviko  2(N2b) kraštai  - skubus tyrimas - be naviko  3(N3): kairės pažasties sarginis limfmazgis - skubus tyrimas - viename iš 5 makrometastazė  4(N1): pašalintas kairės krūties kvadrantas - planinis tyrimas. Krūties sektorius 10,5x7,5x4 cm su odos lopu 9x3,5 cm. Krūties audinyje - pilkšvas standus neaiškių ribų navikas 16x16x12 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 1,5 cm.. 1(Extra). Krūties fibrocistiniai pokyčiai.  2(Extra). Krūties fibrocistiniai pokyčiai. Mikrokalcifikatai.  3(Extra). Krūties duktalinės karcinomos metastazės 2/5 l/m (4,2 mm ir 1,3 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(22 mm) N(sn)1a(mts 2/5 l/m: 4,2 mm ir 1,3 mm), LVI-2(limfovaskulinė invazija).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DIN3/DCIS)(solidinė, kribriforminė).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro ir kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu; yra kanaliukų apokrinine metaplazija bei dilatuotų kanaliukų, klotų suplokštėjusiu epiteliu, negausūs smulkūs kalcifikatai.  3(Extra). Dviejuose (2) iš 5 limfmazgių - žemiau (Nr.4) aprašyto naviko metastazės (4,2 mm ir 1,3 mm).  4. Krūties audinyje - navikas infiltratyviais kraštais (mikroskopiškai 22 mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių ir lizdinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais ir kiek nereguliaraus kontūro, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 9/10 DPRL. Šalia yra dilatuotų kanaliukų su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais.. 4. Navikas (22 blokas):  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.
answer:  0

 36%|███▌      | 238/661 [06:42<11:53,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 18 G automatine biopsine adata punktuotas ~9x11 mm patologinis l/m dešiniosios pažasties I lygmenyje, paimti du biopsiniai stulpeliai histologijai (I buteliukas).   2 ėminio aprašas: 2. 18 G automatine biopsine adata punktuotas hipoechogeninis, nelygiais kontūrais, ~18x25 mm navikas dešiniojoje krūtyje ties 9-10 val. vidurinėje/periferinėje dalyse, paimtas vienas biopsinis stulpelis histologijai (II buteliukas).. 1. 2 biopsiniai stulpeliai: I - 9 mm; II - 9 mm.  2. Biopsinis stulpelis 14 mm ilgio.. N1: Limfmazgio bioptatas su duktalinės karcinomos metastaze.  N2: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. N1: Limfmazgio bioptatas su žemiau aprašyto naviko židiniu.  N2: Krūties audinį infiltruoja duktalinės struktūros ir kribroziniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 1
answer:  1a

 36%|███▌      | 239/661 [06:44<11:33,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, nelygiais kontūrais, ~7x7 mm dydžio darinys dešiniojoje krūtyje ties 11 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 8 mm; II - 7 mm; III - 8 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.. Krūties audinį infiltruoja smulkūs solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 4%.
answer:  1a

 36%|███▋      | 240/661 [06:46<12:14,  1.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2) - Kairės krūties kvadrantas, planinis  4(3) - Kairės krūties limfmazgiai, planinis  5.(3)- Kairės krūties limfmazgiai, planinis. ŽR. KOKYBĖS PASTABĄ!  3. Krūties sektorius 8x6x5 cm su odos lopu 6x4 cm. Odoje rusvos dėmės ir dariniai iki 0,7x0,7 cm, artimiausia dėmė siekia rezekcijos kraštą. Pjūvyje:  - pilkšvas, standus, aiškių ribų I navikas 2,1x1,8x2,5 cm, nuo artimiausio rezekcijos krašto (dažyto mėlynu tušu) nutolęs 1,5 cm, nuo odos - 1,3 cm.   - 0,2 cm nuo naviko balkšvas, standus II (?) navikas 0,9x0,7x0,7 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 2 cm, nuo odos - 0,5 cm.   4. Riebalinio audinio fragmentai, bendras dydis 9x6x2,5 cm. Rasta 19 limfmazgių iki 1,8 cm.  5. Riebalinio audinio fragmentas 3x3x1,5 cm. Rasti 2 limfmazgiai iki 1,2 cm.. 1.(1a) Fibrocistiniai krūties pokyčiai.  2.(1b) Fibrocistiniai krūties pokyčiai.  3. Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(m)(du naviko židiniai - 9mm ir 25mm) pN1mi(1/21 l/m; iki 1,09mm); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).  IHC, FISH reakcijos atliktos VPC:B23-714 tyrime:  "Ki67: proliferacinis indeksas 55%.  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Išoriniai IHC:  Estrogenų receptorių raišką teigiama (stipri raiška 100 proc. naviko ląstelių branduoliuose).  Progesteronų receptorių raišką teigiama (vidutinė raiška 50 proc. naviko ląstelių branduoliuose).  HER2 raiška paribinė (2+: silpna cirkuliari raiška 30 proc. naviko ląstelių membranoje)."  Vidutinio laipsnio krūties intraduktalinė karcinoma (DCIS; solidinis tipas; -komedo tipo nekrozės). Fibrocistiniai krūties pokyčiai. Krūties odos seborėjinės keratozės.  4. Duktalinės karcinomos mikrometastazė limfmazgyje (1/19 l/m; iki 1,09mm).  5. Reaktyvi limfadenopatija (2 l/m).. 1.(1a) Riebaliniame audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, apokrininės metaplazijos židiniais.  2.(1b) Riebaliniame audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, apokrininės metaplazijos židiniais.  3. Krūties audinyje du naviko židiniai (9mm ir 25mm), formuojamas solidinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 17 mitozių/10 DPRL; Limfo-Vaskulinė naviko Invazija (LVI) smulkiose kraujagyslėse/limfagyslėse. Krūties audinyje - dilatuoti latakėliai su solidiniais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, apokrininės metaplazijos, paprastos intraduktalinės hiperplazijos židiniais. Krūties odoje - epidermio hiperkeratozė, papilomatozė, besiliejantys epidermio hiperplazijos plotai su pavienių raginių cistų formacija, bazinio sluoksnio hiperpigmentacija.   4. Iš rastų devyniolikos(19) limfmazgių, viename aukščiau aprašyto naviko metastazė (iki 1,09mm).  5. Du(2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.. nan
answer:  1a

 36%|███▋      | 241/661 [06:47<12:08,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: kairės krūties kvadrantas - planinis tyrimas  2 ėminio aprašas: N2a: kraštai  3 ėminio aprašas: N2b: kraštai  4 ėminio aprašas: N3c: kraštai   5 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis. 1. Krūties sektorius 4,7x2,2x4,5 cm su oda 5x2 cm, žymėtas viela. Vielos projekcijoje, pilkšvas, aiškių ribų darinys 10x10x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,5 cm.  2. Riebalinio audinio fragmentas 1,5x1x0,3 cm. v/m  3. Riebalinio audinio fragmentas 1,6x1,3x0,4 cm. v/m  4. Riebalinio audinio fragmentas 2x1,2x0,6 cm. v/m  5. Riebalinio audinio fragmentas 3x2,5x0,7 cm. Rastas 1 limfmazgis 0,9 cm. v/m. 1. Kvadrantas. Krūties vidutiniškai diferencijuota (G2, 7b. pagal Nottingham skalę) invazyvi duktalinė karcinoma, TNM: pT1b(8 mm), LVI-0 (limfovaskulinė invazija neidentifikuota), R0 (radikali rezekcija).  Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 20%.    2. Kraštai. Krūties audinys. Be naviko.  3. Kraštai. Krūties audinys. Be naviko.  4. Kraštai. Krūties audinio fibrozė. Be naviko.  5. Sarginis limfmazgis. Riebalinio-fibrozinio audinio fragmentas. Žr. pastabą.. 1. Krūties audinyje- ekspansyviuaugimo frontu plintantis navikas, sudarytas iš trabekulėmis, lizdais besidėstančių ląstelių vidutinio gausumo šviesiai eozinofiliška cioplazma, ovaliais ar nelygaus kontūro, polimorfiškais branduoliais su ryškiomis nukleolėmis. Navikas nuo rezekcijos krašto 2 mm. Mitozių 13/DPRL.    2. Krūties audinys su pavieniais latakais, klotasi dvisluoksniu epiteliu.   3. Krūties audinys su pavieniais latakais, klotasi dvisluoksniu epiteliu.   4. Krūties audinys su pavieniais latakais, klotasi dvisluoksniu epiteliu.   5. Riebalinio-fibrozinio audinio fragmentas.. nan
answer:  1.

 37%|███▋      | 242/661 [06:49<11:40,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma. Žemo laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 95% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 30% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.. Bioptate - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos tubulėmis ir kribriforminėmis struktūromis besidėstančių ląstelių negausia eozinofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio kalibro, ovaliais branduoliais; mitozių 0/10 DPRL. Dilatuoti latakai su intraduktaliniais kribriforminiais prloliferatias iš analogiškų navikui ląstelių.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 95%.  Progesterono receptoriai: (+++)(brand. r-ja) 30%.  HER2: silpnas dalies membranos nusidažymas 5% naviko ląstelių.  Ki67 proliferacinis aktyvumas 5%.  CK14(-);
answer:  0

 37%|███▋      | 243/661 [06:51<11:24,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 5 mm.. Krūties invazyvi duktalinė karcinoma (ne mažiau kaip gerai diferencijuota / G1 / 5 balai pagal Nottingham).     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 3%.. Tubulines (80%), pavienes smulkias kribriformines naviko struktūras formuoja ląstelės su saikinga švelniai eozinofiline citoplazma, smulkiais ar kiek stambesnio kalibro kiek netaisyklingais, dalis su smulkia nukleole branduoliais; mitozių navike iki 1 / 10 DPRL.. Navikas:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Prolife
answer:  3%

 37%|███▋      | 244/661 [06:52<11:19,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: kairė krūtis su pažasties limfmazgiais, planinis. Krūtis 865 g svorio, 21x19x5,5 cm, su pažasties narveliena 10x7,5x3 cm. Krūties audinyje, užspenelinėje srityje, balkšvas, standus, neaiškių ribų I navikas 2,5x1,7x1,5 cm, esantis 1,2 cm nuo artimiausio rezekcijos pjūvio, nuo odos - 2,5 cm. 0,8 cm atstumu nuo I-ojo naviko balkšvas, standus II navikas 0,6x0,5x0,5 cm (sudėtas visas), nuo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 5 cm. Bendras didžiausias navikų matmuo 4 cm. Pažasties narvelienoje rasta 10 limfmazgių, didžiausias 1,4 cm.  Gilusis rezekcijos kraštas dažytas juoda spalva.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2 (40mm); pN2a (4 iš 10 l/m).. Krūties audinyje 40mm navikas iš dviejų susijusių dalių: pavienės duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 18/10 DPRL.  Intravaskulinio naviko plitimo židiniai.  Iš rastų 10 limfmazgių 4 l/m su metastazėmis iki 14mm.  Operacinis pjūvis be naviko.. nan
answer:  3b

 37%|███▋      | 245/661 [06:54<10:58,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm ilgio.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35-40%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+ 35-
answer:  3b

 37%|███▋      | 246/661 [06:55<11:13,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). Kvadranto kraštai.-extra   2(N2). Kvadranto kraštai.-extra   3(N3). Sarginiai l/n.-extra   4(N4). Deš.krūties kvadrantas su naviku.. 4. Krūties sektorius 8x7x3 cm, žymėtas viela. Vielos projekcijoje, pjūvyje balkšvas, standus, neaiškių ribų navikas 9x9x9 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 1 cm. šalia naviko krūties audinys du hemoragijomis ir nekrozės zonomis 1x0,9x0,8 cm plote.. PATIKSLINTA DIAGNOZĖ:  1. Fibrocistiniai krūties pokyčiai.  2. Krūties lobulinė karcinoma in situ (LCIS).  3. Reaktyvi limfadenopatija (2 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) lobulinė karcinoma, TNM: pT1b(9 mm naviko židinys), LVI0(neidentifikuota), pN0(sn)(0/2 l/m). Krūties lobulinė karcinoma in situ (LCIS). HER2: reakcija neigiama (1+). Progesterono receptoriai: reakcijos nėra.. 1. Krūties audinyje židininė fibrozė ir smulkūs bei nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  2. Krūties audinyje keli dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Šalia nežymiai dilatuoti kanaliukai, kloti hiperplastišku epiteliu.  3. Du limfmazgiai su sinusų histiocitoze.  4. Krūties audinyje navikas (9 mm mikroskopiškai), infiltratyviu augimo frontu, suformuotas solidinių, trabekulinių ir pavienių struktūrų su spindžių formacija. Naviko ląstelės negausia eozinofiline citoplazma, vidutiniškai polimorfiškais, hiperchromiškais, smulkiai grūdėtu chromatinu branduoliais, pavieniais paryškėjusiais branduolėliais. Mitozių navike 6310DPRL. Limfovaskulinė naviko invazija neidentifikuota(LVI0).  Krūties audinyje negausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Krūties audinyje židininė histiocitų, pigmentuotų makrofagų, MMN ir svetimkūnio tipo gigantinių daugiabranduolių ląstelių infiltracija.. Blokas 16:  HER2: silpna (+) necirkuliari reakcija, 3%  naviko ląstelių membranoje.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra;  ECAD(-)neigiama r-ja navike.
answer:  1.

 37%|███▋      | 247/661 [06:57<11:00,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 13 mm.. PATIKSLINTA (žr. pastabą):   Invazinė lobulinė karcinoma (mažiausiai iki 11 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 3%.. Krūties audinį 2-se bioptatuose infiltruoja iki 11 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  CK14: neigiama (-) atipinių ląstelių membranoje  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 3% navik
answer:  1b

 38%|███▊      | 248/661 [06:58<10:52,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpeliai. Biopsinis stulpelis 5 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 4 mm);  (G1; 3 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 4%.. Krūties audinį 1-me bioptate infiltruoja iki 4 mm :   - duktalinės netaisyklingos struktūros (100% viso naviko);  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  CK14: neigiama (-) atipinių difuziškai plintančių struktūrų ląstelių membranoje  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose,
answer:  4%

 38%|███▊      | 249/661 [07:00<11:38,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.  2(2b). Kraštai - skubus tyrimas - be naviko.  3. Sarginis limfmazgis - 3 l/m dviejose iš trijų limfmazgių makrometastazės.  4(1). Pašalintas dešinės krūties kvadrantas - planinis tyrimas.. 4(1). Krūties sektorius 14x7x5 cm su odos lopu 13,5x3,5 cm. Krūties audinyje balkšvas, standus, neaiškių ribų navikas 2,3x1,6x1,3 cm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos – 2,3 cm.. PAPILDYTAS ATSAKYMAS:   1(2a, ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties-riebalinis audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos metastazės dviejuose limfmazgiuose (mts 2/3 l/m; iki ~ 19 mm skersmens; su ekstranodaliniu plitimu).     4(1). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (mikroskopiškai navikas 15 mm, žr. pastabą) N1a(sn) (mts 2/3 l/m; iki ~19 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+).  Molekuliniai tyrimai:  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: solidinis, kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Navikas nuo sektoriaus rezekcijos krašto nutolęs 1,7 mm.. 1(2a, ekstra). "Kraštai": fibrozuotas brandžių lipocitų suformuotas fragmentas; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": dviejuose (2) limfmazgiuose žemiau, punkte Nr.4, aprašyto naviko metastazės, iki ~19 mm skersmens, su ekstranodaliniu plitimu; didžiausioje riboti nekrozinės židiniai, supami histiocitų ir hemosiderofagų. Viename limfmazgyje smulkių dilatuotų endotelizuotų ertmių proliferacija su eritrocitais spindžiuose.   4(1). NAVIKAS (mikroskopiškai didžiausias išmatuojamas naviko matmuo - 15 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios kribriforminės, trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai ar ryškiau polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, varijuojančio dydžio nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 40/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai gausesnė perinavikinė limfocitinė infiltracija. Periferijoje fibroadenomatoziniai stromos pokyčiai. Navike - ribotas nekrozės židinys (g.b. ankstesnės biopsijos vieta).    APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: navikas nuo artimiausio rezekcijos krašto nutolęs - 1,7 mm.. 4(1). Navikas (blokas 14):  CK14(+) silpna r-ja naviko ląstelių membranoje; GATA3(+++)(brand.r-ja)100%.   HER2: vidutinė (++) necirkuliari reakcija, 10% naviko ląstelių membranoje.
answer:  4(

 38%|███▊      | 250/661 [07:02<12:05,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 16 G automatine biopsine adata punktuotas hipoechogeninis, nelygiais kontūrais, ~6x9 mm dydžio satelitas dešiniojoje krūtyje ties 6-7 val. vidurinėje dalyje, paimti du biopsiniai stulpeliai histologijai (I buteliukas).   2 ėminio aprašas: 2. 16 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~16x28 mm dydžio navikas dešiniojoje krūtyje ties 9 val. vidurinėje dalyje, paimti du biopsiniai stulpeliai histologijai (II buteliukas).  3 ėminio aprašas: 3. 16 G automatine biopsine adata punktuotas ~6x8 mm dydžio patologinis intramamarinis l/m dešiniojoje krūtyje ties 10-11 val. periferinėje dalyje, paimti trys biopsiniai stulpeliai histologijai (III buteliukas).. 1. 2 biopsiniai stulpeliai: I - 13 mm; II - 11 mm.  2. 2 biopsiniai stulpeliai: I - 14 mm; II - 16 mm.  3. 3 fragemntuoti biopsiniai stulpeliai: I - 5 mm; II - 8 mm; III - 7 mm.. 1. Satelitas dešiniojoje krūtyje 6-7 val. vidurinėje: krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.  2. Dešiniojoje krūtyje ties 9 val. vidurinėje dalyje: krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.  3. Intramamarinis l/m dešiniojoje krūtyje ties 10-11 val. krūties duktalinės karcinomos metastazės.    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.   Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 15%.. 1. Satelitas dešiniojoje krūtyje 6-7 val. vidurinėje: bioptatuose (2/2) - krūties audinyje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 12/10 DPRL. Dilatuoti latakai su intraduktalinėmis kribriforminėmis struktūromis iš analogiškų navikui ląstelių.  2. Dešiniojoje krūtyje ties 9 val. vidurinėje dalyje: bioptatuose (2/2) - krūties audinyje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 12/10 DPRL. Dilatuoti latakai su intraduktalinėmis kribriforminėmis struktūromis iš analogiškų navikui ląstelių.  3. Intramamarinis l/m dešiniojoje krūtyje ties 10-11 val.: limfmazgyje analogiškos aprašytoms Nr.1 naviko struktūros.. 1. Navikas (1 blokas):  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 5% naviko ląstelių.  Ki67 proliferacinis aktyvumas 15%.
answer:  1a

 38%|███▊      | 251/661 [07:04<11:43,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 9 mm ilgio.. Invazinė lobulinė karcinoma (mažiausiai iki 9 mm);  (G1; 5 b. pgl. Nottingham sist.) 1-me stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.. Krūties audinį 1-me bioptatuose infiltruoja iki 9 mm :   - pabiros ląstelės, juostos ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: neigiama (-) atipinėse struktūrose  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 5% naviko
answer:  1b

 38%|███▊      | 252/661 [07:05<11:23,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Kairė krūtis su limfmazgiais, planinis. Krūtis 1083 g svorio, 25x16x6 cm, su pažasties narveliena 15x11x4 cm. Krūties audinyje, lateralinių kvadrantų riboje balkšvas, standus, aiškių ribų navikas 2,8x2,5x2,5 cm, esantis 0,5 cm nuo artimiausio rezekcijos pjūvio, peraugantis odą 2,4x2 cm plote.   Pažasties narvelienoje rasti 28 limfmazgiai iki 1,2 cm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT2(28 mm) pLVI-0 pN0(0/28) pR0.  Naviko imunotipas (priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 75% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67+ 8%.. Krūties audinyje naviką formuoja duktalinės struktūros (20%), netaisyklingi kribroziniai ir solidiniai kompleksai bei trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL. Navikas infiltruoja odą, bet be išopėjimo.   Operaciniai kraštai, kraujagyslės be navikinių pokyčių.  Limfmazgiai (28) be patologinių pokyčių.. nan
answer:  1.

 38%|███▊      | 253/661 [07:07<11:18,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 pjūvio kraštas, ekstra  2 ėminio aprašas: 2 pjūvio kraštas, ekstra   3. sektorius, planinis.. 3. Krūties sektorius 8x4x6,5 cm, su odos lopu 7x3 cm. Pjūvyje pilkšvas, standus, ribotas navikas 22x20x18 mm, nuo giliojo rezekcijos kraštonutolęs 0,2 cm, nuo odos - 1,6 cm.. 1. Krūties lobulinė karcinoma in situ (LCIS).   2. Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mucininė karcinoma, TNM: pT2(navikas 22 mm), pLVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).  HER2:reakcijos nėra (0).. 1. Krūties audinyje gausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.  2. Krūties adinyje negausūs, minimaliai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  3. Krūties audinyje navikas (22 mm makroskopiškai), suformuotas gausiuose ekstraląsteliniuose mucinuose besidėstančių solidinių, kribriforminių ir negausių mikropapilinių struktūrų. Naviko ląstelės vidutinio gausumo eozinofiline citoplazma, vidutinio kalibro, kiek polimorfiškais branduoliais su negausiomis smulkiomis nukleolėmis. Mitozių navike iki 13/10 DPRL. Limfovaskulinis naviko plitimas neidentifikuotas. Greta naviko negausūs kanaliukai su solidiniais ir kribriforminiais proliferatais, suformuotais iš vidutinio gausumo eozinofiline citoplazma ląstelių, vidutiniškai polimorfiškais, hiperchromiškais branduoliais su pavieniais paryškėjusiais branduolėliais.. Blokas 1:  E-Cadherin: (-)neigiama r-ja proliferatuose  Blokas 7:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 38%|███▊      | 254/661 [07:09<11:03,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 13 mm; II - 13 mm.. Invazinė lobulinė karcinoma (mažiausiai iki 11 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: silpna (+) reakcija, 5% naviko ląstelių.  HER2: reakcija paribinė (2+). Dėl blogos mėginio kokybės ir nepakankamo ląstelių kiekio mėginyje, HER2 amplifikacijos FISH tyrimas nevertintinas.  Ki67: proliferacinis indeksas 15%.. Krūties audinį 2-se bioptatuose infiltruoja iki 11 mm :   - juostos;  - epitelinių smulkių / vidutinio dydžio ląstelių su neryškiai/ vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozės nestebimos.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: silpna teigiama (+)  membraninė reakcija 10proc. atipinėse ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: vidutinė (++) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67: reakcija
answer:  1b

 39%|███▊      | 255/661 [07:10<11:22,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). Sarginiai l/m. - extra  2(N2). Deš.krūtis su navikiniais dariniais.. 2. Krūtis 19x15x6 cm. Spenelis kiek įtrauktas, centre su balkšva, neaiškių ribų dėme 0,4x0,4 cm. Krūties audinyje, centrinėje dalyje ? - pilkšvas, standus, neaiškių ribų navikas 16x16x10 mm, pereinantis į fibrozę. Navikas nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo odos - 2,5 cm. Fibrozės krašte rusvas, gan aiškių ribų darinys 6x5x5 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 3,5 cm.. 1. Limfmazgiai(2) be karcinomos plitimo. Žr. pastabą.   2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma,   pT1c (16 mm) pN0(sn) (0/2 l/m); LVI2 (limfovaskulinė naviko invazija smulkiose limfagyslėse/ kraujagyslėse). Karcinomos imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-6112, žr. pastabą.   Krūties lobulinė karcinoma in situ (LCIS).   Stulpinis epitelio pokytis su epitelio hiperplazija. Krūties intraduktalinė papiloma.. 1. Limfmazgiai(2) su kiek tušuota architektūra, pavieniais antriniais folikulais, negausiais histiocitais sinusuose.   2. Krūties audinyje - navikas, formuojamas infiltratyviai plintančių, glaudžiai besidėstančių grandinėlių, trabekulinių ir pavienių smulkių blogai suformuotų liaukinių struktūrų, smulkių grupių, sudarytų iš nedidelių-vidutinio dydžio poligonalinių ląstelių šviesiai eozinofiliška citoplazma, vidutiniškai polimorfiškais ovaliais ar skeltais branduoliais su vezikulizuotu chromatinu, retomis labai smulkiomis nukleolėmis. Navike iki 3 mitozių/ 10 DPRL. Limfovaskulinė naviko invazija smulkiose limfagyslėse/ kraujagyslėse.   Aplinkiniame audinyje - lobulės su kanaliukais, užpildytais smulkiomis-vidutinio dydžio monotoniškomis ląstelėmis. Keli latakai, kloti stulpiniu epiteliu su apikalinės sekrecijos požymiais, stratifikuotais, hiperchromiškais, nežymiai polimorfiškais branduoliais.   Grupė latakų su intraduktalinėmis papilinėmis struktūromis ir adenomatozinio tipo proliferatais iš mioepitelinių ir duktalinių ląstelių. Grupės latakų su stulpiniu epitelio pokyčiu ir apikalinės sekrecijos požymiais bei epitelio hiperplazija.. 1. Limfmazgis:   CD20+ nedideli folikulai, CD3/CD5(+) gausūs parakortekso ir perifolikliniai T limfocitai, CD23+ FDC tinklai ir labai negausūs pabiri limfocitai, Cyclin D1(-), Ki67 <5% (pavieniai smulkūs antriniai folikulai su GC ir aukštu Ki67).
answer:  0.

 39%|███▊      | 256/661 [07:12<11:20,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu  3(2). Deš. pažasties sarginiai limfmazgiai, skubu   4(3). Deš. krūties sektorius, planinis. 4. Krūties sektorius 5,8x3x6 cm su oda 5x1,5cm, žymėtas viela. Krūties audinyje, vielos projekcijoje - pilkšvas, standus, aiškių ribų navikas 10x8x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1,2 cm.. 1(1a). Riebalinio audinio fragmentas be patologijos.  2(1b). Fibrocistiniai krūties pokyčiai.  3(2). Krūties duktalinės karcinomos mikrometastazė viename limfmazgyje (1/1 l/m, 1,1 mm skersmens).  4(3). Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma, TNM: pT1b(navikas 8,25 mm), pN1mi(1 l/m su mikrometastaze 1,1 mm), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2: reakcija neigiama (1+).  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).. 1(1a). Riebalinio audinio fragmentas su fibrozinėmis septomis.  2(1b). Krūties audinyje židininė fibrozė su smulkiais ir nežymiai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.  3(2). PO FIKSACIJOS: Limfmazgyje žemiau aprašyto naviko mikrometastazė 1,1 mm skersmens.  4(3). Krūties audinyje, hialinizuotoje stromoje plinta navikas (8,25 mm) infiltratyviu augimo frontu. Navikas suformuotas trabekulinių ir tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su vidutiniškai polimorfiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 6/10DPRL. Limfovaskulinis plitimas smulkiose limfagyslėse/kraujagyslėse(LVI2). Greta naviko gausūs dilatuoti kanaliukai užpildyti solidinių ir kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais; dalies proliferatų centruose - nekrozės zonos.. Blokas 10:  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.
answer:  0

 39%|███▉      | 257/661 [07:14<11:30,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- Kairės pažasties sarginiai limfmazgiai, skubu  4(3)- Kairės krūties sektorius, planinis. 4. Krūties sektorius 8,5x3,5x4 cm, su odos lopu 6,5x2 cm, žymėtas viela. Krūties audinyje, pjūvyje pilkšvas, standus, aiškių ribų navikas 9x6x4 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,5 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties lobulinė karcinoma in situ (LCIS) ir fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija. Mikrokalcifikatai.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(8 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).   Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija. Mikrokalcifikatai.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu, fokaliai hiperplastišku epiteliu; yra kanaliukų, užpildytų monomorfiškomis ląstelėmis (LCIS). Negausūs mikrokalcifikatai.  3(Extra). 2 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.   4. Krūties audinyje - ribotas navikas (mikroskopiškai 8 mm), suformuotas fibrozuotoje stromoje plintančių lizdinių ir trabekulinių struktūrų bei negausių grandinėlių, suformuotų iš ląstelių saikinga švelniai eozinofiliška citoplazma, smulkiais ir vidutinio kalibro, apvaliais/ovaliais, vidutiniškai polimorfiškais, dalis su nukleole branduoliais; negausios žiedines primenančios ląstelės su ekscentrišku branduoliu. Mitozių iki 1/10 DPRL. Navikas 4,5 mm nuo rezekcijos krašto. Gausūs dilatuoti kanaliukai, užpildyti analogiškomis navikui ląstelėmis (LCIS). Aplink yra dilatuotų kanaliukų, klotų hiperplastišku epiteliu bei kanaliukų su apokrinine metaplazija; pavieniai mikrokalcifikatai.. 4. 9 blokas: invazyvi karcinoma E-Cadherin(-); CK14(-); LCIS struktūros su išlaikytu CK14+ mioepiteliniu sluoksniu, E-Cadherin(-) (mioepitelinis sl. +).  16 blokas: LCIS struktūrose E-Cadherin(-) (mioepitelinis sl. +).
answer:  1(

 39%|███▉      | 258/661 [07:15<11:06,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 13 mm; II - 13 mm. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.. Bioptatuose (2/2) - fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos trabekulėmis ir lizdais besidėstančių ląstelių negausia tamsia eozinofiliška citoplazma, polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 10/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 5% naviko ląstelių.  Ki67 proliferacinis aktyvumas 20%.  Synaptophysin+ pavienės ląstelės; CK14 citop
answer:  0.

 39%|███▉      | 259/661 [07:17<11:39,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2): pašalinti  dešinės krūties sarginiai limfmazgiai - skubus tyrimas 2l/m be naviko  2(N1): pašalinta dešinės krūtis - planinis tyrimas. 2(1). Krūtis 1800 gramų svorio, 23x19x6 cm. Rezekcijos kraštas dažytas mėlynu tušu. Krūties audinyje balkšvi standūs naviko židiniai:  - (I) 2,3x2x2,3 cm navikas, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 1,5 cm;  - (II) 0,9x0,9x0,8 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 4 cm, nuo odos - 2 cm, nuo artimiausio (I) naviko - 7,5 cm;  - (III) 1,5x1,7x1,5 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs  6 cm, nuo odos - 2  cm, nuo artimiausio (I)  naviko - 3 cm;  - (IV) 2,2x1,5x1,5 cm navikas, nuo giliojo rezekcijos krašto nutolęs 5 cm, nuo odos - 3 cm, nuo artimiausio (III) naviko nutolęs 3 cm.  - (V) 0,6x0,5x0,5 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 5 cm, nuo odos - 4 cm, nuo artimiausio (III) naviko nutolęs 4 cm.  - (VI) 0,5x0,4x0,2 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 9 cm, nuo odos - 1 cm, nuo artimiausio (V) naviko nutolęs 3 cm.  - Balkšva, standi, netoylgių kraštų fibrozės zona 6x3x3 cm su daugybiniais standžiais židiniais iki 1,5x1x1 cm. Zona nuo giliojo rezekcijos krašto nutolusi 4 cm, nuo odos - 1 cm.. 1(Extra). Reaktyvi limfadenopatija (2 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma (su minimalia mucinine diferenciacija), SUMINIS TNM: pT(m)1c(2 naviko židiniai: 19 mm ir 7 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties išplitusi aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DIN3/DCIS)(solidinė, kribriforminė, komedo) (4 židiniai).  Krūties intraduktalinės papilomos.. 1(Extra). 2 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.  2. SPENELIS: normali histologinė struktūra; žemiau - dilatuotas latakas su intraduktalinėmis papilinėmis struktūromis, klotomis dvisluoksniu epiteliu.   KRŪTIS: krūties audinyje - 2 riboti navikai (I ir II: mikroskopiškai 19 mm ir 7 mm), suformuoti fibrozuotoje stromoje plintančių solidinių, lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 9/10 DPRL. Pirmajame navike negausūs AB+ ekstraląsteliniai mucinai; fokaliai retrakcijos artefaktai aplink naviko lizdus. Aplink dilatuoti kanaliukai su kribriforminiais, negausiais solidiniais intraduktaliniais analogiškų naviko ląstelių proliferatais.   Kiti židiniai (III - VI): - riboti židiniai su DCIS struktūromis bei intraduktalinėmis papilomomis.. 2. Navikas (6 blokas): EMA(+++)(citopl. r-ja), 100%; D2-40+/ERG+ endotelizuotose ertmėse naviko plitimo neidentifikuota.  Navikas (7 blokas): HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.
answer:  1.

 39%|███▉      | 260/661 [07:19<11:05,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Krūtis, biopsija. Trys bioptatai.. 3 fragmentuoti biopsiniai stulpeliai: I - 9 mm; II - 11 mm; III - 7 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Krūties audinį infiltruoja duktalinės struktūros ir negausūs netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 60% naviko ląstelių.  Ki67+ 5%.
answer:  0

 39%|███▉      | 261/661 [07:21<11:27,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra   2. pjūvio kraštai, ekstra.  3. sarginiai limfmazgiai, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 13x9x5 cm su odos lopu 8x3 cm, žymėtas viela. Vielos projekcijoje, pjūvyje - pilkšva, standi, netolygių ribų fibrozės zona 3,5x3x5 cm (sudėta visa), nuo artimiausio rezekcijos krašto nutolusi 0,2 cm (dažytas mėlynu tušu), nuo odos – 1,5 cm.. 1( pjūvio kraštai). Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.     2( pjūvio kraštai). Įprastinė duktalinė hiperplazija. Naviko plitimo nėra.     3(sarginiai limfmazgiai). Reaktyvi limfadenopatija (1 l/m).     4(Krūties sektorius). Krūties invazyvi gerai diferencijuota (G1, 4 balai pagal Nottingham) duktalinė karcinoma,   pT1a(m)(daugybiniai invazijos židiniai iki 3,3 mm mikroskopiškai)   pN0(sn)(1 l/m)    pLVI-0 (limfovaskulinė invazija neidentifikuota).   Naviko imunotipas:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 40% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 8%.    Žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1, kribriforminis ir papilinis piešinys; apie 30 mm).   DCIS struktūros siekia sektoriaus rezekcijos kraštą, invazijos židiniai nuo sektoriaus rezekcijos krašto nutolę bent 4,4 mm atstumu.  DCIS imunotipas:   Estrogenų receptoriai: stipri/vidutinė (+++/++) reakcija, 100% DCIS ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 30% naviko ląstelių branduoliuose.. 1. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.Naviko plitimo nėra.   2. Krūties audinys su fibrozės zonomis ir smulkiais, dalis cistiškai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Dalis latakų su kribriforminiais proliferatais, klotais dvisluoksniu epiteliu be atipijos. Naviko plitimo nėra.   3. 1 limfmazgis su I/II folikulais, sinusų histiocitoze, lipomatoze.  4. Krūties audinyje stambūs latakai (apie 30 mm zonoje), užpildyti kribriforminiais ir papiliniais proliferatais iš ląstelių švelniai polimorfiškais branduoliais, su negausiais kalcifikatais šalia.   Tarp latakų - daugybiniai invazyvūs, morfologiškai panašūs židiniai (didžiausias - 3,3 mm mikroskopiškai), suformuoti tubulių (~30%), trabekulių ir grandinėlių. Naviko ląstelės smulkaus ar vidutinio kalibro, negausia citoplazma, su smulkiais, hiperchromiškais, švelniai polimorfiškais branduoliais su pavienėmis smulkiomis nukleolėmis. Mitozių židiniuose <1/10DPRL.. Blokas 17:  Navikas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 8% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija,
answer:  100%

 40%|███▉      | 262/661 [07:22<10:58,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 15 mm.. Invazinė lobulinė karcinoma (mažiausiai iki 10 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.. Krūties audinį 2-se bioptatuose infiltruoja iki 10 mm :   - juostos;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: neigiama  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono
answer:  0

 40%|███▉      | 263/661 [07:24<11:10,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a kraštas - skubus tyrimas  - be naviko  2. N2b kraštas - skubus tyrimas  - be naviko  3(1) ėminio aprašas: pašalintas kairės krūties darinys - planinis tyrimas  4(3) ėminio aprašas: kairės pažasties sarginiai limfmazgiai planiškai. 3(1). Krūties sektorius 11x5,5x5 cm su odos lopu 9,5x2,5 cm, žymėtas viela. Vielos projekcijoje, pjūvyje balkšvas, standus, neaiškiu ribu navikas 19x17x15 mm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos – 2 cm.  4(3). Riebalinio audinio fragmentai, bendras dydis 6x5x1,2 cm. Rasti 5 l/m iki 2 cm.. 1(2a). Riebalinis (krūties) audinys.  2(2b). Riebalinis (krūties) audinys.  3(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,9 cm) pN(sn)1a (2/5 l/m, mts 0,3 cm ir 1,7 cm; ekstranodalinis plitimas). LVI2(limfovaskulinė naviko invazija). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribriforminis, komedo tipas).  4(3). Duktalinės adenokarcinomos metastazės 2/5 l/m (mts 0,3 cm ir 1,7 cm; ekstranodalinis plitimas).     Ankstesnio/pirminio naviko tyrimo (B23-17508) duomenys  Estrogenų receptoriai: vidutinė (++) reakcija, 30% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: imunohistocheminė reakcija ribinė (2+). Nustatyta HER2 geno amplifikacija (FISH).  Ki67: proliferacinis indeksas 10%. Karštame taške 30%.. 1(2a). Brandžių lipocitų suformuotas audinys.  2(2b). Brandžių lipocitų suformuotas audinys.  3(1).  Krūties audinyje: A) navikas (trabekulines, negausias (5%) tubulines naviko struktūras formuoja ląstelės su negausia-kiek gausesne "švelniai" eozinofiline citoplazma, vidutinio kalibro, nežymiai polimorfiškais, gan retu chromatinu, dalis su smulkia nukleole branduoliais; mitozių navike iki 12 / 10 DPRL), B) DCIS (vidutinio ar stambaus kalibro kanaliukai, iškloti ląstelėmis su vidutinio laipsnio ar ryškia branduolių atipija).  4(3). Aukščiau aprašyto naviko metastazės dviejuose (2) iš penkių (5) limfmazgiuose (metastazės 0,3 cm ir 1,7 cm; ekstranodalinis plitimas).. nan
answer:  1(

 40%|███▉      | 264/661 [07:26<10:57,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  18 G automatine biopsine adata punktuotas hipoechogeninis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~11x19 mm dydžio navikas kairiojoje krūtyje ties 12 val. vidurinėje dalyje, paimti trys biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 14 mm; II - 12 mm; III - 12 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G2; 7 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.    Vidutinio laipsnio intraduktalinė neoplazija (DCIS/DIN2).. Krūties audinį 3-se bioptatuose infiltruoja iki 12 mm :   - duktalinės struktūros (5% viso naviko), netaisyklingi kribroziniai kompleksai ir trabekulės;  - epitelinių vidutinio stambių ląstelių su ryškiai polimorfiškais branduoliais  negausioje bazofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.  Gretimai - keliuose latakuose analogiškų ląstelių tinklinės struktūros.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 15% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  100%

 40%|████      | 265/661 [07:27<10:49,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 9 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 15 mm);  (G1; 5 b. pgl. Nottingham sist.) 1-me stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 5%.. Krūties audinį 1-me bioptate infiltruoja iki 15 mm :   - duktalinės pavienės struktūros ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) necirkuliari reakcija, 25%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 5% naviko ląstelių.  Progesterono receptoriai: stipri
answer:  1b

 40%|████      | 266/661 [07:29<11:37,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(3). dešinės pažasties sarginis limfmazgis - extra - 4 l/m be naviko;  2(2a). kraštas - skubus tyrimas - be naviko;  3(2b). kraštas - skubus tyrimas - LCIS;  4(1). pašalintas dešinės krūties kvadrantas - planinis tyrimas;  5(4). papildomas krašas - planinis tyrimas.. 4(1). Krūties sektorius 6,5x4x3,5 cm su odos lopu 6x2 cm. Krūties audinyje, pjūvyje pilkšvas, standus, neaiškių ribų navikas 17x13x10 mm, nuo odos nutolęs 1 cm, nuo giliojo rezekcijos krašto - 0,2 cm.  5(4). Riebalinio audinio fragmentas 1,5x1x0,3 cm.. 1(3, ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė, židininė fibrozė (3 l/m).   2(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.    3(2b, ekstra). "Kraštai": krūties lobulinė intraepitelinė neoplazija (LCIS). Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM:   pT1c (navikas 17 mm) N0(sn) (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Intraduktalinis karcinomos plitimas (kanaliukų kancerizacija).  Imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.   Progesterono receptoriai: vidutinė-stipri (++/+++) reakcija, 60% naviko ląstelių.   HER2: reakcija neigiama (1+).   Ki67: proliferacinis indeksas ~5%.   Krūties lobulinė intraepitelinė neoplazija (LCIS; konvencinė ir pleomorfinė).  Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Invazyvus navikas nuo artimiausio krūties sektoriaus rezekcijos krašto nutolęs - 0,7 mm;   konvencinis LCIS koaguliacijos zonose.   5(4). "Papildomas kraštas": fibrozuotas riebalinis audinys; be naviko.. 1(3, ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2(2a, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar hiperplastišku epiteliu. Kelios nedidelės koaguliuotos lobulės (planinio tyrimo stikluose neišliekančiomis) su monomorfiškomis, mažai kohezyviomis ląstelėmis šviesia citoplazma.   4(1). NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje su elastozės zonomis, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", solidinės naviko struktūros, suformuotos mažai kohezyvių, daugiausiai pabirai besidėstančių vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesiai eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais, fokaliai skeltais branduoliais su smulkiomis nukleolėmis; mitozės retos, sunkiai identifikuojamos, iki 1/10 DPRL. Šalia - naviko struktūrų plitimas kanaliukų spindžiuose. Perineurinė edema.   APLINKA: zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais; dalies centruose nekrotinis dedritas su negausiais PMN.    Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: infiltratyvaus naviko struktūros nutolusios 0,7 mm; koaguliacijos zonose nedideli koaguliuoti in situ komponento židiniai.   5(4). "Papildomas kraštas": fibrozuotas, vaskuliarizuotas brandžių lipocitų suformuotas audinys; be naviko.. 3(2b, ekstra). "Kraštai": CK14(+) mioepitelinis sluoksnis.   4(1). NAVIKAS (17 blokas): E-Cadherin(-) invazyviame ir in situ komponentuose.   NAVIKAS (18 blokas):  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progeste
answer:  1+

 40%|████      | 267/661 [07:31<11:08,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 5 biopsiniai stulpeliai medžiagos histologiniam ištyrimui. 5 biopsiniai stulpeliai: I - 13  II - 11 mm; III - 12 mm; IV - 8 mm; V - 8 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 6%.  Žemo laipsnio intraduktalinė karcinoma (DCI; DIN1, kribriforminis tipas).. Krūties audinį infiltruoja smulkios duktalinės struktūros, pabiros smulkios minimaliai polimorfiškos ląstelės ir tų ląstelių juostos, mitozių mažiau 1/10 DPRL.  Negausios intraduktalinės kribriforminės struktūros iš monomorfiško epitelio.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 6%.
answer:  0

 41%|████      | 268/661 [07:32<11:07,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- virštuinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- Deš. pažasties sarginiai limfmazgiai, skubu  4(3) - Deš. krūties kvadrantas, planinis.. 4. (3) Krūties sektorius 12x7x5,5 cm, žymėtas viela su odos lopu 10,5x4 cm. Krūties audinyje balkšvas, standus, neaiškių ribų  (I) navikas 11x10x9 mm, nuo rezekcijos krašto nutolęs 1 cm, nuo odos 3 cm. Šalia (II) navikas neaiškių ribų 8x6x6 mm, nuo rezekcijos krašto nutolęs 1,3 cm, nuo odos - 1,5 cm, nuo I naviko - 0,3 cm. Navikai sudėti visi.. Atlikti pjūviai Prosigna.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(m)(2 židiniai 17 mm, 7 mm) pN0(sn)(0/3 l/m) LVI-2(limfovaskulinė invazija).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (2 židiniai 17 mm, 7 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, tubulinėmis, kribriforminėmis struktūromis besidėstančių ląstelių  vidutinio gausumo eozinofiliška-amfofiliška citoplazma, vidutiniais, vidutiniškai ryškiai polimorfiškais, ovaliais branduoliais ryškiomis nukleolėmis; mitozių 3/10 DPRL. limfovaskulinė invazija.  Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu.. Navikas: CD14(-); CD31+ endotelis.
answer:  1(

 41%|████      | 269/661 [07:34<11:04,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1- viršutinis kraštas - Extra  2 - apatinis kraštas - Extra  3 - sarginiai l/m - Extra  4 - kvadrantas - planiniam tyrimui. 4. Krūties sektorius 10x7x5,5 cm, su odos lopu 9x3 cm. Pjūvyje - pilkšvas, neaiškių ribų, standus navikas 22x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 1,3 cm, nuo odos - 2 cm.. 1. Krūties intraduktalinė papiloma.  2. Krūties stulpinis epitelio pokytis.   3. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham s.) duktalinė karcinoma su mikropapilinės karcinomos komponentu (~10%), suminis Nr. 1 - 4 pTNM:   pT2 (22 mm) pN0(sn) (0/1 l/m); LVI0 (limfovaskulinės naviko invazijos patikimai neidentifikuota).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-9611, žr. pastabą.. 1. Nežymiai fibrozuotame krūties audinyje - grupė latakų su intraduktalinėmis papilinėmis struktūromis, klotomis mioepitelinėmis ir duktalinėmis lątelėmis.   2. Krūties audinys su nežymia stromos fibroze, negausiais latakais su stulpiniu epitelio pokyčiu ir apikalinės sekrecijos požymiais.   3. Limfmazgis(1) kiek tušuota architektūra, retai stambiais antriniais folikulais, nežymiai fibrozuota stroma.   4. Krūties audinyje - navikas, formuojamas infiltratyviai plintančių trabekulinių, solidinių, negausių blogai suformuotų liaukinių ir mikropapilinių (iki 10%) struktūrų, sudarytų iš vidutinio dydžio tubulinių ir poligonalinių ir stulpinių ląstelių gausia eozinofiliška citoplazma, vidutiniškai polimorfiškais ovaliais branduoliais su grūdėtu chromatinu, kiek akcentuotomis smulkiomis nukleolėmis dalyje ląstelių. Navike iki 9 mitozių/ 10 DPRL. Limfovaskulinės naviko invazijos patikimai neidentifikuota.. 3. Limfmazgis:   PANCK-, GATA3+ limfocitai, e-cadherin+ histiocitai(?).
answer:  0.

 41%|████      | 270/661 [07:36<10:39,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Krūties audinį infiltruoja smulkios duktalinės struktūros ir smulkūs kribroziniai/solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+ 5
answer:  1a

 41%|████      | 271/661 [07:37<10:52,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  CA mammae dex. cT2N0M0 - IIA (intramamarinis limfmazgfis verifikuotas, pažastis - N0) -extra.   1(2a). Kraštai - extra;  2(2b). Kraštai - extra;  3. Dešinės pažasties sarginis limfmazgis - extra (3 l/m be naiko);  4(1). Pašalintas dešinės krūties kvadrantas - planinis tyrimas;   5(4). Markiruotas dešinės pažasties intramamarinis verifikuotas limfmazgis - planinis tyrimas.. 4(1). Krūties sektorius 10,5x5,5x5,58 cm su odos lopu 9,5x4,7 cm. Pjūvyje pilkšvas, standus, neaiškių ribų navikas 32x30x21 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 0,6 cm.  5. Krūties sektorius 7,5x3x3,5 cm (žymėtas dažais) su odos lopu 7x2,5 cm, žymėta viela. Vielos projekcijoje pilkšvas, ribotas limfmazgis? 1x1x0,8 cm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 2,5 cm.. 1(ekstra). Reaktyvi limfadenopatija (3 l/m).  2(ekstra). Riebalinis - fibrozinis audinys.  3(ekstra). Riebalinis - fibrozinis audinys.  4. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(32 mm navikas) pN1a(sn)(1/4 l/m 8 mm) LVI-2(limfovaskulinė invazija). Perineurinis. R0(radikali rezekcija).  5. Duktalinės karcinomos metastazė intramamariniame limfmazgyje (8 mm).    Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Androgenų receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 70%.. 1(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  2(ekstra). Riebalinis - fibrozinis audinys.  3(ekstra). Riebalinis - fibrozinis audinys.  4. Krūtyje - navikas ekspansyviu augimo frontu, suformuotas lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 44/10 DPRL. Limfovaskulinė invazija. Perineurinis plitimas.  5. Intramamarinis limfmazgis su aprašyto naviko metastaze 7 mm.. Navikas(23):  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Androgenų receptoriai: neigiama reakcija.  Ki67 proliferacinis aktyvumas 70%.
answer:  1(

 41%|████      | 272/661 [07:39<10:40,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Paimti 2 biopsiniai stulpeliai.. 2 biopsiniai stulpeliai: I - 13 mm; II - 10 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 8%.. Krūties audinį 2-se bioptatuose infiltruoja iki 13 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje citoplazmoje;   - su mitozėmis iki 2/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 50%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 8% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  100%

 41%|████▏     | 273/661 [07:41<10:27,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stulpeliai. 3 biopsiniai stulpeliai: I - 11 mm; II - 8 mm; III - 6 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 15%.. Krūties audinį infiltruoja netaisyklingi nedideli kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 30% naviko ląstelių.  Ki67+ 15%.
answer:  3b

 41%|████▏     | 274/661 [07:42<10:21,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N3): kairės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko  4(N1): pašalintas kairės krūties kvadrantas - planinis tyrimas. 4(N1). Krūties sektorius 13,5x9x5x cm, su odos lopu 12x5 cm. Krūties audinyje pilkšvas, standus, gan aiškių ribų navikas 1,6x1,0x0,6 cm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 2,4 cm. Krūties audinys fibrozuotas 9x6 cm plote. Nuo naviko, 2 cm atstumu pilkšvas, standus židinys 0,5 cm, nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo odos - 3,2 cm.. PAPILDYTA  1(N2a). Krūties fibrocistiniai pokyčiai.  2(N2b). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (3 l/m).  4(N1). Krūties invazyvi duktalinė adenokarcinoma (gerai diferencijuota / G1 / 5 balai pagal Nottingham), TNM (Nr.1-Nr.4): pT1c(m) (ne mažiau 3 židinių: 1,6 cm, 0,5 cm, 0,4 cm) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės naviko invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 6%.. nan. nan
answer:  1(n

 42%|████▏     | 275/661 [07:44<10:35,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.  2(2b). Kraštai - skubus tyrimas - be naviko.  3. Kairės pažasties sarginis limfmazgis - skubus tyrimas 2l/m su makrometastazėm.(Atkreiptį dėmesį į limfmazgių skaičių, operacijos metu rasti 3 aiškiai čiuopiami limfmazgiai, gal yra ir trečias limfmazgis?)  4(1). Pašalintas kairės krūties kvadrantas planinis tyrimas. 4. Krūties sektorius 16x7x4 cm, su odos lopu 15,5x6 cm, žymėtas viela. Krūties audinyje pilkšvas, standus, neaiškių ribų navikas 20x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 0,3 cm. Nuo naviko 6,5 cm atstumu vielos projekcijoje neaiškių ribų pilkšvas darinys 7x6x6 cm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 4,5 cm.. 1(2a)  kraštai - krūties audinys be pokyčių.  2(2b) kraštai - krūties audinys be pokyčių.  3(2) kairės pažasties sarginis limfmazgis: karcinomos plitimas iki 12 mm 2-se iš 3 limfmazgiuose.  4(1) kairės krūties kvadrantas. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT1c pN1a pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 20%.    Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS; kribriforminis tipas; 0,5 mm nuo operacinio krašto).. 1(2a)  kraštai - krūties audinys be pokyčių.  2(2b) kraštai - krūties audinys be pokyčių.  3(2) kairės pažasties sarginis limfmazgis: karcinomos plitimas iki 12 mm 2-se iš 3 limfmazgiuose; stebimas ekstranodulinis plitimas.  4(1) kairės krūties kvadrantas. Krūties audinyje naviką (mikroskopoiškai 19 mm) formuoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai ir vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL. Atskiro darinio dilatuotuose kanaliukuose (esančiuose 0,5 mm nu operacinio krašto) kribroziniai intraduktaliniai neryškiai ar vidutiniškai polimorfiško epitelio proliferatai.. nan
answer:  1(

 42%|████▏     | 276/661 [07:45<10:21,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 2  biopsiniai  stulpelis iš kairės pažasties  l/m  2 but. 1  biopsinis  stulpelis  iš kairės krūties BI-RADS 5 darinio. 1. 2 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 4 mm.  2. Biopsinis stulpelis 13 mm ilgio.. N1: Limfmazgio bioptatai be naviko metastazių.  N2: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 20-25%.. N1: Limfmazgio bioptatai be naviko metastazių.  N2: Krūties audinį infiltruoja nedideli netaisyklingi solidiniai kompleksai iš vidutiniškai ir ryškiai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 20-25%.
answer:  0

 42%|████▏     | 277/661 [07:47<10:34,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2a  kraštas skubus tyrimas be naviko  2 ėminio aprašas: 2b kraštas skubus tyrimas be naviko   3 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas 2l/m be naviko   4(1) ėminio aprašas: pašalintas dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 5,5x4,5x2,5 cm su odos lopu 5,5x2 cm, žymėtas viela. Vielos projekcijoje, pjūvyje pilkšvas, standus, gan aiškių ribų navikas 10x10x8 mm navikas, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,2 cm. Atskirai tame pačiame inde odos fragmentas 4,3x0,6 cm. Odoje rusvas, gruoblėtas, iškilęs darinys 0,4x0,4x0,3 cm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm.. 1. Krūties audinys.  2. Krūties audinys.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 15 mm), pN0(sn)(0/2 l/n), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Fibrocistiniai krūties pokyčiai.  Dermalinis nevocitinis nevus.. 1. Krūties audinyje židininė fibrozė ir smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2. Krūties audinyje lobulės, klotos dvisluoksniu epiteliu bei židininė apokrininė epitelio metaplazija.  3. Du limfmazgiai (2 l/m) su sinusų histiocitoze.  4. Krūties audinyje - navikas (15 mm mikroskopiškai), suformuoti susiliejančių lizdinių, kribriforminių bei negausių tubulinių struktūrų iš vidutinio kalibro, vidutinio gausumo eozinofiline citoplazma ląstelių, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiais branduolėliais; mitozių 9/10 DPRL. Limfovaskulinis plitimas (LVI2). Greta naviko dilatuoti latakai, užpildytų kribriforminių proliferatų, suformuotų analogiškų navikui ląstelių. Aplinkiniame krūties audinyje, fibrozuotoje stromoje, gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu su fokalia apokrinine metaplazija.  Odos fragmente, dermoje - formuodami lizdus ir difuziškai plinta nevocitai su brendimo požymiais. Nevocitai rezekcijos krašte.. nan
answer:  1a

 42%|████▏     | 278/661 [07:49<10:31,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  ca mammae dex - extra  1 ėminio aprašas: 1 pjūvio kraštas, ekstra.  2 ėminio aprašas: 2 pjūvio kraštas, ekstra.   3 ėminio aprašas. sarginiai l/m, ekstra.  4. sektorius, planinis.. 4. Krūties sektorius 15x7,5x4,5 cm su odos lopu 12,5x3 cm. Krūties audinyje, balkšvas, standus, neaiškių ribų navikas 31x27x25 mm, nuo artimiausio rezekcijos krašto nutolęs 1,2 cm, nuo odos – 2,5 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/4 l/m, 4,75 mm).  4. Krūties invazyvi blogai diferencijuota (G3; 9 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT2(navikas 31 mm), pN1a(1/4 l/m, metastazė iki 4,75 mm), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.. 1. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.   2. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Viename iš keturių limfmazgių keli žemiau aprašyto naviko židiniai, didžiausias 4,75 mm.   4. Krūties audinyje navikas (31 mm makroskopiškai), infiltratyviu augimo frontu, suformuotas stambių, besiliejančių lizdų, trabekulių ir negausių  tubulinų struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, vidutiniškai ir fokaliai ryškiai polimorfiškais, hiperchromiškais, smulkiai grūdėtu chromatinu branduoliais. Mitozių navike 50/10DPRL. Limfovaskulinė naviko invazija neidentifikuota(LVI0).. nan
answer:  0

 42%|████▏     | 279/661 [07:51<10:48,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 (1a)- viršutinis kraštas, skubu  2 (1b)- apatinis kraštas, skubu  3 (2). sarginiai limfmazgiai, skubu  4 (3). Kairės krūties sektorius, planinis  5 (4). Papildomas kraštas - planinis. 4(3). Krūties sektorius 4,5x4x2,8 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje - balkšvas, standus, pakankamai aiškių ribų navikas 14x12x10 mm navikas (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,4 cm.  5(4). Riebalinio audinio fragmentas 1,5x1,2x0,4 cm. v/m. 1. Krūties audinys be patologinių pokyčių.  2. Krūties intraduktalinė papiloma.   3. Reaktyvi limfadenopatija (2 l/m).   4. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma,   pT1c (14 mm) pN0(sn) (0/2 l/m); LVI0 (limfovaskulinės naviko invazijos nenustatyta).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-26741, žr. pastabą.   Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminė).   Adenozė.    5. Krūties audinys be patologinių pokyčių.. 1. Krūties audinys be patologinių pokyčių.   2. Krūties audinyje - grupė latakų su intraduktalinėmis papilinėmis struktūromis ir adenomatozinio tipo proliferatais iš mioepitelinių ir duktalinių ląstelių, aplinkiniai latakai su stulpiniu epitelio pokyčiu ir apikalinės sekrecijos požymiais bei epitelio hiperplazija.   3. Limfmazgiai (2) su negausiais antriniais folikulais, sinusų histiocitoze, stromos lipomatoze ir nežymia fibroze.   4. Krūties audinyje - navikas, formuojamas infiltratyviai plintančių kompleksinių liaukinių, kribriforminių, tubulinių ir retų trabekulinių struktūrų, sudarytų iš stulpinių ir kubinių ląstelių vidutiniškai polimorfiškais, kiek nelygaus kontūro branduoliais su vezikulizuotu chromatinu; mitozių iki 8/10 DPRL.  Greta infiltratyvių naviko struktūrų, keli latakai su intraduktaliniais kribriforminiais ir arkadiniais duktalinio tipo ląstelių proliferatais su nežymiu ar vidutiniu branduolių polimorfizmu, "apikalinės" sekrecijos požymiais.   Organoidinis smulkių, kiek deformuotų kanaliukų proliferatas krūties audinyje greta naviko.   5. Krūties audinys be patologinių pokyčių.. nan
answer:  0,

 42%|████▏     | 280/661 [07:52<10:30,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 3%.. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozės pavienės.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 3%.
answer:  1a

 43%|████▎     | 281/661 [07:54<10:47,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. Kairės pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: 2. Kairė krūtis, planinis. 2. Krūtis 920 gramų svorio, 21x18x5 cm. Krūties audinyje, apatinių kvadrantų riboje, ties centrine dalimi 2 balkšvi, standūs, susiliejantys, neaiškių ribų navikai (I navikas) 48x32x19 mm, nuo odos nutolę 2,5 cm, nuo giliojo rezekcijos krašto - 1,5 cm. Viršutiniame medialiniame kvadrante balkšvas, standus neaiškių ribų II navikas 19x15x7 mm, nuo odos nutolęs 4,5 cm, nuo giliojo rezekcijos krašto - 0,5 cm.. 1. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/2 l/m, 2,5 mm).  2. Krūties invazyvi mišri blogai diferencijuota (G3; 9 b. pgl. Nottingham) lobulinė (75%) ir duktalinė karcinoma (25%), suminis TNM: pT2(m)(navikai 44 mm ir 21 mm), pN1a(sn)(1/2 l/m), LVI2(limfovaskulinis plitimas). II-sis naviko židinys, plinta koaguliuoatme rezekcijos krašte, ties skersaruožiu raumeniu. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).   Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai. Intraduktalinė krūties papiloma.. 1. Viename limfmazgyje iš dviejų (1/2 l/m) žemiau aprašyto naviko metastazė iki 2,5 mm skersmens.  2. Krūties audinyje - hialinizuotoje stromoje 2 naviko židiniai (44 mm ir 21 mm mikroskopiškai) infiltratyviu augimo frontu, suformuoti 2 komponentų: a) trabekulinių, juostinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, ryškiai polimorfiškais, hiperchromiškais branduoliais; b) smulkių lizdinių, trabekulinių ir pavienių struktūrų su spindžių formacija, suformuotų kiek gausesne eozinofiline citoplazma ląstelių su vidutiniškai polimorfiškais, hiperchromiškais branduoliais. Gausi perinavikinė limfocitų infiltracija. Mitozių navike iki 26/10DPRL. Limfovaskulinė naviko invazija (LVI2). II-sis naviko židinys, plinta koaguliuoatme rezekcijos krašte, ties skersaruožiu raumeniu. Greta naviko daugybiniai dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, polimorfiškais, hiperchromiškais branduoliais. Šalia gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu su fokalia epitelio hiperplazija. Spenelio projekcijoje - dilatuotas latakas su fibrovaskulinėmis struktūromis, klotomis dvisluoksniu epiteliu monomorfiškais branduoliais. Blokas 10:  HER2: reakcijos naviko ląstelių membranoje nėra.  Blokas 20:  E-Cadherin: (+++)membr.r-ja 100%;  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 43%|████▎     | 282/661 [07:56<10:28,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: kairė krūtis su pažasties l/m, planinis. Krūtis 403 gramų svorio, 16x13,5x5 cm, su pažasties narveliena 9,5x6x3 cm.   Krūties audinyje, centrinėj dalyje pilkšvas, standus, neaiškių ribų navikas 55x30x25 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 1,3 cm.   Pažasties narvelienoje rasta 12 limfmazgių, didžiausias 2 cm.. Gerai diferencijuota (G1, 5 balai pgl. Nottingham) krūties invazinė duktalinė karcinoma  pT3 pN1a pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. Krūties audinį infiltruoja (iki 65 mm mikroskopiškai) vienaeilės juostos (< 90 proc.) ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.  Gretimai - analogiškų ląstelių intraduktaliniai solidiniai proliferatai.  Plitimo operaciniame krašte nestebima (2,3 mm).  Atipinių ląstelių plitimas iki 12 mm 3-se iš 25 limfmazgių; stebimas ekstranodulinis plitimas.. nan
answer:  1a

 43%|████▎     | 283/661 [07:57<10:07,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 4 biopsiniai stulpeliai. 4 biopsiniai stulpeliai: I - 11 mm; II - 8 mm; III - 13 mm; IV - 9 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. Krūties audinį infiltruoja smulkios duktalinės struktūros, nedideli kribroziniai ir solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 40% naviko ląst
answer:  1b

 43%|████▎     | 284/661 [07:59<09:51,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 55%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 55%.
answer:  3

 43%|████▎     | 285/661 [08:00<09:40,  1.54s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. Pjūvio kraštai, ekstra.   3. Sarginiai l/m, planinis.   4. Sektorius, planinis.. 3. Riebalinio audinio fragmentas 4x3,5x1 cm. Rasti 2 limfmazgiai iki 1,6 cm. v/m  4. Krūties sektorius 5,5x3x2,7 cm, su odos lopu 5x2 cm. Krūties audinyje, pjūvyje pilkšvas, standus, aiškių ribų navikas 13x8x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 1 cm.. N1-2: Krūties audinys be naviko.  N3: Limfmazgiai be naviko (2 l/m); pN0(sn).  N4: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c (13mm).. N1-2: Krūties audinys be naviko.  N3: Limfmazgiai su lipomatozės židiniais, be naviko (2 l/m).  N4: Kūties audinyje 13mm navikas: duktalinės struktūros, nedideli kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. nan
answer:  0

 43%|████▎     | 286/661 [08:01<09:31,  1.52s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja negausios duktalinės struktūros ir netaisyklingi kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  1a

 43%|████▎     | 287/661 [08:03<09:31,  1.53s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 16 mm; III - 12 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  1a

 44%|████▎     | 288/661 [08:05<09:53,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: Pašalintas markiruotas kairės krūties kvadrantas - planinis tyrimas  2 ėminio aprašas: N2A - kraštas  - planinis tyrimas  3 ėminio aprašas: N2B - kraštas  - planinis tyrimas. 1. Krūties sektorius 8,5x4x5,5 cm su odos lopu 6,5x2,3 cm, žymėtas viela. Vielos projekcijoje, pilkšvas standus neaiškių ribų navikas 6x5x5 mm, nuo giliojo rezekcijos krašto nutolęs 0,9 cm, nuo odos - 1,6 cm.  2. Riebalinio audinio fragmentas 3x1,6x0,7 cm. v/m  3. Riebalinio audinio fragmentas 2x1,6x0,4 cm. v/m. N1: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 6%.  N2a: Žemos laipsnio intraduktalinė krūties karcinoma (DCIS/DIN1; 4mm židinys; mikropapilinis tipas).  N2b: Normalios struktūros krūties audinys.. N1: Krūties audinyje 6mm navikas: duktalinės struktūros, negausūs netaisyklingi kribroziniai kompleksai, juostos ir trabekulės iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.  N2a: Krūties audinyje 4mm židinys su dilatuotais kanaliukais su mikropapiliniais intraduktaliniais minimaliai polimorfiško epitelio proliferatais.  N2b: Krūties audinys su negausiais kanaliukais, išklotais normaliu epiteliu.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 5% naviko ląstelių.  Ki
answer:  6%.

 44%|████▎     | 289/661 [08:07<10:23,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas  2 ėminio aprašas: N2a kraštai - planinis tyrimas  3 ėminio aprašas: N2b kraštai - planinis tyrimas  4 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - planinis tyrimas. 1. Krūties sektorius 14x8x6 su odos lopu 12x4 cm. Krūties audinyje balkšvas, standus, apvalios formos, skiltėtas, neaiškių ribų navikas 28x23x24 mm, nuo artimiausio rezekcijos krašto nutolęs mažiau 0,1 cm, nuo odos - 6 cm.  2. Riebalinio audinio fragmentas 3x2x0,6 cm. v/m   3. Riebalinio audinio fragmentas 2x2x1 cm. v/m  4. Riebalinio audinio fragmentas 3x2x1,5 cm. Rastas limfmazgis 1,8 cm.. 1. Krūties invazyvi adenoidinė cistinė karcinoma (solidinis-bazaloidinis tipas) ir blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma. Žr. pastabą.  SUMINIS TNM: pT2 (2,8 cm) N0(sn)(0/1 l/m) LVI-2(limfovaskulinė invazija). Navikas nuo sektoriaus rezekcijos krašto nutolęs <0,1 mm.   Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis-kribriforminis tipas).     Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.   Her2 imuninė reakcija: neigiama (0).   Ki67 proliferacinis aktyvumas 10%, fokaliai 25%.    2. N2a kraštai - planinis tyrimas: Krūties audinys.   3. N2b kraštai - planinis tyrimas: Riebalinis fibrozinis audinys.  4. N3: kairės pažasties sarginis limfmazgis - planinis tyrimas: Reaktyvi limfadenopatija (1 l/m).. 1. Krūties audinyje - navikas infiltratyviu augimo frontu, suformuotas : a) solidiniais plotais, lizdais su negausiais reguliariais spindžiais,negausiomis tubulinėmis-kribriforminėmis struktūromis besidėstančių ląstelių negausia tamsia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; b) solidinių plotų ir trabekulių iš ląstelių vidutinio gausumo eozinofiliška citoplazma, ryškiai polimorfiškais, stambaus kalibro, nereguliaraus kontūro, fokaliai vezikulizuotais branduoliais su ryškiu branduolėliu. Mitozių navike iki 23/10 DPRL. Pavienės "komedo" tipo nekrozės lizdų centruose. Naviko plitimas endotelizuotuose spindžiuose (LVI-2). Navikas nuo rezekcijos krašto nutolęs <0,1 mm.  Krūties audinyje fibrozė, elastozė bei dilatuoti kanaliukai su intraduktaliniais solidiniais ir kribriforminiais proliferatais iš ląstelių vidutinio gausumo eozinofiliška citoplazma, apvaliais ar ovoidiškais, vezikulizuotais, polimorfiškais branduoliais su nukleolėmis.   Dalyje kanaliukų apokrininė metaplazija.  2. Krūties audinys su negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Riebalinis fibrozinis audinys.  4. Limfmazgis su I folikulais, sinusų histiocitoze ir lipomatoze.. Navikas, 4 blokas:   Estrogenų receptoriai: neigiama reakcija;  Progesterono recepotoriai: neigiama reakcija;  HER2: neigiama reakcija (0 balų);   Ki67 proliferacinis aktyvumas 15%, fokaliai 25%;  CD117(++/+++)(citopl. r-ja) 70%;  EMA: neigiama reakcija;
answer:  0.

 44%|████▍     | 290/661 [08:08<10:12,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 18 G automatine biopsine adata punktuotas ~12x36 mm dydžio, netolygiai iki 10 mm sustorėjusiu žieviniu sluoksniu patologinis l/m dešiniosios pažasties I lygmenyje, paimti du biopsiniai stulpeliai histologijai (I buteliukas).   2. 18 G automatine biopsine adata punktuotas didelių matmenų (>50 mm) išopėjęs navikas dešiniojoje krūtyje, paimti du biopsiniai stulpeliai histologijai (II buteliukas).. 1. 2 biopsiniai stulpeliai: I - 12 mm; II - 12 mm.  2. 2 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 14 mm.. 1. Limfmazgio bioptatai su duktalinės karcinomos metastazėmis.   2. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 9%.. 1. Limfmazgio bioptatai su žemiau aprašyto naviko židiniais.   2. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. 2. Navikas (3 blokas):  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių m
answer:  membrano

 44%|████▍     | 291/661 [08:10<09:49,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 bioptatai 22 mm  12G adata iš ~3 cm   ploto su mkk. Aiškių kalcinatų bioptatuose nematyti.. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 12 mm; III - 11 mm.. Vidutinio laipsnio intraduktalinė karcinoma (DCIS/DIN2, solidinis tipas).  Gerai diferencijuota invazinė duktalinė karcinoma (mikroskopinis židinys apie 0,4mm).  Estrogenų receptorių reakcija navike 100%.. Krūties audinyje dilatuotuose kenaliukuose solidiniai neryškiai polimorfiškų ląstelių proliferatai. Mikroskopinis invazinio augimo židinys aplinkinėje stromoje (apie 0,4mm).. nan
answer:  1a

 44%|████▍     | 292/661 [08:11<09:42,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but.  4 biopsiniai stulpeliai iš BI-RADS 4c darinio periferijoje   2 but. 3 biopsiniai stulpeliai iš BI-RADS 4a darinio vidurinėje dalyje. 1. 4 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 8 mm; IV - 8 mm.   2. 3 biopsiniai stulpeliai: I - 5 mm; II - 4 mm; III - 6 mm.. N1: Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.  N2: Ryški krūties audinio fibrozė, kanaliukų atrofija, galimai sklerozuota fibroadenoma.. N1: Krūties audinyje mucininėje stromoje netaisyklingi kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  N2: Ryški kompaktiška krūties audinio fibrozė, formuojanti gana ribotus mazgus, pavieniai atrofiški kanaliukai.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67+ 4%.
answer:  0

 44%|████▍     | 293/661 [08:13<09:28,  1.54s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. 1 biopsinis stulpelis 10 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 1-2%.. Krūties audinį infiltruoja duktalinės struktūros ir smulkūs solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  1a

 44%|████▍     | 294/661 [08:14<09:19,  1.52s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 15 mm; II - 14 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20-25%.. Krūties audinį infiltruoja netaisyklingi kribroziniai/solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 20-
answer:  3b

 45%|████▍     | 295/661 [08:16<09:31,  1.56s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1 pašalintas kairės krūties markiruotas plotas - planinis tyrimas  N2a kraštas - planinis tyrimas  N2b kraštas - planinis tyrimas. 1. Krūties sektorius 5x2,5x5 cm su oda  3,5x1,5 cm, žymėtas viela. Vielos projekcijoje - pilkšvas, standus, aiškių ribų navikas 16x10x10 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 3,7 cm.  2. Riebalinio audinio fragmentas 2x1,5x0,6 cm. v/m  3. Riebalinio audinio fragmentas 2,2x2x0,5 cm. v/m. N1: Gerai diferencijuota (G1, 4balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(16mm).  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 6%.  N2-3: Riebalinio ir krūties audinio fragmentai be naviko plitimo.. N1: Krūties audinyje 16mm navikas: smulkios duktalinės struktūros, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.  Aplink naviką negausūs intraduktaliniai monomorfiškų ECAD negatyvių ląstelių proliferatai (LCIS intraduktalinis plitimas).  N2-3: Riebalinio ir krūties audinio fragmentai be naviko plitimo.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 6%.
answer:  0

 45%|████▍     | 296/661 [08:18<09:59,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2A) - kraštas - extra - be naviko   2(N2b)-kraštas-extra - ADH  3(N2c)-kraštas-extra - be naviko  4(N3)-l/m-extra - be naviko  5(N4)- pap. kraštas - extra - be naviko  6(N1) - sektorius- planinis tyrimas. 6. Krūties sektorius 10,5x6,5x5 cm, su odos lopu 8,5x6 cm. Krūties audinyje pilkšvas, standus, neaiškių ribų darinys 45x35x30 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nu odos - 0,6 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai; paprasta intraduktalinė hiperplazija.  3. Fibrocistiniai krūties pokyčiai.  4. Reaktyvi limfadenopatija (1 l/m).  5. Krūties audinys.  6. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) lobulinė karcinoma, suminis tyrimo TNM: pT2(navikas - 45mm) pN0(sn)(0/1 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-44252 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  Ki67+ 8%."  Lobulinė krūties Carcinoma in situ(LCIS). Fibrocistiniai krūties pokyčiai; intraduktalinės krūties papilomos.. 1. Krūties audinyje - fibrozės septos su fokaliai cistiškai dilatuotais latakais, klotais dvisluoksniu epiteliu.  2. Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakais, klotais dvisluoksniu epiteliu; židininė paprasta intraduktalinė hiperplazija.  3. Krūties audinyje - fibrozės septos su pavieniais latakėliais, klotais dvisluoksniu epiteliu.  4. Vienas (1) limfmazgis be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  5. Krūties audinyje - fibrozės septos su pavieniais latakėliais, klotais dvisluoksniu epiteliu.  6. Krūties fibroziniame ir tarp lipocitų plinta navikas, formuojamas difuziškai ir trabekulėmis plintančių vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutinio kalibro ląstelių, nežymiai, vietomis vidutiniškai polimorfiškais branduoliais; navike iki 4 mitozių/10 DPRL; pavieniai dilatuoti latakėliai su solidiniais diskohezyvių atipinių ląstelių proliferatais (LCIS). Krūties audinyje - pavieniai dilatuoti latakai su fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu; fokaliai cistiškai dilatuotais latakais, klotais dvisluoksniu epiteliu. Naviko struktūros - koaguliuotame giliajame rezekcijos krašte.. nan
answer:  0

 45%|████▍     | 297/661 [08:19<10:06,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a - naviko kraštai (ekstra tvarka) - be naviko  2 ėminio aprašas: N2b - naviko kraštai (ekstra tvarka) - be naviko  3 ėminio aprašas: N3- sarginis l/m dešinės pažasties (ekstra tvarka) - 3 l/m viename iš trijų mikrometastazė  4 ėminio aprašas: N1: kvadrantas (planine tvarka). 4. Krūties sektorius 10,5x7x5 cm, su odos lopu 10,5x4 cm. Pjūvyje balkšvas, standus, gan aiškių ribų navikas 42x30x39 mm, nuo odos nutolęs 1,5 cm, nuo artimiausio rezekcijos krašto - 0,1 cm. Rezekcijos kraštas dažytas mėlynai, tarp pjūvių - žaliai.. 1(ekstra). Riebalinis fibrozinis audinys.  2(ekstra). Krūties audinys.  3(ekstra). Krūties karcinomos mikrometastazė limfmazgyje (microMTS 1/3 0,6 mm).    4. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) mišri duktalinė-lobulinė karcinoma, SUMINIS TNM: pT2(42 mm navikas) pN1mi(microMTS 1/3 0,6 mm). LVI-2(limfovaskulinė invazija). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 1% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+).  Ki67 proliferacinis aktyvumas 25%.  HER2 geno amplifikacija vertinta IHC kontekste, interpretuota kaip NEIGIAMA (žr. molekulinio tyrimo aprašymą ir pastabas).. 1(ekstra). Riebalinis fibrozinis audinys.  2(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 1 iš 3 limfmazgių aprašyto naviko mikrometatazės iki 0,6 mm.  4. Krūtyje - navikas ekspansyviu augimo frontu, suformuotas trabekulinėmis struktūromis, lizdais, solidiniais potais grandinėlėmis bei pabirai besidėstančių ląstelių vidutinio gausumo eozinofiliška ir gausesne ryškai, grūdėta citoplazma, vidutiniais - stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, dalis ekscentriškais branduoliais ryškiomis nukleolėmis; mitozių 18/10 DPRL. Limfovaskulinė invazija.. Navikas(19 blokas):  E-cadherin(+++) membr. r-ja 100% duktaliniame komponente, (+) trūkinėjanti r-ja 40%.
answer:  0.

 45%|████▌     | 298/661 [08:21<10:08,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra;  2(2b). Kraštai - extra;  3. Kairės pažasties sarginis limfmazgis - extra (viename iš trijų limfmazgių mikrometastazė);  4(1). Pašalintas kairės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 13x6,5x5 cm su odos lopu 13,5x3,5 cm. Pjūvyje, balkšvas, standus, neaiškių ribų navikas 42x38x26 mm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos – 2,5 cm. 1(ekstra). Riebalinis audinys.  2(ekstra). Riebalinis audinys.  3(ekstra). Krūties duktalinės karcinomos mikrometastazė limfmazgyje (1/3 l/m micro MTS 0,9 mm).  4. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(42 mm navikas) pN1mi(sn)(1/3 l/m microMTS 0,9 mm)LVI-4(masyvi limfovaskulinė invazija venose ir smulkiose limfagyslėse). R0(radikali rezekcija).  Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis tipas).    Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: silpna reakcija 5% naviko ląstelių.   Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.. 1(ekstra). Riebalinis audinys.  2(ekstra). Riebalinis audinys.  3(ekstra). 1 iš 3 limfmazgių aprašyto naviko mikroametastazė 0,9 mm.  4. Krūtyje - navikas ekspansyviu augimo frontu, suformuotas nereguliariomis, trabekulinėmis struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių  vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 15/10 DPRL. Greta dilatuoti kanaliukai su solidiniais proliferatais iš analogiškų navikui ląstelių. Limfovaskulinė invazija venose ir smulkiose limfagyslėse.. Navikas:(11 blokas):  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: (+)(brand. r-ja) 5%.  HER2: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.
answer:  1(

 45%|████▌     | 299/661 [08:23<10:28,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 pjūvio kraštas, ekstra.   2 ėminio aprašas: 2 pjūvio kraštas, ekstra.  3. sarginiai l/m, ekstra  4. sektorius, planinis.. 4. Krūties sektorius 12x6x4 cm su oda 7x3,5 cm. Krūties audinyje pilkšvas, apvalios formos, aiškių ribų navikas 1,9x1,8x1,8 cm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2 cm.   Odoje ruda dėmė 0,2x0,2 cm, nuo odos rezekcijos krašto nutolusi 1,5 cm ir pilkšvas, smulkiai gruoblėtas darinys 0,5x0,4x0,1 cm, nuo dėmės nutolęs 2 cm, nuo odos rezekcijos krašto - 1 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/2 l/m, 4,75 mm, ekstranodalinis plitimas).   4. Krūties invazyvi blogai diferencijuota (G3; 8 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 19 mm), pN1a(sn)(1/2 l/m, 4,75 mm metastazė), LVI0(neidnetifikuota). Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS).  Estrogenų receptoriai: reakcijos nėra. HER2:reakcijos nėra (0). Ki67: proliferacinis indeksas 30%. Karštame taške 40%. Progesterono receptoriai: reakcijos nėra.  Androgenų receptoriai: reakcijos nėra.   Seborėjinė keratozė. Hemangioma (vyšninė angioma).. 1. Krūties audinyje židininė fibrozė su negausiais dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.   2. Krūties audinyje židininė fibrozė su negausiais dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.   3. Viename limfmazgyje iš dviejų (1/2 l/m) žemiau aprašyto naviko metastazė iki 4,75 mm su ekstranodaliniu plitimu.  4. Krūties audinyje, hialinizuotoje stromoje - navikas (19 mm makroskopškai) infiltratyviu augimo frontu su plačia centrine nekrozės zona. Navikas suformuotas smulkių lizdinių, trabekulinių ir negausių tubulinių (apie 10%) naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su ryškiai polimorfiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 46/10DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Navikas nuo artimiausio rezekcijos krašto nutolęs per3 mm. Greta naviko negausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais; dalies proliferatų centruose - nekrozės zonos.   Odoje darinys suformuotas besiliejančių epidermio hiperplazijos plotų, su epidermio hiperkeratoze, papilomatoze su pavienių raginių cistų formacija.   Odoje egzofitinis darinys, klotas epidermiu, sufomruotas plonasienių varijuojančio dydžio kraujagyslių, klotų vienu sluoksniu endotelio ląstelių. Kraujagyslių spindžiuose eritrocitai.. Blokas 19:  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 30% naviko ląstelių. Karštame taške 40%.  Progesterono receptoriai: reakcijos naviko ląstelių
answer:  0.

 45%|████▌     | 300/661 [08:25<10:16,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sektoriaus kraštai - extra;  2. Sektoriaus kraštai - extra;  3. Sarginiai l/m - extra.  4. N4. Deš. krūties sektorius su naviku.. 4. Krūties sektorius 9,5x8x3,5 cm su odos lopu 7,5x3 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 1,6x1,5x1,3 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,7 cm, nuo odos – 4,5 cm. Šalia naviko fibrozės zona 4x3x3 cm.. 1. Sektoriaus kraštai - krūties audinys be patologinių pokyčių.  2. Sektoriaus kraštai - krūties audinys be patologinių pokyčių.  3. Sarginiai l/m: karcinomos mikrometastazė 1-me/2 limfmazgyje; pN1mi.    4. Dešinės krūties sektorius su naviku.   Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;   pT1c pN1mi pR0.  Imunotipas (priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 40%.. 1. Sektoriaus kraštai - krūties audinys be patologinių pokyčių.  2. Sektoriaus kraštai - krūties audinys be patologinių pokyčių.  3. Sarginiai l/m: 1-me limfmazgyje iš 2 - nežymiai atipinių epitelinių ląstelių 1,5 mm židinys.  4. Dešinės krūties sektorius su naviku. Krūties audinį infiltruoja naviko negausios duktalinės struktūros, netaisyklingi kribroziniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.. nan
answer:  1a

 46%|████▌     | 301/661 [08:26<09:50,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 16 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma (su mucininės diferencijacijos požymiais).  ---  Estrogenų receptoriai: stiprus(+++) branduolinis/membraninis dažymasis 100% .   Progesterono receptoriai: vidutinis(++) branduolinis dažymasis 60% .   Her2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 10%.. Trabekulines, negausias smulkias solidines naviko struktūras formuoja ląstelės su negausia tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; ekstraląstelinių mucinų židiniai navike; mitozių navike iki 4 / 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus(+++) branduolinis/membraninis dažymasis 100% .   Progesterono receptoriai: vidutinis(++) branduolinis dažymasis 60% .   HER2: nusidažiusių naviko ląstelių nėra.  Ki67: 10% .   E-Cadherin: membraninis dažymasis 100%
answer:  3b

 46%|████▌     | 302/661 [08:28<09:41,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais ~8 mm dydžio darinys kairiojoje krūtyje ties ~6 val. vidurinėje dalyje, paimti 2 biopsiniai stulpeliai histologijai.. 2 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 9 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 10%.
answer:  0

 46%|████▌     | 303/661 [08:29<09:35,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Pašalinta dešinė krūtis su m.pectoralis - planinis tyrimas.. Krūtis 120 gramų svorio, 12,5x6,5x2,5 cm su raumens fragmentu 6x3,8x1,2 cm. Krūties odoje, šalia spenelio išopėjimas 4,5x3 cm. išopėjimo projekcijoje, krūties audinyje - balkšvas, standus navikas 5,3x4,8x2,4 mm, nuo artimiausio rezekcijos krašto nutolęs <0,1 cm, peraugą odą. Raumens fragmente, pjūvyje balkšvas standus mazgas 4,9x3,5x1,1 cm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b(m) (53mm ir 49mm, išopėjimas).. Krūties audinyje 53mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 8/10 DPRL. Epidermyje virš naviko smulkūs išopėjimai. Tokios pačios struktūros 49mm navikas skersaruožių raumenų fragmente.  Navikas plačiai plinta giliajame skersaruožių raumenų ir krūties audinio rezekcijos krašte.. nan
answer:  3b

 46%|████▌     | 304/661 [08:31<09:25,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 11 mm; II - 6 mm; III - 5 mm.. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) karcinoma su tarpiniais lobulinės - duktalinės karcinomos požymiais.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai:  neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 1%.. Bioptatuose (3/3) - fibrozinėje stromoje ir riebaliniame audinyje infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, grandinėlėmis ir pabirai besidėstančių ląstelių negausia eozinofiliška citoplazma, nežymiai polimorfiškais, vidutinio kalibro, ovalaus kontūro branduoliais; mitozių 0/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: neigiama reakcija.  HER2: nusidažiusių naviko ląstelių nėra.  Ki67 proliferacinis aktyvumas 1%.  E-cadherin(+++) membr. r-ja 100%
answer:  1b

 46%|████▌     | 305/661 [08:32<09:32,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai  - skubus tyrimas be naviko  2(N2b) kraštai  - skubus tyrimas be naviko  3(N3) kairės pažasties sarginis limfmazgis - skubus tyrimas 2 l/m be naviko  4(N1): pašalintas kairės krūties kvadrantas  - planinis tyrimas. 4. Krūties sektorius 10,5x7x4 cm su odos lopu 9x2 cm. Pjūvyje pilkšvas, standus, neaiškių ribų navikas 25x16x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1,6 cm.. 1(Extra). Krūties audinys.  2(Extra). Riebalinis audinys.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(21 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).. 1(2a)(Extra). Krūties audinyje - pavieniai smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2(2b)(Extra). Brandus riebalinis audinys su neryškia fibroze.  3(Extra). 2 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 21 mm), suformuotas fibrozuotoje stromoje plintančių lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 9/10 DPRL. Šalia yra dilatuotų kanaliukų su solidiniais, kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais, fokaliai su negausiomis komedo nekrozėmis.. 1. Navikas (12 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 60% naviko ląstelių.
answer:  1.

 46%|████▋     | 306/661 [08:34<09:17,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 10 mm ilgio.. PAPILDYTA  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: ribinė (2+).  Ki67: 5%.  ---  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).. Smulkias solidines, trabekulines naviko struktūras formuoja gan smulkios ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 3 / 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas visos membranos nusidažymas 20% naviko ląstelių.  Prolifer
answer:  5%

 46%|████▋     | 307/661 [08:36<09:22,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais ~8x10 mm dydžio darinys kairiojoje krūtyje ties 1 val. vidurinėje dalyje, paimti du biopsiniai stulpeliai histologijai (I buteliukas).   2. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais ~13x21 mm dydžio navikas kairiojoje krūtyje ties 12 val. vidurinėje dalyje, paimti du biopsiniai stulpeliai histologijai (II buteliukas).. 1. 2 biopsiniai stulpeliai: I - 7 mm; II - 8 mm.  2. 2 biopsiniai stulpeliai: I - 16 mm; II - 12 mm.. 1. Vidutiniškai diferencijuota (G2,6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  2. Vidutiniškai diferencijuota (G2,6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 98% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 7%.. 1. Krūties audinį infiltruoja grandinėlės, trabekulės, smulkūs lizdai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.  2. Krūties audinį infiltruoja grandinėlės, trabekulės, smulkūs lizdai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Blokas 1:  E-Cadherin: neigiama reakcija naviko ląstelėse.  Estrogenų receptoriai: stipri (+++) reakcija, 98% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkulia
answer:  10%

 47%|████▋     | 308/661 [08:37<09:17,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Invazinė duktalinė karcinoma (su apokrinine ER-/AR+ diferenciacija ir onkocitiniu MITO+ imunofenotipu; M8401/3)    (mažiausiai iki 8,5 mm);   (G2; 7 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcijos nėra (0). HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 5%. Karštame taške 10%.. Krūties audinį 1-me bioptate infiltruoja iki 8,5 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su neryškiai ryškiai polimorfiškais branduoliais (AR+) gausioje eozinofilinėje citoplazmoje (su gausiomis MITO+ mitochondrijomis);   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Androgenų receptoriai: stipri  teigiama (+++) branduolių reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių membranoje nėra (stipri reakcija citoplazmoje
answer:  0.

 47%|████▋     | 309/661 [08:39<09:11,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: kairė krūtis, planinis. Krūtis, 626 g svorio, 20x20x7 cm. Krūties audinys difuziškai nežymiai fibrozuotas. Patologinių židinių nerasta.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (8mm navikas).  Estrogenų receptoriai: stiprus ir vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymom nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinyje 8mm navikas: smulkios duktalinės struktūros, smulkūs solidiniai kompleksai ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  Rezekcijos kraštas be naviko.. Navikas  Estrogenų receptoriai: stiprus ir vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymom nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.
answer:  1a

 47%|████▋     | 310/661 [08:40<09:12,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas kairės krūties darinys, paimti 3 biopsiniai stulpeliai medžiagos histologiniam ištyrimui.. 3 biopsiniai stulpeliai: I - 18 mm; II - 12 mm; III - 16 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: silpna (+) reakcija, 3% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%. Karštame taške 70%.. Krūties audinį 3-se bioptatuose infiltruoja iki 12 mm :   - pavienės duktalinės struktūros ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 7/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 30% naviko ląstelių. Karštame taške 70%.  Progesterono receptoriai: silpna (+) reakcija, 3% na
answer:  3a

 47%|████▋     | 311/661 [08:42<09:32,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sarginiai limfmazgiai, ekstra.   2. Kairė krūtis, planinis.. 2. Krūtis 604 gramų svorio, 20x17x4,5 cm. Krūties audinyje, viršutiniame lateraliniame kvadrante 3 neaiškių ribų balkšvi navikai:  - I 2,5x1x1 cm, nuo odos nutolęs 4,5 cm, nuo artimiausio rezekcijos krašto - 0,4 cm.  - II 2,2x0,6x cm, nuo odos nutolęs 3,5 cm, nuo artimiausio rezekcijos krašto - 2,5 cm.  - III 1,5x1x1 cm, nuo I naviko nutolęs 5,5 cm, nuo II naviko - 4,5 cm, nuo odos - 2,5 cm, nuo artimiausio rezekcijos krašto - 0,3 cm.  Apatiniame lateraliniame kvadrante neaiškių ribų židinys 2x1,5x1 cm, nuo I naviko nutolęs 2,5 cm, nuo artimiausio rezekcijos krašto - 1,5 cm, nuo odos - 4,5 cm.. 1(Extra). Krūties lobulinės karcinomos metastazės 2/3 l/m (10 mm ir 4 mm).  2. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT(m)1c(2 naviko židiniai: 11 mm ir 11 mm) pN(sn)1a(mts 2/3 l/m: 10 mm ir 4 mm), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).  Lobulinė karcinoma in situ (LCIS).. 1(Extra). 3 limfmazgiai su antriniais limfoidiniais folikulais ir sinusų histiocitoze. Dviejuose limfmazgiuose - žemiau aprašyto naviko metastazės (10 mm ir 4 mm).   2. SPENELIS: normali histologinė struktūra; fokaliai stambūs latakai užpildyti monomorfiškomis ląstelėmis apvaliais, su smulkia nukleole branduoliais (LCIS); dilatuoti latakai žemiau.   NAVIKAS: krūties audinyje - 2 analogiškos struktūros navikai (mikroskopiškai 11 mm ir 11 mm), suformuoti fibrozuotoje stromoje infiltratyviai plintančių trabekulinių struktūrų, grandinėlėmis, smulkiomis grupelėmis ar pabirai besidėstančių ląstelių negausia švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais/apvaliais, kiek polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 3/10 DPRL. Aplink naviko židinius gausiai dėstosi kanaliukai, užpildyti monomorfiškomis, analogiškomis navikui ląstelėmis (LCIS). Limfovaskulinė invazija. Rezekcijos kraštai - be naviko plitimo.  Aplinkiniame krūties audinyje, fibrozuotoje stromoje dilatuoti latakai, kloti suplokštėjusiu epiteliu.. 2. Navikas (II) (16 blokas): E-cadherin (-).
answer:  0.

 47%|████▋     | 312/661 [08:43<09:15,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja negausios smulkios duktalinės struktūros, siauros šakotos juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  1b

 47%|████▋     | 313/661 [08:45<09:03,  1.56s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Kairės krūties areolės srities punch bioptatas. Odos bioptatas 0,5x0,4x0,6 cm, rusvu, gruoblėtu paviršiumi.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Odą ir poodinį riebalinį audinį infiltruoja smulkios duktalinės struktūros, nedideli netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 60% naviko ląsteli
answer:  1 �

 48%|████▊     | 314/661 [08:47<09:03,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. deš krūtis, planinis.   2. sarginiai l/m, planinis.. 1. Krūtis 356 gramų svorio, 17x14x5 cm. Krūties audinyje, viršutinių kvadrantų riboje balkšvas, standus, neaiškių ribų navikas 25x18x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1,6 cm. Apatiniame lateraliniame kvadrante balkšvas, standus, aiškių ribų darinys 7x6x5 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 2,7 cm, nuo naviko - 3 cm.    2. Riebalinio audinio fragmentai, bendras dydis 4x2,3x0,6 cm. Rasti 3 limfmazgiai, didžiausias 1,3 cm.. N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2(25mm).  Aukšto laipsnio indtraduktalinė karcinoma (DCIS, komedo tipas; 7mm židinys).  N3: Limfmazgiai (3 l/m) be naviko metastazių; pN0(sn).. Krūties audinyje 25mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.  Kitas 7mm navikinis židinys sudarytas iš dilatuotuose kanaliukuose plintančių ryškiai polimorfiškų ląstelių su centrinėmis nekrozėmis.  Operacinis pjūvis be naviko.  N3: Limfmazgiai (3 l/m) su reaktyviais pokyčiais, be naviko metastazių.. nan
answer:  1a

 48%|████▊     | 315/661 [08:48<09:31,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- užspenelinis audinys, skubu  2. deš. pažasties sarginiai limfmazgiai, skubu  3. deš. krūties audinys, planinis. 3. Krūties audinys 358 gramų svorio, 17x16x3,5 cm su odos lopu 8x2 cm. Krūties audinyje:  - I fibrozės zona su dilatuotais latakais 5x4x2 cm, siekia priekinį ir gilųjį rezekcijos kraštą. Zonoje pilkšvas, standus, neaiškių ribų navikas 1,4x1,2x1 cm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo priekinio – 0,3 cm.  - medialiau - II fibrozės zona 1,5x1,3x1 cm, siekianti priekinį rezekcijos kraštą, nuo giliojo rezekcijos krašto nutolusi 0,8 cm, nuo I zonos - 1,2 cm.  - III fibrozės zona 1,5x1x0,8 cm, nuo priekinio rezekcijos krašto nutolusi 1,5 cm, nuo giliojo rezekcijos krašto - 0,3 cm, nuo II zonos - 1,5 cm.  Priekinis rezekcijos kraštas dažytas juoda spalva, gilusis - žalia.. PAPILDYTA (HER2 FISH TYRIMAS):  1(Extra). Krūties audinys.  2(Extra). Reaktyvi limfadenopatija (3 l/m).  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT(m)1c(2 naviko židiniai: 12 mm ir 3 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Imunofenotipas:   HER2 imuninė reakcija: ribinė (2+).  HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).  Krūties lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS) ir kolageninė sferuliozė.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu; grupė kanaliukų su apokrinine metaplazija.  2(Extra). 3 limfmazgiai su fokaline parakortekso hiperplazija, sinusų histiocitoze ir lipomatoze.  3. Krūties audinyje - 2 analogiškos struktūros navikai (mikroskopiškai 12 mm ir 3 mm), suformuoti fibrozuotoje stromoje infiltratyviai plintančių trabekulinių struktūrų, grandinėlėmis, smulkiomis grupelėmis ar pabirai besidėstančiomis ląstelėmis negausia švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais/apvaliais, kiek polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 4/10 DPRL.   Aplink gausūs dilatuoti kanaliukai, užpildyti analogiškomis navikui ląstelėmis, grupės kanaliukų, klotų hiperplastišku epiteliu ar su stulpiniu ląstelių pokyčiu su apikalinės sekrecijos požymiais bei kanaliukai su kolagenine sferulioze, yra dilatuotų kanaliukų, klotų suplokštėjusiu epiteliu su makrofagais spindžiuose, grupės kanaliukų su apokrinine metaplazija; pavieniai smulkūs kalcifikatai.. 1. Navikas (10 blokas):  HER2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 80% naviko ląstelių.
answer:  2+

 48%|████▊     | 316/661 [08:50<09:35,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštas - extra  2. pjūvio kraštas - extra.   3. sektorius, planinis.  4. Papildomas kraštas, planinis.. 3. Krūties sektorius 11,5x8x3,5 cm su odos lopu 6x1 cm, žymėtas viela. Vielos projekcijoje, pjūvyje pilkšvas, neaiškių ribų, standus darinys 25x16x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm.    4. Riebalinio audinio fragmentas 1,3x1x0,2 cm. v/m. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 10,5 mm), LVI0 (neidentifikuota). Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių. HER2: reakcija teigiama (3+); Ki67: proliferacinis indeksas 10%. Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių. Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS).. 1. Fibrozuotame krūties audinyje gausios sklerozuotos lobulės ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  2. Fibrozuotame krūties audinyje gausios sklerozuotos lobulės ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  3. Krūties audinyje - navikas (10,5 mm mikroskopiškai), suformuotas trabekulinių, smulkių lizdinių bei negausių tubulinių struktūrų iš vidutinio gausumo eozinofiline citoplazma ląstelių, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiais branduolėliais; mitozių 10/10 DPRL. Limfovaskulinis plitimas neidentifikuotas (LVI0). Greta naviko daugybiniai dilatuoti latakai, užpildytų solidinių bei kribriforminių proliferatų, suformuotų analogiškų navikui ląstelių. Dalyje pakitusių dilatuotų latakų - centrinės komedonekrozės.. Blokas 12:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: stipri (+++) cirkuliari reakcija, 95% naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono receptoriai: stipri (+
answer:  95%

 48%|████▊     | 317/661 [08:52<09:30,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1): pašalintas dešinės krūties kvadrantas - planinis tyrimas  2(N2a): kraštai  3(N2b): kraštai  4(N3): dešinės pažasties sarginiai limfmazgis - planinis tyrimas, bei keli kietoki įtartini limfmazgiai iš II pažasties lygio  5(N4): papildomas kraštas. 1. Krūties sektorius 16,5x3,5x6 cm su oda 14x1,7 cm. Krūties audinyje, pilkšvas, standus, aiškių ribų navikas 28x20x18 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,3 cm.  2. Riebalinio audinio fragmentas 2,2x1,8x0,4 cm. v/m  3. Riebalinio audinio fragmentas 4x2,2x0,6 cm. v/m  4. Riebalinio audinio fragmentas 4,5x4x1,3 cm. Rasti 9 limfmazgiai iki 2,6 cm.  5. Riebalinio audinio fragmentas 2x1,5x0,3 cm. v/m. N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2(28mm).  N2ab ir N4: Krūties audinys be naviko.  N3: Limfmazgiai (9 l/m) be naviko židinių; pN0.. N1: Krūties audinyje 28mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.  N2ab ir N4: Krūties audinys be naviko.  N3: Limfmazgiai (9 l/m) su reaktyviais pokyčiais, be naviko židinių.. nan
answer:  1(n

 48%|████▊     | 318/661 [08:54<10:03,  1.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2) - sarginiai limfmazgiai, skubu  4(3) - deš.krūties kvadrantas, planinis. 4(3). Poodinis krūties sektorius 6,5x5,5x5 cm. Krūties audinyje - pilkšvas standus, aiškių ribų navikas 22x18x18 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm.. 1(1a, ekstra). "Viršutinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); kalcifikatai; be naviko.   2(1b, ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija); be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": karcinomos (mikro)metastazė 1 limfmazgyje (mts 1/4 l/m; 1,45 mm skersmens).     4(3). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT2 (navikas 22 mm) N1mi(sn) (mts 1/4 l/m; 1,45 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar hiperplastišku epiteliu, pavieniai kalcifikatai; arterijų sienelėse fibrozės židiniai su kalcifikatais (arteriosklerozės požymiai); be naviko.   2(1b, ekstra). "Apatinis kraštas": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS); be naviko.   3(2, ekstra). "Sarginiai limfmazgiai"(4): gilesniuose planinio tyrimo pjūviuose, vieno (1) limfmazgio kapsulėje - 1,45 mm skersmens subtotaliai koaguliuotas epitelinių (PanCK+) ląstelių židinys (labiausiai tikėtina - naviko struktūros).   4(3). NAVIKAS: krūties audinyje, fibrozuotoje, ryškiau kolagenizuotoje desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios netaisyklingos negausios duktalinės, kribriforminės ir dominuojančios lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; pavienės mitozės (mitozių ~1/10 DPRL). Limfovaskulinė naviko invazija smulkiose šakose.    APLINKA: tarp naviko struktūrų - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   SEKTORIAUS REZEKCIJOS KRAŠTAS: naviko struktūros nutolusios 1,7 mm.. 3(2, ekstra). "Sarginiai limfmazgiai":   "Koaguliuotas židinys"(6 blokas):  PANCK(+); CK7/CK20/S100(-).   4(3). Navikas (20 blokas):  HER2: silpna (+) necirkuliari reakcija, 1% naviko ląstelių membranoje.
answer:  1(

 48%|████▊     | 319/661 [08:55<09:34,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 11 mm; III - 13 mm.. Po operacinės medžiagos tyrimo patikslintas naviko tipas  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Krūties audinį infiltruoja smulkios duktalinės struktūros ir solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 5
answer:  1b

 48%|████▊     | 320/661 [08:57<09:30,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 2 biopsiniai stulpeliai iš kairės pažasties I lygio l/m  2 but. 2 biopsiniai stulpeliai iš kairės krūties  BI-RADS 4a darinio (satelitas?) apatiniame lateraliniame kv-te   3 but. 2 biopsiniai stulpeliai iš dominuojančių pakitimų BI-RADS 5 lateralinių kvadrantų ribgoje. 1. 2 biopsiniai stulpeliai: I - 8 mm; II - 6 mm.  2. 2 biopsiniai stulpeliai: I - 4 mm; II - 3 mm.  3. 2 biopsiniai stulpeliai: I - 7 mm; II - 13 mm.. 1. Limfmazgio bioptatai be patologinių pokyčių.  2. Krūties fibrocistiniai pokyčiai: sklerozuojanti adenozė.  3. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.. 2. Fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai smulkių kanaliukų proliferacijos zonos.  3. Krūties audinį 2-se bioptatuose infiltruoja iki 12 mm :   - trabekulės;  -  vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  gausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki /110 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 4:  Androgenų receptoriai: vidutinė ir stipri teigiama (++/+++) branduolių reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  navik
answer:  lą

 49%|████▊     | 321/661 [08:58<09:07,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas:  1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) mikropapilinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: teigiama (3+).  Ki67 proliferacinis aktyvumas 10%.. Bioptate, fibrozinėje stromoje infiltratyvios naviko struktūros, suformuotos mikropapilomis ir lizdais besidėstančių ląstelių gausia ryškia eozinofiliška citoplazma, polimorfiškais, vidutinio-stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 5/10 DPRL.. Navikas:  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  HER2: stiprus visos membranos nusidažymas 100% naviko ląstelių.  Ki67 proliferacinis aktyvumas 10%.
answer:  1b

 49%|████▊     | 322/661 [09:00<09:17,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 12x4,5x6 cm su oda 10,5x3 cm. Krūties audinyje, pilkšvas, standus, neaiškių ribų navikas 16x16x8 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2 cm.. 1(ekstra). Krūties audinio fibrozė.    2(ekstra). Krūties fibrocistiniai pokyčiai: įprastinė duktalinė hiperplazija, apokrininė metaplazija.    3(ekstra). Duktalinės karcinomos metastazė 1/5 limfmazgių (7 mm dydžio).     4. Krūties invazyvi gerai diferencijuota (G1, 4 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT1c (16 mm navikas)    pN1a(sn)(1/5 l/m su mts 7mm)    pLVI-0 (limfovaskulinė invazija neidentifikuota)   pR0(radikalus pašalinimas).   Naviko imunotipas nustatytas priešoperacinėje biopsijoje (nr. B23-5702):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.    Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija.. 1(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis, kompaktiškomis lobulėmis ir smulkiais kanaliukais, klotais dvisluoksniu ar hiperplastišku, papilines ir kribriformines struktūras formuojančiu epiteliu su židinine apokrinine metaplazija.  3(ekstra). 1/5 limfmazgių - žemiau aprašyto naviko metastazė 7 mm su ekstranodaliniu plitimu.      4. Krūties audinyje - desmoplastiškoje stromoje plintantis navikas, suformuotas:   tubulių (80%), kribriforminių ir trabekulinių struktūrų;    naviko ląstelės su negausia eozinofiliška citoplazma,  vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis;   mitozių navike iki 4/10DPRL.   Navike yra mikrokalcifikatų.   Dalyje kanaliukų cistinė dilatacija, paprastoji intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. nan
answer:  1a

 49%|████▉     | 323/661 [09:02<09:07,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas d. krūties BIRADS-5 darinys, paimti 3 biopsiniai stulpeliai medžiagos histologiniam ištyrimui. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 13 mm; III - 9 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma su daline mucinine diferenciacija.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 3%.. Fragmentuotuose bioptatuose (3/3) - fibrozinėje stromoje ir ekstraląsteliniuose mucinuose infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių vidutinio gausumo ryškia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 2/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67 proliferacinis aktyvumas 3%.
answer:  1a

 49%|████▉     | 324/661 [09:03<08:50,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Paimti 3 biopsiniai stulpeliai.. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 11 mm; III - 10 mm.. Krūties mucininė karcinoma; (G1, 5 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinyje mucininėje stromoje netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 10
answer:  1b

 49%|████▉     | 325/661 [09:05<09:23,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštai - extra - be naviko  2(N2b) - kraštai - extra - be naviko   3(N1) - sektorius - planinis tyrimas. 3(1). Fibrozuoto audinio fragmentas 4x2,7x0,7 cm, paviršiuje žymėtas viela. Viela žymėtoje vietoje - balkšvas, standus židinys 0,3x0,2x0,3 cm, židinys siekia artimiausią rezekcijos kraštą. Sudėta visa medžiaga.. 1(2a, ekstra). "Kraštai": normalios histologinės struktūros riebalinis audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.     3(1). Krūties invazyvi bent gerai diferencijuota (G1, bent 5 balai pagal Nottingham, žr. pastabą) duktalinė karcinoma,   SUMINIS TNM:   pT1a (navikas 1,35 mm), LVI-0 (limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.    Krūties žemo-aukšto laipsnio duktalinė karcinoma in situ (DIN1-3/DCIS: solidinis, kribriforminis, papilinis ir komedo tipai). Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, sklerozuojanti adenozė).   DCIS komponentas nuo sektoriaus rezekcijos krašto nutolęs - 0,35 mm.. 1(2a, ekstra). "Kraštai": brandžių lipocitų suformuotas vaskuliarizuotas fragmentas; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(1). NAVIKAS (šalia in situ komponento - 1,35 mm skersmens invazyvus židinys): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios suspaustos duktalinės, trabekulinės ir nedidelės lizdinės naviko struktūros, suformuotos saikingai polimorfiškų ląstelių, negausia šviesia eozinofiline citoplazma, vidutinio dydžio nelygaus kontūro ovaliais/apvaliais branduoliais su kai kur išryškėjusiomis smulkiomis nukleolėmis; mitozių tirtuose naviko pjūviuose nevizualizuota, maksimalus naviko plotas 4 DPRL.   APLINKA: šalia naviko - solidiniai, kribriforminiai, papiliniai intraduktaliniai naviko ląstelių proliferatai su  keliomis centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: in situ komponentas nutolęs 0,35 mm.. 3(1). Navikas (blokas 5):  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.   HER2: silpna (+) necirkuliari reakcija, 3% naviko ląstelių
answer:  1+

 49%|████▉     | 326/661 [09:07<09:11,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 13 mm; II - 11 mm.. Krūties invazyvi žemo laipsnio adenoidinė cistinė karcinoma, tubulinis-trabekulinis tipas   (taikant Nottingham gradavimą, karcinoma atitinka gerai diferencijuotą; G1, 5b.).   Imunofenotipas:  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: silpna (+) reakcija, 30% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 5%.. Bioptatų (2/2) fibrozinėje stromoje gausios infiltratyvios naviko struktūros (plinta mažiausiai 10 mm), suformuotos trabekulėmis, tubulėmis ir kribriforminėmis struktūromis, su reguliariais spindžiais besidėstančių duktalinio tipo ląstelių  negausia eozinofiliška tamsia citoplazma ir bazaloidinių ląstelių nežymiai polimorfiškais branduoliais; mitozių 2/10 DPRL.. Blokas 1:  CD117: silpna teigiama (+)  membraninė reakcija pavienėse atipinėse ląstelėse  CK14: stipri teigiama (+++) membraninė reakcija 100 proc. epitelio ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos n
answer:  0.

 49%|████▉     | 327/661 [09:08<08:52,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+
answer:  2%

 50%|████▉     | 328/661 [09:10<09:01,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. (1a)- viršutinis kraštas, skubu  2. (1b)- apatinis kraštas, skubu  3. (2) Deš. pažasties sarginiai limfmazgiai, skubu  4. (3) deš. krūties sektorius, planinis.. 4. Krūties sektorius 7,5x6x2 cm, be odos, žymėtas viela. Vielos projekcijoje krūties audinys fibrozuotas 3,5x1,8 cm plote, nuo giliojo rezekcijos krašto nutolęs 0,2 cm. Krūties audinyje standus, neaiškių ribų navikas 22x16x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm.. 1.(1a) Riebalinis audinys.  2.(1b) Fibrocistiniai krūties pokyčiai.  3.(2) Reaktyvi limfadenopatija (2 l/m).  4.(3) Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(m)(dauginiai naviko židiniai nuo 0,6mm iki 22mm) pN0(sn)(0/2 l/m).   IHC reakcijos atliktos VPC:B23-30662 tyrime:  "Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0)."  Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis tipas; -komedo tipo nekrozės).. 1.(1a) Riebalinis audinys su fibrovaskulinėmis septomis.  2.(1b) Riebalinis audinys su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu.  3.(2) Du(2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4.(3) Krūties audinyje - dauginiai naviko židiniai (nuo 0,6mm iki 22mm), formuojami trabekulinių, solidinių/lizdinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais, hiperchromiškais branduoliais su fokaliai išryškėjusiomis nukleolėmis; navike iki 20 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozių židiniais (DCIS).. Navikas:  E-Cadherin(+++), membr. r-ja, 100%;   P120(+++), membr. r-ja, 100%.
answer:  0

 50%|████▉     | 329/661 [09:11<08:49,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Infiltracinė multižidininė krūties NST karcinoma, pT(m)2 (2,2x2,1cm ir 0,7x0x7cm) N0 (2 limfmazgiai be metastazių; sentinelinio limfmazgio statusas neįvertintas) LVI1 R0 G3 (8 balai pagal Nottingham). Abiejų navikinių mazgų IH profilis vienodas: ER/PR 0/8 balų pagal Allred. HER2 imuninė reakcija ribinė (2+).. Konsultacijai gauta:  - 1 parafino blokas (žymėtas "23/00684");  - 1 histologinis preparatas (žymėtas ""23/00684"", dažytas HER2 metodu).. Krūties invazyvi duktalinė adenokarcinoma (ne mažiau kaip vidutiniškai diferencijuota / G2 / 7 balai pagal Nottingham).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).. Krūties audiyje - navikas: kribrozines (dominuoja), pavienes solidines naviko struktūras formuoja ląstelės su vidutinio gausumo ųvelniai eozinofiline citoplazma, vidutinio kalibro ar stambesniais, apvalios formos, kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike ne mažiau 3 / 10 DPRL.. nan
answer:  3b

 50%|████▉     | 330/661 [09:13<08:33,  1.55s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 17 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.. Krūties audinį infiltruoja duktalinės struktūros ir negausūs nedideli netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 1-2% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 20% n
answer:  0

 50%|█████     | 331/661 [09:14<08:23,  1.53s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 11 mm; II - 9 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus ir vidutinis branduolių nusidažymas 40% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja negausios duktalinės struktūros, smulkūs solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus ir vidutinis branduolių nusidažymas 40% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% n
answer:  0

 50%|█████     | 332/661 [09:16<09:05,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2) - kairės pažasties sarginis limfmazgis  - skubus tyrimas 2 l/m be naviko.  2(1) - pašalinta kairė krūtis - planinis tyrimas. 2(1). Krūtis 683 gramų svorio, 20x16,5x5 cm. Krūties spenelyje balkšvas plotas 0,9x0,5 cm, odoje rusva dėmė 0,4x0,3 cm, nuo odos rezekcijos krašto nutolusi 2,8 cm. Krūties lateralinė dalis gauta markiruota metileno mėliu. Krūties audinyje, pilkšva, standi, netolygių kraštų su taškinėmis nekrozės zonomis fibrozės zona 6,5x4,5x3,5 cm, nuo giliojo rezekcijos (dažytas mėlynu tušu) krašto nutolusi 0,8 cm, nuo odos - 1 cm. Histologiniam ištyrimui sudėtas kas antras fibrozės pjūvis, pradedant nuo metileno mėliu markiruotos dalies. Rastas intramamarinis limfmazgis 0,5 cm.. PAPILDYTA  1(2). Reaktyvi limfadenopatija (2 l/m), lipomatozė.  2(1). A) Krūties invazyvi karcinoma (galimai mikropapilinė, ne mažiau kaip vidutiniškai diferencijuota / G2 / 7 balai pagal Nottingham).  Naviko kategorizacija pagal TNM (Nr.1-Nr.2): pT1a(1,5 mm navikas) N0(sn) (0/2 l/m + 0/1 intramamarinis l/m). LVI0(limfovaskulinės invazijos nėra). R0(radikalus naviko pašalinimas).  B) Krūties aukšto laipsnio intraduktalinė karcinoma (DCIS/DIN3; mikropapilinis, kribriforminis, plokščias tipai; iki 6 cm skersmens zona).  C) Krūties fibrocistiniai pokyčiai.  D) Krūties odos arterioveninė hemangioma.  ---  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2 imunohistocheminė reakcija: teigiama (3+).  Ki67: ~10%.. 1(2). Du (2) limfmazgiai su sinusų histiocitoze, lipomatoze.  2(1). KRŪTIES SPENELIS: daugiasluoksnis plokščias epitelis fokaliai akantotiškas, su besiliejančiais akantotiniais pluoštais.  KRŪTIS: Krūties audinyje (šalia spenelio ir atokiau: A) gausūs "DCIS kanaliukai" (stambūs ir smulkesni latakai, iškloti "plokščiu", mikropapilines ar kribrozines struktūras formuojančiu epiteliu, suformuotu ląstelių su gausoka tamsia eozinofiliška citoplazma, vidutinio ar stambaus kalibro, ovoidiškais netolygaus kontūro/polimorfiškais branduoliais smulkiai grūdėtu chromatinu ir stambiomis nukleolėmis, B) 1,5 mm invazyvios karcinomos židinys (smulkios solidinės ar mikropapilinės analogiškų aukščiau aprašytoms ląstelių formuojamos struktūros; mitozių invazyviame navike neidentifikuota (3 didelio padidinimo regos laukuose). Nenavikiniame krūties audinyje - fibrozė, su įvairaus kalibro kanaliukais.  Vienas (1) intramamarinis limfmazgis su sinusų histiocitoze, pavieniais pigmenuotais makrofagais parakortekse, lipomatoze.  KRŪTIES ODOS DARINYS: Papilinėje dermoje - smulkus darinys iš smulkių, nereguliarių kraujagyslių, dalis hialinizuota sienele, su negausiais eritrocitais spindyje.. Blokas 34: CK14+ mioepitelis DCIS struktūrose.   Blokas 36: CK14+ mioepitelis DCIS struktūrose; invazyviame navike mioepitelinio išklojimo nėra.  Estrogenų receptoriai: reakcijos invazyvaus naviko ir DCIS ląstelių branduoliuose nėra.  Progesterono recepto
answer:  1+

 50%|█████     | 333/661 [09:18<09:54,  1.81s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - deš. pažasties sarginiai l/m-extra  2 - k. pažasties sarginiai l/m- ekstra  3 - deš. krūtis  4 - k.krūtis 3-4 planniam tyrimui. 3. Krūtis 1055 gramų svorio, 24x18x5 cm. Krūties audinyje, apatinių kvadrantų riboje - balkšvas, standus, neaiškių ribų navikas 15x14x11 mm, nuo odos nutolęs 4,5 cm, nuo giliojo rezekcijos krašto - 0,3 cm. Šalia naviko fibrozės zona su dilatuotais latakais 4x3x1,5 cm, siekia odą, nuo giliojo rezekcijos krašto nutolęs 1,5 cm. Odoje rusvas smulkiai gruoblėtas darinys 0,8x0,6x0,1 cm, nuo artimiausio rezekcijos krašto nutolęs 3 cm.  4. Krūtis 1400 gramų svorio, 27x23x6,5 cm. Krūties audinyje, išorinių kvadrantų riboje - balkšvas, standus neaiškių ribų navikas 6x6x5 mm (sudėtas visas), nuo odos nutolęs 2 cm, nuo giliojo rezekcijos krašto - 3 cm. Krūties audinys fibrozuotas. Odoje rusva dėmė 1x0,7 cm, nuo odos rezekcijos krašto nutolusi 2 cm ir rusvas smulkiai gruoblėtas darinys 0,5x0,4x0,1 cm, nuo odos rezekcijos krašto nutolęs 0,8 cm.. 1(Extra). Reaktyvi limfadenopatija (3 l/m).  2(Extra). Reaktyvi limfadenopatija (3 l/m).  3. Krūties (dešiniosios) invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(15 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).  Odos seborėjinė keratozė.  4. Krūties (kairiosios) invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(6 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: įprastinė duktalinė hiperplazija, fibroadenomatozinė hiperplazija.   Odos seborėjinė keratozė.. 1(Extra). 3 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  2(Extra). 3 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  3.  SPENELIS: normali histologinė struktūra; dilatuoti latakai žemiau.   NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai 15 mm), suformuotas fibrozuotoje stromoje plintančių fokaliai besiliejančių tubulinių, kribriforminių ir negausių trabekulinių bei lizdinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais/apvaliais, kiek polimorfiškais, dalis skeltais ar su smulkia nukleole branduoliais. Mitozių iki 3/10 DPRL.  KRŪTIS: aplinkiniame krūties audinyje yra dilatuotų kanaliukų su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais (DCIS) bei kanaliukų, užpildytų monomorfiškomis ląstelėmis (LCIS); grupės kanaliukų, klotų stulpiniu epiteliu su apikalinės sekrecijos požymiais ar epitelio hiperplazija, yra kanaliukų su apokrinine metaplazija bei dilatuotų kanaliukų, klotų suplokštėjusiu epiteliu.  ODA: darinys su epidermio papiliarizacija ir neryškia akantoze ir hiperkeratoze, bazinių ląstelių hiperplazija ir hiperpigmentacija bei smulkiomis keratininėmis cistomis.  4. SPENELIS: normali histologinė struktūra; dilatuoti latakai bei keli kanaliukai su epitelio hiperplazija žemiau.  NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai -- mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių struktūrų, grandinėlių ir smulkių grupių ląstelių negausia švelniai eozinofiliška citoplazma, smulkiais ir vidutinio kalibro, ovaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 4/10 DPRL.  Šalia yra kanaliukų, užpildytų analogiškomis navikui ląstelėmis ir fibroadenomatozinė hiperplazija.  ODA: darinys su epidermio papiliarizacija ir neryškia akantoze ir hiperkeratoze, bazinių ląstelių hiperplazija ir hiperpigmentacija bei smulkiomis keratininėmis cistomis.. nan
answer:  1a

 51%|█████     | 334/661 [09:20<09:45,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a- skubus - kraštai  2 N2b kraštai - skubus tyrimas - be naviko (DICS įtarimas Nr2a krašte)  3. N3: dešinės pažasties sarginis limfmazgis  - skubus tyrimas 4l/m be naviko  4. N1: pašalintas dešinės krūties kvadrantas - planinis tyrimas   5. N4: papildomas kraštas - planinis tyrimas. 4(N1). Krūties sektorius 8x4,5x6 cm su odos lopu 7,5x3 cm, žymėtas viela. Odoje pilkšvai melsvas, gruoblėtas, egzofitinis darinys 0,7x0,4x0,4 cm, nuo odos rezekcijos krašto nutolęs 0,7 cm. Vielos projekcijoje pilkšvas, neaiškių ribų navikas 15x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2 cm.  5(N4). Riebalinio audinio fragmentas 2x1,6x0,4 cm. v/m. 1(N2a). Krūties žemo laipsnio duktalinės karcinoma (DCIS, kribriforminis tipas).  2(N2b). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (4 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.5): pT1c(1,5 cm) pN(sn)0 (0/4 l/m). LVI0(limfovaskulinės invazijos nėra. Krūties odos kapiliarinė hemangioma.  5(N4). Riebalinis audinys.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 10%.. 1(N2a). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; keli kanaliukai su gan monotoniškų ląstelių kribriforminiais proliferatais spindžiuose.  2(N2b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N3). Sinusų histiocitozė keturiuose (4) limfmazgiuose.  4(N1). Krūties audinyje - navikas: trabekulines, negausias smulkias tubulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 12 / 10 DPRL. Krūties odoje - kapiliarinio tipo kraujagyslių suformuotas darinys/navikas.  5(N4). Brandūs lipocitai, negausus fibrozinis audinys.. nan
answer:  1(n

 51%|█████     | 335/661 [09:22<09:52,  1.82s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. sarginiai l/m, ekstra.   2. deš krūtis, planinis.. 2. Krūtis 437 gramų svorio, 20x14x5 cm. Odoje pilkšvai rusvi, stambiai gruoblėti dariniai 1,2x0,6x0,1 cm, artimiausias nuo odos rezekcijos krašto nutolęs 0,3 cm. Krūties audinyje, viršutiniame, lateraliniame kvadrante - balkšvas, standus kiek neaiškių ribų navikas 0,9x0,7x0,7 cm (sudėtas visas), nuo odos nutolęs 2,7 cm, nuo giliojo rezekcijos krašto - 3,5 cm. Atokiau, viršutiniame lateraliniame kvadrante ir centrinėje krūties dalyje - pilkšvi apvalūs, standūs dariniai iki 0,7 cm skersmens, nuo artimiausio rezekcijos krašto nutolę 1,5 cm, nuo odos 2 cm, artimiausias nuo naviko nutolęs 2,5 cm.. 1. Reaktyvi limfadenopatija (3 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma,   pT1b (9 mm) pN0(sn) (0/3 l/m); LVI0 (limfovaskulinės naviko invazijos neidentifikuota).   Žemo laipsnio duktalinė karcinoma in situ (DCIS, kribriforminė).   Lobulinė karcinoma in situ (LCIS).   Daugybinės intraduktalinės papilomos ir radialiniai randai.   Fibrocistiniai pokyčiai, stulpinis epitelio pokytis su apikalinės sekrecijos požymiais.   Krūties odos seborėjinė keratozė.. 1. Limfmazgiai (3) su ryškia lipomatoze, negausiu limfoidiniu audiniu su tušuota architektūra, negausiais pirminiais folikulais, be naviko plitimo.   2. Spenelis be patologinių pokyčių.   Krūties audinyje - navikas, formuojamas infiltratyviai plintančių, glaudžiai besidėstančių grandinėlių, trabekulinių ir pavienių smulkių blogai suformuotų liaukinių struktūrų, smulkių grupių, sudarytų iš nedidelių-vidutinio dydžio poligonalinių ląstelių šviesiai eozinofiliška citoplazma, nežymiai ar vidutiniškai polimorfiškais ovaliais ar skeltais branduoliais su vezikulizuotu chromatinu, smulkiomis nukleolėmis. Navike iki 1 mitozės/ 10 DPRL. Limfovaskulinės invazijos neidentifikuota. Naviko periferijoje yra latakų su intraduktaliniais solidiniais ir "intraepiteliniais" proliferatais, sudarytais iš aukščiau aprašytam navikui analogiškų ląstelių.   Naviko aplinkoje ir krūties audinyje - daugybinės intraduktalinės šakotos papilinės struktūros, klotos mioepitelinėmis ir dauktalinio epitelio ląstelėmis, su netolygia, fokaliai ryškia hiperplazija. Keli žvaigždiški elastozės ir fibrozės židiniai su stromos deformuotais varijuojančio dydžio ir cistiškai pakitusiais latakais, apokrinine epitelio metaplazija. Viename radialiniame rande - grupė latakų su intraduktaliniais kribriforminiais proliferatais iš duktalinio tipo ląstelių su nežymiu branduolių polimorfizmu.   Cistiškai dilatuotų latakų grupės su apokrinine epitelio metaplazija, lobulių tipo vidutinio dydžio kanaliukų proliferatai su stulpiniu epitelio pokyčiu ir apikalinės sekrecijos požymiais.  Odoje - epidermio dariniai, iškloti hiperplastišku, akantotišku, vietomis papiliarizuotu, hiperkeratotišku daugiasluoksniu plokščiu epiteliu, suformuotu iš bazaloidinių ląstelių su raginėmis cistomis, bazalinio epidermio sluoksnio hiperpigmentacija.. nan
answer:  1a

 51%|█████     | 336/661 [09:23<09:18,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 3 biopsiniai stulpeliai.. 3 biopsiniai stulpeliai: I - 8 mm; II - 12 mm; III - 14 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.. Krūties audinį infiltruoja susiliejančios duktalinės struktūros ir netaisyklingi kribroziniai/solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 7/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 100% n
answer:  1a

 51%|█████     | 337/661 [09:25<09:13,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 but. 2 biopsiniai stulpeliai iš kairės krūties BI-RADS 4c darinio  2 but. 3 biopsiniai stulpeliai iš dešinės krūties BI-RADS 5 darinio. 1. 2 biopsiniai stulpeliai: I - 15 mm; II - 14 mm.  2. 3 fragmentuoti biopsiniai stulpeliai: I - 6 mm; II - 1 mm; III - 2 mm.. 1. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G2; 7 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    2. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 3 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se navikinio audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.. 1. Krūties audinį 2-se bioptatuose infiltruoja iki 13 mm :   - solidiniai kompleksai ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su ryškiai polimorfiškais branduoliais  negausioje bazofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.    2. Naviko audinį 3-se bioptatuose infiltruoja iki 3 mm :   - solidiniai kompleksai;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje bazofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 80%  naviko ląstelių mem
answer:  0.

 51%|█████     | 338/661 [09:27<08:50,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 2 biopsiniai stulpeliai.. 2 biopsiniai stulpeliai: I - 13 mm; II - 9 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja smulkūs solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 1
answer:  1b

 51%|█████▏    | 339/661 [09:28<08:50,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas dešinė krūtis ir dešinės pažasties limfmazgiai. Krūtis 140 g svorio, 13x8,5x2 cm. Spenelio projekcijoje pilkšvas, standus neaiškių ribų navikas 37x35x25 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, siekia odą.   Atskirai tame pačiame inde riebalinio audinio fragmentai, bendras dydis 5,5x5x1,5 cm, didžiausias fragmentas žymėtas viela. Vielos projekcijoje, pilkšvas, ribotas židinys 15x10x6 cm, žymėtas spaustuku.   Rasta 10 limfmazgių iki 2,5 cm.. Invazinė duktalinė (kitaip neklasifikuojama)  karcinoma;  (G2; 6 b. pgl. Nottingham sist.);  pT2(37 mm) pLVI-2 pN1a(2/11) pR0.  Imunotipas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 20%.. Krūties audinį infiltruoja navikas iki 37 mm ir atskiro riebalinio audinio fragmente navikinis židinys (iki 15 mm limfmazgyje su ekstranodaliniu plitimu) suformuoti:   - solidinių kompleksų;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 4/10 DPRL.   Stebimas intravaskulinis plitimas smulkiose gyslose; operaciniai kraštai be pokyčių.  Karcinomos mikrometastazė papildomai 1-me/10 l/m.. nan
answer:  1a

 51%|█████▏    | 340/661 [09:30<08:38,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 8
answer:  1b

 52%|█████▏    | 341/661 [09:31<08:23,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 10 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.. Krūties audinį infiltruoja duktalinės struktūros, nedideli kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+
answer:  6%

 52%|█████▏    | 342/661 [09:33<08:12,  1.54s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 10 mm; III - 10 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja pabiros ląstelės ir smulkūs solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  1a

 52%|█████▏    | 343/661 [09:34<08:21,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - viršutinis kraštas  2 - apatinis kraštas  3 - sarginiai l/m 1-2-3 ekstra  4 - kvadrantas - planiniam tyrimui. 4. Krūties sektorius 5x4,5x3 cm su odos lopu 4,5x0,8 cm. Pjūvyje balkšvas, standus, aiškių ribų navikas 1,2x1,1x1 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,3 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(11 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 4 limfmazgiai su fokaline parakortekso hiperplazija, sinusų histiocitoze ir lipomatoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 11 mm), suformuotas fibrozuotoje stromoje ir fokaliai tarp lipocitų ekspansyviu frontu plintančių kribriforminių ir nereguliarių tubulinių bei trabekulinių struktūrų, klotų ląstelėmis vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 6/10 DPRL. Navikas 2 mm nuo žymėto rezekcijos krašto. Šalia negausūs dilatuoti kanaliukai su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais.. nan
answer:  0.

 52%|█████▏    | 344/661 [09:36<08:19,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  18 G automatine biopsine adata punktuotas 5x8 mm vos hipoechogeninis darinys, su minimalia vidine kraujotaka, kiek neaiškaus kontūro dešiniojoje krūtyje ties 2 val. vidurinėje dalyje giliai, BIRADS4b, paimti trys biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 16 mm; II - 9 mm; III - 11 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G2; 7 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija teigiama (3+);   Ki67: proliferacinis indeksas 60%.. Krūties audinį 3-se bioptatuose infiltruoja iki 9 mm :   - duktalinės pavienės struktūros netaisyklingi kribroziniai kompleksai ir trabekulės;  - epitelinių  stambių ląstelių su ryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 2/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  CD31: stipri teigiama (+++) membraninė reakcija kraujagyslių endotelyje be atipinių struktūrų spindyje  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: stipri (+++) cirkuliari reakcija, 100% naviko ląstelių membranoj
answer:  3.

 52%|█████▏    | 345/661 [09:37<08:08,  1.55s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 2 biopsiniai stulpeliai.. 2 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 12 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ %.. Krūties audinį infiltruoja juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstel
answer:  2]

 52%|█████▏    | 346/661 [09:39<07:59,  1.52s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 16 mm; II - 13 mm; III - 13 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 20%.. Krūties audinį infiltruoja nedideli solidiniai/kribroziniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0.

 52%|█████▏    | 347/661 [09:40<07:58,  1.52s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  4 biopsiniai stulpeliai histologiniam ištyrimui. 4 fragmentuoti biopsiniai stulpeliai: I - 6 mm; II - 3 mm; III - 2 mm; IV - 3 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja pabiros ląstelės ir juostos iš neryškiai polimorfiškų ląstelių, mitozių mažiau 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 8%.
answer:  0

 53%|█████▎    | 348/661 [09:43<08:57,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - deš. pažasties sarginiai l/m-extra  2 - k. pažasties sarginiai l/m- ekstra  3 - deš. krūtis  4 - k.krūtis 3-4 planniam tyrimui. 3. Krūtis 1055 gramų svorio, 24x18x5 cm. Krūties audinyje, apatinių kvadrantų riboje - balkšvas, standus, neaiškių ribų navikas 15x14x11 mm, nuo odos nutolęs 4,5 cm, nuo giliojo rezekcijos krašto - 0,3 cm. Šalia naviko fibrozės zona su dilatuotais latakais 4x3x1,5 cm, siekia odą, nuo giliojo rezekcijos krašto nutolęs 1,5 cm. Odoje rusvas smulkiai gruoblėtas darinys 0,8x0,6x0,1 cm, nuo artimiausio rezekcijos krašto nutolęs 3 cm.  4. Krūtis 1400 gramų svorio, 27x23x6,5 cm. Krūties audinyje, išorinių kvadrantų riboje - balkšvas, standus neaiškių ribų navikas 6x6x5 mm (sudėtas visas), nuo odos nutolęs 2 cm, nuo giliojo rezekcijos krašto - 3 cm. Krūties audinys fibrozuotas. Odoje rusva dėmė 1x0,7 cm, nuo odos rezekcijos krašto nutolusi 2 cm ir rusvas smulkiai gruoblėtas darinys 0,5x0,4x0,1 cm, nuo odos rezekcijos krašto nutolęs 0,8 cm.. 1(Extra). Reaktyvi limfadenopatija (3 l/m).  2(Extra). Reaktyvi limfadenopatija (3 l/m).  3. Krūties (dešiniosios) invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(15 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).  Odos seborėjinė keratozė.  4. Krūties (kairiosios) invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(6 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: įprastinė duktalinė hiperplazija, fibroadenomatozinė hiperplazija.   Odos seborėjinė keratozė.. 1(Extra). 3 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  2(Extra). 3 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  3.  SPENELIS: normali histologinė struktūra; dilatuoti latakai žemiau.   NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai 15 mm), suformuotas fibrozuotoje stromoje plintančių fokaliai besiliejančių tubulinių, kribriforminių ir negausių trabekulinių bei lizdinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais/apvaliais, kiek polimorfiškais, dalis skeltais ar su smulkia nukleole branduoliais. Mitozių iki 3/10 DPRL.  KRŪTIS: aplinkiniame krūties audinyje yra dilatuotų kanaliukų su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais (DCIS) bei kanaliukų, užpildytų monomorfiškomis ląstelėmis (LCIS); grupės kanaliukų, klotų stulpiniu epiteliu su apikalinės sekrecijos požymiais ar epitelio hiperplazija, yra kanaliukų su apokrinine metaplazija bei dilatuotų kanaliukų, klotų suplokštėjusiu epiteliu.  ODA: darinys su epidermio papiliarizacija ir neryškia akantoze ir hiperkeratoze, bazinių ląstelių hiperplazija ir hiperpigmentacija bei smulkiomis keratininėmis cistomis.  4. SPENELIS: normali histologinė struktūra; dilatuoti latakai bei keli kanaliukai su epitelio hiperplazija žemiau.  NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai -- mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių struktūrų, grandinėlių ir smulkių grupių ląstelių negausia švelniai eozinofiliška citoplazma, smulkiais ir vidutinio kalibro, ovaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 4/10 DPRL.  Šalia yra kanaliukų, užpildytų analogiškomis navikui ląstelėmis ir fibroadenomatozinė hiperplazija.  ODA: darinys su epidermio papiliarizacija ir neryškia akantoze ir hiperkeratoze, bazinių ląstelių hiperplazija ir hiperpigmentacija bei smulkiomis keratininėmis cistomis.. nan
answer:  1a

 53%|█████▎    | 349/661 [09:44<08:32,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 17 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja smulkūs solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 8%.  Navikas
answer:  1a

 53%|█████▎    | 350/661 [09:46<08:21,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 5 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6,5 mm);  (G1; 5 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 5%.. Krūties audinį 3-se bioptatuose infiltruoja iki 6,5 mm :   - duktalinės struktūros (<10% viso naviko), juostos ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje vakuolizuotoje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija
answer:  1a

 53%|█████▎    | 351/661 [09:47<08:29,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)- kraštas - skubus tyrimas - be naviko   2(N2b)- kraštas - skubus tyrimas - be naviko  3(N3)- kairės pažasties sarginis limfmazgis - skubus tyrimas - 2 l/m be naviko  4(N1)- pašalintas kairės krūties darinys - planinis tyrimas. 4. Krūties sektorius 12,5x5x5,5 cm, su odos lopu 11x2 cm, žymėtas viela. Vielos projekcijoje krūties audinys fibrozuotas 5,5x4,5 cm plote. Fibrozėje pilkšvas, neaiškių ribų, standus navikas 12x10x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,3 cm.. 1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (2 l/m).  4(1). Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1b(navikas - 6mm) pN0(sn)(0/2 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-43692 tyrime:  "Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 70% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 6%."  Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis, kribriforminis tipai; -komedo tipo nekrozės).. 1(2a). Riebalinis audinys su fibrozės zonomis, pavieniais latakėliais, klotais dvisluoksniu epiteliu.  2(2b). Riebalinis audinys su fibrozės zonomis, pavieniais latakėliais, klotais dvisluoksniu epiteliu.  3. Du (2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4(1). Krūties fibroziniame audinyje - navikas (mikro - 6mm), formuojamas solidinių/lizdinių, kribriforminių, netaisyklingų duktalinių (~5%) struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 7 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais, kribriforminiais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais; -komedo tipo nekrozėmis (DCIS).. nan
answer:  0,

 53%|█████▎    | 352/661 [09:49<08:22,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1. Pašalintas deš.krūties sektorius.   N2. Sektoriaus kraštai.. 1. Krūties sektorius 12x9,5x4 cm su oda 9x6,5 cm. Krūties audinyje, pilkšvas standus, neaiškių ribų navikas 32x27x25 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 1 cm.  2. 2 riebalinio audinio fragmentai: I - 4,5x3,5x0,5 cm, II - 4x2x0,6 cm.. 1. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(32 mm navikas) pNX(limfmazgiai nešalinti) LVI-3(intraveninė invazija). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35-40%.    2. Riebalinis-fibrozinis audinys.  3. Krūties audinys.. 1. Krūtyje - navikas ekspansyviu augimo frontu, suformuotas trabekulinėmis struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais branduoliais ryškiomis nukleolėmis; mitozių 72/10 DPRL. Intraveninė invazija.  2. Riebalinis-fibrozinis audinys.  3.  Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.. Navikas:  HER2: nusidažiusių naviko ląstelių nėra.
answer:  1.

 53%|█████▎    | 353/661 [09:51<08:32,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a - skubus tyrimas - be naviko  2 ėminio aprašas: N2b kraštai - skubus tyrimas - be naviko  3 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas - 7 l/m be naviko  4 ėminio aprašas: N1: pašalintas dešinės krūties. 4. Krūties sektorius 7x4,5x3,5 cm, be odos, pjūvyje pilkšvas, standus, 15x15x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm. Aplink naviką krūties audinys fibrozuotas 3x1 cm plote.. 1(ekstra). Kraštai. Krūties fibrocistiniai pokyčiai.  2(ekstra). Kraštai. Krūties fibrocistiniai pokyčiai.  3(ekstra). Reaktyvi limfadenopatija (7 l/m).  4. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham sistemą) duktalinė karcinoma. Suminis TNM: pT1c(15 mm), pN0 (0/7 l/m), R0(radikali rezekcija), LVI-0 (limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN23 solidinis ir kribriforminis tipas). Krūties fibrocistiniai pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).  Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35-40%.. 1(ekstra). Krūties audinio fibrozė, latakai dilatuoti, kloti dvisluoksniu epiteliu.  2(ekstra). Krūties audinio fibrozė, latakai dilatuoti, kloti dvisluoksniu epiteliu.  3(ekstra). Septyni limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais.  4. Krytyje navikas, sudarytas iš desmoplastiškoje stromoje besidėstančių trabekulių, lizdų ir solidinių struktūrų iš ląstelių vidutinio gausumo šviesiai eozinofiliška citoplazma, vidutinio kalibro, ryškiai polimorfiškais, ovaliais apvaliais, branduoliais ryškiomis nukleolėmis. Limfovaskulinė invazija neidentifikuota. Mitozės iki  22/10 DPRL. Greta dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš ląstelių eozinofiliška citoplazma, polimorfiškais nereguliaraus kontūro branduoliais. Aplinkiniame krūties audinyje fibrozė su dilatuotais latakais  klotais dvisluoksniu epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). nan
answer:  3b

 54%|█████▎    | 354/661 [09:53<08:48,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a kraštai - extra; - be naviko   2. N2b kraštai - extra; - be naviko   3. Kairės pažasties sarginis limfmazgis - extra. 3 l/m be naviko  4(N1). pašalintas kairės krūties kvadrantas - planinis tyrimas. 4(1). Krūties sektorius 13x6x5 cm, su odos lopu 13x4 cm. Pjūvyje balkšvas, standus neaiškių ribų navikas 19x18x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 3 cm. Šalia naviko paryškėjusi riebalinio audinio zona 2x1,2x1 cm (bendras dydis su naviku 2,6 cm). (zona sudėta visa). 1(2a)(Extra). Krūties audinys.  2(2b)(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  3(Extra). Reaktyvi limfadenopatija (3 l/m).  4(1). Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(19 mm) N(sn)0(0/3 l/m), LVI-2(limfovaskulinė invazija).  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.. 1(2a)(Extra). Krūties audinyje, fibrozuotoje stromoje - negausūs smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2(2b)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu, fokaliai hiperplastišku epiteliu.  3(Extra). 3 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze.  4(1). Krūties audinyje - ribotas navikas, suformuotas fibrozuotoje stromoje plintančių lizdinių, trabekulinių ir negausių kribriforminių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 12/10 DPRL. Limfovaskulinė invazija smulkiose šakose. Naviko centre fibrozės ir elastozės zonos, negausūs kalcifikatai. Šalia naviko dilatuoti kanaliukai su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais, fokaliai su komedo nekrozėmis; negausūs kanaliukai su epitelio hiperplazija.. 1. Navikas (16 blokas): CD34+ endotelizuotose ertmėse naviko plitimas.   Navikas (18 blokas): CD31+ endotelizuotose ertmėse naviko plitimo neidentifikuota.  Navikas (19 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląste
answer:  1+.

 54%|█████▎    | 355/661 [09:54<08:33,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 12 mm.. Papildyta HER2 FISH.  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė su apokrinine diferenciacija karcinoma.     Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Androgenų receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+).  Ki67 proliferacinis aktyvumas 3%.  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).. Fragmentuotuose bioptatuose (2/2) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis trabekulėmis besidėstančių ląstelių vidutinio gausumo eozinofiliška - amfofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio kalibro branduoliais; mitozių 1/10 DPRL.. Navikas:  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Androgenų receptoriai: (+++)(brand. r-ja) 100%.  HER2: vidutinis dalies membranos nusidažymas 60% naviko ląstelių.  Ki67 proliferacinis aktyvumas 3%.  E-cad
answer:  0.

 54%|█████▍    | 356/661 [09:56<08:20,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 bioptatai 22 mm 14G adata iš deformacijos židinio centro ir kraštų.. 3 biopsiniai stulpeliai: I - 7 mm; II - 9 mm; III - 14 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 7 mm);  (G1; 4 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 8%.. Krūties audinį 3-se bioptatuose infiltruoja iki 7 mm :   - duktalinės struktūros (15% viso naviko), netaisyklingi kribroziniai kompleksai ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 8% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko
answer:  1a

 54%|█████▍    | 357/661 [09:57<08:08,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Pašalinta dešinė krūtis su išgriuvusiu naviku ir l/n konglomeratais iš I lygio.. Krūtis 366 g svorio, 18,5x8,5x3,5 cm, su raumens fragmentu 8x5x1,6, spenelis pilkšvas standus. Krūties krašte, raumens projekcijoje, pilkšvas standus, neaiškių ribų navikas 65x50x27 mm, nuo giliojo rezekcijos pjūvio nutolęs 0,2 cm, peraugą odą. Naviko projekcijoje oda išopėjusi 2,5x1,6 cm plote. Atskirai tame pačiame inde riebalinio audinio fragmentas 9x7,5x2,3 cm. Rasti 7 limfmazgiai, didžiausias 27 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b (65mm, išopėjimas); pN2a (4 iš 7 l/m).. Krūties audinyje 65mm išopėjęs navikas: solidiniai/kribroziniai kompleksai vidutinio polimorfizmo ląstelių, mitozių iki 10/10 DPRL.   Navikas infiltruoja skersaruožius raumenis.  Iš rastų 7 limfmazgių 4 su metastazėmis iki 27mm.  Naviko židiniai giliajame rezekcijos krašte.. nan
answer:  3b

 54%|█████▍    | 358/661 [09:59<07:56,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 8 mm; II - 7 mm; III - 8 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozės pavienės.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 4%
answer:  1a

 54%|█████▍    | 359/661 [10:00<08:04,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Kairė krūtis su pažasties l/m, planinis. Krūtis1 g svorio, 19,5x15x4,5 cm, su pažasties narveliena 11x6x2 cm. Krūties audinyje, lateralinių kvadrantų riboje - balkšvas, standus navikas 8x6x6 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,5 cm, nuo odos 5 cm. Pažasties narvelienoje, balkšvas standus židinys 20x15x17 mm, nuo rezekcijos krašto nutolęs 0,1 cm. Rasta 13 limfmazgių, didžiausias 18 mm.. Krūties audinyje du navikai:  1. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b(8mm);  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacijos FISH tyrimo rezultatas teigiamas.  Ki67+ 12%, vietomis iki 20%  2. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties lobulinė karcinoma; pT1c(20mm).  Naviko imunoprofilis biopsinėje medžiagoje B23-18396:  ER(++) 100%; PR(+) 20%; HER2(-); Ki67 mažiau 5%.  pN0 (0 iš 13 l/m).. Krūties audinyje 8mm navikas iš duktalinių ir kribrozinių/solidinių kompleksų vidutiniškai polimorfiškų ląstelių, mitozių iki 15/10 DPRL;  ----------  Krūties audinyje ir pažasties audiniuose 20mm navikas iš juostų ir smulkių solidinių kompleksų nedidelių apvalių vidutiniškai polimorfiškų ląstelių; mitozių mažiau 1/10 DPRL.  Lobulinės karcinomos židiniai pažasties audinių rezekcijos krašte.  Rasta 13 l/m su reaktyviais pokyčiais, be naviko židinių.. Duktalinė karcinoma:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 10% naviko ląste
answer:  2.

 54%|█████▍    | 360/661 [10:02<07:50,  1.56s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 8 mm; II - 9 mm.. Gerai diferencijuota (G1, balai 4 pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.. Krūties audinį infiltruoja duktalinės struktūros ir negausūs kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 30% naviko ląsteli
answer:  1b

 55%|█████▍    | 361/661 [10:04<08:04,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.   5. papildomas kraštas, planinis.. 4. Krūties sektorius 10x9x6,5 cm su odos lopu 10x2,9 cm. Pjūvyje balkšvas, neaiškių ribų navikas 22x15x13 mm, nuo odos nutolęs 1,5 cm, nuo artimiausio rezekcijos krašto 0,1 cm. Rezekcijos kraštas markiruotas juodai, tarp naviko pjūvių - žaliai.   5. Riebalinio aufdinio fragmentas 4x1,5x1 cm. v/m. 1. Pjūvio kraštai: krūties audinys be patologinių pokyčių.     2. Pjūvio kraštai: Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS, komedo tipo) krūties audinyje.     3. Sarginiai l/m: limfmazgiai (2) be patologinių pokyčių; pN(sn)0(0/2).    4. Dešinios krūties sektorius.  Krūties invazyvi lobulinė karcinoma (G2, 6b. pagal Nottingham);  pT2(22 mm) pLVI-0 pR0.   Imunofenotipas (nustatytas priešoperaciname naviko biopsijos tyrime):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+). HER2 geno amplifikacija NENUSTATYTA.  Ki67 proliferacinis aktyvumas 3%.    5. Papildomas kraštas. Krūties fibrocistiniai pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).. 1. Pjūvio kraštai: krūties audinys be patologinių pokyčių.   2. Pjūvio kraštai: duktalinių ląstelių  su vidutine branduolių atipija proliferacija išplėstų kanalėlių spindžiuose aplink nekrotinį detritą.   3. Sarginiai l/m: limfmazgiai (2) be patologinių pokyčių.  4. Dešinios krūties sektorius. Krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, trabekulėmis, grandinėlėmis ir pabirai besidėstančių ląstelių negausia eozinofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio-smulkaus kalibro, ovalaus kontūro branduoliais; mitozių 1/10 DPRL. Intravaskulinio plitim nestebima. Navikas 2 mm nuo rezekcijos krašto.  5. Papildomas kraštas. Fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).. nan
answer:  1a

 55%|█████▍    | 362/661 [10:05<08:08,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra (be naviko);  2(2b). Kraštai - extra (be naviko);   3. Limfmazgiai - extra (2 l/m be naviko);   4(1). Pašalintas kairės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 7,5x4,5x3,5 cm su oda 6,5x2 cm. Krūties audinyje, kvadrante - pilkšvas, standus, gan aiškių ribų navikas  17x15x15 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 0,3 cm.. 1(2a). Kraštai - riebalinis audinys be patologinių pokyčių.  2(2b). Kraštai - riebalinis audinys be patologinių pokyčių.   3. Limfmazgiai - limfmazgiai (2) be patologinių pokyčių.    4(1). Kairės krūties kvadrantas.   Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT1c pLVI-0 pN0 pR0.  Imunotipas priešoperaciniame biopsijso tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.. 1(2a). Kraštai - riebalinis audinys be patologinių pokyčių.  2(2b). Kraštai - riebalinis audinys be patologinių pokyčių.   3. Limfmazgiai - limfmazgiai (2) be patologinių pokyčių.  4(1). Kairės krūties kvadrantas. Krūties audinį infiltruoja naviko negausios duktalinės struktūros (iki 15 proc.), nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 5/10 DPRL. Plitimo kraujagyslėse ar operaciniuose kraštuose nestebima.. nan
answer:  1(

 55%|█████▍    | 363/661 [10:07<08:03,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but.  3 biopsiniai stulpeliai iš ~ 10 mm  neaiškių ribų  dešinės krūties darinio   2 but. 2 biopsiniai stulpeliai iš  ~ 30 mm dydžio kairės krūties darinio. 1. 3 biopsiniai stulpeliai: I - 21 mm; II - 14 mm; III - 10 mm.  2. 2 fragmentuoti biopsiniai stulpeliai: I - 11 mm; II - 13 mm.. Po operacinės medžiagos tyrimo patikslintas N1 naviko tipas  Dešinė  N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.  ------------  Kairė  N2: Mucininė krūties karcinoma (G2, 6 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Dešinė  N1: Krūties audinį infiltruoja smulkios duktalinės struktūros ir solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  ------------  Kairė  N2: Krūties audinyje mucininėje stromoje solidiniai/kribroziniai kompleksai vidutinio polimorfizmo ląstelių, mitozių iki 3/10 DPRL.. nan
answer:  1a

 55%|█████▌    | 364/661 [10:08<07:48,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 7 mm; II - 12 mm; III - 9 mm.. Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.. Krūties audinyje mucinų sankaupose netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 4%.
answer:  1a

 55%|█████▌    | 365/661 [10:10<07:46,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Pašalinta kairė krūtis ir pažasties narveliena.. Krūtis 21x16x5 cm, su pažasties narveliena 7,5x6,6x2 cm. Krūties audinyje, viršutinių kvadrantų riboje pilkšvas, standus, gan aiškių ribų navikas 23x20x20 mm, nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo odos - 0,6 cm. Nuo naviko, 0,4 cm atstumu pilkšvas, neaiškių ribų, standus židinys 4x4x2 mm. Krūties audinyje, lateralinių kvadrantų riboje rusvas, elastingas darinys/limfmazgis? 1x0,6x0,3 cm. Krūties audinyje rasta 12 limfmazgių, didžiausias 1,6 cm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma: pT2(23mm); pN1(mi) (metastazės intramamariniame limfmazgyje iki 1,5mm; pažasties limfmazgiai (12 l/m) be metastazių).  Intraduktalinės krūties papilomos, radialiniai randai (7 dariniai).. Krūties audinyje 23mm navikas: duktalinės struktūros ir kribroziniai/solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.  Aplinkiniame krūties audinyje gausūs iki 4mm dariniai: šakotos papilinės intraduktalinės strukūros, radialiai plintantys kampuoti kanaliukai.  Intramamariniame limfmazgyje 2 metastazės iki 1,5mm; pažasties limfmazgiai (12 l/m) be metastazių.. nan
answer:  1b

 55%|█████▌    | 366/661 [10:12<08:11,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1): pašalintas kairės krūties kvadrantas  - planinis tyrimas  2(N2a) kraštai  - planinis tyrimas  3(N2b) kraštai  - planinis tyrimas   4(N3): kairės pažasties sarginis limfmazgis - planinis tyrimas  5(N4): papildomas kraštas - planinis tyrimas. 1. Krūties sektorius 8x6x3 cm, su odos lopu 7x3 cm. Pjūvyje balkšvas, standus, neaiškių ribų navikas 32x27x21 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 0,1 cm.   2. Riebalinio audinio fragmentas 2,8x2x0,5 cm.   3. Riebalinio audinio fragmentas 2x1,3x0,5 cm.  4. Riebalinio audinio fragmentai, bendras dydis 6x3,5x1,5 cm. Rasti 4 limfmazgiai, didžiausias 1,4 cm.  5. Riebalinio audinio fragmentas 2x1,2x1,4 cm. v/m. 1(N1). Kairės krūties kvadrantas.   Krūties invazyvi vidutiniškai diferencijuota (G2, 7 b. pagal Nottingham sist.) duktalinė karcinoma,   suminis TNM: pT2 (32 mm navikas)   pN0(sn)(0/4 l/m)    pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pP1(perineurinis naviko plitimas)   pR0(radikalus pašalinimas).  Naviko imunotipas operacinėje medžiagoje: HER2: reakcija neigiama (1+).  Naviko imunotipas biopsijoje (B23-13989):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 25% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.    2(N2a). Kraštai. Krūties audinys be patologinių pokyčių.   3(N2b). Kraštai. Krūties audinys be patologinių pokyčių.     4(N3). Kairės pažasties sarginis limfmazgis. Reaktyvi limfadenopatija (4 l/m).     5(N4). Papildomas kraštas. Riebalinis fibrozinis audinys be naviko plitimo.. 1(N1). Kairės krūties kvadrantas. Krūties audinyje - navikas, suformuotas lizdų, smulkių solidinių kompleksų, grandinėlių, pavienių tubulių. Naviko ląstelės su vidutinio gausumo, eozinofiliška citoplazma, vidutinio kalibro, apvaliais, vidutiniškai polimorfiškais branduoliais su aiškiomis nukleolėmis. Mitozių navike iki 14/10DPRL. Naviko stroma desmoplastiška, su kolagenizuotomis zonomis ir negausia limfocitų infiltracija periferijoje. Naviko plitimas endotelizuotuose spindžiuose ir perineuriškai.  2(N2a). Kraštai. Riebalinis audinys su fibrozės septomis ir pavieniais smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(N2b). Kraštai. Riebalinis audinys su fibrozės septomis ir pavieniais smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  4(N3). Kairės pažasties sarginis limfmazgis. Limfmazgiai su lipomatoze, sinusų  histiocitoze, makrofagų ir dendritinių ląstelių infiltracija parakortekse.   5(N4). Papildomas kraštas. Vaskuliaruzotas riebalinis fibrozinis audinys su smulkiomis hemoragijomis.. Blokas 4:  CD31: naviko limfovaskulinės invazijos nėra.   Blokas 5:  E-Cadherin: stipri (+++) reakcija 100% naviko ląstelių membranoje.   EMA: vidutinė (++) reakcija 30% naviko ląstelių citoplazmoje.  HER2: stipri (+++) cirkuliari reakcija, iki 1% naviko
answer:  1+

 56%|█████▌    | 367/661 [10:14<08:33,  1.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2): kairės pažasties sarginis limfmazgis - sarginis limfmazgis - 3 l/m be naviko  2(N1): pašalinta kairė krūtis planinis tyrimas. 2(1). Krūtis 1065 gramų svorio, 23x19x7 cm. Krūties audinyje, užspenelinėje srityje - balkšvas, lobulizuotas, elastingas navikas 30x26x16 mm, nuo giliojo rezekcijos krašto - 6 cm, siekia spenelį ir jį įtraukia. Krūties periferijoje vienas limfmazgis, 9 mm skersmens.. 1(2, ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos (mikro)metastazė viename limfmazgyje (mts 1/3 l/m; iki 1,3 mm skersmens).    2(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) mucininė karcinoma, žr. pastabą,   SUMINIS TNM:   pT2 (navikas 30 mm) N1a (mts 2/4 l/m; iki 8,5 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+); mikrometastazėje - reakcijos nėra (0).     Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).  Krūties rezekcijos kraštas be naviko.. 1(2, ekstra). "Sarginiai limfmazgiai": viename (1) limfmazgyje iš trijų (3), planinio tyrimo pjūvyje, naviko (mikro)metastazė - 1,3 mm skersmens, be ekstanodalinio plitimo. Šalia, riebaliniame audinyje - limfovaskulinė invazija smulkiose šakose. Naviką sudaro solidiniai lizdai iš atipinių ląstelių vidutinio gausumo tamsoka citoplazma, ovaliais vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis; metastazėje mucinų produkcijos nėra.   2(1). SPENELIS: dermoje plinta žemiau aprašytas navikas, epidermis hiperkeratotiškas su akatotine hiperplazija, dermoje - gausesnė limfocitinė infiltracija.   NAVIKAS: krūties audinyje, fibrozuotoje stromoje, gausiuose ekstraląsteliniuose mucinuose negausios trabekulinės, kribriforminės ir mikropapilinės naviko struktūros, suformuotos ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio-smulkaus kalibro, ovalaus kontūro branduoliais; mitozių 5/10 DPRL. Židininė MMN infiltracija.   APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).  GILUSIS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.   LIMFMAZGIS(1): viename limfmazgyje - naviko metastazė, 8,5 mm skersmens, be ekstranodalinio plitimo, suformuota dominuojančių nedidelių solidinių ir lizdinių struktūrų bei negausių smulkių duktulių iš analogiškos išvaizdos navikinio epitelio, be mucinų produkcijos.. 1(2, ekstra). "Sarginiai limfmazgiai":   Mikrometastazė (blokas 5):  EMA(+) pavienės ląstelės;  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.   Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių brand
answer:  1.

 56%|█████▌    | 368/661 [10:16<08:35,  1.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sektoriaus kraštai - extra;   2. Sektoriaus kraštai - extra;   3. Limfmazgiai - extra.   4. Deš.krūties sektorius su naviku - planinis tyrimas.. 4. Krūties sektorius 8,5x5x1,5 cm su oda 5x1,3 cm. Krūties audinyje, kvadrante - pilkšvas, standus, neaiškių ribų navikas 13x10x7 mm (sudėtas visas) pereinantis į fibrozę (dažyta mėlynu tušu), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 0,9 cm.. Papildyta HER2 FISH.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties fibroadenoma (0,5 cm).  3(ekstra). Krūties duktalinės karcinomos metastazė limfmazgyje su ekstranodaliniu plitimu(1/3 l/m 4 mm).   4. Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(14 mm navikas) pN1a(sn)(1/3 l/m MTS 4 mm su ekstranodaliniu plitimu) LVI-2(limfovaskulinė invazija). Perineurinis plitimas. R0(radikali rezekcija).  Vidutinio - žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1-DIN2, kribriforminis tipas). Lobulinė karcinoma in situ (LCIS).    Imunofenotipas:   Her2 reakcija: ribinė (2+).  HER2 geno amplifikacija nenustatyta.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su mazgu suformuotu edemiškos fibroblastų stromos ir suspaustų latakų, klotų epiteliu neryškiu mioepiteliniu sluoksniu.     3(ekstra). 1 iš 3 limfmazgių aprašyto naviko metastazė 4 mm su ekstranodaliniu plitimu.    4. Krūtyje - navikas (14 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, tubulinėmis, struktūromis besidėstančių ląstelių  negausia eozinofiliška citoplazma, smulkiais - vidutiniais, nežymiai polimorfiškais, ovaliais branduoliais ryškiomis nukleolėmis; mitozių 1/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių. Dilatuoti latakai su intraduktaliniais solidiniais proliferatais iš ląstelių monomorfiškais branduoliais.  Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaus kanaliukų zonos.. 2. Mazgas, mioepitelis: SMA(+++)citopl. r-ja 100%; CK5(+) citopl. r-ja 5%; CK14(+) citopl. r-ja 15%; p63(+/++) brand. r-ja 30%.  3. Navikas (28 blokas): HER2: vidutinė cirkuliari membr r-ja 15%.
answer:  1(

 56%|█████▌    | 369/661 [10:17<08:18,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra - be naviko   2(2b). Kraštai - extra - be naviko   3. L/m.-ekstra - extra - be naviko   4. pap. l/m - extra  5(1). sektorius - planinis tyrimas  N1- skubus rentgeninis tyrimas- navikas - nevizualizuojamas.. 5. Krūties sektorius 5,5x3x3 cm, su odos lopu 5x2,3 cm. Krūties audinyje, pjūvyje pilkšvas, standus, aiškių ribų navikas 9x7x7 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 1,2 cm.. N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma; pT1b (9mm).  N2ab: Audiniai be naviko.  N3: Riebalinis audinys, l/m nerasta.  N4: Limfmazgiai (2 l/m) be naviko; pN0(sn).. N1: Krūties audinyje 9mm navikas: smulkūs solidiniai kompleksai, pabiros ląstelės ir juostos iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozės pavienės.  N2ab: Audiniai be naviko.  N3: Riebalinis audinys, l/m nerasta.  N4: Limfmazgiai (2 l/m) be naviko.. nan
answer:  1a

 56%|█████▌    | 370/661 [10:19<07:57,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 12  mm ilgio.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 25%.. Krūties audinį infiltruoja juostos ir trabekulės iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: silpnas ar vidutinis dalies membranos nusidažymas 30% naviko ląstel
answer:  1b

 56%|█████▌    | 371/661 [10:20<08:05,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra;  2(2b). Kraštai - extra.   3(1). Pašalintas dešinės krūties kvadrantas - planinis tyrimas.   4(3). Dešinės pažasties sarginiai limfmazgiai - planinis tyrimas.. 3(1). Krūties sektorius 10,5x5x5 cm su odos lopu 10x4 cm. Pjūvyje, balkšvas, standus, neaiškių ribų navikas 13x11x9 mm, nuo artimiausio rezekcijos krašto nutolęs 1,5 cm, nuo odos – 1,8 cm. Šalia naviko fibrozės zona 3,5x3x2,2 cm.  4(3). Riebalinio audinio fragmentai, bendras dydis 7x5x1,5 cm. Rasta 11 limfmazgių iki 1,3 cm.. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Riebalinis-fibrozinis audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c pN2a(5/11 l/m iki 7 mm su ekstranodaliniu plitimu) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).  4. Pažasties limfmazgiai: duktalinės karcinomos metastazės limfmazgiuose (5/11 l/m iki 7 mm su ekstranodaliniu plitimu).   Imunofenotipas(biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Riebalinis-fibrozinis audinys.  3. Krūtyje - navikas infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais, branduoliais ryškiomis nukleolėmis;   mitozių 13/10 DPRL.  4. 5 iš 11 limfmazgių aprašyto naviko metastazės iki 7m ekstranodaliniu plitimu.. 3. Navikas(7 blokas): E-cadherin(++/+++) trūkinėjanti membr. r-ja 80%; p120(++/+++) trūkinėjanti membr. r-ja 80%;  4. Metastazė(16 blokas): HER2 silpnas dalies membranos dažymasis 5%
answer:  3b

 56%|█████▋    | 372/661 [10:22<07:46,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 40%.. Krūties audinį infiltruoja nedideli solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 7/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 50% naviko ląstelių.  Ki67+ 40
answer:  3b

 56%|█████▋    | 373/661 [10:24<08:06,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas - skubu;  2(1b). Apatinis kraštas - skubu;  3(2). Sarginiai limfmazgiai - skubu;  4(3). Kairės krūties kvadrantas - planinis.. 4. Krūties sektorius 9x4x7 cm su odos lopu 7,5x2,5 cm, žymėtas viela. Vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 19x12x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 2,5 cm.. 1(1a, ekstra). "Viršutinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   2(1b, ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos metastazė limfmazgyje (mts 1/3 l/m; iki 6 mm skersmens; be ekstranodalinio plitimo).  4(3). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1c (navikas 18 mm) N1a(sn) (mts 1/3 l/m; iki 6 mm skersmens), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, papilinis, komedo tipai).   Krūties sektoriaus rezekcijos kraštas normalios histologinės struktūros.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys su cistiškai dilatuotais kanaliukais, klotais dvisluoksniu ar kiek hiperplastišku epiteliu; be naviko.   2(1b, ekstra). "Apatinis kraštas": fibrozuotas krūties audinys su cistiškai dilatuotais kanaliukais, klotais dvisluoksniu ar kiek hiperplastišku epiteliu; be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": viename (1) limfmazgyje iš trijų (3) žemiau, punkte Nr.4, aprašyto naviko metastazės, iki 6 mm skersmens, be ekstanodalinio plitimo.   4(3). NAVIKAS (mikroskopiškai - 18 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retos duktalinės, netaisyklingos besiliejančios liaukinės, kribriforminės, trabekulinės, lizdinės, solidinės naviko ir retos papilinės struktūros, suformuotos vidutiniškai ar ryškiai polimorfiškų ląstelių, vidutinio gausumo ar gausesne šviesiai eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis ar ryškiomis nukleolėmis; mitozių iki 10/10 DPRL.   Fokaliai gausi perinavikinė limfocitinė infiltracija su tretinių limfoidinių struktūrų formacija.   APLINKA: šalia naviko - solidiniai, kribriforminiai, papiliniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 4(3). NAVIKAS (blokas 17):   EMA(+)(citopl.r-ja)80%.   HER2: silpna (+) necirkuliari reakcija, 60%  naviko ląstelių membranoje.
answer:  3(

 57%|█████▋    | 374/661 [10:26<08:25,  1.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštai - extra - be naviko   2(N2b). kraštai - extra - be naviko   3(N3). sarg. l/m - extra - be naviko   4(N1)- pašalintas sektorius- planinis patologinis tyrimas   N1- skubus rentgninis tyrimas - sektorius su MK ir 2 žymekliais. 4. Krūties sektorius 15x7,5x5,5 cm su oda 14x5 cm, žymėtas 2 vielomis, atstumas tarp vielų 10 cm. Krūties audinyje:  - I vielos projekcijoje pilkšvas, standus I navikas 10x8x7 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 2,2 cm;  - 4 cm atstumu pilkšvas, ribotas, standus II navikas 6x6x4 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 2,5 cm;. 1(2a). Žymėtas kraštas: fibrocistiniai pokyčiai. Dėl nežymėtos fragmento dalies ŽR.PASTABĄ.  2(2b). Žymėtas kraštas: fibrocistiniai pokyčiai. Dėl nežymėtos fragmento dalies ŽR.PASTABĄ.  3. Krūties duktalinės karcinomos mikrometastazė viename limfmazgyje (1/3 l/m, 1,3 mm).   4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mišri duktalinė (50%) ir mikropapilinė karcinoma (50%), TNM: pT1b(m)(2 židiniai: 8,5 mm ir 5,7 mm), pN1mi(sn)(1/3 l/m), LVI2(identifikuota). HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS), kribriforminis ir mikropapalinis variantai.. 1(2a). Žymėtas kraštas: krūties audinys su nežymiai dilatuotais kanaliukais klotais dvisluoksniu epiteliu. PO FIKSACIJOS (nežymėta fragmento dalis): Krūties audinyje keli dilatuoti latakai, užpildyti kribriforminiais proliferatais iš ląstelių negausia eozinofiline citoplazma ląstelių su vidutiniškai polimorfiškais branduoliais. Aplinkiniame krūties audinyje gausūs dilatuoti kanaliukai kloti dvisluoksniu, fokaliai hiperplastišku epiteliu; židininė apokrininė epitelio metaplazija.  2(2b). Žymėtas kraštas: krūties audinys su nežymiai dilatuotais kanaliukais klotais dvisluoksniu epiteliu. PO FIKSACIJOS (nežymėta fragmento dalis): Krūties audinyje keli dilatuoti latakai, užpildyti kribriforminiais proliferatais iš ląstelių negausia eozinofiline citoplazma ląstelių su vidutiniškai polimorfiškais branduoliais. Aplinkiniame krūties audinyje gausūs dilatuoti kanaliukai kloti dvisluoksniu, fokaliai hiperplastišku epiteliu; židininė apokrininė epitelio metaplazija.  3. Viename iš trijų limfmazgių (1/3) žemiau aprašyto naviko mikrometastazė (1/3 l/m, 1,3 mm skersmens).  4(1). Krūties audinyje, hialinizuotoje stromoje 2 naviko židiniai(8,5 ir 5,7 mm mikroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių tubulinių , trabekulinių ir mikropapilinių (I židinyje iki 60%) naviko struktūrų. Naviko ląstelės vidutinio gausumo eozinofiline citoplazma su ryškiai polimorfiškais, hiperchromiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 9/10DPRL. Limfovaskulinis plitimas (LVI2). Greta naviko gausūs dilatuoti kanaliukai užpildyti kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais; dalyje latakų mikropapilinė proliferacija.  Krūties audinyje - dilatuoti latakai su fibrovaskulinėmis struktūromis, klotomis dvisluoksniu epiteliu monomorfiškais branduoliais.. Blokas 34:  CK5: mioepitelis (+)  EMA: (+++)citop.-membran.r-ja 90%;  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 57%|█████▋    | 375/661 [10:28<08:41,  1.82s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.(2) Deš. pažasties sarginiai limfmazgiai, skubu  2.(3) Deš. krūties sektorius, planinis  3.(4) Papildomas viršutinis kraštas, planinis  4.(5) Papildomas apaptinis kraštas, planinis  5(1a). viršutinis kraštas - planinis (extra)  6(1b). apatinis kraštas - planinis (extra). 2(3). Krūties sektorius 11x9,5x5 cm, be odos, žymėtas viela. Vielos projekcijoje - pilkšvas, standus, neaiškių ribų navikas 13x10x6 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 1 cm.  3(4). Riebalinio audinio fragmentas 3x1,6x0,8 cm.   4(5). Riebalinio audinio fragmentas 2x1,2x0,6 cm.   5. Riebalinio audinio fragmentas 2,5x1,5x0,7 cm.   6. Riebalinio audinio fragmentas 2,6x1,2x0,4 cm.. 1(2, ekstra). "Deš. pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).  2(3). "Deš. krūties sektorius":   Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1c (navikas 13 mm) N0(sn) (0/3 l/m), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcijos nėra (0).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis tipas).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Krūties sektoriaus rezekcijos kraštas normalios histologinės struktūros.  3(4). "Papildomas viršutinis kraštas": krūties fibrocistiniai pokyčiai.  4(5). "Papildomas apaptinis kraštas": fibrozuotas riebalinis audinys; be naviko.  5(1a)."Viršutinis kraštas": fibrozuotas krūties audinys; be naviko.   6(1b). "Apatinis kraštas": fibrozuotas krūties audinys; be naviko.. 1(2, ekstra). "Deš. pažasties sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2(3). "Deš. krūties sektorius":   NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios nedidelės lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo tamsoka citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 5/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose.    Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Židiniai su ksantominiais makrofagais.   APLINKA: šalia naviko - solidiniai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.  3(4). "Papildomas viršutinis kraštas": fibrozuotas krūties audinys su dilatuotais ar suspaustais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   4(5). "Papildomas apaptinis kraštas": fibrozuotas brandžių lipocitų suformuotas audinys; be naviko.   5(1a)."Viršutinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   6(1b). "Apatinis kraštas": fibrozuotas krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.. 2(3). Navikas (blokas 15):  HER2: reakcijos naviko ląstelių membranoje nėra.  GATA3: (+++)(brand.r-ja)100%; Synaptophysin: (-).
answer:  0

 57%|█████▋    | 376/661 [10:29<08:13,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1- pašalinta krūtis. Krūtis, 564 g svorio, 19x15x4,5 cm. Krūties audinyje, pjūvyje šviesiai pilkas, standus, neaiškių ribų navikas 15x25x20 mm, pereinantis į fibrozės zoną.  Navikas nuo artimiausio rezekcijos pjūvio nutolęs 1,3 cm, nuo odos - 1,2 cm. Odoje, spenelio srityje balkšvi, standūs iškilę dariniai iki 0,9x0,7x0,3 cm.. Vidutinės diferenciacijos duktalinė krūties karcinoma: navikas krūtyje 25mm; naviko židiniai/satelitai odoje; intravaskulinis naviko plitimas.. Krūties audinyje 25mm navikas iš solidinių/kribrozinių kompleksų vidutiniškai ir ryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL; tokios pačios struktūros naviko židiniai/satelitai odoje iki 9mm; intravaskulinis naviko plitimas.  Rezkecijos kraštas be naviko.. nan
answer:  1a

 57%|█████▋    | 377/661 [10:31<07:56,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 13 mm; II - 12 mm.. Invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) karcinoma: galima/tikėtina krūties duktalinė ("bazinio" imunofenotipo) adenokarcinoma.     Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Her2 imuninė reakcija: neigiama (0).  Ki67: 30% (hot spot 40%).. Solidines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne blyškiai-saikingai eozinofiline citoplazma, vidutinio kalibro ar stambesniais apvalios formos netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 29 / 10 DPRL.. Navikas  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: nusidažiusių naviko ląstelių nėra.  Her2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  Prolife
answer:  30%

 57%|█████▋    | 378/661 [10:32<08:00,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - viršutinis kraštas, skubu  2 - apatinis kraštas, skubu  3 - sarginiai l/m, skubu  4 - kvadrantas - planiniam tyrimui. 4. Krūties sektorius 7x5,5x4 cm su oda 4x1 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje - balkšvas, standus, neaiškių ribų navikas 11x11x10 mm, nuo giliojo rezekcijos krašto nutolęs 1,1 cm, nuo odos - 1,7 cm.. 1(2a, ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su koaguliaciniais artefaktais; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (5 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 11 mm) N0(sn) (0/5 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2:reakcijos nėra (0).    Krūties fibroadenoma (~4 mm).. 1(2a, ekstra). "Kraštai": fibrozuotas brandžių lipocitų suformuotas fragmentas; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": penki (5) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje, gausiai limfocitais infiltruotoje stromoje, infiltratyviai plinta fokaliai besiliejančios kribriforminės, trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai ar ryškiau polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su fokaliai ryškiomis eozinofiliškomis nukleolėmis; mitozių iki 7/10 DPRL. Gausūs naviką infiltruojantys limfocitai.   APLINKA: šalia naviko ribotas, 4 mm skersmens, darinys, suformuotas edematoziškos/miksoidiškos stromos ir suspaustų kanaliukų, klotų dvisluoksniu epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 4. Navikas (blokas 22):  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 57%|█████▋    | 379/661 [10:34<07:40,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 90% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.. Bioptate - desmoplastiškoje stromoje, infiltratyvios naviko struktūros, suformuotos solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška tamsia ar ryškia citoplazma, polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais; ryškiomis nukleolėmis mitozių 4/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 90%.  HER2: nusidažiusių  aviko ląstelių nėra.  Ki67 proliferacinis aktyvumas 10%.  E-cadherin(+++) membr. r-ja 100%.  CK14 foninė citopl. r-ja.
answer:  1a

 57%|█████▋    | 380/661 [10:35<07:26,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 bioptatai 22 mm 14G adata iš 12 mm spikulinio židinio.. 2 biopsiniai stulpeliai: I - 11 mm; II - 10 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%, vietomis iki 10%.. Krūties audinį infiltruoja negausios duktalinės struktūros, smulkūs netaisyklingi kribroziniai ir solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  1.

 58%|█████▊    | 381/661 [10:37<07:44,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Pašalinta dešinė pažasties narveliena ir deš. krūtis.. Krūtis 809 g svorio, 20x16x5 cm, su fragmentuota pažasties narveliena, bendras dydis 13x10x4 cm. Spenelis įtrauktas. Krūties centrinė dalyje, balkšvi, standus židiniai, bendras dydis 3,2x2,5x3,2 cm:  - I navikas 24x20x32 mm, esantis 2 cm nuo artimiausio rezekcijos pjūvio, nuo odos 1,5 cm,   - galimai atskiras II navikas 6x6x6 mm, nuo pagrindinio (I) naviko nutolęs 0,5 cm, nuo artimiausio rezekcijos pjūvio nutolęs 3 cm.    - galimai atskiras III navikas 7x7x7 mm, nuo pagrindinio (I) naviko nutolęs 0,4 cm, nuo artimiausio rezekcijos pjūvio nutolęs 1 cm.  Pažasties narvelienoje rastas 21 limfmazgis su židiniais iki 1,8 cm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT(m)2(32 mm ir 7 mm naviko židiniai)   pN1a (2/21 l/m su mts iki 18mm)   pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pR0(radikalus pašalinimas).   Naviko imunotipas operacinėje medžiagoje (metastazės limfmazgyje): HER2:reakcijos nėra (0).  Naviko imunotipas iš biopsijos (B23-11819):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 kribriforminis, komedo tipai).  Intraduktalinė papiloma (1 mm).. Spenelis: be patologijos.  Rezekcijos kraštai: be naviko plitimo.    Krūties audinyje -  du atskiri naviko židiniai:  I navikas(makroskopiškai iš I ir II susiliejusių židinių) suformuotas tubulinių (~20%), lizdinių, kribriforminių, šakotų ir besiliejančių papilinių struktūrų. Naviko ląstelės su gausia, šviesiai eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais. Mitozių navike iki 9/10DPRL. Navikas plinta smulkiose gyslose. Naviko stroma desmoplastiška, su negausiais mikrokalcifikatais.   Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.  II (makroskopiškai- III) navikas: lizdinės, kribriforminės struktūros iš I navikui analogiškų ląstelių. Mitozių navike iki 8/10DPRL.  Aplinkiniame krūties audinyje kanaliukai su intraduktaliniais papiliniais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu.  Limfmazgiai: 2/21 limfmazgių - aukščiau aprašyto naviko metastazės iki 18 mm (makroskopiškai); stebimas ekstranodalinis plitimas.. Blokas 38:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  1a

 58%|█████▊    | 382/661 [10:39<07:28,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stulepliai. 3 biopsiniai stulpeliai: I - 10 mm; II - 10 mm; III - 5 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis 15%.. Krūties audinį infiltruoja nedideli solidiniai kompleksai, šakotos juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 10%, vi
answer:  1b

 58%|█████▊    | 383/661 [10:41<07:52,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. Kairės pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: 2. Kairė krūtis, planinis. 2. Krūtis gramų svorio, 22x18x6 cm. Krūties audinyje, spenelio projekcijoje, pilkšvas, neaiškių ribų, standus navikas 20x14x10 mm, nuo giliojo rezekcijos krašto nutolęs 2,5 cm, nuo odos - 1,2 cm. Aplink naviką krūties audinys fibrozuotas su cistinėmis ertmėmis 0,9 cm, nuo naviko 2 cm atstumu lateraliau, balkšvas, ribotas darinys 6x5x4 cm, nuo giliojo rezekcijos krašto nutolęs 0,5, nuo odos - 3 cm. Fibrozuotame audinyje, balkšvi standūs židiniai iki 1 cm. Rasti limfmazgiai iki cm.. 1. Duktalinės karcinomos metastazė limfmazgyje (1/2 l/m; iki 14,6mm).  2. Krūties invazyvi, blogai diferencijuota (G3; 9 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(m)(dauginiai naviko židiniai nuo 1,33mm iki 20mm) pN1a(1/2 l/m; iki 14,6mm); LVI-2(Limfo-Vaskulinė naviko Invazija (LVI) smulkiose kraujagyslėse/limfagyslėse); PN(perineurinis naviko plitimas).   IHC reakcijos atliktos VPC:B23-489 tyrime:  "Estrogenų receptoriai: vidutinė reakcija 90% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 5% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%."  Krūties vidutinio ir aukšto laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas; -komedo tipo nekrozė). Intraduktalinės krūties papilomos. Krūties fibrocistiniai pokyčiai, paprasta intraduktalinė hiperplazija.. 1. Viename(1) iš dviejų(2) limfmazgių žemiau aprašyto naviko metastazės (iki 14,6mm).  2. Krūties audinyje - dauginiai naviko židiniai (nuo 1,33mm iki 20mm), formuojami solidinių/lizdinių, trabekulinių, netaisyklingų duktalinių (<10%) struktūrų iš vidutinio kalibro ląstelių, vidutiniškai, vietomis ryškiai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 16 mitozių/10 DPRL; Limfo-Vaskulinės naviko Invazijos (LVI) smulkiose kraujagyslėse/limfagyslėse židiniai; perineurinis naviko plitimas (PN). Aplinkiniame krūtie audinyje - dilatuoti latakai su kribriforminiais, "arkiniais" atipinių ląstelių (su aukšto laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS). Krūties audinyje - dilatuoti latakai su fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu; fibrozės zonos su dilatuotais latakais, klotais dvisluoksniu epiteliu, apokrininės metaplazijos zonomis, paprastos intraduktalinės hiperplazijos židiniais. Spenelis be patologinių pokyčių. Rezekcijos kraštas be naviko plitimo.. Estrogenų receptoriai: vidutinė reakcija 90% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 5% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.
answer:  1.

 58%|█████▊    | 384/661 [10:42<07:40,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 bioptatai 12G 22 mm adata iš darinio su mkk. 3 biopsiniai stulpeliai: I - 16 mm; II - 12 mm; III - 14 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 35%.. Krūties audinį infiltruoja negausios duktalinės struktūros, smulkūs solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 12/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 80% naviko ląstelių.  Ki67+ 35%.
answer:  3b

 58%|█████▊    | 385/661 [10:44<07:39,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N3) kairės pažasties sarginis limfmazgis - skubus tyrimas - 3 l/m be naviko  4(N1) pašalintas kairės krūties kvadrantas su vielute - planinis tyrimas. 4. Krūties sektorius 6x6x3 cm, be odos. Pjūvyje pilkšvas, standus gan aiškių ribų navikas 10x6x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm. (navikas sudėtas visas). 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Riebalinis - fibrozinis audinys.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(9,5 mm navikas) pN0(sn)(0/3 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas). R0(radikali rezekcija).    Imunofenotipas(biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 10%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Riebalinis - fibrozinis audinys.  3(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (9,5 mm) infiltratyviu augimo frontu, suformuotas pavienėmis tubulinėmis ir lizdais besidėstančių ląstelių vidutinio gausumo ryškia eozinofiliška citoplazma, vidutiniais - stambiais, vidutiniškai polimorfiškais, nereguliaraus kontūro, ovaliais branduoliais ryškiomis nukleolėmis; mitozių 13/10 DPRL. Greta dilatuoti kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių.. nan
answer:  1a

 58%|█████▊    | 386/661 [10:45<07:23,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%, vietomis iki 80%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai ir trabekulės iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 20/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 60%, vietomis
answer:  3

 59%|█████▊    | 387/661 [10:47<08:03,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- kairės krūties sektorius, planinis  4(3)- virš.krašt, papildomai planas. 3(2). Krūties sektorius 6x5x3,5 cm, be odos, žymėtas siūlu. Siūlo projekcijoje fibrozės zona 4,5x2,5x1,7 cm. Fibrozėje pilkšvas, standus, aiškių ribų navikas 2,2x1,9x1,5 cm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm.  4(3). Riebalinio audinio fragmentas 2,2x1,5x0,5 cm.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys; be naviko.   2(1b, ekstra). "Apatinis kraštas": koaguliacijos zonoje, gilesniuose pjūviuose neišliekantis 1,9 mm židinys, kuriame histologiniai pokyčiai artimiausi žemo laipsnio duktalinės karcinomos in situ (DIN1/DCIS; kribriforminio tipo) ar inkapsuliuotos papilinės karcinomos (kuri traktuojama kaip in situ karcinoma) plitimui.     3(2). Krūties inkapsuliuota papilinė karcinoma (~22 mm) su invazyvia gerai diferencijuota (G1, 5 balai pagal Nottingham) duktaline karcinoma, pT1a(m) (keli nedideli invazijos židiniai iki 2 mm; žr. pastabą),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Invazyvaus naviko imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas iki 5%.    Krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: kribriforminis tipas).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė, apokrininė metaplazija).   Inkapsuliuotos papilinės karcinomos neinvazyvus komponentas nuo sektoriaus rezekcijos krašto nutolęs - 0,1 mm.   4(3). "Papildomas kraštas": fibrozuotas riebalinis audinys; be naviko.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(1b, ekstra). "Apatinis kraštas": ekstra tyrimo stikluose, fragmento koaguliacijos zonoje - nedidelis 1,9 mm židinys su dilatuotais latakais užpildytais intraduktaliniais kribriforminiais-papiliniais proliferatais; dėl ryškių koaguliacinių artefaktų citologinės ypatybės dalinai sunkiai įvertinimos. Planinio tyrimo pjūviuose zona neišlieka.   3(2). NAVIKAS: krūties audinyje stambus fokaliai gan aiškiai storos fibrozinės kapsulės ribojamas lobulizuotas naviko židinys (be CK14+ mioepitelinių ląstelių), suformuotas papilinių-kribriforminių ir solidinių plotų iš vidutiniškai ar fokaliai ryškiau polimorfiškų ląstelių su vidutinio gausumo eozinofiline citoplazma, varijuojančio dydžio ovaliais hiperchromiškais braduoliais; gausūs smulkūs kalcifikatai; židinys su hemosiderofagais, cholesterolio kristalais, fibroblastų proliferacija ir histiocitais, negausiais limfocitais. Židinio periferijoje keletas nedidelių darinio kapsulę kertančių ir aplinkinį riebalinį audinį infiltruojančių židinių (iki 2 mm), kuriuos formuoja retos besiliejančios duktalinės ir gausesnės kribriforminės naviko struktūros, suformuotos saikingai polimorfiškų ląstelių, negausia šviesia eozinofiline citoplazma, vidutinio dydžio ovaliais/apvaliais branduoliais; mitozių iki 6/10 DPRL. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Limfovaskulinė naviko invazija smulkiose šakose.    APLINKA: šalia naviko - keli nedideli kribriforminiai intraduktaliniai naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: inkapsuliuoto neinvazyvus naviko komponentas (be CK14+ mioepitelinio sl.) nutolęs 0,1 mm.  4(3). "Papildomas kraštas": brandžių lipocitų suformuotas fragmentas su smulkiomis kraujagyslėmis ir nerviniais kamienais; be naviko.. 3(2). Invazyvus navikas (blokas 23):  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 2% naviko
answer:  2%

 59%|█████▊    | 388/661 [10:49<07:55,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai  - skubus tyrimas  2(N2b) kraštai  - skubus tyrimas  3(N3): dešinės pažasties sarginis limfmazgis - skubus tyrimas  4(N1) pašalintas dešinės krūties kvadrantas su vielute, planiškai.. 4(N1). Krūies sektorius 9x3,5x8,5 cm, su odos lopu 9x3,5 cm; sektoriuje - chirurgine viela žymėtas pilkšvas standus aiškių ribų navikas 15x15x10 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 5 cm.. 1(N2a). Krūties fibrocistiniai pokyčiai.  2(N2b). Krūties fibrocistiniai pokyčiai. Paprastoji duktalinė hiperplazija.  3(N3). Reaktyvi limfadenopatija (4 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,5 cm) pN(sn)0 (0/4 l/m). LVI0(limfovaskulinės invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 15% (hot spot 20%).. 1(N2a). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2(N2b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; intraduktalinės hiperplazijos židiniai.  3(N3). Sinusų histiocitozė keturiuose (4) limfmazgiuose.  4(N1). Krūties audinyje - navikas: solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 5 / 10 DPRL.. 4(N1). Navikas (17 blokas): Her2 silpna trūkinėjanti/necirkuliari membraninė r-ja, 5% naviko ląstelių; Ki67 15% (hot spot 20%).
answer:  4(n

 59%|█████▉    | 389/661 [10:51<07:53,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas  2 ėminio aprašas: N2a  3.  N2b kraštai - planinis tyrimas  4. 3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - planinis tyrimas  5. ėminio aprašas: N4: papildomas kraštas - planinis tyrimas. 1. Krūties sektorius 13x5x3 cm, su odos lopu 10,5x3 cm. Krūties audinyje, pjūvyje balkšvas, standus 25x22x15 mm navikas, nuo artimiausio rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2 cm.   2(2a). Riebalinio audinio fragmentas 2,3x1,2x0,4 cm. v/m  3(2b). Riebalinio audinio fragmentas 2,3x1,7x0,37 cm. v/m  4(3). Riebalinio audinio fragmentai, bendras dydis 3,5x3x1 cm. Rasti 4 limfmazgiai, didžiausias 2 cm.   5(4). Riebalinio audinio fragmentas 2,5x1,5x0,7 cm. v/m. N1: pašalintas kairės krūties kvadrantas.   Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo  nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.    N2(N2a): kraštai. Krūties audinys be patologinių pokyčių.  N3(N2b): kraštai. Krūties audinys be patologinių pokyčių.  N4(N3): kairės pažasties sarginis limfmazgis. Limfmazgiai (4) be patologinių pokyčių.  N5(N4): papildomas kraštas. Krūties audinys be patologinių pokyčių.    pT1c(18 mm) pLVI-0 pL0 pR0.. N1: pašalintas kairės krūties kvadrantas. Krūties audinį infiltruoja naviko (mikroskopoiškai 18 mm) duktalinės struktūros (iki 30 proc.), netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.   Intravaskulinio plitimo nestebima, nuo operacinių kraštų 2 mm.   N2(N2a): kraštai. Krūties audinys be patologinių pokyčių.  N3(N2b): kraštai. Krūties audinys be patologinių pokyčių.  N4(N3): kairės pažasties sarginis limfmazgis. Limfmazgiai (4) be patologinių pokyčių.  N5(N4): papildomas kraštas. Krūties audinys be patologinių pokyčių.. nan
answer:  0.

 59%|█████▉    | 390/661 [10:52<07:34,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 11 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.. Krūties audinį 2-se bioptatuose infiltruoja iki 9 mm :   - smulkios trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių mem
answer:  0

 59%|█████▉    | 391/661 [10:54<07:20,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 13 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%, vietomis iki 80%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 15/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 60%, vietomis iki 80%.
answer:  3b

 59%|█████▉    | 392/661 [10:56<07:49,  1.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštas - extra - be naviko  2(N2b). kraštas - extra - be naviko  3(N3). Sarg. l/m - extra 2 sarginiuose  l/m iš 6 pašalintų rastos mts   4(N1) - sektorius - planinis patologinis tyrimas ir skubus rentgeninis tyrimas- navikas pašalintas. 4(1). Krūties sektorius 5x3,5x2 cm be odos. Pjūvyje, pilkšvas, gan aiškių ribų navikas 17x13x10 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,1 cm.. 1(2a, ekstra). "Kraštai": krūties audinys su koaguliuotais kanaliukais; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos metastazė dvejuose limfmazgiuose (mts 2/6 l/m; iki 9 mm skersmens).  4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma   su mikropapiliniu komponentu (~40%) ir židinine mucinų produkcija (~25%), SUMINIS TNM:   pT1c (navikas 13 mm) N1a(sn) (mts 2/6 l/m; iki 9 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose).   Gausūs naviką infiltruojantys limfocitai. Kalcifikatai.     Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 98% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 5% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%. Karštame taške 15-20%.    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis ir papilinis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).   Nuo sektoriaus rezekcijos krašto invazyvus navikas nutolęs 0,1 mm, DCIS komponentas - 0,5 mm.. 1(2a, ekstra). "Kraštai": nežymiai fibrozuotas krūties audinys su koaguliuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas, vaskuliarizuotas brandus rieb. aud.; be naviko.   3(ekstra). "Sarginiai limfmazgiai"(6): dviejuose (2) limfmazgiuose žemiau, punkte Nr.4, aprašyto naviko metastazės, iki 9 mm skersmens, su ekstranodaliniu plitimu.   4(1). NAVIKAS (invazyvus navikas - 13 mm skersmens; su aplinkiniu DCIS komponentu židinys - 17 mm):   krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios netaisyklingos liaukinės, kribriforminės ir intraliuminalinės mikropapilinės naviko struktūros, suformuotos vidutiniškai ar ryškiau polimorfiškų ląstelių, vidutinio gausumo tamsoka citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 15/10 DPRL. Židininė ekstraląstelinių AB+ mucinų produkcija (iki 25%). Nedideli naviko nekrozės židiniai (<5%). Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Pavieniai mikrokalcifikatai.  APLINKA: šalia naviko - kribriforminiai ir papiliniai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   SEKTORIAUS REZEKCIJOS KRAŠTAS: invazyvus navikas nutolęs 0,1 mm; DCIS komponentas - 0,5 mm.. 4. Navikas (blokas 15):  EMA: (+) mikropapilinių kompleksų periferijoje.   Estrogenų receptoriai: stipri (+++) reakcija, 98% naviko ląstelių branduoliuose.  Progesterono receptoriai: vidutinė (++) reakcija, 5% naviko ląstelių branduoliuose.  HER2: silpna
answer:  1+

 59%|█████▉    | 393/661 [10:57<07:27,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 60% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 40%.. Bioptate - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, nežymiai polimorfiškais, vidutinio kalibro, ovalaus kontūro branduoliais; mitozių 4/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (++)(brand. r-ja) 60%.  HER2: silpnas dalies nusidažymas 1% naviko ląstelių.  Ki67 proliferacinis aktyvumas 40%.
answer:  1b

 60%|█████▉    | 394/661 [10:59<07:41,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu  3(2). Kairės pažasties sarginiai limfmazgiai, skubu  4(3). Kairės krūties sektorius, planinis  3. Kairės krūties sektorius, planinis. 4(3). Krūties sektorius 9,5x4,5x7 cm, su odos lopu 7x3 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 17x10x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos nutolęs 4,3 cm.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys; be naviko.   2(1b, ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai; be naviko.   3(2, ekstra). "Kairės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 17 mm) N0(sn) (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Navikas nuo sektoriaus rezekcijos krašto nutolęs 0,1 mm.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(1b, ekstra). "Apatinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar nežymiai hiperplastišku epiteliu; be naviko.   3(2, ekstra). "Kairės pažasties sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios negausios duktalinės (<10%), kribriforminės, trumpos trabekulinės, nedielės lizdinės naviko struktūros ir pabiros saikingai ar vidutiniškai polimorfiškos ląstelės, negausia ar vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 2/10 DPRL.   Nedideli židiniai su PMN židiniais, pavientės svetimkūnio tipo gigantinės ląstelės.   APLINKA: aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: navikas nutolęs 0,1 mm.. 3(ekstra). "Kairės pažasties sarginiai limfmazgiai" (blokas 3):  CK7(+) elementų nėra.   4. Navikas (blokas 11):  E-Cadherin(++/+++)(kiek netolygi membr.r-ja)100%;   p120-Catenin(++/+++)(kiek netolygi membr.r-ja)100%;   HER2: silpna (+) necirkuliari reakc
answer:  10%

 60%|█████▉    | 395/661 [11:01<07:19,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Histologinis tyrimas. Rusvo audinio fragmentai, bendras dydis 0,9x0,7x0,2 cm. v/m. Suderinama su blogai diferencijuotos duktalinės krūties karcinomos plitimu odos bioptatuose;   G3 (8 b. pgl. Nottingham sist.);  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 50%.. Odos bioptatuose infiltruoja keli smulkūs solidiniai solidiniai kompleksai epitelinių vidutinio dydžio ląstelių su vidutiniškai/ polimorfiškais branduoliais  negausioje citoplazmoje; mitozių iki 5/1 DPRL.   Mikrokalcifikatai nestebimi.. Blokas 1:  CK7: stipri teigiama (+++)   membraninė reakcija 90 proc. duktalinėse ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  GATA3: neigiama  HER2: vidutinė (++) necirkuliari reakcija, 30%  naviko ląstelių membranoje
answer:  2.

 60%|█████▉    | 396/661 [11:02<07:18,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1. Kvadranto kraštai.   N2. Kvadranto kraštai.   N3. Sarginiai l/m,. -ekstra.  N4. K. krūties kvadrantas su naviku.. 4. Krūties sektorius 11x5,5x5 cm su odos lopu 10,5x4,5 cm ir raumens fragmentu giliajame krašte 3x2,5x0,5 cm. pjūvyje balkšvas, standus, spikuliniu kraštu navikas 2,4x2,2x2,3 cm, nuo artimiausio rezekcijos krašto nutolęs 0,4 cm, siekia odą. Oda naviko projekcijoje sustandėjusi. Makroskopiškai navikas infiltruoja raumeninį audinį.. 1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (3 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(23 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).. 1(Extra). Krūties audinyje - negausūs smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje - smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 3 limfmazgiai su pavieniais antriniais limfoidiniais folikulais, neryškia sinusų histiocitoze ir lipomatoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 23 mm), suformuotas fibrozuotoje stromoje ir tarp lipocitų plintančių lizdinių, trabekulinių, tubulinių ir negausių kribriforminių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, apvaliais/ovaliais, kiek polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 9/10 DPRL. Negausūs mikrokalcifikatai. Navikas plinta tarp skersaruožių miocitų bei dermoje, epidermio nesiekia. Navikas 4,1 mm nuo rezekcijos krašto.. nan
answer:  1a

 60%|██████    | 397/661 [11:04<07:08,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm.. Invazinė lobulinė karcinoma (mažiausiai iki 13 mm);  (G2; 6 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 45%.. Krūties audinį 1-me bioptate infiltruoja iki 13 mm :   - solidiniai kompleksai su nekrozėmis;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 5/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: silpna teigiama (+)  membraninė reakcija 10proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose,
answer:  45%.

 60%|██████    | 398/661 [11:06<07:19,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštas, ekstra.  2. pjūvio kraštas, ekstra.  3. sarginiai l/m, ekstra.   4. sektorius, planinis. 4. Krūties sektorius 11,5x3x7,5 cm su odos lopu 9,3x1,5 cm, žymėtas viela. Vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 10x9x6 mm cm, nuo giliojo rezekcijos krašto nutolęs 0,9 cm, nuo odos - 2,6 cm.. 1. Krūties lobulinė karcinoma in situ (LCIS).   2. Fibrocistiniai krūties pokyčiai: plokščia epitelio atipija, apokrininė epitelio metaplazija.  3. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 5 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1b(navikas 8 mm), pN0(sn)(0/1 l/m), LVI0 (neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Krūties lobulinė karcinoma in situ (LCIS).. 1. Krūties audinyje gausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.   2. Krūties audinyje keli nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu su židinine epitelio proliferacija su kiek stratifikuotais, nežymiai polimorfiškais branduoliais. Krūties audinyje židininė fibrozė ir apokrininė epitelio metaplazija.  3. Vienas limfmazgis su sinusų histiocitoze.  4. Krūties audinyje navikas (8 mm mikroskopiškai), infiltratyviu augimo frontu, suformuotas tubulinių, negausių kribriforminių ir trabelinių struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, vidutiniškai polimorfiškais, hiperchromiškais, smulkiai grūdėtu chromatinu branduoliais, pavieniais paryškėjusiais branduolėliais. Mitozių navike 6/10DPRL. Limfovaskulinė naviko invazija neidentifikuota(LVI0). Navikas nuo rezekcijos krašto nutolęs per 6 mm. Krūties audinyje greta naviko gausūs latakai užpildyti kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, hiperchromiškais, vidutiniškai polimorfiškais branduoliais; šalia yra nežymiai dilatuotų latakų užpildytų solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.. Blokas 17:  HER2: reakcijos naviko ląstelių membranoje nėra.  Kanaliukai 3:  CK5:mioepitelinis sluoksnis +.
answer:  0.

 60%|██████    | 399/661 [11:07<07:14,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. kairės pažasties l/m, planinis.  2. kairė krūtis, planinis.. 1. Riebalinio audinio fragmentai, bendras dydis 8,5x6x1,3 cm. Rasta 12 limfmazgių iki 2,7 cm.  2. Krūtis 600 g svorio, 22x18,5x5 cm. Krūties audinyje viršutiniame medialiniame kvadrante - pilkšvas, standus, neaiškių ribų navikas 32x30x25 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 1,5 cm, nuo odos - 1,3 cm. Navike cistinės ertmės iki 0,3 cm skersmens. Fibrozėje pilkšvas, neaiškių ribų sustandėjimas 0,7x0,7x0,5 cm.. N1: Duktalinės karcinomos metastazė limfmazgyje (1 iš 12 l/m, 10 mm); pN1a.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1a (4mm).  Žemo laipsnio intraduktalinė karcinoma (DCIS/DIN1, mikropapilinis tipas); ryškūs fibrocistiniai pokyčiai, intraduktalinės papilomos.. N1: Viename iš rastų 12 limfmazgių 10mm duktalinės karcinomos metastazė su ekstranodaliniu plitimu.  N2: Krūties audinyje 4mm navikas iš nedidelių solidinių ir kribrozinių struktūrų, kurias formuoja vidutinio polimorfizmo ląstelės, mitozių iki 1/10 DPRL. Šalia naviko fibrozės su mikrohemoragijomis juosta, negausia limfocitų ir histiocitų infiltracija (biopsijos vieta).  Aplink naviką gausūs intraduktaliniai papiliniai ląstelių proliferatai, cistinė kanaliukų dilatacija, apokrininė metaplazija, ryški stromos fibrozė.. nan
answer:  1a

 61%|██████    | 400/661 [11:09<07:27,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Užspenelinis audinys, skubu  2. sarginiai limfmazgiai, skubu  3. Kairės krūties audinys, planinis  4. Likę limfmazgiai, planiniai. 3. Krūties fragmentas 12,5x11x2,5 cm, su odos lopu 4x1,5 cm. Pjūvyje, viršutinių kvadrantų riboje, balkšvas, standus, neaiškių ribų navikas 32x24x11 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 2 cm. Medialinių kvadrantų riboje balkšvas standus darinys 0,5x0,4x0,4 cm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,5 cm. Krūties audinys fibrozuotas.   4. Riebalinio audinio fragmentai, bendras dydis 3x3x0,7 cm. Rasti 3 limfmazgiai iki 0,7 cm.. 1. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).   2. Krūties duktalinės karcinomos metastazės 4 limfmazgiuose (4/7 l/m, iki 10 mm skersmens, ekstranodalinis plitimas).   3. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT2(m)(navikai 28 mm ir 5,5 mm), pN2a(4/10 l/m), LVI2 (limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime. HER2:reakcijos nėra (0). Ki67: proliferacinis indeksas 15%. Karštame taške 25%.  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Fibrocistiniai krūties pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).   4. Reaktyvi limfadenopatija (3 l/m).. 1. Fibrozuotame krūties audinyje keli dilatuoti kanaliukai užpildyti kribrifominių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais, nežymiai polimorfiškais branduoliais.  2. Keturiuose limfmazgiuose iš šešių (4/6 l/m) žemiau aprašyto naviko metastazės iki 10 mm skersmens su ekstranodaliniu plitimu. Limfovaskulinis plitimas (LVI2). Papildomai (po fiksacijos) indentifikuotas limfmazgis su sinusų histiocitoze.  3. Krūties audinyje - hialinizuotoje stromoje 2 naviko židiniai (28 mm ir 5,5 mm mikroskopiškai) infiltratyviu augimo frontu, suformuoti gausių tubulinių, kribriforminių ir trabekulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma,  vidutiniškai polimorfiškais, hiperchromiškais branduoliais, nežymiai paryškėjusiais branduolėliais. Mitozių navike iki 10/10DPRL. Limfovaskulinė naviko invazija (LVI2). Greta naviko gausūs dilatuoti kanaliukai užpildyti solidinių ir kribrifominių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Krūties audinyje židininė fibrozė ir negausūs dilatuoti kanaliukai fokaliai kloti dvisluoksniu epiteliu su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   4. Trys limfmazgiai su sinusų histiocitoze.. Blokas 18:  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 15% naviko ląstelių. Karštame taške 25%.
answer:  0.

 61%|██████    | 401/661 [11:11<07:11,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsiniai stulpeliai. Biopsinis stulpelis 15 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G1; 5 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%. Karštame taške 20%.. Krūties audinį 1-me bioptate infiltruoja iki 11 mm :   - trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 5% naviko ląstelių. Karštame taške 20%.  Progesterono rec
answer:  0

 61%|██████    | 402/661 [11:12<07:00,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  18 G automatine biopsine adata punktuoti didelių matmenų (>50 mm) navikiškai pakitę audiniai dešiniojoje  krūtyje nuo 6 val. iki 9 val. centrinėje-vidurinėje-periferinėje dalyse, paimti trys biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 9 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 7%.. Krūties audinį infiltruoja grandinėlės, trabekulės ar pabiros, vidutiniškai polimorfiškos ląstelės, mitozių iki 2/10 DPRL.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 7% naviko ląstelių.  Progesterono receptoriai: reakcijos n
answer:  0

 61%|██████    | 403/661 [11:14<06:54,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, ~9x5 mm dydžio darinys dešiniojoje krūtyje ties 3 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 7 mm; III - 5 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli netaisyklingi kribroziniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 8
answer:  1b

 61%|██████    | 404/661 [11:15<06:54,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 3 biopsiniai stulpeliai iš ploto su mkk dešinėje krūtyje  2 but. 2 biopsiniai stulpeliai iš spikulinės deformacijos židinio prasiplėtusiais latakais kairėje krūtyje, BI-RADS 4c. 1. 3 biopsiniai stulpeliai: I - 19 mm; II - 14 mm; III - 16 mm.  2. 2 biopsiniai stulpeliai: I - 10 mm; II - 12 mm.. Dešinė  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.  Aukšto laipsnio intraduktalinė karcinoma (DCIS; solidinė ir komedo).  --------------  Kairė  N2: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%, vietomis iki 30%.. Dešinė  N1: Krūties audinyje dilatuoti kanaliukai su intraduktaliniais solidiniais polimorfiškų ląstelių proliferatais, vietomis su centrinėmis nekrozėmis. Invazinis solidinis tokių pačių polimorfiškų ląstelių židinys stromoje, mitozių 2/10 DPRL.  --------------  Kairė  N2: Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi solidiniai/kribroziniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. nan
answer:  3a

 61%|██████▏   | 405/661 [11:17<06:47,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 9 mm; II - 4 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 25% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja pavienės duktalinės struktūros, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 25% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 2%.
answer:  0

 61%|██████▏   | 406/661 [11:19<06:47,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biospiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 5 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) lobulinė karcinoma. Krūties lobulinė karcinoma in situ (LCIS).   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.  Progesterono receptoriai: stipri (+++) reakcija, 50% naviko ląstelių.. 2/2 biopsiniuose stulpeliuose plinta fibrozinės stromos apsuptos trabekulinės, lizdinės struktūros, grandinėlės, suformuotos ląstelių negausia šviesiai eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar kiek netolygaus kontūro, hiperchromiškais ar vesikuolizuotais, vidutiniškai polimorfiškais branduoliais. Mitozių navike neidentifikuota. Šalia - latakai su solidiniais proliferatais iš navikui identiškų ląstelių.. Blokas 1:  CK5: mioepitelinio išklojimo navike nėra(-).   E-Cadherin: (-).  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 50% naviko ląstelių membranoje.  Ki67: reakcija branduol
answer:  10%.

 62%|██████▏   | 407/661 [11:20<06:54,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sektorius skubus Ro tyrimas- MK pašalinti. N1 sektorius.  2(2a). Kraštai.  3(2b). Kraštai. - planinis patologinis tyrimas.. 1. Krūties sektorius 3,5x2,5x2 cm be odos, žymėtas viela. Vielos projekcijoje, neaiškių ribų, pilkšvas židinys 8x6x4 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm.  2. Riebalinio/ fibrozinio audinio fragmentas 1,5x0,6x0,3 cm. v/m   3. Riebalinio/ fibrozinio audinio fragmentas 1,5x1,2x0,4 cm. v/m. N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1a (3,3mm).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.  Vidutinio laipsnio papilinė intraduktalinė karcinoma DCIS/DIN2 (6mm židinys aplink invazinį naviką; krūties audinyje dar du, 6mm ir 3 mm, židiniai).  N2a: Žemo laipsnio kribriforminės intraduktalinės karcinomos 0,5mm židinys (DCIS/DIN1).  Rezekcijos kraštas be naviko.  N2b: Krūties audinys be naviko.. N1: Krūties audinyje 3,3mm invazinis navikas:  netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.  Aplink naviką 6mm plote  intraduktaliniai papiliniai vidutinio polimorfizmo ląstelių proliferatai; toliau nuo naviko du, 6mm ir 3mm tokios pačios struktūros intraduktaliniai priloferatai.  Rezekcijos kraštas be naviko.  N2a: Fibrozuotame krūties audinyje 0,5mm dilatuotas kanaliukas su kribroziniais intraduktaliniais neryškiai polimorfiškų ląstelių proliferatais be mioepitelinio sluoksnio.  Rezekcijos kraštas be naviko.  N2b: Krūties audinys be naviko.. Invazinis navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama (branduolių nusidažymas 2% naviko ląstelių).  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 40% navik
answer:  1b

 62%|██████▏   | 408/661 [11:23<07:32,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.  2(2b). Kraštai - skubus tyrimas - be naviko.  3(2). Dešinės pažastie sarginis limfmazgis - skubus tyrimas 6 l/m be naviko.  4(1). Dešinės krūties kvadrantas - planinis tyrimas.. 4(1). Krūties sektorius 13x7,5x4 cm su odos fragmentu 12,5x4,3 cm, žymėtas dviem vielomis ir vienu trumpu, vienu ilgu siūlu. I vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 1,3x1x0,7 cm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 3 cm. II vielos projekcijoje - naviką siekianti fibrozės zona, 5x4,5x3 cm, atstumas tarp vielų 3 cm. Odoje 4 rusvi, smulkiai gruoblėti dariniai iki 0,9x0,6x0,2 cm, vienas jų siekia rezekcijos kraštą.. 1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė, apokrininė metaplazija); be naviko.   2(2b, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija); kalcifikatai; be naviko.   3(2, ekstra). "Dešinės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (6 l/m).     4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma (su apokrininės diferenciacijos požymiais), SUMINIS TNM:   pT1b (navikas 9 mm) N0(sn) (0/6 l/m),   LVI-0 (definityvi limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.   HER2: reakcija neigiama (1+).   Androgenų receptoriai: stipri brand. r-ja, 100%.     Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė, gausūs apokrininės metaplazijos židiniai). Odos seborėjinė keratozė.. 1(2a, ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su apokrinės metaplazijos zonomis, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su apokrinės metaplazijos zonomis; smulkūs kalcifikatai; be naviko.   3(2, ekstra). "Dešinės pažasties sarginiai limfmazgiai": šeši (6) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4(1). NAVIKAS (mikroskopiškai - 9 mm; su aplinkine fibrozės zona ~12 mm židinys): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta besiliejančios kribriforminės ir dominuojančios trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai ar fokaliai ryškiau polimorfiškų ląstelių, gausia ryškiai eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su fokaliai ryškiomis nukleolėmis; mitozių iki 15/10 DPRL. Fokaliai naviko periferijoje kiek gausesnė perinavikinė limfocitinė infiltracija. Pavieniai mikrokalcifikatai. Fokaliai ryškesnės kolageninės fibrozės zonos (g.b. ankstenės biopsijos vieta).   APLINKA: šalia naviko - keli nedideli kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis ir "putotų" makrofagų intarpais. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis su papiliarizacija, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu.   ODOS DARINIAI: epidermio dariniai, kloti hiperplastišku, akantotišku, vietomis papiliarizuotu, hiperkeratotišku daugiasluoksniu plokščiu epiteliu, suformuotu iš bazaloidinių ląstelių su raginėmis cistomis, bazalinio epidermio sluoksnio hiperpigmentacija.  SEKTORIAUS REZEKCIJOS KRAŠTAS: naviko struktūros nutolusios - 1,3 mm.. 4(1). Navikas (blokas 18):  Androgenų receptoriai: stipri (+++) brand.r-ja 100%; GATA3: (+/++)(brand.r-ja)70%;   Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.
answer:  4(

 62%|██████▏   | 409/661 [11:24<07:21,  1.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.N2A- kraštai - extra  2. 2B- kraštai --extra be naviko   3. (3) - sarginis - be naviko -extra  4. (1) sektorius - planis patologinis tyrimas  skubus rentgeninis tyrimas- navikas pašalintas. 4. Krūties sektorius 9,5x4x3 cm su odos lopu 10x3 cm, vienas kraštas žymėtas 2 trumpais siūlais, kitas kraštas - 1 trumpas, 1 ilgas. Pjūvyje pilkšvas, elastingas, gana aiškių ribų navikas 1,8x1,6x1,3 cm (sudėtas visas), nuo artimiausio (giliojo) rezekcijos krašto nutolęs 0,1 cm, nuo krašto, žymėtu 1 trumpu, 1 ilgu siūlu - 0,5 cm, nuo krašto, žymėtu 2 trumpais siūlais - 2,5 cm, odos – 1 cm.. 1. (2a) kraštai -extra: krūties audinys be patologinių pokyčių.  2. (2b) - kraštai -extra: krūties audinys be patologinių pokyčių.  3. Sarginiai l/m - extra: limfmazgis (1) be patologinių pokyčių.    4. Krūties sektorius. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma;  (G3; 9 b. pgl. Nottingham sist.) pT1c pLVI-0 pN0 pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama/žema raiška (1+).  Ki67: proliferacinis indeksas 85%.. 1. (2a) kraštai -extra: krūties audinys be patologinių pokyčių.  2. (2b) - kraštai -extra: krūties audinys be patologinių pokyčių.  3. Sarginiai l/m - extra: limfmazgis (1) be patologinių pokyčių.  4. Krūties sektorius. Krūties audinyje ribotą naviką formuoja:   - solidiniai kompleksai;  - stambių ląstelių su ryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 20/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.  Navike gausi limfoplazmocitinė infiltracija.. nan
answer:  1a

 62%|██████▏   | 410/661 [11:26<07:12,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 11,5x7x5 cm su oda 11x4cm. Pjūvyje - pilkšvas, standus neaiškių ribų navikas 12x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 1,2 cm, nuo odos - 1,7 cm. Naviko projekcijoje krūties audinys fibrozuotas 5x3 cm plote.. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).   4. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma, SUMINIS TNM: pT1c(12 mm navikas) N0(sn)(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Perineurinė invazija. Radikalus pašalinimas.   Naviko imunotipas atliktas biopsijoje (žr.pastabą).. 1(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 3 limfmazgiai su I/II folikulais, fokaline parakortekso hiperplazija, sinusų histiocitoze ir lipomatoze.  4. Krūties audinyje - desmoplastiškoje stromoje, infiltratyviu frontu plintantis navikas, suformuotas solidinių kompleksų, trabekulių, negausių tubulių (<10 %). Naviko ląstelės su negausia, eozinofiliška citoplazma, smulkiais ar vidutinio kalibro, ovoidiškais, hiperchromiškais, vidutiniškai polimorfiškais branduoliais. Mitozių navike iki 75/10 DPRL. Naviko centre plati kolagenizuotos fibrozės zona; periferijoje - pigmentuotų makrofagų židiniai (biopsijos vieta). Naviko plitimas latakų spindžiuose ir perineuriškai.. CD31+ endotelizuotose ertmėse naviko plitimo neidentifikuota.
answer:  1.

 62%|██████▏   | 411/661 [11:28<07:08,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2A) - kraštai - be naviko   2(N2b) - kraštai - be naviko  3(N3) - sarginiai l/m- be naviko  4(N1) - sektrorius su dalimi m. pectoralis major sin - planinis tyrimas. 4. Riebalinio audinio fragmentas 6x4,5x5,5 cm, su raumeniniu audiniu 2,5x2,3 cm plote (žymėtu siūlu). Pjūvyje balkšvas, standus, aiškių ribų navikas 25x19x25 mm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo raumens rezekcijos krašto - 0,5 cm.. PAPILDYTA  1(N2A). Nežymi fokalinė krūties audinio fibrozė.  2(N2b). Nežymi fokalinė krūties audinio fibrozė.  3(N3). Reaktyvi limfadenopatija (1 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenocarcinoma, TNM (Nr.1-Nr.4): pT2(2,5 cm) pN(sn)0 (0/1 l/m). LVI0(limfovaskulinės naviko invazijos nėra).     Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: ribinė (2+).  Ki67: 5%.  ---  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).. 1(N2A). Krūties audinyje - negausūs smulkūs fibrozės židiniai su negausiais smulkiais kanaliukais, išklotais dvisluoksniu epiteliu.   2(N2b). Krūties audinyje - negausūs smulkūs fibrozės židiniai su negausiais smulkiais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N3). Sinusų histiocitozė viename (1) limfmazgyje.  4(N1). Krūties audinyje - navikas; solidines, trabekulines, negausias smulkias kribrozines ar susiliejančias duktalines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 3 / 10 DPRL; menkai ląstelinga /fibrozinė stroma centrinėje naviko dalyje.. 4(N1). Navikas (10 blokas): Her2 silpna ištisinė membraninė r-ja 20% naviko ląstelių; Ki67 5%.
answer:  4(n

 62%|██████▏   | 412/661 [11:29<07:21,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. du sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 7x3,5x6 cm, su odos lopu 6,5x2,5 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 7x7x5 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 2,3 cm.. 1(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (atipinė duktalinė hiperplazija); kalcifikatai.   2(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).    3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).   4. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,    SUMINIS TNM:   pT1b (navikas 7 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis tipas).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, sklerozuojanti adenozė, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).. 1(ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija; kalcifikatai.   2(ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar hiperplastišku epiteliu; keli su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS); be naviko.   3(ekstra). "Sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės, kribriforminės ir nedidelės lizdinės naviko struktūros, suformuotos saikingai ar vidutiniškai polimorfiškų ląstelių, negausia šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozės retos, sunkiai vizualizuojamos. Smulkūs mikrokalcifikatai. Rezekcijos kraštas ties naviku "fragmentuotas", patikimai vizualizuojamos zonos be naviko.   APLINKA: šalia naviko - kribriforminiai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu.. 1(ekstra). "Kraštai"(8 blokas):   CK14(+) mioepitelinis sl.  4. Navikas (17 blokas):   HER2: silpna (+) necirkuliari reakcija, 20% naviko ląstelių membranoje.
answer:  0.

 62%|██████▏   | 413/661 [11:31<07:03,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1  biopsinis  stulpelis. Biopsinis stulpelis 9 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 10%.. Krūties audinį infiltruoja pavienės duktalinės struktūros, nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 95% naviko ląstelių.  Ki67+ 10%
answer:  3b

 63%|██████▎   | 414/661 [11:33<07:22,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštas - skubus tyrimas (invazyvus židinys)  2 ėminio aprašas: N2b kraštas - skubus tyrimas (invazyvus židinys)  3 ėminio aprašas: N3: kairės pažasties limfmazgiai - planinis tyrimas  4 ėminio aprašas: N4: papildomas kraštas - planinis tyrimas  5 ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas. 3. Riebalinio audinio fragmentai, bendras dydis 7,5x5x2 cm. Rasta 12 limfmazgių iki 2 cm.  4. Riebalinio audinio fragmentas 1,5x1x0,6 cm.  5(1). Krūties sektorius 15x8x3 cm, su odos lopu 14x4 cm, su įtrauktu speneliu. Pjūvyje pilkšvas, standus, neaiškių ribų navikas 30x22x14 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1 cm.. 1(2a, ekstra). "Kraštas": duktalinės karcinomos židinys (~0,85 mm skersmens).    2(2b, ekstra). "Kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   3. "Kairės pažasties limfmazgiai": duktalinės karcinomos metastazė keturiuose limfmazgiuose (mts 4/12 l/m; iki 8,5 mm skersmens).  4. "Papildomas kraštas": fibrozuotas riebalinis audinys; be naviko.     5(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT2(m) (du židiniai: I - 30 mm; II - 0,8 mm) N2a (mts 4/12 l/m; iki 8,5 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Perineurinis plitimas.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2:reakcijos nėra (0).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Naviko struktūros sektoriaus koaguliacijos zonoje (~0,4 mm atkarpoje).. 1(2a, ekstra). "Kraštas": žemiau, punkte Nr.5, aprašyto naviko židinys, 0,85 mm skersmens (gilesniuose planinio tyrimo pjūviuose židinys neišlieka).   2(2b, ekstra). "Kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ir hiperplastišku epiteliu; be naviko.   3. "Kairės pažasties limfmazgiai"(12): keturiuose (4) limfmazgiuose žemiau, punkte Nr.5, aprašyto naviko metastazės, iki  8,5 mm skersmens, su ekstranodaliniu plitimu.   4. "Papildomas kraštas": fibrozuotas brandus riebalinis audinys; be naviko.     5(1). SPENELIS: klotas hiperkeratotišku epidermiu su reaktyvia akantoze.   NAVIKAS (du židiniai: I - 30 mm; II - 0,8 mm):   krūties audinyje, fibrozinėje - desmoplastiškoje stromoje, infiltratyvios naviko struktūros, suformuotos pavienių ar nedideliais lizdais-trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio - stambaus kalibro, nereguliaraus kontūro branduoliais, pavienės smulkios duktulės; mitozių iki 8/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Perineurinis naviko plitimas.   Invazijos fronte kiek gausesnė limfocitinė infiltracija. Naviko centre ryški fibrozės zona.   APLINKA: šalia naviko - kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: navikų struktūros siekia koaguliacijos zoną (~0,4 mm atkarpoje).. 5(1). Navikas (blokas 21):  E-Cadherin(+++)(membr.r-ja)100%.   EMA(+/+++)(citopl.r-ja)100%.   HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 63%|██████▎   | 415/661 [11:34<06:53,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 7 mm.. Pokyčiai būdingi intracistinei papilinei karcinomai (traktuojama kaip In situ karcinoma).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.. Krūties audinyje papilinės/kribrozinės ir solidinės struktūros be išlikusio mioepitelinio sluoksnio, sudarytos iš vidutiniškai polimorfiško kubinio/cilindrinio epitelio.. nan
answer:  0.

 63%|██████▎   | 416/661 [11:36<07:04,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai  - skubus tyrimas  2(N2b) kraštai  - skubus tyrimas  3(N3) dešinės pažasties sarginis limfmazgis - skubus tyrimas  4(N1) pašalintas dešinės krūties kvadrantas - planinis tyrimas  5(N4) papildomas kraštas - planinis tyrimas. 4. Krūties sektorius 12,5x5x4 cm su oda 12x3,5 cm, su speneliu. Spenelio projekcijoje - pilkšvas, standus, aiškių ribų navikas 20x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 0,9 cm.  5. Riebalinio audinio fragmentas 1,5x1x0,4 cm. v/m. Koreguotas atsakymas (Indas Nr. 5).  1(ekstra). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir papilinis tipai).  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) mikropapilinė karcinoma, SUMINIS TNM: pT1c(20 mm) pN0(sn)(0/1 l/m) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir papilinis tipai). Intraduktalinės papilomos.  5. Papildomas kraštas. Riebalinis fibrozinis audinys.  Imunofenotipas (biopsijoje):   Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 25%, vietomis iki 40%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu. Dilatuoti latakai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais. Stambus dilatuotas latakas su intraduktalinėmis, papilinėmis fibrovaskulinės stromos struktūromis, klotomis dvisluoksniu epiteliu.   2(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 1 limfmazgis su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Spenelis: normali histologinė struktūra.   Krūtyje - navikas (20 mm) ekspansyviu augimo frontu, suformuotas mikropapilinėmis struktūromis ir lizdais besidėstančių ląstelių vidutinio gausumo - gausia ryškia eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 12/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu. Stambus dilatuotas latakas su intraduktalinėmis, papilinėmis fibrovaskulinės stromos struktūromis, klotomis dvisluoksniu epiteliu.  5. Papildomas kraštas. Riebalinis fibrozinis audinys.  Imunofenotipas (biopsijoje):. Navikas:  EMA(++) fokaliai invertuota citop. r-ja.
answer:  100%.

 63%|██████▎   | 417/661 [11:38<07:15,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Suspitio CA mammae sin - extra.  1(2a). Kraštai (be naviko) - extra;  2(2b). Kraštai (be naviko) - extra;   3(1). Pašalintas markiruotas kaclinatų plotas iš kairės krūties žymėtas trimis vielomis  - planinis tyrimas;  4(3). Dešinės krūties žymėtas kvadrantas žymėtas - planinis tyrimas.. 3(1). Krūties sektorius 8,5x4,5x3cm be odos lopo, žymėtas trimis vielomis. Pjūvyje firbrozės zona 6x4x2,3cm, siekia rezekcijos kraštą.  4(3). Krūties sektorius 5x3x1,7cm su odos lopu 4x1,3cm žymėtas viela. Vielos projekcijoje fibrozės zona 3x1,5x1cm, fibrozės zonoje balkšvas, standus, aiškių ribų darinys (sudėtas visas) 0,7x,0,5x0,5cm, nuo artimiausio rezekcijos krašto nutolęs 0,2cm.. 1(2a). Kraštai. Krūties audinys be patologinių pokyčių.    2(2b). Kraštai. Krūties audinys be patologinių pokyčių.    3(1). Markiruotas kalcinatų plotas iš kairės krūties.  Krūtyje invazinė duktalinė karcinoma G2(6 b. pgl. Nottingham sist.);    pT1c(11 mm), pLVI-0 pR0(1,5 mm).   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 50% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.    Vidutinė intraduktalinė karcinoma, DCIS/DIN2, solidinio, tinklinio ir komedo tipo.  Krūties fibrocistiniai pakitimai.    4(3). Dešinės krūties kvadrantas.   Ribotas darinys: Intraduktalinė karcinoma žemo laipsnio (DCIS/DIN1, galimai adenomoje).  DCIS/DIN1 difuzinis plitimas audinyje ir operaciniame krašte, pR(is)1.   Krūties fibrocistiniai pakitimai.. 1(2a). Kraštai. Krūties audinys be patologinių pokyčių.    2(2b). Kraštai. Krūties audinys be patologinių pokyčių.    3(1). Markiruotas kalcinatų plotas iš kairės krūties.   Krūties fibrozuotame audinyje infiltruoja iki 11 mm trabekulinės struktūros (3 b.) su vidutiniu ląstelių branduolių polimorfizmu (2 b.) ir mitozėmis iki 3/10DPRL (1 b.). Šios infiltracinės struktūros 1,5 mm nuo operacinio krašto. Intralimfatinis / Intravaskulinis plitimas nestebimas.  Analogiškų ląstelių intraduktalinės solidinės, tinklinės struktūros ar su  nekroze, apima >25% naviko ploto ir plinta už invazyvaus naviko ribų apie 15 mm; stebimos 0,5 mm nuo operacinio krašto.  Aplinkui - audinio fibrozė, smulkių kanaliukų proliferacijos židiniai, cistinė kanaliukų dilatacija, kanaliukų epitelio apokrininė metaplazija.    4(3). Dešinės krūties kvadrantas.  Ribotas darinys suformuotas su netaisyklingais įvairaus dydžio nekompaktiškai besidėstančiais latakais, išklotais stulpiniu epiteliu stratifikuotais branduoliais su nežymia atipija.  Analogiškų latakų difuzinis plitimas audinyje ir židiniškai operaciniame krašte.  Audinio fibrozė, smulkių kanaliukų proliferacijos židiniai, cistinė kanaliukų dilatacija, kanaliukų epitelio apokrininė metaplazija.. Nr. 3(kairės krūties).  Blokas 5:  CK14: neigiama (-) atipinių difuziškai plintančių struktūrų ląstelių membranoje  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląst
answer:  1.

 63%|██████▎   | 418/661 [11:40<06:52,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stulpeliai histologinės medžiagos. 3 fragmentuoti biopsiniai stulpeliai: I - 11 mm; II - 9 mm; III - 5 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%, vietomis iki 10%.. Krūties audinį infiltruoja netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  1a

 63%|██████▎   | 419/661 [11:42<07:11,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštas  - skubus tyrimas - be naviko  2 ėminio aprašas: N2b kraštas  - skubus tyrimas - be naviko  3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - skubus tyrimas - viename iš trijų limfmazgių 3mm makrometastazė  4(1) ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas. 4(1). Krūties sektorius 11x8x4 cm su odos lopu 10x3 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje - balkšvas standus, spikulinis navikas 0,8x0,7x0,6 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,5 cm, nuo odos nutolęs 2 cm.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos metastazė limfmazgyje (mts 1/3 l/m; iki 3 mm skersmens).    4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,  SUMINIS TNM:   pT1b (navikas 8 mm) N1a(sn) (mts 1/3 l/m; iki 3 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti ir mikroglandulinė adenozė,   stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).   Sektoriaus rezekcijos kraštas be naviko.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai"(3): viename (1) limfmazgyje žemiau, punkte Nr.4, aprašyto naviko metastazės, 3 mm skersmens, be ekstanodalinio plitimo.   4. NAVIKAS: krūties audinyje, fibrozuotoje-elastozinėje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retos duktalinės, gausesnės kribriforminės, trabekulinės, lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 1/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Nedideli MMN infiltracijos židiniai. Pavieniai mikrokalcifikatai.  APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti, kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 4. Navikas (blokas 14):  HER2: silpna (+) necirkuliari reakcija, 20% naviko ląstelių membranoje.
answer:  0

 64%|██████▎   | 420/661 [11:43<07:05,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2: dešinės pažasties sarginis limfmazgis 1l/m - extra  2 ėminio aprašas: N1: pašalinta dešinė krūtis -  planinis tyrimas. 2(1). Krūtis 1010 gramų svorio, 23x16x5 cm, spenelis kiek įtrauktas. Krūties audinyje, spenelio projekcijoje - pilkšvas, standus, neaiškių ribų navikas 43x20x14 mm, nuo giliojo rezekcijos krašto nutolęs 4 cm, nuo odos - 0,8 cm.. 1(2). Duktalinės karcinomos mikrometastazės limfmazgyje (1/1 l/m; iki 1,93mm).  2(1). Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 43mm) pN1mi(sn)(1/1 l/m; iki 1,93mm); LVI-2 (Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).  IHC reakcijos atliktos VPC:B23-4377 tyrime:  "Estrogenų receptoriai: vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%.". 1(2). Vienas(1) limfmazgis su žemiau aprašyto naviko metastazėmis (iki 1,93mm).  2(1). Krūties audinyje - navikas, formuojamas trabekulinių struktūrų, smulkių agregatų, pavienių netaisyklingų liaukinių/kribriforminių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, nežymiai, vietomis vidutiniškai polimorfiškais branduoliais; navike iki 3 mitozių/10 DPRL. Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse. Spenelis be histologinių patologinių pokyčių.. 1(2). Blokas 2:  Naviko metastazės limfmazgyje:   PANCK(+++), membr. r-ja, 100%.   2(1). Blokas 19:  Navikas:  E-Cadherin(+++), membr. r-ja, 100%;   P120(+++), membr. r-ja, 100%.
answer:  3b

 64%|██████▎   | 421/661 [11:45<06:42,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 10 mm; II - 9 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 50% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 7%.. Krūties audinį infiltruoja duktalinės struktūros (<10%), netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) cirkuliari reakcija, 20%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 7% naviko ląstelių.  Progesterono receptoriai: vidutinė
answer:  0

 64%|██████▍   | 422/661 [11:46<06:31,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 N2a -kraštai -extra  2. N2b kraštai  skubus tyrimas - be naviko  3: dešinės pažasties sarginis limfmazgis - skubus tyrimas 3 l/m be naviko  4. (1) pašalintas dešinės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 15,5x8x5,5 cm, su odos lopu 12,5x4 cm, žymėtas viela. Ant odos rusvas, smulkiai papiliarizuotas, iškilęs darinys 1,7x1,2x0,3 cm, nuo odos rezekcijos krašto nutolęs 0,2 cm. Krūties audinyje, vielos projekcijoje pilkšvas, mazgotas, aiškių ribų navikas 15x16x16 mm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos nutolęs 3cm.. N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(16mm).  N2ab: Audiniai be naviko.  N3: Limfmazgiai (3 l/m) be naviko; pN0(sn).. N1: Krūties audinyje 16mm navikas: netaisyklingi solidiniai kompleksai ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.  N2ab: Audiniai be naviko.  N3: Limfmazgiai (3 l/m) be naviko.. nan
answer:  0.

 64%|██████▍   | 423/661 [11:48<06:22,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 13 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki  mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 35%. Karštame taške 50%.. Krūties audinį 2-se bioptatuose infiltruoja iki 11 mm :   - solidiniai kompleksai;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais gausioje eozinofilinėje citoplazmoje;   - mitozės nestebimos.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  CD56 : stipri teigiama (+++)   membraninė reakcija 3 proc. atipinėse ląstelėse  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių
answer:  1b

 64%|██████▍   | 424/661 [11:49<06:15,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 6 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma. Mikrokalcinatai.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 15%.. Bioptatuose (2/2) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 2/10 DPRL. Mikrokalcinatai.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 95%.  HER2: silpnas/vidutinis dalies membranos nusidažymas 30% naviko ląstelių., foninė citopl. r-ja.  Ki67 proliferacinis aktyvumas 15%.  E-cadherin(+
answer:  100%

 64%|██████▍   | 425/661 [11:51<06:18,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pjūvio kraštai - planinis;  2. Pjūvio kraštai - planinis;  3. Sarginiai l/m - planinis;  4. Sektorius - planinis.. 1. Riebalinio fibrozinio audinio fragmentas 3,8x2,5x0,6 cm. v/m  2. Riebalinio fibrozinio audinio fragmentas 3,5x2,2x0,5 cm. v/m  3. Riebalinio audinio fragmentai, bendras dydis 3x2,6x0,6 cm. Rasti 2 limfmazgiai iki 1 cm.  4. Krūties sektorius 16,5x10x4 cm su odos lopu 17x3,5 cm, žymėtas 2 vielomis:  - I vielos projekcijoje, pjūvyje balkšvas, standus, neaiškių ribų navikas 1x1x0,8 cm, nuo artimiausio rezekcijos krašto nutolęs 1,3 cm, nuo odos – 2 cm.  - II vielos projekcijoje, pjūvyje balkšvas, standus, neaiškių ribų navikas 1,3x1x1 cm, nuo I viela žymėto naviko nutolęs 2,5 cm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos – 2,5 cm.. N1: Atipinė duktalinio epitelio hiperplazija.  N2: Krūties audinys be naviko.  N3: Viename limfmazgyje (1 iš 2 l/m) duktalinės karcinomos 3mm metastazė; pN1a (sn).  N4: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(m) (du navikai 10mm ir 13mm).. N1: Krūties audinyje dilatuoti kanaliukai su mikropapilinėmis ir arkinėmis struktūromis iš nežymiai polimorfiškų ląstelių, vietomis su miopitelinių ląstelių priemaiša.  N2: Krūties audinys be naviko.  N3: Viename limfmazgyje (1 iš 2 l/m) žemiau aprašyto naviko 3mm metastazė.  N4: Krūties audinyje du navikiniai židiniai (10mm ir 13mm): duktalinės struktūros, netaisyklingi solidiniai/kribroziniai kompleksai, trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. nan
answer:  0

 64%|██████▍   | 426/661 [11:53<06:23,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. deš. pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: 2. Deš. krūtis, planinis. 2. Krūtis 2050 gramų svorio, 31x22x8,5 cm. Krūties audinyje:  - apatinių kvadrantų riboje - balkšvas, standus neaiškių ribų I navikas 8x6x6 mm, nuo odos nutolęs 1 cm, nuo giliojo rezekcijos krašto - 6 cm;  - nuo I naviko 1,7 cm atstumu - balkšvas, standus neaiškių ribų II navikas 5x4x3 mm, nuo odos nutolęs 1,5 cm, nuo giliojo rezekcijos krašto - 5,5 cm;  - nuo II naviko 2,5 cm atstumu, vidiniame medialiniame kvadrate - balkšvas, standus neaiškių ribų III navikas 3x3x3 mm, nuo odos nutolęs 3 cm, nuo giliojo rezekcijos krašto - 4,5 cm;  - nuo III naviko 2 cm atstumu, vidiniame medialiniame kvadrate - balkšvas, standus neaiškių ribų IV navikas 5x4x4 mm, nuo odos nutolęs 3,5 cm, nuo giliojo rezekcijos krašto - 3,5 cm, nuo I naviko - 4 cm;  - apatiniame lateraliniame kvadrante - pilkšvas, standus aiškių ribų V navikas 5x4x4 cm, nuo odos nutolęs 2 cm, nuo giliojo rezekcijos krašto - 5 cm.  Bendras didžiausias visų navikų matmuo - 7 cm.. N1-2: Krūties daugiažidininė karcinoma:  trys židiniai (8mm, 5mm ir 5mm) gerai difencijuotos (G1, 4 balai pagal Nottingham) duktalinės karcinomos;  du židiniai (3mm ir 2mm) gerai difencijuotos (G1, 5 balai pagal Nottingham) lobulinės karcinomos;  pT1b(m); pN1a(sn) (10mm metastazė ir duktalinės ir lobulinės karcinomos).. N1: Iš į parafiną įlietos limfmazgio medžiagos po IHC tyrimo išryškėjo 10mm metastazė iš duktalinių struktūrų ir difuziškai plintančių ECAD negatyvių ląstelių.  N2: Krūties audinyje 3 navikai 8mm, 5mm ir 5mm iš duktalinių ir kribrozinių neryškiai polimorfiškų ląstelių struktūrų;  2 navikai 3mm ir 2mm iš juostų ECAD neigiamų neryškiai polimorfiškų ląstelių.  Rezekcijos kraštas be naviko.. nan
answer:  0.

 65%|██████▍   | 427/661 [11:54<06:15,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsiniai stulpelis 13 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 100% naviko ląstelių.  Ki67+ 20%.
answer:  3b

 65%|██████▍   | 428/661 [11:57<07:12,  1.86s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.1a- viršutinis kraštas (deš.krūtis), skubu  2.1b- apatinis kraštas (deš. krūtis), skubu  3.(2). Deš. pažasties sarginiai limfmazgiai, skubu  4.(4a) - viršutinis kraštas (kairė krūtis), skubu  5.(4b)- apatinis kraštas (kairė krūtis), skubu  6.(5) - Kairės pažasties sarginiai limfmazgiai, planas  7.(3)- deš. krūties kvadrantas, planinis  8.(6) - Kairės krūties kvadrantas, planinis  9.(7) - papildomas k.kruties viršut.kraštas-planas  10.(8) - papildomas d.krūtis apat.kraštas-planas. 6(5). Riebalinio audinio fragmentas 5,5x2,5x1,3 cm. Rastas limfmazgis 3 cm.   7(3). Krūties sektorius 13,5x6,5x3 cm su odos lopu 8,5x3,5 cm, žymėtas dvejomis vielomis. Vienos vielos projekcijoje neaiškių ribų, standi fibrozės zona su prasiplėtusiais tarpais 21x9x7 mm, nuo giliojo rezekcijos krašto nutolusi 0,3 cm, nuo odos - 2,5 cm. Kietos vielos projekcijoje 2 intramamariniai limfmazgiai iki 0,5 cm skersmens. Fibrozės zona vielos projekcijoje sudėta visa.   8(6). Krūties sektorius 9x6x2,2 cm, be odos, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 21x18x11 mm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm.  9(7). Riebalinio/fibrozinio audinio fragmentas 2,5x1x0,4 cm. v/m  10(8). Riebalinio audinio fragmentas 3x1,3x0,5 cm. v/m. 1(extra). Viršutinis kraštas, dešinė. Fibrocistiniai pokyčiai.  2(extra). Apatinis kraštas, dešinė. Krūties žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1, kribriforminis tipas).  3(extra). Sarginiai limfmazgiai, dešinė. Reaktyvi limfadenopatija (4 l/m).    4(extra). Viršutinis kraštas, kairė. Fibrocistiniai pokyčiai.  5(extra). Apatinis kraštas, kairė. Fibrocistiniai pokyčiai.  6. Kairės pažasties sarginiai limfmazgiai (planinis). Duktalinės karcinomos metastazė (1/1 l/m, 4,4 mm).    7. DEŠINĖ. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) multižidininė, mikroinvazyvi duktalinė karcinoma, SUMINIS TNM: pT1mi(m)(0,4 mm, 0,5 mm, 0,9 mm, 1 mm) pN0(sn)(0/6 l/m0 LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 DIN1 DIN2, kribriforminis, solidinis, komedo ir papilinis tipai), DCIS židinys iki 2 cm. R0(radikali rezekcija).  Imunofenotipas (biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.    8. KAIRĖ.  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(21 mm navikas) pN1a(sn)(MTS 1/1 l/m 4,4 mm) LVI-2(limfovaskulinė invazija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas). R0(radikali rezekcija).  Imunofenotipas (biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%, vietomis iki 30%.    9. Papildomas kairės krūties viršutinis kraštas. Fibrocistiniai pokyčiai.   10. Papildomas dešinės krūties apatinis kraštas. Fibrocistiniai pokyčiai.. 1(extra). Viršutinis kraštas (deš.krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  2(extra). Apatinis kraštas (deš. krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu. Fokaliai latakų grupė su intraduktaliniais kribriforminiais proliferatais iš ląstelių nežymiai polimorfiškais brnaduoliais.   3(extra). Sarginiai limfmazgiai, dešinė. 4 limfmazgiai su sinusų histiocitoze, lipomatoze ir pirminiais bei antriniais folikulais.  4(extra). Viršutinis kraštas (kairė krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  5(extra). Apatinis kraštas (kairė krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  6. Kairės pažasties sarginiai limfmazgiai. Vienas limfmazgis su metastaze, 4,4 mm suformuota susiliejančių tubulinių struktūrų.  7. DEŠINĖ. Krūtyje - navikas (0,4 mm, 0,5 mm, 0,9 mm, 1 mm židiniai) suformuotas lizdais besidėstančių ląstelių gausia eozinofiliška, ryškia citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 1/10 DPRL.  Greta gausūs dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais ir solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.   2 limfmazgiai su sinusų histiocitoze ir antriniais folikulais.  8. KAIRĖ. Krūtyje - navikas (21 mm) infiltratyviu ekspansyviu frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais branduoliais ryškiomis nukleolėmis; mitozių 4/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais ir solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.   Limfovaskulinė naviko invazija.  9. Papildomas k.kruties viršutinis kr. Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.    10. Papildomas d.krūtis apatinis kr. Krūties audinys su kanaliukais, klotais dvisluoksniu ir hiperplastišku epiteliu su apokrinine metaplazija. Ryškūs koaguliacijos artefaktai.. 2. DCIS (3 blokas): C14 išlaikytas mioepitelinis sluoksnis.  7. Navikas (32, 35 blokai): Ck14(-).
answer:  1.

 65%|██████▍   | 429/661 [11:58<06:53,  1.78s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 buteliukas - 3 biopsiniai stulpeliai.  2 buteliukas - 2 biopsiniai stulpeliai.. 1. 3 biopsiniai stulpeliai: I - 13 mm; II - 7 mm; III - 14 mm.  2. 2 biopsiniai stulpeliai: I - 12 mm; II - 10 mm.. 1. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G1; 5 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 7%.    2. Fibroepiteliniai pokyčiai, gali būti suderinami su krūties fibroadenoma.. 1. Krūties audinį 3-se bioptatuose infiltruoja iki 11 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.    2. Ribotas navikas, suformuotas kompaktiškos fibrozinės stromos su pavieniais suspaustais latakais, klotais dvisluoksniu epiteliu.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 50%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 7% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  80%

 65%|██████▌   | 430/661 [12:00<06:48,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1- skubi histologija - retroareoliarinė sritis - be naviko   N2-sarginis l/n  - be naviko   N3- pašalinta krūtis - planinis tyrimas - skubus rentgeninis tyrimas - 4 cm MK plotas pašalintas. 3. Krūties sektorius 13,5x9x3,5 cm su odos lopu 6x3 cm. Krūties audinyje, pjūvyje pilkšvas, neaiškių ribų židinys 6x5x5 mm (žymėtas kabute), nuo giliojo rezekcijos krašto nutolęs 0,3, nuo odos - 2,6 cm.. 1(Extra). Krūties audinys.  2(Extra). Reaktyvi limfadenopatija (2 l/m). Nodalinis nevocitinis nevusas 1 limfmazgyje.   3. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(6 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio ir žemo laipsnio duktalinė karcinoma in situ (DIN1c/DIN2/DCIS)(kribriforminė, komedo). DCIS struktūros 0,1 mm nuo sektoriaus   rezekcijos krašto.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  2(Extra). 2 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze. Vieno limfmazgio kapsulėje - negausūs lizdais besidėstantys nevocitai švelniai eozinofiliška citoplazma, ovaliais/apvaliais, monomorfiškais branduoliais.  3. Krūties audinyje - ribotas navikas (mikroskopiškai 6 mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių struktūrų, grandinėlėmis ar pabirai besidėstančių ląstelių saikinga vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, smulkiais ar vidutinio kalibro, apvaliais/ovaliais, gan monomorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 1/10 DPRL. Aplink gausūs dilatuoti kanaliukai su kribriforminiais intraduktaliniais proliferatais, suformuotais ląstelių šviesiai eozinofiliška citoplazma, vidutinio kalibro, kiek polimorfiškais, dalis su nukleole branduoliais; negausios komedo nekrozės ir kalcifikatai dalyje kanaliukų. DCIS struktūros 0,1 mm nuo žymėto rezekcijos krašto.  Aplinkiniame krūties audinyje grupės dilatuotų kanaliukų su apokrinine metaplazija.. 2. Limfmazgis (6 blokas): nevocitų lizdai SOX-10+; Cam5.2(-).
answer:  3b

 65%|██████▌   | 431/661 [12:02<06:31,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 8 mm; II - 10 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 8 mm);  (G1; 3 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 8%.. Krūties audinį 2-se bioptatuose infiltruoja iki 8 mm :   - duktalinės struktūros (95% viso naviko), netaisyklingi kribroziniai kompleksai;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 8% naviko ląstelių.  Progesterono receptoriai: stipri (+++
answer:  100%

 65%|██████▌   | 432/661 [12:03<06:25,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, ~21×17 mm dydžio darinys kairiojoje krūtyje ties 3 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai (I buteliukas).   2 ėminio aprašas: 2. 18 G automatine biopsine adata punktuotas hipoechogeninis plotas kairiojoje krūtyje ties 2 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai (II buteliukas).. 1. 3 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 14 mm; III - 7 mm.  2. 3 fragmentuoti biopsiniai stulpeliai: I - 15 mm; II - 15 mm; III - 7 mm.. N1: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.  N2: Ryški krūties audinio fibrozė, vienas fragmentuotas žemo laipsnio intraduktalinės karcinomos mikrožidinys (0,5mm).. N1: Krūties audinį infiltruoja smulkios duktalinės struktūros, negausūs netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  N2: Ryški krūties audinio fibrozė, vienas fragmentuotas žemo laipsnio intraduktalinės mikrožidinys (0,5mm).. N1 navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  1 �

 66%|██████▌   | 433/661 [12:05<06:13,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~45×33 mm dydžio darinys dešiniojoje ties 6 val. centrinėje dalyje, peraugantis odą ir raumenis, paimti 3 biopsiniai stulpeliai histologijai.. 3 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 12 mm; III - 17 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%. Karštame taške 15%.. Krūties audinį ir skersaruožių raumenų skaidulas infiltruoja trabekulės, solidiniai kompleksai, duktalinės struktūros (5%) iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki6
answer:  5%.

 66%|██████▌   | 434/661 [12:07<06:50,  1.81s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - Viršutinis kraštas  2 - Apatinis kraštas  3 - Sarginiai l/m 1-2-3 ekstra  4 - Kvadrantas. 4. Krūties sektorius 7x5x3,5 cm. Atskirai tame pačiame inde 2 riebalinio audinio fragmentai: I - 3,5x2x1,3 cm, II - 1,8x0,8x0,5 cm. Pjūvyje gelsvas, neaiškių ribų navikas 16x15x13 mm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm. 0,2 cm nuo naviko hemoragijos zona 1,1x0,8x0,8 cm. 0,9 cm nuo naviko cista 0,8x0,5x0,6 cm, lygia sienele, nuo artimiausio rezekcijos krašto nutolusi 0,1 cm.. 1(ekstra). "Viršutinis kraštas": krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija); kalcifikatai; be naviko.   2(ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija, sklerozuojanti adenozė); kalcifikatai; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (1 l/m).   Fibrozuoto krūties audinio fragmentas su židininiais fibrocistiniais pokyčiais: tikėtina pridėtinė krūtis, tikslinga klinikinė koreliacija.     4. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1b (navikas 9,63 mm) N0(sn) (0/1 l/m),   LVI-0 (definityvi limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija, sklerozuojanti adenozė).. 1(ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu ar fokaliai hiperplastišku, fokaliai nežymiai atipišku epiteliu, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), apokrininės metaplazijos zonos; kalcifikatai; be naviko.   2(ekstra). "Apatinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu ar fokaliai hiperplastišku atipiniu epiteliu, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS); suspaustų kanaliukų zonos; kalcifikatai; be naviko.   3(ekstra). "Sarginiai limfmazgiai": vienas (1) limfmazgis su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais. Atskiras krūties audinio fragmentas su ryškia kolagenine fibroze ir kanaliukais bei lobulėmis, klotomis dvisluoksniu epiteliu; nedidelis židinys su cistiškai dilatuotais kanaliukais su sekreto lobulėlis, supamomis histiocitais.   4. NAVIKAS (mikroskopiškai didžiausias naviko matmuo - 9,63 mm; su aplinkine fibroze ~16 mm skersmens židinys): krūties audinyje, fibrozuotoje, kiek lobulizuotoje, kolagenizuotoje desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės/tubulinės ir retos kribriforminės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, negausia ar vidutinio gausumo šviesia eozinofiliška citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozės pavienės, retos. Šalia fibrozuoti riboti židiniai su "putotais" makrofagais (g.b. ankstesnės biopsijos vieta). Negausi intranavikinė limfocitinė infiltracija. Pavieniai kalcifikatai.   APLINKA: šalia naviko - kribriforminiai intraduktaliniai naviko ląstelių proliferatai, fokaliai su centrinės nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu su papiliniais proliferatais ir židinine atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu.   Eritrocitų ekstravazacijos zonos tarp lipocitų, šalia fibrozės zonos su gausesne MMN infiltracija.   SEKTORIAUS REZEKCIJOS KRAŠTAS: invazyvaus naviko struktūros nutolusios 3,5 mm.. 4. Navikas (blokas 13):  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląstelių membranoje.
answer:  0

 66%|██████▌   | 435/661 [12:09<06:43,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1a- viršutinis kraštas, skubu  2 ėminio aprašas: 1b- apatinis kraštas, skubu  3 ėminio aprašas: deš. krūties sektorius su limfmazgiais, planinis. 3(2). Krūties sektorius 9x4,5x4 cm su odos lopu 8,5x2,4 cm. Pjūvyje balkšvas, standus, neaiškių ribų navikas 16x14x11 mm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos – 2,3 cm. Atskirai tame pačiame inde - riebalinio audinio fragmentas/pa=asties narveliena (8x6x2 cm, su 17 limfmazgių iki 1,3 cm).. 1(1A). Krūties fibrocistiniai pokyčiai.  2(1B). Krūties fibrocistiniai pokyčiai.  3(2). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, pT1c(1,6 cm) pN1a(2/17 l/m, mts 0,4 cm ir 0,5 cm). LVI2(limfovaskulinė invazija, smulkiose struktūrose).     Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 20% (hot spot 30%).. 1(1A). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2(1B). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(2). SEKTORIUS: Navikas (solidines, trabekulines, kribrozines, smulkias tubulines naviko struktūras formuoja ląstelės su kiek gausesne tamsoka eozinofiline citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 13 / 10 DPRL.  PAŽASTIES NARVELIENA: Aukščiau aprašyto naviko metastazės limfmazgiuose (dviejuose (2) iš septyniolikos (17), metastazės 0,4 cm ir 0,5 cm).. 3(2). Navikas (3 blokas):  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: nusidaži
answer:  0%.

 66%|██████▌   | 436/661 [12:10<06:21,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 13 mm; II - 12 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.. Krūties audinį infiltruoja duktalinės struktūros ir trumpos juostos iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 2%
answer:  1b

 66%|██████▌   | 437/661 [12:12<06:07,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: k.krūtis, k. pažasties l/m - planiniam tyrimui. Krūtis 20x15x9 cm, su pažasties narveliena 8x5x2,6 cm. Krūties audinyje pilkšvas, ribotas navikas 12x11,5x5,5 cm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm. Navikas išopėjęs odoje 11x6 cm plote. Rasti 8 limfmazgiai, didžiausias 4,5 cm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b(12cm, išopėjimas); pN2a (4 iš 8 l/m).  Krūties ir pažasties audinių nekrozė, uždegiminė infiltracija su abscesais.. Krūties audinyje išopėjęs 12cm navikas: susiliejantys kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL. Navike ir aplinkiniame krūties audinyje nekrozės zonos su gausia uždegimine infiltracija.  Iš rastų 8 limfmazgių 4 su metastazėmis iki 4,5cm. Pažasieties audiniuose gausi uždegiminė infiltracija su abscesais.  Operacinis pjūvis be naviko.. nan
answer:  0,

 66%|██████▋   | 438/661 [12:13<06:01,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas dešinės krūties kvadrantas - planinis tyrimas  2 ėminio aprašas: N2a kraštai  planinis tyrimas  3 ėminio aprašas: N2b kraštai  planinis tyrimas  4 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - planinis tyrimas. 1. Krūties sektorius 10x5x4,5 cm su odos lopu 9x3,5 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus navikas 11x9x8 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,5 cm.   2. Riebalinio audinio fragmentas 2,5x1,5x0,6 cm. v/m   3. Riebalinio audinio fragmentas 3,3x1,4x0,5 cm. v/m   4. Riebalinio audinio fragmentai, bendras dydis 2x1,7x1 cm. Rastas limfmazgis 1,2 cm.. N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(11mm).  N2a-2b: Krūties ir riebalinio audinio fragmentai be naviko.  N3: Limfmazgis be naviko metastazių; pN0(sn).. N1: Krūties audinyje 11mm navikas: negausios duktalinės struktūros, nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.  N2a-2b: Krūties ir riebalinio audinio fragmentai be naviko.  N3: Limfmazgis su reaktyviais pokyčiais, be naviko metastazių.. nan
answer:  1a

 66%|██████▋   | 439/661 [12:15<06:04,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 but. 2 biopsiniai stulpeliai iš kairės krūties BI-RADS 4c darinio  2 but. 3 biopsiniai stulpeliai iš dešinės krūties BI-RADS 5 darinio. 1. 2 biopsiniai stulpeliai: I - 15 mm; II - 14 mm.  2. 3 fragmentuoti biopsiniai stulpeliai: I - 6 mm; II - 1 mm; III - 2 mm.. 1. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G2; 7 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    2. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 3 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se navikinio audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.. 1. Krūties audinį 2-se bioptatuose infiltruoja iki 13 mm :   - solidiniai kompleksai ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su ryškiai polimorfiškais branduoliais  negausioje bazofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.    2. Naviko audinį 3-se bioptatuose infiltruoja iki 3 mm :   - solidiniai kompleksai;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje bazofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 80%  naviko ląstelių mem
answer:  0.

 67%|██████▋   | 440/661 [12:18<07:26,  2.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas  2(N2b) kraštai - skubus tyrimas  3(N3): kairės pažasties sarginis limfmazgis - skubus tyrimas - 2l/m be naviko  4(N5a) kraštai - skubus tyrimas  5(N5b) kraštai - skubus tyrimas  6(N6) dešinės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko  7(N7): papildomas kraštas iš kairės krūties - be naviko  8(N1): pašalintas kairės krūties kvadrantas - planinis tyrimas  9(N4): dešinės krūties kvadrantas - planinis tyrimas   10(N8): papildomas kraštas iš dešinės krūties - planinis tyrimas. 8. Krūties sektorius 15,5x8,5x5,5 cm su oda 14x5,5 cm. Krūties audinyje, pilkšvas standus, neaiškių ribų I navikas 10x8x8 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 2,5 cm, nuo odos - 2 cm. Virš I naviko krūties audinys fibrozuotas 3,5x1,7 cm su cistinėmis ertmėmis iki 0,5 cm, pakitimai nuo giliojo rezekcijos krašto nutolę 0,1 cm. Nuo I naviko 2 cm atstumu - pilkšvas standus II navikas 12x6x6 mm(sudėtas visas), nuo giliojo rezekcijos krašto 3 cm, nuo odos 1,8 cm.   9. Krūties sektorius 20x6,5x8,5 cm su oda 19x4 cm. Krūties audinyje, pilkšvas, standus, aiškių ribų I navikas 14x8x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 4,5 cm. 6cm nuo I naviko - pilkšvas, standus, neaiškių ribų II navikas - 23x10x10 mm (sudėtas visas), nuo giliojo rezekcijos krašto 0,3 cm, nuo odos 3,5 cm. Tarp navikų krūties audinys fibrozuotas 4,5x4 cm plote.  10. Riebalinio audinio fragmentas 1x0,8x0,4 cm. v/m. 1.(2a)(kairė). Krūties audinys; pavieniai intraduktaliniai mikrokalcifikatai.  2.(2b)(kairė). Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas). Lobulinė krūties Carcinoma in situ (LCIS). Krūties fibrocistiniai pokyčiai.   3.(3)(kairė) Reaktyvi limfadenopatija (2 l/m).  4(N5a)(dešinė) Krūties audinys.  5(N5b)(dešinė) Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas). Lobulinė krūties Carcinoma in situ (LCIS). Krūties intraduktalinės papilomos. Krūties fibrocistiniai pokyčiai; paprasta intraduktalinė hiperplazija.   6(N6)(dešinė) Reaktyvi limfadenopatija (3 l/m).  7(N7)(pap. kraštas, kairė) Riebalinis audinys.  8(N1)(kairė) Krūties invazyvi, gerai diferencijuota (G1; 4 balai pagal Nottingham sis) duktalinė karcinoma su lobulinės karcinomos komponentu (~5% naviko), suminis tyrimo TNM: pT1c(m)(du naviko židiniai 16,7mm ir 10mm) pN0(sn)(0/2 l/m).   IHC reakcijos atliktos VPC:B23-29805 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%."  Krūties intraduktalinė karcinoma (DCIS; kribriforminis, mikropapilinis tipas). Lobulinė krūties Carcinoma in situ (LCIS). Intraduktalinės krūties papilomos. Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.  9(N4)(dešinė) Krūties invazyvi, gerai diferencijuota (G1; 4 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(m)(dauginiai naviko židiniai nuo 0,6mm iki 14mm) pN0(sn)(0/3 l/m).   IHC reakcijos atliktos VPC:B23-29805 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%."  Krūties žemo ir vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis, kribriforminis tipas; -komedo tipo nekrozėmis). Lobulinė krūties Carcinoma in situ (LCIS). Krūties intraduktalinės papilomos. Krūties fibrocistiniai pokyčiai; paprasta intraduktalinė hiperplazija.   10(N8)(pap. kraštas, dešinė) Krūties audinys.. 1.(2a)(kairė). Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu; pavieniai intraduktaliniai mikrokalcifikatai.  2.(2b)(kairė). Krūties audinyje - fibrozės zonos su fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu su apokrininės metaplazijos židiniais. Fokaliai dilatuoti latakėliai su kribriforminiais atipinių ląstelių (su nedidelio laipsnio branduolių polimorfizmu) proliferatais (DCIS). Dilatuoti latakai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS).   3.(3)(kairė) Du(2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4(N5a)(dešinė) Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  5(N5b)(dešinė) Krūties audinyje - fibrozės zonos su fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu su apokrininės metaplazijos, paprastos intraduktalinės hiperplazijos židiniais; fokaliai dilatuoti latakėliai su fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu. Fokaliai dilatuoti latakėliai su kribriforminiais atipinių ląstelių (su nedidelio laipsnio branduolių polimorfizmu) proliferatais (DCIS). Dilatuoti latakai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS).  6(N6)(dešinė) Trys(3) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  7(N7)(pap. kraštas, kairė) Riebalinis audinys su fibrozinėmis septomis.  8(N1)(kairė) Krūties audinyje - du naviko židiniai (16,7mm ir 10mm), formuojami duktalinių (~60% naviko), solidinių/lizdinių struktūrų, difuziškai, grandinėlėmis plintančių (~5% naviko) ląstelių, eozinofiliška citoplazma, nežymiai polimorfiškais, hiperchromiškais branduoliais; navike iki 7 mitozių/10 DPRL. Aplinkiniame krūties audinyje - fibrozės zonos su fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu su apokrininės metaplazijos židiniais; intraduktalinių mikrokalcifikatų židiniai; dilatuoti latakėliai su fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu. Fokaliai dilatuoti latakėliai su kribriforminiais, mikropapiliniais atipinių ląstelių (su nedidelio laipsnio branduolių polimorfizmu) proliferatais (DCIS). Dilatuoti latakai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS).  9(N4)(dešinė). Krūties audinyje - dauginiai naviko židiniai (nuo 0,6mm iki 14mm), formuojami kribriforminių, duktalinių (~90% naviko), solidinių/lizdinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, nežymiai, vietomis vidutiniškai polimorfiškais, hiperchromiškais branduoliais; navike iki 3 mitozių/10 DPRL. Aplinkiniame krūties audinyje - fibrozės zonos su fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu su apokrininės metaplazijos, paprastos intraduktalinės hiperplazijos židiniais; fokaliai dilatuoti latakėliai su fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu. Fokaliai dilatuoti latakėliai su solidiniais, kribriforminiais atipinių ląstelių (su nedidelio ir vidutinio laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS). Dilatuoti latakai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS).  10(N8)(pap. kraštas, dešinė) Riebalinis audinys su fibrozinėmis septomis.. 5. CK5+ mioepitelinės ląstelės.   DCIS: E-Cadherin(+++), membr. r-ja, 100%; LCIS: E-Cadherin(-).  8. Duktalinės karcinomos komponentas:  E-Cadherin(+++), membr. r-ja, 100%;  Lobulinės karcinomos komponentas:  E-Cadherin(+/+++), citopl. r-ja, 90%;
answer:  0.

 67%|██████▋   | 441/661 [12:20<06:53,  1.88s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 4 biopsiniai stulpeliai.. 4 biopsiniai stulpeliai: I - 10 mm; II - 10 mm; III - 10 mm; IV - 7 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja netaisyklingi šakoti solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozės pavienės.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 10%.
answer:  0

 67%|██████▋   | 442/661 [12:21<06:30,  1.78s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 9 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) adenokarcinoma (galimai duktalinė, su neuroendokrininės diferencijacijos požymiais, ar invazyvi solidinė papilinė karcinoma).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.. Solidines, trabekulines naviko struktūras formuoja gan smulkios ląstelės su negausia ar kiek gausesne tamsoka citoplazma, smulkiais ar vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 5 / 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  Proliferacinis aktyvumas (Ki67
answer:  5%.

 67%|██████▋   | 443/661 [12:23<06:27,  1.78s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštas, ekstra.  2. pjūvio kraštas, ekstra.   3. du sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 9,5x4,5x5,5 cm su odos lopu 2,5x1,3 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje neaiškių ribų, pilkšvas židinys 10x8x8 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 2 cm.. 1(Extra). Krūties audinio fibrozė.  2(Extra). Krūties audinio fibrozė.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(6 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas (R0).  Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 1% naviko ląstelių.  HER2 imuninė reakcija: neigiama (1+).  Ki67: 5%.   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).. 1(Extra). Krūties audinyje, ryškiai fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, ryškiai fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu; negausūs smulkūs kalcifikatai.  3(Extra). 2 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija, smulkiais pigmentuotų makrofagų židiniais bei sinusų histiocitoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 6 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių smulkių, besiliejančių tubulinių, lizdinių ir trabekulinių struktūrų iš ląstelių saikinga švelniai eozinofiliška ar blyškia citoplazma, smulkiais ir vidutinio kalibro, ovaliais/apvaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 1/10 DPRL. Pavieniai smulkūs kalcifikatai navike. Šalia naviko - negausūs dilatuoti kanaliukai su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais.. 1. Navikas (19 blokas):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 1% naviko ląstelių.  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląst
answer:  2.

 67%|██████▋   | 444/661 [12:25<06:24,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.(1a)- viršutinis kraštas, skubu  2.(1b)- apatinis kraštas, skubu  3.(2). deš. pažasties sarginiai limfmazgiai, skubu  4.(3). deš. krūties sektorius, planinis  5.(4). pap A kraštas-planas. 4.(3).  Krūties sektorius 10x6x5 cm su odos lopu 6x2,5 cm,  žymėtas viela. Vielos projekcijoje, pjūvyje navikas 1,6x1,6x1,5 cm, nuo artimiausio rezekcijos krašto nutolęs 0,8 cm (mėlyna), nuo odos – 2 cm. Histologiniam ištyrimui navikas sudėtas visas.  5(4). Riebalinio audinio fragmentas 1,5x1x0,5 cm. v/m. 1(1a). Krūties lobulinė karcinoma in situ (LCIS).  2(1b). Krūties audinys.  3(2). Krūties duktalinės karcinomos mikrometastazė viename limfmazgyje (1/2 l/m, 1 mm skersmens).  4(3). Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 14 mm), pN1mi(sn)(1/2 l/m, 1mm), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties lobulinė karcinoma in situ (LCIS).   5(4). Krūties audinys.. 1(1a). Fibrozuotame krūties audinyje gausūs nežymiai dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.  2(1b). Riebalinio audinio fragmentas su smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(2). Po fiksacijos: viename limfmazgyje iš dviejų žemiau aprašyto naviko mikrometastazės iki 1 mm skersmens.  4(3). Krūties audinyje - navikas (14 mm mikroskopiškai), suformuotas tubulinių ir pavienių kribriforminių struktūrų iš vidutinio kalibro eozinofiline citoplazma ląstelių, nežymiai polimorfiškais, smulkiai grūdėtu chromatinu branduoliais; mitozių 7/10 DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Šalia naviko kelios dilatuotos lobulės užpildytos solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta nežymiai dilatuoti kanaliukai kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.   5(4). Riebalinio audinio fragmentas su smulkiais kanaliukais, klotais dvisluoksniu epiteliu. Ryškūs koaguliaciniai/traiškymo artefaktai.. Blokas 12:  Blokas 13:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 67%|██████▋   | 445/661 [12:26<06:03,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Fragmentuotas biopsinis stulpelis 12 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 18/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 60%.
answer:  3

 67%|██████▋   | 446/661 [12:28<06:20,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu   3(2) deš. pažasties sarginiai limfmazgiai, skubu  4(3). deš. krūties sektorius, planinis. 4. Krūties sektorius 9x6x5 cm su odos lopu 6x2 cm, žymėtas viela. Vielos projekcijoje - gelsvas, neaiškių ribų navikas 1x0,8x0,8 cm, nuo giliojo rezekcijos krašto nutolęs 1,1 cm, nuo odos - 4 cm. 0,6 cm nuo naviko fibrozės zona 1,2x0,9 cm. Navikas sudėtas visas.. 1(N1a, ekstra/Kraštai). Krūties audinys.  2(N1b, ekstra/Kraštai). Krūties audinys.  3(N2, ekstra/Sarginiai l/m). Lobulinės karcinomos metastazė 1/2 limfmazgių (3 mm).  4(N3, D. krūties sektorius). A) Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(11 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinė invazija neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).  B) Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1a(3,3 mm) N(sn)1a(mts 1/2 l/m: 3 mm), LVI-0(limfovaskulinė invazija neidentifikuota). Radikalus pašalinimas. Lobulinė karcinoma in situ (LCIS).  Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 5% naviko ląstelių.  HER2 imuninė reakcija: neigiama (1+).  Ki67: 2%.. 1(N1a, ekstra/Kraštai). Fibrozuotas krūties audinys su negausiais smulkiais, kanaliukais, klotais dvisluoksniu epiteliu.  2(N1b, ekstra/Kraštai). Fibrozuotas krūties audinys su pavieniais smulkiais, kanaliukais, klotais dvisluoksniu epiteliu.  3(N2, ekstra/sarginiai l/m). 2 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze. Ne extra pjūviuose (kitose pusėse), 1/2 limfmazgių - aukščiau aprašyto naviko (invazyvios lobulinės karcinomos) metastazė (3 mm).  4(N3, D. krūties sektorius). Krūties audinyje - fibrozinėje stromoje, infiltratyviu frontu plintantys du atskirų navikų židiniai: I  - 11 mm dydžio, II - 3,3 mm.  I navikas suformuotas trabekulinių struktūrų, smulkesnių grandinėlių bei tubulių (~40%). Naviko ląstelės su vidutinio gausumo, šviesiai eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar ovoidiškais, neryškiai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių navike iki 2/10 DPRL. Aplink naviko židinius dėstosi kanaliukai, su solidiniais ir negausiais kribriforminiais analogiškų navikui ląstelių proliferatais (DCIS).   II naviką sudaro fibrozuotoje stromoje infiltratyviai plintančios trabekulinės struktūros, grandinėlėmis, smulkiomis grupelėmis ar pabirai besidėstančios ląstelės negausia švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais/apvaliais, neryškiai polimorfiškais, dalis su nukleole branduoliais. Mitozių mažiau 1/10 DPRL. Šalia kiek dilatuoti kanaliukai, užpildyti monomorfiškomis ląstelėmis (LCIS).. 4. Limfmazgis (6 blokas): lobulinės karcinomos metastazė: PanCK(+); E-Cadherin(-).  15 blokas: invazyvi duktalinė karcinoma E-Cadherin(+++)(membr. r-ja), 100%.  16 blokas: invazyvi duktalinė karcinoma E-Cadherin(+++)(membr. r-ja), 100%; p120 catenin(+++)(
answer:  100%

 68%|██████▊   | 447/661 [12:30<06:16,  1.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 1 - pjūvio kraštai - extra;  2. 2 - pjūvio kraštai - extra;  3. Sarginiai l/m - extra;  4. Sektorius - planinis tyrimas.. 4. Krūties sektorius 14,5x5x6,5 cm su oda 13x2 cm. Krūties audinyje, kvadrante - pilkšvas, standus, neaiškių ribų navikas 13x10x8 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 1,3 cm.. 1(ekstra). Pjūvio kraštai. Krūties fibrocistiniai pokyčiai. Naviko plitimo nėra.     2(ekstra). Pjūvio kraštai. Krūties fibrocistiniai pokyčiai. Naviko plitimo nėra.    3(ekstra). Sarginiai l/m. Duktalinės karcinomos metastazė 1-me/3 limfmazgių, iki 2 mm skersmens.      4. Krūties sektorius.  Krūties invazyvi vidutiniškai diferencijuota (G1, 5 b. pgl Nottingham sist.) duktalinė karcinoma,   pT1c(13 mm)   pN(sn)1mi(1/3 l/m mts iki 2 mm)   pLVI-0 (limfovaskulinės invazijos nestebima)   pR0(radikalus pašalinimas).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama (0).  Ki67: proliferacinis indeksas 5%.. 1(ekstra: pjūvio kraštai). Krūties audinys su fibrozės zonomis ir smulkiais, dalis cistiškai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.     2(ekstra: pjūvio kraštai) . Krūties audinys su fibrozės zonomis ir smulkiais, dalis cistiškai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.    3(ekstra: sarginiai limfmazgiai). 1-me/3 limfmazgių naviko židinys iki 2 mm skersmens.    4. Krūties sektorius. Krūties audinyje - desmoplastiškoje stromoje plintantis navikas, suformuotas tubulinių, solidinių ir negausių grandinėlių bei trabekulinių struktūrų. Naviko ląstelės su negausia, tamsia eozinofiliška citoplazma, vidutinio kalibro, apvaliais, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių navike iki 2/10 DPRL.. Blokas 19:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, <10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 5% naviko ląstelių.  Progesterono receptoriai: reakcijo
answer:  0.

 68%|██████▊   | 448/661 [12:31<06:11,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2). deš. pažasties sarginiai limfmazgiai, skubu  4(3). deš. krūties sektorius, planinis. 4(3). Krūties sektorius 4,5x3,5x2 cm. Pjūvyje balkšvas, standus, aiškių ribų navikas 0,9x0,7x0,8 mm (sudėtas visas), nuo artimiausio rezekcijos (dažytas mėlyna) krašto nutolęs 0,3 cm.. 1(1a). Riebalinis, fibrozinis audinys.  2(1b). Krūties fibrocistiniai pokyčiai.  3(2). Reaktyvi limfadenopatija (2 l/m).  4(3). Krūties invazyvi duktalinė adenokarcinoma (gerai diferencijuota / G1 / 5 balai pagal Nottingham), TNM (Nr.1-Nr.4): pT1b(0,9 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 3%.. 1(1a). Riebalinis, fibrozinis audinys.  2(1b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai minimaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(2). Sinusų histiocitozė dviejuose (2) limfmazgiuose.  4(3). Krūties audinyje - navikas (tubulines (80%), negausias smulkias trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne švelniai eozinofiline citoplazma, smulkiais ar kiek stambesnio kalibro kiek netaisyklingais, dalis su smulkia nukleole branduoliais; mitozių navike iki 1 / 10 DPRL.. 4(3). Navikas (10 blokas): Her2 silpna trūkinėjanti membraninė r-ja 10% naviko ląstelių.
answer:  0

 68%|██████▊   | 449/661 [12:33<05:56,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas kair. krūties darinys, paimti 3 biopsiniai stulpeliai medžiagos histologiniam ištyrimui. 3 biopsiniai stulpeliai: I - 12 mm; II - 16 mm; III - 17 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 10%.. Krūties audinį infiltruoja duktalinės struktūros, netaisyklingi kribroziniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas visos membranos nusidažymas 20% naviko ląstelių.  Ki67+ 10%
answer:  1a

 68%|██████▊   | 450/661 [12:35<05:46,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm.. Krūties invazyvi duktalinė adenokarcinoma (tikėtina vidutiniškai diferencijuota / G2 / 6 balai pagal Nottingham sistemą), plitimas 1/1 biopsiniame stulpelyje, iki 6,8 mm ilgyje.     Estrogenų receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: 15%.. Krūties audinyje (1 biopsiniame stulpelyje, iki 6,8 mm ilgyje) - fibrozinėje stromoje plintančios ilfiltratyvios trabekulinės, kribriforminės, tubulinės (~10 %) naviko struktūros su negausiais kalcifikatais; naviko ląstelės su negausia eozinofiliška citoplazma, vidutinio kalibro, nereguliaraus kontūro, hiperchromiškais ir vezikuolizuotais, kiek polimorfiškais, be aiškių nukleolių branduoliais; mitozių navike 1 / 10 DPRL.. Navikas (Blokas 1):  Estrogenų receptoriai: stipri (+++) reakcija, 95% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari/trūkinėjanti reakcija, 20% naviko ląs
answer:  1b

 68%|██████▊   | 451/661 [12:36<05:37,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 3 biopsiniai stulpeliai.. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 11 mm; III - 9 mm.. Žemo piktybiškumo metaplastinė (ištęstų ląstelių) krūties karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 1-2%.. Navikinio audinio bioptatai (krūties audinio elementų nerasta): pluoštai ištęstų ląstelių gausia eozinofiline citoplazma, ovaliais, vidutiniškai ar ryškiai polimorfiškais branduoliai; mitozių iki 4/10 DPRL.  Naviko ląstelės Ck5+, p63+, PanCk+.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 1-2%.  p63+, Ck5
answer:  1.

 68%|██████▊   | 452/661 [12:38<05:28,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 6 bioptatai 22 mm 12 G adata, paimti iš ~12 mm mikrokalcinatų plotelio, penkiuose mikrokalcinatai.. 6 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 8 mm; IV - 12 mm; V - 15 mm; VI - 10 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 15%.. Krūties audinį infiltruoja nedideli kribroziniai/solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 80% naviko ląstelių.
answer:  1 �

 69%|██████▊   | 453/661 [12:39<05:40,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N1): pašalintas markiruotas dešinės krūties plotas - planinis tyrimas. 3. Krūties sektorius 5,5x4,5x3 cm, žymėtas viela, rezekcijos kraštas dažytas mėlynu tušu. Vielos projekcijoje, pjūvyje balkšva, standi, fibrozės zona 25x20x30 mm, nuo giliojo rezekcijos krašto nutolusi 0,1 cm.. 1(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  2(Extra). Krūties audinys.  3. Krūties invazyvi blogai diferencijuota (G3; 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(5,5 mm) NX(limfmazgiai nešalinti), LVI-0(limfovaskulinės invazijos neidentifikuota).    Imunofenotipas:   Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2 imuninė reakcija: teigiama (3+).  Ki67: 30%.  Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS)(solidinė, kribriforminė, komedo) (30 mm židinys makro).  Invazyvi karcinoma pašalinta radikaliai, DCIS struktūros siekia sektoriaus rezekcijos kraštą.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu, fokaliai hiperplastišku epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3. Krūties audinyje - zona su fibrozinėje stromoje besidėstančių stambių ir vidutinio kalibro kanaliukų su solidiniais ir kribriforminiais intraduktaliniais proliferatais, suformuotais ląstelių eozinofiliška citoplazma, stambiais, polimorfiškais, su nukleole branduoliais; fokaliai komedo nekrozės centruose. Šalia židininė MMN ir makrofagų infiltracija su cholesterolio kristalais ir makrofagais bei daugiabranduolėmis gigantinėmis ląstelėmis aplink. Viename bloke, šalia DCIS plinta lizdinės ir trabekulinės naviko struktūros (be CK5+ mioepitelinio sluoksnio), suformuotos ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Naviko dydis 5,5 mm. Mitozių iki 11/10 DPRL.. 1. 1 blokas: kanaliukai su CK5+ mioepiteliniu sluoksniu, luminalinė populiacija mišri.  Navikas (15 blokas):  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2 imuninė reakcija: s
answer:  0.

 69%|██████▊   | 454/661 [12:41<05:29,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.  N2a- skubus - kraštai  2. N2b kraštai - skubus tyrimas - be naviko  3.N3: kairės pažasties sarginis limfmazgis - skubus tyrimas 2l/m be naviko  4. N1: pašalintas kairės krūties kvadrantas  - planinis tyrimas. 4. Krūties sektorius 5x5x2 cm, su odos lopu 4x1,5 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje balkšvas, aiškių ribų 9x6x mm navikas, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos - 3 cm.. N1: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (9mm).  N2ab: Audiniai be naviko.  N3: Limfmazgiai (2 l/m) be naviko; pN0(sn).. N1: Krūties audinyje 9mm navikas: smulkios duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.  N2ab: Audiniai be naviko.  N3: Limfmazgiai (2 l/m) be naviko.. nan
answer:  0.

 69%|██████▉   | 455/661 [12:43<05:38,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštai - be naviko - skubus tyrimas   2(N2b). kraštai - be naviko - skubus tyrimas   3(N3). sarginis limfmazgis - 2 l/m be naviko - skubus tyrimas  4(N1). pašalintas dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 5x3,5x3 cm su odos lopu 4,5x2,3 cm. Vielos projekcijoje, pjūvyje - balkšvas, standus, neaiškių ribų navikas 17x15x10 mm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos – 1 cm. Šalia naviko - fibrozės zona 3x2,5x1 cm.. 1. Krūties adenozė.   2. Krūties adenozė.   3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma,   pT1a (17 mm) pN0(sn) (0/2 l/m); LVI2 (limfovaskulinė naviko invazija smulkiose limfagyslėse/ kraujagyslėse).   Krūties aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2-DIN3; kribriforminė, solidinė).. 1. Krūties audinys fibrozuota stroma, su gausiais organoidiniais smulkių kanaliukų proliferatais.   2. Krūties audinys fibrozuota stroma, su gausiais organoidiniais smulkių kanaliukų proliferatais.   3. Limfmazgiai (2) kiek tušuota architektūra, makrofagų reakcija parakortekse, sinusų histiocitoze.   4. Krūties audinyje - navikas, formuojamas infiltratyviai plintančių, glaudžiai besidėstančių grandinėlių, trabekulinių struktūrų, smulkių grupių, sudarytų iš nedidelių-vidutinio dydžio poligonalinių ląstelių šviesiai eozinofiliška citoplazma, vidutiniškai ar ryškiai polimorfiškais ovaliais ar skeltais branduoliais su vezikulizuotu chromatinu, ryškiomis centrinėmis nukleolėmis. Navike iki 5 mitozių/ 10 DPRL.   Limfovaskulinė naviko invazija smulkiose kraujagyslėse/ limfagyslėse.   Naviko periferijoje - įvairaus dydžio latakai ir lobulių kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais, sudarytais iš vidutinio dydžio ir stambių kampuotų ląstelių gausia eozinofiliška citoplazma, vidutiniškai ar ryškiai polimorfiškais branduoliais su ryškiomis nukleolėmis.. 4. Navikas (11 blokas):   e-cadherin(+++)(membr. r-ja) 100%.
answer:  1.

 69%|██████▉   | 456/661 [12:44<05:29,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 6 stulpeliai. 6 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 7 mm; III - 7 mm; IV - 4 mm; V - 4 mm; VI - 3 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcja neigiama, branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 35%.. Krūties audinį infiltruoja negausios duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcja neigiama, branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 10% naviko lą
answer:  3b

 69%|██████▉   | 457/661 [12:46<05:34,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - N2a kraštai - skubus - be naviko  2 - N2b kraštai - skubus - be naviko  3 - N3 kairės pažasties limfmazgiai - skubus tyrimas -  2l/m be naviko  4(1) - pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 12x4,5x5 cm su oda 10,5x3 cm. Krūties audinyje, pilkšvas, standus, aiškių ribų navikas 22x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,6 cm.. 1(ekstra). Krūties audinys.  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (4 l/m).   4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham sistemą) duktalinė karcinoma, pT2 (22 mm navikas) N0(sn)(4 l/m) LVI0 (limfovaskulinė invazija neidentifikuota). Radikalus pašalinimas. Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 komedo tipas).  Stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).     Naviko imunotipas nustatytas biopsijoje:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 4 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.  4. Krūties audinyje - fibrozinėje stromoje plintantis navikas, suformuotas lizdų, trabekulių, grandinėlių, pavienių tubulių (<10 %) ir pabirų ląstelių. Naviko ląstelės su vidutinio gausumo, šviesiai eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių navike iki 19/10DPRL.  Šalia naviko dilatuoti kanaliukai su intraduktaliniais solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.  Aplinkiniame krūties audinyje dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. nan
answer:  1.

 69%|██████▉   | 458/661 [12:47<05:23,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas dešinės krūties darinys - planinis tyrimas  2 ėminio aprašas: N2a ir N2b kraštai - planinis tyrimas. 1. Krūties sektorius 8x6x4 cm su oda 7x2 cm. Pjūvyje pilkšvas, su smulkiomis hemoragijomis mucininis navikas 2,1x1,9x2,1 cm, nuo giliojo rezekcijos krašto (dažytas mėlynu tušu) nutolęs mažiau 0,1 cm, nuo odos - 1,5 cm.  2. Riebalinio audinio fragmentas 2,5x1x0,5 cm. v/m  3. Riebalinio audinio fragmentas 2,5x2x0,8 cm. v/m. N1: Mucininė krūties karcinoma (G1, 5 balai pgl Nottingham); pT2(21mm).  N2ab: Krūties audinys be patologijos.. N1: Krūties audinyje 21mm navikas: mucininėje stromoje netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.  N2ab: Krūties audinys be patologijos.. nan
answer:  1.

 69%|██████▉   | 459/661 [12:49<05:13,  1.55s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 5 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko
answer:  1a

 70%|██████▉   | 460/661 [12:50<05:07,  1.53s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67+ 12%, vietomis iki 20%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 10% naviko ląstelių.  Ki67+ 1
answer:  1b

 70%|██████▉   | 461/661 [12:52<05:04,  1.52s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 6 mm; II - 4 mm; III - 7 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja duktalinės struktūros, smulkūs solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 30% naviko ląstel
answer:  1b

 70%|██████▉   | 462/661 [12:54<05:23,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - sarginiai l/m - ekstra  2 - deš. krūties liauka - planiniam tyrimui   3 - papildomas. 2. Krūtis 346 gramų svorio, 17x14,5x3,5 cm, su odos lopu 8,5x1,5 cm, su speneliu (liauka persiūta ilgu siūlu lateraliai, trumpu - viršus). Krūties audinyje, apatiniame lateraliniame kvadrante - balkšvas, standus, kiek neaiškių ribų navikas 28x11x23 mm, nuo odos nutolęs 1,5 cm, nuo giliojo rezekcijos krašto - 0,4 cm, nuo poodinio rezekcijos krašto - 1 cm. 1,2 cm nuo naviko, I standi zona 0,9x0,8x0,7 cm, nuo odos nutolusi 2 cm, nuo giliojo rezekcijos krašto - 0,5 cm. Nuo naviko 1,7 cm nutolusi II standi zona 0,3x0,2x0,2, nuo odos nutolusi 1 cm, nuo giliojo - 1,7 cm.   3. Riebalinio audinio fragmentas 4x3,4x1,2 cm.. 1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (5 l/m).   2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT2 (navikas 28 mm) N0(sn) (0/5 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).   Kalcifikatai.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis, papilinis ir komedo tipai).   Rezekcijos kraštai be naviko.   3. Fibrozuotas krūties-riebalinis audinys; be naviko.. 1(ekstra). "Sarginiai limfmazgiai": penki (5) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.    2. SPENELIS: su židinine plaukų folikulus supančia MMN infiltracija, spindžiuose Demodex spp. fragmentai.   NAVIKAS (vienas susiliejantis mazguotas židinys su gausiais in situ komponento intarpais, didžiausias matmuo - 28 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės,  kribriforminės, gausesnės trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 3/10 DPRL. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija, hemi Pavieniai mikrokalcifikatai.  APLINKA: multifokaliai krūties audinyje ir šalia naviko - kribriforminiai, papiliniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   KRŪTIES REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.   3. Fibrozuotas, vaskuliarizuotas brandžių lipocitų suformuotas fragmentas su nerviniais kamienais ir fokaliai įsiterpiančiais smulkiais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.. 2. Navikas (blokas 17):  HER2: silpna (+) necirkuliari reakcija, 50%  naviko ląstelių membranoje.  E-Cadherin(+++)(membr.r-ja)100%.
answer:  3b

 70%|███████   | 463/661 [12:55<05:22,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas kairės krūties darinys, paimti 4 biopsiniai stulpeliai medžiagos histologiniam ištyrimui.   2 ėminio aprašas: punktuotas kair. pažasties pakitusios struktūros l/m, paimti 4 biopsiniai stulpeliai medžiagos histologiniam ištyrimui.. 1. 4 fragmentuoti biopsiniai stulpeliai: I - 16 mm; II - 8 mm; III - 11 mm; IV - 8 mm.  2. 4 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 8 mm; III - 8 mm; IV - 12 mm.. N1: Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: silpnas ar vidutinis branduolių nusidažymas 10% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%, vietomis iki 40%.  N2: Lobulinės karcinomos metastazė limfmazgyje.. N1: Krūties audinį infiltruoja nedideli solidiniai kompleksai, juostos ir trabekulės iš ryškiai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.  N2: Limfmazgio bioptatai su aukščiau aprašyto naviko židiniais.. Navikas  Estrogenų receptoriai: silpnas ar vidutinis branduolių nusidažymas 10% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.
answer:  1

 70%|███████   | 464/661 [12:57<05:17,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 bioptatas iš l/m  dešinėje   pažastyje   2 but. 1 biopsinis stulpelis iš dešinės krūties darinio BI-RADS 5. 1. Biopsinis stulpelis 11 mm ilgio.  2. Biopsinis stulpelis 12 mm ilgio.. 1. Limfmazgio bioptatas be naviko plitimo.   2. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 4%.. 1. Limfmazgio bioptatas be naviko plitimo.   2. Krūties audinį infiltruoja duktalinės struktūros (50%), netaisyklingi kribroziniai kompleksai ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. 2. Blokas 2:  Estrogenų receptoriai: stipri (+++) reakcija, 95% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląstelių membranoje.
answer:  0

 70%|███████   | 465/661 [12:58<05:11,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 10 mm; II - 11 mm.. Vyraujantis komponentas vidutinio laipsnio intraduktalinė karcinoma (DCIS/DIN2; kribriforminė).    Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinyje plačios zonos su šakotais dilatuotais kanaliukais su intraduktaliniais kribroziniais neryškiai polimorfiškų ląstelių proliferatais ir negausūs invazinio augimo židiniai: netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 40% naviko ląstel
answer:  1b

 70%|███████   | 466/661 [13:00<05:27,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Deš. pažasties sarginiai limfmazgiai, skubu - extra.  2. Deš. krūtis, planinis.. 2. Krūtis 495 gramų svorio, 19,5x14x5 cm. Centrinė krūties dalis fibrozuota 8x7 cm plote. Fibrozuotos zonos kraštuose:   - I rusvas, standus židinys 32x25x11 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,5 cm;   - II neaiškių ribų heterogeniškos išvaizdos židinys 35x30x30 mm, nusitęsiantis į spenelį, nuo giliojo rezekcijos krašto nutolęs 1,3 cm.. PAPILDYTAS ATSAKYMAS HER2 FISH TYRIMU (HER2 geno amplifikacija nenustatyta):   1(ekstra). "Deš. pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (4 l/m).   2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c(m) (naviko židiniai: I - 11 mm; II - 8 mm; III - 4 mm) N0(sn) (0/4 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, papilinis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė, apokrininė metaplazija).   DCIS struktūros nuo giliojo rezekcijos krašto nutolusios - 1,45 mm.. 1(ekstra). "Deš. pažasties sarginiai limfmazgiai": keturi (4) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2. SPENELIS: normalios histologinės struktūros.   NAVIKAS (naviko židiniai: I - 11 mm; II - 8 mm; III - 4 mm; supami ryškios fibrozės, fibrocistinių pokyčių ir in situ komponento): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės, kribriforminės, trabekulinės, nedidelės lizdinės ir solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo tamsoka citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 15/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Pavieniai mikrokalcifikatai. Keletas zonų su ryškesne fibroze ir "nubyrančiomis" naviko struktūromis (g.b. ankstesnių biopsijų zonos).   APLINKA: šalia naviko - solidiniai, kribriforminiai, papiliniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su papiliniais intraduktaliniais proliferatais, ryškesne epitelio atipija, apokrinės metaplazijos zonomis, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu.   GILUSIS REZEKCIJOS KRAŠTAS: in situ komponentas nutolęs 1,45 mm.. 2. Navikas (blokas 25):  HER2: vidutinė (++) necirkuliari reakcija, 10% naviko ląstelių membranoje.
answer:  0

 71%|███████   | 467/661 [13:02<05:14,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 freagmentuoti biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 8 mm.. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) mucininė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 40% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 3%.. Kribrozines naviko struktūras (išsidėsčiusias gausiuose ekstraląsteliniuose mucinuose) formuoja ląstelės su saikinga tamsoka citoplazma, vidutinio kalibro saikingai polimorfiškais, dalis su nukleole branduoliais; mitozių navike nestebima.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 3% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 40% naviko
answer:  3 fre

 71%|███████   | 468/661 [13:03<05:17,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.  4. sektorius, planinis.. 4. Krūties sektorius 14x4,5x5 cm su oda 12,5x1,6 cm, žymėtas 2 vielomis, atstumas tarp vielų 5 cm. Odoje pilkšvas smulkiai gruoblėtas darinys 1,6x1,4x0,3 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm. Vielų projekcijoje:  - I vielos projekcijoje - pilkšvas, standus navikas 22x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2 cm.  - II vielos projekcijoje - krūties audinys fibrozuotas 2,5x2,2 cm plote, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,2 cm.. 1. pjūvio kraštai: krūties audinys be patologinių pokyčių.    2. pjūvio kraštai: krūties audinys su intraduktaline hiperplazija.    3. sarginiai l/m: limfmazgis (1) be karcinomos ląstelių.; pN(sn)0.    4. sektorius.   Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą)   duktalinė karcinoma su mucininės diferenciacijos požymiais;   pT1c(<20mm) pLVI-0 pR0.  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 1% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.. 1. pjūvio kraštai: krūties audinys be patologinių pokyčių.  2. pjūvio kraštai: krūties audinys su intraduktaline hiperplazija.  3. sarginiai l/m: limfmazgis (1) be karcinomos ląstelių.   4. sektorius. Krūties audinyje - darinio (mikroskopiškai 19 mm) fibrozinės stromos su gausiais AB+ mucinų židiniais apsuptos kribriforminės struktūros ir solidiniai kompleksai, suformuoti ląstelių vidutinio gausumo, tamsia eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar ovoidiškais, hiperchromiškais, vidutiniškai polimorfiškais branduoliais su pavienėmis smulkiomis nukleolėmis. Mitozių navike iki 6/10DPRL. Inravaskulinio plitimo nestebima.. nan
answer:  1a

 71%|███████   | 469/661 [13:05<05:09,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 biopsinis stulpelis  iš dešinės pažasties l/m  2 but. 2 biopsiniai stulpeliai  iš dešinės krūties darinio. 1. Biopsinis stulpelis 7 mm.   2. 2 biopsiniai stulpeliai: I - 12 mm; II - 10 mm.. N1: Limfmazgio bioptatas su lobulinės karcinomos metastaze.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%, vietomis iki 40%.. N1: Limfmazgio bioptatas su žemiau aprašyto naviko židiniais.  N2: Krūties audinį infiltruoja nedideli solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 30
answer:  3b

 71%|███████   | 470/661 [13:07<05:11,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, policikliniais kontūrais be UG fiksuojamos kraujotakos, ~12×5 mm dydžio darinys kairiojoje krūtyje ties 1 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 7 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 4,5 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se/3 krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.    Krūties fibrocistiniai pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).   Kalcifikatai.. Krūties audinį 2-se/3 bioptatuose infiltruoja iki 4,5 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais negausioje citoplazmoje;   - mitozių nestebima.  Intravaskulinės invazijos nėra.    2-se stulpeliuose - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), smulkūs kalcifikatai spindžiuose.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 25%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 5% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  100%

 71%|███████▏  | 471/661 [13:08<05:09,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 biopsinis stulpelis iš kairės pažasties  I lygio l/m  2 but. 1 biopsinis stulpelis iš kairės krūties BI-RADS 5 darinio  3 but. 1 biopsinis stulpelis iš dešinės pažasties I lygio l/m. 1. Biopsinis stulpelis 10 mm ilgio.  2. Biopsinis stulpelis 14 mm ilgio.  3. Fragmentuotas biopsinis stulpelis 8 mm ilgio.. N1: Limfmazgio bioptatas su duktalinės karcinomos metastaze.  N2: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%.  N3: Limfmazgio bioptatas be naviko židinių.. N1: Limfmazgio bioptatas su žemiau aprašyto naviko židiniais.  N2: Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.  N3: Limfmazgio bioptatas be naviko židinių.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 30% naviko ląstel
answer:  1.

 71%|███████▏  | 472/661 [13:10<04:59,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Paimti 3 biopsiniai stulpeliai.. 3 biopsiniai stulpeliai: I - 14 mm; II - 12 mm; III - 17 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 15%.. Krūties audinį infiltruoja negausios duktalinės struktūros, nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 100% naviko ląstelių.  Ki67+ 15
answer:  3b

 72%|███████▏  | 473/661 [13:11<04:55,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 5 stulpeliai. 5 fragmentuoti biopsiniai stulpeliai: I - 17 mm; II - 17 mm; III - 22 mm; IV - 12 mm; V - 10 mm.. Krūties invazyvi duktalinė karcinoma, 0,4 mm židinys (1/5 bioptatų). Žr. pastabą.   Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, solidinis tipas), (2/5 bioptatų).     Naviko imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 20%.. Bioptate (1/5) - krūties audinyje, fibrozinėje stromoje smulkus naviko židinys, suformuotas smulkiomis grupėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais. 2/5 bioptatų dilatuoti latakai su intraduktaliniais solidiniais proliferatais negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: neigiama reakcija.  HER2: vidutinis dalies membranos nusidažymas 40% naviko ląstelių.  Ki67 proliferacinis aktyvumas ---- %.  CK14/p63(-);
answer:  0.

 72%|███████▏  | 474/661 [13:13<05:12,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - be naviko.  2(2b). Kraštai - be naviko.  3(1). Pašalintas sektorius - planinis patologinis tyrimas N1 - skubus rentgeninis tyrimas- navikas pašalintas.. 3(1). Krūties sektorius 14x7x2 cm su odos fragmentu 4,5x1 cm, žymėtas viela, vienoje pusėje - dviem trumpais siūlais, kitoje pusėje - vienu trumpu ir vienu ilgu siūlais. Vielos projekcijoje, krūties audinio pjūvyje - balkšvas standus, neaiškių ribų navikas 1,3x1x0,8 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,5 cm, nuo odos – 6 cm. Šalia naviko fibrozės zona 3,5x2,5x2 cm.. 1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija); kalcifikatai; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.     3(1). Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 9,6 mm),   LVI-0 (definityvi limfovaskulinė invazija neidentifikuota). Kalcifikatai.    Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: solidinis, kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).   DCIS komponentas nuo sektoriaus rezekcijos krašto nutolęs 0,72 mm.. 1(2a, ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su apokrinės metaplazijos zonomis; pavieniai smulkūs kalcifikatai; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas, vaskuliarizuotas brandžių lipocitų suformuotas fragmentas; be naviko.   3(1). NAVIKAS (didžiausias išmatuojamas invazyvaus naviko matmuo - 9,6 mm; tarp naviko struktūrų ir aplink jį gausūs in situ kompleksai, ryški fibrozė ir fibrocistiniai pokyčiai; bendras pokyčių židinio dydis ~18 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės ir kribriforminės naviko struktūros, suformuotos saikingai polimorfiškų ląstelių, negausia šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais; mitozės retos, sunkiai vizualizuojamos. Pavieniai mikrokalcifikatai.   APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   SEKTORIAUS REZEKCIJOS KRAŠTAS: intraduktaliniai naviko ląstelių kompleksai nuo artimiausio rezekcijos krašto nutolę - 0,72 mm.. 3(1). Navikas (blokas 8):  HER2: silpna (+) necirkuliari reakcija, 10% naviko ląstelių membranoje.
answer:  3(

 72%|███████▏  | 475/661 [13:15<05:01,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 90% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.. Bioptate - desmoplastiškoje stromoje, infiltratyvios naviko struktūros, suformuotos solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška tamsia ar ryškia citoplazma, polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais; ryškiomis nukleolėmis mitozių 4/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 90%.  HER2: nusidažiusių  aviko ląstelių nėra.  Ki67 proliferacinis aktyvumas 10%.  E-cadherin(+++) membr. r-ja 100%.  CK14 foninė citopl. r-ja.
answer:  1a

 72%|███████▏  | 476/661 [13:16<05:04,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. (2a) kraštai -extra  2. (2b) kraštai - extra.  3. (3) sarginiasi limfmazgiai -extra  4. (1) pašalintas sektorius- skubus rentgeninis tyrimas- navikas pašalintas, planinis patologinis tyrimas.. 4(1). Krūties sektorius 8x4,5x3,5 cm, su odos lopu 7x2,7 cm, su speneliu. Krūties audinyje - besiribojantis su speneliu balkšvas, standus, žvaigždės formos, neaiškių ribų navikas 17x15x17 mm, nuo artimiausio giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - mažiau 0,1 cm, nuo odos rezekcijos krašto - 0,7 cm. Naviko projekcijoje oda be makroskopinių pokyčių, spenelis nežymiai įtrauktas.. 1(N2A). Krūties fibrocistiniai pokyčiai.  2(N2B). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (1 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,7 cm) pN(sn)0 (0/1 l/m). LVI0(limfovaskulinės invazijos nėra).    Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5% (hot spot 10%).. 1(N2A). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2(N2B). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N3). Sinusų histiocitozė viename (1) limfmazgyje.  4(N1). Krūties audinyje - navikas: solidines, trabekulines, pavienes kribrozines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 7 / 10 DPRL.. 4(N1). Navikas (9 blokas): Her2 nusidažiusių naviko ląstelių nėra.  Ki67: 5% (hot spot 10%).
answer:  0

 72%|███████▏  | 477/661 [13:18<04:56,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biospiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7mm; II - 7 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 5,5 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 8%.. Krūties audinį 2-se bioptatuose infiltruoja iki 5,5 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su neryškiai polimorfiškais branduoliais  negausioje bazofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) cirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 8% naviko ląstelių.  Progesterono receptoriai: stipri (+++)
answer:  1a

 72%|███████▏  | 478/661 [13:19<04:49,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas kairės krūties kraujuojantis peraugantis spenelį navikas. Krūties sektorius 11,5x8x5,5 cm. Krūties audinyje balkšvas, standus, neaiškių ribų navikas 3,3x1,8x3,3 cm, esantis 0,5 nuo artimiausio/giliojo rezekcijos pjūvio, siekia ir perauga odą, nuo odos rezekcijos krašto nutolęs 2 cm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b (33mm, išopėjimas).. Krūties audinyje išopėjęs 33mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.  Operacinis pjūvis be naviko.. nan
answer:  1a

 72%|███████▏  | 479/661 [13:21<04:43,  1.56s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 10 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai kompleksai ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  1a

 73%|███████▎  | 480/661 [13:23<04:40,  1.55s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  16 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais ~8x18 mm dydžio navikas kairiojoje krūtyje ties 12 val. vidurinėje dalyje, paimti trys biopsiniai stulpeliai histologijai.. 3 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 12 mm; III - 13 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.. Krūties audinį difuziškai infiltruoja vidutiniškai polimorfiškos apvalios ląstelės, vietomis ekscentriškais branduoliais, mitozių iki 6/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: vidutinis dalies membranos nusidažymas 60% naviko ląstelių.  Ki67+
answer:  15%

 73%|███████▎  | 481/661 [13:24<04:45,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2). Deš. pažasties sarginiai l/m, skubu  4(3). Deš. krūties sektorius, planinis. 4. Krūties sektorius 7x6x3,5 cm, žymėtas viela. Pjūvyje, vielos projekcijoje - balkšvas, standus, aiškių ribų navikas 15x15x10 mm (sudėtas visas), nuo rezekcijos krašto nutolęs 1 cm.. 1(1a). Viršutinis kraštas. Krūties audinys be patologinių pokyčių.   2(1b). Apatinis kraštas. Krūties audinio fibrozė.   3(2). Deš. pažasties sarginiai l/m. Reaktyvi limfadenopatija (4 l/m).   4(3). Deš. krūties sektorius. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma. SUMINIS TNM: pT1c(15 mm navikas) pN0(sn)(0/4 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikalus pašalinimas).   Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 kribriforminis tipas).. 1(1a). Viršutinis kraštas. Krūties audinys su pavieniais smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2(1b). Apatinis kraštas. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(2). Deš. pažasties sarginiai l/m. 4 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.  4(3). Deš. krūties sektorius. Krūties audinyje - desmoplastiškoje stromoje plintantis navikas, suformuotas tubulių, kribriforminių struktūrų ir lizdų.  Naviko ląstelės su vidutinio gausumo eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar ovoidiškais, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių navike iki 3/10DPRL.  Šalia naviko - stambūs kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių.. Navikas (16 blokas): HER2: silpnas dalies membranos nusidažymas 60% naviko ląstelių.
answer:  1(

 73%|███████▎  | 482/661 [13:26<04:38,  1.55s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 4 mm; II - 4 mm; III - 3 mm. Gleivės.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mucininė karcinoma.   Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: vidutinė reakcija 5% naviko ląstelių.   Her2 imuninė reakcija: teigiama (3+).   Ki67 proliferacinis aktyvumas 5%.. Fragmentuotuose bioptatuose (3/3) - ekstraląsteliniuose mucinuose trabekulinės, kribriforminės, lizdinės naviko struktūros, suformuotos ląstelių gausia eozinofiliška ryškia citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 5/10 DPRL.. Navikas:   Estrogenų receptoriai: (+++)(brand. r-ja) 100%.   Progesterono receptoriai: (++)(brand. r-ja) 5%.   HER2: stiprus visos membranos nusidažymas 100%.   Ki67 proliferacinis aktyvumas 5%.
answer:  0

 73%|███████▎  | 483/661 [13:28<05:22,  1.81s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.1a- viršutinis kraštas (deš.krūtis), skubu  2.1b- apatinis kraštas (deš. krūtis), skubu  3.(2). Deš. pažasties sarginiai limfmazgiai, skubu  4.(4a) - viršutinis kraštas (kairė krūtis), skubu  5.(4b)- apatinis kraštas (kairė krūtis), skubu  6.(5) - Kairės pažasties sarginiai limfmazgiai, planas  7.(3)- deš. krūties kvadrantas, planinis  8.(6) - Kairės krūties kvadrantas, planinis  9.(7) - papildomas k.kruties viršut.kraštas-planas  10.(8) - papildomas d.krūtis apat.kraštas-planas. 6(5). Riebalinio audinio fragmentas 5,5x2,5x1,3 cm. Rastas limfmazgis 3 cm.   7(3). Krūties sektorius 13,5x6,5x3 cm su odos lopu 8,5x3,5 cm, žymėtas dvejomis vielomis. Vienos vielos projekcijoje neaiškių ribų, standi fibrozės zona su prasiplėtusiais tarpais 21x9x7 mm, nuo giliojo rezekcijos krašto nutolusi 0,3 cm, nuo odos - 2,5 cm. Kietos vielos projekcijoje 2 intramamariniai limfmazgiai iki 0,5 cm skersmens. Fibrozės zona vielos projekcijoje sudėta visa.   8(6). Krūties sektorius 9x6x2,2 cm, be odos, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 21x18x11 mm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm.  9(7). Riebalinio/fibrozinio audinio fragmentas 2,5x1x0,4 cm. v/m  10(8). Riebalinio audinio fragmentas 3x1,3x0,5 cm. v/m. 1(extra). Viršutinis kraštas, dešinė. Fibrocistiniai pokyčiai.  2(extra). Apatinis kraštas, dešinė. Krūties žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1, kribriforminis tipas).  3(extra). Sarginiai limfmazgiai, dešinė. Reaktyvi limfadenopatija (4 l/m).    4(extra). Viršutinis kraštas, kairė. Fibrocistiniai pokyčiai.  5(extra). Apatinis kraštas, kairė. Fibrocistiniai pokyčiai.  6. Kairės pažasties sarginiai limfmazgiai (planinis). Duktalinės karcinomos metastazė (1/1 l/m, 4,4 mm).    7. DEŠINĖ. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) multižidininė, mikroinvazyvi duktalinė karcinoma, SUMINIS TNM: pT1mi(m)(0,4 mm, 0,5 mm, 0,9 mm, 1 mm) pN0(sn)(0/6 l/m0 LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 DIN1 DIN2, kribriforminis, solidinis, komedo ir papilinis tipai), DCIS židinys iki 2 cm. R0(radikali rezekcija).  Imunofenotipas (biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.    8. KAIRĖ.  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(21 mm navikas) pN1a(sn)(MTS 1/1 l/m 4,4 mm) LVI-2(limfovaskulinė invazija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas). R0(radikali rezekcija).  Imunofenotipas (biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%, vietomis iki 30%.    9. Papildomas kairės krūties viršutinis kraštas. Fibrocistiniai pokyčiai.   10. Papildomas dešinės krūties apatinis kraštas. Fibrocistiniai pokyčiai.. 1(extra). Viršutinis kraštas (deš.krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  2(extra). Apatinis kraštas (deš. krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu. Fokaliai latakų grupė su intraduktaliniais kribriforminiais proliferatais iš ląstelių nežymiai polimorfiškais brnaduoliais.   3(extra). Sarginiai limfmazgiai, dešinė. 4 limfmazgiai su sinusų histiocitoze, lipomatoze ir pirminiais bei antriniais folikulais.  4(extra). Viršutinis kraštas (kairė krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  5(extra). Apatinis kraštas (kairė krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  6. Kairės pažasties sarginiai limfmazgiai. Vienas limfmazgis su metastaze, 4,4 mm suformuota susiliejančių tubulinių struktūrų.  7. DEŠINĖ. Krūtyje - navikas (0,4 mm, 0,5 mm, 0,9 mm, 1 mm židiniai) suformuotas lizdais besidėstančių ląstelių gausia eozinofiliška, ryškia citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 1/10 DPRL.  Greta gausūs dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais ir solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.   2 limfmazgiai su sinusų histiocitoze ir antriniais folikulais.  8. KAIRĖ. Krūtyje - navikas (21 mm) infiltratyviu ekspansyviu frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais branduoliais ryškiomis nukleolėmis; mitozių 4/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais ir solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.   Limfovaskulinė naviko invazija.  9. Papildomas k.kruties viršutinis kr. Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.    10. Papildomas d.krūtis apatinis kr. Krūties audinys su kanaliukais, klotais dvisluoksniu ir hiperplastišku epiteliu su apokrinine metaplazija. Ryškūs koaguliacijos artefaktai.. 2. DCIS (3 blokas): C14 išlaikytas mioepitelinis sluoksnis.  7. Navikas (32, 35 blokai): Ck14(-).
answer:  1.

 73%|███████▎  | 484/661 [13:30<05:21,  1.82s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas kairė krūtis ir kairės pažasties limfmazgiai. Krūtis 1921 g svorio, 31x22x10 cm. Odoje daugybiniai, rusvi, riboti, gruoblėtu paviršiumi, kiek iškilęs dariniai, didžiausias 1x1x0,2 cm, artimiausias nuo odos rezekcijos krašto nutolęs 0,5 cm.   Krūties audinyje, centrinėje dalyje - pilkšvas, standus, neaiškių ribų I navikas 25x15x10 mm, nuo giliojo rezekcijos krašto nutolęs 7 cm, nuo odos - 1 cm.   Nuo I naviko 2 cm atstumu - pilkšvas, standus, neaiškių ribų II navikas 10x10x6 mm, nuo giliojo rezekcijos krašto nutolęs 6 cm, nuo odos - 1,5 cm. I ir II navikus jungia fibrozė.   Rasti krūties 3 limfmazgiai iki 1,3 cm skersmens. Atskirai inde riebalinio audinio fragmentai, bendras dydis 8x7x2 cm. Rasta 15 limfmazgių iki 3,3 cm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT3(55 mm dydžio navikas)   pN1a(3-se/18 l/m su mts iki 10 mm)   pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pP1(perineurinis naviko plitimas)   pR0(radikalus pašalinimas).   Naviko imunotipas nustatytas priešoperacinėje biopsijoje:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.    Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, komedo tipo).  Įprastinė duktalinė hiperplazija. Apokrininė metaplazija.  Odos seborėjinė keratozė; dermalinis nevusas su seborėjine keratoze.. Odos dariniai: epidermio hiperplazija su formuojamomis raginėmis cistomis ir besiliejančiais akantotiniais pluoštais; viename iš darinių, dermoje stambūs brandžių nevocitų lizdai.   Spenelis: be patologijos.   Krūties audinyje - vienas netaisyklingo kontūro, 55 mm dydžio mikroskopiškai navikas, suformuotas smulkių lizdų, trabekulių ir pavienių tubulių (~5%). Naviko ląstelės su negausia eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais su blyškiu, tolygiu chromatinu ir aiškiomis eozinofiliškomis nukleolėmis. Mitozių navike iki 7/10DPRL.  Naviko plitimas endotelizuotuose spindžiuose ir perineuriškai.  Šalia naviko - gausūs dilatuoti kanaliukai su intraduktaliniais kribriforminiais, solidiniais, papiliniais proliferatais iš analogiškų navikui ląstelių, su komedonekroze ir mikrokalcifikatais spindžiuose.  Atokiau yra latakų su įprastine duktaline hiperplazija ir apokrinine metaplazija.  Krūties ir pažasties limfmazgiai (18): 3-se/18 limfmazgių - aukščiau aprašyto naviko metastazės iki 10mm, su ekstranodaliniu plitimu.. nan
answer:  1a

 73%|███████▎  | 485/661 [13:32<05:16,  1.80s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.  4. sektorius, planinis. 4. Krūties sektorius 9x7x4 cm, su odos lopu 6x3 cm, su speneliu. Oda šalia spenelio žymėta dviem siūlais. Pjūvyje, siūlu projekcijoje, balkšvas, standus, neaiškių ribų navikas 1,1x1,1x1 cm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, siekia odą ir spenelį, juos perauga.(navikas sudėtas visas). 1. pjūvio kraštai. Krūties fibrocistiniai pokyčiai.  2. pjūvio kraštai. Krūties fibrocistiniai pokyčiai.    3. sarginiai l/m - karcinomos mikrometastazė (1 mm) 1-me iš 4 limfmazgyje.    4. Krūties sektorius.   Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma  pT1b pN1mi pR0.  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.    Intraduktalinė papiloma (4 mm).. 1. pjūvio kraštai - Fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu, fokaliai apokrininė metaplazija.  2. pjūvio kraštai - Fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu, fokaliai apokrininė metaplazija.  3. sarginiai l/m - atipinių liaukinių struktūrų židinys 1 mm 1-me iš 4 limfmazgių.  4. Krūties sektorius. Odą (neišopėjusią) ir riebalinį audinį infiltruoja smulkios duktalinės struktūros, nedideli netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  Kompaktišku fibroziniu audiniu riboto darinio (4 mm) papilinės, tinklinės struktūros iš fibrozinės vaskuliarizuotos stromos padengtos dvisluoksniu epiteliu be atipijos.. nan
answer:  1a

 74%|███████▎  | 486/661 [13:34<05:26,  1.87s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2). deš. pažasties sarginiai limfmazgiai, skubu  2(3a). Deš. krūties viršutinis kraštas, skubu  3(3b). deš. krūties apaptinis kraštas, skubu  4(1). Kairės krūties užspenelinis audinys, skubu  5(1a). Kairės pažasties sarginiai limfmazgiai, skubu  6(4). deš. krūties audinys, planinis  7(5). Kairės krūties audinys, planinis. 6. Krūties sektorius 6,5x4,7x2 cm su oda 5x3,5 cm. Krūties audinyje pilkšvas, standus, neaiškių ribų navikas 16x15x15 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos -  0,4 cm.  7. Krūties sektorius 12,5x11,5x2,5 cm su oda 5x1,2 cm. Krūties audinys fibrozuotas visame plote. Poodinis gilusis rezekcijos kraštas dažytas mėlynai.. 1(2/deš. pažasties sarginiai limfmazgiai)(EXTRA). Duktalinės karcinomos mikrometastazė 1/5 l/m (1,4 mm).  2(3a/deš. krūties viršutinis kraštas)(EXTRA). Krūties audinys.  3(3b/deš. krūties apaptinis kraštas)(EXTRA). Krūties audinys.  4(1/kairės krūties užspenelinis audinys)(EXTRA). Krūties audinys.  5(1a/kairės pažasties sarginiai limfmazgiai)(EXTRA). Reaktyvi limfadenopatija (6 l/m).  6(4/deš. krūties audinys). Krūties (dešiniosios) invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(15 mm) N(sn)1mi(mikromts 1/5 l/m), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).  7(5/kairės krūties audinys). Krūties (kairiosios) aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS)(solidinė, kribriforminė, papilinė,  komedo), pTis. DCIS struktūros 0,25 mm nuo poodinio rezekcijos krašto.. 1(2/deš. pažasties sarginiai limfmazgiai)(EXTRA). Viename (1) iš 5 l/m - žemiau (Nr.6) aprašyto naviko mikrometastazė (1,4 mm).  2(3a/deš. krūties viršutinis kraštas)(EXTRA). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(3b/deš. krūties apaptinis kraštas)(EXTRA). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  4(1/kairės krūties užspenelinis audinys)(EXTRA). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  5(1a/kairės pažasties sarginiai limfmazgiai)(EXTRA). 6 limfmazgiai su antriniais limfoidiniais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  6(4/deš. krūties audinys). Krūties audinyje - ribotas navikas (mikroskopiškai 15 mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių, lizdinių ir negausių (<10%) fokaliai besiliejančių tubulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 6/10 DPRL. Pavieniai mikrokalcifikatai. Limfovaskulinė ir perineurinė invazija. Šalia yra dilatuotų kanaliukų su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais.  7(5/kairės krūties audinys). Krūties audinyje, fibrozuotoje stromoje - dilatuoti ir vidutinio kalibro, fokaliai smulkesni kanaliukai su solidiniais, kribriforminiais ir papiliniais intraduktaliniais proliferatais (fokaliai su komedo nekroze ir kalcifikatais centre), suformuoti ląstelių eozinofiliška ar blyškoka citoplazma, vidutinio ir stambaus kalibro, apvaliais/ovaliais, polimorfiškais, dalis su aiškia nukleole branduoliais. DCIS struktūros 0,25 mm nuo žymėto poodinio rezekcijos krašto.. 7. 56 blokas: DCIS struktūros su išlaikytu CK14+ mioepiteliniu sluoksniu.
answer:  0

 74%|███████▎  | 487/661 [13:35<05:21,  1.85s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1a- viršutinis kraštas, skubu  2 ėminio aprašas: 1b- apatinis kraštas, skubu  3 ėminio aprašas: 2. Sarginiai limfmazgiai, skubu  3 ėminio aprašas: 3. Deš. krūties kvadrantas, planinis. 4(3). Krūties sektorius 11x4x4,5 cm su odos lopu 10x3 cm, žymėtas vielomis (atstumas tarp vielų 7,2 cm). Pjūvyje, I vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 14x14x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,8 cm, nuo odos - 3,5 cm. II vielos projekcijoje krūties audinys fibrozuotas 1,8x1,6 cm plote, nuo giliojo rezekcijos krašto nutolęs 0,1 cm.. 1. Krūties audinys.  2. Riebalinio audinio fragmentas.  3. Krūties duktalinės karcinomos mikrometastazė viename limfmazgyje (1/3 l/m, 1,5 mm).  4. Krūties invazyvi  mišri blogai diferencijuota (G3; 8 b. pgl. Nottingham) duktalinė (70%) ir mikropapilinė (30%) karcinoma, suminis TNM: pT1c(navikas 14 mm), pN1mi(1/3 l/m), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).. 1. Krūties audinyje smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2. Riebalinio audinio fragmentas be patologinių pokyčių.  3. Viename limfmazgyje iš 3  (planiniame ištyrime, po fiksacijos) (1/3 l/m) žemiau aprašyto naviko mikrometastazė, iki 1,5 mm skersmens.  4. Krūties audinyje - navikas (mikroskopiškai - 14 mm), suformuotas gausių lizdinių struktūrų su pavienių spindžių formacija ir mikropapilinių struktūrų iš ląstelių negausia eozinofiline citoplazma su ryškiai polimorfiškais, ovoidiniais, hiperchromiškais branduoliais, ryškiais branduolėliais. Mitozių navike 11/10DPRL. Limfovaskulinis naviko plitimas (LVI2). Greta naviko gausūs dilatuoti kanaliukai su solidiniais, kribriforminiais proliferatais, suformuotais analogiškų aukščiau aprašytoms ląstelių. Fibrozuotame krūties audinyje (II vielos projekcijoje) gausūs dilatuoti kanaliukai su solidiniais, kribriforminiais proliferatais, analogiškais aukščiau aprašytiems. Aplinkinis krūties audinys fibrozuotas su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu su fokalia apokrinine epitelio metaplazija.. Anksčiau atliktas tyrimas, B23-23730:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė karcinoma su mikropapiliniu komponentu.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai
answer:  100%

 74%|███████▍  | 488/661 [13:37<05:09,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. (N2a) kraštai - extra  2. (N2b) kraštai - extra  3. (N3) Sarginis l/m - extra  4. (N1) Pašalintas sektorius - planinis tyrimas. 4(N1). Krūties sektorius 12,5x5,5x5 cm, su odos lopu 10x3 cm. Pjūvyje balkšvas, standus neaiškių ribų navikas 2,3x2x1,8 cm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1 cm. Aplink naviką fibrozės zona 5x4,5x3 cm.. 1(2a). Krūties fibrocistiniai pokyčiai.  2(2b). Krūties fibrocistiniai pokyčiai.  3(3). Reaktyvi limfadenopatija (2 l/m).  4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT2(2,3 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės naviko invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 10%.. 1(2a). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2(2b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(3). Sinusų histiocitozė, lipomatozė dviejuose (2) limfmazgiuose.  4(1). Krūties audinyje - navikas; solidines, trabekulines, negausias kribrozines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 3 / 10 DPRL.. 4(1). Navikas (13 blokas): HER2: silpnas(+) membraninis dažymasis 5% naviko ląstelių.
answer:  4(

 74%|███████▍  | 489/661 [13:39<04:52,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 15 mm; II - 13 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas pavienėse ląstelėse.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas pavienėse ląstelėse.  Her2 imuninė reakcija: silpnas ar vidutinis dalies membranos nusidažyma
answer:  1a

 74%|███████▍  | 490/661 [13:40<04:56,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas žymėtas dešinės krūties kvadrantas  - planinis tyrimas  2 ėminio aprašas: N2a kraštai   3 ėminio aprašas: N2b kraštai   4 ėminio aprašas: N3: dešinės pažasties sarginiai limfmazgiai  5 ėminio aprašas: N4: papildomas kraštas. 1. Krūties sektorius 8,5x4,5x5 su odos lopu 8,5x3,7 cm (žymėtas viela). Pjūvyje, viela žymėtoje vietoje, balkšvas, standus, gan aiškių ribų navikas 0,9x0,7x0,8 cm (sudėtas visas). Nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos - 4 cm.  2. Riebalinio fibrozinio audinio fragmentas 1,2x0,9x0,4 cm. v/m  3. Riebalinio fibrozinio audinio fragmentas 1,8x1x0,5 cm. v/m  4. Riebalinio audinio fragmentai 4,8x3x1 cm. Rasti 2 limfmazgiai 2,2 cm ir 0,8 cm.   5. Riebalinio audinio fragmentas 1,5x1x0,6 cm. v/m. 1. Krūties invazyvi duktalinė karcinoma (gerai diferencijuota, G1 / 4 balai pagal Nottingham);   pT1b(9 mm)   pLVI-0   pN(sn)1mi(1/2; 1,2 mm)   pR0(1,2 mm nuo krašto).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 3% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 12%.    Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS, kribrozinio tipo).    2. Krūties audinio nespecifiniai fibroziniai židiniai.   3. Krūties audinio nespecifiniai fibroziniai židiniai.   4. Karcinomos mikrometastazė 1-me/2 limfmazgyje.  5. Riebalinio audinio fragmentas be patologinių pokyčių.. 1. Tubulines (80%), pavienes smulkias kribrozines naviko struktūras formuoja stulpinės ląstelės su saikinga švelniai eozinofiline citoplazma, vidutiniškai polimorfiniais skeltais be nukleolės branduoliais; mitozių navike iki 1 / 10 DPRL.  Gretimai negausios tubulės su anallogiškų atipiniųląstelių tinkliniais proliferatais.   Invazinės struktūros 1,2 mm nuo giliojo krašto.  Intrvaskulinio plitimo nestebima.  2. Krūties audinio nespecifiniai fibroziniai židiniai.   3. Krūties audinio nespecifiniai fibroziniai židiniai.   4. Atipinio epitelio tinklinių struktūrų židinys 1,2 mm limfmazgyje (1-me/2).  5. Riebalinio audinio fragmentas be patologinių pokyčių.. Blokas 1:  CD31: stipri teigiama (+++) membraninė reakcija kraujagyslių endotelyje be atipinių struktūrų spindyje  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: r
answer:  12%.

 74%|███████▍  | 491/661 [13:42<04:41,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 12 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 74%|███████▍  | 492/661 [13:44<04:37,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1  biopsinis stulpelis. Biopsinis stulpelis 13 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma. Aukšto laipsnio duktalinė karcinoma in situ (DCIS, plokščias, kribriforminis tipas).     Imunofenotipas:   Estrogenų receptoriai: vidutinė reakcija 90% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 5% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.. Bioptate - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis lizdais ir trabekulėmis besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais ryškiomis stambiomis nukleolėmis; mitozių 3/10 DPRL. Greta dilatuoti latakais su intraduktaliniais plokščiais ir kribriforminiais proliferatais iš analogiškų navikui ląstelių.. Navikas:  Estrogenų receptoriai: (++)(brand. r-ja) 90%.  Progesterono receptoriai: (++)(brand. r-ja) 5%.  HER2: nusidažiusių naviko ląstelių membranų nėra.  Ki67 proliferacinis aktyvumas 10%.  E-cadherin(+++)(membr. r-ja) 100%.
answer:  1

 75%|███████▍  | 493/661 [13:46<04:56,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas - extra;  2(1b)- Apatinis kraštas - extra;  3(2). Kairės krūties sarginiai limfmazgiai - extra;   4(3). Kairės krūties sektorius - planinis tyrimas;  5(4a). Papildomas viršutinis kraštas - planinis tyrimas;  6(4b). Papildomas viršutinis kraštas - planinis tyrimas;  7(5). Limfmazgiai - planinis tyrimas.. 4(3). Krūties sektorius 9x6,5x4 cm su oda 8x2,5 cm, žymėtas 2 vielomis, vienas kraštas žymėtas dviem siūlais. I vielos projekcijoje - balkšvas, standus, neaiškių ribų navikas 31x29x26 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 1,5 cm ;II vielos projekcijoje - I fibrozės zona 3x2,2x2 cm, susijungianti su naviku (bendras dydis su naviku - 44x36x19 mm ) ir II fibrozės zona - 1,4x1x0,9 cm, nuo I fibrozės nutolusi 0,5 cm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 4 cm. Siūlais žymėtas kraštas dažytas žalia, kitas kraštas- juoda spalva. 29 kasetėje, II fibrozės zonos pusė, žymėta žaliais dažais.  5(4a). Riebalinio audinio fragmentas 2x1x0,3 cm. v/m  6(4b). Riebalinio audinio fragmentas 2,5x1,5x0,4 cm. v/m  7(5). Riebalinio audinio fragmentai, bendras dydis 9x6x1,5 cm. Rasti 20 limfmazgiai iki 1,5 cm.. 1(extra). Viršutinis kraštas. Krūties invazyvi karcinoma (1,3 mm židinys). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 mikropapilinis, solidinis tipai).  2(extra). Apatinis kraštas. Krūties audinys.  3(extra). Kairės krūties sarginiai limfmazgiai. Duktalinės karcinomos metastazės limfmazgiuose (4/4 l/m iki 12 mm).  4. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) mišri duktalinė - mikropapilinė karcinoma, SUMINIS TNM: pT3(56 mm navikas)  pN3a(13/24 l/m MTS iki 14 mm) LVI-2(limfovaskulinė invazija). Navikas siekia sektoriaus rezekcijos kraštą. Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 mikropapilinis, solidinis tipai).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 35%.    5. Papildomas viršutinis kraštas. Krūties invazyvi karcinoma (2,4 mm židinys).  6. Papildomas viršutinis kraštas. Krūties audinys.  7. Limfmazgiai, planinis. Duktalinės karcinomos metastazės limfmazgiuose (9/20 l/m iki 14 mm). 1(extra). Viršutinis kraštas. Krūties audinyje tubulės ir lizdai suformuoti ląstelių vidutinio gausumo eozinofiliška citoplazma, polimorfiškais brnaduoliais. Greta dilatuoti latakai su intraduktaliniais solidiniais, mikropapiliniais proliferatais iš analogiškų ląstelių.  2(extra). Apatinis kraštas. Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3(extra). Kairės krūties sarginiai limfmazgiai. 4 iš 4 limfmazgių aprašyto naviko metastazės iki 12 mm su ekstranodaliniu plitimu.    4. Krūtyje - navikas infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, dominuojančiomis mikropapilinėmis struktūromis, besidėstančių ląstelių vidutinio gausumo eozinofiliška ryškia citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 25/10 DPRL.  Greta dilatuoti latakai su intraduktaliniais solidiniais, mikropapiliniais proliferatais iš analogiškų ląstelių.  5. Krūties audinyje mikropapilinės struktūros iš analogiškų aprašytam navikui ląstelių. Limfovaskulinė invazija.  6. Papildomas viršutinis kraštas. Krūties audinys su fibrozės zonomis, latakais klotais dvisluoksniu epiteliu.  7. Limfmazgiai. Duktalinės karcinomos metastazės limfmazgiuose. 31 blokas: Ck14(-); CD31+ endotelis.
answer:  0

 75%|███████▍  | 494/661 [13:47<04:40,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 5%, vietomis iki 10%.. Krūties audinį infiltruoja juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis netolygus visos membranos nusidažyma
answer:  1a

 75%|███████▍  | 495/661 [13:49<04:39,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1a- viršutinis kraštas, skubu  2 ėminio aprašas: 1b- apatinis kraštas, skubu  3(2) ėminio aprašas: 2. Kairės pažasties sarginiai limfmazgiai, skubu  4(3) ėminio aprašas: 3. Kairės krūties sektorius, planinis. 4. Krūties sektorius 7,5x3x6,5 cm, su odos lopu 6x1,5 cm, žymėtas viela. Vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 10x8x8 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 2,6 cm. Navikas histologiniam ištyrimui sudėtas visas.. 1. Fibrocistiniai krūties pokyčiai.  2. Krūties lobulinė karcinoma in situ (LCIS).   3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 12 mm), pN0(sn)(0/3 l/n), LVI0(neidentifikuota). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.. 1. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu; pavieniai nežymiai dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.  3. Trys limfmazgiai su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.  4. Krūties audinyje - navikas (12 mm mikroskopiškai), suformuotas smulkių lizdinių bei negausių tubulinių struktūrų iš vidutinio kalibro, vidutinio gausumo eozinofiline citoplazma ląstelių, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiais branduolėliais; mitozių 6/10 DPRL. Limfovaskulinis plitimas neidentifikuotas (LVI0). Invazyvus navikas nuo artimiausio rezekcijos krašto nutolęs per 5 mm. Greta naviko dilatuoti latakai, užpildytų solidinių bei kribriforminių proliferatų, suformuotų analogiškų navikui ląstelių.. nan
answer:  0,

 75%|███████▌  | 496/661 [13:51<04:47,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.(N2a) - Kraštai.-skubus tyrimas be naviko  2.(N2b) - Kraštai.-skubus tyrimas be naviko  3.(N1) -  pašalintas kairės krūties kvadrantas - planinis tyrimas. N1- rentgeninis tyrimas- 2 navikai pašalinti  4(N3A) - papildomi kraštai  planinis tyrimas  5(N3B) - papildomi kraštai  planinis tyrimas. 3. Krūties sektorius 11,5x8x4,5 cm su oda 11x7,5 cm. Krūties audinyje, kvadrante - pilkšvas, standus, aiškių ribų navikas 52x20x20 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 1 cm. Poodyje, naviko projekcijoje (nuo naviko 0,4 cm atstumu (foto)), balkšvas standus darinys 10x8x6 mm.  4. Riebalinio audinio fragmentas 2x1,5x0,5 cm. v/m  5. Riebalinio audinio fragmentas 1,8x1x0,5 cm. v/m. 1(ekstra). Riebalinis - fibrozinis audinys.  2(ekstra). Krūties invazyvi karcinoma (0,4 mm židinys). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, komedo tipas).  3. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT3(m)(52 mm, 10 mm navikai) pN0(sn)(0/1 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).  4. Papildomas kraštas. Riebalinis - fibrozinis audinys. Reaktyvi limfadenopatija (1 l/m).  5. Papildomas kraštas. Krūties audinio fibrozė.    Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 60%.. 1(ekstra). Riebalinis fibrozinis audinys.   2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu. Fokaliai latakas su intraduktaliniais solidiniais su komedo nekroze kompleksais, suformuotais analogiškų aprašytoms (Nr.2 naviko ląstelių), smulkūs nubyrantys kompleksai ir pabiros naviko ląstelės šalia.  3. Krūtyje - navikas (52 mm, 10 mm navikai) infiltratyviu augimo frontu, suformuotas struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių  vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais bei gigantiniais, pleomorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 13/10 DPRL.  Gausi perinavikinė limfoplazmocitinė ir polimorfonuklearinė infiltracija, nekrozės zonos.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaus kanaliukų zonos.  4. Papildomas kraštas. Riebalinis - fibrozinis audinys. Vienas limfmazgis su sinusų histiocitoze.  5. Papildomas kraštas. Krūties audinys su židinine fibroze ir negausiais latakais, klotais dvisluoksniu epiteliu.. 2. Navikas, 10 blokas: CK7/CK14 nelieka medžiagos pjūviuose.  Navikas(16 blokas):  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 60%.  CK5+ išla
answer:  0.

 75%|███████▌  | 497/661 [13:52<04:36,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Punktuotas kairės krūties BIRADS V darinys, paimti 2 biopsiniai stulpeliai medžiagos histologiniam ištyrimui.. 2 biopsiniai stulpeliai: I - 15 mm; II - 15 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 3% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 40%.. Krūties audinį 2-se bioptatuose infiltruoja iki 11 mm :   - duktalinės pavienės struktūros, trabekulės;  - epitelinių smulkių / vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje citoplazmoje;   - su mitozėmis iki 1/10 DPRL (didesnė dalis ląstelių artefaktiškai deformuotos).   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 40% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 3% naviko
answer:  3b

 75%|███████▌  | 498/661 [13:54<04:37,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas markiruotas kairės krūties darinys su vielute - planinis tyrimas  2 ėminio aprašas: N2a kraštai - planinis tyrimas  3 ėminio aprašas: N2b kraštai - planinis tyrimas  4 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - planinis tyrimas. 1. Krūties sektorius 5x4x3 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, spikulinis navikas 16x14x16 mm, nuo artimiausio rezekcijos krašto nutolęs 0,5 cm.    2. Riebalinio audinio fragmentas 2x1,5x0,7 cm. v/m   3. Riebalinio audinio fragmentas 2x1x0,4 cm. v/m  4. Riebalinio audinio fragmentas 4x3x2 cm. Rastas limfmazgis 2,5 cm.. 1. Krūties invazyvi gerai diferencijuota (G1,  5b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(14 mm navikas) pN1a(sn)(7 mm MTS 1/1 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stipri reakcija 95% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 30% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.    2. Kraštai (N2a). Krūties audinio fibrozė.  3. Kraštai (N2a). Krūties audinio fibrozė.  4. Krūties duktalinė karcinomos metastazė limfmazgyje (1/1 l/m 7 mm MTS).. 1. Krūtyje - navikas (14 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, struktūromis ir negausiais lizdais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais apvaliais, branduoliais ryškiomis nukleolėmis; mitozių 8/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių.   2. Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  4. 1 limfmazgis su aprašyto naviko metastaze 7 mm.. Navikas:  HER2: silpna dalies membranos r-j 1 % naviko ląstelių.
answer:  0

 75%|███████▌  | 499/661 [13:56<04:30,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 16 mm.. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham sistemą) duktalinė karcinoma (12,5 mm mikroskopiškai).  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 plokščias, solidinis tipai).  Naviko imunofenotipas:  Estrogenų receptoriai: stipri reakcija, 90% naviko ląstelių.  Progesterono receptoriai: stipri reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 7%.. Fibroziniame audinyje (1 biopsiniame stulpelyje) plinta tubulinės (40 %), kribriforminės struktūros ir smulkūs lizdai. Naviko ląstelės su negausia, šviesiai eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais ar netaisyklingo kontūro, vidutiniškai polimorfiškais branduoliais, fokaliai vesikuolizuotu chromatinu ir smulkiomis nukleolėmis. Mitozių navike <1/10DPRL.  Šalia naviko dilatuoti kanaliukai su intraduktaliniais "plokščiais" ir solidiniais proliferatais iš analogiškų navikui ląstelių.. Blokas 1:  CD117: neigiama reakcija.   CK14: neigiama reakcija invazyviame navike, CK14+ mioepitelis DCIS struktūrose.  Estrogenų receptoriai: stipri (+++) reakcija, 90% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 90%
answer:  1.

 76%|███████▌  | 500/661 [13:57<04:20,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 14 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis ar silpnas branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis 20%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis ar silpnas branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 15%
answer:  2

 76%|███████▌  | 501/661 [13:59<04:35,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1) Kraštai - extra  2(N2) kraštai - extra  3(N3) sarg. l/m - extra  4(N4) Deš. kvadrantas su naviku, planiškai. 4. Krūties sektorius 10x8,x5x3cm, su odos lopu 9,5x3 cm. Sektoriaus vieno krašto paviršiuje - standesnė zona 1,5x1x0,5 cm. Tame pačiame inde atskiras poodinis krūties sektorius 8x3x3,5 cm, pjūvyje su balkšvu naviku 1,3x1,3x1,3 cm, su kalcifikatais, nuo artimiausio rezekcijos krašto nutolęs mažiau 0,1 cm.. 1(ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.    2(ekstra). "Kraštai": fibrozuotas krūties-riebalinis audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (4 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT1c (navikas ~13 mm skersmens) N0(sn) (0/4 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   LVI-0 (definityvios limfovaskulinės invazijos nėra).   Kalcifikatai.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties lobulinė intraepitelinė neoplazija (LCIS).  Krūties žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS: kribriforminis tipas).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė duktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).. 1(ekstra). "Kraštai": fibrozuotas, vaskuliarizuotas brandžių lipocitų suformuotas audinys; be naviko.   2(ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": keturi (4) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.     4. NAVIKAS (du naviko fragmentai: I - 1,4 mm ir II - 12 mm; abu fragmentai siekia sektorių rezekcijos kraštus - radiniai atitinka vieno naviko fragmentaciją operacijos metu):   krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", solidinės naviko struktūros, suformuotos mažai kohezyvių vidutiniškai polimorfiškų ląstelių, negausia ar vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 11/10 DPRL. Navike yra kalcifikuotos fibrozės židinių, fibroadenomatozinių stromos pokyčių.   APLINKA: zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais.   Šalia naviko - keli nedideli kribriforminiai intraduktaliniai polimorfiškų kohezyvių naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, papiliarizuotomis struktūromis apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   SEKTORIŲ REZEKCIJOS KRAŠTAS: abiejų krūties sektorių viename iš rezekcijos kraštų - naviko struktūros; priešingos pusės sektorių kraštuose - koaguliuotas krūties audinys.. 4. Navikas (blokas 14):  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.
answer:  0

 76%|███████▌  | 502/661 [14:01<04:25,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~18x18 mm dydžio navikas dešiniojoje krūtyje ties 10 val. periferinėje dalyje, paimti trys biopsiniai stulpeliai histologijai.. 3 fragmentuoti biopsiniai stulpeliai: I - 4 mm; II - 5 mm; III - 6 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 reakcija neigiama 1+.  Ki67+ 3%.  Žemos ir vidutinio laipsnio intraduktalinė karcinom (DCIS/DIN1-2).. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  Aplink invazinio naviko židinius dilatuoti kanaliukai su intraduktaliniais neryškiai ar vidutiniškai polimorfiškų ląstelių proliferatais.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 vidutinis dalies membranos nusidažymas 40% naviko ląstelių.   Ki67+ 3%.
answer:  1a

 76%|███████▌  | 503/661 [14:02<04:20,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but: Deš. krūties, apatinių kvadrantų riboje, ties ~6h, periferinėje dalyje ~6 mm dydžio hipoechogeniškas, nevisai aiškių kontūrų darinys, paimti 2 biopsiniai stulpeliai (čiuopiamas).  2 but: Deš. krūties, apatinių kvadrantų rigoje, ties ~6h, vidurinėje dalyje ~10 mm dydžio, hipoechogeniškas, heterogeniškas darinys, kiek neaiškių kontūrų.. 1. 2 biopsiniai stulpeliai: I - 13 mm; II - 15 mm.  2. 5 fragmentuoti biopsiniai stulpeliai: I - 17 mm; II - 15 mm; III - 12 mm; IV - 8 mm; V - 9 mm.. 1. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma.  2. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma.  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: silpnas(+) branduolinis dažymasis 2%.   HER2 imunohistocheminė reakcija neigiama (0 balų).  Ki67: 80%.. 1. Solidines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne blyškiai-saikingai eozinofiline citoplazma, vidutinio kalibro apvalios formos saikingai netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 35 / 10 DPRL; nekrozė navike (~20%).  2. Analogiškas aukščiau aprašytam navikas.. Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: silpnas(+) branduolinis dažymasis 2%.   HER2: nusidažiusių naviko ląstelių nėra.   Ki67: 80%.
answer:  1 but

 76%|███████▌  | 504/661 [14:04<04:21,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pjūvio kraštai - extra;  2. Pjūvio kraštai - extra;  3. Sarginiai l/m - exstra;  4. Sektorius - planinis.. 4. Krūties sektorius 10,5x4,5x3,5 cm su oda 9,5x2,5 cm, žymėtas viela. Krūties audinyje, kvadrante - pilkšvas, standus navikas 9x9x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 2,7 cm.. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(10 mm navikas) pN0(sn)(0/3 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija). Vidutinio - žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1 DIN2, kribriforminis ir papilinis tipai).    Imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (0+).  Ki67: 15%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (10 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais branduoliais ryškiomis nukleolėmis.  mitozių 3/10 DPRL. Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu.. Navikas:  HER2: silpnas dalies membranos nusidažymas pavienėse ląstelėse.
answer:  0

 76%|███████▋  | 505/661 [14:05<04:11,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 10 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35-40%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 30/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 12% naviko ląstelių.  Ki67+ 35
answer:  3b

 77%|███████▋  | 506/661 [14:07<04:09,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, planinis;  2. pjūvio kraštai, planinis;  3. sarginiai l/m, planinis;  4. sektorius, planinis.. 1. Riebalinio audinio fragmentas 3,5x2,5x0,7 cm. v/m  2. Riebalinio audinio fragmentas 3,5x2x1 cm. v/m  3. Riebalinio audinio fragmentai, bendras dydis 5x4x2 cm. Rasti 4 limfmazgiai iki 1,3 cm.  4. Krūties sektorius 11x6x5 cm su odos lopu 10x2,5 cm, žymėtas viela. Vielos projekcijoje, pilkšvas, standus, apvalios formos navikas 0,9x0,7x0,8 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 1,8 cm, nuo odos – 2,5 cm.. N1-2: Krūties audinio fragmentai be naviko.  N3: Limfmazgiai (4 l/m) be naviko židinių; pN0(sn).  N4: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (9mm).. N1-2: Krūties audinio fragmentai be naviko.  N3: Limfmazgiai (4 l/m) su lipomatoze, be naviko židinių.  N4: Krūties audinyje 9mm navikas: negausios duktalinės struktūros, nedideli solidiniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.. nan
answer:  0

 77%|███████▋  | 507/661 [14:09<04:19,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1) - kraštai - extra  2(N2) - kraštai - extra   3(N3) - Sarginiai l/m - extra  4(N4) - Kairės krūties sektorius.   5(N5) - Likusi k.pažasties narveliena.. 4. Krūties sektorius 9,5x6x5,5 cm su odos lopu 9,5x5 cm, žymėtas viela. Vielos projekcijoje, pjūvyje balkšvas, standus, neaiškių ribų I navikas 12x11x9 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,4 cm, nuo odos – 2,8 cm. Nuo I naviko 0,5 cm atstumu - balkšvas, standus, neaiškių ribų II navikas 16x11x10 mm, nuo artimiausio rezekcijos krašto nutolęs 0,6 cm, nuo odos 3,5 cm. Šalia navikų - fibrozės zona 5,5x3x2,5 cm.  5. Riebalinio audinio fragmentai, bendras dydis 11x7x1,5 cm. Rasta 16 limfmazgių iki 1,3 cm skersmens.. 1. Krūties audinys.  2. Krūties audinys.  3. Krūties duktalinės karcinomos metastazė limfmazgyje (1/1 l/m; 11,7mm; ekstranodalinis naviko plitimas).  4. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(m)(du naviko židiniai: 12mm ir 16mm) pN1a(1/17 l/m; 11,7mm; ekstranodalinis naviko plitimas); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).  IHC reakcijos atliktos VPC:B23-115 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%."  Krūties fibrocistiniai pokyčiai; sklerozuojanti adenozė.. 1. Riebalinis audinys su fibrozinėmis septomis, pavieniais latakėliais, klotais dvisluoksniu epiteliu.  2. Riebalinis audinys su fibrozinėmis septomis, latakėliais, klotais dvisluoksniu epiteliu.  3. Vienas(1) limfmazgis su žemiau aprašyto naviko metastaze (11,7mm; ekstranodalinis naviko plitimas).  4. Krūties audinyje - du naviko židiniai (12mm ir 16mm), formuojami solidinių/lizdinių, trabekulinių, pavienių netaisyklingų liaukinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais; Limfo-Vaskulinė naviko Invazija (LVI) smulkiose kraujagyslėse/limfagyslėse; navike iki 3 mitozių/10 DPRL. Aplinkinis krūties audinys su fibrozės zonomis, fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, smulkių latakėlių, klotų dvisluoksniu epiteliu, organoidinės proliferacijos fibrozinėje stromoje židiniai.  5. Šešiolika(16) limfmazgių be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.. nan
answer:  4.

 77%|███████▋  | 508/661 [14:10<04:11,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas ~7x8x10 mm dydžio sunkiai išsiskiriantis iš aplinkinio audinio deformacijos plotas/darinys kairiojoje krūtyje centrinėje dalyje vos lateraliau spenelio, paimti trys biopsiniai stulpeliai histologijai + į biopsijos vietą implantuotas TUMARK Professional nitinolio žymeklis.. 3  biopsiniai stulpeliai: I - 12 mm; II - 10 mm; III - 10 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 10%.. Krūties audinį infiltruoja negausios duktalinės struktūros, nedideli netaisyklingi kribroziniai kompleksai ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 90% naviko ląstelių.  Ki67+ 1
answer:  1a

 77%|███████▋  | 509/661 [14:12<04:02,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1biopsinis stulpelis. Biopsinis stulpelis 8 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 80% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 3%.. Bioptate, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, ovalaus kontūro branduoliais; mitozių 0/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 80%.  HER2: nusidažiusių naviko ląstelių membranų nėra.  Ki67 proliferacinis aktyvumas 3%.  E-cadherin(+++)(membr. r-ja) 100%.
answer:  1a

 77%|███████▋  | 510/661 [14:14<04:06,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1- retroareoliarinė sritis - be naviko  N2- sarginis l/m -  be naviko  N3- pašalinta liauka - planinis patologinis tyrimas  Skubus N3 Ro tyrimas - 16 mm navikas pašalintas. 3. Krūties liauka be odos 11,5x8x1 cm, pjūvyje balkšvas, elastingas, aiškių ribų navikas 1,6x0,8x1,2 cm, nuo poodinio rezekcijos krašto(dažytas žaliai) nutolęs 0,2 cm, nuo giliojo(dažytas mėlynai) - 0,1 cm. Aplinkinis krūties audinys fibrozuotas su cistomis iki 0,6 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Reaktyvi limfadenopatija (2 l/m).  3. Krūties invazyvi blogai diferencijuota (G3; 9 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 16 mm), pN0(sn)(0/2 l/m), LVI0(neidentifikuota). Estrogenų receptoriai: reakcijos nėra. HER2:reakcijos nėra (0). Progesterono receptoriai: reakcijos nėra. Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija.. 1. Krūties audinyje židininė fibrozė, gausios krūties lobulės ir gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar epiteliu su fokalia apokrinine metaplazija.  2. Du limfmazgiai su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.  3. Krūties audinyje navikas (16 mm makroskopiškai), infiltratyviu augimo frontu, suformuotas stambių, besiliejančių solidinių ir kribriforminių struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, stambiais, ryškiais polimorfiškais, hiperchromiškais, smulkiai grūdėtu chromatinu branduoliais su ryškiais branduolėliais. Gausi perinavikinė limfocitų infiltracija. Mitozių navike 25/10DPRL. Limfovaskulinė naviko invazija neidentifikuota(LVI0). Navikas nuo rezekcijos krašto nutolęs per 1 mm. Aplinkiniame krūties audinyje, fibrozuotoje stromoje, gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu bei keli nežymiai dilatuoti kanaliukai su paprasta epitelio hiperplazija. Židininė apokrininė epitelio metaplazija.. Blokas 6:  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių membranoje nėra.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.
answer:  3.

 77%|███████▋  | 511/661 [14:15<03:58,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 4 stulpeliai histologinės medžiagos.. Gauti 3 biopsiniai stulpeliai: I - 9 mm; II - 11 mm; III - 12 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.. Krūties audinį infiltruoja duktalinės struktūros, netaisyklingi kribroziniai kompleksai ir trabekulės iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 10% naviko ląstelių.  Ki67+ 1
answer:  1b

 77%|███████▋  | 512/661 [14:17<03:51,  1.56s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  4 biopsiniai stulpeliai. 4 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 9 mm; III - 12 mm; IV - 12 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+, HER2 geno amplifikacija nenustatyta.  Ki67+ 10%.. Krūties audinį infiltruoja negausios duktalinės struktūros ir netaisyklingi kribroziniai/solidiniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas ar vidutinis visos membranos nusidažymas 10% naviko ląstelių.
answer:  0

 78%|███████▊  | 513/661 [14:18<03:53,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu  3(2). Deš. pažasties sarginiai limfmazgiai, skubu   4(3). Deš. krūties sektorius, planinis. 4.Krūties sektorius 8x3,5x5,5 cm su odos lopu 6,5x1,8 cm žymėtas viela. Vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 9x5x4 mm, nuo giliojo rezekcijos krašto nutolęs 1cm, nuo odos - 3,7 cm.. 1(1a). Viršutinis kraštas. Krūties audinys be patologinių pokyčių.    2(1b). Apatinis kraštas. Krūties audinys be patologinių pokyčių.    3(2). Dešinės pažasties sarginiai limfmazgiai. Limfmazgiai (2) be karcinomos ląstelių.    4(3). Dešinės krūties sektorius. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.    pT1b(9 mm) pLVI-0 pN(sn)0 pR0.. 1(1a). Viršutinis kraštas. Krūties audinys be patologinių pokyčių.  2(1b). Apatinis kraštas. Krūties audinys be patologinių pokyčių.  3(2). Dešinės pažasties sarginiai limfmazgiai. Limfmazgiai (2) be karcinomos ląstelių.  4(3). Dešinės krūties sektorius. Krūties audinį infiltruoja duktalinės struktūros  (<10 proc.) ir smulkūs kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL. Plitimo kraujagyslėse ar operaciniuose kraštuose nestebima.. nan
answer:  0.

 78%|███████▊  | 514/661 [14:20<03:50,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 bioptatai 22 mm 14 G adata, dviejuose - kalcinatai.. 3 fragmentuoti biopsiniai stulpeliai: I - 15 mm; II - 17 mm; III - 16 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 25%.. Krūties audinį infiltruoja negausūs smulkūs solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 80% naviko ląstelių.  Ki67+ 25%
answer:  3b

 78%|███████▊  | 515/661 [14:21<03:45,  1.54s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 8 mm; II - 9 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.. Krūties audinį infiltruoja juostos ir trabekulės iš neryškiai polimorfiškų nedidelių apvalių ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 4
answer:  1b

 78%|███████▊  | 516/661 [14:23<03:51,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2). Kairės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko.  2(1). Pašalinta kairė krūtis - planinis tyrimas.. 2. Krūtis 1336 gramų svorio, 27x22x7 cm. Krūties audinyje, vidinių kvadrantų riboje - balkšvas, standus, neaiškių ribų navikas 52x39x30 mm, nuo odos nutolęs 2,2 cm, nuo giliojo rezekcijos krašto - 3 cm.. 1(2). Reaktyvi limfadenopatija (3 l/m).  2.  Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) lobulinė karcinoma, TNM: pT3(53 mm naviko židinys), LVI0(neidentifikuota), pN0(sn)(0/3 l/m). Krūties lobulinė karcinoma in situ (LCIS). HER2:reakcijos nėra (0). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).  Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3). Spenelio Pageto liga.. 1(2). Trys limfmazgiai (3 l/m) su sinusų histiocitoze.  2. Krūties audinyje - navikas (53 mm mikroskopiškai), suformuotas juostų ir trabekulių iš vidutinio kalibro eozinofiline citoplazma ląstelių, vidutiniškai polimorfiškais branduoliais su pavieniais paryškėjusiais branduolėliais; mitozių 4/10 DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Šalia naviko dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais; greta naviko negausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš negausia eozinofiline citoplazma ląstelių su hiperchromiškais, polimorfiškais branduoliais su ryškiais branduolėliais. Greta nežymiai dilatuoti kanaliukai kloti dvisluoksniu epiteliu su fokalia epitelio hiperplazija.  Spenelis: epidermyje stambiais lizdais ir pavieniui, visame epitelio aukštyje plinta navikas, suformuotas stambių epitelioidinių ląstelių su polimorfiškais, hiperchromiškais branduoliais.. Blokas 8(atipinės ląstelės epidermyje):  CK7: (+++)citop.r-ja 100%;  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Blokas 10:  E-Cadherin: (-)neigiama r-ja;  Blokas 14:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  3c

 78%|███████▊  | 517/661 [14:24<03:44,  1.56s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 14 mm.. Gerai diferencijuota (G1 , 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros, nedideli kribroziniai iš neryškiai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 8%
answer:  1b

 78%|███████▊  | 518/661 [14:26<03:39,  1.54s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 9 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 1-2% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros ir kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 1-2% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląsteli
answer:  1a

 79%|███████▊  | 519/661 [14:27<03:35,  1.52s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 11 mm; II - 10 mm; III -10 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25-30%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 7/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: vidutinis dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+
answer:  25-

 79%|███████▊  | 520/661 [14:29<03:50,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1a- viršutinis kraštas, skubu  2 ėminio aprašas: 1b- apatinis kraštas, skubu  3 ėminio aprašas: 1c- papildomai viršutinis kraštas, skubu  4 ėminio aprašas: 2- Kairės pažasties sarginiai limfmazgiai, skubu  5 ėminio aprašas: 3- kairės krūties kvadrantas, planinis. 5(3). Krūties sektorius 15x10x5 cm su odos lopu 13x3,5 cm. Pjūvyje balkšvas, standus, neaiškių ribų navikas 17x13x10 mm, nuo artimiausio rezekcijos krašto nutolęs 2,5 cm, nuo odos – 1,7 cm. Krūties audinys fibrozuotas.. 1(1a)(Extra). Krūties invazyvi duktalinė karcinoma (3,6 mm židinys). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).  2(1b)(Extra). Krūties audinys.  3(1c)(Extra). Krūties audinys.  4(2)(Extra). Duktalinės karcinomos metastazės 2/4 l/m (7 mm ir 4,5 mm).   5(3). Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(18 mm) N(sn)1a(mts 2/4 l/m), LVI-2(limfovaskulinė invazija).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.. 1(1a)(Extra). Krūties audinyje, šalia koaguliuoto krašto - židinys (3,6 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių smulkių tubulinių ir trabekulinių naviko struktūrų, suformuotų ląstelių saikinga eozinofiliška citoplazma, vidutinio kalibro, ovaliais ir nereguliariais, kiek polimorfiškais, hiperchromiškais branduoliais; mitozių neidentifikuota. Aplink dilatuoti kanaliukai su kribriforminiais ir negausiai solidiniais intraduktaliniais proliferatais, suformuotais ląstelių su vidutiniu ir ryškesniu branduolių polimorfizmu.  2(1b)(Extra). Krūties audinyje, kiek fibrozuotoje stromoje - negausūs vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(1c)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  4(2)(Extra). 2 iš 4 limfmazgių - žemiau (Nr.5) aprašyto naviko metastazės (7 mm ir 4,5 mm).   5(3). Krūties audinyje - ribotas navikas (mikroskopiškai 18 mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių, lizdinių ir negausių (<10%) smulkių tubulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 4/10 DPRL. Limfovaskulinė invazija. Šalia yra dilatuotų kanaliukų su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais.   Aplinkiniame krūties audinyje yra kiek dilatuotų kanaliukų, klotų suplokštėjusiu epiteliu bei kanaliukų su epitelio hiperplazija, grupės stambių kanaliukų su apokrinine metaplazija. Žymėtas rezekcijos kraštas be naviko plitimo.. 1. Navikas (27 blokas):  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra (0).
answer:  0

 79%|███████▉  | 521/661 [14:31<03:42,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai.. 2 biopsiniai stulpeliai: I - 14 mm; II - 14 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 10
answer:  2b

 79%|███████▉  | 522/661 [14:32<03:37,  1.56s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 14/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: vidutinis dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+
answer:  35%

 79%|███████▉  | 523/661 [14:34<03:42,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.(1a)- viršutinis kraštas, skubu  2.(1b)- apatinis kraštas, skubu  3.(2) Deš. pažsties sarginiai limfmazgiai, skubu  4.(3) deš. krūties sektorius, planinis. 4. Krūties sektorius 7x3,5x4,5 cm su oda 6,5x1,5 cm, žymėtas viela. Krūties audinyje, kvadrante - pilkšvas, standus navikas 13x10x5 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 2,2 cm.. 1(1a). Krūties audinys.  2(1b). Krūties audinys.  3. Krūties duktalinės karcinomos mikrometastazė limfmazgyje (1/3 l/m; iki 1,05mm).  4. Krūties invazyvi, gerai diferencijuota (G1; 4 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(navikas - 13mm) pN1mi(sn)(1/3 l/m; iki 1,05mm); LVI-2 (Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse); perineurinis naviko plitimas (PN). Rezekcijos kraštas be naviko.  IHC reakcijos atliktos VPC:B23-19125 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 1-2% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.". 1(1a). Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  2(1b). Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  3. Iš rastų trijų(3) limfmazgių, viename(1) žemiau aprašyto naviko mikrometastazė (1,05mm).  4. Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas netaisyklingų duktalinių (65%), kribriforminių, solidinių/lizdinių, trabekulinių struktūrų iš vidutinio kalibro ląstelių, nežymiai polimorfiškais branduoliais; navike iki 2 mitozių/10 DPRL. Limfo-Vaskulinė naviko Invazija (LVI) smulkiose kraujagyslėse/limfagyslėse; perineurininis naviko plitimas (PN). Rezekcijos kraštas be naviko.. nan
answer:  1(

 79%|███████▉  | 524/661 [14:36<03:46,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)-kraštas-extra-be naviko    2(N2b)-kraštas-extrabe naviko    3(N3)- sarginis (3)- be naviko    4(N1)- pašalintas sektorius -planinis patologinis tyrimas  N1- skubus rentgeninis tyrimas - navikas pašalintas. 4. Krūties sektorius 11x4,5x4 cm su odos lopu 10x3,5 cm, žymėtas metileno mėliu. Krūties audinyje balkšvas neaiškių ribų, standus navikas 1,5x1,3x1 cm (sudėtas visas), nuo artimiausio rezekcijos krašto (dažytas juoda spalva) nutolęs 0,2 cm, nuo odos – 1,5 cm. Šalia naviko fibrozės zona 4x1,8x1 cm (bendras dydis su naviku 4,7 cm).. 1(2a). Fibrocistiniai krūties pokyčiai.  2(2b). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(navikas - 15mm) pT0(sn)(0/3 l/m); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).  IHC/FISH reakcijos atliktos VPC:B23-33188 tyrime:  "Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta, FISH tyrimo rezultatas interpretuojamas įvertinus HER2 IHC tyrimą kaip neigiamas(žr. molekulinio tyrimo aprašymą ir pastabas).  Ki67: proliferacinis indeksas 15%."  Krūties žemo/vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis ir kribriforminis tipas).. 1(2a). Krūties audinys su fibrozės zonomis, pavieniais dilatuotais latakėliais, klotais dvisluoksniu epiteliu.  2(2b). Krūties audinys su fibrozės zonomis, pavieniais dilatuotais latakėliais, klotais dvisluoksniu epiteliu.  3. Trys(3) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4. Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas solidinių/lizdinių, trabekulinių struktūrų iš vidutinio/stambaus kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai, vietomis ryškiai polimorfiškais, hiperchromiškais branduoliais su ryškiomis nukleolėmis; navike iki 10 mitozių/10 DPRL; Limfo-Vaskulinė naviko Invazija (LVI) smulkiose kraujagyslėse/limfagyslėse. Aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais ir kribriforminiais atipinių ląstelių (su nedidelio ir vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS).. nan
answer:  1(

 79%|███████▉  | 525/661 [14:37<03:43,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 biopsinis stulpelis iš BI-RADS 5 darinio ties 10 val.   2 but. 3 biopsiniai stulpeliai iš ploto su mkk ties 6 val.. 1. Biopsinis stulpelis 12 mm.   2. 3 fragmentuoti biopsiniai stulpeliai: I - 10 mm; II - 7 mm; III - 8 mm.. 1. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 8 mm);  (G2; 6 b. pgl. Nottingham sist.)1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 20%.  Žemo laipsnio intraduktalinė intraepitelinė neoplazija (DIN1/DCIS).    2. Krūties fibrocistiniai pokyčiai.. 1. Krūties audinį 1-me bioptate infiltruoja iki 8 mm :   - duktalinės pavienės struktūros ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.  Gretimai analogiškų atipinių ląstelių intraduktaliniai solidiniai proliferatai.  2. Fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ; kalcifikatų nestebima.. Blokas 1:  CK14: neigiama (-) atipinių difuziškai plintančių struktūrų ląstelių membranoje  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose,
answer:  20%.

 80%|███████▉  | 526/661 [14:39<03:44,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)-kraštas - extra - be naviko  2(N2b)-kraštas - extra - be naviko  3(N3)-sarg. l/m - extra - be naviko   4(N1)-sektorius - extra. Skubus rentgeninis tyrimas - matomas 9 mm navikas, 6 mm navikas - nesidiferencijuoja.. nan. 1(2A). Krūties fibrocistiniai pokyčiai. Intraduktalinė papiloma (0,15 cm).  2(2B). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (1 l/m).  4(N1). Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė ("bazinio" imunofenotipo) adenokarcinoma, TNM (Nr.1-Nr.4): pT1b(0,8 cm) pN(sn)0 (0/1 l/m). LVI0(limfovaskulinės naviko invazijos nėra).  ATSKIRAS/SMULKESNIS FRAGMENTAS: Krūties fibrocistiniai pokyčiai. Krūties fibroadenoma (0,3 cm).  ---  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: silpnas(+) branduolinis dažymasis 2%.   HER2 imunohistocheminė reakcija neigiama (0 balų).  Ki67: 80%.. 1(2A). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; 0,15 cm skersmens intraduktalinės proliferacijos židinys.  2(2B). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N3). Nežymi sinusų histiocitozė viename (1) limfmazgyje.  4(N1). KRŪTIES SEKTORIUS: Krūties audinyje - navikas: Solidines naviko struktūras formuoja ląstelės su kiek gausesne tamsoka amfofiline citoplazma, stambaus kalibro apvalios formos netaisyklingais/polimorfiškais su aiškiomis nukleolėmis branduoliais; mitozių navike iki 42 / 10 DPRL.  ATSKIRAS/SMULKESNIS FRAGMENTAS: Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; fibrozuotos stromos su suspaustais kanaliukais gan aiškiai ribotas darinys.. 4(N1). Navikas (blokas 11):  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.   Progesterono receptoriai: silpnas(+) branduolinis dažymasis 2% naviko ląstelių.   HER2: nusidažiusių naviko ląstelių nėra.  CK5: vidutinis(++) membraninis dažymasis 8
answer:  100%

 80%|███████▉  | 527/661 [14:40<03:35,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm ilgio.. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100 % naviko ląstelių.  Progesterono receptoriai: stipri reakcija 40 % naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 45 %.. Bioptate - desmoplastiškoje stromoje ir riebaliniame audinyje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais, trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 67/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100 %.  Progesterono receptoriai: (+++)(brand. r-ja) 40 %.  HER2: neigiama reakcija.  Ki67 proliferacinis aktyvumas 45 %.
answer:  1

 80%|███████▉  | 528/661 [14:42<03:36,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1-2. pjūvio kraštai, planinis. 3. sarginiai l/m, planinis. 4. sektorius, planinis.. 1. Riebalinio audinio fragmentas 3,5x2x0,5 cm. v/m  2. Riebalinio audinio fragmentas 4,5x1,5x0,8 cm. v/m  3. Riebalinio audinio fragmentai, bendras dydis 4,5x3x1 cm. Rasti 4 limfmazgiai, didžiausias 2 cm.  4. Krūties sektorius 8x7,5x3,5 cm, su odos lopu 8x4,5 cm. Krūties audinyje, pjūvyje aiškių ribų, hemoragiškas, heterogeniškas 22x17x11 mm navikas, nuo artimiausio rezekcijos krašto nutolęs 0,5 cm, nuo odos - 1,3 cm. 1,5 cm atstumu nuo naviko, standi fibrozės zona 1,3x1x0,4 cm, nuo artimiausio rezekcijos krašto nutolusi 0,1 cm, nuo odos - 2 cm.. N1 ir N2: Krūties audinys be naviko.  N3: Limfmazgiai (4 l/m) be naviko metastazių; pN0(sn).  N4: Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham); pT2(22mm).  Žemo laipsnio intraduktalinė karcinoma (0,2mm židinys; DCIS/DIN1, kribriforminė).  Krūties fibrocistiniai pokyčiai, fibroadenomatozinė hiperplazija).. N1 ir N2: Krūties ir riebalinis audinys be naviko. Pavienės duktalinės hiperplazijos ir cistiškai dilatuotų latakų zonos.  N3: Limfmazgiai (4 l/m) su reaktyviais pokyčiais, be naviko metastazių.  N4: Krūties audinyje 22mm navikas: mucinų sankaupose netaisyklingi kribroziniai bei solidiniai kompleksai iš minimaliai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  Fokaliai krūties audinys su fibrozės zonomis ir gausiais, dalis cistiškai dilatuotais ar suspaustais latakais, užpildytais eozinofilišku sekretu, klotais blyškiu dvisluoksniu, fokaliai hiperplastišku epiteliu.  Fibrozės zonoje dilatuotas kanaliukas su intraduktaliniais monomorfiškų ląstelių kribroziniais proliferatais (0,2mm židinys).. Fibrozė (30 ir 31 blokai):   CK5: stiprus citoplazminis 100% nusidažymas mioepitelinėse ląstelėse.
answer:  0

 80%|████████  | 529/661 [14:44<03:31,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 15 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 6%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 6%.
answer:  1b

 80%|████████  | 530/661 [14:45<03:32,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a) - viršutinis kraštas, skubu  2(1b) - apatinis kraštas, skubu  3(2) - deš. pažasties sarginiai limfmazgiai, skubu  4(3) - deš. krūties sektorius, planinis  4(3) - deš. krūties sektorius, planinis. 4. Krūties sektorius 7x5,8x3,3 cm be odos. Krūties audinyje, pilkšvas standus, gan aiškių ribų navikas 17x12x10 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm.. 1(1a). Krūties audinys.  2(1b). Krūties audinys.   3(2). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(navikas - 17mm) pN0(sn)(0/3 l/m); LVI-0(Limfo-Vaskulinė naviko Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-29562 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.". 1(1a). Riebalinis audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  2(1b). Riebalinis audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.   3(2). Trys(3) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4. Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas solidinių lizdinių/trabekulinių, kribriforminių, duktalinių (~15%) struktūrų iš vidutinio kalibro ląstelių, vidutiniškai, vietomis ryškiai polimorfiškais, hiperchromiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 18 mitozių/10 DPRL.. nan
answer:  0,

 80%|████████  | 531/661 [14:47<03:25,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 14  mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja smulkios duktalinės struktūros, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20x% naviko ląstelių.  Ki67+ 8%
answer:  1b

 80%|████████  | 532/661 [14:49<03:37,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - be naviko.  2(2b). Kraštai - be naviko.  3. Sarginis l/m(3) - be naviko.  4(1). Sektorius - planinis patologinis tyrimas N1- skubus rentgeninis tyrimas - navikas pašalintas.. 4(1). Krūties sektorius 8,5x5,5x4 cm su oda 7,5x5 cm. Krūties audinyje, kvadrante - pilkšvas, standus, ribotas, skiltėtas navikas 20x20x15mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 0,4 cm.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(2b, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė);  kalcifikatai; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 19,5 mm) N0(sn) (0/3 l/m),   LVI-0 (definityvi limfovaskulinė invazija neidentifikuota).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis, papilinis, komedo tipai). Krūties lobulinė intraepitelinė neoplazija (LCIS). Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė).. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu; kalcifikatai; be naviko.   3(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4(1). NAVIKAS (mikroskopiškai didžiausias naviko matmuo - 19,5 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės, dominuojančios kribriforminės, trabekulinės, lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais fokaliai vezikulizuotais ar skeltais branduoliais su smulkiomis nukleolėmis; mitozių iki 5/10 DPRL. Naviko spindžiuose sekretas ar nekrotinis detritas su PMN, makrofagais. Fokaliai negausi perinavikinė limfocitinė infiltracija.   APLINKA: šalia naviko - kribriforminiai, papiliniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija ar epitelio papiliarizacija, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu. Intralobuliniai smulkių gan monotoniškų, mažai kohezyvių ląstelių proliferatai.   SEKTORIAUS REZEKCIJOS KRAŠTAS: intraduktaliniai naviko kompleksai nuo artimiausio koaguliuoto krašto nutolę 5 mm.. 4(1). Navikas (blokas 16):  HER2: silpna (+) necirkuliari reakcija, 10% naviko ląstelių membranoje.
answer:  1(

 81%|████████  | 533/661 [14:50<03:35,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- Deš. pažasties sarginiai limfmazgiai, skubu  4(3)- Deš. krūties kvadrantas, planinis. 4. Krūties sektorius 6,5x3x10 cm, su odos lopu 3,5x2 cm, žymėtas viela. Vielos projekcijoje pilkšvas, standus aiškių ribų navikas 12x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 6 cm.. 1(ekstra). Krūties audinys.  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(12 mm navikas) pN0(sn)(0/4 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto - vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN3-DIN2, kribriforminis ir papilinis tipai). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. 1(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.      3(ekstra). 34limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.    4. Krūtyje - navikas (12 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais pavienėmis mikropapilomis besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais - stambiais, polimorfiškais, nereguliaraus kontūro ir ovaliais branduoliais ryškiomis nukleolėmis; mitozių 5/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių.. Navikas:  EMA citopl. r-ja. HER2 silpnas dalies membranos nusidažymas 10%.
answer:  0.

 81%|████████  | 534/661 [14:52<03:26,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 11 mm; II - 8 mm; III - 10 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros ir smulkūs kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 8
answer:  1b

 81%|████████  | 535/661 [14:53<03:20,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 7 mm.. Invazinė tubulinė karcinoma (mažiausiai iki 8 mm);  (G1; 3 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 3%.. Krūties audinį 2-se bioptatuose infiltruoja iki 8 mm :   - duktalinės struktūros (100% viso naviko);  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai stromoje ir spindžiuose. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 3% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  95%

 81%|████████  | 536/661 [14:55<03:21,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 biopsinis stulpelis iš kairės krūties BI-RADS 5 darinio   2 but. 3 biopsiniai stulpeliai iš latakų su kalcinatais bei riboto darinio dešinėje krūtyje.. 1. 1 biopsinis stulpelis 15 mm ilgio.   2. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 9 mm.. 1. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 10%. Karštame taške 20%.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.    2. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 10%.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.. 1.Krūties audinį infiltruoja netaisyklingi kribroziniai kompleksai ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.  2. Krūties audinį infiltruoja duktalinės struktūros (<10%), netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. 1. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) cirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių. Karštame taške 20%.  Progesteron
answer:  1.

 81%|████████  | 537/661 [14:57<03:17,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 12 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 15%.
answer:  1b

 81%|████████▏ | 538/661 [14:58<03:16,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  18 G automatine biopsine adata punktuotas ~5x8 mm dydžio neaiškių ribų izoechogeniškas darinys su aplinkine spikuline deformacija dešiniojoje krūtyje ties 12 val. vidurinėje dalyje (atitinkantis MG matomą spikulinės defomacijos židinį), paimti trys biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 10 mm; II - 14 mm; III - 9 mm.. Įtariama invazinė gerai diferencijuota duktalinė arba tubulinė karcinoma (G1; menkas atipinių struktūrų kiekis):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 0%.    Kompleksinis sklerozuojantis pažeidimas: sklerozuojanti adenozė.  Atipinė duktalinė hiperplazija (ADH).. Krūties audinys su smulkiais, šakotais, suspaustais kanaliukais, klotais dvisluoksniu epiteliu. Dalyje kanaliukų kribriforminiai proliferatais su negausiais mikrokalcifikatais, kloti epitelis apvaliais, monotoniškais, hiperchromiškais branduoliais. Stroma fibrozuota, su elastozės zonomis. Tarp šių pokyčių - 3 mm segmente pavienės smulkios tubulės be mioepitelio (CK14-), be branduolių atipijos.. CK14- mioepitelis smulkiuose latakuose. Kribriforminės struktūros CK14+.  Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 0% navi
answer:  0.

 82%|████████▏ | 539/661 [15:00<03:19,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - be naviko.  2(2b). Kraštai - be naviko.  3. Sarginis l/m(4)- be naviko.  4(1). Pašalintas sektorius - planinis patologinis tyrimas. N1-skubus rentgeninis tyrimas - navikas pašalintas.. 4. Krūties sektorius 5,5x2,5x5 cm, su odos lopu 5x1,5 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 16x12x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 2 cm. Navikas sudėtas visas.. 1(2a)(Extra). Riebalinis audinys.  2(2b)(Extra). Riebalinis audinys.  3(Extra). Reaktyvi limfadenopatija (4 l/m).  4(1). Krūties invazyvi blogai diferencijuota (G3; 8 balai pagal Nottingham) metaplastinė (šeivinių ląstelių) karcinoma (su lygiųjų raumenų diferenciacija), SUMINIS TNM: pT1c(15 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Imunofenotipas:   Estrogenų receptoriai: silpnas/vidutinis branduolių nusidažymas 25% naviko ląstelių.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.   HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.   Ki67: 2%.. 1(2a)(Extra). Brandus riebalinis audinys su fibroze ir kraujagyslėmis.  2(2b)(Extra). Brandus riebalinis audinys su fibroze ir kraujagyslėmis.  3(Extra). 4 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.  4(1). Krūties audinyje - ribotas navikas (mikroskopiškai 15 mm), suformuotas fibrozuotoje stromoje pluoštais besidėstančių šeivinių ląstelių šviesiai eozinofiliška citoplazma, vidutinio ir kiek stambesnio kalibro, ovaliais ir pailgais, polimorfiškais, dalis su aiškia nukleole branduoliais; yra ląstelių stambiais, lobulizuotais branduoliais. Mitozių iki 10/10 DPRL. Negausi židininė perinavikinė MMN infiltracija.. 4. Navikas (14 blokas):   Estrogenų receptoriai: silpnas/vidutinis branduolių nusidažymas 25% naviko ląstelių.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.   HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.   Proliferacinis aktyv
answer:  2%.

 82%|████████▏ | 540/661 [15:02<03:21,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pjūvio kraštai, ekstra.  2. Pjūvio kraštai, ekstra.  3. Sarginiai l/m, ekstra.   4. Sektorius, planinis.. 4. Krūties sekotrius 12,5x8,5x3,5 cm su odos lopu 10x2,5cm žymėtas viela. Pjūvyje, viela žymėtoje vietoje - balkšvas 1,5x1,3x1,2 cm, nuo odos nutolęs 4,5 cm, nuo artimiausio rezekcijos krašto - 0,3 cm.Greta naviko - fibrozinis audinys 2x2x1,6 cm plote.Rezekcijos kraštas dažytas mėlynai, tarp pjūvių - juodai. Rastas intramamarinis limfmazgis 0,6 cm.. 1. Krūties audinys.  2. Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 15 mm), pN0(sn)(0/2 l/m), LVI2 (limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).   HER2: reakcija neigiama (1+).. 1. Krūties audinyje židininė fibrozė bei smulkūs kanaliukai kloti dvisluoksniu epiteliu.  2. Fibrozuotame krūties audinyje keli smulkūs kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Šalia gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar epiteliu su apokrinine epitelio metaplazija; Kkli kanaliukai su fokalia epitelio hiperplazija.  3. Vienas limfmazgis su sinusų histiocitoze (1 l/m).  4. Krūties audinyje, hialinizuotoje stromoje plinta navikas (15 mm mikroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių, trabekulinių ir tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su polimorfiškais, hiperchromiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 8/10DPRL. Limfovaskulinis plitimas smulkiose limfagyslėse/kraujagyslėse(LVI2). Krūties audinyje gausūs dilatuoti kanaliukai užpildyti solidinių ir kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta gausūs dilatuoti kanaliukai kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija. Vienas intramamarinis limfmazgis su sinusų histiocitoze.. Blokas 15:  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.
answer:  0

 82%|████████▏ | 541/661 [15:03<03:15,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 4 biopsiniai stulpeliai. 4 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 12 mm; III - 3 mm, IV - 2 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: stipri reakcija 25% naviko ląstelių.   Her2 imuninė reakcija: neigiama (0).   Ki67 proliferacinis aktyvumas 8%.. 4 bioptatai: fibrozinėje stromoje su negausiais lipocitais pabirai ar grandinėlėmis dėstosi naviko ląstelės negausia/vidutinio gausumo švelniai eozinofiliška citoplazma, vidutiniškai polimorfiškais, ovoidiniais ar kiek nereguliaraus kontūro branduoliais prašviesėjusiu chromatinu su išryškėjusia smulkia nukloele; mitozių 6/10 DPRL.. Navikas:   PanCK(+++)(citop. r-ja) 100%.  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.   Progesterono receptoriai: (+/++)(brand. r-ja) 25%.   HER2: reakcijos naviko ląstelėse nėra (0).   Ki67 proliferacinis aktyvumas 8%.   E-cadherin(-).
answer:  3b

 82%|████████▏ | 542/661 [15:05<03:11,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 biopsinis stulpelis iš  I lygio pakitusio l/m , labai įtartino dėl mts   2 but. 3 biopsiniai stulpeliai iš BI-RADS 5 darinio. 1. Biopsinis stulpelis 10 mm ilgio.  2. 3 fragmentuoti biopsiniai stulpeliai: I - 17 mm; II - 5 mm; III - 3 mm.. N1: Limfmazgio bioptatas su duktalinės karcinomos metastaze.  N2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. N1: Limfmazgio bioptatas su žemiau aprašyto naviko židiniais.  N2: Krūties audinį infiltruoja smulkūs duktaliniai ir kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67+ 1
answer:  1b

 82%|████████▏ | 543/661 [15:06<03:06,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 9 mm; III - 7 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 5%.. Bioptatuose (3/3) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais , grandinėlėmis besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 0/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas - vidutinis dalies membranos nusidažymas 40% naviko ląstelių.  Ki67 proliferacinis aktyvumas 5%.  E-cadherin(+++) membr. r-ja 100%
answer:  3b

 82%|████████▏ | 544/661 [15:08<03:06,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  17 G koaksialine adata punktuotas 13x24 mm neaiškių kontūrų ir ribų, šakotas hipoechogeninis darinys, slopinantis ultragarso signalą, dešiniojoje krūtyje ties 7-8 val. labiau link periferijos, čiuopiamo darinio vietoje, BIRADS4c, 18 G automatine biopsine adata paimti keturi biopsiniai stulpeliai histologijai.. 4 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 9 mm; III - 7 mm; IV - 3 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5%.. Trabekulines, pavienes smulkias duktalines naviko struktūras formuoja ląstelės su negausia ar švelniai eozinofiline citoplazma, smulkiais ar vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 3 / 10 DPRL.. Navikas (2 blokas):  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių
answer:  3b

 82%|████████▏ | 545/661 [15:10<03:02,  1.57s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 9 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai, trabekulės iš ryškiai polimorfiškų ląstelių, mitozių iki 16/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 30
answer:  3b

 83%|████████▎ | 546/661 [15:11<03:05,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 sarginiai l/m, ekstra.  2 ėminio aprašas: 1 pjūvio kraštai, ekstra.  3 ėminio aprašas: 2. pjūvio kraštai, ekstra.  4 ėminio aprašas: 4. sektorius, planinis.. 4.  Krūties sektorius 7,5x5x3,5 cm su odos lopu 5x2,5 cm. Pjūvyje balkšvas, standus, skiltėtas navikas 22x16x13 mm nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos – 2 cm.. 1(3)(ekstra). Reaktyvi limfadenopatija (4 l/m).  2(1)(ekstra). Krūties audinys.   3(2)(ekstra). Krūties audinys.   4. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma, suminis TNM: pT2(22 mm navikas) N0(sn)(4 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). Gausūs intranavikiniai limfocitai (TILs). R0(radikali rezekcija).     Naviko imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  Androgenų receptoriai: silpna reakcija 5% naviko ląstelių.  Ki67: proliferacinis indeksas 80%.  HER2:reakcijos nėra (0).. 1(3)(ekstra). 4 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.  2(1)(ekstra). Nežymiai fibrozuotas krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu.   3(2)(ekstra). Nežymiai fibrozuotas krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu.   4. Krūties audinyje - navikas, suformuotas solidinių kompleksų su pavienių spindžių formacijomis, trabekulių ir lizdų. Naviko ląstelės poligonalinės, su gausoka šviesiai eozinofiliška citoplazma fokaliai su negausiais PAS+ mucinais, stambiais, apvaliais ir netolygaus kontūro, ryškiai polimorfiškais branduoliais blyškiai grūdėtu chromatinu, dalis su makronukleolėmis. Mitozių iki 25/10 DPRL. Naviką supa fibrozinė stroma su gausia monomorfonuklearų infiltracija. Naviko nekrozė ~10%.. Blokas 14:  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  Ki67: reakcija branduoliuose, 80% naviko ląstelių.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  CK5: silpna/stipri (+/+++) membraninė reakcija 4
answer:  4.

 83%|████████▎ | 547/661 [15:13<03:09,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)-kraštas - extra - be naviko    2(N2b)-kraštas - extra - be naviko    3(N1)- sektroius- - planinis patologinis tyrimas N1 - skubus rentgeninis tyrimas - navikas .- Atsisakė nuo pažasties duobės l/m - pašalinimo.. 3. Krūties sektorius 11x8x5 cm su odos lopu 10x4,5 cm, žymėtas viela, atskirai tame pačiame inde viela, neprisitvirtinusi prie krūties audinio. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 0,8x0,6x0,5 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos – 5 cm.. 1. Krūties fibrocistiniai pokyčiai.  2. Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis/kribriforminis; židinys - 2,7mm).  3. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sist.) duktalinė karcinoma, pT1a(navikas - 4,5mm); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-40706 tyrime:   "Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 8%."  Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; kribriforminis, mikropapilinis tipas; -komedo tipo nekrozės, mikrokalcifikatai).. 1. Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu.  2. Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu. Krūties audinyje - dilatuotas latakas (2,7mm) su solidiniais, kribriforminiais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS).  3. Krūties fibroziniame audinyje - navikas(mikro - 4,5mm), formuojamas netaisykingų duktalinių, kribriforminių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 4 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su kribriforminiais, mikropapiliniais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS).. 2. Blokas 8:  DCIS: CK14+ mioepitelinės ląstelės periferijoje.   3. Blokas 10, 11:  Navikas be CK14+ mioepitelinių ląstelių sluoksnio.  DCIS: CK14+ mioepitelinės ląstelės periferijoje.
answer:  3(n

 83%|████████▎ | 548/661 [15:15<03:03,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas kairės krūties apatinio lateralinio kvadranto darinys, paimti 3 biopsiniai stulpeliai medžiagos histologiniam ištyrimui.. 3 biopsiniai stulpeliai: I - 15 mm; II - 15 mm; III - 7 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 b. pgl Nottingham sist.) duktalinė karcinoma   (plitimas mažiausiai iki 16,5 mm mikroskopiškai).  Naviko imunofenotipas:  Estrogenų receptoriai: silpna (+) reakcija, 20% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%.. Fibroziname audinyje (3 biopsiniuose stulpeliuose) - trabekulinės, lizdinės, tubulinės (<10 %) struktūros. Naviko ląstelės su negausia, eozinofiliška citoplazma, vidutinio kalibro, netaisyklingo kontūro, vidutiniškai polimorfiškais branduoliais. Mitozių navike iki 1/10DPRL.. Blokas 1:  Estrogenų receptoriai: silpna (+) reakcija, 20% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 30% naviko ląstelių.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliu
answer:  1b

 83%|████████▎ | 549/661 [15:16<03:00,  1.61s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Tyrimo Nr. XXIIIBO-4848. Krūties navikas. Makroskopinis aprašymas : 3 pilkšvo, vietomis gelsvo, volelio formos audinio fragmentai 0,6-2 cm ilgio. 1. Konsultacijai gauta:  - 1 parafino blokas (žymėtas "XXIIIBO-4848");  - 6 histologiniai preparatai (žymėti ""XXIIIBO-4848"", dažyti HE, Ki67, p63, ER, PR, HER2 metodais).    Atlikti HER-2 geno amplifikacijos tyrimą FISH metodu (HER2).. PAPILDYTA  Krūties invazyvi duktalinė karcinoma (ne mažiau kaip gerai diferencijuota / G1 / 5 balai pagal Nottingham).     Estrogenų receptoriai: silpnas-vidutinis branduolių nusidažymas 80% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: ribinė (2+).  Ki67: iki 5%.  ---  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).. Tubulines (70%), negausias smulkias kribrozines naviko struktūras formuoja ląstelės su saikinga švelniai eozinofiline citoplazma, smulkiais ar kiek stambesnio kalibro kiek netaisyklingais, dalis su smulkia nukleole branduoliais; mitozių navike iki 1 / 10 DPRL.. Navikas  Estrogenų receptoriai: silpnas-vidutinis branduolių nusidažymas 80% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas visos membranos nusidažymas 20% naviko ląstelių.
answer:  1.

 83%|████████▎ | 550/661 [15:18<03:05,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a kraštai - skubus tyrimas  2. N2b kraštai - skubus tyrimas  3. N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas  4. N1: pašalintas dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 9,5x6x3 cm su oda 9x3 cm. Odoje rusvas, smulkiai gruoblėtu paviršiumi, iškilęs I darinys 0,7x0,7x0,1 cm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm. Nuo darinio 0,3 cm atstumu pilkšvas, ribotas II darinys 1x0,6x0,4 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm. Krūties audinyje, pilkšvas, standus, neaiškių ribų navikas 16x14x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 2 cm.. 1,2(ekstra). Riebalinis audinys.  3(ekstra). Reaktyvi limfadenopatija (5 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1c(17 mm navikas) pN0(sn)(0/5 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, solidinis tipas). Lobulinė karcinoma in situ (LCIS). Odos seborėjinė keratozė.    Imunofenotipas:   Estrogenų receptoriai: stiprus ir vidutinis branduolių nusidažymas 40% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. 1,2(ekstra). Riebalinis audinys su negausiomis fibrozinėmis septomis.  3(ekstra). 5 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (17 mm) infiltratyviu augimo frontu, suformuotas trabekulinėmis struktūromis, lizdais, grandinėlėmis ir pabirai bei negausiomi stubulėmis (Ecad-) besidėstančių ląstelių negausia ir vidutinio gausumo ryškia eozinofiliška citoplazma, vidutiniais - stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 3/10 DPRL.  Greta dilatuoti latakia ir lobulės iš analogiškų navikui ląstelių; Negausūs dilatuoti kanaliukai su intraduktaliniais solidiniais proliferatais iš ląstelių vidutiniškai polimorfiškais branduoliais.   Odoje epidermio dariniai suformuotas bazaloidinių ląstelių su fokaline bazinio sluoksnio hiperpigmentacija ir pavienėmis raginėmis cistomis.. Navikas:  E-cadherin(+) trūkinėjanti membr. r-ja  Ki67 proliferacinis aktyvumas ---- %.  CK5+ išlaikytas mioepitelinis sluoknsis, heterogeniška populiacija hiperplazijos zonose.
answer:  1.

 83%|████████▎ | 551/661 [15:19<02:57,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. sarginis l/m, ekstra.   2. deš krūtis, planinis.. 2. Krūtis 703 gramų svorio, 18,5x13,5x3,5 cm. Krūties audinyje, centrinėje dalyje - balkšvas, standus, nelygiais kraštais navikas 1,5x1,3x0,8 mm, nuo odos nutolęs 1,4 cm, nuo artimiausio rezekcijos krašto - 4,5 cm.. N1: Limfmazgis (1 l/m) be naviko; pN0(sn).  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c (15mm).. N1: Limfmazgis (1 l/m) be naviko.  N2: Krūties audinyje 15mm navikas: kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.  Rezkcijos kraštas be naviko.. nan
answer:  1a

 84%|████████▎ | 552/661 [15:21<03:06,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. kairė krūtis su kairės pažasties l/m, planinis. Krūtis 1552 g svorio, 24x22x7 cm, su pažasties narveliena 8x8x2 cm, spenelis įtrauktas.   Spenelio projekcijoje, balkšvas standus I navikas 1,5x1,5x0,9 cm, nuo artimiausio rezekcijos krašto nutolęs 6 cm, nuo odos - 0,7 cm.   5,5 cm nuo I naviko, II balkšvas standus, kiek neaiškių ribų navikas - 0,7x0,6x0,6 cm, nuo artimiausio rezekcijos krašto nutolęs 0,7 cm, nuo odos - 4,5 cm.   7 cm nuo I naviko, balkšvas, standus aiškių ribų I mazgas 0,7x0,6x0,6 cm, nuo artimiausio rezekcijos krašto nutolęs 7 cm.   5 cm nuo I mazgo, analogiškas balkšvas II mazgas 0,6x0,4x0,4 cm, nuo artimiausio rezekcijos krašto nutolęs 5 cm.   Krūties odoje rusvas, elastingas mazgas 0,6x0,5x0,1 cm, nuo artimiausio odos rezekcijos krašto nutolęs 1,4 cm.   Pažasties narvelienoje rasta 16 limfmazgių iki 2 cm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė-mikropapilinė karcinoma;   pT(m)1c(15 mm, 7 mm, 1 mm, 2,5 mm)   pN2a(7/16 ; ekstranodalinis plitimas)   pR0 (radikalus pašalinimas).  Karcinomos metastazės limfmazgyje imunotipas:  HER2: reakcija neigiama (1+).  Imunotipas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.    Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS; kribrozinio tipo).  Krūties fibroadenoma.  Kapiliarinė odos hemangioma.. Krūties audinio 1-ą (15 mm), 2-ą (7 mm) naviką, 2-ą mazgą (1 mm) ir atsitiktinį židinį (2,5 mm) krūties audinyje formuoja infiltruojančios pavienės duktalinės ir gausios pseufopapilinės/trabekulinės struktūros iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL. Operaciniai kraštai be matomų pokyčių (artimiausias 2-as navikas - 3 mm).  Analogiškų ląstelių tinklinės intraduktalinės struktūros negausiuose latakuose aplink invazinius židinius.  1-as mazgas (6 mm) ir atsitiktinai rastas 4 mm mazgas: ribotas navikas, suformuotas kolageninės stromos su suspaustais šakotais ir negausiais smulkiais latakais, klotais dvisluoksniu epiteliu.  Analogiškų ląstelių iki 13 mm metastazės 7-se/16 limfmazgiuose; stebimas ekstranodalinis plitimas.  Odoje gausiai kompaktiškai besidėstančių kapiliarų suformuotas odos darinys.. Blokas 17:  EMA: stipri teigiama (+++)  necirkuliari (išorinė) membraninė reakcija 100 proc. atipinėse struktūrose  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.
answer:  2.

 84%|████████▎ | 553/661 [15:23<03:11,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Galutinė patologinė diagnozė: Krūties invazyvi duktalinė karcinoma, 0,4 mm židinys (1/5 bioptatų). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, solidinis tipas(2/5 bioptatų). Naviko imunofenotipas: Estrogenų receptoriai: 100%. Progesterono receptoriai: neigiama reakcija. Her2 imuninė reakcija: neigiama (1+). Ki67 20%.. 4(1). Krūties liauka 320 gramų svorio, 12x14x5 cm su odos lopu (apatinėje krūties dalyje) 6,5x2,2 cm. Krūties audinyje, 10x11x4,5 cm plote, balkšva, standi, netaisyklingų kontūrų, besiliejanti fibrozės zona; sustandėjusi ir formuojanti balkšvą zoną, apatiniame lateraliniame kvadrante 2,5x2x2 cm plote; fibrozės zona siekia rezekcijos kraštą pospenelinėje zonoje, nuo giliojo rezekcijos krašto nutolusi 0,1 cm; fibrozės zona su hemoragijomis.  5(4). Riebalinio audinio fragmentai, bendras dydis 3x2x0,5 cm. Rasti 7 limfmazgiai iki 1 cm. v/m. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Duktalinės karcinomos metastazė limfmazgyje 3 mm (1/1 l/m).    4. Krūties vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma su daline mikropapiline ir mucinine diferenciacija, SUMINIS TNM: pT2(m)(25 mm, 8 mm, 7 mm, 2,3 mm, 2,2 mm, 1 mm navikai) pN1a(sn)(3/6 l/m MTS iki 5 mm) LVI-2(limfovaskulinė invazija). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 kribriforminis, solidinis, komedo tipai), DCIS nuo priekinio rezekcijos paviršiaus nutolęs 0,8 mm, nuo giliojo - 0,6 mm.    Naviko imunofenotipas (biopsijoje):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 20%.    5. Papildomi limfmazgiai: duktalinės karcinomos metastazės limfmazgiuose (2/5 l/m iki 5 mm). Riebalinis audinys.. 1(ekstra). Krūties audinys su fibrozės zonomis kanaliukais ir lobulėmis, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis kanaliukais ir lobulėmis, klotais dvisluoksniu epiteliu.  3(ekstra). 1 limfmazgis su aprašyto naviko metastaze 3 mm.    4. Krūtyje - navikas (mm, 8 mm, 7 mm, 2,3 mm, 2,2 mm, 1 mm navikai) infiltratyviu augimo frontu, suformuotas trabekulinėmis struktūromis, lizdais, mikropapilinėmis struktūromis su aplinkiniais ekstarląsteliniais mucinais besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais,  nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 7/10 DPRL. Limfovaskulinė invazija.  Greta gausūs dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių; DCIS nuo paviršinio rezekcijos krašto nutolęs 0,8 mm, giliojo - 0,6 mm  Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaus kanaliukų zonos.. HER2: silpnas dalies membranos nusidažymas 30% naviko ląstelių.
answer:  0

 84%|████████▍ | 554/661 [15:25<03:00,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 8 mm; II - 9 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 10%.
answer:  1a

 84%|████████▍ | 555/661 [15:26<02:51,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 14 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja netaisyklingi kribroziniai/solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 84%|████████▍ | 556/661 [15:28<03:00,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu  3(2). Deš. pažasties sarginiai limfmazgiai, skubu  4(3). Deš. krūties sektorius, planinis. 4(3). Krūties sektorius 12,5x9x6 cm su odos lopu 9x5 cm. Pjūvyje balkšvas, standus, neaiškių ribų I navikas 2,7x2x2 cm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos – 2,2 cm. 1,5 cm atstumu nuo I-ojo naviko balkšvas, standus, neaiškių ribų II navikas 0,4x0,6x0,6 cm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 1,5 cm, nuo odos - 2,6 cm. Bendras didžiausias navikų matmuo 3,6 cm.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas riebalinis audinys; be naviko.   2(1b, ekstra). "Apatinis kraštas": fibrozuotas krūties audinys; be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(3). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT2(m) (navikai: I - 27 mm; II - 7 mm) N0(sn) (0/2 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2:reakcijos nėra (0).    Krūties lobulinė intraepitelinė neoplazija (LCIS; pleomorfinis ir konvencinis variantas).  Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas, brandžių lipocitų suformuotas audinys; be naviko.   2(1b, ekstra). "Apatinis kraštas": fibrozuotas krūties audinys su dilatuotais ar suspaustais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.    4(3). NAVIKAS (du židiniai: I - 27 mm; II - 7 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", fokaliai vangiai mazguotos fokaliai "kohezyvesnės" solidinės naviko struktūros, suformuotos mažai kohezyvių vidutiniškai polimorfiškų ląstelių, negausia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais hiperchromiškais branduoliais; fokaliai mitozių iki 22/10 DPRL; fokaliai negausūs intranavikiniai limfocitai; mikrokalcifikatai. Nedideli židiniai su puriu jungiamuoju audiniu, dilatuotomis kraujagyslėmis, fokalinė fibrozė su hemosiderofagais, pavieniais limfocitais (g.b. ankstesnės biopsijos zonos). Limfovaskulinė naviko invazija smulkiose šakose.    APLINKA: zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais; dalis su nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: nežymiai fibrozuotas riebalinis audinys; be naviko.. 4(3). Navikas (blokas 17):  HER2: reakcijos naviko ląstelių membranoje nėra.  Navikas (blokas 22): E-Cadherin(+/++/+++) trūkinėjanti membraninė r-ja ~30% naviko ląstelių; p120-Catenin(+) citoplazminė r-ja, su fokaliai išryškėjančia trūkinėjančia membranin
answer:  10%

 84%|████████▍ | 557/661 [15:30<02:51,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpeliai. Biopsinis stulpelis 14 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis iki 20%.. Krūties audinį infiltruoja netaisyklingi kribroziniai/solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 10
answer:  3b

 84%|████████▍ | 558/661 [15:31<02:55,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pjūvio kraštas, ekstra.  2. Pjūvio kraštas, ekstra.   3. Sarginiai l/m, ekstra.   4. Sektorius, planinis.. 4. Krūties sektorius 10x7,5x4 cm su oda 7x4 cm. Pjūvyje - balkšvas, standus, neaiškių ribų navikas 2,1x1,8x1,1 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos – 4 cm.. PAPILDYTAS ATSAKYMAS HER2 FISH TYRIMU:   1(ekstra). "Kraštas": fibrozuotas riebalinis audinys; be naviko.   2(ekstra). "Kraštas": fibrozuotas krūties audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma (su tikėtinu mikropapiliniu komponentu, ~20%), SUMINIS TNM:   pT1c (mikroskopiškai navikas 15 mm, žr. pastabą) N0(sn) (0/3 l/m),    LVI-0 (definityvi limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.   HER2 geno amplifikacija nenustatyta (žr. molekulinio tyrimo aprašymą ir pastabas).   Navikas nuo sektoriaus rezekcijos krašto nutolęs 0,17 mm.. 1(ekstra). "Kraštas": fibrozuotas brandžių lipocitų suformuotas audinys; be naviko.   2(ekstra). "Kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.    4. NAVIKAS (mikroskopiškai išmatuojamas didžiausias naviko matmuo - 15 mm; su aplinkine fibrozės zona ~ 18 mm skersmens -židinys: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios kribriforminės, trabekulinės, lizdinės, solidinės naviko struktūros su fokaline mikropapilinių struktūrų formacija. Naviko ląstelės vidutiniškai polimorfiškos, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 25/10 DPRL. Fokaliai gausi perinavikinė limfocitinė infiltracija. Pavieniai mikrokalcifikatai.   SEKTORIAUS REZEKCIJOS KRAŠTAS: navikas nutolęs 0,17 mm.. 4. Navikas (blokas 17):  HER2: vidutinė (++) necirkuliari reakcija, 5% naviko ląstelių membranoje.   GATA3(+++)(brand.r-ja)75%; EMA(+); Synaptophysin(-).
answer:  3.

 85%|████████▍ | 559/661 [15:33<02:50,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  14 G automatine biopsine adata punktuoti didelės apimties (apimantys mažiausiai visą viršutinį lateralinį kvadrantą) navikiškai pakitę audiniai su daugybiniais mikrokalcinatais kairės krūties viršutiniame lateraliniame kvadrante, paimti penki biopsiniai stulpeliai histologijai.. 5 biopsiniai stulpeliai: I - 18 mm; II - 7 mm; III - 7 mm; IV - 9 mm; V - 5 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 8% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 30%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 14/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 8% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 100% naviko ląstel
answer:  3.

 85%|████████▍ | 560/661 [15:35<02:45,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 9 mm; III - 9 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 10%.. Bioptatuose (3/3) - fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, kribriforminėmis struktūromis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio-stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 6/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67 proliferacinis aktyvumas 10%.  CK14(-); Synaptophysin(-);
answer:  3b

 85%|████████▍ | 561/661 [15:36<02:49,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a ir N2b kraštai - skubus tyrimas - be naviko  2 ėminio aprašas: N2b kraštai - skubus tyrimas - be naviko  3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis  - skubus tyrimas - 4l/m be naviko  4 ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 93,5x5,5x4,5 cm su odos lopu 7x2,5cm, su įtrauktu speneliu. Krūties audinyje, spenelio projekcijoje - pilkšvas, standus, neaiškių ribų navikas 22x16x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm.. Paruošti pjūviai Prosigna tyrimui.    1(3). Kairės pažasties sarginis limfmazgis. Reaktyvi limfadenopatija (6 l/m).   2(N2a). N2a kraštai. Krūties audinys. Naviko plitimo nėra.   3(N2b). N2a kraštai. Krūties audinys. Naviko plitimo nėra.   4(1). Kairės krūties kvadrantas. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham sistemą) duktalinė karcinoma, pT4b (22 mm išopėjęs navikas) N0(sn)(6 l/m) LVI-0 (limfovaskulinė invazija neidentifikuota). Radikalus pašalinimas (R0).  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis, kribriforminis tipai).  Naviko imunofenotipas:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 20-25%.. 1(3). Kairės pažasties sarginis limfmazgis. 6 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.  2(N2a). N2a kraštai. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   3(N2b). N2a kraštai. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   4(1). Kairės krūties kvadrantas. Krūties audinyje - desmoplastiškoje stromoje plintantis navikas, suformuotas trabekulių, grandinėlių, solidinių kompleksų, pavienių tubulių (<10%). Naviko ląstelės su vidutinio gausumo, šviesiai eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais. Mitozių navike 9/10DPRL. Navikas plinta spenelyje, epidermis ties naviko struktūromis fokaliai išopėjęs.   Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių.  Atokiau krūties latakai su cistine dilatacija ir apokrine metaplazija.. Blokas 18: CD31+ endotelis (limfovaskulinė invazija neidentifikuota)  Blokas 25:  E-Cadherin: (++/+++)(membr.r-ja)100%  HER2: silpna (+) cirkuliari reakcija, 5%  naviko ląstelių membranoje.  P120: (++/+++)(membr.r-ja)100%
answer:  3.

 85%|████████▌ | 562/661 [15:38<02:46,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Kairė krūtis su limfmazgiais, planinis. Krūtis 500 g svorio, 20x16x6 cm, su pažasties narveliena 11x7x5 cm. Spenelis smulkiai gruoblėtas, trapiu paviršiumi 1,3x0,8 cm plote.   Krūties audinyje navikiniai pokyčiai apimantys 3,7x2x3,3 cm, navikų židiniai balkšvi, standūs, spikulinių kraštų:  - I navikas 2,4x1,5x3,2 cm esantis 0,4 cm nuo artimiausio rezekcijos pjūvio, siekia dermą.   - II naviko židinys 1,4x1,2x1,3 cm, nuo I naviko nutolęs 0,5 cm, su juo jungiasi standžiais fibrozės pluoštais, nuo rezekcijos krašto nutolęs 1,3 cm, nuo odos - 1,8 cm.  Krūties audinyje 2 cm nuo naviko fibrozės zona su dilatuotais latakais 3x2x2 cm plote, nuo rezekcijos krašto nutolę 0,5 cm.   Rasta 12 limfmazgių su židiniais iki 1,4 cm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;   pT(m)2(24 mm ir 14 mm) pN2a(8/12) pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%, vietomis iki 20%.. Krūties audinį infiltruoja 2ų navikų židiniuose negausios duktalinės struktūros, smulkūs netaisyklingi kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių 20-30/10 DPRL. Operaciniai kraštai be matomų pokyčių.  Limfmazgiai: aprašyto naviko iki 12 mm plitimas 8-se/12 limfmazgiuose; stebimas ekstranodulinis plitimas.. nan
answer:  0,

 85%|████████▌ | 563/661 [15:40<03:03,  1.87s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2). Dešinės pažasties sarginis limfmazgis - extra.   2(N4a). kraštas, skubu  3(N4b). kraštas, skubu  4(N5). kairės pažasties sarg. l/m, skubu  5(N1). Pašalinta dešinė krūtis - planinis tyrimas  6(N3). Kairės krūties markiruotas kvadrantas - planinis tyrimas. 5. Krūtis 1131 gramų svorio, 24x17,5x7 cm. Pjūvyje fibrozės zona 7,5x6x4,5 cm. Krūties audinyje, viršutiniame lateraliniame kvadrante, fibrozės zonoje - balkšvas, elastingas, nehomogeniškas I navikas su cistinėmis ertmėmis 22x20x17 mm, nuo odos nutolęs 4 cm, nuo giliojo rezekcijos krašto - 3,5 cm. Šalia I naviko - pilkšvas, aiškių ribų II navikas 10x8x7 mm, nuo I naviko nutolęs 0,5 cm, nuo giliojo rezekcijos krašto nutolęs 5 cm, nuo odos - 5 cm. Viršutinių kvadrantų riboje, balkšvas, standus darinys 1,6x1,1x0,7 cm, nuo odos nutolęs 3,5 cm, nuo giliojo rezekcijos krašto - 3,5 cm.   6. Krūties sektorius 248 gramų svorio, 13x7,5x5 cm su odos lopu 10x3,5 cm, žymėtas viela. Vielos projekcijoje, rusva I fibrozės zona 1,9x1x0,8 cm, nuo odos nutolęs 3 cm, nuo giliojo rezekcijos krašto - 0,7 cm. Pjūvyje, II fibrozės zona 3,8x3,2x2,9 cm, nuo odos nutolęs 0,8 cm, nuo giliojo rezekcijos krašto 0,9 cm.. 1(N2, "Dešinės pažasties sarginis limfmazgis"). Reaktyvi limfadenopatija (3 l/m).  2(N4a, "kraštas"). Krūties fibrocistiniai pokyčiai.  3(N4b, kraštas"). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, papilinis tipas).  4(N5, "kairės pažasties sarginis l/m"). Reaktyvi limfadenopatija (2 l/m).  5(N1, "dešinė krūtis"). Krūties invazyvi multicentrinė adenokarcinoma, TNM (Nr.1, Nr.2, Nr.3, Nr.5): pT1c(m) (1,5 cm, 1 cm, 0,8 cm naviko židiniai) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės naviko invazijos nėra). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, papilinis, kribriforminis tipai). R0(radikalus navikų pašalinimas).  Navikų diferencijacijos laipsniai:  - vidutiniškai diferencijuota / G2 / 7 balai pagal Nottingham (1 cm ir 0,8 cm židiniai),  - blogai diferencijuota / G3 / 8 balai pagal Nottingham (1,5 cm židinys).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama.  Ki67: 10% (hot spot 20%).  ---  6(N3, "Kairės krūties markiruotas kvadrantas"). Krūties invazyvi duktalinės adenokarcinoma (vidutiniškai diferencijuota / G2 / 7 balai pagal Nottingham), TNM (Nr.4, Nr.6): pT1c(1,7 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės naviko invazijos nėra). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama.  Ki67: 10% (hot spot 20%).. 1(N2, "Dešinės pažasties sarginis limfmazgis"). Nežymi sinusų histiocitozė trijuose (3) limfmazgiuose.  2(N4a, "kraštas"). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N4b, kraštas"). Krūties audinyje - negausūs vidutinio kalibro kanaliukai su kribriforminiais, negausiais papiliniais atipinių ląstelių proliferatais.  4(N5, "kairės pažasties sarginis l/m"). Nežymi sinusų histiocitozė dviejuose (2) limfmazgiuose.  5(N1, "dešinė krūtis"). Krūties audinyje - dauginiai (iki 3) naviko židiniai (1,5 cm, 1 cm ir 0,8 cm):  A) Stambiausias (1,5 cm) židinys: solidines, trabekulines naviko struktūras formuoja ląstelės su gan gausia amfofiline citoplazma, vidutinio kalibro apvalios formos netaisyklingais/polimorfiškais branduoliais, mitozių navike iki 20 / 10 DPRL;  B) Smulkesni (1 cm ir 0,8 cm) židiniai: kribriformines, trabekulines, negausias susiliejančias tubulines navikų struktūras formuoja ląstelės su negausia ar kiek gausesne blyškia citoplazma, vidutinio kalibro apvalios formos netaisyklingais/polimorfiškais branduoliais, mitozių navikuose iki 7 / 10 DPRL.  Šalia navikų krūties audinyje - stambūs kanaliukai su kribriforminiais, negausiais papiliniais atipinių ląstelių proliferatais.  6(N3, "Kairės krūties markiruotas kvadrantas"). Krūties audinyje - A) invazyvi karcinoma (kribriformines, trabekulines, negausias susiliejančias tubulines navikų struktūras formuoja ląstelės su negausia ar kiek gausesne blyškia citoplazma, vidutinio kalibro apvalios formos netaisyklingais/polimorfiškais branduoliais, mitozių navikuose iki 12 / 10 DPRL), B) krūties audinyje - vidutinio kalibro ar stambūs kanaliukai su kribriforminiais atipinių ląstelių proliferatais.. 5(N1, "dešinė krūtis").  33 blokas (1,5 cm navikas):  Her2 nusidažiusių naviko ląstelių nėra.  Ki67 10% (hot spot 20%). CK5(++/+++)(citoplazminė r-ja), 5%.  39 blokas (1,0 cm navikas): Her2 nusidažiusių naviko ląstelių nėra.  47 blokas (0,8 cm navikas): H
answer:  0,

 85%|████████▌ | 564/661 [15:42<02:49,  1.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 11 mm; II - 10 mm; III - 8 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 80% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 2%.. Bioptatuose (3/3) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos grandinėlėmis ir pabirai besidėstančių ląstelių negausia eozinofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio kalibro, dalis ekscentriškais, branduoliais; mitozių 1/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 80%.  HER2: nusidažiusių naviko ląstelių membranų nėra.  Ki67 proliferacinis aktyvumas 2%.  E-cadherin(-).
answer:  2

 85%|████████▌ | 565/661 [15:44<02:50,  1.78s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Kairės pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: Kairė krūtis, planinis. 2. Krūtis 710 gramų svorio, 22x17x6 cm. Krūties audinyje, apatinių kvadrantų riboje balkšvas, standus, neaiškių ribų navikas 26x16x12 mm, nuo odos nutolęs 2 cm, nuo gilioji rezekcijos krašto - 1 cm. Aplink naviką fibrozės zona 4,5x4,5x2,2 cm, nuo odos zona nutolusi 1,2 cm, nuo giliojo rezekcijos krašto - 0,2 cm. Spenelis įtrauktas. Odoje rusvas, smulkiai gruoblėtas darinys 1,5x1,1x0,3 cm, nuo artimiausio odos rezekcijos krašto nutolęs 0,8 cm.. 1(Extra). Reaktyvi limfadenopatija su dermatopatinės limfadenopatijos požymiais (4 l/m).  2. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(31 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas (R0) (naviko atstumas nuo 1 mm nuo rezekcijos krašto).  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties inkapsuliuota papilinė karcinoma (11 mm) ir išplitusi vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė) (45 mm plote).  Krūties intraduktalinė papiloma.  Odos seborėjinė keratozė.. 1(Extra). 4 limfmazgiai su fokaline parakortekso hiperplazija su histiocitų agregatais ir sinusų histiocitoze.  2. SPENELIS: normali histologinė struktūra.  NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai 31 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių smulkių tubulinių, kribriforminių ir negausių trabekulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 1/10 DPRL. Naviko atstumas nuo 1 mm nuo rezekcijos krašto.  Šalia naviko - cistinis darinys (11 mm) fibrozuota siena su židinine MMN infiltracija ir siderofagais su daugiabranduolėmis gigantinėmis ląstelėmis, vidiniame paviršiuje klotas epiteliu su kribriforminėmis ir besiliejančiomis papilinėmis struktūromis, suformuotomis ląstelių eozinofiliška citoplazma, vidutinio kalibro, ovaliais, dalis skeltais ar su smulkia nukleole branduoliais. Aplink naviką (45 mm plote) - gausūs dilatuoti kanaliukai su solidiniais ir kribriforminiais analogiškų navikui ląstelių proliferatais; dilatuotas kanaliukas su papilinėmis intraduktalinėmis struktūromis, klotomis dvisluoksniu stulpiniu epiteliu; grupės kanaliukų su apokrinine metaplazija.   ODA: darinys su epidermio papiliarizacija ir neryškia akantoze ir hiperkeratoze, bazinių ląstelių hiperplazija ir hiperpigmentacija bei smulkiomis keratininėmis cistomis.. nan
answer:  0.

 86%|████████▌ | 566/661 [15:45<02:44,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a - skubu - kraštai  2. N2b kraštai - skubus tyrimas - be naviko  3. N3: kairės pažasties sarginis limfmazgis  - skubus tyrimas 4l/m be naviko  4. N1: kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 13x8x4 cm su oda 11,5x4 cm, žymėtas 2 vielomis:   - I vielos projekcijoje - balkšvas, standus, neaiškių ribų navikas 1,8x1,7x1,5 cm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 4,5 cm.  - II vielos projekcijoje - fibrozės zona 3x1,5x1,3 cm, siekia gilųjį rezekcijos kraštą, nuo odos - 3,5 cm.. N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(18mm).  N2ab: Krūties audinys be naviko.  N3: Karcinomos metastazės viename limfmazgyje (iki 1mm židiniai, 1 iš 4 l/m); pN1mi(sn).. N1: Krūties audinyje 18mm navikas: negausios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai neryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.  N2ab: Krūties audinys be naviko.  N3: Iš į parafiną įlietos medžiagos - viename limfmazgyje (1 iš 4 l/m) karcinomos metastazės iki 1mm.. nan
answer:  0.

 86%|████████▌ | 567/661 [15:47<02:42,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 18 G automatine biopsine adata punktuotas ~10x17 mm dydžio, netolygiai iki ~7,0 mm sustorėjusiu žieviniu sluoksniu l/m dešiniosios pažasties I zonoje, paimti trys biopsiniai stulpeliai histologijai (I buteliukas).   2 ėminio aprašas: 2. 18 G automatine biopsine adata punktuotas ~7x15 mm dydžio, netolygiai iki ~5,0 mm sustorėjusiu žieviniu sluoksniu l/m kairiosios pažasties I zonoje, paimti trys biopsiniai stulpeliai histologijai (II buteliukas). @#3 ėminio aprašas: 3. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~60x65 mm dydžio navikas kairiojoje krūtyje viršutiniame lateraliniame kvadrante, paimti penki biopsiniai stulpeliai histologijai (III buteliukas).. 1. 3 biopsiniai stulpeliai: I - 11 mm; II - 8 mm; III - 14 mm.  2. 3 biopsiniai stulpeliai: I - 8 mm; II - 6 mm; III - 7 mm.  3. 5 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 9 mm; III - 7 mm; IV - 7 mm; V - 3 mm.. 1. Limfmazgio 3 stulpeliai be patologinių pokyčių.    2. Limfmazgio 3 stulpeliai be patologinių pokyčių.    3. Krūties invazyvi gerai diferencijuota (G1) mucininė karcinoma (mažiausiai 11 mm skersmens) 5-se bioptatuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 5% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 2%.. 3. Krūties 5-se stulpeliuose naviko struktūras (infiltruojančias iki 11 mm ir išsidėsčiusias gausiuose ekstraląsteliniuose mucinuose) formuoja ląstelės su saikinga citoplazma, vidutinio dydžio saikingai polimorfiškais, dalis su nukleole branduoliais; mitozių navike iki 1 / 10 DPRL.. Blokas 7:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) necirkuliari reakcija, 40%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 2% naviko ląstelių.  Progesterono receptoriai: stipri
answer:  100%

 86%|████████▌ | 568/661 [15:49<02:43,  1.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. retroarveolinė sritis - extra  2. limfmazgiai - extra  N2- pašalinti sarginai l/n- be naviko - 1 mikromts iš 3 l/m   3. N1- pašalinta retroareoliarinė sritis- DCIS įtarimas - papildomas kraštas - planinis tyrimas  4. N3 - pašalinta liauka -planinis patologinis tyrimas@# Skubus rentgeninis N1 tyrimas - pašalintas 28 mm navikas. 3. Riebalinio audinio fragmentas 2,5x1x0,5 cm.v/m  4. Krūties liauka 164 gr. svorio, 16x14x4 cm  su odos lopu 6,5x2,5 cm ir atskiri krūties audinio fragmentai, bendras dydis 4x4x0,5 cm. Krūties audinyje balkšvas, standus, aiškių ribų navikas 3,8x2,5x1,8 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos  - 1 cm. Krūties audinyje, 5 cm nuo naviko pilkšvas apvalus, elastingas darinys 0,9x0,7x0,5 cm, nuo rezekcijos krašto nutolęs 0,8 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/3 l/m, 2,5 mm).  3. Krūties audinys.  4. Krūties invazyvi blogai diferencijuota (G3; 9 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT2(navikas 38 mm), pN1a(sn)(1/3 l/m, 2,5 mm), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Progesterono receptoriai: reakcijos nėra.  Krūties fibroadenoma. Fibrocistiniai krūties pokyčiai.. 1. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu su fokalia apokrinine epitelio metaplazija.  2. Viename limfmazgyje iš trijų (1/3 l/m) žemiau aprašyto naviko metastazė iki 2,5 mm.  3. Krūties audinyje lobulės klotos dvisluoksniu epiteliu.  4. Krūties audinyje, fibrozuotoje stromoje plinta navikas (38 mm makroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas stambių solidinių, fokaliai susiliejančių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su ryškiai polimorfiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 63/10DPRL. Limfovaskulinis plitimas (LVI2). Navikas nuo artimiausio rezekcijos krašto nutolęs per 1 mm. Krūties audinyje darinys (9 mm) suformuotas fibromiksoidinės proliferuojančių fibroblastų stromos su suspaustais, šakotais vidutinio kalibro ir kiek dilatuotais latakais, klotais dvisluoksniu epiteliu. Aplinkiniame krūties audinyje nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar epiteliu au apokrinine epitelio metaplazija.. Blokas 1:  CK14: mioepitelinis sluoksnis (+).  Blokas 24:  HER2: reakcijos naviko ląstelių membranoje nėra.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.
answer:  1.

 86%|████████▌ | 569/661 [15:51<02:48,  1.83s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas - be naviko   2(N2b) - kraštas - skubus tyrimas - be naviko  3(N1) - pašalintas kairės krūties kvadrantas kartu su kairės pažasties limfmazgiais. (keli limfmazgiai čiuopiasi pačiame kvadranto lateraliniame krašte). 3(1). Krūties sektorius 12,5x8,5x5 cm su oda 10,5x6 cm. Krūties audinyje - balkšvas, standus, neaiškių ribų navikas 32x30x18 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1 cm. Sektoriuje rasti 3 limfmazgiai iki 0,6 cm. Atskiri riebalinio audinio fragmentai, bendras dydis 5,5x5x1,7 cm, su 7 limfmazgiais iki 1,2 cm.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.     3(1). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT2(m) (du naviko židiniai: I - 32 mm; II - 0,82 mm) N2a (mts 5/10 l/m; iki 8 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė). Kalcifikatai.   Sektoriaus rezekcijos krašte - koaguliacinių artefaktų zonos su kalcifikatais; DCIS komponentas nutolęs 2,9 mm.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys su deformuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(1). NAVIKAS (I - 32 mm; II - 0,82 mm, smulkus satelitinis židinys šalia in situ komponento): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta retos besiliejančios duktalinės, trabekulinės, lizdinės, nedidelės solidinės ir lizdinės naviko struktūros, suformuotos vidutiniškai ar ryškiau polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki 20/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Gausūs mikrokalcifikatai.  APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis ir gausiai kalcifikatais. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti, kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.   LIMFMAZGIAI(10): penkiuose (5) limfmazgiuose aukščiau aprašyto naviko metastazės, iki 8 mm skersmens, su ekstranodaliniu plitimu.  SEKTORIAUS REZEKCIJOS KRAŠTAS: in situ komponentas nutolęs 2,9 mm; invazyvus navikas - 2,4 mm; krašte - ryškiai koaguliuotos zonos su kalcifikatais.. 3(1). Navikas (blokas 5):  EMA(+) daugiau citoplazminė r-ja dalyje naviko ląstelių.   HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.
answer:  3(

 86%|████████▌ | 570/661 [15:53<02:42,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštas - skubus tyrimas - be naviko  2 ėminio aprašas: N2b kraštas - skubus tyrimas - be naviko  3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis -  skubus tyrimas - 1 l/m be naviko  4(1)pašalintas kairės krūties kvadrantas - planinis tyrimas. 4(1). Krūties sektorius 9x5x3 cm su odos lopu 8x3 cm, žymėtas viela, markiruotas metilėno mėliu. Vielos projekcijoje, pjūvyje - balkšvas, standus, aiškių ribu navikas 1,4x0,7x1,2 cm (histologiniam tyrimui paimtas visas), nuo artimiausio rezekcijos krašto (patologijos skyriuje dažyto žaliu tušu) nutolęs mažiau 0,1 cm, nuo odos – 1,5 cm.. 1(2a). Fokalinė krūties audinio fibrozė.  2(2b). Fokalinė krūties audinio fibrozė.  3(3). Reaktyvi limfadenopatija (1 l/m).  4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,4 cm) pn(SN)0 (0/1 l/m). LVI0(limfovaskulinės invazijos nėra).     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5%.. 1(2a). Krūties audinyje - negausūs fibrozės židiniai su smulkiais ar kiek stambesnio kalibro kanaliukais, išklotais dvisluoksniu epiteliu.  2(2b). Krūties audinyje - negausūs fibrozės židiniai su smulkiais ar kiek stambesnio kalibro kanaliukais, išklotais dvisluoksniu epiteliu.  3(3). Nežymi sinusų histiocitozė viename (1) limfmazgyje.  4(1). Krūties audinyje - navikas: smulkias ar kiek stambesnes solidines, periferijoje - negausias smulkias susiliejančias tubulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne amfofiline citoplazma, vidutinio kalibro gan monotoniškais, minimaliai netaisyklingais branduoliais; mitozių navike iki 5 / 10 DPRL.. 4(1). Navikas (13 blokas): Her2 silpna trūkinėjanti membraninė r-ja 10% naviko ląstelių.  Ki67: 5%, CK5(-), Synaptophysin(-).
answer:  0

 86%|████████▋ | 571/661 [15:54<02:39,  1.78s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2A)- kraštai- be naviko   2(N2B)- kraštai- be naviko   3(N3)- sarginai ( 2 ) - be naviko   4(N1)- sektorius - planinis ptologinis tyrimas    N1- skubus rentgeninis tyrimas - navikas pašalintas. 4. Krūties sektorius 33x5x4 cm su odos lopu 11x4 cm, žymėtas viela. Vielos projekcijoje, pjūvyje - balkšvas, standus, spikulinių kraštu navikas 6x7x7 mm (sudėtas visas), nuo artimiausio rezekcijos krašto (dažyto mėlynai) nutolęs 0,2 cm, nuo odos – 3,5 cm. 3 cm nuo naviko - krūties audinyje fibrozės zona su dilatuotais latakais ~2x1x1 cm.. 1(2a). Fibrocistiniai krūties pokyčiai.  2(2b). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1b (navikas 7,5 mm), pN0(sn)(0/2 l/m), LVI0 (neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). HER2: reakcija paribinė (2+); HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).. 1(2a). Krūties audinyje ryški fibrozė su smulkiais ir nežymiai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.  2(2b). Krūties audinyje židininė fibrozė su smulkiais ir nežymiai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu ar epiteliu su fokalia apokrinine metaplazija.  3. Du limfmazgiai su sinusų histiocitoze.  4. Krūties audinyje navikas (7,5 mm makroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių, trabekulinių ir tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su  polimorfiškais, hiperchromiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 5/10DPRL. Limfovaskulinio plitimo neidentifikuota(LVI0). Navikas nuo artimiausio rezekcijos krašto nutolęs per 3,5 mm (mikroskopiškai).  Krūties audinyje gausūs dilatuoti kanaliukai užpildyti solidinių  ir kribrifominių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta gausūs dilatuoti kanaliukai kloti dvisluoksniu epiteliu.. Blokas 10:  CK5: mioepitelis (+);  HER2: vidutinė (++) necirkuliari reakcija, 20%  naviko ląstelių membranoje.
answer:  1(

 87%|████████▋ | 572/661 [15:56<02:31,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas kair. krūties darinys, paimti 4 stulpeliai medžiagos histologiniam išturimui. 4 fragmentuoti biopsiniai stulpeliai: I - 10 mm; II - 14 mm; III - 9 mm; IV - 10 mm, fragmentuotas.. Invazinė karcinoma (mažiausiai iki 13 mm; galimai lobulinė);  (G1; 5 b. pgl. Nottingham sist.) 4-se krūties audinio stulpeliuose.  Estrogenų receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 10% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 2%.. Krūties kompaktišką fibrozinį audinį 4-se bioptatuose infiltruoja iki 13 mm :   - deformuotos juostos ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: vidutinė teigiama (++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcij
answer:  2%

 87%|████████▋ | 573/661 [15:58<02:31,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- Kairės krūties sektorius su limfmazgiais, planinis. 3(2). Krūties sektorius 8,5x8,5x5 cm su oda 8x3,5 cm su pažasties narveliena 10,5x6,5x5 cm. Krūties audinyje, pilkšvas, standus, aiškių ribų navikas 25x22x20 mm, nuo giliojo rezekcijos krašto 1 cm, nuo odos - 0,7 cm. Rasta 18 limfmazgių iki 1,7 cm.. 1(1a). Krūties fibrocistiniai pokyčiai.  2(1b). Krūties fibrocistiniai pokyčiai.  3(2). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, pT2(2,5 cm) pN1a(1/18 l/m, mts 0,7 cm; ekstranodalinis plitimas). Rezekcijos kraštų būklė: be naviko.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5% (hot spot 8%).. 1(1a). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai minimaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2(1b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai minimaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(2). Krūtis: Navikas - solidines, trabekulines, pavienes smulkias tubulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 4 / 10 DPRL.  Pažasties narveliena: Aukščiau aprašyto naviko metastazė viename (1) iš aštuoniolikos (18) limfmazgyje (0,7 cm, ekstranodalinis plitimas).. 3(2). Navikas (5 blokas): HER2: silpnas(+) membraninis dažymasis 10% naviko ląstelėse.   Ki67: 5% (hot spot 8%).
answer:  1(

 87%|████████▋ | 574/661 [15:59<02:30,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a kraštai - skubus tyrimas (be naviko);   2. N2b kraštai - skubus tyrimas (be naviko);  3. N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas (3 l/m be naviko);   4(1). N1: Pašalintas dešinės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 10x5x3 cm su odos lopu 7x4 cm. Krūties audinys balkšvas, standus, fibrozuotas 6,5x6 cm plote. Fibrozėje gelsvas, neaiškių ribų navikas 15x7x7 cm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 0,7 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  3(Extra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(18 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Naviko struktūros siekia koaguliuotą sektoriaus kraštą.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Židininė krūties audinio fibrozė.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu; vienas kanaliukas su epitelio hiperplazija.  3(Extra). 3 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 18 mm), suformuotas fibrozuotoje stromoje plintančių lizdinių, trabekulinių ir negausių solidinių bei pavienių tubulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 4/10 DPRL. Naviko struktūros siekia koaguliuotą sektoriaus kraštą.   Aplinkiniame krūties audinyje - fibrozės zonos su kiek dilatuotais kanaliukais, klotais suplokštėjusiu epiteliu.. 2. CK14+ mioepitelinis sluoksnis bei mišri populiacija hiperplastiškame epitelyje.  4. Navikas (10 blokas):  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.
answer:  0.

 87%|████████▋ | 575/661 [16:01<02:24,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 2 biopsiniai stulpeliai iš kairės krūties  BI-RADS 4c darinio   2 but. 1 biopsinis stulpelis iš dešinės krūties BI-RADS 5 darinio. 1. 2 biopsiniai stulpeliai: I - 8 mm; II - 11 mm.  2. Biopsinis stulpelis 13 mm.. Kairė  N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ar vidutinis branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.  ------------------  Dešinė  N2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Kairė  N1: Krūties audinį infiltruoja nedideli kribroziniai/solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ECAD negatyvių ląstelių, mitozių mažiau 1/10 DPRL.  ------------------  Dešinė  N2: Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. nan
answer:  1a

 87%|████████▋ | 576/661 [16:03<02:30,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. sarginiai limfmazgiai, skubu  2. deš. krūtis, planinis. 2. Krūtis 1022 gramų svorio, 24x20x10 cm, spenelis įtrauktas. Krūties audinyje, centrinėje dalyje - pilkšvas, neaiškių ribų navikas 30x26x25 mm, su aplinkine fibroze 5x4 cm plote ir hemoragijos. Navikas nuo giliojo rezekcijos krašto nutolęs 3,6 cm, nuo odos - 2 cm. Nuo naviko 3 cm atstumu pilkšvas, standus, gan aiškių ribų židinys 11x8x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo odos - 4 cm. Krūties krašte riebalinis darinys 5,5x4,3x2 cm.. 1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   2. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma (su apokrininės diferenciacijos požymiais), SUMINIS TNM:   pT2(m) (du navikai: I - 30 mm; II - 11 mm) N0(sn) (0/3 l/mm), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Intraduktalinis karcinomos plitimas (kanaliukų kancerizacija). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).   Androgenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.   Synaptophysin/GATA3/E-Cadherin(+).     Krūties žemo-aukšto laipsnio duktalinė karcinoma in situ (DIN1c-3/DCIS: solidinis, kribriforminis, ploščias, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, sklerozuojanti ir mikroglandulinė adenozė, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).   Krūties rezekcijos kraštas normalios histologinės struktūros.. 1(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2. SPENELIS: normalios histologinės struktūros.   NAVIKAS(du židiniai: I - 30 mm; II - 11 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios nedidelės  kribriforminės, trabekulinės, smulkios lizdinės naviko struktūros ir pabiros ląstelės, ryškiai polimorfiškų ląstelių, gausia šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis eozinofiliškomis nukleolėmis; retos dvi- ar keliabranduolės ląstelės; mitozių iki 7-8/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Naviko ląstelės plinta kanaliukų spindžiuose. Pavieniai mikrokalcifikatai. Fokaliai kiek negausi limfocitinė infiltracija.   APLINKA: šalia naviko - solidiniai, kribriforminiai, plokšti vienasluoksniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti, kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.   GILUSIS REZEKCIJOS KRAŠTAS: fibrozuotas brandus riebalinis audinys; be naviko.. 2. NAVIKAS (blokas 18):   Androgenų receptoriai: (+/+++)(brand.r-ja)95%;   Synaptophysin: (+++)(grūd.citopl.r-ja)100%;   GATA3: (+++)(brand.r-ja)100%;   E-Cadherin: (+++)(membr.r-ja)100%;   HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląstelių memb
answer:  20%

 87%|████████▋ | 577/661 [16:05<02:25,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. Pjūvio kraštai, ekstra.   3. Sarginiai l/m, ekstra.   4. Sektorius, planinis.. 4. Krūties sektorius 7x4x4,5 cm su oda 5,5x3 cm, žymėtas viela. Vielos projekcijoje, pilkšvas standus, aiškių ribų navikas 13x13x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 3 cm.. 1. Pjūvio kraštai. Krūties audinys be patologinių pokyčių.    2. Pjūvio kraštai. Krūties audinys be patologinių pokyčių.    3. Sarginiai l/m. Limfmazgiai (2) be karcinomos ląstelių.    4. Sektorius.   Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20-25%.    pT1c pN0 pLVI-0 pR0.. 1. Pjūvio kraštai. Krūties audinys be patologinių pokyčių.  2. Pjūvio kraštai. Krūties audinys be patologinių pokyčių.  3. Sarginiai l/m. Limfmazgiai (2) be karcinomos ląstelių.  4. Sektorius. Krūties audinį infiltruoja dalinai riboto naviko negausios duktalinės struktūros ir netaisyklingi kribroziniai/solidiniai kompleksai iš  vidutiniškai polimorfiškų ląstelių, mitozių iki 12/10 DPRL. Navikas 1 mm nuo operacinio krašto.. Blokas 12:  CD31: stipri teigiama (+) membraninė reakcija kraujagyslių endotelyje be atipinių struktūrų spindyje
answer:  0.

 87%|████████▋ | 578/661 [16:06<02:22,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N1 sarginiai l/m - extra  2. N2 K krūtis su naviku - planiškai. 2. Krūtis 1348 g svorio, 25x18x7 cm. Odoje randas 5,5 cm ilgio, cirkuliariai apvedantis areole 5 cm skersmenyje. Krūties audinyje pilkšvas, standus, spikuliniais kraštais navikas 38x25x34 mm, siekia odą, nuo artimiausio rezekcijos krašto nutolęs 4 cm.. 1(extra). Reaktyvi limfadenopatija (5 l/m).  2. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, suminis TNM: pT2(38 mm navikas), pN0(0/5 l/m), R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2). Krūties fibrocistiniai pokyčiai.  Naviko imunofenotipas(biopsijoje):  Estrogenų receptoriai: stipri reakcija, 90% naviko ląstelių.  Progesterono receptoriai: stipri reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Operacinėje medžiagoje kartota: Ki67: proliferacinis indeksas 10%, fokaliai iki 20%.. 1. Penki limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais.  2. Spenelis normalios histologinės struktūros. Rezekcijos kraštas be naviko. Krūtyje navikas infiltratyviu augimo frontu, sudarytas iš desmoplastiškoje stromoje besidėstančių tubulių, lizdinių, trabekulinių, kribriforminių struktūrų ir solidinių kompleksų iš ląstelių negausia šviesiai eozinofiliška citoplazma ir vidutinio kalibro, apvaliais ar nelygaus kontūro, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių iki 19/10 DPRL. Limfovaskulinė invazija neidentifikuota. Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių. Krūties audinys su mažai ląstelingomis fibrozės zonomis ir atrofiškomis lobulėmis bei dilatuotais latakais, klotais dvisluoksniu epiteliu.. nan
answer:  1a

 88%|████████▊ | 579/661 [16:08<02:14,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Paimti 5 biopsiniai stulpeliai.. 5 biopsiniai stulpeliai: I - 16 mm; II - 8 mm; III - 13 mm; IV - 7 mm, V - 9 mm.. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma.  ---  Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100% .   Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 80% .   Her2 imunohistocheminė reakcija neigiama (0 balų).  Ki67: 35%.. Solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne blyškiai-saikingai eozinofiline citoplazma, vidutinio kalibro apvalios formos saikingai netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 25 / 10 DPRL.. Navikas (1 blokas):  Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100% .   Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 80% .   HER2: nusidažiusių naviko ląstelių nėra.  Ki67: 35%.   CK5(-); PanCK(+++)(citoplazminė r-ja), 10
answer:  10/

 88%|████████▊ | 580/661 [16:09<02:15,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.   2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 7,5x4,5x3 cm su oda 5x2,2 cm, žymėtas viela. Vielos projekcijoje - pilkšvas, standus, neaiškių ribų navikas 18x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 0,6 cm.. PATAISYTAS ATSAKYMAS (naviko diferenciacijos laipsnis):  1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (5 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(15 mm) N(sn)0(0/5 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   HER2 imuninė reakcija: neigiama (1+).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro ir fokaliai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu; negausi aplinkinė MMN infiltracija.  3(Extra). 5 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija, sinusų histiocitoze ir neryškia lipomatoze.  4. Krūties audinyje - ribotas skiltėtas navikas (mikroskopiškai 15 mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių, solidinių ir negausių lizdinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 12/10 DPRL.  Aplinkinis krūties audinys fibrozuotas, su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.. 1. Navikas (18 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.
answer:  1(

 88%|████████▊ | 581/661 [16:12<02:30,  1.88s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 1 - viršutinis kraštas;  2. 2 - apatinis kraštas;  3. 3 - sarginiai l/m;  4. 4 - kvadrantas - planiniam tyrimui;  5. 5 - k. krūties audiniai.    1-2-3 ekstra; 4 - kvadrantas - planiniam tyrimui.. 4.  Krūties sektorius 6x4x4 cm su odos lopu 5x0,7 cm, žymėtas viela. Patologijos skyriuje rezekcijos kraštas žymėtas mėlynu tušu. Krūties audinyje:  - Vielos projekcijoje - balkšvas, neaiškių ribų, standus I navikas 2,3x1,8x1 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos 0,4 cm.  - II navikas 0,4x0,4x0,4 cm (histologiniam tyrimui paimtas visas), makroskopiškai siekiantis rezekcijos kraštą, nuo odos nutolęs 2,5 cm, nuo I naviko - 1 cm.  5. Krūtis (290 g svorio, 20x13x4 cm), su odos lopu 15x14 cm, žymėta ilgu siūlu lateraliniame krašte ir trumpu siūlu viršutiniame krašte.    - Krūties apatinio lateralinio kvadranto odoje - operacinis pjūvis 5 cm ilgio, su tūriniu audinių defektu (~6 cm dydžio ir koaguliuotais kraštais: sektoriaus šalinimo vieta). Krūtis virš operacinio pjūvio 2 cm storio.   - Viršutiniame lateraliniame kvadrante - pilkšvas, apvalus darinys 0,6x0,5x0,5 cm, nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo paviršinio - 3 cm.  - Centrinėje dalyje - fibrozės zona 8x7x1,5 cm, nuo giliojo rezekcijos krašto nutolusi 1 cm, nuo odos - 1,3 cm.. SUMINĖ (Nr.1-Nr.5) patologijos tyrimo išvada:  Krūties invazyvi multifokalinė karcinoma (mišrios duktalinės+lobulinės karcinomos židinys, ir dauginiai (ne mažiau 3) lobulinės karcinomos židiniai), pT1c(m) (dauginiai židiniai, didžiausias iki 1,2 cm) pN1mi(1/1 intramamarinis limfmazgis su 0,15 cm duktalinės adenokarcinomos mikromts + 0/4 sarginiai l/m). LVI0(limfovaskulinės invazijos nėra). Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribriforminis tipas). Krūties fibrocistiniai pokyčiai (paprastoji duktalinė hiperplazija, stulpinis ląstelių pokytis). Rezekcijos kraštai be patologijos.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5%.     1(extra). Invazyvios karcinomos židinys (iki 0,25 cm skersmens) krūties audinyje.  2(extra). Invazyvios karcinomos židinys (iki 0,7 cm skersmens) krūties audinyje.  3(extra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi mišri (lobulinė + duktalinė) karcinoma (iki 1,2 cm židinys, mikroskopiškai). Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribriforminis tipas). Krūties fibrocistiniai pokyčiai (paprastoji duktalinė hiperplazija, stulpinis ląstelių pokytis). Krūties duktalinės adenokarcinomos mikrometastazė (0,15 cm) intramamariniame limfmazgyje.  5. Krūties invazyvi lobulinė karcinoma (0,3 cm židinys). Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribriforminis tipas). Krūties fibrocistiniai pokyčiai (paprastoji duktalinė hiperplazija, stulpinis ląstelių pokytis).. 1(extra). Žemiau (Nr.4, krūties sektoriuje) aprašyto naviko (lobulinės karcinomos) židinys (iki 0,25 cm skersmens) krūties audinyje.  2(extra). Žemiau (Nr.4, krūties sektoriuje) aprašyto naviko (lobulinės karcinomos) židinys (iki 0,7 cm skersmens) krūties audinyje.  3(extra). Nežymi sinusų histiocitozė keturiuose (4) limfmazgiuose.  4. Krūties sektoriuje - dauginiai kompleksiniai pažeidimai/pokyčiai:  A) invazyvaus naviko židiniai: A) mišrios (duktalinės + lobulinės) karcimomos židinys (~1,2 cm): trabekulinės, kribriforminės, duktalinės struktūros, suformuotos ląstelių su vidutinio gausumo švelniai eozinofiline citoplazma, vidutinio kalibro kiek netaisyklingais branduoliais (duktalinė karcinoma), trabekulėmis, grandinėlėmis ar pabirais besidėstančios gan smulkios ląstelės su negausia blyškia citoplazma, smulkiais apvalios formos kiek netaisyklingais branduoliais (lobulinė karcinoma); mitozių navike iki 2 / 10 DPRL.  B) in situ pažeidimas (kanaliukai su solidiniais atipinių ląstelių (su gan monotoniškais branduoliais) proliferatais spindžiuose;  C) Fibrocistinių pokyčių spektro pažeidimas (fibrozės zonos, su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; apokrininės metaplazijos, intraduktalinės hiperplazijos židiniai; zonos su stulpiniu epiteliu išklotais kanaliukais).  D) Intramamarinis limfmazgis su duktalinės adenokarcinomos mikrometastaze (0,15 cm).  5. KRŪTIES SPENELIS: Be patologijos.  KRŪTIES AUDINYS: Fibrozės zonos, su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; apokrininės metaplazijos, intraduktalinės hiperplazijos židiniai; zonos su stulpiniu epiteliu išklotais kanaliukais; kanaliukai su solidiniais atipinių ląstelių (su gan monotoniškais branduoliais) proliferatais spindžiuose; 0,3 cm invazyvaus naviko (lobulinės karcinomos) židinys.. 1. Navikas (lobulinė karcinoma) (10 blokas): E-Cadherin(-), p120(+++)(citoplazminė r-ja), 100%.  2. Navikas (lobulinė karcinoma) (11 blokas): E-Cadherin(+)(silpna trūkinėjanti membraninė r-ja), 20%, p120(+++)(citoplazminė r-ja), 100%.  4. Navikas (lobulin
answer:  12 blo

 88%|████████▊ | 582/661 [16:13<02:21,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 3 biopsiniai stulpeliai iš kairės krūties difuzinių navikinių pakitimų su dariniu  viršutiniame lateraliniame kv-te    2 but. 1 biopsinis stulpelis iš navikinių pakitimų viršutiniame vidiniame kv-te. 1. 3 biopsiniai stulpeliai: I - 16 mm; II - 15 mm; III - 12 mm.  2. Biopsinis stulpelis 12 mm ilgio.. N1: Vidutinio laipsnio intraduktalinė karcinoma (DCIS/DIN2; solidinis tipas). Invazinė duktalinė karcinoma, navikas tokios pačios struktūros, kaip ir žemiau aprašytas; intravaskulinis naviko plitimas.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 8%.. N1: Krūties audinyje dilatuotuose kanaliukuose solidiniai vidutiniškai polimorfiškų ląstelių proliferatai ir solidiniai invaziniai naviko židiniai stromoje ir intravaskuliariai.  N2: Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. N2 navikas:  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 100% naviko ląstelių.  Ki67+
answer:  8%.

 88%|████████▊ | 583/661 [16:16<02:29,  1.91s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. Deš. pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: 2. Kairės pažasties sarginiai limfmazgiai, skubu  3 ėminio aprašas: 3. Deš. krūtis, planinis  4 ėminio aprašas: 4. Kairė krūtis, planinis. 3. Dex. Krūtis 2118 gramų svorio , 23x21x9,5 cm. Krūties viršutinių kvadrantų riboje -  skiltėtas, rusvas, standus  navikas 2,7x2,3x2,5 cm, nuo rezekcijos krašto nutolęs 1,4 cm, nuo odos - 2,5 cm. Krūties auidinyje viršutiniame lateraliniame kvadrante - balkšva, standi , aiškių ribų (I) zona 1,3x0,7x0,4 cm, nuo rezekcijos krašto nutolusi 2,4 cm, nuo odos - 2 cm, nuo naviko - 2,5 cm. Krūties audinyje , centrinėje dalyje balkšva, elastinga (II) fibrozės zona 9x7x5,5cm, nuo rezekcijos krašto nutolusi 0,5 cm, nuo odos - 1,5 cm.  4. SIN. Krūtis 2025 gramų svorio , 22x21x9 cm. Krūties viršutiniame medialiniame kvadrante - pilkšvas, standus, gerai ribotas  (I) navikas 3,5x3,5x2,3 cm, nuo rezekcijos krašto nutolęs 3 cm, nuo odos - 2 cm. Krūties auidinyje viršutiniame medialiniame kvadrante - balkšvas, standus, neaiškių ribų (II) navikas  0,9x0,7x0,6cm, nuo rezekcijos krašto nutolęs 1,8 cm, nuo odos - 5,5 cm, nuo (I)naviko - 0,5 cm. Krūties audinyje , viršutiniame lateraliniame kvadrante  zona  9x5x5 cm su dilatuotais, standžiais latakais iki 0,8 cm skersmens, didžiausias latakas nuo rezekcijos krašto nutolęs 1,4 cm.. 1(ekstra). DEŠINĖ. Duktalinės karcinomos mikrometastazė limfmazgyje (1/4 l/m, 0,4mm). Limfovaskulinė invazija.   2(extra). KAIRĖ. Reaktyvi limfadenopatija (3 l/m).    3. DEŠINĖ. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma su daline neuroendokrinine diferenciacija, SUMINIS TNM: pT2(27 mm) pN1a(sn)(1/4 l/m, 0,4mm). LVI-2(limfovaskulinė invazija). Vidutinio žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas), gausūs židiniai iki 1 cm.    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    4. KAIRĖ. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma neuroendokrinine diferenciacija, SUMINIS TNM: pT2(m)(35 mm ir 7 mm navikai) pN0(sn)(0/3 l/m). LVI-2(limfovaskulinė invazija). Vidutinio žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas).  Židininiai fibrocistiniai pokyčiai.    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.. 1(ekstra). 1 iš 4 limfmazgių aprašyto naviko metasatzė 0,4 mm. Limfovaskulinė invazija.  2(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  3. Spenelis: normali histologinė struktūra.   Krūtyje - navikas ekspansyviu augimo frontu, suformuotas lizdais ir solidiniais plotais besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 19/10 DPRL. Limfovaskulinė invazija.  Aplinkiniame krūties dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaustų kanaliukų zonos.    4. Spenelis: normali histologinė struktūra.   Krūtyje - navikas (35 mm ir 7 mm navikas) ekspansyviu augimo frontu, suformuotas lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 5/10 DPRL. Limfovaskulinė invazija.  Aplinkiniame krūties dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.. 3. Navikas (17 blokas): Synaptophysin(+++) citopl. r-ja 10%;  HER2 silpnas dalies membranų nusidažymas <5%.  4. Navikas (39 blokas): Synaptophysin(+++) citopl. r-ja 100%;  HER2 silpnas dalies membranų nusidažymas <5%.
answer:  0

 88%|████████▊ | 584/661 [16:17<02:17,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 12 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.. Krūties audinį infiltruoja netaisyklingos duktalinės struktūros ir pavieniai kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+ 4
answer:  1a

 89%|████████▊ | 585/661 [16:19<02:10,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 9 mm; II - 8 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 7 mm);  (G1; 4 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.. Krūties audinį 2-se bioptatuose infiltruoja iki 7 mm :   - duktalinės struktūros (20% viso naviko) ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 15% naviko ląstelių.  Progesterono receptoriai: stipri (+
answer:  100%

 89%|████████▊ | 586/661 [16:20<02:04,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 15 mm; II - 12 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma (su apokrininės diferencijacijos požymiais).  ---  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 20%.. Solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne eozinofiline citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 5 / 10 DPRL.. Navikas  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: nusidažiusių naviko ląste
answer:  0

 89%|████████▉ | 587/661 [16:22<02:01,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 6 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mikropapilinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 5%.. Bioptate fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais besidėstančių ląstelių gausia ryškai eozinofiliška citoplazma, ryškiai polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais, dalis branduolių gigantiniais, pleomorfiški; mitozių 3/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67 proliferacinis aktyvumas 5%.  EMA invertuota r-ja.
answer:  1a

 89%|████████▉ | 588/661 [16:23<01:56,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 12
answer:  1b

 89%|████████▉ | 589/661 [16:25<02:01,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2): pašalinti  dešinės krūties sarginiai limfmazgiai - skubus tyrimas 2l/m be naviko  2(N1): pašalinta dešinės krūtis - planinis tyrimas. 2(1). Krūtis 1800 gramų svorio, 23x19x6 cm. Rezekcijos kraštas dažytas mėlynu tušu. Krūties audinyje balkšvi standūs naviko židiniai:  - (I) 2,3x2x2,3 cm navikas, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 1,5 cm;  - (II) 0,9x0,9x0,8 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 4 cm, nuo odos - 2 cm, nuo artimiausio (I) naviko - 7,5 cm;  - (III) 1,5x1,7x1,5 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs  6 cm, nuo odos - 2  cm, nuo artimiausio (I)  naviko - 3 cm;  - (IV) 2,2x1,5x1,5 cm navikas, nuo giliojo rezekcijos krašto nutolęs 5 cm, nuo odos - 3 cm, nuo artimiausio (III) naviko nutolęs 3 cm.  - (V) 0,6x0,5x0,5 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 5 cm, nuo odos - 4 cm, nuo artimiausio (III) naviko nutolęs 4 cm.  - (VI) 0,5x0,4x0,2 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 9 cm, nuo odos - 1 cm, nuo artimiausio (V) naviko nutolęs 3 cm.  - Balkšva, standi, netoylgių kraštų fibrozės zona 6x3x3 cm su daugybiniais standžiais židiniais iki 1,5x1x1 cm. Zona nuo giliojo rezekcijos krašto nutolusi 4 cm, nuo odos - 1 cm.. 1(Extra). Reaktyvi limfadenopatija (2 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma (su minimalia mucinine diferenciacija), SUMINIS TNM: pT(m)1c(2 naviko židiniai: 19 mm ir 7 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties išplitusi aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DIN3/DCIS)(solidinė, kribriforminė, komedo) (4 židiniai).  Krūties intraduktalinės papilomos.. 1(Extra). 2 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.  2. SPENELIS: normali histologinė struktūra; žemiau - dilatuotas latakas su intraduktalinėmis papilinėmis struktūromis, klotomis dvisluoksniu epiteliu.   KRŪTIS: krūties audinyje - 2 riboti navikai (I ir II: mikroskopiškai 19 mm ir 7 mm), suformuoti fibrozuotoje stromoje plintančių solidinių, lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 9/10 DPRL. Pirmajame navike negausūs AB+ ekstraląsteliniai mucinai; fokaliai retrakcijos artefaktai aplink naviko lizdus. Aplink dilatuoti kanaliukai su kribriforminiais, negausiais solidiniais intraduktaliniais analogiškų naviko ląstelių proliferatais.   Kiti židiniai (III - VI): - riboti židiniai su DCIS struktūromis bei intraduktalinėmis papilomomis.. 2. Navikas (6 blokas): EMA(+++)(citopl. r-ja), 100%; D2-40+/ERG+ endotelizuotose ertmėse naviko plitimo neidentifikuota.  Navikas (7 blokas): HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.
answer:  1.

 89%|████████▉ | 590/661 [16:27<02:03,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.  3. sektorius su pažasties l/m, planinis. 3. Krūties sektorius 14,5x5,5x5,5 cm su oda 11,5x3 cm, žymėtas viela, su pažasties narveliena 9x7,5x3 cm. Vielos projekcijoje - pilkšvas, standus, aiškių ribų navikas 18x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 3 cm. Nuo naviko 1,6 cm atstumu rusvas, aiškių ribų židinys 6x5x5 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,5 cm.   Rasta 19 limfmazgių iki 2 cm.. 1(ekstra). Pjūvio kraštai. Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.     2(ekstra). Pjūvio kraštai. Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.    3. Sektorius su pažasties l/m.   Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT1c (18 mm navikas)   pN1mi(1/19 l/m su mts 0,9 mm)    pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pR0(radikalus pašalinimas).  Naviko imunotipas (iš biopsijos):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 kribriforminis tipas).  Krūties fibrocistiniai pokyčiai, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).   Lėtinė židininė granulominė (svetimkūnio tipo) uždegiminė reakcija krūties audinyje.. 1(ekstra). Pjūvio kraštai. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu ar hiperplastišku epiteliu. Naviko plitimo nėra.   2(ekstra). Pjūvio kraštai. Riebalinis fibrozinis audinys su smulkiomis hemoragijomis. Naviko plitimo nėra.   3. Sektorius su pažasties l/m.   Navikas: Krūties audinyje - navikas, suformuotas tubulių (50 %), lizdų, kribriforminių struktūrų ir solidinių kompleksų. Naviko ląstelės su vidutinio gausumo, šviesiai eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais. Mitozių navike iki 4/10DPRL. Naviko plitimas endotelizuotuose spindžiuose.  Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių.  Darinys: židininė putotų ir pigmentuotų makrofagų infiltracija su limfocitų priemaiša ir pavienėmis gigantinėmis daugiabranduolėmis svetimkūnio tipo ląstelėmis.   Atokiau krūties audinyje, dalyje kanaliukų cistinė dilatacija stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).   Limfmazgiai: 1-me/19 limfmazgių - aukščiau aprašyto naviko ląstelių (>200) metastazinės grupės židinyje iki 0,9 mm.. nan
answer:  0.

 89%|████████▉ | 591/661 [16:29<02:00,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 13x6,5x4 cm su odos lopu 9,5x3 cm, žymėtas viela. Vielos projekcijoje, pjūvyje pilkšvas, neaiškių ribų navikas 4x3x3 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 2 cm, nuo odos – 3 cm.. 1. Krūties audinys.  2. Vidutinio laipsnio krūties intraduktalinė karcinoma (DCIS; solidinis tipas; židinys - 1,5mm). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi, gerai diferencijuota (G1, 4 balai pagal Nottingham sis.) duktalinė karcinoma, suminis tyrimo TNM: pT1a(navikas - 4mm) pN0(sn)(0/3 l/m); LVI-0(Limfo-Vaskulinė naviko Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-43421 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.". 1. Riebalinis audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  2. Krūties audinyje - pavieniai dilatuoti latakėliai (židinys 1,5mm) su solidiniais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS). Riebalinis audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  3. Trys(3) limfmazgiai be naviko metastazių su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4. Krūties fibroziniame audinyje - navikas, formuojamas duktalinių, pavienių kribriforminių struktūrų iš vidutinio kalibro ląstelių, nežymiai polimorfiškais branduoliais su fokaliai išryškėjusiomis nukleolėmis; navike iki 2 mitozių/10 DPRL.. nan
answer:  1a

 90%|████████▉ | 592/661 [16:30<01:55,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Dešiniosios krūties audinys  Kairiosios krūties audinys. 1. Riebalinio audinio fragmentas 42x9x7,5 cm su odos lopu 38x7,5 cm.  2. Riebalinio audinio fragmentas 41x9,5x6,5 cm su odos lopu 39x6 cm.. 1. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma;   pT1b(9 mm) pLVI-0 pR0.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 18%. Karštame taške 50%.    2. Krūties audinys be patologinių pokyčių.. 1. Krūties audinyje naviko (mikroskopiškai 9 mm skersmens) desmoplazinėje stromoje pabiros ląstelės ar pavienės jų linijinės struktūros su gausia saikingai eozinofiline citoplazma, stambios ląstelės ryškiai polimorfiškais branduoliais; mitozių navike iki 2 / 10 DPRL. Navikas apie 1 mm nuo operacinio krašto.. Blokas 5:  CK5: vidutinė ir stipri teigiama (++) membraninė reakcija 90 proc. atipinėse ląstelėse  CK7: stipri teigiama (+++) membraninė reakcija 100 proc. epitelio ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  GCDFP15:
answer:  0.

 90%|████████▉ | 593/661 [16:32<01:49,  1.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 4 mm; II - 3 mm; III - 4 mm.. Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.. Krūties audinyje mucininėje stromoje aiškių ribų netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  1a

 90%|████████▉ | 594/661 [16:34<01:51,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas  - skubus tyrimas - be naviko  2(N2b) - kraštas  - skubus tyrimas - be naviko  3(N3) - sarginis limfmazgis - dviejose iš trijų limfmazgių makrometastazė.  4(N1) - pašalintas dešinės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 5,3x5x4 cm be odos. Pjūvyje pilkšvas, standus, aiškių ribų navikas 23x16x16 cm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Krūties duktalinės karcinomos metastazės 2/3 l/m (18 mm ir 2 mm, su ekstranodaliniu plitimu).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(22 mm) N(sn)1a(mts 2/3 l/m), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro ir smulkaus kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro ir smulkaus kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 2 iš 3 limfmazgiuose - žemiau aprašyto naviko metastazės (18 mm ir 2 mm), su ekstranodaliniu plitimu.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 22 mm), suformuotas fibrozuotoje stromoje ir tarp lipocitų infiltratyviai plintančių lizdinių, trabekulinių ir negausių, fokaliai besiliejančių tubulinių (~10%) struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška, fokaliai "tamsoka" citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, dalis su aiškia nukleole branduoliais. Mitozių iki 15/10 DPRL. Šalia yra dilatuotų kanaliukų su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais, fokaliai su komedo nekroze centre.. 1. Navikas (18 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 2% naviko ląstelių.
answer:  1(n

 90%|█████████ | 595/661 [16:35<01:53,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2) - Kairės pažasties sarginiai limfmazgiai, skubu  4(3) - Kairės krūties sektorius, planinis. 4(3). Krūties sektorius 9x6x3 cm su odos lopu 4x0,8 cm, žymėtas viela. Vielos projekcijoje, pjūvyje balkšvas, standus navikas 13x10x9 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos – 5,5 cm.. 1(1a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   2(1b, ekstra). "Kraštai": fibrozuotas krūties audinys.   3(2, ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   4(3). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1c (navikas 11 mm) N0(sn) (0/3 l/m), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   HER2: reakcija neigiama (1+); AR(+)100%.    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: solidinis, kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).. 1(1a, ekstra). "Kraštai": aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   2(1b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.   3(2, ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4(3). NAVIKAS (mikroskopiškai 11 mm): krūties audinyje, ryškiai fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retos kribriforminės ir besiliejančios dominuojančios lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, gausia šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis; mitozių iki 7/10 DPRL.   Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Pavieniai mikrokalcifikatai. Zona su gausia PMN infiltracija (g.b. biopsijos vieta).   APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: fibrozuotas krūties audinys; be naviko.. 4(3). NAVIKAS(10 blokas):   Androgenų receptoriai: (++/+++)(brand.r-ja)100%.   HER2: silpna (+) necirkuliari reakcija, 2-3%  naviko ląstelių membranoje.
answer:  1(

 90%|█████████ | 596/661 [16:37<01:49,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1) pašalintas dešinės krūties kvadrantas - planinis tyrimas;  2(N2a) kraštai;  3(N2b) kraštai;  4(3). Dešinės pažasties sarginis limfmazgis;  5(4). Papildomas kraštas - planinis tyrimas.. 1. Krūties sektorius 8,5x4x4 cm su oda 7,5x2,5 cm, žymėtas viela. Vielos projekcijoje, krūties audinys fibrozuotas 5,5x2 cm, fibrozėje gelsvai pilkšvas, neaiškių ribų židinys 10x6x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 1 cm.  2. Riebalinio audinio fragmentas 1,5x1x1 cm. v/m  3. Riebalinio audinio fragmentas 2x1,2x0,7 cm. v/m  4. Riebalinio audinio fragmentas 3,5x2,5x0,6 cm. Rasti 2 limfmazgiai iki 1,6 cm. v/m  5. Riebalinio audinio fragmentas 2x1x0,4 cm. v/m. N1: Gerai diferencijuota (G1 , 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (10mm).  N2ab: Krūties audinys be naviko.  N3: Limfmazgiai (2 l/m) be naviko židinių; pN0(sn).  N4: Krūties audinys be naviko.. N1: Krūties audinyje 10mm navikas: netaisyklingos kampuotos duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.  N2ab: Krūties audinys be naviko.  N3: Limfmazgiai (2 l/m) su reaktyviais pokyčiais, be naviko židinių.  N4: Krūties audinys be naviko.. nan
answer:  0.

 90%|█████████ | 597/661 [16:39<01:49,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. sarginiai l/m, ekstra.   2. deš krūtis, planinis.. 2. Krūtis 804 gramų svorio, 20x17x8 cm. Krūties audinyje - balkšvi, neaiškių ribų židiniai:  -  centrinėje dalyje - I židinys - 0,7x0,5x0,4 cm (histologiniam tyrimui paimtas visas), nuo artimiausiojo rezekcijos krašto nutolęs 1,7 cm, nuo odos 2,5 cm.   -  apatinių kvadrantų riboje - II židinys (su paryškėjusios spalvos aplinkiniu riebaliniu audiniu, histologiniam tyrimui paimtas visas) - 1,5x0,7x1 cm, nuo  I-ojo židinio nutolęs 3 cm, nuo artimiausiojo rezekcijos krašto nutolęs 4 cm, nuo odos - 1 cm.  - virš pospenelinės zonos - III židinys - 1x0,7x0,6 cm (histologiniam tyrimui paimtas visas), nuo II-ojo židinio nutolęs 1,5 cm, nuo rezekcijos krašto - 4,5, nuo odos - 1 cm.  Visose krūties kvadrantuose vyrauja riebalinis audinys, yra negausios fibrozinės septos, pavienės apsuktos ryškesnės spalvos riebalinio audinio.. 1. Reaktyvi limfadenopatija (1 l/m).  2. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.2): pT1a(m) (0,4 cm ir 0,2 cm židiniai) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės invazijos nėra). Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, komedo tipas). R0(radikalus naviko pašalinimas).     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: teigiama (3+).  Ki67: 25%.. 1. Nežymi sinusų histiocitozė dviejuose (2) limfmazgiuose.  2. Krūties audinyje - kelios sritys su vidutinio kalibro kanaliukais (su solidiniais intraduktaliniais ląstelių su eozinofiliška citoplazma, vidutinio kalibro ir stambiais, polimorfiškais branduoliais proliferatais, nekrotinis detritas dalies kanaliukų spindžiuose) (DCIS), bei du (2) invazyvaus naviko židiniai (0,4 cm ir 0,2 cm skersmens): solidines naviko struktūras formuoja ląstelės su gan gausia tamsoka eozinofiline, amfofiline citoplazma, vidutinio ar stambaus kalibro apvalios formos saikingai netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 25 / 10 DPRL.. 2. Navikas (7 blokas): CK14(-).  Navikas (18 blokas): CK14(-).  DCIS (7,17,18 blokai): CK14+ bazinis sluoksnis išlikęs.
answer:  0.

 90%|█████████ | 598/661 [16:41<01:48,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 2a - kraštas - extra  2. 2b - kraštas - extra  3. 2c - kraštas - extra  4(3). sarginiai limfmazgiai - extra  5(4) ėminio aprašas: N1 - pašalintas sektrius su naviku- planinis patologinis tyrimas skubus rengenis N1 tyrimas- navikas pašalintas. 5. Krūties sektorius 7,5x2,5x6 cm, su odos lopu 7x1,5 cm. Pjūvyje pilkšvas, standus, gan aiškių ribų navikas 30x26x20 mm, nuo giliojo rezekcijos krašto nutolęs 0,5cm, nuo odos - 2,2 cm.. Anksčiau atliktas aktualus VPC tyrimas, B23-23353:  1. Krūties audinys.  2. Krūties audinys.  3. Fibrocistiniai krūties pokyčiai, intraduktalinė krūties papiloma.  4. Reaktyvi limfadenopatija (1 l/m).  5. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT2(navikas 30 mm), pN0(sn)(0/1 l/m), LVI0(limfovaskulinis plitimas neidentifikuotas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Postbiopsiniai pokyčiai krūties audinyje.. 1. Krūties audinyje negausūs smulkūs kanaliukai, kloti dvisluoksniu epiteliu; židininė audinio fibrozė.  2. Krūties audinyje židininė fibrozė ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  3. Krūties audinyje - nežymiai dilatuotas latakas su fibrovaskulinėmis struktūromis, klotomis dvisluoksniu epiteliu monomorfiškais branduoliais; greta keli dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  4. Vienas limfmazgis su sinusų histiocitoze ir šerdies lipomatoze.  5. Krūties audinyje, hialinizuotoje stromoje plinta navikas (30 mm makroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių, trabekulinių ir negausių tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su vidutiniškai polimorfiškais, hiperchromiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 13/10DPRL. Limfovaskulinis plitimas neidentifikuotas (LVI0). Krūties audinyje greta naviko gausūs dilatuoti kanaliukai užpildyti solidinių ir kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Krūties audinyje yra riebalinio audinio nekrozės plotas, rbotas histiocitų, pigmentuotų makrofagų ir svetimkūnio tipo giganitnių daugiabranuolių ląstelių.. Blokas 10:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 91%|█████████ | 599/661 [16:42<01:45,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra (be patologijos);  2(2b). Kraštai - extra (be patologijos);   3. Sarginiai l/m - extra (be patologijos);  4(1). N1- sektorius - planinis patolginis tyrimas ir N1- skubus rentgeninis tyrimas - navikas pašalintas.. 4(1). Krūties sektorius 8x5,5x4,5 cm su odos lopu 7,5x2,9 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, aiškių ribų navikas 1,2x1x1,1 cm (sudėtas visas), siekia rezekcijos kraštą, nuo odos – 1,5 cm.. 1(2a). Kraštai - riebalinis audinys be patologinių pokyčių.    2(2b). Kraštai - riebalinis audinys be patologinių pokyčių.    3. Sarginiai l/m: limfmazgis (1) be patologinių pokyčių; pN0.    4(1). Sektorius. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma pT1c pLVI-0 pR0;  (G1; 4 b. pgl. Nottingham sist.).  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 8%.. 1(2a). Kraštai - riebalinis audinys be patologinių pokyčių.  2(2b). Kraštai - riebalinis audinys be patologinių pokyčių.  3. Sarginiai l/m: limfmazgis (1) be patologinių pokyčių.  4(1). Sektorius. Krūties audinį infiltruoja navikas (mikroskopiškai iki 12 mm), sudarytas   - duktalinių struktūrų (5% viso naviko), netaisyklingų kribrozinių kompleksų ir trabekulių;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. nan
answer:  1(

 91%|█████████ | 600/661 [16:44<01:42,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 18 G automatine biopsine adata punktuotas ~7×5 mm dydžio l/m be riebalinių vartų dešiniosios pažasties I zonoje, paimti 2 biopsiniai stulpeliai histologijai (I buteliukas).   2. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais ~20×13 mm dydžio darinys dešiniojoje krūtyje ties 10 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai (II buteliukas).. 1. 2 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 7 mm.  2. 3 fragmentuoti biopsiniai stulpeliai: I - 15 mm; II - 12 mm; III - 14 mm.. 1. Limfmazgio bioptatai su duktalinės karcinomos metastazėmis.   2. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: silpna (+) reakcija, 25% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.. 1. Limfmazgio bioptatai su žemiau aprašyto naviko židiniais.  2. Krūties audinį infiltruoja duktalinės struktūros (25%), netaisyklingi kribroziniai kompleksai ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. 2. Navikas (3 blokas):  Blokas 3:  Estrogenų receptoriai: silpna (+) reakcija, <1% naviko ląstelių branduoliuose.  Progesterono receptoriai: silpna (+) reakcija, 25% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląste
answer:  1.

 91%|█████████ | 601/661 [16:45<01:37,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20-25%.. Krūties audinį infiltruoja negausios duktalinės struktūros ir netaisyklingi kribroziniai/solidiniai kompleksai iš neryškiai ar  vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 20
answer:  1b

 91%|█████████ | 602/661 [16:47<01:40,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N3) dešinės pažasties  sarginis limfmazgis - skubus tyrimas - 3 l/m be naviko  4(N1) pašalintas dešinės krūties kvadrantas - planinis tyrimas. 4(N1). Krūties sektorius 4x2,5x2,5 cm be odos, žymėtas viela. Vielos projekcijoje -  pilkšvas, standus, neaiškių ribų navikas 8x6x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm. Aplink naviką krūties audinys fibrozuotas su cistinėmis ertmėmis.. 1(2a). Krūties fibrocistiniai pokyčiai.  2(2b). Lobulinė krūties Carcinoma in situ (LCIS). Krūties fibrocistiniai pokyčiai.  3(3). Reaktyvi limfadenopatija (3 l/m).  4(N1). Krūties invazyvi, gerai diferencijuota (G2; 5 balai pagal Nottingham sis) lobulinė karcinoma, suminis tyrimo TNM: pT1b(m)(trys naviko židiniai - 1,5mm, 1,7mm ir 8mm) pN0(sn)(0/3 l/m); LVI-0(Limfo-Vaskulinė naviko Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-5935 tyrime:  "Estrogenų receptoriai: stiprus ar vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%."  Vidutinio laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas). Lobulinė krūties Carcinoma in situ (LCIS). Krūties fibroadenoma.  Krūties fibrocistiniai pokyčiai.. 1(2a). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, židinine apokrinine metaplazija.  2(2b). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, židinine apokrinine metaplazija. Fokaliai dilatuoti latakėliai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS).  3(3). Trys(3) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4(N1). Krūties fibroziniame audinyje - trys naviko židiniai (1,5mm, 1,7mm ir 8mm), formuojami trabekulinių struktūrų, smulkių agregatų, difuziškai plintančių vidutinio kalibro ląstelių, eozinofiliška citoplazma, nežymiai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 1 mitozės/10 DPRL. Aplinkiniame krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, židinine apokrinine metaplazija. Fokaliai dilatuoti latakėliai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS). Pavieniai dilatuoti latakėliai su kribriforminiais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS). Krūties audinyje - ribotas darinys, formuojamas specializuotos fibrozinės stromos proliferatų supamų suspaustų latakėlių, klotų dvisluoksniu epiteliu.. nan
answer:  1(

 91%|█████████ | 603/661 [16:49<01:37,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas be naviko   2(N2b) - kraštas - skubus tyrimas be naviko  3(N3) - dešinės pažasties sarginis limfmazgis - skubus tyrimas 3 l/m be naviko  4(N1) - pašalintas markiruotas dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 11x4,5x7,5 cm su oda 9,5x2 cm, žymėtas viela. Vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 12x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,9 cm, nuo odos - 4,5 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(18 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, neryškiai fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 3 limfmazgiai su neryškia sinusų histiocitoze ir lipomatoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 18 mm), suformuotas fibrozuotoje stromoje plintančių solidinių, lizdinių ir trabekulinių bei negausių (<10%) tubulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 6/10 DPRL. Šalia yra dilatuotų kanaliukų su kribriforminiais ir solidiniais intraduktaliniais analogiškų navikui ląstelių proliferatais.. nan
answer:  0.

 91%|█████████▏| 604/661 [16:51<01:36,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pašalintas dešinės krūties kvadrantas - planinis tyrimas  2(2a). Kraštai - planinis tyrimas  3(2b). Kraštai - planinis tyrimas  4(3). Dešinės pažasties sarginis limfmazgis - planinis tyrimas  5(4). Papildomas kraštas - planinis tyrimas. 1(2a). Riebalinio audinio fragmentas 3,2x1,8x0,5 cm. v/m  2(2b). Riebalinio audinio fragmentas 1,8x1,3x0,6 cm. v/m  3. Riebalinio audinio fragmentai, bendras dydis 4,5x4x1,3 cm. Rasti 5 limfmazgiai iki 2,6 cm.  4. Krūties sektorius 12x7x4 cm su odos lopu 10,5x4 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 1,6x1x0,9 cm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 4 cm.  5. Riebalinio audinio fragmentas 2x1,5x0,3 cm. v/m. N1: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma, pT1c(16mm).  N2a: Gerai diferencijuotos invazinės lobulinės karcinomos židiniai (2,4mm ir 0,2mm).  N2b: Krūties audinys be naviko.  N3: Limfmazgiai be naviko (5 l/m); pN0(sn).  N4: Riebalinis audinys be naviko.. N1: Krūties audinyje 16mm: nedidelės duktalinės struktūros ir kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.  N2a: Krūties audinyje 2,4mm ir 0,2mm navikiniai židiniai: smulkūs solidiniai kompleksai ir juostos nedidelių apvalių minimaliai polimorfiškų ląstelių.  Naviko ląstelės ECAD-, Estrogenų receptorių reakcija teigiama 100% ląstelių.  Rezekcijos kraštas 0,4mm nuo naviko.  N2b: Krūties audinys be naviko.  N3: Limfmazgiai su lipomatozės židiniais, be naviko židinių (5 l/m).  N4: Riebalinis audinys be naviko.. nan
answer:  1a

 92%|█████████▏| 605/661 [16:52<01:31,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja nedideli netaisyklingi solidiniai kompleksai su pavieniais spindžiais iš neryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  1a

 92%|█████████▏| 606/661 [16:54<01:34,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 -deš. užspenelinė zona - extra  2 - deš. pažasties sarginiai l/m - extra   3 - deš.krūties liauka-planas  4 - kairės krūties liauka  5 - D.K pažasties limfmazgiai-planas. 3. Krūtis 171 gr svorio, 11x10x3 cm, su odos lopu 7,5x2,5 cm ir raumens fragmentu 4x2,5x1 cm, be spenelio. Krūties liauka persiūta ilgu siūlu lateraliai, trumpu viršus. Viršutiniame lateraliniame kvadrante balkšvas, standus, neaiškių ribų navikas 19x15x12 cm, nuo giliojo rezekcijos krašto 0,7 cm, nuo odos - 0,2 cm. Krūties audinys fibrozuotas visame plote.  4. Krūtis 183 gr svorio, 13x11x3 cm, žymėtas siūlais (operacijos protokole kairės krūties žymėjimas nenurodytas), be spenelio. Krūties audinys fibrozuotas visame plote.  5. Riebalinio audinio fragmentai, bendras dydis 7x4,5x1 cm su 3 limfmazgiais iki 1,3 cm.. PAPILDYTAS ATSAKYMAS (žr. molekuliniai):  1. Fibrocistiniai krūties pokyčiai.   2. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/3 l/m, 7,5 mm).  3. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) lobulinė karcinoma (21 mm židinys), TNM: pT2(21 mm naviko židinys), LVI2, pN1a(1/6 l/m). Naviko imunofenotipas nustatytas (žr.klinikinius duomenis). Krūties lobulinė karcinoma in situ (LCIS). Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS). Fibrocistiniai krūties pokyčiai: plokščia epitelio atipija, apokrininė epitelio metaplazija.   HER2: reakcija paribinė (2+). HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).  4. Fibrocistiniai krūties pokyčiai.   5. Reaktyvi limfadenopatija (3 l/m).. 1. Krūties audinyje ryški fibrozė su smulkiais kanaliukais ir dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Židininė apokrininė epitelio metaplazija.  2. Viename limfmazgyje iš trijų (1/3 l/m) žemiau aprašyto naviko metastazė iki 7,5 mm.  3. Krūties audinyje - navikas (21 mm mikroskopiškai), suformuotas trabekulinių/juostinių struktūrų iš vidutinio kalibro eozinofiline citoplazma ląstelių, vidutiniškai ir fokaliai ryškiai polimorfiškais branduoliais su paryškėjusiais branduolėliais; mitozių 12/10 DPRL. Limfovaskulinis plitimas (LVI2). Greta naviko gausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Šalia keli dilatuoti kanaliukai užpildyti solidinių proliferatų iš negausia eozinoifline citoplazma ląstelių apvaliais, hiperchromiškais branduoliais. Aplinkiniame fibrozuotame krūties audinyje gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar metaplastišku apokrininiu epiteliu; keli nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu su židinine epitelio proliferacija su kiek stratifikuotais, nežymiai polimorfiškais branduoliais.  4. Krūties audinyje ryški fibrozė, fokalinė stromos hislinozė su sklerozuotomis lobulėmis ir cistiškai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Dalis kanaliukų klota epiteliu su apokrinine epitelio metaplazija.  5. Trys limfmazgiai su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.. Blokas 11:  HER2: vidutinė (++) necirkuliari reakcija, 20%  naviko ląstelių membranoje.  Blokas 12:  HER2: silpna (+) necirkuliari reakcija, 15%  naviko ląstelių membranoje.
answer:  0

 92%|█████████▏| 607/661 [16:56<01:32,  1.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.  2(2b). Kraštai - skubus tyrimas - be naviko.  3. Kairės pažasties limfmazgiai - planinis tyrimas.  4(1). Pašalintas kairės krūties kvadrantas - planinis tyrimas.. 3. Riebalinio audinio fragmentai, bendras dydis 6x4,7x1,3 cm. Rasti 5 limfmazgiai iki 1,7 cm.  4. Krūties sektorius 10x4,5x4 cm, su odos lopu 8x2,2 cm. Pjūvyje pilkšvas, standus neaiškių ribų, skiltėtas navikas 18x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos 1,5 cm.. 1(N2a) kraštai. Krūties audinys be patologinių pokyčių.  2(N2b) kraštai. Krūties audinys be patologinių pokyčių.    3. Kairės pažasties limfmazgiai. Karcinomos metastazės 2-se iš 5 limfmazgių; ekstranodulinio plitimo nestebima.    4(1). Pašalintas kairės krūties kvadrantas. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT1c pN1a pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacijos FISH tyrimo rezultatas neigiamas.  Ki67+ 20%.. 1(N2a) kraštai. Krūties audinys be patologinių pokyčių.  2(N2b) kraštai. Krūties audinys be patologinių pokyčių.  3. Kairės pažasties limfmazgiai. Solidinis atipinių epitelinių ląstelių plitimas (iki 11 mm) 2-se iš 5 limfmazgių; ekstranodulinio plitimo nestebima.  4(1). Pašalintas kairės krūties kvadrantas. Krūties audinį infiltruoja netaisyklingi šakoti kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.. nan
answer:  1.

 92%|█████████▏| 608/661 [16:57<01:28,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 12 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėrįa, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  Ki67
answer:  1b

 92%|█████████▏| 609/661 [16:59<01:25,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6,5 mm);  (G2; 7 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: silpna (+) reakcija, 15% naviko ląstelių.  HER2: reakcija teigiama (3+);   Ki67: proliferacinis indeksas 50%. Karštame taške 70%.    Vidutinio laipsnio intraduktalinė neoplazija (DIN2/DCIS).. Krūties audinį 1-me bioptate infiltruoja iki 6,5 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su ryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - su mitozėmis iki 7 /10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.  Gretimai - analogiškų ląstelių solidinis proliferatas.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: stipri (+++) cirkuliari reakcija, 100% naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 50% naviko ląstelių. Karštame taške 70%.  Progesterono re
answer:  0.

 92%|█████████▏| 610/661 [17:01<01:28,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko;  2(2b). Kraštai - skubus tyrimas - be naviko;  3(N3). Dešinės pažasties sarginis limfmazgis - planinis tyrimas  4(N1). pašalintas dešinės krūties kvadrantas - planinis tyrimas. 3(N3). Riebalinio audinio fragmentai, bendras dydis 9x7x4 cm. Rasta 13 limfmazgių iki 3 cm, 2 limfmazgiuose matomi balkšvi standūs židiniai, didžiausiame iki 2,7 cm.  4(N1). Krūties sektorius 15x9x4 cm su odos lopu 14x7 cm. Odoje pilkšvi, smulkiai gruoblėti 3 dariniai, didžiausias 1,2x1,2 cm, artimiausias nuo odos rezekcijos krašto nutolęs 0,3 cm. Odoje rusva, aiškių ribų dėmė 0,4x0,3 cm (sudėta visa), nuo rezekcijos krašto (dažytas mėlyna) nutolusi 1 cm. Krūties audinyje pilkšvas, standus, aiškių ribų navikas 1,9x1,5x1,9 cm, nuo artimiausio rezekcijos krašto (dažytas mėlyna) nutolęs 0,3 cm, nuo odos – 1 cm.. 1(2a). Krūties fibrocistiniai pokyčiai. Krūties intraduktalinė papiloma.  2(2b). Krūties fibrocistiniai pokyčiai. Krūties intraduktalinė papiloma.  3(N3). Duktalinės karcinomos metastazės limfmazgiuose (3/13 l/m; iki 27mm; ekstranodalinis naviko plitimas).  4(N1). Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, pT1c(navikas - 19mm) pN1a(3/13 l/m; iki 27mm; ekstranodalinis naviko plitimas).   IHC reakcijos atliktos VPC:B23-33542 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  Ki67+ 10%.  ECAD+."  Odos seborėjinė keratozė. Odos kapiliarinė hemangioma.. 1(2a). Krūties audinys su fibrozinėmis septomis, fokaliai dilatuotais latakais, klotais dvisluoksniu epiteliu; pavieniai dilatuoti latakai su  fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu.  2(2b). Krūties audinys su fibrozinėmis septomis, fokaliai dilatuotais latakais, klotais dvisluoksniu epiteliu; pavieniai dilatuoti latakai su  fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu.  3(N3). Iš trylikos(13) rastų limfmazgių, trijuose(3) žemiau aprašyto naviko metastazės (iki 27mm; ekstranodalinis naviko plitimas).  4(N1). Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas solidinių, trabekulinių, kribriforminių, duktalinių (~15%) struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliai su fokaliai išryškėjusiomis nukleolėmis; navike iki 8 mitozių/10 DPRL; Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse. Naviko struktūros - 0,2mm nuo rezekcijos krašto.  Odos du dariniai - epidermio hiperkeratozė, papilomatozė, besiliejantys epidermio hiperplazijos plotai su pavienių raginių cistų formacija, bazinio sluoksnio hiperpigmentacija. Vienas iš odos darinių: papilinėje dermoje - dilatuotų plonasienių kraujagyslių proliferatai.. nan
answer:  1(

 92%|█████████▏| 611/661 [17:02<01:22,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Paimti 3 biopsiniai stulpeliai.. 3 biopsiniai stulpeliai: I - 12 mm; II - 12 mm; III - 8 mm.. Krūties invazyvi adenokarcinoma, tikėtina lobulinė (ne mažiau kaip vidutiniškai diferencijuota /G2, 6-7 balai pagal Nottingham).  ---   Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100% .   Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 100% .   Her2 imunohistocheminė reakcija: neigiama (1+).  Ki67: 8%.. Trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike ne mažiau 5 / 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100% .   Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 100% .   HER2: silpnas(+) trūkinėjantis membraninis dažymasis 20% naviko ląstelių.   Ki67: 8% .   E-Cadherin: silpna
answer:  0

 93%|█████████▎| 612/661 [17:04<01:22,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2)- pašalinti sarginai l/m - extra (1 mts iš 3 l/m)  2.(N3) papildomi l/m - extra  2(N1)- pašalinta krūtis. 3. Krūtis 302 gramų svorio, 17x12x3 cm, spenelis įtrauktas (sudėtas visas). Krūties audinyje, spenelio projekcijoje pilkšvas standus, neaiškių ribų navikas 18x14x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2 cm. Krūties audinys fibrozuotas visame plote.. 1(Extra). Krūties duktalinės karcinomos metastazė 1/1 limfmazgyje (7 mm).  2(Extra). Reaktyvi limfadenopatija (2 l/m).  3. Krūties invazyvi blogai diferencijuota (G3; 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(12 mm) N(sn)1a(mts 1/3 l/m: 7 mm), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.  Imunofenotipas:   Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: nusidažiusių naviko ląstelių nėra.  HER2 imuninė reakcija: teigiama (3+).  Ki67: 70% (hot-spot 90%).   Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS)(kribriforminė, komedo).  Paget`o liga spenelyje.. 1(Extra). Limfmazgyje - žemiau (Nr.3) aprašyto naviko metastazė (7 mm).  2(Extra). 2 limfmazgiai su fokaline parakortekso hiperplazija, sinusų histiocitoze ir lipomatoze.  3. SPENELIS: epidermyje plinta žemiau aprašyto naviko ląstelės; išopėjimas paviršiuje. DCIS struktūros giliau.   NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai 12 mm), suformuotas fibrozuotoje, fokaliai desmoplastiškoje stromoje infiltratyviai plintančių trabekulinių, lizdinių ir negausių (~10%) besiliejančių tubulinių ir kribriforminių struktūrų iš ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutinio kalibro ir stambiais, ovaliais, polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 36/10 DPRL. Pavieniai mikrokalcifikatai. Šalia yra dilatuotų kanaliukų su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais, fokaliai su komedo nekroze centre. Navikas 3,1 mm nuo rezekcijos krašto.. 3. Spenelis (10 blokas): CK14+ mioepitelinis sluoksnis DCIS struktūrose.  Navikas (19 blokas):  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: nusidažiusių na
answer:  0.

 93%|█████████▎| 613/661 [17:06<01:23,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, planinis  2. pjūvio kraštai, planinis.   3. sarginiai l/m, planinis.   4. sektorius, planinis.. 1. Riebalinio audinio fragmentas 4x2x1 cm. v/m   2. Riebalinio audinio fragmentas 4x1,5x1 cm. v/m   3. Riebalinio audinio fragmentai, bendras dydis 5x4x2 cm. Rasti 4 limfmazgiai, didžiausias 2,5 cm (suriebėję).    4. Krūties sektorius 14x8x6 cm su odos lopu 14x4 cm ir speneliu. Krūties audinyje balkšvas, standus, neaiškių ribų navikas 18x16x15 mm, nuo artimiausio rezekcijos krašto nutolęs 2 cm, siekia spenelį. Rezekcijos kraštas dažytas mėlynu tušu. Naviką supa pilkšva, standi fibrozės zona 9x6x3 cm, makroskopiškai siekianti rezekcijos kraštą. Fibrozės zonoje apvalus, standus darinys 0,9x0,8x0,7 cm.. 1. Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.  2. Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.  3. Reaktyvi limfadenopatija (4 l/m).   4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham sistemą) duktalinė karcinoma, suminis TNM: pT1c (18 mm navikas) N0(sn)(0/4 l/m) LVI-4 (limfovaskulinė invazija smulkiose ir stambiose kraujagyslėse). Radikalus pašalinimas. Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis ir kribriforminis tipai). Krūties fibroadenomos (iki 9 mm). Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.    Naviko imunotipas nustatytas biopsijoje:  Estrogenų receptoriai: stipri reakcija 90% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: teigiama (3+).  Ki67 proliferacinis aktyvumas 20%.. 1. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu, su židinine apokrinine metaplazija.  2. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu, su židinine apokrinine metaplazija.  3. 4 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.  4. Krūties audinyje - fibrozinėje stromoje, infiltratyviu frontu plintantis, stambius latakus apsupantis navikas, suformuotas lizdų, trabekulių, grandinėlių, kribriforminių struktūrų ir pavienių tubulių (<10 %),  Naviko ląstelės su vidutinio gausumo ar gausia, ryškia eozinofiliška citoplazma, vidutinio kalibro , apvaliais ar ovoidiškais, vidutiniškai polimorfiškais branduoliais su ryškiomis nukleolėmis. Mitozių navike iki 61/10DPRL. Naviko plitimas endotelizuotuose spindžiuose ir stambiose venose.   Šalia naviko dilatuoti kanaliukai su intraduktaliniais solidiniais ir kribriforminiais proliferatais iš analogiškų navikui ląstelių.  Atokiau krūties audinyje:  - du riboti dariniai (9 mm ir 1 mm skersmens), suformuoti miksoidinės proliferuojančių fibroblastų stromos su smulkiais, dilatuotais ar suspaustais latakais, klotais dvisluoksniu epiteliu.   - latakai su cistine dilatacija ir apokrinine metaplazija.. nan
answer:  1a

 93%|█████████▎| 614/661 [17:07<01:17,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  1a

 93%|█████████▎| 615/661 [17:09<01:19,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1. Sektoriaus kraštai. N2. Sektoriaus kraštai. N3. Sarginiai l/n. N4.K.krūties sektorius su naviku.. 4. Krūties sektorius 5x2,5x4,5 cm su odos lopu 3,5x0,6 cm. Krūties audinys fibrozuotas 4,5x4 cm plote. Fibrozėje pilkšvas, standus, neaiškių ribų navikas 20x14x14 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 0,8 cm.. 1(ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (6 l/m).   4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1c (navikas 20 mm) N0(sn) (0/6 l/m), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2:reakcijos nėra (0).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).. 1(ekstra). "Kraštai": fibrozuotas krūties audinys su gausiais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": šeši (6) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS (mikroskopiškai - 20 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai negausios besiliejančios duktalinės, dominuojančios trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai ar kiek ryškiau polimorfiškų ląstelių, negausia ar vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su  smulkiomis nukleolėmis; mitozių iki 25/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija.   APLINKA: šalia naviko - solidiniai, kribriforminiai, papiliniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, apokrinės metaplazijos zonomis.   GILUSIS REZEKCIJOS KRAŠTAS: navikas nuo artimiausio rezekcijos krašto nutolusios - 0,6 mm.. 4. Navikas (27 blokas):   E-Cadherin(+++)(membr.r-ja)100%;   HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0.

 93%|█████████▎| 616/661 [17:11<01:15,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Deš. krūties didžiausio židinio (BIRADS V) ties ~10 val darinio stulpelinė biopsija, 2 stulpeliai histologinės medžiagos.. 2 biopsiniai stulpeliai: I - 7 mm; II - 7 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Krūties audinį infiltruoja duktalinės struktūros ir kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 5%
answer:  1b

 93%|█████████▎| 617/661 [17:12<01:14,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. pjūvio kraštai, planinis.   3. sarginiai l/m, planinis.   4. sektorius, planinis.. 1. Riebalinio audinio fragmentas 2,5x2x0,6 cm. v/m  2. Riebalinio audinio fragmentas 2,2x1,5x1 cm. v/m  3. 2 pilkšvi limfmazgiai iki 0,7 cm. v/m  4. Krūties sektorius 12,5x8x7 cm su odos lopu 11x3 cm. Pjūvyje pilkšvas, standus neaiškių ribų 16x16x10 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,3 cm.. 1. Krūties audinio fibrozė.  2. Krūties audinio fibrozė.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(16 mm) pN0(sn)(0/3 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir papilinis tipai). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 12% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. 1. Krūties audinys su fibrozės zonomis smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2. Krūties audinys su fibrozės zonomis smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3. 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (16 mm) infiltratyviu ekspansyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, papilinėmis struktūromis besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai-ryškiai polimorfiškais, ovaliais ir nereguliaraus kontūro skeltais branduoliais ryškiomis nukleolėmis; mitozių 4/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.. Navikas(14 blokas):  silpnas dalies membranos nusidažymas 2%.
answer:  0

 93%|█████████▎| 618/661 [17:14<01:16,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2: kairės pažasties sarginis limfmazgis - skubus tyrimas 3 l/m makrometastazės trijuose limfmazgiuose.   2. N1: pašalinta kairė krūtis planinis tyrimas  3. (N2)Likę pažasties limfmazgiai iš kairės pažasties  - planinis tyrimas priet Nr 2. 2. Krūtis 263,6 gramų svorio, 15,5x10,5x2,5 cm. Krūties audinyje:  - apatiniame medialiniame kvadrante - pilkšvas, standus, neaiškų ribų I navikas 35x25x14 mm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos - 1,2 cm;  - vidurinių kvadrantų riboje - pilkšvas, standus, neaiškių ribų II navikas 18x15x15 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,7 cm, nuo odos - 0,9 cm;  - centrinis krūties audinys balkšvas, standus, fibrozuotas visame plote;  - lateralinių kvadrantų riboje - pilkšvas židinys 8x8x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos 1 cm;  - atstumas tarp I ir II naviko 0,8 cm.  - I NAVIKAS SUDĖTAS NUO MEDIALINĖS PUSĖS LINK CENTRO (9-17 BLOKAI).  3. Riebalinio audinio fragmentai, bendras dydis 5x3,5x1,7 cm. Rasta 10 limfmazgių iki 1 cm.. 1. Krūties lobulinės karcinomos metastazės trijuose limfmazgiuose (3/3 l/m, 14 mm skersmens).   2. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) lobulinė karcinoma su duktalinės karcinomos komponentu (<3%), suminis TNM: pT2(m)(5 naviko židiniai nuo 1 mm iki 33 mm), pN2a(5/16 l/m), LVI2(limfovaskulinis plitimas). Krūties lobulinė karcinoma in situ (LCIS). I naviko židinys nuo koaguliuoto rezekcijos krašto nutolęs per <0,1 mm. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.  3. Krūties lobulinės karcinomos metastazės dviejuose limfmazgiuose (2/10 l/m, 5 mm skersmens).. 1(2). Trijuose iš trijų limfmazgių plinta navikas, analogiškas žemiau aprašytam. Naviko metastazės iki 14 mm skersmens su ekstranodaliniu plitimu.  2. Krūties audinyje - hialinizuotoje stromoje 5 naviko židiniai (33mm, 14mm, 2mm, 1,5mm ir 1 mm mikroskopiškai) infiltratyviu augimo frontu, suformuoti trabekulinių, juostinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, vidutiniškai polimorfiškais, hiperchromiškais branduoliais su pavieniais, paryškėjusiais branduolėliais. Mitozių navike iki 6/10DPRL. Limfovaskulinė naviko invazija (LVI2). I-jame naviko židinyje yra kitas naviko komponentas (1,5 mm), suformuotas tubulinių ir negausių trabekulinių struktūrų ir negausia eozinofiline citoplazma ląstelių su vidutiniškai polimorfiškais branduoliais, ryškiais branduolėliais.   I navikas nuo artimiausio rezekcijos krašto nutolęs per 0,1 mm. Šalia naviko dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Spenelis be patologinių pokyčių.  3. Dviejuose limazgiuose iš 10 (2/10 l/m) plinta navikas, analogiškas aukščiau aprašytam. Naviko metastazės iki 5 mm skersmens.. Blokas 12(duktalinis komponentas):  E-Cadherin: (++)membra.r-ja 90%(duktaliniame komponente)  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.  Prog
answer:  10%.

 94%|█████████▎| 619/661 [17:17<01:18,  1.87s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštai - extra - be naviko  2(N2b). kraštai - extra - be naviko  3(N3). sarg. l/m - extra - be naviko  4(N1). sektorius, planinis, Skubus Ro - 10 mm navikas, MK  pašalintas. 4(1). Krūties sektorius 12x10,5x4,5 cm su odos lopu 8,5x3,5 cm. Krūties audinyje, balkšva, standi fibrozė 4x4 cm plote, nuo giliojo rezekcijos krašto nutolęs 0,1 cm. Fibrozėje neaiškių ribų, pilkšvas židinys 10x10x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1,6 cm.. Papildytas HER2 FISH tyrimu:  1(2a, ekstra). "Kraštai": dažais žymėtoje pusėje - fibrozuotas krūties audinys; be naviko;  (dažais nežymėtoje pusėje - krūties fibrocistiniai pokyčiai: paprasta ir atipinė intraduktalinė hiperplazija).   2(2b, ekstra). "Kraštai": dažais žymėtoje pusėje - fibrozuotas krūties audinys; be naviko;   (dažais nežymėtoje pusėje - krūties fibrocistiniai pokyčiai: paprasta ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė).   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(1). Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 7 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).   Kalcifikatai.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis ir papilinis tipai; bendra pokyčių zona su naviku ~15 mm skersmens).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).. 1(2a, ekstra). "Kraštai": dažais žymėtame krašte - fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko. Priešingoje dažais nežymėtoje pusėje - kelios zonos su ryškesne epitelio atipija.   2(2b, ekstra). "Kraštai": dažais žymėtame krašte - fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko. Priešingoje dažais nežymėtoje pusėje - kelios zonos su ryškesne epitelio atipija, fokaliai suspausti kanaliukai, kloti dvisluoksniu epiteliu.   3(ekstra). "Sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.     4(1). NAVIKAS (mikroskopiškai - 7 mm infiltratyvus židinys; su aplinkine fibroze ir in situ pokyčių zona - 15 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės, netaisyklingos liaukinės, kribriforminės ir retos lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais kiek skeltais branduoliais; mitozės pavienės retos, mažiau 5/10 DPRL. Naviko ląstelės fokaliai su apikalinėmis sekrecinėmis vakuolėmis. Pavieniai mikrokalcifikatai.  APLINKA: šalia naviko - kribriforminiai ir papiliniai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, intraduktalinėmis papilinėmis formacijomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti.   SEKTORIAUS REZEKCIJOS KRAŠTAS: fibrozuotas krūties audinys su aukščiau aprašytais fibrocistiniais pokyčiais; be naviko.. 4(1). Navikas (blokas 15):  CK14/CK5(+) miopetelinis sl. in situ komponente;   HER2: vidutinė (++) necirkuliari reakcija, 20% naviko ląstelių membranoje.
answer:  1(

 94%|█████████▍| 620/661 [17:18<01:16,  1.86s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2A)-kraštas -extra-muvcininės karcinomos židinys  2(N2b)-kraštas -extra-be naviko   3(N3)-l/m-extra-be naviko   4.(pap.kraštas Nr.4) extra - Atlikta krašto reekscizija - be naviko   5.(N1)- sektorius - skubus rentgeninis tyrimas- 2 navikai pašalinti N1- sektorius -  planinis patologinis tyrimas. 5. Krūties sektorius 9,5x6x4 cm su odos lopu 9x3,5 cm žymėtas 2 vielomis(atstumas tarp vielų - 4,5 cm). I vielos projekcijoje pilkšvas, elastingas, kiek mucininis I navikas 16x11x10 mm. II vielos projekcijoje analogiškas II navikas 14x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos – 2,5 cm.. 1(2a). Krūties invazyvi, vidutiniškai diferencijuota (G2) mucininė karcinoma.  Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas).  2(2b). Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis, mikropapilinis tipas).  3. Reaktyvi limfadenopatija (1 l/m).  4(pap. kraštas). Krūties audinys.   5. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) mucininė karcinoma, suminis tyrimo TNM: pT1c(m)(du naviko židiniai: 16mm ir 14mm) pN0(sn)(0/1 l/m).   IHC reakcijos atliktos VPC:B23-31824 tyrime:   "Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 3%."  Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas).. 1(2a). Krūties audinyje - ekstraląstelinių mucinų zonos su naviko ląstelių kompleksais; fibrozinėje stromoje - dilatuoti latakai su kribriforminiais atipinių ląstelių (su nedidelio laipsnio branduolių polimorfizmu) prolideratais (DCIS).  2(2b). Krūties audinyje - fibrozės zonos su dilatuotais latakais, fokaliai su mucinais spindžiuose ir mikropapiliais, kribriforminiais atipinių ląstelių (su nedidelio laipsnio branduolių polimorfizmu) proliferatais (DCIS).   3. Vienas(1) limfmazgis be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4(pap. kraštas). Riebalinis audinys su fibrozinėmis septomis, pavieniais latakėliais, klotais dvisluoksniu epiteliu.   5. Krūties audinyje - du naviko židiniai (16mm ir 14mm), formuojami ekstraląstelinių mucinų su smulkiais solidiniais naviko kompleksais, formuojamais vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 4 mitozių/10 DPRL. Aplinkiniame krūties audinyje - fibrozės zonos su dilatuotais latakais, fokaliai su mucinais spindžiuose ir kribriforminiais atipinių ląstelių (su nedidelio laipsnio branduolių polimorfizmu) proliferatais (DCIS).. nan
answer:  1(

 94%|█████████▍| 621/661 [17:20<01:12,  1.81s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- Deš. pažasties sarginiai limfmazgiai, skubu  4(3)- Deš. krūties kvadrantas, planinis. 4. Krūties sektorius 8x6x6 cm su odos lopu 8x1 cm. Pjūvyje balkšvas, spikulinių kraštų, standus navikas 18x14x23 mm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos – 0,7 cm.. Atlikti pjūviai Prosigna.  1(ekstra). Riebalinis audinys.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(18 mm navikas) pN0(sn)(0/3 l/m) LVI-2(limfovaskulinė invazija).   R0(radikali rezekcija). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, kribriforminis tipas).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 15%.. 1(ekstra). Riebalinis audinys su fibrozinėmis septomis.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.   3(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (18 mm) infiltratyviu augimo frontu, suformuotas, susiliejančiomis tubulinėmis, kribriforminėmis ir trabekulinėmis struktūromis besidėstančių ląstelių  vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 16/10 DPRL. Limfovaskulinė invazija. Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais ir solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) ---- %.  Progesterono receptoriai: (+++)(brand. r-ja) ---- %.  HER2: silpnas/vidutinis/stiprus dalies/visos membranos nusidažymas xx% naviko ląstelių.  Ki67 proliferacinis aktyvumas ---- %.  CK5+ išlaiky
answer:  100%.

 94%|█████████▍| 622/661 [17:22<01:12,  1.86s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). Sarginiai l/n-extra.   2(N2). Kairė krūtis su naviku.. 2. Krūtis 381 gramų svorio, 17x10,5x4,5 cm, spenelis įdubęs. Apatiniame medialiniame kvadrante - pilkšvas standus, aiškių ribų navikas 21x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 1,8 cm. Centrinė krūties dalis fibrozuota 8x5,5 cm plote. Makroskopiškai fibrozėje satelitiniai naviko židiniai neidentifikuojami.. PAPILDYTAS ATSAKYMAS HER2 FISH TYRIMU:   1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (5 l/m).     2. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT2 (navikas 21 mm) N0(sn) (0/5 l/m),    LVI-0 (limfovaskulinė invazija neidentifikuota).    Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.    Molekuliniai tyrimai:   HER2 geno amplifikacija nenustatyta (interpretuojama įvertinus HER2 IHC tyrimą; žr. molekulinio tyrimo aprašymą ir pastabas).    Krūties lobulinė intraepitelinė neoplazija (LCIS).  Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė duktalinė hiperplazija, sklerozuojanti ir mikroglandulinė adenozė, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija; fokaliai fibrocistiniai pokyčiai - kompleksiniai, sudarantys iki 10 mm skersmens židinius).   Krūties rezekcijos kraštas - be naviko.. 1(ekstra). "Sarginiai limfmazgiai": penki (5) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2. SPENELIS: klotas fokaliai akantotišku epidermiu su židinine bazinio sl. hiperpigmentacija.   NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", solidinės naviko struktūros, suformuotos mažai kohezyvių saikingai ar vidutiniškai polimorfiškų ląstelių, negausia ar vidutinio gausumo šviesia citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 12/10 DPRL. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Smulkūs kalcifikatai. Pavieniais hemosiderofagai.   APLINKA: zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti, kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu, fokaliai nedideli intraduktaliniai proliferatai; fokaliai krūties audiniopokyčiai sudaro ribotus lobulizuotus gan ribotus židinius su edemiška stroma, iki 10 mm skersmens. Atliktas platus fibrozuotos zonos ištyrimas.   GILUSIS REZEKCIJOS KRAŠTAS: infiltratyvus navikas nutolęs 5 mm.. 2. Navikas (blokas 14):  HER2: vidutinė (++) necirkuliari reakcija, 10%  naviko ląstelių membranoje.
answer:  2+

 94%|█████████▍| 623/661 [17:24<01:08,  1.81s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. deš krūtis su pažasties l/m, planinis. Krūtis 500 g svorio, 20x13,5x4,5 cm, su raumens fragmentu 2,2x1,6x0,6 cm.   Krūties audinyje, viršutinių kvadrantų riboje, pilkšvas standus neaiškių ribų I navikas 27x20x12 mm (pereinantis į fibrozę), nuo giliojo rezekcijos krašto nutolęs 0,2, nuo odos - 2,2 cm.   Raumens projekcijoje pilkšvas standus, neaiškių ribų II navikas 20x20x12 cm., nuo giliojo rezekcijos krašto nutolęs 0,2 cm, siekia odą. Atskirai tame pačiame inde, pažasties narvelienos fragmentas 8,5x6x2,5 cm. Rasta 10 limfmazgių iki 2 cm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;   pT(m)2(22 mm, 27 mm)   pN1a(2,2 mm 1-me/10 l/m)   pR0 (0,5 mm)   pPn1(perineurinis plitimas).  Metastazės limfmazgyje imunotipas:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).    Imunotipas priešoperaciniame naviko tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%.. Krūties audinyje 2 navikiniai židiniai (I-as 22 mm, II-as 27 mm): infiltruoja duktalinės ir negausios kribrozinės struktūros iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  I-as navikas 2 mm , II-as navikas 0,5 mm nuo operacinio krašto ir su perineuriniu plitimu.  Aprašyto naviko ląstelių solidiniai židiniai iki 2,2 mm 1-me/10 limfmazgyje; ekstranodulinio plitimo nestebima.. Blokas 23:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  1a

 94%|█████████▍| 624/661 [17:25<01:06,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 1 pjūvio kraštas, ekstra.  2. 2 pjūvio kraštas, ekstra.   3. sarginiai l/m, ekstra.  4. sektorius, planinis.. 4. Krūties sektorius 12,5x4,5x6,5 cm, su odos lopu 9x3 cm, žymėtas viela. Vielos projekcijoje pilkšvas, standus  gan aiškių ribų navikas 13x10x8 mm, nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo odos - 2,2 cm. Navikas histologiniam ištyrimui sudėtas visas.. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai, paprasta intraduktalinė hiperplazija. Intraduktalinė krūties papiloma.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi, vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(navikas - 13mm) pN0(sn)(0/3 l/m); LVI-0 (Limfo-Vaskulinė naviko Invazija neidentifikuota).   IHC reakcijos atliktos VPC:B23-19620 tyrime:  "Estrogenų receptoriai: stipri (+++)  reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67+ 15%."  Vidutinio laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas).. 1. Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu.  2. Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu su židinine apokrinine metaplazija; dilatuoti latakėliai su paprasta intraduktaline hiperplazija; dilatuoti latakėliai su fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu.  3. Trys(3) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4. Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas solidinių/lizdinių, pavienių duktalinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike - iki 10 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su kribriforminiais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS). Rezekcijos kraštas be naviko.. nan
answer:  1a

 95%|█████████▍| 625/661 [17:27<01:00,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 stulpeliai. 2 biopsiniai stulpeliai: I - 17 mm; II - 15 mm.. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: teigiama ribinė neigiama (0).  Ki67 proliferacinis aktyvumas 40%.. Bioptatuose (2/2) - fibrozinėje stromoje, infiltratyvios naviko struktūros, lizdais, trabekulėmis ir solidiniai plotais besidėstančių ląstelių negausia-vidutinio gausumo eozinofiliška citoplazma, ryškiai polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 22/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas pavienių naviko ląstelių membr. dažymasis.  Ki67 proliferacinis aktyvumas 40%.  GATA3(+++)(brand. r-ja) 100%; E-cadherin(+++) memb
answer:  100%

 95%|█████████▍| 626/661 [17:29<00:58,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: NR1 Kair. krūties dominuojančio darinio biopsija, paimti 3 biopsiniai stulepliai  2 ėminio aprašas: NR2 Kair. krūties satelitinio darinio biopsija, paimti 2 biopsiniai stulepliai  3 ėminio aprašas: NR 3 Kair. pažasties pakitusio l/m biopsija, paimti 2 biopsiniai stulepliai. 1. 3 biopsiniai stulpeliai: I - 15 mm; II - 11 mm; III - 9 mm.  2. 2 biopsiniai stulpeliai: I - 11 mm; II - 9 mm.  3. 2 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 12 mm.. N1-2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.  N3: Limfmazgio bioptatai ne naviko.. N1-2: Visuose krūties audinio bioptatuose tokios pačios struktūros navikas: duktalinės struktūros, nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  N3: Limfmazgio bioptatai ne naviko.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 10%
answer:  0

 95%|█████████▍| 627/661 [17:30<00:55,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 but.  2 biopsiniai stulpeliai iš ploto kairėje viršutiniame kvadrante   2 but.  2 biopsiniai stulpeliai iš ploto kairėje  virš spenelio @#3 but. 1 biopsinis stulpelis iš darinio dešinėje krūtyje  viršutiniame lateraliniame kv-te. 1. 2 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 9 mm.   2. 2 biopsiniai stulpeliai: I - 14 mm; II - 10 mm.   3. Biopsinis stulpelis 9 mm.. Kairė  N1-2: Intraduktalinė krūties Carcinoma in situ (Din2/DCIS; solidinis/kribriforminis tipas).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  ---------  Dešinė  N3: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis iki 20%.. Kairė  N1-2: Krūties audinyje dilatuotuose kanaliukuose solidiniai/kribroziniai neryškiai polimorfiškų ląstelių proliferatai.  ---------  Dešinė  N3: Krūties audinį infiltruoja pavienės duktalinės struktūros, nedideli netaisyklingi solidiniai kompleksai iš neryškiai ir vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. nan
answer:  0.

 95%|█████████▌| 628/661 [17:32<00:52,  1.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai; I - 13 mm; II - 9 mm.. Krūties invazyvi blogai diferencijuota (G3, 8-9 balai pagal Nottingham) duktalinė adenokarcinoma.  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2: imuninė reakcija neigiama (0 balų).  Ki67: 45%.. Solidines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne blyškiai-saikingai eozinofiline citoplazma, vidutinio kalibro apvalios formos saikingai netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 40 / 10 DPRL.. Navikas  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2: nusidažiusių naviko ląstelių nėra.  Ki67: 45%. CK5(+/++)(citoplazminė r-ja), 20%.
answer:  3b

 95%|█████████▌| 629/661 [17:33<00:50,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but.  3 biopsiniai stulpeliai iš ~ 10 mm  neaiškių ribų  dešinės krūties darinio   2 but. 2 biopsiniai stulpeliai iš  ~ 30 mm dydžio kairės krūties darinio. 1. 3 biopsiniai stulpeliai: I - 21 mm; II - 14 mm; III - 10 mm.  2. 2 fragmentuoti biopsiniai stulpeliai: I - 11 mm; II - 13 mm.. Po operacinės medžiagos tyrimo patikslintas N1 naviko tipas  Dešinė  N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.  ------------  Kairė  N2: Mucininė krūties karcinoma (G2, 6 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Dešinė  N1: Krūties audinį infiltruoja smulkios duktalinės struktūros ir solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  ------------  Kairė  N2: Krūties audinyje mucininėje stromoje solidiniai/kribroziniai kompleksai vidutinio polimorfizmo ląstelių, mitozių iki 3/10 DPRL.. nan
answer:  1a

 95%|█████████▌| 630/661 [17:35<00:52,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 1a- viršutinis kraštas, skubu  2. 1b- apatinis kraštas, skubu  3. (2.) Deš. pažasties sarginiai limfmazgiai, skubu  4. (3) deš. krūties sektorius, planinis. 4. Krūties sektorius 6x3,3x6 cm, su odos lopu 5,5x2 cm, žymėtas viela. Vielos projekcijoje pilkšvas, neaiškių ribų, standus navikas 12x12x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos nutolęs 2 cm.. 1(1a, ekstra). "Viršutinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   2(1b, ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.    3(2, ekstra). "Deš. pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) mucininė karcinoma,   SUMINIS TNM:   pT1c (navikas 12 mm) N0(sn) (0/3 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose).     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis ir papilinis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Nuo sektoriaus rezekcijos krašto navikas nutolęs 0,15 mm.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu; be naviko.   2(1b, ekstra). "Apatinis kraštas": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu; be naviko.   3(2, ekstra). "Deš. pažasties sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.     4. NAVIKAS (mikro 12 mm židinys, su aplinkine fibroze pokyčių plotas ~22 mm skersmens):   krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, tarp gausių AB+ ekstraląstelinių mucinų telkinių infiltratyviai plinta fokaliai besiliejančios papilinė, kribriforminės ir lizdinės naviko struktūros, suformuotos saikingai polimorfiškų ląstelių, vidutinio gausumo eozinofiline citoplazma, vidutinio dydžio kiek nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 14/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose.   APLINKA: šalia naviko - keli kribriforminiai ir papiliniai intraduktaliniai naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: navikas nutolęs 0,15 mm.. 4. Navikas (blokas 15):  EMA(+) židininė citopl. r-ja.   HER2: silpna (+) necirkuliari reakcija, 20% naviko ląstelių membranoje.
answer:  1a

 95%|█████████▌| 631/661 [17:37<00:49,  1.63s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.N2a - skubu - kraštai  2.N2b kraštai  -  skubus tyrimas - be naviko  3. N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas 1 l/m be naviko.  4. N1: dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 12x7x4cm su odos lopu 11x2,7 cm. Krūties audinyje - balkšvas, standus, vietomis neaiškių ribų navikas 2x1,4x1,8 cm, nuo giliojo rezekcijos krašto (dažytas mėlynu tušu) nutolęs 0,7 cm, nuo odos - 4 cm.. N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(20mm).  N2ab: Audiniai be naviko.  N3: Limfmazgis (1 l/m) be naviko; pN0(sn).. N1: Krūties audinyje 20mm navikas: negausios smulkios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.  N2ab: Audiniai be naviko.  N3: Limfmazgis (1 l/m) be naviko.. nan
answer:  0

 96%|█████████▌| 632/661 [17:38<00:48,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. (2). Kairės pažasties sarginiai limfmazgiai, skubu  2. (1a)- viršutinis kraštas, skubu  3. (1b)- apatinis kraštas, skubu.   4. (3). Kairės krūties kvadrantas, planinis. 4. Krūties sektorius 9,5x7,5x5 cm, su odos lopu cm. Krūties audinyje, pjūvyje pilkšvas, standus, gan aiškių ribų navikas 35x35x25 mm, nuo giliojo rezekcijos krašto nutolęs 1,3 cm, nuo odos - 2,6 cm.. 1(2)(Extra). Reaktyvi limfadenopatija (3 l/m).  2(1a)(Extra). Krūties audinys.  3(1b)(Extra). Krūties audinys.  4. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(33 mm) N(sn)0(0/3 l/m), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).. 1(2)(Extra). 3 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  2(1a)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  3(1b)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 33 mm), suformuotas fibrozuotoje stromoje ir tarp lipocitų infiltratyviai plintančių lizdinių, trabekulinių ir besiliejančių tubulinių struktūrų bei negausių smulkiomis grupėmis ar grandinėlėmis besidėstančių ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais ar kiek nereguliaraus kontūro, vidutiniškai polimorfiškais, dalis su smulkia nukleole branduoliais. Gausūs retrakcijos artefaktai aplink naviko struktūras. Mitozių iki 4/10 DPRL. Negausūs makrofagų ir limfocitų židiniai, smulkios elastozės zonos.  Aplinkiniame krūties audinyje - dilatuoti kanaliukai/latakai, fokaliai su makrofagais spindžiuose.. 1. Navikas (15 blokas): EMA(+/+++)(citopl.-membr. r-ja), 85%; naviko struktūros D2-40+ endotelizuotoje ertmėje.  Navikas (19 blokas):  E-Cadherin(++/+++)(cirkuliari, fokaliai trūkinėjanti membr. r-ja), 100%;   p120(+++)(cirkuliari, fokaliai trūkinėjanti m
answer:  100%;

 96%|█████████▌| 633/661 [17:40<00:47,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. sarginiai l/m, ekstra.  2 .pap.sarginis l/m-extra   3(2). kairė krūtis, planinis.. 2. Krūtis 24x20x6,5 cm, 1300 gramų svorio. Odoje neaiškių ribų, gruoblėta dėmė 1,4x0,7 cm, nuo odos nutolusi 0,3 cm. Krūties audinyje, apatinių kvadrantų riboje pilkšvas, skiltėtas, standus navikas 34x25x20 mm, nuo giliojo rezekcijos krašto nutolęs 3 cm, nuo odos - 2,5 cm. Šalia naviko pilkšvas, ribotas darinys 0,4x0,4x0,4 cm.. 1(Extra). Reaktyvi limfadenopatija (6 l/m).  2(Extra). Reaktyvi limfadenopatija (1 l/m).  3. Krūties invazyvi blogai diferencijuota (G3; 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT(m)2(2 naviko židiniai: 28 mm ir 4 mm) N(sn)0(0/7 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas (R0).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Odos seborėjinė keratozė.. 1(Extra). 6 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  2(Extra). Limfmazgis su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  3. SPENELIS: be patologijos.  ODA: darinys su epidermio papiliarizacija ir neryškia akantoze ir hiperkeratoze, bazinių ląstelių hiperplazija ir hiperpigmentacija bei smulkiomis keratininėmis cistomis.  NAVIKAS: krūties audinyje - 2 riboti analogiškos struktūros navikai (mikroskopiškai 28 mm ir 4 mm), suformuoti fibrozuotoje stromoje plintančių trabekulinių, lizdinių ir negausių solidinių struktūrų iš ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 35/10 DPRL. Navike yra nekrozės zonų, fokalinė intra-/perinavikinė MMN infiltracija.. 1. Navikas (24 blokas):  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  Proliferacinis aktyvumas: Ki67(+++)(branduolinė r-
answer:  100%

 96%|█████████▌| 634/661 [17:42<00:47,  1.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 12x7x6 cm su odos lopu 10x4 cm, žymėtas viela. Metalinė viela pilnai perveria sektorių. Krūties audinyje:  - 3 cm nuo vielos - balkšvas, standus, neaiškių ribų I navikas 1,2x0,8x1,2 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos – 1,4 cm. Navikas histologiniam ištyrimui sudėtas visas.  - vielos projekcijoje - balkšvas, standus II naviko židinys 0,2 cm skersmens, nuo rezekcijos krašto nutolęs 0,5 cm.   Aplinkiniame krūties audinyje cistos iki 0,8 cm skersmens. Krūties audinyje, 1,5 cm atstumu nuo vielos rasta metalinė kabutė, aplinkiniai audiniai be makroskopinių pokyčių.. 1(ekstra). Pjūvio kraštai. Krūties fibrocistiniai pokyčiai, apokrininė metaplazija. Naviko plitimo nėra.    2(ekstra). Pjūvio kraštai. Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.     3(ekstra). Sarginiai l/m. Duktalinės karcinomos metastazė 2-se/9 limfmazgių (iki 2,1 mm metastazė).     4. Sektorius.   Krūties invazyvi vidutiniškai diferencijuota duktalinė karcinoma   (G2, I navike - 7 balai, II navike - 6 balai pagal Nottingham sistemą) ,    pT1c(m) (12 mm ir 2 mm naviko židiniai)    pN1a(sn)(2-se/9 l/m su mts iki 2,1 mm)     pLVI-2 (limfovaskulinė invazija smulkiose gyslose)    pR0(radikalus pašalinimas).  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%. Karštame taške 20%.. 1(ekstra). Pjūvio kraštai. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu, su židinine apokrinine metaplazija. Naviko plitimo nėra.  2(ekstra). Pjūvio kraštai. Krūties audinys su fibrozės zonomis ir smulkiais, dalis cistiškai dilatuotais kanaliukais bei lobulėmis, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.  3(ekstra). Sarginiai l/m. Riebaliniame audinyje - trys makroskopiškai aprašyti ir šeši smulkūs limfmazgiai.   1-me/9 limfmazgių - žemiau aprašyto naviko metastazė 2,1 mm.   1-me limfmazgyje izoliuotos naviko ląstelės (0,18 mm dydžio metastazė).    4. Sektorius. Krūties audinyje ir ties metaline viela - du naviko židiniai (I - 12 mm, II - 2,1 mm mikroskopiškai), suformuoti lizdų, trabekulių, tubulių (30%). Naviko ląstelės su negausia, neaiškių ribų eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais ar skeltais, vidutiniškai polimorfiškais branduoliais su pavienėmis smulkiomis nukleolėmis.   Mitozių I navike iki 20/10DPRL, II navike - iki 4/10DPRL. Naviko plitimas endotelizuotuose spindžiuose. Navikas nuo sektoriaus rezekcijos krašto nutolęs 0,9 mm.  Metalinės kabutės projekcijoje ir atokiau krūties audinys su dilatuotais latakais ir židinine apokrinine metaplazija.. Blokas 16:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių. Karštame taške 20%.  Progesterono re
answer:  1(

 96%|█████████▌| 635/661 [17:43<00:43,  1.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 11 mm; II - 10 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6 mm);  (G3; 9 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 85%.. Krūties audinį 2-se bioptatuose infiltruoja iki 6 mm :   - solidiniai kompleksai;  - stambių ląstelių su ryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 20/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  CK5: silpna teigiama (+)  membraninė reakcija 30proc. atipinėse ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliu
answer:  3b

 96%|█████████▌| 636/661 [17:46<00:46,  1.86s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas - be naviko   2(N2b) - kraštas - skubus tyrimas - be naviko  3(N4a) - kraštas - skubus tyrimas - be naviko   4(N4b) - kraštas - skubus tyrimas - be naviko  5(N1) - pašalintas kairės krūties markiruotas plotas - planinis tyrimas  6(N3) - pašalintas dešinės krūties markiruotas plotas - planinis tyrimas. 5. Krūties sektorius 9x5,5x4 cm su odos lopu 8x4 cm, žymėtas viela. Vielos projekcijoje, pjūvyje fibrozės zona 5,5x4x3 cm, siekia artimiausią rezekcijos kraštą, nuo odos – 1,5 cm.  6. Krūties sektorius 9x5x2 cm, žymėtas 2 vielomis. Tarp vielų, pjūvyje fibrozės zona 5,5x4,5x1,7 cm, siekia artimiausią rezekcijos kraštą.. 1(N2a). Krūties lobulinė karcinoma (židinys 1mm). Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.   2(N2b). Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.  3(N4a). Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.  4(N4b). Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.  5(N1). Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) lobulinė karcinoma (multižidininis navikas), pT2(m)(dauginiai naviko židiniai nuo 0,6mm iki 31mm); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  Estrogenų receptoriai: reakcija teigiama (stipri branduolių r-ja, 100% naviko ląstelių).   Progesterono receptoriai: reakcija teigiama (silpna/vidutinė/stipri branduolių r-ja, 85% naviko ląstelių).   HER2: žema imunohistocheminė raiška (1+).  Ki67 proliferacinis aktyvumas ~20%, fokaliai iki 30%.   Lobulinė krūties karcinoma in situ (LCIS). Krūties aukšto laipsnio intraduktalinė karcinoma (DCIS; solidinis ir kribriforminis tipas, -komedo tipo nekrozės). Fibrocistiniai krūties pokyčiai; sklerozuojanti adenozė. LCIS struktūros - rezekcijos krašte.  6(N3). Krūties žemo ir vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis ir kribriforminis tipas; -komedo tipo nekrozės).    IHC reakcijos atliktos VPC:B23-41914 tyrime:  "Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių."  Lobulinė krūties karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai; sklerozuojanti adenozė; intraduktaliniai ir ekstraduktaliniai mikrokalcifikatai. Rezekcijos kraštas be naviko.. 1(N2a). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu; intraduktalinių mikrokalcifikatų židiniai; fibroziniame audinyje ir tarp lipocitų plinta negausios monotoniškos ląstelės (židinys - 1mm).   2(N2b). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu; intraduktalinių mikrokalcifikatų židiniai.  3(N4a). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu; intraduktalinių mikrokalcifikatų židiniai.  4(N4b). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu; intraduktalinių mikrokalcifikatų židiniai.  5(N1). Krūties audinyje - dauginiai naviko židiniai (nuo 0,6mm iki 31mm), formuojami difuziškai, trabekulėmis plintančių vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais; navike iki 19 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais diskohezyvių atipinių ląstelių proliferatais (LCIS). Dilatuoti latakai su solidiniais ir kribriforminiais atipinių ląstelių (su ryškiu branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakais, klotais dvisluoksniu epiteliu; smulkių latakėlių, klotų dvisluoksniu epiteliu organoidinės proliferacijos fibrozinėje stromoje zonos, intraduktalinių mikrokalcifiktų židiniai. LCIS struktūros - rezekcijos krašte.  6(N3). Krūties audinyje - dilatuoti latakai su solidiniais ir kribriforminiais atipinių ląstelių (su žemo ir vidutinio laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS); fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu; intraduktaliniai ir ekstraduktaliniai mikrokalcifikatai; smulkių latakėlių, klotų dvisluoksniu epitelių organoidinės proliferacijos fibrozuotoje stromoje zonos. Rezekcijos kraštas be naviko.. 5(N1). Blokas 12:  Navikas:  Estrogenų receptoriai: stipri branduolių r-ja, 100% naviko ląstelių.   Progesterono receptoriai: silpna/vidutinė/stipri branduolių r-ja, 85% naviko ląstelių.   HER2: silpna dalies membranos reakcija, 15% naviko ląstelių.  Ki67
answer:  20%.

 96%|█████████▋| 637/661 [17:47<00:42,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 4 biopsiniai stulpeliai.. 4 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 9 mm; III - 8 mm; IV - 8 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%, vietomis iki 15%.. Krūties audinį infiltruoja netaisyklingi kribroziniai/solidiniai kompleksai ir trabekulės iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 20% n
answer:  0.

 97%|█████████▋| 638/661 [17:49<00:40,  1.76s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. (N2a) kraštai -  skubus tyrimas - be naviko  2. (N2b) kraštai -  skubus tyrimas - be naviko  3. (N3) kairės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko  4. (N1) pašalintas kairės krūties markiruotas kvadrantas - planinis tyrimas. 4(N1). Krūties sektorius 5x5,5x3 cm, be odos, žymėtas viela. Vielos projekcijoje - pilkšvas, standus, neaiškių ribų I navikas 11x6x5 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm. 0,4 cm atstumu (galimai susiliejantis) nuo I naviko - analogiškas II navikas 10x7x5 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm. Šalia II naviko ribota hemoragija 0,5 cm skersmens. Sektoriaus krašte tamsiai rudas darinys (ankstesnės biopsijos vieta) 1,6x1,2x0,4 cm.. 1(N2a). Krūties fibrocistiniai pokyčiai.  2(N2b). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (3 l/m).  4(N1). Krūties invazyvi duktalinė karcinoma (gerai diferencijuota / G1 / 5 balai pagal Nottingham), TNM (Nr.1-Nr4): pT1c(m) (1,1 cm ir 1,0 cm naviko židiniai) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 1-2%.. 1(N2a). Krūties audinyje - negausūs fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, minimaliai dilatuotais kanaliukais.  2(N2b). Krūties audinyje - negausūs fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, minimaliai dilatuotais kanaliukais.  3(N3). Sinusų histiocitozė trijuose (3) limfmazgiuose.  4(N1). Krūties audinyje - du panašios architektūrinės ir citologinės išvaizdos naviko židiniai (tubulines (80%), negausias smulkias kribrozines naviko struktūras formuoja ląstelės su kiek gausesne švelniai eozinofiline citoplazma, smulkiais ar kiek stambesnio kalibro kiek netaisyklingais, dalis su smulkia nukleole branduoliais; mitozių navikuose: 1-2 / 10 DPRL.. 4(N1). Navikas (20 blokas): HER2 Nusidažiusių naviko ląstelių nėra.
answer:  4(n

 97%|█████████▋| 639/661 [17:51<00:38,  1.75s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas markiruotas dešinės krūties kvadrantas - planinis tyrimas  2 ėminio aprašas: N2a kraštai - planinis tyrimas  3 ėminio aprašas: N2b kraštai - planinis tyrimas  4 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis planinis tyrimas. 1. Krūties sektorius 11,5x4,5x3,5 cm su oda 8x2,3 cm, žymėtas viela. Vielos projekcijoje - pilkšvas, standus, aiškių ribų navikas 10x10x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 2,3 cm.  2. Riebalinio audinio fragmentas 2,5x1,6x0,4 cm. v/m  3. Riebalinio audinio fragmentas 2x1,5x0,6 cm. v/m  4. Riebalinio audinio fragmentas 4x4x1,5 cm. Rasti 5 limfmazgiai iki 1,7 cm.. Paruošti pjūviai Prosigna.  1. Krūties vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: T1b(9 mm navikas) pN1a(sn)(1/5 l/m MTS 16 mm) LVI-2(limfovaskulinė invazija ).  R0(radikali rezekcija).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 80% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 3%.    2. Krūties audinio fibrozė.  3. Krūties audinio fibrozė.  4. Duktalinės karcinomos metastazė limfmazgyje (1/5 l/m MTS 16 mm).. 1. Krūtyje - navikas (9 mm) infiltratyviu augimo frontu, suformuotas trabekulinėmis struktūromis besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais apvaliais; mitozių 3/10 DPRL.  Aplinkinis krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2. Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Riebalinis fibrozinis audinys.  4. 1 iš 5 limfmazgių aprašyto naviko metastazė 16 mm.. nan
answer:  1a

 97%|█████████▋| 640/661 [17:52<00:35,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 10 mm; II - 10 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.. Krūties audinį infiltruoja negausios duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis visos membranos nusidažymas 15% naviko ląstelių.  K
answer:  0.

 97%|█████████▋| 641/661 [17:54<00:36,  1.83s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - deš. užspenelinė zona - extra  2 - deš. pažasties sarginiai l/m - extra  3 - deš. krūties liauka - planinis  4 - k.krūties liauka - planinis. 3. Krūtis 14x13,5x4 cm be odos. Krūties audinyje pilkšvas, aiškių ribų, standus, kiek skiltėtos struktūros navikas 16x13x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo poodinio rezekcijos krašto - 1,5 cm. Spenelinė zona dažyta raudonai, jos projekcijoje krūties audinys fibrozuotas 5x3 cm plote su smulkiomis cistinėmis ertmėmis iki 0,3 cm skersmens.  4. Krūtis 14x11,5x3 cm be odos. Spenelinė zona dažyta raudonai, jos projekcijoje krūties audinys fibrozuotas 5x3,5 cm plote su smulkiomis cistinėmis ertmėmis iki 0,3 cm skersmens.. 1(ekstra) Dešinė užspenelinė zona: fibrocistiniai pokyčiai.   2(ekstra) Deš. pažasties sarginiai l/m. Reaktyvi limfadenopatija (2 l/m).   3. Dešinės krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(16 mm navikas) N0(sn)(2 l/m) LVI-0(limfovaskulinė invazija neidentifikuota) R0(radikali rezekcija). Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, DIN3, kribriforminis ir papilinis tipai).  Krūties fibrocistiniai pokyčiai, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).     Naviko imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 70%.  Androgenų receptoriai: reakcijos nėra.       4. Kairės krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, pT1c(11 mm židinys) LVI-0(limfovaskulinė invazija neidentifikuota) R0(radikali rezekcija). Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, DIN3, solidinis, komedo tipai). Krūties fibrocistiniai pokyčiai, ląstelinga (florid) adenozė, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS). Lobulinė karcinoma in situ (LCIS).  Naviko imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 70%.. 1(ekstra) Dešinė užspenelinė zona. Švelniai fibrozuotas krūties audinys su smulkiais ar pavieniais cistiškai dilatuotais latakais, klotais dvisluoksniu epiteliu.  2(ekstra) Deš. pažasties sarginiai l/m. 2 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.     3. Dešinė krūties liauka. Krūties audinyje - navikas, suformuotas desmoplastiškoje stromoje besidėstančių trabekulinių, lizdinių struktūrų ir solidinių plotų. Naviko ląstelės vidutinio gausumo tamsia eozinofiliška citoplazma, vidutinio kalibro, ryškiai polimorfiškais, ovaliais ir nereguliaraus kontūro branduoliais su vesikuolizuotu chromatinu ir smulkiomis nukleolėmis; mitozių iki 58/10 DPRL. Navike yra komedonekrozių. Fokaliai stromoje gausi monomorfonuklearų infiltracija. Navikas nuo rezekcijos krašto nutolęs 3 mm.  Šalia yra stambių latakų su kribriforminiais ir papiliniais proliferatais, suformuotais navikui analogiškų ląstelių.   Aplinkinis krūties audinys su fibrozės apsuptais smulkiais ar pavieniais cistiškai dilatuotais latakais su pavienėmis smulkiomis papilomis, klotais dvisluoksniu epiteliu, fokaliai su apikalinės sekrecijos požymiais ir apokrinine metaplazija. Dalis lobulių apsuptos vidutinio gausumo monomorfonuklearų infiltracija.    4. Kairė krūties liauka. Krūties audinyje - 11 mm (mikroskopiškai) navikas, suformuotas lizdinių, trabekulinių, pavienių tubulinių (<10%) struktūrų. Naviko ląstelės vidutinio gausumo blyškia citoplazma, vidutinio kalibro ar stambiais, ryškiai polimorfiškais, ovaliais ir nereguliaraus kontūro, vesikuolizuotais branduoliais su grūdėtu chromatinu ir smulkiomis nukleolėmis. Mitozių navike iki 16/10DPRL. Šalia yra latakų su solidiniais proliferatais su komedo tipo nekroze, suformuotais navikui analogiškų ląstelių.   Aplinkinis krūties audinys su fibrozės apsuptomis, stambiomis lobulėmis su kompaktiškais smulkiais latakais, dalis užpildytais ryškiai eozinofilišku AB+>PAS+ skysčiu, išklotais epiteliu su vidutinio gausumo šviesia eozinofiliška citoplazma, vidutinio kalibro, apvaliais, monotoniškais branduoliais. Latakų epitelyje yra zonų su apikalinės sekrecijos požymiais. Yra vidutinio kalibro kanaliukų su intraduktaliniais solidiniais proliferatais iš ląstelių monomorfiškais branduoliais.. 3. Blokas 14 (dešinės krūties navikas):  Androgenų receptoriai: vidutinė (++) branduolinė reakcija 5% naviko ląstelių.  CK5: vidutinė /stipri (++/+++) membraninė reakcija 80% naviko ląstelių.  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose
answer:  0.

 97%|█████████▋| 642/661 [17:56<00:32,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 stulpeliai. 2 biopsiniai stulpeliai: I - 11 mm; II - 15 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%.. Krūties audinį infiltruoja pavienės smulkios duktalinės struktūros, smulkūs solidiniai kompleksai, juostos iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 5%.
answer:  1a

 97%|█████████▋| 643/661 [17:58<00:32,  1.79s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.(2a)Kraštas - extra - be naviko  2.(2b)Kraštas - extra - be naviko  3.(3)Sarginis l/m - extra - be naviko  4(N1)- pašalintas sektorius -planinis patologinis tyrimas - skubus rentgeninis tyrimas - navikas pašalintas. 4(1). Krūties sektorius 3,5x3,5x2 cm, be odos, žymėtas viela. Vielos projekcijoje pilkšvas, standus navikas 11x10x6 cm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm.. 1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė).   2(2b, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(1). Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 11 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).   Naviko nekrozė iki 15%.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atlikta šio tyrimo metu:   HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija ir sklerozuojanti adenozė).   Nuo sektoriaus rezekcijos krašto naviko struktūros nutolusios 0,6 mm.. 1(2a, ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu; fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu; degeneruojančių skaidulų židinys.   2(2b, ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   3(ekstra). "Sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.     4(1). NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos ryškiai polimorfiškų ląstelių, vidutinio gausumo eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais ryškiais polimorfiškais branduoliais su ryškiomis nukleolėmis; mitozių iki 18/10 DPRL. Centrinės nekrozės zonos iki 15%; fokalinė fibrozė su fibroblastų proliferacija. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija.   APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, fokaliai smulkūs suspausti, kloti dvisluoksniu epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: naviko struktūros nutolusios 0,6 mm.. 4(1). Navikas (9 blokas): EMA(+) citoplazminė r-ja; E-Cadherin(+++)(membr.r-ja)100%.  HER2: silpna (+) necirkuliari reakcija, 15% naviko ląstelių membranoje.
answer:  0

 97%|█████████▋| 644/661 [18:00<00:30,  1.81s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštas  - skubus tyrimas - be naviko  2(N2b). kraštas  - skubus tyrimas - be naviko  3(N3). kairės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko  4(N1). pašalintas kairės krūties kvadrantas planinis tyrimas. 4. Krūties sektorius 13,5x4x5,5 cm su odos lopu 9,5x3 cm, žymėtas viela. Pjūvyje, vielos projekcijoje - rusvas, elastingas, mucininis navikas 20x16x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 4 cm. Naviko projekcijoje fibrozė 3,5x1,5 cm plote susiūta chirurginiais siūlais.. 1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) mucininė karcinoma, TNM: pT1c(navikas 20 mm), pN0(sn)(0/3 l/n), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Ki67: proliferacinis indeksas 5%. Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  Krūties hamartoma (1,5 cm). Fibrocistiniai krūties pokyčiai: intraduktalinė krūties papiloma. Atipinė duktalinė hiperplazija (ADH).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).. Papildytas atsakymas (žr. molekuliniai tyrimai):    1(2a). Krūties audinyje minimali fibrozė ir smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2(2b). Krūties audinyje minimali fibrozė ir smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  3. Trys limfmazgiai su sinusų histiocitoze (3 l/m).  4. Krūties audinyje navikas (20 mm mikroskopiškai), suformuotas gausiuose ekstraląsteliniuose mucinuose besidėstančių smulkių lizdinių, pavienių tubulinių ir negausių mikropapilinių struktūrų. Naviko ląstelės vidutinio gausumo eozinofiline citoplazma, vidutinio kalibro, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Limfovaskulinis plitimas neidentifikuotas (LVI0). Mitozių navike iki 2/10 DPRL.   Krūties audinyje darinys, suformuotas mažos ląstelingos stromos su dilatuotais latakais, lobulėmis, pavieniais lipocitais. Krūties audinyje - dilatuotas latakas su fibrovaskulinėmis struktūromis, klotomis dvisluoksniu epiteliu monomorfiškais branduoliais. Keli dilatuoti kanaliukai su solidine proliferacija su kiek hiperchromiškais branduoliais su išlikusiu mioepiteliniu sluoksniu.. Blokas 21:  HER2: vidutinė (++) necirkuliari reakcija, 15%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 5% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių branduoliuose.
answer:  0

 98%|█████████▊| 645/661 [18:01<00:28,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Deš. krūtis su deš. pažasties l/m, planinis. Krūtis 1510 g svorio, 24x22x8,5 cm, su pažasties narveliena 13x8,5x3 cm.   Apatiniame lateraliniame kvadrante pilkšvas, standus, aiškių ribų navikas 30x22x20 mm (plintantis link spenelio, didžiausias naviko matmuo galimai 5,5 cm), esantis 2,6 cm nuo giliojo rezekcijos pjūvio, siekia odą.   Nuo naviko 1,8 cm atstumu pilkšvas, standus darinys 5x4x3 mm, giliojo rezekcijos krašto nutolęs 1,8 cm.   Spenelio projekcijoje krūties audinys balkšvas, standus, fibrozuotas 4,5x3 cm.   Pažasties narvelienoje rasta 11 limfmazgių, didžiausias 3,6 cm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma;  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: silpna (+) reakcija, 3% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    Vidutinio laipsnio intraduktalinė karcinoma (DCIS/DIN2 su plitimu operaciniame krašte).    pT2(30 mm ir 5 mm), pLVI-2, pN1a, pR0.. Krūties audinyje solidines, trabekulines, pavienes kribrozines naviko židinių struktūras formuoja ląstelės su negausia citoplazma, vidutinio dydžio vidutiniškai polimorfiškais branduoliais; mitozių navike iki 4 / 10 DPRL. Stebimas intrakapiliarinis plitimas.  Navike ir gretimai stebimos gausūs intraduktaliniai analogiškų ląstelių solidiniai ir tinkliniai proliferatai; židiniškai stebimi giliajame operaciniame pjūvyje.   Aprašyto naviko plitimas (iki 10 mm) 3-se iš 11 limfmazgių; stebimas ekstranodulinis plitimas.. Blokas 9:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono receptoriai: silpna (+
answer:  3%

 98%|█████████▊| 646/661 [18:04<00:28,  1.88s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas  2(N2b) - kraštas - skubus tyrimas  3(N3) - kairės pažasties sarginis limfmazgis - skubus tyrimas  4(N1) - pašalintas kairės krūties kvadrantas - planinis tyrimas  5(N4) - papildomi kraštai - planinis tyrimas. 4(1). Krūties sektorius 13,5x9,5x5 cm su oda 12x4 cm, žymėtas 2 vielomis. Vielų projekcijoje, pilkšvas, neaiškių ribų elastingas židinys 16x14x8 mm, pereinantis į netolygiai fibrozuotą krūties audinį, 5,5x2,5 cm plote. Pakitimai nuo giliojo rezekcijos krašto nutolę 0,1 cm, nuo odos -  2,5 cm.  5(4). Riebalinio audinio fragmentas 2x2x0,6 cm. Sudėta visa medžiaga.. 1(2a, ekstra). "Kraštai": krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai; ~15 mm skersmens židinys).  2(2b, ekstra). "Kraštai": krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai; ~12 mm skersmens židinys).  3(ekstra). "Kairės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(1). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b(m) (naviko židiniai: I - 5,2 mm; II - 0,4 mm; III - 0,35 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.     Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai; ~50 mm zona su išskiriančiu ~16 mm židiniu aplink didžiausiąjį I naviką).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   Incidentinė krūties fibroadenoma (4,35 mm).   DCIS komponentas sektoriaus rezekcijos krašte.    5(4). "Papildomi kraštai": fibrozuotas riebalinis audinys.. 1(2a, ekstra). "Kraštai": solidiniai, kribriforminiai intraduktaliniai žemiau, punkte Nr.3, aprašyto naviko ląstelių proliferatai su centrinėmis nekrozės zonomis (15 mm skersmens židinys).   2(2b, ekstra). "Kraštai": solidiniai, kribriforminiai intraduktaliniai žemiau, punkte Nr.3, aprašyto naviko ląstelių proliferatai su centrinėmis nekrozės zonomis (12 mm skersmens židinys).   3(ekstra). "Kairės pažasties sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.     4(1). NAVIKAS (daugybiniai, dalis nedideli mikroinvazyvūs naviko židiniai: I - 5,2 mm; II - 0,4 mm; III - 0,35 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai ar ryškiai polimorfiškų ląstelių, vidutinio gausumo ar gausia šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki 10/10 DPRL. Pavieniai spindžiai dalyje naviko struktūrų. Aplinkinė stroma fibrozuota su saikinga limfocitine infiltracija.   APLINKA: šalia naviko - gausūs dominuojantys solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis ir kalcifikatais. Gausi limfocitinė infiltracija su tretinių limfoidinių struktūrų formacija aplink in situ komponentą. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, apokrinės metaplazijos zonomis. Incidentinis ribotas skiltėtas navikas (4,35 mm), suformuotas edemiškos stromos su suspaustais ar minimaliai dilatuotais šakotais ir negausiais smulkiais latakais, klotais dvisluoksniu, kiek hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: fokalinis in situ komponento plitimas rezekcijos krašte.   5(4). "Papildomi kraštai": fokaliai fibrozuotas brandžių lipocitų suformuotas audinys.. 1(2a, ekstra). "Kraštai"(1 blokas):  CK14/CK5(+) mioepitelinis sl. DCIS komponente.   2(2b, ekstra). "Kraštai"(4 blokas):   CK14/CK5(+) mioepitelinis sl. DCIS komponente.   4(1). "Židinys-fibrozė" (4,22-24,28-29 blokai):   CK14(+) mioepitelinis sl. DCIS k
answer:  4,

 98%|█████████▊| 647/661 [18:05<00:25,  1.83s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - pjūvio kraštai - extra  2 - pjūvio kraštai - extra  3 - sarginis l/m - extra  4. sektorius, planinis.. 4. Krūties sektorius 6x5,3x5 cm su oda 5,5x3,5x cm. Krūties audinyje, pilkšvas, standus, aiškių ribų navikas 16x15x13 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 1 cm.. 1. Pjūvio kraštai. Krūties audinys su židinine lėtine uždegimine infiltracija. Naviko plitimo nėra.     2. Pjūvio kraštai. Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.      3. Sarginis l/m. Reaktyvi limfadenopatija (3 l/m).     4. Sektorius. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma,    suminis TNM: pT1c (16 mm navikas)   pN0(sn)(3 l/m)    pLVI-0(limfovaskulinė invazija neidentifikuota).   pR0(radikalus pašalinimas).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 85% naviko ląstelių.  HER2: reakcija neigiama (0/1+).  Ki67: proliferacinis indeksas 30%.. 1(ekstra). Pjūvio kraštai. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Stromoje židininė gausoka periduktalinė limfocitinė infiltracija. Naviko plitimo nėra.   2(ekstra). Pjūvio kraštai. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   3(ekstra). Sarginis l/m. 3 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.    4. Sektorius. Krūties audinyje - navikas, suformuotas lizdų, trabekulių ir grandinėlių. Naviko ląstelės su vidutinio gausumo, šviesiai amfofiliška citoplazma, vidutinio kalibro ar stambiais, apvaliais ar ovoidiškais, vesikuolizuotais, ryškiai polimorfiškais branduoliais su ryškiomis nukleolėmis. Mitozių navike iki 21/10DPRL.. Blokas 19:  CD31: + endotelis (limfovaskulinė invazija neideintifikuota).   E-Cadherin: stipri (+++) reakcija, 100% naviko membranose.   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakc
answer:  10%

 98%|█████████▊| 648/661 [18:07<00:22,  1.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 7 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 12% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.. Krūties audinį infiltruoja negausios duktalinės struktūros, smulkūs kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 12% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 15%.
answer:  1b

 98%|█████████▊| 649/661 [18:08<00:20,  1.67s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 stulpelis. Biopsinis stulpelis 15 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G2; 7 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (galutinai interpretuota įvertinus HER2 IHC rezultatą; žr. molekulinio tyrimo aprašymą ir pastabą).  Ki67: proliferacinis indeksas 40%.. Krūties audinį 1-me bioptate infiltruoja iki 9 mm :   - trabekulės;  - epitelinių stambių ląstelių su ryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 3/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) necirkuliari reakcija, 50%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 40% naviko ląstelių.  Progesterono receptoriai: stipri
answer:  1b

 98%|█████████▊| 650/661 [18:10<00:18,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: PREPARATAI   -   UAB PATOLOGIJOS DIAGNOSTIKA. Konsultacijai gauta:  - 4 parafino blokai (žymėti "B22-1-28082");  - 8 histologiniai preparatai (žymėti ""B22-1-28082"", dažyti HE, CK5, ER, PR, HER2 metodais).. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se stulpeliuose.  Ki67: proliferacinis indeksas 55%.  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Išoriniai IHC:  Estrogenų receptorių raišką teigiama (stipri raiška 100 proc. naviko ląstelių branduoliuose).  Progesteronų receptorių raišką teigiama (vidutinė raiška 50 proc. naviko ląstelių branduoliuose).  HER2 raiška paribinė (2+: silpna cirkuliari raiška 30 proc. naviko ląstelių membranoje).  CK5: raiškos nestebima.. Fibrozinį audinį 3-se/4 bioptatuose infiltruoja iki 9 mm :   - solidiniai kompleksai ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje kiek vakuolizuotoje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Ki67: reakcija branduoliuose, 55% naviko ląstelių.
answer:  1b

 98%|█████████▊| 651/661 [18:12<00:17,  1.72s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pjūvio kraštai - extra;  2. Pjūvio kraštai - extra;   3. Sarginiai l/m - extra.   4. sektorius, planinis.. 4. Krūties sektorius 8,5x4,5x6 cm su oda 7,5x3 cm, žymėtas viela. Vielos projekcijoje, kvadrante - pilkšvas, standus neaiškių ribų navikas 10x10x8 mm (sudėtas visas), pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,7 cm. Paruošti pjūviai Prosigna.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (1 l/m).    4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(10,5 mm navikas) pN0(sn)(0/1 l/m) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir solidinis tipai). Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija.    Imunofenotipas:(biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 1 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (10,5 mm) infiltratyviu augimo frontu, trabekulinėmis struktūromis, lizdais ir grandinėlėmis ir pabirai besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, vidutiniais polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 10/10 DPRL. Limfovaskulinė invazija.  Greta dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu Fokaliai smulkių suspaustų kanaliukų zonos.. Navikas(13 blokas):  HER2: nusidažiusių naviko ląstelių nėra.  E-cadherin membr. trūkinėjanti r-ja 90%.
answer:  1b

 99%|█████████▊| 652/661 [18:13<00:14,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm ilgio.. Gerai diferencijuota (G, balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 6
answer:  1b

 99%|█████████▉| 653/661 [18:15<00:13,  1.64s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra;  2(2b). Kraštai - extra;  3. Sarginiai l/m - extra;  4(1). N41 - sektorius - planinis patologinis tyrimas.. 4. Krūties sektorius 8x5x2,5 cm, žymėtas dažais. Krūties audinyje, kvadrante - pilkšvas, standus navikas 22x16x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm.. 1(2a) Kraštai. Krūties audinys, naviko plitimo nėra.    2(2b) Kraštai. Krūties audinys, naviko plitimo nėra.     3 Sarginiai l/m. Reaktyvi limfadenopatija (2 l/m).     4(1) Sektorius.   Krūties invazyvi vidutiniškai diferencijuota (G2, 7 b. pgl Nottingham) duktalinė karcinoma,   pT2(22 mm)   pN(sn)0(0/2 l/m)   pLVI-0 (limfovaskulinės invazijos nestebima)  Naviko imunotipas nustatytas biopsijoje (žr.pastabą).  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 kribriforminis tipas).. 1(2a) Kraštai. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.    2(2b) Kraštai. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.    3 Sarginiai l/m. Limfmazgiai su sinusų histiocitoze, lipomatoze.      4(1) sektorius. Krūties audinyje infiltratyviai plintantis navikas, suformuotas trabekulinių, netaisyklingų kribriforminių bei solidinių struktūrų. Naviko ląstelės su vidutinio gausumo, eozinofiliška citoplazma, netaisyklingais, ryškiai polimorfiškais branduoliais. Mirozių navike iki 7/10 DPRL. Nekrozės zonos navike iki 5%. Naviko plitimo kraujagyslėse nestebima. Šalia naviko kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių. Fokaliai naviko struktūros plinta žymėtame rezekcijos krašte.. nan
answer:  1(

 99%|█████████▉| 654/661 [18:16<00:11,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 3 mm; III - 6 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros, smulkūs solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  Ki67+
answer:  8%

 99%|█████████▉| 655/661 [18:18<00:10,  1.69s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2 - retroareoliarinė sritis - DCIS    2. N3 - viena makromts iš 2 pašalintų sarginių l/m    3. N4 papildomai keliuose kanaliukuose -DCIS  4.  N5- papildomai - dalis areolės su oda ir poodžiu - be naviko   5.  N1 - pašalinta krūtis - planinis patologinis tyrimas. 5. Krūtis 13,5x11,5x3 cm, su odos lopu 7,5x2,5 cm.   Krūties audinyje, pjūvyje pilkšvas, ribotas 15x12x10 mm navikas, nuo giliojo rezekcijos krašto nutolęs 1,2 cm, nuo poodinio rezekcijos krašto - 0,1 cm. Krūties audinys fibrozuotas 8,5x4,5 cm plote.. 1. N2 - retroareoliarinė sritis: Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, tinklinis tipas) / (DIN3).    2. N3 -  sarginiai limfmazgiai: viename iš 3 limfmazgių karcinomos plitimo daugybiniai židiniai iki 3 mm; pN(sn)1a.      3. N4 papildomai keliuose kanaliukuose: Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, tinklinis tipas) / (DIN3).    4. N5- papildomai - dalis areolės su oda ir poodžiu: be patologinių pokyčių.     5. N1 - pašalinta dešinė krūtis.  Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mikropapilinė karcinoma;  pT(m)1c(15 mm, 8 mm) pR0.   Imunofenotipas (nustatytas priešoperaciniame naviko biopsijos tyrime):   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: teigiama (3+).  Ki67 proliferacinis aktyvumas 10%.    Krūties daugybiniai aukšto laipsnio duktalinės karcinomos in situ (DCIS, tinklinis tipas) / (DIN3) židiniai.  Krūties fibrocistiniai pokyčiai:  sklerozuojanti adenozė.. 1. N2 - retroareoliarinė sritis: Krūties audinyje 3 mm židinyje - vidutinio kalibro kanaliukai su tinkliniais intraduktaliniais ląstelių su eozinofiliška citoplazma, vidutinio kalibro ir stambiais, polimorfiškais branduoliais proliferatais kanaliukų spindžiuose.    2. N3 - sarginiai limfmazgiai: viename iš 3 limfmazgių karcinomos plitimo daugybiniai židiniai iki 3 mm.   3. N4 papildomai keliuose kanaliukuose: Krūties audinyje 2 mm židinyje - vidutinio kalibro kanaliukai su tinkliniais intraduktaliniais ląstelių su eozinofiliška citoplazma, vidutinio kalibro ir stambiais, polimorfiškais branduoliais proliferatais kanaliukų spindžiuose.  4. N5- papildomai - dalis areolės su oda ir poodžiu: be patologinių pokyčių.   5. N1 - pašalinta dešinė krūtis. Naviko fibrozinėje stromoje infiltratyvios naviko struktūros, suformuotos mikropapilomis ir lizdais besidėstančių ląstelių gausia ryškia eozinofiliška citoplazma, polimorfiškais, vidutinio-stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 8/10 DPRL.  Fibrozuotame krūties audinyje:  vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, smulkių kanaliukų proliferacijos zonos, apokrininė metaplazija; stebimi vidutinio kalibro kanaliukai su tinkliniais intraduktaliniais ląstelių su eozinofiliška citoplazma, vidutinio kalibro ir stambiais, polimorfiškais branduoliais proliferatais kanaliukų spindžiuose ir 8 mm invazinio aukščiau aprašyto naviko židinys.. nan
answer:  1.

 99%|█████████▉| 656/661 [18:20<00:08,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Kairės pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: Kairė krūtis, planinis. 2. Krūtis 352 gramų svorio, 15x13,5x4,2 cm. Krūties audinyje, viršutinių kvadrantų riboje - pilkšvas, standus, neaiškių ribų I navikas 11x6x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 2,3 cm. Apatinių kvadrantų riboje - pilkšvas, elastingas I darinys 7x6x6 cm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 1,5 cm, nuo odos - 1 cm. Viršutiniame medialiniame kvadrante pilkšvas elastingas aiškių ribų II darinys 6x5x5 cm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 1 cm. 1 cm atstumu nuo II darinio, link šoninio giliojo rezekcijos krašto - pilkšvas, standus II navikas 10x6x5 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 1,4 cm. Spenelio projekcijoje krūties audinys fibrozuotas 7x3,5 cm plote.. 1(ekstra). Reaktyvi limfadenopatija (2 l/m).  2. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(m)(11 mm ir 9 mm navikai) pN0(sn)(0/2 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).   Žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1, kribriforminis ir papilinis tipai). Lobulinė karcinoma in situ (LCIS). Fibroadenoma (6 mm).  Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 10% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 3%.. 1(ekstra). 2 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  2. Spenelis: normali histologinė struktūra.  Krūtyje - navikas (11 mm ir 9 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, trabekulinėmis struktūromis, lizdais ir pabirai besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, smulkiais - vidutiniais, vidutiniškai polimorfiškais,  ovaliais apvaliais, vezikulizuotais branduoliais ryškiomis nukleolėmis; mitozių 2/10 DPRL.  Navikas (9 mm židinys) nuo rezekcijos krašto nutolęs 1,5 mm.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių. Latakai ir lobulės su monomorfiškų ląstelių proliferacija. Mazgas suformuotas proliferuojančių fibroblastų stromos ir suspaustų latakų, klotų dvisluoksniu epiteliu.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaus kanaliukų zonos.. nan
answer:  0.

 99%|█████████▉| 657/661 [18:22<00:07,  1.84s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 pjūvio kraštai, ekstra.   2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.  4. papildomas kraštas. ekstra.  5. sektorius, planinis.. Krūties sektorius 10x6x4,5 cm, su odos lopu 7x2,5 cm. Pjūvyje balkšvas, standus, neaiškių ribų navikas 31x22x11 mm, nuo artimiausio rezekcijos krašto nutolęs 0,7 cm, nuo odos 1,3 cm. Šalia naviko fibrozės zona 4x3x2 cm.. 1(intraoperative margin). Invasive lobular carcinoma.  2.(intraoperative margin). Invasive lobular carcinoma (1.3 mm focus).  3.(intraoperative) lymph node. Breast lobular carcinoma metastasis in a lymph node (1/4 l/n, MTS 3.2 mm).  4.(intraoperative margin). Invasive lobular carcinoma (2 mm focus in marked margin).    5. Breast invasive moderately differentiated (G2, 7b. Nottingham syst.) lobular carcinoma. TNM: pT2(m)(31 mm, 1.3 mm tumors) pN1a(sn)(1/4 l/n, MTs 3.2 mm) LVI-2 (lymphovascular invasion). R1 (carcinoma reaches the edge of the sector, spreads in additional edges No. 1, 2, 4). Lobular carcinoma in situ (LCIS).    Immunophenotype:  Estrogen receptors: strong reaction in 95% of tumor cells.  Progesterone receptors: strong reaction in 100% of tumor cells.  Her2 immunoreaction: negative (0).  Ki67 proliferative activity 5%.        LT  1(ekstra). Invazyvi lobulinė karcinoma.  2(ekstra). Invazyvi lobulinė karcinoma (1,3 mm židinys).  3(ekstra). Krūties lobulinės karcinomos metastazė limfmazgyje (1/4 l/m, MTS 3,2 mm).  4. Papildomas kraštas. Invazyvi lobulinė karcinoma (2 mm židinys žymėtame krašte).    5. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(m)(31 mm, 1,3 mm navikai) pN1a(sn)(1/4 l/m, MTs 3,2 mm) LVI-2(limfovaskulinė invazija). R1(karcinoma siekia sektoriaus kraštą, plinta papildomuose Nr.1,2,4 kraštuose). Lobulinė karcinoma in situ (LCIS).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 95% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.. 1(intraoperative margin). Breast tissue with areas of fibrosis and sparse ducts lined with double-layered epithelium; invasive tumor cells around ducts.  2 (intraoperative margin). Breast tissue with single tubules lined by double-layered epithelium; the focus of the described tumor is 1.3 mm.  3 (intraoperative l/n). Metastasis of the described tumor in 1 of 4 lymph nodes 3.2 mm.  4(intraoperative margin). The focus of the invasive tumor up to 1.3 mm; dilated ducts and lobules with intraductal solid proliferates of cells analogous to the tumor.  5. In the breast - a tumor (32, 1.3 mm foci) with an infiltrative growth front with trabecular structures, chains and discohesive cells with moderately abundant eosinophilic cytoplasm, large, polymorphous, irregularly contoured nuclei with bright nucleoli; mitoses 7/10 HPF. Tumor in coagulated edge.  Adjacent dilated tubules with intraductal solid proliferates from tumor-analogous cells (LCIS).      LT    1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu; aplink latakus pabirai besidėstančio aprašyto Nr. 5 naviko ląstelės.  2(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu; aprašyto naviko židinys 1,3 mm.  3(ekstra). 1 iš 4 limfmazgių aprašyto naviko metastazė 3,2 mm.  4(extra). Papildomas kraštas. Krūties audinyje aprašyto naviko židinys 1,3 mm, dilatuoti latakai ir lobulės su intraduktaliniais solidiniais proliferatais iš analogiškų navikui ląstelių.  5. Krūtyje - navikas (32, 1,3 mm židiniai) infiltratyviu augimo frontu trabekulinėmis struktūromis, grandinėlėmis ir pabirai besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 7/10 DPRL. Navikas koaguliuotame krašte.  Greta dilatuoti kanaliukai su intraduktaliniais solidiniais proliferatais iš analogiškų navikui ląstelių.. Tumor:  Estrogen receptors: (+++)(nuclear reaction) 95%.  Progesterone receptors: (+++)(nuclear reaction) 100%.  HER2: weak staining of single cell membranes.  Ki67 proliferative activity 5%.  E-cadherin single cell with fint staining in the membrane ; p1
answer:  0.

100%|█████████▉| 658/661 [18:24<00:05,  1.78s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 12 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma su mucininės diferenciacijos požymiais   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.  Progesterono receptoriai: stipri (+++) reakcija, 1% naviko ląstelių.. Krūties audinyje (2/2 biopsiniuose stulpeliuose) - fibrozinės stromos su gausiais AB+ mucinų židiniais apsuptos kribriforminės struktūros ir solidiniai kompleksai, suformuoti ląstelių vidutinio gausumo, tamsia eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar ovoidiškais, hiperchromiškais, vidutiniškai polimorfiškais branduoliais su pavienėmis smulkiomis nukleolėmis. Mitozių navike iki 6/10DPRL.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 15% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 1% naviko
answer:  1b

100%|█████████▉| 659/661 [18:25<00:03,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 7 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+, HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.. Krūties audinį infiltruoja netaisyklingi šakoti kribroziniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 12% naviko ląstelių.  Ki67+ 12
answer:  3b

100%|█████████▉| 660/661 [18:27<00:01,  1.66s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~42x39 mm dydžio navikas dešiniojoje krūtyje ties 10-11 val.  vidurinėje-periferinėje dalyse, paimti trys biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 12 mm; II - 13 mm; III - 8 mm.. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: teigiama (3+).  Ki67 proliferacinis aktyvumas 60%.. Bioptatuose (3/3) - krūties audinyje, desmoplastiškoje stromoje, infiltratyvios naviko struktūros, suformuotos trabekulėmis ir lizdais bei solidiniais plotais besidėstančių ląstelių vidutinio gausmo ryškai eozinofiliška citoplazma, polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais eozinofiliškomis nukleolėmis; mitozių 9/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 950%.  HER2: stiprus visos membranos nusidažymas 100% naviko ląstelių.  Ki67 proliferacinis aktyvumas 60%.
answer:  3

100%|██████████| 661/661 [18:28<00:00,  1.68s/it]

input:  1 ėminio aprašas: 1 but. 1 biopsinis stulpelis i š dešinės pažasties l lygio l/m.   2 but. 1 biopsinis stulpelis iš dešinės krūties BI-RADS 5  darinio. 1. Biopsinis stulpelis 7 mm ilgio.  2. Biopsinis stulpelis 14 mm ilgio.. 1. Duktalinės karcinomos metastazė limfmazgyje.   2. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67+ 10%.. 1. Limfmazgio bioptate plinta žemiau aprašyto naviko struktūros.  2. Krūties audinį infiltruoja duktalinės struktūros (20%), netaisyklingi kribroziniai kompleksai ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Blokas 2:  Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių branduoliuose.  Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 3%  naviko ląstelių membranoje.  Ki
answer:  1.

In [ ]:
evaluateWeighted(n_labels, n_pred)

Accuracy: 0.1346444780635401
Precision: 0.49804124532207983
Recall: 0.1346444780635401
F1 Score: 0.20127659802711884

## Metastasis (M)

Kadangi binary klasifikacija, išfiltruojami rezultatai, kurie nėra 0 arba 1. Kažkodėl neretai generuoja random skaičius kaip 5, 20, 100. Modelis nežino kas yra tolimoji metastazė, todėl įdėta sąvoka užklausoje

In [ ]:
def generate_prompt_M(data_point):
    return f"""
            **Sąvoka**
            Tolimoji metastazė - vėžio plitimas į kitus organus ar audinius, esančius toliau nuo pirminio naviko vietos.

            **Tolimosios metastazės klasifikacijos ir paaiškinimai**:
            0 – tolimųjų metastazių nėra;
            1 – yra tolimųjų metastazių;

            **Pavyzdžiai:**
            - Įvestis: 1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 13 mm; II - 13 mm. Invazinė lobulinė karcinoma (mažiausiai iki 11 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: silpna (+) reakcija, 5% naviko ląstelių.  HER2: reakcija paribinė (2+). Dėl blogos mėginio kokybės ir nepakankamo ląstelių kiekio mėginyje, HER2 amplifikacijos FISH tyrimas nevertintinas.  Ki67: proliferacinis indeksas 15%.Krūties audinį 2-se bioptatuose infiltruoja iki 11 mm : - juostos; - epitelinių smulkių / vidutinio dydžio ląstelių su neryškiai/ vidutiniškai polimorfiškais branduoliais negausioje eozinofilinėje citoplazmoje; - su mitozės nestebimos. Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra. Blokas 1: E-Cadherin: silpna teigiama (+) membraninė reakcija 10proc. atipinėse ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra. HER2: vidutinė (++) necirkuliari reakcija, 30%  naviko ląstelių membranoje. Ki67: reakcija.
            - Rezultatas: 0

            - Įvestis: 1 ėminio aprašas: Paimti 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 14 mm; II - 14 mm; III - 10 mm. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių. Her2 imuninė reakcija: neigiama 0+. Ki67+ 8%, fokaliai iki 20%. Krūties audinį infiltruoja smulkūs kribroziniai/solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių. Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių. K.
            - Rezultatas: 0

            - Įvestis: 1 ėminio aprašas: N1: pašalintas kairės krūties kraujuojantis peraugantis spenelį navikas. Krūties sektorius 11,5x8x5,5 cm. Krūties audinyje balkšvas, standus, neaiškių ribų navikas 3,3x1,8x3,3 cm, esantis 0,5 nuo artimiausio/giliojo rezekcijos pjūvio, siekia ir perauga odą, nuo odos rezekcijos krašto nutolęs 2 cm. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b (33mm, išopėjimas). Krūties audinyje išopėjęs 33mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL. Operacinis pjūvis be naviko.
            - Rezultatas: 1

            - Įvestis: 1 but. 1 biopsinis stulpelis iš kairės pažasties l/m 2 but. 1 biopsinis stulpelis iš dešinės krūties darinio. 1. Biopsinis stulpelis 11 mm ilgio. 2. Biopsinis stulpelis 7 mm ilgio. N1: Limfmazgio bioptatas su duktalinės karcinomos metastaze.  N2: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių. Her2 imuninė reakcija: neigiama 1+. Ki67+ 10%. N1: Limfmazgio bioptatas su žemiau aprašyto naviko židiniais.  N2: Krūties audinį infiltruoja nedideli solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL. Navikas Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių. Ki67+ 10.
            - Rezultatas: 1

            **Užduotis:**
            Išanalizuokite šį tekstą ir padarykite tolimosios metastazės klasifikaciją tik pagal dvi duotas žymes. Rezultatas gali būti 0 arba 1.

            [{data_point["input"]}] = """

In [ ]:
m_labels = train["Metastasis (M)"].astype(int).tolist()

testM = test
trainM = train
valM = val

X_test = pd.DataFrame(testM.apply(generate_prompt_M, axis=1), columns=["input"])
X_train = pd.DataFrame(trainM.apply(generate_prompt_M, axis=1), columns=["input"])
X_val = pd.DataFrame(valM.apply(generate_prompt_M, axis=1), columns=["input"])

In [ ]:
from tqdm import tqdm
from transformers import pipeline

def predictM(model, tokenizer):
    m_pred = []
    pipe = pipeline(task="text-generation",
                model=model,
                tokenizer=tokenizer,
                max_new_tokens = 1,
                do_sample=False
                )

    for i in tqdm(range(len(X_train))):
        prompt = X_train.iloc[i]["input"]
        result = pipe(prompt)
        answer = result[0]['generated_text'].split("=")[-1].strip()
        print("input: ", trainM.iloc[i]["input"])
        print("answer: ", answer)
        if answer.strip() == "1":
            m_pred.append(1)
        elif answer.strip() == "0":
             m_pred.append(0)
        else:
            m_pred.append(-1)

    return m_pred

In [ ]:
m_pred = predictM(model, tokenizer)

Device set to use cuda:0
  0%|          | 0/661 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 1/661 [00:01<12:58,  1.18s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 - viršutinis kraštas- extra  2 - apatinis kraštas -extra  3 - sarginiai l/m - extra  4 - kvadrantas - planiniam tyrimui. 4. Krūties sektorius 6,5x6,5x2 cm su odos lopu 5x1,5 cm, žymėtas viela ir siūlais: 2 trumpi siūlai sektoriaus krašte (žalia spalva), kita pusė - be žymėjimo (juoda spalva). Vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 15x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,5 cm.. 1(3)(Extra). Reaktyvi limfadenopatija (1 l/m).  2(1)(Extra). Krūties audinys.  3(2)(Extra). Krūties audinys. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT(m)1c(2 naviko židiniai: 12 mm ir 1,7 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Krūties žemo laipsnio duktalinė karcinoma in situ (DIN1c/DCIS)(kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. 1(3)(Extra). 1 limfmazgis su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze.  2(1)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  3(2)Extra). Krūties audinyje, fibrozuotoje stromoje - negausūs vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu. 1 limfmazgis su fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze.  4. Krūties audinyje - 2 naviko židiniai (mikroskopiškai 12 mm ir 1,7 mm), suformuoti fibrozuotoje stromoje infiltratyviai grandinėlėmis, smulkiomis grupelėmis ar pabirai plintančių ląstelių saikinga švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, apvaliais/ovaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 1/10 DPRL. Šalia yra kanaliukų, užpildytų analogiškomis navikui ląstelėmis (LCIS) bei dilatuotų kanaliukų su kribriforminiais intraduktaliniais neryškiai polimorfiškų ląstelių proliferatais (DCIS), negausūs kanaliukai su epitelio hiperplazija ar su stulpiniu ląstelių pokyčiu su apikalinės sekrecijos požymiais (CCAPSS); pavieniai smulkūs kalcifikatai, makrofagų židiniai, smulkios hemoragijos ir židininė MMN infiltracija.. 1. Navikas (15 blokas):  E-Cadherin(-).  Navikas (16 blokas):   E-Cadherin(-).  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.
answer:  0

  0%|          | 2/661 [00:02<11:12,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu  3(2). Kairės pažasties sarginiai limfmazgiai, skubu  4(3). Kairės krūties sektorius, planinis. 4. Krūties sektorius 6x2,7x5 cm su oda 3,5x1,6 cm, žymėtas viela. Krūties audinyje, kvadrante - pilkšvas, standus, neaiškių ribų navikas 12x8x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2 cm.. 1(1a). Fibrocistiniai krūties pokyčiai.  2(1b). Krūties audinys.  3(2). Reaktyvi limfadenopatija (2 l/m).  4(3). Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, TNM: pT1b(navikas 8,5 mm), pN0sn)(0/2 l/m), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).. 1(1a). Krūties audinyje gausūs dilatuoti latakai, kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.   2(1b). Krūties audinyje židininė fibrozė ir smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  3(2). Du limfmazgiai su sinusų histiocitoze ir šerdies lipomatoze.  4(3). Krūties audinyje - navikas (8,5 mm mikroskopiškai), suformuotas tubulinių struktūrų iš vidutinio kalibro eozinofiline citoplazma ląstelių, nežymiai polimorfiškais, smulkiai grūdėtu chromatinu branduoliais; mitozių 4/10 DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Krūties audinyje greta naviko negausūs dilatuoti latakai, kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.. Blokas 16:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

  0%|          | 3/661 [00:03<10:57,  1.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)- kraštas - (extra)- be naviko   2(N2b)- kraštas - (extra)- be naviko   3(N3) -  sarginis l/m (extra)-  be naviko   4(1)- pašalintas sektorius( planinis tyrimas) Skubus Ro- -navikas pašalintas. Krūties sektorius 10x6x5 cm su oda 10x5,5 cm, žymėtas dviejomis vielomis, viena iš jų kiaurai perveria sektorių. Tarp vielų - balkšvas, standus, neaiškių ribų, netaisyklingos formos navikas 35x30x35 mm, nuo sektoriaus rezekcijos krašto (mėlyna spalva) nutolęs 0,1 cm, nuo odos - 2 cm.. 1. Riebalinis audinys.  2. Krūties audinys.  3. Reaktyvi limfadenopatija (1 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) lobulinė karcinoma, TNM: pT2(40 mm naviko židinys), LVI0(neidentifikuota), pN0(sn)(0/1 l/m). Krūties lobulinė karcinoma in situ (LCIS). HER2:reakcijos nėra (0). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.. 1. Riebalinis audinys su fibrozinėmis septomis.  2. Krūties audinys us pavieniais smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Vienas limfmazgis su sinusų histiocitoze.  4. Krūties audinyje - navikas (40 mm mikroskopiškai), suformuotas trabekulinių/juostinių struktūrų iš vidutinio kalibro eozinofiline citoplazma ląstelių, vidutiniškai polimorfiškais branduoliais su pavieniais paryškėjusiais branduolėliais; mitozių 2/10 DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Navikas nuo artimiausio krūties sektoriaus rezekcijos krašto nutolęs per 1 mm. Greta naviko gausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Aplinkiniame fibrozuotame krūties audinyje gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar metaplastišku apokrininiu epiteliu.. Blokas 7:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

  1%|          | 4/661 [00:04<11:12,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 1a- viršutinis kraštas - extra;  2. 1b- apatinis kraštas - extra.  3(2). sarginiai limfmazgiai - extra;  4(3). Deš. krūties sektorius - planinis.. 4. Krūties sektorius 6,5x5x3,8 cm, su odos lopu 6,5x4 cm ir skersaruožio raumens fragmentu 2x1,5x0,4 cm. Krūties audinyje balkšvas, standus neaiškių ribų infiltratyviai plintantis navikas 2,7x1,8x2,7 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, įtraukia odą, siekia skersaruožius raumenis. Rezekcijos kraštas dažytas mėlynu tušu.. 1(Extra). Krūties audinys.  2(Extra). Riebalinis audinys.  3(Extra). Duktalinės karcinomos metastazės 2/4 limfmazgiuose (9 mm ir 1,8 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(22 mm) N(sn)1a(mts 2/4 l/m: 9 mm ir 1,8 mm), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).. 1(Extra). Krūties audinyje, neryškiai fibrozuotoje stromoje - negausūs smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 2 iš 4 limfmazgių - žemiau aprašyto naviko metastazės (9 mm ir 1,8 mm).  4. Krūties audinyje, dermoje ir fokaliai tarp skersaruožių miocitų - navikas (mikroskopiškai 22 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių lizdinių, trabekulinių ir negausių (<10%) smulkių tubulinių struktūrų bei fokaliai grandinėlėmis ar pabirai besidėstančių ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, ovaliais, neryškiai polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 7/10 DPRL. Limfovaskulinė smulkių šakų ir perineurinė invazija.. 1. Navikas (24 blokas):  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  E-Cadherin(+++)(membr. r-ja), 100%
answer:  100

  1%|          | 5/661 [00:05<11:59,  1.10s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 10 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi nedideli šakoti kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 10%.
answer:  0

  1%|          | 6/661 [00:06<11:52,  1.09s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 16 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 10%.. Bioptate - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio-stambaus kalibro, nereguliaraus kontūro branduoliais eozinofiliškomis nukleolėmis; mitozių 0/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67 proliferacinis aktyvumas 10%.
answer:  0

  1%|          | 7/661 [00:07<11:50,  1.09s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštas - extra - be naviko  2(N2b). kraštas - extra - be naviko  3(N1). pašalintas sektorius - planinis tyrimas.. 3. Krūties sektorius 13,5x6,5x5,5 cm su oda 12,5x6 cm. Krūties audinyje, pilkšvas, standus navikas 2,2x16x16 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 1,3 cm, nuo odos - 2 cm. 1(ekstra). Krūties audinys. Naviko plitimo nėra.   2(ekstra). Krūties audinys. Naviko plitimo nėra.   3. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) mišri duktalinė - mikropapilinė karcinoma. SUMINIS TNM: pT2 (22 mm navikas) NX(l/m nešalinti) LVI-2 (limfovaskulinė invazija smulkiose gyslose). Radikalus pašalinimas (R0).    Naviko imunotipas biopsijoje:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. 1(N2a, ekstra). Krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   2(N2b, ekstra). Krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   3(N1).  Krūties audinyje - infiltratyviu frontu plintantis, 22 mm dydžio (mikroskopiškai) navikas, suformuotas mikropapilinių struktūrų(50%), tubulių (<10%), kribriforminių struktūrų, trabekulių ir lizdų. Naviko ląstelės su gausoka, ryškia eozinofiliška citoplazma, vidutinio kalibro ar stambiais, ovoidiškais, vidutiniškai ar fokaliai ryškiai polimorfiškais branduoliais su blyškiu chromatinu ir makronukleolėmis. Mitozių navike iki 8/10DPRL. Naviko centre stambi hipoląstelinga kolagenizuotos fibrozės zona.  Naviko plitimas endotelizuotuose spindžiuose.. Blokas 11:  EMA: silpna/vidutinė (+/++) membraninė reakcija naviko mikropapilinių struktūrų išorėje.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.
answer:  1

  1%|          | 8/661 [00:08<11:07,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1. Sektoriaus kraštai. N2. Sektoriaus kraštai. N3. Deš.krūties sektorius . 4.  pažasties limfmazgiai.. 3. Krūties sektorius 15,5x6x4,5 cm su odos lopu 15x2,5 cm. Pjūvyje balkšvas, standus, gan aiškių ribų navikas 2,1x1,9x1,1 cm, nuo odos nutolęs 1,5 cm, nuo artimiausio rezekcijos krašto - 2cm.  4. Riebalinio audinio fragmentai, bendras dysis 11x7,5x2 cm. Rasta 14 limfmazgių iki 1,4 cm.. 1. Riebalinis (krūties) audinys.  2. Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT2(2,1 cm) pN1a(1/14 l/m, mts 0,25 cm). LVI0(limfovaskulinės invazijos nėra).  4. Duktalinės adenokarcinomos metastazė 1/14 l/m.    Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2 imuninė reakcija neigiama (1+).  Ki67: 8%.. 1. Brandūs lipocitai, negausus fibrozinis audinys.  2. Krūties audinyje - negausūs smulkūs fibrozės židiniai su smulkiais kanaliukais, išklotais dvisluoksniu epiteliu.  3. Krūties audinyje - navikas: Solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 5 / 10 DPRL.   4. Aukščiau aprašyto naviko metastazė 1/14 limfmazgyje (0,25 cm).. nan
answer:  0

  1%|▏         | 9/661 [00:09<11:17,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1-2. pjūvio kraštai, ekstra. 3. sektorius, planinis. 4. pažasties l/m, planinis. 3. Krūties sektorius 9x8x2,5 cm su odos lopu 6x3,8 cm. Pjūvyje - balkšvas, standus, neaiškių ribų navikas 3x2x1,8 cm, nuo artimiausio rezekcijos krašto (mėlyna) nutolęs 0,1 cm, nuo odos – 1,5 cm. Navikas sudėtas visas, serijiniais pjūviais.  4. Riebalinio audinio fragmentai, bendras dydis 7,5x5x3,5 cm. Rastas 21 limfmazgiai iki 3 cm. Viename (II) limfmazgyje visą parenchimą apima balkšvas židinys 2,5 cm.. 1(ekstra). Kraštai. Krūties audinys be patologinių pokyčių.    2(ekstra). Kraštai. Krūties audinys be patologinių pokyčių.    3. Kairės krūties sektorius.   Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham sistemą) duktalinė karcinoma,   suminis TNM: pT2(30 mm makroskopiškai) pN1a (2/21 l/m su mts iki 25mm) pLVI-0.   Naviko struktūros siekia sektoriaus rezekcijos kraštą, žr. pastabą.  Naviko imunofenotipas (priešoperacinės biopsijos tyrime):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.   Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.   Her2 imuninė reakcija: neigiama 0.   Ki67+ 10%.  Her2 karcinomos metastazės limfmazgyje: HER2:reakcijos nėra (0).    4. Pažasties l/m. Krūties duktalinės karcinomos (iki 25 mm) metastazės 2/21 limfmazgių.. 1(ekstra). Kraštai. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Kraštai. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.    3. Kairės krūties sektorius.  Krūties audinyje - infiltratyviu frontu plintantis navikas, suformuotas tubulių (80%), pavienių grandinėlių, lizdų ir kribriforminių struktūrų su negausiais kalcifikatais. Naviko ląstelės negausia ar vidutinio gausumo, eozinofiliška citoplazma, vidutinio kalibro ar keliais stambiais, ovoidiškais ar netaisyklingo kontūro, vidutiniškai polimorfiškais branduoliais su negausiu, smulkiai grūdėtu chromatinu ir pavienėmis nukleolėmis. Mitozių navike iki 6/10DPRL. Naviko intravaskulinio plitimo nestebima.    4. Pažasties l/m. 2/21 limfmazgių - aukščiau (nr.3) aprašyto naviko metastazės, didžiausia 25 mm.. 2(ekstra). Kraštai. 2 blokas: CK14+ mioepitelis. Invazyvaus naviko struktūrų neidentifikuota.   1(ekstra). Kraštai. 3 blokas: CK14+ mioepitelis. Invazyvaus naviko struktūrų neidentifikuota.   3. Navikas (11 blokas): E-cadherin(+++)(membr.r-ja)100%.   4. N
answer:  21

  2%|▏         | 10/661 [00:10<10:33,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta dešinė krūtis - planinis tyrimas. Krūtis 1701 gramų svorio 31x22x7 cm. Krūties centrinėje dalyje prasidedantis pilkšvas, standus navikas (I) 9x9x3 cm, odoje išopėjęs 8,5x7 cm plote, nuo giliojo rezekcijos krašto navikas nutolęs 3 cm. Nuo naviko, 3 cm atstumu pilkšvas, ribotas, standus navikas (II) 1,5x1,2x1 cm, nuo giliojo rezekcijos krašto nutolęs 4,5 cm.. Blogai diferencijuota (G3, 9 b. pgl Nottingham) metaplastinė (matriksą produkuojanti) krūties karcinoma;   pT(m)4b(90 mm, 15mm su odos išopėjimu), pLVI-0, pR0.  Imunotipas (nustatytas priešoperaciniame naviko biopsijos tyrime):  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.   Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.   Her2 imuninė reakcija: neigiama 0+.   Ki67+ 90%.. Krūties audinyje 2-jų gausiai nekrozuojančių (apie 80 proc. navikų ploto) navikų netaisyklingas trabekulines struktūras sudaro smulkios ryškiai polimorfiškos ląstelės, stroma vietomis chondroidinė, mitozių iki 20/10 DPRL.. nan
answer:  0

  2%|▏         | 11/661 [00:11<10:22,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštai - extra - be naviko   2(N2b). kraštai - extra - be naviko   3(N3). sarg. l/m - extra - be naviko   4(N1). sektorius, planiškai. 4(N1). Krūties sektorius 10x5x4,5 cm, su odos lopu 9x3,5 cm. Pjūvyje balkšvas, standus neaiškių ribų navikas 2,1x1,7x1,2 cm, nuo artimiausio rezekcijos krašto nutolęs 0,4 cm, nuo odos 1 cm.. 1(N2a). Fokalinė krūties audinio fibrozė.  2(N2b). Fokalinė krūties audinio fibrozė.  3(N3). Reaktyvi limfadenopatija (2 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma, TNM (Nr.1-Nr.4): pT2(2,1 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės invazijos nėra).   ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 20%.. 1(N2a). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2(N2b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N3). Sinusų histiocitozė dviejuose (2) limfmazgiuose.  4(N1). Krūties audinyje - navikas (grandinėlėmis, trabekulėmis besidėstančios ląstelės su negausia ar kiek gausesne blyškiai eozinofiline citoplazma, vidutinio kalibro apvaliais-ovaliais ar kampuotais, dalis ląstelės periferijoje lokalizuotais be nukleolių branduoliais; mitozių navike iki 5 / 10 DPRL).. nan
answer:  0

  2%|▏         | 12/661 [00:12<09:48,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pašalintas kairė krūtis - planinis tyrimas ir kairės pažasties I ir II lygio limfmazgiai. Krūtis 1768 gramų svorio, 32x27x6,5 cm. Krūties audinyje, užspenelinėje srityje, labiau medialiai, balkšvas, standus, neaiškių ribų navikas 46x37x35 mm, nuo giliojo rezekcijos krašto nutolęs 3 cm, nuo odos  - 1 cm.  Aureolė stambiai gruoblėta 3x2,5 cm. Atskirai tame pačiame inde riebalinio audinio fragmentai, bendras dydis 9x8x3 cm. Rasta 10 limfmazgių iki 3,5 cm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2 (46mm) pN2a (7 iš 10 l/m) LVI 1.. Krūties audinyje ir odoje 46mm navikas: netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 30/10 DPRL.  Intravskulinis naviko plitimas.  Iš rastų 10 limfmagzių 7 su metastazėmis iki 35mm.  Operacinis pjūvis be naviko.. nan
answer:  0

  2%|▏         | 13/661 [00:12<09:31,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis ~9×8 mm dydžio darinys kairiojoje krūtyje ties 5 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 fragmentuoti biopsiniai stulpeliai: I - 11 mm; II - 11 mm; III - 7 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 20%.. Krūties audinį infiltruoja pavienės duktalinės struktūros, nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67+ 15
answer:  1

  2%|▏         | 14/661 [00:13<09:11,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2  biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 11 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja netaisyklingi kribroziniai/solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 10%.  ECAD+.
answer:  0

  2%|▏         | 15/661 [00:14<08:57,  1.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. 1 nefragmentuotas biopsinisi stulpelis: I - 12 mm;. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ %.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 10%.  ECAD+.
answer:  0

  2%|▏         | 16/661 [00:15<09:47,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštas - skubus tyrimas- be naviko  2 ėminio aprašas: N2b kraštas - skubus tyrimas- be naviko   3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko  4 ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 9,5x6,5x4 cm, su odos lopu 8x4 cm. Pjūvyje pilkšvas, standus, neaiškių ribų navikas 24x18x18 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2 cm. Nuo naviko 0,5 cm atstumu rusvas, standus darinys 10x5x5 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos  -2,8 cm. Sekančiame pjūvyje galimai darinys susilieja su naviku. Nuo naviko 1 cm atstumu pilkšvas židinys 3x3x2 mm.. PAPILDYTAS ATSAKYMAS (žr. Molekuliniai/FISH/CISH):    1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi mišri vidutiniškai diferencijuota (G2; 7 b. pgl. Nottingham) lobulinė (40%) ir duktalinė karcinoma (60%), suminis TNM: pT2(m)(navikai 30 mm ir 2,5 mm), pN0(sn)(0/3 l/m), LVI2(limfovaskulinis plitimas). Perineurinis naviko plitimas. Gausi perinavikinė limfocitų infiltracija. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.    HER2 geno amplifikacija nenustatyta, tačiau FISH tyrimo rezultatas yra artimas teigiamam, todėl turi būti interpretuojamas įvertinus HER2 IHC tyrimą (žr. molekulinio tyrimo aprašymą ir pastabas).. 1(2a). Krūties audinys su negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(2b). Krūties audinys su negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Trys limfmazgiai su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.  4. Krūties audinyje - hialinizuotoje stromoje 2 naviko židiniai (30 mm ir 2,5 mm mikroskopiškai) infiltratyviu augimo frontu, suformuoti 2 komponentų: a) trabekulinių, juostinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, vidutiniškai polimorfiškais, hiperchromiškais branduoliais; b) smulkių lizdinių, trabekulinių ir pavienių struktūrų su spindžių formacija, suformuotų kiek gausesne eozinofiline citoplazma ląstelių su vidutiniškai polimorfiškais, hiperchromiškais branduoliais. Gausi perinavikinė limfocitų infiltracija. Mitozių navike iki 17/10DPRL. Limfovaskulinė naviko invazija (LVI2). Perineurinis naviko plitimas.. Blokas 15:  E-Cadherin: (++)membran.r-ja 15%;  HER2: vidutinė (++) necirkuliari reakcija, 15%  naviko ląstelių membranoje.
answer:  0

  3%|▎         | 17/661 [00:16<09:23,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 stulpeliai. 2 biopsiniai stulpeliai: I - 17 mm; II - 12 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 75% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 4% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 35%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai/solidiniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 75% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 4% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 80% naviko ląstelių.  Ki67+ 35%
answer:  1

  3%|▎         | 18/661 [00:17<09:12,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. Gauta 2 bioptatai iki 0,01 cm, gleivės - citoblokas.. Mucininė karcinoma (smulkūs naviko fragmentai be aplinkinio audinio).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija paribinė (2+); ŽR.PASTABĄ.  Ki67: proliferacinis indeksas 10%.. Negausūs AB+ mucinų apsupti naviko fragmentai, iš lizdais ar papilinėmis struktūromis besidėstančių ląstelių eozinofiliška citoplazma, vidutinio kalibro, ovaliais, hiperchromiškais branduoliais.. Blokas 1:  CK14: reakcijos naviko ląstelėse nėra (-).  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) cirkuliari reakcija, 15% naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko lą
answer:  0

  3%|▎         | 19/661 [00:18<09:41,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta kairė krūtis - planinis tyrimas. Krūtis, 1163 g svorio, 25,5x19,5x7 cm, spenelis įtrauktas. Centrinėje krūties dalyje, pilkšvas, neaiškių ribų iš susiliejančių židinių sudarytas plotas 22x20 mm, giliojo rezekcijos krašto nutolęs 1,6 cm, nuo odos - 2,3 cm. Krūties audinyje, smulkūs vietomis susiliejantys židiniai.. Vidutinio ir aukšto laipsnio intraduktalinė krūties karcinoma (DCIS/DIN2-3): 22mm plotas, papilinis ir komedo tipas.  ---------------  Du invaziniai navikai:  1. Vidutinės diferenciacijos (G2; 7 balai pgl Nottingham) invazinė duktalinė karcinoma; 1,1mm navikas.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.  Androgenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.    2. Vidutinės diferenciacijos (G2; 6 balai pgl Nottingham) invazinė duktalinė karcinoma; 3,0mm navikas.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 3%.  Androgenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  ---------------  Suminis TNM pT1a(m).. Krūties audinyje 22mm plotas ir atskiri mažesni židiniai visame krūties plote su dilatuotais kanaliukais su intraduktaliniais kribriforminiais vidutiniškai ar ryškiai polimorfiškų ląstelių, vietomis su centrinėmis nekrozėmis.  Šiame 22mm plote invazijos židinys 1,1mm: pabiros polimorfiškos ląstelės ir smulkūs solidiniai kompleksai, mitozių iki 3/DPRL.  Atskiras 3,0mm invazinis naviko židinys krūties audinyje: kribroziniai kompleksai vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  Rezekcijos kraštas be naviko.. nan
answer:  0

  3%|▎         | 20/661 [00:19<09:36,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta kairė krūtis  - planinis tyrimas  2 ėminio aprašas: N2: kairės pažasties sarginiai limfmazgiai planinis tyrimas. 1. Krūtis, 622 g svorio, 24x15x4 cm. Lateralinių kvadrantų riboje, neaiškių ribų, standus, skiltėtos struktūros plotas 6,5x4,5x4,5  mm, nuo giliojo rezekcijos krašto nutolęs 1,5 cm, nuo odos- 1 cm.  2. Riebalinio audinio fragmentas 2,5x1,5x1 cm. Rastas 1 limfmazgis iki 0,6 cm. v/m. N1: Gerai diferencijuota invazinė duktalinė karcinoma pT1mi(m) (daugybiniai smulkūs invazinės karcinomos židiniai, didžiausias 0,7mm).  Invaziniame navike:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigimia (branduolių nusidažymas 2% naviko ląstelių).  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.  Vidutinio laipsnio intraduktalinė krūties Carcinoma in situ (Din2/DCIS; solidinis/kribriforminis tipas; pakitimai 65mm plote).  N2: Limfmazgis be naviko židinių; pN0(sn).. N1: Krūties audinyje 65mm plote gausūs intraduktaliniai solidiniai ir kribroziniai neryškiai ar vidutiniškai polimorfiškų ląstelių proliferatai.  Daugybiniai mikroskopiniai invazijos židiniai stromoje, didžiausias 0,7mm: solidiniai kompleksai minimaliai polimorfiškų ląstelių, vietomis mucininėje stromoje.  Rezekcijos kraštas be naviko.  N2: Limfmazgis be naviko židinių.. nan
answer:  0

  3%|▎         | 21/661 [00:20<10:17,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 2a kraštas - extra - be naviko    2. 2b kraštas - extra - be naviko    3. limgmagis - extra - be naviko    4. N1- sektorius- planinis patologinis tyrimas N1- skubus rentgeninis tyrimas - navikas pašalintas. 4(1). Krūties sektorius 8,5x5,5x2,5 cm su odos lopu 7,5x2,3 cm, žymėtas viela. Vielos projekcijoje, balkšvas, standus neaiškių ribų navikas 0,9x0,7x0,6 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos – 3,5 cm.. 1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija); be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su skersaruožiu raumeniu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(1). Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 6 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).   Pavienės naviko struktūros siekia sektoriaus koaguliacijos zoną.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ir hiperplastišku epiteliu su apokrinine metaplazija; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu, skersaruožio raumens skaidulos; be naviko.   3(ekstra). "Sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4(1). NAVIKAS (6 mm skersmens): krūties audinyje, fibrozuotoje-elastozinėje, desmoplastiškoje stromoje, infiltratyviai plinta smulkios duktalinės, trabekulinės, nedidelės lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 1/10 DPRL.   APLINKA: aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   SEKTORIAUS REZEKCIJOS KRAŠTAS: pavienės naviko struktūros siekia koaguliacijos zoną.. 4(1). Navikas (blokas 13):  HER2: silpna (+) necirkuliari reakcija, 80% naviko ląstelių membranoje.
answer:  0

  3%|▎         | 22/661 [00:20<09:54,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 11 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma   (plitimas 2/2 biopsiniuose stulpeliuose, iki 8,8 mm ilgyje).  Naviko imunofenotipas:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 50% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 15%.. Krūties audinyje (2/2 biopsiniuose stulpeliuose, iki 8,8 mm ilgyje) - lizdinės ir solidinės struktūros, suformuotos ląstelių su vidutinio gausumo, eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, hiperchromšikais, vesikuolizuotais, vidutiniškai polimorfiškais branduoliais. Mitozių navike iki 1/10DPRL. Kalcifikatų, intravaskulinio plitimo nestebima.. Blokas 1:  CD31: vidutinis (++)  dažymasis 30% naviko ląstelių membranoje. CD31+ endotelis (intravaskulinio naviko plitimo nėra).  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) cirkuliari reakcija,
answer:  30

  3%|▎         | 23/661 [00:21<09:26,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 . 1a- viršutinis kraštas, skubu  2. 1b- apatinis kraštas, skubu  3. (2). deš. pažasties sarginiai limfmazgiai, skubu  4. (3). Deš. krūties sektorius, planinis. 4. Krūties sektorius 4x3x1,2 cm be odos. Pjūvyje pilkšvas ribotas navikas 9x8x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm.. N1ab: Krūties audinys be naviko.  N2: Limfmazgiai (3 l/m) be naviko; pN0(sn).  N3: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (9mm).. N1ab: Krūties audinys be naviko.  N2: Limfmazgiai (3 l/m) be naviko.  N3: Krūties audinyje 9mm navikas: kampuotos duktalinės struktūros, negausūs kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. nan
answer:  0

  4%|▎         | 24/661 [00:22<09:08,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Vidutiniškai diferencijuota (G2, 7balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 25%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 80% naviko ląstelių.  Ki67+ 25%.
answer:  1

  4%|▍         | 25/661 [00:23<08:55,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 15 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma.     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.. Solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne švelniai eozinofiline citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 6 / 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 5% naviko ląstelių.  Prolifer
answer:  5

  4%|▍         | 26/661 [00:24<08:49,  1.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 7 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.. Bioptatuose (2/2) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, lizdais ir trabekulėmis besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, ryškiai polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 3/10 DPRL. Gausi perinavikinė limfoplazmocitinė infiltracija.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 95%.  HER2: silpnas dalies membranos nusidažymas 1% naviko ląstelių.  Ki67 proliferacinis aktyvumas 20%.  E-cadherin(+++) membr r-ja 100%. Synaptophysi
answer:  0

  4%|▍         | 27/661 [00:24<08:39,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 12 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 60% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 6%.. Krūties audinį infiltruoja duktalinės struktūros (25%), netaisyklingi kribroziniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: vidutinė (++) reakcija, 60% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 70%  naviko ląstelių membranoje; vi
answer:  1

  4%|▍         | 28/661 [00:26<09:36,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2). Kairės pažasties sarginiai limfmazgiai, skubu  4(3). Kairės krūties sektorius, planinis. 4(3). Krūties sektorius 8x3,5x7,5 cm be odos, žymėtas viela. Vielos projekcijoje pilkšvas, neaiškių ribų navikas 11x9x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm. Nuo naviko 2,3 cm atstumu rusvas sustandėjimas 9x8x6 mm plote, nuo giliojo rezekcijos krašto nutolęs 0,1 cm.. 1(1a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(1b, ekstra). "Kraštai": fibrozuotas krūties audinys; kalcifikatai; be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   4(3). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 7 mm) N0(sn) (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, sklerozuojanti ir mikroglandulinė adenozė,   stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).. 1(1a, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(1b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; keli smulkūs kalcifikatai; be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4(3). NAVIKAS (mikroskopiškai naviko židinys - 7 mm; aplink naviką kompaktiškas fibrozinis audinys): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios kribriforminės ir lizdinės, naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, negausia ar vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozės pavienės sunkiai identifikuojamos.   APLINKA: aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti, kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  SEKTORIAUS REZEKCIJOS KRAŠTAS: aukščiau aprašyti fibrocistiniai pokyčiai; be naviko.. Navikas (blokas 17):  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.
answer:  0

  4%|▍         | 29/661 [00:27<09:43,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sarginiai l/m , ekstra;  2. deš krūtis, planinis.. 2. Krūtis 261 gramų svorio, 12,5x9,5x4,5 cm. Krūties audinyje, pospenelinėje zonoje - pilkšvai rusvas, standus, aiškių ribų navikas 2,4x2x2,4 cm, nuo odos nutolęs <0,1 cm, nuo artimiausio rezekcijos krašto - 2,3 cm.. 1. Reaktyvi limfadenopatija (2 l/m).  2. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 24mm) pN0(sn)(0/2 l/m); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse). Rezekcijos kraštas be naviko.  Estrogenų receptoriai: reakcija teigiama (vidutinė/stipri branduolių r-ja, 90% naviko ląstelių);   Progesterono receptoriai: reakcija teigiama (stipri branduolių r-ja, 85% naviko ląstelių);  HER2: reakcija neigiama (0+).  Androgenų receptoriai(++/+++), brand. r-ja, 60%;   Ki67 proliferacinis aktyvumas ~10%, fokaliai iki 20%;. 1. Du(2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  2. Krūties riebaliniame/fibroziniame audinyje, spenelio dermoje - navikas, formuojamas besieliejančių solidinių, fokaliai kribriforminių, pavienių papilinių struktūrų, smulkių agregatų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais; navike iki 7 mitozių/10 DPRL; Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse. Rezekcijos kraštas be naviko.. Navikas:  Estrogenų receptoriai: vidutinė/stipri branduolių r-ja, 90% naviko ląstelių;   Progesterono receptoriai: stipri branduolių r-ja, 85% naviko ląstelių;  HER2: nusidažiusių naviko ląstelių membranų nėra.  Androgenų receptoriai(++/+++), brand. r-ja,
answer:  60

  5%|▍         | 30/661 [00:28<09:54,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N3): kairės pažasties sarginis limfmazgis - skubus tyrimas - 2l/m be naviko  4(N1): pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 12x4,5x10 cm su oda 10x2,5 cm. Krūties audinyje, kvadrante - pilkšvas, standus, aiškių ribų navikas  25x16x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 1,8 cm.. 1. Krūties audinys.  2. Krūties audinys.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi, vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 25mm) pN0(sn)(0/2 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC/FISH reakcijos atliktos VPC:B23-19184 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcja neigiama, branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 35%.  HER2(FISH): NUSTATYTA HER2 GENO AMPLIFIKACIJA"  Stulpinis ląstelių pokytis su apikaline sekrecija.. 1. Riebalinis audinys su fibrozinėmis septomis, pavieniais latakėliais, klotais dvisluoksniu epiteliu.  2. Riebalinis audinys su fibrozinėmis septomis, pavieniais latakėliais, klotais dvisluoksniu epiteliu.  3. Du(2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze, lipomatoze.  4. Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas solidinių/lizdinių, trabekulinių, netaisyklingų liaukinių, kribriforminių struktūrų (~70% naviko) struktūrų iš vidutinio/stambaus kalibro ląstelių, vidutiniškai, vietomis ryškiai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 10 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su stulpiniu ląstelių pokyčiu ir apikaline sekrecija.. nan
answer:  0

  5%|▍         | 31/661 [00:28<09:21,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 10 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 12%.. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 100% naviko ląstelių.  Ki67+ 12
answer:  1

  5%|▍         | 32/661 [00:30<11:25,  1.09s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas (DCIS įtarimas viename krašte)  2(N2b) kraštai - skubus tyrimas (DCIS įtarimas viename krašte)  3(N3): kairės pažasties markiruotas limfmazgis  - skubus tyrimas 2l/m makromts  4(N4): papildomas kraštas - planinis tyrimas  5(N1): pašalintas markiruotas kairės krūties kvadrantas - planinis tyrimas. 4. Riebalinio audinio fragmentas 2x1,2x0,6 cm.   5. Krūties sektorius 12,5x5,5x4,5 cm, su odos fragmentu 11x3,5 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 17x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,2 cm.. PAPILDYTAS ATSAKYMAS HER2 FISH TYRIMO REZULTATU:   1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(2b, ekstra). "Kraštai": krūties žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS: plokščias tipas). Krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė). Kalcifikatai.  3(ekstra). "Sarginiai limfmazgiai": lobulinės karcinomos metastazės dviejuose limfmazgiuose (mts 2/2 l/m; iki 12 mm skersmens).  4. "Papildomas kraštas": fibrozuotas riebalinis audinys; be naviko.     5(1). Krūties invazyvi mišri karcinoma:   vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma (~70%) ir   gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma (~30%),  SUMINIS TNM:   pT1c (navikas 17 mm) N1a(sn) (lobulinės karcinomos mts 2/2 l/m; iki 12 mm skersmens),   LVI-0 (definityvios limfovaskulinė invazija neidentifikuota).   Kalcifikatai.     Imunofenotipas:   Duktalinėje karcinomoje:   Estrogenų receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.   Progesterono receptoriai: vidutinė (++) reakcija, 20% naviko ląstelių.  HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.  Ki67: proliferacinis indeksas 1-2%.     Molekuliniai tyrimai:   HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Lobulinėje karcinomoje: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: plokščias, kribriforminis tipai).   Krūties lobulinė intraepitelinė neoplazija (LCIS).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(2b, ekstra). "Kraštai": keli intraduktaliniai plokščios konfigūracijos proliferatai, sudaryti saikingai polimorfiškų ląstelių ir CK14(+) atenuoto mioepitelinio sl.; fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu, hiperplastišku ir fokaliai atipiniu epiteliu epiteliu, nedidelės suspaustų kanaliukų zonos, židininė MMN infiltracija, pavieniai kalcifikatai; gausūs koaguliaciniai artefaktai.   3(ekstra). "Sarginiai limfmazgiai"(2): dviejuose (2) limfmazgiuose žemiau, punkte Nr.5, aprašyto naviko (lobulinio komponento) metastazės, iki 12 mm skersmens, su minimaliu ekstranodaliniu plitimu.   4. "Papildomas kraštas": fibrozuotas brandžių lipocitų suformuotas audinys; be naviko.     5(1). NAVIKAS: viename židinyje dvi išsiskiriančios zonos:   1) židinio centre (~30% ploto) - krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta minimaliai besiliejančios ir kiek netaisyklingos duktalinės naviko struktūros, suformuotos saikingai polimorfiškų ląstelių, negausia šviesia citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su  smulkiomis nukleolėmis; mitozės retos sunkiai vizualizuojamos. Pavieniai mikrokalcifikatai. Tarp naviko struktūrų gausūs dilatuoti latakai su kribriforminiais intraduktaliniai naviko ląstelių proliferatais;   2) daugiau židinio periferijoje (~70% ploto) - krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", nedidelės solidinės naviko struktūros, suformuotos mažai kohezyvių vidutiniškai polimorfiškų ląstelių, vidutinio gausumo eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 6/10 DPRL. Zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais.   APLINKA: aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti, kloti dvisluoksniu epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: žemo laipsnio in situ komponentas nutolęs 0,13 mm.. 2(2b, ekstra). "Kraštai" (blokas 4):  CK14(+) atenuotas mioepitelis sluoksnis.      5(1). Navikas (blokas 28):  CK14(+) mioepitelinis sl. neišlikęs invazyviame komponente.     Duktaliniame komponente:   E-Cadherin(+++)(membr.r-ja)100%;   Estrogenų recepto
answer:  100

  5%|▍         | 33/661 [00:31<10:37,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas:  2 fragmentuoti biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 15 mm; II - 3 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G1; 5 b. pgl. Nottingham sist.) išlikusiame 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija teigiama (3+);   Ki67: proliferacinis indeksas 15%.. Kompaktišką fibrozinį audinį audinį išlikusiame 1-me bioptate infiltruoja iki 13 mm :   - duktalinės pavienės struktūros, pabiros ląstelės ir jų paviencės juostos ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: stipri (+++) cirkuliari reakcija, 80% naviko ląstelių memb
answer:  1

  5%|▌         | 34/661 [00:31<09:53,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 7 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja pavienės duktalinės struktūros ir smulkūs netaisyklingi kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

  5%|▌         | 35/661 [00:32<09:57,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)-kraštas - extra tyrimas be naviko  2(N2b)-kraštas - extra tyrimas be naviko  3(N3)- sarginiai l/m - extra  tyrimas be naviko  4(N1) - pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 13x6,5x4,5 cm su oda 12x5 cm. Krūties audinyje, kvadrante - pilkšvas standus, neaiškių ribų navikas 26x12x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1 cm.. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties lobulinė karcinoma in situ (LCIS).  3(ekstra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(30 mm navikas) pN0(sn)(0/2 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir papilinis tipai).      Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu. Keletas dilatuotų latakų su intraduktaliniais monomorfiškų ląstelių proliferatais.  3(ekstra). 2 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (30 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, trabekulinėmis struktūromis, grandinėlėmis ir pabirai besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais stambiais, vidutiniškai polimorfiškais, nereguliaraus kontūro, branduoliais; mitozių 3/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš ląstelių polimorfiškais branduoliais.. 2. 10 blokas: CK14+ mioepitelis.  Navikas(18 blokas):  HER2: neigiama r-ja.   Ki67 proliferacinis aktyvumas 5%.  Ecadherin(-);
answer:  0

  5%|▌         | 36/661 [00:33<09:26,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 16 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6 mm);  (G2; 6 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 5%. Karštame taške 8%.. Krūties audinį 1-me bioptate infiltruoja iki 6 mm :   - solidiniai mazginiai kompleksai;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  eozinofilinėje citoplazmoje;   - su mitozėmis iki 2/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Androgenų receptoriai: stipri  teigiama (+++) branduolių reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija
answer:  0

  6%|▌         | 37/661 [00:34<09:42,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu   3(2). Kairės krūties sektorius su limfmazgiais, planinis. 3. Krūties sektorius 7x6,5x3 cm be odos, žymėtas 2 vielomis, atstumas tarp vielų - 1,5 cm. I vielos projekcijoje, krūties audinyje - pilkšvas, standus, neaiškių ribų navikas 18x15x10 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm. II vielos projekcijoje hemoragija 2,5x1,7 cm plote. Atskirai tame pačiame inde pažasties narveliena 11x6,5x2 cm. Rasti 14 limfmazgiai iki 4 cm.. 1(1a) - viršutinis kraštas. Riebalinis audinys be patologinių pokyčių.  2(1b) - apatinis kraštas. Krūties audinys be patologinių pokyčių.  3(2). Kairės krūties sektorius su limfmazgiais.  Krūtyje invazinė duktalinė karcinoma G2(7 b. pgl. Nottingham sist.);    pT(m)1c, pLVI-0 pN1a pR0.   Estrogenų receptoriai: stipri (+++)  reakcija, 90% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%.    Vidutinio laipsnio intraduktalinė karcinoma, DCIS/DIN2.. 1(1a) - viršutinis kraštas. Riebalinis audinys be patologinių pokyčių.  2(1b) - apatinis kraštas. Krūties audinys be patologinių pokyčių.  3(2). Kairės krūties sektorius su limfmazgiais.  Naviko (mikroskopiškai 16 mm) ir atsitiktinio židinio (1,8 mm) histologinės diferenciacijos suminis laipsniavimas (pagal Nottingham sistemą):   tubulių nestebima, dominuoja trabekulinės struktūros (3 b.) + ląstelių branduolių polimorfizmas vidutinis(2 b.) + mitozių  8-12/10DPRL (2 b.).  Analogiškų ląstelių intraduktalinės struktūros be nekrozės, apima <25% naviko ploto ir plinta už invazyvaus naviko ribų.  Intralimfatinis / Intravaskulinis plitimas nestebimas.  Limfmazgiai: 3-se l/m iš 14 l/m karcinomos plitimas iki 14 mm, kapsulės peraugimas nestebimas.. Blokas 8:  E-Cadherin: stipri teigiama (+++)  cirkuliari (išorinė) membraninė reakcija 100 proc. atipinėse struktūrose  Estrogenų receptoriai: stipri (+++) reakcija, 90% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki6
answer:  30

  6%|▌         | 38/661 [00:35<09:28,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta kairė krūtis  - planinis tyrimas  2 ėminio aprašas: N2: kairės pažasties sarginiai limfmazgiai planinis tyrimas. 1. Krūtis, 622 g svorio, 24x15x4 cm. Lateralinių kvadrantų riboje, neaiškių ribų, standus, skiltėtos struktūros plotas 6,5x4,5x4,5  mm, nuo giliojo rezekcijos krašto nutolęs 1,5 cm, nuo odos- 1 cm.  2. Riebalinio audinio fragmentas 2,5x1,5x1 cm. Rastas 1 limfmazgis iki 0,6 cm. v/m. N1: Gerai diferencijuota invazinė duktalinė karcinoma pT1mi(m) (daugybiniai smulkūs invazinės karcinomos židiniai, didžiausias 0,7mm).  Invaziniame navike:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigimia (branduolių nusidažymas 2% naviko ląstelių).  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.  Vidutinio laipsnio intraduktalinė krūties Carcinoma in situ (Din2/DCIS; solidinis/kribriforminis tipas; pakitimai 65mm plote).  N2: Limfmazgis be naviko židinių; pN0(sn).. N1: Krūties audinyje 65mm plote gausūs intraduktaliniai solidiniai ir kribroziniai neryškiai ar vidutiniškai polimorfiškų ląstelių proliferatai.  Daugybiniai mikroskopiniai invazijos židiniai stromoje, didžiausias 0,7mm: solidiniai kompleksai minimaliai polimorfiškų ląstelių, vietomis mucininėje stromoje.  Rezekcijos kraštas be naviko.  N2: Limfmazgis be naviko židinių.. nan
answer:  0

  6%|▌         | 39/661 [00:36<09:01,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 14 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.. Krūties audinį infiltruoja negausios duktalinės struktūros, nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 20% naviko ląstel
answer:  0

  6%|▌         | 40/661 [00:37<08:59,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Pašalinta dešinė krūtis ir pažasties narveliena.. Krūtis 825 g svorio, 22,5x17,5x4 cm, su pažasties narveliena 9x6,5x2,5 cm. Krūties audinyje balkšvas, standus, gan aiškių ribų navikas 20x14x18 mm, esantis 4,5 cm nuo giliojo rezekcijos pjūvio, siekia odą, bet jos neperauga. Naviko projekcijoje, odoje - sustandėjimas 1,3x1 cm plote. Pažasties narvelienoje rasta 16 limfmazgių, didžiausias 1,7 cm.. Krūties invazyvi gerai diferencijuota (G1,5b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(19,5 mm navikas) pN1a(1/16 l/m MTS 2,1 mm) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 60% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 6%.. Spenelis normali histologinė struktūra.  Krūtyje - navikas (19,5 mm) infiltratyviu ir ekspansyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais stambiais, vidutiniškai polimorfiškais, nereguliaraus kontūro ir ovaliais branduoliais ryškiomis nukleolėmis; mitozių 3/10 DPRL. Limfovaskulinė invazija.  Navikas epidermio neinfiltruoja.  Aplinkinis krūties audinys fibrozuotas su negausiais latakais.. nan
answer:  0

  6%|▌         | 41/661 [00:38<09:26,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - viršutinis kraštas - extra  2 - apatinis kraštas - extra  3- sarginiai l/m - extra  4 - kvadrantas - planiniam tyrimui. 4. Krūties sektorius 6,5x4x4 cm, su odos lopu 5x2 cm. Pjūvyje gelsvas, standus, ribotas navikas 10x10x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 1,8 cm.. 1. Fibrocistiniai krūties pokyčiai.   2. Fibrocistiniai krūties pokyčiai.   3. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/2 l/m, 2,75 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 11 mm), pN1a(sn)(1/2 l/m), LVI2 (limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime (klinikiniai duomenys). HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).. 1. Krūties audinyje, fibrozuotoje stromoje, gausios sklerozuotos lobulės bei dilatuoti kanaliukai, kloti dvisluoksniu epiteliu bei keli nežymiai dilatuoti kanaliukai, kloti hiperplastišku epiteliu. Židininė apokrininė epitelio metaplazija.  2. Krūties audinyje, fibrozuotoje stromoje, gausios sklerozuotos lobulės bei dilatuoti kanaliukai, kloti dvisluoksniu epiteliu bei keli nežymiai dilatuoti kanaliukai, kloti epiteliu su apokrinine metaplazija. Fibroziniame audinyje židininė limfocitų ir putotų makrofagų infiltracija.  3. PO FIKSACIJOS: Viename limfmazgyje iš dviejų žemiau aprašyto naviko metastazė iki 2,75 mm.  4. Krūties audinyje, hialinizuotoje stromoje plinta navikas (mikroskopiškai 11 mm) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių, trabekulinių ir negausių tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su vidutiniškai polimorfiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 6/10DPRL. Limfovaskulinis plitimas smulkiose limfagyslėse/kraujagyslėse(LVI2). Greta naviko gausūs dilatuoti kanaliukai užpildyti kribriforminių proliferatų iš analogiškų navikui ląstelių. Aplinkiniame krūties audinyje, fibrozuotoje stromoje, gausios sklerozuotos lobulės bei dilatuoti kanaliukai, kloti dvisluoksniu epiteliu bei keli nežymiai dilatuoti kanaliukai, kloti hiperplastišku epiteliu. Židininė apokrininė epitelio metaplazija.. Blokas 15:  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.
answer:  0

  6%|▋         | 42/661 [00:38<08:54,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1  biopsinis stulpelis.. Biopsinis stulpelis 9 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: vidutinis ir silpnas branduolių nusidažymas 20% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis ir silpnas branduolių nusidažymas 20% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas
answer:  1

  7%|▋         | 43/661 [00:39<08:40,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 16 mm; II - 13 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 15 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.. Krūties audinį 2-se bioptatuose infiltruoja iki 15 mm :   - duktalinės struktūros (10% viso naviko), netaisyklingi kribroziniai kompleksai;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje citoplazmoje;   - su mitozėmis iki 3/10 DPRL.   Mikrokalcifikatai. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono receptoriai: stipri (+
answer:  50

  7%|▋         | 44/661 [00:40<09:05,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai. - ekstra  2(2b). Kraštai. - ekstra  3. Sarginiai l/m. - ekstra.  4(1). N1- pašalintas sektorius - planinis patologinis tyrimas. 4(1). Krūties sektorius 15x6,5x4 cm su odos lopu 14x14 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 11x10x8 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 3 cm.. 1. Krūties fibrocistiniai pokyčiai.   2. Krūties radialinis randas.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma,   pT1c (11 mm) pN0(sn) (0/2 l/m); LVI0 (limfovaskulinės naviko invazijos neidentifikuota).   Lobulinės karcinomos imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-27803, žr. pastabą.   Žemo laipsnio duktalinė karcinoma in situ (DCIS; kribriforminė, mikropapilinė).. 1. Krūties audinyje - netolygi stromos fibrozė, kelios grupės latakų su apokrinine epitelio metaplazija, intraduktaliniai mikrokalcifikatai.    2. Krūties audinyje - "žvaigždiškas" darinys su centrine fibroze ir smulkiais, vidutinio dydžio bei cistiškai dilatuotais latakais, klotais mioepitelinėmis ląstelėmis ir stulpiniu epiteliu su apikalinės sekrecijos požymiais, intraduktaline epitelio hiperplazija.   3. Limfmazgiai (3) su ryškia lipomatoze, nedideliais antriniais folikulais, be naviko plitimo.  4. Krūties audinyje - navikas, formuojamas infiltratyviai plintančių, glaudžiai besidėstančių grandinėlių, trabekulinių struktūrų, smulkių grupių, sudarytų iš nedidelių-vidutinio dydžio poligonalinių ląstelių šviesiai eozinofiliška citoplazma, nežymiai ar vidutiniškai polimorfiškais ovaliais ar skeltais branduoliais su vezikulizuotu chromatinu, smulkiomis nukleolėmis. Gausios pabirai-difuziškai plintančios naviko ląstelės. Navike iki 1 mitozės/ 10 DPRL. Limfovaskulinės invazijos neidentifikuota.   Aplinkiniame krūties audinyje - grupė latakų su intraduktaliniais kribriforminiais proliferatais iš duktalinio tipo ląstelių su nežymiu branduolių polimorfizmu, pavienis latakas su intraduktalinėmis mikropapilinėmis analogiško epitelio struktūromis.. nan
answer:  0

  7%|▋         | 45/661 [00:41<09:36,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)- kraštai - skubus tyrimas LCIS viename krašte  2(N2b) - kraštai - skubus tyrimas LCIS viename krašte  3(N3) - kairės pažasties sarginis limfmazgis - skubus tyrimas - 2l/m be naviko  4(N1) - pašalintas kairės krūties kvadrantas su speneliu (atskirai) - planinis tyrimas. 4. Krūties sektorius 15x6,5x6 cm su oda 13,5x2,5 cm. Krūties audinyje, pilkšvas standus neaiškių ribų navikas 30x30x22 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 2,2 cm. Atskirai tame pačiame inde spenelis su aplinkine oda 4,5x3x1,8 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties lobulinė karcinoma in situ (LCIS).   3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(31 mm) N(sn)0(0/2 l/m), LVI-2(limfovaskulinė invazija). Perineurinė invazija. Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties lobulinė karcinoma in situ (LCIS).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Krūties intraduktalinės papilomos ir fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  3(Extra). 2 limfmazgiai su fokaline parakortekso hiperplazija, sinusų histiocitoze ir lipomatoze.  4. KRŪTIS: krūties audinyje - ribotas navikas (mikroskopiškai 31 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių trabekulinių ir lizdinių struktūrų bei grandinėlėmis, smulkiomis grupėmis ir pabirai besidėstančių ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais/apvaliais ir nereguliariais, kiek polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 3/10 DPRL. Perineurinė ir limfovaskulinė invazija. Negausūs smulkūs kalcifikatai. LCIS šalia.  Aplink yra dilatuotų kanaliukų su kribriforminiais intraduktaliniais vidutiniškai polimorfiškų ląstelių proliferatais, kanaliukų su intraduktalinėmis papilinėmis struktūromis, klotomis dvisluoksniu stulpiniu epiteliu bei kanaliukų su epitelio hiperplazija.  SPENELIS: normali histologinė struktūra.. 4. Navikas (15 blokas):  Lobulinė karcinoma E-Cadherin(-); DCIS struktūrose E-Cadherin(+).
answer:  0

  7%|▋         | 46/661 [00:42<09:41,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 . 3 sarginiai l/m - skubi patologija - be naviko   2. (N1)- pašalinta krūtis - planinis tyrimas. 2. Krūtis 600 gramų svorio, 22x15,5x5 cm. Krūties audinyje, viršutiniame medialiniame kvadrante, balkšvas, standus, neaiškių ribų navikas 4,5x3,5x3 cm, siekia odą, ją įtraukia 1,7x0,6 cm plote, nuo giliojo rezekcijos krašto nutolęs 0,5 cm.   Viršutiniame lateraliniame kvadrante balkšvas, standus, gana aiškių ribų darinys 1,5x1,5x0,7 cm, nuo odos nutolęs 4 cm, nuo giliojo rezekcijos krašto - 0,4 cm, nuo naviko - 8 cm.. 1(N2)-sarginiai l/m-extra: limfmazgiai (3) be karcinomos ląstelių plitimo; pN0.    2(N1)- pašalinta dešinė krūtis.   Invazinė duktalinė (kitaip neklasifikuojama) karcinoma;  (G2; 7 b. pgl. Nottingham sist.);  pT2 pLVI-0 pR0 (<1 mm).  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija teigiama (3+);   Ki67: proliferacinis indeksas 15%.    Krūties fibrocistiniai pokyčiai.. 1(N2)-sarginiai l/m-extra: limfmazgiai (3) be karcinomos ląstelių plitimo.  2(N1)- pašalinta dešinė krūtis. Kompaktišką fibrozinį audinį audinį netaisyklingų ribų navikas infiltruoja iki 45mm :   - duktalinės pavienės struktūros, pabiros ląstelės ir jų paviencės juostos ir trabekulės;  - epitelinių smulkių  ir vidutinio dydžio ląstelių su visutiniškai polimorfiškais branduoliais gausioje eozinofilinėje citoplazmoje;   - mitozių iki 12 / 10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.  Navikas 1 mm nuo operacinio krašto.  Atskirai esančio darinio fibrozuotame audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu, fokaliai apokrininė metaplazija.. nan
answer:  0

  7%|▋         | 47/661 [00:43<09:08,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stlpeliai. 3 biopsiniai stulpeliai: I - 10 mm; II - 7 mm; III - 8 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo  nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo  nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 15%.
answer:  0

  7%|▋         | 48/661 [00:44<09:19,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N3) dešinės pažasties sarginis limfmazgis  skubus tyrimas - 3l/m be naviko  4(N1): pašalintas dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 5x3,7x2,5 cm su odos lopu 4,5x2 cm. Pjūvyje pilkšvas, standus, aiškių ribų navikas 19x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 1,2 cm.. 1(N2a) kraštai. Krūties audinys be patologinių pokyčių.    2(N2b) kraštai. Krūties audinys be patologinių pokyčių.    3(N3) dešinės pažasties sarginis limfmazgis. Limfmazgiai (3) be karcinomos ląstelių.    4(N1) dešinės krūties kvadrantas.  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma;(G3; 8 b. pgl. Nottingham sist.).  pT1c pN(sn)0(0/3) pLVI-0 pR0.  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stipri (+++)  reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%.    Intraduktalinė vidutinio laipsnio karcinoma (DCIS, DIN2 solidinio ir komedo tipo).. 1(N2a) kraštai. Krūties audinys be patologinių pokyčių.  2(N2b) kraštai. Krūties audinys be patologinių pokyčių.  3(N3) dešinės pažasties sarginis limfmazgis. Limfmazgiai (3) be karcinomos ląstelių.  4(N1) dešinės krūties kvadrantas. Krūties audinį infiltruoja aiškių ribų navikas, suformuotas trabekules sudarančių epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje su mitozėmis iki 20/10 DPRL. Intravaskulinės invazijos nėra.  Gretimai analogiškų ląstelių solidinės inraduktalinės struktūros, židiniškai su centrinėmis nekrozėmis. Intraduktalinės ir invazinės struktūros nuo žymėto operacinio krašto 0,6 mm.. nan
answer:  0

  7%|▋         | 49/661 [00:45<09:38,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. kraštai - extra  2. kraštai - extra  3. sektorius su limfmazgiais, planinis.. 3. Krūties sektorius 13x9x6 cm su odos lopu 10x5 cm ir pažasties narveliena 12x9x4 cm. Rezekcijos kraštas dažytas mėlynu tušu. Pjūvyje gausus liaukinis audinys 10x9x6 cm zonoje ir pilkšvas, netolygių kontūrų, neaiškių ribų navikas 6,5x5,5x2 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos - 2 cm. Pažasties narvelienoje rasti 22 limfmazgiai iki 3,5 cm su židiniais iki 3 cm skersmens.. 1(ekstra). Krūties fibrocistiniai pokyčiai, stulpinis ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija. Adenozė.   2(ekstra). Krūties intraduktalinė papiloma. Fibrocistiniai pokyčiai, stulpinis ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija.   3. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma (su morfologiniais lobulinės karcinomos požymiais).   SUMINIS TNM: pT3(65 mm navikas) N3a(12/22 l/m MTS iki 3 cm) LVI-2 (limfovaskulinė invazija). Naviko struktūros plinta sektoriaus rezekcijos krašte.   Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis tipas).. 1(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais, kompaktiškais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Dalyje kanaliukų apokrininė metaplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).    2(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Dalyje kanaliukų apokrininė metaplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Darinys suformuotas šakotų papilinių struktūrų iš fibrozinės stromos, klotos dvisluoksniu epiteliu.  3. Krūties audinyje - fibrozinėje stromoje, infiltratyviu frontu plintantis navikas, suformuotas trabekulių, grandinėlių ir smulkių lizdų. Naviko ląstelės su negausia, blyškia citoplazma, vidutinio kalibro, apvaliais ar netolygaus kontūro, vidutiniškai polimorfiškais branduoliais. Mitozių navike iki 4/10DPRL. Naviko plitimas endotelizuotuose spindžiuose.  Šalia naviko dilatuoti kanaliukai su intraduktaliniais solidiniais proliferatais iš analogiškų navikui ląstelių.  Limfmazgiai (22): 12/22 limfmazgių - aukščiau aprašyto naviko metastazės (iki 3 cm makroskopiškai).. 3. 17 blokas(navikas): E-cadherin(+++)(membr.r-ja)100%;  p120(+++)(membr.r-ja)(su silpna fonine citoplazmine r-ja)100%; Beta-Catenin(+++)(membr.r-ja)100%.
answer:  0

  8%|▊         | 50/661 [00:46<09:04,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3  biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 11 mm; III - 8 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 45%, vietomis iki 60%.. Krūties audinį infiltruoja solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 45%,
answer:  1

  8%|▊         | 51/661 [00:47<08:44,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 13 mm; II - 10 mm; III - 14 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.. Krūties audinį 3-se bioptatuose infiltruoja iki 11 mm :   - solidiniai kompleksai, juostos ir trabekulės;  - epitelinių vidutinio dydžio / stambių ląstelių su vidutiniškai polimorfiškais branduoliais negausioje citoplazmoje;   - su mitozėmis iki 5/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  100

  8%|▊         | 52/661 [00:48<09:36,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). kraštai, skubu  2(N2). kraštai, skubu  3(N3). sarginiai l/m  4(N4). Deš.krūties kvadrantas.. 4. Krūties sektorius 13,5x3,5x8,5 cm su oda 10x2 cm, žymėtas 2 vielomis:  - I vielos projekcijoje, pilkšvas, standus, neaiškių ribų navikas 12x10x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 5,3 cm.  - II vielos projekcijoje, gelsvas, neaiškių ribų židinys 4x4x4 mm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 3,2 cm.. 1(Extra). Krūties audinys.  2(Extra). Riebalinis audinys.  3(Extra). Reaktyvi limfadenopatija (5 l/m).  4. A) Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(8,5 mm) N(sn)0(0/5 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus/vidutinis branduolių nusidažymas 50% naviko ląstelių.  HER2 imuninė reakcija: neigiama (0).  Ki67: 10% (hot-spot 15%).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).     B) Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1a(1,3 mm) N(sn)0(0/5 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  HER2 imuninė reakcija: neigiama (1+).  Ki67: 1%.   Lobulinė karcinoma in situ (LCIS).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - negausūs vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Brandus riebalinis audinys su negausiomis kraujagyslėmis.  3(Extra). 5 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.  4. Krūties audinyje (ties I viela) - ribotas navikas (mikroskopiškai 8,5 mm), suformuotas fibrozuotoje stromoje plintančių lizdinių ir tubulinių bei kribriforminių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 9/10 DPRL. Šalia negausūs dilatuoti kanaliukai su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais.  Ties II viela, fibrozuotoje stromoje - dilatuoti kanaliukai su solidiniais intraduktaliniais proliferatais, fokaliai su komedo nekrozėmis centre, suformuotais analogiškų navikui ląstelių.  Atokiau - smulkus (1,3 mm) židinys, suformuotas smulkiomis grupėmis besidėstančių ląstelių saikinga, šviesiai eozinofiliška citoplazma, smulkiais ir vidutinio kalibro, apvaliais, gan monomorfiškais, su smulkia nukleole branduoliais; mitozių neidentifikuota. Aplink dilatuoti kanaliukai, užpildyti monomorfiškomis ląstelėmis (LCIS).. 4. Navikas/duktalinė karcinoma (19 blokas):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus/vidutinis branduolių nusidažymas 50% naviko ląstelių.  HER2 imuninė reakcija: nusidažiusių naviko l
answer:  100

  8%|▊         | 53/661 [00:48<08:59,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 10 mm; II - 12 mm; III - 12 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 15/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląs
answer:  1

  8%|▊         | 54/661 [00:49<08:36,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 10 mm ilgio.. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.. Bioptate - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 5/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 5% naviko ląstelių.  Ki67 proliferacinis aktyvumas 5%.
answer:  0

  8%|▊         | 55/661 [00:50<09:29,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Ca mammae sin cT1Nx..I st. Ca mammae dex pT1Na(SN)... I st. (2015 m.). - extra.  1. Sektoriaus kraštai - extra;  2. Sektoriaus kraštai - extra;  3. Sarginiai lifmazgiai - extra;  4(5). Papildomas kraštas - extra.  5(4). Krūties sektorius - planinis.. 5. Krūties sektorius 9x8x3 cm odos lopu 8,5x2,3 cm. Pjūvyje balkšvas, standus, kiek neaiškių ribų navikas 1,9x1,6x1,5 cm, nuo odos nutolęs 2,6 cm, nuo artimiausio rezekcijos krašto - 0,8 cm. 1. Sektoriaus kraštai.   Krūties žemo laipsnio duktalinė karcinoma in situ (DCIS,DIN1).   Intraduktalinė papiloma. Židininė intraduktalinė hiperplazija.    2. Sektoriaus kraštai. Krūties audinys be patologinių pokyčių.    3. Sarginiai limfmazgiai. Karcinomos plitimas iki 4,5 mm 1-me/9 limfmazgių; stebimas ekstranodalinis plitimas.    4(5). Papildomas kraštas. Krūties audinys be patologinių pokyčių.    5(4). Krūties sektorius.   Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma;   pT1c(15 mm mikroskopiškai) pN1a (1/9; 4,5 mm) pR0.   Imunofenotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.   Progesterono receptoriai: (+++)(brand. r-ja) 100%.   HER2 imuninės reakcijos nėra (0).  Ki67 proliferacinis aktyvumas iki 10%.    Krūties žemo laipsnio duktalinė karcinoma in situ (DCIS,DIN1).   Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija,   sklerozuojanti adenozė.. 1. Sektoriaus kraštai. Negausūs kiek išplėsti kanaliukai su tinkliniais intraduktaliniais ląstelių proliferatais su eozinofiliška citoplazma, vidutinio kalibro ir nežymiai polimorfiškais branduoliais. Cista su tubulo- papilinėmis aukšto epitelio struktūromis su kiek stratifikuotais pailgais branduoliais bei mioepiteliu. išplėstas kanaliukas hiperplastiniu duktaliniu epiteliu be atipijos.  2. Sektoriaus kraštai. Krūties audinys be patologinių pokyčių.  3. Sarginiai limfmazgiai. Karcinomos duktalinės ir tinklinės struktūros plinta iki 4,5 mm 1-me/9 limfmazgių; stebimas ekstranodalinis plitimas.  4(5). Papildomas kraštas. Krūties audinys be patologinių pokyčių.  5(4). Krūties sektorius. Krūties audinyje, fibrozinėje stromoje, plinta mikroskopiškai iki 15 mm infiltratyvios tubulinės (apie 40 proc.), trabekulinės bei pavienės kribriforminės naviko struktūros, suformuotos ląstelių vidutinio gausumo eozinofiliška citoplazma, nežymiai ar vidutiniškai polimorfiškais, hiperchromiškais, ovoidinias ar kiek nereguliaraus kontūro branduoliais; mitozių iki 3/10 DPRL.  Intravaskulinio plitimo nestebima.  Operaciniame krašte -židiniškai stebimi išplėsti kanaliukai su tinkliniais intraduktaliniais ląstelių proliferatais su eozinofiliška citoplazma, vidutinio kalibro ir nežymiai polimorfiškais branduoliais.  Aplink naviką - fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, smulkių kanaliukų proliferacijos zonos, apokrininė metaplazija.. p63: neigiamas(-) branduolinis dažymasis .   CD56 : neigiamas(-) membraninis dažymasis naviko ląstelėse.   Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100% naviko ląstelėse.   Progesterono receptoriai: vidutinis(++) branduolinis dažymasis 1
answer:  100

  8%|▊         | 56/661 [00:51<09:21,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta dešinė krūtis ir dešinės pažasties limfmazgiai. Krūtis 812 g svorio, 22x16x5 cm, su pažasties narveliena ir atskiru riebalinio audinio fragmentu, bendras dydis 10x12x4 cm.   Krūties audinyje pilkšvas, standus, aiškių ribų navikas 30x25x24 mm, esantis 0,7 mm nuo artimiausio/giliojo rezekcijos pjūvio, nuo odos 2 cm. Pažasties narvelienoje rasta 12 limfmazgių, didžiausias 3,8 cm su pilkšvu židiniu 3,3 cm.. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT2(30 mm navikas) pN1a(1/12 l/m su mts 33mm) pLVI0 (limfovaskulinė invazija neidentifikuota) pR0(radikalus pašalinimas).  Naviko imunotipas:  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 80%.    Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis, kribriforminis tipai).. Krūties audinyje - navikas, suformuotas solidinių kompleksų ir lizdų, iš ląstelių su negausia amfofiliška citoplazma, vidutinio kalibro ar stambiais, ovoidiškais, ryškiai polimorfiškais branduoliais su  smulkiomis nukleolėmis. Mitozių navike iki 77/10DPRL.   Naviko nekrozė ~30%.   Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių.  Limfmazgiai (12): 1-me/12 limfmazgių - aukščiau aprašyto naviko metastazės iki 3,3 cm (makroskopiškai).. Blokas 7(navikas):  CD31: endotelis+ (limfovaskulinė invazija neidentifikuota);  CK5(+)(citopl.r-ja)15%; GATA3(++)(brand.r-ja)80%; Synaptophysin(-);  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių mem
answer:  0

  9%|▊         | 57/661 [00:53<10:54,  1.08s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Kairė krūtis su limfmazgiais, planinis. Krūtis 1535 g svorio, 19x19x8 cm. Krūties audinyje, apatinių kvadrantų ribose, multižidininis navikas, kurių bendras dydis 4,5x3x2,8 cm, nuo rezekcijos krašto nutolęs 2,5 cm, nuo odos 1 cm.   - rusvas, su cistinėmis ertmėmis, užpildytomis hemoragišku turiniu ir trapiomis masėmis I navikas 4,2x3,8x2,7 nuo artimiausio rezekcijos krašto nutolęs 2 cm, nuo odos - 0,8 cm.  - 0,5 cm, medialiau - balkšvas, standus, netolygių kraštų II navikas 1,4x0,7x1 cm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos 1,5 cm.  - 2,5 cm virš I naviko - balkšvas, standus, neaiškių ribų III navikas 0,7x0,4x0,5 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 2 cm, nuo odos - 5 cm.  - 1 cm virš I naviko - 4 ovalūs, pilkšvi, aiškių ribų židiniai nuo 0,3 cm iki 0,7 cm skersmens.  - viršutiniame lateraliniame kvadrante, pilkšva, standi, neaiškių ribų, fibrozės zona 2,5x2,5x2 cm, nuo I židinio nutolęs 4 cm, nuo artimiausio rezekcijos krašto nutolęs 1,5 cm, nuo odos - 3 cm.  Atskirai tame pačiame inde - pažasties narveliena (12x11x4 cm), su 31 limfmazgiu (didžiausias 4 cm; dviejuose limfmazgiuose - makroskopiškai vizualizuojami balkšvi židiniai, 2 cm ir 2 cm).. A) Krūties invazyvi multicentrinė karcinoma:  - invazyvi duktalinė adenokarcinoma (vidutiniškai diferencijuota/G2/6 balai pagal Nottingham) (4,2 cm naviko židinys; intraduktalinės papilinės, solidinės papilinės karcinomos fone),  - invazyvi lobulinė karcinoma (vidutiniškai diferencijuota/G2/6 balai pagal Nottingham) (1,4 cm naviko židinys).   B) Dauginės intraduktalinės papilomos.  C) Lobulinė karcinoma in situ (LCIS).  D) Krūties fibrocistiniai pokyčiai.  ---  Piktybinių navikų (karcinomų) "suminis" kategorizavimas pagal TNM: pT2(m)(iki 4,2 cm duktalinės karcinomos + iki 1,4 cm lobulinės karcinomos židiniai) pN2a(duktalinės adenokarcinomos mts 5/31 l/m, didžiausia metastazė 2,0 cm, nežymus ekstranodalinis plitimas). LVI2(duktalinės adenokarcinomos limfovaskulinė naviko invazija, smulkiose struktūrose). R0(radikalus navikų pašalinimas).   ---  Krūties invazyvios duktalinės adenokarcinomos imunofenotipas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.  ---  Krūties invazyvios lobulinės karcinomos imunofenotipas  Estrogenų receptoriai: stiprus-vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.. KRŪTIES SPENELIS: Be patologijos.  KRŪTIS: Krūties audinyje - dauginiai skirtingi "pažeidimai":  A) Invazyvios karcinomos:  - Invazyvi duktalinė adenokarcinoma (iki 4,2 cm; intraduktalinės papilinės, solidinės papilinės karcinomos fone): trabekulines, pavienes smulkias duktalines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne šviesia citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 6 / 10 DPRL; gausios susiliejančios papilinės, negausios solidinės struktūros, suformuotos ląstelių su kiek netaisyklingais branduoliais.  - Invazyvi lobulinė karcinoma (iki 1,4 cm naviko židinys): grandinėlėmis, trabekulėmis ar pabirai besidėstančios ląstelės su negausia ar kiek gausesne blyškiai eozinofiline citoplazma, vidutinio kalibro apvaliais-ovaliais ar kampuotais, dalis ląstelės periferijoje lokalizuotais be nukleolių branduoliais; mitozių navike iki 3 / 10 DPRL).    B) dauginės intraduktalinės papilomos (zonos su susiliejančiomis žemu stulpiniu, stulpiniu, kubiniu epiteliu išklotomis papilinėmis struktūromis kanaliukų spindžiuose),  C) Lobulinė karcinoma in situ (LCIS): kanaliukai su monotoniškais solidiniais smulkių ląstelių proliferatais spindžiuose.  D) Įvairių formų "fibrocistiniai pokyčiai": fibrozinėje stromoje - smulkūs ar kiek stambesnio kalibro, fokaliai dilatuoti kanaliukai, iškloti dvisluoksniu epiteliu; apokrininės metaplazijos, intraduktalinės hiperplazijos židiniai.  PAŽASTIES NARVELIENA: Aukščiau aprašyto naviko (duktalinės adenokarcinomos) metastazės limfmazgiuose (penkiuose (5) iš trisdešimt vieno (31), didžiausia metastazė 2,0 cm, nežymus ekstranodalinis plitimas).. Navikas (lobulinė karcinoma; 16 blokas):  Estrogenų receptoriai: stiprus-vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: nusidažiusių naviko ląst
answer:  20

  9%|▉         | 58/661 [00:54<10:36,  1.06s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 2a kraštas - extra - be naviko  2. 2b kraštas - extra - be naviko  3. sarginiai l/m - extra - (3) be naviko  4 ėminio aprašas:  N1 - pašalintas sekorius su sukietėjimu- planinis paologinis tyrimas (Skubus N1- rentgeninis tyrimas - navikas 13 mm ir intramammarinis l/m - pašalinti. 4. Krūties sektorius 12,8x8,5x6 cm su odos lopu 12x6 cm. Pjūvyje  pilkšvas, standus, ribotas 14x12x10 mm navikas, pereinantis į fibrozę. Nuo giliojo rezekcijos krašto nutolę 0,6 cm, nuo odos - 2,4 cm.. 1. Krūties audinys.  2. Riebalinis audinys be patologijos.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi blogai diferencijuota (G3; 8 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 13,5 mm), pN0(sn)(0/3 l/m), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS). HER2:reakcijos nėra (0).  Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija.. 1. Krūties audinyje smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2. Riebalinis audinys su plonomis fibrozinėmis septomis ir smulkiomis kraujagyslėmis.  3. Trys limfmazgiai (3 l/m) su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.   4. Krūties audinyje, hialinizuotoje stromoje plinta navikas (13,5 mm mikroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių, trabekulinių ir negausių struktūrų su spindžių formacija. Naviko ląstelės negausia eozinofiline citoplazma su ryškiai polimorfiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 16/10DPRL. Limfovaskulinis plitimas smulkiose limfagyslėse/kraujagyslėse(LVI2). Navikas nuo artimiausio rezekcijos krašto nutolęs per 7 mm. Greta naviko negausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Krūties audinyje, fibrozuotoje stromoje dilatuoti kanaliukai, kloti dvisluoksniu epiteliu bei keli nežymiai dilatuoti kanaliukai, kloti hiperplastišku epiteliu.. Blokas 19:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

  9%|▉         | 59/661 [00:55<09:59,  1.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 9 mm; II - 10 mm; III - 3 mm.. Papildyta HER2 FISH.  Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma. Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+).  Ki67 proliferacinis aktyvumas 15%.  HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).. Fragmentuotuose bioptatuose (3/3) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos tubulėmis, kribriforminėmis str. ir lizdais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio kalibro, nereguliaraus kontūro - ovaliais branduoliais; mitozių 2/10 DPRL. gausūs dilatuoti latakai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: vidutinis visos membranos nusidažymas 60% naviko ląstelių.  Ki67 proliferacinis aktyvumas 15%.
answer:  0

  9%|▉         | 60/661 [00:55<09:17,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm ilgio.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 15%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 10% naviko ląstelių.  Ki67+ 15%
answer:  1

  9%|▉         | 61/661 [00:57<10:40,  1.07s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.  2(2b). Kraštai - skubus tyrimas - be naviko.  3(1). Pašalintas kairės krūties kvadrantas - planinis tyrimas.  4(3). Kairės pažasties limfmazgiai - planinis tyrimas.. 3(1). Krūties sektorius 10,5x6x4,5 cm. Krūties audinyje, pjūvyje pilkšvas, standus, aiškių ribų 15x13x8 mm navikas, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1,6 cm.   4(3). Riebalinio audinio fragmentai, bendras dydis 7,5x4,5x2 cm. Rasta 10 limfmazgių, didžiausias 4,5 cm.. 1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   2(2b, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko  3(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (I - 14 mm; II - 4 mm) N2a (mts 6/10 l/m; iki 45 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.     Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: solidinis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   4(3). "Kairės pažasties limfmazgiai": duktalinės karcinomos metastazė šešiuose limfmazgiuose (mts 6/10 l/m; iki 45 mm skersmens; su ekstranodaliniu plitimu).. 1(2a, ekstra). "Kraštai": fokaliai fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar nežymiai hiperplastišku epiteliu; be naviko.   2(2b, ekstra). "Kraštai": fokaliai fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar nežymiai hiperplastišku epiteliu; be naviko.   3(1). NAVIKAS(du izoliuoti 4 mm atstumu nutolę naviko židiniai: I - 14 mm; II - 4 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės (~15%), kribriforminės, trabekulinės, nedidelės lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, negausia ar vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki 9/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Negausi perinavikinė limfocitinė infiltracija.     APLINKA: šalia naviko - solidiniai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su apokrinės metaplazijos zonomis.   SEKTORIAUS REZEKCIJOS KRAŠTAS: fibrozuotas brandus riebalinis audinys; be naviko.   4(3). "Kairės pažasties limfmazgiai"(10): šešiuose (6) limfmazgiuose aukščiau, punkte Nr.3, aprašyto naviko metastazės, iki 45 mm skersmens, su ekstranodaliniu plitimu.. nan
answer:  1

  9%|▉         | 62/661 [00:58<09:44,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 55% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacijos FISH tyrimo rezultatas teigiamas (žr. molekulinio tyrimo aprašymą ir pastabas).  Ki67+ 25%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 7/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 55% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos ir netolygus stiprus membranos nusidažymas 60% navik
answer:  1

 10%|▉         | 63/661 [00:58<09:08,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 15 mm; II - 12 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Krūties audinį infiltruoja duktalinės struktūros, netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko lą
answer:  1

 10%|▉         | 64/661 [00:59<08:59,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 18 G automatine biopsine adata punktuotas ~4x5 mm dydžio neaiškių ribų deformacijos židinys (atitinkantis MR tyrime BIRADS 4 k/m kaupiantį židinį) dešiniojoje krūtyje ties 12-1 val. vidurinėje/ periferinėje dalyje, paimti trys biopsiniai stulpeliai histologijai (I buteliukas).   2 ėminio aprašas: 2. 18 G automatine biopsine adata punktuotas ~7x9 mm dydžio neaiškių ribų deformacijos židinys (atitinkantis MR tyrime BIRADS 4 k/m kaupiantį židinį) dešiniojoje krūtyje ties 1 val. vidurinėje/ periferinėje dalyje, paimti keturi biopsiniai stulpeliai histologijai (II buteliukas).. 1. 3 biopsiniai stulpeliai: I - 7 mm; II - 10 mm; III - 12 mm.  2. 4 biopsiniai stulpeliai: I - 7 mm; II - 9 mm; III - 6 mm; IV - 6 mm.. N1: Krūties audinio fibrozė.  N2: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.. N1: Krūties audinio fibrozė, pavieniai normalios struktūros kanaliukai.  N2: Krūties audinį infiltruoja pabiros ląstelės ir juostos iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 2%.
answer:  0

 10%|▉         | 65/661 [01:00<08:32,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 10 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros, negausūs smulkūs kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 8
answer:  0

 10%|▉         | 66/661 [01:01<08:13,  1.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. Krūties audinį infiltruoja smulkios duktalinės struktūros, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 12%
answer:  0

 10%|█         | 67/661 [01:01<08:02,  1.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 4 biopsiniai stulpeliai. 4 biopsiniai stulpeliai: I - 7 mm; II - 6 mm; III - 4 mm, IV - 3 mm.. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 90% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 1%.. Bioptatuose (4/4) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos trabekulėmis ir pabirai besidėstančių ląstelių negausia šviesia eozinofiliška citoplazma, nežymiai polimorfiškais, vidutinio kalibro, ovaliais branduoliais; mitozių 1/10 DPRL. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 90%.  HER2: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67 proliferacinis aktyvumas 1%.  E-cadherin(+) trūkinėjanti membr. r-ja <5%.
answer:  0

 10%|█         | 68/661 [01:02<07:56,  1.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 14 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 8%. Karštame taške 15%.. Krūties audinį 2-se bioptatuose infiltruoja iki 9 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 3/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 8% naviko ląstelių. Karštame taške 15%.  Progesterono receptoriai: stipri (+++) r
answer:  0

 10%|█         | 69/661 [01:03<08:25,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, planinis.  2. pjūvio kraštai, planinis.   3. sarginiai l/m, planinis.   4. sektorius, planinis.. 1. Riebalinio audinio fragmentas 2,2x2x1,2 cm. v/m  2. Riebalinio audinio fragmentas 2x1,5x1,2 cm. v/m  3. Riebalinio audinio fragmentas 3x2,5x1,5 cm. Rasti 3 limfmazgiai iki 2,2 cm.   4. Krūties sektorius 7,5x3,5x3 cm su oda 7x2 cm. Odoje rusvas, gruoblėtas, elastingas, kiek iškilęs darinys 1,5x0,3x0,1 cm, nuo odos rezekcijos krašto nutolęs 0,1 cm. Krūties audinyje balkšvas, standus, gerai ribotas navikas 18x15x11 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 0,8 cm, nuo odos darinio - 1,3 cm.. 1. Krūties fibrocistiniai pokyčiai.  2. Nežymi fokalinė krūties audinio fibrozė.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,8 cm) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės naviko invazijos nėra). Seborėjinė keratozė.     Estrogenų receptoriai: stipri (+++)  reakcija, 90% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 15%.. 1. Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2. Krūties audinyje - negausūs smulkūs fibrozės židiniai su smulkiais kanaliukais, išklotais dvisluoksniu epiteliu.  3. Nežymi sinusų histiocitozė trijuose (3) limfmazgiuose.  4. Krūties audinyje - navikas: solidines naviko struktūras formuoja ląstelės su gan gausia eozinofiline citoplazma, vidutinio kalibro ar kiek stambesniais apvalios formos netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 27 / 10 DPRL. Krūties odoje - epidermio darinys, išklotas hiperplastišku, akantotišku, vietomis papiliarizuotu, hiperkeratotišku daugiasluoksniu plokščiu epiteliu, suformuotu iš bazaloidinių ląstelių su raginėmis cistomis, bazalinio epidermio sluoksnio hiperpigmentacija.. 4. Navikas (10 blokas):  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 3% naviko ląstelių.
answer:  1

 11%|█         | 70/661 [01:04<08:41,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas,   3(2)- Kairės pažasties sarginiai limfmazgiai, skubu  4(3)- Kairės krūties sektorius, planinis. 4. Krūties sektorius 7x4,5x5 cm su oda 6,5x4,5 cm, su įdubusiu speneliu. Krūties audinyje, pilkšvas standus neaiškių ribų navikas 18x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 2 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi blogai diferencijuota (G3; 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(20 mm) N(sn)0(0/4 l/m), LVI-2(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS)(solidinė, kribriforminė, komedo).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 4 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.  4. SPENELIS: be patologijos.  NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai 20 mm), suformuotas fibrozuotoje stromoje ir tarp lipocitų infiltratyviai plintančių solidinių, lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 39/10 DPRL. Šalia yra dilatuotų kanaliukų su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais, fokaliai su komedo nekroze centre; negausūs kanaliukai su apokrinine metaplazija.. 4. Navikas (16 blokas):  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  D2-40+ ir CD34+ endotelizuotose ertmėse naviko plitimo neidentifikuota.
answer:  0

 11%|█         | 71/661 [01:05<08:49,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). Sektoriaus kraštai.   2(N2). Sektoriaus kraštai.   3(N3). Sarginiai l/n.   4(N4). Deš.krūties sektorius su naviku.. 4. Krūties sektorius 9x5,7x4,5 cm su odos lopu 7x2 cm, žymėtas viela. Pjūvyje, vielos projekcijoje balkšvas, kiek neaiškių ribų navikas 18x18x10 mm, nuo artimiausio rezekcijos krašto nutolęs 0,7 cm, nuo odos - 1,6 cm.. 1. Krūties fibrocistiniai pokyčiai: stulpinis epitelio pokytis, paprasta intraduktalinė hiperplazija.   2. Krūties audinys be patologinių pokyčių.   3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2/ 6 b. pagal Nottingham s.) duktalinė karcinoma, suminis Nr. 1 - 4 pTNM:   pT1c (18 mm) pN0(sn) (0/3 l/m), LVI0 (limfovaskulinės naviko invazijos neidentifikuota).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-19395, žr. pastabą.. 1. Krūties audinyje - minimali stromos fibrozė, yra latakų su stulpiniu epitelio pokyčiu, keli latakai su ryškia intraduktaline epitelio ir mioepitelinių ląstelių hiperplazija.   2. Krūties audinyje - minimali stromos fibrozė.   3. Limfmazgiai (3) su tušuota architektūra, negausiais pirminiais folikulais, makrofagų reakcija parakortekse, nežymia stromos fibroze.  4. Krūties audinyje - infiltratyviai plintantis navikas, formuojamas solidinių, trabekulinių, negausių kompleksinių ar blogai suformuotų liaukinių struktūrų, sudarytų iš vidutinio dydžio stulpinių bei poligonalinių ląstelių gausia šviesiai eozinofiliška citoplazma, vidutiniškai polimorfiškais, kiek nelygaus kontūro ovoidiniais branduoliais su vezikulizuotu chromatinu ir smulkiomis ryškiomis nukleolėmis. Navike iki 3 mitozių/ 10 DPRL.. nan
answer:  0

 11%|█         | 72/661 [01:06<08:31,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 8 mm.. PAPILDYTA  Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 1%.. Bioptatuose (2/2) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, nežymiai polimorfiškais, vidutinio kalibro, ovalaus kontūro branduoliais; mitozių 1/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: neigiama reakcija.  HER2: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67 proliferacinis aktyvumas 1%.  E-cadherin(+++) membr. r-ja 100%.
answer:  0

 11%|█         | 73/661 [01:07<08:27,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta dešinė krūtis ir dešinės pažasties limfmazgiai. Krūtis, 1232 g svorio, 23x16,5x5 cm. Spenelis įtrauktas. Lateralinių kvadrantų riboje - pilkšvas standus navikas 56x43x35 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, peraugantis ir išopėjęs odoje. Pažasties narveliena 8x7x3,5 cm. Rasti 12 limfmazgių iki 1,6 cm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham sistemą) duktalinė karcinoma, pT4b (56 mm, odoje išopėjęs navikas) pN2a (4/11 l/m su mts iki 10mm) LVI-0 (limfovaskulinė invazija neidentifikuota).  Radikalus pašalinimas.. Krūties audinyje - desmoplastiškoje stromoje, infiltratyviu frontu plintantis, odoje išopėjęs navikas, suformuotas lizdų, solidinių kompleksų, trabekulių, pavienių tubulių (<10%).  Naviko ląstelės su vidutinio gausumo, eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar ovoidiškais, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių navike iki 14/10DPRL.  Aplinkiniame krūties audinyje latakai su židinine apokrinine metaplazija.   4/11 limfmazgių - aukščiau aprašyto naviko metastazės iki 10 mm.. nan
answer:  0

 11%|█         | 74/661 [01:08<09:17,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2) - dešinės pažasties sarginis limfmazgis  - skubus tyrimas dviejose iš trijų limfmazgių metastazės  2(N1) - pašalinta dešinė krūtis - planinis tyrimas. 2(1). Krūtis 1835 gramų svorio, 30x22x7,5 cm, žymėtas viela. Vielos projekcijoje, lateralinių kvadrantų riboje, balkšvas, standus, neaiškių ribų navikas 3,4x2x1,3 cm, nuo giliojo rezekcijos krašto nutolęs 3 cm, nuo odos - 2,5 cm. Viršutinių kvadrantų riboje balkšvas, standus, gana aiškių ribų darinys 1,5x1x0,8 cm, nuo giliojo rezekcijos krašto nutolęs 2,5 cm, nuo odos - 5 cm.. 1(ekstra). "Dešinės pažasties sarginiai limfmazgiai":   lobulinės karcinomos metastazė limfmazgiuose (mts 2/3 l/m; iki 18 mm skersmens).    2(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT2(m) (navikai: I - 34 mm; II - 7 mm) N1a(sn) (mts 2/3 l/m; iki 18 mm skersmens),    LVI-2 (limfovaskulinė invazija smulkiose šakose). Perineurinis plitimas.   Imunofenotipas:   Estrogenų receptoriai: vidutinė-stipri (++/+++) reakcija, 99% naviko ląstelių.  Progesterono receptoriai: vidutinė-stipri (++/+++) reakcija, 99% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%. Karštame taške 10%.    Krūties lobulinė intraepitelinė neoplazija (LCIS).  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Krūties rezekcijos kraštas be naviko.. 1(ekstra). "Dešinės pažasties sarginiai limfmazgiai"(3): dviejuose (2) limfmazgiuose žemiau, punkte Nr.2, aprašyto naviko metastazės, iki 18 mm skersmens, su ekstranodaliniu plitimu.   2(1). SPENELIS: normalios histologinės struktūros.   NAVIKAS (du navikai: I - 34 mm; II - 7 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", solidinės naviko struktūros, suformuotos mažai kohezyvių vidutiniškai ar ryškiai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 7/10 DPRL.   Limfovaskulinė naviko invazija smulkiose šakose. Perineurinis naviko plitimas. Fokaliai negausi perinavikinė limfocitinė infiltracija, fibrozės židiniai su hemosiderofagais, fibroadenomatoziniai stromos pokyčiai, pavieniai mikrokalcifikatai.   APLINKA: zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais. Šalia II naviko - kribriforminiai intraduktaliniai polimorfiškų kohezyvių naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   GILUSIS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 2(1). Navikas (blokas 25):  Estrogenų receptoriai: vidutinė-stipri (++/+++) reakcija, 99% naviko ląstelių branduolių.  Progesterono receptoriai: vidutinė-stipri (++/+++) reakcija, 99% naviko ląstelių branduolių.   HER2: silpna (+) necirkuliari reakcija, 4
answer:  30

 11%|█▏        | 75/661 [01:09<08:41,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis iš 16 mm dominuojančio darinio. Biopsinis stulpelis 13 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 12
answer:  1

 11%|█▏        | 76/661 [01:09<08:17,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsiniai stulpeliai. Biopsinis stulpelis 13 mm ilgio.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 85%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 12/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 85%.
answer:  1

 12%|█▏        | 77/661 [01:10<08:25,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2 - deš. pažasties sarginis l/m   -  skubus tyrimas dviejose iš trijų limfmazgiu markometastazės  2 ėminio aprašas: N1 - pašalinta deš krūtis - planinis ištyrimas. 2. Krūtis 427 g svorio, 18x15x4 cm. Krūties audinyje, viršutinių lateraliniame kvadrante - balkšvas, standus, neaiškių ribų navikas 34x22x12 mm, nuo odos nutolęs 1,5 cm, nuo artimiausio rezekcijos krašto - 0,6 cm. 1,9 cm atstumu nuo naviko balkšvas, standus židinys 0,5x0,4x0,3 cm.. 1(ekstra). Duktalinės karcinomos metastazės limfmazgiuose (3/3 l/m iki 7 mm).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(m)(34 mm ir 4 mm navikai) pN1a(sn)(3/3 l/m MTS iki 7 mm) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija).(DCIS/DIN3 DIN1 DIN2, kribriforminis ir papilinis tipai).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis iki 20%.. 1(ekstra). 3/3 limfmazgių aprašyto naviko metastazės iki 7 mm.  2. Krūtyje - navikas (34 mm ir 4 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, trabekulinėmis struktūromis, lizdais, grandinėlėmis ir pabirai besidėstančių ląstelių negausia - vidutinio gausumo blyškia eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais - apvaliais, vezikulizuotais branduoliais ryškiomis nukleolėmis; mitozių 3/10 DPRL. Limfovaskulinė invazija.. NAvikas (16 blokas): E-cadherin(+++) membr. r-ja 100%; p120_catenin(+++) membr. r-ja 100%;
answer:  0

 12%|█▏        | 78/661 [01:11<08:51,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinia kraštas, skubu  3(2). Kairės pažasties sarginiai limfmazgiai, skubu  4(3). Kairės krūties kvadrantas, planinis. 4. Krūties sektorius 20x10,5x7,5 cm su odos lopu 16,5x7 cm, su speneliu, žymėtas vielomis. I vielos projekcijoje pilkšvas standus darinys 10x6x5 mm, nuo giliojo rezekcijos krašto nutolęs 3 cm, nuo odos - 3,7 cm. Atstumas tarp vielų 8 cm.  II vielos projekcijoje neaiškių ribų darinys 16x6x6 mm, nuo odos rezekcijos krašto nutolęs 2 cm, nuo giliojo - 2,6 cm.  Spenelio projekcijoje pilkšvas, skiltėtas navikas 40x35x30 mm, nuo giliojo rezekcijos krašto nutolęs 3 cm, infiltruoja odą.  Dariniai sudėti visi. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (4 l/m).    4. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(m)(16 mm, 10 mm navikai) pN0(sn)(0/4 l/m) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija). Aukšto laipsnio duktalinė karcinoma in situ (DIN3 solidinis tipas).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 95% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 70% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 25%.. 1(1a). Krūties audinyje - fibrozės zonos su fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu.  2(1b). Krūties audinyje - fibrozės zonos su fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu. 2,35  3(2). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (16 mm, 10 mm židiniai) ekspansyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais - stambiais, ryškiai polimorfiškais,  nereguliaraus kontūro ir ovaliais branduoliais ryškiomis nukleolėmis; mitozių 13/10 DPRL. Limfovaskulinė invazija.  Greta dilatuoti kanaliukai su solidiniais proliferatais iš analogiškų navikui ląstelių.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 95%.  Progesterono receptoriai: (+++)(brand. r-ja) 70%.  HER2: nusidažiusių membranų nėra.  Ki67 proliferacinis aktyvums 25%.  CK14(-); Synaptophysin+ <1%.
answer:  1

 12%|█▏        | 79/661 [01:12<08:24,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 14 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 60%.. Bioptate - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis lizdais ir trabekulėmis besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 5/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 95%.  HER2: nusidažiusių naviko ląstelių nėra.  Ki67 proliferacinis aktyvumas 60%.
answer:  0

 12%|█▏        | 80/661 [01:13<08:05,  1.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 40%.. Krūties audinį infiltruoja smulkūs netaisyklingi solidiniai kompleksai ir trumpos juostos iš vidutiniškai, vietomis ryškiai, polimorfiškų ląstelių, mitozių neidentifikuota.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: vidutinis dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+
answer:  40

 12%|█▏        | 81/661 [01:14<08:18,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. Pjūvio kraštai, ekstra.   3. Sarginiai l/m, ekstra.   4. Sektorius, planinis.. 4. Krūties sektorius 9,5x7x3,5 cm su oda 7x2,5 cm. Krūties audinys fibrozuotas visame plote, fibrozėje gelsvas standus, neaiškių ribų navikas 30x25x20 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 1 cm.. 1. Pjūvio kraštai - sklerozuojanti adenozė su gestacijai/laktacijai būdingais pokyčiais.  2. Pjūvio kraštai - sklerozuojanti adenozė su gestacijai/laktacijai būdingais pokyčiais.    3. Sarginiai l/m - limfmazgiai (3) be patologinių pokyčių.    4. Krūties sektorius.   Blogai diferencijuota krūties invazinė duktalinė  karcinoma(su medulinės karcinomos struktūra ir gausiais naviką infiltruojančiais limfocitais);   (G3, 9 balai pgl Nottingham),   pT2 pLVI-0 pN0 pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: reakcija neigiama.  Progesterono receptoriai: vidutinis branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 60%.    Sklerozuojanti adenozė.. 1. Pjūvio kraštai - Kompaktiška liaukų hiperplazija fibrozuotoje stromoje, sudarytų iš sekrecinio tipo epitelinio, mioepitelinio ląstelių sluoksnio ir bazinės membranos.     2. Pjūvio kraštai - Kompaktiška liaukų hiperplazija fibrozuotoje stromoje, sudarytų iš sekrecinio tipo epitelinio, mioepitelinio ląstelių sluoksnio ir bazinės membranos.     3. Sarginiai l/m - limfmazgiai (3) be patologinių pokyčių.    4. Krūties sektorius. Krūties audinį infiltruoja dalinai riboto, bet netaisyklingų kraštų naviko solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių >35/10 DPRL; gausi intranavikinė limfocitų infiltracija. Navikas 1 mm nuo artimiausio giliojo krašto. Plitimo kraujagyslėse nestebima.. nan
answer:  0

 12%|█▏        | 82/661 [01:15<08:52,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2: dešinės pažasties sarginis limfmazgis - skubus tyrimas 2l/m be naviko  2 ėminio aprašas: N1: pašalinta dešinė krūtis - planinis tyrimas. 2. Krūtis gramų 363 svorio, 17,5x12x3 cm. Apatiniame lateraliniame kvadrante, balkšvas, standus, neaiškių ribų navikas 1,2x1x0,8 cm (sudėtas visas), nuo odos nutolęs 2,5 cm, nuo giliojo rezekcijos krašto - 0,5 cm. Odoje randas 6,5 cm ilgio.. 1(2, ekstra). "Dešinės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).   2(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 12 mm) N0(sn) (0/2 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS). Randiniai pokyčiai odoje.   Gilusis krūties rezekcijos kraštas be naviko.. 1(2, ekstra). "Dešinės pažasties sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2(1). SPENELIS: normalios histologinės struktūros.   RANDAS: dermoje ryškios kolageninės fibrozės židinys su vertikalai orientuotomis, kiek dilatuotomis kraujagyslėmis.   NAVIKAS (mikroskopiškai bent 11 mm skersmens): krūties audinyje, ryškiai fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retos duktalinės ir kribriforminės bei dominuojančios trabekulinės ir nedidelės lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio kiek nelygaus kontūro ovaliais/apvaliais branduoliais su retomis smulkiomis nukleolėmis; mitozių iki 2/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija, pavieniai hemosiderofagai. Pavieniai mikrokalcifikatai.   APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   GILUSIS REZEKCIJOS KRAŠTAS: fibrozuotas brandžių lipocitų suformuotas audinys; be naviko.. 2(1). Navikas (blokas 12):  HER2: silpna (+) necirkuliari reakcija, 15% naviko ląstelių membranoje.
answer:  1

 13%|█▎        | 83/661 [01:16<09:16,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštas, ekstra.  2. pjūvio kraštas, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 11,5x4,5x5,5 cm, su odos fragmentu 10,5x2,5 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 10x10x7 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 3 cm.. 1(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija); be naviko.   2(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 9 mm) N0(sn) (0/3 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis tipas).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).. 1(ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, apokrinės metaplazijos zonomis; be naviko.   2(ekstra). "Kraštai": vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS (mikroskopiškai 9 mm skersmens): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės, kribriforminės, trabekulinės, nedidelės lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomisnukleolėmis; mitozių iki 6/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija, pavieniai hemosiderofagai. Pavieniai mikrokalcifikatai.  APLINKA: šalia naviko - kribriforminiai intraduktaliniai naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 4. Navikas (blokas 36):  HER2: silpna (+) necirkuliari reakcija, 1% naviko ląstelių membranoje.
answer:  0

 13%|█▎        | 84/661 [01:17<08:39,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Deš. krūtis su limfmazgiais, planinis. Krūtis 1100 g svorio, 25x20x4  cm, spenelis įtrauktas, su pažasties narveliena 13x9x4 cm. Krūties audinyje pilkšvas standus netaisyklingų kontūrų navikas 2,8x1,7x2,2 cm, nuo artimiausio rezekcijos krašto(dažyta mėlynu tušu) 2,5 cm, nuo odos 1,5 cm. Pažasties narvelienoje rasta 16 limfmazgių, didžiausias 3,4 cm.. Krūties mikropapilinė karcinoma (G2, 6 balai pgl Nottingham) pT2(28mm); pN2a (iš 16 l/m).. Krūties audinyje 28mm navikas: smulkūs solidiniai kompleksai, vietomis su spindžiu centre ir su stromos prašviesėjimu aplink, sudaryti iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.  Iš rastų 16 limfmazgių 8 su metastazėmis iki 34mm.  Rezkecijos kraštas be naviko.. nan
answer:  0

 13%|█▎        | 85/661 [01:17<08:20,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 15 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 35%, vietomis iki 60%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 20/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  Ki67+ 35%,
answer:  1

 13%|█▎        | 86/661 [01:18<08:05,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 8 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 80%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 20/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 95% naviko ląstelių.  Ki67+ 80%.
answer:  1

 13%|█▎        | 87/661 [01:19<07:55,  1.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 14 mm; II - 14 mm; III - 10 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%, fokaliai iki 20%.. Krūties audinį infiltruoja smulkūs kribroziniai/solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 13%|█▎        | 88/661 [01:20<07:44,  1.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 8 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20%.. Krūties audinį infiltruoja netaisyklingi kribroziniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: vidutinis dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 20%.
answer:  0

 13%|█▎        | 89/661 [01:21<08:29,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.(N2a). kraštai - extra;  2(N2b). kraštai - extra.  3(N1). Pašalintas kairės krūties kvadrantas ir kairės pažasties limfmazgiai.-planinis. 3. Krūties sektorius 12x7x5,5 cm su oda 11,5x3,5 cm. Krūties audinyje, balkšvas standus, neaiškių ribų I navikas 18x14x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 4,5 cm. Šalia I naviko, balkšvas standus, aiškių ribų II navikas 12x10x8 cm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos 4 cm, nuo I naviko 0,1 cm. Nuo I naviko 0,3 cm atstumu, balkšvas, standus, aiškių ribų III navikas 10x8x8 cm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos 3 cm. Bendras navikų dydis 25x23x20 mm. Rastas vienas intramamarinis limfmazgis, 0,5 cm. Atskirai riebalinio audinio fragmentai, bendras dydis 7x4x,5x2,5 cm. Rasti 9 limfmazgiai iki 3,3 cm.. 1(2a)(Extra). Krūties audinys.  2(2b)(Extra). Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT(m)1c(3 naviko židiniai: 15 mm, 13 mm ir 9 mm) N2a(mts 5/10 l/m; didžiausia 33 mm, su ekstranodaliniu plitimu), LVI-2(limfovaskulinė invazija). Didžiausias (I) navikas siekia markiruotą rezekcijos kraštą.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Androgenų receptoriai: vidutinis branduolių nusidažymas 70% naviko ląstelių.  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).. 1(2a)(Extra). Krūties audinyje, neryškiai fibrozuotoje stromoje - pavieniai smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(2b)(Extra). Krūties audinyje, neryškiai fibrozuotoje stromoje - pavieniai smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(1). NAVIKAS: krūties audinyje - 3 identiškos histologinės struktūros riboti navikai (mikroskopiškai 15 mm, 13 mm ir 9 mm), suformuotas fibrozuotoje stromoje plintančių fokaliai besiliejančių vidutinių ir smulkių lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo "tamsia" eozinofiliška citoplazma, vidutinio kalibro, apvaliais/ovaliais, kiek polimorfiškais, dalis su aiškia nukleole branduoliais. Mitozių iki 9/10 DPRL. Šalia naviko kiek dilatuoti kanaliukai su solidiniais ir negausiais kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais, fokaliai su centrine komedo nekroze.  LIMFMAZGIAI: 5 iš 10 limfmazgių - naviko metastazės (didžiausia 33 mm, su ekstranodaliniu plitimu). Limfovaskulinė invazija šalia.. 1. Navikas (7 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Androgenų receptoriai: vidutinis branduolių nusidažymas 70% naviko ląstelių.  Synaptophysin(-).
answer:  1

 14%|█▎        | 90/661 [01:22<08:24,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N3). Sarg. l/m - skubus - be naviko  2(N2a). kraštai - skubus - be naviko  3(N2b). kraštai - skubus - be naviko  4(N1)- sektorius - planinis patologinis tyrimas. 4. Krūties sektorius 8x4,5x5 cm su odos lopu 6,5x2,5 cm ir speneliu. Spenelio projekcijoje pilkšvas, standus neaiškių ribų navikas 25x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 2 cm, infiltruoja spenelį.. 1. Krūties audinys.  2. Krūties audinys.   3. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi, gerai diferencijuota (G1, 4 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 25mm) pN0(sn)(0/1 l/m); LVI-0 (Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-19397 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.". 1. Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  2. Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  3. Vienas(1) limfmazgis be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4. Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas duktalinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais; navike - iki 2 mitozių/10 DPRL; naviko plitimas dermoje (spenelio projekcijoje).. nan
answer:  0

 14%|█▍        | 91/661 [01:23<08:44,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2). Deš. pažasties sarginiai limfmazgiai, skubu  4(3). Deš. krūties sektorius, planinis. 3. Krūties sektorius 5x4x2,2 cm, be odos, žymėtas viela. Vielos projekcijoje pilkšvas, neaiškių ribų židinys 6x5x5 mm, nuo giliojo rezekcijos krašto nutolęs 1,5 cm. (židinys sudėtas visas). 1. Krūties atipinė lobulinė hiperplazija.   2. Krūties fibrocistiniai pokyčiai.    3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2/ 6 b. pagal Nottingham s.) duktalinė karcinoma,   pT1b (6 mm) pN0(sn) (0/3 l/m), LVI0 (limfovaskulinės naviko invazijos neidentifikuota).   Imunofenotipas:   estrogenų receptorių (ER) reakcija teigiama: stiprus/ vidutinis branduolių nusidažymas 100% naviko ląstelių,   progesterono receptorių (PR) reakcija teigiama: stiprus/ vidutinis branduolių nusidažymas 10% naviko ląstelių,   HER2 reakcija neigiama (0),   Ki67 prolif. indeksas ~5%.   Žemo laipsnio duktalinė karcinoma in situ (DCIS).. 1. Krūties audinys su labai negausiais smulkiais normalios struktūros kanaliukais ir keliais smulkiais kanaliukais su "intraepitelinėmis" diskohezyviomis ląstelėmis eozinofiliška citoplazma, ekscentriškais, nežymiai polimorfiškais branduoliais.   2. Krūties audinys netolygiai fibrozuota stroma, su negausiais cistiškai pakitusiais ir smulkiais latakais.   3. Limfmazgiai(3) su negausiais antriniais folikulais, sinusų histiocitoze, be naviko plitimo.   4. Krūties audinyje - infiltratyviai plintantis navikas, formuojamas negausių tubulinių, kompleksinių ar blogai suformuotų liaukinių bei smulkių solidinių struktūrų, sudarytų iš vidutinio dydžio stulpinių bei poligonalinių ląstelių gausia šviesiai eozinofiliška citoplazma, nežymiai ar vidutiniškai polimorfiškais, kiek nelygaus kontūro ovoidiniais branduoliais su smulkiomis ryškiomis nukleolėmis. Navike iki 2 mitozių/ 10 DPRL.   Naviko periferijoje - grupės latakų su intraduktaliniais kribriforminiais proliferatais iš duktalinio tipo stambių ląstelių nežymiai polimorfiškais branduoliais.. 1. ALH ląstelės e-cadherin(-).   4. Navikas (15 blokas):   ER: stiprus/ vidutinis branduolių nusidažymas 100% naviko ląstelių,   PR: stiprus/ vidutinis branduolių nusidažymas 10% naviko ląstelių,   HER2: silpnas dalies membranos nusidažymas <10% naviko lą
answer:  1

 14%|█▍        | 92/661 [01:24<08:50,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštas  - skubus tyrimas  2 ėminio aprašas: N2b kraštas  - skubus tyrimas  3 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas  4 ėminio aprašas: N1: pašalintas dešinės krūties kvadrantas su vielute - planinis tyrimas  5 ėminio aprašas: N4: papildomas kraštas - planinis tyrimas. 4. Krūties sektorius 3x1x6,5 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 6x4x4 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,5 cm.  5. Riebalinio audinio fragmentas 2x1,3x0,4 cm. v/m. 1(N2a) kraštas - riebalinis audinys be patologinių pokyčių.  2 (N2b) kraštas - riebalinis audinys be patologinių pokyčių.    3 (N3) dešinės pažasties sarginis limfmazgis: limfmazgiai(3) be patologinių pokyčių.    4 (N1) - dešinės krūties kvadrantas.   Invazinė lobulinė karcinoma  (G1; 5 b. pgl. Nottingham sist.);  pT1b pN0 pLVI-0 pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    5 (N4) - papildomas kraštas. Riebalinio audinio fragmentas be patologinių pokyčių.. 1(N2a) kraštas - riebalinis audinys be patologinių pokyčių.  2 (N2b) kraštas - riebalinis audinys be patologinių pokyčių.  3 (N3) dešinės pažasties sarginis limfmazgis: limfmazgiai(3) be patologinių pokyčių.  4 (N1) - dešinės krūties kvadrantas. Riebalinį audinį infiltruoja iki 6,5 mm :   - juostos ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais negausioje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.  5 (N4) - papildomas kraštas. Riebalinio audinio fragmentas be patologinių pokyčių.. nan
answer:  0

 14%|█▍        | 93/661 [01:24<08:15,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Pašalinta kairė krūtis planinis tyrimas. Krūtis, 454 g svorio, 14,5x10,5x6 cm su raumens fragmentu 6x3x1 cm, spenelis įtrauktas. Raumens projekcijoje pilkšvas, standus, aiškių ribų navikas 8x5,5x4,5 cm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, išopėjęs odoje.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b (8cm navikas; išopėjimas).. Krūties audinyje išopėjęs 8cm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 15/10 DPRL.  Operacinis pjūvis be naviko.. nan
answer:  0

 14%|█▍        | 94/661 [01:25<07:56,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 10 mm; II - 13 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%, vietomis 15%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 4%, vietomis
answer:  0

 14%|█▍        | 95/661 [01:26<08:35,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 11,5x6,5x4 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 18x12x11 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos - 2,8 cm. Šalia naviko fibrozės zona 5,5x2,5x1,5 cm.. 1(kraštai). Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.     2(kraštai). Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.     3(sarginiai l/m). Duktalinės karcinomos mikrometastazės (iki 1 mm skersmens) 1-me/3 limfmazgių.    4(krūties sektorius).   Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT1c (18 mm) pN1mi(1/3 l/m iki 1mm) pLVI-2 (limfovaskulinė invazija smulkiose gyslose) pR0(radikalus pašalinimas).  Naviko imunotipas nustatytas priešoperaciniame biopsijos tyrime (žr. pastabą).   Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis, kribriforminis, komedo tipai).  Krūties fibrocistiniai pokyčiai:   paprastoji intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija. Adenozė.. 1(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais ar cistiškai dilatuotais kanaliukais, klotais dvisluoksniu ar hiperplastišku epiteliu, su židinine apokrinine metaplazija.  2(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais ar cistiškai dilatuotais kanaliukais, klotais dvisluoksniu ar hiperplastišku epiteliu, su židinine apokrinine metaplazija.  3(ekstra). 1/3 limfmazgių trys žemiau aprašyto naviko židiniai iki 1 mm skersmens;   4. NAVIKAS. Krūties audinyje - desmoplastiškoje stromoje, infiltratyviu frontu plintantis navikas, suformuotas lizdų, trabekulių, kribriforminių struktūrų ir tubulių (<10 %). Naviko ląstelės su negausia ar vidutinio gausumo, amfofiliška citoplazma, vidutinio kalibro ar stambiais, apvaliais ar ovoidiškais, vesikuolizuotais, ryškiai polimorfiškais branduoliais su aiškiomis nukleolėmis. Mitozių navike iki 9/10DPRL.  Navikas nuo sektoriaus rezekcijos krašto nutolęs 1,5 mm. Naviko plitimas endotelizuotuose spindžiuose.  Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių, siekiantys rezekcijos kraštą. Stromoje yra  zonų su cholesterolio kristalais, apsuptais makrofagų ir svetimkūnio tipo daugiabranduolių gigantinių ląstelių.  FIBROZĖ. Krūties audinys su fibrozės zonomis, smulkiomis ar stambiomis lobulėmis su smulkiais latakais, klotais dvisluoksniu epiteliu. Yra latakų su cistine dilatacija, apokrinine metaplazija, stulpinių ląstelių pokyčiu su apikaline sekrecija, įprastine duktaline hiperplazija.. nan
answer:  0

 15%|█▍        | 96/661 [01:27<08:34,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu   3(2). Kairės pažasties sarginiai limfmazgiai, skubu  4(3). Kairės krūties sektorius, planinis. 4. Krūties sektorius 9x4,5x4 cm su oda 8x3 cm. Krūties audinys visame plote fibrozuotas. Fibrozėje - rusvas, standus, neaiškių ribų navikas 17x17x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1,6 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi blogai diferencijuota (G3; 8 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 17 mm), pN0(sn)(0/2), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).. 1. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.   2. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.   3. Du limfmazgiai (2 l/m) su sinusų histiocitoze.  4. Krūties audinyje navikas (17 mm mairoskopiškai), infiltratyviu augimo frontu, suformuotas solidinių, trabekulių ir negausių kribriforminių struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, polimorfiškais, hiperchromiškais branduoliais su ryškiais branduolėliais. Mitozių navike 30/10DPRL. Limfovaskulinė naviko invazija (LVI2). Navikas nuo rezekcijos krašto nutolęs per 4 mm. Krūties audinyje greta naviko gausūs latakai užpildyti kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, hiperchromiškais, polimorfiškais branduoliais. Aplinkiame audinyje gausūs dilatuoti latakai, kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.. nan
answer:  0

 15%|█▍        | 97/661 [01:28<09:25,  1.00s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). Sarginiai l/n - extra.   2(N2). Deš.krūtis su navikais.. 2. Krūtis 585 gramų svorio, 19x10,5x4,5 cm. Krūties audinyje - du balkšvi standūs naviko židiniai:   - I - centrinėje dalyje, 9x8x7 mm dydžio, nuo odos nutolęs 3 cm, nuo giliojo rezekcijos krašto - 1,5 cm;   - II - medialiniame viršutiniame kvadrante, 12x11x7 mm dyžio, nuo I naviko nutolęs 2,5 cm, nuo odos - 2 cm, nuo artimiausio rezekcijos krašto - 0,2 cm. Navikai sudėti visi.. 1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     2. Krūties multižidininė vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) invazyvi duktalinė (12 mm) ir lobulinė (9 mm) karcinoma, SUMINIS TNM:   pT1c(m) (I - 9 mm; II - 12 mm) N0(sn) (0/3 l/m),    LVI-0 (limfovaskulinė invazija neidentifikuota).   Perineurinis plitimas. Kalcifikatai.     Imunofenotipas (šiame tyrime):  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 20% naviko ląstelių.   HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%. Karštame taške 10%.  ŽR. PASTABĄ.     Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis tipas).   Krūties lobulinė intraepitelinė neoplazija (LCIS).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   Gilusis rezekcijos kraštas normalios histologinės struktūros.. 1(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.     2. SPENELIS: reaktyvi epidermio akantozė su bazinio sl. hiperpigmentacija, nežymi perivaskulinė limfocitinė infiltracija papilinėje dermoje.      I NAVIKAS (9 mm židinys): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", solidinės naviko struktūros, suformuotos mažai kohezyvių vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 3/10 DPRL.     II NAVIKAS (12 mm židinys): krūties audinyje, fibrozuotoje-elastozinėje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retokos duktalinės, kribriforminės, gausesnės trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 5/10 DPRL. Ryškios centrinės fibrozės zonos. Pavieniai mikrokalcifikatai. Perineurinis naviko plitimas. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija.     APLINKA: nedidelės zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais. Šalia II naviko - keli kribriforminiai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su apokrinės metaplazijos zonomis.   GILUSIS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 2. I NAVIKAS (blokas 13):  E-Cadherin: (+/++)(trūkinėjanti membr.citopl.r-ja)20%;   p120-catenin: (+++)(citopl.r-ja)100%;   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.   Progesterono receptoriai: stipri (+++) reakcija
answer:  100

 15%|█▍        | 98/661 [01:29<09:37,  1.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštas - skubus tyrimas - be naviko   2 ėminio aprašas: N2b kraštas - skubus tyrimas - be naviko   3 ėminio aprašas: N1: pašalintas dešinės krūties kvadrantas su vielute - planinis tyrimas  4 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - planinis tyrimas - pašalinti apie 6-7 kietoki, limfmazgiai, su įtrauktais aplinkiniais audiniais. 3. Krūties sektorius 8x5x4 cm su odos lopu 7,5x3,5 cm ir raumens fragmentu 1,8x1,5x0,2 cm,  žymėtas viela. Krūties audinyje pilkšvas, standus, spikulinių kraštų navikas 2x1,8x1,8 cm, nuo rezekcijos krašto(dažytas mėlynai)-(ties raumens fragmentu) nutolęs mažiau nei 0,1 cm, nuo odos 1,5 cm.    4. Riebalinio audinio fragmentai, bendras dydis 6x6x2 cm su 9 limfmazgiais iki 1 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 20 mm), pN2a(6/9 l/m), LVI2 (limfovaskulinis plitimas). Perineurinis naviko plitimas. Navikas nuo skersaruožio raumens rezekcijos krašto nutolęs per 1,2 mm. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).   4. Krūties duktalinės karcinomos metastazės šešiuose limfmazgiuose (6/9 l/m, 9,5 mm, ekstranodalinis plitimas).. 1. Krūties audinyje židininė fibrozė su negausiais dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.   2. Krūties audinys su negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Krūties audinyje, hialinizuotoje stromoje plinta navikas (20 mm mikroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių, trabekulinių ir tubulinių (15%) naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su vidutiniškai polimorfiškais, hiperchromiškais branduoliais su pavieniais paryškėjusiais branduolėliais. Mitozių navike iki 12/10DPRL. Limfovaskulinis plitimas smulkiose limfagyslėse/kraujagyslėse(LVI2). pPrineurinis naviko plitimas. Navikas nuo skersaruožio raumens rezekcijos krašto nutolęs per 1,2 mm. Krūties audinyje dilatuoti kanaliukai užpildyti solidinių ir kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais.   4. Šešiuose limfmazgiuose iš devynių (6/9 l/m) aukščiau aprašyto naviko metastazės iki 9,5 mm su ekstranodaliniu plitimu.. Blokas 10:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 15%|█▍        | 99/661 [01:30<09:16,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 3 biopsiniai stulpeliai iš ploto su mkk dešinėje krūtyje  2 but. 2 biopsiniai stulpeliai iš spikulinės deformacijos židinio prasiplėtusiais latakais kairėje krūtyje, BI-RADS 4c. 1. 3 biopsiniai stulpeliai: I - 19 mm; II - 14 mm; III - 16 mm.  2. 2 biopsiniai stulpeliai: I - 10 mm; II - 12 mm.. Dešinė  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.  Aukšto laipsnio intraduktalinė karcinoma (DCIS; solidinė ir komedo).  --------------  Kairė  N2: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%, vietomis iki 30%.. Dešinė  N1: Krūties audinyje dilatuoti kanaliukai su intraduktaliniais solidiniais polimorfiškų ląstelių proliferatais, vietomis su centrinėmis nekrozėmis. Invazinis solidinis tokių pačių polimorfiškų ląstelių židinys stromoje, mitozių 2/10 DPRL.  --------------  Kairė  N2: Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi solidiniai/kribroziniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. nan
answer:  0

 15%|█▌        | 100/661 [01:31<08:40,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 7 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.. Bioptate fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos lizdais besidėstančių ląstelių negausia-vidutinio gausumo eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 2/10 DPRL.. Navikas:  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  HER2: silpnas dalies membranos nusidažymas pavienėse ląstelėse.  Ki67 proliferacinis aktyvumas 10%.
answer:  0

 15%|█▌        | 101/661 [01:32<09:27,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. Pjūvio kraštai, ekstra.   3. Sarginiai l/m, planinis.   4. Sektorius, planinis.. 3. Riebalinio audinio fragmentai, bendras dydis 5x3x1 cm. Rasti 3 limfmazgiai iki 2,5 cm.  4. Krūties sektorius 13x9x6 cm su oda 9x2 cm, žymėtas viela. Vielos projekcijoje, pjūvyje balkšvas, standus, neaiškių ribų navikas 0,6x0,5x0,5 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 1,3 cm, nuo odos – 3,5 cm.. 1(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); kalcifikatai; be naviko.   2(ekstra). "Kraštai": krūties lobulinė intraepitelinė neoplazija (LCIS).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 6 mm) N0(sn) (0/3 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    Krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: plokščias, papilinis tipai).  Krūties lobulinė intraepitelinė neoplazija (LCIS). Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).. 1(ekstra). "Kraštai": fokaliai nežymiai fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu; kalcifikatai; be naviko.   2(ekstra). "Kraštai": fokaliai nežymiai fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, apokrininės metaplazijos zonos. Zona su keletu dilatuotų lobulių, užpildytų nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais.   3(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retos duktalinės, dominuojančios trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo tamsoka citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki 5/10 DPRL. Pavieniai mikrokalcifikatai.   APLINKA: aplink naviką - keli dilatuoti kanaliukai su plokščiais ar kiek papiliarizuotais naviko ląstelių prolifetais; zonos su keletu dilatuotų lobulių, užpildytų nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).    SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 2(2b, ekstra). "Kraštai": E-Cadherin(-) intraduktaliniuose proliferatuose.  4. Navikas (34 blokas):   E-Cadherin(+) membraninė r-ja navike.   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stip
answer:  100

 15%|█▌        | 102/661 [01:33<08:55,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 3 biopsiniai stulpeliai iš cistinio solidinio darinio  praplėstų latakų fone   2 but. 3 biopsiniai stulpeliai iš  izoechogeninio solidinio darinio šalia. 1. 3 biopsiniai stulpeliai: I - 9 mm; II - 8 mm; III - 9 mm.  2. 3 biopsiniai stulpeliai: I - 6 mm; II - 8 mm; III - 6 mm.. N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus ar vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.  N2: Krūties fibroadenoma.. N1: Krūties audinį infiltruoja juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozės pavienės.  Aplink naviką gausūs intraduktaliniai monomorfiškų ECAD negatyvių ląstelių proliferacijos židiniai (LIN/LCIS židiniai).  N2: Krūties audinyje mazgas iš fibroblastų stromos, suspaustų kanaliukų, išklotų dvieiliu epiteliu.. Navikas  Estrogenų receptoriai: stiprus ar vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas xx% naviko ląste
answer:  1

 16%|█▌        | 103/661 [01:34<09:13,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1. Sarginiai l/n. - extra  N2. Kairė krūtis su naviku.. 2. Krūtis 836 gramų svorio, 20x16,5x8 cm, spenelio centras balkšvos spalvos. Krūties audinyje, viršutiniame lateraliniame kvadrante - pilkšvas, standus, neaiškių ribų navikas 22x20x18 mm, nuo odos nutolęs 1,9 cm, nuo giliojo rezekcijos krašto - 1 cm. Spenelio projekcijoje krūties audinys fibrozuotas 5x1,6 cm plote, kuris nuo giliojo rezekcijos krašto nutolęs 3 cm.. 1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).   2. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT2 (navikas 22 mm) N0(sn) (0/2 l/m), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcijos nėra (0).  Androgenų receptoriai: vidutinis branduolių nusidažymas 100% naviko ląstelių.    Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS: solidinis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta ir papilinė intraduktalinė hiperplazija, apokrininė metaplazija).   Krūties rezekcijos kraštas normalios histologinės struktūros.. 1(ekstra). "Sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2. SPENELIS: su nežymia reaktyvia epidermio hiperplazija ir akantoze, bazinio sluoksnio hiperpigmentacija.   NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta besiliejančios lizdinės ir solidinės, retos kribriforminės naviko struktūros, suformuotos ryškiai polimorfiškų ląstelių, vidutinio gausumo tamsoka citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro lobulizuotais ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki 30/10 DPRL. Naviko centre ryški fibrozė, hidropiniai pokyčiai, nedideli nekrozės židiniai. Limfovaskulinė naviko invazija smulkiose šakose.    APLINKA: šalia naviko - solidiniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su papilinių proliferatų formacija, apokrinės metaplazijos zonomis.   GILUSIS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 2. NAVIKAS (blokas 11):  HER2: reakcijos naviko ląstelių membranoje nėra.  Androgenų receptoriai: vidutinis branduolių nusidažymas 100% naviko ląstelių.  GATA3(+++)(brand.r-ja)100%; SOX-10(-); Synaptophysin(+++)(citopl.r-ja)3%.
answer:  1

 16%|█▌        | 104/661 [01:35<08:35,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: biopsijos iš kairės krūties. 2 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 8 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.. Krūties audinį infiltruoja susiliejantys kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  0

 16%|█▌        | 105/661 [01:36<08:44,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra;  2(2b). Kraštai - extra;  3. Dešinės krūties sarginis l/m - extra;  4(1). Dešinės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 12x6x4,5 cm su oda 11x1,5 cm, žymėtas dažais. Krūties audinyje, kvadrante - pilkšvas, standus, neaiškių ribų navikas 20x16x12 mm, pereinantis į fibrozę nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 0,2 cm.. 1(2a) kraštai-ekstra: krūties fibrocistiniai pokyčiai. Naviko plitmo nėra.     2(2b) kraštai-ekstra: krūties fibrocistiniai pokyčiai. Naviko plitimo nėra.     3 sarginis l/m. Limfmazgis su sinusų histiocitoze, lipomatoze.     4(1) dešinės krūties kvadrantas.  Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma;  pT1c(16 mm) pN(sn)0 (0/1 l/m) pLVI-0 pR0.   Imunofenotipas (nustatytas priešoperaciniame biopsijos tyrime):   Estrogenų receptoriai: reakcija teigiama (stiprus branduolių nusidažymas 100% naviko ląstelių).  Progesterono receptoriai: reakcija teigiama (stiprus branduolių nusidažymas 100% naviko ląstelių).  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, solidinis tipas).. 1(2a) kraštai-ekstra: krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitmo nėra.   2(2b) kraštai-ekstra: krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   3 sarginis l/m. Limfmazgis (1) su sinusų histiocitoze, lipomatoze.   4(1) dešinės krūties kvadrantas.  Krūties audinyje, desmoplastiškoje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis grandinėlėmis, gausiomis trabekulinėmis struktūromis besidėstančių ląstelių negausia eozinofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių iki 18/10 DPRL.   Greta naviko gausūs dilatuoti latakai su intraduktalinėmis solidinėmis struktūromis iš analogiškų navikui ląstelių.. nan
answer:  0

 16%|█▌        | 106/661 [01:37<08:55,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)-retroareoliariai - kraštai - be naviko   2(N2b)-retroareoliariai - kraštai - be naviko   3(N2c)-retroareoliariai - kraštai - be naviko   4(N1) - sektorius- planinis  patologinis tyrimas. N1- skubus rentgenis N1tyrimas- Mikrokalcinatai -17 mm plote  pašalinti. 4. Krūties sektorius 5,5x5,5x3,5 cm be odos. Krūties audinys fibrozuotas visame plote, fibrozėje neaiškių ribų pilkšvas, standus navikas 20x12x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm.. PAPILDYTA (HER2 FISH TYRIMAS):  1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Krūties audinys.  4. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(16 mm) pNX(limfmazgiai nešalinti, LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).  HER2 imuninė reakcija: ribinė (2+).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).   Krūties vidutinio ir žemo laipsnio duktalinė karcinoma in situ (DIN1c/DIN2/DCIS)(kribriforminė).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai bei lobulės, kloti dvisluoksniu epiteliu; fokalinis sekrecinis pokytis.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai bei lobulės, kloti dvisluoksniu epiteliu.  3(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai bei lobulės, kloti dvisluoksniu epiteliu.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 16 mm), suformuotas fibrozuotoje desmoplastiškoje stromoje plintančių kribriforminių ir besiliejančių liaukinių struktūrų, klotų ląstelėmis vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, skeltais, dalis su smulkia nukleole branduoliais. Mitozių iki 1/10 DPRL. Negausūs smulkūs mikrokalcifikatai. Aplink gan gausūs dilatuoti kanaliukai su kribriforminiais analogiškų navikui ląstelių proliferatais.. 4. Navikas (8 ir 10 blokai): invazyvios karcinomos struktūros be CK14+ mioepitelinio sl.; DCIS struktūrose išlaikytas mioepitelinis sl.  10 blokas: HER2 imuninė reakcija: silpnas/vidutinis dalies membranos nusidažymas 70% naviko ląstelių.
answer:  0

 16%|█▌        | 107/661 [01:38<09:02,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. sektoriaus kraštai - extra;  2. sektoriaus kraštai - extra;  3. sarginiai l/m - extra.  4. Deš.krūties sektorius su naviku.. 4. Krūties sektorius 9,5x7x4 cm su oda 7x1,3 cm, žymėtas viela. Vielos projekcijoje - pilkšvas standus, neaiškių ribų navikas 24x16x14 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 5,2 cm.. 1(ekstra). Sektoriaus kraštai. Riebalinis fibrozinis audinys, be naviko plitimo.   2(ekstra). Sektoriaus kraštai. Krūties audinys be naviko plitimo.     3(ekstra). Sarginiai l/m. Reaktyvi limfadenopatija (1 l/m).     4. Dešinės krūties sektorius.   Krūties invazyvi vidutiniškai diferencijuota (G2, 6 b. pagal Nottingham sist.) duktalinė karcinoma,   pT2 (24 mm) pN0(sn)(0/1 l/m) pLVI-2 (invazija smulkiose gyslose) pR0(radikalus pašalinimas).   Naviko imunotipas nustatytas biopsiniame tyrime (B23-13987):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis, kribriforminis tipas).  Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija, apokrininė metaplazija.. 1(ekstra). Sektoriaus kraštai. Riebalinis fibrozinis audinys, be naviko plitimo.   2(ekstra). Sektoriaus kraštai. Riebalinis fibrozinis audinys su smulkiais latakėliais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   3(ekstra). Sarginiai l/m: 1 limfmazgis su I/II folikulais, sinusų histiocitoze, lipomatoze.  4. Deš.krūties sektorius. Krūties audinyje - 24 mm dydžio (mikroskopiškai) navikas, suformuotas lizdų, trabekulių, pavienių tubulių (<10%). Naviko ląstelės su vidutinio gausumo, šviesiai eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais fokaliai su smulkiomis nukleolėmis. Mitozių navike iki 2/10DPRL.   Naviko plitimas endotelizuotuose spindžiuose.   Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių, vietomis su komedonekroze spindžiuose.  Kituose kanaliukuose cistinė dilatacija, paprastoji intraduktalinė hiperplazija, apokrininė metaplazija.. nan
answer:  0

 16%|█▋        | 108/661 [01:39<08:58,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1.dešinė krūtis, planinis. 2. sarginiai l/m, planinis.. 1. Krūtis 905 gramų svorio, 23x18x4,2 cm. Krūties audinyje, apatiniame lateraliniame kvadrante pilkšvas, neaiškių ribų, standus navikas 29x23x19 mm, esantis 0,5 cm nuo artimiausio rezekcijos krašto.   2. Riebalinio audinio fragmentas 4x3,5x1,2 cm. Rastas limfmazgis 1,4 cm.. N1: Krūties audinyje 29mm navikas iš trijų komponentų:  Intracistinė papilinė karcinoma (14mm, traktuojama kaip In situ karcinoma);  Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS, solidinė ir kribrozinė; 13mm);  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma (trys invazijos židiniai, didžiausias 6mm); pT1b.  Invazinis navikas:  estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių;  progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių;  Her2 imuninė reakcija: neigiama 1+;  Ki67+ 15%.  N2: Limfmazgis be naviko metastazių; pN0(sn).. N1: Krūties audinį gana aiškių ribų 14mm cistinis darinys su gausiomis papilinėmis struktūromis išklotomis neryškiai polimorfišku cilindriniu epitleiu be mioepitelinio sluoksnio nei papilinėse struktūrose, nei darinio periferijoje.  Aplink darinį 13mm ilgyje gausūs dilatuoti kanaliukai su intraduktaliniais solidiniais/kribroziniais neryškiai polimorfiškų ląstelių proliferatais.  Pirmajame navike ir jo periferijoje trys invazinio naviko židiniai (didžiausias 6mm): duktalinės struktūros, nedideli kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.  Operacinis pjūvis be naviko.  N2: Limfmazgis su reaktyviais pokyčiais, be naviko metastazių.. Invazinis navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių;  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių;  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.
answer:  0

 16%|█▋        | 109/661 [01:40<08:50,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - skubus patologinis tyrimas- kraštai be naviko  2(N2B) - skubus patologinis tyrimas- kraštai be naviko  3(N3)- l/m-skubus  4(N1) - sektorius patologinis planinis   N1- skubus rentgeninis tyrimas - navikas pašalintas. 4. Krūties sektorius 9x4,5x4 cm su oda 8x3 cm, žymėtas viela. Vielos projekcijoje - pilkšvas, neaiškių ribų navikas 9x9x6 mm(sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 2 cm.. 1(Extra). Riebalinis audinys.  2(Extra). Riebalinis audinys.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma (g.b. iš solidinės papilinės karcinomos), SUMINIS TNM: pT1b(8 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).. 1(Extra). Brandus riebalinis audinys.  2(Extra). Brandus riebalinis audinys su neryškia fibroze.  3(Extra). 2 limfmazgiai su neryškia parakortekso hiperplazija ir sinusų histiocitoze.  4. Krūties audinyje, fibrozuotoje stromoje - ribotas navikas (mikroskopiškai 8 mm), suformuotas stambių lizdinių struktūrų (su smulkiomis fibrovaskulinėmis septomis) ir į periferiją plintančių smulkesnių lizdinių ir trabekulinių struktūrų iš ląstelių saikinga ar vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, smulkiais ir vidutinio kalibro, apvaliais/ovaliais, gan monomorfiškais, dalis skeltais ar su smulkia nukleole branduoliais. Mitozių iki 2/10 DPRL. Naviko atstumas nuo rezekcijos krašto 3 mm. Šalia zona su fibroze, makrofagais, siderofagais ir daugiabranduolėmis gigantinėmis ląstelėmis (biopsijos vieta?).. 4. Navikas (12 blokas): CK14+ mioepitelinio sluoksnio nėra.  Navikas (13 blokas): CK14+/SMA+ mioepitelinio sluoksnio nėra; Synaptophysin(+/+++)(citopl. r-ja), 5%; Chromogranin A(-).
answer:  0

 17%|█▋        | 110/661 [01:41<08:35,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 16 G automatine biopsine adata punktuotas ~11x27 mm dydžio, netolygiai, iki ~3,8 mm akcentuotu žieviniu sluoksniu l/m dešiniosios pažasties I zonoje, paimti trys biopsiniai stulpeliai  histologijai (I buteliukas).   2 ėminio aprašas: 2. 16 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis (>50 mm), deformuoto liaukinio audinio plotas (atitinkantis MR tyrime k/m kiek labiau pakaupiantį plotą)  dešiniojoje krūtyje ties 10-11 val. vidurinėje/periferinėje dalyje daugiau prie krūtinės ląstos sienos, paimti keturi biopsiniai stulpeliai histologijai (II buteliukas).. 1. 3 biopsiniai stulpeliai: I - 15 mm; II - 8 mm; III - 10 mm.  2. 4 biopsiniai stulpeliai: I - 18 mm; II - 18 mm; III - 11 mm; IV - 12 mm.. N1: Duktalinės karcinomos metastazė limfmazgyje.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 30%.. N1: Žemiau aprašyto naviko metastazė limfmazgyje.  N2: Krūties audinį infiltruoja smulkūs solidiniai kompleksai, juostos iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.. Navikas (vertinta metastazės audinyje)  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% navik
answer:  0

 17%|█▋        | 111/661 [01:42<08:23,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas BI RADS 5 darinys kairėje krūtyje, paimti 3 biopsiniai stulpeliai medžiagos histologiniam ištyrimui  2 ėminio aprašas: punktuotas kair. pažasties l/m sustorėjusiu žieviniu sluoksniu, paimti 2 biopsiniai stulpeliai medžiagos histologiniam ištyrimui. 1. 3 biopsiniai stulpeliai: I - 10 mm; II - 12 mm; III - 11 mm.  2. 2 biopsiniai stulpeliai: I - 5 mm; II - 7 mm.. N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.  N2: Duktalinės karcinomos metastazės (navikinio audinio bioptatai, limfmazgio audinio nėra).. N1: Krūties audinį infiltruoja juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  N2: Aukščiau aprašyto navikinio audinio bioptatai (limfmazgio audinio gautoje medžiagoje nėra).. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 12
answer:  1

 17%|█▋        | 112/661 [01:43<08:03,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 75% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros (20%), netaisyklingi kribroziniai ir solidiniai kompleksai bei trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 75% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 70%  naviko ląstelių membranoje.  Ki
answer:  8

 17%|█▋        | 113/661 [01:43<07:59,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~16×18 mm dydžio darinys dešiniojoje krūtyje ties 12 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 15 mm; II - 12 mm; III - 11 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 30%.. Krūties audinį 3-se bioptatuose infiltruoja iki 12 mm :   - solidiniai kompleksai ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) necirkuliari reakcija, 20%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 30% naviko ląstelių.  Progesterono receptoriai: reakci
answer:  0

 17%|█▋        | 114/661 [01:44<07:43,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 6 mm; III - 12 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė karcinoma, tikėtina duktalinė (navikas ECAD+).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja siauri šakoti solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ECAD pozityvių smulkių ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 2%.
answer:  0

 17%|█▋        | 115/661 [01:45<07:56,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a) - viršutinis kraštas, skubu;  2(1b) - apatinis kraštas, skubu;  3(2) - sarginiai limfmazgiai, skubu;  4(3)- dex. sektorius, planinis.. 4(3). Krūties sektorius 5,5x4x2,5 cm, be odos, žymėtas viela. Pjūvyje, vielos projekcijoje - balkšvas, standus, neaiškių ribų navikas 16x10x9 mm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm.. 1(1a). Krūties audinys.  2(1b). Krūties fibrocistiniai pokyčiai. Intraduktalinė papiloma (0,3 cm).  3(2). Reaktyvi limfadenopatija (2 l/m).  4(3). Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,6 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės invazijos nėra). Krūties intraduktalinė papiloma (0,3 cm).     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.. 1(1a). Negausūs smulkūs kanaliukai riebaliniame audinyje.  2(1b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; kanaliukas su susiliejančiomis žemu stulpiniu, stulpiniu epiteliu išklotomis papilinėmis struktūromis spindyje (0,3 cm).  3(2). Nežymi sinusų histiocitozė dviejuose (2) limfmazgiuose.  4(3). Krūties audinyje - navikas: smulkias solidines, negausias kribrozines ar smulkias tubulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 3 / 10 DPRL.. 4(3). Navikas (17 blokas): Her2 nusidažiusių naviko ląstelių nėra; Ki67 5%.
answer:  1

 18%|█▊        | 116/661 [01:46<07:38,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 1-2%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 1-
answer:  0

 18%|█▊        | 117/661 [01:47<07:27,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 4 mm; II - 4 mm; III - 4 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 16%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai su pavieniais spindžiais iš ryškiai polimorfiškų ląstelių, mitozių iki 0-1/DPRL (navikinis židinys tik du regėjimo laukai).. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 40% naviko ląstel
answer:  1

 18%|█▊        | 118/661 [01:47<07:21,  1.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 10 mm; III - 11 mm.. Invazinė duktalinė (kitaip neklasifikuojama)  karcinoma (mažiausiai iki 9 mm);  (G2; 6 b. pgl. Nottingham sist.) 2/3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 20%.. Krūties audinį 2/3-se bioptatuose infiltruoja iki 9 mm :   - solidiniai kompleksai;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 2/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 40%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 20% naviko ląstelių.  Progesterono receptoriai: stipri (+
answer:  90

 18%|█▊        | 119/661 [01:48<07:54,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta dešinė krūtis planinis tyrimas  2 ėminio aprašas: N2: pašalintas dešinės krūties sarginis limfmazgis - planinis tyrimas. 1. Krūtis 1490 gramų svorio, 26x22x6 cm. Krūties audinyje:  - Apatiniame lateraliniame kvadrante pilkšvas, standus, neaiškių ribų I navikas 23x22x21 mm, nuo giliojo rezekcijos krašto nutolęs 4 cm, nuo odos - 1,7 cm;  - Medialiau pilkšvas, standus, neaiškių ribų II navikas 9x6x5 mm, nuo I naviko nutolęs 0,5 cm;  - Viršutinių kvadrantų riboje pilkšvas, standus, neaiškių ribų III navikas 11x7x5 mm, nuo giliojo rezekcijos krašto nutolęs 4,5 cm, nuo odos - 2,5 cm.   - Viršutiniame lateraliniame kvadrante pilkšvas, standus IV židinys 7x6x4 mm.  - Pilkšvas, standus, neaiškių ribų V navikas 4x4x3 mm.    Aplink navikus fibrozės zona 12x7x6 cm. 3,6 bloke zona virš I naviko žymėta juodais dažais, virš II naviko - mėlynais.    2. Riebalinio audinio fragmentai, bendras dydis 5x3,5x1 cm. Rasti 3 limfmazgiai, didžiausias 2,5 cm.. 1. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.2): pT2m(iki 4 naviko židinių, didžiausias 2,3 cm) pN1a(1/1 intramamarinis l/m + 1/3 sarginis l/m, didžiausia mts 0,6 cm). LVI2(limfovaskulinė naviko invazija, smulkiose struktūrose). R0(radikalus naviko pašalinimas).  2. Duktalinės adenokarcinomos mts 1/3 l/m (mts 0,5 cm).  ---  Estrogenų receptoriai: stipri branduolinė r-ja 100% naviko ląstelių.  Progesterono receptoriai: stipri branduolinė r-ja 100% naviko ląstelių.  HER2: silpnas dalies membranos nusidažymas 5% naviko ląstelių.  Ki67: iki 15%.. 1. KRŪTIES SPENELIS: Be patologijos.  KRŪTIS: Krūties audinyje - A) panašios histologinės ir citologinės išvaizdos keturi (4) naviko židiniai (trabekulines, kribrozines, susiliejančias tubulines naviko struktūras formuoja ląstelės su kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 12 / 10 DPRL), B) intramamarinis limfmazgis su aukščiau aprašyto naviko metastaze (iki 0,6 cm).  2. Aukščiau aprašyto naviko metastazė (iki 0,5 cm) viename (1) iš trijų (3) limfmazgyje.. nan
answer:  0

 18%|█▊        | 120/661 [01:49<07:36,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinias stulpelis. Biopsinis stulpelis 15 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja pavienės duktalinės struktūros, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 18%|█▊        | 121/661 [01:50<07:56,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.   2(2b). Kraštai - skubus tyrimas - be naviko.  3. Dešinės pažasties sarginis limfmazgis - skubus tyrimas 2 l/m be naviko.  4(1). Pašalintas dešinės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 12x6x4 cm su odos lopu 9,5x2 cm. Pjūvyje balkšvas, standus, neaiškių ribų navikas 9x8x8 mm, nuo artimiausio rezekcijos krašto nutolęs 1,3 cm, nuo odos – 2 cm. Šalia naviko - fibrozės zona 4x4x2,5 cm, siekianti rezekcijos kraštą, nuo odos nutolusi 2,2 cm.. 1(2a). Fibrocistiniai krūties pokyčiai.  2(2b). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (2 l/m).  4(1). Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 11 mm), pN0(sn)(0/2 l/n), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).. 1(2a). Fibrozuotame krūties audinyje gausūs smulkūs bei dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar epiteliu su apokrinine epitelio metaplazija.  2(2b). Fibrozuotame krūties audinyje gausūs smulkūs bei dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  3. Du limfmazgiai su sinusų histiocitoze ir šerdies lipomatoze.  4(1). Krūties audinyje - navikas (11 mm mikroskopiškai), suformuotas tubulinių ir kribriforminių struktūrų iš vidutinio kalibro eozinofiline citoplazma ląstelių, nežymiai polimorfiškais, smulkiai grūdėtu chromatinu branduoliais; mitozių 3/10 DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Greta naviko negausūs dilatuoti kanaliukai su kribriformine proliferacija iš monomorfiškų, negausia šviesiai eozinofiline citoplazma ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta nežymiai dilatuoti kanaliukai kloti fokaliai hiperplastišku epiteliu.. Blokas 12:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 18%|█▊        | 122/661 [01:51<07:37,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. Kairė krūtis su limfmazgiais, planinis. Krūtis 885 g svorio, 20x18x5 cm, su pažasties narveliena 12x7x3 cm. Krūties audinyje, viršutiniame medialiniame kvadrante - pilkšvas gana aiškių ribų navikas 25x18x15 mm, esantis 2,5 cm nuo artimiausio/giliojo rezekcijos pjūvio, nuo odos 2 cm. Krūties audinyje fibrozės židiniai, kitųas navikinis židinys 1,1cm. Pažasties narvelienoje rasti 23 limfmazgiai, didžiausias 2,5 cm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2(m) (11mm ir 25mm); pN1a (1 iš 23 l/m; 25mm).. Krūties audinyje du navikiniai židiniai (11mm ir 25mm): nedideli solidiniai kompleksai ir trabekulės iš ryškiai polimorfiškų ląstelių, mitozių iki 18/10 DPRL. Nekrozės židiniai navike.  Iš rastų 23 limfmazgių vienas (1) su 25mm metastaze.. nan
answer:  1

 19%|█▊        | 123/661 [01:52<07:25,  1.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 fraqgmenituoti biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 10 mm; II - 6 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma su apokrininės diferenciacijos požymiais.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 8% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 20%.. Krūties audinį infiltruoja susiliejantys kribroziniai ir solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 14/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 8% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67+ 15%, v
answer:  0

 19%|█▉        | 124/661 [01:53<07:56,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N3) dešinės pažasties sarginis limfmazgis - skubus tyrimas - 3 l/m be naviko  4(N1) pašalintas dešinės krūties kvadrantas planinis tyrimas. 4. Krūties sektorius 7x4x4 cm su odos lopu 5,5x2,2 cm. Krūties audinyje, pjūvyje pilkšvas, standus, neaiškių ribų navikas 17x15x15 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 1 cm.. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Krūties karcinomos mikrometastazė limfmazgyje (microMTS 1/3 l/m 1,6 mm)    4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma su mikropapilinės karcinomos komponentu,   SUMINIS TNM: pT1c(17 mm navikas) pN1mi(sn)(microMTS 1/3 l/m 1,6 mm) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija).  Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 kribriforminis ir papilinis tipai).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 60% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 40%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 1 iš 3 limfmazgių aprašyto naviko mikrometastazė 1,6 mm.     4. Krūtyje - navikas (17 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis struktūromis, lizdais ir mikropapilomis besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai - ryškiai polimorfiškais, nereguliaraus kontūro, ovaliais apvaliais, vezikulizuotais branduoliais ryškiomis nukleolėmis; mitozių 18/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių. Limfovaskulinė invazija.  Navikas, nuo sektoriaus rezekcijos krašto nutolęs 0,25 mm.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) ---- %.  Progesterono receptoriai: (+++)(brand. r-ja) ---- %.  HER2: silpnas/vidutinis/stiprus dalies/visos membranos nusidažymas xx% naviko ląstelių.  Ki67 proliferacinis aktyvumas ---- %.  CK5+ išlaiky
answer:  0

 19%|█▉        | 125/661 [01:54<07:55,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. punktuotas deš. krūties ties 12val. esantis židinys, paimti 3 stulpeliai medžiagos histologiniam ištyrimui (Nr. 1).   @#@#2. punktuotas kair. krūties ties 2-3val. esantis kalcifikuotas darinys, paimti 3 stulpeliai medžiagos histologiniam ištyrimui (Nr. 2).. 1. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 7 mm; III - 7 mm.  3. 3 fragmentuoti biopsiniai stulpeliai: I - 5 mm; II - 3 mm; III - 7 mm.. N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.  Krūties fibroadenoma.  N2: Krūties fibroadenoma.. N1: Krūties audinyje mazgas iš proliferuojančių fibroblastų stromos, suspaustų kanaliukų, išklotų dvieiliu epiteliu, vietomis su intrakanalikuliniais stromos proliferatais. Viename fragmente krūties audinį infiltruoja smulkios duktalinės struktūros, smulkūs netaisyklingi kribroziniai kompleksai ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  N1: Krūties audinyje mazgas iš proliferuojančių fibroblastų stromos, suspaustų kanaliukų, išklotų dvieiliu epiteliu, vietomis su intrakanalikuliniais stromos proliferatais. N1 navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67
answer:  15

 19%|█▉        | 126/661 [01:55<08:16,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas dešinės krūties žymėtas kvadrantas - planinis tyrimas  2 ėminio aprašas: N2a kraštai planinis tyrimas  3 ėminio aprašas: N2b kraštai - planinis tyrimas  4 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - planinis tyrimas. 1. Krūties sektorius 10,5x7x3,5 cm su odos lopu 9x4 cm, žymėtas viela. Vielos projekcijoje - pilkšvas, standus, neaiškių ribų navikas 13x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 1,2 cm, nuo odos - 1 cm.  2. Riebalinio audinio fragmentas 1,6x1,2x0,4 cm. v/m  3. Riebalinio audinio fragmentas 1x1x0,4 cm. v/m  4. Riebalinio audinio fragmentas 3x2,5x1 cm. Rasti 4 limfmazgiai iki 1 cm. v/m. 1. Krūties gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: T1c(14 mm navikas) pN1a(sn)(1/5 l/m MTS 4,4 mm) LVI-2(limfovaskulinė invazija).  R0(radikali rezekcija).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.    2. Krūties audinio fibrozė.  3. Krūties audinio fibrozė.  4. Duktalinės karcinomos metastazė limfmazgyje (1/4 l/m MTS 4,4 mm).. 1. Krūtyje - navikas (14 mm) infiltratyviu augimo frontu, suformuotas tubulinėmis, trabekulinėmis struktūromis ir pabirai besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais apvaliais; mitozių 3/10 DPRL.  Aplinkinis krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2. Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Riebalinis fibrozinis audinys.  4. 1 iš 4 limfmazgių aprašyto naviko metastazė 4,4 mm.. Navikas (11 blokas): Ecadherin(+++) membr. r-ja 90%; p120(+++) membr. r-ja 90%;
answer:  0

 19%|█▉        | 127/661 [01:56<08:27,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 18 G automatine biopsine adata punktuotas hipoechogeninis ~10×8 mm dydžio deformacijos plotaskairiojoje krūtyje ties 2 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai (I buteliukas).   2 ėminio aprašas: 2. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais ~8×4 mm dydžio darinys kairiojoje krūtyje ties 1 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai (II buteliukas).   3 ėminio aprašas: 3. 18 G automatine biopsine adata punktuotas hipoechogeninis, gana aiškiomis ribomis su spikulėmis ~12×9 mm dydžio darinys dešiniojoje krūtyje ties 1 val. vidurinėje-periferinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai (III buteliukas).. 1. 3 biopsiniai stulpeliai: I -5 mm; II - 10 mm; III - 6 mm.  2. 3 biopsiniai stulpeliai: I - 11 mm; II - 9 mm; III - 7 mm.  3. 3 biopsiniai stulpeliai: I - 11 mm; II - 10 mm; III - 6 mm.. Kairė  N1-2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.  ----------  Dešinė  N3: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Kairė  N1-2: Krūties audinį infiltruoja duktalinės struktūros ir kribroziniai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL. Navikas visuose 6iuose biopsiniuose stulpeliuose.  ----------  Dešinė  N3: Krūties audinį infiltruoja duktalinės struktūros ir negausūs kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL. Navikas visuose 3uose biopsiniuose stulpeliuose. nan
answer:  0

 19%|█▉        | 128/661 [01:56<08:00,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a   2. ėminio aprašas N2b kraštai  - skubus tyrimas be naviko   3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - skubus tyrimas 1 mts  4. (1) ėminio aprašas: pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 12x5,5x6 cm su oda 11x3 cm. Krūties audinyje, pilkšvas, neaiškių ribų standus navikas 17x15x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,5 cm.. N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(17mm).  N2ab: Krūties audinys be naviko.  N3: Limfmazgis (1 iš 2 l/m) su metastaze 4mm; pN1a(sn).. N1: Krūties audinyje 17mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.  N2ab: Krūties audinys be naviko.  N3: Limfmazgis (1 iš 2 l/m) su metastaze 4mm.. nan
answer:  0

 20%|█▉        | 129/661 [01:58<08:27,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  ca mammae dex - extra  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4(3). pap. prie nr. 3 - ekstra  5(4). sektorius, planinis.   6(5). papildomas kraštas, planinis.. 5. Krūties sektorius 13,5x7,5x5,5 cm su oda 11,5x3 cm. Krūties audinyje - pilkšvas, standus, aiškių ribų navikas 25x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,2 cm. Rasti 4 limfmazgiai iki 1,3 cm.  6. Riebalinio audinio fragmentas 2,5x2x0,6 cm. v/m. 1. Krūties fibrocistiniai pokyčiai.   2. Krūties intraduktalinė papiloma. Atipinė duktalinė hiperplazija, fibrocistiniai pokyčiai.   3. Reaktyvi limfadenopatija (1 l/m).   4. Reaktyvi limfadenopatija (1 l/m).   5. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma su minimaliu(~5%) mikropapilinės karcinomos komponentu,   suminis Nr. 1 - 4 pTNM:   pT2 (25 mm) pN1mi(sn) (3/6 l/m, metastazės iki 1,2 mm); LVI2 (limfovaskulinė naviko invazija smulkiose kraujagyslėse/limfagyslėse).   Fibroadenoma.   6. Riebalinis audinys be patologinių pokyčių.. 1. Krūties audinio stroma ryškiai fibrozuota, su atrofiškomis lobulėmis, cistiškai dilatuotais latakais.   2. Krūties audinyje - grupė latakų su keliomis smulkiomis intraduktalinėmis papilinėmis struktūromis klotomis mioepitelinėmis ir duktalinėmis ląstelėmis, su ryškia netolygia hiperplazija, aplinkiniai latakai su stulpiniu epitelio pokyčiu ir apikalinės sekrecijos požymiais bei epitelio hiperplazija. Pora latakų su pavieniais, kiek monotoniškais kribriforminiais epitelio proliferatais dalyje latako spindžio.    3. Limfmazgis (1) tušuota architektūra, sinusų histiocitoze, stromos lipomatoze ir nežymia fibroze.  4. Limfmazgis (1) tušuota architektūra, sinusų histiocitoze, stromos lipomatoze ir nežymia fibroze.  5. Krūties audinyje - infiltratyviai plintantis navikas, formuojamas kompleksinių ir kribriforminių liaukinių, tubulinių, solidinių ir labai negausių mikropapilinių(~5%) struktūrų, sudarytų iš vidutinio dydžio kampuotų ląstelių šviesiai eozinofiliška citoplazma, vidutiniškai polimorfiškais ovoidiniais branduoliais su smulkiai grūdėtu chromatinu, ryškiomis nedidelėmis nukleolėmis. Navike iki 4 mitozių/ 10 DPRL. Limfovaskulinė naviko invazija smulkiose kraujagyslėse/limfagyslėse (LVI2).   Limfmazgiuose (3 iš 4) - aukščiau aprašyto naviko metastazės iki 1,2 mm.   Krūties audinyje - nedidelis aiškių ribų navikas, formuojamas kolagenizuotos stromos ir suspaustų kanaliukų.   6. Riebalinis audinys be patologinių pokyčių.. nan
answer:  1

 20%|█▉        | 130/661 [01:58<08:04,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 4 biopsiniai stulpeliai. 4 biopsiniai stulpeliai: I - 15 mm; II - 11 mm; III - 12 mm; IV - 7 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G2; 6 b. pgl. Nottingham sist.) 4-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 10%.. Krūties audinį 4-se bioptatuose infiltruoja iki 13 mm :   - solidiniai kompleksai ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko
answer:  1

 20%|█▉        | 131/661 [01:59<07:59,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. pjūvio kraštai, ekstra.   3. Sarginiai l/m, ekstra.   4. Sektorius, planinis.. 4. Krūties sektorius 14,5x9x5 cm su odos lopu 14x2 cm, su speneliu, pjūvyje užspenelinėje srityje balkšvas, standus, aiškių ribų navikas 2,4x1,7x1,2 cm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos – 3,2 cm.. 1. Kraštai. Krūties audinys be patologinių pokyčių.  2. Kraštai. Krūties audinys be patologinių pokyčių.  3. Sarginiai limfmazgiai: Limfmazgiai (4) be karcinomos ląstelių; pN0.  4. Kairės krūties sektorius.   Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT2(24 mm) pLVI-0 pR0.  Imunotipas nsutatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%. 1. Kraštai. Krūties audinys be patologinių pokyčių.  2. Kraštai. Krūties audinys be patologinių pokyčių.  3. Sarginiai limfmazgiai: Limfmazgiai (4) be karcinomos ląstelių.  4. Kairės krūties sektorius. Krūties audinį infiltruoja naviko susiliejančios duktalinės struktūros ir netaisyklingi kribroziniai/solidiniai  bei smulkūs pseudopapiliniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 14/10 DPRL.  Plitimo operaciniuose kraštuose ar kraujagyslėse nestebima.. EMA: vidutinis(++)/stiprus(+++) citoplazminis dažymasis 100% .
answer:  0

 20%|█▉        | 132/661 [02:00<08:26,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a kraštai - skubus tyrimas - be naviko  2. N2b kraštai - skubus tyrimas - be naviko   3. N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas - 3 l/m be naviko  4. N1. pašalintas dešinės krūties kvadrantas  - planinis tyrimas. 4. Krūties sektorius 11x5,5x6 cm, su odos lopu 10,5x3 cm. Krūties audinyje pilkšvas, ribotas, standus navikas 23x23x20 mm, nuo giliojo rezekcijos krato nutolęs 1,6 cm, nuo odos - 2,2 cm.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties-riebalinis audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties-riebalinis audinys su lėtine nespecifine uždegimine infiltracija; be naviko.   3(ekstra). "Dešinės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   4(1). Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT2 (navikas 23 mm) N0(sn) (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Naviko nekrozė iki 40%.   Imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcijos nėra (0).  Ki67: proliferacinis indeksas 50%.   GATA3(+)30%; SOX-10(+)99%.   Krūties sektoriaus rezekcijos kraštas normalios histologinės struktūros.. 1(2a, ekstra). "Kraštai": brandžių lipocitų suformuotas audinys su židinine fibroze, fokaliai retais kanaliukais, klotais dvisluoksniu epiteliu.   2(2b, ekstra). "Kraštai": brandžių lipocitų suformuotas audinys su židinine fibroze ir MMN infiltracija, fokaliai retais kanaliukais, klotais dvisluoksniu epiteliu.   3(ekstra). "Dešinės pažasties sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4(1). NAVIKAS: krūties audinyje - fibrozinio audinio juosta apribotas navikas, kurį sudaro besiliejančios lizdinės ir solidinės naviko struktūros su retais nedideliais spindžiais, suformuotos ryškiai polimorfiškų ląstelių, vidutinio gausumo tamsoka citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki ~30/10 DPRL. Naviko struktūrų centrinėse dalyse gausios nekrozės zonos (~40%) su PMN ("komedo" tipo piešinys). Naviko stroma infiltruota MMN.   APLINKA: visame krūties audinyje nedideli MMN suformuoti agregatai.   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 4(1). Navikas (blokas 15):   GATA3(+)(brand.r-ja)30%; SOX-10(+/+++)(brand.r-ja)99%.  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląst
answer:  0

 20%|██        | 133/661 [02:01<08:22,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pašalinta  kairė krūtis - planinis tyrimas. Krūtis, 2023 gramų svorio, 20x20x7 cm dydžio. Odoje areolės srityje ir aplinkinėje odoje - 9x4 cm plote hematoma ir rusvos neaiškių ribų dėmės iki 0,4 cm. Krūties audinyje:  - centrinėje dalyje - balkšvas standus, neaiškių ribų I židinys 0,7x0,4x0,5 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 4 cm, nuo odos 1,5 cm.  - pilkšvas, neaiškių ribų II židinys 1,9x0,8x1,4 cm (sudėtas visas), nuo I židinio nutolęs 3 cm, nuo artimiausio rezekcijos krašto(dažytas mėlynu tušu) nutolęs 5 cm, nuo odos 1 cm.. Krūties vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma, pT1b (9 mm navikas) pLVI-2 (limfovaskulinė invazija smulkiose gyslose).   Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis, kribriforminis tipai). Paprastoji duktalinė hiperplazija. Intraduktalinė papiloma.  Radikalus pašalinimas.. Krūties audinyje du židiniai:    I židinys: Krūties audinyje - 9 mm dydžio (mikroskopiškai) navikas, suformuotas netaisyklingų solidinių kompleksų, iš ląstelių su gausia, šviesiai eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar ovoidiškais, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių navike iki 3/10DPRL. Šalia naviko stambūs kanaliukai su intraduktaliniais solidiniais ir kribriforminiais proliferatais iš analogiškų navikui ląstelių. Stromoje hemosiderofagai, putoti makrofagai, cholesterolio kristalus apsupančios svetimkūnio tipo daugiabranduolės gigantinės ląstelės, židininė fibrozė su suspaustais deformuotais kanaliukais, klotais dvisluoksniu epiteliu.    II židinys: krūties audinio fibrozė, stambūs latakai su intraduktaliniais solidiniais ir kribriforminiais proliferatais iš analogiškų I židinyje esantiems latakams ląstelių. Yra latakų su papiliniais ir kribriforminiais intraduktaliniais proliferatais, klotais dvisluoksniu epiteliu.. nan
answer:  0

 20%|██        | 134/661 [02:02<07:53,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 bioptatai. 3 fragmentuoti biopsiniai stulpeliai: I - 15 mm; II - 17 mm; III - 13 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis iki 15%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 10
answer:  0

 20%|██        | 135/661 [02:03<07:33,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 8 mm; II - 7 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.. Krūties audinį infiltruoja smulkios duktalinės struktūros, nedideli kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 2%.
answer:  0

 21%|██        | 136/661 [02:04<07:22,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais policikliniais kontūrais, su UG fiksuojama kraujotaka, ~ 19x11 mm dydžio darinys dešiniojoje krūtyje ties 7 val. vidurinėje-periferinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 12 mm; II - 8 mm; III - 12 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+
answer:  30

 21%|██        | 137/661 [02:04<07:09,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsy cores: I - 14 mm; II - 13 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja juostos iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 2%.
answer:  0

 21%|██        | 138/661 [02:06<07:56,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)-kraštas-extra- DCIS   2.(N2b)-kraštas-extra - be naviko  3.(N2c)-nuo spenelio-extra - be naviko  4.(N3)- Sarginiai l/m(3)- be naviko   5.pap.kraštas-extra- be naviko  6.(N1) - pašalinas sektorius. -planinis patologinis tyrimas N1-skubus Ro tyrimas- navikas pašalintas.. 6. Krūties sektorius 6,5x6x4 cm, su odos lopu 6x3 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje tamsiai rudas, standus, ribotas navikas 16x15x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 2 cm. Visas sektorius žymėtas tušu.. 1(2a). Krūties žemo ir vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis, kribriforminis tipai).  2(2b). Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis tipas).  3(2c). Krūties audinys.    4. Reaktyvi limfadenopatija (4 l/m).  5(pap.). Krūties audinys.  6. Krūties invazyvi, vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham sis) karcinoma (kilusi iš solidinės papilinės karcinomos) su mucininės karcinomos diferenciacijos zonomis (~70% naviko), suminis tyrimo TNM: pT1c(navikas - 16mm) pN0(sn)(0/4 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).   IHC reakcijos atliktos VPC:B23-34296 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  Proliferacinis aktyvumas (Ki67+++, branduolinė r-ja): 5%.  CK5(-), CK14(-), Synaptophysin(++/+++)(citoplazminė r-ja), 90%."  Krūties žemo ir vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis, kribriforminis tipai).. 1(2a). Krūties audinyje - dilatuoti latakai su solidiniais ir kribriforminiais atipinių ląstelių (su žemo ir vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS).  2(2b). Krūties audinyje - pavieniai dilatuoti latakai su solidiniais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS).   3(2c). Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.    4. Keturi(4) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  5(pap.). Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  6. Krūties audinyje - navikas, formuojamas solidinių struktūrų su plonomis fibrovaskulinėmis septomis, ekstraląstelinių mucinų zonos su solidiniai naviko kompleksiais iš vidutinio kalibro ląstelių eozinofiliška/amfofiliška citoplazma, vidutiniškai polimorfiškais, hiperchromiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 10 mitozių/10 DPRL; aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais ir kribriforminiais atipinių ląstelių (su žemo ir vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS).. nan
answer:  0

 21%|██        | 139/661 [02:06<07:41,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 14 mm.. Invazinė duktalinė (su apokrinine diferenciacija) karcinoma (mažiausiai iki 11 mm);  (G2; 7 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija paribinė (2+); nustatyta HER2 geno amplifikacija (žr. molekulinio tyrimo aprašymą).  Ki67: proliferacinis indeksas 20%.. Krūties audinį 1-me bioptate infiltruoja iki 11 mm :   - trabekulės;  - epitelinių vidutinio dydžio ir stambių ląstelių su vidutiniškai ir ryškiai polimorfiškais branduoliais su ryškiu branduolėliu gausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Androgenų receptoriai: stipri  teigiama (+++) branduolių reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: silpna (+) cirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67:
answer:  0

 21%|██        | 140/661 [02:07<07:29,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 11 mm; II - 11 mm; III - 10 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) adenokarcinoma, tikėtina duktalinė.  Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 90%.  Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 80%.   HER2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 8%.. Smulkias solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 5 / 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 90%.  Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 80%.   HER2: nusidažiusių naviko ląstelių nėra.   Ki67: 8%.
answer:  0

 21%|██▏       | 141/661 [02:08<07:57,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sarginiai l/m - extra;  2. Poareolinės zonos audiniai - extra;  3. Kairė krūtis, planinis.. 3. Krūties liauka 12,5x9,5x2 cm su 3 odos lopais, didžiausias 3x2 cm, žymėtas tušu. Krūties audinyje, didžiausio odos lopo projekcijoje - pilkšvas, standus, aiškių ribų I navikas 22x22x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 0,3 cm. Apatiniame lateraliniame kvadrante 1,5 cm atstumu nuo I naviko 17x15x10 mm nutolęs II pilkšvas standus navikas, nuo giliojo rezekcijos krašto 0,1 cm, nuo poodinio rezekcijos krašto 0,1 cm. Visas krūties audinys fibrozuotas su cistinėmis ertmėmis. Paruošti pjūviai Prosigna.  1(ekstra). Reaktyvi limfadenopatija (1 l/m).  2(ekstra). Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai pokyčiai: parastoji intraduktalinė hiperplazija.  3. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(m)(25 mm, 10 mm navikai) pN0(sn)(0/1 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).  Lobulinė karcinoma in situ (LCIS).     Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%.. 1(ekstra). 1 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu ir hiperplastišku epiteliu su apokrinine metaplazija. Dilatuoti latakai ir lobulės su intraduktaliniais solidiniais proliferatais iš ląstelių monomorfiškais branduoliais.    3. Krūtyje - navikas (25 mm, 10 mm) infiltratyviu ekspansyviu augimo frontu,trabekulinėmis struktūromis, lizdais, grandinėlėmis ir pabirai besidėstančių ląstelių negausia eozinofiliška citoplazma, vidutiniais - stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 5/10 DPRL.  navikas nuo giliojo rezekcijos krašto nutolęs 1 mm.  Greta dilatuoti kanaliukai su intraduktaliniais solidiniais proliferatais iš analogiškų navikui ląstelių.  Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaus kanaliukų zonos.. nan
answer:  0

 21%|██▏       | 142/661 [02:09<07:54,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu  3(2). Deš. pažasties sarginiai limfmazgiai, skubu  4(3). Deš. krūties sektorius, planinis. 4. Krūties sektorius 9x5x5,5 cm su odos lopu 8x3 cm. Krūties audinyje, pjūvyje pilkšvas, standus, neaiškių ribų navikas 20x18x15 mm, nuo gilijo rezekcijos krašto nutolęs 0,9 cm, nuo odos - 1 cm.. 1(Extra). Krūties audinys.  2(Extra). Riebalinis audinys.  3(Extra). Krūties duktalinės karcinomos metastazė 1/3 l/m (4,5 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(20 mm) N(sn)1a(mts 1/3 l/m: 4,5 mm), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - įvairaus kalibro ir kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu; negausi židininė MMN infiltracija.  2(Extra). Brandus riebalinis audinys su neryškia fibroze.  3(Extra). 1 iš 3 limfmazgių - žemiau (Nr.4) aprašyto naviko metastazė (4,5 mm).  4. Krūties audinyje - navikas (mikroskopiškai 20 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių lizdinių, trabekulinių ir pavienių (iki 5%) tubulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 5/10 DPRL. Limfovaskulinė invazija.  Žymėtas rezekcijos kraštas - be naviko plitimo.. 1. 1 blokas: kanaliukai su CK14+ mioepiteliniu sluoksniu, ER+ luminalinis sluoksnis.
answer:  1

 22%|██▏       | 143/661 [02:10<07:37,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: stiklai peržiūrai. Konsultacijai gauta:  - 1 parafino blokas (žymėtas H4090-23);  - 6 histologiniai preparatai (žymėti analogišku numeriu, dažyti HE; E-CAD; PRG ; ER; Her2; Ki-67, xx, xx, xx metodais).    stiklai peržiūrai. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 5%.. Bioptatuose (4/4) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, grandinėlėmis ir pabirai besidėstančių ląstelių negausia eozinofiliška citoplazma, nežymiai polimorfiškais, vidutinio kalibro, ovalaus kontūro branduoliais; mitozių 1/10 DPRL.. VPC imunohistocheminiai dažymai:  HER2: silpnas dalies membranos nusidažymas 10% naviko ląstelių.    KMUK/LSMU imunohistocheminiai dažymai:  Estrogenų receptoriai: (+++) brand. r-ja 100%.  Progesterono receptoriai: (+++) brand. r-ja 100%.  Her2: silpnas d
answer:  10

 22%|██▏       | 144/661 [02:11<07:49,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštai - skubus tyrimas  2 ėminio aprašas: N2b kraštai - skubus tyrimas  3 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas  4 ėminio aprašas: N1: pašalintas dešinės krūties kvadrantas - planinis tyrimas  5 ėminio aprašas: N3: papildomai įtartini limfmazgiai - planinis tyrimas. 4. Krūties sektorius 13,5x9x5,5 cm su oda 12,5x5 cm. Krūties audinyje, pilkšvas, standus, skiltėtas navikas 32x30x26 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,2 cm.   5. Riebalinio audinio fragmentas 3x3x1,5 cm. Rasti 2 limfmazgiai iki 1,5 cm. v/m. 1(2a)(Extra). Riebalinis audinys.  2(2b)(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi blogai diferencijuota (G3; 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(32 mm) N(sn)0(0/3 l/m), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas (naviko atstumas nuo rezekcijos krašto 0,6 mm).  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   5. Reaktyvi limfadenopatija (2 l/m).. 1(2a)(Extra). Brandus riebalinis audinys su neryškia fibroze.  2(2b)(Extra). Krūties audinyje - negausūs vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 1 limfmazgis su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze.  4. Krūties audinyje - ribotas navikas, suformuotas fibrozuotoje stromoje plintančių lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais ir nereguliariais, gan polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 35/10 DPRL. Perinavikinė limfocitų infiltracija. Limfovaskulinė invazija smulkiose šakose. Mažiausias naviko atstumas nuo rezekcijos krašto 0,6 mm.  5. 2 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.. nan
answer:  0

 22%|██▏       | 145/661 [02:12<07:25,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros ir smulkūs solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67+ 8%
answer:  0

 22%|██▏       | 146/661 [02:13<08:21,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. Kairė krūtis su limfmazgaiais, planinis. Krūtis 1430 g svorio, 22x19,5x6 cm, su pažasties narveliena 14x13x4,5 cm. Krūties audinyje:  - medialiniame viršutiniame kvadrante balkšvas standus neaiškių ribų I navikas 18x13x12 mm, esantis 3 cm nuo giliojo rezekcijos pjūvio, nuo odos 4 cm.   - 0,5 cm atstumu balkšvas, standus, aiškių ribų II navikas 7x5x4 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 4,5 cm, nuo odos 3,5 cm.   - Nuo I naviko 11 cm atstumu balkšvas standus neaiškių ribų III navikas 15x13x9 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 4,5 cm, nuo odos - 2 cm.   Bendrai pirmi trys navikai išsidėsto 4,5x3x3 cm plote.   - Lateraliniame apatiniame kvadrante pilkšvas, standus IV navikas 21x11x10 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 4,5 cm.   - Lateraliniame viršutiniame kvadrante fibrozės zona 2,5x1,5x3,3 cm su paryškėjusiu aplinkiniu audiniu.   Pažasties narvelienoje rasta 16 limfmazgių, didžiausias 3,5 cm.. Krūties multižidininė duktalinė karcinoma su dviem morfologiniais variantais:   A. I, II, III židiniai:   Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma (kitaip neklasifikuotina).   Naviko imunotipas nustatytas biopsijoje (B23-4490):   Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 12%.    B. IV-tas židinys:   krūties invazyvi vidutiniškai diferencijuota (G2, 7 b. pgl. Nottingham sist.) duktalinė karcinoma (šviesių ląstelių variantas).  Naviko imunotipas:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacijos FISH tyrimo rezultatas laikytinas TEIGIAMU (interpretuojamas HER2 IHC tyrimo kontekste; žr. molekulinio tyrimo aprašymą ir pastabas).    Suminis TNM:   pT(m)2 (21 mm, 18 mm, 15 mm, 7mm naviko židiniai)   pN1a(1/16 l/m su mts iki 8,3 mm)   pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pR0(radikalus pašalinimas).. Spenelis: be patologijos.    Krūties audinyje - trys (I-III) morfologiškai panašūs naviko židiniai ir vienas (IV-as) morfologiškai išsiskiriantis navikas:   I, II, III naviko židiniai suformuoti lizdų, trabekulių, grandinėlių ir pabirų ląstelių. Naviko ląstelės su vidutinio gausumo tamsia eozinofiliška citoplazma, vidutinio kalibro ar stambiais, ryškiai polimorfiškais branduoliais su smulkiai grūdėtu chromatinu ir ryškiomis nukleolėmis. Mitozių I navike iki 16/10DPRL. II navike - iki 10/10DPRL, III navike - iki 23/10DPRL. Naviko plitimas endotelizuotuose spindžiuose (šalia I ir II židinių).     IV navikas: solidinės struktūros ir lizdai iš ląstelių gausoka šviesia citoplazma su PAS+ granulėmis, apvaliais, vidutiniškai polimorfiškais branduoliais smulkiai grūdėtu chromatinu ir aiškiomis nukleolėmis. Mitozių navike iki  9/10 DPRL. Šalia yra latakų su solidiniais intraduktaliniais proliferatais iš IV navikui analogiškų ląstelių.    Aplinkiniuose latakuose cistinė dilatacija, apokrininė metaplazija, įprastinė duktalinė hiperplazija.    Limfmazgiai: 1-me/16 limfmazgių - I/II/III navikams analogiškos struktūros iki 8,3 mm; ekstranodulinio plitimo nestebima.. Blokas 12:  CK14: mioepitelinio išklojimo invazyviose naviko struktūrose nėra.  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) cirkuliari reakcija, 40%  naviko ląstelių membranoje.  Synaptophysin: neigi
answer:  0

 22%|██▏       | 147/661 [02:14<08:13,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.  2(2b). Kraštai - skubus tyrimas - be naviko.  3. Dešinės pažasties sarginis limfmazgis - skubus tyrimas 3 l/m be naviko.  4(1). Pašalintas dešinės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 7,5x3,5x3,5 cm su oda 6x3 cm. Krūties audinyje, kvadrante - pilkšvas, standus, aiškių ribų navikas 22x18x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 1 cm.. 1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (3 l/m).  4(1). Krūties invazyvi blogai diferencijuota (G3; 9 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 18 mm), pN0(sn)(0/3 l/m), LVI2(limfovaskulinis plitimas). Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS). R0(radikali rezekcija). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).. 1(2a). Krūties audinyje smulkūs ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  2(2b). Krūties audinyje gausios lobulės, klotos dvisluoksniu epiteliu.  3. Trys limfmazgiai su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.  4(1). Krūties audinyje, hialinizuotoje stromoje plinta navikas (18 mm) infiltratyviu augimo frontu. Navikas suformuotas solidinių, trabekulinių ir negausių tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su ryškiai polimorfiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 44/10DPRL. Limfovaskulinis plitimas smulkiose limfagyslėse/kraujagyslėse(LVI2). Greta naviko gausūs dilatuoti kanaliukai užpildyti solidinių ir kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais; dalies proliferatų centruose - nekrozės zonos.. Blokas 12:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 22%|██▏       | 148/661 [02:15<07:42,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas:   1-2. pjūvio kraštai, ekstra.  3. sarginiai l/m, ekstra.  4. sektorius. ekstra. 4. Krūties sektorius 11,5x5,5x6,5 cm su oda 10x2,5 cm. Krūties audinyje, pilkšvas, standus, aiškių ribų navikas 20x15x15 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 1,5 cm.. N1-2: Krūties audinys be naviko.  N3: Limfmazgiai (2 l/m) be naviko; pN0(sn).  N4: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pN1c(20mm).. N1-2: Krūties audinys be naviko.  N3: Limfmazgiai (2 l/m) be naviko.  N4: Krūties audinyje 20mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. nan
answer:  0

 23%|██▎       | 149/661 [02:15<07:22,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 8 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10-12%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 23%|██▎       | 150/661 [02:17<08:14,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2) - retroareoliarinė sritis- be naviko   2(N3) - sarginai - be naviko (3)   3(N1) - pašalinta krūtis  - planinis patologinis tyrimas N1 - skubus rentgeninis tyrimas- navikas pašalintas. 3. Krūtis liauka 535 svorio, 19,5x16,5x3 cm su odos lopu 10,5x6 cm. Pjūvyje 2 balkšvi, standūs naviko židiniai: I - 1,1x1x1 cm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 2,3 cm, II - 0,9x0,6x0,5 cm, nuo I-ojo židinio nutolęs 1,5 cm, nuo giliojo rezekcijos krašto - 1 cm, nuo odos - 2,5 cm.. 1. Atipinė lobulinė hiperplazija (ALH; intraduktalinis plitimas). Fibrocistiniai krūties pokyčiai.  2. Reaktyvi limfadenopatija (3 l/m).  3. Multižidininė krūties karcinoma: invazyvi, vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham sis) duktalinė karcinoma (židinys - 10,9mm) ir invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham sis) lobulinė karcinomos (židinys - 12,2mm), suminis tyrimo TNM: pT1c(m)(du naviko židiniai: 10,9mm ir 12,2mm); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).   Duktalinė krūties karcinoma:  Estrogenų receptoriai: reakcija teigiama (stipri branduolių r-ja, 100% naviko ląstelių).   Progesterono receptoriai: reakcija teigiama (vidutinė/stipri branduolių r-ja, 95% naviko ląstelių).   HER2: žema imunohistocheminė raiška (1+).   Ki67 proliferacinis aktyvumas ~10%.  Lobulinė krūties karcinoma (IHC reakcijos atliktos VPC:B23-44687 tyrime):   "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 5%, vietomis iki 10%."  Lobulinė krūties karcinoma in situ (LCIS). Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; kribriforminis, solidinis tipas; -komedo tipo nekrozės). Rezekcijos kraštas be naviko.. 1. Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu; pavieniai latakėliai su negausiu pedžetoidiniu smulkių, monotoniškų (E-cadherin(-)) ląstelių plitimu.  2. Trys(3) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  3. Krūties audinyje - du naviko židiniai: I) (mikro: 12,2mm)formuojamas difuziškai bei trabekulėmis besidėstančių vidutinio kalibro ląstelių, eozinofiliška citoplazma, nežymiai polimorfiškais branduoliais su fokaliai išryškėjusiomis nukleolėmis; navike iki 5 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS). Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse. II) (mikro: 10,9mm) formuojamas solidinių/lizdinių, trabekulinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai, vietomis ryškiai polimorfiškais, hiperchromiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 2 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais ir kribriforminiais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS). Rezekcijos kraštas be naviko.. Blokas 1:  ALH: E-Cadherin(-).   Blokas 19:  II navikas:  Estrogenų receptoriai: stipri branduolių r-ja, 100% naviko ląstelių.   Progesterono receptoriai: vidutinė/stipri branduolių r-ja, 95% naviko ląstelių.   HER2: silpna/vidutinė dalies membranos reakc
answer:  20

 23%|██▎       | 151/661 [02:17<07:42,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm ilgio.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.. Krūties audinį infiltruoja netaisyklingi kribroziniai kompleksai iš vidutiniškai ir ryškiai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis visos membranos nusidažymas 20% naviko ląstel
answer:  1

 23%|██▎       | 152/661 [02:18<07:29,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 bioptatai 22 mm 14 G adata, kalcinatų juose nematyti. 3 fragmentuoti biopsiniai stulpeliai: I - 17 mm; II - 8 mm; III - 7 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė tubulinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 98% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 4%.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).. Krūties audinį infiltruoja duktalinės struktūros (100%) iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.  Šalia naviko latakai su kribriforminiais proliferatais iš navikui analogiškų ląstelių.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 98% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 90%  naviko ląstelių membranoje (pamatinėse dalyse).  Ki67: reakcija branduoliuose, 4% naviko ląstelių.  Progesterono rece
answer:  0

 23%|██▎       | 153/661 [02:19<07:15,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biospiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 11 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 5%.. Krūties audinį infiltruoja juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 30% naviko ląstelių.  Ki67+
answer:  5

 23%|██▎       | 154/661 [02:20<07:05,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 9 mm; II - 8 mm; III - 9 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai/solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+ 12
answer:  0

 23%|██▎       | 155/661 [02:20<06:53,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 10 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%.. Krūties audinį infiltruoja nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai ir vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67+ 25
answer:  1

 24%|██▎       | 156/661 [02:21<07:14,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sarginiai limfmazgiai - extra.   2. Dešinė krūtis su navikais - planinis tyrimas.. 2. Krūtis 581 gramų svorio, 19x17,5x7 cm. Krūties audinyje, vidurinėje dalyje pilkšvas, standus, neaiškių ribų navikas 10x9x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 0,8 cm. Krūties krašte audinys fibrozuotas 6,5x2,5 cm plote. Fibrozėje rusvas, neaiškių ribų židinys 9x9x4 mm, nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo odos - 1,4 cm. Spenelio projekcijoje neaiškių ribų, sustandėjimai iki 6 mm.. 1(Extra). Reaktyvi limfadenopatija (4 l/m).  2. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(10 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Židininė krūties audinio fibrozė ir fibrocistiniai pokyčiai: stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. 1(Extra). 4 limfmazgiai su fokaline parakortekso hiperplazija, sinusų histiocitoze ir neryškia lipomatoze.  2. SPENELIS: normali histologinė struktūra.  NAVIKAS: krūties audinyje - navikas (mikroskopiškai 10 mm), suformuotas fibrozuotoje stromoje ir tarp lipocitų infiltratyviai plintančių lizdinių ir trabekulinių struktūrų bei pabirai ar grandinėlėmis besidėstančių ląstelių saikinga ar vidutinio gausumo švelniai eozinofiliška citoplazma, smulkiais ir vidutinio kalibro, apvaliais/ovaliais, gan monomorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 2/10 DPRL. Šalia kiek dilatuoti kanaliukai su analogiškomis navikui ląstelėmis.  Aplink plačios mažai ląstelingos fibrozės zonos su dilatuotais kanaliukais, klotais suplokštėjusiu epiteliu, ar su stulpiniu ląstelių pokyčiu su apikalinės sekrecijos požymiais (CCAPSS); yra zonų su hemoragijomis, MMN ir makrofagų ar siderofagų židiniais (biopsijos vieta).. nan
answer:  0

 24%|██▍       | 157/661 [02:22<07:35,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas kairės krūties kvadrnatas - planinis tyrimas  2 ėminio aprašas: N2a kraštai  3 ėminio aprašas: N2b kraštai   4 ėminio aprašas: N3: kairės pažasties sarginiai limfmazgiai  5 ėminio aprašas: N4: papildomas kraštas - planinis tyrimas. 1. Krūties sektorius 7,5x5,5x4,2 cm be odos. Pjūvyje neaiškių ribų, rusvas, standus navikas 22x20x18 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm.  2. Riebalinio audinio fragmentas 2x2x0,5 cm. v/m  3. Riebalinio audinio fragmentas 2x1x0,5 cm. v/m  4. Riebalinio audinio fragmentai, bendras dydis 3,5x3,5x1 cm. Rasti 4 limfmazgiai iki 1,4 cm. v/m  5. Riebalinio audinio fragmentas 1,6x1,6x0,6 cm. v/m. 1. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma;   pT2(28 mm) pLVI-0 pN0(0/4).  Imunotipas (pirminis, pagal klinikinius duomenis):  ER imuninė reakcija neigiama.   PR imuninė reakcija teigiama (silpnas branduolių nusidažymas apie 3% navikinių ląstelių).   Reakcija su HER2 neigiama (1+).    Pakartotas/papildytas (operacinėje medžiagoje):  Estrogenų receptoriai: reakcijos nėra.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 50%.    2. Krūties audinys be patologinių pokyčių.  3. Krūties audinys be patologinių pokyčių.  4. Limfmazgiai(4) be patologinių pokyčių.  5. Krūties audinys be patologinių pokyčių.. 1. Solidines, tinklines ir gausias pseudoliaukines (be spindžių) naviko struktūras formuoja ląstelės su negausia saikingai eozinofiline citoplazma, vidutinio dydžio apvalios formos vidutiniškai polimorfiškais branduoliais; mitozių navike >30 / 10 DPRL. Navikas ties giliuoju operaciniu kraštu.  Intravaskulinio plitimo nestebima.  2. Krūties audinys be patologinių pokyčių.  3. Krūties audinys be patologinių pokyčių.  4. Limfmazgiai(4) be patologinių pokyčių.  5. Krūties audinys be patologinių pokyčių.. Blokas 2:  CD117: neigiama (-) atipinėse struktūrose  CK5: neigiama (-) atipinių ląstelių membranoje  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  GATA3: vidutinė ir stipri reakcija 100 proc. atipinių ląstelių branduoliuose  HER2:
answer:  1

 24%|██▍       | 158/661 [02:23<07:20,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~27x20 mm dydžio darinys kairiojoje krūtyje ties 11-2 val. centrinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 11 mm; II - 15 mm; III - 17 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.  .  Progesterono receptoriai: stipri reakcija 90% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.. Bioptatuose (3/3) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos lizdais, grandinėlėmis ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 5/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 90%.  HER2: nusidažiusių naviko ląstelių nėra.  Ki67 proliferacinis aktyvumas 20%.  E-cadherin(+++) membr. r-ja 100%.
answer:  0

 24%|██▍       | 159/661 [02:24<08:02,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Tyrimo Nr. XXIIIBO-2930. Sarginio limfmazgio biopsija + quadrantectomia. Krūties navikas. Makroskopinis aprašymas: Krūties audinio 6x4,8x3,6 cm, iš vienos pusės žymėta tušu. Pjūvyje riebalinis, fibrozinis audinys. Fibrozinis audinys netaisyklingos formos, susiliejantis.  (1,2,3,4),(5,6,7,8) - pjūvis, (9,10),(11,12) - šoniniai kraštai, 13 - iš židinio.. Konsultacijai gauta:  - 4 parafino blokai (žymėti "XXIIIBO-2907"  1-4);  - 7 histologiniai preparatai (žymėti "XXIIIBO-2907", dažyti HE metodu).  - 1 parafino blokas (žymėtas "XXIIIBO 2416");  - 5 histologiniai preparatai, žymėti "XXIIIBO 2416", dažyti HE; ER; PR; Her2; Ki-67 metodais;  - 13 parafino blokų, žymėtų "XXIIIBO-2930" (nuo 1 iki 13);  - 17 histologinių preparatų, žymėtų "XXIIIBO-2930" (nuo 1 iki 13), dažytų HE; PR; ER; Ki-67; Her2 metodais.  Pilnai konsultacijai.. PAPILDYTA  "XXIIIBO-2907" (keturi blokai; limfmazgiai)  Reaktyvi limfadenopatija (galimai 3 l/m).  "XXIIIBO-2416" (vienas blokas; krūties naviko biopsija)  Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma.  "XXIIIBO-2930" (trylika blokų; krūties sektorius)  Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma, ne mažiau kaip pT1c(ne mažiau kaip 1,8 cm) pN(sn)0 (0/3 l/m). LVI2(limfovaskulinė naviko invazija, pavienėse smulkiose struktūrose).  Her2 imunohistocheminė reakcija ribinė (2+).     Nustatyta HER2 geno amplifikacija navike (žr. molekulinio tyrimo aprašymą).. XXIIIBO-2907 (keturi blokai; limfmazgiai)  Nežymi sinusų histiocitozė, minimali lipomatozė limfmazgiuose (galimai trijuose).  "XXIIIBO-2416" (vienas blokas; krūties naviko biopsija)  Krūties audinyje - navikas (smulkias solidines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne blyškiai eozinofiline ar amfofiline  citoplazma, vidutinio kalibro apvalios formos netaisyklingais/polimorfiškais branduoliais; mitozių navike ne mažiau 18 / 10 DPRL.  "XXIIIBO-2930" (trylika blokų; krūties sektorius)  Krūties audinyje - navikas (smulkias ar stambesnes solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne blyškiai eozinofiline ar amfofiline  citoplazma, vidutinio kalibro apvalios formos netaisyklingais/polimorfiškais branduoliais; negausios zonos su pabirai plintančiomis ląstelėmis; mitozių navike iki 22 / 10 DPRL; vidutinio kalibro ar stambūs kanaliukai (su solidiniais analogiškų atipinių ląstelių proliferatais spindžiuose, nekrotinis detritas dalies kanaliukų spindžiuose) navike; naviko struktūros dalyje koaguliuotų kraštų; didžiausias naviko matmuo parafino blokuose: iki 1,8 cm (bendras naviko skersmuo tikėtina didesnis: derinti su makroskopiniu tyrimu); kelios smulkios kraujagyslės/limfagyslės su naviko struktūromis spindžiuose.. XXIIIBO-2416 ( krūties naviko biopsija)  Originalūs stiklai  Estrogenų receptoriai: stiprus-vidutinis branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus-vidutinis branduolių nusidažymas 70% naviko ląstelių.  Her2 imuninė reakci
answer:  2

 24%|██▍       | 160/661 [02:25<07:35,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 9 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6 mm);  (G2; 6 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 8%.. Navikinį audinį 1-me bioptate infiltruoja iki 6 mm :   - netaisyklingi kribroziniai kompleksai ir trabekulės;  - epitelinių smulkių ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 8% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  100

 24%|██▍       | 161/661 [02:26<07:24,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 13 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G1 ; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: vidutinė (++) reakcija, 30% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija paribinė (2+); nustatyta HER2 geno amplifikacija (žr. molekulinio tyrimo aprašymą).  Ki67: proliferacinis indeksas 10%. Karštame taške 30%.  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas).. Krūties audinį 2-se bioptatuose infiltruoja iki 11 mm :   - duktalinės struktūros (30% viso naviko), netaisyklingos kribriforminės struktūros, trabekulės;  - epitelinių vidutinio dydžio ląstelių su netolygaus kontūro, hiperchromiškais, vidutiniškai polimorfiškais branduoliais su pavienėmis nukleolėmis negausioje amfofiliškoje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.  Šalia - kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių, su mikrokalcifikatais ir nekrotiniu detritu spindžiuose.. Blokas 1:  CK14: silpna (+), galimai foninė reakcija 100% naviko ląstelių citoplazmoje. CK14+ mioepitelinis sluoksnis išlaikytas DCIS struktūrose.  Estrogenų receptoriai: vidutinė (++) reakcija, 30% naviko ląstelių branduoliuose.  HER2: vidutinė (++) neci
answer:  30

 25%|██▍       | 162/661 [02:27<07:20,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1  - sarginiai l/m (ekstra)  2 - deš.krūtis (planiškai). 2. Krūtis 1099 gramų svorio, 27x21x6,5 cm.  Krūties audinyje, apatiniame lateraliniame kvadrante balkšvas, standus, neaiškių ribų  navikas 45x29x25 mm, nuo odos nutolęs 1 cm, nuo giliojo rezekcijos krašto - 1,7 cm.. 1. Reaktyvi limfadenopatija (3 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma, TNM (Nr.1-Nr.2): pT2(~4 cm, mikroskopiškai) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės invazijos nėra). R0(radikalus naviko pašalinimas).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5%.. 1. Nežymi sinusų histiocitozė trijuose (3) limfmazgiuose.  2. KRŪTIES SPENELIS: Be patologijos.  KRŪTIS: Krūties audinyje - navikas (grandinėlėmis, trabekulėmis besidėstančios ląstelės su negausia ar kiek gausesne blyškiai eozinofiline citoplazma, vidutinio kalibro apvaliais-ovaliais ar kampuotais, dalis ląstelės periferijoje lokalizuotais be nukleolių branduoliais; mitozių navike iki 3 / 10 DPRL).. 2. Navikas (10 blokas):   Progesterono receptoriai: silpnas branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Proliferacinis aktyvumas (Ki67+++, branduolinė r-ja): 5%.
answer:  0

 25%|██▍       | 163/661 [02:28<07:14,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. sarginiai l/m, planinis.  2. deš krūtis planinis. 1. Riebalinio audinio fragmentai, bendras dydis 5x3x1,5 cm. Rasti 2 limfmazgiai iki 1,5 cm.  2. Krūtis, 603 g svorio, 20x12x8 cm. Odoje pilkšvas, smulkiai gruoblėtas darinys 0,9x0,8x0,1 cm, nuo odos rezekcijos krašto nutolęs 0,4 cm. Krūties audinyje - balkšvi, standūs, neaiškių, spikulinių ribų naviko židiniai:   - I židinys 2,8x1,2x1,8 cm, nuo artimiausio rezekcijos krašto nutolęs 3 cm, nuo odos - 2 cm.  - II židinys 0,4x0,4x0,4 cm (sudėtas visas), nuo I-ojo židinio nutolęs 2 cm, nuo artimiausio rezekcijos krašto - 2,5 cm, nuo odos - 5,5 cm.  - III židinys 0,2x0,2x0,1 cm (sudėtas visas), nuo I-ojo židinio nutolęs 4,5 cm, nuo artimiausio rezekcijos krašto - 3 cm, nuo odos  - 3 cm.. N1: Limfmazgiai (2 l/m) be naviko židinių; pN0(sn).  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2(28mm).. N1: Limfmazgiai (2 l/m) su reaktyviais pokyčiais, be naviko židinių.  N2: Krūties audinyje 28mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.  Krūties audinyje šalia naviko dvi intraduktalinės papilomos 4mm ir 2mm.  Operacinis pjūvis be naviko.  Odoje seborėjinė keratozė.. nan
answer:  0

 25%|██▍       | 164/661 [02:29<06:58,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 bioptatai, vienas kietas.. 3 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 5 mm; III - 5 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja trumpos juostos iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 2%.
answer:  0

 25%|██▍       | 165/661 [02:29<06:56,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 2 biopsiniai stulpeliai iš kairės krūties  BI-RADS 4c darinio   2 but. 1 biopsinis stulpelis iš dešinės krūties BI-RADS 5 darinio. 1. 2 biopsiniai stulpeliai: I - 8 mm; II - 11 mm.  2. Biopsinis stulpelis 13 mm.. Kairė  N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ar vidutinis branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.  ------------------  Dešinė  N2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Kairė  N1: Krūties audinį infiltruoja nedideli kribroziniai/solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ECAD negatyvių ląstelių, mitozių mažiau 1/10 DPRL.  ------------------  Dešinė  N2: Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. nan
answer:  0

 25%|██▌       | 166/661 [02:30<07:19,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Ca mammae sin cT1NxMo I st. 2 kl. - extra  1. kvadranto kraštas - extra  2. kvadranto kraštas - extra  3. sarginai l/m - extra  4. K.krūties kvadrantas.. 4. Krūties sektorius 8x5x2,5 cm, be odos, žymėtas viela. Vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 10x9x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma (8,3 mm židinys), TNM: pT1b(8,3 mm naviko židinys), LVI0(neidentifikuota), pN0(sn)(0/2 l/m). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).  Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai.. 1. Krūties audinyje židininė fibrozė bei sklerozuotos krūties lobulės ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  2. Krūties audinyje židininė fibrozė bei sklerozuotos krūties lobulės ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  3. Du limfmazgiai (2 l/m) su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.  4.  Krūties audinyje - hialinizuotoje stromoje navikas (8,3 mm mikroskopiškai) infiltratyviu augimo frontu, suformuotas trabekulinių ir juostinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, vidutiniškai polimorfiškais, hiperchromiškais branduoliais, nežymiai paryškėjusiais branduolėliais. Mitozių navike iki 3/10DPRL. Limfovaskulinė naviko invazija neidentifikuota( LVI0). Aplinkiniame fibrozuotame krūties audinyje gausūs nežymiai dilatuoti kanaliukaibei lobulės užpildyti solidinių proliferatų iš monomorfiškų ląstelių su apvaliais, kiek ekscentriškais branduoliais. Likusiame krūties audinyje židininė fibrozė, gausūs dilatuoti kanaliukai kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.. Blokas 12:  E-Cadherin: neigiama r-ja invazyviame komponente;  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 25%|██▌       | 167/661 [02:31<07:44,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas-be naviko   2(N2b) - kraštas - skubus tyrimas-be naviko  3(N3) - dešinės pažasties sarginis limfmazgis - skubus tyrimas - 4 l/m be naviko  4(N1)- pašalintas dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 10x6,5x3,5 cm su oda 9x4 cm. Krūties audinyje, pilkšvas, standus, neaiškių ribų navikas 16x15x12 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 1,2 cm.. 1(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  2(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  3(Extra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(16 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu, fokaliai hiperplastišku epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu, fokaliai hiperplastišku epiteliu.  3(Extra). 4 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze bei lipomatoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 16 mm), suformuotas fibrozuotoje stromoje ir fokaliai tarp lipocitų infiltratyviai plintančių dominuojančių tubulinių ir negausių kribriforminių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, ovaliais/apvaliais, vidutiniškai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 4/10 DPRL. Šalia yra dilatuotų kanaliukų su kribriforminiais intraduktaliniais analogiškų navikui proliferatais.  Aplink yra dilatuotų kanaliukų, klotų suplokštėjusiu ar kiek hiperplastišku epiteliu, fokaliai su stulpiniu ląstelių pokyčiu su apikalinės sekrecijos požymiais (CCAPSS) bei kanaliukų su apokrinine metaplazija.. 1. Navikas (18 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 1% naviko ląstelių.
answer:  0

 25%|██▌       | 168/661 [02:32<07:33,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalinta kairė krūtis - planinis tyrimas. Krūtis, 510 g svorio, 20x18x5 cm. Krūties audinys fibrozuotas 6x4x2 cm plote, nuo artimiausio rezekcijos krašto nutolusi 1cm, nuo odos 2,5 cm. Fibrozės zonoje neaiškių ribų sustandėjimas 0,5x0,5x0,4 cm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos - 5 cm.. PAPILDYTAS ATSAKYMAS, ATLIKTI PAPILDOMI HISTOLOGINIAI PJŪVIAI IR IHC REAKCIJOS:  šalia didžiausio DCIS židinio išryškėjo 2,3mm invazijos židinys: gerai diferencijuota (G1; 4 balai pagal Nottinghma) invazinė duktalinė karcinoma; pT1a.  --------------------  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma; pT1c(m) (du naviko židiniai 2,7mm ir 13mm).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ mažiau 1%.  Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS; kribriforminio ir solidinio tipo; trys židiniai 5,5mm; 10mm ir 17mm).. Krūties audinyje trys židiniai (5,5mm; 10mm ir 17mm) su gausiais dilatuotais kanaliukais su intraduktaliniais kribroziniais ir solidiniais proliferatais iš vidutiniškai atipinių ląstelių.  Krūties audinyje 2,7mm ir 13mm invaziniai navikai: smulkūs solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  Rezekcijos kraštas be naviko.. Invazinis navikas ECAD-.
answer:  1

 26%|██▌       | 169/661 [02:33<07:30,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 10,5x5,5x7 cm, su odos lopu 6x1,3 cm ir speneliu. Krūties audinyje pilkšvas, standus navikas 13x10x10 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 0,8 cm.. 1(ekstra). Krūties audinys.  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (5 l/m).    4. Krūties (kairės) invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(13 mm navikas) pN0(sn)(0/5 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija, navikas nuo sektoriaus rezekcijos krašto nutolęs 0,1 mm).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 20%.. 1(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 5 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.    4. Krūtyje - navikas (13 mm) ekspansyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, trabekulinėmis struktūromis, lizdais  besidėstančių ląstelių vidutinio gausumo šviesia eozinofiliška citoplazma, vidutiniais stambiais, vidutiniškai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 16/10 DPRL. Navikas nuo sektoriaus rezekcijos krašto nutolęs 0,1 mm.. Navikas: Synaptophysin/Chromogranin(-).
answer:  0

 26%|██▌       | 170/661 [02:34<07:58,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(1c)- užspenelinė zona, skubu  4(2). sarginiai limfmazgiai, skubu  5(3). Deš. krūties kvadrantas, planinis  6(4a) - viršutinis kraštas, papildomas  7(5a) - apatinis kraštas, papildomas. 5. Krūties sektorius 16x14x6 cm su odos lopu 15x9 cm, žymėtas viela. Vielos projekcijoje, pjūvyje fibrozės zona 6x5x3,5 cm. Krūties vienas kraštas žymėtas metaline kabute. Fibrozės zonoje balkšvas, standus neaiškių ribų navikas 15x12x10 mm, nuo viela žymėto rezekcijos krašto nutolęs 2,5 cm, nuo kabute žymėto krašto 0,6 cm, nuo odos – 2 cm.  6. Riebalinio audinio fragmentas 2,7x1x0,4 cm. v/m  7. Riebalinio audinio fragmentas 3x1,2x0,4 cm. v/m. 1(1a). Krūties paprasta intraduktalinė hiperplazija, stulpinis epitelio pokytis.   2(1b). Krūties fibrocistiniai pokyčiai.   3(1c). Krūties fibrocistiniai pokyčiai.   4(2). Krūties duktalinės karcinomos metastazė (1-ame iš 5 l/m, metastazė 5,5 mm).  5. Krūties invazyvi vidutiniškai diferencijuota (G2/ 7 b. pagal Nottingham) duktalinė karcinoma,   pT1c (15 mm) pN1a(sn) (1 iš 5 l/m; metastazė 5,5 mm); LVI2 (limfovaskulinė naviko invazija smulkiose kraujagyslėse/ limfagyslėse).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-96091, žr. pastabą.   6. Krūties fibrocistiniai pokyčiai.   7. Krūties audinys be patologinių pokyčių.. 1. Krūties audinyje - nežymi stromos fibrozė, grupės latakų su stulpiniu epitelio pokyčiu, fokaline intraduktaline epitelio ir mioepitelinių ląstelių hiperplazija.   2. Krūties audinyje - stromos fibrozė, cistiškai dilatuoti latakai, apokrininė epitelio metaplazija.   3. Krūties audinyje - stromos fibrozė, cistiškai dilatuoti latakai.   4. Limfmazgyje (1-ame iš 5) - žemiau aprašyto naviko metastazė 5,5 mm.   5. Krūties audinyje - histologiškai iš dalies heterogeniškas navikas, formuojamas 2 komponentų:   1) blogai suformuotos liaukinės ir solidinės naviko struktūros, sudarytos iš vidutinio dydžio ir stambių poligonalinių bei stulpinių ląstelių gausia eozinofiliška citoplazma, gana stambiais, ovoidiniais, vidutiniškai polimorfiškais branduoliais su grūdėtu chromatinu, ryškiomis centrinėmis nukleolėmis,   2) trabekulinės struktūros ir grandinėlės, sudarytos iš vidutinio dydžio poligonalinių ląstelių negausia citoplazma, branduoliais, analogiškais aukščiau aprašytam komponentui.   Navike iki 9 mitozių/ 10 DPRL. Limfovaskulinė naviko invazija smulkiose kraujagyslėse/ limfagyslėse.   Krūties audinyje - stromos fibrozė, cistiškai dilatuoti latakai, apokrininė epitelio metaplazija, grupės latakų su stulpiniu epitelio pokyčiu ir intraduktaliniais kalcifikatais.   6. Krūties audinys nežymiai fibrozuotas, su negausiais cistiškai pakitusiais latakais.   7. Krūties audinys be patologinių pokyčių.. 5. Navikas:   e-cadherin(+++)(membr. r-ja) 100%.
answer:  0

 26%|██▌       | 171/661 [02:35<07:38,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 2 biopsiniai stulpeliai iš kairės krūties BI-RADS 5 darinio  2 but. 2 biopsiniai stulpeliai iš dešinės krūties riboto darinio. 1. 2 biopsiniai stulpeliai: I - 18 mm; II - 15 mm.  2. 2 biopsiniai stulpeliai: I - 9 mm; II - 5 mm.. Kairė  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 20-25%.  ------  Dešinė  N2: Krūties fibrocistiniai pokyčiai, paprastoji intraduktalinė epitelio hiperplazija.. Kairė  N1: Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 7/10 DPRL.  ------  Dešinė  N2: Krūties audinio fibrozė, smulkių kanaliukų proliferacijos židiniai, cistinė kanaliukų dilatacija, kanaliukų epitelio apokrininė metaplazija, vietomis intraduktaliniai epitelio ir mioepitelio proliferatai be atipijos.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  1

 26%|██▌       | 172/661 [02:36<07:13,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%, vietomis iki 15%.. Krūties audinį infiltruoja pavienės duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+
answer:  12

 26%|██▌       | 173/661 [02:37<06:54,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozės pavienės.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ %.
answer:  0

 26%|██▋       | 174/661 [02:37<06:41,  1.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 10 mm ilgio.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 35%.. Krūties audinį nedideli netaisyklingi solidiniai kompleksai ir trabekulės iš ryškiai polimorfiškų ląstelių, mitozių iki 2-3/1 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis visos membranos nusidažymas 15% naviko ląsteli
answer:  1

 26%|██▋       | 175/661 [02:38<06:42,  1.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2A - extra  2. extreaN2B- kraštai - be naviko  3. N3- sarginiai - be naviko -extra  4. N1- sektorius -planinis patologinis tyrimas N1- skubus Ro tyrimas - MK pašalinti. 4. Krūties sektorius 8x4,5x5,5 cm, su odos lopu 8x2,5 cm, žymėtas dvejomis vielomis. Tarp vielų neaiškių ribų standus fibrozės plotas 3x2,2 cm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 2,8 cm.. N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (invazinis navikas 5,2mm).  Aukšto laipsnio intraduktalinė karcinoma (DCIS/DIN3; solidinis ir komedo tipas; pakitimai 10mm plote aplink invazinį naviką).  N2ab: Krūties audinys be naviko, paprasta intraduktalinė epitelio hiperplazija.  N3: Limfmazgiai (2 l/m) be naviko; pN0(sn).. N1: Krūties audinyje 10mm plote intraduktaliniai solidiniai/kribroziniai polimorfiškų ląstelių kompleksai ir 5,2mm invazinis navikas iš nedidelių kribrozinių/solidinių kompleksų vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.  N2a: Krūties audinys be naviko.  N2b: Krūties audinyje intraduktaliniai kribroziniai epitelio ir mioepitelio proliferatai, navikinio augimo nėra.  N3: Limfmazgiai (2 l/m) be naviko.. nan
answer:  0

 27%|██▋       | 176/661 [02:39<06:39,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 but. 1 biopsinis stulpelis iš kairės pažasties  l/m  2 but. 1 biopsinis stulpelis iš kairės krūties BI-RADS 5 darinio. 1. Biopsinis stulpelis 7 mm ilgio.  2. Biopsinis stulpelis 10 mm ilgio.. N1: Krūties duktalinės karcinomos metastazė limfmazgyje.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%, vietomis iki 20%.. N1: Limfmazgio bioptatas su žemiau aprašytu naviku.  N2: Krūties audinį infiltruoja negausios duktalinės struktūros, smulkūs netaisyklingi kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  0

 27%|██▋       | 177/661 [02:40<07:09,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas   2(N2b) - kraštas - skubus tyrimas (invazyvus navikas krašte  3(N3) - dešinės pažasties sarginis limfmazgis skubus tyrimas - 3l/m be naviko  4(N4) - papildomas kraštas - planinis tyrimas  5(N1) - pašalintas dešinės krūties kvadrantas  - planinis tyrimas. 4. Riebalinio audinio fragmentai, bendras dydis 3x1,6x1 cm.  5. Krūties sektorius 12x6,5x8,5 cm su oda 10x4,5 cm, žymėtas viela. Krūties audinys fibrozuotas 8x5,5 cm plote, fibrozėje pilkšvas, standus, neaiškių ribų navikas 15x13x10 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 3,2 cm. Rastas intramamarinis limfmazgis 0,6 cm.. 1(Extra). Krūties lobulinė karcinoma (2,5 mm židinys). Lobulinė karcinoma in situ (LCIS).  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (3 l/m).  4. Riebalinis audinys.  5. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1c(16 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).  HER2 imuninė reakcija: neigiama (1+).   Lobulinė karcinoma in situ (LCIS).  Reaktyvi limfadenopatija (1 intramamarinis l/m).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - 2,5 mm židinys, suformuotas infiltratyvių smulkių trabekulinių žemiau (Nr.5) aprašyto naviko struktūrų. LCIS šalia.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu; keli kanaliukai su apokrinine metaplazija; pavieniai smulkūs kalcifikatai.  3(Extra). 3 limfmazgiai su fokaline parakortekso hiperplazija, sinusų histiocitoze ir keliais smulkiais histiocitų agregatais; neryški lipomatozė.  4. Brandus riebalinis audinys su negausiomis kraujagyslėmis.  5. Krūties audinyje - ribotas navikas (mikroskopiškai 16 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių trabekulinių struktūrų, grandinėlėmis, smulkiomis grupėmis ar pabirai besidėstančių ląstelių saikinga švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 1/10 DPRL. Aplink dilatuoti kanaliukai, užpildyti analogiškomis navikui ląstelėmis (LCIS).  LIMFMAZGIS: fokalinė parakortekso hiperplazija ir neryški sinusų histiocitozė.. 1. Navikas (24 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.
answer:  1

 27%|██▋       | 178/661 [02:41<06:50,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stulpeliai. 3 biopsiniai stulpeliai: I - 15 mm; II - 12 mm; III - 13 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) metaplastinė (matriksą produkuojanti) krūties karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 90%.. Krūties audinį infiltruoja smulkios ryškiai polimorfiškos ląstelės, stroma vietomis chondroidinė, mitozių iki 20/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 90%.
answer:  1

 27%|██▋       | 179/661 [02:42<06:41,  1.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1  biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 8 mm);  (G2; 7 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 80% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 20%.. Krūties audinį 1-me bioptate infiltruoja iki 8 mm :   - solidiniai kompleksai;  - epitelinių vidutinio dydžio ląstelių su ryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - su mitozėmis iki 5/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  CD31: stipri teigiama (+) membraninė reakcija kraujagyslių endotelyje be atipinių struktūrų spindyje  Estrogenų receptoriai: stipri (+++) reakcija, 80% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reak
answer:  20

 27%|██▋       | 180/661 [02:43<06:42,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 11 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 40%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai, juostos ir trabekulės iš ryškiai polimorfiškų ląstelių, mitozių iki 14/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 40%.
answer:  1

 27%|██▋       | 181/661 [02:44<08:29,  1.06s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 10 mm; II - 12 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 20/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 60%.
answer:  1

 28%|██▊       | 182/661 [02:45<09:02,  1.13s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a - kraštai skubus tyrimas  2. N2b - kraštai skubus tyrimas   3. N1 pašalintas markiruotas mikrokalcinatų plotas - planas. 1. Krūties sektorius 10,5x10,5x4 cm su oda 10x2,5 cm, žymėtas 3 vielomis.   - plote tarp I ir II vielų, besitęsiantis - neaiškių ribų, pilkšvas spikulinis židinys su aplinkine riebalinio audinio reakcija 4,5x1x1,3 cm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 3,5 cm.  - III vielos projekcija be makroskopinių pokyčių.. Paruošti pjūviai Prosigna.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Riebalinis - fibrozinis audinys.   3. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(m)(7 mm ir 6 židiniai ~ 1mm) NX(l/m nešalinti) LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis, komedo tipai), židiniai 4,5 cm plote. R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Riebalinis - fibrozinis audinys.   3. Krūtyje - navikas (7 mm ir 6 židiniai ~ 1mm) infiltratyviu augimo frontu, suformuotas trabekulinėmis struktūromis, lizdais besidėstančių ląstelių negausia vidutinio gausumo eozinofiliška citoplazma, smulkiais vidutiniais stambiais, vidutiniškai ryškiai polimorfiškais,  nereguliaraus kontūro, ovaliais apvaliais, vezikulizuotais branduoliais ryškiomis nukleolėmis; mitozių 7/10 DPRL.    Greta gausūs dilatuoti kanaliukai su intraduktaliniais solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.. 3. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas/vidutinis/stiprus dalies/visos membranos nusidažymas xx% naviko ląstelių.  Ki67 proliferacinis aktyvumas 20%.
answer:  1

 28%|██▊       | 183/661 [02:46<08:09,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 4 biopsiniai stulpeliai.. 4 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 12 mm; III - 6 mm; IV - 6 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.. Krūties audinį infiltruoja nedideli netaisyklingi kribroziniai ir solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ %.
answer:  0

 28%|██▊       | 184/661 [02:47<07:31,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 14 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja smulkios duktalinės struktūros ir kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas.  Ki67+ 8%.
answer:  0

 28%|██▊       | 185/661 [02:48<07:04,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm ilgio.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20%, vietomis iki 35%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 20
answer:  1

 28%|██▊       | 186/661 [02:49<06:53,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas ~40x20 mm neaiškių ribų deformuoto liaukinio audinio plotas atitinkantis mamogramose matomus pakitimus dešiniojoje krūtyje ties 1-2 val. vidurinėje/periferinėje dalyse, paimti keturi biopsiniai stulpeliai histologijai.. 4 biopsiniai stulpeliai: I - 7 mm; II - 12 mm; III - 9 mm; IV - 14 mm.. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) galimai lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 1%.. Bioptatuose (4/4) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos grandinėlėmis ir pabirai besidėstančių ląstelių negausia eozinofiliška citoplazma, nežymiai polimorfiškais, smulkaus kalibro, ovalais branduoliais; mitozės neidentifikuotos.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas pavienėse ląstelėse.  Ki67 proliferacinis aktyvumas 1%.  E-cadherin(+++) membr. r-ja 100%; p120_caten
answer:  100

 28%|██▊       | 187/661 [02:49<06:39,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1  biopsinis  stulpelis. Biopsinis stulpelis 12 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė karcinoma, galimai metaplastinė.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 25%, vietomis iki 40%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, vietomis su plokščialąstelinės diferenciacijos požymiais, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 25%, vietomis iki 40%.
answer:  1

 28%|██▊       | 188/661 [02:50<06:27,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 stulpeliai. Gautas 1 biopsinis stulpelis 17 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.. Krūties audinį infiltruoja solidiniai kompleksai, juostos, trabekulės, pavienės tubulės (<10%) iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Blokas 1:  CK14: mioepitelinio išklojimo navike nėra.   Estrogenų receptoriai: stipri (+++) reakcija, 90% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari re
answer:  1

 29%|██▊       | 189/661 [02:51<06:21,  1.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas dešinės krūties kvadrantas  - planinis tyrimas  2 ėminio aprašas: N2a ir N2b kraštai - planinis tyrimas. 1. Krūties sektorius 8x6x4 cm, su odos lopu 6,5x3,5 cm. Pjūvyje pilkšvas, elastingas miksoidinis navikas 2,4x2,2x1,9 cm, nuo artimiausio  rezekcijos krašto nutolęs 0,1 cm, nuo odos -  3 cm.  2(2a). Riebalinio audinio fragmentas 2,5x2x0,8 cm. v/m  3(2b). Riebalinio audinio fragmentas 3x2,5x1,2 cm. v/m. N1: Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham); pT2 (24mm).  N2ab: Krūties ir riebalinis audinys be naviko.. N1: Krūties audinyje 24mm navikas: mucininėje stromoje aiškių ribų netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  N2ab: Krūties ir riebalinis audinys be naviko.. nan
answer:  0

 29%|██▊       | 190/661 [02:52<06:14,  1.26it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 7 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 5% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+, HER2 geno amplifikacija nenustatyta.  Ki67+ 20%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 5% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos ar stiprus dalies membranos nusidažymas 20% naviko ląstel
answer:  1

 29%|██▉       | 191/661 [02:52<06:10,  1.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 9 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 8%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 10% naviko ląstelių.  Ki67+
answer:  8

 29%|██▉       | 192/661 [02:53<06:06,  1.28it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 bioptatai 12 G 22 mm iš ~2 cm kieto darinio. 2 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 15 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 12% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Krūties audinį infiltruoja netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 12% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+ 5%
answer:  0

 29%|██▉       | 193/661 [02:54<07:02,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1a pašalintas pagrindinis čiuopiamas navikas kartu su markiruotu naviku ties 9/10 valanda su vielute - planinis tyrimas  2 ėminio aprašas: N1b: pašalintas markiruotas navikas su vielute ties 3 val - planinis tyrimas  3 ėminio aprašas: N2a ir N2b kraštai - planinis tyrimas  4 ėminio aprašas: N2a ir N2b kraštai - planinis tyrimas  5 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - planinis tyrimas. 1. Krūties sektorius 7,5x4x3 cm su oda 4x2,2 cm, kraštas be odos žymėtas viela. Vielos projekcijoje - krūties audinys fibrozuotas visame plote (fibrozės plotas sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 4,2 cm. Odos lopo projekcijoje pilkšvas, standus, neaiškių ribų navikas 16x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos 0,9 cm.  2. Riebalinio fibrozinio audinio fragmentas 2,2x1,6x1,3 cm, žymėtas viela. Vielos projekcijoje krūties audinys fibrozuotas visame plote, su cistine ertme 0,3 cm. v/m  3. Riebalinio audinio fragmentas 1x0,6x0,3 cm. v/m  4. Riebalinio audinio fragmentas 0,7x0,7x0,4 cm. v/m  5. Riebalinio audinio fragmentai, bendras dydis 3,3x2,7x1,2 cm. Rasti 2 limfmazgiai iki 1,4 cm. v/m. 1(1a - pagrindinis navikas).  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma;   pT1c(16 mm) pLVI-0 pR0.   Imunofenotipas (nustatytas priešoperaciniame biopsijos tyrime):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 5%.  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).     2(1b - markiruotas navikas).   Krūties fibrocistiniai pokyčiai: atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė.    3(2a - kraštai). Riebalinis audinys be patologinių pokyčių.  4(2b - kraštai). Riebalinis audinys be patologinių pokyčių.    5(sarginis limfmazgis). Limfmazgiai (2) be patologinių pokyčių; pN(sn)0.. 1(1a - pagrindinis navikas). Krūties audinio desmoplastiškoje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, gausiomis tinklinėmis struktūromis besidėstančių ląstelių negausia eozinofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 5/10 DPRL. Greta gausūs dilatuoti latakai su intraduktalinėmis kribriforminėmis ir solidinėmis struktūromis iš analogiškų navikui ląstelių. Atipiniai epitelio pokyčiai 1 mm nuo krašto. Intravaskulinio plitimo nestebima.  2(1b - markiruotas navikas). Fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku ne=ymiai atipiniu epiteliu, smulkių kanaliukų poliferacijos zonos, =idininiai intraduktaliniai stromos proliferatai.  3(2a - kraštai). Riebalinis audinys be patologinių pokyčių.  4(2b - kraštai). Riebalinis audinys be patologinių pokyčių.  5(sarginis limfmazgis). Limfmazgiai (2) be patologinių pokyčių.    apokrininė metaplazija,  smulkūs kalcifikatai spindžiuose.. nan
answer:  1

 29%|██▉       | 194/661 [02:56<08:00,  1.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - k. pažasties sarginiai l/m (ekstra)  2 - k. krutis su speneliu, planiniam tyrimui  3 - deš. krūties liauka po NSM, planiniam tyrimui. 2. Krūtis 344 gramų svorio 18x15x4 cm su odos lopu 12x1,5 cm. Krūties audinyje - neaiškių ribų, nehomogeniška, lobulizuota standi balkšvai gelsvų nedidelių 1 mm atstumu besidėstančių mazgų suformuota zona 24x15x15 mm su nuo odos nutolusi 0,7 cm, nuo giliojo rezekcijos krašto - 0,3 cm. Aplinkiniame krūties audinyje 2 elastingos pilkšvos fibrozės zonos: I - 8x6x2,5 cm, II - 7x3,5x2 cm. Rastas 1 limfmazgis 0,5 cm.  3. Krūties sektorius 13x10x3 cm su balšvos elastingos ar kiek standokos fibrozės zona 7,5x5,5x3 cm.. 1(ekstra). "K. pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).   2. "K. krūtis su speneliu": krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1a(m) (naviko židiniai: I - 4,5 mm; II - 1,5 mm; III - 1,5 mm; IV - 1 mm) N0 (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%.    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis ir komedo tipai; pokyčių zona ~25 mm skersmens).     Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Incidentinė krūties fibroadenoma (0,6 mm).     3. "Deš. krūties liauka po NSM": ryški krūties audinio fibrozė (g.b. post-terapiniai pokyčiai).   SUMINIS TNM: ypT0 (vitalinio naviko neidentifikuota) N0 (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Krūties fibrocistiniai pokyčiai (sklerozuojanti ir mikroglandulinė adenozė).. 1(ekstra). "K. pažasties sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2. "K. krūtis su speneliu":   SPENELIS: normali histologinė struktūra.   "PAKITUSI ZONA" (~25 mm skersmens): krūties audinyje su gausiu perifokaliniu limfocitiniu infiltratu ir tretinių limfoidinių struktūrų formavimusi dėstosi įvairaus dydžio solidiniai, kribriformoniai intraduktaliniai žemiau aprašytos išvaizdos naviko ląstelių kompleksai su centrinėmis komedo tipo nekrozėmis ir kalcifikatais. Fokaliai nuo intraduktalinių kompleksų prasideda nedideli izoliuoti invazyvaus naviko židiniai (žr. aprašymą žemiau).   NAVIKAI (mikroskopiškai identifikuoti - atskiri židiniai: I - 4,5 mm; II - 1,5 mm; III - 1,5 mm; IV - 1 mm):  krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios trabekulinės,  nereguliaraus kontūro, įvairaus dydžio lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo eozinofiline citoplazma, vidutinio dydžio kiek nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 25/10 DPRL.   APLINKA: fokaliai krūties audinys ryškiai fibrozuotas su vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu. Atskiras nedidelis židinys, kurį sudaro proliferuojančių fibroblastų stroma ir suspausti kanaliukai, kloti dvisluoksniu epiteliu.   INTRAMAMARINIS LIMFMAZGIS(1): su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais.   GILUSIS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.  3. "Deš. krūties liauka po NSM": ryškiai fibrozuotas krūties audinys su homogeniškos fibrozės zonomis, kanaliukais, klotais dvisluoksniu epiteliu. Fokaliai suspausti ar kiek dilatuoti kanaliukai formuoja nedidelius židinius.. 2. Navikas (blokas 7):   Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 30% nav
answer:  0

 30%|██▉       | 195/661 [02:57<08:11,  1.06s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2). Kairės pažasties sarginiai limfmazgiai, skubu  4(3). Kairės krūties kvadrantas, planinis. 4. Krūties sektorius 9x6x3 cm su odos lopu 9x2 cm, žymėtas viela. Pjūvyje 3 balkšvi standūs, naviko židiniai:  - I židinys 25x14x12 mm, nuo artimiausio rezekcijos krašto nutolęs 0,5 cm, nuo odos – 1,5 cm, nuo vielos - 4,5 cm;  - II židinys 4x4x3 mm (sudėtas visas),nuo artimiausio rezekcijos krašto nutolęs <0,1 cm, nuo odos – 2,5 cm, nuo vielos - 1 cm, nuo I židinio - 3 cm;  - III židinys 5x5x4 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,6 cm, nuo odos – 3 cm, nuo vielos - 3 cm, nuo I naviko - 3 cm, nuo II naviko - 3,5 cm.  Rezekcijos kraštas dažytas mėlynu tušu.. 1(Extra). Krūties audinys.  2(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT(m)1c(3 naviko židiniai: 13 mm, 4,7 mm ir 3 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). II naviko struktūros <0,1 mm nuo rezekcijos krašto.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu; grupė kiek dilatuotų kanaliukų, klotų kiek hiperplastišku epiteliu.  3(Extra). 2 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  4. Krūties audinyje - 3 riboti identiškos struktūros navikai (mikroskopiškai 13 mm, 4,7 mm ir 3 mm), suformuoti fibrozuotoje stromoje su fokaline elastoze plintančių dominuojančių tubulinių ir kribriforminių bei negausių trabekulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, smulkiais ir vidutinio kalibro, ovaliais, gan monomorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 2/10 DPRL. Pavieniai smulkūs kalcifikatai. Perineurinė invazija. Negausūs dilatuoti kanaliukai su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais bei grupė kanaliukų, klotų hiperplastišku epiteliu. Židininė PMN infiltracija. II naviko struktūros <0,1 mm nuo rezekcijos krašto.. 4. Navikas I (11 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 5% naviko ląstelių.   nusidažiusių naviko ląstelių nėra.  Navikas II: CK5(-).
answer:  0

 30%|██▉       | 196/661 [02:58<07:31,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 3 biopsiniai stulpeliai.. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 9 mm; III - 10 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 1-2%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstel
answer:  0

 30%|██▉       | 197/661 [02:59<07:26,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  ca mammae sin - extra  1. pjūvio kraštai, ekstra.   2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 10x6x5 cm su oda 8x3 cm. Krūties audinyje, pilkšvas, standus, neaiškių ribų navikas 22x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 1,2 cm.. 1-2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma. SUMINIS TNM: pT2(22 mm navikas) N0(sn)(1 l/m) LVI-4 (limfovaskulinė invazija smulkiose gyslose ir venose). Radikalus pašalinimas. Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis ir kribriforminis tipai).  Imunofenotipas:  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 40%.. 1-2(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 1 limfmazgis su I/II folikulais, sinusų histiocitoze.  4. Krūties audinyje - 22 mm dydžio (mikroskopiškai) navikas, suformuotas solidinių kompleksų, trabekulių, lizdų bei pavienių tubulių. Naviko ląstelės su vidutinio gausumo, amfofiliška citoplazma, stambiais, netolygaus kontūro, ryškiai polimorfiškais branduoliais su makronukleolėmis. Mitozių navike iki 27/10DPRL. Naviko desmoplastiškoje stromoje gausi monomorfonuklearų infiltracija. Navikas plinta latakų spindžiuose, endotelizuotuose spindžiuose ir stambiose venose.   Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių.. Blokas 12:  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 40% naviko ląstelių.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.
answer:  0

 30%|██▉       | 198/661 [03:00<08:21,  1.08s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. Deš. pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: 2. Kairės pažasties sarginiai limfmazgiai, skubu  3 ėminio aprašas: 3. Deš. krūtis, planinis  4 ėminio aprašas: 4. Kairė krūtis, planinis. 3. Dex. Krūtis 2118 gramų svorio , 23x21x9,5 cm. Krūties viršutinių kvadrantų riboje -  skiltėtas, rusvas, standus  navikas 2,7x2,3x2,5 cm, nuo rezekcijos krašto nutolęs 1,4 cm, nuo odos - 2,5 cm. Krūties auidinyje viršutiniame lateraliniame kvadrante - balkšva, standi , aiškių ribų (I) zona 1,3x0,7x0,4 cm, nuo rezekcijos krašto nutolusi 2,4 cm, nuo odos - 2 cm, nuo naviko - 2,5 cm. Krūties audinyje , centrinėje dalyje balkšva, elastinga (II) fibrozės zona 9x7x5,5cm, nuo rezekcijos krašto nutolusi 0,5 cm, nuo odos - 1,5 cm.  4. SIN. Krūtis 2025 gramų svorio , 22x21x9 cm. Krūties viršutiniame medialiniame kvadrante - pilkšvas, standus, gerai ribotas  (I) navikas 3,5x3,5x2,3 cm, nuo rezekcijos krašto nutolęs 3 cm, nuo odos - 2 cm. Krūties auidinyje viršutiniame medialiniame kvadrante - balkšvas, standus, neaiškių ribų (II) navikas  0,9x0,7x0,6cm, nuo rezekcijos krašto nutolęs 1,8 cm, nuo odos - 5,5 cm, nuo (I)naviko - 0,5 cm. Krūties audinyje , viršutiniame lateraliniame kvadrante  zona  9x5x5 cm su dilatuotais, standžiais latakais iki 0,8 cm skersmens, didžiausias latakas nuo rezekcijos krašto nutolęs 1,4 cm.. 1(ekstra). DEŠINĖ. Duktalinės karcinomos mikrometastazė limfmazgyje (1/4 l/m, 0,4mm). Limfovaskulinė invazija.   2(extra). KAIRĖ. Reaktyvi limfadenopatija (3 l/m).    3. DEŠINĖ. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma su daline neuroendokrinine diferenciacija, SUMINIS TNM: pT2(27 mm) pN1a(sn)(1/4 l/m, 0,4mm). LVI-2(limfovaskulinė invazija). Vidutinio žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas), gausūs židiniai iki 1 cm.    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    4. KAIRĖ. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma neuroendokrinine diferenciacija, SUMINIS TNM: pT2(m)(35 mm ir 7 mm navikai) pN0(sn)(0/3 l/m). LVI-2(limfovaskulinė invazija). Vidutinio žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas).  Židininiai fibrocistiniai pokyčiai.    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.. 1(ekstra). 1 iš 4 limfmazgių aprašyto naviko metasatzė 0,4 mm. Limfovaskulinė invazija.  2(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  3. Spenelis: normali histologinė struktūra.   Krūtyje - navikas ekspansyviu augimo frontu, suformuotas lizdais ir solidiniais plotais besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 19/10 DPRL. Limfovaskulinė invazija.  Aplinkiniame krūties dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaustų kanaliukų zonos.    4. Spenelis: normali histologinė struktūra.   Krūtyje - navikas (35 mm ir 7 mm navikas) ekspansyviu augimo frontu, suformuotas lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 5/10 DPRL. Limfovaskulinė invazija.  Aplinkiniame krūties dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.. 3. Navikas (17 blokas): Synaptophysin(+++) citopl. r-ja 10%;  HER2 silpnas dalies membranų nusidažymas <5%.  4. Navikas (39 blokas): Synaptophysin(+++) citopl. r-ja 100%;  HER2 silpnas dalies membranų nusidažymas <5%.
answer:  0

 30%|███       | 199/661 [03:01<07:58,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas - be naviko   2(N2b) - kraštas - skubus tyrimas - be naviko  3(N3) - kairės pažasties sarginis limfmazgis - skubus tyrimas - 2 l/m be naviko  4(N1) - pašalintas markiruotas kairės krūties kvadrantas planinis tyrimas. 4(N1). Viela žymėtas krūties sektorius 9,5x4,5x3 cm su odos lopu 8x1,8 cm. Vielos projekcijoje, pjūvyje balkšvas, gan aiškių ribų navikas 9x6x5 mm, nuo artimiausio rezekcijos krašto nutolęs 0,6 cm, nuo odos – 2,2 cm.. 1(2a). Riebalinis audinys.  2(2b). Krūties audinys; intraduktaliniai mikrokalcifikatai.  3. Reaktyvi limfadenopatija (2 l/m).  4(1). Krūties invazyvi, gerai diferencijuota (G1; 4 balai pagal Nottingham sis) duktalinė karcinoma, pT1b(navikas - 9mm) pN0(sn)(0/2 l/m).  IHC reakcijos atliktos VPC:B23-43418 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%."  Krūties fibrocistiniai pokyčiai.. 1(2a). Riebalinis audinys su fibrovaskulinėmis septomis.  2(2b). Riebalinis audinys su fibrozės zonomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu; intraduktalinių mikrokalcifikatų židiniais.  3. Du(2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4(1). Krūties fibroziniame audinyje - navikas, formuojamas netaisyklingų duktalinių, pavienių kribriforminių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, nežymiai, vietomis vidutiniškai polimorfiškais branduoliais; navike iki 2 mitozių/10 DPRL. Aplinkiniame krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu.. nan
answer:  0

 30%|███       | 200/661 [03:02<07:43,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2A)- kraštas -skubi histologija - be naviko  2(N2b)- kraštas -skubi histologija - be naviko  3(N3)- pašalinti sarginis l/m - skubi patologija - be naviko  4(N1)-pašalintas sektorius - planinis tyrimas. 4. Krūties sektorius 11x8,5x6 cm su oda 10x6 cm, odoje, krūties audinyje injekuotas metileno mėlis. Krūties audinyje - pilkšvas, standus, mucininis navikas 48x32x46 mm, nuo giliojo rezekcijos krašto (dažyto mėlynu tušu) nutolęs 0,1 cm, nuo odos - 2 cm. Sektoriuje rastas suriebėjęs limfmazgis 1,7 cm (sudėtas visas).. 1. Fibrocistiniai krūties pokyčiai: paprastoji intraduktalinė hiperplazija.  2. Riebalinis audinys be naviko plitimo.   3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) mucininė karcinoma, TNM: pT2(navikas 48 mm), pN0(sn)(0/3 l/n), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).. 1(2a). Krūties audinyje gausios lobulės ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu bei keli nežymiai dilatuoti kanaliukai, kloti hiperplastišku epiteliu..   2(2b). Riebalinio audinio fragmentas su fibrozinėmis septomis ir kraujagyslėmis.  3. Du limfmazgiai (2 l/m) su sinusų histiocitoze.  4. Krūties audinyje navikas (48 mm makroskopiškai), suformuotas gausiuose ekstraląsteliniuose mucinuose besidėstančių smulkių solidinių, tubulinių ir negausių mikropapilinių struktūrų. Naviko ląstelės vidutinio gausumo eozinofiline citoplazma, vidutiniškai polimorfiškais branduoliais su negausiomis smulkiomis nukleolėmis. Mitozių navike iki 5/10 DPRL. Limfovaskulinis naviko plitimas neidentifikuotas. Navikas nuo sektoriaus rezekcijos krašto nutolęs per 0,4 mm. Krūties audinyje identifikuotas limfmazgis su sinusų histiocitoze ir pavieniais antriniais limfiniais folikulais.. Blokas 15:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 30%|███       | 201/661 [03:03<07:36,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.  4. krūties sektorius, planinis.. 4. Krūties sektorius 7x5,5x4 cm su oda 6,5x4,5 cm. Krūties audinyje - pilkšvas standus, spikulinių kraštų navikas 1,8x1,5x1,8 cm, nuo giliojo rezekcijos krašto nutolęs mažiau 0,1 cm, nuo odos - 1,3 cm.. Paruošti pjūviai Prosigna tyrimui.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Krūties duktalinės karcinomos mikrometastazė limfmazgyje (1/3 0,4 mm).  4. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(17 mm navikas) pN1mi(sn)(1/3 l/m mikro MTS 0,4 mm) LVI-0(limfovaskulinė invazija neidentifikuota). Perineurinis plitimas. R0(navikas nuo sektoriaus rezekcijos krašto nutolęs <0,1 mm).     Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 1 iš 3 limfmazgių aprašyto naviko mikrometastazė 0,4 mm.  4. Krūtyje - navikas (17 mm) infiltratyviu ekspansyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, ovaliais apvaliais, vezikulizuotais branduoliais ryškiomis nukleolėmis;  mitozių 24/10 DPRL.  Perineurinis plitimas.. 2. 3 blokas: CK5/CK14+ mioepitelis; E-cadherin(+++) membr. r-ja 100%  3. Navikas (13 blokas):  HER2: nusidažiusių naviko ląstelių nėra.
answer:  0

 31%|███       | 202/661 [03:04<07:24,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštai  - skubus tyrimas - be naviko  2(N2b). kraštai  - skubus tyrimas - be naviko  3(N3). kairės pažasties sarginis limfmazgis - skubus tyrimas -  2l/m be naviko  4(N1): pašalintas kairės krūties kvadrantas - planinis tyrimas. 4(N1). Krūties sektorius 9x5,5x5 cm su odos lopu 6,3x3 cm žymėtas viela. Vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 11x10x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos 1,8 cm. Navikas histologiniam ištyrimui sudėtas visas.. 1(N2a). Krūties audinys.  2(N2b). Krūties audinys.  3(N3). Reaktyvi limfadenopatija (2 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,1 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės naviko invazijos nėra).    Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 12% (hot spot 15%).. 1(N2a). Krūties audinyje - pavieniai smulkūs fibrozės židiniai su negausiais smulkiais kanaliukais, išklotais dvisluoksniu epiteliu.  2(N2b). Krūties audinyje - pavieniai smulkūs fibrozės židiniai su negausiais smulkiais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N3). Sinusų histiocitozė dviejuose (2) limfmazgiuose.  4(N1). Krūties audinyje - navikas: Solidines, trabekulines, pavienes smulkias tubulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne amfofiline citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 3 / 10 DPRL.. 4(N1). Navikas (12 blokas):  Her2 nusidažiusių ląstelių nėra; Synaptophysin(-).
answer:  0

 31%|███       | 203/661 [03:05<08:31,  1.12s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas  2(N2b) kraštai - skubus tyrimas -(N2B krašte invazyvus židinys)  3(N3): kairės pažasties sarginis limfmazgis - skubus tyrimas 2l/m be naviko  4(N5a) - kraštai  - skubus tyrimas be naviko  5(N5b) - kraštai  - skubus tyrimas be naviko  6(N1): pašalintas žymėtas kairės krūties verifikuotas navikas - planinis tyrimas  7(N4): dešinės krūties markiruotas plotas - planinis tyrimas  8(N6) - papildomas kraštas  iš kairės krūties. 6(N1). Krūties sektorius 8x7x3 cm su odos lopu 5x1,5 cm, žymėtas dviem vielomis. Tarp vielų pilkšvas, neaiškių ribų navikas 0,7x0,5x0,6 cm (sudėtas visas). Makroskopiškai siekiantis rezekcijos kraštą 4 mm ilgyje, nuo odos nutolęs 3,5 cm. Krūties sektorius fibrozuotas 6,5x3,5x2 cm plote, fibrozė siekia rezekcijos kraštą, nuo odos nutolusi 1,5 cm. Fibrozės zonoje standus plotas su paryškėjusios spalvos riebaliniu audiniu (II naviko židinys?) 0,8x0,7x0,8 cm, makroskopiškai siekiantis rezekcijos kraštą, nuo naviko nutolęs 1,8 cm (sudėtas visas)  7(N4). Krūties sektorius 11x8x6 cm su odos lopu 11x4,5 cm, žymėtas trim vielomis. Tarp vielų balkšva, elastinga fibrozės zona 9x5x5 cm, makroskopiškai siekianti rezekcijos kraštą, nuo odos nutolusi 1 cm. Sudėtas kas antras fibrozės pjūvis. Atokiau nuo vielų, krūties audinyje pilkšvas, apvalus židinys 0,9x0,7x0,0,7 cm (sudėtas visas), nuo rezekcijos krašto nutolęs 0,7 cm.  8(N6). Riebalinio audinio fragmentas 1,5x1,2x0,5 cm. v/m. 1(N2a). Krūties fibrocistiniai pokyčiai.   2(N2b). Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, kribriforminė).   3(N3). Krūties duktalinės karcinomos metastazė limfmazgyje (1 iš 3 l/m, metastazė 1,6 mm).   4(N5a). Krūties fibrocistiniai pokyčiai, paprasta intraduktalinė hiperplazija.  5(N5b). Krūties fibrocistiniai pokyčiai, stulpinis epitelio pokytis.  6(N1). Krūties invazyvi daugiažidininė blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma,   pT1b(m) (2 naviko židiniai 6,5 mm ir 4 mm) pN1mi (1 iš 3 l/m, metastazė 1,6 mm); LVI2 (limfovaskulinė naviko invazija smulkiose limfagyslėse/ kraujagyslėse).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-17740, žr. pastabą.   Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, kribriforminė, plokščia, solidinė su comedo nekroze).   7(N4). Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS/ DIN1c - DIN2, kribriforminė ir mikropapilinė), pTis.   Intraduktalinės papilomos.   8(N6). Krūties audinio fibrozė.. 1. Krūties audinyje - nežymi stromos fibrozė, reti kanaliukai ir atrofiškos lobulės, pavieniai cistiškai dilatuoti latakai su apokrinine epitelio metaplazija.   2. Krūties audinyje - nežymi stromos fibrozė, kelios grupės latakų su intraduktaliniais kribriforminiais proliferatais, formuojamais vidutinio dydžio ir stambių ląstelių su vidutiniškai ar ryškiai polimorfiškais, hiperchromiškais branduoliais.   3. Limfmazgyje (1-ame iš 3, "poekstriniame" pjūvyje) - žemiau aprašyto naviko metastazė 1,6 mm.   4. Krūties audinyje - stromos fibrozė, cistiškai pakitę latakai su apokrinine epitelio metaplazija, keli kanaliukai su intraduktaline epitelinių ir mioepitelinių ląstelių hiperplazija.   5. Krūties audinyje - stromos fibrozė, cistiškai pakitę latakai, stulpinis epitelio pokytis su apikalinės sekrecijos požymiais latakuose ir kanaliukuose.   6. Krūties audinyje - 2 invazyvaus naviko židiniai 6,5 mm ir 4 mm, formuojami trabekulinių, smulkių solidinių grupių ir pavienių liaukinių struktūrų, sudarytų iš vidutinio dydžio ir stambių ląstelių eozinfiliška citoplazma, ryškiai polimorfiškais ovoidiniais branduoliais su stambiomis nukleolėmis, grūdėtu chromatinu.   Limfovaskulinė naviko invazija smulkiose limfagyslėse/ kraujagyslėse.   Aplinkiniame krūties audinyje - grupės latakų su intraduktaliniais kribriforminiais, solidiniais ir plokščiais proliferatais su comedo tipo nekroze, formuojamais vidutinio dydžio ir stambių ląstelių su ryškiai polimorfiškais branduoliais su ryškiomis nukleolėmis, netolygiai grūdėtu chromatinu.    7. Krūties audinyje - kelios grupės latakų ir pavieniai latakai su intraduktaliniais kribriforminiais proliferatais, sudarytais iš vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais su ryškiomis nedidelėmis nukleolėmis. Keli latakai kloti aukštu stulpiniu epiteliu ir pavienėmis mikropapilinėmis struktūromis, su santykinai monotoniškais pailgais, hiperchromiškais branduoliais. Intraduktaliniuose epiteliniuose proliferatuose yra smulkių kalcifikatų.   Keli nežymiai dilatuoti latakai su minimaliai šakotomis smulkiomis papilinėmis struktūromis, klotomis mioepitelinėmis ir epitelinėmis ląstelėmis.   8. Krūties audinyje - židininė kolagenizuota stromos fibrozė.. nan
answer:  0

 31%|███       | 204/661 [03:06<08:09,  1.07s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 18 G automatine biopsine adata punktuotas ~6x12 mm dydžio cistinis su izoechogenišku intracistiniu komponentu darinys labiausiai panašus į papilomą dešiniojoje krūtyje ties 8 val. vidurinėje dalyje, paimti trys biopsiniai stulpeliai histologijai (I buteliukas).   2. 18 G automatine biopsine adata punktuotas ~35 mm ilgyje plėstas latakėlis su izoechogenišku turiniu (labiausiai panašu į papilomą) dešiniojoje krūtyje ties 12 val. centrinėje dalyje areolės srityje, paimti trys biopsiniai stulpeliai histologijai (II buteliukas).  3. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~21x26 mm dydžio navikas dešiniojoje krūtyje ties 1-2 val. vidurinėje dalyje, paimti trys biopsiniai stulpeliai histologijai (III buteliukas).. 1. 3 fragmentuoti biopsiniai stulpeliai: I - 5 mm; II - 4 mm; III - 4 mm.  2. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 5 mm; III - 5 mm.  3. Gauti 2 biopsiniai stulpeliai: I - 6 mm; II - 4 mm ir bioptatas 0,1 cm.. N1: Intraduktalinė krūties papiloma.  N2: Krūties cista.  N3: Gerai diferencijuota (G1, 4balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. N1: Krūties audinyje dilatuotame kanalėlyje šakotos intraduktalinės papilinės struktūros iš fibrozinės stromos, išklotos dvisluoksniu epiteliu.  N2: Krūties audinyje cista, išklota suplokštėjusiu epiteliu. Papilomos komponentų nėra.  N3: Krūties audinį infiltruoja duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 12
answer:  1

 31%|███       | 205/661 [03:07<08:18,  1.09s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Kairės pažasties sarginiai limfmazgiai, skubu  2. Kairė krūtis - planinis. 2. Krūtis 682 gramų svorio, 19,5x15,5x4,5 cm. Krūties audinyje balkšvi standūs neaiškių ribų naviko židiniai:    - I - viršutinių kvadrantų riboje, 2,7x2x2,3 cm skersmens, nuo odos nutolęs 1,8 cm, nuo artimiausio rezekcijos krašto - 0,9 cm;   - II - 1,1 cm nuo I židinio, 1x0,7x0,7 cm skersmens, nuo odos nutolęs 4 cm, nuo artimiausio rezekcijos krašto - 1 cm;   - III - 1 cm nuo I židinio, 0,5x0,5x0,5 cm skersmens, nuo odos nutolęs 2,5 cm, nuo artimiausio rezekcijos krašto - 3,5 cm;   - IV - 1 cm nuo I židinio, 0,3x0,2x0,3 cm, nuo odos nutolęs 3,5 cm, nuo artimiausio rezekcijos krašto - 1,5 cm.   Krūties audinyje smulkios cistos iki 0,4 cm.. 1(ekstra). "Kairės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT2(m) (navikai: I - 27 mm; II - 10 mm; III - 5 mm; IV - 3 mm) N0(sn) (0/3 l/m),   LVI-0 (definityvios limfovaskulinės invazijos neidentifikuota).     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties lobulinė intraepitelinė neoplazija (LCIS).  Krūties žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS: solidinis ir kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   Krūties gilusis rezekcijos kraštas be naviko.. 1(ekstra). "Kairės pažasties sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2. SPENELIS: normalios histologinės struktūros.   NAVIKO ŽIDINIAI (I - 27 mm; II - 10 mm; III - 5 mm; IV - 3 mm):   krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės, nedideli lizdai struktūros, trumpos "grandinėlės", solidinės naviko struktūros, suformuotos mažai kohezyvių vidutiniškai polimorfiškų ląstelių, vidutinio gausumo eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su  smulkiomis nukleolėmis; mitozių iki 5/10 DPRL.   APLINKA: zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais. Keli nedideli solidiniai ir kribriforminiai intraduktaliniai nežymiai polimorfiškų kohezyvių naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, apokrinės metaplazijos zonomis.   GILUSIS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 2. Navikas (blokas 12):  HER2: silpna (+) necirkuliari reakcija, 10% naviko ląstelių membranoje.
answer:  1

 31%|███       | 206/661 [03:08<07:38,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 3 mm; III - 5 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja smulkūs solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 8%.
answer:  0

 31%|███▏      | 207/661 [03:09<07:10,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 14 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 3%.. Krūties audinį 2-se bioptatuose infiltruoja iki 12 mm :   - pavienės duktalinės struktūros, juostos ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++) membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki
answer:  3

 31%|███▏      | 208/661 [03:10<07:24,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. (2a) kraštai - skubus tyrimas - be naviko;  2. (2b) kraštai - skubus tyrimas - be naviko;   3. (N3) Kairės pažasties limfmazgis - skubus tyrimas 3 l/m  - viename iš trijų limfmazgių makrometastazė.  4. (N1) pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 5x4x2,5 cm be odos, žymėtas viela. Vielos projekcijoje - pilkšvas, neaiškių ribų židinys 9x9x6 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm.. PAPILDYTA (HER2 FISH tyrimas):  1(Extra). Krūties audinio fibrozė.  2(Extra). Krūties audinio fibrozė.  3(Extra). Duktalinės karcinomos metastazė 1/3 limfmazgyje (5,7 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(8 mm) N(sn)1a(mts 1/3 l/m; 5,7 mm), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Her2 imuninė reakcija: ribinė (2+).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, plokščia).  Krūties intraduktalinės papilomos (dalis su vidutinio laipsnio DCIS).. 1(2a)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(2b)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). Viename iš 3 limfmazgių - žemiau (Nr.4) aprašyto naviko metastazė (5,7 mm).  4. Krūties audinyje - ribotas navikas (mikroskopiškai 8 mm), suformuotas fibrozuotoje stromoje plintančių lizdinių ir trabekulinių, pavienių tubulinių ir kribriforminių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 3/10 DPRL. Negausūs smulkūs kalcifikatai. Šalia naviko ir fokaliai atokiau yra dilatuotų ir kiek smulkesnių kanaliukų su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais bei grupė dilatuotų latakų su papilinėmis intraduktalinėmis struktūromis, klotomis dvisluoksniu epiteliu, fokaliai su DCIS plitimu.. 1. Navikas (11 blokas): HER2 imuninė reakcija: vidutinis dalies ir visos, fokaliai stiprus dalies membranos nusidažymas 80% naviko ląstelių.  14 blokas: CK14+ negausios mioepitelinės ląstelėse papilomose su DCIS.  18 blokas: DCIS su išlaikytu CK14+ mioepi
answer:  1

 32%|███▏      | 209/661 [03:11<07:06,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Kairė krūtis, planinis. Krūtis, 133,5 gramų svorio, 14x10x3 cm. Pjūvyje fibrozės zona 4x2x1,5 cm, nuo giliojo rezekcijos krašto nutolusi 0,1 cm, nuo odos - 1,5 cm. Krūties audinys difuziškai fibrozuotas.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1a (daugybiniai invazijos židiniai, didžiausias 1,5mm).  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 12%.  Krūties aukšto laipsnio intraduktalinė karcinoma (DIN3/DCIS, kribriforminis ir komedo tipas; du navikiniai židiniai - 40mm plote ir 9mm plote).  Rezkecijos kraštas be naviko.. Krūties audinyje 40mm plote intraduktaliniai solidiniai ir kribroziniai polimorfiškų ląstelių proliferatai, vietomis su nekrozės židiniais spindyje. Daugybiniai mikroskopiniai invazijos židiniai iki 1,5mm: solidiniai/kribroziniai kompleksai vidutinio ar ryškaus polimorfizmo ląstelių, mitozių  mažiau 1/10 DPRL.   Tokios pačios struktūros 9mm DCIS židinys aplinkiniame krūties audinyje.  Rezekcijos kraštas be naviko.. Invazinis navikas:  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 60% naviko ląstelių.  Ki67+ 1
answer:  10

 32%|███▏      | 210/661 [03:12<07:30,  1.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). Sektoriaus krašai.-extra   2(N2). Sektoriaus kraštai.-extra   3(N3). Sarginiai l/n. -extra  4(N5). Papildomas kraštas - LCIS įtarimas.-extra  5(N4). K.krūties sektorius su naviku.. 5. Krūties sektorius 10x7x4 cm su oda 9x2,5 cm, žymėtas viela ir metileno mėliu viename sektoriaus krašte. Viela kiaurai perveria sektorių. Krūties audinyje šalia vielos - balkšvas, standus, spikulinių kraštų navikas 16x12x15 mm, nuo giliojo rezekcijos krašto (dažyta mėlynu tušu) nutolęs 0,3 cm, nuo odos - 5,5 cm. Ties viela, 2,5 cm nuo naviko krūties riebalinis audinys standus, su nekrozės zonomis ir hemoragijomis 1,3x1x1 cm plote, pakitusi zona nuo rezekcijos krašto nutolusi 0,5 cm, nuo odos - 1 cm.. 1. Krūties žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS). Krūties lobulinė karcinoma in situ (LCIS).   2. Krūties audinys.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties lobulinė karcinoma in situ (LCIS). Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija.  5. Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 12 mm), pN0(sn)(0/2 l/n), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.HER2:reakcijos nėra (0).  Žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS). Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai: paprastoji intraduktalinė hiperplazija, apokrinine metaplazija.. 1. Krūties audinyje pavieniai dilatuoti kanaliukai užpildyti kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Šalia gausūs nežymiai dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.   2. Krūties audinyje smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  3. Du limfmazgiai (2 l/m) su sinusų histiocitoze.  4. Krūties audinyje gausūs nežymiai dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta nežymiai dilatuoti kanaliukai kloti fokaliai hiperplastišku epiteliu ar epiteliu su apokrinine metaplazija.  5. Krūties audinyje - navikas (12 mm mikroskopiškai), suformuotas tubulinių, kribriforminių bei trabekulinių struktūrų iš vidutinio kalibro eozinofiline citoplazma ląstelių, nežymiai polimorfiškais, smulkiai grūdėtu chromatinu branduoliais; mitozių 1/10 DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Greta naviko negausūs dilatuoti kanaliukai su kribriformine proliferacija iš monomorfiškų, negausia šviesiai eozinofiline citoplazma ląstelių apvaliais, kiek hiperchromiškais branduoliais. Krūties audinyje gausūs nežymiai dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta nežymiai dilatuoti kanaliukai kloti fokaliai hiperplastišku epiteliu ar epiteliu su apokrinine metaplazija. Fokaliai krūties audinyje - histiocitų, svetimkūnio tipo gigantinių daugiabranduolių ląstelių ir limfocitų infiltracija.. Blokas 20:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 32%|███▏      | 211/661 [03:13<07:49,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1. 1 - sarginiai l/m - extra  N2. Kairė krūtis su navikais.. 2. Krūtis 690 gramų svorio, 22x16x8 cm. Visas krūties audinys balkšvas, fibrozuotas.  Periferijoje, fibrozėje, rusvas, neaiškių ribų sustandėjimas 14x10 mm plote, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos 1,7 cm.   Nuo sustandėjimo 3 cm atstumu, pilkšvas, neaiškių ribų židinys 12x10x6 mm, nuo giliojo rezekcijos krašto nutolęs 2,5 cm, nuo odos - 2 cm.. 1(ekstra). Sarginiai l/m. Reaktyvi limfadenopatija (2 l/m).    2. Krūties invazinė duktalinė karcinoma,   pT1c(m) (naviko židiniai iki 10,4 mm)   pN0(sn)(2 l/m)    pLVI-0 (limfovaskulinė invazija neidentifikuota)   pR0(radikalus pašalinimas).  Diferenciacijos laipsniai navikuose:   I navike (9,6 mm) - blogai diferencijuota (G3, 9 balai pagal Nottingham),   II navike (10,4 mm) - gerai diferencijuota (G1, 3 balai pagal Nottingham),   III navike (5,4 mm) - vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham).       I naviko imunotipas nustatytas priešoperacinėje biopsijoje (B23-6714):  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 80%.    II naviko imunotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.    Lobulinė karcinoma in situ (LCIS).. 1(ekstra). Sarginiai l/m. 2 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.    2. Krūties audinyje - trys morfologiškai skirtingi navikai:  I navikas (9,7 mm dydžio mikroskopiškai): gausios limfocitų infiltracijos apsupsti solidiniai kompleksai iš ląstelių gausia eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais branduoliais su stambiomis nukleolėmis. Mitozių navike iki 20/10DPRL.  II navikas (10,4 mm dydžio mikroskopiškai): desmoplastiškoje stromoje plintančios infiltratyvios tubulinės (90%) ir kribriforminės struktūros, iš stulpinių ląstelių eozinofiliška citoplazma, smulkiais, ovoidiškais, gan monotoniškais branduoliais su pavienėmis smulkiomis nukleolėmis. Mitozių navike <1/10DPRL.    III navikas (5,4 mm dydžio mikroskopiškai): fibrozinėje stromoje plintančios infiltratyvios trabekulės ir lizdai, suformuoti ląstelių negausia tamsiai eozinofiliška citoplazma, ovoidiškais, vidutiniškai polimorfiškais, vesikuolizuotais branduoliais. Mitozių navike iki 2/10DPLR.      Aplinkiniame krūties audinyje gausūs latakėliai su solidiniais proliferatais iš ląstelių apvaliais, hiperchromiškais, gan monotoniškais branduoliais, plintantys mažiausiai 11 mm už invazyvaus naviko ribų.  Atokiau stambesnės lobulės su tankiai išsidėsčiusiais kanalėliais (adenozės židiniai), apokrininė metaplazija.. Blokas 13: CD31+ endotelis ir naviko stroma; naviko limfovaskulinė invazija neidentifikuota).  II navikas (Blokas 15):  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 70%  naviko
answer:  ą

 32%|███▏      | 212/661 [03:14<07:25,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra (be naviko);  2(2b). Kraštai - extra (be naviko);  3. Sarginiai l/m - extra (be naviko);  4(1). Sektorius skubus rentgeninis tyrimas, navikas pašalintas - planinis tyrimas.. 4. Krūties sektorius 11x4x4,5 cm su oda 9x2,5 cm, žymėtas viela. Krūties audinyje, kvadrante - pilkšvas, neaiškių ribų sustandėjimas 6x6x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,5 cm.. 1(2a). Kraštai - krūties audinys be patologinių pokyčių.  2(2b). Kraštai - krūties audinys be patologinių pokyčių.  3. Sarginiai l/m - limfmazgis (1) be patologinių pokyčių.    4. Krūties sektorius.   Invazinė duktalinė (kitaip neklasifikuojama) karcinoma;   (G1; 3 b. pgl. Nottingham sist.);   pT1b pN0 pLVI-0 pR0.  Imunotipas (priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 4%.. 1(2a). Kraštai - krūties audinys be patologinių pokyčių.  2(2b). Kraštai - krūties audinys be patologinių pokyčių.  3. Sarginiai l/m - limfmazgis (1) be patologinių pokyčių.  4. Krūties sektorius. Krūties audinį infiltruoja navikas (mikroskopiškai 5 mm) , kurį sudaro:   - duktalinės netaisyklingos struktūros (95% viso naviko);  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. nan
answer:  0

 32%|███▏      | 213/661 [03:15<07:08,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 biopsinis stulpelis iš kairės krūties BI-RADS 5 darinio   2 but. 3 biopsiniai stulpeliai iš latakų su kalcinatais bei riboto darinio dešinėje krūtyje.. 1. 1 biopsinis stulpelis 15 mm ilgio.   2. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 9 mm.. 1. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 10%. Karštame taške 20%.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.    2. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 10%.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.. 1.Krūties audinį infiltruoja netaisyklingi kribroziniai kompleksai ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.  2. Krūties audinį infiltruoja duktalinės struktūros (<10%), netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. 1. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) cirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių. Karštame taške 20%.  Progesteron
answer:  1

 32%|███▏      | 214/661 [03:16<06:47,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas švelniai hipoechogeninis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~21×15 mm dydžio darinys dešiniojoje krūtyje ties 11 val. periferinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 16 mm; II - 14 mm; III - 14 mm.. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma.   Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.   Her2 imuninės r-ja: neigiama (0).   Ki67 proliferacinis aktyvumas iki 10%.. 3 bioptatai: krūties audinyje plinta netaisyklingos tubulinės ir kribriforminės struktūros, suformuotos ląstelių eozinofiline citoplazma, ovoidiniais, su neryškiu polimorfizmu, stratifikuotais branduoliais. Mitozių 2/10 DPRL.. Navikas:   CK14+ mioepitelinio sl. nėra.   Synaptophysin(-);  Estrogenų receptoriai: (++++)(brand. r-ja) 100%.   Progesterono receptoriai: (++++)(brand. r-ja) 100%.  HER2: nusidažiusių naviko ląstelių membranų nėra.  Ki67 proliferacinis aktyvumas iki 10%.
answer:  0

 33%|███▎      | 215/661 [03:17<07:07,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- Deš. krūties sektorius, planinis. 3(2). Riebalinio audinio fragmentas 9x6x5 cm, be odos lopo, žymėtas 3 vielomis. Pjūvyje, neaiškių ribų, balkšvi susiliejantys židiniai iki 3,5x3x2 cm, bendras židinių dydis 5,5x4x2,5 cm. Vietomis židiniai siekia rezekcijos kraštą. Juoda spalva dažytas gilusis kraštas, poodinis kraštas dažytas raudonai, medialinis kraštas - mėlynai, lateralinis kraštas dažytas žalia spalva. Pjūviai imti nuo viršaus į apačią.. 1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, pT1a(1,6 mm) NX(limfmazgiai nešalinti), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Imunofenotipas:   Estrogenų receptoriai: vidutinis branduolių nusidažymas 70% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  HER2 imuninė reakcija: neigiama (0).  Ki67: 10%.  Krūties aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DIN3/DCIS)(solidinė, kribriforminė, komedo).  DCIS struktūros siekia medialinį rezekcijos kraštą, 0,15 mm nuo poodinio rezekcijos krašto, 0,5 mm nuo giliojo krašto.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  3. Krūties audinyje - fibrozės zona su gausiais dilatuotais kanaliukais su solidiniais ir kribriforminiais intraduktaliniais proliferatais (fokaliai su komedo nekrozėmis ir kalcifikatais), suformuotais ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutinio ir kiek stambesnio kalibro, ovaliais/apvaliais, polimorfiškais, su nukleole branduoliais. Šalia - ribotas navikas (mikroskopiškai 1,6 mm), suformuotas fibrozuotoje stromoje plintančių solidinių, lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 1/10 DPRL.  DCIS struktūros siekia medialinį rezekcijos kraštą, 0,15 mm nuo poodinio rezekcijos krašto, 0,5 mm nuo giliojo krašto.. 1. 17 blokas:  INVAZYVI KARCINOMA:   Estrogenų receptoriai: vidutinis branduolių nusidažymas 70% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  Pr
answer:  10

 33%|███▎      | 216/661 [03:18<07:10,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- deš. pažasties sarginiai limfmazgiai, skubu  4(3)- deš. krūties sektorius, planinis. 4(3). Krūties sektorius 6,5x5x2,5 cm, su odos lopu 4x2 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 13x11x10 mm (sudėtas visas), nnuo artimiausio rezekcijos krašto 0,2 cm, nuo odos 2,5 cm.. 1(1a). Viršutinis kraštas. Krūties audinys be patologinių pokyčių.    2(1b). Apatinis kraštas. Krūties audinys be patologinių pokyčių.    3(2). Deš. pažasties sarginiai limfmazgiai. Reaktyvi limfadenopatija (3 l/m).     4(3). Deš. krūties sektorius. Krūties invazyvi duktalinė karcinoma,    vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą),   pT1c (13 mm navikas)   pN0(sn)(3 l/m)   pLVI-0 (limfovaskulinė invazija neidentifikuota)   pR0(radikalus pašalinimas).   Naviko imunotipas nustatytas biopsijoje (B23-15090):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.    Krūties fibrocistiniai pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).. 1(1a). Viršutinis kraštas. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2(1b). Apatinis kraštas. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(2). Deš. pažasties sarginiai limfmazgiai. limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.  4(3). Deš. krūties sektorius.  Krūties audinyje - navikas, suformuotas lizdų, trabekulių, kribriforminių ir solidinių struktūrų. Naviko ląstelės su negausia, eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais, fokaliai su smulkiomis nukleolėmis. Mitozių navike iki 6/10DPRL.  Aplinkiniame krūties audinyje smulkūs, dalis ektatiški latakai, kloti dvisluoksniu epiteliu, su periduktaline limfocitine infiltracija. Dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. nan
answer:  0

 33%|███▎      | 217/661 [03:19<07:13,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas kairės krūties kvadrantas  - planinis tyrimas  2 ėminio aprašas: N2a kraštai  3 ėminio aprašas: N2b kraštai  4 ėminio aprašas: N3: kairės pažasties sarginiai limfmazgiai  5 ėminio aprašas: N4: papildomas kraštas. 1. Krūties sektorius 4,5x4x3 cm, be odos, žymėtas viela. Vielos projekcijoje neaiškių ribų, gelsvai pilkšvas, standokas židinys 10x10x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, žymėtas metaliniu spaustuku.  2. Riebalinio/fibrozinio audinio fragmentas 1,5x1x0,7 cm. v/m  3. Riebalinio/fibrozinio audinio fragmentas 1,2x1x0,6 cm. v/m  4. Riebalinio audinio fragmentai, bendras dydis 3x2,5x0,6 cm. Rasti 3 limfmazgiai iki 1,2 cm. v/m  5. Riebalinio audinio fragmentas 1,5x1x0,4 cm. v/m. 1. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė tubulinė karcinoma;   pT1b(10 mm) pLVI-0 pN0(0/4) pR0.  Naviko imunotipas (priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 98% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 4%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).    2. Riebalinio audinio fragmentas be patologinių pokyčių.  3. Riebalinio audinio fragmentas be patologinių pokyčių.  4. Limfmazgiai(3) be patologinių pokyčių.  5. Riebalinio audinio fragmentas be patologinių pokyčių.. 1. Krūties audinį infiltruoja duktalinės struktūros (100%) iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.  Šalia naviko latakai su kribriforminiais proliferatais iš navikui analogiškų ląstelių. Invazyvios struktūros židiniškai 1 mm nuo operacinio krašto.  Intravaskulinio plitimo nestebima.  2. Riebalinio audinio fragmentas be patologinių pokyčių.  3. Riebalinio audinio fragmentas be patologinių pokyčių.  4. Limfmazgiai(3) be patologinių pokyčių.  5. Riebalinio audinio fragmentas be patologinių pokyčių.. nan
answer:  0

 33%|███▎      | 218/661 [03:20<07:19,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.deš krūtis, planinis.   2. deš pažasties sarginiai l/m, planinis.. 1. Krūtis, 1068 g svorio, 28x11,5x5 cm. Krūties audinyje pilkšvas, standus, aiškių ribų, kiek mucininis I navikas 12x12x10 mm (krašte pereina į skiltėta struktūrą), esantis 3 cm nuo giliojo rezekcijos pjūvio, nuo odos - 1,2 cm. Šalia naviko 0,3 cm atstumu, pilkšvas, ribotas židinys 6x5x4 mm. Spenelio projekcijoje - pilkšvas, standus II navikas 20x20x12 mm, esantis 1,6 cm nuo giliojo rezekcijos pjūvio, nuo odos - 2,6 cm.  2. Riebalinio audinio fragmentai, bendras dydis 3,5x3x0,8 cm. Rasti 3 limfmazgiai iki 2,4 cm.. Paruošti pjūviai Prosigna.  1. Krūties invazyvi blogai diferencijuota (G3, 8. pagal Nottingham) multižidininė karcinoma: mucininė karcinoma (6,5 mm, 13 mm židiniai) ir mišri mucininė-duktalinė karcinoma (20,5 mm židinys).  SUMINIS TNM: pT2(m)(6,5 mm, 13 mm, 20,5 mm navikai) pN0(sn)(0/3) LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis, komedo tipai). R0(radikali rezekcija).    Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 75% naviko ląstelių.  HER2: neigiama (1+)  Ki67: proliferacinis indeksas 15%.    2. Sarginiai limfmazgiai. Reaktyvi limfadenopatija (3 l/m).. 1. SPENELIS: normalios histologinės struktūros.   NAVIKAS (6,5 mm, 13 mm, 20,5 mm) ekspansyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais ir solidiniais plotais mucinuose besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 13/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.   2. 3 limfmazgiai su sinusų histiocitoze antriniais folikulais ir lipomatoze.. 1. Navikas (14 blokas):   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 75% naviko ląstelių branduoliuose.  HER2: silpnas - vidutinė necirkuliari reakcija, 10%  naviko l
answer:  ą

 33%|███▎      | 219/661 [03:21<07:14,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2). Kairės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko - extra.  2(1). Pašalinta kairė krūtis - planinis tyrimas.. 2. Krūtis 859 gramų svorio, 20x14x5 cm dydžio. Krūties audinyje, lateralinių kvadrantų riboje, rusvas, gleivėtas, elastingas navikas 5,5x4,2x3,5 cm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos - 0,2 cm. Oda naviko projekcijoje be makroskopinių pokyčių.. 1(ekstra). Reaktyvi limfadenopatija (3 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mišri duktalinė - mucininė karcinoma, SUMINIS TNM: pT3(55 mm navikas) pN(sn)(0/3 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis tipas).    Imunofenotipas(biopsijoje):   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 5% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.. 1(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  2. Krūtyje - navikas (55 mm) infiltratyviu ir ekspansyviu augimo frontu, suformuotas trabekulinėmis struktūromis, lizdais ir solidiniais plotais ir mikropapilinėmis struktūromis, fokaliai ekstraląsteliniuose mucinuose(~50% ploto) besidėstančių ląstelių vidutinio gausumo ryškia eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 7/10 DPRL. Greta dilatuoti kanaliukai su intraduktaliniais solidiniais proliferatais iš analogiškų navikui ląstelių.. HER2: silpna-vidutinė r-ja <10% naviko ląstelių.
answer:  1

 33%|███▎      | 220/661 [03:22<07:20,  1.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.N2a kraštai  - skubus tyrimas - be naviko   2.N2b kraštai  - skubus tyrimas - be naviko  3.N1 pašalintas kairės krūties kvadrantas - planinis tyrimas  4.N3 kairės pažasties sarginiai limfmazgiai - planinis tyrimas. 3(N1). Krūties sektorius 9x6x3,6 cm su odos lopu 7,5x1,9cm. Pjūvyje balkšvas, stansu, aiškių ribų navikas 1,4x1,4x1,1 mm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos – 1,9cm. Greta naviko - du atskiri balkšvi standūs židiniai:  I - 0,3x0,3x0,3x, nuo naviko nutolęs 0,6 cm, nuo artimiausio rezekcijos krašto - 2 cm.  II - 0,3x0,3x0,3x, nuo naviko nutolęs 2 cm, nuo I židinio - 0,7cm, nuo artimiausio rezekcijos krašto - 1 cm.  4(N3). Riebalinio audinio fragmentas 10,5x7,5x3 cm (Pažasties narveliena cm). Rasta 16 limfmazgių iki 1,5 cm.. 1(N2a). Krūties audinys.  2(N2b). Krūties audinys.  3(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(m) (1,4 cm, 0,3 cm ir 0,3 cm židiniai) pN1a(2/16 l/m, mts 0,2 cm ir 0,7 cm; ekstranodalinis plitimas). LVI2(limfovaskulinė naviko invazija, smulkiose struktūrose).  4(N3). Duktalinės adenokarcinomos metastazės 2/16 limfmazgiuose (mts 0,2 cm ir 0,7 cm; ekstranodalinis plitimas).. 1(N2a). Krūties audinyje - negausūs smulkūs fibrozės židiniai su negausiais smulkiais ar kiek stambesnio kalibro kanaliukais, išklotais dvisluoksniu epiteliu.  2(N2b). Krūties audinyje - negausūs smulkūs fibrozės židiniai su negausiais smulkiais ar kiek stambesnio kalibro kanaliukais, išklotais dvisluoksniu epiteliu.  3(N1). Krūties audinyje - trys panašios architektūrinės ir citologinės išvaizdos naviko židiniai: solidines, trabekulines, smulkias tubulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navikuose iki 12 / 10 DPRL.   4(N3). Aukščiau aprašyto naviko metastazės 2/16 limfmazgiuose (mts 0,2 cm ir 0,7 cm; ekstranodalinis plitimas).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 25%.. 3(N1). HER2: silpnas(+) membraninis dažymasis 20% naviko ląstelių.
answer:  1

 33%|███▎      | 221/661 [03:22<06:54,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais spikuliuotais kontūrais, su UG fiksuojama kraujotaka, ~10x12 mm dydžio navikas dešiniojoje krūtyje už spenelio/spenelyje, paimti trys biopsiniai stulpeliai histologijai.. 3 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 13 mm; III - 14 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja duktalinės struktūros, smulkūs kribroziniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 2%.
answer:  0

 34%|███▎      | 222/661 [03:23<06:33,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Papildyta HER2 FISH.  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+).  Ki67 proliferacinis aktyvumas 3%.  HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).. Bioptate krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais besidėstančių ląstelių negausia-vidutinio gausumo eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 2/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: vidutinis visos membranos nusidažymas 15% naviko ląstelių.  Ki67 proliferacinis aktyvumas 3%.
answer:  0

 34%|███▎      | 223/661 [03:24<06:43,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. deš krūtis su pažasties l/m, planinis.. Krūtis 960 g svorio, 21x17x6 cm su raumens fragmentu 3x1,7x0,5 cm. Krūties audinyje daugybiniai, balkšvi standūs navikai:  I - 1,7x1,4x1 cm, makroskopiškai infiltruojantis raumeninį audinį, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos 2,5 cm;   II - 1,1x0,9x0,7 cm, nuo I naviko nutolęs 1 cm, nuo artimiausio rezekcijos krašto nutolęs mažiau 0,1 cm, nuo odos - 1,3 cm;   III - 1x0,5x0,7 cm, nuo I naviko nutolęs 1,5 cm, nuo artimiausio rezekcijos krašto nutolęs 2,2 cm, nuo odos - 3 cm;  IV - 3,3x2,2x3 cm, nuo III naviko nutolęs 1 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos - 3,5 cm;  V - 2,5x1x1,5 cm, nuo IV naviko nutolęs 2 cm, nuo artimiausio rezekcijos krašto nutolęs 3,7 cm, nuo odos - 1,2 cm;  VI - 0,6x0,4x0,4 cm, nuo V naviko nutolęs - 4 cm, artimiausio rezekcijos krašto nutolęs 4 cm, nuo odos - 2,5 cm;  VII - 1,5x1,2x1,2 cm, nuo VI naviko nutolęs - 2 cm, artimiausio rezekcijos krašto nutolęs 1,7 cm, nuo odos - 2 cm;  VIII (intramamarinis limfmazgis) - 1,1x0,6x0,5 cm, nuo VII naviko nutolęs - 1 cm, artimiausio rezekcijos krašto nutolęs 2 cm, nuo odos - 2 cm;  Atskirai tame pačiame inde pažastie narveliena 9x5x2 cm. Rasta 20 limfmazgių iki 1 cm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma su mikropapiliniu komponentu; pT2(m) (7 navikiniai židiniai nuo 6mm iki 33mm); pN3a (16 iš 20 l/m).. Krūties audinyje 7 navikiniai židiniai (nuo 6mmm iki 33mm): negausios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 3/10 DPRL. Visuose navikiniuose židiniuose yra daugiau ar mažiau išreikštas mikropapilinis augimo komponentas.  Iš rastų 20 limfmazgių 16 su metastazėmis iki 10mm.  Naviko židiniai giliajame rezekcijos krašte.. nan
answer:  0

 34%|███▍      | 224/661 [03:25<06:31,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but.  1  biopsinis  stulpelis   2 but.  2 biopsiniai stulpeliai. 1. Biopsinis stulpelis 7 mm ilgio.   2. 2 biopsiniai stulpeliai: I - 5 mm; II - 6 mm.. 1. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma.   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%. Karštame taške 20%.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.    2. Krūties fibrocistiniai pokyčiai, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).. 1. Krūties audinyje - navikas: trabekulės, smulkūs lizdai, solidiniai kompleksai ir pavienės tubulės, suformuotos ląstelių su negausia eozinofiliška citoplazma, vidutinio kalibro, netaisyklingo kontūro, hiperchromiškais, vidutiniškai polimorfiškais branduoliais. Mitozių navike neidentifikuota. Navike ryškūs koaguliaciniai artefaktai.   2. Fibrozuotas krūties audinys su smulkiais latakais, klotais dvisluoksniu ar hiperplastišku epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).. Blokas 1:  CK5: (-).   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių. Karštame taške 20%.  Pro
answer:  1

 34%|███▍      | 225/661 [03:26<06:54,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1a- viršutinis kraštas, skubu  2 ėminio aprašas: 1b- apatinis kraštas, skubu  3 ėminio aprašas: Krūties kvadrantas - planinis  4 ėminio aprašas: kairės pažasties limfmazgiai - planiškai  5 ėminio aprašas: papildomas apatinis kraštas - planiškai. 3. Krūties sektorius 9x6x3,5 cm su odos lopu 8x4 cm (rezekcijos kraštas dažytas mėlynu tušu). Krūties audinyje - balkšvas, standus, gan aiškių ribų navikas 2,5x2x2,2 cm, nuo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 0,5 cm.  4. Riebalinio audinio fragmentas  8x7x2,5 cm. Rasta 17 limfmazgių iki 1 cm.  5.Riebalinio audinio fragmentas  1,7x0,8x0,5 cm. v/m. 1. Fibrocistiniai krūties pokyčiai: paprasta epitelio hiperplazija, apokrininė epitelio metaplazija.   2. Krūties lobulinė karcinoma in situ (LCIS).  3. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) lobulinė karcinoma, TNM: pT2(23 mm naviko židinys), LVI0(neidentifikuota), pN0(0/15 l/m). Krūties lobulinė karcinoma in situ (LCIS). HER2:reakcijos nėra (0). Progesterono receptoriai: reakcijos nėra. Fibrocistiniai krūties pokyčiai.  4. Reaktyvi limfadenopatija (15 l/m).  5. Krūties lobulinė karcinoma in situ (LCIS).. 1. Krūties audinyje gausūs nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu su fokalia apokrinine epitelio metaplazija ir nežymiai dilatuoti kanaliukai, kloti hiperplastišku epiteliu.   2. Krūties audinyje gausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.   3. Krūties audinyje - hialinizuotoje stromoje navikas (23 mm mikroskopiškai) infiltratyviu augimo frontu, suformuotas trabekulinių, juostinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, ekscentriškais, vidutiniškai polimorfiškais, hiperchromiškais branduoliais, nežymiai paryškėjusiais branduolėliais. Mitozių navike iki 3/10DPRL. Limfovaskulinė naviko invazija neidentifkuota (LVI0). Perineurinis naviko plitimas. Invazyvus navikas nuo artimiausio rezekcijos krašto nutolęs per 3 mm. Greta naviko negausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta daugybiniai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.  4. Penkiolika limfmazgių (15 l/m) su sinusų histiocitoze ir gausiais antriniais limfiniais folikulais.  5. Krūties audinyje gausūkeli smulkūs kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.. Blokas 5:  HER2: reakcijos naviko ląstelių membranoje nėra.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.
answer:  0

 34%|███▍      | 226/661 [03:27<07:29,  1.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2A) - kraštas-extra - be naviko    2(N2B) - kraštas-extra - be naviko    3(N3) - l/m-extra - be naviko    4(N1) - sektorius - planinis tyrimas. 4. Krūties sektorius 10x4,5x6 cm, su odos fragmentu 9,5x3 cm, žymėtas dviem vielom (atstumas tarp vielų - 5,5 cm). Krūties audinyje, vienos vielos projekcijoje - neaiškių ribų, fibrozės plotas 2x1,6 cm, žymėtas metaliniu spaustuku, nuo giliojo rezekcijos krašto nutolęs 0,3 cm. Krūties audinyje, kitos vielos projekcijoje neaiškių ribų židinys 1x1 cm plote, nuo giliojo rezekcijos krašto nutolęs 0,3 cm. Pakitimai sudėti visi.. 1(2a, ekstra). "Kraštai":   dažais žymėtame krašte - fibrozuotas riebalinis audinys; be naviko.   Planinio tyrimo metu tirtoje, dažais nežymėtoje medžiagoje - krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: kribriforminis tipas; 3,2 mm židinys).  2(2b, ekstra). "Kraštai":   dažais žymėtame krašte - fibrozuotas riebalinis audinys; be naviko.  Planinio tyrimo metu tirtoje, dažais nežymėtoje medžiagoje - fibrozuotas krūties audinys su koaguliaciniais artefaktais.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (1 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (du naviko židiniai: I - 9 mm; II - 4 mm) N0(sn) (0/1 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.     Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   DCIS komponentas nuo sektoriaus rezekcijos krašto nutolęs - 0,1 mm.. 1(2a, ekstra). "Kraštai": dažais žymėtame krašte - fibrozuotas brandžių lipocitų suformuotas audinys be naviko.   Planinio tyrimo metu tirtoje likusioje medžiagoje - 3,2 mm židinys su intraduktaliniais kribriformiais, žemiau, punkte Nr.4, aprašyto naviko proliferatais.   2(2b, ekstra). "Kraštai": dažais žymėtame krašte - fibrozuotas brandžių lipocitų suformuotas audinys be naviko.   Planinio tyrimo metu tirtoje likusioje medžiagoje - fibrozuotas krūties audinys su gausiais koaguliaciniais artefaktais.    3(ekstra). "Sarginiai limfmazgiai": vienas (1) limfmazgis su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS (du židiniai: I - 9 mm (su aplinkine fibroze ir in situ komponentu ~15 mm židinys); II - 4 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios kai kur netaisyklingos duktalinės, retos kribriforminės ir smulkios trabekulinės bei lizdinės naviko struktūros ir kai kur pabiros saikingai ar vidutiniškai polimorfiškos ląstelės, negausia ir vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 3/10 DPRL. I židinyje tubulės retos, II tubulės dominuoja. Gausūs mikrokalcifikatai. Pirmame židinyje - fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija, ryškesnė fibrozė, eritrocitų ekstravazija, hemosiderofagai (g.b. ankstesnės biopsijos vieta).   APLINKA: šalia naviko - gausūs solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: in situ komponentas nutolęs - 0,1 mm.. nan
answer:  0

 34%|███▍      | 227/661 [03:28<06:56,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G1; 5 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 10% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.. Krūties audinį 1-me bioptate infiltruoja iki 11 mm :   - pavienės duktalinės struktūros ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono receptoriai: stipri (+
answer:  10

 34%|███▍      | 228/661 [03:29<07:29,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.   5. papildomas kraštas, planinis.. 4. Krūties sektorius 8,5x6x4 cm su odos lopu 5x3 cm. Pjūvyje balkšvas, standus, neaiškių ribų navikas 1,4x1,2x0,8 cm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos 2 cm.  5. Riebalinio audinio fragmentas 2,3x2x 0,6 cm. Sudėtas visas.. Atsakymas papildytas HER2 FISH tyrimo rezultatu (HER2 geno amplifikacija nenustatyta):   1(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).    2(ekstra). "Kraštai": krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis tipas).   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 19,5 mm) N0(sn) (0/3 l/m),    LVI-2 (limfovaskulinė invazija smulkiose šakose).   Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).   5. "Papildomas kraštas": fibrozuotas krūties audinys; be naviko.. 1(ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   2(ekstra). "Kraštai": keli dilatuoti latakai su intraduktaliniais kribriforminiai vidutiniškai polimorfiškų ląstelių proliferatai, vienas nedidelis nekrozės židinys. ----  3(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS (mikroskopiškai ~19,5 mm skersmens): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retos duktalinės, dominuojančios kribriforminės, besiliejančios trabekulinės ir nedidelės lizdinės naviko struktūros, suformuotos vidutiniškai ar fokaliai ryškiau polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki 5/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Pavieniai mikrokalcifikatai.   Fokaliai kiek gausesnė židininė limfocitinė infiltracija bei fibrozė (g.b. ankstesnės biopsijos vieta).   APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.  5. "Papildomas kraštas": fibrozuotas krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.. 4. Navikas (blokas 28):  HER2: vidutinė (++) necirkuliari reakcija, 10% naviko ląstelių membranoje.
answer:  0

 35%|███▍      | 229/661 [03:30<07:14,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sarginiai l/m - extra;  2. Kairė krūtis - planinis.. 2. Krūtis 760 gramų svorio, 21x16,5x4,5 cm. Pjūvyje, centrinėje dalyje - balkšvas, standus, gan aiškių ribų navikas 8x4x7 mm, nuo odos nutolęs 2,8 cm, nuo artimiausio rezekcijos krašto - 0,3 cm. 1,5 cm nuo naviko - balkšvas, standus, židinys 1x0,8x0,8 cm, nuo artimiausio rezekcijos krašto nutolęs 1,3 cm, nuo odos - 1,5 cm. 7,5 cm nuo naviko - riebalinis inkapsuliuotas plotas 5x4x2,5 cm.. 1. Reaktyvi limfadenopatija (4 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.2): pT1b(m) (0,8 cm ir 0,9 cm naviko židiniai) pN(sn)0 (0/4 l/m). LVI0(limfovaskulinės naviko invazijos nėra). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribrozinis tipas).  ---  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: Neigamas (imunohistocheminė reakcija ribinė (2+), HER2 geno amplifikacija (FISH) nenustatyta).  Ki67: 20%.. 1. Sinusų histiocitozė keturiuose (4) limfmazgiuose.  2. KRŪTIES SPENELIS: Be patologijos.  KRŪTIS: Krūties audinyje - du (2) panašios histologinės ir citologinės išvaizdos naviko židiniai (0,8 cm ir 0,9 cm): kribrozines, susiliejančias tubulines naviko struktūras formuoja ląstelės su gan gausia eozinofiline citoplazma, vidutinio kalibro ar stambesniais kiek netaisyklingais/polimorfiškais, su nukleole branduoliais; mitozių navike iki 5 / 10 DPRL. Gan gausūs vidutinio kalibro kanaliukai su solidiniais, kribroziniais intraduktaliniais ląstelių su eozinofiliška citoplazma, vidutinio kalibro ir stambiais, polimorfiškais branduoliais proliferatais spindžiuose.. nan
answer:  0

 35%|███▍      | 230/661 [03:31<06:47,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 9 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%, vietomis iki 80%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 60%, vietomis iki 80%.
answer:  1

 35%|███▍      | 231/661 [03:32<06:50,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b) - apatinis kraštas, skubu  3(2) - Kairės pažasties sarginiai limfmazgiai, skubu  4(3) - Kairės krūties sektorius, planinis. 4(3). Krūties sektorius 9x8,5x2 cm, su odos lopu 8,5x2 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 8x7x5 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2 cm.. 1(1a). Riebalinis audinys.  2(1b). Krūties audinys.  3(2). Reaktyvi limfadenopatija (2 l/m).  4(3). Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1b(navikas 6,25 mm), pN0(sn)(0/2 l/m), LVI0. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).   HER2: reakcija neigiama (1+).. 1(1a). Riebalinis audinys su plonomis fibrozinėmis septomis ir smulkiomis kraujagyslėmis.  2(1b). Riebalinis audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(2). Du limfmazgiai su sinusų histiocitoze ir pavieniais antriniais limfiniais folikulais.  4(3).Krūties audinyje, hialinizuotoje stromoje plinta navikas (6,25 mm mikroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių ir tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su vidutiniškai polimorfiškais, hiperchromiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 12/10DPRL. Limfovaskulinio plitimo neidentifikuota (LVI0). Navikas nuo artimiausio rezekcijos krašto nutolęs per 4mm. Krūties audinyje gausūs dilatuoti kanaliukai užpildyti kribrifominių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais.. Blokas 12:  HER2: silpna (+) necirkuliari reakcija, 15%  naviko ląstelių membranoje.
answer:  1

 35%|███▌      | 232/661 [03:33<07:07,  1.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko    2(N2b) kraštai - skubus tyrimas - be naviko    3(N3): dešinės pažasties sarginis limfmazgis - skubus tyrimas - be naviko- (2l/m)  4(N1): pašalintas markiruotas dešinės krūties plotas su vielute  - planinis histologinis tyrimas. 4. Krūties sektorius 13x11x6 cm su odos lopu 9x2,5 cm, žymėtas viela. Vielos projekcijoje, pjūvyje balkšvas, standus, neaiškių ribų navikas 20x12x20 mm, nuo artimiausio rezekcijos krašto (dažyto mėlynu tušu) nutolęs 1,5 cm, nuo odos – 4 cm. Naviką apsupa balkšvas, standi, neaiškių ribų fibrozės zona 5,2x4,4x4,5 cm, nuo artimiausio rezekcijos krašto nutolusi 0,2 cm, nuo odos - 3 cm.. 1(N2a, ekstra) kraštai. Krūties audinys su židinine apokrinine metaplazija ir įprastine duktaline hiperplazija.     2(N2b, ekstra) kraštai. Krūties audinys be patologinių pokyčių.     3(N3, ekstra) dešinės pažasties sarginis limfmazgis. Reaktyvi limfadenopatija (2 l/m).    4(N1). Dešinės krūties plotas.  Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham sistemą) lobulinė karcinoma, suminis TNM:   pT3 (52 mm navikas)    pN0(sn)(0/2 l/m)    pLVI-0(limfovaskulinė invazija neidentifikuota)    pR0(radikalus pašalinimas).   Imunotipas priešoperaciname biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.    Krūties lobulinė karcinoma in situ (LCIS).. 1(N2a, ekstra) kraštai. Krūties audinys su smulkiais ir vidutinio kalibro kanaliukais, klotais dvisluoksniu epiteliu, su židinine apokrinine metaplazija ir įprastine duktaline hiperplazija.   2(N2b, ekstra) kraštai. Krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu  3(N3, ekstra) dešinės pažasties sarginis limfmazgis. 2 limfmazgiai su sinusų histiocitoze, lipomatoze.  4(N1). Dešinės krūties plotas. Krūties audinyje - infiltratyviu frontu plintantis, 52 mm dydžio (mikroskopiškai) navikas, suformuotas trabekulių, grandinėlių, smulkias tubulių. Naviko ląstelės su vidutinio gausumo, blyškia eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar kiek netaisyklingo kontūro, vidutiniškai, vietomis ryškiai polimorfiškais branduoliais su aiškiomis nukleolėmis. Mitozių navike iki 3/10DPRL.  Šalia naviko - dilatuoti kanaliukai su solidiniais ar kribriforminiais proloferatais iš analogiškų navikui ląstelių.. 3. Limfmazgiai:   Blokas 4: Cam5,2: dendritinės ląstelės +.   Blokas 16: Cam5,2: dendritinės ląstelės +.   Blokas 17: Cam5,2: dendritinės ląstelės +.   4. Navikas:   Blokas 25: CK14: mioepitelis aplink normalius latakus ir LCIS; navikas CK14(-).   E-cadhe
answer:  0

 35%|███▌      | 233/661 [03:35<08:06,  1.14s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pašalintas kairės krūties sektorius - extra  2(N2). Deš. pažasties sarginiai l/m - Extra  3. Kair. pažasties sarginiai l/m - Extra  4(N4). Deš.krūtis.   5(N5). Kairė krūtis.. 4. Krūtis 1000 gramų svorio, 26x20x5 cm. Krūties audinyje, lateralinių kvadrantų riboje - balkšvas, standus, neaiškių ribų I navikas 23x21x15 mm, nuo odos nutolęs 3,5 cm, nuo giliojo rezekcijos krašto - 2,5 cm. Medialiau, balkšvas, standus, neaiškių ribų II navikas 24x13x11 mm, nuo odos nutolęs 2 cm, nuo giliojo rezekcijos krašto - 4 cm, nuo I naviko - 0,3 cm. 26-32 kasetėse- riba tarp navikų, pjūvis per I naviką žymėtas mėlyna spalva, pusė link II naviko- juoda. Krūtis fibrozuota 13x12x3 cm plote.  5. Krūtis 780 gramų svorio, 23x18x6 cm su defektu odoje 7x6 cm plote (šalinto sektoriaus vieta). Krūties audinyje, fibrozės zona 12x6x3,5 cm, vietomis siekia rezekcijos kraštą, nuo odos nutolęs 1 cm. Makroskopiškai navikas neidentifikuojamas.. 1(Extra). Krūties (kairiosios) invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(25 mm) N(sn)1mi(mikromts 1/4 l/m), LVI-2(limfovaskulinė invazija).   Imunofenotipas:   Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  HER2 imuninė reakcija: neigiama (1+).  Ki67: 5%.  2(Extra)(Deš. pažasties sarginiai l/m). Reaktyvi limfadenopatija (2 l/m).  3(Extra)(Kair. pažasties sarginiai l/m). Duktalinės karcinomos mikrometastazė 1/4 limfmazgyje (0,45 mm).   4. Krūties (dešiniosios) invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT(m)2(2 naviko židiniai: 23 mm ir 24 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).  5. Lobulinė karcinoma in situ (LCIS). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. 1(Extra). Krūties audinyje - ribotas navikas (mikroskopiškai 25 mm), suformuotas fibrozuotoje stromoje plintančių lizdinių, trabekulinių ir fokaliai besiliejančių liaukinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia, fokaliai PASD+ grūdėta ar vakuolizuota citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 6/10 DPRL. Pavieniai smulkūs kalcifikatai. Limfovaskulinė invazija smulkioje šakoje.  2(Extra). 2 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze.  3(Extra). 4 limfmazgiai su pirminiais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze. Papildomuose (ne extra) pjūviuose, viename limfmazgyje (limfoidiniame audinyje ir kapsulėje) atsiranda smulkūs (iki 0,45 mm) lizdai, suformuoti tubulinių ir lizdinių naviko struktūrų iš ląstelių eozinofiliška citoplazma, vidutinio kalibro, kiek polimorfiškais, su nukleole branduoliais.  4. Krūties audinyje - 2 navikai (mikroskopiškai 23 mm ir 24 mm), suformuoti fibrozuotoje stromoje plintančių trabekulinių struktūrų, grandinėlių, smulkių grupių ir pabirų ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 2/10 DPRL. Pavieniai smulkūs kalcifikatai, negausūs makrofagų židiniai. Aplink yra dilatuotų kanaliukų, užpildytų analogiškomis navikui ląstelėmis bei keli dilatuoti kanaliukai su kribriforminiais intraduktaliniais proliferatais, suformuotais ląstelių vidutiniškai polimorfiškais branduoliais; negausūs kanaliukai su apokrinine metaplazija ar su epitelio hiperplazija bei stulpiniu ląstelių pokyčiu su apikaline sekrecija.  5. Krūties audinyje, fibrozuotoje stromoje vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu; yra dilatuotų kanaliukų, klotų suplokštėjusiu epiteliu, kanaliukų su epitelio hiperplazija ar su apokrinine metaplazija. Yra kanaliukų, užpildytų ląstelėmis gan monomorfiškais branduoliais (LCIS).. 1. Navikas/duktalinė karcinoma (10 blokas):  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  HER2 imuninė
answer:  0

 35%|███▌      | 234/661 [03:35<07:18,  1.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 20%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis visos membranos nusidažymas 12% naviko ląstelių
answer:  1

 36%|███▌      | 235/661 [03:36<07:05,  1.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštai - skubus tyrimas - be naviko  2 ėminio aprašas: N2b -b be naviko  3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - skubus tyrimas 1l/m be navimo  4. (1) ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas. 4(1). Krūties sektorius 8x7x4 cm su odos lopu 7x3 cm, žymėtas viela. Krūties audinyje balkšvas, standus navikas 28x22x27 mm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos – 2,5cm.. 1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (1 l/m).  4(1). Krūties invazyvi, blogai diferencijuota (G3; 9 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 28mm) pN0(sn)(0/1 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-3406:  "Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 35%, vietomis iki 60%.". 1(2a). Krūties audinys su įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  2(2b). Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  3. Vienas(1) limfmazgis be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4(1). Krūties audinyje - navikas, formuojamas solidinių, trabekulinių, kribriforminių struktūrų iš vidutinio/stambaus kalibro ląstelių, eozinofiliška citoplazma, ryškiai polimorfiškais, hiperchromiškais branduoliais; navike - iki 59 mitozių/10 DPRL. Rezekcijos kraštas be naviko.. nan
answer:  0

 36%|███▌      | 236/661 [03:37<06:53,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2): kairės pažasties sarginis limfmazgis - skubus tyrimas  2(N1): pašalitna kairė krūtis - planinis tyrimas. 2(N1). Krūtis gramų 498 svorio, 23x15x4,5 cm. Krūties audinyje, viršutiniame lateraliniame kvadrante pilkšvas, standus, neaiškių ribų navikas 35x30x22 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 1,5 cm, nuo odos - 1,7 cm.. 1(ekstra). Krūties lobulinės karcinomos metastazė (1/5 l/m 5,5 mm).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(m)(40 mm, 2,3 mm, 1,2 mm navikai) pN1a(sn) (1/5 l/m MTS 5,5 mm) LVI-0(limfovaskulinė invazija neidentifikuota). R0(navikas nuo rez. krašto nutolęs 1,3 mm). Lobulinė karcinoma in situ.    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. 1(ekstra). 1 iš 5 limfmazgių aprašyto naviko metastazė 5,5 mm.  2. Spenelis: Spenelis: latakuose naviko ląstelių intraepitelinis plitimas.  Krūtyje - navikas (40 mm, 2,3 mm, 1,2 mm) infiltratyviu augimo frontu, suformuotas grandinėlėmis, pabirai, trabekulinėmis struktūromis, lizdais besidėstančių ląstelių  negausia - vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, nereguliaraus kontūro ir ovaliais branduoliais ryškiomis nukleolėmis; mitozių 3/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais solidiniais proliferatais iš analogiškų navikui ląstelių.. 2. Navikas(24 blokas): E-cadherin(+++) membr. r-ja 100%; p120-catenin(+++) citopl/ r-ja 100%.
answer:  1

 36%|███▌      | 237/661 [03:38<06:53,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai  - skubus tyrimas - be naviko  2(N2b) kraštai  - skubus tyrimas - be naviko  3(N3): kairės pažasties sarginis limfmazgis - skubus tyrimas - viename iš 5 makrometastazė  4(N1): pašalintas kairės krūties kvadrantas - planinis tyrimas. Krūties sektorius 10,5x7,5x4 cm su odos lopu 9x3,5 cm. Krūties audinyje - pilkšvas standus neaiškių ribų navikas 16x16x12 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 1,5 cm.. 1(Extra). Krūties fibrocistiniai pokyčiai.  2(Extra). Krūties fibrocistiniai pokyčiai. Mikrokalcifikatai.  3(Extra). Krūties duktalinės karcinomos metastazės 2/5 l/m (4,2 mm ir 1,3 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(22 mm) N(sn)1a(mts 2/5 l/m: 4,2 mm ir 1,3 mm), LVI-2(limfovaskulinė invazija).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DIN3/DCIS)(solidinė, kribriforminė).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro ir kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu; yra kanaliukų apokrinine metaplazija bei dilatuotų kanaliukų, klotų suplokštėjusiu epiteliu, negausūs smulkūs kalcifikatai.  3(Extra). Dviejuose (2) iš 5 limfmazgių - žemiau (Nr.4) aprašyto naviko metastazės (4,2 mm ir 1,3 mm).  4. Krūties audinyje - navikas infiltratyviais kraštais (mikroskopiškai 22 mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių ir lizdinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais ir kiek nereguliaraus kontūro, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 9/10 DPRL. Šalia yra dilatuotų kanaliukų su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais.. 4. Navikas (22 blokas):  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.
answer:  0

 36%|███▌      | 238/661 [03:39<06:35,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 18 G automatine biopsine adata punktuotas ~9x11 mm patologinis l/m dešiniosios pažasties I lygmenyje, paimti du biopsiniai stulpeliai histologijai (I buteliukas).   2 ėminio aprašas: 2. 18 G automatine biopsine adata punktuotas hipoechogeninis, nelygiais kontūrais, ~18x25 mm navikas dešiniojoje krūtyje ties 9-10 val. vidurinėje/periferinėje dalyse, paimtas vienas biopsinis stulpelis histologijai (II buteliukas).. 1. 2 biopsiniai stulpeliai: I - 9 mm; II - 9 mm.  2. Biopsinis stulpelis 14 mm ilgio.. N1: Limfmazgio bioptatas su duktalinės karcinomos metastaze.  N2: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. N1: Limfmazgio bioptatas su žemiau aprašyto naviko židiniu.  N2: Krūties audinį infiltruoja duktalinės struktūros ir kribroziniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 1
answer:  0

 36%|███▌      | 239/661 [03:40<06:16,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, nelygiais kontūrais, ~7x7 mm dydžio darinys dešiniojoje krūtyje ties 11 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 8 mm; II - 7 mm; III - 8 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.. Krūties audinį infiltruoja smulkūs solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 4%.
answer:  0

 36%|███▋      | 240/661 [03:41<06:58,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2) - Kairės krūties kvadrantas, planinis  4(3) - Kairės krūties limfmazgiai, planinis  5.(3)- Kairės krūties limfmazgiai, planinis. ŽR. KOKYBĖS PASTABĄ!  3. Krūties sektorius 8x6x5 cm su odos lopu 6x4 cm. Odoje rusvos dėmės ir dariniai iki 0,7x0,7 cm, artimiausia dėmė siekia rezekcijos kraštą. Pjūvyje:  - pilkšvas, standus, aiškių ribų I navikas 2,1x1,8x2,5 cm, nuo artimiausio rezekcijos krašto (dažyto mėlynu tušu) nutolęs 1,5 cm, nuo odos - 1,3 cm.   - 0,2 cm nuo naviko balkšvas, standus II (?) navikas 0,9x0,7x0,7 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 2 cm, nuo odos - 0,5 cm.   4. Riebalinio audinio fragmentai, bendras dydis 9x6x2,5 cm. Rasta 19 limfmazgių iki 1,8 cm.  5. Riebalinio audinio fragmentas 3x3x1,5 cm. Rasti 2 limfmazgiai iki 1,2 cm.. 1.(1a) Fibrocistiniai krūties pokyčiai.  2.(1b) Fibrocistiniai krūties pokyčiai.  3. Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(m)(du naviko židiniai - 9mm ir 25mm) pN1mi(1/21 l/m; iki 1,09mm); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).  IHC, FISH reakcijos atliktos VPC:B23-714 tyrime:  "Ki67: proliferacinis indeksas 55%.  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Išoriniai IHC:  Estrogenų receptorių raišką teigiama (stipri raiška 100 proc. naviko ląstelių branduoliuose).  Progesteronų receptorių raišką teigiama (vidutinė raiška 50 proc. naviko ląstelių branduoliuose).  HER2 raiška paribinė (2+: silpna cirkuliari raiška 30 proc. naviko ląstelių membranoje)."  Vidutinio laipsnio krūties intraduktalinė karcinoma (DCIS; solidinis tipas; -komedo tipo nekrozės). Fibrocistiniai krūties pokyčiai. Krūties odos seborėjinės keratozės.  4. Duktalinės karcinomos mikrometastazė limfmazgyje (1/19 l/m; iki 1,09mm).  5. Reaktyvi limfadenopatija (2 l/m).. 1.(1a) Riebaliniame audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, apokrininės metaplazijos židiniais.  2.(1b) Riebaliniame audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, apokrininės metaplazijos židiniais.  3. Krūties audinyje du naviko židiniai (9mm ir 25mm), formuojamas solidinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 17 mitozių/10 DPRL; Limfo-Vaskulinė naviko Invazija (LVI) smulkiose kraujagyslėse/limfagyslėse. Krūties audinyje - dilatuoti latakėliai su solidiniais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, apokrininės metaplazijos, paprastos intraduktalinės hiperplazijos židiniais. Krūties odoje - epidermio hiperkeratozė, papilomatozė, besiliejantys epidermio hiperplazijos plotai su pavienių raginių cistų formacija, bazinio sluoksnio hiperpigmentacija.   4. Iš rastų devyniolikos(19) limfmazgių, viename aukščiau aprašyto naviko metastazė (iki 1,09mm).  5. Du(2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.. nan
answer:  0

 36%|███▋      | 241/661 [03:42<06:55,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: kairės krūties kvadrantas - planinis tyrimas  2 ėminio aprašas: N2a: kraštai  3 ėminio aprašas: N2b: kraštai  4 ėminio aprašas: N3c: kraštai   5 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis. 1. Krūties sektorius 4,7x2,2x4,5 cm su oda 5x2 cm, žymėtas viela. Vielos projekcijoje, pilkšvas, aiškių ribų darinys 10x10x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,5 cm.  2. Riebalinio audinio fragmentas 1,5x1x0,3 cm. v/m  3. Riebalinio audinio fragmentas 1,6x1,3x0,4 cm. v/m  4. Riebalinio audinio fragmentas 2x1,2x0,6 cm. v/m  5. Riebalinio audinio fragmentas 3x2,5x0,7 cm. Rastas 1 limfmazgis 0,9 cm. v/m. 1. Kvadrantas. Krūties vidutiniškai diferencijuota (G2, 7b. pagal Nottingham skalę) invazyvi duktalinė karcinoma, TNM: pT1b(8 mm), LVI-0 (limfovaskulinė invazija neidentifikuota), R0 (radikali rezekcija).  Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 20%.    2. Kraštai. Krūties audinys. Be naviko.  3. Kraštai. Krūties audinys. Be naviko.  4. Kraštai. Krūties audinio fibrozė. Be naviko.  5. Sarginis limfmazgis. Riebalinio-fibrozinio audinio fragmentas. Žr. pastabą.. 1. Krūties audinyje- ekspansyviuaugimo frontu plintantis navikas, sudarytas iš trabekulėmis, lizdais besidėstančių ląstelių vidutinio gausumo šviesiai eozinofiliška cioplazma, ovaliais ar nelygaus kontūro, polimorfiškais branduoliais su ryškiomis nukleolėmis. Navikas nuo rezekcijos krašto 2 mm. Mitozių 13/DPRL.    2. Krūties audinys su pavieniais latakais, klotasi dvisluoksniu epiteliu.   3. Krūties audinys su pavieniais latakais, klotasi dvisluoksniu epiteliu.   4. Krūties audinys su pavieniais latakais, klotasi dvisluoksniu epiteliu.   5. Riebalinio-fibrozinio audinio fragmentas.. nan
answer:  0

 37%|███▋      | 242/661 [03:43<06:30,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma. Žemo laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 95% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 30% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.. Bioptate - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos tubulėmis ir kribriforminėmis struktūromis besidėstančių ląstelių negausia eozinofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio kalibro, ovaliais branduoliais; mitozių 0/10 DPRL. Dilatuoti latakai su intraduktaliniais kribriforminiais prloliferatias iš analogiškų navikui ląstelių.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 95%.  Progesterono receptoriai: (+++)(brand. r-ja) 30%.  HER2: silpnas dalies membranos nusidažymas 5% naviko ląstelių.  Ki67 proliferacinis aktyvumas 5%.  CK14(-);
answer:  0

 37%|███▋      | 243/661 [03:44<06:13,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 5 mm.. Krūties invazyvi duktalinė karcinoma (ne mažiau kaip gerai diferencijuota / G1 / 5 balai pagal Nottingham).     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 3%.. Tubulines (80%), pavienes smulkias kribriformines naviko struktūras formuoja ląstelės su saikinga švelniai eozinofiline citoplazma, smulkiais ar kiek stambesnio kalibro kiek netaisyklingais, dalis su smulkia nukleole branduoliais; mitozių navike iki 1 / 10 DPRL.. Navikas:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Prolife
answer:  3

 37%|███▋      | 244/661 [03:45<06:06,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: kairė krūtis su pažasties limfmazgiais, planinis. Krūtis 865 g svorio, 21x19x5,5 cm, su pažasties narveliena 10x7,5x3 cm. Krūties audinyje, užspenelinėje srityje, balkšvas, standus, neaiškių ribų I navikas 2,5x1,7x1,5 cm, esantis 1,2 cm nuo artimiausio rezekcijos pjūvio, nuo odos - 2,5 cm. 0,8 cm atstumu nuo I-ojo naviko balkšvas, standus II navikas 0,6x0,5x0,5 cm (sudėtas visas), nuo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 5 cm. Bendras didžiausias navikų matmuo 4 cm. Pažasties narvelienoje rasta 10 limfmazgių, didžiausias 1,4 cm.  Gilusis rezekcijos kraštas dažytas juoda spalva.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2 (40mm); pN2a (4 iš 10 l/m).. Krūties audinyje 40mm navikas iš dviejų susijusių dalių: pavienės duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 18/10 DPRL.  Intravaskulinio naviko plitimo židiniai.  Iš rastų 10 limfmazgių 4 l/m su metastazėmis iki 14mm.  Operacinis pjūvis be naviko.. nan
answer:  0

 37%|███▋      | 245/661 [03:45<05:53,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm ilgio.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35-40%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+ 35-
answer:  1

 37%|███▋      | 246/661 [03:46<06:09,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). Kvadranto kraštai.-extra   2(N2). Kvadranto kraštai.-extra   3(N3). Sarginiai l/n.-extra   4(N4). Deš.krūties kvadrantas su naviku.. 4. Krūties sektorius 8x7x3 cm, žymėtas viela. Vielos projekcijoje, pjūvyje balkšvas, standus, neaiškių ribų navikas 9x9x9 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 1 cm. šalia naviko krūties audinys du hemoragijomis ir nekrozės zonomis 1x0,9x0,8 cm plote.. PATIKSLINTA DIAGNOZĖ:  1. Fibrocistiniai krūties pokyčiai.  2. Krūties lobulinė karcinoma in situ (LCIS).  3. Reaktyvi limfadenopatija (2 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) lobulinė karcinoma, TNM: pT1b(9 mm naviko židinys), LVI0(neidentifikuota), pN0(sn)(0/2 l/m). Krūties lobulinė karcinoma in situ (LCIS). HER2: reakcija neigiama (1+). Progesterono receptoriai: reakcijos nėra.. 1. Krūties audinyje židininė fibrozė ir smulkūs bei nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  2. Krūties audinyje keli dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Šalia nežymiai dilatuoti kanaliukai, kloti hiperplastišku epiteliu.  3. Du limfmazgiai su sinusų histiocitoze.  4. Krūties audinyje navikas (9 mm mikroskopiškai), infiltratyviu augimo frontu, suformuotas solidinių, trabekulinių ir pavienių struktūrų su spindžių formacija. Naviko ląstelės negausia eozinofiline citoplazma, vidutiniškai polimorfiškais, hiperchromiškais, smulkiai grūdėtu chromatinu branduoliais, pavieniais paryškėjusiais branduolėliais. Mitozių navike 6310DPRL. Limfovaskulinė naviko invazija neidentifikuota(LVI0).  Krūties audinyje negausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Krūties audinyje židininė histiocitų, pigmentuotų makrofagų, MMN ir svetimkūnio tipo gigantinių daugiabranduolių ląstelių infiltracija.. Blokas 16:  HER2: silpna (+) necirkuliari reakcija, 3%  naviko ląstelių membranoje.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra;  ECAD(-)neigiama r-ja navike.
answer:  0

 37%|███▋      | 247/661 [03:47<05:56,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 13 mm.. PATIKSLINTA (žr. pastabą):   Invazinė lobulinė karcinoma (mažiausiai iki 11 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 3%.. Krūties audinį 2-se bioptatuose infiltruoja iki 11 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  CK14: neigiama (-) atipinių ląstelių membranoje  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 3% navik
answer:  0

 38%|███▊      | 248/661 [03:48<05:46,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpeliai. Biopsinis stulpelis 5 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 4 mm);  (G1; 3 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 4%.. Krūties audinį 1-me bioptate infiltruoja iki 4 mm :   - duktalinės netaisyklingos struktūros (100% viso naviko);  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  CK14: neigiama (-) atipinių difuziškai plintančių struktūrų ląstelių membranoje  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose,
answer:  0

 38%|███▊      | 249/661 [03:49<06:28,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.  2(2b). Kraštai - skubus tyrimas - be naviko.  3. Sarginis limfmazgis - 3 l/m dviejose iš trijų limfmazgių makrometastazės.  4(1). Pašalintas dešinės krūties kvadrantas - planinis tyrimas.. 4(1). Krūties sektorius 14x7x5 cm su odos lopu 13,5x3,5 cm. Krūties audinyje balkšvas, standus, neaiškių ribų navikas 2,3x1,6x1,3 cm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos – 2,3 cm.. PAPILDYTAS ATSAKYMAS:   1(2a, ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties-riebalinis audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos metastazės dviejuose limfmazgiuose (mts 2/3 l/m; iki ~ 19 mm skersmens; su ekstranodaliniu plitimu).     4(1). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (mikroskopiškai navikas 15 mm, žr. pastabą) N1a(sn) (mts 2/3 l/m; iki ~19 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+).  Molekuliniai tyrimai:  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: solidinis, kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Navikas nuo sektoriaus rezekcijos krašto nutolęs 1,7 mm.. 1(2a, ekstra). "Kraštai": fibrozuotas brandžių lipocitų suformuotas fragmentas; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": dviejuose (2) limfmazgiuose žemiau, punkte Nr.4, aprašyto naviko metastazės, iki ~19 mm skersmens, su ekstranodaliniu plitimu; didžiausioje riboti nekrozinės židiniai, supami histiocitų ir hemosiderofagų. Viename limfmazgyje smulkių dilatuotų endotelizuotų ertmių proliferacija su eritrocitais spindžiuose.   4(1). NAVIKAS (mikroskopiškai didžiausias išmatuojamas naviko matmuo - 15 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios kribriforminės, trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai ar ryškiau polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, varijuojančio dydžio nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 40/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai gausesnė perinavikinė limfocitinė infiltracija. Periferijoje fibroadenomatoziniai stromos pokyčiai. Navike - ribotas nekrozės židinys (g.b. ankstesnės biopsijos vieta).    APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: navikas nuo artimiausio rezekcijos krašto nutolęs - 1,7 mm.. 4(1). Navikas (blokas 14):  CK14(+) silpna r-ja naviko ląstelių membranoje; GATA3(+++)(brand.r-ja)100%.   HER2: vidutinė (++) necirkuliari reakcija, 10% naviko ląstelių membranoje.
answer:  1

 38%|███▊      | 250/661 [03:50<06:44,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 16 G automatine biopsine adata punktuotas hipoechogeninis, nelygiais kontūrais, ~6x9 mm dydžio satelitas dešiniojoje krūtyje ties 6-7 val. vidurinėje dalyje, paimti du biopsiniai stulpeliai histologijai (I buteliukas).   2 ėminio aprašas: 2. 16 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~16x28 mm dydžio navikas dešiniojoje krūtyje ties 9 val. vidurinėje dalyje, paimti du biopsiniai stulpeliai histologijai (II buteliukas).  3 ėminio aprašas: 3. 16 G automatine biopsine adata punktuotas ~6x8 mm dydžio patologinis intramamarinis l/m dešiniojoje krūtyje ties 10-11 val. periferinėje dalyje, paimti trys biopsiniai stulpeliai histologijai (III buteliukas).. 1. 2 biopsiniai stulpeliai: I - 13 mm; II - 11 mm.  2. 2 biopsiniai stulpeliai: I - 14 mm; II - 16 mm.  3. 3 fragemntuoti biopsiniai stulpeliai: I - 5 mm; II - 8 mm; III - 7 mm.. 1. Satelitas dešiniojoje krūtyje 6-7 val. vidurinėje: krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.  2. Dešiniojoje krūtyje ties 9 val. vidurinėje dalyje: krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.  3. Intramamarinis l/m dešiniojoje krūtyje ties 10-11 val. krūties duktalinės karcinomos metastazės.    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.   Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 15%.. 1. Satelitas dešiniojoje krūtyje 6-7 val. vidurinėje: bioptatuose (2/2) - krūties audinyje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 12/10 DPRL. Dilatuoti latakai su intraduktalinėmis kribriforminėmis struktūromis iš analogiškų navikui ląstelių.  2. Dešiniojoje krūtyje ties 9 val. vidurinėje dalyje: bioptatuose (2/2) - krūties audinyje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 12/10 DPRL. Dilatuoti latakai su intraduktalinėmis kribriforminėmis struktūromis iš analogiškų navikui ląstelių.  3. Intramamarinis l/m dešiniojoje krūtyje ties 10-11 val.: limfmazgyje analogiškos aprašytoms Nr.1 naviko struktūros.. 1. Navikas (1 blokas):  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 5% naviko ląstelių.  Ki67 proliferacinis aktyvumas 15%.
answer:  0

 38%|███▊      | 251/661 [03:51<06:18,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 9 mm ilgio.. Invazinė lobulinė karcinoma (mažiausiai iki 9 mm);  (G1; 5 b. pgl. Nottingham sist.) 1-me stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.. Krūties audinį 1-me bioptatuose infiltruoja iki 9 mm :   - pabiros ląstelės, juostos ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: neigiama (-) atipinėse struktūrose  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 5% naviko
answer:  0

 38%|███▊      | 252/661 [03:52<06:05,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Kairė krūtis su limfmazgiais, planinis. Krūtis 1083 g svorio, 25x16x6 cm, su pažasties narveliena 15x11x4 cm. Krūties audinyje, lateralinių kvadrantų riboje balkšvas, standus, aiškių ribų navikas 2,8x2,5x2,5 cm, esantis 0,5 cm nuo artimiausio rezekcijos pjūvio, peraugantis odą 2,4x2 cm plote.   Pažasties narvelienoje rasti 28 limfmazgiai iki 1,2 cm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT2(28 mm) pLVI-0 pN0(0/28) pR0.  Naviko imunotipas (priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 75% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67+ 8%.. Krūties audinyje naviką formuoja duktalinės struktūros (20%), netaisyklingi kribroziniai ir solidiniai kompleksai bei trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL. Navikas infiltruoja odą, bet be išopėjimo.   Operaciniai kraštai, kraujagyslės be navikinių pokyčių.  Limfmazgiai (28) be patologinių pokyčių.. nan
answer:  0

 38%|███▊      | 253/661 [03:53<06:07,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 pjūvio kraštas, ekstra  2 ėminio aprašas: 2 pjūvio kraštas, ekstra   3. sektorius, planinis.. 3. Krūties sektorius 8x4x6,5 cm, su odos lopu 7x3 cm. Pjūvyje pilkšvas, standus, ribotas navikas 22x20x18 mm, nuo giliojo rezekcijos kraštonutolęs 0,2 cm, nuo odos - 1,6 cm.. 1. Krūties lobulinė karcinoma in situ (LCIS).   2. Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mucininė karcinoma, TNM: pT2(navikas 22 mm), pLVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).  HER2:reakcijos nėra (0).. 1. Krūties audinyje gausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.  2. Krūties adinyje negausūs, minimaliai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  3. Krūties audinyje navikas (22 mm makroskopiškai), suformuotas gausiuose ekstraląsteliniuose mucinuose besidėstančių solidinių, kribriforminių ir negausių mikropapilinių struktūrų. Naviko ląstelės vidutinio gausumo eozinofiline citoplazma, vidutinio kalibro, kiek polimorfiškais branduoliais su negausiomis smulkiomis nukleolėmis. Mitozių navike iki 13/10 DPRL. Limfovaskulinis naviko plitimas neidentifikuotas. Greta naviko negausūs kanaliukai su solidiniais ir kribriforminiais proliferatais, suformuotais iš vidutinio gausumo eozinofiline citoplazma ląstelių, vidutiniškai polimorfiškais, hiperchromiškais branduoliais su pavieniais paryškėjusiais branduolėliais.. Blokas 1:  E-Cadherin: (-)neigiama r-ja proliferatuose  Blokas 7:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 38%|███▊      | 254/661 [03:53<05:55,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 13 mm; II - 13 mm.. Invazinė lobulinė karcinoma (mažiausiai iki 11 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: silpna (+) reakcija, 5% naviko ląstelių.  HER2: reakcija paribinė (2+). Dėl blogos mėginio kokybės ir nepakankamo ląstelių kiekio mėginyje, HER2 amplifikacijos FISH tyrimas nevertintinas.  Ki67: proliferacinis indeksas 15%.. Krūties audinį 2-se bioptatuose infiltruoja iki 11 mm :   - juostos;  - epitelinių smulkių / vidutinio dydžio ląstelių su neryškiai/ vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozės nestebimos.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: silpna teigiama (+)  membraninė reakcija 10proc. atipinėse ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: vidutinė (++) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67: reakcija
answer:  0

 39%|███▊      | 255/661 [03:55<06:14,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). Sarginiai l/m. - extra  2(N2). Deš.krūtis su navikiniais dariniais.. 2. Krūtis 19x15x6 cm. Spenelis kiek įtrauktas, centre su balkšva, neaiškių ribų dėme 0,4x0,4 cm. Krūties audinyje, centrinėje dalyje ? - pilkšvas, standus, neaiškių ribų navikas 16x16x10 mm, pereinantis į fibrozę. Navikas nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo odos - 2,5 cm. Fibrozės krašte rusvas, gan aiškių ribų darinys 6x5x5 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 3,5 cm.. 1. Limfmazgiai(2) be karcinomos plitimo. Žr. pastabą.   2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma,   pT1c (16 mm) pN0(sn) (0/2 l/m); LVI2 (limfovaskulinė naviko invazija smulkiose limfagyslėse/ kraujagyslėse). Karcinomos imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-6112, žr. pastabą.   Krūties lobulinė karcinoma in situ (LCIS).   Stulpinis epitelio pokytis su epitelio hiperplazija. Krūties intraduktalinė papiloma.. 1. Limfmazgiai(2) su kiek tušuota architektūra, pavieniais antriniais folikulais, negausiais histiocitais sinusuose.   2. Krūties audinyje - navikas, formuojamas infiltratyviai plintančių, glaudžiai besidėstančių grandinėlių, trabekulinių ir pavienių smulkių blogai suformuotų liaukinių struktūrų, smulkių grupių, sudarytų iš nedidelių-vidutinio dydžio poligonalinių ląstelių šviesiai eozinofiliška citoplazma, vidutiniškai polimorfiškais ovaliais ar skeltais branduoliais su vezikulizuotu chromatinu, retomis labai smulkiomis nukleolėmis. Navike iki 3 mitozių/ 10 DPRL. Limfovaskulinė naviko invazija smulkiose limfagyslėse/ kraujagyslėse.   Aplinkiniame audinyje - lobulės su kanaliukais, užpildytais smulkiomis-vidutinio dydžio monotoniškomis ląstelėmis. Keli latakai, kloti stulpiniu epiteliu su apikalinės sekrecijos požymiais, stratifikuotais, hiperchromiškais, nežymiai polimorfiškais branduoliais.   Grupė latakų su intraduktalinėmis papilinėmis struktūromis ir adenomatozinio tipo proliferatais iš mioepitelinių ir duktalinių ląstelių. Grupės latakų su stulpiniu epitelio pokyčiu ir apikalinės sekrecijos požymiais bei epitelio hiperplazija.. 1. Limfmazgis:   CD20+ nedideli folikulai, CD3/CD5(+) gausūs parakortekso ir perifolikliniai T limfocitai, CD23+ FDC tinklai ir labai negausūs pabiri limfocitai, Cyclin D1(-), Ki67 <5% (pavieniai smulkūs antriniai folikulai su GC ir aukštu Ki67).
answer:  0

 39%|███▊      | 256/661 [03:56<06:20,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu  3(2). Deš. pažasties sarginiai limfmazgiai, skubu   4(3). Deš. krūties sektorius, planinis. 4. Krūties sektorius 5,8x3x6 cm su oda 5x1,5cm, žymėtas viela. Krūties audinyje, vielos projekcijoje - pilkšvas, standus, aiškių ribų navikas 10x8x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1,2 cm.. 1(1a). Riebalinio audinio fragmentas be patologijos.  2(1b). Fibrocistiniai krūties pokyčiai.  3(2). Krūties duktalinės karcinomos mikrometastazė viename limfmazgyje (1/1 l/m, 1,1 mm skersmens).  4(3). Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma, TNM: pT1b(navikas 8,25 mm), pN1mi(1 l/m su mikrometastaze 1,1 mm), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2: reakcija neigiama (1+).  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).. 1(1a). Riebalinio audinio fragmentas su fibrozinėmis septomis.  2(1b). Krūties audinyje židininė fibrozė su smulkiais ir nežymiai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.  3(2). PO FIKSACIJOS: Limfmazgyje žemiau aprašyto naviko mikrometastazė 1,1 mm skersmens.  4(3). Krūties audinyje, hialinizuotoje stromoje plinta navikas (8,25 mm) infiltratyviu augimo frontu. Navikas suformuotas trabekulinių ir tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su vidutiniškai polimorfiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 6/10DPRL. Limfovaskulinis plitimas smulkiose limfagyslėse/kraujagyslėse(LVI2). Greta naviko gausūs dilatuoti kanaliukai užpildyti solidinių ir kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais; dalies proliferatų centruose - nekrozės zonos.. Blokas 10:  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.
answer:  1

 39%|███▉      | 257/661 [03:57<06:34,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- Kairės pažasties sarginiai limfmazgiai, skubu  4(3)- Kairės krūties sektorius, planinis. 4. Krūties sektorius 8,5x3,5x4 cm, su odos lopu 6,5x2 cm, žymėtas viela. Krūties audinyje, pjūvyje pilkšvas, standus, aiškių ribų navikas 9x6x4 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,5 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties lobulinė karcinoma in situ (LCIS) ir fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija. Mikrokalcifikatai.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(8 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).   Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija. Mikrokalcifikatai.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu, fokaliai hiperplastišku epiteliu; yra kanaliukų, užpildytų monomorfiškomis ląstelėmis (LCIS). Negausūs mikrokalcifikatai.  3(Extra). 2 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.   4. Krūties audinyje - ribotas navikas (mikroskopiškai 8 mm), suformuotas fibrozuotoje stromoje plintančių lizdinių ir trabekulinių struktūrų bei negausių grandinėlių, suformuotų iš ląstelių saikinga švelniai eozinofiliška citoplazma, smulkiais ir vidutinio kalibro, apvaliais/ovaliais, vidutiniškai polimorfiškais, dalis su nukleole branduoliais; negausios žiedines primenančios ląstelės su ekscentrišku branduoliu. Mitozių iki 1/10 DPRL. Navikas 4,5 mm nuo rezekcijos krašto. Gausūs dilatuoti kanaliukai, užpildyti analogiškomis navikui ląstelėmis (LCIS). Aplink yra dilatuotų kanaliukų, klotų hiperplastišku epiteliu bei kanaliukų su apokrinine metaplazija; pavieniai mikrokalcifikatai.. 4. 9 blokas: invazyvi karcinoma E-Cadherin(-); CK14(-); LCIS struktūros su išlaikytu CK14+ mioepiteliniu sluoksniu, E-Cadherin(-) (mioepitelinis sl. +).  16 blokas: LCIS struktūrose E-Cadherin(-) (mioepitelinis sl. +).
answer:  0

 39%|███▉      | 258/661 [03:57<06:13,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 13 mm; II - 13 mm. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.. Bioptatuose (2/2) - fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos trabekulėmis ir lizdais besidėstančių ląstelių negausia tamsia eozinofiliška citoplazma, polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 10/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 5% naviko ląstelių.  Ki67 proliferacinis aktyvumas 20%.  Synaptophysin+ pavienės ląstelės; CK14 citop
answer:  1

 39%|███▉      | 259/661 [03:59<06:42,  1.00s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2): pašalinti  dešinės krūties sarginiai limfmazgiai - skubus tyrimas 2l/m be naviko  2(N1): pašalinta dešinės krūtis - planinis tyrimas. 2(1). Krūtis 1800 gramų svorio, 23x19x6 cm. Rezekcijos kraštas dažytas mėlynu tušu. Krūties audinyje balkšvi standūs naviko židiniai:  - (I) 2,3x2x2,3 cm navikas, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 1,5 cm;  - (II) 0,9x0,9x0,8 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 4 cm, nuo odos - 2 cm, nuo artimiausio (I) naviko - 7,5 cm;  - (III) 1,5x1,7x1,5 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs  6 cm, nuo odos - 2  cm, nuo artimiausio (I)  naviko - 3 cm;  - (IV) 2,2x1,5x1,5 cm navikas, nuo giliojo rezekcijos krašto nutolęs 5 cm, nuo odos - 3 cm, nuo artimiausio (III) naviko nutolęs 3 cm.  - (V) 0,6x0,5x0,5 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 5 cm, nuo odos - 4 cm, nuo artimiausio (III) naviko nutolęs 4 cm.  - (VI) 0,5x0,4x0,2 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 9 cm, nuo odos - 1 cm, nuo artimiausio (V) naviko nutolęs 3 cm.  - Balkšva, standi, netoylgių kraštų fibrozės zona 6x3x3 cm su daugybiniais standžiais židiniais iki 1,5x1x1 cm. Zona nuo giliojo rezekcijos krašto nutolusi 4 cm, nuo odos - 1 cm.. 1(Extra). Reaktyvi limfadenopatija (2 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma (su minimalia mucinine diferenciacija), SUMINIS TNM: pT(m)1c(2 naviko židiniai: 19 mm ir 7 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties išplitusi aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DIN3/DCIS)(solidinė, kribriforminė, komedo) (4 židiniai).  Krūties intraduktalinės papilomos.. 1(Extra). 2 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.  2. SPENELIS: normali histologinė struktūra; žemiau - dilatuotas latakas su intraduktalinėmis papilinėmis struktūromis, klotomis dvisluoksniu epiteliu.   KRŪTIS: krūties audinyje - 2 riboti navikai (I ir II: mikroskopiškai 19 mm ir 7 mm), suformuoti fibrozuotoje stromoje plintančių solidinių, lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 9/10 DPRL. Pirmajame navike negausūs AB+ ekstraląsteliniai mucinai; fokaliai retrakcijos artefaktai aplink naviko lizdus. Aplink dilatuoti kanaliukai su kribriforminiais, negausiais solidiniais intraduktaliniais analogiškų naviko ląstelių proliferatais.   Kiti židiniai (III - VI): - riboti židiniai su DCIS struktūromis bei intraduktalinėmis papilomomis.. 2. Navikas (6 blokas): EMA(+++)(citopl. r-ja), 100%; D2-40+/ERG+ endotelizuotose ertmėse naviko plitimo neidentifikuota.  Navikas (7 blokas): HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.
answer:  1

 39%|███▉      | 260/661 [03:59<06:13,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Krūtis, biopsija. Trys bioptatai.. 3 fragmentuoti biopsiniai stulpeliai: I - 9 mm; II - 11 mm; III - 7 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Krūties audinį infiltruoja duktalinės struktūros ir negausūs netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 60% naviko ląstelių.  Ki67+ 5%.
answer:  0

 39%|███▉      | 261/661 [04:00<06:30,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra   2. pjūvio kraštai, ekstra.  3. sarginiai limfmazgiai, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 13x9x5 cm su odos lopu 8x3 cm, žymėtas viela. Vielos projekcijoje, pjūvyje - pilkšva, standi, netolygių ribų fibrozės zona 3,5x3x5 cm (sudėta visa), nuo artimiausio rezekcijos krašto nutolusi 0,2 cm (dažytas mėlynu tušu), nuo odos – 1,5 cm.. 1( pjūvio kraštai). Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.     2( pjūvio kraštai). Įprastinė duktalinė hiperplazija. Naviko plitimo nėra.     3(sarginiai limfmazgiai). Reaktyvi limfadenopatija (1 l/m).     4(Krūties sektorius). Krūties invazyvi gerai diferencijuota (G1, 4 balai pagal Nottingham) duktalinė karcinoma,   pT1a(m)(daugybiniai invazijos židiniai iki 3,3 mm mikroskopiškai)   pN0(sn)(1 l/m)    pLVI-0 (limfovaskulinė invazija neidentifikuota).   Naviko imunotipas:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 40% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 8%.    Žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1, kribriforminis ir papilinis piešinys; apie 30 mm).   DCIS struktūros siekia sektoriaus rezekcijos kraštą, invazijos židiniai nuo sektoriaus rezekcijos krašto nutolę bent 4,4 mm atstumu.  DCIS imunotipas:   Estrogenų receptoriai: stipri/vidutinė (+++/++) reakcija, 100% DCIS ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 30% naviko ląstelių branduoliuose.. 1. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.Naviko plitimo nėra.   2. Krūties audinys su fibrozės zonomis ir smulkiais, dalis cistiškai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Dalis latakų su kribriforminiais proliferatais, klotais dvisluoksniu epiteliu be atipijos. Naviko plitimo nėra.   3. 1 limfmazgis su I/II folikulais, sinusų histiocitoze, lipomatoze.  4. Krūties audinyje stambūs latakai (apie 30 mm zonoje), užpildyti kribriforminiais ir papiliniais proliferatais iš ląstelių švelniai polimorfiškais branduoliais, su negausiais kalcifikatais šalia.   Tarp latakų - daugybiniai invazyvūs, morfologiškai panašūs židiniai (didžiausias - 3,3 mm mikroskopiškai), suformuoti tubulių (~30%), trabekulių ir grandinėlių. Naviko ląstelės smulkaus ar vidutinio kalibro, negausia citoplazma, su smulkiais, hiperchromiškais, švelniai polimorfiškais branduoliais su pavienėmis smulkiomis nukleolėmis. Mitozių židiniuose <1/10DPRL.. Blokas 17:  Navikas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 8% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija,
answer:  30

 40%|███▉      | 262/661 [04:01<06:06,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 15 mm.. Invazinė lobulinė karcinoma (mažiausiai iki 10 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.. Krūties audinį 2-se bioptatuose infiltruoja iki 10 mm :   - juostos;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: neigiama  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono
answer:  1

 40%|███▉      | 263/661 [04:02<06:16,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a kraštas - skubus tyrimas  - be naviko  2. N2b kraštas - skubus tyrimas  - be naviko  3(1) ėminio aprašas: pašalintas kairės krūties darinys - planinis tyrimas  4(3) ėminio aprašas: kairės pažasties sarginiai limfmazgiai planiškai. 3(1). Krūties sektorius 11x5,5x5 cm su odos lopu 9,5x2,5 cm, žymėtas viela. Vielos projekcijoje, pjūvyje balkšvas, standus, neaiškiu ribu navikas 19x17x15 mm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos – 2 cm.  4(3). Riebalinio audinio fragmentai, bendras dydis 6x5x1,2 cm. Rasti 5 l/m iki 2 cm.. 1(2a). Riebalinis (krūties) audinys.  2(2b). Riebalinis (krūties) audinys.  3(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,9 cm) pN(sn)1a (2/5 l/m, mts 0,3 cm ir 1,7 cm; ekstranodalinis plitimas). LVI2(limfovaskulinė naviko invazija). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribriforminis, komedo tipas).  4(3). Duktalinės adenokarcinomos metastazės 2/5 l/m (mts 0,3 cm ir 1,7 cm; ekstranodalinis plitimas).     Ankstesnio/pirminio naviko tyrimo (B23-17508) duomenys  Estrogenų receptoriai: vidutinė (++) reakcija, 30% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: imunohistocheminė reakcija ribinė (2+). Nustatyta HER2 geno amplifikacija (FISH).  Ki67: proliferacinis indeksas 10%. Karštame taške 30%.. 1(2a). Brandžių lipocitų suformuotas audinys.  2(2b). Brandžių lipocitų suformuotas audinys.  3(1).  Krūties audinyje: A) navikas (trabekulines, negausias (5%) tubulines naviko struktūras formuoja ląstelės su negausia-kiek gausesne "švelniai" eozinofiline citoplazma, vidutinio kalibro, nežymiai polimorfiškais, gan retu chromatinu, dalis su smulkia nukleole branduoliais; mitozių navike iki 12 / 10 DPRL), B) DCIS (vidutinio ar stambaus kalibro kanaliukai, iškloti ląstelėmis su vidutinio laipsnio ar ryškia branduolių atipija).  4(3). Aukščiau aprašyto naviko metastazės dviejuose (2) iš penkių (5) limfmazgiuose (metastazės 0,3 cm ir 1,7 cm; ekstranodalinis plitimas).. nan
answer:  0

 40%|███▉      | 264/661 [04:03<06:03,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  18 G automatine biopsine adata punktuotas hipoechogeninis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~11x19 mm dydžio navikas kairiojoje krūtyje ties 12 val. vidurinėje dalyje, paimti trys biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 14 mm; II - 12 mm; III - 12 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G2; 7 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.    Vidutinio laipsnio intraduktalinė neoplazija (DCIS/DIN2).. Krūties audinį 3-se bioptatuose infiltruoja iki 12 mm :   - duktalinės struktūros (5% viso naviko), netaisyklingi kribroziniai kompleksai ir trabekulės;  - epitelinių vidutinio stambių ląstelių su ryškiai polimorfiškais branduoliais  negausioje bazofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.  Gretimai - keliuose latakuose analogiškų ląstelių tinklinės struktūros.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 15% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  100

 40%|████      | 265/661 [04:04<05:48,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 9 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 15 mm);  (G1; 5 b. pgl. Nottingham sist.) 1-me stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 5%.. Krūties audinį 1-me bioptate infiltruoja iki 15 mm :   - duktalinės pavienės struktūros ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) necirkuliari reakcija, 25%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 5% naviko ląstelių.  Progesterono receptoriai: stipri
answer:  0

 40%|████      | 266/661 [04:05<06:33,  1.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(3). dešinės pažasties sarginis limfmazgis - extra - 4 l/m be naviko;  2(2a). kraštas - skubus tyrimas - be naviko;  3(2b). kraštas - skubus tyrimas - LCIS;  4(1). pašalintas dešinės krūties kvadrantas - planinis tyrimas;  5(4). papildomas krašas - planinis tyrimas.. 4(1). Krūties sektorius 6,5x4x3,5 cm su odos lopu 6x2 cm. Krūties audinyje, pjūvyje pilkšvas, standus, neaiškių ribų navikas 17x13x10 mm, nuo odos nutolęs 1 cm, nuo giliojo rezekcijos krašto - 0,2 cm.  5(4). Riebalinio audinio fragmentas 1,5x1x0,3 cm.. 1(3, ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė, židininė fibrozė (3 l/m).   2(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.    3(2b, ekstra). "Kraštai": krūties lobulinė intraepitelinė neoplazija (LCIS). Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM:   pT1c (navikas 17 mm) N0(sn) (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Intraduktalinis karcinomos plitimas (kanaliukų kancerizacija).  Imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.   Progesterono receptoriai: vidutinė-stipri (++/+++) reakcija, 60% naviko ląstelių.   HER2: reakcija neigiama (1+).   Ki67: proliferacinis indeksas ~5%.   Krūties lobulinė intraepitelinė neoplazija (LCIS; konvencinė ir pleomorfinė).  Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Invazyvus navikas nuo artimiausio krūties sektoriaus rezekcijos krašto nutolęs - 0,7 mm;   konvencinis LCIS koaguliacijos zonose.   5(4). "Papildomas kraštas": fibrozuotas riebalinis audinys; be naviko.. 1(3, ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2(2a, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar hiperplastišku epiteliu. Kelios nedidelės koaguliuotos lobulės (planinio tyrimo stikluose neišliekančiomis) su monomorfiškomis, mažai kohezyviomis ląstelėmis šviesia citoplazma.   4(1). NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje su elastozės zonomis, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", solidinės naviko struktūros, suformuotos mažai kohezyvių, daugiausiai pabirai besidėstančių vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesiai eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais, fokaliai skeltais branduoliais su smulkiomis nukleolėmis; mitozės retos, sunkiai identifikuojamos, iki 1/10 DPRL. Šalia - naviko struktūrų plitimas kanaliukų spindžiuose. Perineurinė edema.   APLINKA: zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais; dalies centruose nekrotinis dedritas su negausiais PMN.    Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: infiltratyvaus naviko struktūros nutolusios 0,7 mm; koaguliacijos zonose nedideli koaguliuoti in situ komponento židiniai.   5(4). "Papildomas kraštas": fibrozuotas, vaskuliarizuotas brandžių lipocitų suformuotas audinys; be naviko.. 3(2b, ekstra). "Kraštai": CK14(+) mioepitelinis sluoksnis.   4(1). NAVIKAS (17 blokas): E-Cadherin(-) invazyviame ir in situ komponentuose.   NAVIKAS (18 blokas):  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progeste
answer:  0

 40%|████      | 267/661 [04:06<06:10,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 5 biopsiniai stulpeliai medžiagos histologiniam ištyrimui. 5 biopsiniai stulpeliai: I - 13  II - 11 mm; III - 12 mm; IV - 8 mm; V - 8 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 6%.  Žemo laipsnio intraduktalinė karcinoma (DCI; DIN1, kribriforminis tipas).. Krūties audinį infiltruoja smulkios duktalinės struktūros, pabiros smulkios minimaliai polimorfiškos ląstelės ir tų ląstelių juostos, mitozių mažiau 1/10 DPRL.  Negausios intraduktalinės kribriforminės struktūros iš monomorfiško epitelio.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 6%.
answer:  0

 41%|████      | 268/661 [04:07<06:13,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- virštuinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- Deš. pažasties sarginiai limfmazgiai, skubu  4(3) - Deš. krūties kvadrantas, planinis.. 4. (3) Krūties sektorius 12x7x5,5 cm, žymėtas viela su odos lopu 10,5x4 cm. Krūties audinyje balkšvas, standus, neaiškių ribų  (I) navikas 11x10x9 mm, nuo rezekcijos krašto nutolęs 1 cm, nuo odos 3 cm. Šalia (II) navikas neaiškių ribų 8x6x6 mm, nuo rezekcijos krašto nutolęs 1,3 cm, nuo odos - 1,5 cm, nuo I naviko - 0,3 cm. Navikai sudėti visi.. Atlikti pjūviai Prosigna.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(m)(2 židiniai 17 mm, 7 mm) pN0(sn)(0/3 l/m) LVI-2(limfovaskulinė invazija).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (2 židiniai 17 mm, 7 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, tubulinėmis, kribriforminėmis struktūromis besidėstančių ląstelių  vidutinio gausumo eozinofiliška-amfofiliška citoplazma, vidutiniais, vidutiniškai ryškiai polimorfiškais, ovaliais branduoliais ryškiomis nukleolėmis; mitozių 3/10 DPRL. limfovaskulinė invazija.  Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu.. Navikas: CD14(-); CD31+ endotelis.
answer:  0

 41%|████      | 269/661 [04:08<06:12,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1- viršutinis kraštas - Extra  2 - apatinis kraštas - Extra  3 - sarginiai l/m - Extra  4 - kvadrantas - planiniam tyrimui. 4. Krūties sektorius 10x7x5,5 cm, su odos lopu 9x3 cm. Pjūvyje - pilkšvas, neaiškių ribų, standus navikas 22x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 1,3 cm, nuo odos - 2 cm.. 1. Krūties intraduktalinė papiloma.  2. Krūties stulpinis epitelio pokytis.   3. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham s.) duktalinė karcinoma su mikropapilinės karcinomos komponentu (~10%), suminis Nr. 1 - 4 pTNM:   pT2 (22 mm) pN0(sn) (0/1 l/m); LVI0 (limfovaskulinės naviko invazijos patikimai neidentifikuota).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-9611, žr. pastabą.. 1. Nežymiai fibrozuotame krūties audinyje - grupė latakų su intraduktalinėmis papilinėmis struktūromis, klotomis mioepitelinėmis ir duktalinėmis lątelėmis.   2. Krūties audinys su nežymia stromos fibroze, negausiais latakais su stulpiniu epitelio pokyčiu ir apikalinės sekrecijos požymiais.   3. Limfmazgis(1) kiek tušuota architektūra, retai stambiais antriniais folikulais, nežymiai fibrozuota stroma.   4. Krūties audinyje - navikas, formuojamas infiltratyviai plintančių trabekulinių, solidinių, negausių blogai suformuotų liaukinių ir mikropapilinių (iki 10%) struktūrų, sudarytų iš vidutinio dydžio tubulinių ir poligonalinių ir stulpinių ląstelių gausia eozinofiliška citoplazma, vidutiniškai polimorfiškais ovaliais branduoliais su grūdėtu chromatinu, kiek akcentuotomis smulkiomis nukleolėmis dalyje ląstelių. Navike iki 9 mitozių/ 10 DPRL. Limfovaskulinės naviko invazijos patikimai neidentifikuota.. 3. Limfmazgis:   PANCK-, GATA3+ limfocitai, e-cadherin+ histiocitai(?).
answer:  0

 41%|████      | 270/661 [04:09<05:55,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Krūties audinį infiltruoja smulkios duktalinės struktūros ir smulkūs kribroziniai/solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+ 5
answer:  0

 41%|████      | 271/661 [04:10<06:08,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  CA mammae dex. cT2N0M0 - IIA (intramamarinis limfmazgfis verifikuotas, pažastis - N0) -extra.   1(2a). Kraštai - extra;  2(2b). Kraštai - extra;  3. Dešinės pažasties sarginis limfmazgis - extra (3 l/m be naiko);  4(1). Pašalintas dešinės krūties kvadrantas - planinis tyrimas;   5(4). Markiruotas dešinės pažasties intramamarinis verifikuotas limfmazgis - planinis tyrimas.. 4(1). Krūties sektorius 10,5x5,5x5,58 cm su odos lopu 9,5x4,7 cm. Pjūvyje pilkšvas, standus, neaiškių ribų navikas 32x30x21 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 0,6 cm.  5. Krūties sektorius 7,5x3x3,5 cm (žymėtas dažais) su odos lopu 7x2,5 cm, žymėta viela. Vielos projekcijoje pilkšvas, ribotas limfmazgis? 1x1x0,8 cm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 2,5 cm.. 1(ekstra). Reaktyvi limfadenopatija (3 l/m).  2(ekstra). Riebalinis - fibrozinis audinys.  3(ekstra). Riebalinis - fibrozinis audinys.  4. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(32 mm navikas) pN1a(sn)(1/4 l/m 8 mm) LVI-2(limfovaskulinė invazija). Perineurinis. R0(radikali rezekcija).  5. Duktalinės karcinomos metastazė intramamariniame limfmazgyje (8 mm).    Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Androgenų receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 70%.. 1(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  2(ekstra). Riebalinis - fibrozinis audinys.  3(ekstra). Riebalinis - fibrozinis audinys.  4. Krūtyje - navikas ekspansyviu augimo frontu, suformuotas lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 44/10 DPRL. Limfovaskulinė invazija. Perineurinis plitimas.  5. Intramamarinis limfmazgis su aprašyto naviko metastaze 7 mm.. Navikas(23):  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Androgenų receptoriai: neigiama reakcija.  Ki67 proliferacinis aktyvumas 70%.
answer:  0

 41%|████      | 272/661 [04:10<05:48,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Paimti 2 biopsiniai stulpeliai.. 2 biopsiniai stulpeliai: I - 13 mm; II - 10 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 8%.. Krūties audinį 2-se bioptatuose infiltruoja iki 13 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje citoplazmoje;   - su mitozėmis iki 2/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 50%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 8% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  100

 41%|████▏     | 273/661 [04:11<05:33,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stulpeliai. 3 biopsiniai stulpeliai: I - 11 mm; II - 8 mm; III - 6 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 15%.. Krūties audinį infiltruoja netaisyklingi nedideli kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 30% naviko ląstelių.  Ki67+ 15%.
answer:  0

 41%|████▏     | 274/661 [04:12<05:31,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N3): kairės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko  4(N1): pašalintas kairės krūties kvadrantas - planinis tyrimas. 4(N1). Krūties sektorius 13,5x9x5x cm, su odos lopu 12x5 cm. Krūties audinyje pilkšvas, standus, gan aiškių ribų navikas 1,6x1,0x0,6 cm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 2,4 cm. Krūties audinys fibrozuotas 9x6 cm plote. Nuo naviko, 2 cm atstumu pilkšvas, standus židinys 0,5 cm, nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo odos - 3,2 cm.. PAPILDYTA  1(N2a). Krūties fibrocistiniai pokyčiai.  2(N2b). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (3 l/m).  4(N1). Krūties invazyvi duktalinė adenokarcinoma (gerai diferencijuota / G1 / 5 balai pagal Nottingham), TNM (Nr.1-Nr.4): pT1c(m) (ne mažiau 3 židinių: 1,6 cm, 0,5 cm, 0,4 cm) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės naviko invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 6%.. nan. nan
answer:  0

 42%|████▏     | 275/661 [04:13<05:48,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.  2(2b). Kraštai - skubus tyrimas - be naviko.  3. Kairės pažasties sarginis limfmazgis - skubus tyrimas 2l/m su makrometastazėm.(Atkreiptį dėmesį į limfmazgių skaičių, operacijos metu rasti 3 aiškiai čiuopiami limfmazgiai, gal yra ir trečias limfmazgis?)  4(1). Pašalintas kairės krūties kvadrantas planinis tyrimas. 4. Krūties sektorius 16x7x4 cm, su odos lopu 15,5x6 cm, žymėtas viela. Krūties audinyje pilkšvas, standus, neaiškių ribų navikas 20x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 0,3 cm. Nuo naviko 6,5 cm atstumu vielos projekcijoje neaiškių ribų pilkšvas darinys 7x6x6 cm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 4,5 cm.. 1(2a)  kraštai - krūties audinys be pokyčių.  2(2b) kraštai - krūties audinys be pokyčių.  3(2) kairės pažasties sarginis limfmazgis: karcinomos plitimas iki 12 mm 2-se iš 3 limfmazgiuose.  4(1) kairės krūties kvadrantas. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT1c pN1a pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 20%.    Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS; kribriforminis tipas; 0,5 mm nuo operacinio krašto).. 1(2a)  kraštai - krūties audinys be pokyčių.  2(2b) kraštai - krūties audinys be pokyčių.  3(2) kairės pažasties sarginis limfmazgis: karcinomos plitimas iki 12 mm 2-se iš 3 limfmazgiuose; stebimas ekstranodulinis plitimas.  4(1) kairės krūties kvadrantas. Krūties audinyje naviką (mikroskopoiškai 19 mm) formuoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai ir vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL. Atskiro darinio dilatuotuose kanaliukuose (esančiuose 0,5 mm nu operacinio krašto) kribroziniai intraduktaliniai neryškiai ar vidutiniškai polimorfiško epitelio proliferatai.. nan
answer:  0

 42%|████▏     | 276/661 [04:14<05:36,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 2  biopsiniai  stulpelis iš kairės pažasties  l/m  2 but. 1  biopsinis  stulpelis  iš kairės krūties BI-RADS 5 darinio. 1. 2 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 4 mm.  2. Biopsinis stulpelis 13 mm ilgio.. N1: Limfmazgio bioptatai be naviko metastazių.  N2: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 20-25%.. N1: Limfmazgio bioptatai be naviko metastazių.  N2: Krūties audinį infiltruoja nedideli netaisyklingi solidiniai kompleksai iš vidutiniškai ir ryškiai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 20-25%.
answer:  1

 42%|████▏     | 277/661 [04:15<05:49,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2a  kraštas skubus tyrimas be naviko  2 ėminio aprašas: 2b kraštas skubus tyrimas be naviko   3 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas 2l/m be naviko   4(1) ėminio aprašas: pašalintas dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 5,5x4,5x2,5 cm su odos lopu 5,5x2 cm, žymėtas viela. Vielos projekcijoje, pjūvyje pilkšvas, standus, gan aiškių ribų navikas 10x10x8 mm navikas, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,2 cm. Atskirai tame pačiame inde odos fragmentas 4,3x0,6 cm. Odoje rusvas, gruoblėtas, iškilęs darinys 0,4x0,4x0,3 cm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm.. 1. Krūties audinys.  2. Krūties audinys.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 15 mm), pN0(sn)(0/2 l/n), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Fibrocistiniai krūties pokyčiai.  Dermalinis nevocitinis nevus.. 1. Krūties audinyje židininė fibrozė ir smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2. Krūties audinyje lobulės, klotos dvisluoksniu epiteliu bei židininė apokrininė epitelio metaplazija.  3. Du limfmazgiai (2 l/m) su sinusų histiocitoze.  4. Krūties audinyje - navikas (15 mm mikroskopiškai), suformuoti susiliejančių lizdinių, kribriforminių bei negausių tubulinių struktūrų iš vidutinio kalibro, vidutinio gausumo eozinofiline citoplazma ląstelių, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiais branduolėliais; mitozių 9/10 DPRL. Limfovaskulinis plitimas (LVI2). Greta naviko dilatuoti latakai, užpildytų kribriforminių proliferatų, suformuotų analogiškų navikui ląstelių. Aplinkiniame krūties audinyje, fibrozuotoje stromoje, gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu su fokalia apokrinine metaplazija.  Odos fragmente, dermoje - formuodami lizdus ir difuziškai plinta nevocitai su brendimo požymiais. Nevocitai rezekcijos krašte.. nan
answer:  0

 42%|████▏     | 278/661 [04:16<05:44,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  ca mammae dex - extra  1 ėminio aprašas: 1 pjūvio kraštas, ekstra.  2 ėminio aprašas: 2 pjūvio kraštas, ekstra.   3 ėminio aprašas. sarginiai l/m, ekstra.  4. sektorius, planinis.. 4. Krūties sektorius 15x7,5x4,5 cm su odos lopu 12,5x3 cm. Krūties audinyje, balkšvas, standus, neaiškių ribų navikas 31x27x25 mm, nuo artimiausio rezekcijos krašto nutolęs 1,2 cm, nuo odos – 2,5 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/4 l/m, 4,75 mm).  4. Krūties invazyvi blogai diferencijuota (G3; 9 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT2(navikas 31 mm), pN1a(1/4 l/m, metastazė iki 4,75 mm), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.. 1. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.   2. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Viename iš keturių limfmazgių keli žemiau aprašyto naviko židiniai, didžiausias 4,75 mm.   4. Krūties audinyje navikas (31 mm makroskopiškai), infiltratyviu augimo frontu, suformuotas stambių, besiliejančių lizdų, trabekulių ir negausių  tubulinų struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, vidutiniškai ir fokaliai ryškiai polimorfiškais, hiperchromiškais, smulkiai grūdėtu chromatinu branduoliais. Mitozių navike 50/10DPRL. Limfovaskulinė naviko invazija neidentifikuota(LVI0).. nan
answer:  0

 42%|████▏     | 279/661 [04:17<05:52,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 (1a)- viršutinis kraštas, skubu  2 (1b)- apatinis kraštas, skubu  3 (2). sarginiai limfmazgiai, skubu  4 (3). Kairės krūties sektorius, planinis  5 (4). Papildomas kraštas - planinis. 4(3). Krūties sektorius 4,5x4x2,8 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje - balkšvas, standus, pakankamai aiškių ribų navikas 14x12x10 mm navikas (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,4 cm.  5(4). Riebalinio audinio fragmentas 1,5x1,2x0,4 cm. v/m. 1. Krūties audinys be patologinių pokyčių.  2. Krūties intraduktalinė papiloma.   3. Reaktyvi limfadenopatija (2 l/m).   4. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma,   pT1c (14 mm) pN0(sn) (0/2 l/m); LVI0 (limfovaskulinės naviko invazijos nenustatyta).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-26741, žr. pastabą.   Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminė).   Adenozė.    5. Krūties audinys be patologinių pokyčių.. 1. Krūties audinys be patologinių pokyčių.   2. Krūties audinyje - grupė latakų su intraduktalinėmis papilinėmis struktūromis ir adenomatozinio tipo proliferatais iš mioepitelinių ir duktalinių ląstelių, aplinkiniai latakai su stulpiniu epitelio pokyčiu ir apikalinės sekrecijos požymiais bei epitelio hiperplazija.   3. Limfmazgiai (2) su negausiais antriniais folikulais, sinusų histiocitoze, stromos lipomatoze ir nežymia fibroze.   4. Krūties audinyje - navikas, formuojamas infiltratyviai plintančių kompleksinių liaukinių, kribriforminių, tubulinių ir retų trabekulinių struktūrų, sudarytų iš stulpinių ir kubinių ląstelių vidutiniškai polimorfiškais, kiek nelygaus kontūro branduoliais su vezikulizuotu chromatinu; mitozių iki 8/10 DPRL.  Greta infiltratyvių naviko struktūrų, keli latakai su intraduktaliniais kribriforminiais ir arkadiniais duktalinio tipo ląstelių proliferatais su nežymiu ar vidutiniu branduolių polimorfizmu, "apikalinės" sekrecijos požymiais.   Organoidinis smulkių, kiek deformuotų kanaliukų proliferatas krūties audinyje greta naviko.   5. Krūties audinys be patologinių pokyčių.. nan
answer:  0

 42%|████▏     | 280/661 [04:18<05:34,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 3%.. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozės pavienės.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 3%.
answer:  0

 43%|████▎     | 281/661 [04:19<05:54,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. Kairės pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: 2. Kairė krūtis, planinis. 2. Krūtis 920 gramų svorio, 21x18x5 cm. Krūties audinyje, apatinių kvadrantų riboje, ties centrine dalimi 2 balkšvi, standūs, susiliejantys, neaiškių ribų navikai (I navikas) 48x32x19 mm, nuo odos nutolę 2,5 cm, nuo giliojo rezekcijos krašto - 1,5 cm. Viršutiniame medialiniame kvadrante balkšvas, standus neaiškių ribų II navikas 19x15x7 mm, nuo odos nutolęs 4,5 cm, nuo giliojo rezekcijos krašto - 0,5 cm.. 1. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/2 l/m, 2,5 mm).  2. Krūties invazyvi mišri blogai diferencijuota (G3; 9 b. pgl. Nottingham) lobulinė (75%) ir duktalinė karcinoma (25%), suminis TNM: pT2(m)(navikai 44 mm ir 21 mm), pN1a(sn)(1/2 l/m), LVI2(limfovaskulinis plitimas). II-sis naviko židinys, plinta koaguliuoatme rezekcijos krašte, ties skersaruožiu raumeniu. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).   Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai. Intraduktalinė krūties papiloma.. 1. Viename limfmazgyje iš dviejų (1/2 l/m) žemiau aprašyto naviko metastazė iki 2,5 mm skersmens.  2. Krūties audinyje - hialinizuotoje stromoje 2 naviko židiniai (44 mm ir 21 mm mikroskopiškai) infiltratyviu augimo frontu, suformuoti 2 komponentų: a) trabekulinių, juostinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, ryškiai polimorfiškais, hiperchromiškais branduoliais; b) smulkių lizdinių, trabekulinių ir pavienių struktūrų su spindžių formacija, suformuotų kiek gausesne eozinofiline citoplazma ląstelių su vidutiniškai polimorfiškais, hiperchromiškais branduoliais. Gausi perinavikinė limfocitų infiltracija. Mitozių navike iki 26/10DPRL. Limfovaskulinė naviko invazija (LVI2). II-sis naviko židinys, plinta koaguliuoatme rezekcijos krašte, ties skersaruožiu raumeniu. Greta naviko daugybiniai dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, polimorfiškais, hiperchromiškais branduoliais. Šalia gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu su fokalia epitelio hiperplazija. Spenelio projekcijoje - dilatuotas latakas su fibrovaskulinėmis struktūromis, klotomis dvisluoksniu epiteliu monomorfiškais branduoliais. Blokas 10:  HER2: reakcijos naviko ląstelių membranoje nėra.  Blokas 20:  E-Cadherin: (+++)membr.r-ja 100%;  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 43%|████▎     | 282/661 [04:19<05:42,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: kairė krūtis su pažasties l/m, planinis. Krūtis 403 gramų svorio, 16x13,5x5 cm, su pažasties narveliena 9,5x6x3 cm.   Krūties audinyje, centrinėj dalyje pilkšvas, standus, neaiškių ribų navikas 55x30x25 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 1,3 cm.   Pažasties narvelienoje rasta 12 limfmazgių, didžiausias 2 cm.. Gerai diferencijuota (G1, 5 balai pgl. Nottingham) krūties invazinė duktalinė karcinoma  pT3 pN1a pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. Krūties audinį infiltruoja (iki 65 mm mikroskopiškai) vienaeilės juostos (< 90 proc.) ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.  Gretimai - analogiškų ląstelių intraduktaliniai solidiniai proliferatai.  Plitimo operaciniame krašte nestebima (2,3 mm).  Atipinių ląstelių plitimas iki 12 mm 3-se iš 25 limfmazgių; stebimas ekstranodulinis plitimas.. nan
answer:  0

 43%|████▎     | 283/661 [04:20<05:30,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 4 biopsiniai stulpeliai. 4 biopsiniai stulpeliai: I - 11 mm; II - 8 mm; III - 13 mm; IV - 9 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. Krūties audinį infiltruoja smulkios duktalinės struktūros, nedideli kribroziniai ir solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 40% naviko ląst
answer:  1

 43%|████▎     | 284/661 [04:21<05:21,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 55%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 55%.
answer:  1

 43%|████▎     | 285/661 [04:22<05:13,  1.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. Pjūvio kraštai, ekstra.   3. Sarginiai l/m, planinis.   4. Sektorius, planinis.. 3. Riebalinio audinio fragmentas 4x3,5x1 cm. Rasti 2 limfmazgiai iki 1,6 cm. v/m  4. Krūties sektorius 5,5x3x2,7 cm, su odos lopu 5x2 cm. Krūties audinyje, pjūvyje pilkšvas, standus, aiškių ribų navikas 13x8x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 1 cm.. N1-2: Krūties audinys be naviko.  N3: Limfmazgiai be naviko (2 l/m); pN0(sn).  N4: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c (13mm).. N1-2: Krūties audinys be naviko.  N3: Limfmazgiai su lipomatozės židiniais, be naviko (2 l/m).  N4: Kūties audinyje 13mm navikas: duktalinės struktūros, nedideli kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. nan
answer:  0

 43%|████▎     | 286/661 [04:23<05:05,  1.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja negausios duktalinės struktūros ir netaisyklingi kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 43%|████▎     | 287/661 [04:23<04:59,  1.25it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 16 mm; III - 12 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  0

 44%|████▎     | 288/661 [04:24<05:12,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: Pašalintas markiruotas kairės krūties kvadrantas - planinis tyrimas  2 ėminio aprašas: N2A - kraštas  - planinis tyrimas  3 ėminio aprašas: N2B - kraštas  - planinis tyrimas. 1. Krūties sektorius 8,5x4x5,5 cm su odos lopu 6,5x2,3 cm, žymėtas viela. Vielos projekcijoje, pilkšvas standus neaiškių ribų navikas 6x5x5 mm, nuo giliojo rezekcijos krašto nutolęs 0,9 cm, nuo odos - 1,6 cm.  2. Riebalinio audinio fragmentas 3x1,6x0,7 cm. v/m  3. Riebalinio audinio fragmentas 2x1,6x0,4 cm. v/m. N1: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 6%.  N2a: Žemos laipsnio intraduktalinė krūties karcinoma (DCIS/DIN1; 4mm židinys; mikropapilinis tipas).  N2b: Normalios struktūros krūties audinys.. N1: Krūties audinyje 6mm navikas: duktalinės struktūros, negausūs netaisyklingi kribroziniai kompleksai, juostos ir trabekulės iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.  N2a: Krūties audinyje 4mm židinys su dilatuotais kanaliukais su mikropapiliniais intraduktaliniais minimaliai polimorfiško epitelio proliferatais.  N2b: Krūties audinys su negausiais kanaliukais, išklotais normaliu epiteliu.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 5% naviko ląstelių.  Ki
answer:  6

 44%|████▎     | 289/661 [04:25<05:42,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas  2 ėminio aprašas: N2a kraštai - planinis tyrimas  3 ėminio aprašas: N2b kraštai - planinis tyrimas  4 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - planinis tyrimas. 1. Krūties sektorius 14x8x6 su odos lopu 12x4 cm. Krūties audinyje balkšvas, standus, apvalios formos, skiltėtas, neaiškių ribų navikas 28x23x24 mm, nuo artimiausio rezekcijos krašto nutolęs mažiau 0,1 cm, nuo odos - 6 cm.  2. Riebalinio audinio fragmentas 3x2x0,6 cm. v/m   3. Riebalinio audinio fragmentas 2x2x1 cm. v/m  4. Riebalinio audinio fragmentas 3x2x1,5 cm. Rastas limfmazgis 1,8 cm.. 1. Krūties invazyvi adenoidinė cistinė karcinoma (solidinis-bazaloidinis tipas) ir blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma. Žr. pastabą.  SUMINIS TNM: pT2 (2,8 cm) N0(sn)(0/1 l/m) LVI-2(limfovaskulinė invazija). Navikas nuo sektoriaus rezekcijos krašto nutolęs <0,1 mm.   Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis-kribriforminis tipas).     Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.   Her2 imuninė reakcija: neigiama (0).   Ki67 proliferacinis aktyvumas 10%, fokaliai 25%.    2. N2a kraštai - planinis tyrimas: Krūties audinys.   3. N2b kraštai - planinis tyrimas: Riebalinis fibrozinis audinys.  4. N3: kairės pažasties sarginis limfmazgis - planinis tyrimas: Reaktyvi limfadenopatija (1 l/m).. 1. Krūties audinyje - navikas infiltratyviu augimo frontu, suformuotas : a) solidiniais plotais, lizdais su negausiais reguliariais spindžiais,negausiomis tubulinėmis-kribriforminėmis struktūromis besidėstančių ląstelių negausia tamsia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; b) solidinių plotų ir trabekulių iš ląstelių vidutinio gausumo eozinofiliška citoplazma, ryškiai polimorfiškais, stambaus kalibro, nereguliaraus kontūro, fokaliai vezikulizuotais branduoliais su ryškiu branduolėliu. Mitozių navike iki 23/10 DPRL. Pavienės "komedo" tipo nekrozės lizdų centruose. Naviko plitimas endotelizuotuose spindžiuose (LVI-2). Navikas nuo rezekcijos krašto nutolęs <0,1 mm.  Krūties audinyje fibrozė, elastozė bei dilatuoti kanaliukai su intraduktaliniais solidiniais ir kribriforminiais proliferatais iš ląstelių vidutinio gausumo eozinofiliška citoplazma, apvaliais ar ovoidiškais, vezikulizuotais, polimorfiškais branduoliais su nukleolėmis.   Dalyje kanaliukų apokrininė metaplazija.  2. Krūties audinys su negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Riebalinis fibrozinis audinys.  4. Limfmazgis su I folikulais, sinusų histiocitoze ir lipomatoze.. Navikas, 4 blokas:   Estrogenų receptoriai: neigiama reakcija;  Progesterono recepotoriai: neigiama reakcija;  HER2: neigiama reakcija (0 balų);   Ki67 proliferacinis aktyvumas 15%, fokaliai 25%;  CD117(++/+++)(citopl. r-ja) 70%;  EMA: neigiama reakcija;
answer:  1

 44%|████▍     | 290/661 [04:26<05:32,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 18 G automatine biopsine adata punktuotas ~12x36 mm dydžio, netolygiai iki 10 mm sustorėjusiu žieviniu sluoksniu patologinis l/m dešiniosios pažasties I lygmenyje, paimti du biopsiniai stulpeliai histologijai (I buteliukas).   2. 18 G automatine biopsine adata punktuotas didelių matmenų (>50 mm) išopėjęs navikas dešiniojoje krūtyje, paimti du biopsiniai stulpeliai histologijai (II buteliukas).. 1. 2 biopsiniai stulpeliai: I - 12 mm; II - 12 mm.  2. 2 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 14 mm.. 1. Limfmazgio bioptatai su duktalinės karcinomos metastazėmis.   2. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 9%.. 1. Limfmazgio bioptatai su žemiau aprašyto naviko židiniais.   2. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. 2. Navikas (3 blokas):  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių m
answer:  100

 44%|████▍     | 291/661 [04:27<05:13,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 bioptatai 22 mm  12G adata iš ~3 cm   ploto su mkk. Aiškių kalcinatų bioptatuose nematyti.. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 12 mm; III - 11 mm.. Vidutinio laipsnio intraduktalinė karcinoma (DCIS/DIN2, solidinis tipas).  Gerai diferencijuota invazinė duktalinė karcinoma (mikroskopinis židinys apie 0,4mm).  Estrogenų receptorių reakcija navike 100%.. Krūties audinyje dilatuotuose kenaliukuose solidiniai neryškiai polimorfiškų ląstelių proliferatai. Mikroskopinis invazinio augimo židinys aplinkinėje stromoje (apie 0,4mm).. nan
answer:  1

 44%|████▍     | 292/661 [04:28<05:10,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but.  4 biopsiniai stulpeliai iš BI-RADS 4c darinio periferijoje   2 but. 3 biopsiniai stulpeliai iš BI-RADS 4a darinio vidurinėje dalyje. 1. 4 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 8 mm; IV - 8 mm.   2. 3 biopsiniai stulpeliai: I - 5 mm; II - 4 mm; III - 6 mm.. N1: Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.  N2: Ryški krūties audinio fibrozė, kanaliukų atrofija, galimai sklerozuota fibroadenoma.. N1: Krūties audinyje mucininėje stromoje netaisyklingi kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  N2: Ryški kompaktiška krūties audinio fibrozė, formuojanti gana ribotus mazgus, pavieniai atrofiški kanaliukai.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67+ 4%.
answer:  0

 44%|████▍     | 293/661 [04:29<05:02,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. 1 biopsinis stulpelis 10 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 1-2%.. Krūties audinį infiltruoja duktalinės struktūros ir smulkūs solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 44%|████▍     | 294/661 [04:29<04:56,  1.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 15 mm; II - 14 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20-25%.. Krūties audinį infiltruoja netaisyklingi kribroziniai/solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 20-
answer:  1

 45%|████▍     | 295/661 [04:30<05:01,  1.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1 pašalintas kairės krūties markiruotas plotas - planinis tyrimas  N2a kraštas - planinis tyrimas  N2b kraštas - planinis tyrimas. 1. Krūties sektorius 5x2,5x5 cm su oda  3,5x1,5 cm, žymėtas viela. Vielos projekcijoje - pilkšvas, standus, aiškių ribų navikas 16x10x10 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 3,7 cm.  2. Riebalinio audinio fragmentas 2x1,5x0,6 cm. v/m  3. Riebalinio audinio fragmentas 2,2x2x0,5 cm. v/m. N1: Gerai diferencijuota (G1, 4balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(16mm).  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 6%.  N2-3: Riebalinio ir krūties audinio fragmentai be naviko plitimo.. N1: Krūties audinyje 16mm navikas: smulkios duktalinės struktūros, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.  Aplink naviką negausūs intraduktaliniai monomorfiškų ECAD negatyvių ląstelių proliferatai (LCIS intraduktalinis plitimas).  N2-3: Riebalinio ir krūties audinio fragmentai be naviko plitimo.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 6%.
answer:  1

 45%|████▍     | 296/661 [04:31<05:23,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2A) - kraštas - extra - be naviko   2(N2b)-kraštas-extra - ADH  3(N2c)-kraštas-extra - be naviko  4(N3)-l/m-extra - be naviko  5(N4)- pap. kraštas - extra - be naviko  6(N1) - sektorius- planinis tyrimas. 6. Krūties sektorius 10,5x6,5x5 cm, su odos lopu 8,5x6 cm. Krūties audinyje pilkšvas, standus, neaiškių ribų darinys 45x35x30 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nu odos - 0,6 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai; paprasta intraduktalinė hiperplazija.  3. Fibrocistiniai krūties pokyčiai.  4. Reaktyvi limfadenopatija (1 l/m).  5. Krūties audinys.  6. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) lobulinė karcinoma, suminis tyrimo TNM: pT2(navikas - 45mm) pN0(sn)(0/1 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-44252 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  Ki67+ 8%."  Lobulinė krūties Carcinoma in situ(LCIS). Fibrocistiniai krūties pokyčiai; intraduktalinės krūties papilomos.. 1. Krūties audinyje - fibrozės septos su fokaliai cistiškai dilatuotais latakais, klotais dvisluoksniu epiteliu.  2. Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakais, klotais dvisluoksniu epiteliu; židininė paprasta intraduktalinė hiperplazija.  3. Krūties audinyje - fibrozės septos su pavieniais latakėliais, klotais dvisluoksniu epiteliu.  4. Vienas (1) limfmazgis be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  5. Krūties audinyje - fibrozės septos su pavieniais latakėliais, klotais dvisluoksniu epiteliu.  6. Krūties fibroziniame ir tarp lipocitų plinta navikas, formuojamas difuziškai ir trabekulėmis plintančių vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutinio kalibro ląstelių, nežymiai, vietomis vidutiniškai polimorfiškais branduoliais; navike iki 4 mitozių/10 DPRL; pavieniai dilatuoti latakėliai su solidiniais diskohezyvių atipinių ląstelių proliferatais (LCIS). Krūties audinyje - pavieniai dilatuoti latakai su fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu; fokaliai cistiškai dilatuotais latakais, klotais dvisluoksniu epiteliu. Naviko struktūros - koaguliuotame giliajame rezekcijos krašte.. nan
answer:  0

 45%|████▍     | 297/661 [04:32<05:35,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a - naviko kraštai (ekstra tvarka) - be naviko  2 ėminio aprašas: N2b - naviko kraštai (ekstra tvarka) - be naviko  3 ėminio aprašas: N3- sarginis l/m dešinės pažasties (ekstra tvarka) - 3 l/m viename iš trijų mikrometastazė  4 ėminio aprašas: N1: kvadrantas (planine tvarka). 4. Krūties sektorius 10,5x7x5 cm, su odos lopu 10,5x4 cm. Pjūvyje balkšvas, standus, gan aiškių ribų navikas 42x30x39 mm, nuo odos nutolęs 1,5 cm, nuo artimiausio rezekcijos krašto - 0,1 cm. Rezekcijos kraštas dažytas mėlynai, tarp pjūvių - žaliai.. 1(ekstra). Riebalinis fibrozinis audinys.  2(ekstra). Krūties audinys.  3(ekstra). Krūties karcinomos mikrometastazė limfmazgyje (microMTS 1/3 0,6 mm).    4. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) mišri duktalinė-lobulinė karcinoma, SUMINIS TNM: pT2(42 mm navikas) pN1mi(microMTS 1/3 0,6 mm). LVI-2(limfovaskulinė invazija). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 1% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+).  Ki67 proliferacinis aktyvumas 25%.  HER2 geno amplifikacija vertinta IHC kontekste, interpretuota kaip NEIGIAMA (žr. molekulinio tyrimo aprašymą ir pastabas).. 1(ekstra). Riebalinis fibrozinis audinys.  2(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 1 iš 3 limfmazgių aprašyto naviko mikrometatazės iki 0,6 mm.  4. Krūtyje - navikas ekspansyviu augimo frontu, suformuotas trabekulinėmis struktūromis, lizdais, solidiniais potais grandinėlėmis bei pabirai besidėstančių ląstelių vidutinio gausumo eozinofiliška ir gausesne ryškai, grūdėta citoplazma, vidutiniais - stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, dalis ekscentriškais branduoliais ryškiomis nukleolėmis; mitozių 18/10 DPRL. Limfovaskulinė invazija.. Navikas(19 blokas):  E-cadherin(+++) membr. r-ja 100% duktaliniame komponente, (+) trūkinėjanti r-ja 40%.
answer:  0

 45%|████▌     | 298/661 [04:33<05:39,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra;  2(2b). Kraštai - extra;  3. Kairės pažasties sarginis limfmazgis - extra (viename iš trijų limfmazgių mikrometastazė);  4(1). Pašalintas kairės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 13x6,5x5 cm su odos lopu 13,5x3,5 cm. Pjūvyje, balkšvas, standus, neaiškių ribų navikas 42x38x26 mm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos – 2,5 cm. 1(ekstra). Riebalinis audinys.  2(ekstra). Riebalinis audinys.  3(ekstra). Krūties duktalinės karcinomos mikrometastazė limfmazgyje (1/3 l/m micro MTS 0,9 mm).  4. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(42 mm navikas) pN1mi(sn)(1/3 l/m microMTS 0,9 mm)LVI-4(masyvi limfovaskulinė invazija venose ir smulkiose limfagyslėse). R0(radikali rezekcija).  Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis tipas).    Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: silpna reakcija 5% naviko ląstelių.   Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.. 1(ekstra). Riebalinis audinys.  2(ekstra). Riebalinis audinys.  3(ekstra). 1 iš 3 limfmazgių aprašyto naviko mikroametastazė 0,9 mm.  4. Krūtyje - navikas ekspansyviu augimo frontu, suformuotas nereguliariomis, trabekulinėmis struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių  vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 15/10 DPRL. Greta dilatuoti kanaliukai su solidiniais proliferatais iš analogiškų navikui ląstelių. Limfovaskulinė invazija venose ir smulkiose limfagyslėse.. Navikas:(11 blokas):  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: (+)(brand. r-ja) 5%.  HER2: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.
answer:  1

 45%|████▌     | 299/661 [04:34<05:59,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 pjūvio kraštas, ekstra.   2 ėminio aprašas: 2 pjūvio kraštas, ekstra.  3. sarginiai l/m, ekstra  4. sektorius, planinis.. 4. Krūties sektorius 12x6x4 cm su oda 7x3,5 cm. Krūties audinyje pilkšvas, apvalios formos, aiškių ribų navikas 1,9x1,8x1,8 cm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2 cm.   Odoje ruda dėmė 0,2x0,2 cm, nuo odos rezekcijos krašto nutolusi 1,5 cm ir pilkšvas, smulkiai gruoblėtas darinys 0,5x0,4x0,1 cm, nuo dėmės nutolęs 2 cm, nuo odos rezekcijos krašto - 1 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/2 l/m, 4,75 mm, ekstranodalinis plitimas).   4. Krūties invazyvi blogai diferencijuota (G3; 8 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 19 mm), pN1a(sn)(1/2 l/m, 4,75 mm metastazė), LVI0(neidnetifikuota). Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS).  Estrogenų receptoriai: reakcijos nėra. HER2:reakcijos nėra (0). Ki67: proliferacinis indeksas 30%. Karštame taške 40%. Progesterono receptoriai: reakcijos nėra.  Androgenų receptoriai: reakcijos nėra.   Seborėjinė keratozė. Hemangioma (vyšninė angioma).. 1. Krūties audinyje židininė fibrozė su negausiais dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.   2. Krūties audinyje židininė fibrozė su negausiais dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.   3. Viename limfmazgyje iš dviejų (1/2 l/m) žemiau aprašyto naviko metastazė iki 4,75 mm su ekstranodaliniu plitimu.  4. Krūties audinyje, hialinizuotoje stromoje - navikas (19 mm makroskopškai) infiltratyviu augimo frontu su plačia centrine nekrozės zona. Navikas suformuotas smulkių lizdinių, trabekulinių ir negausių tubulinių (apie 10%) naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su ryškiai polimorfiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 46/10DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Navikas nuo artimiausio rezekcijos krašto nutolęs per3 mm. Greta naviko negausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais; dalies proliferatų centruose - nekrozės zonos.   Odoje darinys suformuotas besiliejančių epidermio hiperplazijos plotų, su epidermio hiperkeratoze, papilomatoze su pavienių raginių cistų formacija.   Odoje egzofitinis darinys, klotas epidermiu, sufomruotas plonasienių varijuojančio dydžio kraujagyslių, klotų vienu sluoksniu endotelio ląstelių. Kraujagyslių spindžiuose eritrocitai.. Blokas 19:  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 30% naviko ląstelių. Karštame taške 40%.  Progesterono receptoriai: reakcijos naviko ląstelių
answer:  0

 45%|████▌     | 300/661 [04:35<05:44,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sektoriaus kraštai - extra;  2. Sektoriaus kraštai - extra;  3. Sarginiai l/m - extra.  4. N4. Deš. krūties sektorius su naviku.. 4. Krūties sektorius 9,5x8x3,5 cm su odos lopu 7,5x3 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 1,6x1,5x1,3 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,7 cm, nuo odos – 4,5 cm. Šalia naviko fibrozės zona 4x3x3 cm.. 1. Sektoriaus kraštai - krūties audinys be patologinių pokyčių.  2. Sektoriaus kraštai - krūties audinys be patologinių pokyčių.  3. Sarginiai l/m: karcinomos mikrometastazė 1-me/2 limfmazgyje; pN1mi.    4. Dešinės krūties sektorius su naviku.   Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;   pT1c pN1mi pR0.  Imunotipas (priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 40%.. 1. Sektoriaus kraštai - krūties audinys be patologinių pokyčių.  2. Sektoriaus kraštai - krūties audinys be patologinių pokyčių.  3. Sarginiai l/m: 1-me limfmazgyje iš 2 - nežymiai atipinių epitelinių ląstelių 1,5 mm židinys.  4. Dešinės krūties sektorius su naviku. Krūties audinį infiltruoja naviko negausios duktalinės struktūros, netaisyklingi kribroziniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.. nan
answer:  0

 46%|████▌     | 301/661 [04:36<05:24,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 16 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma (su mucininės diferencijacijos požymiais).  ---  Estrogenų receptoriai: stiprus(+++) branduolinis/membraninis dažymasis 100% .   Progesterono receptoriai: vidutinis(++) branduolinis dažymasis 60% .   Her2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 10%.. Trabekulines, negausias smulkias solidines naviko struktūras formuoja ląstelės su negausia tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; ekstraląstelinių mucinų židiniai navike; mitozių navike iki 4 / 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus(+++) branduolinis/membraninis dažymasis 100% .   Progesterono receptoriai: vidutinis(++) branduolinis dažymasis 60% .   HER2: nusidažiusių naviko ląstelių nėra.  Ki67: 10% .   E-Cadherin: membraninis dažymasis 100%
answer:  1

 46%|████▌     | 302/661 [04:37<05:11,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais ~8 mm dydžio darinys kairiojoje krūtyje ties ~6 val. vidurinėje dalyje, paimti 2 biopsiniai stulpeliai histologijai.. 2 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 9 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 10%.
answer:  0

 46%|████▌     | 303/661 [04:38<05:03,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Pašalinta dešinė krūtis su m.pectoralis - planinis tyrimas.. Krūtis 120 gramų svorio, 12,5x6,5x2,5 cm su raumens fragmentu 6x3,8x1,2 cm. Krūties odoje, šalia spenelio išopėjimas 4,5x3 cm. išopėjimo projekcijoje, krūties audinyje - balkšvas, standus navikas 5,3x4,8x2,4 mm, nuo artimiausio rezekcijos krašto nutolęs <0,1 cm, peraugą odą. Raumens fragmente, pjūvyje balkšvas standus mazgas 4,9x3,5x1,1 cm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b(m) (53mm ir 49mm, išopėjimas).. Krūties audinyje 53mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 8/10 DPRL. Epidermyje virš naviko smulkūs išopėjimai. Tokios pačios struktūros 49mm navikas skersaruožių raumenų fragmente.  Navikas plačiai plinta giliajame skersaruožių raumenų ir krūties audinio rezekcijos krašte.. nan
answer:  0

 46%|████▌     | 304/661 [04:38<04:55,  1.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 11 mm; II - 6 mm; III - 5 mm.. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) karcinoma su tarpiniais lobulinės - duktalinės karcinomos požymiais.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai:  neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 1%.. Bioptatuose (3/3) - fibrozinėje stromoje ir riebaliniame audinyje infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, grandinėlėmis ir pabirai besidėstančių ląstelių negausia eozinofiliška citoplazma, nežymiai polimorfiškais, vidutinio kalibro, ovalaus kontūro branduoliais; mitozių 0/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: neigiama reakcija.  HER2: nusidažiusių naviko ląstelių nėra.  Ki67 proliferacinis aktyvumas 1%.  E-cadherin(+++) membr. r-ja 100%
answer:  0

 46%|████▌     | 305/661 [04:39<05:06,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai  - skubus tyrimas be naviko  2(N2b) kraštai  - skubus tyrimas be naviko  3(N3) kairės pažasties sarginis limfmazgis - skubus tyrimas 2 l/m be naviko  4(N1): pašalintas kairės krūties kvadrantas  - planinis tyrimas. 4. Krūties sektorius 10,5x7x4 cm su odos lopu 9x2 cm. Pjūvyje pilkšvas, standus, neaiškių ribų navikas 25x16x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1,6 cm.. 1(Extra). Krūties audinys.  2(Extra). Riebalinis audinys.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(21 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).. 1(2a)(Extra). Krūties audinyje - pavieniai smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2(2b)(Extra). Brandus riebalinis audinys su neryškia fibroze.  3(Extra). 2 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 21 mm), suformuotas fibrozuotoje stromoje plintančių lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 9/10 DPRL. Šalia yra dilatuotų kanaliukų su solidiniais, kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais, fokaliai su negausiomis komedo nekrozėmis.. 1. Navikas (12 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 60% naviko ląstelių.
answer:  1

 46%|████▋     | 306/661 [04:40<04:57,  1.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 10 mm ilgio.. PAPILDYTA  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: ribinė (2+).  Ki67: 5%.  ---  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).. Smulkias solidines, trabekulines naviko struktūras formuoja gan smulkios ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 3 / 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas visos membranos nusidažymas 20% naviko ląstelių.  Prolifer
answer:  5

 46%|████▋     | 307/661 [04:41<05:00,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais ~8x10 mm dydžio darinys kairiojoje krūtyje ties 1 val. vidurinėje dalyje, paimti du biopsiniai stulpeliai histologijai (I buteliukas).   2. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais ~13x21 mm dydžio navikas kairiojoje krūtyje ties 12 val. vidurinėje dalyje, paimti du biopsiniai stulpeliai histologijai (II buteliukas).. 1. 2 biopsiniai stulpeliai: I - 7 mm; II - 8 mm.  2. 2 biopsiniai stulpeliai: I - 16 mm; II - 12 mm.. 1. Vidutiniškai diferencijuota (G2,6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  2. Vidutiniškai diferencijuota (G2,6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 98% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 7%.. 1. Krūties audinį infiltruoja grandinėlės, trabekulės, smulkūs lizdai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.  2. Krūties audinį infiltruoja grandinėlės, trabekulės, smulkūs lizdai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Blokas 1:  E-Cadherin: neigiama reakcija naviko ląstelėse.  Estrogenų receptoriai: stipri (+++) reakcija, 98% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkulia
answer:  20

 47%|████▋     | 308/661 [04:42<04:55,  1.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Invazinė duktalinė karcinoma (su apokrinine ER-/AR+ diferenciacija ir onkocitiniu MITO+ imunofenotipu; M8401/3)    (mažiausiai iki 8,5 mm);   (G2; 7 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcijos nėra (0). HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 5%. Karštame taške 10%.. Krūties audinį 1-me bioptate infiltruoja iki 8,5 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su neryškiai ryškiai polimorfiškais branduoliais (AR+) gausioje eozinofilinėje citoplazmoje (su gausiomis MITO+ mitochondrijomis);   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Androgenų receptoriai: stipri  teigiama (+++) branduolių reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių membranoje nėra (stipri reakcija citoplazmoje
answer:  0

 47%|████▋     | 309/661 [04:43<04:49,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: kairė krūtis, planinis. Krūtis, 626 g svorio, 20x20x7 cm. Krūties audinys difuziškai nežymiai fibrozuotas. Patologinių židinių nerasta.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (8mm navikas).  Estrogenų receptoriai: stiprus ir vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymom nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinyje 8mm navikas: smulkios duktalinės struktūros, smulkūs solidiniai kompleksai ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  Rezekcijos kraštas be naviko.. Navikas  Estrogenų receptoriai: stiprus ir vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymom nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.
answer:  0

 47%|████▋     | 310/661 [04:43<04:48,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas kairės krūties darinys, paimti 3 biopsiniai stulpeliai medžiagos histologiniam ištyrimui.. 3 biopsiniai stulpeliai: I - 18 mm; II - 12 mm; III - 16 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: silpna (+) reakcija, 3% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%. Karštame taške 70%.. Krūties audinį 3-se bioptatuose infiltruoja iki 12 mm :   - pavienės duktalinės struktūros ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 7/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 30% naviko ląstelių. Karštame taške 70%.  Progesterono receptoriai: silpna (+) reakcija, 3% na
answer:  0

 47%|████▋     | 311/661 [04:44<05:11,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sarginiai limfmazgiai, ekstra.   2. Kairė krūtis, planinis.. 2. Krūtis 604 gramų svorio, 20x17x4,5 cm. Krūties audinyje, viršutiniame lateraliniame kvadrante 3 neaiškių ribų balkšvi navikai:  - I 2,5x1x1 cm, nuo odos nutolęs 4,5 cm, nuo artimiausio rezekcijos krašto - 0,4 cm.  - II 2,2x0,6x cm, nuo odos nutolęs 3,5 cm, nuo artimiausio rezekcijos krašto - 2,5 cm.  - III 1,5x1x1 cm, nuo I naviko nutolęs 5,5 cm, nuo II naviko - 4,5 cm, nuo odos - 2,5 cm, nuo artimiausio rezekcijos krašto - 0,3 cm.  Apatiniame lateraliniame kvadrante neaiškių ribų židinys 2x1,5x1 cm, nuo I naviko nutolęs 2,5 cm, nuo artimiausio rezekcijos krašto - 1,5 cm, nuo odos - 4,5 cm.. 1(Extra). Krūties lobulinės karcinomos metastazės 2/3 l/m (10 mm ir 4 mm).  2. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT(m)1c(2 naviko židiniai: 11 mm ir 11 mm) pN(sn)1a(mts 2/3 l/m: 10 mm ir 4 mm), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).  Lobulinė karcinoma in situ (LCIS).. 1(Extra). 3 limfmazgiai su antriniais limfoidiniais folikulais ir sinusų histiocitoze. Dviejuose limfmazgiuose - žemiau aprašyto naviko metastazės (10 mm ir 4 mm).   2. SPENELIS: normali histologinė struktūra; fokaliai stambūs latakai užpildyti monomorfiškomis ląstelėmis apvaliais, su smulkia nukleole branduoliais (LCIS); dilatuoti latakai žemiau.   NAVIKAS: krūties audinyje - 2 analogiškos struktūros navikai (mikroskopiškai 11 mm ir 11 mm), suformuoti fibrozuotoje stromoje infiltratyviai plintančių trabekulinių struktūrų, grandinėlėmis, smulkiomis grupelėmis ar pabirai besidėstančių ląstelių negausia švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais/apvaliais, kiek polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 3/10 DPRL. Aplink naviko židinius gausiai dėstosi kanaliukai, užpildyti monomorfiškomis, analogiškomis navikui ląstelėmis (LCIS). Limfovaskulinė invazija. Rezekcijos kraštai - be naviko plitimo.  Aplinkiniame krūties audinyje, fibrozuotoje stromoje dilatuoti latakai, kloti suplokštėjusiu epiteliu.. 2. Navikas (II) (16 blokas): E-cadherin (-).
answer:  1

 47%|████▋     | 312/661 [04:45<05:01,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja negausios smulkios duktalinės struktūros, siauros šakotos juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 47%|████▋     | 313/661 [04:46<04:54,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Kairės krūties areolės srities punch bioptatas. Odos bioptatas 0,5x0,4x0,6 cm, rusvu, gruoblėtu paviršiumi.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Odą ir poodinį riebalinį audinį infiltruoja smulkios duktalinės struktūros, nedideli netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 60% naviko ląsteli
answer:  0

 48%|████▊     | 314/661 [04:47<04:52,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. deš krūtis, planinis.   2. sarginiai l/m, planinis.. 1. Krūtis 356 gramų svorio, 17x14x5 cm. Krūties audinyje, viršutinių kvadrantų riboje balkšvas, standus, neaiškių ribų navikas 25x18x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1,6 cm. Apatiniame lateraliniame kvadrante balkšvas, standus, aiškių ribų darinys 7x6x5 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 2,7 cm, nuo naviko - 3 cm.    2. Riebalinio audinio fragmentai, bendras dydis 4x2,3x0,6 cm. Rasti 3 limfmazgiai, didžiausias 1,3 cm.. N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2(25mm).  Aukšto laipsnio indtraduktalinė karcinoma (DCIS, komedo tipas; 7mm židinys).  N3: Limfmazgiai (3 l/m) be naviko metastazių; pN0(sn).. Krūties audinyje 25mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.  Kitas 7mm navikinis židinys sudarytas iš dilatuotuose kanaliukuose plintančių ryškiai polimorfiškų ląstelių su centrinėmis nekrozėmis.  Operacinis pjūvis be naviko.  N3: Limfmazgiai (3 l/m) su reaktyviais pokyčiais, be naviko metastazių.. nan
answer:  0

 48%|████▊     | 315/661 [04:48<05:18,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- užspenelinis audinys, skubu  2. deš. pažasties sarginiai limfmazgiai, skubu  3. deš. krūties audinys, planinis. 3. Krūties audinys 358 gramų svorio, 17x16x3,5 cm su odos lopu 8x2 cm. Krūties audinyje:  - I fibrozės zona su dilatuotais latakais 5x4x2 cm, siekia priekinį ir gilųjį rezekcijos kraštą. Zonoje pilkšvas, standus, neaiškių ribų navikas 1,4x1,2x1 cm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo priekinio – 0,3 cm.  - medialiau - II fibrozės zona 1,5x1,3x1 cm, siekianti priekinį rezekcijos kraštą, nuo giliojo rezekcijos krašto nutolusi 0,8 cm, nuo I zonos - 1,2 cm.  - III fibrozės zona 1,5x1x0,8 cm, nuo priekinio rezekcijos krašto nutolusi 1,5 cm, nuo giliojo rezekcijos krašto - 0,3 cm, nuo II zonos - 1,5 cm.  Priekinis rezekcijos kraštas dažytas juoda spalva, gilusis - žalia.. PAPILDYTA (HER2 FISH TYRIMAS):  1(Extra). Krūties audinys.  2(Extra). Reaktyvi limfadenopatija (3 l/m).  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT(m)1c(2 naviko židiniai: 12 mm ir 3 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Imunofenotipas:   HER2 imuninė reakcija: ribinė (2+).  HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).  Krūties lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS) ir kolageninė sferuliozė.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu; grupė kanaliukų su apokrinine metaplazija.  2(Extra). 3 limfmazgiai su fokaline parakortekso hiperplazija, sinusų histiocitoze ir lipomatoze.  3. Krūties audinyje - 2 analogiškos struktūros navikai (mikroskopiškai 12 mm ir 3 mm), suformuoti fibrozuotoje stromoje infiltratyviai plintančių trabekulinių struktūrų, grandinėlėmis, smulkiomis grupelėmis ar pabirai besidėstančiomis ląstelėmis negausia švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais/apvaliais, kiek polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 4/10 DPRL.   Aplink gausūs dilatuoti kanaliukai, užpildyti analogiškomis navikui ląstelėmis, grupės kanaliukų, klotų hiperplastišku epiteliu ar su stulpiniu ląstelių pokyčiu su apikalinės sekrecijos požymiais bei kanaliukai su kolagenine sferulioze, yra dilatuotų kanaliukų, klotų suplokštėjusiu epiteliu su makrofagais spindžiuose, grupės kanaliukų su apokrinine metaplazija; pavieniai smulkūs kalcifikatai.. 1. Navikas (10 blokas):  HER2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 80% naviko ląstelių.
answer:  1

 48%|████▊     | 316/661 [04:49<05:21,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštas - extra  2. pjūvio kraštas - extra.   3. sektorius, planinis.  4. Papildomas kraštas, planinis.. 3. Krūties sektorius 11,5x8x3,5 cm su odos lopu 6x1 cm, žymėtas viela. Vielos projekcijoje, pjūvyje pilkšvas, neaiškių ribų, standus darinys 25x16x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm.    4. Riebalinio audinio fragmentas 1,3x1x0,2 cm. v/m. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 10,5 mm), LVI0 (neidentifikuota). Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių. HER2: reakcija teigiama (3+); Ki67: proliferacinis indeksas 10%. Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių. Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS).. 1. Fibrozuotame krūties audinyje gausios sklerozuotos lobulės ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  2. Fibrozuotame krūties audinyje gausios sklerozuotos lobulės ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  3. Krūties audinyje - navikas (10,5 mm mikroskopiškai), suformuotas trabekulinių, smulkių lizdinių bei negausių tubulinių struktūrų iš vidutinio gausumo eozinofiline citoplazma ląstelių, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiais branduolėliais; mitozių 10/10 DPRL. Limfovaskulinis plitimas neidentifikuotas (LVI0). Greta naviko daugybiniai dilatuoti latakai, užpildytų solidinių bei kribriforminių proliferatų, suformuotų analogiškų navikui ląstelių. Dalyje pakitusių dilatuotų latakų - centrinės komedonekrozės.. Blokas 12:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: stipri (+++) cirkuliari reakcija, 95% naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono receptoriai: stipri (+
answer:  95

 48%|████▊     | 317/661 [04:50<05:10,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1): pašalintas dešinės krūties kvadrantas - planinis tyrimas  2(N2a): kraštai  3(N2b): kraštai  4(N3): dešinės pažasties sarginiai limfmazgis - planinis tyrimas, bei keli kietoki įtartini limfmazgiai iš II pažasties lygio  5(N4): papildomas kraštas. 1. Krūties sektorius 16,5x3,5x6 cm su oda 14x1,7 cm. Krūties audinyje, pilkšvas, standus, aiškių ribų navikas 28x20x18 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,3 cm.  2. Riebalinio audinio fragmentas 2,2x1,8x0,4 cm. v/m  3. Riebalinio audinio fragmentas 4x2,2x0,6 cm. v/m  4. Riebalinio audinio fragmentas 4,5x4x1,3 cm. Rasti 9 limfmazgiai iki 2,6 cm.  5. Riebalinio audinio fragmentas 2x1,5x0,3 cm. v/m. N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2(28mm).  N2ab ir N4: Krūties audinys be naviko.  N3: Limfmazgiai (9 l/m) be naviko židinių; pN0.. N1: Krūties audinyje 28mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.  N2ab ir N4: Krūties audinys be naviko.  N3: Limfmazgiai (9 l/m) su reaktyviais pokyčiais, be naviko židinių.. nan
answer:  0

 48%|████▊     | 318/661 [04:51<05:40,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2) - sarginiai limfmazgiai, skubu  4(3) - deš.krūties kvadrantas, planinis. 4(3). Poodinis krūties sektorius 6,5x5,5x5 cm. Krūties audinyje - pilkšvas standus, aiškių ribų navikas 22x18x18 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm.. 1(1a, ekstra). "Viršutinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); kalcifikatai; be naviko.   2(1b, ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija); be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": karcinomos (mikro)metastazė 1 limfmazgyje (mts 1/4 l/m; 1,45 mm skersmens).     4(3). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT2 (navikas 22 mm) N1mi(sn) (mts 1/4 l/m; 1,45 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar hiperplastišku epiteliu, pavieniai kalcifikatai; arterijų sienelėse fibrozės židiniai su kalcifikatais (arteriosklerozės požymiai); be naviko.   2(1b, ekstra). "Apatinis kraštas": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS); be naviko.   3(2, ekstra). "Sarginiai limfmazgiai"(4): gilesniuose planinio tyrimo pjūviuose, vieno (1) limfmazgio kapsulėje - 1,45 mm skersmens subtotaliai koaguliuotas epitelinių (PanCK+) ląstelių židinys (labiausiai tikėtina - naviko struktūros).   4(3). NAVIKAS: krūties audinyje, fibrozuotoje, ryškiau kolagenizuotoje desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios netaisyklingos negausios duktalinės, kribriforminės ir dominuojančios lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; pavienės mitozės (mitozių ~1/10 DPRL). Limfovaskulinė naviko invazija smulkiose šakose.    APLINKA: tarp naviko struktūrų - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   SEKTORIAUS REZEKCIJOS KRAŠTAS: naviko struktūros nutolusios 1,7 mm.. 3(2, ekstra). "Sarginiai limfmazgiai":   "Koaguliuotas židinys"(6 blokas):  PANCK(+); CK7/CK20/S100(-).   4(3). Navikas (20 blokas):  HER2: silpna (+) necirkuliari reakcija, 1% naviko ląstelių membranoje.
answer:  0

 48%|████▊     | 319/661 [04:52<05:17,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 11 mm; III - 13 mm.. Po operacinės medžiagos tyrimo patikslintas naviko tipas  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Krūties audinį infiltruoja smulkios duktalinės struktūros ir solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 5
answer:  0

 48%|████▊     | 320/661 [04:53<05:14,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 2 biopsiniai stulpeliai iš kairės pažasties I lygio l/m  2 but. 2 biopsiniai stulpeliai iš kairės krūties  BI-RADS 4a darinio (satelitas?) apatiniame lateraliniame kv-te   3 but. 2 biopsiniai stulpeliai iš dominuojančių pakitimų BI-RADS 5 lateralinių kvadrantų ribgoje. 1. 2 biopsiniai stulpeliai: I - 8 mm; II - 6 mm.  2. 2 biopsiniai stulpeliai: I - 4 mm; II - 3 mm.  3. 2 biopsiniai stulpeliai: I - 7 mm; II - 13 mm.. 1. Limfmazgio bioptatai be patologinių pokyčių.  2. Krūties fibrocistiniai pokyčiai: sklerozuojanti adenozė.  3. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.. 2. Fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai smulkių kanaliukų proliferacijos zonos.  3. Krūties audinį 2-se bioptatuose infiltruoja iki 12 mm :   - trabekulės;  -  vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  gausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki /110 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 4:  Androgenų receptoriai: vidutinė ir stipri teigiama (++/+++) branduolių reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  navik
answer:  l

 49%|████▊     | 321/661 [04:53<04:57,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas:  1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) mikropapilinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: teigiama (3+).  Ki67 proliferacinis aktyvumas 10%.. Bioptate, fibrozinėje stromoje infiltratyvios naviko struktūros, suformuotos mikropapilomis ir lizdais besidėstančių ląstelių gausia ryškia eozinofiliška citoplazma, polimorfiškais, vidutinio-stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 5/10 DPRL.. Navikas:  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  HER2: stiprus visos membranos nusidažymas 100% naviko ląstelių.  Ki67 proliferacinis aktyvumas 10%.
answer:  0

 49%|████▊     | 322/661 [04:54<05:07,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 12x4,5x6 cm su oda 10,5x3 cm. Krūties audinyje, pilkšvas, standus, neaiškių ribų navikas 16x16x8 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2 cm.. 1(ekstra). Krūties audinio fibrozė.    2(ekstra). Krūties fibrocistiniai pokyčiai: įprastinė duktalinė hiperplazija, apokrininė metaplazija.    3(ekstra). Duktalinės karcinomos metastazė 1/5 limfmazgių (7 mm dydžio).     4. Krūties invazyvi gerai diferencijuota (G1, 4 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT1c (16 mm navikas)    pN1a(sn)(1/5 l/m su mts 7mm)    pLVI-0 (limfovaskulinė invazija neidentifikuota)   pR0(radikalus pašalinimas).   Naviko imunotipas nustatytas priešoperacinėje biopsijoje (nr. B23-5702):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.    Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija.. 1(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis, kompaktiškomis lobulėmis ir smulkiais kanaliukais, klotais dvisluoksniu ar hiperplastišku, papilines ir kribriformines struktūras formuojančiu epiteliu su židinine apokrinine metaplazija.  3(ekstra). 1/5 limfmazgių - žemiau aprašyto naviko metastazė 7 mm su ekstranodaliniu plitimu.      4. Krūties audinyje - desmoplastiškoje stromoje plintantis navikas, suformuotas:   tubulių (80%), kribriforminių ir trabekulinių struktūrų;    naviko ląstelės su negausia eozinofiliška citoplazma,  vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis;   mitozių navike iki 4/10DPRL.   Navike yra mikrokalcifikatų.   Dalyje kanaliukų cistinė dilatacija, paprastoji intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. nan
answer:  0

 49%|████▉     | 323/661 [04:55<04:56,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas d. krūties BIRADS-5 darinys, paimti 3 biopsiniai stulpeliai medžiagos histologiniam ištyrimui. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 13 mm; III - 9 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma su daline mucinine diferenciacija.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 3%.. Fragmentuotuose bioptatuose (3/3) - fibrozinėje stromoje ir ekstraląsteliniuose mucinuose infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių vidutinio gausumo ryškia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 2/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67 proliferacinis aktyvumas 3%.
answer:  0

 49%|████▉     | 324/661 [04:56<04:46,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Paimti 3 biopsiniai stulpeliai.. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 11 mm; III - 10 mm.. Krūties mucininė karcinoma; (G1, 5 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinyje mucininėje stromoje netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 10
answer:  0

 49%|████▉     | 325/661 [04:57<05:10,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštai - extra - be naviko  2(N2b) - kraštai - extra - be naviko   3(N1) - sektorius - planinis tyrimas. 3(1). Fibrozuoto audinio fragmentas 4x2,7x0,7 cm, paviršiuje žymėtas viela. Viela žymėtoje vietoje - balkšvas, standus židinys 0,3x0,2x0,3 cm, židinys siekia artimiausią rezekcijos kraštą. Sudėta visa medžiaga.. 1(2a, ekstra). "Kraštai": normalios histologinės struktūros riebalinis audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.     3(1). Krūties invazyvi bent gerai diferencijuota (G1, bent 5 balai pagal Nottingham, žr. pastabą) duktalinė karcinoma,   SUMINIS TNM:   pT1a (navikas 1,35 mm), LVI-0 (limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.    Krūties žemo-aukšto laipsnio duktalinė karcinoma in situ (DIN1-3/DCIS: solidinis, kribriforminis, papilinis ir komedo tipai). Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, sklerozuojanti adenozė).   DCIS komponentas nuo sektoriaus rezekcijos krašto nutolęs - 0,35 mm.. 1(2a, ekstra). "Kraštai": brandžių lipocitų suformuotas vaskuliarizuotas fragmentas; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(1). NAVIKAS (šalia in situ komponento - 1,35 mm skersmens invazyvus židinys): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios suspaustos duktalinės, trabekulinės ir nedidelės lizdinės naviko struktūros, suformuotos saikingai polimorfiškų ląstelių, negausia šviesia eozinofiline citoplazma, vidutinio dydžio nelygaus kontūro ovaliais/apvaliais branduoliais su kai kur išryškėjusiomis smulkiomis nukleolėmis; mitozių tirtuose naviko pjūviuose nevizualizuota, maksimalus naviko plotas 4 DPRL.   APLINKA: šalia naviko - solidiniai, kribriforminiai, papiliniai intraduktaliniai naviko ląstelių proliferatai su  keliomis centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: in situ komponentas nutolęs 0,35 mm.. 3(1). Navikas (blokas 5):  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.   HER2: silpna (+) necirkuliari reakcija, 3% naviko ląstelių
answer:  1

 49%|████▉     | 326/661 [04:58<05:00,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 13 mm; II - 11 mm.. Krūties invazyvi žemo laipsnio adenoidinė cistinė karcinoma, tubulinis-trabekulinis tipas   (taikant Nottingham gradavimą, karcinoma atitinka gerai diferencijuotą; G1, 5b.).   Imunofenotipas:  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: silpna (+) reakcija, 30% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 5%.. Bioptatų (2/2) fibrozinėje stromoje gausios infiltratyvios naviko struktūros (plinta mažiausiai 10 mm), suformuotos trabekulėmis, tubulėmis ir kribriforminėmis struktūromis, su reguliariais spindžiais besidėstančių duktalinio tipo ląstelių  negausia eozinofiliška tamsia citoplazma ir bazaloidinių ląstelių nežymiai polimorfiškais branduoliais; mitozių 2/10 DPRL.. Blokas 1:  CD117: silpna teigiama (+)  membraninė reakcija pavienėse atipinėse ląstelėse  CK14: stipri teigiama (+++) membraninė reakcija 100 proc. epitelio ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos n
answer:  0

 49%|████▉     | 327/661 [04:59<04:46,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+
answer:  2

 50%|████▉     | 328/661 [05:00<04:56,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. (1a)- viršutinis kraštas, skubu  2. (1b)- apatinis kraštas, skubu  3. (2) Deš. pažasties sarginiai limfmazgiai, skubu  4. (3) deš. krūties sektorius, planinis.. 4. Krūties sektorius 7,5x6x2 cm, be odos, žymėtas viela. Vielos projekcijoje krūties audinys fibrozuotas 3,5x1,8 cm plote, nuo giliojo rezekcijos krašto nutolęs 0,2 cm. Krūties audinyje standus, neaiškių ribų navikas 22x16x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm.. 1.(1a) Riebalinis audinys.  2.(1b) Fibrocistiniai krūties pokyčiai.  3.(2) Reaktyvi limfadenopatija (2 l/m).  4.(3) Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(m)(dauginiai naviko židiniai nuo 0,6mm iki 22mm) pN0(sn)(0/2 l/m).   IHC reakcijos atliktos VPC:B23-30662 tyrime:  "Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0)."  Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis tipas; -komedo tipo nekrozės).. 1.(1a) Riebalinis audinys su fibrovaskulinėmis septomis.  2.(1b) Riebalinis audinys su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu.  3.(2) Du(2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4.(3) Krūties audinyje - dauginiai naviko židiniai (nuo 0,6mm iki 22mm), formuojami trabekulinių, solidinių/lizdinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais, hiperchromiškais branduoliais su fokaliai išryškėjusiomis nukleolėmis; navike iki 20 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozių židiniais (DCIS).. Navikas:  E-Cadherin(+++), membr. r-ja, 100%;   P120(+++), membr. r-ja, 100%.
answer:  0

 50%|████▉     | 329/661 [05:00<04:43,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Infiltracinė multižidininė krūties NST karcinoma, pT(m)2 (2,2x2,1cm ir 0,7x0x7cm) N0 (2 limfmazgiai be metastazių; sentinelinio limfmazgio statusas neįvertintas) LVI1 R0 G3 (8 balai pagal Nottingham). Abiejų navikinių mazgų IH profilis vienodas: ER/PR 0/8 balų pagal Allred. HER2 imuninė reakcija ribinė (2+).. Konsultacijai gauta:  - 1 parafino blokas (žymėtas "23/00684");  - 1 histologinis preparatas (žymėtas ""23/00684"", dažytas HER2 metodu).. Krūties invazyvi duktalinė adenokarcinoma (ne mažiau kaip vidutiniškai diferencijuota / G2 / 7 balai pagal Nottingham).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).. Krūties audiyje - navikas: kribrozines (dominuoja), pavienes solidines naviko struktūras formuoja ląstelės su vidutinio gausumo ųvelniai eozinofiline citoplazma, vidutinio kalibro ar stambesniais, apvalios formos, kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike ne mažiau 3 / 10 DPRL.. nan
answer:  0

 50%|████▉     | 330/661 [05:01<04:33,  1.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 17 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.. Krūties audinį infiltruoja duktalinės struktūros ir negausūs nedideli netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 1-2% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 20% n
answer:  0

 50%|█████     | 331/661 [05:02<04:27,  1.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 11 mm; II - 9 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus ir vidutinis branduolių nusidažymas 40% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja negausios duktalinės struktūros, smulkūs solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus ir vidutinis branduolių nusidažymas 40% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% n
answer:  0

 50%|█████     | 332/661 [05:03<04:57,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2) - kairės pažasties sarginis limfmazgis  - skubus tyrimas 2 l/m be naviko.  2(1) - pašalinta kairė krūtis - planinis tyrimas. 2(1). Krūtis 683 gramų svorio, 20x16,5x5 cm. Krūties spenelyje balkšvas plotas 0,9x0,5 cm, odoje rusva dėmė 0,4x0,3 cm, nuo odos rezekcijos krašto nutolusi 2,8 cm. Krūties lateralinė dalis gauta markiruota metileno mėliu. Krūties audinyje, pilkšva, standi, netolygių kraštų su taškinėmis nekrozės zonomis fibrozės zona 6,5x4,5x3,5 cm, nuo giliojo rezekcijos (dažytas mėlynu tušu) krašto nutolusi 0,8 cm, nuo odos - 1 cm. Histologiniam ištyrimui sudėtas kas antras fibrozės pjūvis, pradedant nuo metileno mėliu markiruotos dalies. Rastas intramamarinis limfmazgis 0,5 cm.. PAPILDYTA  1(2). Reaktyvi limfadenopatija (2 l/m), lipomatozė.  2(1). A) Krūties invazyvi karcinoma (galimai mikropapilinė, ne mažiau kaip vidutiniškai diferencijuota / G2 / 7 balai pagal Nottingham).  Naviko kategorizacija pagal TNM (Nr.1-Nr.2): pT1a(1,5 mm navikas) N0(sn) (0/2 l/m + 0/1 intramamarinis l/m). LVI0(limfovaskulinės invazijos nėra). R0(radikalus naviko pašalinimas).  B) Krūties aukšto laipsnio intraduktalinė karcinoma (DCIS/DIN3; mikropapilinis, kribriforminis, plokščias tipai; iki 6 cm skersmens zona).  C) Krūties fibrocistiniai pokyčiai.  D) Krūties odos arterioveninė hemangioma.  ---  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2 imunohistocheminė reakcija: teigiama (3+).  Ki67: ~10%.. 1(2). Du (2) limfmazgiai su sinusų histiocitoze, lipomatoze.  2(1). KRŪTIES SPENELIS: daugiasluoksnis plokščias epitelis fokaliai akantotiškas, su besiliejančiais akantotiniais pluoštais.  KRŪTIS: Krūties audinyje (šalia spenelio ir atokiau: A) gausūs "DCIS kanaliukai" (stambūs ir smulkesni latakai, iškloti "plokščiu", mikropapilines ar kribrozines struktūras formuojančiu epiteliu, suformuotu ląstelių su gausoka tamsia eozinofiliška citoplazma, vidutinio ar stambaus kalibro, ovoidiškais netolygaus kontūro/polimorfiškais branduoliais smulkiai grūdėtu chromatinu ir stambiomis nukleolėmis, B) 1,5 mm invazyvios karcinomos židinys (smulkios solidinės ar mikropapilinės analogiškų aukščiau aprašytoms ląstelių formuojamos struktūros; mitozių invazyviame navike neidentifikuota (3 didelio padidinimo regos laukuose). Nenavikiniame krūties audinyje - fibrozė, su įvairaus kalibro kanaliukais.  Vienas (1) intramamarinis limfmazgis su sinusų histiocitoze, pavieniais pigmenuotais makrofagais parakortekse, lipomatoze.  KRŪTIES ODOS DARINYS: Papilinėje dermoje - smulkus darinys iš smulkių, nereguliarių kraujagyslių, dalis hialinizuota sienele, su negausiais eritrocitais spindyje.. Blokas 34: CK14+ mioepitelis DCIS struktūrose.   Blokas 36: CK14+ mioepitelis DCIS struktūrose; invazyviame navike mioepitelinio išklojimo nėra.  Estrogenų receptoriai: reakcijos invazyvaus naviko ir DCIS ląstelių branduoliuose nėra.  Progesterono recepto
answer:  0

 50%|█████     | 333/661 [05:04<05:40,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - deš. pažasties sarginiai l/m-extra  2 - k. pažasties sarginiai l/m- ekstra  3 - deš. krūtis  4 - k.krūtis 3-4 planniam tyrimui. 3. Krūtis 1055 gramų svorio, 24x18x5 cm. Krūties audinyje, apatinių kvadrantų riboje - balkšvas, standus, neaiškių ribų navikas 15x14x11 mm, nuo odos nutolęs 4,5 cm, nuo giliojo rezekcijos krašto - 0,3 cm. Šalia naviko fibrozės zona su dilatuotais latakais 4x3x1,5 cm, siekia odą, nuo giliojo rezekcijos krašto nutolęs 1,5 cm. Odoje rusvas smulkiai gruoblėtas darinys 0,8x0,6x0,1 cm, nuo artimiausio rezekcijos krašto nutolęs 3 cm.  4. Krūtis 1400 gramų svorio, 27x23x6,5 cm. Krūties audinyje, išorinių kvadrantų riboje - balkšvas, standus neaiškių ribų navikas 6x6x5 mm (sudėtas visas), nuo odos nutolęs 2 cm, nuo giliojo rezekcijos krašto - 3 cm. Krūties audinys fibrozuotas. Odoje rusva dėmė 1x0,7 cm, nuo odos rezekcijos krašto nutolusi 2 cm ir rusvas smulkiai gruoblėtas darinys 0,5x0,4x0,1 cm, nuo odos rezekcijos krašto nutolęs 0,8 cm.. 1(Extra). Reaktyvi limfadenopatija (3 l/m).  2(Extra). Reaktyvi limfadenopatija (3 l/m).  3. Krūties (dešiniosios) invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(15 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).  Odos seborėjinė keratozė.  4. Krūties (kairiosios) invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(6 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: įprastinė duktalinė hiperplazija, fibroadenomatozinė hiperplazija.   Odos seborėjinė keratozė.. 1(Extra). 3 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  2(Extra). 3 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  3.  SPENELIS: normali histologinė struktūra; dilatuoti latakai žemiau.   NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai 15 mm), suformuotas fibrozuotoje stromoje plintančių fokaliai besiliejančių tubulinių, kribriforminių ir negausių trabekulinių bei lizdinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais/apvaliais, kiek polimorfiškais, dalis skeltais ar su smulkia nukleole branduoliais. Mitozių iki 3/10 DPRL.  KRŪTIS: aplinkiniame krūties audinyje yra dilatuotų kanaliukų su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais (DCIS) bei kanaliukų, užpildytų monomorfiškomis ląstelėmis (LCIS); grupės kanaliukų, klotų stulpiniu epiteliu su apikalinės sekrecijos požymiais ar epitelio hiperplazija, yra kanaliukų su apokrinine metaplazija bei dilatuotų kanaliukų, klotų suplokštėjusiu epiteliu.  ODA: darinys su epidermio papiliarizacija ir neryškia akantoze ir hiperkeratoze, bazinių ląstelių hiperplazija ir hiperpigmentacija bei smulkiomis keratininėmis cistomis.  4. SPENELIS: normali histologinė struktūra; dilatuoti latakai bei keli kanaliukai su epitelio hiperplazija žemiau.  NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai -- mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių struktūrų, grandinėlių ir smulkių grupių ląstelių negausia švelniai eozinofiliška citoplazma, smulkiais ir vidutinio kalibro, ovaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 4/10 DPRL.  Šalia yra kanaliukų, užpildytų analogiškomis navikui ląstelėmis ir fibroadenomatozinė hiperplazija.  ODA: darinys su epidermio papiliarizacija ir neryškia akantoze ir hiperkeratoze, bazinių ląstelių hiperplazija ir hiperpigmentacija bei smulkiomis keratininėmis cistomis.. nan
answer:  0

 51%|█████     | 334/661 [05:05<05:36,  1.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a- skubus - kraštai  2 N2b kraštai - skubus tyrimas - be naviko (DICS įtarimas Nr2a krašte)  3. N3: dešinės pažasties sarginis limfmazgis  - skubus tyrimas 4l/m be naviko  4. N1: pašalintas dešinės krūties kvadrantas - planinis tyrimas   5. N4: papildomas kraštas - planinis tyrimas. 4(N1). Krūties sektorius 8x4,5x6 cm su odos lopu 7,5x3 cm, žymėtas viela. Odoje pilkšvai melsvas, gruoblėtas, egzofitinis darinys 0,7x0,4x0,4 cm, nuo odos rezekcijos krašto nutolęs 0,7 cm. Vielos projekcijoje pilkšvas, neaiškių ribų navikas 15x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2 cm.  5(N4). Riebalinio audinio fragmentas 2x1,6x0,4 cm. v/m. 1(N2a). Krūties žemo laipsnio duktalinės karcinoma (DCIS, kribriforminis tipas).  2(N2b). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (4 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.5): pT1c(1,5 cm) pN(sn)0 (0/4 l/m). LVI0(limfovaskulinės invazijos nėra. Krūties odos kapiliarinė hemangioma.  5(N4). Riebalinis audinys.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 10%.. 1(N2a). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; keli kanaliukai su gan monotoniškų ląstelių kribriforminiais proliferatais spindžiuose.  2(N2b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N3). Sinusų histiocitozė keturiuose (4) limfmazgiuose.  4(N1). Krūties audinyje - navikas: trabekulines, negausias smulkias tubulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 12 / 10 DPRL. Krūties odoje - kapiliarinio tipo kraujagyslių suformuotas darinys/navikas.  5(N4). Brandūs lipocitai, negausus fibrozinis audinys.. nan
answer:  0

 51%|█████     | 335/661 [05:07<05:44,  1.06s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. sarginiai l/m, ekstra.   2. deš krūtis, planinis.. 2. Krūtis 437 gramų svorio, 20x14x5 cm. Odoje pilkšvai rusvi, stambiai gruoblėti dariniai 1,2x0,6x0,1 cm, artimiausias nuo odos rezekcijos krašto nutolęs 0,3 cm. Krūties audinyje, viršutiniame, lateraliniame kvadrante - balkšvas, standus kiek neaiškių ribų navikas 0,9x0,7x0,7 cm (sudėtas visas), nuo odos nutolęs 2,7 cm, nuo giliojo rezekcijos krašto - 3,5 cm. Atokiau, viršutiniame lateraliniame kvadrante ir centrinėje krūties dalyje - pilkšvi apvalūs, standūs dariniai iki 0,7 cm skersmens, nuo artimiausio rezekcijos krašto nutolę 1,5 cm, nuo odos 2 cm, artimiausias nuo naviko nutolęs 2,5 cm.. 1. Reaktyvi limfadenopatija (3 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma,   pT1b (9 mm) pN0(sn) (0/3 l/m); LVI0 (limfovaskulinės naviko invazijos neidentifikuota).   Žemo laipsnio duktalinė karcinoma in situ (DCIS, kribriforminė).   Lobulinė karcinoma in situ (LCIS).   Daugybinės intraduktalinės papilomos ir radialiniai randai.   Fibrocistiniai pokyčiai, stulpinis epitelio pokytis su apikalinės sekrecijos požymiais.   Krūties odos seborėjinė keratozė.. 1. Limfmazgiai (3) su ryškia lipomatoze, negausiu limfoidiniu audiniu su tušuota architektūra, negausiais pirminiais folikulais, be naviko plitimo.   2. Spenelis be patologinių pokyčių.   Krūties audinyje - navikas, formuojamas infiltratyviai plintančių, glaudžiai besidėstančių grandinėlių, trabekulinių ir pavienių smulkių blogai suformuotų liaukinių struktūrų, smulkių grupių, sudarytų iš nedidelių-vidutinio dydžio poligonalinių ląstelių šviesiai eozinofiliška citoplazma, nežymiai ar vidutiniškai polimorfiškais ovaliais ar skeltais branduoliais su vezikulizuotu chromatinu, smulkiomis nukleolėmis. Navike iki 1 mitozės/ 10 DPRL. Limfovaskulinės invazijos neidentifikuota. Naviko periferijoje yra latakų su intraduktaliniais solidiniais ir "intraepiteliniais" proliferatais, sudarytais iš aukščiau aprašytam navikui analogiškų ląstelių.   Naviko aplinkoje ir krūties audinyje - daugybinės intraduktalinės šakotos papilinės struktūros, klotos mioepitelinėmis ir dauktalinio epitelio ląstelėmis, su netolygia, fokaliai ryškia hiperplazija. Keli žvaigždiški elastozės ir fibrozės židiniai su stromos deformuotais varijuojančio dydžio ir cistiškai pakitusiais latakais, apokrinine epitelio metaplazija. Viename radialiniame rande - grupė latakų su intraduktaliniais kribriforminiais proliferatais iš duktalinio tipo ląstelių su nežymiu branduolių polimorfizmu.   Cistiškai dilatuotų latakų grupės su apokrinine epitelio metaplazija, lobulių tipo vidutinio dydžio kanaliukų proliferatai su stulpiniu epitelio pokyčiu ir apikalinės sekrecijos požymiais.  Odoje - epidermio dariniai, iškloti hiperplastišku, akantotišku, vietomis papiliarizuotu, hiperkeratotišku daugiasluoksniu plokščiu epiteliu, suformuotu iš bazaloidinių ląstelių su raginėmis cistomis, bazalinio epidermio sluoksnio hiperpigmentacija.. nan
answer:  0

 51%|█████     | 336/661 [05:07<05:15,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 3 biopsiniai stulpeliai.. 3 biopsiniai stulpeliai: I - 8 mm; II - 12 mm; III - 14 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.. Krūties audinį infiltruoja susiliejančios duktalinės struktūros ir netaisyklingi kribroziniai/solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 7/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 100% n
answer:  1

 51%|█████     | 337/661 [05:08<05:13,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 but. 2 biopsiniai stulpeliai iš kairės krūties BI-RADS 4c darinio  2 but. 3 biopsiniai stulpeliai iš dešinės krūties BI-RADS 5 darinio. 1. 2 biopsiniai stulpeliai: I - 15 mm; II - 14 mm.  2. 3 fragmentuoti biopsiniai stulpeliai: I - 6 mm; II - 1 mm; III - 2 mm.. 1. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G2; 7 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    2. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 3 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se navikinio audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.. 1. Krūties audinį 2-se bioptatuose infiltruoja iki 13 mm :   - solidiniai kompleksai ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su ryškiai polimorfiškais branduoliais  negausioje bazofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.    2. Naviko audinį 3-se bioptatuose infiltruoja iki 3 mm :   - solidiniai kompleksai;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje bazofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 80%  naviko ląstelių mem
answer:  1

 51%|█████     | 338/661 [05:09<04:56,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 2 biopsiniai stulpeliai.. 2 biopsiniai stulpeliai: I - 13 mm; II - 9 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja smulkūs solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 1
answer:  0

 51%|█████▏    | 339/661 [05:10<04:52,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas dešinė krūtis ir dešinės pažasties limfmazgiai. Krūtis 140 g svorio, 13x8,5x2 cm. Spenelio projekcijoje pilkšvas, standus neaiškių ribų navikas 37x35x25 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, siekia odą.   Atskirai tame pačiame inde riebalinio audinio fragmentai, bendras dydis 5,5x5x1,5 cm, didžiausias fragmentas žymėtas viela. Vielos projekcijoje, pilkšvas, ribotas židinys 15x10x6 cm, žymėtas spaustuku.   Rasta 10 limfmazgių iki 2,5 cm.. Invazinė duktalinė (kitaip neklasifikuojama)  karcinoma;  (G2; 6 b. pgl. Nottingham sist.);  pT2(37 mm) pLVI-2 pN1a(2/11) pR0.  Imunotipas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 20%.. Krūties audinį infiltruoja navikas iki 37 mm ir atskiro riebalinio audinio fragmente navikinis židinys (iki 15 mm limfmazgyje su ekstranodaliniu plitimu) suformuoti:   - solidinių kompleksų;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 4/10 DPRL.   Stebimas intravaskulinis plitimas smulkiose gyslose; operaciniai kraštai be pokyčių.  Karcinomos mikrometastazė papildomai 1-me/10 l/m.. nan
answer:  1

 51%|█████▏    | 340/661 [05:11<04:37,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 8
answer:  0

 52%|█████▏    | 341/661 [05:11<04:27,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 10 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.. Krūties audinį infiltruoja duktalinės struktūros, nedideli kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+
answer:  6

 52%|█████▏    | 342/661 [05:12<04:20,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 10 mm; III - 10 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja pabiros ląstelės ir smulkūs solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 52%|█████▏    | 343/661 [05:13<04:29,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - viršutinis kraštas  2 - apatinis kraštas  3 - sarginiai l/m 1-2-3 ekstra  4 - kvadrantas - planiniam tyrimui. 4. Krūties sektorius 5x4,5x3 cm su odos lopu 4,5x0,8 cm. Pjūvyje balkšvas, standus, aiškių ribų navikas 1,2x1,1x1 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,3 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(11 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 4 limfmazgiai su fokaline parakortekso hiperplazija, sinusų histiocitoze ir lipomatoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 11 mm), suformuotas fibrozuotoje stromoje ir fokaliai tarp lipocitų ekspansyviu frontu plintančių kribriforminių ir nereguliarių tubulinių bei trabekulinių struktūrų, klotų ląstelėmis vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 6/10 DPRL. Navikas 2 mm nuo žymėto rezekcijos krašto. Šalia negausūs dilatuoti kanaliukai su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais.. nan
answer:  0

 52%|█████▏    | 344/661 [05:14<04:26,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  18 G automatine biopsine adata punktuotas 5x8 mm vos hipoechogeninis darinys, su minimalia vidine kraujotaka, kiek neaiškaus kontūro dešiniojoje krūtyje ties 2 val. vidurinėje dalyje giliai, BIRADS4b, paimti trys biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 16 mm; II - 9 mm; III - 11 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G2; 7 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija teigiama (3+);   Ki67: proliferacinis indeksas 60%.. Krūties audinį 3-se bioptatuose infiltruoja iki 9 mm :   - duktalinės pavienės struktūros netaisyklingi kribroziniai kompleksai ir trabekulės;  - epitelinių  stambių ląstelių su ryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 2/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  CD31: stipri teigiama (+++) membraninė reakcija kraujagyslių endotelyje be atipinių struktūrų spindyje  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: stipri (+++) cirkuliari reakcija, 100% naviko ląstelių membranoj
answer:  0

 52%|█████▏    | 345/661 [05:15<04:18,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 2 biopsiniai stulpeliai.. 2 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 12 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ %.. Krūties audinį infiltruoja juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstel
answer:  0

 52%|█████▏    | 346/661 [05:16<04:13,  1.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 16 mm; II - 13 mm; III - 13 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 20%.. Krūties audinį infiltruoja nedideli solidiniai/kribroziniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 52%|█████▏    | 347/661 [05:16<04:09,  1.26it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  4 biopsiniai stulpeliai histologiniam ištyrimui. 4 fragmentuoti biopsiniai stulpeliai: I - 6 mm; II - 3 mm; III - 2 mm; IV - 3 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja pabiros ląstelės ir juostos iš neryškiai polimorfiškų ląstelių, mitozių mažiau 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 8%.
answer:  0

 53%|█████▎    | 348/661 [05:18<05:00,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - deš. pažasties sarginiai l/m-extra  2 - k. pažasties sarginiai l/m- ekstra  3 - deš. krūtis  4 - k.krūtis 3-4 planniam tyrimui. 3. Krūtis 1055 gramų svorio, 24x18x5 cm. Krūties audinyje, apatinių kvadrantų riboje - balkšvas, standus, neaiškių ribų navikas 15x14x11 mm, nuo odos nutolęs 4,5 cm, nuo giliojo rezekcijos krašto - 0,3 cm. Šalia naviko fibrozės zona su dilatuotais latakais 4x3x1,5 cm, siekia odą, nuo giliojo rezekcijos krašto nutolęs 1,5 cm. Odoje rusvas smulkiai gruoblėtas darinys 0,8x0,6x0,1 cm, nuo artimiausio rezekcijos krašto nutolęs 3 cm.  4. Krūtis 1400 gramų svorio, 27x23x6,5 cm. Krūties audinyje, išorinių kvadrantų riboje - balkšvas, standus neaiškių ribų navikas 6x6x5 mm (sudėtas visas), nuo odos nutolęs 2 cm, nuo giliojo rezekcijos krašto - 3 cm. Krūties audinys fibrozuotas. Odoje rusva dėmė 1x0,7 cm, nuo odos rezekcijos krašto nutolusi 2 cm ir rusvas smulkiai gruoblėtas darinys 0,5x0,4x0,1 cm, nuo odos rezekcijos krašto nutolęs 0,8 cm.. 1(Extra). Reaktyvi limfadenopatija (3 l/m).  2(Extra). Reaktyvi limfadenopatija (3 l/m).  3. Krūties (dešiniosios) invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(15 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).  Odos seborėjinė keratozė.  4. Krūties (kairiosios) invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(6 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: įprastinė duktalinė hiperplazija, fibroadenomatozinė hiperplazija.   Odos seborėjinė keratozė.. 1(Extra). 3 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  2(Extra). 3 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  3.  SPENELIS: normali histologinė struktūra; dilatuoti latakai žemiau.   NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai 15 mm), suformuotas fibrozuotoje stromoje plintančių fokaliai besiliejančių tubulinių, kribriforminių ir negausių trabekulinių bei lizdinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais/apvaliais, kiek polimorfiškais, dalis skeltais ar su smulkia nukleole branduoliais. Mitozių iki 3/10 DPRL.  KRŪTIS: aplinkiniame krūties audinyje yra dilatuotų kanaliukų su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais (DCIS) bei kanaliukų, užpildytų monomorfiškomis ląstelėmis (LCIS); grupės kanaliukų, klotų stulpiniu epiteliu su apikalinės sekrecijos požymiais ar epitelio hiperplazija, yra kanaliukų su apokrinine metaplazija bei dilatuotų kanaliukų, klotų suplokštėjusiu epiteliu.  ODA: darinys su epidermio papiliarizacija ir neryškia akantoze ir hiperkeratoze, bazinių ląstelių hiperplazija ir hiperpigmentacija bei smulkiomis keratininėmis cistomis.  4. SPENELIS: normali histologinė struktūra; dilatuoti latakai bei keli kanaliukai su epitelio hiperplazija žemiau.  NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai -- mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių struktūrų, grandinėlių ir smulkių grupių ląstelių negausia švelniai eozinofiliška citoplazma, smulkiais ir vidutinio kalibro, ovaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 4/10 DPRL.  Šalia yra kanaliukų, užpildytų analogiškomis navikui ląstelėmis ir fibroadenomatozinė hiperplazija.  ODA: darinys su epidermio papiliarizacija ir neryškia akantoze ir hiperkeratoze, bazinių ląstelių hiperplazija ir hiperpigmentacija bei smulkiomis keratininėmis cistomis.. nan
answer:  0

 53%|█████▎    | 349/661 [05:18<04:40,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 17 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja smulkūs solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 8%.  Navikas
answer:  0

 53%|█████▎    | 350/661 [05:19<04:31,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 5 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6,5 mm);  (G1; 5 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 5%.. Krūties audinį 3-se bioptatuose infiltruoja iki 6,5 mm :   - duktalinės struktūros (<10% viso naviko), juostos ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje vakuolizuotoje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija
answer:  0

 53%|█████▎    | 351/661 [05:20<04:41,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)- kraštas - skubus tyrimas - be naviko   2(N2b)- kraštas - skubus tyrimas - be naviko  3(N3)- kairės pažasties sarginis limfmazgis - skubus tyrimas - 2 l/m be naviko  4(N1)- pašalintas kairės krūties darinys - planinis tyrimas. 4. Krūties sektorius 12,5x5x5,5 cm, su odos lopu 11x2 cm, žymėtas viela. Vielos projekcijoje krūties audinys fibrozuotas 5,5x4,5 cm plote. Fibrozėje pilkšvas, neaiškių ribų, standus navikas 12x10x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,3 cm.. 1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (2 l/m).  4(1). Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1b(navikas - 6mm) pN0(sn)(0/2 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-43692 tyrime:  "Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 70% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 6%."  Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis, kribriforminis tipai; -komedo tipo nekrozės).. 1(2a). Riebalinis audinys su fibrozės zonomis, pavieniais latakėliais, klotais dvisluoksniu epiteliu.  2(2b). Riebalinis audinys su fibrozės zonomis, pavieniais latakėliais, klotais dvisluoksniu epiteliu.  3. Du (2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4(1). Krūties fibroziniame audinyje - navikas (mikro - 6mm), formuojamas solidinių/lizdinių, kribriforminių, netaisyklingų duktalinių (~5%) struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 7 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais, kribriforminiais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais; -komedo tipo nekrozėmis (DCIS).. nan
answer:  0

 53%|█████▎    | 352/661 [05:21<04:37,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1. Pašalintas deš.krūties sektorius.   N2. Sektoriaus kraštai.. 1. Krūties sektorius 12x9,5x4 cm su oda 9x6,5 cm. Krūties audinyje, pilkšvas standus, neaiškių ribų navikas 32x27x25 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 1 cm.  2. 2 riebalinio audinio fragmentai: I - 4,5x3,5x0,5 cm, II - 4x2x0,6 cm.. 1. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(32 mm navikas) pNX(limfmazgiai nešalinti) LVI-3(intraveninė invazija). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35-40%.    2. Riebalinis-fibrozinis audinys.  3. Krūties audinys.. 1. Krūtyje - navikas ekspansyviu augimo frontu, suformuotas trabekulinėmis struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais branduoliais ryškiomis nukleolėmis; mitozių 72/10 DPRL. Intraveninė invazija.  2. Riebalinis-fibrozinis audinys.  3.  Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.. Navikas:  HER2: nusidažiusių naviko ląstelių nėra.
answer:  0

 53%|█████▎    | 353/661 [05:22<04:48,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a - skubus tyrimas - be naviko  2 ėminio aprašas: N2b kraštai - skubus tyrimas - be naviko  3 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas - 7 l/m be naviko  4 ėminio aprašas: N1: pašalintas dešinės krūties. 4. Krūties sektorius 7x4,5x3,5 cm, be odos, pjūvyje pilkšvas, standus, 15x15x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm. Aplink naviką krūties audinys fibrozuotas 3x1 cm plote.. 1(ekstra). Kraštai. Krūties fibrocistiniai pokyčiai.  2(ekstra). Kraštai. Krūties fibrocistiniai pokyčiai.  3(ekstra). Reaktyvi limfadenopatija (7 l/m).  4. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham sistemą) duktalinė karcinoma. Suminis TNM: pT1c(15 mm), pN0 (0/7 l/m), R0(radikali rezekcija), LVI-0 (limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN23 solidinis ir kribriforminis tipas). Krūties fibrocistiniai pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).  Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35-40%.. 1(ekstra). Krūties audinio fibrozė, latakai dilatuoti, kloti dvisluoksniu epiteliu.  2(ekstra). Krūties audinio fibrozė, latakai dilatuoti, kloti dvisluoksniu epiteliu.  3(ekstra). Septyni limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais.  4. Krytyje navikas, sudarytas iš desmoplastiškoje stromoje besidėstančių trabekulių, lizdų ir solidinių struktūrų iš ląstelių vidutinio gausumo šviesiai eozinofiliška citoplazma, vidutinio kalibro, ryškiai polimorfiškais, ovaliais apvaliais, branduoliais ryškiomis nukleolėmis. Limfovaskulinė invazija neidentifikuota. Mitozės iki  22/10 DPRL. Greta dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš ląstelių eozinofiliška citoplazma, polimorfiškais nereguliaraus kontūro branduoliais. Aplinkiniame krūties audinyje fibrozė su dilatuotais latakais  klotais dvisluoksniu epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). nan
answer:  0

 54%|█████▎    | 354/661 [05:23<04:55,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a kraštai - extra; - be naviko   2. N2b kraštai - extra; - be naviko   3. Kairės pažasties sarginis limfmazgis - extra. 3 l/m be naviko  4(N1). pašalintas kairės krūties kvadrantas - planinis tyrimas. 4(1). Krūties sektorius 13x6x5 cm, su odos lopu 13x4 cm. Pjūvyje balkšvas, standus neaiškių ribų navikas 19x18x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 3 cm. Šalia naviko paryškėjusi riebalinio audinio zona 2x1,2x1 cm (bendras dydis su naviku 2,6 cm). (zona sudėta visa). 1(2a)(Extra). Krūties audinys.  2(2b)(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  3(Extra). Reaktyvi limfadenopatija (3 l/m).  4(1). Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(19 mm) N(sn)0(0/3 l/m), LVI-2(limfovaskulinė invazija).  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.. 1(2a)(Extra). Krūties audinyje, fibrozuotoje stromoje - negausūs smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2(2b)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu, fokaliai hiperplastišku epiteliu.  3(Extra). 3 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze.  4(1). Krūties audinyje - ribotas navikas, suformuotas fibrozuotoje stromoje plintančių lizdinių, trabekulinių ir negausių kribriforminių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 12/10 DPRL. Limfovaskulinė invazija smulkiose šakose. Naviko centre fibrozės ir elastozės zonos, negausūs kalcifikatai. Šalia naviko dilatuoti kanaliukai su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais, fokaliai su komedo nekrozėmis; negausūs kanaliukai su epitelio hiperplazija.. 1. Navikas (16 blokas): CD34+ endotelizuotose ertmėse naviko plitimas.   Navikas (18 blokas): CD31+ endotelizuotose ertmėse naviko plitimo neidentifikuota.  Navikas (19 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląste
answer:  1

 54%|█████▎    | 355/661 [05:24<04:40,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 12 mm.. Papildyta HER2 FISH.  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė su apokrinine diferenciacija karcinoma.     Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Androgenų receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+).  Ki67 proliferacinis aktyvumas 3%.  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).. Fragmentuotuose bioptatuose (2/2) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis trabekulėmis besidėstančių ląstelių vidutinio gausumo eozinofiliška - amfofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio kalibro branduoliais; mitozių 1/10 DPRL.. Navikas:  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Androgenų receptoriai: (+++)(brand. r-ja) 100%.  HER2: vidutinis dalies membranos nusidažymas 60% naviko ląstelių.  Ki67 proliferacinis aktyvumas 3%.  E-cad
answer:  0

 54%|█████▍    | 356/661 [05:25<04:30,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 bioptatai 22 mm 14G adata iš deformacijos židinio centro ir kraštų.. 3 biopsiniai stulpeliai: I - 7 mm; II - 9 mm; III - 14 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 7 mm);  (G1; 4 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 8%.. Krūties audinį 3-se bioptatuose infiltruoja iki 7 mm :   - duktalinės struktūros (15% viso naviko), netaisyklingi kribroziniai kompleksai ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 8% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko
answer:  0

 54%|█████▍    | 357/661 [05:26<04:20,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Pašalinta dešinė krūtis su išgriuvusiu naviku ir l/n konglomeratais iš I lygio.. Krūtis 366 g svorio, 18,5x8,5x3,5 cm, su raumens fragmentu 8x5x1,6, spenelis pilkšvas standus. Krūties krašte, raumens projekcijoje, pilkšvas standus, neaiškių ribų navikas 65x50x27 mm, nuo giliojo rezekcijos pjūvio nutolęs 0,2 cm, peraugą odą. Naviko projekcijoje oda išopėjusi 2,5x1,6 cm plote. Atskirai tame pačiame inde riebalinio audinio fragmentas 9x7,5x2,3 cm. Rasti 7 limfmazgiai, didžiausias 27 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b (65mm, išopėjimas); pN2a (4 iš 7 l/m).. Krūties audinyje 65mm išopėjęs navikas: solidiniai/kribroziniai kompleksai vidutinio polimorfizmo ląstelių, mitozių iki 10/10 DPRL.   Navikas infiltruoja skersaruožius raumenis.  Iš rastų 7 limfmazgių 4 su metastazėmis iki 27mm.  Naviko židiniai giliajame rezekcijos krašte.. nan
answer:  0

 54%|█████▍    | 358/661 [05:26<04:12,  1.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 8 mm; II - 7 mm; III - 8 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozės pavienės.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 4%
answer:  0

 54%|█████▍    | 359/661 [05:27<04:20,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Kairė krūtis su pažasties l/m, planinis. Krūtis1 g svorio, 19,5x15x4,5 cm, su pažasties narveliena 11x6x2 cm. Krūties audinyje, lateralinių kvadrantų riboje - balkšvas, standus navikas 8x6x6 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,5 cm, nuo odos 5 cm. Pažasties narvelienoje, balkšvas standus židinys 20x15x17 mm, nuo rezekcijos krašto nutolęs 0,1 cm. Rasta 13 limfmazgių, didžiausias 18 mm.. Krūties audinyje du navikai:  1. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b(8mm);  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacijos FISH tyrimo rezultatas teigiamas.  Ki67+ 12%, vietomis iki 20%  2. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties lobulinė karcinoma; pT1c(20mm).  Naviko imunoprofilis biopsinėje medžiagoje B23-18396:  ER(++) 100%; PR(+) 20%; HER2(-); Ki67 mažiau 5%.  pN0 (0 iš 13 l/m).. Krūties audinyje 8mm navikas iš duktalinių ir kribrozinių/solidinių kompleksų vidutiniškai polimorfiškų ląstelių, mitozių iki 15/10 DPRL;  ----------  Krūties audinyje ir pažasties audiniuose 20mm navikas iš juostų ir smulkių solidinių kompleksų nedidelių apvalių vidutiniškai polimorfiškų ląstelių; mitozių mažiau 1/10 DPRL.  Lobulinės karcinomos židiniai pažasties audinių rezekcijos krašte.  Rasta 13 l/m su reaktyviais pokyčiais, be naviko židinių.. Duktalinė karcinoma:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 10% naviko ląste
answer:  1

 54%|█████▍    | 360/661 [05:28<04:10,  1.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 8 mm; II - 9 mm.. Gerai diferencijuota (G1, balai 4 pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.. Krūties audinį infiltruoja duktalinės struktūros ir negausūs kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 30% naviko ląsteli
answer:  0

 55%|█████▍    | 361/661 [05:29<04:23,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.   5. papildomas kraštas, planinis.. 4. Krūties sektorius 10x9x6,5 cm su odos lopu 10x2,9 cm. Pjūvyje balkšvas, neaiškių ribų navikas 22x15x13 mm, nuo odos nutolęs 1,5 cm, nuo artimiausio rezekcijos krašto 0,1 cm. Rezekcijos kraštas markiruotas juodai, tarp naviko pjūvių - žaliai.   5. Riebalinio aufdinio fragmentas 4x1,5x1 cm. v/m. 1. Pjūvio kraštai: krūties audinys be patologinių pokyčių.     2. Pjūvio kraštai: Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS, komedo tipo) krūties audinyje.     3. Sarginiai l/m: limfmazgiai (2) be patologinių pokyčių; pN(sn)0(0/2).    4. Dešinios krūties sektorius.  Krūties invazyvi lobulinė karcinoma (G2, 6b. pagal Nottingham);  pT2(22 mm) pLVI-0 pR0.   Imunofenotipas (nustatytas priešoperaciname naviko biopsijos tyrime):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+). HER2 geno amplifikacija NENUSTATYTA.  Ki67 proliferacinis aktyvumas 3%.    5. Papildomas kraštas. Krūties fibrocistiniai pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).. 1. Pjūvio kraštai: krūties audinys be patologinių pokyčių.   2. Pjūvio kraštai: duktalinių ląstelių  su vidutine branduolių atipija proliferacija išplėstų kanalėlių spindžiuose aplink nekrotinį detritą.   3. Sarginiai l/m: limfmazgiai (2) be patologinių pokyčių.  4. Dešinios krūties sektorius. Krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, trabekulėmis, grandinėlėmis ir pabirai besidėstančių ląstelių negausia eozinofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio-smulkaus kalibro, ovalaus kontūro branduoliais; mitozių 1/10 DPRL. Intravaskulinio plitim nestebima. Navikas 2 mm nuo rezekcijos krašto.  5. Papildomas kraštas. Fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).. nan
answer:  0

 55%|█████▍    | 362/661 [05:30<04:21,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra (be naviko);  2(2b). Kraštai - extra (be naviko);   3. Limfmazgiai - extra (2 l/m be naviko);   4(1). Pašalintas kairės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 7,5x4,5x3,5 cm su oda 6,5x2 cm. Krūties audinyje, kvadrante - pilkšvas, standus, gan aiškių ribų navikas  17x15x15 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 0,3 cm.. 1(2a). Kraštai - riebalinis audinys be patologinių pokyčių.  2(2b). Kraštai - riebalinis audinys be patologinių pokyčių.   3. Limfmazgiai - limfmazgiai (2) be patologinių pokyčių.    4(1). Kairės krūties kvadrantas.   Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT1c pLVI-0 pN0 pR0.  Imunotipas priešoperaciniame biopsijso tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.. 1(2a). Kraštai - riebalinis audinys be patologinių pokyčių.  2(2b). Kraštai - riebalinis audinys be patologinių pokyčių.   3. Limfmazgiai - limfmazgiai (2) be patologinių pokyčių.  4(1). Kairės krūties kvadrantas. Krūties audinį infiltruoja naviko negausios duktalinės struktūros (iki 15 proc.), nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 5/10 DPRL. Plitimo kraujagyslėse ar operaciniuose kraštuose nestebima.. nan
answer:  0

 55%|█████▍    | 363/661 [05:31<04:18,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but.  3 biopsiniai stulpeliai iš ~ 10 mm  neaiškių ribų  dešinės krūties darinio   2 but. 2 biopsiniai stulpeliai iš  ~ 30 mm dydžio kairės krūties darinio. 1. 3 biopsiniai stulpeliai: I - 21 mm; II - 14 mm; III - 10 mm.  2. 2 fragmentuoti biopsiniai stulpeliai: I - 11 mm; II - 13 mm.. Po operacinės medžiagos tyrimo patikslintas N1 naviko tipas  Dešinė  N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.  ------------  Kairė  N2: Mucininė krūties karcinoma (G2, 6 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Dešinė  N1: Krūties audinį infiltruoja smulkios duktalinės struktūros ir solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  ------------  Kairė  N2: Krūties audinyje mucininėje stromoje solidiniai/kribroziniai kompleksai vidutinio polimorfizmo ląstelių, mitozių iki 3/10 DPRL.. nan
answer:  0

 55%|█████▌    | 364/661 [05:32<04:08,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 7 mm; II - 12 mm; III - 9 mm.. Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.. Krūties audinyje mucinų sankaupose netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 4%.
answer:  0

 55%|█████▌    | 365/661 [05:32<04:09,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Pašalinta kairė krūtis ir pažasties narveliena.. Krūtis 21x16x5 cm, su pažasties narveliena 7,5x6,6x2 cm. Krūties audinyje, viršutinių kvadrantų riboje pilkšvas, standus, gan aiškių ribų navikas 23x20x20 mm, nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo odos - 0,6 cm. Nuo naviko, 0,4 cm atstumu pilkšvas, neaiškių ribų, standus židinys 4x4x2 mm. Krūties audinyje, lateralinių kvadrantų riboje rusvas, elastingas darinys/limfmazgis? 1x0,6x0,3 cm. Krūties audinyje rasta 12 limfmazgių, didžiausias 1,6 cm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma: pT2(23mm); pN1(mi) (metastazės intramamariniame limfmazgyje iki 1,5mm; pažasties limfmazgiai (12 l/m) be metastazių).  Intraduktalinės krūties papilomos, radialiniai randai (7 dariniai).. Krūties audinyje 23mm navikas: duktalinės struktūros ir kribroziniai/solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.  Aplinkiniame krūties audinyje gausūs iki 4mm dariniai: šakotos papilinės intraduktalinės strukūros, radialiai plintantys kampuoti kanaliukai.  Intramamariniame limfmazgyje 2 metastazės iki 1,5mm; pažasties limfmazgiai (12 l/m) be metastazių.. nan
answer:  0

 55%|█████▌    | 366/661 [05:34<04:34,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1): pašalintas kairės krūties kvadrantas  - planinis tyrimas  2(N2a) kraštai  - planinis tyrimas  3(N2b) kraštai  - planinis tyrimas   4(N3): kairės pažasties sarginis limfmazgis - planinis tyrimas  5(N4): papildomas kraštas - planinis tyrimas. 1. Krūties sektorius 8x6x3 cm, su odos lopu 7x3 cm. Pjūvyje balkšvas, standus, neaiškių ribų navikas 32x27x21 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 0,1 cm.   2. Riebalinio audinio fragmentas 2,8x2x0,5 cm.   3. Riebalinio audinio fragmentas 2x1,3x0,5 cm.  4. Riebalinio audinio fragmentai, bendras dydis 6x3,5x1,5 cm. Rasti 4 limfmazgiai, didžiausias 1,4 cm.  5. Riebalinio audinio fragmentas 2x1,2x1,4 cm. v/m. 1(N1). Kairės krūties kvadrantas.   Krūties invazyvi vidutiniškai diferencijuota (G2, 7 b. pagal Nottingham sist.) duktalinė karcinoma,   suminis TNM: pT2 (32 mm navikas)   pN0(sn)(0/4 l/m)    pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pP1(perineurinis naviko plitimas)   pR0(radikalus pašalinimas).  Naviko imunotipas operacinėje medžiagoje: HER2: reakcija neigiama (1+).  Naviko imunotipas biopsijoje (B23-13989):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 25% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.    2(N2a). Kraštai. Krūties audinys be patologinių pokyčių.   3(N2b). Kraštai. Krūties audinys be patologinių pokyčių.     4(N3). Kairės pažasties sarginis limfmazgis. Reaktyvi limfadenopatija (4 l/m).     5(N4). Papildomas kraštas. Riebalinis fibrozinis audinys be naviko plitimo.. 1(N1). Kairės krūties kvadrantas. Krūties audinyje - navikas, suformuotas lizdų, smulkių solidinių kompleksų, grandinėlių, pavienių tubulių. Naviko ląstelės su vidutinio gausumo, eozinofiliška citoplazma, vidutinio kalibro, apvaliais, vidutiniškai polimorfiškais branduoliais su aiškiomis nukleolėmis. Mitozių navike iki 14/10DPRL. Naviko stroma desmoplastiška, su kolagenizuotomis zonomis ir negausia limfocitų infiltracija periferijoje. Naviko plitimas endotelizuotuose spindžiuose ir perineuriškai.  2(N2a). Kraštai. Riebalinis audinys su fibrozės septomis ir pavieniais smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(N2b). Kraštai. Riebalinis audinys su fibrozės septomis ir pavieniais smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  4(N3). Kairės pažasties sarginis limfmazgis. Limfmazgiai su lipomatoze, sinusų  histiocitoze, makrofagų ir dendritinių ląstelių infiltracija parakortekse.   5(N4). Papildomas kraštas. Vaskuliaruzotas riebalinis fibrozinis audinys su smulkiomis hemoragijomis.. Blokas 4:  CD31: naviko limfovaskulinės invazijos nėra.   Blokas 5:  E-Cadherin: stipri (+++) reakcija 100% naviko ląstelių membranoje.   EMA: vidutinė (++) reakcija 30% naviko ląstelių citoplazmoje.  HER2: stipri (+++) cirkuliari reakcija, iki 1% naviko
answer:  1

 56%|█████▌    | 367/661 [05:35<04:55,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2): kairės pažasties sarginis limfmazgis - sarginis limfmazgis - 3 l/m be naviko  2(N1): pašalinta kairė krūtis planinis tyrimas. 2(1). Krūtis 1065 gramų svorio, 23x19x7 cm. Krūties audinyje, užspenelinėje srityje - balkšvas, lobulizuotas, elastingas navikas 30x26x16 mm, nuo giliojo rezekcijos krašto - 6 cm, siekia spenelį ir jį įtraukia. Krūties periferijoje vienas limfmazgis, 9 mm skersmens.. 1(2, ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos (mikro)metastazė viename limfmazgyje (mts 1/3 l/m; iki 1,3 mm skersmens).    2(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) mucininė karcinoma, žr. pastabą,   SUMINIS TNM:   pT2 (navikas 30 mm) N1a (mts 2/4 l/m; iki 8,5 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+); mikrometastazėje - reakcijos nėra (0).     Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).  Krūties rezekcijos kraštas be naviko.. 1(2, ekstra). "Sarginiai limfmazgiai": viename (1) limfmazgyje iš trijų (3), planinio tyrimo pjūvyje, naviko (mikro)metastazė - 1,3 mm skersmens, be ekstanodalinio plitimo. Šalia, riebaliniame audinyje - limfovaskulinė invazija smulkiose šakose. Naviką sudaro solidiniai lizdai iš atipinių ląstelių vidutinio gausumo tamsoka citoplazma, ovaliais vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis; metastazėje mucinų produkcijos nėra.   2(1). SPENELIS: dermoje plinta žemiau aprašytas navikas, epidermis hiperkeratotiškas su akatotine hiperplazija, dermoje - gausesnė limfocitinė infiltracija.   NAVIKAS: krūties audinyje, fibrozuotoje stromoje, gausiuose ekstraląsteliniuose mucinuose negausios trabekulinės, kribriforminės ir mikropapilinės naviko struktūros, suformuotos ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio-smulkaus kalibro, ovalaus kontūro branduoliais; mitozių 5/10 DPRL. Židininė MMN infiltracija.   APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).  GILUSIS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.   LIMFMAZGIS(1): viename limfmazgyje - naviko metastazė, 8,5 mm skersmens, be ekstranodalinio plitimo, suformuota dominuojančių nedidelių solidinių ir lizdinių struktūrų bei negausių smulkių duktulių iš analogiškos išvaizdos navikinio epitelio, be mucinų produkcijos.. 1(2, ekstra). "Sarginiai limfmazgiai":   Mikrometastazė (blokas 5):  EMA(+) pavienės ląstelės;  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.   Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių brand
answer:  1

 56%|█████▌    | 368/661 [05:36<04:57,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sektoriaus kraštai - extra;   2. Sektoriaus kraštai - extra;   3. Limfmazgiai - extra.   4. Deš.krūties sektorius su naviku - planinis tyrimas.. 4. Krūties sektorius 8,5x5x1,5 cm su oda 5x1,3 cm. Krūties audinyje, kvadrante - pilkšvas, standus, neaiškių ribų navikas 13x10x7 mm (sudėtas visas) pereinantis į fibrozę (dažyta mėlynu tušu), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 0,9 cm.. Papildyta HER2 FISH.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties fibroadenoma (0,5 cm).  3(ekstra). Krūties duktalinės karcinomos metastazė limfmazgyje su ekstranodaliniu plitimu(1/3 l/m 4 mm).   4. Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(14 mm navikas) pN1a(sn)(1/3 l/m MTS 4 mm su ekstranodaliniu plitimu) LVI-2(limfovaskulinė invazija). Perineurinis plitimas. R0(radikali rezekcija).  Vidutinio - žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1-DIN2, kribriforminis tipas). Lobulinė karcinoma in situ (LCIS).    Imunofenotipas:   Her2 reakcija: ribinė (2+).  HER2 geno amplifikacija nenustatyta.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su mazgu suformuotu edemiškos fibroblastų stromos ir suspaustų latakų, klotų epiteliu neryškiu mioepiteliniu sluoksniu.     3(ekstra). 1 iš 3 limfmazgių aprašyto naviko metastazė 4 mm su ekstranodaliniu plitimu.    4. Krūtyje - navikas (14 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, tubulinėmis, struktūromis besidėstančių ląstelių  negausia eozinofiliška citoplazma, smulkiais - vidutiniais, nežymiai polimorfiškais, ovaliais branduoliais ryškiomis nukleolėmis; mitozių 1/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių. Dilatuoti latakai su intraduktaliniais solidiniais proliferatais iš ląstelių monomorfiškais branduoliais.  Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaus kanaliukų zonos.. 2. Mazgas, mioepitelis: SMA(+++)citopl. r-ja 100%; CK5(+) citopl. r-ja 5%; CK14(+) citopl. r-ja 15%; p63(+/++) brand. r-ja 30%.  3. Navikas (28 blokas): HER2: vidutinė cirkuliari membr r-ja 15%.
answer:  1

 56%|█████▌    | 369/661 [05:37<04:36,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra - be naviko   2(2b). Kraštai - extra - be naviko   3. L/m.-ekstra - extra - be naviko   4. pap. l/m - extra  5(1). sektorius - planinis tyrimas  N1- skubus rentgeninis tyrimas- navikas - nevizualizuojamas.. 5. Krūties sektorius 5,5x3x3 cm, su odos lopu 5x2,3 cm. Krūties audinyje, pjūvyje pilkšvas, standus, aiškių ribų navikas 9x7x7 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 1,2 cm.. N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma; pT1b (9mm).  N2ab: Audiniai be naviko.  N3: Riebalinis audinys, l/m nerasta.  N4: Limfmazgiai (2 l/m) be naviko; pN0(sn).. N1: Krūties audinyje 9mm navikas: smulkūs solidiniai kompleksai, pabiros ląstelės ir juostos iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozės pavienės.  N2ab: Audiniai be naviko.  N3: Riebalinis audinys, l/m nerasta.  N4: Limfmazgiai (2 l/m) be naviko.. nan
answer:  0

 56%|█████▌    | 370/661 [05:37<04:20,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 12  mm ilgio.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 25%.. Krūties audinį infiltruoja juostos ir trabekulės iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: silpnas ar vidutinis dalies membranos nusidažymas 30% naviko ląstel
answer:  1

 56%|█████▌    | 371/661 [05:38<04:26,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra;  2(2b). Kraštai - extra.   3(1). Pašalintas dešinės krūties kvadrantas - planinis tyrimas.   4(3). Dešinės pažasties sarginiai limfmazgiai - planinis tyrimas.. 3(1). Krūties sektorius 10,5x5x5 cm su odos lopu 10x4 cm. Pjūvyje, balkšvas, standus, neaiškių ribų navikas 13x11x9 mm, nuo artimiausio rezekcijos krašto nutolęs 1,5 cm, nuo odos – 1,8 cm. Šalia naviko fibrozės zona 3,5x3x2,2 cm.  4(3). Riebalinio audinio fragmentai, bendras dydis 7x5x1,5 cm. Rasta 11 limfmazgių iki 1,3 cm.. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Riebalinis-fibrozinis audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c pN2a(5/11 l/m iki 7 mm su ekstranodaliniu plitimu) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).  4. Pažasties limfmazgiai: duktalinės karcinomos metastazės limfmazgiuose (5/11 l/m iki 7 mm su ekstranodaliniu plitimu).   Imunofenotipas(biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Riebalinis-fibrozinis audinys.  3. Krūtyje - navikas infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais, branduoliais ryškiomis nukleolėmis;   mitozių 13/10 DPRL.  4. 5 iš 11 limfmazgių aprašyto naviko metastazės iki 7m ekstranodaliniu plitimu.. 3. Navikas(7 blokas): E-cadherin(++/+++) trūkinėjanti membr. r-ja 80%; p120(++/+++) trūkinėjanti membr. r-ja 80%;  4. Metastazė(16 blokas): HER2 silpnas dalies membranos dažymasis 5%
answer:  1

 56%|█████▋    | 372/661 [05:39<04:12,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 40%.. Krūties audinį infiltruoja nedideli solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 7/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 50% naviko ląstelių.  Ki67+ 40
answer:  1

 56%|█████▋    | 373/661 [05:40<04:32,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas - skubu;  2(1b). Apatinis kraštas - skubu;  3(2). Sarginiai limfmazgiai - skubu;  4(3). Kairės krūties kvadrantas - planinis.. 4. Krūties sektorius 9x4x7 cm su odos lopu 7,5x2,5 cm, žymėtas viela. Vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 19x12x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 2,5 cm.. 1(1a, ekstra). "Viršutinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   2(1b, ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos metastazė limfmazgyje (mts 1/3 l/m; iki 6 mm skersmens; be ekstranodalinio plitimo).  4(3). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1c (navikas 18 mm) N1a(sn) (mts 1/3 l/m; iki 6 mm skersmens), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, papilinis, komedo tipai).   Krūties sektoriaus rezekcijos kraštas normalios histologinės struktūros.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys su cistiškai dilatuotais kanaliukais, klotais dvisluoksniu ar kiek hiperplastišku epiteliu; be naviko.   2(1b, ekstra). "Apatinis kraštas": fibrozuotas krūties audinys su cistiškai dilatuotais kanaliukais, klotais dvisluoksniu ar kiek hiperplastišku epiteliu; be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": viename (1) limfmazgyje iš trijų (3) žemiau, punkte Nr.4, aprašyto naviko metastazės, iki 6 mm skersmens, be ekstanodalinio plitimo.   4(3). NAVIKAS (mikroskopiškai - 18 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retos duktalinės, netaisyklingos besiliejančios liaukinės, kribriforminės, trabekulinės, lizdinės, solidinės naviko ir retos papilinės struktūros, suformuotos vidutiniškai ar ryškiai polimorfiškų ląstelių, vidutinio gausumo ar gausesne šviesiai eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis ar ryškiomis nukleolėmis; mitozių iki 10/10 DPRL.   Fokaliai gausi perinavikinė limfocitinė infiltracija su tretinių limfoidinių struktūrų formacija.   APLINKA: šalia naviko - solidiniai, kribriforminiai, papiliniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 4(3). NAVIKAS (blokas 17):   EMA(+)(citopl.r-ja)80%.   HER2: silpna (+) necirkuliari reakcija, 60%  naviko ląstelių membranoje.
answer:  1

 57%|█████▋    | 374/661 [05:41<04:51,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštai - extra - be naviko   2(N2b). kraštai - extra - be naviko   3(N3). sarg. l/m - extra - be naviko   4(N1)- pašalintas sektorius- planinis patologinis tyrimas   N1- skubus rentgninis tyrimas - sektorius su MK ir 2 žymekliais. 4. Krūties sektorius 15x7,5x5,5 cm su oda 14x5 cm, žymėtas 2 vielomis, atstumas tarp vielų 10 cm. Krūties audinyje:  - I vielos projekcijoje pilkšvas, standus I navikas 10x8x7 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 2,2 cm;  - 4 cm atstumu pilkšvas, ribotas, standus II navikas 6x6x4 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 2,5 cm;. 1(2a). Žymėtas kraštas: fibrocistiniai pokyčiai. Dėl nežymėtos fragmento dalies ŽR.PASTABĄ.  2(2b). Žymėtas kraštas: fibrocistiniai pokyčiai. Dėl nežymėtos fragmento dalies ŽR.PASTABĄ.  3. Krūties duktalinės karcinomos mikrometastazė viename limfmazgyje (1/3 l/m, 1,3 mm).   4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mišri duktalinė (50%) ir mikropapilinė karcinoma (50%), TNM: pT1b(m)(2 židiniai: 8,5 mm ir 5,7 mm), pN1mi(sn)(1/3 l/m), LVI2(identifikuota). HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS), kribriforminis ir mikropapalinis variantai.. 1(2a). Žymėtas kraštas: krūties audinys su nežymiai dilatuotais kanaliukais klotais dvisluoksniu epiteliu. PO FIKSACIJOS (nežymėta fragmento dalis): Krūties audinyje keli dilatuoti latakai, užpildyti kribriforminiais proliferatais iš ląstelių negausia eozinofiline citoplazma ląstelių su vidutiniškai polimorfiškais branduoliais. Aplinkiniame krūties audinyje gausūs dilatuoti kanaliukai kloti dvisluoksniu, fokaliai hiperplastišku epiteliu; židininė apokrininė epitelio metaplazija.  2(2b). Žymėtas kraštas: krūties audinys su nežymiai dilatuotais kanaliukais klotais dvisluoksniu epiteliu. PO FIKSACIJOS (nežymėta fragmento dalis): Krūties audinyje keli dilatuoti latakai, užpildyti kribriforminiais proliferatais iš ląstelių negausia eozinofiline citoplazma ląstelių su vidutiniškai polimorfiškais branduoliais. Aplinkiniame krūties audinyje gausūs dilatuoti kanaliukai kloti dvisluoksniu, fokaliai hiperplastišku epiteliu; židininė apokrininė epitelio metaplazija.  3. Viename iš trijų limfmazgių (1/3) žemiau aprašyto naviko mikrometastazė (1/3 l/m, 1,3 mm skersmens).  4(1). Krūties audinyje, hialinizuotoje stromoje 2 naviko židiniai(8,5 ir 5,7 mm mikroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių tubulinių , trabekulinių ir mikropapilinių (I židinyje iki 60%) naviko struktūrų. Naviko ląstelės vidutinio gausumo eozinofiline citoplazma su ryškiai polimorfiškais, hiperchromiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 9/10DPRL. Limfovaskulinis plitimas (LVI2). Greta naviko gausūs dilatuoti kanaliukai užpildyti kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais; dalyje latakų mikropapilinė proliferacija.  Krūties audinyje - dilatuoti latakai su fibrovaskulinėmis struktūromis, klotomis dvisluoksniu epiteliu monomorfiškais branduoliais.. Blokas 34:  CK5: mioepitelis (+)  EMA: (+++)citop.-membran.r-ja 90%;  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 57%|█████▋    | 375/661 [05:42<05:04,  1.07s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.(2) Deš. pažasties sarginiai limfmazgiai, skubu  2.(3) Deš. krūties sektorius, planinis  3.(4) Papildomas viršutinis kraštas, planinis  4.(5) Papildomas apaptinis kraštas, planinis  5(1a). viršutinis kraštas - planinis (extra)  6(1b). apatinis kraštas - planinis (extra). 2(3). Krūties sektorius 11x9,5x5 cm, be odos, žymėtas viela. Vielos projekcijoje - pilkšvas, standus, neaiškių ribų navikas 13x10x6 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 1 cm.  3(4). Riebalinio audinio fragmentas 3x1,6x0,8 cm.   4(5). Riebalinio audinio fragmentas 2x1,2x0,6 cm.   5. Riebalinio audinio fragmentas 2,5x1,5x0,7 cm.   6. Riebalinio audinio fragmentas 2,6x1,2x0,4 cm.. 1(2, ekstra). "Deš. pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).  2(3). "Deš. krūties sektorius":   Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1c (navikas 13 mm) N0(sn) (0/3 l/m), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcijos nėra (0).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis tipas).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Krūties sektoriaus rezekcijos kraštas normalios histologinės struktūros.  3(4). "Papildomas viršutinis kraštas": krūties fibrocistiniai pokyčiai.  4(5). "Papildomas apaptinis kraštas": fibrozuotas riebalinis audinys; be naviko.  5(1a)."Viršutinis kraštas": fibrozuotas krūties audinys; be naviko.   6(1b). "Apatinis kraštas": fibrozuotas krūties audinys; be naviko.. 1(2, ekstra). "Deš. pažasties sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2(3). "Deš. krūties sektorius":   NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios nedidelės lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo tamsoka citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 5/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose.    Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Židiniai su ksantominiais makrofagais.   APLINKA: šalia naviko - solidiniai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.  3(4). "Papildomas viršutinis kraštas": fibrozuotas krūties audinys su dilatuotais ar suspaustais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   4(5). "Papildomas apaptinis kraštas": fibrozuotas brandžių lipocitų suformuotas audinys; be naviko.   5(1a)."Viršutinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   6(1b). "Apatinis kraštas": fibrozuotas krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.. 2(3). Navikas (blokas 15):  HER2: reakcijos naviko ląstelių membranoje nėra.  GATA3: (+++)(brand.r-ja)100%; Synaptophysin: (-).
answer:  0

 57%|█████▋    | 376/661 [05:43<04:38,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1- pašalinta krūtis. Krūtis, 564 g svorio, 19x15x4,5 cm. Krūties audinyje, pjūvyje šviesiai pilkas, standus, neaiškių ribų navikas 15x25x20 mm, pereinantis į fibrozės zoną.  Navikas nuo artimiausio rezekcijos pjūvio nutolęs 1,3 cm, nuo odos - 1,2 cm. Odoje, spenelio srityje balkšvi, standūs iškilę dariniai iki 0,9x0,7x0,3 cm.. Vidutinės diferenciacijos duktalinė krūties karcinoma: navikas krūtyje 25mm; naviko židiniai/satelitai odoje; intravaskulinis naviko plitimas.. Krūties audinyje 25mm navikas iš solidinių/kribrozinių kompleksų vidutiniškai ir ryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL; tokios pačios struktūros naviko židiniai/satelitai odoje iki 9mm; intravaskulinis naviko plitimas.  Rezkecijos kraštas be naviko.. nan
answer:  0

 57%|█████▋    | 377/661 [05:44<04:20,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 13 mm; II - 12 mm.. Invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) karcinoma: galima/tikėtina krūties duktalinė ("bazinio" imunofenotipo) adenokarcinoma.     Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Her2 imuninė reakcija: neigiama (0).  Ki67: 30% (hot spot 40%).. Solidines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne blyškiai-saikingai eozinofiline citoplazma, vidutinio kalibro ar stambesniais apvalios formos netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 29 / 10 DPRL.. Navikas  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: nusidažiusių naviko ląstelių nėra.  Her2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  Prolife
answer:  30

 57%|█████▋    | 378/661 [05:45<04:29,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - viršutinis kraštas, skubu  2 - apatinis kraštas, skubu  3 - sarginiai l/m, skubu  4 - kvadrantas - planiniam tyrimui. 4. Krūties sektorius 7x5,5x4 cm su oda 4x1 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje - balkšvas, standus, neaiškių ribų navikas 11x11x10 mm, nuo giliojo rezekcijos krašto nutolęs 1,1 cm, nuo odos - 1,7 cm.. 1(2a, ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su koaguliaciniais artefaktais; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (5 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 11 mm) N0(sn) (0/5 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2:reakcijos nėra (0).    Krūties fibroadenoma (~4 mm).. 1(2a, ekstra). "Kraštai": fibrozuotas brandžių lipocitų suformuotas fragmentas; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": penki (5) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje, gausiai limfocitais infiltruotoje stromoje, infiltratyviai plinta fokaliai besiliejančios kribriforminės, trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai ar ryškiau polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su fokaliai ryškiomis eozinofiliškomis nukleolėmis; mitozių iki 7/10 DPRL. Gausūs naviką infiltruojantys limfocitai.   APLINKA: šalia naviko ribotas, 4 mm skersmens, darinys, suformuotas edematoziškos/miksoidiškos stromos ir suspaustų kanaliukų, klotų dvisluoksniu epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 4. Navikas (blokas 22):  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 57%|█████▋    | 379/661 [05:46<04:17,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 90% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.. Bioptate - desmoplastiškoje stromoje, infiltratyvios naviko struktūros, suformuotos solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška tamsia ar ryškia citoplazma, polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais; ryškiomis nukleolėmis mitozių 4/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 90%.  HER2: nusidažiusių  aviko ląstelių nėra.  Ki67 proliferacinis aktyvumas 10%.  E-cadherin(+++) membr. r-ja 100%.  CK14 foninė citopl. r-ja.
answer:  0

 57%|█████▋    | 380/661 [05:47<04:07,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 bioptatai 22 mm 14G adata iš 12 mm spikulinio židinio.. 2 biopsiniai stulpeliai: I - 11 mm; II - 10 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%, vietomis iki 10%.. Krūties audinį infiltruoja negausios duktalinės struktūros, smulkūs netaisyklingi kribroziniai ir solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 58%|█████▊    | 381/661 [05:48<04:22,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Pašalinta dešinė pažasties narveliena ir deš. krūtis.. Krūtis 809 g svorio, 20x16x5 cm, su fragmentuota pažasties narveliena, bendras dydis 13x10x4 cm. Spenelis įtrauktas. Krūties centrinė dalyje, balkšvi, standus židiniai, bendras dydis 3,2x2,5x3,2 cm:  - I navikas 24x20x32 mm, esantis 2 cm nuo artimiausio rezekcijos pjūvio, nuo odos 1,5 cm,   - galimai atskiras II navikas 6x6x6 mm, nuo pagrindinio (I) naviko nutolęs 0,5 cm, nuo artimiausio rezekcijos pjūvio nutolęs 3 cm.    - galimai atskiras III navikas 7x7x7 mm, nuo pagrindinio (I) naviko nutolęs 0,4 cm, nuo artimiausio rezekcijos pjūvio nutolęs 1 cm.  Pažasties narvelienoje rastas 21 limfmazgis su židiniais iki 1,8 cm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT(m)2(32 mm ir 7 mm naviko židiniai)   pN1a (2/21 l/m su mts iki 18mm)   pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pR0(radikalus pašalinimas).   Naviko imunotipas operacinėje medžiagoje (metastazės limfmazgyje): HER2:reakcijos nėra (0).  Naviko imunotipas iš biopsijos (B23-11819):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 kribriforminis, komedo tipai).  Intraduktalinė papiloma (1 mm).. Spenelis: be patologijos.  Rezekcijos kraštai: be naviko plitimo.    Krūties audinyje -  du atskiri naviko židiniai:  I navikas(makroskopiškai iš I ir II susiliejusių židinių) suformuotas tubulinių (~20%), lizdinių, kribriforminių, šakotų ir besiliejančių papilinių struktūrų. Naviko ląstelės su gausia, šviesiai eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais. Mitozių navike iki 9/10DPRL. Navikas plinta smulkiose gyslose. Naviko stroma desmoplastiška, su negausiais mikrokalcifikatais.   Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.  II (makroskopiškai- III) navikas: lizdinės, kribriforminės struktūros iš I navikui analogiškų ląstelių. Mitozių navike iki 8/10DPRL.  Aplinkiniame krūties audinyje kanaliukai su intraduktaliniais papiliniais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu.  Limfmazgiai: 2/21 limfmazgių - aukščiau aprašyto naviko metastazės iki 18 mm (makroskopiškai); stebimas ekstranodalinis plitimas.. Blokas 38:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 58%|█████▊    | 382/661 [05:49<04:07,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stulepliai. 3 biopsiniai stulpeliai: I - 10 mm; II - 10 mm; III - 5 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis 15%.. Krūties audinį infiltruoja nedideli solidiniai kompleksai, šakotos juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 10%, vi
answer:  0

 58%|█████▊    | 383/661 [05:50<04:24,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. Kairės pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: 2. Kairė krūtis, planinis. 2. Krūtis gramų svorio, 22x18x6 cm. Krūties audinyje, spenelio projekcijoje, pilkšvas, neaiškių ribų, standus navikas 20x14x10 mm, nuo giliojo rezekcijos krašto nutolęs 2,5 cm, nuo odos - 1,2 cm. Aplink naviką krūties audinys fibrozuotas su cistinėmis ertmėmis 0,9 cm, nuo naviko 2 cm atstumu lateraliau, balkšvas, ribotas darinys 6x5x4 cm, nuo giliojo rezekcijos krašto nutolęs 0,5, nuo odos - 3 cm. Fibrozuotame audinyje, balkšvi standūs židiniai iki 1 cm. Rasti limfmazgiai iki cm.. 1. Duktalinės karcinomos metastazė limfmazgyje (1/2 l/m; iki 14,6mm).  2. Krūties invazyvi, blogai diferencijuota (G3; 9 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(m)(dauginiai naviko židiniai nuo 1,33mm iki 20mm) pN1a(1/2 l/m; iki 14,6mm); LVI-2(Limfo-Vaskulinė naviko Invazija (LVI) smulkiose kraujagyslėse/limfagyslėse); PN(perineurinis naviko plitimas).   IHC reakcijos atliktos VPC:B23-489 tyrime:  "Estrogenų receptoriai: vidutinė reakcija 90% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 5% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%."  Krūties vidutinio ir aukšto laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas; -komedo tipo nekrozė). Intraduktalinės krūties papilomos. Krūties fibrocistiniai pokyčiai, paprasta intraduktalinė hiperplazija.. 1. Viename(1) iš dviejų(2) limfmazgių žemiau aprašyto naviko metastazės (iki 14,6mm).  2. Krūties audinyje - dauginiai naviko židiniai (nuo 1,33mm iki 20mm), formuojami solidinių/lizdinių, trabekulinių, netaisyklingų duktalinių (<10%) struktūrų iš vidutinio kalibro ląstelių, vidutiniškai, vietomis ryškiai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 16 mitozių/10 DPRL; Limfo-Vaskulinės naviko Invazijos (LVI) smulkiose kraujagyslėse/limfagyslėse židiniai; perineurinis naviko plitimas (PN). Aplinkiniame krūtie audinyje - dilatuoti latakai su kribriforminiais, "arkiniais" atipinių ląstelių (su aukšto laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS). Krūties audinyje - dilatuoti latakai su fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu; fibrozės zonos su dilatuotais latakais, klotais dvisluoksniu epiteliu, apokrininės metaplazijos zonomis, paprastos intraduktalinės hiperplazijos židiniais. Spenelis be patologinių pokyčių. Rezekcijos kraštas be naviko plitimo.. Estrogenų receptoriai: vidutinė reakcija 90% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 5% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.
answer:  0

 58%|█████▊    | 384/661 [05:50<04:08,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 bioptatai 12G 22 mm adata iš darinio su mkk. 3 biopsiniai stulpeliai: I - 16 mm; II - 12 mm; III - 14 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 35%.. Krūties audinį infiltruoja negausios duktalinės struktūros, smulkūs solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 12/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 80% naviko ląstelių.  Ki67+ 35%.
answer:  1

 58%|█████▊    | 385/661 [05:51<04:11,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N3) kairės pažasties sarginis limfmazgis - skubus tyrimas - 3 l/m be naviko  4(N1) pašalintas kairės krūties kvadrantas su vielute - planinis tyrimas. 4. Krūties sektorius 6x6x3 cm, be odos. Pjūvyje pilkšvas, standus gan aiškių ribų navikas 10x6x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm. (navikas sudėtas visas). 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Riebalinis - fibrozinis audinys.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(9,5 mm navikas) pN0(sn)(0/3 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas). R0(radikali rezekcija).    Imunofenotipas(biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 10%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Riebalinis - fibrozinis audinys.  3(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (9,5 mm) infiltratyviu augimo frontu, suformuotas pavienėmis tubulinėmis ir lizdais besidėstančių ląstelių vidutinio gausumo ryškia eozinofiliška citoplazma, vidutiniais - stambiais, vidutiniškai polimorfiškais, nereguliaraus kontūro, ovaliais branduoliais ryškiomis nukleolėmis; mitozių 13/10 DPRL. Greta dilatuoti kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių.. nan
answer:  0

 58%|█████▊    | 386/661 [05:52<03:58,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%, vietomis iki 80%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai ir trabekulės iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 20/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 60%, vietomis
answer:  1

 59%|█████▊    | 387/661 [05:53<04:35,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- kairės krūties sektorius, planinis  4(3)- virš.krašt, papildomai planas. 3(2). Krūties sektorius 6x5x3,5 cm, be odos, žymėtas siūlu. Siūlo projekcijoje fibrozės zona 4,5x2,5x1,7 cm. Fibrozėje pilkšvas, standus, aiškių ribų navikas 2,2x1,9x1,5 cm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm.  4(3). Riebalinio audinio fragmentas 2,2x1,5x0,5 cm.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys; be naviko.   2(1b, ekstra). "Apatinis kraštas": koaguliacijos zonoje, gilesniuose pjūviuose neišliekantis 1,9 mm židinys, kuriame histologiniai pokyčiai artimiausi žemo laipsnio duktalinės karcinomos in situ (DIN1/DCIS; kribriforminio tipo) ar inkapsuliuotos papilinės karcinomos (kuri traktuojama kaip in situ karcinoma) plitimui.     3(2). Krūties inkapsuliuota papilinė karcinoma (~22 mm) su invazyvia gerai diferencijuota (G1, 5 balai pagal Nottingham) duktaline karcinoma, pT1a(m) (keli nedideli invazijos židiniai iki 2 mm; žr. pastabą),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Invazyvaus naviko imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas iki 5%.    Krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: kribriforminis tipas).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė, apokrininė metaplazija).   Inkapsuliuotos papilinės karcinomos neinvazyvus komponentas nuo sektoriaus rezekcijos krašto nutolęs - 0,1 mm.   4(3). "Papildomas kraštas": fibrozuotas riebalinis audinys; be naviko.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(1b, ekstra). "Apatinis kraštas": ekstra tyrimo stikluose, fragmento koaguliacijos zonoje - nedidelis 1,9 mm židinys su dilatuotais latakais užpildytais intraduktaliniais kribriforminiais-papiliniais proliferatais; dėl ryškių koaguliacinių artefaktų citologinės ypatybės dalinai sunkiai įvertinimos. Planinio tyrimo pjūviuose zona neišlieka.   3(2). NAVIKAS: krūties audinyje stambus fokaliai gan aiškiai storos fibrozinės kapsulės ribojamas lobulizuotas naviko židinys (be CK14+ mioepitelinių ląstelių), suformuotas papilinių-kribriforminių ir solidinių plotų iš vidutiniškai ar fokaliai ryškiau polimorfiškų ląstelių su vidutinio gausumo eozinofiline citoplazma, varijuojančio dydžio ovaliais hiperchromiškais braduoliais; gausūs smulkūs kalcifikatai; židinys su hemosiderofagais, cholesterolio kristalais, fibroblastų proliferacija ir histiocitais, negausiais limfocitais. Židinio periferijoje keletas nedidelių darinio kapsulę kertančių ir aplinkinį riebalinį audinį infiltruojančių židinių (iki 2 mm), kuriuos formuoja retos besiliejančios duktalinės ir gausesnės kribriforminės naviko struktūros, suformuotos saikingai polimorfiškų ląstelių, negausia šviesia eozinofiline citoplazma, vidutinio dydžio ovaliais/apvaliais branduoliais; mitozių iki 6/10 DPRL. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Limfovaskulinė naviko invazija smulkiose šakose.    APLINKA: šalia naviko - keli nedideli kribriforminiai intraduktaliniai naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: inkapsuliuoto neinvazyvus naviko komponentas (be CK14+ mioepitelinio sl.) nutolęs 0,1 mm.  4(3). "Papildomas kraštas": brandžių lipocitų suformuotas fragmentas su smulkiomis kraujagyslėmis ir nerviniais kamienais; be naviko.. 3(2). Invazyvus navikas (blokas 23):  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 2% naviko
answer:  0

 59%|█████▊    | 388/661 [05:54<04:28,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai  - skubus tyrimas  2(N2b) kraštai  - skubus tyrimas  3(N3): dešinės pažasties sarginis limfmazgis - skubus tyrimas  4(N1) pašalintas dešinės krūties kvadrantas su vielute, planiškai.. 4(N1). Krūies sektorius 9x3,5x8,5 cm, su odos lopu 9x3,5 cm; sektoriuje - chirurgine viela žymėtas pilkšvas standus aiškių ribų navikas 15x15x10 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 5 cm.. 1(N2a). Krūties fibrocistiniai pokyčiai.  2(N2b). Krūties fibrocistiniai pokyčiai. Paprastoji duktalinė hiperplazija.  3(N3). Reaktyvi limfadenopatija (4 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,5 cm) pN(sn)0 (0/4 l/m). LVI0(limfovaskulinės invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 15% (hot spot 20%).. 1(N2a). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2(N2b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; intraduktalinės hiperplazijos židiniai.  3(N3). Sinusų histiocitozė keturiuose (4) limfmazgiuose.  4(N1). Krūties audinyje - navikas: solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 5 / 10 DPRL.. 4(N1). Navikas (17 blokas): Her2 silpna trūkinėjanti/necirkuliari membraninė r-ja, 5% naviko ląstelių; Ki67 15% (hot spot 20%).
answer:  1

 59%|█████▉    | 389/661 [05:55<04:29,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas  2 ėminio aprašas: N2a  3.  N2b kraštai - planinis tyrimas  4. 3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - planinis tyrimas  5. ėminio aprašas: N4: papildomas kraštas - planinis tyrimas. 1. Krūties sektorius 13x5x3 cm, su odos lopu 10,5x3 cm. Krūties audinyje, pjūvyje balkšvas, standus 25x22x15 mm navikas, nuo artimiausio rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2 cm.   2(2a). Riebalinio audinio fragmentas 2,3x1,2x0,4 cm. v/m  3(2b). Riebalinio audinio fragmentas 2,3x1,7x0,37 cm. v/m  4(3). Riebalinio audinio fragmentai, bendras dydis 3,5x3x1 cm. Rasti 4 limfmazgiai, didžiausias 2 cm.   5(4). Riebalinio audinio fragmentas 2,5x1,5x0,7 cm. v/m. N1: pašalintas kairės krūties kvadrantas.   Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo  nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.    N2(N2a): kraštai. Krūties audinys be patologinių pokyčių.  N3(N2b): kraštai. Krūties audinys be patologinių pokyčių.  N4(N3): kairės pažasties sarginis limfmazgis. Limfmazgiai (4) be patologinių pokyčių.  N5(N4): papildomas kraštas. Krūties audinys be patologinių pokyčių.    pT1c(18 mm) pLVI-0 pL0 pR0.. N1: pašalintas kairės krūties kvadrantas. Krūties audinį infiltruoja naviko (mikroskopoiškai 18 mm) duktalinės struktūros (iki 30 proc.), netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.   Intravaskulinio plitimo nestebima, nuo operacinių kraštų 2 mm.   N2(N2a): kraštai. Krūties audinys be patologinių pokyčių.  N3(N2b): kraštai. Krūties audinys be patologinių pokyčių.  N4(N3): kairės pažasties sarginis limfmazgis. Limfmazgiai (4) be patologinių pokyčių.  N5(N4): papildomas kraštas. Krūties audinys be patologinių pokyčių.. nan
answer:  0

 59%|█████▉    | 390/661 [05:56<04:12,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 11 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.. Krūties audinį 2-se bioptatuose infiltruoja iki 9 mm :   - smulkios trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių mem
answer:  0

 59%|█████▉    | 391/661 [05:57<04:00,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 13 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%, vietomis iki 80%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 15/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 60%, vietomis iki 80%.
answer:  0

 59%|█████▉    | 392/661 [05:58<04:28,  1.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštas - extra - be naviko  2(N2b). kraštas - extra - be naviko  3(N3). Sarg. l/m - extra 2 sarginiuose  l/m iš 6 pašalintų rastos mts   4(N1) - sektorius - planinis patologinis tyrimas ir skubus rentgeninis tyrimas- navikas pašalintas. 4(1). Krūties sektorius 5x3,5x2 cm be odos. Pjūvyje, pilkšvas, gan aiškių ribų navikas 17x13x10 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,1 cm.. 1(2a, ekstra). "Kraštai": krūties audinys su koaguliuotais kanaliukais; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos metastazė dvejuose limfmazgiuose (mts 2/6 l/m; iki 9 mm skersmens).  4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma   su mikropapiliniu komponentu (~40%) ir židinine mucinų produkcija (~25%), SUMINIS TNM:   pT1c (navikas 13 mm) N1a(sn) (mts 2/6 l/m; iki 9 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose).   Gausūs naviką infiltruojantys limfocitai. Kalcifikatai.     Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 98% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 5% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%. Karštame taške 15-20%.    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis ir papilinis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).   Nuo sektoriaus rezekcijos krašto invazyvus navikas nutolęs 0,1 mm, DCIS komponentas - 0,5 mm.. 1(2a, ekstra). "Kraštai": nežymiai fibrozuotas krūties audinys su koaguliuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas, vaskuliarizuotas brandus rieb. aud.; be naviko.   3(ekstra). "Sarginiai limfmazgiai"(6): dviejuose (2) limfmazgiuose žemiau, punkte Nr.4, aprašyto naviko metastazės, iki 9 mm skersmens, su ekstranodaliniu plitimu.   4(1). NAVIKAS (invazyvus navikas - 13 mm skersmens; su aplinkiniu DCIS komponentu židinys - 17 mm):   krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios netaisyklingos liaukinės, kribriforminės ir intraliuminalinės mikropapilinės naviko struktūros, suformuotos vidutiniškai ar ryškiau polimorfiškų ląstelių, vidutinio gausumo tamsoka citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 15/10 DPRL. Židininė ekstraląstelinių AB+ mucinų produkcija (iki 25%). Nedideli naviko nekrozės židiniai (<5%). Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Pavieniai mikrokalcifikatai.  APLINKA: šalia naviko - kribriforminiai ir papiliniai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   SEKTORIAUS REZEKCIJOS KRAŠTAS: invazyvus navikas nutolęs 0,1 mm; DCIS komponentas - 0,5 mm.. 4. Navikas (blokas 15):  EMA: (+) mikropapilinių kompleksų periferijoje.   Estrogenų receptoriai: stipri (+++) reakcija, 98% naviko ląstelių branduoliuose.  Progesterono receptoriai: vidutinė (++) reakcija, 5% naviko ląstelių branduoliuose.  HER2: silpna
answer:  1

 59%|█████▉    | 393/661 [05:59<04:09,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 60% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 40%.. Bioptate - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, nežymiai polimorfiškais, vidutinio kalibro, ovalaus kontūro branduoliais; mitozių 4/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (++)(brand. r-ja) 60%.  HER2: silpnas dalies nusidažymas 1% naviko ląstelių.  Ki67 proliferacinis aktyvumas 40%.
answer:  0

 60%|█████▉    | 394/661 [06:00<04:21,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu  3(2). Kairės pažasties sarginiai limfmazgiai, skubu  4(3). Kairės krūties sektorius, planinis  3. Kairės krūties sektorius, planinis. 4(3). Krūties sektorius 9,5x4,5x7 cm, su odos lopu 7x3 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 17x10x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos nutolęs 4,3 cm.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys; be naviko.   2(1b, ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai; be naviko.   3(2, ekstra). "Kairės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 17 mm) N0(sn) (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Navikas nuo sektoriaus rezekcijos krašto nutolęs 0,1 mm.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(1b, ekstra). "Apatinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar nežymiai hiperplastišku epiteliu; be naviko.   3(2, ekstra). "Kairės pažasties sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios negausios duktalinės (<10%), kribriforminės, trumpos trabekulinės, nedielės lizdinės naviko struktūros ir pabiros saikingai ar vidutiniškai polimorfiškos ląstelės, negausia ar vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 2/10 DPRL.   Nedideli židiniai su PMN židiniais, pavientės svetimkūnio tipo gigantinės ląstelės.   APLINKA: aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: navikas nutolęs 0,1 mm.. 3(ekstra). "Kairės pažasties sarginiai limfmazgiai" (blokas 3):  CK7(+) elementų nėra.   4. Navikas (blokas 11):  E-Cadherin(++/+++)(kiek netolygi membr.r-ja)100%;   p120-Catenin(++/+++)(kiek netolygi membr.r-ja)100%;   HER2: silpna (+) necirkuliari reakc
answer:  20

 60%|█████▉    | 395/661 [06:01<04:03,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Histologinis tyrimas. Rusvo audinio fragmentai, bendras dydis 0,9x0,7x0,2 cm. v/m. Suderinama su blogai diferencijuotos duktalinės krūties karcinomos plitimu odos bioptatuose;   G3 (8 b. pgl. Nottingham sist.);  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 50%.. Odos bioptatuose infiltruoja keli smulkūs solidiniai solidiniai kompleksai epitelinių vidutinio dydžio ląstelių su vidutiniškai/ polimorfiškais branduoliais  negausioje citoplazmoje; mitozių iki 5/1 DPRL.   Mikrokalcifikatai nestebimi.. Blokas 1:  CK7: stipri teigiama (+++)   membraninė reakcija 90 proc. duktalinėse ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  GATA3: neigiama  HER2: vidutinė (++) necirkuliari reakcija, 30%  naviko ląstelių membranoje
answer:  1

 60%|█████▉    | 396/661 [06:02<04:03,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1. Kvadranto kraštai.   N2. Kvadranto kraštai.   N3. Sarginiai l/m,. -ekstra.  N4. K. krūties kvadrantas su naviku.. 4. Krūties sektorius 11x5,5x5 cm su odos lopu 10,5x4,5 cm ir raumens fragmentu giliajame krašte 3x2,5x0,5 cm. pjūvyje balkšvas, standus, spikuliniu kraštu navikas 2,4x2,2x2,3 cm, nuo artimiausio rezekcijos krašto nutolęs 0,4 cm, siekia odą. Oda naviko projekcijoje sustandėjusi. Makroskopiškai navikas infiltruoja raumeninį audinį.. 1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (3 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(23 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).. 1(Extra). Krūties audinyje - negausūs smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje - smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 3 limfmazgiai su pavieniais antriniais limfoidiniais folikulais, neryškia sinusų histiocitoze ir lipomatoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 23 mm), suformuotas fibrozuotoje stromoje ir tarp lipocitų plintančių lizdinių, trabekulinių, tubulinių ir negausių kribriforminių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro, apvaliais/ovaliais, kiek polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 9/10 DPRL. Negausūs mikrokalcifikatai. Navikas plinta tarp skersaruožių miocitų bei dermoje, epidermio nesiekia. Navikas 4,1 mm nuo rezekcijos krašto.. nan
answer:  0

 60%|██████    | 397/661 [06:03<03:51,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm.. Invazinė lobulinė karcinoma (mažiausiai iki 13 mm);  (G2; 6 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 45%.. Krūties audinį 1-me bioptate infiltruoja iki 13 mm :   - solidiniai kompleksai su nekrozėmis;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 5/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: silpna teigiama (+)  membraninė reakcija 10proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose,
answer:  0

 60%|██████    | 398/661 [06:04<04:00,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštas, ekstra.  2. pjūvio kraštas, ekstra.  3. sarginiai l/m, ekstra.   4. sektorius, planinis. 4. Krūties sektorius 11,5x3x7,5 cm su odos lopu 9,3x1,5 cm, žymėtas viela. Vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 10x9x6 mm cm, nuo giliojo rezekcijos krašto nutolęs 0,9 cm, nuo odos - 2,6 cm.. 1. Krūties lobulinė karcinoma in situ (LCIS).   2. Fibrocistiniai krūties pokyčiai: plokščia epitelio atipija, apokrininė epitelio metaplazija.  3. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 5 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1b(navikas 8 mm), pN0(sn)(0/1 l/m), LVI0 (neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Krūties lobulinė karcinoma in situ (LCIS).. 1. Krūties audinyje gausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.   2. Krūties audinyje keli nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu su židinine epitelio proliferacija su kiek stratifikuotais, nežymiai polimorfiškais branduoliais. Krūties audinyje židininė fibrozė ir apokrininė epitelio metaplazija.  3. Vienas limfmazgis su sinusų histiocitoze.  4. Krūties audinyje navikas (8 mm mikroskopiškai), infiltratyviu augimo frontu, suformuotas tubulinių, negausių kribriforminių ir trabelinių struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, vidutiniškai polimorfiškais, hiperchromiškais, smulkiai grūdėtu chromatinu branduoliais, pavieniais paryškėjusiais branduolėliais. Mitozių navike 6/10DPRL. Limfovaskulinė naviko invazija neidentifikuota(LVI0). Navikas nuo rezekcijos krašto nutolęs per 6 mm. Krūties audinyje greta naviko gausūs latakai užpildyti kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, hiperchromiškais, vidutiniškai polimorfiškais branduoliais; šalia yra nežymiai dilatuotų latakų užpildytų solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.. Blokas 17:  HER2: reakcijos naviko ląstelių membranoje nėra.  Kanaliukai 3:  CK5:mioepitelinis sluoksnis +.
answer:  0

 60%|██████    | 399/661 [06:04<03:54,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. kairės pažasties l/m, planinis.  2. kairė krūtis, planinis.. 1. Riebalinio audinio fragmentai, bendras dydis 8,5x6x1,3 cm. Rasta 12 limfmazgių iki 2,7 cm.  2. Krūtis 600 g svorio, 22x18,5x5 cm. Krūties audinyje viršutiniame medialiniame kvadrante - pilkšvas, standus, neaiškių ribų navikas 32x30x25 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 1,5 cm, nuo odos - 1,3 cm. Navike cistinės ertmės iki 0,3 cm skersmens. Fibrozėje pilkšvas, neaiškių ribų sustandėjimas 0,7x0,7x0,5 cm.. N1: Duktalinės karcinomos metastazė limfmazgyje (1 iš 12 l/m, 10 mm); pN1a.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1a (4mm).  Žemo laipsnio intraduktalinė karcinoma (DCIS/DIN1, mikropapilinis tipas); ryškūs fibrocistiniai pokyčiai, intraduktalinės papilomos.. N1: Viename iš rastų 12 limfmazgių 10mm duktalinės karcinomos metastazė su ekstranodaliniu plitimu.  N2: Krūties audinyje 4mm navikas iš nedidelių solidinių ir kribrozinių struktūrų, kurias formuoja vidutinio polimorfizmo ląstelės, mitozių iki 1/10 DPRL. Šalia naviko fibrozės su mikrohemoragijomis juosta, negausia limfocitų ir histiocitų infiltracija (biopsijos vieta).  Aplink naviką gausūs intraduktaliniai papiliniai ląstelių proliferatai, cistinė kanaliukų dilatacija, apokrininė metaplazija, ryški stromos fibrozė.. nan
answer:  0

 61%|██████    | 400/661 [06:06<04:08,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Užspenelinis audinys, skubu  2. sarginiai limfmazgiai, skubu  3. Kairės krūties audinys, planinis  4. Likę limfmazgiai, planiniai. 3. Krūties fragmentas 12,5x11x2,5 cm, su odos lopu 4x1,5 cm. Pjūvyje, viršutinių kvadrantų riboje, balkšvas, standus, neaiškių ribų navikas 32x24x11 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 2 cm. Medialinių kvadrantų riboje balkšvas standus darinys 0,5x0,4x0,4 cm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,5 cm. Krūties audinys fibrozuotas.   4. Riebalinio audinio fragmentai, bendras dydis 3x3x0,7 cm. Rasti 3 limfmazgiai iki 0,7 cm.. 1. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).   2. Krūties duktalinės karcinomos metastazės 4 limfmazgiuose (4/7 l/m, iki 10 mm skersmens, ekstranodalinis plitimas).   3. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT2(m)(navikai 28 mm ir 5,5 mm), pN2a(4/10 l/m), LVI2 (limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime. HER2:reakcijos nėra (0). Ki67: proliferacinis indeksas 15%. Karštame taške 25%.  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Fibrocistiniai krūties pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).   4. Reaktyvi limfadenopatija (3 l/m).. 1. Fibrozuotame krūties audinyje keli dilatuoti kanaliukai užpildyti kribrifominių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais, nežymiai polimorfiškais branduoliais.  2. Keturiuose limfmazgiuose iš šešių (4/6 l/m) žemiau aprašyto naviko metastazės iki 10 mm skersmens su ekstranodaliniu plitimu. Limfovaskulinis plitimas (LVI2). Papildomai (po fiksacijos) indentifikuotas limfmazgis su sinusų histiocitoze.  3. Krūties audinyje - hialinizuotoje stromoje 2 naviko židiniai (28 mm ir 5,5 mm mikroskopiškai) infiltratyviu augimo frontu, suformuoti gausių tubulinių, kribriforminių ir trabekulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma,  vidutiniškai polimorfiškais, hiperchromiškais branduoliais, nežymiai paryškėjusiais branduolėliais. Mitozių navike iki 10/10DPRL. Limfovaskulinė naviko invazija (LVI2). Greta naviko gausūs dilatuoti kanaliukai užpildyti solidinių ir kribrifominių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Krūties audinyje židininė fibrozė ir negausūs dilatuoti kanaliukai fokaliai kloti dvisluoksniu epiteliu su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   4. Trys limfmazgiai su sinusų histiocitoze.. Blokas 18:  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 15% naviko ląstelių. Karštame taške 25%.
answer:  0

 61%|██████    | 401/661 [06:06<03:54,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsiniai stulpeliai. Biopsinis stulpelis 15 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G1; 5 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%. Karštame taške 20%.. Krūties audinį 1-me bioptate infiltruoja iki 11 mm :   - trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 5% naviko ląstelių. Karštame taške 20%.  Progesterono rec
answer:  0

 61%|██████    | 402/661 [06:07<03:46,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  18 G automatine biopsine adata punktuoti didelių matmenų (>50 mm) navikiškai pakitę audiniai dešiniojoje  krūtyje nuo 6 val. iki 9 val. centrinėje-vidurinėje-periferinėje dalyse, paimti trys biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 9 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 7%.. Krūties audinį infiltruoja grandinėlės, trabekulės ar pabiros, vidutiniškai polimorfiškos ląstelės, mitozių iki 2/10 DPRL.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 7% naviko ląstelių.  Progesterono receptoriai: reakcijos n
answer:  0

 61%|██████    | 403/661 [06:08<03:40,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, ~9x5 mm dydžio darinys dešiniojoje krūtyje ties 3 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 7 mm; III - 5 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli netaisyklingi kribroziniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 8
answer:  0

 61%|██████    | 404/661 [06:09<03:42,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 3 biopsiniai stulpeliai iš ploto su mkk dešinėje krūtyje  2 but. 2 biopsiniai stulpeliai iš spikulinės deformacijos židinio prasiplėtusiais latakais kairėje krūtyje, BI-RADS 4c. 1. 3 biopsiniai stulpeliai: I - 19 mm; II - 14 mm; III - 16 mm.  2. 2 biopsiniai stulpeliai: I - 10 mm; II - 12 mm.. Dešinė  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.  Aukšto laipsnio intraduktalinė karcinoma (DCIS; solidinė ir komedo).  --------------  Kairė  N2: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%, vietomis iki 30%.. Dešinė  N1: Krūties audinyje dilatuoti kanaliukai su intraduktaliniais solidiniais polimorfiškų ląstelių proliferatais, vietomis su centrinėmis nekrozėmis. Invazinis solidinis tokių pačių polimorfiškų ląstelių židinys stromoje, mitozių 2/10 DPRL.  --------------  Kairė  N2: Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi solidiniai/kribroziniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. nan
answer:  0

 61%|██████▏   | 405/661 [06:10<03:36,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 9 mm; II - 4 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 25% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja pavienės duktalinės struktūros, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 25% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 2%.
answer:  0

 61%|██████▏   | 406/661 [06:10<03:35,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biospiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 5 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) lobulinė karcinoma. Krūties lobulinė karcinoma in situ (LCIS).   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.  Progesterono receptoriai: stipri (+++) reakcija, 50% naviko ląstelių.. 2/2 biopsiniuose stulpeliuose plinta fibrozinės stromos apsuptos trabekulinės, lizdinės struktūros, grandinėlės, suformuotos ląstelių negausia šviesiai eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar kiek netolygaus kontūro, hiperchromiškais ar vesikuolizuotais, vidutiniškai polimorfiškais branduoliais. Mitozių navike neidentifikuota. Šalia - latakai su solidiniais proliferatais iš navikui identiškų ląstelių.. Blokas 1:  CK5: mioepitelinio išklojimo navike nėra(-).   E-Cadherin: (-).  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 50% naviko ląstelių membranoje.  Ki67: reakcija branduol
answer:  10

 62%|██████▏   | 407/661 [06:11<03:45,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Sektorius skubus Ro tyrimas- MK pašalinti. N1 sektorius.  2(2a). Kraštai.  3(2b). Kraštai. - planinis patologinis tyrimas.. 1. Krūties sektorius 3,5x2,5x2 cm be odos, žymėtas viela. Vielos projekcijoje, neaiškių ribų, pilkšvas židinys 8x6x4 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm.  2. Riebalinio/ fibrozinio audinio fragmentas 1,5x0,6x0,3 cm. v/m   3. Riebalinio/ fibrozinio audinio fragmentas 1,5x1,2x0,4 cm. v/m. N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1a (3,3mm).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.  Vidutinio laipsnio papilinė intraduktalinė karcinoma DCIS/DIN2 (6mm židinys aplink invazinį naviką; krūties audinyje dar du, 6mm ir 3 mm, židiniai).  N2a: Žemo laipsnio kribriforminės intraduktalinės karcinomos 0,5mm židinys (DCIS/DIN1).  Rezekcijos kraštas be naviko.  N2b: Krūties audinys be naviko.. N1: Krūties audinyje 3,3mm invazinis navikas:  netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.  Aplink naviką 6mm plote  intraduktaliniai papiliniai vidutinio polimorfizmo ląstelių proliferatai; toliau nuo naviko du, 6mm ir 3mm tokios pačios struktūros intraduktaliniai priloferatai.  Rezekcijos kraštas be naviko.  N2a: Fibrozuotame krūties audinyje 0,5mm dilatuotas kanaliukas su kribroziniais intraduktaliniais neryškiai polimorfiškų ląstelių proliferatais be mioepitelinio sluoksnio.  Rezekcijos kraštas be naviko.  N2b: Krūties audinys be naviko.. Invazinis navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama (branduolių nusidažymas 2% naviko ląstelių).  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 40% navik
answer:  1

 62%|██████▏   | 408/661 [06:13<04:21,  1.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.  2(2b). Kraštai - skubus tyrimas - be naviko.  3(2). Dešinės pažastie sarginis limfmazgis - skubus tyrimas 6 l/m be naviko.  4(1). Dešinės krūties kvadrantas - planinis tyrimas.. 4(1). Krūties sektorius 13x7,5x4 cm su odos fragmentu 12,5x4,3 cm, žymėtas dviem vielomis ir vienu trumpu, vienu ilgu siūlu. I vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 1,3x1x0,7 cm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 3 cm. II vielos projekcijoje - naviką siekianti fibrozės zona, 5x4,5x3 cm, atstumas tarp vielų 3 cm. Odoje 4 rusvi, smulkiai gruoblėti dariniai iki 0,9x0,6x0,2 cm, vienas jų siekia rezekcijos kraštą.. 1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė, apokrininė metaplazija); be naviko.   2(2b, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija); kalcifikatai; be naviko.   3(2, ekstra). "Dešinės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (6 l/m).     4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma (su apokrininės diferenciacijos požymiais), SUMINIS TNM:   pT1b (navikas 9 mm) N0(sn) (0/6 l/m),   LVI-0 (definityvi limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.   HER2: reakcija neigiama (1+).   Androgenų receptoriai: stipri brand. r-ja, 100%.     Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė, gausūs apokrininės metaplazijos židiniai). Odos seborėjinė keratozė.. 1(2a, ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su apokrinės metaplazijos zonomis, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su apokrinės metaplazijos zonomis; smulkūs kalcifikatai; be naviko.   3(2, ekstra). "Dešinės pažasties sarginiai limfmazgiai": šeši (6) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4(1). NAVIKAS (mikroskopiškai - 9 mm; su aplinkine fibrozės zona ~12 mm židinys): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta besiliejančios kribriforminės ir dominuojančios trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai ar fokaliai ryškiau polimorfiškų ląstelių, gausia ryškiai eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su fokaliai ryškiomis nukleolėmis; mitozių iki 15/10 DPRL. Fokaliai naviko periferijoje kiek gausesnė perinavikinė limfocitinė infiltracija. Pavieniai mikrokalcifikatai. Fokaliai ryškesnės kolageninės fibrozės zonos (g.b. ankstenės biopsijos vieta).   APLINKA: šalia naviko - keli nedideli kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis ir "putotų" makrofagų intarpais. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis su papiliarizacija, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu.   ODOS DARINIAI: epidermio dariniai, kloti hiperplastišku, akantotišku, vietomis papiliarizuotu, hiperkeratotišku daugiasluoksniu plokščiu epiteliu, suformuotu iš bazaloidinių ląstelių su raginėmis cistomis, bazalinio epidermio sluoksnio hiperpigmentacija.  SEKTORIAUS REZEKCIJOS KRAŠTAS: naviko struktūros nutolusios - 1,3 mm.. 4(1). Navikas (blokas 18):  Androgenų receptoriai: stipri (+++) brand.r-ja 100%; GATA3: (+/++)(brand.r-ja)70%;   Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.
answer:  1

 62%|██████▏   | 409/661 [06:14<04:11,  1.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.N2A- kraštai - extra  2. 2B- kraštai --extra be naviko   3. (3) - sarginis - be naviko -extra  4. (1) sektorius - planis patologinis tyrimas  skubus rentgeninis tyrimas- navikas pašalintas. 4. Krūties sektorius 9,5x4x3 cm su odos lopu 10x3 cm, vienas kraštas žymėtas 2 trumpais siūlais, kitas kraštas - 1 trumpas, 1 ilgas. Pjūvyje pilkšvas, elastingas, gana aiškių ribų navikas 1,8x1,6x1,3 cm (sudėtas visas), nuo artimiausio (giliojo) rezekcijos krašto nutolęs 0,1 cm, nuo krašto, žymėtu 1 trumpu, 1 ilgu siūlu - 0,5 cm, nuo krašto, žymėtu 2 trumpais siūlais - 2,5 cm, odos – 1 cm.. 1. (2a) kraštai -extra: krūties audinys be patologinių pokyčių.  2. (2b) - kraštai -extra: krūties audinys be patologinių pokyčių.  3. Sarginiai l/m - extra: limfmazgis (1) be patologinių pokyčių.    4. Krūties sektorius. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma;  (G3; 9 b. pgl. Nottingham sist.) pT1c pLVI-0 pN0 pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama/žema raiška (1+).  Ki67: proliferacinis indeksas 85%.. 1. (2a) kraštai -extra: krūties audinys be patologinių pokyčių.  2. (2b) - kraštai -extra: krūties audinys be patologinių pokyčių.  3. Sarginiai l/m - extra: limfmazgis (1) be patologinių pokyčių.  4. Krūties sektorius. Krūties audinyje ribotą naviką formuoja:   - solidiniai kompleksai;  - stambių ląstelių su ryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 20/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.  Navike gausi limfoplazmocitinė infiltracija.. nan
answer:  1

 62%|██████▏   | 410/661 [06:15<04:03,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 11,5x7x5 cm su oda 11x4cm. Pjūvyje - pilkšvas, standus neaiškių ribų navikas 12x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 1,2 cm, nuo odos - 1,7 cm. Naviko projekcijoje krūties audinys fibrozuotas 5x3 cm plote.. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).   4. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma, SUMINIS TNM: pT1c(12 mm navikas) N0(sn)(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Perineurinė invazija. Radikalus pašalinimas.   Naviko imunotipas atliktas biopsijoje (žr.pastabą).. 1(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 3 limfmazgiai su I/II folikulais, fokaline parakortekso hiperplazija, sinusų histiocitoze ir lipomatoze.  4. Krūties audinyje - desmoplastiškoje stromoje, infiltratyviu frontu plintantis navikas, suformuotas solidinių kompleksų, trabekulių, negausių tubulių (<10 %). Naviko ląstelės su negausia, eozinofiliška citoplazma, smulkiais ar vidutinio kalibro, ovoidiškais, hiperchromiškais, vidutiniškai polimorfiškais branduoliais. Mitozių navike iki 75/10 DPRL. Naviko centre plati kolagenizuotos fibrozės zona; periferijoje - pigmentuotų makrofagų židiniai (biopsijos vieta). Naviko plitimas latakų spindžiuose ir perineuriškai.. CD31+ endotelizuotose ertmėse naviko plitimo neidentifikuota.
answer:  0

 62%|██████▏   | 411/661 [06:16<04:00,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2A) - kraštai - be naviko   2(N2b) - kraštai - be naviko  3(N3) - sarginiai l/m- be naviko  4(N1) - sektrorius su dalimi m. pectoralis major sin - planinis tyrimas. 4. Riebalinio audinio fragmentas 6x4,5x5,5 cm, su raumeniniu audiniu 2,5x2,3 cm plote (žymėtu siūlu). Pjūvyje balkšvas, standus, aiškių ribų navikas 25x19x25 mm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo raumens rezekcijos krašto - 0,5 cm.. PAPILDYTA  1(N2A). Nežymi fokalinė krūties audinio fibrozė.  2(N2b). Nežymi fokalinė krūties audinio fibrozė.  3(N3). Reaktyvi limfadenopatija (1 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenocarcinoma, TNM (Nr.1-Nr.4): pT2(2,5 cm) pN(sn)0 (0/1 l/m). LVI0(limfovaskulinės naviko invazijos nėra).     Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: ribinė (2+).  Ki67: 5%.  ---  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).. 1(N2A). Krūties audinyje - negausūs smulkūs fibrozės židiniai su negausiais smulkiais kanaliukais, išklotais dvisluoksniu epiteliu.   2(N2b). Krūties audinyje - negausūs smulkūs fibrozės židiniai su negausiais smulkiais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N3). Sinusų histiocitozė viename (1) limfmazgyje.  4(N1). Krūties audinyje - navikas; solidines, trabekulines, negausias smulkias kribrozines ar susiliejančias duktalines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 3 / 10 DPRL; menkai ląstelinga /fibrozinė stroma centrinėje naviko dalyje.. 4(N1). Navikas (10 blokas): Her2 silpna ištisinė membraninė r-ja 20% naviko ląstelių; Ki67 5%.
answer:  1

 62%|██████▏   | 412/661 [06:17<04:11,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. du sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 7x3,5x6 cm, su odos lopu 6,5x2,5 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 7x7x5 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 2,3 cm.. 1(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (atipinė duktalinė hiperplazija); kalcifikatai.   2(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).    3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).   4. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,    SUMINIS TNM:   pT1b (navikas 7 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis tipas).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, sklerozuojanti adenozė, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).. 1(ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija; kalcifikatai.   2(ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar hiperplastišku epiteliu; keli su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS); be naviko.   3(ekstra). "Sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės, kribriforminės ir nedidelės lizdinės naviko struktūros, suformuotos saikingai ar vidutiniškai polimorfiškų ląstelių, negausia šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozės retos, sunkiai vizualizuojamos. Smulkūs mikrokalcifikatai. Rezekcijos kraštas ties naviku "fragmentuotas", patikimai vizualizuojamos zonos be naviko.   APLINKA: šalia naviko - kribriforminiai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu.. 1(ekstra). "Kraštai"(8 blokas):   CK14(+) mioepitelinis sl.  4. Navikas (17 blokas):   HER2: silpna (+) necirkuliari reakcija, 20% naviko ląstelių membranoje.
answer:  0

 62%|██████▏   | 413/661 [06:17<03:52,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1  biopsinis  stulpelis. Biopsinis stulpelis 9 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 10%.. Krūties audinį infiltruoja pavienės duktalinės struktūros, nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 95% naviko ląstelių.  Ki67+ 10%
answer:  1

 63%|██████▎   | 414/661 [06:19<04:13,  1.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštas - skubus tyrimas (invazyvus židinys)  2 ėminio aprašas: N2b kraštas - skubus tyrimas (invazyvus židinys)  3 ėminio aprašas: N3: kairės pažasties limfmazgiai - planinis tyrimas  4 ėminio aprašas: N4: papildomas kraštas - planinis tyrimas  5 ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas. 3. Riebalinio audinio fragmentai, bendras dydis 7,5x5x2 cm. Rasta 12 limfmazgių iki 2 cm.  4. Riebalinio audinio fragmentas 1,5x1x0,6 cm.  5(1). Krūties sektorius 15x8x3 cm, su odos lopu 14x4 cm, su įtrauktu speneliu. Pjūvyje pilkšvas, standus, neaiškių ribų navikas 30x22x14 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1 cm.. 1(2a, ekstra). "Kraštas": duktalinės karcinomos židinys (~0,85 mm skersmens).    2(2b, ekstra). "Kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   3. "Kairės pažasties limfmazgiai": duktalinės karcinomos metastazė keturiuose limfmazgiuose (mts 4/12 l/m; iki 8,5 mm skersmens).  4. "Papildomas kraštas": fibrozuotas riebalinis audinys; be naviko.     5(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT2(m) (du židiniai: I - 30 mm; II - 0,8 mm) N2a (mts 4/12 l/m; iki 8,5 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Perineurinis plitimas.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2:reakcijos nėra (0).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Naviko struktūros sektoriaus koaguliacijos zonoje (~0,4 mm atkarpoje).. 1(2a, ekstra). "Kraštas": žemiau, punkte Nr.5, aprašyto naviko židinys, 0,85 mm skersmens (gilesniuose planinio tyrimo pjūviuose židinys neišlieka).   2(2b, ekstra). "Kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ir hiperplastišku epiteliu; be naviko.   3. "Kairės pažasties limfmazgiai"(12): keturiuose (4) limfmazgiuose žemiau, punkte Nr.5, aprašyto naviko metastazės, iki  8,5 mm skersmens, su ekstranodaliniu plitimu.   4. "Papildomas kraštas": fibrozuotas brandus riebalinis audinys; be naviko.     5(1). SPENELIS: klotas hiperkeratotišku epidermiu su reaktyvia akantoze.   NAVIKAS (du židiniai: I - 30 mm; II - 0,8 mm):   krūties audinyje, fibrozinėje - desmoplastiškoje stromoje, infiltratyvios naviko struktūros, suformuotos pavienių ar nedideliais lizdais-trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio - stambaus kalibro, nereguliaraus kontūro branduoliais, pavienės smulkios duktulės; mitozių iki 8/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Perineurinis naviko plitimas.   Invazijos fronte kiek gausesnė limfocitinė infiltracija. Naviko centre ryški fibrozės zona.   APLINKA: šalia naviko - kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: navikų struktūros siekia koaguliacijos zoną (~0,4 mm atkarpoje).. 5(1). Navikas (blokas 21):  E-Cadherin(+++)(membr.r-ja)100%.   EMA(+/+++)(citopl.r-ja)100%.   HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 63%|██████▎   | 415/661 [06:19<03:49,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 7 mm.. Pokyčiai būdingi intracistinei papilinei karcinomai (traktuojama kaip In situ karcinoma).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.. Krūties audinyje papilinės/kribrozinės ir solidinės struktūros be išlikusio mioepitelinio sluoksnio, sudarytos iš vidutiniškai polimorfiško kubinio/cilindrinio epitelio.. nan
answer:  0

 63%|██████▎   | 416/661 [06:21<04:00,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai  - skubus tyrimas  2(N2b) kraštai  - skubus tyrimas  3(N3) dešinės pažasties sarginis limfmazgis - skubus tyrimas  4(N1) pašalintas dešinės krūties kvadrantas - planinis tyrimas  5(N4) papildomas kraštas - planinis tyrimas. 4. Krūties sektorius 12,5x5x4 cm su oda 12x3,5 cm, su speneliu. Spenelio projekcijoje - pilkšvas, standus, aiškių ribų navikas 20x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 0,9 cm.  5. Riebalinio audinio fragmentas 1,5x1x0,4 cm. v/m. Koreguotas atsakymas (Indas Nr. 5).  1(ekstra). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir papilinis tipai).  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) mikropapilinė karcinoma, SUMINIS TNM: pT1c(20 mm) pN0(sn)(0/1 l/m) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir papilinis tipai). Intraduktalinės papilomos.  5. Papildomas kraštas. Riebalinis fibrozinis audinys.  Imunofenotipas (biopsijoje):   Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 25%, vietomis iki 40%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu. Dilatuoti latakai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais. Stambus dilatuotas latakas su intraduktalinėmis, papilinėmis fibrovaskulinės stromos struktūromis, klotomis dvisluoksniu epiteliu.   2(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 1 limfmazgis su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Spenelis: normali histologinė struktūra.   Krūtyje - navikas (20 mm) ekspansyviu augimo frontu, suformuotas mikropapilinėmis struktūromis ir lizdais besidėstančių ląstelių vidutinio gausumo - gausia ryškia eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 12/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu. Stambus dilatuotas latakas su intraduktalinėmis, papilinėmis fibrovaskulinės stromos struktūromis, klotomis dvisluoksniu epiteliu.  5. Papildomas kraštas. Riebalinis fibrozinis audinys.  Imunofenotipas (biopsijoje):. Navikas:  EMA(++) fokaliai invertuota citop. r-ja.
answer:  100

 63%|██████▎   | 417/661 [06:22<04:14,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Suspitio CA mammae sin - extra.  1(2a). Kraštai (be naviko) - extra;  2(2b). Kraštai (be naviko) - extra;   3(1). Pašalintas markiruotas kaclinatų plotas iš kairės krūties žymėtas trimis vielomis  - planinis tyrimas;  4(3). Dešinės krūties žymėtas kvadrantas žymėtas - planinis tyrimas.. 3(1). Krūties sektorius 8,5x4,5x3cm be odos lopo, žymėtas trimis vielomis. Pjūvyje firbrozės zona 6x4x2,3cm, siekia rezekcijos kraštą.  4(3). Krūties sektorius 5x3x1,7cm su odos lopu 4x1,3cm žymėtas viela. Vielos projekcijoje fibrozės zona 3x1,5x1cm, fibrozės zonoje balkšvas, standus, aiškių ribų darinys (sudėtas visas) 0,7x,0,5x0,5cm, nuo artimiausio rezekcijos krašto nutolęs 0,2cm.. 1(2a). Kraštai. Krūties audinys be patologinių pokyčių.    2(2b). Kraštai. Krūties audinys be patologinių pokyčių.    3(1). Markiruotas kalcinatų plotas iš kairės krūties.  Krūtyje invazinė duktalinė karcinoma G2(6 b. pgl. Nottingham sist.);    pT1c(11 mm), pLVI-0 pR0(1,5 mm).   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 50% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.    Vidutinė intraduktalinė karcinoma, DCIS/DIN2, solidinio, tinklinio ir komedo tipo.  Krūties fibrocistiniai pakitimai.    4(3). Dešinės krūties kvadrantas.   Ribotas darinys: Intraduktalinė karcinoma žemo laipsnio (DCIS/DIN1, galimai adenomoje).  DCIS/DIN1 difuzinis plitimas audinyje ir operaciniame krašte, pR(is)1.   Krūties fibrocistiniai pakitimai.. 1(2a). Kraštai. Krūties audinys be patologinių pokyčių.    2(2b). Kraštai. Krūties audinys be patologinių pokyčių.    3(1). Markiruotas kalcinatų plotas iš kairės krūties.   Krūties fibrozuotame audinyje infiltruoja iki 11 mm trabekulinės struktūros (3 b.) su vidutiniu ląstelių branduolių polimorfizmu (2 b.) ir mitozėmis iki 3/10DPRL (1 b.). Šios infiltracinės struktūros 1,5 mm nuo operacinio krašto. Intralimfatinis / Intravaskulinis plitimas nestebimas.  Analogiškų ląstelių intraduktalinės solidinės, tinklinės struktūros ar su  nekroze, apima >25% naviko ploto ir plinta už invazyvaus naviko ribų apie 15 mm; stebimos 0,5 mm nuo operacinio krašto.  Aplinkui - audinio fibrozė, smulkių kanaliukų proliferacijos židiniai, cistinė kanaliukų dilatacija, kanaliukų epitelio apokrininė metaplazija.    4(3). Dešinės krūties kvadrantas.  Ribotas darinys suformuotas su netaisyklingais įvairaus dydžio nekompaktiškai besidėstančiais latakais, išklotais stulpiniu epiteliu stratifikuotais branduoliais su nežymia atipija.  Analogiškų latakų difuzinis plitimas audinyje ir židiniškai operaciniame krašte.  Audinio fibrozė, smulkių kanaliukų proliferacijos židiniai, cistinė kanaliukų dilatacija, kanaliukų epitelio apokrininė metaplazija.. Nr. 3(kairės krūties).  Blokas 5:  CK14: neigiama (-) atipinių difuziškai plintančių struktūrų ląstelių membranoje  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląst
answer:  1

 63%|██████▎   | 418/661 [06:23<03:56,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 stulpeliai histologinės medžiagos. 3 fragmentuoti biopsiniai stulpeliai: I - 11 mm; II - 9 mm; III - 5 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%, vietomis iki 10%.. Krūties audinį infiltruoja netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  0

 63%|██████▎   | 419/661 [06:24<04:11,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštas  - skubus tyrimas - be naviko  2 ėminio aprašas: N2b kraštas  - skubus tyrimas - be naviko  3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - skubus tyrimas - viename iš trijų limfmazgių 3mm makrometastazė  4(1) ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas. 4(1). Krūties sektorius 11x8x4 cm su odos lopu 10x3 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje - balkšvas standus, spikulinis navikas 0,8x0,7x0,6 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,5 cm, nuo odos nutolęs 2 cm.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos metastazė limfmazgyje (mts 1/3 l/m; iki 3 mm skersmens).    4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,  SUMINIS TNM:   pT1b (navikas 8 mm) N1a(sn) (mts 1/3 l/m; iki 3 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti ir mikroglandulinė adenozė,   stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).   Sektoriaus rezekcijos kraštas be naviko.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai"(3): viename (1) limfmazgyje žemiau, punkte Nr.4, aprašyto naviko metastazės, 3 mm skersmens, be ekstanodalinio plitimo.   4. NAVIKAS: krūties audinyje, fibrozuotoje-elastozinėje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retos duktalinės, gausesnės kribriforminės, trabekulinės, lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 1/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Nedideli MMN infiltracijos židiniai. Pavieniai mikrokalcifikatai.  APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti, kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.. 4. Navikas (blokas 14):  HER2: silpna (+) necirkuliari reakcija, 20% naviko ląstelių membranoje.
answer:  0

 64%|██████▎   | 420/661 [06:25<04:01,  1.00s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2: dešinės pažasties sarginis limfmazgis 1l/m - extra  2 ėminio aprašas: N1: pašalinta dešinė krūtis -  planinis tyrimas. 2(1). Krūtis 1010 gramų svorio, 23x16x5 cm, spenelis kiek įtrauktas. Krūties audinyje, spenelio projekcijoje - pilkšvas, standus, neaiškių ribų navikas 43x20x14 mm, nuo giliojo rezekcijos krašto nutolęs 4 cm, nuo odos - 0,8 cm.. 1(2). Duktalinės karcinomos mikrometastazės limfmazgyje (1/1 l/m; iki 1,93mm).  2(1). Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 43mm) pN1mi(sn)(1/1 l/m; iki 1,93mm); LVI-2 (Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).  IHC reakcijos atliktos VPC:B23-4377 tyrime:  "Estrogenų receptoriai: vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%.". 1(2). Vienas(1) limfmazgis su žemiau aprašyto naviko metastazėmis (iki 1,93mm).  2(1). Krūties audinyje - navikas, formuojamas trabekulinių struktūrų, smulkių agregatų, pavienių netaisyklingų liaukinių/kribriforminių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, nežymiai, vietomis vidutiniškai polimorfiškais branduoliais; navike iki 3 mitozių/10 DPRL. Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse. Spenelis be histologinių patologinių pokyčių.. 1(2). Blokas 2:  Naviko metastazės limfmazgyje:   PANCK(+++), membr. r-ja, 100%.   2(1). Blokas 19:  Navikas:  E-Cadherin(+++), membr. r-ja, 100%;   P120(+++), membr. r-ja, 100%.
answer:  1

 64%|██████▎   | 421/661 [06:25<03:44,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 10 mm; II - 9 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 50% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 7%.. Krūties audinį infiltruoja duktalinės struktūros (<10%), netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) cirkuliari reakcija, 20%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 7% naviko ląstelių.  Progesterono receptoriai: vidutinė
answer:  0

 64%|██████▍   | 422/661 [06:26<03:34,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 N2a -kraštai -extra  2. N2b kraštai  skubus tyrimas - be naviko  3: dešinės pažasties sarginis limfmazgis - skubus tyrimas 3 l/m be naviko  4. (1) pašalintas dešinės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 15,5x8x5,5 cm, su odos lopu 12,5x4 cm, žymėtas viela. Ant odos rusvas, smulkiai papiliarizuotas, iškilęs darinys 1,7x1,2x0,3 cm, nuo odos rezekcijos krašto nutolęs 0,2 cm. Krūties audinyje, vielos projekcijoje pilkšvas, mazgotas, aiškių ribų navikas 15x16x16 mm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos nutolęs 3cm.. N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(16mm).  N2ab: Audiniai be naviko.  N3: Limfmazgiai (3 l/m) be naviko; pN0(sn).. N1: Krūties audinyje 16mm navikas: netaisyklingi solidiniai kompleksai ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.  N2ab: Audiniai be naviko.  N3: Limfmazgiai (3 l/m) be naviko.. nan
answer:  0

 64%|██████▍   | 423/661 [06:27<03:26,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 13 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki  mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 35%. Karštame taške 50%.. Krūties audinį 2-se bioptatuose infiltruoja iki 11 mm :   - solidiniai kompleksai;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais gausioje eozinofilinėje citoplazmoje;   - mitozės nestebimos.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  CD56 : stipri teigiama (+++)   membraninė reakcija 3 proc. atipinėse ląstelėse  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių
answer:  0

 64%|██████▍   | 424/661 [06:28<03:20,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 6 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma. Mikrokalcinatai.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 15%.. Bioptatuose (2/2) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 2/10 DPRL. Mikrokalcinatai.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 95%.  HER2: silpnas/vidutinis dalies membranos nusidažymas 30% naviko ląstelių., foninė citopl. r-ja.  Ki67 proliferacinis aktyvumas 15%.  E-cadherin(+
answer:  10

 64%|██████▍   | 425/661 [06:29<03:24,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pjūvio kraštai - planinis;  2. Pjūvio kraštai - planinis;  3. Sarginiai l/m - planinis;  4. Sektorius - planinis.. 1. Riebalinio fibrozinio audinio fragmentas 3,8x2,5x0,6 cm. v/m  2. Riebalinio fibrozinio audinio fragmentas 3,5x2,2x0,5 cm. v/m  3. Riebalinio audinio fragmentai, bendras dydis 3x2,6x0,6 cm. Rasti 2 limfmazgiai iki 1 cm.  4. Krūties sektorius 16,5x10x4 cm su odos lopu 17x3,5 cm, žymėtas 2 vielomis:  - I vielos projekcijoje, pjūvyje balkšvas, standus, neaiškių ribų navikas 1x1x0,8 cm, nuo artimiausio rezekcijos krašto nutolęs 1,3 cm, nuo odos – 2 cm.  - II vielos projekcijoje, pjūvyje balkšvas, standus, neaiškių ribų navikas 1,3x1x1 cm, nuo I viela žymėto naviko nutolęs 2,5 cm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos – 2,5 cm.. N1: Atipinė duktalinio epitelio hiperplazija.  N2: Krūties audinys be naviko.  N3: Viename limfmazgyje (1 iš 2 l/m) duktalinės karcinomos 3mm metastazė; pN1a (sn).  N4: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(m) (du navikai 10mm ir 13mm).. N1: Krūties audinyje dilatuoti kanaliukai su mikropapilinėmis ir arkinėmis struktūromis iš nežymiai polimorfiškų ląstelių, vietomis su miopitelinių ląstelių priemaiša.  N2: Krūties audinys be naviko.  N3: Viename limfmazgyje (1 iš 2 l/m) žemiau aprašyto naviko 3mm metastazė.  N4: Krūties audinyje du navikiniai židiniai (10mm ir 13mm): duktalinės struktūros, netaisyklingi solidiniai/kribroziniai kompleksai, trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. nan
answer:  0

 64%|██████▍   | 426/661 [06:30<03:30,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. deš. pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: 2. Deš. krūtis, planinis. 2. Krūtis 2050 gramų svorio, 31x22x8,5 cm. Krūties audinyje:  - apatinių kvadrantų riboje - balkšvas, standus neaiškių ribų I navikas 8x6x6 mm, nuo odos nutolęs 1 cm, nuo giliojo rezekcijos krašto - 6 cm;  - nuo I naviko 1,7 cm atstumu - balkšvas, standus neaiškių ribų II navikas 5x4x3 mm, nuo odos nutolęs 1,5 cm, nuo giliojo rezekcijos krašto - 5,5 cm;  - nuo II naviko 2,5 cm atstumu, vidiniame medialiniame kvadrate - balkšvas, standus neaiškių ribų III navikas 3x3x3 mm, nuo odos nutolęs 3 cm, nuo giliojo rezekcijos krašto - 4,5 cm;  - nuo III naviko 2 cm atstumu, vidiniame medialiniame kvadrate - balkšvas, standus neaiškių ribų IV navikas 5x4x4 mm, nuo odos nutolęs 3,5 cm, nuo giliojo rezekcijos krašto - 3,5 cm, nuo I naviko - 4 cm;  - apatiniame lateraliniame kvadrante - pilkšvas, standus aiškių ribų V navikas 5x4x4 cm, nuo odos nutolęs 2 cm, nuo giliojo rezekcijos krašto - 5 cm.  Bendras didžiausias visų navikų matmuo - 7 cm.. N1-2: Krūties daugiažidininė karcinoma:  trys židiniai (8mm, 5mm ir 5mm) gerai difencijuotos (G1, 4 balai pagal Nottingham) duktalinės karcinomos;  du židiniai (3mm ir 2mm) gerai difencijuotos (G1, 5 balai pagal Nottingham) lobulinės karcinomos;  pT1b(m); pN1a(sn) (10mm metastazė ir duktalinės ir lobulinės karcinomos).. N1: Iš į parafiną įlietos limfmazgio medžiagos po IHC tyrimo išryškėjo 10mm metastazė iš duktalinių struktūrų ir difuziškai plintančių ECAD negatyvių ląstelių.  N2: Krūties audinyje 3 navikai 8mm, 5mm ir 5mm iš duktalinių ir kribrozinių neryškiai polimorfiškų ląstelių struktūrų;  2 navikai 3mm ir 2mm iš juostų ECAD neigiamų neryškiai polimorfiškų ląstelių.  Rezekcijos kraštas be naviko.. nan
answer:  0

 65%|██████▍   | 427/661 [06:30<03:20,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsiniai stulpelis 13 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 100% naviko ląstelių.  Ki67+ 20%.
answer:  0

 65%|██████▍   | 428/661 [06:32<04:11,  1.08s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.1a- viršutinis kraštas (deš.krūtis), skubu  2.1b- apatinis kraštas (deš. krūtis), skubu  3.(2). Deš. pažasties sarginiai limfmazgiai, skubu  4.(4a) - viršutinis kraštas (kairė krūtis), skubu  5.(4b)- apatinis kraštas (kairė krūtis), skubu  6.(5) - Kairės pažasties sarginiai limfmazgiai, planas  7.(3)- deš. krūties kvadrantas, planinis  8.(6) - Kairės krūties kvadrantas, planinis  9.(7) - papildomas k.kruties viršut.kraštas-planas  10.(8) - papildomas d.krūtis apat.kraštas-planas. 6(5). Riebalinio audinio fragmentas 5,5x2,5x1,3 cm. Rastas limfmazgis 3 cm.   7(3). Krūties sektorius 13,5x6,5x3 cm su odos lopu 8,5x3,5 cm, žymėtas dvejomis vielomis. Vienos vielos projekcijoje neaiškių ribų, standi fibrozės zona su prasiplėtusiais tarpais 21x9x7 mm, nuo giliojo rezekcijos krašto nutolusi 0,3 cm, nuo odos - 2,5 cm. Kietos vielos projekcijoje 2 intramamariniai limfmazgiai iki 0,5 cm skersmens. Fibrozės zona vielos projekcijoje sudėta visa.   8(6). Krūties sektorius 9x6x2,2 cm, be odos, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 21x18x11 mm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm.  9(7). Riebalinio/fibrozinio audinio fragmentas 2,5x1x0,4 cm. v/m  10(8). Riebalinio audinio fragmentas 3x1,3x0,5 cm. v/m. 1(extra). Viršutinis kraštas, dešinė. Fibrocistiniai pokyčiai.  2(extra). Apatinis kraštas, dešinė. Krūties žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1, kribriforminis tipas).  3(extra). Sarginiai limfmazgiai, dešinė. Reaktyvi limfadenopatija (4 l/m).    4(extra). Viršutinis kraštas, kairė. Fibrocistiniai pokyčiai.  5(extra). Apatinis kraštas, kairė. Fibrocistiniai pokyčiai.  6. Kairės pažasties sarginiai limfmazgiai (planinis). Duktalinės karcinomos metastazė (1/1 l/m, 4,4 mm).    7. DEŠINĖ. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) multižidininė, mikroinvazyvi duktalinė karcinoma, SUMINIS TNM: pT1mi(m)(0,4 mm, 0,5 mm, 0,9 mm, 1 mm) pN0(sn)(0/6 l/m0 LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 DIN1 DIN2, kribriforminis, solidinis, komedo ir papilinis tipai), DCIS židinys iki 2 cm. R0(radikali rezekcija).  Imunofenotipas (biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.    8. KAIRĖ.  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(21 mm navikas) pN1a(sn)(MTS 1/1 l/m 4,4 mm) LVI-2(limfovaskulinė invazija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas). R0(radikali rezekcija).  Imunofenotipas (biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%, vietomis iki 30%.    9. Papildomas kairės krūties viršutinis kraštas. Fibrocistiniai pokyčiai.   10. Papildomas dešinės krūties apatinis kraštas. Fibrocistiniai pokyčiai.. 1(extra). Viršutinis kraštas (deš.krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  2(extra). Apatinis kraštas (deš. krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu. Fokaliai latakų grupė su intraduktaliniais kribriforminiais proliferatais iš ląstelių nežymiai polimorfiškais brnaduoliais.   3(extra). Sarginiai limfmazgiai, dešinė. 4 limfmazgiai su sinusų histiocitoze, lipomatoze ir pirminiais bei antriniais folikulais.  4(extra). Viršutinis kraštas (kairė krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  5(extra). Apatinis kraštas (kairė krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  6. Kairės pažasties sarginiai limfmazgiai. Vienas limfmazgis su metastaze, 4,4 mm suformuota susiliejančių tubulinių struktūrų.  7. DEŠINĖ. Krūtyje - navikas (0,4 mm, 0,5 mm, 0,9 mm, 1 mm židiniai) suformuotas lizdais besidėstančių ląstelių gausia eozinofiliška, ryškia citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 1/10 DPRL.  Greta gausūs dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais ir solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.   2 limfmazgiai su sinusų histiocitoze ir antriniais folikulais.  8. KAIRĖ. Krūtyje - navikas (21 mm) infiltratyviu ekspansyviu frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais branduoliais ryškiomis nukleolėmis; mitozių 4/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais ir solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.   Limfovaskulinė naviko invazija.  9. Papildomas k.kruties viršutinis kr. Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.    10. Papildomas d.krūtis apatinis kr. Krūties audinys su kanaliukais, klotais dvisluoksniu ir hiperplastišku epiteliu su apokrinine metaplazija. Ryškūs koaguliacijos artefaktai.. 2. DCIS (3 blokas): C14 išlaikytas mioepitelinis sluoksnis.  7. Navikas (32, 35 blokai): Ck14(-).
answer:  0

 65%|██████▍   | 429/661 [06:33<03:53,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 buteliukas - 3 biopsiniai stulpeliai.  2 buteliukas - 2 biopsiniai stulpeliai.. 1. 3 biopsiniai stulpeliai: I - 13 mm; II - 7 mm; III - 14 mm.  2. 2 biopsiniai stulpeliai: I - 12 mm; II - 10 mm.. 1. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G1; 5 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 7%.    2. Fibroepiteliniai pokyčiai, gali būti suderinami su krūties fibroadenoma.. 1. Krūties audinį 3-se bioptatuose infiltruoja iki 11 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.    2. Ribotas navikas, suformuotas kompaktiškos fibrozinės stromos su pavieniais suspaustais latakais, klotais dvisluoksniu epiteliu.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 50%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 7% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  80

 65%|██████▌   | 430/661 [06:34<03:53,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1- skubi histologija - retroareoliarinė sritis - be naviko   N2-sarginis l/n  - be naviko   N3- pašalinta krūtis - planinis tyrimas - skubus rentgeninis tyrimas - 4 cm MK plotas pašalintas. 3. Krūties sektorius 13,5x9x3,5 cm su odos lopu 6x3 cm. Krūties audinyje, pjūvyje pilkšvas, neaiškių ribų židinys 6x5x5 mm (žymėtas kabute), nuo giliojo rezekcijos krašto nutolęs 0,3, nuo odos - 2,6 cm.. 1(Extra). Krūties audinys.  2(Extra). Reaktyvi limfadenopatija (2 l/m). Nodalinis nevocitinis nevusas 1 limfmazgyje.   3. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(6 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio ir žemo laipsnio duktalinė karcinoma in situ (DIN1c/DIN2/DCIS)(kribriforminė, komedo). DCIS struktūros 0,1 mm nuo sektoriaus   rezekcijos krašto.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  2(Extra). 2 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze. Vieno limfmazgio kapsulėje - negausūs lizdais besidėstantys nevocitai švelniai eozinofiliška citoplazma, ovaliais/apvaliais, monomorfiškais branduoliais.  3. Krūties audinyje - ribotas navikas (mikroskopiškai 6 mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių struktūrų, grandinėlėmis ar pabirai besidėstančių ląstelių saikinga vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, smulkiais ar vidutinio kalibro, apvaliais/ovaliais, gan monomorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 1/10 DPRL. Aplink gausūs dilatuoti kanaliukai su kribriforminiais intraduktaliniais proliferatais, suformuotais ląstelių šviesiai eozinofiliška citoplazma, vidutinio kalibro, kiek polimorfiškais, dalis su nukleole branduoliais; negausios komedo nekrozės ir kalcifikatai dalyje kanaliukų. DCIS struktūros 0,1 mm nuo žymėto rezekcijos krašto.  Aplinkiniame krūties audinyje grupės dilatuotų kanaliukų su apokrinine metaplazija.. 2. Limfmazgis (6 blokas): nevocitų lizdai SOX-10+; Cam5.2(-).
answer:  0

 65%|██████▌   | 431/661 [06:35<03:40,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 8 mm; II - 10 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 8 mm);  (G1; 3 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 8%.. Krūties audinį 2-se bioptatuose infiltruoja iki 8 mm :   - duktalinės struktūros (95% viso naviko), netaisyklingi kribroziniai kompleksai;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 8% naviko ląstelių.  Progesterono receptoriai: stipri (+++
answer:  100

 65%|██████▌   | 432/661 [06:36<03:34,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, ~21×17 mm dydžio darinys kairiojoje krūtyje ties 3 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai (I buteliukas).   2 ėminio aprašas: 2. 18 G automatine biopsine adata punktuotas hipoechogeninis plotas kairiojoje krūtyje ties 2 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai (II buteliukas).. 1. 3 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 14 mm; III - 7 mm.  2. 3 fragmentuoti biopsiniai stulpeliai: I - 15 mm; II - 15 mm; III - 7 mm.. N1: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.  N2: Ryški krūties audinio fibrozė, vienas fragmentuotas žemo laipsnio intraduktalinės karcinomos mikrožidinys (0,5mm).. N1: Krūties audinį infiltruoja smulkios duktalinės struktūros, negausūs netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  N2: Ryški krūties audinio fibrozė, vienas fragmentuotas žemo laipsnio intraduktalinės mikrožidinys (0,5mm).. N1 navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  0

 66%|██████▌   | 433/661 [06:36<03:24,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~45×33 mm dydžio darinys dešiniojoje ties 6 val. centrinėje dalyje, peraugantis odą ir raumenis, paimti 3 biopsiniai stulpeliai histologijai.. 3 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 12 mm; III - 17 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%. Karštame taške 15%.. Krūties audinį ir skersaruožių raumenų skaidulas infiltruoja trabekulės, solidiniai kompleksai, duktalinės struktūros (5%) iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki6
answer:  5

 66%|██████▌   | 434/661 [06:38<03:55,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - Viršutinis kraštas  2 - Apatinis kraštas  3 - Sarginiai l/m 1-2-3 ekstra  4 - Kvadrantas. 4. Krūties sektorius 7x5x3,5 cm. Atskirai tame pačiame inde 2 riebalinio audinio fragmentai: I - 3,5x2x1,3 cm, II - 1,8x0,8x0,5 cm. Pjūvyje gelsvas, neaiškių ribų navikas 16x15x13 mm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm. 0,2 cm nuo naviko hemoragijos zona 1,1x0,8x0,8 cm. 0,9 cm nuo naviko cista 0,8x0,5x0,6 cm, lygia sienele, nuo artimiausio rezekcijos krašto nutolusi 0,1 cm.. 1(ekstra). "Viršutinis kraštas": krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija); kalcifikatai; be naviko.   2(ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija, sklerozuojanti adenozė); kalcifikatai; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (1 l/m).   Fibrozuoto krūties audinio fragmentas su židininiais fibrocistiniais pokyčiais: tikėtina pridėtinė krūtis, tikslinga klinikinė koreliacija.     4. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1b (navikas 9,63 mm) N0(sn) (0/1 l/m),   LVI-0 (definityvi limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija, sklerozuojanti adenozė).. 1(ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu ar fokaliai hiperplastišku, fokaliai nežymiai atipišku epiteliu, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), apokrininės metaplazijos zonos; kalcifikatai; be naviko.   2(ekstra). "Apatinis kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu ar fokaliai hiperplastišku atipiniu epiteliu, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS); suspaustų kanaliukų zonos; kalcifikatai; be naviko.   3(ekstra). "Sarginiai limfmazgiai": vienas (1) limfmazgis su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais. Atskiras krūties audinio fragmentas su ryškia kolagenine fibroze ir kanaliukais bei lobulėmis, klotomis dvisluoksniu epiteliu; nedidelis židinys su cistiškai dilatuotais kanaliukais su sekreto lobulėlis, supamomis histiocitais.   4. NAVIKAS (mikroskopiškai didžiausias naviko matmuo - 9,63 mm; su aplinkine fibroze ~16 mm skersmens židinys): krūties audinyje, fibrozuotoje, kiek lobulizuotoje, kolagenizuotoje desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės/tubulinės ir retos kribriforminės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, negausia ar vidutinio gausumo šviesia eozinofiliška citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozės pavienės, retos. Šalia fibrozuoti riboti židiniai su "putotais" makrofagais (g.b. ankstesnės biopsijos vieta). Negausi intranavikinė limfocitinė infiltracija. Pavieniai kalcifikatai.   APLINKA: šalia naviko - kribriforminiai intraduktaliniai naviko ląstelių proliferatai, fokaliai su centrinės nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu su papiliniais proliferatais ir židinine atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu.   Eritrocitų ekstravazacijos zonos tarp lipocitų, šalia fibrozės zonos su gausesne MMN infiltracija.   SEKTORIAUS REZEKCIJOS KRAŠTAS: invazyvaus naviko struktūros nutolusios 3,5 mm.. 4. Navikas (blokas 13):  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląstelių membranoje.
answer:  1

 66%|██████▌   | 435/661 [06:39<03:50,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1a- viršutinis kraštas, skubu  2 ėminio aprašas: 1b- apatinis kraštas, skubu  3 ėminio aprašas: deš. krūties sektorius su limfmazgiais, planinis. 3(2). Krūties sektorius 9x4,5x4 cm su odos lopu 8,5x2,4 cm. Pjūvyje balkšvas, standus, neaiškių ribų navikas 16x14x11 mm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos – 2,3 cm. Atskirai tame pačiame inde - riebalinio audinio fragmentas/pa=asties narveliena (8x6x2 cm, su 17 limfmazgių iki 1,3 cm).. 1(1A). Krūties fibrocistiniai pokyčiai.  2(1B). Krūties fibrocistiniai pokyčiai.  3(2). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, pT1c(1,6 cm) pN1a(2/17 l/m, mts 0,4 cm ir 0,5 cm). LVI2(limfovaskulinė invazija, smulkiose struktūrose).     Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 20% (hot spot 30%).. 1(1A). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2(1B). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(2). SEKTORIUS: Navikas (solidines, trabekulines, kribrozines, smulkias tubulines naviko struktūras formuoja ląstelės su kiek gausesne tamsoka eozinofiline citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 13 / 10 DPRL.  PAŽASTIES NARVELIENA: Aukščiau aprašyto naviko metastazės limfmazgiuose (dviejuose (2) iš septyniolikos (17), metastazės 0,4 cm ir 0,5 cm).. 3(2). Navikas (3 blokas):  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: nusidaži
answer:  10

 66%|██████▌   | 436/661 [06:40<03:32,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 13 mm; II - 12 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.. Krūties audinį infiltruoja duktalinės struktūros ir trumpos juostos iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 2%
answer:  0

 66%|██████▌   | 437/661 [06:40<03:21,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: k.krūtis, k. pažasties l/m - planiniam tyrimui. Krūtis 20x15x9 cm, su pažasties narveliena 8x5x2,6 cm. Krūties audinyje pilkšvas, ribotas navikas 12x11,5x5,5 cm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm. Navikas išopėjęs odoje 11x6 cm plote. Rasti 8 limfmazgiai, didžiausias 4,5 cm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b(12cm, išopėjimas); pN2a (4 iš 8 l/m).  Krūties ir pažasties audinių nekrozė, uždegiminė infiltracija su abscesais.. Krūties audinyje išopėjęs 12cm navikas: susiliejantys kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL. Navike ir aplinkiniame krūties audinyje nekrozės zonos su gausia uždegimine infiltracija.  Iš rastų 8 limfmazgių 4 su metastazėmis iki 4,5cm. Pažasieties audiniuose gausi uždegiminė infiltracija su abscesais.  Operacinis pjūvis be naviko.. nan
answer:  0

 66%|██████▋   | 438/661 [06:41<03:16,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas dešinės krūties kvadrantas - planinis tyrimas  2 ėminio aprašas: N2a kraštai  planinis tyrimas  3 ėminio aprašas: N2b kraštai  planinis tyrimas  4 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis - planinis tyrimas. 1. Krūties sektorius 10x5x4,5 cm su odos lopu 9x3,5 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus navikas 11x9x8 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,5 cm.   2. Riebalinio audinio fragmentas 2,5x1,5x0,6 cm. v/m   3. Riebalinio audinio fragmentas 3,3x1,4x0,5 cm. v/m   4. Riebalinio audinio fragmentai, bendras dydis 2x1,7x1 cm. Rastas limfmazgis 1,2 cm.. N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(11mm).  N2a-2b: Krūties ir riebalinio audinio fragmentai be naviko.  N3: Limfmazgis be naviko metastazių; pN0(sn).. N1: Krūties audinyje 11mm navikas: negausios duktalinės struktūros, nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.  N2a-2b: Krūties ir riebalinio audinio fragmentai be naviko.  N3: Limfmazgis su reaktyviais pokyčiais, be naviko metastazių.. nan
answer:  0

 66%|██████▋   | 439/661 [06:42<03:19,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 but. 2 biopsiniai stulpeliai iš kairės krūties BI-RADS 4c darinio  2 but. 3 biopsiniai stulpeliai iš dešinės krūties BI-RADS 5 darinio. 1. 2 biopsiniai stulpeliai: I - 15 mm; II - 14 mm.  2. 3 fragmentuoti biopsiniai stulpeliai: I - 6 mm; II - 1 mm; III - 2 mm.. 1. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G2; 7 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    2. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 3 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se navikinio audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.. 1. Krūties audinį 2-se bioptatuose infiltruoja iki 13 mm :   - solidiniai kompleksai ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su ryškiai polimorfiškais branduoliais  negausioje bazofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.    2. Naviko audinį 3-se bioptatuose infiltruoja iki 3 mm :   - solidiniai kompleksai;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje bazofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 80%  naviko ląstelių mem
answer:  1

 67%|██████▋   | 440/661 [06:44<04:30,  1.22s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas  2(N2b) kraštai - skubus tyrimas  3(N3): kairės pažasties sarginis limfmazgis - skubus tyrimas - 2l/m be naviko  4(N5a) kraštai - skubus tyrimas  5(N5b) kraštai - skubus tyrimas  6(N6) dešinės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko  7(N7): papildomas kraštas iš kairės krūties - be naviko  8(N1): pašalintas kairės krūties kvadrantas - planinis tyrimas  9(N4): dešinės krūties kvadrantas - planinis tyrimas   10(N8): papildomas kraštas iš dešinės krūties - planinis tyrimas. 8. Krūties sektorius 15,5x8,5x5,5 cm su oda 14x5,5 cm. Krūties audinyje, pilkšvas standus, neaiškių ribų I navikas 10x8x8 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 2,5 cm, nuo odos - 2 cm. Virš I naviko krūties audinys fibrozuotas 3,5x1,7 cm su cistinėmis ertmėmis iki 0,5 cm, pakitimai nuo giliojo rezekcijos krašto nutolę 0,1 cm. Nuo I naviko 2 cm atstumu - pilkšvas standus II navikas 12x6x6 mm(sudėtas visas), nuo giliojo rezekcijos krašto 3 cm, nuo odos 1,8 cm.   9. Krūties sektorius 20x6,5x8,5 cm su oda 19x4 cm. Krūties audinyje, pilkšvas, standus, aiškių ribų I navikas 14x8x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 4,5 cm. 6cm nuo I naviko - pilkšvas, standus, neaiškių ribų II navikas - 23x10x10 mm (sudėtas visas), nuo giliojo rezekcijos krašto 0,3 cm, nuo odos 3,5 cm. Tarp navikų krūties audinys fibrozuotas 4,5x4 cm plote.  10. Riebalinio audinio fragmentas 1x0,8x0,4 cm. v/m. 1.(2a)(kairė). Krūties audinys; pavieniai intraduktaliniai mikrokalcifikatai.  2.(2b)(kairė). Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas). Lobulinė krūties Carcinoma in situ (LCIS). Krūties fibrocistiniai pokyčiai.   3.(3)(kairė) Reaktyvi limfadenopatija (2 l/m).  4(N5a)(dešinė) Krūties audinys.  5(N5b)(dešinė) Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas). Lobulinė krūties Carcinoma in situ (LCIS). Krūties intraduktalinės papilomos. Krūties fibrocistiniai pokyčiai; paprasta intraduktalinė hiperplazija.   6(N6)(dešinė) Reaktyvi limfadenopatija (3 l/m).  7(N7)(pap. kraštas, kairė) Riebalinis audinys.  8(N1)(kairė) Krūties invazyvi, gerai diferencijuota (G1; 4 balai pagal Nottingham sis) duktalinė karcinoma su lobulinės karcinomos komponentu (~5% naviko), suminis tyrimo TNM: pT1c(m)(du naviko židiniai 16,7mm ir 10mm) pN0(sn)(0/2 l/m).   IHC reakcijos atliktos VPC:B23-29805 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%."  Krūties intraduktalinė karcinoma (DCIS; kribriforminis, mikropapilinis tipas). Lobulinė krūties Carcinoma in situ (LCIS). Intraduktalinės krūties papilomos. Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.  9(N4)(dešinė) Krūties invazyvi, gerai diferencijuota (G1; 4 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(m)(dauginiai naviko židiniai nuo 0,6mm iki 14mm) pN0(sn)(0/3 l/m).   IHC reakcijos atliktos VPC:B23-29805 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%."  Krūties žemo ir vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis, kribriforminis tipas; -komedo tipo nekrozėmis). Lobulinė krūties Carcinoma in situ (LCIS). Krūties intraduktalinės papilomos. Krūties fibrocistiniai pokyčiai; paprasta intraduktalinė hiperplazija.   10(N8)(pap. kraštas, dešinė) Krūties audinys.. 1.(2a)(kairė). Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu; pavieniai intraduktaliniai mikrokalcifikatai.  2.(2b)(kairė). Krūties audinyje - fibrozės zonos su fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu su apokrininės metaplazijos židiniais. Fokaliai dilatuoti latakėliai su kribriforminiais atipinių ląstelių (su nedidelio laipsnio branduolių polimorfizmu) proliferatais (DCIS). Dilatuoti latakai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS).   3.(3)(kairė) Du(2) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4(N5a)(dešinė) Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  5(N5b)(dešinė) Krūties audinyje - fibrozės zonos su fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu su apokrininės metaplazijos, paprastos intraduktalinės hiperplazijos židiniais; fokaliai dilatuoti latakėliai su fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu. Fokaliai dilatuoti latakėliai su kribriforminiais atipinių ląstelių (su nedidelio laipsnio branduolių polimorfizmu) proliferatais (DCIS). Dilatuoti latakai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS).  6(N6)(dešinė) Trys(3) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  7(N7)(pap. kraštas, kairė) Riebalinis audinys su fibrozinėmis septomis.  8(N1)(kairė) Krūties audinyje - du naviko židiniai (16,7mm ir 10mm), formuojami duktalinių (~60% naviko), solidinių/lizdinių struktūrų, difuziškai, grandinėlėmis plintančių (~5% naviko) ląstelių, eozinofiliška citoplazma, nežymiai polimorfiškais, hiperchromiškais branduoliais; navike iki 7 mitozių/10 DPRL. Aplinkiniame krūties audinyje - fibrozės zonos su fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu su apokrininės metaplazijos židiniais; intraduktalinių mikrokalcifikatų židiniai; dilatuoti latakėliai su fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu. Fokaliai dilatuoti latakėliai su kribriforminiais, mikropapiliniais atipinių ląstelių (su nedidelio laipsnio branduolių polimorfizmu) proliferatais (DCIS). Dilatuoti latakai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS).  9(N4)(dešinė). Krūties audinyje - dauginiai naviko židiniai (nuo 0,6mm iki 14mm), formuojami kribriforminių, duktalinių (~90% naviko), solidinių/lizdinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, nežymiai, vietomis vidutiniškai polimorfiškais, hiperchromiškais branduoliais; navike iki 3 mitozių/10 DPRL. Aplinkiniame krūties audinyje - fibrozės zonos su fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu su apokrininės metaplazijos, paprastos intraduktalinės hiperplazijos židiniais; fokaliai dilatuoti latakėliai su fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu. Fokaliai dilatuoti latakėliai su solidiniais, kribriforminiais atipinių ląstelių (su nedidelio ir vidutinio laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS). Dilatuoti latakai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS).  10(N8)(pap. kraštas, dešinė) Riebalinis audinys su fibrozinėmis septomis.. 5. CK5+ mioepitelinės ląstelės.   DCIS: E-Cadherin(+++), membr. r-ja, 100%; LCIS: E-Cadherin(-).  8. Duktalinės karcinomos komponentas:  E-Cadherin(+++), membr. r-ja, 100%;  Lobulinės karcinomos komponentas:  E-Cadherin(+/+++), citopl. r-ja, 90%;
answer:  0

 67%|██████▋   | 441/661 [06:45<03:59,  1.09s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 4 biopsiniai stulpeliai.. 4 biopsiniai stulpeliai: I - 10 mm; II - 10 mm; III - 10 mm; IV - 7 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja netaisyklingi šakoti solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozės pavienės.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 10%.
answer:  0

 67%|██████▋   | 442/661 [06:46<03:40,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 9 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) adenokarcinoma (galimai duktalinė, su neuroendokrininės diferencijacijos požymiais, ar invazyvi solidinė papilinė karcinoma).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.. Solidines, trabekulines naviko struktūras formuoja gan smulkios ląstelės su negausia ar kiek gausesne tamsoka citoplazma, smulkiais ar vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 5 / 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  Proliferacinis aktyvumas (Ki67
answer:  5

 67%|██████▋   | 443/661 [06:47<03:42,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštas, ekstra.  2. pjūvio kraštas, ekstra.   3. du sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 9,5x4,5x5,5 cm su odos lopu 2,5x1,3 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje neaiškių ribų, pilkšvas židinys 10x8x8 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 2 cm.. 1(Extra). Krūties audinio fibrozė.  2(Extra). Krūties audinio fibrozė.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(6 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas (R0).  Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 1% naviko ląstelių.  HER2 imuninė reakcija: neigiama (1+).  Ki67: 5%.   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).. 1(Extra). Krūties audinyje, ryškiai fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, ryškiai fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu; negausūs smulkūs kalcifikatai.  3(Extra). 2 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija, smulkiais pigmentuotų makrofagų židiniais bei sinusų histiocitoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 6 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių smulkių, besiliejančių tubulinių, lizdinių ir trabekulinių struktūrų iš ląstelių saikinga švelniai eozinofiliška ar blyškia citoplazma, smulkiais ir vidutinio kalibro, ovaliais/apvaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 1/10 DPRL. Pavieniai smulkūs kalcifikatai navike. Šalia naviko - negausūs dilatuoti kanaliukai su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais.. 1. Navikas (19 blokas):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 1% naviko ląstelių.  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląst
answer:  2

 67%|██████▋   | 444/661 [06:48<03:42,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.(1a)- viršutinis kraštas, skubu  2.(1b)- apatinis kraštas, skubu  3.(2). deš. pažasties sarginiai limfmazgiai, skubu  4.(3). deš. krūties sektorius, planinis  5.(4). pap A kraštas-planas. 4.(3).  Krūties sektorius 10x6x5 cm su odos lopu 6x2,5 cm,  žymėtas viela. Vielos projekcijoje, pjūvyje navikas 1,6x1,6x1,5 cm, nuo artimiausio rezekcijos krašto nutolęs 0,8 cm (mėlyna), nuo odos – 2 cm. Histologiniam ištyrimui navikas sudėtas visas.  5(4). Riebalinio audinio fragmentas 1,5x1x0,5 cm. v/m. 1(1a). Krūties lobulinė karcinoma in situ (LCIS).  2(1b). Krūties audinys.  3(2). Krūties duktalinės karcinomos mikrometastazė viename limfmazgyje (1/2 l/m, 1 mm skersmens).  4(3). Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 14 mm), pN1mi(sn)(1/2 l/m, 1mm), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties lobulinė karcinoma in situ (LCIS).   5(4). Krūties audinys.. 1(1a). Fibrozuotame krūties audinyje gausūs nežymiai dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.  2(1b). Riebalinio audinio fragmentas su smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(2). Po fiksacijos: viename limfmazgyje iš dviejų žemiau aprašyto naviko mikrometastazės iki 1 mm skersmens.  4(3). Krūties audinyje - navikas (14 mm mikroskopiškai), suformuotas tubulinių ir pavienių kribriforminių struktūrų iš vidutinio kalibro eozinofiline citoplazma ląstelių, nežymiai polimorfiškais, smulkiai grūdėtu chromatinu branduoliais; mitozių 7/10 DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Šalia naviko kelios dilatuotos lobulės užpildytos solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta nežymiai dilatuoti kanaliukai kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija.   5(4). Riebalinio audinio fragmentas su smulkiais kanaliukais, klotais dvisluoksniu epiteliu. Ryškūs koaguliaciniai/traiškymo artefaktai.. Blokas 12:  Blokas 13:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 67%|██████▋   | 445/661 [06:49<03:24,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Fragmentuotas biopsinis stulpelis 12 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 18/10 DPRL.. Navikas  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 60%.
answer:  1

 67%|██████▋   | 446/661 [06:50<03:40,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu   3(2) deš. pažasties sarginiai limfmazgiai, skubu  4(3). deš. krūties sektorius, planinis. 4. Krūties sektorius 9x6x5 cm su odos lopu 6x2 cm, žymėtas viela. Vielos projekcijoje - gelsvas, neaiškių ribų navikas 1x0,8x0,8 cm, nuo giliojo rezekcijos krašto nutolęs 1,1 cm, nuo odos - 4 cm. 0,6 cm nuo naviko fibrozės zona 1,2x0,9 cm. Navikas sudėtas visas.. 1(N1a, ekstra/Kraštai). Krūties audinys.  2(N1b, ekstra/Kraštai). Krūties audinys.  3(N2, ekstra/Sarginiai l/m). Lobulinės karcinomos metastazė 1/2 limfmazgių (3 mm).  4(N3, D. krūties sektorius). A) Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(11 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinė invazija neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).  B) Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1a(3,3 mm) N(sn)1a(mts 1/2 l/m: 3 mm), LVI-0(limfovaskulinė invazija neidentifikuota). Radikalus pašalinimas. Lobulinė karcinoma in situ (LCIS).  Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 5% naviko ląstelių.  HER2 imuninė reakcija: neigiama (1+).  Ki67: 2%.. 1(N1a, ekstra/Kraštai). Fibrozuotas krūties audinys su negausiais smulkiais, kanaliukais, klotais dvisluoksniu epiteliu.  2(N1b, ekstra/Kraštai). Fibrozuotas krūties audinys su pavieniais smulkiais, kanaliukais, klotais dvisluoksniu epiteliu.  3(N2, ekstra/sarginiai l/m). 2 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir neryškia sinusų histiocitoze. Ne extra pjūviuose (kitose pusėse), 1/2 limfmazgių - aukščiau aprašyto naviko (invazyvios lobulinės karcinomos) metastazė (3 mm).  4(N3, D. krūties sektorius). Krūties audinyje - fibrozinėje stromoje, infiltratyviu frontu plintantys du atskirų navikų židiniai: I  - 11 mm dydžio, II - 3,3 mm.  I navikas suformuotas trabekulinių struktūrų, smulkesnių grandinėlių bei tubulių (~40%). Naviko ląstelės su vidutinio gausumo, šviesiai eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar ovoidiškais, neryškiai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių navike iki 2/10 DPRL. Aplink naviko židinius dėstosi kanaliukai, su solidiniais ir negausiais kribriforminiais analogiškų navikui ląstelių proliferatais (DCIS).   II naviką sudaro fibrozuotoje stromoje infiltratyviai plintančios trabekulinės struktūros, grandinėlėmis, smulkiomis grupelėmis ar pabirai besidėstančios ląstelės negausia švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais/apvaliais, neryškiai polimorfiškais, dalis su nukleole branduoliais. Mitozių mažiau 1/10 DPRL. Šalia kiek dilatuoti kanaliukai, užpildyti monomorfiškomis ląstelėmis (LCIS).. 4. Limfmazgis (6 blokas): lobulinės karcinomos metastazė: PanCK(+); E-Cadherin(-).  15 blokas: invazyvi duktalinė karcinoma E-Cadherin(+++)(membr. r-ja), 100%.  16 blokas: invazyvi duktalinė karcinoma E-Cadherin(+++)(membr. r-ja), 100%; p120 catenin(+++)(
answer:  100

 68%|██████▊   | 447/661 [06:51<03:36,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 1 - pjūvio kraštai - extra;  2. 2 - pjūvio kraštai - extra;  3. Sarginiai l/m - extra;  4. Sektorius - planinis tyrimas.. 4. Krūties sektorius 14,5x5x6,5 cm su oda 13x2 cm. Krūties audinyje, kvadrante - pilkšvas, standus, neaiškių ribų navikas 13x10x8 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 1,3 cm.. 1(ekstra). Pjūvio kraštai. Krūties fibrocistiniai pokyčiai. Naviko plitimo nėra.     2(ekstra). Pjūvio kraštai. Krūties fibrocistiniai pokyčiai. Naviko plitimo nėra.    3(ekstra). Sarginiai l/m. Duktalinės karcinomos metastazė 1-me/3 limfmazgių, iki 2 mm skersmens.      4. Krūties sektorius.  Krūties invazyvi vidutiniškai diferencijuota (G1, 5 b. pgl Nottingham sist.) duktalinė karcinoma,   pT1c(13 mm)   pN(sn)1mi(1/3 l/m mts iki 2 mm)   pLVI-0 (limfovaskulinės invazijos nestebima)   pR0(radikalus pašalinimas).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama (0).  Ki67: proliferacinis indeksas 5%.. 1(ekstra: pjūvio kraštai). Krūties audinys su fibrozės zonomis ir smulkiais, dalis cistiškai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.     2(ekstra: pjūvio kraštai) . Krūties audinys su fibrozės zonomis ir smulkiais, dalis cistiškai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.    3(ekstra: sarginiai limfmazgiai). 1-me/3 limfmazgių naviko židinys iki 2 mm skersmens.    4. Krūties sektorius. Krūties audinyje - desmoplastiškoje stromoje plintantis navikas, suformuotas tubulinių, solidinių ir negausių grandinėlių bei trabekulinių struktūrų. Naviko ląstelės su negausia, tamsia eozinofiliška citoplazma, vidutinio kalibro, apvaliais, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių navike iki 2/10 DPRL.. Blokas 19:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, <10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 5% naviko ląstelių.  Progesterono receptoriai: reakcijo
answer:  0

 68%|██████▊   | 448/661 [06:52<03:28,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2). deš. pažasties sarginiai limfmazgiai, skubu  4(3). deš. krūties sektorius, planinis. 4(3). Krūties sektorius 4,5x3,5x2 cm. Pjūvyje balkšvas, standus, aiškių ribų navikas 0,9x0,7x0,8 mm (sudėtas visas), nuo artimiausio rezekcijos (dažytas mėlyna) krašto nutolęs 0,3 cm.. 1(1a). Riebalinis, fibrozinis audinys.  2(1b). Krūties fibrocistiniai pokyčiai.  3(2). Reaktyvi limfadenopatija (2 l/m).  4(3). Krūties invazyvi duktalinė adenokarcinoma (gerai diferencijuota / G1 / 5 balai pagal Nottingham), TNM (Nr.1-Nr.4): pT1b(0,9 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 3%.. 1(1a). Riebalinis, fibrozinis audinys.  2(1b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai minimaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(2). Sinusų histiocitozė dviejuose (2) limfmazgiuose.  4(3). Krūties audinyje - navikas (tubulines (80%), negausias smulkias trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne švelniai eozinofiline citoplazma, smulkiais ar kiek stambesnio kalibro kiek netaisyklingais, dalis su smulkia nukleole branduoliais; mitozių navike iki 1 / 10 DPRL.. 4(3). Navikas (10 blokas): Her2 silpna trūkinėjanti membraninė r-ja 10% naviko ląstelių.
answer:  1

 68%|██████▊   | 449/661 [06:52<03:15,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas kair. krūties darinys, paimti 3 biopsiniai stulpeliai medžiagos histologiniam ištyrimui. 3 biopsiniai stulpeliai: I - 12 mm; II - 16 mm; III - 17 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 10%.. Krūties audinį infiltruoja duktalinės struktūros, netaisyklingi kribroziniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas visos membranos nusidažymas 20% naviko ląstelių.  Ki67+ 10%
answer:  0

 68%|██████▊   | 450/661 [06:53<03:07,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm.. Krūties invazyvi duktalinė adenokarcinoma (tikėtina vidutiniškai diferencijuota / G2 / 6 balai pagal Nottingham sistemą), plitimas 1/1 biopsiniame stulpelyje, iki 6,8 mm ilgyje.     Estrogenų receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: 15%.. Krūties audinyje (1 biopsiniame stulpelyje, iki 6,8 mm ilgyje) - fibrozinėje stromoje plintančios ilfiltratyvios trabekulinės, kribriforminės, tubulinės (~10 %) naviko struktūros su negausiais kalcifikatais; naviko ląstelės su negausia eozinofiliška citoplazma, vidutinio kalibro, nereguliaraus kontūro, hiperchromiškais ir vezikuolizuotais, kiek polimorfiškais, be aiškių nukleolių branduoliais; mitozių navike 1 / 10 DPRL.. Navikas (Blokas 1):  Estrogenų receptoriai: stipri (+++) reakcija, 95% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari/trūkinėjanti reakcija, 20% naviko ląs
answer:  1

 68%|██████▊   | 451/661 [06:54<03:00,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 3 biopsiniai stulpeliai.. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 11 mm; III - 9 mm.. Žemo piktybiškumo metaplastinė (ištęstų ląstelių) krūties karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 1-2%.. Navikinio audinio bioptatai (krūties audinio elementų nerasta): pluoštai ištęstų ląstelių gausia eozinofiline citoplazma, ovaliais, vidutiniškai ar ryškiai polimorfiškais branduoliai; mitozių iki 4/10 DPRL.  Naviko ląstelės Ck5+, p63+, PanCk+.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 1-2%.  p63+, Ck5
answer:  0

 68%|██████▊   | 452/661 [06:55<02:54,  1.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 6 bioptatai 22 mm 12 G adata, paimti iš ~12 mm mikrokalcinatų plotelio, penkiuose mikrokalcinatai.. 6 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 8 mm; IV - 12 mm; V - 15 mm; VI - 10 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 15%.. Krūties audinį infiltruoja nedideli kribroziniai/solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 80% naviko ląstelių.
answer:  1

 69%|██████▊   | 453/661 [06:56<03:06,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N1): pašalintas markiruotas dešinės krūties plotas - planinis tyrimas. 3. Krūties sektorius 5,5x4,5x3 cm, žymėtas viela, rezekcijos kraštas dažytas mėlynu tušu. Vielos projekcijoje, pjūvyje balkšva, standi, fibrozės zona 25x20x30 mm, nuo giliojo rezekcijos krašto nutolusi 0,1 cm.. 1(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  2(Extra). Krūties audinys.  3. Krūties invazyvi blogai diferencijuota (G3; 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(5,5 mm) NX(limfmazgiai nešalinti), LVI-0(limfovaskulinės invazijos neidentifikuota).    Imunofenotipas:   Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2 imuninė reakcija: teigiama (3+).  Ki67: 30%.  Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS)(solidinė, kribriforminė, komedo) (30 mm židinys makro).  Invazyvi karcinoma pašalinta radikaliai, DCIS struktūros siekia sektoriaus rezekcijos kraštą.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu, fokaliai hiperplastišku epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3. Krūties audinyje - zona su fibrozinėje stromoje besidėstančių stambių ir vidutinio kalibro kanaliukų su solidiniais ir kribriforminiais intraduktaliniais proliferatais, suformuotais ląstelių eozinofiliška citoplazma, stambiais, polimorfiškais, su nukleole branduoliais; fokaliai komedo nekrozės centruose. Šalia židininė MMN ir makrofagų infiltracija su cholesterolio kristalais ir makrofagais bei daugiabranduolėmis gigantinėmis ląstelėmis aplink. Viename bloke, šalia DCIS plinta lizdinės ir trabekulinės naviko struktūros (be CK5+ mioepitelinio sluoksnio), suformuotos ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Naviko dydis 5,5 mm. Mitozių iki 11/10 DPRL.. 1. 1 blokas: kanaliukai su CK5+ mioepiteliniu sluoksniu, luminalinė populiacija mišri.  Navikas (15 blokas):  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2 imuninė reakcija: s
answer:  0

 69%|██████▊   | 454/661 [06:57<02:57,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.  N2a- skubus - kraštai  2. N2b kraštai - skubus tyrimas - be naviko  3.N3: kairės pažasties sarginis limfmazgis - skubus tyrimas 2l/m be naviko  4. N1: pašalintas kairės krūties kvadrantas  - planinis tyrimas. 4. Krūties sektorius 5x5x2 cm, su odos lopu 4x1,5 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje balkšvas, aiškių ribų 9x6x mm navikas, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos - 3 cm.. N1: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (9mm).  N2ab: Audiniai be naviko.  N3: Limfmazgiai (2 l/m) be naviko; pN0(sn).. N1: Krūties audinyje 9mm navikas: smulkios duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.  N2ab: Audiniai be naviko.  N3: Limfmazgiai (2 l/m) be naviko.. nan
answer:  0

 69%|██████▉   | 455/661 [06:58<03:05,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštai - be naviko - skubus tyrimas   2(N2b). kraštai - be naviko - skubus tyrimas   3(N3). sarginis limfmazgis - 2 l/m be naviko - skubus tyrimas  4(N1). pašalintas dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 5x3,5x3 cm su odos lopu 4,5x2,3 cm. Vielos projekcijoje, pjūvyje - balkšvas, standus, neaiškių ribų navikas 17x15x10 mm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm, nuo odos – 1 cm. Šalia naviko - fibrozės zona 3x2,5x1 cm.. 1. Krūties adenozė.   2. Krūties adenozė.   3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma,   pT1a (17 mm) pN0(sn) (0/2 l/m); LVI2 (limfovaskulinė naviko invazija smulkiose limfagyslėse/ kraujagyslėse).   Krūties aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2-DIN3; kribriforminė, solidinė).. 1. Krūties audinys fibrozuota stroma, su gausiais organoidiniais smulkių kanaliukų proliferatais.   2. Krūties audinys fibrozuota stroma, su gausiais organoidiniais smulkių kanaliukų proliferatais.   3. Limfmazgiai (2) kiek tušuota architektūra, makrofagų reakcija parakortekse, sinusų histiocitoze.   4. Krūties audinyje - navikas, formuojamas infiltratyviai plintančių, glaudžiai besidėstančių grandinėlių, trabekulinių struktūrų, smulkių grupių, sudarytų iš nedidelių-vidutinio dydžio poligonalinių ląstelių šviesiai eozinofiliška citoplazma, vidutiniškai ar ryškiai polimorfiškais ovaliais ar skeltais branduoliais su vezikulizuotu chromatinu, ryškiomis centrinėmis nukleolėmis. Navike iki 5 mitozių/ 10 DPRL.   Limfovaskulinė naviko invazija smulkiose kraujagyslėse/ limfagyslėse.   Naviko periferijoje - įvairaus dydžio latakai ir lobulių kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais, sudarytais iš vidutinio dydžio ir stambių kampuotų ląstelių gausia eozinofiliška citoplazma, vidutiniškai ar ryškiai polimorfiškais branduoliais su ryškiomis nukleolėmis.. 4. Navikas (11 blokas):   e-cadherin(+++)(membr. r-ja) 100%.
answer:  0

 69%|██████▉   | 456/661 [06:58<02:59,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 6 stulpeliai. 6 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 7 mm; III - 7 mm; IV - 4 mm; V - 4 mm; VI - 3 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcja neigiama, branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 35%.. Krūties audinį infiltruoja negausios duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcja neigiama, branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 10% naviko lą
answer:  1

 69%|██████▉   | 457/661 [06:59<03:07,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - N2a kraštai - skubus - be naviko  2 - N2b kraštai - skubus - be naviko  3 - N3 kairės pažasties limfmazgiai - skubus tyrimas -  2l/m be naviko  4(1) - pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 12x4,5x5 cm su oda 10,5x3 cm. Krūties audinyje, pilkšvas, standus, aiškių ribų navikas 22x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,6 cm.. 1(ekstra). Krūties audinys.  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (4 l/m).   4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham sistemą) duktalinė karcinoma, pT2 (22 mm navikas) N0(sn)(4 l/m) LVI0 (limfovaskulinė invazija neidentifikuota). Radikalus pašalinimas. Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 komedo tipas).  Stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).     Naviko imunotipas nustatytas biopsijoje:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 4 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.  4. Krūties audinyje - fibrozinėje stromoje plintantis navikas, suformuotas lizdų, trabekulių, grandinėlių, pavienių tubulių (<10 %) ir pabirų ląstelių. Naviko ląstelės su vidutinio gausumo, šviesiai eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių navike iki 19/10DPRL.  Šalia naviko dilatuoti kanaliukai su intraduktaliniais solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.  Aplinkiniame krūties audinyje dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).. nan
answer:  0

 69%|██████▉   | 458/661 [07:00<02:58,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas dešinės krūties darinys - planinis tyrimas  2 ėminio aprašas: N2a ir N2b kraštai - planinis tyrimas. 1. Krūties sektorius 8x6x4 cm su oda 7x2 cm. Pjūvyje pilkšvas, su smulkiomis hemoragijomis mucininis navikas 2,1x1,9x2,1 cm, nuo giliojo rezekcijos krašto (dažytas mėlynu tušu) nutolęs mažiau 0,1 cm, nuo odos - 1,5 cm.  2. Riebalinio audinio fragmentas 2,5x1x0,5 cm. v/m  3. Riebalinio audinio fragmentas 2,5x2x0,8 cm. v/m. N1: Mucininė krūties karcinoma (G1, 5 balai pgl Nottingham); pT2(21mm).  N2ab: Krūties audinys be patologijos.. N1: Krūties audinyje 21mm navikas: mucininėje stromoje netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.  N2ab: Krūties audinys be patologijos.. nan
answer:  0

 69%|██████▉   | 459/661 [07:01<02:51,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 5 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko
answer:  0

 70%|██████▉   | 460/661 [07:02<02:46,  1.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 15 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67+ 12%, vietomis iki 20%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 10% naviko ląstelių.  Ki67+ 1
answer:  0

 70%|██████▉   | 461/661 [07:03<02:42,  1.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 6 mm; II - 4 mm; III - 7 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja duktalinės struktūros, smulkūs solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 30% naviko ląstel
answer:  0

 70%|██████▉   | 462/661 [07:04<02:59,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - sarginiai l/m - ekstra  2 - deš. krūties liauka - planiniam tyrimui   3 - papildomas. 2. Krūtis 346 gramų svorio, 17x14,5x3,5 cm, su odos lopu 8,5x1,5 cm, su speneliu (liauka persiūta ilgu siūlu lateraliai, trumpu - viršus). Krūties audinyje, apatiniame lateraliniame kvadrante - balkšvas, standus, kiek neaiškių ribų navikas 28x11x23 mm, nuo odos nutolęs 1,5 cm, nuo giliojo rezekcijos krašto - 0,4 cm, nuo poodinio rezekcijos krašto - 1 cm. 1,2 cm nuo naviko, I standi zona 0,9x0,8x0,7 cm, nuo odos nutolusi 2 cm, nuo giliojo rezekcijos krašto - 0,5 cm. Nuo naviko 1,7 cm nutolusi II standi zona 0,3x0,2x0,2, nuo odos nutolusi 1 cm, nuo giliojo - 1,7 cm.   3. Riebalinio audinio fragmentas 4x3,4x1,2 cm.. 1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (5 l/m).   2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT2 (navikas 28 mm) N0(sn) (0/5 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).   Kalcifikatai.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis, papilinis ir komedo tipai).   Rezekcijos kraštai be naviko.   3. Fibrozuotas krūties-riebalinis audinys; be naviko.. 1(ekstra). "Sarginiai limfmazgiai": penki (5) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.    2. SPENELIS: su židinine plaukų folikulus supančia MMN infiltracija, spindžiuose Demodex spp. fragmentai.   NAVIKAS (vienas susiliejantis mazguotas židinys su gausiais in situ komponento intarpais, didžiausias matmuo - 28 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės,  kribriforminės, gausesnės trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 3/10 DPRL. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija, hemi Pavieniai mikrokalcifikatai.  APLINKA: multifokaliai krūties audinyje ir šalia naviko - kribriforminiai, papiliniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   KRŪTIES REZEKCIJOS KRAŠTAS: normalios histologinės struktūros; be naviko.   3. Fibrozuotas, vaskuliarizuotas brandžių lipocitų suformuotas fragmentas su nerviniais kamienais ir fokaliai įsiterpiančiais smulkiais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.. 2. Navikas (blokas 17):  HER2: silpna (+) necirkuliari reakcija, 50%  naviko ląstelių membranoje.  E-Cadherin(+++)(membr.r-ja)100%.
answer:  1

 70%|███████   | 463/661 [07:04<02:54,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas kairės krūties darinys, paimti 4 biopsiniai stulpeliai medžiagos histologiniam ištyrimui.   2 ėminio aprašas: punktuotas kair. pažasties pakitusios struktūros l/m, paimti 4 biopsiniai stulpeliai medžiagos histologiniam ištyrimui.. 1. 4 fragmentuoti biopsiniai stulpeliai: I - 16 mm; II - 8 mm; III - 11 mm; IV - 8 mm.  2. 4 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 8 mm; III - 8 mm; IV - 12 mm.. N1: Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: silpnas ar vidutinis branduolių nusidažymas 10% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%, vietomis iki 40%.  N2: Lobulinės karcinomos metastazė limfmazgyje.. N1: Krūties audinį infiltruoja nedideli solidiniai kompleksai, juostos ir trabekulės iš ryškiai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.  N2: Limfmazgio bioptatai su aukščiau aprašyto naviko židiniais.. Navikas  Estrogenų receptoriai: silpnas ar vidutinis branduolių nusidažymas 10% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.
answer:  0

 70%|███████   | 464/661 [07:05<02:48,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 bioptatas iš l/m  dešinėje   pažastyje   2 but. 1 biopsinis stulpelis iš dešinės krūties darinio BI-RADS 5. 1. Biopsinis stulpelis 11 mm ilgio.  2. Biopsinis stulpelis 12 mm ilgio.. 1. Limfmazgio bioptatas be naviko plitimo.   2. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 4%.. 1. Limfmazgio bioptatas be naviko plitimo.   2. Krūties audinį infiltruoja duktalinės struktūros (50%), netaisyklingi kribroziniai kompleksai ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. 2. Blokas 2:  Estrogenų receptoriai: stipri (+++) reakcija, 95% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląstelių membranoje.
answer:  0

 70%|███████   | 465/661 [07:06<02:44,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 10 mm; II - 11 mm.. Vyraujantis komponentas vidutinio laipsnio intraduktalinė karcinoma (DCIS/DIN2; kribriforminė).    Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinyje plačios zonos su šakotais dilatuotais kanaliukais su intraduktaliniais kribroziniais neryškiai polimorfiškų ląstelių proliferatais ir negausūs invazinio augimo židiniai: netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 40% naviko ląstel
answer:  1

 70%|███████   | 466/661 [07:07<03:01,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Deš. pažasties sarginiai limfmazgiai, skubu - extra.  2. Deš. krūtis, planinis.. 2. Krūtis 495 gramų svorio, 19,5x14x5 cm. Centrinė krūties dalis fibrozuota 8x7 cm plote. Fibrozuotos zonos kraštuose:   - I rusvas, standus židinys 32x25x11 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,5 cm;   - II neaiškių ribų heterogeniškos išvaizdos židinys 35x30x30 mm, nusitęsiantis į spenelį, nuo giliojo rezekcijos krašto nutolęs 1,3 cm.. PAPILDYTAS ATSAKYMAS HER2 FISH TYRIMU (HER2 geno amplifikacija nenustatyta):   1(ekstra). "Deš. pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (4 l/m).   2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c(m) (naviko židiniai: I - 11 mm; II - 8 mm; III - 4 mm) N0(sn) (0/4 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, papilinis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė, apokrininė metaplazija).   DCIS struktūros nuo giliojo rezekcijos krašto nutolusios - 1,45 mm.. 1(ekstra). "Deš. pažasties sarginiai limfmazgiai": keturi (4) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2. SPENELIS: normalios histologinės struktūros.   NAVIKAS (naviko židiniai: I - 11 mm; II - 8 mm; III - 4 mm; supami ryškios fibrozės, fibrocistinių pokyčių ir in situ komponento): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės, kribriforminės, trabekulinės, nedidelės lizdinės ir solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo tamsoka citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 15/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Pavieniai mikrokalcifikatai. Keletas zonų su ryškesne fibroze ir "nubyrančiomis" naviko struktūromis (g.b. ankstesnių biopsijų zonos).   APLINKA: šalia naviko - solidiniai, kribriforminiai, papiliniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su papiliniais intraduktaliniais proliferatais, ryškesne epitelio atipija, apokrinės metaplazijos zonomis, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu.   GILUSIS REZEKCIJOS KRAŠTAS: in situ komponentas nutolęs 1,45 mm.. 2. Navikas (blokas 25):  HER2: vidutinė (++) necirkuliari reakcija, 10% naviko ląstelių membranoje.
answer:  0

 71%|███████   | 467/661 [07:08<02:51,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 freagmentuoti biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 8 mm.. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) mucininė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 40% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 3%.. Kribrozines naviko struktūras (išsidėsčiusias gausiuose ekstraląsteliniuose mucinuose) formuoja ląstelės su saikinga tamsoka citoplazma, vidutinio kalibro saikingai polimorfiškais, dalis su nukleole branduoliais; mitozių navike nestebima.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 3% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 40% naviko
answer:  0

 71%|███████   | 468/661 [07:09<02:55,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.  4. sektorius, planinis.. 4. Krūties sektorius 14x4,5x5 cm su oda 12,5x1,6 cm, žymėtas 2 vielomis, atstumas tarp vielų 5 cm. Odoje pilkšvas smulkiai gruoblėtas darinys 1,6x1,4x0,3 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm. Vielų projekcijoje:  - I vielos projekcijoje - pilkšvas, standus navikas 22x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2 cm.  - II vielos projekcijoje - krūties audinys fibrozuotas 2,5x2,2 cm plote, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 2,2 cm.. 1. pjūvio kraštai: krūties audinys be patologinių pokyčių.    2. pjūvio kraštai: krūties audinys su intraduktaline hiperplazija.    3. sarginiai l/m: limfmazgis (1) be karcinomos ląstelių.; pN(sn)0.    4. sektorius.   Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą)   duktalinė karcinoma su mucininės diferenciacijos požymiais;   pT1c(<20mm) pLVI-0 pR0.  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 1% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.. 1. pjūvio kraštai: krūties audinys be patologinių pokyčių.  2. pjūvio kraštai: krūties audinys su intraduktaline hiperplazija.  3. sarginiai l/m: limfmazgis (1) be karcinomos ląstelių.   4. sektorius. Krūties audinyje - darinio (mikroskopiškai 19 mm) fibrozinės stromos su gausiais AB+ mucinų židiniais apsuptos kribriforminės struktūros ir solidiniai kompleksai, suformuoti ląstelių vidutinio gausumo, tamsia eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar ovoidiškais, hiperchromiškais, vidutiniškai polimorfiškais branduoliais su pavienėmis smulkiomis nukleolėmis. Mitozių navike iki 6/10DPRL. Inravaskulinio plitimo nestebima.. nan
answer:  0

 71%|███████   | 469/661 [07:10<02:50,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 biopsinis stulpelis  iš dešinės pažasties l/m  2 but. 2 biopsiniai stulpeliai  iš dešinės krūties darinio. 1. Biopsinis stulpelis 7 mm.   2. 2 biopsiniai stulpeliai: I - 12 mm; II - 10 mm.. N1: Limfmazgio bioptatas su lobulinės karcinomos metastaze.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%, vietomis iki 40%.. N1: Limfmazgio bioptatas su žemiau aprašyto naviko židiniais.  N2: Krūties audinį infiltruoja nedideli solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 30
answer:  1

 71%|███████   | 470/661 [07:11<02:49,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, policikliniais kontūrais be UG fiksuojamos kraujotakos, ~12×5 mm dydžio darinys kairiojoje krūtyje ties 1 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 7 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 4,5 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se/3 krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.    Krūties fibrocistiniai pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).   Kalcifikatai.. Krūties audinį 2-se/3 bioptatuose infiltruoja iki 4,5 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais negausioje citoplazmoje;   - mitozių nestebima.  Intravaskulinės invazijos nėra.    2-se stulpeliuose - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu, fokaliai su stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), smulkūs kalcifikatai spindžiuose.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 25%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 5% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  100

 71%|███████▏  | 471/661 [07:12<02:48,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 biopsinis stulpelis iš kairės pažasties  I lygio l/m  2 but. 1 biopsinis stulpelis iš kairės krūties BI-RADS 5 darinio  3 but. 1 biopsinis stulpelis iš dešinės pažasties I lygio l/m. 1. Biopsinis stulpelis 10 mm ilgio.  2. Biopsinis stulpelis 14 mm ilgio.  3. Fragmentuotas biopsinis stulpelis 8 mm ilgio.. N1: Limfmazgio bioptatas su duktalinės karcinomos metastaze.  N2: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%.  N3: Limfmazgio bioptatas be naviko židinių.. N1: Limfmazgio bioptatas su žemiau aprašyto naviko židiniais.  N2: Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.  N3: Limfmazgio bioptatas be naviko židinių.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 30% naviko ląstel
answer:  1

 71%|███████▏  | 472/661 [07:12<02:41,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Paimti 3 biopsiniai stulpeliai.. 3 biopsiniai stulpeliai: I - 14 mm; II - 12 mm; III - 17 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 15%.. Krūties audinį infiltruoja negausios duktalinės struktūros, nedideli netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 100% naviko ląstelių.  Ki67+ 15
answer:  0

 72%|███████▏  | 473/661 [07:13<02:39,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 5 stulpeliai. 5 fragmentuoti biopsiniai stulpeliai: I - 17 mm; II - 17 mm; III - 22 mm; IV - 12 mm; V - 10 mm.. Krūties invazyvi duktalinė karcinoma, 0,4 mm židinys (1/5 bioptatų). Žr. pastabą.   Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, solidinis tipas), (2/5 bioptatų).     Naviko imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 20%.. Bioptate (1/5) - krūties audinyje, fibrozinėje stromoje smulkus naviko židinys, suformuotas smulkiomis grupėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais. 2/5 bioptatų dilatuoti latakai su intraduktaliniais solidiniais proliferatais negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: neigiama reakcija.  HER2: vidutinis dalies membranos nusidažymas 40% naviko ląstelių.  Ki67 proliferacinis aktyvumas ---- %.  CK14/p63(-);
answer:  0

 72%|███████▏  | 474/661 [07:14<02:53,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - be naviko.  2(2b). Kraštai - be naviko.  3(1). Pašalintas sektorius - planinis patologinis tyrimas N1 - skubus rentgeninis tyrimas- navikas pašalintas.. 3(1). Krūties sektorius 14x7x2 cm su odos fragmentu 4,5x1 cm, žymėtas viela, vienoje pusėje - dviem trumpais siūlais, kitoje pusėje - vienu trumpu ir vienu ilgu siūlais. Vielos projekcijoje, krūties audinio pjūvyje - balkšvas standus, neaiškių ribų navikas 1,3x1x0,8 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,5 cm, nuo odos – 6 cm. Šalia naviko fibrozės zona 3,5x2,5x2 cm.. 1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija); kalcifikatai; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.     3(1). Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 9,6 mm),   LVI-0 (definityvi limfovaskulinė invazija neidentifikuota). Kalcifikatai.    Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: solidinis, kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).   DCIS komponentas nuo sektoriaus rezekcijos krašto nutolęs 0,72 mm.. 1(2a, ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su apokrinės metaplazijos zonomis; pavieniai smulkūs kalcifikatai; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas, vaskuliarizuotas brandžių lipocitų suformuotas fragmentas; be naviko.   3(1). NAVIKAS (didžiausias išmatuojamas invazyvaus naviko matmuo - 9,6 mm; tarp naviko struktūrų ir aplink jį gausūs in situ kompleksai, ryški fibrozė ir fibrocistiniai pokyčiai; bendras pokyčių židinio dydis ~18 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės ir kribriforminės naviko struktūros, suformuotos saikingai polimorfiškų ląstelių, negausia šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais; mitozės retos, sunkiai vizualizuojamos. Pavieniai mikrokalcifikatai.   APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   SEKTORIAUS REZEKCIJOS KRAŠTAS: intraduktaliniai naviko ląstelių kompleksai nuo artimiausio rezekcijos krašto nutolę - 0,72 mm.. 3(1). Navikas (blokas 8):  HER2: silpna (+) necirkuliari reakcija, 10% naviko ląstelių membranoje.
answer:  0

 72%|███████▏  | 475/661 [07:15<02:43,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 90% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.. Bioptate - desmoplastiškoje stromoje, infiltratyvios naviko struktūros, suformuotos solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška tamsia ar ryškia citoplazma, polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais; ryškiomis nukleolėmis mitozių 4/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 90%.  HER2: nusidažiusių  aviko ląstelių nėra.  Ki67 proliferacinis aktyvumas 10%.  E-cadherin(+++) membr. r-ja 100%.  CK14 foninė citopl. r-ja.
answer:  0

 72%|███████▏  | 476/661 [07:16<02:47,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. (2a) kraštai -extra  2. (2b) kraštai - extra.  3. (3) sarginiasi limfmazgiai -extra  4. (1) pašalintas sektorius- skubus rentgeninis tyrimas- navikas pašalintas, planinis patologinis tyrimas.. 4(1). Krūties sektorius 8x4,5x3,5 cm, su odos lopu 7x2,7 cm, su speneliu. Krūties audinyje - besiribojantis su speneliu balkšvas, standus, žvaigždės formos, neaiškių ribų navikas 17x15x17 mm, nuo artimiausio giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - mažiau 0,1 cm, nuo odos rezekcijos krašto - 0,7 cm. Naviko projekcijoje oda be makroskopinių pokyčių, spenelis nežymiai įtrauktas.. 1(N2A). Krūties fibrocistiniai pokyčiai.  2(N2B). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (1 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,7 cm) pN(sn)0 (0/1 l/m). LVI0(limfovaskulinės invazijos nėra).    Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5% (hot spot 10%).. 1(N2A). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2(N2B). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N3). Sinusų histiocitozė viename (1) limfmazgyje.  4(N1). Krūties audinyje - navikas: solidines, trabekulines, pavienes kribrozines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 7 / 10 DPRL.. 4(N1). Navikas (9 blokas): Her2 nusidažiusių naviko ląstelių nėra.  Ki67: 5% (hot spot 10%).
answer:  0

 72%|███████▏  | 477/661 [07:17<02:41,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biospiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7mm; II - 7 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 5,5 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 8%.. Krūties audinį 2-se bioptatuose infiltruoja iki 5,5 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su neryškiai polimorfiškais branduoliais  negausioje bazofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) cirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 8% naviko ląstelių.  Progesterono receptoriai: stipri (+++)
answer:  0

 72%|███████▏  | 478/661 [07:18<02:33,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas kairės krūties kraujuojantis peraugantis spenelį navikas. Krūties sektorius 11,5x8x5,5 cm. Krūties audinyje balkšvas, standus, neaiškių ribų navikas 3,3x1,8x3,3 cm, esantis 0,5 nuo artimiausio/giliojo rezekcijos pjūvio, siekia ir perauga odą, nuo odos rezekcijos krašto nutolęs 2 cm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b (33mm, išopėjimas).. Krūties audinyje išopėjęs 33mm navikas: netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 6/10 DPRL.  Operacinis pjūvis be naviko.. nan
answer:  0

 72%|███████▏  | 479/661 [07:18<02:28,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 10 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai kompleksai ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  0

 73%|███████▎  | 480/661 [07:19<02:26,  1.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  16 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais ~8x18 mm dydžio navikas kairiojoje krūtyje ties 12 val. vidurinėje dalyje, paimti trys biopsiniai stulpeliai histologijai.. 3 fragmentuoti biopsiniai stulpeliai: I - 13 mm; II - 12 mm; III - 13 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.. Krūties audinį difuziškai infiltruoja vidutiniškai polimorfiškos apvalios ląstelės, vietomis ekscentriškais branduoliais, mitozių iki 6/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: vidutinis dalies membranos nusidažymas 60% naviko ląstelių.  Ki67+
answer:  15

 73%|███████▎  | 481/661 [07:20<02:32,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2). Deš. pažasties sarginiai l/m, skubu  4(3). Deš. krūties sektorius, planinis. 4. Krūties sektorius 7x6x3,5 cm, žymėtas viela. Pjūvyje, vielos projekcijoje - balkšvas, standus, aiškių ribų navikas 15x15x10 mm (sudėtas visas), nuo rezekcijos krašto nutolęs 1 cm.. 1(1a). Viršutinis kraštas. Krūties audinys be patologinių pokyčių.   2(1b). Apatinis kraštas. Krūties audinio fibrozė.   3(2). Deš. pažasties sarginiai l/m. Reaktyvi limfadenopatija (4 l/m).   4(3). Deš. krūties sektorius. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma. SUMINIS TNM: pT1c(15 mm navikas) pN0(sn)(0/4 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikalus pašalinimas).   Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 kribriforminis tipas).. 1(1a). Viršutinis kraštas. Krūties audinys su pavieniais smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2(1b). Apatinis kraštas. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3(2). Deš. pažasties sarginiai l/m. 4 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.  4(3). Deš. krūties sektorius. Krūties audinyje - desmoplastiškoje stromoje plintantis navikas, suformuotas tubulių, kribriforminių struktūrų ir lizdų.  Naviko ląstelės su vidutinio gausumo eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar ovoidiškais, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių navike iki 3/10DPRL.  Šalia naviko - stambūs kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių.. Navikas (16 blokas): HER2: silpnas dalies membranos nusidažymas 60% naviko ląstelių.
answer:  0

 73%|███████▎  | 482/661 [07:21<02:27,  1.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 4 mm; II - 4 mm; III - 3 mm. Gleivės.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mucininė karcinoma.   Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: vidutinė reakcija 5% naviko ląstelių.   Her2 imuninė reakcija: teigiama (3+).   Ki67 proliferacinis aktyvumas 5%.. Fragmentuotuose bioptatuose (3/3) - ekstraląsteliniuose mucinuose trabekulinės, kribriforminės, lizdinės naviko struktūros, suformuotos ląstelių gausia eozinofiliška ryškia citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 5/10 DPRL.. Navikas:   Estrogenų receptoriai: (+++)(brand. r-ja) 100%.   Progesterono receptoriai: (++)(brand. r-ja) 5%.   HER2: stiprus visos membranos nusidažymas 100%.   Ki67 proliferacinis aktyvumas 5%.
answer:  0

 73%|███████▎  | 483/661 [07:22<03:09,  1.06s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.1a- viršutinis kraštas (deš.krūtis), skubu  2.1b- apatinis kraštas (deš. krūtis), skubu  3.(2). Deš. pažasties sarginiai limfmazgiai, skubu  4.(4a) - viršutinis kraštas (kairė krūtis), skubu  5.(4b)- apatinis kraštas (kairė krūtis), skubu  6.(5) - Kairės pažasties sarginiai limfmazgiai, planas  7.(3)- deš. krūties kvadrantas, planinis  8.(6) - Kairės krūties kvadrantas, planinis  9.(7) - papildomas k.kruties viršut.kraštas-planas  10.(8) - papildomas d.krūtis apat.kraštas-planas. 6(5). Riebalinio audinio fragmentas 5,5x2,5x1,3 cm. Rastas limfmazgis 3 cm.   7(3). Krūties sektorius 13,5x6,5x3 cm su odos lopu 8,5x3,5 cm, žymėtas dvejomis vielomis. Vienos vielos projekcijoje neaiškių ribų, standi fibrozės zona su prasiplėtusiais tarpais 21x9x7 mm, nuo giliojo rezekcijos krašto nutolusi 0,3 cm, nuo odos - 2,5 cm. Kietos vielos projekcijoje 2 intramamariniai limfmazgiai iki 0,5 cm skersmens. Fibrozės zona vielos projekcijoje sudėta visa.   8(6). Krūties sektorius 9x6x2,2 cm, be odos, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 21x18x11 mm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm.  9(7). Riebalinio/fibrozinio audinio fragmentas 2,5x1x0,4 cm. v/m  10(8). Riebalinio audinio fragmentas 3x1,3x0,5 cm. v/m. 1(extra). Viršutinis kraštas, dešinė. Fibrocistiniai pokyčiai.  2(extra). Apatinis kraštas, dešinė. Krūties žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1, kribriforminis tipas).  3(extra). Sarginiai limfmazgiai, dešinė. Reaktyvi limfadenopatija (4 l/m).    4(extra). Viršutinis kraštas, kairė. Fibrocistiniai pokyčiai.  5(extra). Apatinis kraštas, kairė. Fibrocistiniai pokyčiai.  6. Kairės pažasties sarginiai limfmazgiai (planinis). Duktalinės karcinomos metastazė (1/1 l/m, 4,4 mm).    7. DEŠINĖ. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) multižidininė, mikroinvazyvi duktalinė karcinoma, SUMINIS TNM: pT1mi(m)(0,4 mm, 0,5 mm, 0,9 mm, 1 mm) pN0(sn)(0/6 l/m0 LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 DIN1 DIN2, kribriforminis, solidinis, komedo ir papilinis tipai), DCIS židinys iki 2 cm. R0(radikali rezekcija).  Imunofenotipas (biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.    8. KAIRĖ.  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(21 mm navikas) pN1a(sn)(MTS 1/1 l/m 4,4 mm) LVI-2(limfovaskulinė invazija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas). R0(radikali rezekcija).  Imunofenotipas (biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%, vietomis iki 30%.    9. Papildomas kairės krūties viršutinis kraštas. Fibrocistiniai pokyčiai.   10. Papildomas dešinės krūties apatinis kraštas. Fibrocistiniai pokyčiai.. 1(extra). Viršutinis kraštas (deš.krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  2(extra). Apatinis kraštas (deš. krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu. Fokaliai latakų grupė su intraduktaliniais kribriforminiais proliferatais iš ląstelių nežymiai polimorfiškais brnaduoliais.   3(extra). Sarginiai limfmazgiai, dešinė. 4 limfmazgiai su sinusų histiocitoze, lipomatoze ir pirminiais bei antriniais folikulais.  4(extra). Viršutinis kraštas (kairė krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  5(extra). Apatinis kraštas (kairė krūtis). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  6. Kairės pažasties sarginiai limfmazgiai. Vienas limfmazgis su metastaze, 4,4 mm suformuota susiliejančių tubulinių struktūrų.  7. DEŠINĖ. Krūtyje - navikas (0,4 mm, 0,5 mm, 0,9 mm, 1 mm židiniai) suformuotas lizdais besidėstančių ląstelių gausia eozinofiliška, ryškia citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 1/10 DPRL.  Greta gausūs dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais ir solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.   2 limfmazgiai su sinusų histiocitoze ir antriniais folikulais.  8. KAIRĖ. Krūtyje - navikas (21 mm) infiltratyviu ekspansyviu frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais branduoliais ryškiomis nukleolėmis; mitozių 4/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais ir solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.   Limfovaskulinė naviko invazija.  9. Papildomas k.kruties viršutinis kr. Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.    10. Papildomas d.krūtis apatinis kr. Krūties audinys su kanaliukais, klotais dvisluoksniu ir hiperplastišku epiteliu su apokrinine metaplazija. Ryškūs koaguliacijos artefaktai.. 2. DCIS (3 blokas): C14 išlaikytas mioepitelinis sluoksnis.  7. Navikas (32, 35 blokai): Ck14(-).
answer:  0

 73%|███████▎  | 484/661 [07:24<03:11,  1.08s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas kairė krūtis ir kairės pažasties limfmazgiai. Krūtis 1921 g svorio, 31x22x10 cm. Odoje daugybiniai, rusvi, riboti, gruoblėtu paviršiumi, kiek iškilęs dariniai, didžiausias 1x1x0,2 cm, artimiausias nuo odos rezekcijos krašto nutolęs 0,5 cm.   Krūties audinyje, centrinėje dalyje - pilkšvas, standus, neaiškių ribų I navikas 25x15x10 mm, nuo giliojo rezekcijos krašto nutolęs 7 cm, nuo odos - 1 cm.   Nuo I naviko 2 cm atstumu - pilkšvas, standus, neaiškių ribų II navikas 10x10x6 mm, nuo giliojo rezekcijos krašto nutolęs 6 cm, nuo odos - 1,5 cm. I ir II navikus jungia fibrozė.   Rasti krūties 3 limfmazgiai iki 1,3 cm skersmens. Atskirai inde riebalinio audinio fragmentai, bendras dydis 8x7x2 cm. Rasta 15 limfmazgių iki 3,3 cm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT3(55 mm dydžio navikas)   pN1a(3-se/18 l/m su mts iki 10 mm)   pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pP1(perineurinis naviko plitimas)   pR0(radikalus pašalinimas).   Naviko imunotipas nustatytas priešoperacinėje biopsijoje:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.    Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, komedo tipo).  Įprastinė duktalinė hiperplazija. Apokrininė metaplazija.  Odos seborėjinė keratozė; dermalinis nevusas su seborėjine keratoze.. Odos dariniai: epidermio hiperplazija su formuojamomis raginėmis cistomis ir besiliejančiais akantotiniais pluoštais; viename iš darinių, dermoje stambūs brandžių nevocitų lizdai.   Spenelis: be patologijos.   Krūties audinyje - vienas netaisyklingo kontūro, 55 mm dydžio mikroskopiškai navikas, suformuotas smulkių lizdų, trabekulių ir pavienių tubulių (~5%). Naviko ląstelės su negausia eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais su blyškiu, tolygiu chromatinu ir aiškiomis eozinofiliškomis nukleolėmis. Mitozių navike iki 7/10DPRL.  Naviko plitimas endotelizuotuose spindžiuose ir perineuriškai.  Šalia naviko - gausūs dilatuoti kanaliukai su intraduktaliniais kribriforminiais, solidiniais, papiliniais proliferatais iš analogiškų navikui ląstelių, su komedonekroze ir mikrokalcifikatais spindžiuose.  Atokiau yra latakų su įprastine duktaline hiperplazija ir apokrinine metaplazija.  Krūties ir pažasties limfmazgiai (18): 3-se/18 limfmazgių - aukščiau aprašyto naviko metastazės iki 10mm, su ekstranodaliniu plitimu.. nan
answer:  0

 73%|███████▎  | 485/661 [07:25<03:03,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.  4. sektorius, planinis. 4. Krūties sektorius 9x7x4 cm, su odos lopu 6x3 cm, su speneliu. Oda šalia spenelio žymėta dviem siūlais. Pjūvyje, siūlu projekcijoje, balkšvas, standus, neaiškių ribų navikas 1,1x1,1x1 cm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, siekia odą ir spenelį, juos perauga.(navikas sudėtas visas). 1. pjūvio kraštai. Krūties fibrocistiniai pokyčiai.  2. pjūvio kraštai. Krūties fibrocistiniai pokyčiai.    3. sarginiai l/m - karcinomos mikrometastazė (1 mm) 1-me iš 4 limfmazgyje.    4. Krūties sektorius.   Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma  pT1b pN1mi pR0.  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.    Intraduktalinė papiloma (4 mm).. 1. pjūvio kraštai - Fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu, fokaliai apokrininė metaplazija.  2. pjūvio kraštai - Fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu, fokaliai apokrininė metaplazija.  3. sarginiai l/m - atipinių liaukinių struktūrų židinys 1 mm 1-me iš 4 limfmazgių.  4. Krūties sektorius. Odą (neišopėjusią) ir riebalinį audinį infiltruoja smulkios duktalinės struktūros, nedideli netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  Kompaktišku fibroziniu audiniu riboto darinio (4 mm) papilinės, tinklinės struktūros iš fibrozinės vaskuliarizuotos stromos padengtos dvisluoksniu epiteliu be atipijos.. nan
answer:  0

 74%|███████▎  | 486/661 [07:26<03:13,  1.11s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2). deš. pažasties sarginiai limfmazgiai, skubu  2(3a). Deš. krūties viršutinis kraštas, skubu  3(3b). deš. krūties apaptinis kraštas, skubu  4(1). Kairės krūties užspenelinis audinys, skubu  5(1a). Kairės pažasties sarginiai limfmazgiai, skubu  6(4). deš. krūties audinys, planinis  7(5). Kairės krūties audinys, planinis. 6. Krūties sektorius 6,5x4,7x2 cm su oda 5x3,5 cm. Krūties audinyje pilkšvas, standus, neaiškių ribų navikas 16x15x15 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos -  0,4 cm.  7. Krūties sektorius 12,5x11,5x2,5 cm su oda 5x1,2 cm. Krūties audinys fibrozuotas visame plote. Poodinis gilusis rezekcijos kraštas dažytas mėlynai.. 1(2/deš. pažasties sarginiai limfmazgiai)(EXTRA). Duktalinės karcinomos mikrometastazė 1/5 l/m (1,4 mm).  2(3a/deš. krūties viršutinis kraštas)(EXTRA). Krūties audinys.  3(3b/deš. krūties apaptinis kraštas)(EXTRA). Krūties audinys.  4(1/kairės krūties užspenelinis audinys)(EXTRA). Krūties audinys.  5(1a/kairės pažasties sarginiai limfmazgiai)(EXTRA). Reaktyvi limfadenopatija (6 l/m).  6(4/deš. krūties audinys). Krūties (dešiniosios) invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(15 mm) N(sn)1mi(mikromts 1/5 l/m), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).  7(5/kairės krūties audinys). Krūties (kairiosios) aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS)(solidinė, kribriforminė, papilinė,  komedo), pTis. DCIS struktūros 0,25 mm nuo poodinio rezekcijos krašto.. 1(2/deš. pažasties sarginiai limfmazgiai)(EXTRA). Viename (1) iš 5 l/m - žemiau (Nr.6) aprašyto naviko mikrometastazė (1,4 mm).  2(3a/deš. krūties viršutinis kraštas)(EXTRA). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(3b/deš. krūties apaptinis kraštas)(EXTRA). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  4(1/kairės krūties užspenelinis audinys)(EXTRA). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  5(1a/kairės pažasties sarginiai limfmazgiai)(EXTRA). 6 limfmazgiai su antriniais limfoidiniais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  6(4/deš. krūties audinys). Krūties audinyje - ribotas navikas (mikroskopiškai 15 mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių, lizdinių ir negausių (<10%) fokaliai besiliejančių tubulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 6/10 DPRL. Pavieniai mikrokalcifikatai. Limfovaskulinė ir perineurinė invazija. Šalia yra dilatuotų kanaliukų su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais.  7(5/kairės krūties audinys). Krūties audinyje, fibrozuotoje stromoje - dilatuoti ir vidutinio kalibro, fokaliai smulkesni kanaliukai su solidiniais, kribriforminiais ir papiliniais intraduktaliniais proliferatais (fokaliai su komedo nekroze ir kalcifikatais centre), suformuoti ląstelių eozinofiliška ar blyškoka citoplazma, vidutinio ir stambaus kalibro, apvaliais/ovaliais, polimorfiškais, dalis su aiškia nukleole branduoliais. DCIS struktūros 0,25 mm nuo žymėto poodinio rezekcijos krašto.. 7. 56 blokas: DCIS struktūros su išlaikytu CK14+ mioepiteliniu sluoksniu.
answer:  0

 74%|███████▎  | 487/661 [07:27<03:08,  1.08s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1a- viršutinis kraštas, skubu  2 ėminio aprašas: 1b- apatinis kraštas, skubu  3 ėminio aprašas: 2. Sarginiai limfmazgiai, skubu  3 ėminio aprašas: 3. Deš. krūties kvadrantas, planinis. 4(3). Krūties sektorius 11x4x4,5 cm su odos lopu 10x3 cm, žymėtas vielomis (atstumas tarp vielų 7,2 cm). Pjūvyje, I vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 14x14x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,8 cm, nuo odos - 3,5 cm. II vielos projekcijoje krūties audinys fibrozuotas 1,8x1,6 cm plote, nuo giliojo rezekcijos krašto nutolęs 0,1 cm.. 1. Krūties audinys.  2. Riebalinio audinio fragmentas.  3. Krūties duktalinės karcinomos mikrometastazė viename limfmazgyje (1/3 l/m, 1,5 mm).  4. Krūties invazyvi  mišri blogai diferencijuota (G3; 8 b. pgl. Nottingham) duktalinė (70%) ir mikropapilinė (30%) karcinoma, suminis TNM: pT1c(navikas 14 mm), pN1mi(1/3 l/m), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).. 1. Krūties audinyje smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2. Riebalinio audinio fragmentas be patologinių pokyčių.  3. Viename limfmazgyje iš 3  (planiniame ištyrime, po fiksacijos) (1/3 l/m) žemiau aprašyto naviko mikrometastazė, iki 1,5 mm skersmens.  4. Krūties audinyje - navikas (mikroskopiškai - 14 mm), suformuotas gausių lizdinių struktūrų su pavienių spindžių formacija ir mikropapilinių struktūrų iš ląstelių negausia eozinofiline citoplazma su ryškiai polimorfiškais, ovoidiniais, hiperchromiškais branduoliais, ryškiais branduolėliais. Mitozių navike 11/10DPRL. Limfovaskulinis naviko plitimas (LVI2). Greta naviko gausūs dilatuoti kanaliukai su solidiniais, kribriforminiais proliferatais, suformuotais analogiškų aukščiau aprašytoms ląstelių. Fibrozuotame krūties audinyje (II vielos projekcijoje) gausūs dilatuoti kanaliukai su solidiniais, kribriforminiais proliferatais, analogiškais aukščiau aprašytiems. Aplinkinis krūties audinys fibrozuotas su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu su fokalia apokrinine epitelio metaplazija.. Anksčiau atliktas tyrimas, B23-23730:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė karcinoma su mikropapiliniu komponentu.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai
answer:  0

 74%|███████▍  | 488/661 [07:28<02:59,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. (N2a) kraštai - extra  2. (N2b) kraštai - extra  3. (N3) Sarginis l/m - extra  4. (N1) Pašalintas sektorius - planinis tyrimas. 4(N1). Krūties sektorius 12,5x5,5x5 cm, su odos lopu 10x3 cm. Pjūvyje balkšvas, standus neaiškių ribų navikas 2,3x2x1,8 cm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1 cm. Aplink naviką fibrozės zona 5x4,5x3 cm.. 1(2a). Krūties fibrocistiniai pokyčiai.  2(2b). Krūties fibrocistiniai pokyčiai.  3(3). Reaktyvi limfadenopatija (2 l/m).  4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT2(2,3 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės naviko invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 10%.. 1(2a). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2(2b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(3). Sinusų histiocitozė, lipomatozė dviejuose (2) limfmazgiuose.  4(1). Krūties audinyje - navikas; solidines, trabekulines, negausias kribrozines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 3 / 10 DPRL.. 4(1). Navikas (13 blokas): HER2: silpnas(+) membraninis dažymasis 5% naviko ląstelių.
answer:  0

 74%|███████▍  | 489/661 [07:29<02:44,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 15 mm; II - 13 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas pavienėse ląstelėse.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas pavienėse ląstelėse.  Her2 imuninė reakcija: silpnas ar vidutinis dalies membranos nusidažyma
answer:  0

 74%|███████▍  | 490/661 [07:30<02:49,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas žymėtas dešinės krūties kvadrantas  - planinis tyrimas  2 ėminio aprašas: N2a kraštai   3 ėminio aprašas: N2b kraštai   4 ėminio aprašas: N3: dešinės pažasties sarginiai limfmazgiai  5 ėminio aprašas: N4: papildomas kraštas. 1. Krūties sektorius 8,5x4,5x5 su odos lopu 8,5x3,7 cm (žymėtas viela). Pjūvyje, viela žymėtoje vietoje, balkšvas, standus, gan aiškių ribų navikas 0,9x0,7x0,8 cm (sudėtas visas). Nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos - 4 cm.  2. Riebalinio fibrozinio audinio fragmentas 1,2x0,9x0,4 cm. v/m  3. Riebalinio fibrozinio audinio fragmentas 1,8x1x0,5 cm. v/m  4. Riebalinio audinio fragmentai 4,8x3x1 cm. Rasti 2 limfmazgiai 2,2 cm ir 0,8 cm.   5. Riebalinio audinio fragmentas 1,5x1x0,6 cm. v/m. 1. Krūties invazyvi duktalinė karcinoma (gerai diferencijuota, G1 / 4 balai pagal Nottingham);   pT1b(9 mm)   pLVI-0   pN(sn)1mi(1/2; 1,2 mm)   pR0(1,2 mm nuo krašto).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 3% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 12%.    Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS, kribrozinio tipo).    2. Krūties audinio nespecifiniai fibroziniai židiniai.   3. Krūties audinio nespecifiniai fibroziniai židiniai.   4. Karcinomos mikrometastazė 1-me/2 limfmazgyje.  5. Riebalinio audinio fragmentas be patologinių pokyčių.. 1. Tubulines (80%), pavienes smulkias kribrozines naviko struktūras formuoja stulpinės ląstelės su saikinga švelniai eozinofiline citoplazma, vidutiniškai polimorfiniais skeltais be nukleolės branduoliais; mitozių navike iki 1 / 10 DPRL.  Gretimai negausios tubulės su anallogiškų atipiniųląstelių tinkliniais proliferatais.   Invazinės struktūros 1,2 mm nuo giliojo krašto.  Intrvaskulinio plitimo nestebima.  2. Krūties audinio nespecifiniai fibroziniai židiniai.   3. Krūties audinio nespecifiniai fibroziniai židiniai.   4. Atipinio epitelio tinklinių struktūrų židinys 1,2 mm limfmazgyje (1-me/2).  5. Riebalinio audinio fragmentas be patologinių pokyčių.. Blokas 1:  CD31: stipri teigiama (+++) membraninė reakcija kraujagyslių endotelyje be atipinių struktūrų spindyje  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: r
answer:  10

 74%|███████▍  | 491/661 [07:30<02:36,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 12 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 74%|███████▍  | 492/661 [07:31<02:30,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1  biopsinis stulpelis. Biopsinis stulpelis 13 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma. Aukšto laipsnio duktalinė karcinoma in situ (DCIS, plokščias, kribriforminis tipas).     Imunofenotipas:   Estrogenų receptoriai: vidutinė reakcija 90% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 5% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.. Bioptate - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis lizdais ir trabekulėmis besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais ryškiomis stambiomis nukleolėmis; mitozių 3/10 DPRL. Greta dilatuoti latakais su intraduktaliniais plokščiais ir kribriforminiais proliferatais iš analogiškų navikui ląstelių.. Navikas:  Estrogenų receptoriai: (++)(brand. r-ja) 90%.  Progesterono receptoriai: (++)(brand. r-ja) 5%.  HER2: nusidažiusių naviko ląstelių membranų nėra.  Ki67 proliferacinis aktyvumas 10%.  E-cadherin(+++)(membr. r-ja) 100%.
answer:  0

 75%|███████▍  | 493/661 [07:32<02:48,  1.00s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas - extra;  2(1b)- Apatinis kraštas - extra;  3(2). Kairės krūties sarginiai limfmazgiai - extra;   4(3). Kairės krūties sektorius - planinis tyrimas;  5(4a). Papildomas viršutinis kraštas - planinis tyrimas;  6(4b). Papildomas viršutinis kraštas - planinis tyrimas;  7(5). Limfmazgiai - planinis tyrimas.. 4(3). Krūties sektorius 9x6,5x4 cm su oda 8x2,5 cm, žymėtas 2 vielomis, vienas kraštas žymėtas dviem siūlais. I vielos projekcijoje - balkšvas, standus, neaiškių ribų navikas 31x29x26 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 1,5 cm ;II vielos projekcijoje - I fibrozės zona 3x2,2x2 cm, susijungianti su naviku (bendras dydis su naviku - 44x36x19 mm ) ir II fibrozės zona - 1,4x1x0,9 cm, nuo I fibrozės nutolusi 0,5 cm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 4 cm. Siūlais žymėtas kraštas dažytas žalia, kitas kraštas- juoda spalva. 29 kasetėje, II fibrozės zonos pusė, žymėta žaliais dažais.  5(4a). Riebalinio audinio fragmentas 2x1x0,3 cm. v/m  6(4b). Riebalinio audinio fragmentas 2,5x1,5x0,4 cm. v/m  7(5). Riebalinio audinio fragmentai, bendras dydis 9x6x1,5 cm. Rasti 20 limfmazgiai iki 1,5 cm.. 1(extra). Viršutinis kraštas. Krūties invazyvi karcinoma (1,3 mm židinys). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 mikropapilinis, solidinis tipai).  2(extra). Apatinis kraštas. Krūties audinys.  3(extra). Kairės krūties sarginiai limfmazgiai. Duktalinės karcinomos metastazės limfmazgiuose (4/4 l/m iki 12 mm).  4. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) mišri duktalinė - mikropapilinė karcinoma, SUMINIS TNM: pT3(56 mm navikas)  pN3a(13/24 l/m MTS iki 14 mm) LVI-2(limfovaskulinė invazija). Navikas siekia sektoriaus rezekcijos kraštą. Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 mikropapilinis, solidinis tipai).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 35%.    5. Papildomas viršutinis kraštas. Krūties invazyvi karcinoma (2,4 mm židinys).  6. Papildomas viršutinis kraštas. Krūties audinys.  7. Limfmazgiai, planinis. Duktalinės karcinomos metastazės limfmazgiuose (9/20 l/m iki 14 mm). 1(extra). Viršutinis kraštas. Krūties audinyje tubulės ir lizdai suformuoti ląstelių vidutinio gausumo eozinofiliška citoplazma, polimorfiškais brnaduoliais. Greta dilatuoti latakai su intraduktaliniais solidiniais, mikropapiliniais proliferatais iš analogiškų ląstelių.  2(extra). Apatinis kraštas. Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3(extra). Kairės krūties sarginiai limfmazgiai. 4 iš 4 limfmazgių aprašyto naviko metastazės iki 12 mm su ekstranodaliniu plitimu.    4. Krūtyje - navikas infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, dominuojančiomis mikropapilinėmis struktūromis, besidėstančių ląstelių vidutinio gausumo eozinofiliška ryškia citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 25/10 DPRL.  Greta dilatuoti latakai su intraduktaliniais solidiniais, mikropapiliniais proliferatais iš analogiškų ląstelių.  5. Krūties audinyje mikropapilinės struktūros iš analogiškų aprašytam navikui ląstelių. Limfovaskulinė invazija.  6. Papildomas viršutinis kraštas. Krūties audinys su fibrozės zonomis, latakais klotais dvisluoksniu epiteliu.  7. Limfmazgiai. Duktalinės karcinomos metastazės limfmazgiuose. 31 blokas: Ck14(-); CD31+ endotelis.
answer:  0

 75%|███████▍  | 494/661 [07:33<02:35,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 5%, vietomis iki 10%.. Krūties audinį infiltruoja juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis netolygus visos membranos nusidažyma
answer:  0

 75%|███████▍  | 495/661 [07:34<02:37,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1a- viršutinis kraštas, skubu  2 ėminio aprašas: 1b- apatinis kraštas, skubu  3(2) ėminio aprašas: 2. Kairės pažasties sarginiai limfmazgiai, skubu  4(3) ėminio aprašas: 3. Kairės krūties sektorius, planinis. 4. Krūties sektorius 7,5x3x6,5 cm, su odos lopu 6x1,5 cm, žymėtas viela. Vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 10x8x8 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 2,6 cm. Navikas histologiniam ištyrimui sudėtas visas.. 1. Fibrocistiniai krūties pokyčiai.  2. Krūties lobulinė karcinoma in situ (LCIS).   3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 12 mm), pN0(sn)(0/3 l/n), LVI0(neidentifikuota). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.. 1. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu; pavieniai nežymiai dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais.  3. Trys limfmazgiai su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.  4. Krūties audinyje - navikas (12 mm mikroskopiškai), suformuotas smulkių lizdinių bei negausių tubulinių struktūrų iš vidutinio kalibro, vidutinio gausumo eozinofiline citoplazma ląstelių, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiais branduolėliais; mitozių 6/10 DPRL. Limfovaskulinis plitimas neidentifikuotas (LVI0). Invazyvus navikas nuo artimiausio rezekcijos krašto nutolęs per 5 mm. Greta naviko dilatuoti latakai, užpildytų solidinių bei kribriforminių proliferatų, suformuotų analogiškų navikui ląstelių.. nan
answer:  0

 75%|███████▌  | 496/661 [07:35<02:46,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.(N2a) - Kraštai.-skubus tyrimas be naviko  2.(N2b) - Kraštai.-skubus tyrimas be naviko  3.(N1) -  pašalintas kairės krūties kvadrantas - planinis tyrimas. N1- rentgeninis tyrimas- 2 navikai pašalinti  4(N3A) - papildomi kraštai  planinis tyrimas  5(N3B) - papildomi kraštai  planinis tyrimas. 3. Krūties sektorius 11,5x8x4,5 cm su oda 11x7,5 cm. Krūties audinyje, kvadrante - pilkšvas, standus, aiškių ribų navikas 52x20x20 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 1 cm. Poodyje, naviko projekcijoje (nuo naviko 0,4 cm atstumu (foto)), balkšvas standus darinys 10x8x6 mm.  4. Riebalinio audinio fragmentas 2x1,5x0,5 cm. v/m  5. Riebalinio audinio fragmentas 1,8x1x0,5 cm. v/m. 1(ekstra). Riebalinis - fibrozinis audinys.  2(ekstra). Krūties invazyvi karcinoma (0,4 mm židinys). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, komedo tipas).  3. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT3(m)(52 mm, 10 mm navikai) pN0(sn)(0/1 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).  4. Papildomas kraštas. Riebalinis - fibrozinis audinys. Reaktyvi limfadenopatija (1 l/m).  5. Papildomas kraštas. Krūties audinio fibrozė.    Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 60%.. 1(ekstra). Riebalinis fibrozinis audinys.   2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu. Fokaliai latakas su intraduktaliniais solidiniais su komedo nekroze kompleksais, suformuotais analogiškų aprašytoms (Nr.2 naviko ląstelių), smulkūs nubyrantys kompleksai ir pabiros naviko ląstelės šalia.  3. Krūtyje - navikas (52 mm, 10 mm navikai) infiltratyviu augimo frontu, suformuotas struktūromis, lizdais ir solidiniais plotais besidėstančių ląstelių  vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais bei gigantiniais, pleomorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 13/10 DPRL.  Gausi perinavikinė limfoplazmocitinė ir polimorfonuklearinė infiltracija, nekrozės zonos.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaus kanaliukų zonos.  4. Papildomas kraštas. Riebalinis - fibrozinis audinys. Vienas limfmazgis su sinusų histiocitoze.  5. Papildomas kraštas. Krūties audinys su židinine fibroze ir negausiais latakais, klotais dvisluoksniu epiteliu.. 2. Navikas, 10 blokas: CK7/CK14 nelieka medžiagos pjūviuose.  Navikas(16 blokas):  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 60%.  CK5+ išla
answer:  100

 75%|███████▌  | 497/661 [07:36<02:37,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Punktuotas kairės krūties BIRADS V darinys, paimti 2 biopsiniai stulpeliai medžiagos histologiniam ištyrimui.. 2 biopsiniai stulpeliai: I - 15 mm; II - 15 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 3% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 40%.. Krūties audinį 2-se bioptatuose infiltruoja iki 11 mm :   - duktalinės pavienės struktūros, trabekulės;  - epitelinių smulkių / vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje citoplazmoje;   - su mitozėmis iki 1/10 DPRL (didesnė dalis ląstelių artefaktiškai deformuotos).   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 40% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 3% naviko
answer:  0

 75%|███████▌  | 498/661 [07:37<02:37,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas markiruotas kairės krūties darinys su vielute - planinis tyrimas  2 ėminio aprašas: N2a kraštai - planinis tyrimas  3 ėminio aprašas: N2b kraštai - planinis tyrimas  4 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis - planinis tyrimas. 1. Krūties sektorius 5x4x3 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, spikulinis navikas 16x14x16 mm, nuo artimiausio rezekcijos krašto nutolęs 0,5 cm.    2. Riebalinio audinio fragmentas 2x1,5x0,7 cm. v/m   3. Riebalinio audinio fragmentas 2x1x0,4 cm. v/m  4. Riebalinio audinio fragmentas 4x3x2 cm. Rastas limfmazgis 2,5 cm.. 1. Krūties invazyvi gerai diferencijuota (G1,  5b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(14 mm navikas) pN1a(sn)(7 mm MTS 1/1 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stipri reakcija 95% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 30% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.    2. Kraštai (N2a). Krūties audinio fibrozė.  3. Kraštai (N2a). Krūties audinio fibrozė.  4. Krūties duktalinė karcinomos metastazė limfmazgyje (1/1 l/m 7 mm MTS).. 1. Krūtyje - navikas (14 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, struktūromis ir negausiais lizdais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais apvaliais, branduoliais ryškiomis nukleolėmis; mitozių 8/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių.   2. Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  4. 1 limfmazgis su aprašyto naviko metastaze 7 mm.. Navikas:  HER2: silpna dalies membranos r-j 1 % naviko ląstelių.
answer:  0

 75%|███████▌  | 499/661 [07:38<02:29,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 16 mm.. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham sistemą) duktalinė karcinoma (12,5 mm mikroskopiškai).  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 plokščias, solidinis tipai).  Naviko imunofenotipas:  Estrogenų receptoriai: stipri reakcija, 90% naviko ląstelių.  Progesterono receptoriai: stipri reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 7%.. Fibroziniame audinyje (1 biopsiniame stulpelyje) plinta tubulinės (40 %), kribriforminės struktūros ir smulkūs lizdai. Naviko ląstelės su negausia, šviesiai eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais ar netaisyklingo kontūro, vidutiniškai polimorfiškais branduoliais, fokaliai vesikuolizuotu chromatinu ir smulkiomis nukleolėmis. Mitozių navike <1/10DPRL.  Šalia naviko dilatuoti kanaliukai su intraduktaliniais "plokščiais" ir solidiniais proliferatais iš analogiškų navikui ląstelių.. Blokas 1:  CD117: neigiama reakcija.   CK14: neigiama reakcija invazyviame navike, CK14+ mioepitelis DCIS struktūrose.  Estrogenų receptoriai: stipri (+++) reakcija, 90% naviko ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 90%
answer:  1

 76%|███████▌  | 500/661 [07:39<02:21,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 14 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis ar silpnas branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis 20%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai, vietomis ryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis ar silpnas branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 15%
answer:  0

 76%|███████▌  | 501/661 [07:40<02:34,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1) Kraštai - extra  2(N2) kraštai - extra  3(N3) sarg. l/m - extra  4(N4) Deš. kvadrantas su naviku, planiškai. 4. Krūties sektorius 10x8,x5x3cm, su odos lopu 9,5x3 cm. Sektoriaus vieno krašto paviršiuje - standesnė zona 1,5x1x0,5 cm. Tame pačiame inde atskiras poodinis krūties sektorius 8x3x3,5 cm, pjūvyje su balkšvu naviku 1,3x1,3x1,3 cm, su kalcifikatais, nuo artimiausio rezekcijos krašto nutolęs mažiau 0,1 cm.. 1(ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.    2(ekstra). "Kraštai": fibrozuotas krūties-riebalinis audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (4 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT1c (navikas ~13 mm skersmens) N0(sn) (0/4 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   LVI-0 (definityvios limfovaskulinės invazijos nėra).   Kalcifikatai.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties lobulinė intraepitelinė neoplazija (LCIS).  Krūties žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS: kribriforminis tipas).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė duktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).. 1(ekstra). "Kraštai": fibrozuotas, vaskuliarizuotas brandžių lipocitų suformuotas audinys; be naviko.   2(ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": keturi (4) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.     4. NAVIKAS (du naviko fragmentai: I - 1,4 mm ir II - 12 mm; abu fragmentai siekia sektorių rezekcijos kraštus - radiniai atitinka vieno naviko fragmentaciją operacijos metu):   krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", solidinės naviko struktūros, suformuotos mažai kohezyvių vidutiniškai polimorfiškų ląstelių, negausia ar vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 11/10 DPRL. Navike yra kalcifikuotos fibrozės židinių, fibroadenomatozinių stromos pokyčių.   APLINKA: zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais.   Šalia naviko - keli nedideli kribriforminiai intraduktaliniai polimorfiškų kohezyvių naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, papiliarizuotomis struktūromis apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS).   SEKTORIŲ REZEKCIJOS KRAŠTAS: abiejų krūties sektorių viename iš rezekcijos kraštų - naviko struktūros; priešingos pusės sektorių kraštuose - koaguliuotas krūties audinys.. 4. Navikas (blokas 14):  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.
answer:  0

 76%|███████▌  | 502/661 [07:41<02:26,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~18x18 mm dydžio navikas dešiniojoje krūtyje ties 10 val. periferinėje dalyje, paimti trys biopsiniai stulpeliai histologijai.. 3 fragmentuoti biopsiniai stulpeliai: I - 4 mm; II - 5 mm; III - 6 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 reakcija neigiama 1+.  Ki67+ 3%.  Žemos ir vidutinio laipsnio intraduktalinė karcinom (DCIS/DIN1-2).. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  Aplink invazinio naviko židinius dilatuoti kanaliukai su intraduktaliniais neryškiai ar vidutiniškai polimorfiškų ląstelių proliferatais.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 vidutinis dalies membranos nusidažymas 40% naviko ląstelių.   Ki67+ 3%.
answer:  0

 76%|███████▌  | 503/661 [07:42<02:22,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but: Deš. krūties, apatinių kvadrantų riboje, ties ~6h, periferinėje dalyje ~6 mm dydžio hipoechogeniškas, nevisai aiškių kontūrų darinys, paimti 2 biopsiniai stulpeliai (čiuopiamas).  2 but: Deš. krūties, apatinių kvadrantų rigoje, ties ~6h, vidurinėje dalyje ~10 mm dydžio, hipoechogeniškas, heterogeniškas darinys, kiek neaiškių kontūrų.. 1. 2 biopsiniai stulpeliai: I - 13 mm; II - 15 mm.  2. 5 fragmentuoti biopsiniai stulpeliai: I - 17 mm; II - 15 mm; III - 12 mm; IV - 8 mm; V - 9 mm.. 1. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma.  2. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma.  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: silpnas(+) branduolinis dažymasis 2%.   HER2 imunohistocheminė reakcija neigiama (0 balų).  Ki67: 80%.. 1. Solidines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne blyškiai-saikingai eozinofiline citoplazma, vidutinio kalibro apvalios formos saikingai netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 35 / 10 DPRL; nekrozė navike (~20%).  2. Analogiškas aukščiau aprašytam navikas.. Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: silpnas(+) branduolinis dažymasis 2%.   HER2: nusidažiusių naviko ląstelių nėra.   Ki67: 80%.
answer:  1

 76%|███████▌  | 504/661 [07:43<02:24,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pjūvio kraštai - extra;  2. Pjūvio kraštai - extra;  3. Sarginiai l/m - exstra;  4. Sektorius - planinis.. 4. Krūties sektorius 10,5x4,5x3,5 cm su oda 9,5x2,5 cm, žymėtas viela. Krūties audinyje, kvadrante - pilkšvas, standus navikas 9x9x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 2,7 cm.. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(10 mm navikas) pN0(sn)(0/3 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija). Vidutinio - žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1 DIN2, kribriforminis ir papilinis tipai).    Imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (0+).  Ki67: 15%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (10 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais branduoliais ryškiomis nukleolėmis.  mitozių 3/10 DPRL. Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu.. Navikas:  HER2: silpnas dalies membranos nusidažymas pavienėse ląstelėse.
answer:  0

 76%|███████▋  | 505/661 [07:43<02:16,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 10 mm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35-40%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 30/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 12% naviko ląstelių.  Ki67+ 35
answer:  1

 77%|███████▋  | 506/661 [07:44<02:13,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, planinis;  2. pjūvio kraštai, planinis;  3. sarginiai l/m, planinis;  4. sektorius, planinis.. 1. Riebalinio audinio fragmentas 3,5x2,5x0,7 cm. v/m  2. Riebalinio audinio fragmentas 3,5x2x1 cm. v/m  3. Riebalinio audinio fragmentai, bendras dydis 5x4x2 cm. Rasti 4 limfmazgiai iki 1,3 cm.  4. Krūties sektorius 11x6x5 cm su odos lopu 10x2,5 cm, žymėtas viela. Vielos projekcijoje, pilkšvas, standus, apvalios formos navikas 0,9x0,7x0,8 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 1,8 cm, nuo odos – 2,5 cm.. N1-2: Krūties audinio fragmentai be naviko.  N3: Limfmazgiai (4 l/m) be naviko židinių; pN0(sn).  N4: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (9mm).. N1-2: Krūties audinio fragmentai be naviko.  N3: Limfmazgiai (4 l/m) su lipomatoze, be naviko židinių.  N4: Krūties audinyje 9mm navikas: negausios duktalinės struktūros, nedideli solidiniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.. nan
answer:  0

 77%|███████▋  | 507/661 [07:45<02:21,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1) - kraštai - extra  2(N2) - kraštai - extra   3(N3) - Sarginiai l/m - extra  4(N4) - Kairės krūties sektorius.   5(N5) - Likusi k.pažasties narveliena.. 4. Krūties sektorius 9,5x6x5,5 cm su odos lopu 9,5x5 cm, žymėtas viela. Vielos projekcijoje, pjūvyje balkšvas, standus, neaiškių ribų I navikas 12x11x9 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,4 cm, nuo odos – 2,8 cm. Nuo I naviko 0,5 cm atstumu - balkšvas, standus, neaiškių ribų II navikas 16x11x10 mm, nuo artimiausio rezekcijos krašto nutolęs 0,6 cm, nuo odos 3,5 cm. Šalia navikų - fibrozės zona 5,5x3x2,5 cm.  5. Riebalinio audinio fragmentai, bendras dydis 11x7x1,5 cm. Rasta 16 limfmazgių iki 1,3 cm skersmens.. 1. Krūties audinys.  2. Krūties audinys.  3. Krūties duktalinės karcinomos metastazė limfmazgyje (1/1 l/m; 11,7mm; ekstranodalinis naviko plitimas).  4. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(m)(du naviko židiniai: 12mm ir 16mm) pN1a(1/17 l/m; 11,7mm; ekstranodalinis naviko plitimas); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).  IHC reakcijos atliktos VPC:B23-115 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%."  Krūties fibrocistiniai pokyčiai; sklerozuojanti adenozė.. 1. Riebalinis audinys su fibrozinėmis septomis, pavieniais latakėliais, klotais dvisluoksniu epiteliu.  2. Riebalinis audinys su fibrozinėmis septomis, latakėliais, klotais dvisluoksniu epiteliu.  3. Vienas(1) limfmazgis su žemiau aprašyto naviko metastaze (11,7mm; ekstranodalinis naviko plitimas).  4. Krūties audinyje - du naviko židiniai (12mm ir 16mm), formuojami solidinių/lizdinių, trabekulinių, pavienių netaisyklingų liaukinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais; Limfo-Vaskulinė naviko Invazija (LVI) smulkiose kraujagyslėse/limfagyslėse; navike iki 3 mitozių/10 DPRL. Aplinkinis krūties audinys su fibrozės zonomis, fokaliai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, smulkių latakėlių, klotų dvisluoksniu epiteliu, organoidinės proliferacijos fibrozinėje stromoje židiniai.  5. Šešiolika(16) limfmazgių be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.. nan
answer:  0

 77%|███████▋  | 508/661 [07:46<02:16,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas ~7x8x10 mm dydžio sunkiai išsiskiriantis iš aplinkinio audinio deformacijos plotas/darinys kairiojoje krūtyje centrinėje dalyje vos lateraliau spenelio, paimti trys biopsiniai stulpeliai histologijai + į biopsijos vietą implantuotas TUMARK Professional nitinolio žymeklis.. 3  biopsiniai stulpeliai: I - 12 mm; II - 10 mm; III - 10 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 10%.. Krūties audinį infiltruoja negausios duktalinės struktūros, nedideli netaisyklingi kribroziniai kompleksai ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 90% naviko ląstelių.  Ki67+ 1
answer:  0

 77%|███████▋  | 509/661 [07:47<02:12,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1biopsinis stulpelis. Biopsinis stulpelis 8 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 80% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 3%.. Bioptate, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, ovalaus kontūro branduoliais; mitozių 0/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 80%.  HER2: nusidažiusių naviko ląstelių membranų nėra.  Ki67 proliferacinis aktyvumas 3%.  E-cadherin(+++)(membr. r-ja) 100%.
answer:  0

 77%|███████▋  | 510/661 [07:48<02:17,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  N1- retroareoliarinė sritis - be naviko  N2- sarginis l/m -  be naviko  N3- pašalinta liauka - planinis patologinis tyrimas  Skubus N3 Ro tyrimas - 16 mm navikas pašalintas. 3. Krūties liauka be odos 11,5x8x1 cm, pjūvyje balkšvas, elastingas, aiškių ribų navikas 1,6x0,8x1,2 cm, nuo poodinio rezekcijos krašto(dažytas žaliai) nutolęs 0,2 cm, nuo giliojo(dažytas mėlynai) - 0,1 cm. Aplinkinis krūties audinys fibrozuotas su cistomis iki 0,6 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Reaktyvi limfadenopatija (2 l/m).  3. Krūties invazyvi blogai diferencijuota (G3; 9 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 16 mm), pN0(sn)(0/2 l/m), LVI0(neidentifikuota). Estrogenų receptoriai: reakcijos nėra. HER2:reakcijos nėra (0). Progesterono receptoriai: reakcijos nėra. Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija.. 1. Krūties audinyje židininė fibrozė, gausios krūties lobulės ir gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar epiteliu su fokalia apokrinine metaplazija.  2. Du limfmazgiai su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.  3. Krūties audinyje navikas (16 mm makroskopiškai), infiltratyviu augimo frontu, suformuotas stambių, besiliejančių solidinių ir kribriforminių struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, stambiais, ryškiais polimorfiškais, hiperchromiškais, smulkiai grūdėtu chromatinu branduoliais su ryškiais branduolėliais. Gausi perinavikinė limfocitų infiltracija. Mitozių navike 25/10DPRL. Limfovaskulinė naviko invazija neidentifikuota(LVI0). Navikas nuo rezekcijos krašto nutolęs per 1 mm. Aplinkiniame krūties audinyje, fibrozuotoje stromoje, gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu bei keli nežymiai dilatuoti kanaliukai su paprasta epitelio hiperplazija. Židininė apokrininė epitelio metaplazija.. Blokas 6:  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: reakcijos naviko ląstelių membranoje nėra.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.
answer:  0

 77%|███████▋  | 511/661 [07:49<02:12,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 4 stulpeliai histologinės medžiagos.. Gauti 3 biopsiniai stulpeliai: I - 9 mm; II - 11 mm; III - 12 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.. Krūties audinį infiltruoja duktalinės struktūros, netaisyklingi kribroziniai kompleksai ir trabekulės iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 10% naviko ląstelių.  Ki67+ 1
answer:  0

 77%|███████▋  | 512/661 [07:49<02:07,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  4 biopsiniai stulpeliai. 4 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 9 mm; III - 12 mm; IV - 12 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+, HER2 geno amplifikacija nenustatyta.  Ki67+ 10%.. Krūties audinį infiltruoja negausios duktalinės struktūros ir netaisyklingi kribroziniai/solidiniai kompleksai iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas ar vidutinis visos membranos nusidažymas 10% naviko ląstelių.
answer:  0

 78%|███████▊  | 513/661 [07:50<02:09,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu  3(2). Deš. pažasties sarginiai limfmazgiai, skubu   4(3). Deš. krūties sektorius, planinis. 4.Krūties sektorius 8x3,5x5,5 cm su odos lopu 6,5x1,8 cm žymėtas viela. Vielos projekcijoje pilkšvas, standus, neaiškių ribų navikas 9x5x4 mm, nuo giliojo rezekcijos krašto nutolęs 1cm, nuo odos - 3,7 cm.. 1(1a). Viršutinis kraštas. Krūties audinys be patologinių pokyčių.    2(1b). Apatinis kraštas. Krūties audinys be patologinių pokyčių.    3(2). Dešinės pažasties sarginiai limfmazgiai. Limfmazgiai (2) be karcinomos ląstelių.    4(3). Dešinės krūties sektorius. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.    pT1b(9 mm) pLVI-0 pN(sn)0 pR0.. 1(1a). Viršutinis kraštas. Krūties audinys be patologinių pokyčių.  2(1b). Apatinis kraštas. Krūties audinys be patologinių pokyčių.  3(2). Dešinės pažasties sarginiai limfmazgiai. Limfmazgiai (2) be karcinomos ląstelių.  4(3). Dešinės krūties sektorius. Krūties audinį infiltruoja duktalinės struktūros  (<10 proc.) ir smulkūs kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL. Plitimo kraujagyslėse ar operaciniuose kraštuose nestebima.. nan
answer:  0

 78%|███████▊  | 514/661 [07:51<02:03,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 bioptatai 22 mm 14 G adata, dviejuose - kalcinatai.. 3 fragmentuoti biopsiniai stulpeliai: I - 15 mm; II - 17 mm; III - 16 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 25%.. Krūties audinį infiltruoja negausūs smulkūs solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 80% naviko ląstelių.  Ki67+ 25%
answer:  1

 78%|███████▊  | 515/661 [07:52<02:00,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 8 mm; II - 9 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.. Krūties audinį infiltruoja juostos ir trabekulės iš neryškiai polimorfiškų nedidelių apvalių ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 4
answer:  0

 78%|███████▊  | 516/661 [07:53<02:05,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2). Kairės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko.  2(1). Pašalinta kairė krūtis - planinis tyrimas.. 2. Krūtis 1336 gramų svorio, 27x22x7 cm. Krūties audinyje, vidinių kvadrantų riboje - balkšvas, standus, neaiškių ribų navikas 52x39x30 mm, nuo odos nutolęs 2,2 cm, nuo giliojo rezekcijos krašto - 3 cm.. 1(2). Reaktyvi limfadenopatija (3 l/m).  2.  Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) lobulinė karcinoma, TNM: pT3(53 mm naviko židinys), LVI0(neidentifikuota), pN0(sn)(0/3 l/m). Krūties lobulinė karcinoma in situ (LCIS). HER2:reakcijos nėra (0). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).  Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3). Spenelio Pageto liga.. 1(2). Trys limfmazgiai (3 l/m) su sinusų histiocitoze.  2. Krūties audinyje - navikas (53 mm mikroskopiškai), suformuotas juostų ir trabekulių iš vidutinio kalibro eozinofiline citoplazma ląstelių, vidutiniškai polimorfiškais branduoliais su pavieniais paryškėjusiais branduolėliais; mitozių 4/10 DPRL. Limfovaskulinis plitimas neidentifikuotas(LVI0). Šalia naviko dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais; greta naviko negausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš negausia eozinofiline citoplazma ląstelių su hiperchromiškais, polimorfiškais branduoliais su ryškiais branduolėliais. Greta nežymiai dilatuoti kanaliukai kloti dvisluoksniu epiteliu su fokalia epitelio hiperplazija.  Spenelis: epidermyje stambiais lizdais ir pavieniui, visame epitelio aukštyje plinta navikas, suformuotas stambių epitelioidinių ląstelių su polimorfiškais, hiperchromiškais branduoliais.. Blokas 8(atipinės ląstelės epidermyje):  CK7: (+++)citop.r-ja 100%;  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  Blokas 10:  E-Cadherin: (-)neigiama r-ja;  Blokas 14:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  1

 78%|███████▊  | 517/661 [07:54<02:00,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 7 mm; II - 14 mm.. Gerai diferencijuota (G1 , 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros, nedideli kribroziniai iš neryškiai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 8%
answer:  0

 78%|███████▊  | 518/661 [07:54<01:57,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 9 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 1-2% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros ir kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 1-2% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląsteli
answer:  0

 79%|███████▊  | 519/661 [07:55<01:54,  1.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 11 mm; II - 10 mm; III -10 mm.. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25-30%.. Krūties audinį infiltruoja negausios duktalinės struktūros, netaisyklingi kribroziniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 7/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: vidutinis dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+
answer:  25

 79%|███████▊  | 520/661 [07:56<02:07,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1a- viršutinis kraštas, skubu  2 ėminio aprašas: 1b- apatinis kraštas, skubu  3 ėminio aprašas: 1c- papildomai viršutinis kraštas, skubu  4 ėminio aprašas: 2- Kairės pažasties sarginiai limfmazgiai, skubu  5 ėminio aprašas: 3- kairės krūties kvadrantas, planinis. 5(3). Krūties sektorius 15x10x5 cm su odos lopu 13x3,5 cm. Pjūvyje balkšvas, standus, neaiškių ribų navikas 17x13x10 mm, nuo artimiausio rezekcijos krašto nutolęs 2,5 cm, nuo odos – 1,7 cm. Krūties audinys fibrozuotas.. 1(1a)(Extra). Krūties invazyvi duktalinė karcinoma (3,6 mm židinys). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).  2(1b)(Extra). Krūties audinys.  3(1c)(Extra). Krūties audinys.  4(2)(Extra). Duktalinės karcinomos metastazės 2/4 l/m (7 mm ir 4,5 mm).   5(3). Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(18 mm) N(sn)1a(mts 2/4 l/m), LVI-2(limfovaskulinė invazija).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.. 1(1a)(Extra). Krūties audinyje, šalia koaguliuoto krašto - židinys (3,6 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių smulkių tubulinių ir trabekulinių naviko struktūrų, suformuotų ląstelių saikinga eozinofiliška citoplazma, vidutinio kalibro, ovaliais ir nereguliariais, kiek polimorfiškais, hiperchromiškais branduoliais; mitozių neidentifikuota. Aplink dilatuoti kanaliukai su kribriforminiais ir negausiai solidiniais intraduktaliniais proliferatais, suformuotais ląstelių su vidutiniu ir ryškesniu branduolių polimorfizmu.  2(1b)(Extra). Krūties audinyje, kiek fibrozuotoje stromoje - negausūs vidutinio kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(1c)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  4(2)(Extra). 2 iš 4 limfmazgių - žemiau (Nr.5) aprašyto naviko metastazės (7 mm ir 4,5 mm).   5(3). Krūties audinyje - ribotas navikas (mikroskopiškai 18 mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių, lizdinių ir negausių (<10%) smulkių tubulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 4/10 DPRL. Limfovaskulinė invazija. Šalia yra dilatuotų kanaliukų su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais.   Aplinkiniame krūties audinyje yra kiek dilatuotų kanaliukų, klotų suplokštėjusiu epiteliu bei kanaliukų su epitelio hiperplazija, grupės stambių kanaliukų su apokrinine metaplazija. Žymėtas rezekcijos kraštas be naviko plitimo.. 1. Navikas (27 blokas):  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra (0).
answer:  0

 79%|███████▉  | 521/661 [07:57<02:01,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai.. 2 biopsiniai stulpeliai: I - 14 mm; II - 14 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67+ 10
answer:  0

 79%|███████▉  | 522/661 [07:58<01:56,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35%.. Krūties audinį infiltruoja netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai ar ryškiai polimorfiškų ląstelių, mitozių iki 14/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: vidutinis dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+
answer:  35

 79%|███████▉  | 523/661 [07:59<02:02,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.(1a)- viršutinis kraštas, skubu  2.(1b)- apatinis kraštas, skubu  3.(2) Deš. pažsties sarginiai limfmazgiai, skubu  4.(3) deš. krūties sektorius, planinis. 4. Krūties sektorius 7x3,5x4,5 cm su oda 6,5x1,5 cm, žymėtas viela. Krūties audinyje, kvadrante - pilkšvas, standus navikas 13x10x5 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 1 cm, nuo odos - 2,2 cm.. 1(1a). Krūties audinys.  2(1b). Krūties audinys.  3. Krūties duktalinės karcinomos mikrometastazė limfmazgyje (1/3 l/m; iki 1,05mm).  4. Krūties invazyvi, gerai diferencijuota (G1; 4 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(navikas - 13mm) pN1mi(sn)(1/3 l/m; iki 1,05mm); LVI-2 (Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse); perineurinis naviko plitimas (PN). Rezekcijos kraštas be naviko.  IHC reakcijos atliktos VPC:B23-19125 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 1-2% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.". 1(1a). Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  2(1b). Krūties audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  3. Iš rastų trijų(3) limfmazgių, viename(1) žemiau aprašyto naviko mikrometastazė (1,05mm).  4. Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas netaisyklingų duktalinių (65%), kribriforminių, solidinių/lizdinių, trabekulinių struktūrų iš vidutinio kalibro ląstelių, nežymiai polimorfiškais branduoliais; navike iki 2 mitozių/10 DPRL. Limfo-Vaskulinė naviko Invazija (LVI) smulkiose kraujagyslėse/limfagyslėse; perineurininis naviko plitimas (PN). Rezekcijos kraštas be naviko.. nan
answer:  0

 79%|███████▉  | 524/661 [08:00<02:07,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)-kraštas-extra-be naviko    2(N2b)-kraštas-extrabe naviko    3(N3)- sarginis (3)- be naviko    4(N1)- pašalintas sektorius -planinis patologinis tyrimas  N1- skubus rentgeninis tyrimas - navikas pašalintas. 4. Krūties sektorius 11x4,5x4 cm su odos lopu 10x3,5 cm, žymėtas metileno mėliu. Krūties audinyje balkšvas neaiškių ribų, standus navikas 1,5x1,3x1 cm (sudėtas visas), nuo artimiausio rezekcijos krašto (dažytas juoda spalva) nutolęs 0,2 cm, nuo odos – 1,5 cm. Šalia naviko fibrozės zona 4x1,8x1 cm (bendras dydis su naviku 4,7 cm).. 1(2a). Fibrocistiniai krūties pokyčiai.  2(2b). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(navikas - 15mm) pT0(sn)(0/3 l/m); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).  IHC/FISH reakcijos atliktos VPC:B23-33188 tyrime:  "Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta, FISH tyrimo rezultatas interpretuojamas įvertinus HER2 IHC tyrimą kaip neigiamas(žr. molekulinio tyrimo aprašymą ir pastabas).  Ki67: proliferacinis indeksas 15%."  Krūties žemo/vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis ir kribriforminis tipas).. 1(2a). Krūties audinys su fibrozės zonomis, pavieniais dilatuotais latakėliais, klotais dvisluoksniu epiteliu.  2(2b). Krūties audinys su fibrozės zonomis, pavieniais dilatuotais latakėliais, klotais dvisluoksniu epiteliu.  3. Trys(3) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4. Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas solidinių/lizdinių, trabekulinių struktūrų iš vidutinio/stambaus kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai, vietomis ryškiai polimorfiškais, hiperchromiškais branduoliais su ryškiomis nukleolėmis; navike iki 10 mitozių/10 DPRL; Limfo-Vaskulinė naviko Invazija (LVI) smulkiose kraujagyslėse/limfagyslėse. Aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais ir kribriforminiais atipinių ląstelių (su nedidelio ir vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS).. nan
answer:  0

 79%|███████▉  | 525/661 [08:01<02:04,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 biopsinis stulpelis iš BI-RADS 5 darinio ties 10 val.   2 but. 3 biopsiniai stulpeliai iš ploto su mkk ties 6 val.. 1. Biopsinis stulpelis 12 mm.   2. 3 fragmentuoti biopsiniai stulpeliai: I - 10 mm; II - 7 mm; III - 8 mm.. 1. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 8 mm);  (G2; 6 b. pgl. Nottingham sist.)1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 20%.  Žemo laipsnio intraduktalinė intraepitelinė neoplazija (DIN1/DCIS).    2. Krūties fibrocistiniai pokyčiai.. 1. Krūties audinį 1-me bioptate infiltruoja iki 8 mm :   - duktalinės pavienės struktūros ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.  Gretimai analogiškų atipinių ląstelių intraduktaliniai solidiniai proliferatai.  2. Fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ; kalcifikatų nestebima.. Blokas 1:  CK14: neigiama (-) atipinių difuziškai plintančių struktūrų ląstelių membranoje  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose,
answer:  20

 80%|███████▉  | 526/661 [08:02<02:05,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)-kraštas - extra - be naviko  2(N2b)-kraštas - extra - be naviko  3(N3)-sarg. l/m - extra - be naviko   4(N1)-sektorius - extra. Skubus rentgeninis tyrimas - matomas 9 mm navikas, 6 mm navikas - nesidiferencijuoja.. nan. 1(2A). Krūties fibrocistiniai pokyčiai. Intraduktalinė papiloma (0,15 cm).  2(2B). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (1 l/m).  4(N1). Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė ("bazinio" imunofenotipo) adenokarcinoma, TNM (Nr.1-Nr.4): pT1b(0,8 cm) pN(sn)0 (0/1 l/m). LVI0(limfovaskulinės naviko invazijos nėra).  ATSKIRAS/SMULKESNIS FRAGMENTAS: Krūties fibrocistiniai pokyčiai. Krūties fibroadenoma (0,3 cm).  ---  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: silpnas(+) branduolinis dažymasis 2%.   HER2 imunohistocheminė reakcija neigiama (0 balų).  Ki67: 80%.. 1(2A). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; 0,15 cm skersmens intraduktalinės proliferacijos židinys.  2(2B). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N3). Nežymi sinusų histiocitozė viename (1) limfmazgyje.  4(N1). KRŪTIES SEKTORIUS: Krūties audinyje - navikas: Solidines naviko struktūras formuoja ląstelės su kiek gausesne tamsoka amfofiline citoplazma, stambaus kalibro apvalios formos netaisyklingais/polimorfiškais su aiškiomis nukleolėmis branduoliais; mitozių navike iki 42 / 10 DPRL.  ATSKIRAS/SMULKESNIS FRAGMENTAS: Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; fibrozuotos stromos su suspaustais kanaliukais gan aiškiai ribotas darinys.. 4(N1). Navikas (blokas 11):  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.   Progesterono receptoriai: silpnas(+) branduolinis dažymasis 2% naviko ląstelių.   HER2: nusidažiusių naviko ląstelių nėra.  CK5: vidutinis(++) membraninis dažymasis 8
answer:  10

 80%|███████▉  | 527/661 [08:03<01:58,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm ilgio.. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100 % naviko ląstelių.  Progesterono receptoriai: stipri reakcija 40 % naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 45 %.. Bioptate - desmoplastiškoje stromoje ir riebaliniame audinyje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais, trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 67/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100 %.  Progesterono receptoriai: (+++)(brand. r-ja) 40 %.  HER2: neigiama reakcija.  Ki67 proliferacinis aktyvumas 45 %.
answer:  1

 80%|███████▉  | 528/661 [08:04<01:59,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1-2. pjūvio kraštai, planinis. 3. sarginiai l/m, planinis. 4. sektorius, planinis.. 1. Riebalinio audinio fragmentas 3,5x2x0,5 cm. v/m  2. Riebalinio audinio fragmentas 4,5x1,5x0,8 cm. v/m  3. Riebalinio audinio fragmentai, bendras dydis 4,5x3x1 cm. Rasti 4 limfmazgiai, didžiausias 2 cm.  4. Krūties sektorius 8x7,5x3,5 cm, su odos lopu 8x4,5 cm. Krūties audinyje, pjūvyje aiškių ribų, hemoragiškas, heterogeniškas 22x17x11 mm navikas, nuo artimiausio rezekcijos krašto nutolęs 0,5 cm, nuo odos - 1,3 cm. 1,5 cm atstumu nuo naviko, standi fibrozės zona 1,3x1x0,4 cm, nuo artimiausio rezekcijos krašto nutolusi 0,1 cm, nuo odos - 2 cm.. N1 ir N2: Krūties audinys be naviko.  N3: Limfmazgiai (4 l/m) be naviko metastazių; pN0(sn).  N4: Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham); pT2(22mm).  Žemo laipsnio intraduktalinė karcinoma (0,2mm židinys; DCIS/DIN1, kribriforminė).  Krūties fibrocistiniai pokyčiai, fibroadenomatozinė hiperplazija).. N1 ir N2: Krūties ir riebalinis audinys be naviko. Pavienės duktalinės hiperplazijos ir cistiškai dilatuotų latakų zonos.  N3: Limfmazgiai (4 l/m) su reaktyviais pokyčiais, be naviko metastazių.  N4: Krūties audinyje 22mm navikas: mucinų sankaupose netaisyklingi kribroziniai bei solidiniai kompleksai iš minimaliai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  Fokaliai krūties audinys su fibrozės zonomis ir gausiais, dalis cistiškai dilatuotais ar suspaustais latakais, užpildytais eozinofilišku sekretu, klotais blyškiu dvisluoksniu, fokaliai hiperplastišku epiteliu.  Fibrozės zonoje dilatuotas kanaliukas su intraduktaliniais monomorfiškų ląstelių kribroziniais proliferatais (0,2mm židinys).. Fibrozė (30 ir 31 blokai):   CK5: stiprus citoplazminis 100% nusidažymas mioepitelinėse ląstelėse.
answer:  0

 80%|████████  | 529/661 [08:04<01:53,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 15 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 6%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 6%.
answer:  0

 80%|████████  | 530/661 [08:05<01:55,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a) - viršutinis kraštas, skubu  2(1b) - apatinis kraštas, skubu  3(2) - deš. pažasties sarginiai limfmazgiai, skubu  4(3) - deš. krūties sektorius, planinis  4(3) - deš. krūties sektorius, planinis. 4. Krūties sektorius 7x5,8x3,3 cm be odos. Krūties audinyje, pilkšvas standus, gan aiškių ribų navikas 17x12x10 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm.. 1(1a). Krūties audinys.  2(1b). Krūties audinys.   3(2). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(navikas - 17mm) pN0(sn)(0/3 l/m); LVI-0(Limfo-Vaskulinė naviko Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-29562 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.". 1(1a). Riebalinis audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  2(1b). Riebalinis audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.   3(2). Trys(3) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4. Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas solidinių lizdinių/trabekulinių, kribriforminių, duktalinių (~15%) struktūrų iš vidutinio kalibro ląstelių, vidutiniškai, vietomis ryškiai polimorfiškais, hiperchromiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 18 mitozių/10 DPRL.. nan
answer:  0

 80%|████████  | 531/661 [08:06<01:50,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 14  mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja smulkios duktalinės struktūros, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20x% naviko ląstelių.  Ki67+ 8%
answer:  0

 80%|████████  | 532/661 [08:07<02:01,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - be naviko.  2(2b). Kraštai - be naviko.  3. Sarginis l/m(3) - be naviko.  4(1). Sektorius - planinis patologinis tyrimas N1- skubus rentgeninis tyrimas - navikas pašalintas.. 4(1). Krūties sektorius 8,5x5,5x4 cm su oda 7,5x5 cm. Krūties audinyje, kvadrante - pilkšvas, standus, ribotas, skiltėtas navikas 20x20x15mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 0,4 cm.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(2b, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė);  kalcifikatai; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 19,5 mm) N0(sn) (0/3 l/m),   LVI-0 (definityvi limfovaskulinė invazija neidentifikuota).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis, papilinis, komedo tipai). Krūties lobulinė intraepitelinė neoplazija (LCIS). Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė).. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu; kalcifikatai; be naviko.   3(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4(1). NAVIKAS (mikroskopiškai didžiausias naviko matmuo - 19,5 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės, dominuojančios kribriforminės, trabekulinės, lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais fokaliai vezikulizuotais ar skeltais branduoliais su smulkiomis nukleolėmis; mitozių iki 5/10 DPRL. Naviko spindžiuose sekretas ar nekrotinis detritas su PMN, makrofagais. Fokaliai negausi perinavikinė limfocitinė infiltracija.   APLINKA: šalia naviko - kribriforminiai, papiliniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija ar epitelio papiliarizacija, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu. Intralobuliniai smulkių gan monotoniškų, mažai kohezyvių ląstelių proliferatai.   SEKTORIAUS REZEKCIJOS KRAŠTAS: intraduktaliniai naviko kompleksai nuo artimiausio koaguliuoto krašto nutolę 5 mm.. 4(1). Navikas (blokas 16):  HER2: silpna (+) necirkuliari reakcija, 10% naviko ląstelių membranoje.
answer:  0

 81%|████████  | 533/661 [08:08<02:00,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- Deš. pažasties sarginiai limfmazgiai, skubu  4(3)- Deš. krūties kvadrantas, planinis. 4. Krūties sektorius 6,5x3x10 cm, su odos lopu 3,5x2 cm, žymėtas viela. Vielos projekcijoje pilkšvas, standus aiškių ribų navikas 12x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 6 cm.. 1(ekstra). Krūties audinys.  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(12 mm navikas) pN0(sn)(0/4 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto - vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN3-DIN2, kribriforminis ir papilinis tipai). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. 1(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu.      3(ekstra). 34limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.    4. Krūtyje - navikas (12 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, trabekulinėmis struktūromis, lizdais pavienėmis mikropapilomis besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais - stambiais, polimorfiškais, nereguliaraus kontūro ir ovaliais branduoliais ryškiomis nukleolėmis; mitozių 5/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių.. Navikas:  EMA citopl. r-ja. HER2 silpnas dalies membranos nusidažymas 10%.
answer:  1

 81%|████████  | 534/661 [08:09<01:53,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 11 mm; II - 8 mm; III - 10 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros ir smulkūs kribroziniai/solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 8
answer:  0

 81%|████████  | 535/661 [08:10<01:48,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 7 mm.. Invazinė tubulinė karcinoma (mažiausiai iki 8 mm);  (G1; 3 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 3%.. Krūties audinį 2-se bioptatuose infiltruoja iki 8 mm :   - duktalinės struktūros (100% viso naviko);  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai stromoje ir spindžiuose. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 3% naviko ląstelių.  Progesterono receptoriai: stipri (++
answer:  95

 81%|████████  | 536/661 [08:11<01:49,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 biopsinis stulpelis iš kairės krūties BI-RADS 5 darinio   2 but. 3 biopsiniai stulpeliai iš latakų su kalcinatais bei riboto darinio dešinėje krūtyje.. 1. 1 biopsinis stulpelis 15 mm ilgio.   2. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 7 mm; III - 9 mm.. 1. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 10%. Karštame taške 20%.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.    2. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 10%.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.. 1.Krūties audinį infiltruoja netaisyklingi kribroziniai kompleksai ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.  2. Krūties audinį infiltruoja duktalinės struktūros (<10%), netaisyklingi kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. 1. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) cirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių. Karštame taške 20%.  Progesteron
answer:  1

 81%|████████  | 537/661 [08:11<01:45,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 12 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 15%.
answer:  0

 81%|████████▏ | 538/661 [08:12<01:45,  1.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  18 G automatine biopsine adata punktuotas ~5x8 mm dydžio neaiškių ribų izoechogeniškas darinys su aplinkine spikuline deformacija dešiniojoje krūtyje ties 12 val. vidurinėje dalyje (atitinkantis MG matomą spikulinės defomacijos židinį), paimti trys biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 10 mm; II - 14 mm; III - 9 mm.. Įtariama invazinė gerai diferencijuota duktalinė arba tubulinė karcinoma (G1; menkas atipinių struktūrų kiekis):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 0%.    Kompleksinis sklerozuojantis pažeidimas: sklerozuojanti adenozė.  Atipinė duktalinė hiperplazija (ADH).. Krūties audinys su smulkiais, šakotais, suspaustais kanaliukais, klotais dvisluoksniu epiteliu. Dalyje kanaliukų kribriforminiai proliferatais su negausiais mikrokalcifikatais, kloti epitelis apvaliais, monotoniškais, hiperchromiškais branduoliais. Stroma fibrozuota, su elastozės zonomis. Tarp šių pokyčių - 3 mm segmente pavienės smulkios tubulės be mioepitelio (CK14-), be branduolių atipijos.. CK14- mioepitelis smulkiuose latakuose. Kribriforminės struktūros CK14+.  Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 0% navi
answer:  0

 82%|████████▏ | 539/661 [08:13<01:49,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - be naviko.  2(2b). Kraštai - be naviko.  3. Sarginis l/m(4)- be naviko.  4(1). Pašalintas sektorius - planinis patologinis tyrimas. N1-skubus rentgeninis tyrimas - navikas pašalintas.. 4. Krūties sektorius 5,5x2,5x5 cm, su odos lopu 5x1,5 cm, žymėtas viela. Krūties audinyje, vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 16x12x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 2 cm. Navikas sudėtas visas.. 1(2a)(Extra). Riebalinis audinys.  2(2b)(Extra). Riebalinis audinys.  3(Extra). Reaktyvi limfadenopatija (4 l/m).  4(1). Krūties invazyvi blogai diferencijuota (G3; 8 balai pagal Nottingham) metaplastinė (šeivinių ląstelių) karcinoma (su lygiųjų raumenų diferenciacija), SUMINIS TNM: pT1c(15 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Imunofenotipas:   Estrogenų receptoriai: silpnas/vidutinis branduolių nusidažymas 25% naviko ląstelių.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.   HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.   Ki67: 2%.. 1(2a)(Extra). Brandus riebalinis audinys su fibroze ir kraujagyslėmis.  2(2b)(Extra). Brandus riebalinis audinys su fibroze ir kraujagyslėmis.  3(Extra). 4 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.  4(1). Krūties audinyje - ribotas navikas (mikroskopiškai 15 mm), suformuotas fibrozuotoje stromoje pluoštais besidėstančių šeivinių ląstelių šviesiai eozinofiliška citoplazma, vidutinio ir kiek stambesnio kalibro, ovaliais ir pailgais, polimorfiškais, dalis su aiškia nukleole branduoliais; yra ląstelių stambiais, lobulizuotais branduoliais. Mitozių iki 10/10 DPRL. Negausi židininė perinavikinė MMN infiltracija.. 4. Navikas (14 blokas):   Estrogenų receptoriai: silpnas/vidutinis branduolių nusidažymas 25% naviko ląstelių.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.   HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.   Proliferacinis aktyv
answer:  10

 82%|████████▏ | 540/661 [08:14<01:52,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pjūvio kraštai, ekstra.  2. Pjūvio kraštai, ekstra.  3. Sarginiai l/m, ekstra.   4. Sektorius, planinis.. 4. Krūties sekotrius 12,5x8,5x3,5 cm su odos lopu 10x2,5cm žymėtas viela. Pjūvyje, viela žymėtoje vietoje - balkšvas 1,5x1,3x1,2 cm, nuo odos nutolęs 4,5 cm, nuo artimiausio rezekcijos krašto - 0,3 cm.Greta naviko - fibrozinis audinys 2x2x1,6 cm plote.Rezekcijos kraštas dažytas mėlynai, tarp pjūvių - juodai. Rastas intramamarinis limfmazgis 0,6 cm.. 1. Krūties audinys.  2. Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 15 mm), pN0(sn)(0/2 l/m), LVI2 (limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).   HER2: reakcija neigiama (1+).. 1. Krūties audinyje židininė fibrozė bei smulkūs kanaliukai kloti dvisluoksniu epiteliu.  2. Fibrozuotame krūties audinyje keli smulkūs kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Šalia gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar epiteliu su apokrinine epitelio metaplazija; Kkli kanaliukai su fokalia epitelio hiperplazija.  3. Vienas limfmazgis su sinusų histiocitoze (1 l/m).  4. Krūties audinyje, hialinizuotoje stromoje plinta navikas (15 mm mikroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių, trabekulinių ir tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su polimorfiškais, hiperchromiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 8/10DPRL. Limfovaskulinis plitimas smulkiose limfagyslėse/kraujagyslėse(LVI2). Krūties audinyje gausūs dilatuoti kanaliukai užpildyti solidinių ir kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta gausūs dilatuoti kanaliukai kloti dvisluoksniu epiteliu ar epiteliu su apokrinine metaplazija. Vienas intramamarinis limfmazgis su sinusų histiocitoze.. Blokas 15:  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.
answer:  0

 82%|████████▏ | 541/661 [08:15<01:46,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 4 biopsiniai stulpeliai. 4 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 12 mm; III - 3 mm, IV - 2 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: stipri reakcija 25% naviko ląstelių.   Her2 imuninė reakcija: neigiama (0).   Ki67 proliferacinis aktyvumas 8%.. 4 bioptatai: fibrozinėje stromoje su negausiais lipocitais pabirai ar grandinėlėmis dėstosi naviko ląstelės negausia/vidutinio gausumo švelniai eozinofiliška citoplazma, vidutiniškai polimorfiškais, ovoidiniais ar kiek nereguliaraus kontūro branduoliais prašviesėjusiu chromatinu su išryškėjusia smulkia nukloele; mitozių 6/10 DPRL.. Navikas:   PanCK(+++)(citop. r-ja) 100%.  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.   Progesterono receptoriai: (+/++)(brand. r-ja) 25%.   HER2: reakcijos naviko ląstelėse nėra (0).   Ki67 proliferacinis aktyvumas 8%.   E-cadherin(-).
answer:  0

 82%|████████▏ | 542/661 [08:16<01:43,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 1 biopsinis stulpelis iš  I lygio pakitusio l/m , labai įtartino dėl mts   2 but. 3 biopsiniai stulpeliai iš BI-RADS 5 darinio. 1. Biopsinis stulpelis 10 mm ilgio.  2. 3 fragmentuoti biopsiniai stulpeliai: I - 17 mm; II - 5 mm; III - 3 mm.. N1: Limfmazgio bioptatas su duktalinės karcinomos metastaze.  N2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. N1: Limfmazgio bioptatas su žemiau aprašyto naviko židiniais.  N2: Krūties audinį infiltruoja smulkūs duktaliniai ir kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių.  Ki67+ 1
answer:  1

 82%|████████▏ | 543/661 [08:17<01:39,  1.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 9 mm; III - 7 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 5%.. Bioptatuose (3/3) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais , grandinėlėmis besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, polimorfiškais, vidutinio kalibro, nereguliaraus kontūro branduoliais; mitozių 0/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas - vidutinis dalies membranos nusidažymas 40% naviko ląstelių.  Ki67 proliferacinis aktyvumas 5%.  E-cadherin(+++) membr. r-ja 100%
answer:  0

 82%|████████▏ | 544/661 [08:17<01:37,  1.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  17 G koaksialine adata punktuotas 13x24 mm neaiškių kontūrų ir ribų, šakotas hipoechogeninis darinys, slopinantis ultragarso signalą, dešiniojoje krūtyje ties 7-8 val. labiau link periferijos, čiuopiamo darinio vietoje, BIRADS4c, 18 G automatine biopsine adata paimti keturi biopsiniai stulpeliai histologijai.. 4 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 9 mm; III - 7 mm; IV - 3 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5%.. Trabekulines, pavienes smulkias duktalines naviko struktūras formuoja ląstelės su negausia ar švelniai eozinofiline citoplazma, smulkiais ar vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 3 / 10 DPRL.. Navikas (2 blokas):  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 10% naviko ląstelių
answer:  1

 82%|████████▏ | 545/661 [08:18<01:34,  1.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 9 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai, trabekulės iš ryškiai polimorfiškų ląstelių, mitozių iki 16/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 30
answer:  1

 83%|████████▎ | 546/661 [08:19<01:39,  1.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 sarginiai l/m, ekstra.  2 ėminio aprašas: 1 pjūvio kraštai, ekstra.  3 ėminio aprašas: 2. pjūvio kraštai, ekstra.  4 ėminio aprašas: 4. sektorius, planinis.. 4.  Krūties sektorius 7,5x5x3,5 cm su odos lopu 5x2,5 cm. Pjūvyje balkšvas, standus, skiltėtas navikas 22x16x13 mm nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos – 2 cm.. 1(3)(ekstra). Reaktyvi limfadenopatija (4 l/m).  2(1)(ekstra). Krūties audinys.   3(2)(ekstra). Krūties audinys.   4. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma, suminis TNM: pT2(22 mm navikas) N0(sn)(4 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). Gausūs intranavikiniai limfocitai (TILs). R0(radikali rezekcija).     Naviko imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  Androgenų receptoriai: silpna reakcija 5% naviko ląstelių.  Ki67: proliferacinis indeksas 80%.  HER2:reakcijos nėra (0).. 1(3)(ekstra). 4 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.  2(1)(ekstra). Nežymiai fibrozuotas krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu.   3(2)(ekstra). Nežymiai fibrozuotas krūties audinys su smulkiais kanaliukais, klotais dvisluoksniu epiteliu.   4. Krūties audinyje - navikas, suformuotas solidinių kompleksų su pavienių spindžių formacijomis, trabekulių ir lizdų. Naviko ląstelės poligonalinės, su gausoka šviesiai eozinofiliška citoplazma fokaliai su negausiais PAS+ mucinais, stambiais, apvaliais ir netolygaus kontūro, ryškiai polimorfiškais branduoliais blyškiai grūdėtu chromatinu, dalis su makronukleolėmis. Mitozių iki 25/10 DPRL. Naviką supa fibrozinė stroma su gausia monomorfonuklearų infiltracija. Naviko nekrozė ~10%.. Blokas 14:  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  Ki67: reakcija branduoliuose, 80% naviko ląstelių.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  CK5: silpna/stipri (+/+++) membraninė reakcija 4
answer:  10

 83%|████████▎ | 547/661 [08:20<01:43,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a)-kraštas - extra - be naviko    2(N2b)-kraštas - extra - be naviko    3(N1)- sektroius- - planinis patologinis tyrimas N1 - skubus rentgeninis tyrimas - navikas .- Atsisakė nuo pažasties duobės l/m - pašalinimo.. 3. Krūties sektorius 11x8x5 cm su odos lopu 10x4,5 cm, žymėtas viela, atskirai tame pačiame inde viela, neprisitvirtinusi prie krūties audinio. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 0,8x0,6x0,5 cm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos – 5 cm.. 1. Krūties fibrocistiniai pokyčiai.  2. Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis/kribriforminis; židinys - 2,7mm).  3. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sist.) duktalinė karcinoma, pT1a(navikas - 4,5mm); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-40706 tyrime:   "Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 8%."  Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; kribriforminis, mikropapilinis tipas; -komedo tipo nekrozės, mikrokalcifikatai).. 1. Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu.  2. Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu. Krūties audinyje - dilatuotas latakas (2,7mm) su solidiniais, kribriforminiais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS).  3. Krūties fibroziniame audinyje - navikas(mikro - 4,5mm), formuojamas netaisykingų duktalinių, kribriforminių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 4 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su kribriforminiais, mikropapiliniais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS).. 2. Blokas 8:  DCIS: CK14+ mioepitelinės ląstelės periferijoje.   3. Blokas 10, 11:  Navikas be CK14+ mioepitelinių ląstelių sluoksnio.  DCIS: CK14+ mioepitelinės ląstelės periferijoje.
answer:  0

 83%|████████▎ | 548/661 [08:21<01:39,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas kairės krūties apatinio lateralinio kvadranto darinys, paimti 3 biopsiniai stulpeliai medžiagos histologiniam ištyrimui.. 3 biopsiniai stulpeliai: I - 15 mm; II - 15 mm; III - 7 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 b. pgl Nottingham sist.) duktalinė karcinoma   (plitimas mažiausiai iki 16,5 mm mikroskopiškai).  Naviko imunofenotipas:  Estrogenų receptoriai: silpna (+) reakcija, 20% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%.. Fibroziname audinyje (3 biopsiniuose stulpeliuose) - trabekulinės, lizdinės, tubulinės (<10 %) struktūros. Naviko ląstelės su negausia, eozinofiliška citoplazma, vidutinio kalibro, netaisyklingo kontūro, vidutiniškai polimorfiškais branduoliais. Mitozių navike iki 1/10DPRL.. Blokas 1:  Estrogenų receptoriai: silpna (+) reakcija, 20% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 30% naviko ląstelių.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliu
answer:  0

 83%|████████▎ | 549/661 [08:22<01:37,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Tyrimo Nr. XXIIIBO-4848. Krūties navikas. Makroskopinis aprašymas : 3 pilkšvo, vietomis gelsvo, volelio formos audinio fragmentai 0,6-2 cm ilgio. 1. Konsultacijai gauta:  - 1 parafino blokas (žymėtas "XXIIIBO-4848");  - 6 histologiniai preparatai (žymėti ""XXIIIBO-4848"", dažyti HE, Ki67, p63, ER, PR, HER2 metodais).    Atlikti HER-2 geno amplifikacijos tyrimą FISH metodu (HER2).. PAPILDYTA  Krūties invazyvi duktalinė karcinoma (ne mažiau kaip gerai diferencijuota / G1 / 5 balai pagal Nottingham).     Estrogenų receptoriai: silpnas-vidutinis branduolių nusidažymas 80% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: ribinė (2+).  Ki67: iki 5%.  ---  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).. Tubulines (70%), negausias smulkias kribrozines naviko struktūras formuoja ląstelės su saikinga švelniai eozinofiline citoplazma, smulkiais ar kiek stambesnio kalibro kiek netaisyklingais, dalis su smulkia nukleole branduoliais; mitozių navike iki 1 / 10 DPRL.. Navikas  Estrogenų receptoriai: silpnas-vidutinis branduolių nusidažymas 80% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas visos membranos nusidažymas 20% naviko ląstelių.
answer:  0

 83%|████████▎ | 550/661 [08:23<01:43,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a kraštai - skubus tyrimas  2. N2b kraštai - skubus tyrimas  3. N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas  4. N1: pašalintas dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 9,5x6x3 cm su oda 9x3 cm. Odoje rusvas, smulkiai gruoblėtu paviršiumi, iškilęs I darinys 0,7x0,7x0,1 cm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm. Nuo darinio 0,3 cm atstumu pilkšvas, ribotas II darinys 1x0,6x0,4 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm. Krūties audinyje, pilkšvas, standus, neaiškių ribų navikas 16x14x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 2 cm.. 1,2(ekstra). Riebalinis audinys.  3(ekstra). Reaktyvi limfadenopatija (5 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1c(17 mm navikas) pN0(sn)(0/5 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, solidinis tipas). Lobulinė karcinoma in situ (LCIS). Odos seborėjinė keratozė.    Imunofenotipas:   Estrogenų receptoriai: stiprus ir vidutinis branduolių nusidažymas 40% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. 1,2(ekstra). Riebalinis audinys su negausiomis fibrozinėmis septomis.  3(ekstra). 5 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (17 mm) infiltratyviu augimo frontu, suformuotas trabekulinėmis struktūromis, lizdais, grandinėlėmis ir pabirai bei negausiomi stubulėmis (Ecad-) besidėstančių ląstelių negausia ir vidutinio gausumo ryškia eozinofiliška citoplazma, vidutiniais - stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 3/10 DPRL.  Greta dilatuoti latakia ir lobulės iš analogiškų navikui ląstelių; Negausūs dilatuoti kanaliukai su intraduktaliniais solidiniais proliferatais iš ląstelių vidutiniškai polimorfiškais branduoliais.   Odoje epidermio dariniai suformuotas bazaloidinių ląstelių su fokaline bazinio sluoksnio hiperpigmentacija ir pavienėmis raginėmis cistomis.. Navikas:  E-cadherin(+) trūkinėjanti membr. r-ja  Ki67 proliferacinis aktyvumas ---- %.  CK5+ išlaikytas mioepitelinis sluoknsis, heterogeniška populiacija hiperplazijos zonose.
answer:  0

 83%|████████▎ | 551/661 [08:24<01:37,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. sarginis l/m, ekstra.   2. deš krūtis, planinis.. 2. Krūtis 703 gramų svorio, 18,5x13,5x3,5 cm. Krūties audinyje, centrinėje dalyje - balkšvas, standus, nelygiais kraštais navikas 1,5x1,3x0,8 mm, nuo odos nutolęs 1,4 cm, nuo artimiausio rezekcijos krašto - 4,5 cm.. N1: Limfmazgis (1 l/m) be naviko; pN0(sn).  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c (15mm).. N1: Limfmazgis (1 l/m) be naviko.  N2: Krūties audinyje 15mm navikas: kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 8/10 DPRL.  Rezkcijos kraštas be naviko.. nan
answer:  0

 84%|████████▎ | 552/661 [08:25<01:44,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. kairė krūtis su kairės pažasties l/m, planinis. Krūtis 1552 g svorio, 24x22x7 cm, su pažasties narveliena 8x8x2 cm, spenelis įtrauktas.   Spenelio projekcijoje, balkšvas standus I navikas 1,5x1,5x0,9 cm, nuo artimiausio rezekcijos krašto nutolęs 6 cm, nuo odos - 0,7 cm.   5,5 cm nuo I naviko, II balkšvas standus, kiek neaiškių ribų navikas - 0,7x0,6x0,6 cm, nuo artimiausio rezekcijos krašto nutolęs 0,7 cm, nuo odos - 4,5 cm.   7 cm nuo I naviko, balkšvas, standus aiškių ribų I mazgas 0,7x0,6x0,6 cm, nuo artimiausio rezekcijos krašto nutolęs 7 cm.   5 cm nuo I mazgo, analogiškas balkšvas II mazgas 0,6x0,4x0,4 cm, nuo artimiausio rezekcijos krašto nutolęs 5 cm.   Krūties odoje rusvas, elastingas mazgas 0,6x0,5x0,1 cm, nuo artimiausio odos rezekcijos krašto nutolęs 1,4 cm.   Pažasties narvelienoje rasta 16 limfmazgių iki 2 cm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė-mikropapilinė karcinoma;   pT(m)1c(15 mm, 7 mm, 1 mm, 2,5 mm)   pN2a(7/16 ; ekstranodalinis plitimas)   pR0 (radikalus pašalinimas).  Karcinomos metastazės limfmazgyje imunotipas:  HER2: reakcija neigiama (1+).  Imunotipas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.    Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS; kribrozinio tipo).  Krūties fibroadenoma.  Kapiliarinė odos hemangioma.. Krūties audinio 1-ą (15 mm), 2-ą (7 mm) naviką, 2-ą mazgą (1 mm) ir atsitiktinį židinį (2,5 mm) krūties audinyje formuoja infiltruojančios pavienės duktalinės ir gausios pseufopapilinės/trabekulinės struktūros iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL. Operaciniai kraštai be matomų pokyčių (artimiausias 2-as navikas - 3 mm).  Analogiškų ląstelių tinklinės intraduktalinės struktūros negausiuose latakuose aplink invazinius židinius.  1-as mazgas (6 mm) ir atsitiktinai rastas 4 mm mazgas: ribotas navikas, suformuotas kolageninės stromos su suspaustais šakotais ir negausiais smulkiais latakais, klotais dvisluoksniu epiteliu.  Analogiškų ląstelių iki 13 mm metastazės 7-se/16 limfmazgiuose; stebimas ekstranodalinis plitimas.  Odoje gausiai kompaktiškai besidėstančių kapiliarų suformuotas odos darinys.. Blokas 17:  EMA: stipri teigiama (+++)  necirkuliari (išorinė) membraninė reakcija 100 proc. atipinėse struktūrose  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.
answer:  0

 84%|████████▎ | 553/661 [08:26<01:49,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Galutinė patologinė diagnozė: Krūties invazyvi duktalinė karcinoma, 0,4 mm židinys (1/5 bioptatų). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, solidinis tipas(2/5 bioptatų). Naviko imunofenotipas: Estrogenų receptoriai: 100%. Progesterono receptoriai: neigiama reakcija. Her2 imuninė reakcija: neigiama (1+). Ki67 20%.. 4(1). Krūties liauka 320 gramų svorio, 12x14x5 cm su odos lopu (apatinėje krūties dalyje) 6,5x2,2 cm. Krūties audinyje, 10x11x4,5 cm plote, balkšva, standi, netaisyklingų kontūrų, besiliejanti fibrozės zona; sustandėjusi ir formuojanti balkšvą zoną, apatiniame lateraliniame kvadrante 2,5x2x2 cm plote; fibrozės zona siekia rezekcijos kraštą pospenelinėje zonoje, nuo giliojo rezekcijos krašto nutolusi 0,1 cm; fibrozės zona su hemoragijomis.  5(4). Riebalinio audinio fragmentai, bendras dydis 3x2x0,5 cm. Rasti 7 limfmazgiai iki 1 cm. v/m. 1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Duktalinės karcinomos metastazė limfmazgyje 3 mm (1/1 l/m).    4. Krūties vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma su daline mikropapiline ir mucinine diferenciacija, SUMINIS TNM: pT2(m)(25 mm, 8 mm, 7 mm, 2,3 mm, 2,2 mm, 1 mm navikai) pN1a(sn)(3/6 l/m MTS iki 5 mm) LVI-2(limfovaskulinė invazija). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 kribriforminis, solidinis, komedo tipai), DCIS nuo priekinio rezekcijos paviršiaus nutolęs 0,8 mm, nuo giliojo - 0,6 mm.    Naviko imunofenotipas (biopsijoje):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 20%.    5. Papildomi limfmazgiai: duktalinės karcinomos metastazės limfmazgiuose (2/5 l/m iki 5 mm). Riebalinis audinys.. 1(ekstra). Krūties audinys su fibrozės zonomis kanaliukais ir lobulėmis, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis kanaliukais ir lobulėmis, klotais dvisluoksniu epiteliu.  3(ekstra). 1 limfmazgis su aprašyto naviko metastaze 3 mm.    4. Krūtyje - navikas (mm, 8 mm, 7 mm, 2,3 mm, 2,2 mm, 1 mm navikai) infiltratyviu augimo frontu, suformuotas trabekulinėmis struktūromis, lizdais, mikropapilinėmis struktūromis su aplinkiniais ekstarląsteliniais mucinais besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais,  nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 7/10 DPRL. Limfovaskulinė invazija.  Greta gausūs dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių; DCIS nuo paviršinio rezekcijos krašto nutolęs 0,8 mm, giliojo - 0,6 mm  Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaus kanaliukų zonos.. HER2: silpnas dalies membranos nusidažymas 30% naviko ląstelių.
answer:  0

 84%|████████▍ | 554/661 [08:27<01:40,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 8 mm; II - 9 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 10%.
answer:  0

 84%|████████▍ | 555/661 [08:28<01:34,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 14 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja netaisyklingi kribroziniai/solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 84%|████████▍ | 556/661 [08:29<01:42,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a). Viršutinis kraštas, skubu  2(1b). Apatinis kraštas, skubu  3(2). Deš. pažasties sarginiai limfmazgiai, skubu  4(3). Deš. krūties sektorius, planinis. 4(3). Krūties sektorius 12,5x9x6 cm su odos lopu 9x5 cm. Pjūvyje balkšvas, standus, neaiškių ribų I navikas 2,7x2x2 cm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos – 2,2 cm. 1,5 cm atstumu nuo I-ojo naviko balkšvas, standus, neaiškių ribų II navikas 0,4x0,6x0,6 cm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 1,5 cm, nuo odos - 2,6 cm. Bendras didžiausias navikų matmuo 3,6 cm.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas riebalinis audinys; be naviko.   2(1b, ekstra). "Apatinis kraštas": fibrozuotas krūties audinys; be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(3). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT2(m) (navikai: I - 27 mm; II - 7 mm) N0(sn) (0/2 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2:reakcijos nėra (0).    Krūties lobulinė intraepitelinė neoplazija (LCIS; pleomorfinis ir konvencinis variantas).  Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotas, brandžių lipocitų suformuotas audinys; be naviko.   2(1b, ekstra). "Apatinis kraštas": fibrozuotas krūties audinys su dilatuotais ar suspaustais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.    4(3). NAVIKAS (du židiniai: I - 27 mm; II - 7 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", fokaliai vangiai mazguotos fokaliai "kohezyvesnės" solidinės naviko struktūros, suformuotos mažai kohezyvių vidutiniškai polimorfiškų ląstelių, negausia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais hiperchromiškais branduoliais; fokaliai mitozių iki 22/10 DPRL; fokaliai negausūs intranavikiniai limfocitai; mikrokalcifikatai. Nedideli židiniai su puriu jungiamuoju audiniu, dilatuotomis kraujagyslėmis, fokalinė fibrozė su hemosiderofagais, pavieniais limfocitais (g.b. ankstesnės biopsijos zonos). Limfovaskulinė naviko invazija smulkiose šakose.    APLINKA: zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais; dalis su nekrozės zonomis. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: nežymiai fibrozuotas riebalinis audinys; be naviko.. 4(3). Navikas (blokas 17):  HER2: reakcijos naviko ląstelių membranoje nėra.  Navikas (blokas 22): E-Cadherin(+/++/+++) trūkinėjanti membraninė r-ja ~30% naviko ląstelių; p120-Catenin(+) citoplazminė r-ja, su fokaliai išryškėjančia trūkinėjančia membranin
answer:  30

 84%|████████▍ | 557/661 [08:29<01:34,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpeliai. Biopsinis stulpelis 14 mm ilgio.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis iki 20%.. Krūties audinį infiltruoja netaisyklingi kribroziniai/solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 10
answer:  0

 84%|████████▍ | 558/661 [08:31<01:37,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pjūvio kraštas, ekstra.  2. Pjūvio kraštas, ekstra.   3. Sarginiai l/m, ekstra.   4. Sektorius, planinis.. 4. Krūties sektorius 10x7,5x4 cm su oda 7x4 cm. Pjūvyje - balkšvas, standus, neaiškių ribų navikas 2,1x1,8x1,1 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos – 4 cm.. PAPILDYTAS ATSAKYMAS HER2 FISH TYRIMU:   1(ekstra). "Kraštas": fibrozuotas riebalinis audinys; be naviko.   2(ekstra). "Kraštas": fibrozuotas krūties audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma (su tikėtinu mikropapiliniu komponentu, ~20%), SUMINIS TNM:   pT1c (mikroskopiškai navikas 15 mm, žr. pastabą) N0(sn) (0/3 l/m),    LVI-0 (definityvi limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.   HER2 geno amplifikacija nenustatyta (žr. molekulinio tyrimo aprašymą ir pastabas).   Navikas nuo sektoriaus rezekcijos krašto nutolęs 0,17 mm.. 1(ekstra). "Kraštas": fibrozuotas brandžių lipocitų suformuotas audinys; be naviko.   2(ekstra). "Kraštas": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.    4. NAVIKAS (mikroskopiškai išmatuojamas didžiausias naviko matmuo - 15 mm; su aplinkine fibrozės zona ~ 18 mm skersmens -židinys: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios kribriforminės, trabekulinės, lizdinės, solidinės naviko struktūros su fokaline mikropapilinių struktūrų formacija. Naviko ląstelės vidutiniškai polimorfiškos, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 25/10 DPRL. Fokaliai gausi perinavikinė limfocitinė infiltracija. Pavieniai mikrokalcifikatai.   SEKTORIAUS REZEKCIJOS KRAŠTAS: navikas nutolęs 0,17 mm.. 4. Navikas (blokas 17):  HER2: vidutinė (++) necirkuliari reakcija, 5% naviko ląstelių membranoje.   GATA3(+++)(brand.r-ja)75%; EMA(+); Synaptophysin(-).
answer:  1

 85%|████████▍ | 559/661 [08:31<01:32,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  14 G automatine biopsine adata punktuoti didelės apimties (apimantys mažiausiai visą viršutinį lateralinį kvadrantą) navikiškai pakitę audiniai su daugybiniais mikrokalcinatais kairės krūties viršutiniame lateraliniame kvadrante, paimti penki biopsiniai stulpeliai histologijai.. 5 biopsiniai stulpeliai: I - 18 mm; II - 7 mm; III - 7 mm; IV - 9 mm; V - 5 mm.. Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 8% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 30%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš ryškiai polimorfiškų ląstelių, mitozių iki 14/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 8% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 100% naviko ląstel
answer:  1

 85%|████████▍ | 560/661 [08:32<01:27,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 9 mm; III - 9 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 10%.. Bioptatuose (3/3) - fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, kribriforminėmis struktūromis, lizdais ir trabekulėmis besidėstančių ląstelių negausia eozinofiliška citoplazma, polimorfiškais, vidutinio-stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 6/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 15% naviko ląstelių.  Ki67 proliferacinis aktyvumas 10%.  CK14(-); Synaptophysin(-);
answer:  0

 85%|████████▍ | 561/661 [08:33<01:33,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a ir N2b kraštai - skubus tyrimas - be naviko  2 ėminio aprašas: N2b kraštai - skubus tyrimas - be naviko  3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis  - skubus tyrimas - 4l/m be naviko  4 ėminio aprašas: N1: pašalintas kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 93,5x5,5x4,5 cm su odos lopu 7x2,5cm, su įtrauktu speneliu. Krūties audinyje, spenelio projekcijoje - pilkšvas, standus, neaiškių ribų navikas 22x16x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm.. Paruošti pjūviai Prosigna tyrimui.    1(3). Kairės pažasties sarginis limfmazgis. Reaktyvi limfadenopatija (6 l/m).   2(N2a). N2a kraštai. Krūties audinys. Naviko plitimo nėra.   3(N2b). N2a kraštai. Krūties audinys. Naviko plitimo nėra.   4(1). Kairės krūties kvadrantas. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham sistemą) duktalinė karcinoma, pT4b (22 mm išopėjęs navikas) N0(sn)(6 l/m) LVI-0 (limfovaskulinė invazija neidentifikuota). Radikalus pašalinimas (R0).  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis, kribriforminis tipai).  Naviko imunofenotipas:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 20-25%.. 1(3). Kairės pažasties sarginis limfmazgis. 6 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.  2(N2a). N2a kraštai. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   3(N2b). N2a kraštai. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   4(1). Kairės krūties kvadrantas. Krūties audinyje - desmoplastiškoje stromoje plintantis navikas, suformuotas trabekulių, grandinėlių, solidinių kompleksų, pavienių tubulių (<10%). Naviko ląstelės su vidutinio gausumo, šviesiai eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais. Mitozių navike 9/10DPRL. Navikas plinta spenelyje, epidermis ties naviko struktūromis fokaliai išopėjęs.   Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių.  Atokiau krūties latakai su cistine dilatacija ir apokrine metaplazija.. Blokas 18: CD31+ endotelis (limfovaskulinė invazija neidentifikuota)  Blokas 25:  E-Cadherin: (++/+++)(membr.r-ja)100%  HER2: silpna (+) cirkuliari reakcija, 5%  naviko ląstelių membranoje.  P120: (++/+++)(membr.r-ja)100%
answer:  0

 85%|████████▌ | 562/661 [08:34<01:31,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Kairė krūtis su limfmazgiais, planinis. Krūtis 500 g svorio, 20x16x6 cm, su pažasties narveliena 11x7x5 cm. Spenelis smulkiai gruoblėtas, trapiu paviršiumi 1,3x0,8 cm plote.   Krūties audinyje navikiniai pokyčiai apimantys 3,7x2x3,3 cm, navikų židiniai balkšvi, standūs, spikulinių kraštų:  - I navikas 2,4x1,5x3,2 cm esantis 0,4 cm nuo artimiausio rezekcijos pjūvio, siekia dermą.   - II naviko židinys 1,4x1,2x1,3 cm, nuo I naviko nutolęs 0,5 cm, su juo jungiasi standžiais fibrozės pluoštais, nuo rezekcijos krašto nutolęs 1,3 cm, nuo odos - 1,8 cm.  Krūties audinyje 2 cm nuo naviko fibrozės zona su dilatuotais latakais 3x2x2 cm plote, nuo rezekcijos krašto nutolę 0,5 cm.   Rasta 12 limfmazgių su židiniais iki 1,4 cm.. Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;   pT(m)2(24 mm ir 14 mm) pN2a(8/12) pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%, vietomis iki 20%.. Krūties audinį infiltruoja 2ų navikų židiniuose negausios duktalinės struktūros, smulkūs netaisyklingi kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių 20-30/10 DPRL. Operaciniai kraštai be matomų pokyčių.  Limfmazgiai: aprašyto naviko iki 12 mm plitimas 8-se/12 limfmazgiuose; stebimas ekstranodulinis plitimas.. nan
answer:  0

 85%|████████▌ | 563/661 [08:36<01:47,  1.10s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2). Dešinės pažasties sarginis limfmazgis - extra.   2(N4a). kraštas, skubu  3(N4b). kraštas, skubu  4(N5). kairės pažasties sarg. l/m, skubu  5(N1). Pašalinta dešinė krūtis - planinis tyrimas  6(N3). Kairės krūties markiruotas kvadrantas - planinis tyrimas. 5. Krūtis 1131 gramų svorio, 24x17,5x7 cm. Pjūvyje fibrozės zona 7,5x6x4,5 cm. Krūties audinyje, viršutiniame lateraliniame kvadrante, fibrozės zonoje - balkšvas, elastingas, nehomogeniškas I navikas su cistinėmis ertmėmis 22x20x17 mm, nuo odos nutolęs 4 cm, nuo giliojo rezekcijos krašto - 3,5 cm. Šalia I naviko - pilkšvas, aiškių ribų II navikas 10x8x7 mm, nuo I naviko nutolęs 0,5 cm, nuo giliojo rezekcijos krašto nutolęs 5 cm, nuo odos - 5 cm. Viršutinių kvadrantų riboje, balkšvas, standus darinys 1,6x1,1x0,7 cm, nuo odos nutolęs 3,5 cm, nuo giliojo rezekcijos krašto - 3,5 cm.   6. Krūties sektorius 248 gramų svorio, 13x7,5x5 cm su odos lopu 10x3,5 cm, žymėtas viela. Vielos projekcijoje, rusva I fibrozės zona 1,9x1x0,8 cm, nuo odos nutolęs 3 cm, nuo giliojo rezekcijos krašto - 0,7 cm. Pjūvyje, II fibrozės zona 3,8x3,2x2,9 cm, nuo odos nutolęs 0,8 cm, nuo giliojo rezekcijos krašto 0,9 cm.. 1(N2, "Dešinės pažasties sarginis limfmazgis"). Reaktyvi limfadenopatija (3 l/m).  2(N4a, "kraštas"). Krūties fibrocistiniai pokyčiai.  3(N4b, kraštas"). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, papilinis tipas).  4(N5, "kairės pažasties sarginis l/m"). Reaktyvi limfadenopatija (2 l/m).  5(N1, "dešinė krūtis"). Krūties invazyvi multicentrinė adenokarcinoma, TNM (Nr.1, Nr.2, Nr.3, Nr.5): pT1c(m) (1,5 cm, 1 cm, 0,8 cm naviko židiniai) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės naviko invazijos nėra). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, papilinis, kribriforminis tipai). R0(radikalus navikų pašalinimas).  Navikų diferencijacijos laipsniai:  - vidutiniškai diferencijuota / G2 / 7 balai pagal Nottingham (1 cm ir 0,8 cm židiniai),  - blogai diferencijuota / G3 / 8 balai pagal Nottingham (1,5 cm židinys).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama.  Ki67: 10% (hot spot 20%).  ---  6(N3, "Kairės krūties markiruotas kvadrantas"). Krūties invazyvi duktalinės adenokarcinoma (vidutiniškai diferencijuota / G2 / 7 balai pagal Nottingham), TNM (Nr.4, Nr.6): pT1c(1,7 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės naviko invazijos nėra). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama.  Ki67: 10% (hot spot 20%).. 1(N2, "Dešinės pažasties sarginis limfmazgis"). Nežymi sinusų histiocitozė trijuose (3) limfmazgiuose.  2(N4a, "kraštas"). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(N4b, kraštas"). Krūties audinyje - negausūs vidutinio kalibro kanaliukai su kribriforminiais, negausiais papiliniais atipinių ląstelių proliferatais.  4(N5, "kairės pažasties sarginis l/m"). Nežymi sinusų histiocitozė dviejuose (2) limfmazgiuose.  5(N1, "dešinė krūtis"). Krūties audinyje - dauginiai (iki 3) naviko židiniai (1,5 cm, 1 cm ir 0,8 cm):  A) Stambiausias (1,5 cm) židinys: solidines, trabekulines naviko struktūras formuoja ląstelės su gan gausia amfofiline citoplazma, vidutinio kalibro apvalios formos netaisyklingais/polimorfiškais branduoliais, mitozių navike iki 20 / 10 DPRL;  B) Smulkesni (1 cm ir 0,8 cm) židiniai: kribriformines, trabekulines, negausias susiliejančias tubulines navikų struktūras formuoja ląstelės su negausia ar kiek gausesne blyškia citoplazma, vidutinio kalibro apvalios formos netaisyklingais/polimorfiškais branduoliais, mitozių navikuose iki 7 / 10 DPRL.  Šalia navikų krūties audinyje - stambūs kanaliukai su kribriforminiais, negausiais papiliniais atipinių ląstelių proliferatais.  6(N3, "Kairės krūties markiruotas kvadrantas"). Krūties audinyje - A) invazyvi karcinoma (kribriformines, trabekulines, negausias susiliejančias tubulines navikų struktūras formuoja ląstelės su negausia ar kiek gausesne blyškia citoplazma, vidutinio kalibro apvalios formos netaisyklingais/polimorfiškais branduoliais, mitozių navikuose iki 12 / 10 DPRL), B) krūties audinyje - vidutinio kalibro ar stambūs kanaliukai su kribriforminiais atipinių ląstelių proliferatais.. 5(N1, "dešinė krūtis").  33 blokas (1,5 cm navikas):  Her2 nusidažiusių naviko ląstelių nėra.  Ki67 10% (hot spot 20%). CK5(++/+++)(citoplazminė r-ja), 5%.  39 blokas (1,0 cm navikas): Her2 nusidažiusių naviko ląstelių nėra.  47 blokas (0,8 cm navikas): H
answer:  0

 85%|████████▌ | 564/661 [08:36<01:38,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 biopsiniai stulpeliai: I - 11 mm; II - 10 mm; III - 8 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 80% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 2%.. Bioptatuose (3/3) - krūties audinyje, fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos grandinėlėmis ir pabirai besidėstančių ląstelių negausia eozinofiliška citoplazma, vidutiniškai polimorfiškais, vidutinio kalibro, dalis ekscentriškais, branduoliais; mitozių 1/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 80%.  HER2: nusidažiusių naviko ląstelių membranų nėra.  Ki67 proliferacinis aktyvumas 2%.  E-cadherin(-).
answer:  0

 85%|████████▌ | 565/661 [08:37<01:39,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Kairės pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: Kairė krūtis, planinis. 2. Krūtis 710 gramų svorio, 22x17x6 cm. Krūties audinyje, apatinių kvadrantų riboje balkšvas, standus, neaiškių ribų navikas 26x16x12 mm, nuo odos nutolęs 2 cm, nuo gilioji rezekcijos krašto - 1 cm. Aplink naviką fibrozės zona 4,5x4,5x2,2 cm, nuo odos zona nutolusi 1,2 cm, nuo giliojo rezekcijos krašto - 0,2 cm. Spenelis įtrauktas. Odoje rusvas, smulkiai gruoblėtas darinys 1,5x1,1x0,3 cm, nuo artimiausio odos rezekcijos krašto nutolęs 0,8 cm.. 1(Extra). Reaktyvi limfadenopatija su dermatopatinės limfadenopatijos požymiais (4 l/m).  2. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(31 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas (R0) (naviko atstumas nuo 1 mm nuo rezekcijos krašto).  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties inkapsuliuota papilinė karcinoma (11 mm) ir išplitusi vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė) (45 mm plote).  Krūties intraduktalinė papiloma.  Odos seborėjinė keratozė.. 1(Extra). 4 limfmazgiai su fokaline parakortekso hiperplazija su histiocitų agregatais ir sinusų histiocitoze.  2. SPENELIS: normali histologinė struktūra.  NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai 31 mm), suformuotas fibrozuotoje stromoje infiltratyviai plintančių smulkių tubulinių, kribriforminių ir negausių trabekulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 1/10 DPRL. Naviko atstumas nuo 1 mm nuo rezekcijos krašto.  Šalia naviko - cistinis darinys (11 mm) fibrozuota siena su židinine MMN infiltracija ir siderofagais su daugiabranduolėmis gigantinėmis ląstelėmis, vidiniame paviršiuje klotas epiteliu su kribriforminėmis ir besiliejančiomis papilinėmis struktūromis, suformuotomis ląstelių eozinofiliška citoplazma, vidutinio kalibro, ovaliais, dalis skeltais ar su smulkia nukleole branduoliais. Aplink naviką (45 mm plote) - gausūs dilatuoti kanaliukai su solidiniais ir kribriforminiais analogiškų navikui ląstelių proliferatais; dilatuotas kanaliukas su papilinėmis intraduktalinėmis struktūromis, klotomis dvisluoksniu stulpiniu epiteliu; grupės kanaliukų su apokrinine metaplazija.   ODA: darinys su epidermio papiliarizacija ir neryškia akantoze ir hiperkeratoze, bazinių ląstelių hiperplazija ir hiperpigmentacija bei smulkiomis keratininėmis cistomis.. nan
answer:  0

 86%|████████▌ | 566/661 [08:38<01:32,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a - skubu - kraštai  2. N2b kraštai - skubus tyrimas - be naviko  3. N3: kairės pažasties sarginis limfmazgis  - skubus tyrimas 4l/m be naviko  4. N1: kairės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 13x8x4 cm su oda 11,5x4 cm, žymėtas 2 vielomis:   - I vielos projekcijoje - balkšvas, standus, neaiškių ribų navikas 1,8x1,7x1,5 cm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 4,5 cm.  - II vielos projekcijoje - fibrozės zona 3x1,5x1,3 cm, siekia gilųjį rezekcijos kraštą, nuo odos - 3,5 cm.. N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(18mm).  N2ab: Krūties audinys be naviko.  N3: Karcinomos metastazės viename limfmazgyje (iki 1mm židiniai, 1 iš 4 l/m); pN1mi(sn).. N1: Krūties audinyje 18mm navikas: negausios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai neryškiai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.  N2ab: Krūties audinys be naviko.  N3: Iš į parafiną įlietos medžiagos - viename limfmazgyje (1 iš 4 l/m) karcinomos metastazės iki 1mm.. nan
answer:  0

 86%|████████▌ | 567/661 [08:39<01:31,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 18 G automatine biopsine adata punktuotas ~10x17 mm dydžio, netolygiai iki ~7,0 mm sustorėjusiu žieviniu sluoksniu l/m dešiniosios pažasties I zonoje, paimti trys biopsiniai stulpeliai histologijai (I buteliukas).   2 ėminio aprašas: 2. 18 G automatine biopsine adata punktuotas ~7x15 mm dydžio, netolygiai iki ~5,0 mm sustorėjusiu žieviniu sluoksniu l/m kairiosios pažasties I zonoje, paimti trys biopsiniai stulpeliai histologijai (II buteliukas). @#3 ėminio aprašas: 3. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~60x65 mm dydžio navikas kairiojoje krūtyje viršutiniame lateraliniame kvadrante, paimti penki biopsiniai stulpeliai histologijai (III buteliukas).. 1. 3 biopsiniai stulpeliai: I - 11 mm; II - 8 mm; III - 14 mm.  2. 3 biopsiniai stulpeliai: I - 8 mm; II - 6 mm; III - 7 mm.  3. 5 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 9 mm; III - 7 mm; IV - 7 mm; V - 3 mm.. 1. Limfmazgio 3 stulpeliai be patologinių pokyčių.    2. Limfmazgio 3 stulpeliai be patologinių pokyčių.    3. Krūties invazyvi gerai diferencijuota (G1) mucininė karcinoma (mažiausiai 11 mm skersmens) 5-se bioptatuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 5% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 2%.. 3. Krūties 5-se stulpeliuose naviko struktūras (infiltruojančias iki 11 mm ir išsidėsčiusias gausiuose ekstraląsteliniuose mucinuose) formuoja ląstelės su saikinga citoplazma, vidutinio dydžio saikingai polimorfiškais, dalis su nukleole branduoliais; mitozių navike iki 1 / 10 DPRL.. Blokas 7:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) necirkuliari reakcija, 40%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 2% naviko ląstelių.  Progesterono receptoriai: stipri
answer:  100

 86%|████████▌ | 568/661 [08:40<01:33,  1.00s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. retroarveolinė sritis - extra  2. limfmazgiai - extra  N2- pašalinti sarginai l/n- be naviko - 1 mikromts iš 3 l/m   3. N1- pašalinta retroareoliarinė sritis- DCIS įtarimas - papildomas kraštas - planinis tyrimas  4. N3 - pašalinta liauka -planinis patologinis tyrimas@# Skubus rentgeninis N1 tyrimas - pašalintas 28 mm navikas. 3. Riebalinio audinio fragmentas 2,5x1x0,5 cm.v/m  4. Krūties liauka 164 gr. svorio, 16x14x4 cm  su odos lopu 6,5x2,5 cm ir atskiri krūties audinio fragmentai, bendras dydis 4x4x0,5 cm. Krūties audinyje balkšvas, standus, aiškių ribų navikas 3,8x2,5x1,8 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos  - 1 cm. Krūties audinyje, 5 cm nuo naviko pilkšvas apvalus, elastingas darinys 0,9x0,7x0,5 cm, nuo rezekcijos krašto nutolęs 0,8 cm.. 1. Fibrocistiniai krūties pokyčiai.  2. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/3 l/m, 2,5 mm).  3. Krūties audinys.  4. Krūties invazyvi blogai diferencijuota (G3; 9 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT2(navikas 38 mm), pN1a(sn)(1/3 l/m, 2,5 mm), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Progesterono receptoriai: reakcijos nėra.  Krūties fibroadenoma. Fibrocistiniai krūties pokyčiai.. 1. Krūties audinyje židininė fibrozė su dilatuotais ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu su fokalia apokrinine epitelio metaplazija.  2. Viename limfmazgyje iš trijų (1/3 l/m) žemiau aprašyto naviko metastazė iki 2,5 mm.  3. Krūties audinyje lobulės klotos dvisluoksniu epiteliu.  4. Krūties audinyje, fibrozuotoje stromoje plinta navikas (38 mm makroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas stambių solidinių, fokaliai susiliejančių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su ryškiai polimorfiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 63/10DPRL. Limfovaskulinis plitimas (LVI2). Navikas nuo artimiausio rezekcijos krašto nutolęs per 1 mm. Krūties audinyje darinys (9 mm) suformuotas fibromiksoidinės proliferuojančių fibroblastų stromos su suspaustais, šakotais vidutinio kalibro ir kiek dilatuotais latakais, klotais dvisluoksniu epiteliu. Aplinkiniame krūties audinyje nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar epiteliu au apokrinine epitelio metaplazija.. Blokas 1:  CK14: mioepitelinis sluoksnis (+).  Blokas 24:  HER2: reakcijos naviko ląstelių membranoje nėra.  Progesterono receptoriai: reakcijos naviko ląstelių branduoliuose nėra.
answer:  1

 86%|████████▌ | 569/661 [08:42<01:37,  1.06s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas - be naviko   2(N2b) - kraštas - skubus tyrimas - be naviko  3(N1) - pašalintas kairės krūties kvadrantas kartu su kairės pažasties limfmazgiais. (keli limfmazgiai čiuopiasi pačiame kvadranto lateraliniame krašte). 3(1). Krūties sektorius 12,5x8,5x5 cm su oda 10,5x6 cm. Krūties audinyje - balkšvas, standus, neaiškių ribų navikas 32x30x18 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1 cm. Sektoriuje rasti 3 limfmazgiai iki 0,6 cm. Atskiri riebalinio audinio fragmentai, bendras dydis 5,5x5x1,7 cm, su 7 limfmazgiais iki 1,2 cm.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.     3(1). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT2(m) (du naviko židiniai: I - 32 mm; II - 0,82 mm) N2a (mts 5/10 l/m; iki 8 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė). Kalcifikatai.   Sektoriaus rezekcijos krašte - koaguliacinių artefaktų zonos su kalcifikatais; DCIS komponentas nutolęs 2,9 mm.. 1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys su deformuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(1). NAVIKAS (I - 32 mm; II - 0,82 mm, smulkus satelitinis židinys šalia in situ komponento): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta retos besiliejančios duktalinės, trabekulinės, lizdinės, nedidelės solidinės ir lizdinės naviko struktūros, suformuotos vidutiniškai ar ryškiau polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki 20/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Gausūs mikrokalcifikatai.  APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis ir gausiai kalcifikatais. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti, kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.   LIMFMAZGIAI(10): penkiuose (5) limfmazgiuose aukščiau aprašyto naviko metastazės, iki 8 mm skersmens, su ekstranodaliniu plitimu.  SEKTORIAUS REZEKCIJOS KRAŠTAS: in situ komponentas nutolęs 2,9 mm; invazyvus navikas - 2,4 mm; krašte - ryškiai koaguliuotos zonos su kalcifikatais.. 3(1). Navikas (blokas 5):  EMA(+) daugiau citoplazminė r-ja dalyje naviko ląstelių.   HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.
answer:  0

 86%|████████▌ | 570/661 [08:43<01:33,  1.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N2a kraštas - skubus tyrimas - be naviko  2 ėminio aprašas: N2b kraštas - skubus tyrimas - be naviko  3 ėminio aprašas: N3: kairės pažasties sarginis limfmazgis -  skubus tyrimas - 1 l/m be naviko  4(1)pašalintas kairės krūties kvadrantas - planinis tyrimas. 4(1). Krūties sektorius 9x5x3 cm su odos lopu 8x3 cm, žymėtas viela, markiruotas metilėno mėliu. Vielos projekcijoje, pjūvyje - balkšvas, standus, aiškių ribu navikas 1,4x0,7x1,2 cm (histologiniam tyrimui paimtas visas), nuo artimiausio rezekcijos krašto (patologijos skyriuje dažyto žaliu tušu) nutolęs mažiau 0,1 cm, nuo odos – 1,5 cm.. 1(2a). Fokalinė krūties audinio fibrozė.  2(2b). Fokalinė krūties audinio fibrozė.  3(3). Reaktyvi limfadenopatija (1 l/m).  4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,4 cm) pn(SN)0 (0/1 l/m). LVI0(limfovaskulinės invazijos nėra).     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5%.. 1(2a). Krūties audinyje - negausūs fibrozės židiniai su smulkiais ar kiek stambesnio kalibro kanaliukais, išklotais dvisluoksniu epiteliu.  2(2b). Krūties audinyje - negausūs fibrozės židiniai su smulkiais ar kiek stambesnio kalibro kanaliukais, išklotais dvisluoksniu epiteliu.  3(3). Nežymi sinusų histiocitozė viename (1) limfmazgyje.  4(1). Krūties audinyje - navikas: smulkias ar kiek stambesnes solidines, periferijoje - negausias smulkias susiliejančias tubulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne amfofiline citoplazma, vidutinio kalibro gan monotoniškais, minimaliai netaisyklingais branduoliais; mitozių navike iki 5 / 10 DPRL.. 4(1). Navikas (13 blokas): Her2 silpna trūkinėjanti membraninė r-ja 10% naviko ląstelių.  Ki67: 5%, CK5(-), Synaptophysin(-).
answer:  0

 86%|████████▋ | 571/661 [08:44<01:32,  1.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2A)- kraštai- be naviko   2(N2B)- kraštai- be naviko   3(N3)- sarginai ( 2 ) - be naviko   4(N1)- sektorius - planinis ptologinis tyrimas    N1- skubus rentgeninis tyrimas - navikas pašalintas. 4. Krūties sektorius 33x5x4 cm su odos lopu 11x4 cm, žymėtas viela. Vielos projekcijoje, pjūvyje - balkšvas, standus, spikulinių kraštu navikas 6x7x7 mm (sudėtas visas), nuo artimiausio rezekcijos krašto (dažyto mėlynai) nutolęs 0,2 cm, nuo odos – 3,5 cm. 3 cm nuo naviko - krūties audinyje fibrozės zona su dilatuotais latakais ~2x1x1 cm.. 1(2a). Fibrocistiniai krūties pokyčiai.  2(2b). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1b (navikas 7,5 mm), pN0(sn)(0/2 l/m), LVI0 (neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). HER2: reakcija paribinė (2+); HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).. 1(2a). Krūties audinyje ryški fibrozė su smulkiais ir nežymiai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.  2(2b). Krūties audinyje židininė fibrozė su smulkiais ir nežymiai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu ar epiteliu su fokalia apokrinine metaplazija.  3. Du limfmazgiai su sinusų histiocitoze.  4. Krūties audinyje navikas (7,5 mm makroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių, trabekulinių ir tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su  polimorfiškais, hiperchromiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 5/10DPRL. Limfovaskulinio plitimo neidentifikuota(LVI0). Navikas nuo artimiausio rezekcijos krašto nutolęs per 3,5 mm (mikroskopiškai).  Krūties audinyje gausūs dilatuoti kanaliukai užpildyti solidinių  ir kribrifominių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Greta gausūs dilatuoti kanaliukai kloti dvisluoksniu epiteliu.. Blokas 10:  CK5: mioepitelis (+);  HER2: vidutinė (++) necirkuliari reakcija, 20%  naviko ląstelių membranoje.
answer:  0

 87%|████████▋ | 572/661 [08:44<01:25,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: punktuotas kair. krūties darinys, paimti 4 stulpeliai medžiagos histologiniam išturimui. 4 fragmentuoti biopsiniai stulpeliai: I - 10 mm; II - 14 mm; III - 9 mm; IV - 10 mm, fragmentuotas.. Invazinė karcinoma (mažiausiai iki 13 mm; galimai lobulinė);  (G1; 5 b. pgl. Nottingham sist.) 4-se krūties audinio stulpeliuose.  Estrogenų receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 10% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 2%.. Krūties kompaktišką fibrozinį audinį 4-se bioptatuose infiltruoja iki 13 mm :   - deformuotos juostos ir trabekulės;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: vidutinė teigiama (++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Estrogenų receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcij
answer:  0

 87%|████████▋ | 573/661 [08:45<01:23,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- Kairės krūties sektorius su limfmazgiais, planinis. 3(2). Krūties sektorius 8,5x8,5x5 cm su oda 8x3,5 cm su pažasties narveliena 10,5x6,5x5 cm. Krūties audinyje, pilkšvas, standus, aiškių ribų navikas 25x22x20 mm, nuo giliojo rezekcijos krašto 1 cm, nuo odos - 0,7 cm. Rasta 18 limfmazgių iki 1,7 cm.. 1(1a). Krūties fibrocistiniai pokyčiai.  2(1b). Krūties fibrocistiniai pokyčiai.  3(2). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, pT2(2,5 cm) pN1a(1/18 l/m, mts 0,7 cm; ekstranodalinis plitimas). Rezekcijos kraštų būklė: be naviko.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5% (hot spot 8%).. 1(1a). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai minimaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  2(1b). Krūties audinyje - fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, fokaliai minimaliai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu.  3(2). Krūtis: Navikas - solidines, trabekulines, pavienes smulkias tubulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 4 / 10 DPRL.  Pažasties narveliena: Aukščiau aprašyto naviko metastazė viename (1) iš aštuoniolikos (18) limfmazgyje (0,7 cm, ekstranodalinis plitimas).. 3(2). Navikas (5 blokas): HER2: silpnas(+) membraninis dažymasis 10% naviko ląstelėse.   Ki67: 5% (hot spot 8%).
answer:  0

 87%|████████▋ | 574/661 [08:46<01:23,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2a kraštai - skubus tyrimas (be naviko);   2. N2b kraštai - skubus tyrimas (be naviko);  3. N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas (3 l/m be naviko);   4(1). N1: Pašalintas dešinės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 10x5x3 cm su odos lopu 7x4 cm. Krūties audinys balkšvas, standus, fibrozuotas 6,5x6 cm plote. Fibrozėje gelsvas, neaiškių ribų navikas 15x7x7 cm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 0,7 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  3(Extra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(18 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Naviko struktūros siekia koaguliuotą sektoriaus kraštą.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Židininė krūties audinio fibrozė.. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro kanaliukai ir lobulės, kloti dvisluoksniu epiteliu; vienas kanaliukas su epitelio hiperplazija.  3(Extra). 3 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 18 mm), suformuotas fibrozuotoje stromoje plintančių lizdinių, trabekulinių ir negausių solidinių bei pavienių tubulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 4/10 DPRL. Naviko struktūros siekia koaguliuotą sektoriaus kraštą.   Aplinkiniame krūties audinyje - fibrozės zonos su kiek dilatuotais kanaliukais, klotais suplokštėjusiu epiteliu.. 2. CK14+ mioepitelinis sluoksnis bei mišri populiacija hiperplastiškame epitelyje.  4. Navikas (10 blokas):  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.
answer:  0

 87%|████████▋ | 575/661 [08:47<01:19,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 2 biopsiniai stulpeliai iš kairės krūties  BI-RADS 4c darinio   2 but. 1 biopsinis stulpelis iš dešinės krūties BI-RADS 5 darinio. 1. 2 biopsiniai stulpeliai: I - 8 mm; II - 11 mm.  2. Biopsinis stulpelis 13 mm.. Kairė  N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ar vidutinis branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.  ------------------  Dešinė  N2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Kairė  N1: Krūties audinį infiltruoja nedideli kribroziniai/solidiniai kompleksai, juostos ir trabekulės iš neryškiai polimorfiškų ECAD negatyvių ląstelių, mitozių mažiau 1/10 DPRL.  ------------------  Dešinė  N2: Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. nan
answer:  0

 87%|████████▋ | 576/661 [08:48<01:26,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. sarginiai limfmazgiai, skubu  2. deš. krūtis, planinis. 2. Krūtis 1022 gramų svorio, 24x20x10 cm, spenelis įtrauktas. Krūties audinyje, centrinėje dalyje - pilkšvas, neaiškių ribų navikas 30x26x25 mm, su aplinkine fibroze 5x4 cm plote ir hemoragijos. Navikas nuo giliojo rezekcijos krašto nutolęs 3,6 cm, nuo odos - 2 cm. Nuo naviko 3 cm atstumu pilkšvas, standus, gan aiškių ribų židinys 11x8x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo odos - 4 cm. Krūties krašte riebalinis darinys 5,5x4,3x2 cm.. 1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   2. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma (su apokrininės diferenciacijos požymiais), SUMINIS TNM:   pT2(m) (du navikai: I - 30 mm; II - 11 mm) N0(sn) (0/3 l/mm), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Intraduktalinis karcinomos plitimas (kanaliukų kancerizacija). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).   Androgenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.   Synaptophysin/GATA3/E-Cadherin(+).     Krūties žemo-aukšto laipsnio duktalinė karcinoma in situ (DIN1c-3/DCIS: solidinis, kribriforminis, ploščias, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, sklerozuojanti ir mikroglandulinė adenozė, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).   Krūties rezekcijos kraštas normalios histologinės struktūros.. 1(ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2. SPENELIS: normalios histologinės struktūros.   NAVIKAS(du židiniai: I - 30 mm; II - 11 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios nedidelės  kribriforminės, trabekulinės, smulkios lizdinės naviko struktūros ir pabiros ląstelės, ryškiai polimorfiškų ląstelių, gausia šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis eozinofiliškomis nukleolėmis; retos dvi- ar keliabranduolės ląstelės; mitozių iki 7-8/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Naviko ląstelės plinta kanaliukų spindžiuose. Pavieniai mikrokalcifikatai. Fokaliai kiek negausi limfocitinė infiltracija.   APLINKA: šalia naviko - solidiniai, kribriforminiai, plokšti vienasluoksniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti, kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.   GILUSIS REZEKCIJOS KRAŠTAS: fibrozuotas brandus riebalinis audinys; be naviko.. 2. NAVIKAS (blokas 18):   Androgenų receptoriai: (+/+++)(brand.r-ja)95%;   Synaptophysin: (+++)(grūd.citopl.r-ja)100%;   GATA3: (+++)(brand.r-ja)100%;   E-Cadherin: (+++)(membr.r-ja)100%;   HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląstelių memb
answer:  20

 87%|████████▋ | 577/661 [08:49<01:22,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. Pjūvio kraštai, ekstra.   3. Sarginiai l/m, ekstra.   4. Sektorius, planinis.. 4. Krūties sektorius 7x4x4,5 cm su oda 5,5x3 cm, žymėtas viela. Vielos projekcijoje, pilkšvas standus, aiškių ribų navikas 13x13x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 3 cm.. 1. Pjūvio kraštai. Krūties audinys be patologinių pokyčių.    2. Pjūvio kraštai. Krūties audinys be patologinių pokyčių.    3. Sarginiai l/m. Limfmazgiai (2) be karcinomos ląstelių.    4. Sektorius.   Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20-25%.    pT1c pN0 pLVI-0 pR0.. 1. Pjūvio kraštai. Krūties audinys be patologinių pokyčių.  2. Pjūvio kraštai. Krūties audinys be patologinių pokyčių.  3. Sarginiai l/m. Limfmazgiai (2) be karcinomos ląstelių.  4. Sektorius. Krūties audinį infiltruoja dalinai riboto naviko negausios duktalinės struktūros ir netaisyklingi kribroziniai/solidiniai kompleksai iš  vidutiniškai polimorfiškų ląstelių, mitozių iki 12/10 DPRL. Navikas 1 mm nuo operacinio krašto.. Blokas 12:  CD31: stipri teigiama (+) membraninė reakcija kraujagyslių endotelyje be atipinių struktūrų spindyje
answer:  0

 87%|████████▋ | 578/661 [08:50<01:20,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N1 sarginiai l/m - extra  2. N2 K krūtis su naviku - planiškai. 2. Krūtis 1348 g svorio, 25x18x7 cm. Odoje randas 5,5 cm ilgio, cirkuliariai apvedantis areole 5 cm skersmenyje. Krūties audinyje pilkšvas, standus, spikuliniais kraštais navikas 38x25x34 mm, siekia odą, nuo artimiausio rezekcijos krašto nutolęs 4 cm.. 1(extra). Reaktyvi limfadenopatija (5 l/m).  2. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, suminis TNM: pT2(38 mm navikas), pN0(0/5 l/m), R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2). Krūties fibrocistiniai pokyčiai.  Naviko imunofenotipas(biopsijoje):  Estrogenų receptoriai: stipri reakcija, 90% naviko ląstelių.  Progesterono receptoriai: stipri reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Operacinėje medžiagoje kartota: Ki67: proliferacinis indeksas 10%, fokaliai iki 20%.. 1. Penki limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais.  2. Spenelis normalios histologinės struktūros. Rezekcijos kraštas be naviko. Krūtyje navikas infiltratyviu augimo frontu, sudarytas iš desmoplastiškoje stromoje besidėstančių tubulių, lizdinių, trabekulinių, kribriforminių struktūrų ir solidinių kompleksų iš ląstelių negausia šviesiai eozinofiliška citoplazma ir vidutinio kalibro, apvaliais ar nelygaus kontūro, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Mitozių iki 19/10 DPRL. Limfovaskulinė invazija neidentifikuota. Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių. Krūties audinys su mažai ląstelingomis fibrozės zonomis ir atrofiškomis lobulėmis bei dilatuotais latakais, klotais dvisluoksniu epiteliu.. nan
answer:  0

 88%|████████▊ | 579/661 [08:51<01:14,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Paimti 5 biopsiniai stulpeliai.. 5 biopsiniai stulpeliai: I - 16 mm; II - 8 mm; III - 13 mm; IV - 7 mm, V - 9 mm.. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma.  ---  Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100% .   Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 80% .   Her2 imunohistocheminė reakcija neigiama (0 balų).  Ki67: 35%.. Solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne blyškiai-saikingai eozinofiline citoplazma, vidutinio kalibro apvalios formos saikingai netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 25 / 10 DPRL.. Navikas (1 blokas):  Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100% .   Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 80% .   HER2: nusidažiusių naviko ląstelių nėra.  Ki67: 35%.   CK5(-); PanCK(+++)(citoplazminė r-ja), 10
answer:  100

 88%|████████▊ | 580/661 [08:52<01:14,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.   2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 7,5x4,5x3 cm su oda 5x2,2 cm, žymėtas viela. Vielos projekcijoje - pilkšvas, standus, neaiškių ribų navikas 18x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 0,6 cm.. PATAISYTAS ATSAKYMAS (naviko diferenciacijos laipsnis):  1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (5 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(15 mm) N(sn)0(0/5 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   HER2 imuninė reakcija: neigiama (1+).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro ir fokaliai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu; negausi aplinkinė MMN infiltracija.  3(Extra). 5 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija, sinusų histiocitoze ir neryškia lipomatoze.  4. Krūties audinyje - ribotas skiltėtas navikas (mikroskopiškai 15 mm), suformuotas fibrozuotoje stromoje plintančių trabekulinių, solidinių ir negausių lizdinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, dalis su nukleole branduoliais. Mitozių iki 12/10 DPRL.  Aplinkinis krūties audinys fibrozuotas, su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.. 1. Navikas (18 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 15% naviko ląstelių.
answer:  0

 88%|████████▊ | 581/661 [08:53<01:28,  1.10s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 1 - viršutinis kraštas;  2. 2 - apatinis kraštas;  3. 3 - sarginiai l/m;  4. 4 - kvadrantas - planiniam tyrimui;  5. 5 - k. krūties audiniai.    1-2-3 ekstra; 4 - kvadrantas - planiniam tyrimui.. 4.  Krūties sektorius 6x4x4 cm su odos lopu 5x0,7 cm, žymėtas viela. Patologijos skyriuje rezekcijos kraštas žymėtas mėlynu tušu. Krūties audinyje:  - Vielos projekcijoje - balkšvas, neaiškių ribų, standus I navikas 2,3x1,8x1 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos 0,4 cm.  - II navikas 0,4x0,4x0,4 cm (histologiniam tyrimui paimtas visas), makroskopiškai siekiantis rezekcijos kraštą, nuo odos nutolęs 2,5 cm, nuo I naviko - 1 cm.  5. Krūtis (290 g svorio, 20x13x4 cm), su odos lopu 15x14 cm, žymėta ilgu siūlu lateraliniame krašte ir trumpu siūlu viršutiniame krašte.    - Krūties apatinio lateralinio kvadranto odoje - operacinis pjūvis 5 cm ilgio, su tūriniu audinių defektu (~6 cm dydžio ir koaguliuotais kraštais: sektoriaus šalinimo vieta). Krūtis virš operacinio pjūvio 2 cm storio.   - Viršutiniame lateraliniame kvadrante - pilkšvas, apvalus darinys 0,6x0,5x0,5 cm, nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo paviršinio - 3 cm.  - Centrinėje dalyje - fibrozės zona 8x7x1,5 cm, nuo giliojo rezekcijos krašto nutolusi 1 cm, nuo odos - 1,3 cm.. SUMINĖ (Nr.1-Nr.5) patologijos tyrimo išvada:  Krūties invazyvi multifokalinė karcinoma (mišrios duktalinės+lobulinės karcinomos židinys, ir dauginiai (ne mažiau 3) lobulinės karcinomos židiniai), pT1c(m) (dauginiai židiniai, didžiausias iki 1,2 cm) pN1mi(1/1 intramamarinis limfmazgis su 0,15 cm duktalinės adenokarcinomos mikromts + 0/4 sarginiai l/m). LVI0(limfovaskulinės invazijos nėra). Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribriforminis tipas). Krūties fibrocistiniai pokyčiai (paprastoji duktalinė hiperplazija, stulpinis ląstelių pokytis). Rezekcijos kraštai be patologijos.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5%.     1(extra). Invazyvios karcinomos židinys (iki 0,25 cm skersmens) krūties audinyje.  2(extra). Invazyvios karcinomos židinys (iki 0,7 cm skersmens) krūties audinyje.  3(extra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi mišri (lobulinė + duktalinė) karcinoma (iki 1,2 cm židinys, mikroskopiškai). Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribriforminis tipas). Krūties fibrocistiniai pokyčiai (paprastoji duktalinė hiperplazija, stulpinis ląstelių pokytis). Krūties duktalinės adenokarcinomos mikrometastazė (0,15 cm) intramamariniame limfmazgyje.  5. Krūties invazyvi lobulinė karcinoma (0,3 cm židinys). Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribriforminis tipas). Krūties fibrocistiniai pokyčiai (paprastoji duktalinė hiperplazija, stulpinis ląstelių pokytis).. 1(extra). Žemiau (Nr.4, krūties sektoriuje) aprašyto naviko (lobulinės karcinomos) židinys (iki 0,25 cm skersmens) krūties audinyje.  2(extra). Žemiau (Nr.4, krūties sektoriuje) aprašyto naviko (lobulinės karcinomos) židinys (iki 0,7 cm skersmens) krūties audinyje.  3(extra). Nežymi sinusų histiocitozė keturiuose (4) limfmazgiuose.  4. Krūties sektoriuje - dauginiai kompleksiniai pažeidimai/pokyčiai:  A) invazyvaus naviko židiniai: A) mišrios (duktalinės + lobulinės) karcimomos židinys (~1,2 cm): trabekulinės, kribriforminės, duktalinės struktūros, suformuotos ląstelių su vidutinio gausumo švelniai eozinofiline citoplazma, vidutinio kalibro kiek netaisyklingais branduoliais (duktalinė karcinoma), trabekulėmis, grandinėlėmis ar pabirais besidėstančios gan smulkios ląstelės su negausia blyškia citoplazma, smulkiais apvalios formos kiek netaisyklingais branduoliais (lobulinė karcinoma); mitozių navike iki 2 / 10 DPRL.  B) in situ pažeidimas (kanaliukai su solidiniais atipinių ląstelių (su gan monotoniškais branduoliais) proliferatais spindžiuose;  C) Fibrocistinių pokyčių spektro pažeidimas (fibrozės zonos, su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; apokrininės metaplazijos, intraduktalinės hiperplazijos židiniai; zonos su stulpiniu epiteliu išklotais kanaliukais).  D) Intramamarinis limfmazgis su duktalinės adenokarcinomos mikrometastaze (0,15 cm).  5. KRŪTIES SPENELIS: Be patologijos.  KRŪTIES AUDINYS: Fibrozės zonos, su smulkiais ar kiek stambesnio kalibro, fokaliai nežymiai dilatuotais kanaliukais, išklotais dvisluoksniu epiteliu; apokrininės metaplazijos, intraduktalinės hiperplazijos židiniai; zonos su stulpiniu epiteliu išklotais kanaliukais; kanaliukai su solidiniais atipinių ląstelių (su gan monotoniškais branduoliais) proliferatais spindžiuose; 0,3 cm invazyvaus naviko (lobulinės karcinomos) židinys.. 1. Navikas (lobulinė karcinoma) (10 blokas): E-Cadherin(-), p120(+++)(citoplazminė r-ja), 100%.  2. Navikas (lobulinė karcinoma) (11 blokas): E-Cadherin(+)(silpna trūkinėjanti membraninė r-ja), 20%, p120(+++)(citoplazminė r-ja), 100%.  4. Navikas (lobulin
answer:  0

 88%|████████▊ | 582/661 [08:54<01:21,  1.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but. 3 biopsiniai stulpeliai iš kairės krūties difuzinių navikinių pakitimų su dariniu  viršutiniame lateraliniame kv-te    2 but. 1 biopsinis stulpelis iš navikinių pakitimų viršutiniame vidiniame kv-te. 1. 3 biopsiniai stulpeliai: I - 16 mm; II - 15 mm; III - 12 mm.  2. Biopsinis stulpelis 12 mm ilgio.. N1: Vidutinio laipsnio intraduktalinė karcinoma (DCIS/DIN2; solidinis tipas). Invazinė duktalinė karcinoma, navikas tokios pačios struktūros, kaip ir žemiau aprašytas; intravaskulinis naviko plitimas.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 8%.. N1: Krūties audinyje dilatuotuose kanaliukuose solidiniai vidutiniškai polimorfiškų ląstelių proliferatai ir solidiniai invaziniai naviko židiniai stromoje ir intravaskuliariai.  N2: Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. N2 navikas:  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: stiprus visos membranos nusidažymas 100% naviko ląstelių.  Ki67+
answer:  10

 88%|████████▊ | 583/661 [08:56<01:28,  1.13s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. Deš. pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: 2. Kairės pažasties sarginiai limfmazgiai, skubu  3 ėminio aprašas: 3. Deš. krūtis, planinis  4 ėminio aprašas: 4. Kairė krūtis, planinis. 3. Dex. Krūtis 2118 gramų svorio , 23x21x9,5 cm. Krūties viršutinių kvadrantų riboje -  skiltėtas, rusvas, standus  navikas 2,7x2,3x2,5 cm, nuo rezekcijos krašto nutolęs 1,4 cm, nuo odos - 2,5 cm. Krūties auidinyje viršutiniame lateraliniame kvadrante - balkšva, standi , aiškių ribų (I) zona 1,3x0,7x0,4 cm, nuo rezekcijos krašto nutolusi 2,4 cm, nuo odos - 2 cm, nuo naviko - 2,5 cm. Krūties audinyje , centrinėje dalyje balkšva, elastinga (II) fibrozės zona 9x7x5,5cm, nuo rezekcijos krašto nutolusi 0,5 cm, nuo odos - 1,5 cm.  4. SIN. Krūtis 2025 gramų svorio , 22x21x9 cm. Krūties viršutiniame medialiniame kvadrante - pilkšvas, standus, gerai ribotas  (I) navikas 3,5x3,5x2,3 cm, nuo rezekcijos krašto nutolęs 3 cm, nuo odos - 2 cm. Krūties auidinyje viršutiniame medialiniame kvadrante - balkšvas, standus, neaiškių ribų (II) navikas  0,9x0,7x0,6cm, nuo rezekcijos krašto nutolęs 1,8 cm, nuo odos - 5,5 cm, nuo (I)naviko - 0,5 cm. Krūties audinyje , viršutiniame lateraliniame kvadrante  zona  9x5x5 cm su dilatuotais, standžiais latakais iki 0,8 cm skersmens, didžiausias latakas nuo rezekcijos krašto nutolęs 1,4 cm.. 1(ekstra). DEŠINĖ. Duktalinės karcinomos mikrometastazė limfmazgyje (1/4 l/m, 0,4mm). Limfovaskulinė invazija.   2(extra). KAIRĖ. Reaktyvi limfadenopatija (3 l/m).    3. DEŠINĖ. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma su daline neuroendokrinine diferenciacija, SUMINIS TNM: pT2(27 mm) pN1a(sn)(1/4 l/m, 0,4mm). LVI-2(limfovaskulinė invazija). Vidutinio žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas), gausūs židiniai iki 1 cm.    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    4. KAIRĖ. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma neuroendokrinine diferenciacija, SUMINIS TNM: pT2(m)(35 mm ir 7 mm navikai) pN0(sn)(0/3 l/m). LVI-2(limfovaskulinė invazija). Vidutinio žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas).  Židininiai fibrocistiniai pokyčiai.    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.. 1(ekstra). 1 iš 4 limfmazgių aprašyto naviko metasatzė 0,4 mm. Limfovaskulinė invazija.  2(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  3. Spenelis: normali histologinė struktūra.   Krūtyje - navikas ekspansyviu augimo frontu, suformuotas lizdais ir solidiniais plotais besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 19/10 DPRL. Limfovaskulinė invazija.  Aplinkiniame krūties dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaustų kanaliukų zonos.    4. Spenelis: normali histologinė struktūra.   Krūtyje - navikas (35 mm ir 7 mm navikas) ekspansyviu augimo frontu, suformuotas lizdais ir solidiniais plotais besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 5/10 DPRL. Limfovaskulinė invazija.  Aplinkiniame krūties dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.. 3. Navikas (17 blokas): Synaptophysin(+++) citopl. r-ja 10%;  HER2 silpnas dalies membranų nusidažymas <5%.  4. Navikas (39 blokas): Synaptophysin(+++) citopl. r-ja 100%;  HER2 silpnas dalies membranų nusidažymas <5%.
answer:  0

 88%|████████▊ | 584/661 [08:56<01:18,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. 1 biopsinis stulpelis 12 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.. Krūties audinį infiltruoja netaisyklingos duktalinės struktūros ir pavieniai kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 40% naviko ląstelių.  Ki67+ 4
answer:  0

 89%|████████▊ | 585/661 [08:57<01:12,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 9 mm; II - 8 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 7 mm);  (G1; 4 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.. Krūties audinį 2-se bioptatuose infiltruoja iki 7 mm :   - duktalinės struktūros (20% viso naviko) ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - mitozių nestebima.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 30%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 15% naviko ląstelių.  Progesterono receptoriai: stipri (+
answer:  50

 89%|████████▊ | 586/661 [08:58<01:07,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 15 mm; II - 12 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma (su apokrininės diferencijacijos požymiais).  ---  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 20%.. Solidines, trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne eozinofiline citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 5 / 10 DPRL.. Navikas  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: nusidažiusių naviko ląste
answer:  0

 89%|████████▉ | 587/661 [08:59<01:04,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 6 mm ilgio.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mikropapilinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 5%.. Bioptate fibrozinėje stromoje, infiltratyvios naviko struktūros, suformuotos pavienėmis tubulėmis, lizdais besidėstančių ląstelių gausia ryškai eozinofiliška citoplazma, ryškiai polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais, dalis branduolių gigantiniais, pleomorfiški; mitozių 3/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67 proliferacinis aktyvumas 5%.  EMA invertuota r-ja.
answer:  0

 89%|████████▉ | 588/661 [09:00<01:01,  1.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.. Krūties audinį infiltruoja duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 12
answer:  0

 89%|████████▉ | 589/661 [09:01<01:08,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2): pašalinti  dešinės krūties sarginiai limfmazgiai - skubus tyrimas 2l/m be naviko  2(N1): pašalinta dešinės krūtis - planinis tyrimas. 2(1). Krūtis 1800 gramų svorio, 23x19x6 cm. Rezekcijos kraštas dažytas mėlynu tušu. Krūties audinyje balkšvi standūs naviko židiniai:  - (I) 2,3x2x2,3 cm navikas, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 1,5 cm;  - (II) 0,9x0,9x0,8 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 4 cm, nuo odos - 2 cm, nuo artimiausio (I) naviko - 7,5 cm;  - (III) 1,5x1,7x1,5 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs  6 cm, nuo odos - 2  cm, nuo artimiausio (I)  naviko - 3 cm;  - (IV) 2,2x1,5x1,5 cm navikas, nuo giliojo rezekcijos krašto nutolęs 5 cm, nuo odos - 3 cm, nuo artimiausio (III) naviko nutolęs 3 cm.  - (V) 0,6x0,5x0,5 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 5 cm, nuo odos - 4 cm, nuo artimiausio (III) naviko nutolęs 4 cm.  - (VI) 0,5x0,4x0,2 cm navikas (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 9 cm, nuo odos - 1 cm, nuo artimiausio (V) naviko nutolęs 3 cm.  - Balkšva, standi, netoylgių kraštų fibrozės zona 6x3x3 cm su daugybiniais standžiais židiniais iki 1,5x1x1 cm. Zona nuo giliojo rezekcijos krašto nutolusi 4 cm, nuo odos - 1 cm.. 1(Extra). Reaktyvi limfadenopatija (2 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma (su minimalia mucinine diferenciacija), SUMINIS TNM: pT(m)1c(2 naviko židiniai: 19 mm ir 7 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties išplitusi aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DIN3/DCIS)(solidinė, kribriforminė, komedo) (4 židiniai).  Krūties intraduktalinės papilomos.. 1(Extra). 2 limfmazgiai su fokaline parakortekso hiperplazija ir sinusų histiocitoze.  2. SPENELIS: normali histologinė struktūra; žemiau - dilatuotas latakas su intraduktalinėmis papilinėmis struktūromis, klotomis dvisluoksniu epiteliu.   KRŪTIS: krūties audinyje - 2 riboti navikai (I ir II: mikroskopiškai 19 mm ir 7 mm), suformuoti fibrozuotoje stromoje plintančių solidinių, lizdinių ir trabekulinių struktūrų iš ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, kiek polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 9/10 DPRL. Pirmajame navike negausūs AB+ ekstraląsteliniai mucinai; fokaliai retrakcijos artefaktai aplink naviko lizdus. Aplink dilatuoti kanaliukai su kribriforminiais, negausiais solidiniais intraduktaliniais analogiškų naviko ląstelių proliferatais.   Kiti židiniai (III - VI): - riboti židiniai su DCIS struktūromis bei intraduktalinėmis papilomomis.. 2. Navikas (6 blokas): EMA(+++)(citopl. r-ja), 100%; D2-40+/ERG+ endotelizuotose ertmėse naviko plitimo neidentifikuota.  Navikas (7 blokas): HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.
answer:  1

 89%|████████▉ | 590/661 [09:02<01:10,  1.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.  3. sektorius su pažasties l/m, planinis. 3. Krūties sektorius 14,5x5,5x5,5 cm su oda 11,5x3 cm, žymėtas viela, su pažasties narveliena 9x7,5x3 cm. Vielos projekcijoje - pilkšvas, standus, aiškių ribų navikas 18x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 3 cm. Nuo naviko 1,6 cm atstumu rusvas, aiškių ribų židinys 6x5x5 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,5 cm.   Rasta 19 limfmazgių iki 2 cm.. 1(ekstra). Pjūvio kraštai. Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.     2(ekstra). Pjūvio kraštai. Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.    3. Sektorius su pažasties l/m.   Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT1c (18 mm navikas)   pN1mi(1/19 l/m su mts 0,9 mm)    pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pR0(radikalus pašalinimas).  Naviko imunotipas (iš biopsijos):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 kribriforminis tipas).  Krūties fibrocistiniai pokyčiai, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).   Lėtinė židininė granulominė (svetimkūnio tipo) uždegiminė reakcija krūties audinyje.. 1(ekstra). Pjūvio kraštai. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu ar hiperplastišku epiteliu. Naviko plitimo nėra.   2(ekstra). Pjūvio kraštai. Riebalinis fibrozinis audinys su smulkiomis hemoragijomis. Naviko plitimo nėra.   3. Sektorius su pažasties l/m.   Navikas: Krūties audinyje - navikas, suformuotas tubulių (50 %), lizdų, kribriforminių struktūrų ir solidinių kompleksų. Naviko ląstelės su vidutinio gausumo, šviesiai eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais, vidutiniškai polimorfiškais branduoliais. Mitozių navike iki 4/10DPRL. Naviko plitimas endotelizuotuose spindžiuose.  Šalia naviko dilatuoti kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių.  Darinys: židininė putotų ir pigmentuotų makrofagų infiltracija su limfocitų priemaiša ir pavienėmis gigantinėmis daugiabranduolėmis svetimkūnio tipo ląstelėmis.   Atokiau krūties audinyje, dalyje kanaliukų cistinė dilatacija stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).   Limfmazgiai: 1-me/19 limfmazgių - aukščiau aprašyto naviko ląstelių (>200) metastazinės grupės židinyje iki 0,9 mm.. nan
answer:  0

 89%|████████▉ | 591/661 [09:03<01:08,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 13x6,5x4 cm su odos lopu 9,5x3 cm, žymėtas viela. Vielos projekcijoje, pjūvyje pilkšvas, neaiškių ribų navikas 4x3x3 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 2 cm, nuo odos – 3 cm.. 1. Krūties audinys.  2. Vidutinio laipsnio krūties intraduktalinė karcinoma (DCIS; solidinis tipas; židinys - 1,5mm). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi, gerai diferencijuota (G1, 4 balai pagal Nottingham sis.) duktalinė karcinoma, suminis tyrimo TNM: pT1a(navikas - 4mm) pN0(sn)(0/3 l/m); LVI-0(Limfo-Vaskulinė naviko Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-43421 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.". 1. Riebalinis audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  2. Krūties audinyje - pavieniai dilatuoti latakėliai (židinys 1,5mm) su solidiniais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS). Riebalinis audinys su fibrozinėmis septomis, įvairaus kalibro latakėliais, klotais dvisluoksniu epiteliu.  3. Trys(3) limfmazgiai be naviko metastazių su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4. Krūties fibroziniame audinyje - navikas, formuojamas duktalinių, pavienių kribriforminių struktūrų iš vidutinio kalibro ląstelių, nežymiai polimorfiškais branduoliais su fokaliai išryškėjusiomis nukleolėmis; navike iki 2 mitozių/10 DPRL.. nan
answer:  4

 90%|████████▉ | 592/661 [09:04<01:04,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Dešiniosios krūties audinys  Kairiosios krūties audinys. 1. Riebalinio audinio fragmentas 42x9x7,5 cm su odos lopu 38x7,5 cm.  2. Riebalinio audinio fragmentas 41x9,5x6,5 cm su odos lopu 39x6 cm.. 1. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma;   pT1b(9 mm) pLVI-0 pR0.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 18%. Karštame taške 50%.    2. Krūties audinys be patologinių pokyčių.. 1. Krūties audinyje naviko (mikroskopiškai 9 mm skersmens) desmoplazinėje stromoje pabiros ląstelės ar pavienės jų linijinės struktūros su gausia saikingai eozinofiline citoplazma, stambios ląstelės ryškiai polimorfiškais branduoliais; mitozių navike iki 2 / 10 DPRL. Navikas apie 1 mm nuo operacinio krašto.. Blokas 5:  CK5: vidutinė ir stipri teigiama (++) membraninė reakcija 90 proc. atipinėse ląstelėse  CK7: stipri teigiama (+++) membraninė reakcija 100 proc. epitelio ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  GCDFP15:
answer:  0

 90%|████████▉ | 593/661 [09:04<01:00,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 4 mm; II - 3 mm; III - 4 mm.. Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.. Krūties audinyje mucininėje stromoje aiškių ribų netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  K
answer:  0

 90%|████████▉ | 594/661 [09:05<01:00,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas  - skubus tyrimas - be naviko  2(N2b) - kraštas  - skubus tyrimas - be naviko  3(N3) - sarginis limfmazgis - dviejose iš trijų limfmazgių makrometastazė.  4(N1) - pašalintas dešinės krūties kvadrantas - planinis tyrimas.. 4. Krūties sektorius 5,3x5x4 cm be odos. Pjūvyje pilkšvas, standus, aiškių ribų navikas 23x16x16 cm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Krūties duktalinės karcinomos metastazės 2/3 l/m (18 mm ir 2 mm, su ekstranodaliniu plitimu).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(22 mm) N(sn)1a(mts 2/3 l/m), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro ir smulkaus kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro ir smulkaus kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 2 iš 3 limfmazgiuose - žemiau aprašyto naviko metastazės (18 mm ir 2 mm), su ekstranodaliniu plitimu.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 22 mm), suformuotas fibrozuotoje stromoje ir tarp lipocitų infiltratyviai plintančių lizdinių, trabekulinių ir negausių, fokaliai besiliejančių tubulinių (~10%) struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška, fokaliai "tamsoka" citoplazma, vidutinio kalibro, ovaliais, kiek polimorfiškais, dalis su aiškia nukleole branduoliais. Mitozių iki 15/10 DPRL. Šalia yra dilatuotų kanaliukų su solidiniais ir kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais, fokaliai su komedo nekroze centre.. 1. Navikas (18 blokas):  HER2 imuninė reakcija: silpnas dalies membranos nusidažymas 2% naviko ląstelių.
answer:  1

 90%|█████████ | 595/661 [09:06<01:03,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2) - Kairės pažasties sarginiai limfmazgiai, skubu  4(3) - Kairės krūties sektorius, planinis. 4(3). Krūties sektorius 9x6x3 cm su odos lopu 4x0,8 cm, žymėtas viela. Vielos projekcijoje, pjūvyje balkšvas, standus navikas 13x10x9 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos – 5,5 cm.. 1(1a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   2(1b, ekstra). "Kraštai": fibrozuotas krūties audinys.   3(2, ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   4(3). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1c (navikas 11 mm) N0(sn) (0/3 l/m), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   HER2: reakcija neigiama (1+); AR(+)100%.    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: solidinis, kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).. 1(1a, ekstra). "Kraštai": aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   2(1b, ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu.   3(2, ekstra). "Sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4(3). NAVIKAS (mikroskopiškai 11 mm): krūties audinyje, ryškiai fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios retos kribriforminės ir besiliejančios dominuojančios lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, gausia šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis; mitozių iki 7/10 DPRL.   Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Pavieniai mikrokalcifikatai. Zona su gausia PMN infiltracija (g.b. biopsijos vieta).   APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: fibrozuotas krūties audinys; be naviko.. 4(3). NAVIKAS(10 blokas):   Androgenų receptoriai: (++/+++)(brand.r-ja)100%.   HER2: silpna (+) necirkuliari reakcija, 2-3%  naviko ląstelių membranoje.
answer:  1

 90%|█████████ | 596/661 [09:07<01:00,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1) pašalintas dešinės krūties kvadrantas - planinis tyrimas;  2(N2a) kraštai;  3(N2b) kraštai;  4(3). Dešinės pažasties sarginis limfmazgis;  5(4). Papildomas kraštas - planinis tyrimas.. 1. Krūties sektorius 8,5x4x4 cm su oda 7,5x2,5 cm, žymėtas viela. Vielos projekcijoje, krūties audinys fibrozuotas 5,5x2 cm, fibrozėje gelsvai pilkšvas, neaiškių ribų židinys 10x6x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 1 cm.  2. Riebalinio audinio fragmentas 1,5x1x1 cm. v/m  3. Riebalinio audinio fragmentas 2x1,2x0,7 cm. v/m  4. Riebalinio audinio fragmentas 3,5x2,5x0,6 cm. Rasti 2 limfmazgiai iki 1,6 cm. v/m  5. Riebalinio audinio fragmentas 2x1x0,4 cm. v/m. N1: Gerai diferencijuota (G1 , 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (10mm).  N2ab: Krūties audinys be naviko.  N3: Limfmazgiai (2 l/m) be naviko židinių; pN0(sn).  N4: Krūties audinys be naviko.. N1: Krūties audinyje 10mm navikas: netaisyklingos kampuotos duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 1/10 DPRL.  N2ab: Krūties audinys be naviko.  N3: Limfmazgiai (2 l/m) su reaktyviais pokyčiais, be naviko židinių.  N4: Krūties audinys be naviko.. nan
answer:  0

 90%|█████████ | 597/661 [09:08<01:00,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. sarginiai l/m, ekstra.   2. deš krūtis, planinis.. 2. Krūtis 804 gramų svorio, 20x17x8 cm. Krūties audinyje - balkšvi, neaiškių ribų židiniai:  -  centrinėje dalyje - I židinys - 0,7x0,5x0,4 cm (histologiniam tyrimui paimtas visas), nuo artimiausiojo rezekcijos krašto nutolęs 1,7 cm, nuo odos 2,5 cm.   -  apatinių kvadrantų riboje - II židinys (su paryškėjusios spalvos aplinkiniu riebaliniu audiniu, histologiniam tyrimui paimtas visas) - 1,5x0,7x1 cm, nuo  I-ojo židinio nutolęs 3 cm, nuo artimiausiojo rezekcijos krašto nutolęs 4 cm, nuo odos - 1 cm.  - virš pospenelinės zonos - III židinys - 1x0,7x0,6 cm (histologiniam tyrimui paimtas visas), nuo II-ojo židinio nutolęs 1,5 cm, nuo rezekcijos krašto - 4,5, nuo odos - 1 cm.  Visose krūties kvadrantuose vyrauja riebalinis audinys, yra negausios fibrozinės septos, pavienės apsuktos ryškesnės spalvos riebalinio audinio.. 1. Reaktyvi limfadenopatija (1 l/m).  2. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.2): pT1a(m) (0,4 cm ir 0,2 cm židiniai) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės invazijos nėra). Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, komedo tipas). R0(radikalus naviko pašalinimas).     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: teigiama (3+).  Ki67: 25%.. 1. Nežymi sinusų histiocitozė dviejuose (2) limfmazgiuose.  2. Krūties audinyje - kelios sritys su vidutinio kalibro kanaliukais (su solidiniais intraduktaliniais ląstelių su eozinofiliška citoplazma, vidutinio kalibro ir stambiais, polimorfiškais branduoliais proliferatais, nekrotinis detritas dalies kanaliukų spindžiuose) (DCIS), bei du (2) invazyvaus naviko židiniai (0,4 cm ir 0,2 cm skersmens): solidines naviko struktūras formuoja ląstelės su gan gausia tamsoka eozinofiline, amfofiline citoplazma, vidutinio ar stambaus kalibro apvalios formos saikingai netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 25 / 10 DPRL.. 2. Navikas (7 blokas): CK14(-).  Navikas (18 blokas): CK14(-).  DCIS (7,17,18 blokai): CK14+ bazinis sluoksnis išlikęs.
answer:  0

 90%|█████████ | 598/661 [09:09<01:01,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 2a - kraštas - extra  2. 2b - kraštas - extra  3. 2c - kraštas - extra  4(3). sarginiai limfmazgiai - extra  5(4) ėminio aprašas: N1 - pašalintas sektrius su naviku- planinis patologinis tyrimas skubus rengenis N1 tyrimas- navikas pašalintas. 5. Krūties sektorius 7,5x2,5x6 cm, su odos lopu 7x1,5 cm. Pjūvyje pilkšvas, standus, gan aiškių ribų navikas 30x26x20 mm, nuo giliojo rezekcijos krašto nutolęs 0,5cm, nuo odos - 2,2 cm.. Anksčiau atliktas aktualus VPC tyrimas, B23-23353:  1. Krūties audinys.  2. Krūties audinys.  3. Fibrocistiniai krūties pokyčiai, intraduktalinė krūties papiloma.  4. Reaktyvi limfadenopatija (1 l/m).  5. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT2(navikas 30 mm), pN0(sn)(0/1 l/m), LVI0(limfovaskulinis plitimas neidentifikuotas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Postbiopsiniai pokyčiai krūties audinyje.. 1. Krūties audinyje negausūs smulkūs kanaliukai, kloti dvisluoksniu epiteliu; židininė audinio fibrozė.  2. Krūties audinyje židininė fibrozė ir nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  3. Krūties audinyje - nežymiai dilatuotas latakas su fibrovaskulinėmis struktūromis, klotomis dvisluoksniu epiteliu monomorfiškais branduoliais; greta keli dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  4. Vienas limfmazgis su sinusų histiocitoze ir šerdies lipomatoze.  5. Krūties audinyje, hialinizuotoje stromoje plinta navikas (30 mm makroskopiškai) infiltratyviu augimo frontu. Navikas suformuotas smulkių lizdinių, trabekulinių ir negausių tubulinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma su vidutiniškai polimorfiškais, hiperchromiškais branduoliais su ryškiais branduolėliais. Mitozių navike iki 13/10DPRL. Limfovaskulinis plitimas neidentifikuotas (LVI0). Krūties audinyje greta naviko gausūs dilatuoti kanaliukai užpildyti solidinių ir kribriforminių proliferatų iš analogiškų navikui ląstelių apvaliais, kiek hiperchromiškais branduoliais. Krūties audinyje yra riebalinio audinio nekrozės plotas, rbotas histiocitų, pigmentuotų makrofagų ir svetimkūnio tipo giganitnių daugiabranuolių ląstelių.. Blokas 10:  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 91%|█████████ | 599/661 [09:10<00:59,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra (be patologijos);  2(2b). Kraštai - extra (be patologijos);   3. Sarginiai l/m - extra (be patologijos);  4(1). N1- sektorius - planinis patolginis tyrimas ir N1- skubus rentgeninis tyrimas - navikas pašalintas.. 4(1). Krūties sektorius 8x5,5x4,5 cm su odos lopu 7,5x2,9 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, aiškių ribų navikas 1,2x1x1,1 cm (sudėtas visas), siekia rezekcijos kraštą, nuo odos – 1,5 cm.. 1(2a). Kraštai - riebalinis audinys be patologinių pokyčių.    2(2b). Kraštai - riebalinis audinys be patologinių pokyčių.    3. Sarginiai l/m: limfmazgis (1) be patologinių pokyčių; pN0.    4(1). Sektorius. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma pT1c pLVI-0 pR0;  (G1; 4 b. pgl. Nottingham sist.).  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 8%.. 1(2a). Kraštai - riebalinis audinys be patologinių pokyčių.  2(2b). Kraštai - riebalinis audinys be patologinių pokyčių.  3. Sarginiai l/m: limfmazgis (1) be patologinių pokyčių.  4(1). Sektorius. Krūties audinį infiltruoja navikas (mikroskopiškai iki 12 mm), sudarytas   - duktalinių struktūrų (5% viso naviko), netaisyklingų kribrozinių kompleksų ir trabekulių;  - epitelinių smulkių ląstelių su neryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. nan
answer:  0

 91%|█████████ | 600/661 [09:11<00:56,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1. 18 G automatine biopsine adata punktuotas ~7×5 mm dydžio l/m be riebalinių vartų dešiniosios pažasties I zonoje, paimti 2 biopsiniai stulpeliai histologijai (I buteliukas).   2. 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais ~20×13 mm dydžio darinys dešiniojoje krūtyje ties 10 val. vidurinėje dalyje, paimti 3 biopsiniai stulpeliai histologijai (II buteliukas).. 1. 2 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 7 mm.  2. 3 fragmentuoti biopsiniai stulpeliai: I - 15 mm; II - 12 mm; III - 14 mm.. 1. Limfmazgio bioptatai su duktalinės karcinomos metastazėmis.   2. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: silpna (+) reakcija, 25% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.. 1. Limfmazgio bioptatai su žemiau aprašyto naviko židiniais.  2. Krūties audinį infiltruoja duktalinės struktūros (25%), netaisyklingi kribroziniai kompleksai ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. 2. Navikas (3 blokas):  Blokas 3:  Estrogenų receptoriai: silpna (+) reakcija, <1% naviko ląstelių branduoliuose.  Progesterono receptoriai: silpna (+) reakcija, 25% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 20%  naviko ląste
answer:  1

 91%|█████████ | 601/661 [09:12<00:53,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 11 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20-25%.. Krūties audinį infiltruoja negausios duktalinės struktūros ir netaisyklingi kribroziniai/solidiniai kompleksai iš neryškiai ar  vidutiniškai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 20
answer:  1

 91%|█████████ | 602/661 [09:13<00:56,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) kraštai - skubus tyrimas - be naviko  2(N2b) kraštai - skubus tyrimas - be naviko  3(N3) dešinės pažasties  sarginis limfmazgis - skubus tyrimas - 3 l/m be naviko  4(N1) pašalintas dešinės krūties kvadrantas - planinis tyrimas. 4(N1). Krūties sektorius 4x2,5x2,5 cm be odos, žymėtas viela. Vielos projekcijoje -  pilkšvas, standus, neaiškių ribų navikas 8x6x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm. Aplink naviką krūties audinys fibrozuotas su cistinėmis ertmėmis.. 1(2a). Krūties fibrocistiniai pokyčiai.  2(2b). Lobulinė krūties Carcinoma in situ (LCIS). Krūties fibrocistiniai pokyčiai.  3(3). Reaktyvi limfadenopatija (3 l/m).  4(N1). Krūties invazyvi, gerai diferencijuota (G2; 5 balai pagal Nottingham sis) lobulinė karcinoma, suminis tyrimo TNM: pT1b(m)(trys naviko židiniai - 1,5mm, 1,7mm ir 8mm) pN0(sn)(0/3 l/m); LVI-0(Limfo-Vaskulinė naviko Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-5935 tyrime:  "Estrogenų receptoriai: stiprus ar vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%."  Vidutinio laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas). Lobulinė krūties Carcinoma in situ (LCIS). Krūties fibroadenoma.  Krūties fibrocistiniai pokyčiai.. 1(2a). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, židinine apokrinine metaplazija.  2(2b). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, židinine apokrinine metaplazija. Fokaliai dilatuoti latakėliai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS).  3(3). Trys(3) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4(N1). Krūties fibroziniame audinyje - trys naviko židiniai (1,5mm, 1,7mm ir 8mm), formuojami trabekulinių struktūrų, smulkių agregatų, difuziškai plintančių vidutinio kalibro ląstelių, eozinofiliška citoplazma, nežymiai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 1 mitozės/10 DPRL. Aplinkiniame krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu, židinine apokrinine metaplazija. Fokaliai dilatuoti latakėliai su solidiniais atipinių diskohezyvių ląstelių proliferatais (LCIS). Pavieniai dilatuoti latakėliai su kribriforminiais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS). Krūties audinyje - ribotas darinys, formuojamas specializuotos fibrozinės stromos proliferatų supamų suspaustų latakėlių, klotų dvisluoksniu epiteliu.. nan
answer:  0

 91%|█████████ | 603/661 [09:14<00:55,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas be naviko   2(N2b) - kraštas - skubus tyrimas be naviko  3(N3) - dešinės pažasties sarginis limfmazgis - skubus tyrimas 3 l/m be naviko  4(N1) - pašalintas markiruotas dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 11x4,5x7,5 cm su oda 9,5x2 cm, žymėtas viela. Vielos projekcijoje pilkšvas, standus, aiškių ribų navikas 12x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,9 cm, nuo odos - 4,5 cm.. 1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(18 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).. 1(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  2(Extra). Krūties audinyje, neryškiai fibrozuotoje stromoje - vidutinio ir smulkaus kalibro kanaliukai, kloti dvisluoksniu epiteliu.  3(Extra). 3 limfmazgiai su neryškia sinusų histiocitoze ir lipomatoze.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 18 mm), suformuotas fibrozuotoje stromoje plintančių solidinių, lizdinių ir trabekulinių bei negausių (<10%) tubulinių struktūrų iš ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais, neryškiai polimorfiškais, dalis su smulkia nukleole branduoliais. Mitozių iki 6/10 DPRL. Šalia yra dilatuotų kanaliukų su kribriforminiais ir solidiniais intraduktaliniais analogiškų navikui ląstelių proliferatais.. nan
answer:  0

 91%|█████████▏| 604/661 [09:15<00:53,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pašalintas dešinės krūties kvadrantas - planinis tyrimas  2(2a). Kraštai - planinis tyrimas  3(2b). Kraštai - planinis tyrimas  4(3). Dešinės pažasties sarginis limfmazgis - planinis tyrimas  5(4). Papildomas kraštas - planinis tyrimas. 1(2a). Riebalinio audinio fragmentas 3,2x1,8x0,5 cm. v/m  2(2b). Riebalinio audinio fragmentas 1,8x1,3x0,6 cm. v/m  3. Riebalinio audinio fragmentai, bendras dydis 4,5x4x1,3 cm. Rasti 5 limfmazgiai iki 2,6 cm.  4. Krūties sektorius 12x7x4 cm su odos lopu 10,5x4 cm, žymėtas viela. Vielos projekcijoje balkšvas, standus, neaiškių ribų navikas 1,6x1x0,9 cm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 4 cm.  5. Riebalinio audinio fragmentas 2x1,5x0,3 cm. v/m. N1: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma, pT1c(16mm).  N2a: Gerai diferencijuotos invazinės lobulinės karcinomos židiniai (2,4mm ir 0,2mm).  N2b: Krūties audinys be naviko.  N3: Limfmazgiai be naviko (5 l/m); pN0(sn).  N4: Riebalinis audinys be naviko.. N1: Krūties audinyje 16mm: nedidelės duktalinės struktūros ir kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.  N2a: Krūties audinyje 2,4mm ir 0,2mm navikiniai židiniai: smulkūs solidiniai kompleksai ir juostos nedidelių apvalių minimaliai polimorfiškų ląstelių.  Naviko ląstelės ECAD-, Estrogenų receptorių reakcija teigiama 100% ląstelių.  Rezekcijos kraštas 0,4mm nuo naviko.  N2b: Krūties audinys be naviko.  N3: Limfmazgiai su lipomatozės židiniais, be naviko židinių (5 l/m).  N4: Riebalinis audinys be naviko.. nan
answer:  0

 92%|█████████▏| 605/661 [09:16<00:49,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm ilgio.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.. Krūties audinį infiltruoja nedideli netaisyklingi solidiniai kompleksai su pavieniais spindžiais iš neryškiai polimorfiškų ląstelių, mitozių iki 4/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  0

 92%|█████████▏| 606/661 [09:17<00:53,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 -deš. užspenelinė zona - extra  2 - deš. pažasties sarginiai l/m - extra   3 - deš.krūties liauka-planas  4 - kairės krūties liauka  5 - D.K pažasties limfmazgiai-planas. 3. Krūtis 171 gr svorio, 11x10x3 cm, su odos lopu 7,5x2,5 cm ir raumens fragmentu 4x2,5x1 cm, be spenelio. Krūties liauka persiūta ilgu siūlu lateraliai, trumpu viršus. Viršutiniame lateraliniame kvadrante balkšvas, standus, neaiškių ribų navikas 19x15x12 cm, nuo giliojo rezekcijos krašto 0,7 cm, nuo odos - 0,2 cm. Krūties audinys fibrozuotas visame plote.  4. Krūtis 183 gr svorio, 13x11x3 cm, žymėtas siūlais (operacijos protokole kairės krūties žymėjimas nenurodytas), be spenelio. Krūties audinys fibrozuotas visame plote.  5. Riebalinio audinio fragmentai, bendras dydis 7x4,5x1 cm su 3 limfmazgiais iki 1,3 cm.. PAPILDYTAS ATSAKYMAS (žr. molekuliniai):  1. Fibrocistiniai krūties pokyčiai.   2. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/3 l/m, 7,5 mm).  3. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) lobulinė karcinoma (21 mm židinys), TNM: pT2(21 mm naviko židinys), LVI2, pN1a(1/6 l/m). Naviko imunofenotipas nustatytas (žr.klinikinius duomenis). Krūties lobulinė karcinoma in situ (LCIS). Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS). Fibrocistiniai krūties pokyčiai: plokščia epitelio atipija, apokrininė epitelio metaplazija.   HER2: reakcija paribinė (2+). HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).  4. Fibrocistiniai krūties pokyčiai.   5. Reaktyvi limfadenopatija (3 l/m).. 1. Krūties audinyje ryški fibrozė su smulkiais kanaliukais ir dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Židininė apokrininė epitelio metaplazija.  2. Viename limfmazgyje iš trijų (1/3 l/m) žemiau aprašyto naviko metastazė iki 7,5 mm.  3. Krūties audinyje - navikas (21 mm mikroskopiškai), suformuotas trabekulinių/juostinių struktūrų iš vidutinio kalibro eozinofiline citoplazma ląstelių, vidutiniškai ir fokaliai ryškiai polimorfiškais branduoliais su paryškėjusiais branduolėliais; mitozių 12/10 DPRL. Limfovaskulinis plitimas (LVI2). Greta naviko gausūs dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Šalia keli dilatuoti kanaliukai užpildyti solidinių proliferatų iš negausia eozinoifline citoplazma ląstelių apvaliais, hiperchromiškais branduoliais. Aplinkiniame fibrozuotame krūties audinyje gausūs dilatuoti kanaliukai, kloti dvisluoksniu epiteliu ar metaplastišku apokrininiu epiteliu; keli nežymiai dilatuoti kanaliukai, kloti dvisluoksniu epiteliu su židinine epitelio proliferacija su kiek stratifikuotais, nežymiai polimorfiškais branduoliais.  4. Krūties audinyje ryški fibrozė, fokalinė stromos hislinozė su sklerozuotomis lobulėmis ir cistiškai dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Dalis kanaliukų klota epiteliu su apokrinine epitelio metaplazija.  5. Trys limfmazgiai su sinusų histiocitoze ir negausiais antriniais limfiniais folikulais.. Blokas 11:  HER2: vidutinė (++) necirkuliari reakcija, 20%  naviko ląstelių membranoje.  Blokas 12:  HER2: silpna (+) necirkuliari reakcija, 15%  naviko ląstelių membranoje.
answer:  0

 92%|█████████▏| 607/661 [09:18<00:51,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko.  2(2b). Kraštai - skubus tyrimas - be naviko.  3. Kairės pažasties limfmazgiai - planinis tyrimas.  4(1). Pašalintas kairės krūties kvadrantas - planinis tyrimas.. 3. Riebalinio audinio fragmentai, bendras dydis 6x4,7x1,3 cm. Rasti 5 limfmazgiai iki 1,7 cm.  4. Krūties sektorius 10x4,5x4 cm, su odos lopu 8x2,2 cm. Pjūvyje pilkšvas, standus neaiškių ribų, skiltėtas navikas 18x15x12 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos 1,5 cm.. 1(N2a) kraštai. Krūties audinys be patologinių pokyčių.  2(N2b) kraštai. Krūties audinys be patologinių pokyčių.    3. Kairės pažasties limfmazgiai. Karcinomos metastazės 2-se iš 5 limfmazgių; ekstranodulinio plitimo nestebima.    4(1). Pašalintas kairės krūties kvadrantas. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT1c pN1a pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacijos FISH tyrimo rezultatas neigiamas.  Ki67+ 20%.. 1(N2a) kraštai. Krūties audinys be patologinių pokyčių.  2(N2b) kraštai. Krūties audinys be patologinių pokyčių.  3. Kairės pažasties limfmazgiai. Solidinis atipinių epitelinių ląstelių plitimas (iki 11 mm) 2-se iš 5 limfmazgių; ekstranodulinio plitimo nestebima.  4(1). Pašalintas kairės krūties kvadrantas. Krūties audinį infiltruoja netaisyklingi šakoti kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 10/10 DPRL.. nan
answer:  0

 92%|█████████▏| 608/661 [09:19<00:47,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 12 mm; II - 12 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.. Krūties audinį infiltruoja netaisyklingi solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 3/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėrįa, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  Ki67
answer:  0

 92%|█████████▏| 609/661 [09:19<00:45,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 13 mm ilgio.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6,5 mm);  (G2; 7 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: silpna (+) reakcija, 15% naviko ląstelių.  HER2: reakcija teigiama (3+);   Ki67: proliferacinis indeksas 50%. Karštame taške 70%.    Vidutinio laipsnio intraduktalinė neoplazija (DIN2/DCIS).. Krūties audinį 1-me bioptate infiltruoja iki 6,5 mm :   - trabekulės;  - epitelinių vidutinio dydžio ląstelių su ryškiai polimorfiškais branduoliais  negausioje citoplazmoje;   - su mitozėmis iki 7 /10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.  Gretimai - analogiškų ląstelių solidinis proliferatas.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: stipri (+++) cirkuliari reakcija, 100% naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 50% naviko ląstelių. Karštame taške 70%.  Progesterono re
answer:  0

 92%|█████████▏| 610/661 [09:21<00:49,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - skubus tyrimas - be naviko;  2(2b). Kraštai - skubus tyrimas - be naviko;  3(N3). Dešinės pažasties sarginis limfmazgis - planinis tyrimas  4(N1). pašalintas dešinės krūties kvadrantas - planinis tyrimas. 3(N3). Riebalinio audinio fragmentai, bendras dydis 9x7x4 cm. Rasta 13 limfmazgių iki 3 cm, 2 limfmazgiuose matomi balkšvi standūs židiniai, didžiausiame iki 2,7 cm.  4(N1). Krūties sektorius 15x9x4 cm su odos lopu 14x7 cm. Odoje pilkšvi, smulkiai gruoblėti 3 dariniai, didžiausias 1,2x1,2 cm, artimiausias nuo odos rezekcijos krašto nutolęs 0,3 cm. Odoje rusva, aiškių ribų dėmė 0,4x0,3 cm (sudėta visa), nuo rezekcijos krašto (dažytas mėlyna) nutolusi 1 cm. Krūties audinyje pilkšvas, standus, aiškių ribų navikas 1,9x1,5x1,9 cm, nuo artimiausio rezekcijos krašto (dažytas mėlyna) nutolęs 0,3 cm, nuo odos – 1 cm.. 1(2a). Krūties fibrocistiniai pokyčiai. Krūties intraduktalinė papiloma.  2(2b). Krūties fibrocistiniai pokyčiai. Krūties intraduktalinė papiloma.  3(N3). Duktalinės karcinomos metastazės limfmazgiuose (3/13 l/m; iki 27mm; ekstranodalinis naviko plitimas).  4(N1). Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, pT1c(navikas - 19mm) pN1a(3/13 l/m; iki 27mm; ekstranodalinis naviko plitimas).   IHC reakcijos atliktos VPC:B23-33542 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  Ki67+ 10%.  ECAD+."  Odos seborėjinė keratozė. Odos kapiliarinė hemangioma.. 1(2a). Krūties audinys su fibrozinėmis septomis, fokaliai dilatuotais latakais, klotais dvisluoksniu epiteliu; pavieniai dilatuoti latakai su  fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu.  2(2b). Krūties audinys su fibrozinėmis septomis, fokaliai dilatuotais latakais, klotais dvisluoksniu epiteliu; pavieniai dilatuoti latakai su  fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu.  3(N3). Iš trylikos(13) rastų limfmazgių, trijuose(3) žemiau aprašyto naviko metastazės (iki 27mm; ekstranodalinis naviko plitimas).  4(N1). Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas solidinių, trabekulinių, kribriforminių, duktalinių (~15%) struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliai su fokaliai išryškėjusiomis nukleolėmis; navike iki 8 mitozių/10 DPRL; Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse. Naviko struktūros - 0,2mm nuo rezekcijos krašto.  Odos du dariniai - epidermio hiperkeratozė, papilomatozė, besiliejantys epidermio hiperplazijos plotai su pavienių raginių cistų formacija, bazinio sluoksnio hiperpigmentacija. Vienas iš odos darinių: papilinėje dermoje - dilatuotų plonasienių kraujagyslių proliferatai.. nan
answer:  0

 92%|█████████▏| 611/661 [09:21<00:45,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Paimti 3 biopsiniai stulpeliai.. 3 biopsiniai stulpeliai: I - 12 mm; II - 12 mm; III - 8 mm.. Krūties invazyvi adenokarcinoma, tikėtina lobulinė (ne mažiau kaip vidutiniškai diferencijuota /G2, 6-7 balai pagal Nottingham).  ---   Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100% .   Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 100% .   Her2 imunohistocheminė reakcija: neigiama (1+).  Ki67: 8%.. Trabekulines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne tamsoka citoplazma, vidutinio kalibro kiek netaisyklingais/polimorfiškais branduoliais; mitozių navike ne mažiau 5 / 10 DPRL.. Navikas  Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100% .   Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 100% .   HER2: silpnas(+) trūkinėjantis membraninis dažymasis 20% naviko ląstelių.   Ki67: 8% .   E-Cadherin: silpna
answer:  0

 93%|█████████▎| 612/661 [09:22<00:46,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2)- pašalinti sarginai l/m - extra (1 mts iš 3 l/m)  2.(N3) papildomi l/m - extra  2(N1)- pašalinta krūtis. 3. Krūtis 302 gramų svorio, 17x12x3 cm, spenelis įtrauktas (sudėtas visas). Krūties audinyje, spenelio projekcijoje pilkšvas standus, neaiškių ribų navikas 18x14x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2 cm. Krūties audinys fibrozuotas visame plote.. 1(Extra). Krūties duktalinės karcinomos metastazė 1/1 limfmazgyje (7 mm).  2(Extra). Reaktyvi limfadenopatija (2 l/m).  3. Krūties invazyvi blogai diferencijuota (G3; 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(12 mm) N(sn)1a(mts 1/3 l/m: 7 mm), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.  Imunofenotipas:   Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: nusidažiusių naviko ląstelių nėra.  HER2 imuninė reakcija: teigiama (3+).  Ki67: 70% (hot-spot 90%).   Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS)(kribriforminė, komedo).  Paget`o liga spenelyje.. 1(Extra). Limfmazgyje - žemiau (Nr.3) aprašyto naviko metastazė (7 mm).  2(Extra). 2 limfmazgiai su fokaline parakortekso hiperplazija, sinusų histiocitoze ir lipomatoze.  3. SPENELIS: epidermyje plinta žemiau aprašyto naviko ląstelės; išopėjimas paviršiuje. DCIS struktūros giliau.   NAVIKAS: krūties audinyje - ribotas navikas (mikroskopiškai 12 mm), suformuotas fibrozuotoje, fokaliai desmoplastiškoje stromoje infiltratyviai plintančių trabekulinių, lizdinių ir negausių (~10%) besiliejančių tubulinių ir kribriforminių struktūrų iš ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutinio kalibro ir stambiais, ovaliais, polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 36/10 DPRL. Pavieniai mikrokalcifikatai. Šalia yra dilatuotų kanaliukų su kribriforminiais intraduktaliniais analogiškų navikui ląstelių proliferatais, fokaliai su komedo nekroze centre. Navikas 3,1 mm nuo rezekcijos krašto.. 3. Spenelis (10 blokas): CK14+ mioepitelinis sluoksnis DCIS struktūrose.  Navikas (19 blokas):  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: nusidažiusių na
answer:  0

 93%|█████████▎| 613/661 [09:23<00:47,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, planinis  2. pjūvio kraštai, planinis.   3. sarginiai l/m, planinis.   4. sektorius, planinis.. 1. Riebalinio audinio fragmentas 4x2x1 cm. v/m   2. Riebalinio audinio fragmentas 4x1,5x1 cm. v/m   3. Riebalinio audinio fragmentai, bendras dydis 5x4x2 cm. Rasti 4 limfmazgiai, didžiausias 2,5 cm (suriebėję).    4. Krūties sektorius 14x8x6 cm su odos lopu 14x4 cm ir speneliu. Krūties audinyje balkšvas, standus, neaiškių ribų navikas 18x16x15 mm, nuo artimiausio rezekcijos krašto nutolęs 2 cm, siekia spenelį. Rezekcijos kraštas dažytas mėlynu tušu. Naviką supa pilkšva, standi fibrozės zona 9x6x3 cm, makroskopiškai siekianti rezekcijos kraštą. Fibrozės zonoje apvalus, standus darinys 0,9x0,8x0,7 cm.. 1. Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.  2. Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.  3. Reaktyvi limfadenopatija (4 l/m).   4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham sistemą) duktalinė karcinoma, suminis TNM: pT1c (18 mm navikas) N0(sn)(0/4 l/m) LVI-4 (limfovaskulinė invazija smulkiose ir stambiose kraujagyslėse). Radikalus pašalinimas. Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis ir kribriforminis tipai). Krūties fibroadenomos (iki 9 mm). Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.    Naviko imunotipas nustatytas biopsijoje:  Estrogenų receptoriai: stipri reakcija 90% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: teigiama (3+).  Ki67 proliferacinis aktyvumas 20%.. 1. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu, su židinine apokrinine metaplazija.  2. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu, su židinine apokrinine metaplazija.  3. 4 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.  4. Krūties audinyje - fibrozinėje stromoje, infiltratyviu frontu plintantis, stambius latakus apsupantis navikas, suformuotas lizdų, trabekulių, grandinėlių, kribriforminių struktūrų ir pavienių tubulių (<10 %),  Naviko ląstelės su vidutinio gausumo ar gausia, ryškia eozinofiliška citoplazma, vidutinio kalibro , apvaliais ar ovoidiškais, vidutiniškai polimorfiškais branduoliais su ryškiomis nukleolėmis. Mitozių navike iki 61/10DPRL. Naviko plitimas endotelizuotuose spindžiuose ir stambiose venose.   Šalia naviko dilatuoti kanaliukai su intraduktaliniais solidiniais ir kribriforminiais proliferatais iš analogiškų navikui ląstelių.  Atokiau krūties audinyje:  - du riboti dariniai (9 mm ir 1 mm skersmens), suformuoti miksoidinės proliferuojančių fibroblastų stromos su smulkiais, dilatuotais ar suspaustais latakais, klotais dvisluoksniu epiteliu.   - latakai su cistine dilatacija ir apokrinine metaplazija.. nan
answer:  0

 93%|█████████▎| 614/661 [09:24<00:43,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 14 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.. Krūties audinį infiltruoja juostos ir trabekulės iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.
answer:  0

 93%|█████████▎| 615/661 [09:25<00:45,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1. Sektoriaus kraštai. N2. Sektoriaus kraštai. N3. Sarginiai l/n. N4.K.krūties sektorius su naviku.. 4. Krūties sektorius 5x2,5x4,5 cm su odos lopu 3,5x0,6 cm. Krūties audinys fibrozuotas 4,5x4 cm plote. Fibrozėje pilkšvas, standus, neaiškių ribų navikas 20x14x14 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 0,8 cm.. 1(ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (6 l/m).   4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1c (navikas 20 mm) N0(sn) (0/6 l/m), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2:reakcijos nėra (0).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).. 1(ekstra). "Kraštai": fibrozuotas krūties audinys su gausiais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   2(ekstra). "Kraštai": fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": šeši (6) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   4. NAVIKAS (mikroskopiškai - 20 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai negausios besiliejančios duktalinės, dominuojančios trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai ar kiek ryškiau polimorfiškų ląstelių, negausia ar vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su  smulkiomis nukleolėmis; mitozių iki 25/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija.   APLINKA: šalia naviko - solidiniai, kribriforminiai, papiliniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, apokrinės metaplazijos zonomis.   GILUSIS REZEKCIJOS KRAŠTAS: navikas nuo artimiausio rezekcijos krašto nutolusios - 0,6 mm.. 4. Navikas (27 blokas):   E-Cadherin(+++)(membr.r-ja)100%;   HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 93%|█████████▎| 616/661 [09:26<00:41,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Deš. krūties didžiausio židinio (BIRADS V) ties ~10 val darinio stulpelinė biopsija, 2 stulpeliai histologinės medžiagos.. 2 biopsiniai stulpeliai: I - 7 mm; II - 7 mm.. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. Krūties audinį infiltruoja duktalinės struktūros ir kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 5%
answer:  0

 93%|█████████▎| 617/661 [09:27<00:41,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1-2. pjūvio kraštai, planinis.   3. sarginiai l/m, planinis.   4. sektorius, planinis.. 1. Riebalinio audinio fragmentas 2,5x2x0,6 cm. v/m  2. Riebalinio audinio fragmentas 2,2x1,5x1 cm. v/m  3. 2 pilkšvi limfmazgiai iki 0,7 cm. v/m  4. Krūties sektorius 12,5x8x7 cm su odos lopu 11x3 cm. Pjūvyje pilkšvas, standus neaiškių ribų 16x16x10 mm, pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,3 cm.. 1. Krūties audinio fibrozė.  2. Krūties audinio fibrozė.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(16 mm) pN0(sn)(0/3 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir papilinis tipai). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 12% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.. 1. Krūties audinys su fibrozės zonomis smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  2. Krūties audinys su fibrozės zonomis smulkiais kanaliukais, klotais dvisluoksniu epiteliu.  3. 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (16 mm) infiltratyviu ekspansyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, kribriforminėmis, papilinėmis struktūromis besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai-ryškiai polimorfiškais, ovaliais ir nereguliaraus kontūro skeltais branduoliais ryškiomis nukleolėmis; mitozių 4/10 DPRL.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių.. Navikas(14 blokas):  silpnas dalies membranos nusidažymas 2%.
answer:  0

 93%|█████████▎| 618/661 [09:28<00:43,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2: kairės pažasties sarginis limfmazgis - skubus tyrimas 3 l/m makrometastazės trijuose limfmazgiuose.   2. N1: pašalinta kairė krūtis planinis tyrimas  3. (N2)Likę pažasties limfmazgiai iš kairės pažasties  - planinis tyrimas priet Nr 2. 2. Krūtis 263,6 gramų svorio, 15,5x10,5x2,5 cm. Krūties audinyje:  - apatiniame medialiniame kvadrante - pilkšvas, standus, neaiškų ribų I navikas 35x25x14 mm, nuo artimiausio rezekcijos krašto nutolęs 0,3 cm, nuo odos - 1,2 cm;  - vidurinių kvadrantų riboje - pilkšvas, standus, neaiškių ribų II navikas 18x15x15 mm (sudėtas visas), nuo artimiausio rezekcijos krašto nutolęs 0,7 cm, nuo odos - 0,9 cm;  - centrinis krūties audinys balkšvas, standus, fibrozuotas visame plote;  - lateralinių kvadrantų riboje - pilkšvas židinys 8x8x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos 1 cm;  - atstumas tarp I ir II naviko 0,8 cm.  - I NAVIKAS SUDĖTAS NUO MEDIALINĖS PUSĖS LINK CENTRO (9-17 BLOKAI).  3. Riebalinio audinio fragmentai, bendras dydis 5x3,5x1,7 cm. Rasta 10 limfmazgių iki 1 cm.. 1. Krūties lobulinės karcinomos metastazės trijuose limfmazgiuose (3/3 l/m, 14 mm skersmens).   2. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) lobulinė karcinoma su duktalinės karcinomos komponentu (<3%), suminis TNM: pT2(m)(5 naviko židiniai nuo 1 mm iki 33 mm), pN2a(5/16 l/m), LVI2(limfovaskulinis plitimas). Krūties lobulinė karcinoma in situ (LCIS). I naviko židinys nuo koaguliuoto rezekcijos krašto nutolęs per <0,1 mm. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.  3. Krūties lobulinės karcinomos metastazės dviejuose limfmazgiuose (2/10 l/m, 5 mm skersmens).. 1(2). Trijuose iš trijų limfmazgių plinta navikas, analogiškas žemiau aprašytam. Naviko metastazės iki 14 mm skersmens su ekstranodaliniu plitimu.  2. Krūties audinyje - hialinizuotoje stromoje 5 naviko židiniai (33mm, 14mm, 2mm, 1,5mm ir 1 mm mikroskopiškai) infiltratyviu augimo frontu, suformuoti trabekulinių, juostinių naviko struktūrų. Naviko ląstelės negausia eozinofiline citoplazma, vidutiniškai polimorfiškais, hiperchromiškais branduoliais su pavieniais, paryškėjusiais branduolėliais. Mitozių navike iki 6/10DPRL. Limfovaskulinė naviko invazija (LVI2). I-jame naviko židinyje yra kitas naviko komponentas (1,5 mm), suformuotas tubulinių ir negausių trabekulinių struktūrų ir negausia eozinofiline citoplazma ląstelių su vidutiniškai polimorfiškais branduoliais, ryškiais branduolėliais.   I navikas nuo artimiausio rezekcijos krašto nutolęs per 0,1 mm. Šalia naviko dilatuoti kanaliukai užpildyti solidinių proliferatų iš monomorfiškų ląstelių apvaliais, kiek hiperchromiškais branduoliais. Spenelis be patologinių pokyčių.  3. Dviejuose limazgiuose iš 10 (2/10 l/m) plinta navikas, analogiškas aukščiau aprašytam. Naviko metastazės iki 5 mm skersmens.. Blokas 12(duktalinis komponentas):  E-Cadherin: (++)membra.r-ja 90%(duktaliniame komponente)  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.  Prog
answer:  10

 94%|█████████▎| 619/661 [09:30<00:45,  1.09s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštai - extra - be naviko  2(N2b). kraštai - extra - be naviko  3(N3). sarg. l/m - extra - be naviko  4(N1). sektorius, planinis, Skubus Ro - 10 mm navikas, MK  pašalintas. 4(1). Krūties sektorius 12x10,5x4,5 cm su odos lopu 8,5x3,5 cm. Krūties audinyje, balkšva, standi fibrozė 4x4 cm plote, nuo giliojo rezekcijos krašto nutolęs 0,1 cm. Fibrozėje neaiškių ribų, pilkšvas židinys 10x10x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 1,6 cm.. Papildytas HER2 FISH tyrimu:  1(2a, ekstra). "Kraštai": dažais žymėtoje pusėje - fibrozuotas krūties audinys; be naviko;  (dažais nežymėtoje pusėje - krūties fibrocistiniai pokyčiai: paprasta ir atipinė intraduktalinė hiperplazija).   2(2b, ekstra). "Kraštai": dažais žymėtoje pusėje - fibrozuotas krūties audinys; be naviko;   (dažais nežymėtoje pusėje - krūties fibrocistiniai pokyčiai: paprasta ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė).   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(1). Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 7 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).   Kalcifikatai.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis ir papilinis tipai; bendra pokyčių zona su naviku ~15 mm skersmens).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).. 1(2a, ekstra). "Kraštai": dažais žymėtame krašte - fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko. Priešingoje dažais nežymėtoje pusėje - kelios zonos su ryškesne epitelio atipija.   2(2b, ekstra). "Kraštai": dažais žymėtame krašte - fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu epiteliu; be naviko. Priešingoje dažais nežymėtoje pusėje - kelios zonos su ryškesne epitelio atipija, fokaliai suspausti kanaliukai, kloti dvisluoksniu epiteliu.   3(ekstra). "Sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.     4(1). NAVIKAS (mikroskopiškai - 7 mm infiltratyvus židinys; su aplinkine fibroze ir in situ pokyčių zona - 15 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios duktalinės, netaisyklingos liaukinės, kribriforminės ir retos lizdinės naviko struktūros, suformuotos vidutiniškai polimorfiškų ląstelių, vidutinio gausumo šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais kiek skeltais branduoliais; mitozės pavienės retos, mažiau 5/10 DPRL. Naviko ląstelės fokaliai su apikalinėmis sekrecinėmis vakuolėmis. Pavieniai mikrokalcifikatai.  APLINKA: šalia naviko - kribriforminiai ir papiliniai intraduktaliniai naviko ląstelių proliferatai.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, intraduktalinėmis papilinėmis formacijomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti.   SEKTORIAUS REZEKCIJOS KRAŠTAS: fibrozuotas krūties audinys su aukščiau aprašytais fibrocistiniais pokyčiais; be naviko.. 4(1). Navikas (blokas 15):  CK14/CK5(+) miopetelinis sl. in situ komponente;   HER2: vidutinė (++) necirkuliari reakcija, 20% naviko ląstelių membranoje.
answer:  0

 94%|█████████▍| 620/661 [09:31<00:44,  1.08s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2A)-kraštas -extra-muvcininės karcinomos židinys  2(N2b)-kraštas -extra-be naviko   3(N3)-l/m-extra-be naviko   4.(pap.kraštas Nr.4) extra - Atlikta krašto reekscizija - be naviko   5.(N1)- sektorius - skubus rentgeninis tyrimas- 2 navikai pašalinti N1- sektorius -  planinis patologinis tyrimas. 5. Krūties sektorius 9,5x6x4 cm su odos lopu 9x3,5 cm žymėtas 2 vielomis(atstumas tarp vielų - 4,5 cm). I vielos projekcijoje pilkšvas, elastingas, kiek mucininis I navikas 16x11x10 mm. II vielos projekcijoje analogiškas II navikas 14x10x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos – 2,5 cm.. 1(2a). Krūties invazyvi, vidutiniškai diferencijuota (G2) mucininė karcinoma.  Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas).  2(2b). Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis, mikropapilinis tipas).  3. Reaktyvi limfadenopatija (1 l/m).  4(pap. kraštas). Krūties audinys.   5. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) mucininė karcinoma, suminis tyrimo TNM: pT1c(m)(du naviko židiniai: 16mm ir 14mm) pN0(sn)(0/1 l/m).   IHC reakcijos atliktos VPC:B23-31824 tyrime:   "Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 3%."  Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas).. 1(2a). Krūties audinyje - ekstraląstelinių mucinų zonos su naviko ląstelių kompleksais; fibrozinėje stromoje - dilatuoti latakai su kribriforminiais atipinių ląstelių (su nedidelio laipsnio branduolių polimorfizmu) prolideratais (DCIS).  2(2b). Krūties audinyje - fibrozės zonos su dilatuotais latakais, fokaliai su mucinais spindžiuose ir mikropapiliais, kribriforminiais atipinių ląstelių (su nedidelio laipsnio branduolių polimorfizmu) proliferatais (DCIS).   3. Vienas(1) limfmazgis be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4(pap. kraštas). Riebalinis audinys su fibrozinėmis septomis, pavieniais latakėliais, klotais dvisluoksniu epiteliu.   5. Krūties audinyje - du naviko židiniai (16mm ir 14mm), formuojami ekstraląstelinių mucinų su smulkiais solidiniais naviko kompleksais, formuojamais vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike iki 4 mitozių/10 DPRL. Aplinkiniame krūties audinyje - fibrozės zonos su dilatuotais latakais, fokaliai su mucinais spindžiuose ir kribriforminiais atipinių ląstelių (su nedidelio laipsnio branduolių polimorfizmu) proliferatais (DCIS).. nan
answer:  0

 94%|█████████▍| 621/661 [09:32<00:42,  1.05s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- Deš. pažasties sarginiai limfmazgiai, skubu  4(3)- Deš. krūties kvadrantas, planinis. 4. Krūties sektorius 8x6x6 cm su odos lopu 8x1 cm. Pjūvyje balkšvas, spikulinių kraštų, standus navikas 18x14x23 mm, nuo artimiausio rezekcijos krašto nutolęs 1 cm, nuo odos – 0,7 cm.. Atlikti pjūviai Prosigna.  1(ekstra). Riebalinis audinys.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(18 mm navikas) pN0(sn)(0/3 l/m) LVI-2(limfovaskulinė invazija).   R0(radikali rezekcija). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, kribriforminis tipas).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 15%.. 1(ekstra). Riebalinis audinys su fibrozinėmis septomis.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.   3(ekstra). 3 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (18 mm) infiltratyviu augimo frontu, suformuotas, susiliejančiomis tubulinėmis, kribriforminėmis ir trabekulinėmis struktūromis besidėstančių ląstelių  vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 16/10 DPRL. Limfovaskulinė invazija. Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais ir solidiniais su "komedo" tipo nekroze proliferatais iš analogiškų navikui ląstelių.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) ---- %.  Progesterono receptoriai: (+++)(brand. r-ja) ---- %.  HER2: silpnas/vidutinis/stiprus dalies/visos membranos nusidažymas xx% naviko ląstelių.  Ki67 proliferacinis aktyvumas ---- %.  CK5+ išlaiky
answer:  0

 94%|█████████▍| 622/661 [09:33<00:42,  1.08s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N1). Sarginiai l/n-extra.   2(N2). Kairė krūtis su naviku.. 2. Krūtis 381 gramų svorio, 17x10,5x4,5 cm, spenelis įdubęs. Apatiniame medialiniame kvadrante - pilkšvas standus, aiškių ribų navikas 21x20x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 1,8 cm. Centrinė krūties dalis fibrozuota 8x5,5 cm plote. Makroskopiškai fibrozėje satelitiniai naviko židiniai neidentifikuojami.. PAPILDYTAS ATSAKYMAS HER2 FISH TYRIMU:   1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (5 l/m).     2. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT2 (navikas 21 mm) N0(sn) (0/5 l/m),    LVI-0 (limfovaskulinė invazija neidentifikuota).    Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.    Molekuliniai tyrimai:   HER2 geno amplifikacija nenustatyta (interpretuojama įvertinus HER2 IHC tyrimą; žr. molekulinio tyrimo aprašymą ir pastabas).    Krūties lobulinė intraepitelinė neoplazija (LCIS).  Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė duktalinė hiperplazija, sklerozuojanti ir mikroglandulinė adenozė, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija; fokaliai fibrocistiniai pokyčiai - kompleksiniai, sudarantys iki 10 mm skersmens židinius).   Krūties rezekcijos kraštas - be naviko.. 1(ekstra). "Sarginiai limfmazgiai": penki (5) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.   2. SPENELIS: klotas fokaliai akantotišku epidermiu su židinine bazinio sl. hiperpigmentacija.   NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta trabekulinės struktūros, trumpos "grandinėlės", solidinės naviko struktūros, suformuotos mažai kohezyvių saikingai ar vidutiniškai polimorfiškų ląstelių, negausia ar vidutinio gausumo šviesia citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 12/10 DPRL. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija. Smulkūs kalcifikatai. Pavieniais hemosiderofagai.   APLINKA: zonos su dilatuotomis lobulėmis, užpildytomis nedideliais apvalių monomorfiškų, su šviesia citoplazma ląstelių proliferatais. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, stulpinių ląstelių pokyčiu su apikaline sekrecija (CCAPSS), fokaliai smulkūs suspausti, kiek dilatuoti kanaliukai, kloti dvisluoksniu epiteliu, fokaliai nedideli intraduktaliniai proliferatai; fokaliai krūties audiniopokyčiai sudaro ribotus lobulizuotus gan ribotus židinius su edemiška stroma, iki 10 mm skersmens. Atliktas platus fibrozuotos zonos ištyrimas.   GILUSIS REZEKCIJOS KRAŠTAS: infiltratyvus navikas nutolęs 5 mm.. 2. Navikas (blokas 14):  HER2: vidutinė (++) necirkuliari reakcija, 10%  naviko ląstelių membranoje.
answer:  1

 94%|█████████▍| 623/661 [09:34<00:39,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. deš krūtis su pažasties l/m, planinis. Krūtis 500 g svorio, 20x13,5x4,5 cm, su raumens fragmentu 2,2x1,6x0,6 cm.   Krūties audinyje, viršutinių kvadrantų riboje, pilkšvas standus neaiškių ribų I navikas 27x20x12 mm (pereinantis į fibrozę), nuo giliojo rezekcijos krašto nutolęs 0,2, nuo odos - 2,2 cm.   Raumens projekcijoje pilkšvas standus, neaiškių ribų II navikas 20x20x12 cm., nuo giliojo rezekcijos krašto nutolęs 0,2 cm, siekia odą. Atskirai tame pačiame inde, pažasties narvelienos fragmentas 8,5x6x2,5 cm. Rasta 10 limfmazgių iki 2 cm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;   pT(m)2(22 mm, 27 mm)   pN1a(2,2 mm 1-me/10 l/m)   pR0 (0,5 mm)   pPn1(perineurinis plitimas).  Metastazės limfmazgyje imunotipas:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).    Imunotipas priešoperaciniame naviko tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%.. Krūties audinyje 2 navikiniai židiniai (I-as 22 mm, II-as 27 mm): infiltruoja duktalinės ir negausios kribrozinės struktūros iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  I-as navikas 2 mm , II-as navikas 0,5 mm nuo operacinio krašto ir su perineuriniu plitimu.  Aprašyto naviko ląstelių solidiniai židiniai iki 2,2 mm 1-me/10 limfmazgyje; ekstranodulinio plitimo nestebima.. Blokas 23:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.
answer:  0

 94%|█████████▍| 624/661 [09:35<00:37,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 1 pjūvio kraštas, ekstra.  2. 2 pjūvio kraštas, ekstra.   3. sarginiai l/m, ekstra.  4. sektorius, planinis.. 4. Krūties sektorius 12,5x4,5x6,5 cm, su odos lopu 9x3 cm, žymėtas viela. Vielos projekcijoje pilkšvas, standus  gan aiškių ribų navikas 13x10x8 mm, nuo giliojo rezekcijos krašto nutolęs 2 cm, nuo odos - 2,2 cm. Navikas histologiniam ištyrimui sudėtas visas.. 1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai, paprasta intraduktalinė hiperplazija. Intraduktalinė krūties papiloma.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi, vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(navikas - 13mm) pN0(sn)(0/3 l/m); LVI-0 (Limfo-Vaskulinė naviko Invazija neidentifikuota).   IHC reakcijos atliktos VPC:B23-19620 tyrime:  "Estrogenų receptoriai: stipri (+++)  reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67+ 15%."  Vidutinio laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas).. 1. Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu.  2. Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu su židinine apokrinine metaplazija; dilatuoti latakėliai su paprasta intraduktaline hiperplazija; dilatuoti latakėliai su fibrovaskulinės stromos papilinėmis struktūromis, klotomis dvisluoksniu epiteliu.  3. Trys(3) limfmazgiai be naviko metastazių, su reaktyvia folikulų hiperplazija, sinusų histiocitoze.  4. Krūties fibroziniame audinyje ir tarp lipocitų plinta navikas, formuojamas solidinių/lizdinių, pavienių duktalinių struktūrų iš vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais su fokaliai ryškiomis nukleolėmis; navike - iki 10 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su kribriforminiais atipinių ląstelių (su vidutinio laipsnio branduolių polimorfizmu) proliferatais (DCIS). Rezekcijos kraštas be naviko.. nan
answer:  0

 95%|█████████▍| 625/661 [09:35<00:34,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 stulpeliai. 2 biopsiniai stulpeliai: I - 17 mm; II - 15 mm.. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: teigiama ribinė neigiama (0).  Ki67 proliferacinis aktyvumas 40%.. Bioptatuose (2/2) - fibrozinėje stromoje, infiltratyvios naviko struktūros, lizdais, trabekulėmis ir solidiniai plotais besidėstančių ląstelių negausia-vidutinio gausumo eozinofiliška citoplazma, ryškiai polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 22/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 100%.  HER2: silpnas pavienių naviko ląstelių membr. dažymasis.  Ki67 proliferacinis aktyvumas 40%.  GATA3(+++)(brand. r-ja) 100%; E-cadherin(+++) memb
answer:  100

 95%|█████████▍| 626/661 [09:36<00:32,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: NR1 Kair. krūties dominuojančio darinio biopsija, paimti 3 biopsiniai stulepliai  2 ėminio aprašas: NR2 Kair. krūties satelitinio darinio biopsija, paimti 2 biopsiniai stulepliai  3 ėminio aprašas: NR 3 Kair. pažasties pakitusio l/m biopsija, paimti 2 biopsiniai stulepliai. 1. 3 biopsiniai stulpeliai: I - 15 mm; II - 11 mm; III - 9 mm.  2. 2 biopsiniai stulpeliai: I - 11 mm; II - 9 mm.  3. 2 fragmentuoti biopsiniai stulpeliai: I - 12 mm; II - 12 mm.. N1-2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.  N3: Limfmazgio bioptatai ne naviko.. N1-2: Visuose krūties audinio bioptatuose tokios pačios struktūros navikas: duktalinės struktūros, nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  N3: Limfmazgio bioptatai ne naviko.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 30% naviko ląstelių.  Ki67+ 10%
answer:  1

 95%|█████████▍| 627/661 [09:37<00:30,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 but.  2 biopsiniai stulpeliai iš ploto kairėje viršutiniame kvadrante   2 but.  2 biopsiniai stulpeliai iš ploto kairėje  virš spenelio @#3 but. 1 biopsinis stulpelis iš darinio dešinėje krūtyje  viršutiniame lateraliniame kv-te. 1. 2 fragmentuoti biopsiniai stulpeliai: I - 7 mm; II - 9 mm.   2. 2 biopsiniai stulpeliai: I - 14 mm; II - 10 mm.   3. Biopsinis stulpelis 9 mm.. Kairė  N1-2: Intraduktalinė krūties Carcinoma in situ (Din2/DCIS; solidinis/kribriforminis tipas).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  ---------  Dešinė  N3: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis iki 20%.. Kairė  N1-2: Krūties audinyje dilatuotuose kanaliukuose solidiniai/kribroziniai neryškiai polimorfiškų ląstelių proliferatai.  ---------  Dešinė  N3: Krūties audinį infiltruoja pavienės duktalinės struktūros, nedideli netaisyklingi solidiniai kompleksai iš neryškiai ir vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. nan
answer:  1

 95%|█████████▌| 628/661 [09:38<00:28,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai; I - 13 mm; II - 9 mm.. Krūties invazyvi blogai diferencijuota (G3, 8-9 balai pagal Nottingham) duktalinė adenokarcinoma.  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2: imuninė reakcija neigiama (0 balų).  Ki67: 45%.. Solidines naviko struktūras formuoja ląstelės su negausia ar kiek gausesne blyškiai-saikingai eozinofiline citoplazma, vidutinio kalibro apvalios formos saikingai netaisyklingais/polimorfiškais branduoliais; mitozių navike iki 40 / 10 DPRL.. Navikas  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2: nusidažiusių naviko ląstelių nėra.  Ki67: 45%. CK5(+/++)(citoplazminė r-ja), 20%.
answer:  1

 95%|█████████▌| 629/661 [09:39<00:27,  1.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 but.  3 biopsiniai stulpeliai iš ~ 10 mm  neaiškių ribų  dešinės krūties darinio   2 but. 2 biopsiniai stulpeliai iš  ~ 30 mm dydžio kairės krūties darinio. 1. 3 biopsiniai stulpeliai: I - 21 mm; II - 14 mm; III - 10 mm.  2. 2 fragmentuoti biopsiniai stulpeliai: I - 11 mm; II - 13 mm.. Po operacinės medžiagos tyrimo patikslintas N1 naviko tipas  Dešinė  N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.  ------------  Kairė  N2: Mucininė krūties karcinoma (G2, 6 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Dešinė  N1: Krūties audinį infiltruoja smulkios duktalinės struktūros ir solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.  ------------  Kairė  N2: Krūties audinyje mucininėje stromoje solidiniai/kribroziniai kompleksai vidutinio polimorfizmo ląstelių, mitozių iki 3/10 DPRL.. nan
answer:  0

 95%|█████████▌| 630/661 [09:40<00:29,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. 1a- viršutinis kraštas, skubu  2. 1b- apatinis kraštas, skubu  3. (2.) Deš. pažasties sarginiai limfmazgiai, skubu  4. (3) deš. krūties sektorius, planinis. 4. Krūties sektorius 6x3,3x6 cm, su odos lopu 5,5x2 cm, žymėtas viela. Vielos projekcijoje pilkšvas, neaiškių ribų, standus navikas 12x12x10 mm, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos nutolęs 2 cm.. 1(1a, ekstra). "Viršutinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   2(1b, ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.    3(2, ekstra). "Deš. pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) mucininė karcinoma,   SUMINIS TNM:   pT1c (navikas 12 mm) N0(sn) (0/3 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose).     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis ir papilinis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Nuo sektoriaus rezekcijos krašto navikas nutolęs 0,15 mm.. 1(1a, ekstra). "Viršutinis kraštas": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu; be naviko.   2(1b, ekstra). "Apatinis kraštas": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu; be naviko.   3(2, ekstra). "Deš. pažasties sarginiai limfmazgiai": trys (3) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.     4. NAVIKAS (mikro 12 mm židinys, su aplinkine fibroze pokyčių plotas ~22 mm skersmens):   krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, tarp gausių AB+ ekstraląstelinių mucinų telkinių infiltratyviai plinta fokaliai besiliejančios papilinė, kribriforminės ir lizdinės naviko struktūros, suformuotos saikingai polimorfiškų ląstelių, vidutinio gausumo eozinofiline citoplazma, vidutinio dydžio kiek nelygaus kontūro ovaliais/apvaliais branduoliais su smulkiomis nukleolėmis; mitozių iki 14/10 DPRL. Limfovaskulinė naviko invazija smulkiose šakose.   APLINKA: šalia naviko - keli kribriforminiai ir papiliniai intraduktaliniai naviko ląstelių proliferatai. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: navikas nutolęs 0,15 mm.. 4. Navikas (blokas 15):  EMA(+) židininė citopl. r-ja.   HER2: silpna (+) necirkuliari reakcija, 20% naviko ląstelių membranoje.
answer:  1

 95%|█████████▌| 631/661 [09:41<00:26,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.N2a - skubu - kraštai  2.N2b kraštai  -  skubus tyrimas - be naviko  3. N3: dešinės pažasties sarginis limfmazgis - skubus tyrimas 1 l/m be naviko.  4. N1: dešinės krūties kvadrantas - planinis tyrimas. 4. Krūties sektorius 12x7x4cm su odos lopu 11x2,7 cm. Krūties audinyje - balkšvas, standus, vietomis neaiškių ribų navikas 2x1,4x1,8 cm, nuo giliojo rezekcijos krašto (dažytas mėlynu tušu) nutolęs 0,7 cm, nuo odos - 4 cm.. N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(20mm).  N2ab: Audiniai be naviko.  N3: Limfmazgis (1 l/m) be naviko; pN0(sn).. N1: Krūties audinyje 20mm navikas: negausios smulkios duktalinės struktūros, netaisyklingi kribroziniai ir solidiniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.  N2ab: Audiniai be naviko.  N3: Limfmazgis (1 l/m) be naviko.. nan
answer:  0

 96%|█████████▌| 632/661 [09:42<00:26,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. (2). Kairės pažasties sarginiai limfmazgiai, skubu  2. (1a)- viršutinis kraštas, skubu  3. (1b)- apatinis kraštas, skubu.   4. (3). Kairės krūties kvadrantas, planinis. 4. Krūties sektorius 9,5x7,5x5 cm, su odos lopu cm. Krūties audinyje, pjūvyje pilkšvas, standus, gan aiškių ribų navikas 35x35x25 mm, nuo giliojo rezekcijos krašto nutolęs 1,3 cm, nuo odos - 2,6 cm.. 1(2)(Extra). Reaktyvi limfadenopatija (3 l/m).  2(1a)(Extra). Krūties audinys.  3(1b)(Extra). Krūties audinys.  4. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(33 mm) N(sn)0(0/3 l/m), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).. 1(2)(Extra). 3 limfmazgiai su negausiais antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  2(1a)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  3(1b)(Extra). Krūties audinyje, fibrozuotoje stromoje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu epiteliu.  4. Krūties audinyje - ribotas navikas (mikroskopiškai 33 mm), suformuotas fibrozuotoje stromoje ir tarp lipocitų infiltratyviai plintančių lizdinių, trabekulinių ir besiliejančių tubulinių struktūrų bei negausių smulkiomis grupėmis ar grandinėlėmis besidėstančių ląstelių vidutinio gausumo švelniai eozinofiliška ar blyškia citoplazma, vidutinio kalibro, ovaliais ar kiek nereguliaraus kontūro, vidutiniškai polimorfiškais, dalis su smulkia nukleole branduoliais. Gausūs retrakcijos artefaktai aplink naviko struktūras. Mitozių iki 4/10 DPRL. Negausūs makrofagų ir limfocitų židiniai, smulkios elastozės zonos.  Aplinkiniame krūties audinyje - dilatuoti kanaliukai/latakai, fokaliai su makrofagais spindžiuose.. 1. Navikas (15 blokas): EMA(+/+++)(citopl.-membr. r-ja), 85%; naviko struktūros D2-40+ endotelizuotoje ertmėje.  Navikas (19 blokas):  E-Cadherin(++/+++)(cirkuliari, fokaliai trūkinėjanti membr. r-ja), 100%;   p120(+++)(cirkuliari, fokaliai trūkinėjanti m
answer:  100

 96%|█████████▌| 633/661 [09:43<00:26,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. sarginiai l/m, ekstra.  2 .pap.sarginis l/m-extra   3(2). kairė krūtis, planinis.. 2. Krūtis 24x20x6,5 cm, 1300 gramų svorio. Odoje neaiškių ribų, gruoblėta dėmė 1,4x0,7 cm, nuo odos nutolusi 0,3 cm. Krūties audinyje, apatinių kvadrantų riboje pilkšvas, skiltėtas, standus navikas 34x25x20 mm, nuo giliojo rezekcijos krašto nutolęs 3 cm, nuo odos - 2,5 cm. Šalia naviko pilkšvas, ribotas darinys 0,4x0,4x0,4 cm.. 1(Extra). Reaktyvi limfadenopatija (6 l/m).  2(Extra). Reaktyvi limfadenopatija (1 l/m).  3. Krūties invazyvi blogai diferencijuota (G3; 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT(m)2(2 naviko židiniai: 28 mm ir 4 mm) N(sn)0(0/7 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas (R0).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Odos seborėjinė keratozė.. 1(Extra). 6 limfmazgiai su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  2(Extra). Limfmazgis su antriniais limfoidiniais folikulais, fokaline parakortekso hiperplazija ir sinusų histiocitoze.  3. SPENELIS: be patologijos.  ODA: darinys su epidermio papiliarizacija ir neryškia akantoze ir hiperkeratoze, bazinių ląstelių hiperplazija ir hiperpigmentacija bei smulkiomis keratininėmis cistomis.  NAVIKAS: krūties audinyje - 2 riboti analogiškos struktūros navikai (mikroskopiškai 28 mm ir 4 mm), suformuoti fibrozuotoje stromoje plintančių trabekulinių, lizdinių ir negausių solidinių struktūrų iš ląstelių vidutinio gausumo eozinofiliška citoplazma, vidutinio kalibro ir kiek stambesniais, ovaliais, polimorfiškais, su aiškia nukleole branduoliais. Mitozių iki 35/10 DPRL. Navike yra nekrozės zonų, fokalinė intra-/perinavikinė MMN infiltracija.. 1. Navikas (24 blokas):  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  Proliferacinis aktyvumas: Ki67(+++)(branduolinė r-
answer:  50

 96%|█████████▌| 634/661 [09:44<00:27,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. pjūvio kraštai, ekstra.  2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.   4. sektorius, planinis.. 4. Krūties sektorius 12x7x6 cm su odos lopu 10x4 cm, žymėtas viela. Metalinė viela pilnai perveria sektorių. Krūties audinyje:  - 3 cm nuo vielos - balkšvas, standus, neaiškių ribų I navikas 1,2x0,8x1,2 cm, nuo artimiausio rezekcijos krašto nutolęs 0,1 cm, nuo odos – 1,4 cm. Navikas histologiniam ištyrimui sudėtas visas.  - vielos projekcijoje - balkšvas, standus II naviko židinys 0,2 cm skersmens, nuo rezekcijos krašto nutolęs 0,5 cm.   Aplinkiniame krūties audinyje cistos iki 0,8 cm skersmens. Krūties audinyje, 1,5 cm atstumu nuo vielos rasta metalinė kabutė, aplinkiniai audiniai be makroskopinių pokyčių.. 1(ekstra). Pjūvio kraštai. Krūties fibrocistiniai pokyčiai, apokrininė metaplazija. Naviko plitimo nėra.    2(ekstra). Pjūvio kraštai. Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.     3(ekstra). Sarginiai l/m. Duktalinės karcinomos metastazė 2-se/9 limfmazgių (iki 2,1 mm metastazė).     4. Sektorius.   Krūties invazyvi vidutiniškai diferencijuota duktalinė karcinoma   (G2, I navike - 7 balai, II navike - 6 balai pagal Nottingham sistemą) ,    pT1c(m) (12 mm ir 2 mm naviko židiniai)    pN1a(sn)(2-se/9 l/m su mts iki 2,1 mm)     pLVI-2 (limfovaskulinė invazija smulkiose gyslose)    pR0(radikalus pašalinimas).  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%. Karštame taške 20%.. 1(ekstra). Pjūvio kraštai. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu, su židinine apokrinine metaplazija. Naviko plitimo nėra.  2(ekstra). Pjūvio kraštai. Krūties audinys su fibrozės zonomis ir smulkiais, dalis cistiškai dilatuotais kanaliukais bei lobulėmis, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.  3(ekstra). Sarginiai l/m. Riebaliniame audinyje - trys makroskopiškai aprašyti ir šeši smulkūs limfmazgiai.   1-me/9 limfmazgių - žemiau aprašyto naviko metastazė 2,1 mm.   1-me limfmazgyje izoliuotos naviko ląstelės (0,18 mm dydžio metastazė).    4. Sektorius. Krūties audinyje ir ties metaline viela - du naviko židiniai (I - 12 mm, II - 2,1 mm mikroskopiškai), suformuoti lizdų, trabekulių, tubulių (30%). Naviko ląstelės su negausia, neaiškių ribų eozinofiliška citoplazma, vidutinio kalibro, ovoidiškais ar skeltais, vidutiniškai polimorfiškais branduoliais su pavienėmis smulkiomis nukleolėmis.   Mitozių I navike iki 20/10DPRL, II navike - iki 4/10DPRL. Naviko plitimas endotelizuotuose spindžiuose. Navikas nuo sektoriaus rezekcijos krašto nutolęs 0,9 mm.  Metalinės kabutės projekcijoje ir atokiau krūties audinys su dilatuotais latakais ir židinine apokrinine metaplazija.. Blokas 16:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 5%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių. Karštame taške 20%.  Progesterono re
answer:  0

 96%|█████████▌| 635/661 [09:45<00:24,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 11 mm; II - 10 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6 mm);  (G3; 9 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 85%.. Krūties audinį 2-se bioptatuose infiltruoja iki 6 mm :   - solidiniai kompleksai;  - stambių ląstelių su ryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 20/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  CK5: silpna teigiama (+)  membraninė reakcija 30proc. atipinėse ląstelėse  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose nėra.  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliu
answer:  0

 96%|█████████▌| 636/661 [09:46<00:27,  1.09s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas - be naviko   2(N2b) - kraštas - skubus tyrimas - be naviko  3(N4a) - kraštas - skubus tyrimas - be naviko   4(N4b) - kraštas - skubus tyrimas - be naviko  5(N1) - pašalintas kairės krūties markiruotas plotas - planinis tyrimas  6(N3) - pašalintas dešinės krūties markiruotas plotas - planinis tyrimas. 5. Krūties sektorius 9x5,5x4 cm su odos lopu 8x4 cm, žymėtas viela. Vielos projekcijoje, pjūvyje fibrozės zona 5,5x4x3 cm, siekia artimiausią rezekcijos kraštą, nuo odos – 1,5 cm.  6. Krūties sektorius 9x5x2 cm, žymėtas 2 vielomis. Tarp vielų, pjūvyje fibrozės zona 5,5x4,5x1,7 cm, siekia artimiausią rezekcijos kraštą.. 1(N2a). Krūties lobulinė karcinoma (židinys 1mm). Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.   2(N2b). Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.  3(N4a). Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.  4(N4b). Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.  5(N1). Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) lobulinė karcinoma (multižidininis navikas), pT2(m)(dauginiai naviko židiniai nuo 0,6mm iki 31mm); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  Estrogenų receptoriai: reakcija teigiama (stipri branduolių r-ja, 100% naviko ląstelių).   Progesterono receptoriai: reakcija teigiama (silpna/vidutinė/stipri branduolių r-ja, 85% naviko ląstelių).   HER2: žema imunohistocheminė raiška (1+).  Ki67 proliferacinis aktyvumas ~20%, fokaliai iki 30%.   Lobulinė krūties karcinoma in situ (LCIS). Krūties aukšto laipsnio intraduktalinė karcinoma (DCIS; solidinis ir kribriforminis tipas, -komedo tipo nekrozės). Fibrocistiniai krūties pokyčiai; sklerozuojanti adenozė. LCIS struktūros - rezekcijos krašte.  6(N3). Krūties žemo ir vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis ir kribriforminis tipas; -komedo tipo nekrozės).    IHC reakcijos atliktos VPC:B23-41914 tyrime:  "Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių."  Lobulinė krūties karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai; sklerozuojanti adenozė; intraduktaliniai ir ekstraduktaliniai mikrokalcifikatai. Rezekcijos kraštas be naviko.. 1(N2a). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu; intraduktalinių mikrokalcifikatų židiniai; fibroziniame audinyje ir tarp lipocitų plinta negausios monotoniškos ląstelės (židinys - 1mm).   2(N2b). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu; intraduktalinių mikrokalcifikatų židiniai.  3(N4a). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu; intraduktalinių mikrokalcifikatų židiniai.  4(N4b). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu; intraduktalinių mikrokalcifikatų židiniai.  5(N1). Krūties audinyje - dauginiai naviko židiniai (nuo 0,6mm iki 31mm), formuojami difuziškai, trabekulėmis plintančių vidutinio kalibro ląstelių, eozinofiliška citoplazma, vidutiniškai polimorfiškais branduoliais; navike iki 19 mitozių/10 DPRL. Aplinkiniame krūties audinyje - dilatuoti latakai su solidiniais diskohezyvių atipinių ląstelių proliferatais (LCIS). Dilatuoti latakai su solidiniais ir kribriforminiais atipinių ląstelių (su ryškiu branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS). Krūties audinyje - fibrozės zonos su fokaliai cistiškai dilatuotais latakais, klotais dvisluoksniu epiteliu; smulkių latakėlių, klotų dvisluoksniu epiteliu organoidinės proliferacijos fibrozinėje stromoje zonos, intraduktalinių mikrokalcifiktų židiniai. LCIS struktūros - rezekcijos krašte.  6(N3). Krūties audinyje - dilatuoti latakai su solidiniais ir kribriforminiais atipinių ląstelių (su žemo ir vidutinio laipsnio branduolių polimorfizmu) proliferatais, -komedo tipo nekrozėmis (DCIS); fibrozės zonos su fokaliai cistiškai dilatuotais latakėliais, klotais dvisluoksniu epiteliu; intraduktaliniai ir ekstraduktaliniai mikrokalcifikatai; smulkių latakėlių, klotų dvisluoksniu epitelių organoidinės proliferacijos fibrozuotoje stromoje zonos. Rezekcijos kraštas be naviko.. 5(N1). Blokas 12:  Navikas:  Estrogenų receptoriai: stipri branduolių r-ja, 100% naviko ląstelių.   Progesterono receptoriai: silpna/vidutinė/stipri branduolių r-ja, 85% naviko ląstelių.   HER2: silpna dalies membranos reakcija, 15% naviko ląstelių.  Ki67
answer:  10

 96%|█████████▋| 637/661 [09:47<00:23,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Paimti 4 biopsiniai stulpeliai.. 4 fragmentuoti biopsiniai stulpeliai: I - 14 mm; II - 9 mm; III - 8 mm; IV - 8 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%, vietomis iki 15%.. Krūties audinį infiltruoja netaisyklingi kribroziniai/solidiniai kompleksai ir trabekulės iš neryškiai ar vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis dalies membranos nusidažymas 20% n
answer:  0

 97%|█████████▋| 638/661 [09:48<00:22,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. (N2a) kraštai -  skubus tyrimas - be naviko  2. (N2b) kraštai -  skubus tyrimas - be naviko  3. (N3) kairės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko  4. (N1) pašalintas kairės krūties markiruotas kvadrantas - planinis tyrimas. 4(N1). Krūties sektorius 5x5,5x3 cm, be odos, žymėtas viela. Vielos projekcijoje - pilkšvas, standus, neaiškių ribų I navikas 11x6x5 mm, nuo giliojo rezekcijos krašto nutolęs 1 cm. 0,4 cm atstumu (galimai susiliejantis) nuo I naviko - analogiškas II navikas 10x7x5 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm. Šalia II naviko ribota hemoragija 0,5 cm skersmens. Sektoriaus krašte tamsiai rudas darinys (ankstesnės biopsijos vieta) 1,6x1,2x0,4 cm.. 1(N2a). Krūties fibrocistiniai pokyčiai.  2(N2b). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (3 l/m).  4(N1). Krūties invazyvi duktalinė karcinoma (gerai diferencijuota / G1 / 5 balai pagal Nottingham), TNM (Nr.1-Nr4): pT1c(m) (1,1 cm ir 1,0 cm naviko židiniai) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 1-2%.. 1(N2a). Krūties audinyje - negausūs fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, minimaliai dilatuotais kanaliukais.  2(N2b). Krūties audinyje - negausūs fibrozės židiniai su smulkiais ar kiek stambesnio kalibro, minimaliai dilatuotais kanaliukais.  3(N3). Sinusų histiocitozė trijuose (3) limfmazgiuose.  4(N1). Krūties audinyje - du panašios architektūrinės ir citologinės išvaizdos naviko židiniai (tubulines (80%), negausias smulkias kribrozines naviko struktūras formuoja ląstelės su kiek gausesne švelniai eozinofiline citoplazma, smulkiais ar kiek stambesnio kalibro kiek netaisyklingais, dalis su smulkia nukleole branduoliais; mitozių navikuose: 1-2 / 10 DPRL.. 4(N1). Navikas (20 blokas): HER2 Nusidažiusių naviko ląstelių nėra.
answer:  0

 97%|█████████▋| 639/661 [09:49<00:21,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: N1: pašalintas markiruotas dešinės krūties kvadrantas - planinis tyrimas  2 ėminio aprašas: N2a kraštai - planinis tyrimas  3 ėminio aprašas: N2b kraštai - planinis tyrimas  4 ėminio aprašas: N3: dešinės pažasties sarginis limfmazgis planinis tyrimas. 1. Krūties sektorius 11,5x4,5x3,5 cm su oda 8x2,3 cm, žymėtas viela. Vielos projekcijoje - pilkšvas, standus, aiškių ribų navikas 10x10x6 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 2,3 cm.  2. Riebalinio audinio fragmentas 2,5x1,6x0,4 cm. v/m  3. Riebalinio audinio fragmentas 2x1,5x0,6 cm. v/m  4. Riebalinio audinio fragmentas 4x4x1,5 cm. Rasti 5 limfmazgiai iki 1,7 cm.. Paruošti pjūviai Prosigna.  1. Krūties vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: T1b(9 mm navikas) pN1a(sn)(1/5 l/m MTS 16 mm) LVI-2(limfovaskulinė invazija ).  R0(radikali rezekcija).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 80% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 3%.    2. Krūties audinio fibrozė.  3. Krūties audinio fibrozė.  4. Duktalinės karcinomos metastazė limfmazgyje (1/5 l/m MTS 16 mm).. 1. Krūtyje - navikas (9 mm) infiltratyviu augimo frontu, suformuotas trabekulinėmis struktūromis besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, vidutiniais, vidutiniškai polimorfiškais, ovaliais apvaliais; mitozių 3/10 DPRL.  Aplinkinis krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2. Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3. Riebalinis fibrozinis audinys.  4. 1 iš 5 limfmazgių aprašyto naviko metastazė 16 mm.. nan
answer:  0

 97%|█████████▋| 640/661 [09:50<00:19,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 fragmentuoti biopsiniai stulpeliai: I - 10 mm; II - 10 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.. Krūties audinį infiltruoja negausios duktalinės struktūros ir netaisyklingi kribroziniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 5/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas ir vidutinis visos membranos nusidažymas 15% naviko ląstelių.  K
answer:  0

 97%|█████████▋| 641/661 [09:51<00:21,  1.08s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - deš. užspenelinė zona - extra  2 - deš. pažasties sarginiai l/m - extra  3 - deš. krūties liauka - planinis  4 - k.krūties liauka - planinis. 3. Krūtis 14x13,5x4 cm be odos. Krūties audinyje pilkšvas, aiškių ribų, standus, kiek skiltėtos struktūros navikas 16x13x8 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo poodinio rezekcijos krašto - 1,5 cm. Spenelinė zona dažyta raudonai, jos projekcijoje krūties audinys fibrozuotas 5x3 cm plote su smulkiomis cistinėmis ertmėmis iki 0,3 cm skersmens.  4. Krūtis 14x11,5x3 cm be odos. Spenelinė zona dažyta raudonai, jos projekcijoje krūties audinys fibrozuotas 5x3,5 cm plote su smulkiomis cistinėmis ertmėmis iki 0,3 cm skersmens.. 1(ekstra) Dešinė užspenelinė zona: fibrocistiniai pokyčiai.   2(ekstra) Deš. pažasties sarginiai l/m. Reaktyvi limfadenopatija (2 l/m).   3. Dešinės krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(16 mm navikas) N0(sn)(2 l/m) LVI-0(limfovaskulinė invazija neidentifikuota) R0(radikali rezekcija). Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, DIN3, kribriforminis ir papilinis tipai).  Krūties fibrocistiniai pokyčiai, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).     Naviko imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 70%.  Androgenų receptoriai: reakcijos nėra.       4. Kairės krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, pT1c(11 mm židinys) LVI-0(limfovaskulinė invazija neidentifikuota) R0(radikali rezekcija). Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, DIN3, solidinis, komedo tipai). Krūties fibrocistiniai pokyčiai, ląstelinga (florid) adenozė, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS). Lobulinė karcinoma in situ (LCIS).  Naviko imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 70%.. 1(ekstra) Dešinė užspenelinė zona. Švelniai fibrozuotas krūties audinys su smulkiais ar pavieniais cistiškai dilatuotais latakais, klotais dvisluoksniu epiteliu.  2(ekstra) Deš. pažasties sarginiai l/m. 2 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.     3. Dešinė krūties liauka. Krūties audinyje - navikas, suformuotas desmoplastiškoje stromoje besidėstančių trabekulinių, lizdinių struktūrų ir solidinių plotų. Naviko ląstelės vidutinio gausumo tamsia eozinofiliška citoplazma, vidutinio kalibro, ryškiai polimorfiškais, ovaliais ir nereguliaraus kontūro branduoliais su vesikuolizuotu chromatinu ir smulkiomis nukleolėmis; mitozių iki 58/10 DPRL. Navike yra komedonekrozių. Fokaliai stromoje gausi monomorfonuklearų infiltracija. Navikas nuo rezekcijos krašto nutolęs 3 mm.  Šalia yra stambių latakų su kribriforminiais ir papiliniais proliferatais, suformuotais navikui analogiškų ląstelių.   Aplinkinis krūties audinys su fibrozės apsuptais smulkiais ar pavieniais cistiškai dilatuotais latakais su pavienėmis smulkiomis papilomis, klotais dvisluoksniu epiteliu, fokaliai su apikalinės sekrecijos požymiais ir apokrinine metaplazija. Dalis lobulių apsuptos vidutinio gausumo monomorfonuklearų infiltracija.    4. Kairė krūties liauka. Krūties audinyje - 11 mm (mikroskopiškai) navikas, suformuotas lizdinių, trabekulinių, pavienių tubulinių (<10%) struktūrų. Naviko ląstelės vidutinio gausumo blyškia citoplazma, vidutinio kalibro ar stambiais, ryškiai polimorfiškais, ovaliais ir nereguliaraus kontūro, vesikuolizuotais branduoliais su grūdėtu chromatinu ir smulkiomis nukleolėmis. Mitozių navike iki 16/10DPRL. Šalia yra latakų su solidiniais proliferatais su komedo tipo nekroze, suformuotais navikui analogiškų ląstelių.   Aplinkinis krūties audinys su fibrozės apsuptomis, stambiomis lobulėmis su kompaktiškais smulkiais latakais, dalis užpildytais ryškiai eozinofilišku AB+>PAS+ skysčiu, išklotais epiteliu su vidutinio gausumo šviesia eozinofiliška citoplazma, vidutinio kalibro, apvaliais, monotoniškais branduoliais. Latakų epitelyje yra zonų su apikalinės sekrecijos požymiais. Yra vidutinio kalibro kanaliukų su intraduktaliniais solidiniais proliferatais iš ląstelių monomorfiškais branduoliais.. 3. Blokas 14 (dešinės krūties navikas):  Androgenų receptoriai: vidutinė (++) branduolinė reakcija 5% naviko ląstelių.  CK5: vidutinė /stipri (++/+++) membraninė reakcija 80% naviko ląstelių.  Estrogenų receptoriai: reakcijos naviko ląstelių branduoliuose
answer:  0

 97%|█████████▋| 642/661 [09:52<00:18,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 stulpeliai. 2 biopsiniai stulpeliai: I - 11 mm; II - 15 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%.. Krūties audinį infiltruoja pavienės smulkios duktalinės struktūros, smulkūs solidiniai kompleksai, juostos iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 5%.
answer:  0

 97%|█████████▋| 643/661 [09:53<00:18,  1.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1.(2a)Kraštas - extra - be naviko  2.(2b)Kraštas - extra - be naviko  3.(3)Sarginis l/m - extra - be naviko  4(N1)- pašalintas sektorius -planinis patologinis tyrimas - skubus rentgeninis tyrimas - navikas pašalintas. 4(1). Krūties sektorius 3,5x3,5x2 cm, be odos, žymėtas viela. Vielos projekcijoje pilkšvas, standus navikas 11x10x6 cm, nuo artimiausio rezekcijos krašto nutolęs 0,2 cm.. 1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė).   2(2b, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(1). Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 11 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).   Naviko nekrozė iki 15%.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atlikta šio tyrimo metu:   HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija ir sklerozuojanti adenozė).   Nuo sektoriaus rezekcijos krašto naviko struktūros nutolusios 0,6 mm.. 1(2a, ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu; fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu; degeneruojančių skaidulų židinys.   2(2b, ekstra). "Kraštai": fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu.   3(ekstra). "Sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.     4(1). NAVIKAS: krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios trabekulinės, lizdinės, solidinės naviko struktūros, suformuotos ryškiai polimorfiškų ląstelių, vidutinio gausumo eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais ryškiais polimorfiškais branduoliais su ryškiomis nukleolėmis; mitozių iki 18/10 DPRL. Centrinės nekrozės zonos iki 15%; fokalinė fibrozė su fibroblastų proliferacija. Fokaliai kiek gausesnė perinavikinė limfocitinė infiltracija.   APLINKA: šalia naviko - solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis.   Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, fokaliai smulkūs suspausti, kloti dvisluoksniu epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: naviko struktūros nutolusios 0,6 mm.. 4(1). Navikas (9 blokas): EMA(+) citoplazminė r-ja; E-Cadherin(+++)(membr.r-ja)100%.  HER2: silpna (+) necirkuliari reakcija, 15% naviko ląstelių membranoje.
answer:  0

 97%|█████████▋| 644/661 [09:54<00:17,  1.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a). kraštas  - skubus tyrimas - be naviko  2(N2b). kraštas  - skubus tyrimas - be naviko  3(N3). kairės pažasties sarginis limfmazgis - skubus tyrimas - 3l/m be naviko  4(N1). pašalintas kairės krūties kvadrantas planinis tyrimas. 4. Krūties sektorius 13,5x4x5,5 cm su odos lopu 9,5x3 cm, žymėtas viela. Pjūvyje, vielos projekcijoje - rusvas, elastingas, mucininis navikas 20x16x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,3 cm, nuo odos - 4 cm. Naviko projekcijoje fibrozė 3,5x1,5 cm plote susiūta chirurginiais siūlais.. 1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) mucininė karcinoma, TNM: pT1c(navikas 20 mm), pN0(sn)(0/3 l/n), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Ki67: proliferacinis indeksas 5%. Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  Krūties hamartoma (1,5 cm). Fibrocistiniai krūties pokyčiai: intraduktalinė krūties papiloma. Atipinė duktalinė hiperplazija (ADH).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).. Papildytas atsakymas (žr. molekuliniai tyrimai):    1(2a). Krūties audinyje minimali fibrozė ir smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  2(2b). Krūties audinyje minimali fibrozė ir smulkūs kanaliukai, kloti dvisluoksniu epiteliu.  3. Trys limfmazgiai su sinusų histiocitoze (3 l/m).  4. Krūties audinyje navikas (20 mm mikroskopiškai), suformuotas gausiuose ekstraląsteliniuose mucinuose besidėstančių smulkių lizdinių, pavienių tubulinių ir negausių mikropapilinių struktūrų. Naviko ląstelės vidutinio gausumo eozinofiline citoplazma, vidutinio kalibro, vidutiniškai polimorfiškais branduoliais su smulkiomis nukleolėmis. Limfovaskulinis plitimas neidentifikuotas (LVI0). Mitozių navike iki 2/10 DPRL.   Krūties audinyje darinys, suformuotas mažos ląstelingos stromos su dilatuotais latakais, lobulėmis, pavieniais lipocitais. Krūties audinyje - dilatuotas latakas su fibrovaskulinėmis struktūromis, klotomis dvisluoksniu epiteliu monomorfiškais branduoliais. Keli dilatuoti kanaliukai su solidine proliferacija su kiek hiperchromiškais branduoliais su išlikusiu mioepiteliniu sluoksniu.. Blokas 21:  HER2: vidutinė (++) necirkuliari reakcija, 15%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 5% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių branduoliuose.
answer:  0

 98%|█████████▊| 645/661 [09:55<00:15,  1.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  Deš. krūtis su deš. pažasties l/m, planinis. Krūtis 1510 g svorio, 24x22x8,5 cm, su pažasties narveliena 13x8,5x3 cm.   Apatiniame lateraliniame kvadrante pilkšvas, standus, aiškių ribų navikas 30x22x20 mm (plintantis link spenelio, didžiausias naviko matmuo galimai 5,5 cm), esantis 2,6 cm nuo giliojo rezekcijos pjūvio, siekia odą.   Nuo naviko 1,8 cm atstumu pilkšvas, standus darinys 5x4x3 mm, giliojo rezekcijos krašto nutolęs 1,8 cm.   Spenelio projekcijoje krūties audinys balkšvas, standus, fibrozuotas 4,5x3 cm.   Pažasties narvelienoje rasta 11 limfmazgių, didžiausias 3,6 cm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma;  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: silpna (+) reakcija, 3% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    Vidutinio laipsnio intraduktalinė karcinoma (DCIS/DIN2 su plitimu operaciniame krašte).    pT2(30 mm ir 5 mm), pLVI-2, pN1a, pR0.. Krūties audinyje solidines, trabekulines, pavienes kribrozines naviko židinių struktūras formuoja ląstelės su negausia citoplazma, vidutinio dydžio vidutiniškai polimorfiškais branduoliais; mitozių navike iki 4 / 10 DPRL. Stebimas intrakapiliarinis plitimas.  Navike ir gretimai stebimos gausūs intraduktaliniai analogiškų ląstelių solidiniai ir tinkliniai proliferatai; židiniškai stebimi giliajame operaciniame pjūvyje.   Aprašyto naviko plitimas (iki 10 mm) 3-se iš 11 limfmazgių; stebimas ekstranodulinis plitimas.. Blokas 9:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 10%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 10% naviko ląstelių.  Progesterono receptoriai: silpna (+
answer:  3

 98%|█████████▊| 646/661 [09:56<00:16,  1.10s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(N2a) - kraštas - skubus tyrimas  2(N2b) - kraštas - skubus tyrimas  3(N3) - kairės pažasties sarginis limfmazgis - skubus tyrimas  4(N1) - pašalintas kairės krūties kvadrantas - planinis tyrimas  5(N4) - papildomi kraštai - planinis tyrimas. 4(1). Krūties sektorius 13,5x9,5x5 cm su oda 12x4 cm, žymėtas 2 vielomis. Vielų projekcijoje, pilkšvas, neaiškių ribų elastingas židinys 16x14x8 mm, pereinantis į netolygiai fibrozuotą krūties audinį, 5,5x2,5 cm plote. Pakitimai nuo giliojo rezekcijos krašto nutolę 0,1 cm, nuo odos -  2,5 cm.  5(4). Riebalinio audinio fragmentas 2x2x0,6 cm. Sudėta visa medžiaga.. 1(2a, ekstra). "Kraštai": krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai; ~15 mm skersmens židinys).  2(2b, ekstra). "Kraštai": krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai; ~12 mm skersmens židinys).  3(ekstra). "Kairės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(1). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b(m) (naviko židiniai: I - 5,2 mm; II - 0,4 mm; III - 0,35 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.     Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai; ~50 mm zona su išskiriančiu ~16 mm židiniu aplink didžiausiąjį I naviką).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   Incidentinė krūties fibroadenoma (4,35 mm).   DCIS komponentas sektoriaus rezekcijos krašte.    5(4). "Papildomi kraštai": fibrozuotas riebalinis audinys.. 1(2a, ekstra). "Kraštai": solidiniai, kribriforminiai intraduktaliniai žemiau, punkte Nr.3, aprašyto naviko ląstelių proliferatai su centrinėmis nekrozės zonomis (15 mm skersmens židinys).   2(2b, ekstra). "Kraštai": solidiniai, kribriforminiai intraduktaliniai žemiau, punkte Nr.3, aprašyto naviko ląstelių proliferatai su centrinėmis nekrozės zonomis (12 mm skersmens židinys).   3(ekstra). "Kairės pažasties sarginiai limfmazgiai": du (2) limfmazgiai su sinusų histiocitoze, parakortekso hiperplazija, I/II folikulais, brandžiais lipocitų intarpais, fibrozės židiniais.     4(1). NAVIKAS (daugybiniai, dalis nedideli mikroinvazyvūs naviko židiniai: I - 5,2 mm; II - 0,4 mm; III - 0,35 mm): krūties audinyje, fibrozuotoje, desmoplastiškoje stromoje, infiltratyviai plinta fokaliai besiliejančios lizdinės, solidinės naviko struktūros, suformuotos vidutiniškai ar ryškiai polimorfiškų ląstelių, vidutinio gausumo ar gausia šviesia eozinofiline citoplazma, vidutinio dydžio ir kiek stambesniais nelygaus kontūro ovaliais/apvaliais branduoliais su ryškiomis nukleolėmis; mitozių iki 10/10 DPRL. Pavieniai spindžiai dalyje naviko struktūrų. Aplinkinė stroma fibrozuota su saikinga limfocitine infiltracija.   APLINKA: šalia naviko - gausūs dominuojantys solidiniai, kribriforminiai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis ir kalcifikatais. Gausi limfocitinė infiltracija su tretinių limfoidinių struktūrų formacija aplink in situ komponentą. Aplinkiniame fibrozuotame krūties audinyje - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, apokrinės metaplazijos zonomis. Incidentinis ribotas skiltėtas navikas (4,35 mm), suformuotas edemiškos stromos su suspaustais ar minimaliai dilatuotais šakotais ir negausiais smulkiais latakais, klotais dvisluoksniu, kiek hiperplastišku epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: fokalinis in situ komponento plitimas rezekcijos krašte.   5(4). "Papildomi kraštai": fokaliai fibrozuotas brandžių lipocitų suformuotas audinys.. 1(2a, ekstra). "Kraštai"(1 blokas):  CK14/CK5(+) mioepitelinis sl. DCIS komponente.   2(2b, ekstra). "Kraštai"(4 blokas):   CK14/CK5(+) mioepitelinis sl. DCIS komponente.   4(1). "Židinys-fibrozė" (4,22-24,28-29 blokai):   CK14(+) mioepitelinis sl. DCIS k
answer:  0

 98%|█████████▊| 647/661 [09:57<00:14,  1.06s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 - pjūvio kraštai - extra  2 - pjūvio kraštai - extra  3 - sarginis l/m - extra  4. sektorius, planinis.. 4. Krūties sektorius 6x5,3x5 cm su oda 5,5x3,5x cm. Krūties audinyje, pilkšvas, standus, aiškių ribų navikas 16x15x13 mm, nuo giliojo rezekcijos krašto nutolęs 0,7 cm, nuo odos - 1 cm.. 1. Pjūvio kraštai. Krūties audinys su židinine lėtine uždegimine infiltracija. Naviko plitimo nėra.     2. Pjūvio kraštai. Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.      3. Sarginis l/m. Reaktyvi limfadenopatija (3 l/m).     4. Sektorius. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma,    suminis TNM: pT1c (16 mm navikas)   pN0(sn)(3 l/m)    pLVI-0(limfovaskulinė invazija neidentifikuota).   pR0(radikalus pašalinimas).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 85% naviko ląstelių.  HER2: reakcija neigiama (0/1+).  Ki67: proliferacinis indeksas 30%.. 1(ekstra). Pjūvio kraštai. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Stromoje židininė gausoka periduktalinė limfocitinė infiltracija. Naviko plitimo nėra.   2(ekstra). Pjūvio kraštai. Krūties audinys su fibrozės zonomis ir smulkiais, dalis dilatuotais kanaliukais, klotais dvisluoksniu epiteliu. Naviko plitimo nėra.   3(ekstra). Sarginis l/m. 3 limfmazgiai su I/II folikulais, sinusų histiocitoze, lipomatoze.    4. Sektorius. Krūties audinyje - navikas, suformuotas lizdų, trabekulių ir grandinėlių. Naviko ląstelės su vidutinio gausumo, šviesiai amfofiliška citoplazma, vidutinio kalibro ar stambiais, apvaliais ar ovoidiškais, vesikuolizuotais, ryškiai polimorfiškais branduoliais su ryškiomis nukleolėmis. Mitozių navike iki 21/10DPRL.. Blokas 19:  CD31: + endotelis (limfovaskulinė invazija neideintifikuota).   E-Cadherin: stipri (+++) reakcija, 100% naviko membranose.   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakc
answer:  20

 98%|█████████▊| 648/661 [09:58<00:12,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 9 mm; II - 7 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 12% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.. Krūties audinį infiltruoja negausios duktalinės struktūros, smulkūs kribroziniai ir solidiniai kompleksai iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 12% naviko ląstelių.  Her2 imuninė reakcija: membranos nusidažymo nėra, 0% naviko ląstelių.  Ki67+ 15%.
answer:  0

 98%|█████████▊| 649/661 [09:59<00:11,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 stulpelis. Biopsinis stulpelis 15 mm.. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G2; 7 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (galutinai interpretuota įvertinus HER2 IHC rezultatą; žr. molekulinio tyrimo aprašymą ir pastabą).  Ki67: proliferacinis indeksas 40%.. Krūties audinį 1-me bioptate infiltruoja iki 9 mm :   - trabekulės;  - epitelinių stambių ląstelių su ryškiai polimorfiškais branduoliais  negausioje eozinofilinėje citoplazmoje;   - su mitozėmis iki 3/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: vidutinė (++) necirkuliari reakcija, 50%  naviko ląstelių membranoje.  Ki67: reakcija branduoliuose, 40% naviko ląstelių.  Progesterono receptoriai: stipri
answer:  1

 98%|█████████▊| 650/661 [10:00<00:09,  1.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: PREPARATAI   -   UAB PATOLOGIJOS DIAGNOSTIKA. Konsultacijai gauta:  - 4 parafino blokai (žymėti "B22-1-28082");  - 8 histologiniai preparatai (žymėti ""B22-1-28082"", dažyti HE, CK5, ER, PR, HER2 metodais).. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se stulpeliuose.  Ki67: proliferacinis indeksas 55%.  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Išoriniai IHC:  Estrogenų receptorių raišką teigiama (stipri raiška 100 proc. naviko ląstelių branduoliuose).  Progesteronų receptorių raišką teigiama (vidutinė raiška 50 proc. naviko ląstelių branduoliuose).  HER2 raiška paribinė (2+: silpna cirkuliari raiška 30 proc. naviko ląstelių membranoje).  CK5: raiškos nestebima.. Fibrozinį audinį 3-se/4 bioptatuose infiltruoja iki 9 mm :   - solidiniai kompleksai ir trabekulės;  - epitelinių vidutinio dydžio ląstelių su vidutiniškai polimorfiškais branduoliais  negausioje eozinofilinėje kiek vakuolizuotoje citoplazmoje;   - su mitozėmis iki 1/10 DPRL.   Mikrokalcifikatai nestebimi. Intravaskulinės invazijos nėra.. Blokas 1:  E-Cadherin: stipri teigiama (+++)  cirkuliari membraninė reakcija 100 proc. atipinėse ląstelėse  Ki67: reakcija branduoliuose, 55% naviko ląstelių.
answer:  0

 98%|█████████▊| 651/661 [10:01<00:09,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. Pjūvio kraštai - extra;  2. Pjūvio kraštai - extra;   3. Sarginiai l/m - extra.   4. sektorius, planinis.. 4. Krūties sektorius 8,5x4,5x6 cm su oda 7,5x3 cm, žymėtas viela. Vielos projekcijoje, kvadrante - pilkšvas, standus neaiškių ribų navikas 10x10x8 mm (sudėtas visas), pereinantis į fibrozę, nuo giliojo rezekcijos krašto nutolęs 0,4 cm, nuo odos - 2,7 cm. Paruošti pjūviai Prosigna.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (1 l/m).    4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(10,5 mm navikas) pN0(sn)(0/1 l/m) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir solidinis tipai). Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija.    Imunofenotipas:(biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. 1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  2(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu.  3(ekstra). 1 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  4. Krūtyje - navikas (10,5 mm) infiltratyviu augimo frontu, trabekulinėmis struktūromis, lizdais ir grandinėlėmis ir pabirai besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, vidutiniais polimorfiškais, nereguliaraus kontūro, branduoliais ryškiomis nukleolėmis; mitozių 10/10 DPRL. Limfovaskulinė invazija.  Greta dilatuoti kanaliukai su intraduktaliniais kribriforminiais ir solidiniais proliferatais iš analogiškų navikui ląstelių.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu Fokaliai smulkių suspaustų kanaliukų zonos.. Navikas(13 blokas):  HER2: nusidažiusių naviko ląstelių nėra.  E-cadherin membr. trūkinėjanti r-ja 90%.
answer:  0

 99%|█████████▊| 652/661 [10:01<00:08,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 1 biopsinis stulpelis. Biopsinis stulpelis 12 mm ilgio.. Gerai diferencijuota (G, balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.. Krūties audinį infiltruoja duktalinės struktūros ir nedideli kribroziniai kompleksai iš neryškiai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas 20% naviko ląstelių.  Ki67+ 6
answer:  0

 99%|█████████▉| 653/661 [10:02<00:07,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1(2a). Kraštai - extra;  2(2b). Kraštai - extra;  3. Sarginiai l/m - extra;  4(1). N41 - sektorius - planinis patologinis tyrimas.. 4. Krūties sektorius 8x5x2,5 cm, žymėtas dažais. Krūties audinyje, kvadrante - pilkšvas, standus navikas 22x16x16 mm, nuo giliojo rezekcijos krašto nutolęs 0,2 cm.. 1(2a) Kraštai. Krūties audinys, naviko plitimo nėra.    2(2b) Kraštai. Krūties audinys, naviko plitimo nėra.     3 Sarginiai l/m. Reaktyvi limfadenopatija (2 l/m).     4(1) Sektorius.   Krūties invazyvi vidutiniškai diferencijuota (G2, 7 b. pgl Nottingham) duktalinė karcinoma,   pT2(22 mm)   pN(sn)0(0/2 l/m)   pLVI-0 (limfovaskulinės invazijos nestebima)  Naviko imunotipas nustatytas biopsijoje (žr.pastabą).  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 kribriforminis tipas).. 1(2a) Kraštai. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.    2(2b) Kraštai. Krūties audinys su fibrozės zonomis ir smulkiais kanaliukais, klotais dvisluoksniu epiteliu.    3 Sarginiai l/m. Limfmazgiai su sinusų histiocitoze, lipomatoze.      4(1) sektorius. Krūties audinyje infiltratyviai plintantis navikas, suformuotas trabekulinių, netaisyklingų kribriforminių bei solidinių struktūrų. Naviko ląstelės su vidutinio gausumo, eozinofiliška citoplazma, netaisyklingais, ryškiai polimorfiškais branduoliais. Mirozių navike iki 7/10 DPRL. Nekrozės zonos navike iki 5%. Naviko plitimo kraujagyslėse nestebima. Šalia naviko kanaliukai su intraduktaliniais kribriforminiais proliferatais iš analogiškų navikui ląstelių. Fokaliai naviko struktūros plinta žymėtame rezekcijos krašte.. nan
answer:  0

 99%|█████████▉| 654/661 [10:03<00:06,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 3 biopsiniai stulpeliai. 3 fragmentuoti biopsiniai stulpeliai: I - 8 mm; II - 3 mm; III - 6 mm.. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.. Krūties audinį infiltruoja duktalinės struktūros, smulkūs solidiniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  Ki67+
answer:  8

 99%|█████████▉| 655/661 [10:04<00:05,  1.05it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1. N2 - retroareoliarinė sritis - DCIS    2. N3 - viena makromts iš 2 pašalintų sarginių l/m    3. N4 papildomai keliuose kanaliukuose -DCIS  4.  N5- papildomai - dalis areolės su oda ir poodžiu - be naviko   5.  N1 - pašalinta krūtis - planinis patologinis tyrimas. 5. Krūtis 13,5x11,5x3 cm, su odos lopu 7,5x2,5 cm.   Krūties audinyje, pjūvyje pilkšvas, ribotas 15x12x10 mm navikas, nuo giliojo rezekcijos krašto nutolęs 1,2 cm, nuo poodinio rezekcijos krašto - 0,1 cm. Krūties audinys fibrozuotas 8,5x4,5 cm plote.. 1. N2 - retroareoliarinė sritis: Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, tinklinis tipas) / (DIN3).    2. N3 -  sarginiai limfmazgiai: viename iš 3 limfmazgių karcinomos plitimo daugybiniai židiniai iki 3 mm; pN(sn)1a.      3. N4 papildomai keliuose kanaliukuose: Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, tinklinis tipas) / (DIN3).    4. N5- papildomai - dalis areolės su oda ir poodžiu: be patologinių pokyčių.     5. N1 - pašalinta dešinė krūtis.  Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mikropapilinė karcinoma;  pT(m)1c(15 mm, 8 mm) pR0.   Imunofenotipas (nustatytas priešoperaciniame naviko biopsijos tyrime):   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: teigiama (3+).  Ki67 proliferacinis aktyvumas 10%.    Krūties daugybiniai aukšto laipsnio duktalinės karcinomos in situ (DCIS, tinklinis tipas) / (DIN3) židiniai.  Krūties fibrocistiniai pokyčiai:  sklerozuojanti adenozė.. 1. N2 - retroareoliarinė sritis: Krūties audinyje 3 mm židinyje - vidutinio kalibro kanaliukai su tinkliniais intraduktaliniais ląstelių su eozinofiliška citoplazma, vidutinio kalibro ir stambiais, polimorfiškais branduoliais proliferatais kanaliukų spindžiuose.    2. N3 - sarginiai limfmazgiai: viename iš 3 limfmazgių karcinomos plitimo daugybiniai židiniai iki 3 mm.   3. N4 papildomai keliuose kanaliukuose: Krūties audinyje 2 mm židinyje - vidutinio kalibro kanaliukai su tinkliniais intraduktaliniais ląstelių su eozinofiliška citoplazma, vidutinio kalibro ir stambiais, polimorfiškais branduoliais proliferatais kanaliukų spindžiuose.  4. N5- papildomai - dalis areolės su oda ir poodžiu: be patologinių pokyčių.   5. N1 - pašalinta dešinė krūtis. Naviko fibrozinėje stromoje infiltratyvios naviko struktūros, suformuotos mikropapilomis ir lizdais besidėstančių ląstelių gausia ryškia eozinofiliška citoplazma, polimorfiškais, vidutinio-stambaus kalibro, nereguliaraus kontūro branduoliais; mitozių 8/10 DPRL.  Fibrozuotame krūties audinyje:  vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, smulkių kanaliukų proliferacijos zonos, apokrininė metaplazija; stebimi vidutinio kalibro kanaliukai su tinkliniais intraduktaliniais ląstelių su eozinofiliška citoplazma, vidutinio kalibro ir stambiais, polimorfiškais branduoliais proliferatais kanaliukų spindžiuose ir 8 mm invazinio aukščiau aprašyto naviko židinys.. nan
answer:  1

 99%|█████████▉| 656/661 [10:05<00:05,  1.00s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: Kairės pažasties sarginiai limfmazgiai, skubu  2 ėminio aprašas: Kairė krūtis, planinis. 2. Krūtis 352 gramų svorio, 15x13,5x4,2 cm. Krūties audinyje, viršutinių kvadrantų riboje - pilkšvas, standus, neaiškių ribų I navikas 11x6x6 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,1 cm, nuo odos - 2,3 cm. Apatinių kvadrantų riboje - pilkšvas, elastingas I darinys 7x6x6 cm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 1,5 cm, nuo odos - 1 cm. Viršutiniame medialiniame kvadrante pilkšvas elastingas aiškių ribų II darinys 6x5x5 cm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,5 cm, nuo odos - 1 cm. 1 cm atstumu nuo II darinio, link šoninio giliojo rezekcijos krašto - pilkšvas, standus II navikas 10x6x5 mm (sudėtas visas), nuo giliojo rezekcijos krašto nutolęs 0,2 cm, nuo odos - 1,4 cm. Spenelio projekcijoje krūties audinys fibrozuotas 7x3,5 cm plote.. 1(ekstra). Reaktyvi limfadenopatija (2 l/m).  2. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(m)(11 mm ir 9 mm navikai) pN0(sn)(0/2 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).   Žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1, kribriforminis ir papilinis tipai). Lobulinė karcinoma in situ (LCIS). Fibroadenoma (6 mm).  Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 10% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 3%.. 1(ekstra). 2 limfmazgiai su sinusų histiocitoze ir pirminiais bei antriniais folikulais.  2. Spenelis: normali histologinė struktūra.  Krūtyje - navikas (11 mm ir 9 mm) infiltratyviu augimo frontu, suformuotas nereguliariomis, susiliejančiomis tubulinėmis, trabekulinėmis struktūromis, lizdais ir pabirai besidėstančių ląstelių negausia - vidutinio gausumo eozinofiliška citoplazma, smulkiais - vidutiniais, vidutiniškai polimorfiškais,  ovaliais apvaliais, vezikulizuotais branduoliais ryškiomis nukleolėmis; mitozių 2/10 DPRL.  Navikas (9 mm židinys) nuo rezekcijos krašto nutolęs 1,5 mm.  Greta dilatuoti kanaliukai su intraduktaliniais papiliniais, kribriforminiais proliferatais iš analogiškų navikui ląstelių. Latakai ir lobulės su monomorfiškų ląstelių proliferacija. Mazgas suformuotas proliferuojančių fibroblastų stromos ir suspaustų latakų, klotų dvisluoksniu epiteliu.   Aplinkiniame krūties audinyje kanaliukais su intraduktaliniais papiliniais ir kribriforminiais proliferatais, klotais dvisluoksniu ar hiperplastišku epiteliu, dalyje kanaliukų stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS). Fokaliai smulkių suspaus kanaliukų zonos.. nan
answer:  0

 99%|█████████▉| 657/661 [10:07<00:04,  1.07s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 pjūvio kraštai, ekstra.   2. pjūvio kraštai, ekstra.   3. sarginiai l/m, ekstra.  4. papildomas kraštas. ekstra.  5. sektorius, planinis.. Krūties sektorius 10x6x4,5 cm, su odos lopu 7x2,5 cm. Pjūvyje balkšvas, standus, neaiškių ribų navikas 31x22x11 mm, nuo artimiausio rezekcijos krašto nutolęs 0,7 cm, nuo odos 1,3 cm. Šalia naviko fibrozės zona 4x3x2 cm.. 1(intraoperative margin). Invasive lobular carcinoma.  2.(intraoperative margin). Invasive lobular carcinoma (1.3 mm focus).  3.(intraoperative) lymph node. Breast lobular carcinoma metastasis in a lymph node (1/4 l/n, MTS 3.2 mm).  4.(intraoperative margin). Invasive lobular carcinoma (2 mm focus in marked margin).    5. Breast invasive moderately differentiated (G2, 7b. Nottingham syst.) lobular carcinoma. TNM: pT2(m)(31 mm, 1.3 mm tumors) pN1a(sn)(1/4 l/n, MTs 3.2 mm) LVI-2 (lymphovascular invasion). R1 (carcinoma reaches the edge of the sector, spreads in additional edges No. 1, 2, 4). Lobular carcinoma in situ (LCIS).    Immunophenotype:  Estrogen receptors: strong reaction in 95% of tumor cells.  Progesterone receptors: strong reaction in 100% of tumor cells.  Her2 immunoreaction: negative (0).  Ki67 proliferative activity 5%.        LT  1(ekstra). Invazyvi lobulinė karcinoma.  2(ekstra). Invazyvi lobulinė karcinoma (1,3 mm židinys).  3(ekstra). Krūties lobulinės karcinomos metastazė limfmazgyje (1/4 l/m, MTS 3,2 mm).  4. Papildomas kraštas. Invazyvi lobulinė karcinoma (2 mm židinys žymėtame krašte).    5. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(m)(31 mm, 1,3 mm navikai) pN1a(sn)(1/4 l/m, MTs 3,2 mm) LVI-2(limfovaskulinė invazija). R1(karcinoma siekia sektoriaus kraštą, plinta papildomuose Nr.1,2,4 kraštuose). Lobulinė karcinoma in situ (LCIS).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 95% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.. 1(intraoperative margin). Breast tissue with areas of fibrosis and sparse ducts lined with double-layered epithelium; invasive tumor cells around ducts.  2 (intraoperative margin). Breast tissue with single tubules lined by double-layered epithelium; the focus of the described tumor is 1.3 mm.  3 (intraoperative l/n). Metastasis of the described tumor in 1 of 4 lymph nodes 3.2 mm.  4(intraoperative margin). The focus of the invasive tumor up to 1.3 mm; dilated ducts and lobules with intraductal solid proliferates of cells analogous to the tumor.  5. In the breast - a tumor (32, 1.3 mm foci) with an infiltrative growth front with trabecular structures, chains and discohesive cells with moderately abundant eosinophilic cytoplasm, large, polymorphous, irregularly contoured nuclei with bright nucleoli; mitoses 7/10 HPF. Tumor in coagulated edge.  Adjacent dilated tubules with intraductal solid proliferates from tumor-analogous cells (LCIS).      LT    1(ekstra). Krūties audinys su fibrozės zonomis ir negausiais kanaliukais, klotais dvisluoksniu epiteliu; aplink latakus pabirai besidėstančio aprašyto Nr. 5 naviko ląstelės.  2(ekstra). Krūties audinys su pavieniais kanaliukais, klotais dvisluoksniu epiteliu; aprašyto naviko židinys 1,3 mm.  3(ekstra). 1 iš 4 limfmazgių aprašyto naviko metastazė 3,2 mm.  4(extra). Papildomas kraštas. Krūties audinyje aprašyto naviko židinys 1,3 mm, dilatuoti latakai ir lobulės su intraduktaliniais solidiniais proliferatais iš analogiškų navikui ląstelių.  5. Krūtyje - navikas (32, 1,3 mm židiniai) infiltratyviu augimo frontu trabekulinėmis struktūromis, grandinėlėmis ir pabirai besidėstančių ląstelių vidutinio gausumo eozinofiliška citoplazma, stambiais, ryškiai polimorfiškais, nereguliaraus kontūro branduoliais ryškiomis nukleolėmis; mitozių 7/10 DPRL. Navikas koaguliuotame krašte.  Greta dilatuoti kanaliukai su intraduktaliniais solidiniais proliferatais iš analogiškų navikui ląstelių.. Tumor:  Estrogen receptors: (+++)(nuclear reaction) 95%.  Progesterone receptors: (+++)(nuclear reaction) 100%.  HER2: weak staining of single cell membranes.  Ki67 proliferative activity 5%.  E-cadherin single cell with fint staining in the membrane ; p1
answer:  0

100%|█████████▉| 658/661 [10:07<00:02,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 12 mm.. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma su mucininės diferenciacijos požymiais   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.  Progesterono receptoriai: stipri (+++) reakcija, 1% naviko ląstelių.. Krūties audinyje (2/2 biopsiniuose stulpeliuose) - fibrozinės stromos su gausiais AB+ mucinų židiniais apsuptos kribriforminės struktūros ir solidiniai kompleksai, suformuoti ląstelių vidutinio gausumo, tamsia eozinofiliška citoplazma, vidutinio kalibro, apvaliais ar ovoidiškais, hiperchromiškais, vidutiniškai polimorfiškais branduoliais su pavienėmis smulkiomis nukleolėmis. Mitozių navike iki 6/10DPRL.. Blokas 1:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 15% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 1% naviko
answer:  0

100%|█████████▉| 659/661 [10:08<00:01,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  2 biopsiniai stulpeliai. 2 biopsiniai stulpeliai: I - 14 mm; II - 7 mm.. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+, HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.. Krūties audinį infiltruoja netaisyklingi šakoti kribroziniai kompleksai, juostos ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių iki 2/10 DPRL.. Navikas  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: vidutinis visos membranos nusidažymas 12% naviko ląstelių.  Ki67+ 12
answer:  0

100%|█████████▉| 660/661 [10:09<00:00,  1.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

input:  1 ėminio aprašas: 18 G automatine biopsine adata punktuotas hipoechogeninis, neaiškiomis ribomis, nelygiais kontūrais, su UG fiksuojama kraujotaka, ~42x39 mm dydžio navikas dešiniojoje krūtyje ties 10-11 val.  vidurinėje-periferinėje dalyse, paimti trys biopsiniai stulpeliai histologijai.. 3 biopsiniai stulpeliai: I - 12 mm; II - 13 mm; III - 8 mm.. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: teigiama (3+).  Ki67 proliferacinis aktyvumas 60%.. Bioptatuose (3/3) - krūties audinyje, desmoplastiškoje stromoje, infiltratyvios naviko struktūros, suformuotos trabekulėmis ir lizdais bei solidiniais plotais besidėstančių ląstelių vidutinio gausmo ryškai eozinofiliška citoplazma, polimorfiškais, stambaus kalibro, nereguliaraus kontūro branduoliais eozinofiliškomis nukleolėmis; mitozių 9/10 DPRL.. Navikas:  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.  Progesterono receptoriai: (+++)(brand. r-ja) 950%.  HER2: stiprus visos membranos nusidažymas 100% naviko ląstelių.  Ki67 proliferacinis aktyvumas 60%.
answer:  1

100%|██████████| 661/661 [10:10<00:00,  1.08it/s]

input:  1 ėminio aprašas: 1 but. 1 biopsinis stulpelis i š dešinės pažasties l lygio l/m.   2 but. 1 biopsinis stulpelis iš dešinės krūties BI-RADS 5  darinio. 1. Biopsinis stulpelis 7 mm ilgio.  2. Biopsinis stulpelis 14 mm ilgio.. 1. Duktalinės karcinomos metastazė limfmazgyje.   2. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67+ 10%.. 1. Limfmazgio bioptate plinta žemiau aprašyto naviko struktūros.  2. Krūties audinį infiltruoja duktalinės struktūros (20%), netaisyklingi kribroziniai kompleksai ir trabekulės iš vidutiniškai polimorfiškų ląstelių, mitozių mažiau 1/10 DPRL.. Blokas 2:  Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių branduoliuose.  Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių branduoliuose.  HER2: silpna (+) necirkuliari reakcija, 3%  naviko ląstelių membranoje.  Ki
answer:  10

In [ ]:
m_pred = [int(x) for x in m_pred]

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def evaluateBinary(y_true, y_pred):
    mask = [y != -1 for y in y_pred]
    filtered_y_true = [y_true[i] for i in range(len(y_true)) if mask[i]]
    filtered_y_pred = [y_pred[i] for i in range(len(y_pred)) if mask[i]]

    accuracy = accuracy_score(filtered_y_true, filtered_y_pred)
    precision = precision_score(filtered_y_true, filtered_y_pred)
    recall = recall_score(filtered_y_true, filtered_y_pred)
    f1 = f1_score(filtered_y_true, filtered_y_pred)

    print(f"Accuracy: {accuracy}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print(len(m_pred) - len(filtered_y_pred)) #filtered out count

evaluateBinary(m_labels, m_pred)

Accuracy: 0.7543554006968641
Precision: 0.007142857142857143
Recall: 0.3333333333333333
F1 Score: 0.013986013986013986
87

In [ ]:
question = "Kas yra tolimoji metastazė?"

# Tokenize the question
inputs = tokenizer(question, return_tensors="pt").to("cuda")
# Generate a response
output_tokens = model.generate(inputs["input_ids"], max_length=200, do_sample=True, top_p=0.95, temperature=0.7)

# Decode the response
tokenizer.decode(output_tokens[0], skip_special_tokens=True) # nežino, kas yra tolimoji metastazė

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

'Kas yra tolimoji metastazė? (1)\nA. Metastazė nuo paprastos rūšies kancero\nB. Metastazė nuo ligos, kurioje yra paprastos rūšies kancero\nC. Metastazė nuo kancero rūšies, kuri nėra paprastos\nD. Metastazė nuo ligos, kurioje yra kancero rūšis, kuri nėra paprastos\nE. Metastazė nuo paprastos rūšies kancero, kurioje yra kancero rūšis, kuri nėra paprastos\nAnswer: E'

## Grade (G)

Čia naudojama tik PatologijosDiag, nes kiek žiūrėjau, tai visada tik ten ir yra G. Also, per šį dataset nebuvo, bet manau įprastai gali būti ir atvejų, kad vietoj G3 yra Grade 3.
Išfiltravau atvejų, kai yra neteisingi labels. Aš galėčiau pati pakeisti, bet nežinau kodėl kai kurie buvo pažymėti kaip grade 4 arba 9

In [ ]:
def generate_prompt_G(data_point):
    return f"""
            Yra duotos naviko diferenciacijos laipsnio klasifikacijos žymės ir jų aprašymai:
            x – naviko diferenciacijos laipsnio įvertinti neįmanoma;
            1 – gerai diferencijuotas navikas;
            2 – vidutiniškai diferencijuotas navikas;
            3 – blogai diferencijuotas navikas;

            Pavyzdžiai:
            - Įvestis: 1-2(ekstra). Krūties audinys. 3(ekstra). Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma. SUMINIS TNM: pT2(22 mm navikas) N0(sn)(1 l/m) LVI-4 (limfovaskulinė invazija smulkiose gyslose ir venose). Radikalus pašalinimas. Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis ir kribriforminis tipai).  Imunofenotipas:  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 40%.
            - Rezultatas: 3
            - Paaiškinimas: rastas 'blogai diferencijuota' ir 'G3'

            - Įvestis: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma. Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių. Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių. Her2 imuninė reakcija: neigiama 1+. Ki67+ 10%.
            - Rezultatas: 1
            - Paaiškinimas: rastas 'gerai diferencijuota' ir 'G1'

            - Įvestis: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 10%, vietomis iki 15%.
            - Rezultatas: 2
            - Paaiškinimas: rastas 'vidutiniškai diferencijuota' ir 'G2'

            Užduotis:
            Išanalizuokite šį tekstą ir padarykite naviko diferenciacijos laipsnio klasifikaciją pagal duotas žymes. Tai gali būti trumpiniai (pvz., G1, G2, G3, ..), įvertinimai (pvz., Grade 1, Grade 2, Grade 3, ..).

            [{data_point["PatologijosDiag"]}] = """

In [ ]:
g_labels = train["G"].astype(int).astype(str).tolist()
# g_labels = [int(num) for num in g_labels]
# g_labels = list(map(str, g_labels))

testG = test
trainG = train
valG = val

X_test = pd.DataFrame(testG.apply(generate_prompt_G, axis=1), columns=["PatologijosDiag"])
X_train = pd.DataFrame(trainG.apply(generate_prompt_G, axis=1), columns=["PatologijosDiag"])
X_val = pd.DataFrame(valG.apply(generate_prompt_G, axis=1), columns=["PatologijosDiag"])

In [ ]:
from tqdm import tqdm
from transformers import pipeline

def predictG(model, tokenizer):
    g_pred = []
    pipe = pipeline(task="text-generation",
                model=model,
                tokenizer=tokenizer,
                max_new_tokens = 1,
                do_sample=False
                )

    for i in tqdm(range(len(X_train))):
        prompt = X_train.iloc[i]["PatologijosDiag"]
        result = pipe(prompt)
        answer = result[0]['generated_text'].split("=")[-1].strip()
        print("PatologijosDiag: ", trainG.iloc[i]["PatologijosDiag"])
        print("answer: ", answer)
        answer = str(answer)
        if answer in classification_labels_G:
            g_pred.append(answer)
        else:
            g_pred.append("-1")

    return g_pred

In [ ]:
g_pred = predictG(model, tokenizer)

Device set to use cuda:0
  0%|          | 0/661 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
  0%|          | 1/661 [00:00<10:23,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(3)(Extra). Reaktyvi limfadenopatija (1 l/m).  2(1)(Extra). Krūties audinys.  3(2)(Extra). Krūties audinys. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT(m)1c(2 naviko židiniai: 12 mm ir 1,7 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Krūties žemo laipsnio duktalinė karcinoma in situ (DIN1c/DCIS)(kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).
answer:  1

  0%|          | 2/661 [00:01<06:32,  1.68it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a). Fibrocistiniai krūties pokyčiai.  2(1b). Krūties audinys.  3(2). Reaktyvi limfadenopatija (2 l/m).  4(3). Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, TNM: pT1b(navikas 8,5 mm), pN0sn)(0/2 l/m), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).
answer:  1

  0%|          | 3/661 [00:01<05:05,  2.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Riebalinis audinys.  2. Krūties audinys.  3. Reaktyvi limfadenopatija (1 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) lobulinė karcinoma, TNM: pT2(40 mm naviko židinys), LVI0(neidentifikuota), pN0(sn)(0/1 l/m). Krūties lobulinė karcinoma in situ (LCIS). HER2:reakcijos nėra (0). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.
answer:  1

  1%|          | 4/661 [00:02<05:56,  1.85it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Riebalinis audinys.  3(Extra). Duktalinės karcinomos metastazės 2/4 limfmazgiuose (9 mm ir 1,8 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(22 mm) N(sn)1a(mts 2/4 l/m: 9 mm ir 1,8 mm), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).
answer:  3

  1%|          | 5/661 [00:02<05:01,  2.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.
answer:  1

  1%|          | 6/661 [00:02<04:10,  2.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 10%.
answer:  2

  1%|          | 7/661 [00:03<03:50,  2.84it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties audinys. Naviko plitimo nėra.   2(ekstra). Krūties audinys. Naviko plitimo nėra.   3. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) mišri duktalinė - mikropapilinė karcinoma. SUMINIS TNM: pT2 (22 mm navikas) NX(l/m nešalinti) LVI-2 (limfovaskulinė invazija smulkiose gyslose). Radikalus pašalinimas (R0).    Naviko imunotipas biopsijoje:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.
answer:  3

  1%|          | 8/661 [00:03<03:33,  3.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Riebalinis (krūties) audinys.  2. Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT2(2,1 cm) pN1a(1/14 l/m, mts 0,25 cm). LVI0(limfovaskulinės invazijos nėra).  4. Duktalinės adenokarcinomos metastazė 1/14 l/m.    Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2 imuninė reakcija neigiama (1+).  Ki67: 8%.
answer:  1

  1%|▏         | 9/661 [00:03<03:31,  3.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Kraštai. Krūties audinys be patologinių pokyčių.    2(ekstra). Kraštai. Krūties audinys be patologinių pokyčių.    3. Kairės krūties sektorius.   Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham sistemą) duktalinė karcinoma,   suminis TNM: pT2(30 mm makroskopiškai) pN1a (2/21 l/m su mts iki 25mm) pLVI-0.   Naviko struktūros siekia sektoriaus rezekcijos kraštą, žr. pastabą.  Naviko imunofenotipas (priešoperacinės biopsijos tyrime):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.   Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.   Her2 imuninė reakcija: neigiama 0.   Ki67+ 10%.  Her2 karcinomos metastazės limfmazgyje: HER2:reakcijos nėra (0).    4. Pažasties l/m. Krūties duktalinės karcinomos (iki 25 mm) metastazės 2/21 limfmazgių.
answer:  3

  2%|▏         | 10/661 [00:03<03:19,  3.26it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 b. pgl Nottingham) metaplastinė (matriksą produkuojanti) krūties karcinoma;   pT(m)4b(90 mm, 15mm su odos išopėjimu), pLVI-0, pR0.  Imunotipas (nustatytas priešoperaciniame naviko biopsijos tyrime):  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.   Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.   Her2 imuninė reakcija: neigiama 0+.   Ki67+ 90%.
answer:  3

  2%|▏         | 11/661 [00:04<03:13,  3.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2a). Fokalinė krūties audinio fibrozė.  2(N2b). Fokalinė krūties audinio fibrozė.  3(N3). Reaktyvi limfadenopatija (2 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma, TNM (Nr.1-Nr.4): pT2(2,1 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės invazijos nėra).   ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 20%.
answer:  4

  2%|▏         | 12/661 [00:04<03:01,  3.57it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2 (46mm) pN2a (7 iš 10 l/m) LVI 1.
answer:  3

  2%|▏         | 13/661 [00:04<02:53,  3.74it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 20%.
answer:  2

  2%|▏         | 14/661 [00:04<02:49,  3.82it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.
answer:  2

  2%|▏         | 15/661 [00:05<02:48,  3.83it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ %.
answer:  2

  2%|▏         | 16/661 [00:05<03:02,  3.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTAS ATSAKYMAS (žr. Molekuliniai/FISH/CISH):    1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi mišri vidutiniškai diferencijuota (G2; 7 b. pgl. Nottingham) lobulinė (40%) ir duktalinė karcinoma (60%), suminis TNM: pT2(m)(navikai 30 mm ir 2,5 mm), pN0(sn)(0/3 l/m), LVI2(limfovaskulinis plitimas). Perineurinis naviko plitimas. Gausi perinavikinė limfocitų infiltracija. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.    HER2 geno amplifikacija nenustatyta, tačiau FISH tyrimo rezultatas yra artimas teigiamam, todėl turi būti interpretuojamas įvertinus HER2 IHC tyrimą (žr. molekulinio tyrimo aprašymą ir pastabas).
answer:  1

  3%|▎         | 17/661 [00:05<02:57,  3.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 75% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 4% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 35%.
answer:  3

  3%|▎         | 18/661 [00:06<02:52,  3.74it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Mucininė karcinoma (smulkūs naviko fragmentai be aplinkinio audinio).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija paribinė (2+); ŽR.PASTABĄ.  Ki67: proliferacinis indeksas 10%.
answer:  1

  3%|▎         | 19/661 [00:06<03:11,  3.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutinio ir aukšto laipsnio intraduktalinė krūties karcinoma (DCIS/DIN2-3): 22mm plotas, papilinis ir komedo tipas.  ---------------  Du invaziniai navikai:  1. Vidutinės diferenciacijos (G2; 7 balai pgl Nottingham) invazinė duktalinė karcinoma; 1,1mm navikas.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.  Androgenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.    2. Vidutinės diferenciacijos (G2; 6 balai pgl Nottingham) invazinė duktalinė karcinoma; 3,0mm navikas.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 3%.  Androgenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  ---------------  Suminis TNM pT1a(m).
answer:  1

  3%|▎         | 20/661 [00:06<03:13,  3.31it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Gerai diferencijuota invazinė duktalinė karcinoma pT1mi(m) (daugybiniai smulkūs invazinės karcinomos židiniai, didžiausias 0,7mm).  Invaziniame navike:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigimia (branduolių nusidažymas 2% naviko ląstelių).  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.  Vidutinio laipsnio intraduktalinė krūties Carcinoma in situ (Din2/DCIS; solidinis/kribriforminis tipas; pakitimai 65mm plote).  N2: Limfmazgis be naviko židinių; pN0(sn).
answer:  1

  3%|▎         | 21/661 [00:07<03:20,  3.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija); be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su skersaruožiu raumeniu; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(1). Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 6 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).   Pavienės naviko struktūros siekia sektoriaus koaguliacijos zoną.
answer:  1

  3%|▎         | 22/661 [00:07<03:09,  3.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma   (plitimas 2/2 biopsiniuose stulpeliuose, iki 8,8 mm ilgyje).  Naviko imunofenotipas:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 50% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 15%.
answer:  2

  3%|▎         | 23/661 [00:07<02:56,  3.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1ab: Krūties audinys be naviko.  N2: Limfmazgiai (3 l/m) be naviko; pN0(sn).  N3: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (9mm).
answer:  1

  4%|▎         | 24/661 [00:07<02:50,  3.74it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 25%.
answer:  2

  4%|▍         | 25/661 [00:08<02:43,  3.89it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma.     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.
answer:  2

  4%|▍         | 26/661 [00:08<02:38,  4.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.
answer:  2

  4%|▍         | 27/661 [00:08<02:35,  4.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 60% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 6%.
answer:  1

  4%|▍         | 28/661 [00:08<02:49,  3.74it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(1b, ekstra). "Kraštai": fibrozuotas krūties audinys; kalcifikatai; be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   4(3). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 7 mm) N0(sn) (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, sklerozuojanti ir mikroglandulinė adenozė,   stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).
answer:  1

  4%|▍         | 29/661 [00:09<02:53,  3.64it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Reaktyvi limfadenopatija (2 l/m).  2. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 24mm) pN0(sn)(0/2 l/m); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse). Rezekcijos kraštas be naviko.  Estrogenų receptoriai: reakcija teigiama (vidutinė/stipri branduolių r-ja, 90% naviko ląstelių);   Progesterono receptoriai: reakcija teigiama (stipri branduolių r-ja, 85% naviko ląstelių);  HER2: reakcija neigiama (0+).  Androgenų receptoriai(++/+++), brand. r-ja, 60%;   Ki67 proliferacinis aktyvumas ~10%, fokaliai iki 20%;
answer:  3

  5%|▍         | 30/661 [00:09<02:59,  3.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties audinys.  2. Krūties audinys.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi, vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 25mm) pN0(sn)(0/2 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC/FISH reakcijos atliktos VPC:B23-19184 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcja neigiama, branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 35%.  HER2(FISH): NUSTATYTA HER2 GENO AMPLIFIKACIJA"  Stulpinis ląstelių pokytis su apikaline sekrecija.
answer:  3

  5%|▍         | 31/661 [00:09<02:51,  3.68it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 12%.
answer:  1

  5%|▍         | 32/661 [00:10<03:27,  3.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTAS ATSAKYMAS HER2 FISH TYRIMO REZULTATU:   1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(2b, ekstra). "Kraštai": krūties žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS: plokščias tipas). Krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė). Kalcifikatai.  3(ekstra). "Sarginiai limfmazgiai": lobulinės karcinomos metastazės dviejuose limfmazgiuose (mts 2/2 l/m; iki 12 mm skersmens).  4. "Papildomas kraštas": fibrozuotas riebalinis audinys; be naviko.     5(1). Krūties invazyvi mišri karcinoma:   vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma (~70%) ir   gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma (~30%),  SUMINIS TNM:   pT1c (navikas 17 mm) N1a(sn) (lobulinės karcinomos mts 2/2 l/m; iki 12 mm skersmens),   LVI-0 (definityvios limfovaskulinė invazija neidentifikuota).   Kalcifikatai.     Imunofenotipas:   Duktalinėje karcinomoje:   Estrogenų receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.   Progesterono receptoriai: vidutinė (++) reakcija, 20% naviko ląstelių.  HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.  Ki67: proliferacinis indeksas 1-2%.     Molekuliniai tyrimai:   HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Lobulinėje karcinomoje: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: plokščias, kribriforminis tipai).   Krūties lobulinė intraepitelinė neoplazija (LCIS).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).
answer:  1

  5%|▍         | 33/661 [00:10<03:12,  3.26it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G1; 5 b. pgl. Nottingham sist.) išlikusiame 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija teigiama (3+);   Ki67: proliferacinis indeksas 15%.
answer:  1

  5%|▌         | 34/661 [00:10<02:59,  3.49it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.
answer:  1

  5%|▌         | 35/661 [00:10<03:02,  3.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties lobulinė karcinoma in situ (LCIS).  3(ekstra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(30 mm navikas) pN0(sn)(0/2 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir papilinis tipai).      Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.
answer:  1

  5%|▌         | 36/661 [00:11<02:54,  3.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6 mm);  (G2; 6 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 5%. Karštame taške 8%.
answer:  2

  6%|▌         | 37/661 [00:11<02:54,  3.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a) - viršutinis kraštas. Riebalinis audinys be patologinių pokyčių.  2(1b) - apatinis kraštas. Krūties audinys be patologinių pokyčių.  3(2). Kairės krūties sektorius su limfmazgiais.  Krūtyje invazinė duktalinė karcinoma G2(7 b. pgl. Nottingham sist.);    pT(m)1c, pLVI-0 pN1a pR0.   Estrogenų receptoriai: stipri (+++)  reakcija, 90% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%.    Vidutinio laipsnio intraduktalinė karcinoma, DCIS/DIN2.
answer:  2

  6%|▌         | 38/661 [00:11<02:53,  3.60it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Gerai diferencijuota invazinė duktalinė karcinoma pT1mi(m) (daugybiniai smulkūs invazinės karcinomos židiniai, didžiausias 0,7mm).  Invaziniame navike:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigimia (branduolių nusidažymas 2% naviko ląstelių).  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.  Vidutinio laipsnio intraduktalinė krūties Carcinoma in situ (Din2/DCIS; solidinis/kribriforminis tipas; pakitimai 65mm plote).  N2: Limfmazgis be naviko židinių; pN0(sn).
answer:  1

  6%|▌         | 39/661 [00:11<02:44,  3.78it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.
answer:  1

  6%|▌         | 40/661 [00:12<02:45,  3.76it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi gerai diferencijuota (G1,5b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(19,5 mm navikas) pN1a(1/16 l/m MTS 2,1 mm) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 60% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 6%.
answer:  1

  6%|▌         | 41/661 [00:12<02:45,  3.74it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai.   2. Fibrocistiniai krūties pokyčiai.   3. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/2 l/m, 2,75 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 11 mm), pN1a(sn)(1/2 l/m), LVI2 (limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime (klinikiniai duomenys). HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).
answer:  3

  6%|▋         | 42/661 [00:12<02:40,  3.86it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: vidutinis ir silpnas branduolių nusidažymas 20% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.
answer:  2

  7%|▋         | 43/661 [00:13<02:39,  3.88it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 15 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.
answer:  2

  7%|▋         | 44/661 [00:13<02:41,  3.83it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties fibrocistiniai pokyčiai.   2. Krūties radialinis randas.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma,   pT1c (11 mm) pN0(sn) (0/2 l/m); LVI0 (limfovaskulinės naviko invazijos neidentifikuota).   Lobulinės karcinomos imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-27803, žr. pastabą.   Žemo laipsnio duktalinė karcinoma in situ (DCIS; kribriforminė, mikropapilinė).
answer:  1

  7%|▋         | 45/661 [00:13<02:47,  3.69it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Krūties lobulinė karcinoma in situ (LCIS).   3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(31 mm) N(sn)0(0/2 l/m), LVI-2(limfovaskulinė invazija). Perineurinė invazija. Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties lobulinė karcinoma in situ (LCIS).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Krūties intraduktalinės papilomos ir fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.
answer:  1

  7%|▋         | 46/661 [00:13<02:48,  3.64it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2)-sarginiai l/m-extra: limfmazgiai (3) be karcinomos ląstelių plitimo; pN0.    2(N1)- pašalinta dešinė krūtis.   Invazinė duktalinė (kitaip neklasifikuojama) karcinoma;  (G2; 7 b. pgl. Nottingham sist.);  pT2 pLVI-0 pR0 (<1 mm).  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija teigiama (3+);   Ki67: proliferacinis indeksas 15%.    Krūties fibrocistiniai pokyčiai.
answer:  1

  7%|▋         | 47/661 [00:14<02:41,  3.80it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo  nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.
answer:  1

  7%|▋         | 48/661 [00:14<02:50,  3.60it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2a) kraštai. Krūties audinys be patologinių pokyčių.    2(N2b) kraštai. Krūties audinys be patologinių pokyčių.    3(N3) dešinės pažasties sarginis limfmazgis. Limfmazgiai (3) be karcinomos ląstelių.    4(N1) dešinės krūties kvadrantas.  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma;(G3; 8 b. pgl. Nottingham sist.).  pT1c pN(sn)0(0/3) pLVI-0 pR0.  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stipri (+++)  reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%.    Intraduktalinė vidutinio laipsnio karcinoma (DCIS, DIN2 solidinio ir komedo tipo).
answer:  4

  7%|▋         | 49/661 [00:14<02:54,  3.50it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties fibrocistiniai pokyčiai, stulpinis ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija. Adenozė.   2(ekstra). Krūties intraduktalinė papiloma. Fibrocistiniai pokyčiai, stulpinis ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija.   3. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma (su morfologiniais lobulinės karcinomos požymiais).   SUMINIS TNM: pT3(65 mm navikas) N3a(12/22 l/m MTS iki 3 cm) LVI-2 (limfovaskulinė invazija). Naviko struktūros plinta sektoriaus rezekcijos krašte.   Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis tipas).
answer:  3

  8%|▊         | 50/661 [00:14<02:48,  3.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 45%, vietomis iki 60%.
answer:  3

  8%|▊         | 51/661 [00:15<02:44,  3.71it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.
answer:  2

  8%|▊         | 52/661 [00:15<03:01,  3.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Riebalinis audinys.  3(Extra). Reaktyvi limfadenopatija (5 l/m).  4. A) Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(8,5 mm) N(sn)0(0/5 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus/vidutinis branduolių nusidažymas 50% naviko ląstelių.  HER2 imuninė reakcija: neigiama (0).  Ki67: 10% (hot-spot 15%).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).     B) Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1a(1,3 mm) N(sn)0(0/5 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  HER2 imuninė reakcija: neigiama (1+).  Ki67: 1%.   Lobulinė karcinoma in situ (LCIS).
answer:  2

  8%|▊         | 53/661 [00:15<02:50,  3.56it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.
answer:  3

  8%|▊         | 54/661 [00:16<02:41,  3.75it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.
answer:  1

  8%|▊         | 55/661 [00:16<02:55,  3.45it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Sektoriaus kraštai.   Krūties žemo laipsnio duktalinė karcinoma in situ (DCIS,DIN1).   Intraduktalinė papiloma. Židininė intraduktalinė hiperplazija.    2. Sektoriaus kraštai. Krūties audinys be patologinių pokyčių.    3. Sarginiai limfmazgiai. Karcinomos plitimas iki 4,5 mm 1-me/9 limfmazgių; stebimas ekstranodalinis plitimas.    4(5). Papildomas kraštas. Krūties audinys be patologinių pokyčių.    5(4). Krūties sektorius.   Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma;   pT1c(15 mm mikroskopiškai) pN1a (1/9; 4,5 mm) pR0.   Imunofenotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: (+++)(brand. r-ja) 100%.   Progesterono receptoriai: (+++)(brand. r-ja) 100%.   HER2 imuninės reakcijos nėra (0).  Ki67 proliferacinis aktyvumas iki 10%.    Krūties žemo laipsnio duktalinė karcinoma in situ (DCIS,DIN1).   Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija,   sklerozuojanti adenozė.
answer:  1

  8%|▊         | 56/661 [00:16<02:51,  3.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT2(30 mm navikas) pN1a(1/12 l/m su mts 33mm) pLVI0 (limfovaskulinė invazija neidentifikuota) pR0(radikalus pašalinimas).  Naviko imunotipas:  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 80%.    Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis, kribriforminis tipai).
answer:  3

  9%|▊         | 57/661 [00:17<03:14,  3.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  A) Krūties invazyvi multicentrinė karcinoma:  - invazyvi duktalinė adenokarcinoma (vidutiniškai diferencijuota/G2/6 balai pagal Nottingham) (4,2 cm naviko židinys; intraduktalinės papilinės, solidinės papilinės karcinomos fone),  - invazyvi lobulinė karcinoma (vidutiniškai diferencijuota/G2/6 balai pagal Nottingham) (1,4 cm naviko židinys).   B) Dauginės intraduktalinės papilomos.  C) Lobulinė karcinoma in situ (LCIS).  D) Krūties fibrocistiniai pokyčiai.  ---  Piktybinių navikų (karcinomų) "suminis" kategorizavimas pagal TNM: pT2(m)(iki 4,2 cm duktalinės karcinomos + iki 1,4 cm lobulinės karcinomos židiniai) pN2a(duktalinės adenokarcinomos mts 5/31 l/m, didžiausia metastazė 2,0 cm, nežymus ekstranodalinis plitimas). LVI2(duktalinės adenokarcinomos limfovaskulinė naviko invazija, smulkiose struktūrose). R0(radikalus navikų pašalinimas).   ---  Krūties invazyvios duktalinės adenokarcinomos imunofenotipas  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.  ---  Krūties invazyvios lobulinės karcinomos imunofenotipas  Estrogenų receptoriai: stiprus-vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.
answer:  3

  9%|▉         | 58/661 [00:17<03:08,  3.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties audinys.  2. Riebalinis audinys be patologijos.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi blogai diferencijuota (G3; 8 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 13,5 mm), pN0(sn)(0/3 l/m), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS). HER2:reakcijos nėra (0).  Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija.
answer:  3

  9%|▉         | 59/661 [00:17<03:04,  3.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Papildyta HER2 FISH.  Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma. Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+).  Ki67 proliferacinis aktyvumas 15%.  HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).
answer:  1

  9%|▉         | 60/661 [00:17<02:58,  3.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 15%.
answer:  2

  9%|▉         | 61/661 [00:18<03:06,  3.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   2(2b, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko  3(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (I - 14 mm; II - 4 mm) N2a (mts 6/10 l/m; iki 45 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.     Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: solidinis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   4(3). "Kairės pažasties limfmazgiai": duktalinės karcinomos metastazė šešiuose limfmazgiuose (mts 6/10 l/m; iki 45 mm skersmens; su ekstranodaliniu plitimu).
answer:  3

  9%|▉         | 62/661 [00:18<03:02,  3.29it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 55% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacijos FISH tyrimo rezultatas teigiamas (žr. molekulinio tyrimo aprašymą ir pastabas).  Ki67+ 25%.
answer:  2

 10%|▉         | 63/661 [00:18<02:57,  3.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.
answer:  1

 10%|▉         | 64/661 [00:19<02:54,  3.42it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Krūties audinio fibrozė.  N2: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.
answer:  1

 10%|▉         | 65/661 [00:19<02:45,  3.60it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.
answer:  1

 10%|▉         | 66/661 [00:19<02:38,  3.75it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.
answer:  1

 10%|█         | 67/661 [00:19<02:32,  3.88it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 90% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 1%.
answer:  1

 10%|█         | 68/661 [00:20<02:33,  3.87it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 8%. Karštame taške 15%.
answer:  2

 10%|█         | 69/661 [00:20<02:36,  3.78it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties fibrocistiniai pokyčiai.  2. Nežymi fokalinė krūties audinio fibrozė.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,8 cm) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės naviko invazijos nėra). Seborėjinė keratozė.     Estrogenų receptoriai: stipri (+++)  reakcija, 90% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 15%.
answer:  3

 11%|█         | 70/661 [00:20<02:39,  3.70it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi blogai diferencijuota (G3; 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(20 mm) N(sn)0(0/4 l/m), LVI-2(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS)(solidinė, kribriforminė, komedo).
answer:  1

 11%|█         | 71/661 [00:20<02:40,  3.68it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties fibrocistiniai pokyčiai: stulpinis epitelio pokytis, paprasta intraduktalinė hiperplazija.   2. Krūties audinys be patologinių pokyčių.   3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2/ 6 b. pagal Nottingham s.) duktalinė karcinoma, suminis Nr. 1 - 4 pTNM:   pT1c (18 mm) pN0(sn) (0/3 l/m), LVI0 (limfovaskulinės naviko invazijos neidentifikuota).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-19395, žr. pastabą.
answer:  3

 11%|█         | 72/661 [00:21<02:33,  3.84it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTA  Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 1%.
answer:  1

 11%|█         | 73/661 [00:21<02:27,  3.97it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham sistemą) duktalinė karcinoma, pT4b (56 mm, odoje išopėjęs navikas) pN2a (4/11 l/m su mts iki 10mm) LVI-0 (limfovaskulinė invazija neidentifikuota).  Radikalus pašalinimas.
answer:  2

 11%|█         | 74/661 [00:21<02:43,  3.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). "Dešinės pažasties sarginiai limfmazgiai":   lobulinės karcinomos metastazė limfmazgiuose (mts 2/3 l/m; iki 18 mm skersmens).    2(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT2(m) (navikai: I - 34 mm; II - 7 mm) N1a(sn) (mts 2/3 l/m; iki 18 mm skersmens),    LVI-2 (limfovaskulinė invazija smulkiose šakose). Perineurinis plitimas.   Imunofenotipas:   Estrogenų receptoriai: vidutinė-stipri (++/+++) reakcija, 99% naviko ląstelių.  Progesterono receptoriai: vidutinė-stipri (++/+++) reakcija, 99% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%. Karštame taške 10%.    Krūties lobulinė intraepitelinė neoplazija (LCIS).  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Krūties rezekcijos kraštas be naviko.
answer:  1

 11%|█▏        | 75/661 [00:22<02:37,  3.73it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.
answer:  2

 11%|█▏        | 76/661 [00:22<02:32,  3.84it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 85%.
answer:  3

 12%|█▏        | 77/661 [00:22<02:38,  3.69it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Duktalinės karcinomos metastazės limfmazgiuose (3/3 l/m iki 7 mm).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(m)(34 mm ir 4 mm navikai) pN1a(sn)(3/3 l/m MTS iki 7 mm) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija).(DCIS/DIN3 DIN1 DIN2, kribriforminis ir papilinis tipai).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis iki 20%.
answer:  1

 12%|█▏        | 78/661 [00:22<02:42,  3.59it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (4 l/m).    4. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(m)(16 mm, 10 mm navikai) pN0(sn)(0/4 l/m) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija). Aukšto laipsnio duktalinė karcinoma in situ (DIN3 solidinis tipas).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 95% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 70% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 25%.
answer:  3

 12%|█▏        | 79/661 [00:23<02:34,  3.76it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 60%.
answer:  2

 12%|█▏        | 80/661 [00:23<02:29,  3.89it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 40%.
answer:  2

 12%|█▏        | 81/661 [00:23<02:38,  3.66it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Pjūvio kraštai - sklerozuojanti adenozė su gestacijai/laktacijai būdingais pokyčiais.  2. Pjūvio kraštai - sklerozuojanti adenozė su gestacijai/laktacijai būdingais pokyčiais.    3. Sarginiai l/m - limfmazgiai (3) be patologinių pokyčių.    4. Krūties sektorius.   Blogai diferencijuota krūties invazinė duktalinė  karcinoma(su medulinės karcinomos struktūra ir gausiais naviką infiltruojančiais limfocitais);   (G3, 9 balai pgl Nottingham),   pT2 pLVI-0 pN0 pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: reakcija neigiama.  Progesterono receptoriai: vidutinis branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 60%.    Sklerozuojanti adenozė.
answer:  3

 12%|█▏        | 82/661 [00:23<02:45,  3.49it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2, ekstra). "Dešinės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).   2(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 12 mm) N0(sn) (0/2 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS). Randiniai pokyčiai odoje.   Gilusis krūties rezekcijos kraštas be naviko.
answer:  3

 13%|█▎        | 83/661 [00:24<02:51,  3.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija); be naviko.   2(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 9 mm) N0(sn) (0/3 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis tipas).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).
answer:  1

 13%|█▎        | 84/661 [00:24<02:40,  3.59it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties mikropapilinė karcinoma (G2, 6 balai pgl Nottingham) pT2(28mm); pN2a (iš 16 l/m).
answer:  2

 13%|█▎        | 85/661 [00:24<02:34,  3.74it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 35%, vietomis iki 60%.
answer:  3

 13%|█▎        | 86/661 [00:24<02:28,  3.87it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 80%.
answer:  3

 13%|█▎        | 87/661 [00:25<02:24,  3.97it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%, fokaliai iki 20%.
answer:  1

 13%|█▎        | 88/661 [00:25<02:22,  4.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20%.
answer:  2

 13%|█▎        | 89/661 [00:25<02:29,  3.82it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a)(Extra). Krūties audinys.  2(2b)(Extra). Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT(m)1c(3 naviko židiniai: 15 mm, 13 mm ir 9 mm) N2a(mts 5/10 l/m; didžiausia 33 mm, su ekstranodaliniu plitimu), LVI-2(limfovaskulinė invazija). Didžiausias (I) navikas siekia markiruotą rezekcijos kraštą.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Androgenų receptoriai: vidutinis branduolių nusidažymas 70% naviko ląstelių.  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).
answer:  3

 14%|█▎        | 90/661 [00:26<02:31,  3.76it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties audinys.  2. Krūties audinys.   3. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi, gerai diferencijuota (G1, 4 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 25mm) pN0(sn)(0/1 l/m); LVI-0 (Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-19397 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%."
answer:  1

 14%|█▍        | 91/661 [00:26<02:37,  3.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties atipinė lobulinė hiperplazija.   2. Krūties fibrocistiniai pokyčiai.    3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2/ 6 b. pagal Nottingham s.) duktalinė karcinoma,   pT1b (6 mm) pN0(sn) (0/3 l/m), LVI0 (limfovaskulinės naviko invazijos neidentifikuota).   Imunofenotipas:   estrogenų receptorių (ER) reakcija teigiama: stiprus/ vidutinis branduolių nusidažymas 100% naviko ląstelių,   progesterono receptorių (PR) reakcija teigiama: stiprus/ vidutinis branduolių nusidažymas 10% naviko ląstelių,   HER2 reakcija neigiama (0),   Ki67 prolif. indeksas ~5%.   Žemo laipsnio duktalinė karcinoma in situ (DCIS).
answer:  1

 14%|█▍        | 92/661 [00:26<02:41,  3.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2a) kraštas - riebalinis audinys be patologinių pokyčių.  2 (N2b) kraštas - riebalinis audinys be patologinių pokyčių.    3 (N3) dešinės pažasties sarginis limfmazgis: limfmazgiai(3) be patologinių pokyčių.    4 (N1) - dešinės krūties kvadrantas.   Invazinė lobulinė karcinoma  (G1; 5 b. pgl. Nottingham sist.);  pT1b pN0 pLVI-0 pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    5 (N4) - papildomas kraštas. Riebalinio audinio fragmentas be patologinių pokyčių.
answer:  1

 14%|█▍        | 93/661 [00:26<02:33,  3.70it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b (8cm navikas; išopėjimas).
answer:  3

 14%|█▍        | 94/661 [00:27<02:28,  3.83it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%, vietomis 15%.
answer:  2

 14%|█▍        | 95/661 [00:27<02:37,  3.59it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(kraštai). Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.     2(kraštai). Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.     3(sarginiai l/m). Duktalinės karcinomos mikrometastazės (iki 1 mm skersmens) 1-me/3 limfmazgių.    4(krūties sektorius).   Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT1c (18 mm) pN1mi(1/3 l/m iki 1mm) pLVI-2 (limfovaskulinė invazija smulkiose gyslose) pR0(radikalus pašalinimas).  Naviko imunotipas nustatytas priešoperaciniame biopsijos tyrime (žr. pastabą).   Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis, kribriforminis, komedo tipai).  Krūties fibrocistiniai pokyčiai:   paprastoji intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija. Adenozė.
answer:  1

 15%|█▍        | 96/661 [00:27<02:34,  3.65it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi blogai diferencijuota (G3; 8 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 17 mm), pN0(sn)(0/2), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).
answer:  3

 15%|█▍        | 97/661 [00:28<02:45,  3.41it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     2. Krūties multižidininė vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) invazyvi duktalinė (12 mm) ir lobulinė (9 mm) karcinoma, SUMINIS TNM:   pT1c(m) (I - 9 mm; II - 12 mm) N0(sn) (0/3 l/m),    LVI-0 (limfovaskulinė invazija neidentifikuota).   Perineurinis plitimas. Kalcifikatai.     Imunofenotipas (šiame tyrime):  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 20% naviko ląstelių.   HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%. Karštame taške 10%.  ŽR. PASTABĄ.     Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis tipas).   Krūties lobulinė intraepitelinė neoplazija (LCIS).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   Gilusis rezekcijos kraštas normalios histologinės struktūros.
answer:  3

 15%|█▍        | 98/661 [00:28<02:45,  3.41it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai.  2. Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 20 mm), pN2a(6/9 l/m), LVI2 (limfovaskulinis plitimas). Perineurinis naviko plitimas. Navikas nuo skersaruožio raumens rezekcijos krašto nutolęs per 1,2 mm. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).   4. Krūties duktalinės karcinomos metastazės šešiuose limfmazgiuose (6/9 l/m, 9,5 mm, ekstranodalinis plitimas).
answer:  3

 15%|█▍        | 99/661 [00:28<02:47,  3.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Dešinė  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.  Aukšto laipsnio intraduktalinė karcinoma (DCIS; solidinė ir komedo).  --------------  Kairė  N2: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%, vietomis iki 30%.
answer:  2

 15%|█▌        | 100/661 [00:28<02:35,  3.60it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.
answer:  2

 15%|█▌        | 101/661 [00:29<02:48,  3.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); kalcifikatai; be naviko.   2(ekstra). "Kraštai": krūties lobulinė intraepitelinė neoplazija (LCIS).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 6 mm) N0(sn) (0/3 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    Krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: plokščias, papilinis tipai).  Krūties lobulinė intraepitelinė neoplazija (LCIS). Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).
answer:  3

 15%|█▌        | 102/661 [00:29<02:44,  3.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus ar vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.  N2: Krūties fibroadenoma.
answer:  1

 16%|█▌        | 103/661 [00:29<02:51,  3.26it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).   2. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT2 (navikas 22 mm) N0(sn) (0/2 l/m), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcijos nėra (0).  Androgenų receptoriai: vidutinis branduolių nusidažymas 100% naviko ląstelių.    Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS: solidinis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta ir papilinė intraduktalinė hiperplazija, apokrininė metaplazija).   Krūties rezekcijos kraštas normalios histologinės struktūros.
answer:  3

 16%|█▌        | 104/661 [00:30<02:42,  3.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.
answer:  1

 16%|█▌        | 105/661 [00:30<02:49,  3.28it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a) kraštai-ekstra: krūties fibrocistiniai pokyčiai. Naviko plitmo nėra.     2(2b) kraštai-ekstra: krūties fibrocistiniai pokyčiai. Naviko plitimo nėra.     3 sarginis l/m. Limfmazgis su sinusų histiocitoze, lipomatoze.     4(1) dešinės krūties kvadrantas.  Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma;  pT1c(16 mm) pN(sn)0 (0/1 l/m) pLVI-0 pR0.   Imunofenotipas (nustatytas priešoperaciniame biopsijos tyrime):   Estrogenų receptoriai: reakcija teigiama (stiprus branduolių nusidažymas 100% naviko ląstelių).  Progesterono receptoriai: reakcija teigiama (stiprus branduolių nusidažymas 100% naviko ląstelių).  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, solidinis tipas).
answer:  3

 16%|█▌        | 106/661 [00:30<02:51,  3.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTA (HER2 FISH TYRIMAS):  1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Krūties audinys.  4. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(16 mm) pNX(limfmazgiai nešalinti, LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).  HER2 imuninė reakcija: ribinė (2+).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).   Krūties vidutinio ir žemo laipsnio duktalinė karcinoma in situ (DIN1c/DIN2/DCIS)(kribriforminė).
answer:  1

 16%|█▌        | 107/661 [00:31<02:59,  3.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Sektoriaus kraštai. Riebalinis fibrozinis audinys, be naviko plitimo.   2(ekstra). Sektoriaus kraštai. Krūties audinys be naviko plitimo.     3(ekstra). Sarginiai l/m. Reaktyvi limfadenopatija (1 l/m).     4. Dešinės krūties sektorius.   Krūties invazyvi vidutiniškai diferencijuota (G2, 6 b. pagal Nottingham sist.) duktalinė karcinoma,   pT2 (24 mm) pN0(sn)(0/1 l/m) pLVI-2 (invazija smulkiose gyslose) pR0(radikalus pašalinimas).   Naviko imunotipas nustatytas biopsiniame tyrime (B23-13987):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis, kribriforminis tipas).  Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija, apokrininė metaplazija.
answer:  3

 16%|█▋        | 108/661 [00:31<03:00,  3.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Krūties audinyje 29mm navikas iš trijų komponentų:  Intracistinė papilinė karcinoma (14mm, traktuojama kaip In situ karcinoma);  Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS, solidinė ir kribrozinė; 13mm);  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma (trys invazijos židiniai, didžiausias 6mm); pT1b.  Invazinis navikas:  estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių;  progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių;  Her2 imuninė reakcija: neigiama 1+;  Ki67+ 15%.  N2: Limfmazgis be naviko metastazių; pN0(sn).
answer:  1

 16%|█▋        | 109/661 [00:31<02:49,  3.25it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Riebalinis audinys.  2(Extra). Riebalinis audinys.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma (g.b. iš solidinės papilinės karcinomos), SUMINIS TNM: pT1b(8 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).
answer:  1

 17%|█▋        | 110/661 [00:31<02:40,  3.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Duktalinės karcinomos metastazė limfmazgyje.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 30%.
answer:  3

 17%|█▋        | 111/661 [00:32<02:34,  3.55it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.  N2: Duktalinės karcinomos metastazės (navikinio audinio bioptatai, limfmazgio audinio nėra).
answer:  1

 17%|█▋        | 112/661 [00:32<02:27,  3.73it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 75% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67+ 8%.
answer:  1

 17%|█▋        | 113/661 [00:32<02:25,  3.76it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 30%.
answer:  2

 17%|█▋        | 114/661 [00:32<02:21,  3.86it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė karcinoma, tikėtina duktalinė (navikas ECAD+).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.
answer:  1

 17%|█▋        | 115/661 [00:33<02:47,  3.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a). Krūties audinys.  2(1b). Krūties fibrocistiniai pokyčiai. Intraduktalinė papiloma (0,3 cm).  3(2). Reaktyvi limfadenopatija (2 l/m).  4(3). Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,6 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės invazijos nėra). Krūties intraduktalinė papiloma (0,3 cm).     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.
answer:  1

 18%|█▊        | 116/661 [00:33<02:41,  3.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 1-2%.
answer:  1

 18%|█▊        | 117/661 [00:33<02:40,  3.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 16%.
answer:  2

 18%|█▊        | 118/661 [00:34<02:39,  3.41it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama)  karcinoma (mažiausiai iki 9 mm);  (G2; 6 b. pgl. Nottingham sist.) 2/3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 20%.
answer:  2

 18%|█▊        | 119/661 [00:34<02:42,  3.34it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.2): pT2m(iki 4 naviko židinių, didžiausias 2,3 cm) pN1a(1/1 intramamarinis l/m + 1/3 sarginis l/m, didžiausia mts 0,6 cm). LVI2(limfovaskulinė naviko invazija, smulkiose struktūrose). R0(radikalus naviko pašalinimas).  2. Duktalinės adenokarcinomos mts 1/3 l/m (mts 0,5 cm).  ---  Estrogenų receptoriai: stipri branduolinė r-ja 100% naviko ląstelių.  Progesterono receptoriai: stipri branduolinė r-ja 100% naviko ląstelių.  HER2: silpnas dalies membranos nusidažymas 5% naviko ląstelių.  Ki67: iki 15%.
answer:  1

 18%|█▊        | 120/661 [00:34<02:36,  3.45it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.
answer:  1

 18%|█▊        | 121/661 [00:35<02:38,  3.41it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Fibrocistiniai krūties pokyčiai.  2(2b). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (2 l/m).  4(1). Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 11 mm), pN0(sn)(0/2 l/n), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).
answer:  1

 18%|█▊        | 122/661 [00:35<02:32,  3.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2(m) (11mm ir 25mm); pN1a (1 iš 23 l/m; 25mm).
answer:  3

 19%|█▊        | 123/661 [00:35<02:36,  3.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma su apokrininės diferenciacijos požymiais.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 8% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 20%.
answer:  3

 19%|█▉        | 124/661 [00:35<02:42,  3.31it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Krūties karcinomos mikrometastazė limfmazgyje (microMTS 1/3 l/m 1,6 mm)    4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma su mikropapilinės karcinomos komponentu,   SUMINIS TNM: pT1c(17 mm navikas) pN1mi(sn)(microMTS 1/3 l/m 1,6 mm) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija).  Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 kribriforminis ir papilinis tipai).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 60% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 40%.
answer:  3

 19%|█▉        | 125/661 [00:36<02:39,  3.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.  Krūties fibroadenoma.  N2: Krūties fibroadenoma.
answer:  1

 19%|█▉        | 126/661 [00:36<02:43,  3.28it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: T1c(14 mm navikas) pN1a(sn)(1/5 l/m MTS 4,4 mm) LVI-2(limfovaskulinė invazija).  R0(radikali rezekcija).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.    2. Krūties audinio fibrozė.  3. Krūties audinio fibrozė.  4. Duktalinės karcinomos metastazė limfmazgyje (1/4 l/m MTS 4,4 mm).
answer:  1

 19%|█▉        | 127/661 [00:36<02:48,  3.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Kairė  N1-2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.  ----------  Dešinė  N3: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.
answer:  1

 19%|█▉        | 128/661 [00:37<02:36,  3.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(17mm).  N2ab: Krūties audinys be naviko.  N3: Limfmazgis (1 iš 2 l/m) su metastaze 4mm; pN1a(sn).
answer:  2

 20%|█▉        | 129/661 [00:37<02:34,  3.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties fibrocistiniai pokyčiai.   2. Krūties intraduktalinė papiloma. Atipinė duktalinė hiperplazija, fibrocistiniai pokyčiai.   3. Reaktyvi limfadenopatija (1 l/m).   4. Reaktyvi limfadenopatija (1 l/m).   5. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma su minimaliu(~5%) mikropapilinės karcinomos komponentu,   suminis Nr. 1 - 4 pTNM:   pT2 (25 mm) pN1mi(sn) (3/6 l/m, metastazės iki 1,2 mm); LVI2 (limfovaskulinė naviko invazija smulkiose kraujagyslėse/limfagyslėse).   Fibroadenoma.   6. Riebalinis audinys be patologinių pokyčių.
answer:  1

 20%|█▉        | 130/661 [00:37<02:28,  3.56it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G2; 6 b. pgl. Nottingham sist.) 4-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 10%.
answer:  2

 20%|█▉        | 131/661 [00:38<02:31,  3.49it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Kraštai. Krūties audinys be patologinių pokyčių.  2. Kraštai. Krūties audinys be patologinių pokyčių.  3. Sarginiai limfmazgiai: Limfmazgiai (4) be karcinomos ląstelių; pN0.  4. Kairės krūties sektorius.   Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT2(24 mm) pLVI-0 pR0.  Imunotipas nsutatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%
answer:  3

 20%|█▉        | 132/661 [00:38<02:34,  3.42it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai": fibrozuotas krūties-riebalinis audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties-riebalinis audinys su lėtine nespecifine uždegimine infiltracija; be naviko.   3(ekstra). "Dešinės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   4(1). Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT2 (navikas 23 mm) N0(sn) (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Naviko nekrozė iki 40%.   Imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcijos nėra (0).  Ki67: proliferacinis indeksas 50%.   GATA3(+)30%; SOX-10(+)99%.   Krūties sektoriaus rezekcijos kraštas normalios histologinės struktūros.
answer:  4

 20%|██        | 133/661 [00:38<02:30,  3.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma, pT1b (9 mm navikas) pLVI-2 (limfovaskulinė invazija smulkiose gyslose).   Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis, kribriforminis tipai). Paprastoji duktalinė hiperplazija. Intraduktalinė papiloma.  Radikalus pašalinimas.
answer:  2

 20%|██        | 134/661 [00:38<02:22,  3.71it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis iki 15%.
answer:  2

 20%|██        | 135/661 [00:39<02:16,  3.87it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.
answer:  1

 21%|██        | 136/661 [00:39<02:12,  3.98it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.
answer:  2

 21%|██        | 137/661 [00:39<02:19,  3.76it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.
answer:  1

 21%|██        | 138/661 [00:39<02:36,  3.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Krūties žemo ir vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis, kribriforminis tipai).  2(2b). Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis tipas).  3(2c). Krūties audinys.    4. Reaktyvi limfadenopatija (4 l/m).  5(pap.). Krūties audinys.  6. Krūties invazyvi, vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham sis) karcinoma (kilusi iš solidinės papilinės karcinomos) su mucininės karcinomos diferenciacijos zonomis (~70% naviko), suminis tyrimo TNM: pT1c(navikas - 16mm) pN0(sn)(0/4 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).   IHC reakcijos atliktos VPC:B23-34296 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.  Proliferacinis aktyvumas (Ki67+++, branduolinė r-ja): 5%.  CK5(-), CK14(-), Synaptophysin(++/+++)(citoplazminė r-ja), 90%."  Krūties žemo ir vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis, kribriforminis tipai).
answer:  1

 21%|██        | 139/661 [00:40<02:29,  3.50it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (su apokrinine diferenciacija) karcinoma (mažiausiai iki 11 mm);  (G2; 7 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija paribinė (2+); nustatyta HER2 geno amplifikacija (žr. molekulinio tyrimo aprašymą).  Ki67: proliferacinis indeksas 20%.
answer:  2

 21%|██        | 140/661 [00:40<02:21,  3.69it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) adenokarcinoma, tikėtina duktalinė.  Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 90%.  Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 80%.   HER2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 8%.
answer:  2

 21%|██▏       | 141/661 [00:40<02:25,  3.57it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Paruošti pjūviai Prosigna.  1(ekstra). Reaktyvi limfadenopatija (1 l/m).  2(ekstra). Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai pokyčiai: parastoji intraduktalinė hiperplazija.  3. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(m)(25 mm, 10 mm navikai) pN0(sn)(0/1 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).  Lobulinė karcinoma in situ (LCIS).     Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%.
answer:  3

 21%|██▏       | 142/661 [00:41<02:26,  3.54it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Riebalinis audinys.  3(Extra). Krūties duktalinės karcinomos metastazė 1/3 l/m (4,5 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(20 mm) N(sn)1a(mts 1/3 l/m: 4,5 mm), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).
answer:  1

 22%|██▏       | 143/661 [00:41<02:21,  3.66it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 5%.
answer:  1

 22%|██▏       | 144/661 [00:41<02:35,  3.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a)(Extra). Riebalinis audinys.  2(2b)(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi blogai diferencijuota (G3; 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(32 mm) N(sn)0(0/3 l/m), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas (naviko atstumas nuo rezekcijos krašto 0,6 mm).  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   5. Reaktyvi limfadenopatija (2 l/m).
answer:  1

 22%|██▏       | 145/661 [00:42<02:52,  3.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.
answer:  1

 22%|██▏       | 146/661 [00:42<03:41,  2.32it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties multižidininė duktalinė karcinoma su dviem morfologiniais variantais:   A. I, II, III židiniai:   Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma (kitaip neklasifikuotina).   Naviko imunotipas nustatytas biopsijoje (B23-4490):   Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 12%.    B. IV-tas židinys:   krūties invazyvi vidutiniškai diferencijuota (G2, 7 b. pgl. Nottingham sist.) duktalinė karcinoma (šviesių ląstelių variantas).  Naviko imunotipas:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacijos FISH tyrimo rezultatas laikytinas TEIGIAMU (interpretuojamas HER2 IHC tyrimo kontekste; žr. molekulinio tyrimo aprašymą ir pastabas).    Suminis TNM:   pT(m)2 (21 mm, 18 mm, 15 mm, 7mm naviko židiniai)   pN1a(1/16 l/m su mts iki 8,3 mm)   pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pR0(radikalus pašalinimas).
answer:  3

 22%|██▏       | 147/661 [00:43<03:41,  2.32it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (3 l/m).  4(1). Krūties invazyvi blogai diferencijuota (G3; 9 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 18 mm), pN0(sn)(0/3 l/m), LVI2(limfovaskulinis plitimas). Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS). R0(radikali rezekcija). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).
answer:  3

 22%|██▏       | 148/661 [00:43<03:30,  2.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1-2: Krūties audinys be naviko.  N3: Limfmazgiai (2 l/m) be naviko; pN0(sn).  N4: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pN1c(20mm).
answer:  3

 23%|██▎       | 149/661 [00:43<03:35,  2.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10-12%.
answer:  1

 23%|██▎       | 150/661 [00:44<03:52,  2.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Atipinė lobulinė hiperplazija (ALH; intraduktalinis plitimas). Fibrocistiniai krūties pokyčiai.  2. Reaktyvi limfadenopatija (3 l/m).  3. Multižidininė krūties karcinoma: invazyvi, vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham sis) duktalinė karcinoma (židinys - 10,9mm) ir invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham sis) lobulinė karcinomos (židinys - 12,2mm), suminis tyrimo TNM: pT1c(m)(du naviko židiniai: 10,9mm ir 12,2mm); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).   Duktalinė krūties karcinoma:  Estrogenų receptoriai: reakcija teigiama (stipri branduolių r-ja, 100% naviko ląstelių).   Progesterono receptoriai: reakcija teigiama (vidutinė/stipri branduolių r-ja, 95% naviko ląstelių).   HER2: žema imunohistocheminė raiška (1+).   Ki67 proliferacinis aktyvumas ~10%.  Lobulinė krūties karcinoma (IHC reakcijos atliktos VPC:B23-44687 tyrime):   "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 5%, vietomis iki 10%."  Lobulinė krūties karcinoma in situ (LCIS). Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; kribriforminis, solidinis tipas; -komedo tipo nekrozės). Rezekcijos kraštas be naviko.
answer:  3

 23%|██▎       | 151/661 [00:44<03:27,  2.46it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.
answer:  2

 23%|██▎       | 152/661 [00:45<03:09,  2.69it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė tubulinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 98% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 4%.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).
answer:  1

 23%|██▎       | 153/661 [00:45<02:55,  2.89it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 5%.
answer:  2

 23%|██▎       | 154/661 [00:45<02:45,  3.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.
answer:  1

 23%|██▎       | 155/661 [00:45<02:37,  3.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%.
answer:  2

 24%|██▎       | 156/661 [00:46<02:35,  3.26it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Reaktyvi limfadenopatija (4 l/m).  2. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(10 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Židininė krūties audinio fibrozė ir fibrocistiniai pokyčiai: stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).
answer:  1

 24%|██▍       | 157/661 [00:46<02:37,  3.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma;   pT2(28 mm) pLVI-0 pN0(0/4).  Imunotipas (pirminis, pagal klinikinius duomenis):  ER imuninė reakcija neigiama.   PR imuninė reakcija teigiama (silpnas branduolių nusidažymas apie 3% navikinių ląstelių).   Reakcija su HER2 neigiama (1+).    Pakartotas/papildytas (operacinėje medžiagoje):  Estrogenų receptoriai: reakcijos nėra.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 50%.    2. Krūties audinys be patologinių pokyčių.  3. Krūties audinys be patologinių pokyčių.  4. Limfmazgiai(4) be patologinių pokyčių.  5. Krūties audinys be patologinių pokyčių.
answer:  3

 24%|██▍       | 158/661 [00:46<02:30,  3.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.  .  Progesterono receptoriai: stipri reakcija 90% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.
answer:  2

 24%|██▍       | 159/661 [00:47<02:36,  3.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTA  "XXIIIBO-2907" (keturi blokai; limfmazgiai)  Reaktyvi limfadenopatija (galimai 3 l/m).  "XXIIIBO-2416" (vienas blokas; krūties naviko biopsija)  Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma.  "XXIIIBO-2930" (trylika blokų; krūties sektorius)  Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma, ne mažiau kaip pT1c(ne mažiau kaip 1,8 cm) pN(sn)0 (0/3 l/m). LVI2(limfovaskulinė naviko invazija, pavienėse smulkiose struktūrose).  Her2 imunohistocheminė reakcija ribinė (2+).     Nustatyta HER2 geno amplifikacija navike (žr. molekulinio tyrimo aprašymą).
answer:  3

 24%|██▍       | 160/661 [00:47<02:30,  3.32it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6 mm);  (G2; 6 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 8%.
answer:  2

 24%|██▍       | 161/661 [00:47<02:31,  3.29it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G1 ; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: vidutinė (++) reakcija, 30% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija paribinė (2+); nustatyta HER2 geno amplifikacija (žr. molekulinio tyrimo aprašymą).  Ki67: proliferacinis indeksas 10%. Karštame taške 30%.  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas).
answer:  1

 25%|██▍       | 162/661 [00:48<02:37,  3.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Reaktyvi limfadenopatija (3 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma, TNM (Nr.1-Nr.2): pT2(~4 cm, mikroskopiškai) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės invazijos nėra). R0(radikalus naviko pašalinimas).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5%.
answer:  1

 25%|██▍       | 163/661 [00:48<02:33,  3.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Limfmazgiai (2 l/m) be naviko židinių; pN0(sn).  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2(28mm).
answer:  2

 25%|██▍       | 164/661 [00:48<02:41,  3.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.
answer:  1

 25%|██▍       | 165/661 [00:49<02:53,  2.86it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Kairė  N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ar vidutinis branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.  ------------------  Dešinė  N2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.
answer:  1

 25%|██▌       | 166/661 [00:49<02:47,  2.96it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma (8,3 mm židinys), TNM: pT1b(8,3 mm naviko židinys), LVI0(neidentifikuota), pN0(sn)(0/2 l/m). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).  Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai.
answer:  3

 25%|██▌       | 167/661 [00:49<02:56,  2.80it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  2(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  3(Extra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(16 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).
answer:  1

 25%|██▌       | 168/661 [00:50<02:56,  2.79it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTAS ATSAKYMAS, ATLIKTI PAPILDOMI HISTOLOGINIAI PJŪVIAI IR IHC REAKCIJOS:  šalia didžiausio DCIS židinio išryškėjo 2,3mm invazijos židinys: gerai diferencijuota (G1; 4 balai pagal Nottinghma) invazinė duktalinė karcinoma; pT1a.  --------------------  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma; pT1c(m) (du naviko židiniai 2,7mm ir 13mm).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ mažiau 1%.  Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS; kribriforminio ir solidinio tipo; trys židiniai 5,5mm; 10mm ir 17mm).
answer:  1

 26%|██▌       | 169/661 [00:50<03:44,  2.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties audinys.  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (5 l/m).    4. Krūties (kairės) invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(13 mm navikas) pN0(sn)(0/5 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija, navikas nuo sektoriaus rezekcijos krašto nutolęs 0,1 mm).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 20%.
answer:  1

 26%|██▌       | 170/661 [00:51<03:43,  2.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a). Krūties paprasta intraduktalinė hiperplazija, stulpinis epitelio pokytis.   2(1b). Krūties fibrocistiniai pokyčiai.   3(1c). Krūties fibrocistiniai pokyčiai.   4(2). Krūties duktalinės karcinomos metastazė (1-ame iš 5 l/m, metastazė 5,5 mm).  5. Krūties invazyvi vidutiniškai diferencijuota (G2/ 7 b. pagal Nottingham) duktalinė karcinoma,   pT1c (15 mm) pN1a(sn) (1 iš 5 l/m; metastazė 5,5 mm); LVI2 (limfovaskulinė naviko invazija smulkiose kraujagyslėse/ limfagyslėse).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-96091, žr. pastabą.   6. Krūties fibrocistiniai pokyčiai.   7. Krūties audinys be patologinių pokyčių.
answer:  1

 26%|██▌       | 171/661 [00:51<03:13,  2.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Kairė  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 20-25%.  ------  Dešinė  N2: Krūties fibrocistiniai pokyčiai, paprastoji intraduktalinė epitelio hiperplazija.
answer:  2

 26%|██▌       | 172/661 [00:51<02:49,  2.88it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%, vietomis iki 15%.
answer:  1

 26%|██▌       | 173/661 [00:52<02:32,  3.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.
answer:  1

 26%|██▋       | 174/661 [00:52<02:23,  3.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 35%.
answer:  3

 26%|██▋       | 175/661 [00:52<02:18,  3.50it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (invazinis navikas 5,2mm).  Aukšto laipsnio intraduktalinė karcinoma (DCIS/DIN3; solidinis ir komedo tipas; pakitimai 10mm plote aplink invazinį naviką).  N2ab: Krūties audinys be naviko, paprasta intraduktalinė epitelio hiperplazija.  N3: Limfmazgiai (2 l/m) be naviko; pN0(sn).
answer:  3

 27%|██▋       | 176/661 [00:52<02:14,  3.60it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Krūties duktalinės karcinomos metastazė limfmazgyje.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%, vietomis iki 20%.
answer:  3

 27%|██▋       | 177/661 [00:53<02:14,  3.60it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties lobulinė karcinoma (2,5 mm židinys). Lobulinė karcinoma in situ (LCIS).  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (3 l/m).  4. Riebalinis audinys.  5. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1c(16 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).  HER2 imuninė reakcija: neigiama (1+).   Lobulinė karcinoma in situ (LCIS).  Reaktyvi limfadenopatija (1 intramamarinis l/m).
answer:  1

 27%|██▋       | 178/661 [00:53<02:08,  3.77it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) metaplastinė (matriksą produkuojanti) krūties karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 90%.
answer:  3

 27%|██▋       | 179/661 [00:53<02:06,  3.82it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 8 mm);  (G2; 7 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 80% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 20%.
answer:  2

 27%|██▋       | 180/661 [00:53<02:01,  3.95it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 40%.
answer:  3

 27%|██▋       | 181/661 [00:54<01:59,  4.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%.
answer:  3

 28%|██▊       | 182/661 [00:54<02:08,  3.74it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Paruošti pjūviai Prosigna.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Riebalinis - fibrozinis audinys.   3. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(m)(7 mm ir 6 židiniai ~ 1mm) NX(l/m nešalinti) LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis, komedo tipai), židiniai 4,5 cm plote. R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.
answer:  3

 28%|██▊       | 183/661 [00:54<02:06,  3.78it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.
answer:  2

 28%|██▊       | 184/661 [00:54<02:04,  3.83it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.
answer:  1

 28%|██▊       | 185/661 [00:55<02:04,  3.81it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20%, vietomis iki 35%.
answer:  2

 28%|██▊       | 186/661 [00:55<02:02,  3.87it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) galimai lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 1%.
answer:  1

 28%|██▊       | 187/661 [00:55<02:04,  3.80it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė karcinoma, galimai metaplastinė.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 25%, vietomis iki 40%.
answer:  3

 28%|██▊       | 188/661 [00:55<02:05,  3.75it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.
answer:  2

 29%|██▊       | 189/661 [00:56<02:07,  3.70it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham); pT2 (24mm).  N2ab: Krūties ir riebalinis audinys be naviko.
answer:  1

 29%|██▊       | 190/661 [00:56<02:09,  3.65it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 5% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+, HER2 geno amplifikacija nenustatyta.  Ki67+ 20%.
answer:  3

 29%|██▉       | 191/661 [00:56<02:06,  3.73it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 8%.
answer:  1

 29%|██▉       | 192/661 [00:57<02:00,  3.88it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 12% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.
answer:  1

 29%|██▉       | 193/661 [00:57<02:08,  3.64it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a - pagrindinis navikas).  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma;   pT1c(16 mm) pLVI-0 pR0.   Imunofenotipas (nustatytas priešoperaciniame biopsijos tyrime):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 5%.  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).     2(1b - markiruotas navikas).   Krūties fibrocistiniai pokyčiai: atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė.    3(2a - kraštai). Riebalinis audinys be patologinių pokyčių.  4(2b - kraštai). Riebalinis audinys be patologinių pokyčių.    5(sarginis limfmazgis). Limfmazgiai (2) be patologinių pokyčių; pN(sn)0.
answer:  1

 29%|██▉       | 194/661 [00:57<02:19,  3.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). "K. pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).   2. "K. krūtis su speneliu": krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1a(m) (naviko židiniai: I - 4,5 mm; II - 1,5 mm; III - 1,5 mm; IV - 1 mm) N0 (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%.    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis ir komedo tipai; pokyčių zona ~25 mm skersmens).     Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Incidentinė krūties fibroadenoma (0,6 mm).     3. "Deš. krūties liauka po NSM": ryški krūties audinio fibrozė (g.b. post-terapiniai pokyčiai).   SUMINIS TNM: ypT0 (vitalinio naviko neidentifikuota) N0 (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Krūties fibrocistiniai pokyčiai (sklerozuojanti ir mikroglandulinė adenozė).
answer:  3

 30%|██▉       | 195/661 [00:58<02:17,  3.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT(m)1c(3 naviko židiniai: 13 mm, 4,7 mm ir 3 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). II naviko struktūros <0,1 mm nuo rezekcijos krašto.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.
answer:  1

 30%|██▉       | 196/661 [00:58<02:08,  3.61it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 1-2%.
answer:  1

 30%|██▉       | 197/661 [00:58<02:08,  3.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1-2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma. SUMINIS TNM: pT2(22 mm navikas) N0(sn)(1 l/m) LVI-4 (limfovaskulinė invazija smulkiose gyslose ir venose). Radikalus pašalinimas. Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis ir kribriforminis tipai).  Imunofenotipas:  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 40%.
answer:  3

 30%|██▉       | 198/661 [00:58<02:22,  3.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). DEŠINĖ. Duktalinės karcinomos mikrometastazė limfmazgyje (1/4 l/m, 0,4mm). Limfovaskulinė invazija.   2(extra). KAIRĖ. Reaktyvi limfadenopatija (3 l/m).    3. DEŠINĖ. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma su daline neuroendokrinine diferenciacija, SUMINIS TNM: pT2(27 mm) pN1a(sn)(1/4 l/m, 0,4mm). LVI-2(limfovaskulinė invazija). Vidutinio žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas), gausūs židiniai iki 1 cm.    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    4. KAIRĖ. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma neuroendokrinine diferenciacija, SUMINIS TNM: pT2(m)(35 mm ir 7 mm navikai) pN0(sn)(0/3 l/m). LVI-2(limfovaskulinė invazija). Vidutinio žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas).  Židininiai fibrocistiniai pokyčiai.    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.
answer:  3

 30%|███       | 199/661 [00:59<02:25,  3.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Riebalinis audinys.  2(2b). Krūties audinys; intraduktaliniai mikrokalcifikatai.  3. Reaktyvi limfadenopatija (2 l/m).  4(1). Krūties invazyvi, gerai diferencijuota (G1; 4 balai pagal Nottingham sis) duktalinė karcinoma, pT1b(navikas - 9mm) pN0(sn)(0/2 l/m).  IHC reakcijos atliktos VPC:B23-43418 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%."  Krūties fibrocistiniai pokyčiai.
answer:  1

 30%|███       | 200/661 [00:59<02:24,  3.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai: paprastoji intraduktalinė hiperplazija.  2. Riebalinis audinys be naviko plitimo.   3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) mucininė karcinoma, TNM: pT2(navikas 48 mm), pN0(sn)(0/3 l/n), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).
answer:  3

 30%|███       | 201/661 [00:59<02:26,  3.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Paruošti pjūviai Prosigna tyrimui.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Krūties duktalinės karcinomos mikrometastazė limfmazgyje (1/3 0,4 mm).  4. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(17 mm navikas) pN1mi(sn)(1/3 l/m mikro MTS 0,4 mm) LVI-0(limfovaskulinė invazija neidentifikuota). Perineurinis plitimas. R0(navikas nuo sektoriaus rezekcijos krašto nutolęs <0,1 mm).     Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.
answer:  3

 31%|███       | 202/661 [01:00<02:25,  3.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2a). Krūties audinys.  2(N2b). Krūties audinys.  3(N3). Reaktyvi limfadenopatija (2 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,1 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės naviko invazijos nėra).    Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 12% (hot spot 15%).
answer:  1

 31%|███       | 203/661 [01:00<02:35,  2.94it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2a). Krūties fibrocistiniai pokyčiai.   2(N2b). Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, kribriforminė).   3(N3). Krūties duktalinės karcinomos metastazė limfmazgyje (1 iš 3 l/m, metastazė 1,6 mm).   4(N5a). Krūties fibrocistiniai pokyčiai, paprasta intraduktalinė hiperplazija.  5(N5b). Krūties fibrocistiniai pokyčiai, stulpinis epitelio pokytis.  6(N1). Krūties invazyvi daugiažidininė blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma,   pT1b(m) (2 naviko židiniai 6,5 mm ir 4 mm) pN1mi (1 iš 3 l/m, metastazė 1,6 mm); LVI2 (limfovaskulinė naviko invazija smulkiose limfagyslėse/ kraujagyslėse).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-17740, žr. pastabą.   Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, kribriforminė, plokščia, solidinė su comedo nekroze).   7(N4). Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS/ DIN1c - DIN2, kribriforminė ir mikropapilinė), pTis.   Intraduktalinės papilomos.   8(N6). Krūties audinio fibrozė.
answer:  1

 31%|███       | 204/661 [01:00<02:30,  3.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Intraduktalinė krūties papiloma.  N2: Krūties cista.  N3: Gerai diferencijuota (G1, 4balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.
answer:  3

 31%|███       | 205/661 [01:01<02:31,  3.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). "Kairės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT2(m) (navikai: I - 27 mm; II - 10 mm; III - 5 mm; IV - 3 mm) N0(sn) (0/3 l/m),   LVI-0 (definityvios limfovaskulinės invazijos neidentifikuota).     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties lobulinė intraepitelinė neoplazija (LCIS).  Krūties žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS: solidinis ir kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   Krūties gilusis rezekcijos kraštas be naviko.
answer:  3

 31%|███       | 206/661 [01:01<02:23,  3.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.
answer:  1

 31%|███▏      | 207/661 [01:01<02:24,  3.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 3%.
answer:  1

 31%|███▏      | 208/661 [01:02<02:46,  2.72it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTA (HER2 FISH tyrimas):  1(Extra). Krūties audinio fibrozė.  2(Extra). Krūties audinio fibrozė.  3(Extra). Duktalinės karcinomos metastazė 1/3 limfmazgyje (5,7 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(8 mm) N(sn)1a(mts 1/3 l/m; 5,7 mm), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Her2 imuninė reakcija: ribinė (2+).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, plokščia).  Krūties intraduktalinės papilomos (dalis su vidutinio laipsnio DCIS).
answer:  4

 32%|███▏      | 209/661 [01:02<03:05,  2.43it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1a (daugybiniai invazijos židiniai, didžiausias 1,5mm).  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 12%.  Krūties aukšto laipsnio intraduktalinė karcinoma (DIN3/DCIS, kribriforminis ir komedo tipas; du navikiniai židiniai - 40mm plote ir 9mm plote).  Rezkecijos kraštas be naviko.
answer:  2

 32%|███▏      | 210/661 [01:03<03:16,  2.29it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS). Krūties lobulinė karcinoma in situ (LCIS).   2. Krūties audinys.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties lobulinė karcinoma in situ (LCIS). Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija.  5. Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 12 mm), pN0(sn)(0/2 l/n), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.HER2:reakcijos nėra (0).  Žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS). Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai: paprastoji intraduktalinė hiperplazija, apokrinine metaplazija.
answer:  1

 32%|███▏      | 211/661 [01:03<03:36,  2.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Sarginiai l/m. Reaktyvi limfadenopatija (2 l/m).    2. Krūties invazinė duktalinė karcinoma,   pT1c(m) (naviko židiniai iki 10,4 mm)   pN0(sn)(2 l/m)    pLVI-0 (limfovaskulinė invazija neidentifikuota)   pR0(radikalus pašalinimas).  Diferenciacijos laipsniai navikuose:   I navike (9,6 mm) - blogai diferencijuota (G3, 9 balai pagal Nottingham),   II navike (10,4 mm) - gerai diferencijuota (G1, 3 balai pagal Nottingham),   III navike (5,4 mm) - vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham).       I naviko imunotipas nustatytas priešoperacinėje biopsijoje (B23-6714):  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 80%.    II naviko imunotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.    Lobulinė karcinoma in situ (LCIS).
answer:  1

 32%|███▏      | 212/661 [01:04<03:21,  2.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Kraštai - krūties audinys be patologinių pokyčių.  2(2b). Kraštai - krūties audinys be patologinių pokyčių.  3. Sarginiai l/m - limfmazgis (1) be patologinių pokyčių.    4. Krūties sektorius.   Invazinė duktalinė (kitaip neklasifikuojama) karcinoma;   (G1; 3 b. pgl. Nottingham sist.);   pT1b pN0 pLVI-0 pR0.  Imunotipas (priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 4%.
answer:  1

 32%|███▏      | 213/661 [01:04<03:26,  2.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 10%. Karštame taške 20%.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.    2. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 10%.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.
answer:  2

 32%|███▏      | 214/661 [01:05<03:04,  2.43it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma.   Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.   Her2 imuninės r-ja: neigiama (0).   Ki67 proliferacinis aktyvumas iki 10%.
answer:  1

 33%|███▎      | 215/661 [01:05<02:56,  2.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, pT1a(1,6 mm) NX(limfmazgiai nešalinti), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Imunofenotipas:   Estrogenų receptoriai: vidutinis branduolių nusidažymas 70% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  HER2 imuninė reakcija: neigiama (0).  Ki67: 10%.  Krūties aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DIN3/DCIS)(solidinė, kribriforminė, komedo).  DCIS struktūros siekia medialinį rezekcijos kraštą, 0,15 mm nuo poodinio rezekcijos krašto, 0,5 mm nuo giliojo krašto.
answer:  3

 33%|███▎      | 216/661 [01:05<02:55,  2.54it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a). Viršutinis kraštas. Krūties audinys be patologinių pokyčių.    2(1b). Apatinis kraštas. Krūties audinys be patologinių pokyčių.    3(2). Deš. pažasties sarginiai limfmazgiai. Reaktyvi limfadenopatija (3 l/m).     4(3). Deš. krūties sektorius. Krūties invazyvi duktalinė karcinoma,    vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą),   pT1c (13 mm navikas)   pN0(sn)(3 l/m)   pLVI-0 (limfovaskulinė invazija neidentifikuota)   pR0(radikalus pašalinimas).   Naviko imunotipas nustatytas biopsijoje (B23-15090):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.    Krūties fibrocistiniai pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).
answer:  1

 33%|███▎      | 217/661 [01:06<02:42,  2.73it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė tubulinė karcinoma;   pT1b(10 mm) pLVI-0 pN0(0/4) pR0.  Naviko imunotipas (priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 98% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 4%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).    2. Riebalinio audinio fragmentas be patologinių pokyčių.  3. Riebalinio audinio fragmentas be patologinių pokyčių.  4. Limfmazgiai(3) be patologinių pokyčių.  5. Riebalinio audinio fragmentas be patologinių pokyčių.
answer:  1

 33%|███▎      | 218/661 [01:06<02:33,  2.88it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Paruošti pjūviai Prosigna.  1. Krūties invazyvi blogai diferencijuota (G3, 8. pagal Nottingham) multižidininė karcinoma: mucininė karcinoma (6,5 mm, 13 mm židiniai) ir mišri mucininė-duktalinė karcinoma (20,5 mm židinys).  SUMINIS TNM: pT2(m)(6,5 mm, 13 mm, 20,5 mm navikai) pN0(sn)(0/3) LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis, komedo tipai). R0(radikali rezekcija).    Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 75% naviko ląstelių.  HER2: neigiama (1+)  Ki67: proliferacinis indeksas 15%.    2. Sarginiai limfmazgiai. Reaktyvi limfadenopatija (3 l/m).
answer:  3

 33%|███▎      | 219/661 [01:06<02:30,  2.93it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Reaktyvi limfadenopatija (3 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mišri duktalinė - mucininė karcinoma, SUMINIS TNM: pT3(55 mm navikas) pN(sn)(0/3 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis tipas).    Imunofenotipas(biopsijoje):   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 5% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.
answer:  3

 33%|███▎      | 220/661 [01:07<02:27,  2.98it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2a). Krūties audinys.  2(N2b). Krūties audinys.  3(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(m) (1,4 cm, 0,3 cm ir 0,3 cm židiniai) pN1a(2/16 l/m, mts 0,2 cm ir 0,7 cm; ekstranodalinis plitimas). LVI2(limfovaskulinė naviko invazija, smulkiose struktūrose).  4(N3). Duktalinės adenokarcinomos metastazės 2/16 limfmazgiuose (mts 0,2 cm ir 0,7 cm; ekstranodalinis plitimas).
answer:  3

 33%|███▎      | 221/661 [01:07<02:51,  2.57it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.
answer:  1

 34%|███▎      | 222/661 [01:08<03:05,  2.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Papildyta HER2 FISH.  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+).  Ki67 proliferacinis aktyvumas 3%.  HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).
answer:  3

 34%|███▎      | 223/661 [01:08<02:52,  2.54it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma su mikropapiliniu komponentu; pT2(m) (7 navikiniai židiniai nuo 6mm iki 33mm); pN3a (16 iš 20 l/m).
answer:  2

 34%|███▍      | 224/661 [01:08<02:39,  2.74it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma.   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%. Karštame taške 20%.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.    2. Krūties fibrocistiniai pokyčiai, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).
answer:  2

 34%|███▍      | 225/661 [01:09<02:31,  2.87it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai: paprasta epitelio hiperplazija, apokrininė epitelio metaplazija.   2. Krūties lobulinė karcinoma in situ (LCIS).  3. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) lobulinė karcinoma, TNM: pT2(23 mm naviko židinys), LVI0(neidentifikuota), pN0(0/15 l/m). Krūties lobulinė karcinoma in situ (LCIS). HER2:reakcijos nėra (0). Progesterono receptoriai: reakcijos nėra. Fibrocistiniai krūties pokyčiai.  4. Reaktyvi limfadenopatija (15 l/m).  5. Krūties lobulinė karcinoma in situ (LCIS).
answer:  3

 34%|███▍      | 226/661 [01:09<02:33,  2.83it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai":   dažais žymėtame krašte - fibrozuotas riebalinis audinys; be naviko.   Planinio tyrimo metu tirtoje, dažais nežymėtoje medžiagoje - krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: kribriforminis tipas; 3,2 mm židinys).  2(2b, ekstra). "Kraštai":   dažais žymėtame krašte - fibrozuotas riebalinis audinys; be naviko.  Planinio tyrimo metu tirtoje, dažais nežymėtoje medžiagoje - fibrozuotas krūties audinys su koaguliaciniais artefaktais.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (1 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (du naviko židiniai: I - 9 mm; II - 4 mm) N0(sn) (0/1 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.     Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   DCIS komponentas nuo sektoriaus rezekcijos krašto nutolęs - 0,1 mm.
answer:  3

 34%|███▍      | 227/661 [01:09<02:20,  3.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G1; 5 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 10% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.
answer:  1

 34%|███▍      | 228/661 [01:09<02:24,  2.99it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Atsakymas papildytas HER2 FISH tyrimo rezultatu (HER2 geno amplifikacija nenustatyta):   1(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).    2(ekstra). "Kraštai": krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis tipas).   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 19,5 mm) N0(sn) (0/3 l/m),    LVI-2 (limfovaskulinė invazija smulkiose šakose).   Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).   5. "Papildomas kraštas": fibrozuotas krūties audinys; be naviko.
answer:  1

 35%|███▍      | 229/661 [01:10<02:19,  3.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Reaktyvi limfadenopatija (4 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.2): pT1b(m) (0,8 cm ir 0,9 cm naviko židiniai) pN(sn)0 (0/4 l/m). LVI0(limfovaskulinės naviko invazijos nėra). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribrozinis tipas).  ---  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: Neigamas (imunohistocheminė reakcija ribinė (2+), HER2 geno amplifikacija (FISH) nenustatyta).  Ki67: 20%.
answer:  1

 35%|███▍      | 230/661 [01:10<02:08,  3.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%, vietomis iki 80%.
answer:  3

 35%|███▍      | 231/661 [01:10<02:04,  3.46it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a). Riebalinis audinys.  2(1b). Krūties audinys.  3(2). Reaktyvi limfadenopatija (2 l/m).  4(3). Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1b(navikas 6,25 mm), pN0(sn)(0/2 l/m), LVI0. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).   HER2: reakcija neigiama (1+).
answer:  1

 35%|███▌      | 232/661 [01:11<02:08,  3.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2a, ekstra) kraštai. Krūties audinys su židinine apokrinine metaplazija ir įprastine duktaline hiperplazija.     2(N2b, ekstra) kraštai. Krūties audinys be patologinių pokyčių.     3(N3, ekstra) dešinės pažasties sarginis limfmazgis. Reaktyvi limfadenopatija (2 l/m).    4(N1). Dešinės krūties plotas.  Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham sistemą) lobulinė karcinoma, suminis TNM:   pT3 (52 mm navikas)    pN0(sn)(0/2 l/m)    pLVI-0(limfovaskulinė invazija neidentifikuota)    pR0(radikalus pašalinimas).   Imunotipas priešoperaciname biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.    Krūties lobulinė karcinoma in situ (LCIS).
answer:  4

 35%|███▌      | 233/661 [01:11<02:20,  3.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties (kairiosios) invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(25 mm) N(sn)1mi(mikromts 1/4 l/m), LVI-2(limfovaskulinė invazija).   Imunofenotipas:   Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  HER2 imuninė reakcija: neigiama (1+).  Ki67: 5%.  2(Extra)(Deš. pažasties sarginiai l/m). Reaktyvi limfadenopatija (2 l/m).  3(Extra)(Kair. pažasties sarginiai l/m). Duktalinės karcinomos mikrometastazė 1/4 limfmazgyje (0,45 mm).   4. Krūties (dešiniosios) invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT(m)2(2 naviko židiniai: 23 mm ir 24 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).  5. Lobulinė karcinoma in situ (LCIS). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).
answer:  3

 35%|███▌      | 234/661 [01:11<02:10,  3.26it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 20%.
answer:  3

 36%|███▌      | 235/661 [01:12<02:07,  3.34it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (1 l/m).  4(1). Krūties invazyvi, blogai diferencijuota (G3; 9 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 28mm) pN0(sn)(0/1 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-3406:  "Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 35%, vietomis iki 60%."
answer:  3

 36%|███▌      | 236/661 [01:12<02:08,  3.30it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties lobulinės karcinomos metastazė (1/5 l/m 5,5 mm).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(m)(40 mm, 2,3 mm, 1,2 mm navikai) pN1a(sn) (1/5 l/m MTS 5,5 mm) LVI-0(limfovaskulinė invazija neidentifikuota). R0(navikas nuo rez. krašto nutolęs 1,3 mm). Lobulinė karcinoma in situ.    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.
answer:  1

 36%|███▌      | 237/661 [01:12<02:05,  3.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties fibrocistiniai pokyčiai.  2(Extra). Krūties fibrocistiniai pokyčiai. Mikrokalcifikatai.  3(Extra). Krūties duktalinės karcinomos metastazės 2/5 l/m (4,2 mm ir 1,3 mm).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(22 mm) N(sn)1a(mts 2/5 l/m: 4,2 mm ir 1,3 mm), LVI-2(limfovaskulinė invazija).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DIN3/DCIS)(solidinė, kribriforminė).
answer:  4

 36%|███▌      | 238/661 [01:12<01:59,  3.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Limfmazgio bioptatas su duktalinės karcinomos metastaze.  N2: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.
answer:  1

 36%|███▌      | 239/661 [01:13<01:54,  3.69it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.
answer:  1

 36%|███▋      | 240/661 [01:13<02:05,  3.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1.(1a) Fibrocistiniai krūties pokyčiai.  2.(1b) Fibrocistiniai krūties pokyčiai.  3. Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(m)(du naviko židiniai - 9mm ir 25mm) pN1mi(1/21 l/m; iki 1,09mm); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).  IHC, FISH reakcijos atliktos VPC:B23-714 tyrime:  "Ki67: proliferacinis indeksas 55%.  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Išoriniai IHC:  Estrogenų receptorių raišką teigiama (stipri raiška 100 proc. naviko ląstelių branduoliuose).  Progesteronų receptorių raišką teigiama (vidutinė raiška 50 proc. naviko ląstelių branduoliuose).  HER2 raiška paribinė (2+: silpna cirkuliari raiška 30 proc. naviko ląstelių membranoje)."  Vidutinio laipsnio krūties intraduktalinė karcinoma (DCIS; solidinis tipas; -komedo tipo nekrozės). Fibrocistiniai krūties pokyčiai. Krūties odos seborėjinės keratozės.  4. Duktalinės karcinomos mikrometastazė limfmazgyje (1/19 l/m; iki 1,09mm).  5. Reaktyvi limfadenopatija (2 l/m).
answer:  3

 36%|███▋      | 241/661 [01:13<02:04,  3.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Kvadrantas. Krūties vidutiniškai diferencijuota (G2, 7b. pagal Nottingham skalę) invazyvi duktalinė karcinoma, TNM: pT1b(8 mm), LVI-0 (limfovaskulinė invazija neidentifikuota), R0 (radikali rezekcija).  Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 20%.    2. Kraštai. Krūties audinys. Be naviko.  3. Kraštai. Krūties audinys. Be naviko.  4. Kraštai. Krūties audinio fibrozė. Be naviko.  5. Sarginis limfmazgis. Riebalinio-fibrozinio audinio fragmentas. Žr. pastabą.
answer:  1

 37%|███▋      | 242/661 [01:14<02:27,  2.84it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma. Žemo laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 95% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 30% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.
answer:  1

 37%|███▋      | 243/661 [01:15<03:23,  2.06it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi duktalinė karcinoma (ne mažiau kaip gerai diferencijuota / G1 / 5 balai pagal Nottingham).     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 3%.
answer:  1

 37%|███▋      | 244/661 [01:15<03:40,  1.89it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2 (40mm); pN2a (4 iš 10 l/m).
answer:  3

 37%|███▋      | 245/661 [01:16<03:42,  1.87it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35-40%.
answer:  3

 37%|███▋      | 246/661 [01:16<03:58,  1.74it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PATIKSLINTA DIAGNOZĖ:  1. Fibrocistiniai krūties pokyčiai.  2. Krūties lobulinė karcinoma in situ (LCIS).  3. Reaktyvi limfadenopatija (2 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) lobulinė karcinoma, TNM: pT1b(9 mm naviko židinys), LVI0(neidentifikuota), pN0(sn)(0/2 l/m). Krūties lobulinė karcinoma in situ (LCIS). HER2: reakcija neigiama (1+). Progesterono receptoriai: reakcijos nėra.
answer:  1

 37%|███▋      | 247/661 [01:17<03:54,  1.77it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PATIKSLINTA (žr. pastabą):   Invazinė lobulinė karcinoma (mažiausiai iki 11 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 3%.
answer:  1

 38%|███▊      | 248/661 [01:17<03:15,  2.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 4 mm);  (G1; 3 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 4%.
answer:  1

 38%|███▊      | 249/661 [01:18<02:59,  2.29it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTAS ATSAKYMAS:   1(2a, ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties-riebalinis audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos metastazės dviejuose limfmazgiuose (mts 2/3 l/m; iki ~ 19 mm skersmens; su ekstranodaliniu plitimu).     4(1). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (mikroskopiškai navikas 15 mm, žr. pastabą) N1a(sn) (mts 2/3 l/m; iki ~19 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+).  Molekuliniai tyrimai:  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: solidinis, kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Navikas nuo sektoriaus rezekcijos krašto nutolęs 1,7 mm.
answer:  4

 38%|███▊      | 250/661 [01:18<02:40,  2.57it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Satelitas dešiniojoje krūtyje 6-7 val. vidurinėje: krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.  2. Dešiniojoje krūtyje ties 9 val. vidurinėje dalyje: krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.  3. Intramamarinis l/m dešiniojoje krūtyje ties 10-11 val. krūties duktalinės karcinomos metastazės.    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.   Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 15%.
answer:  3

 38%|███▊      | 251/661 [01:18<02:21,  2.89it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė lobulinė karcinoma (mažiausiai iki 9 mm);  (G1; 5 b. pgl. Nottingham sist.) 1-me stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.
answer:  1

 38%|███▊      | 252/661 [01:18<02:09,  3.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT2(28 mm) pLVI-0 pN0(0/28) pR0.  Naviko imunotipas (priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 75% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67+ 8%.
answer:  1

 38%|███▊      | 253/661 [01:19<02:14,  3.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties lobulinė karcinoma in situ (LCIS).   2. Krūties audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mucininė karcinoma, TNM: pT2(navikas 22 mm), pLVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).  HER2:reakcijos nėra (0).
answer:  3

 38%|███▊      | 254/661 [01:19<02:25,  2.80it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė lobulinė karcinoma (mažiausiai iki 11 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: silpna (+) reakcija, 5% naviko ląstelių.  HER2: reakcija paribinė (2+). Dėl blogos mėginio kokybės ir nepakankamo ląstelių kiekio mėginyje, HER2 amplifikacijos FISH tyrimas nevertintinas.  Ki67: proliferacinis indeksas 15%.
answer:  2

 39%|███▊      | 255/661 [01:19<02:26,  2.76it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Limfmazgiai(2) be karcinomos plitimo. Žr. pastabą.   2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma,   pT1c (16 mm) pN0(sn) (0/2 l/m); LVI2 (limfovaskulinė naviko invazija smulkiose limfagyslėse/ kraujagyslėse). Karcinomos imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-6112, žr. pastabą.   Krūties lobulinė karcinoma in situ (LCIS).   Stulpinis epitelio pokytis su epitelio hiperplazija. Krūties intraduktalinė papiloma.
answer:  3

 39%|███▊      | 256/661 [01:20<02:36,  2.59it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a). Riebalinio audinio fragmentas be patologijos.  2(1b). Fibrocistiniai krūties pokyčiai.  3(2). Krūties duktalinės karcinomos mikrometastazė viename limfmazgyje (1/1 l/m, 1,1 mm skersmens).  4(3). Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma, TNM: pT1b(navikas 8,25 mm), pN1mi(1 l/m su mikrometastaze 1,1 mm), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2: reakcija neigiama (1+).  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).
answer:  4

 39%|███▉      | 257/661 [01:20<02:55,  2.30it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Krūties lobulinė karcinoma in situ (LCIS) ir fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija. Mikrokalcifikatai.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(8 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).   Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija. Mikrokalcifikatai.
answer:  1

 39%|███▉      | 258/661 [01:21<02:49,  2.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.
answer:  3

 39%|███▉      | 259/661 [01:21<02:46,  2.42it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Reaktyvi limfadenopatija (2 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma (su minimalia mucinine diferenciacija), SUMINIS TNM: pT(m)1c(2 naviko židiniai: 19 mm ir 7 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties išplitusi aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DIN3/DCIS)(solidinė, kribriforminė, komedo) (4 židiniai).  Krūties intraduktalinės papilomos.
answer:  3

 39%|███▉      | 260/661 [01:22<02:31,  2.65it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.
answer:  1

 39%|███▉      | 261/661 [01:22<02:35,  2.57it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1( pjūvio kraštai). Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.     2( pjūvio kraštai). Įprastinė duktalinė hiperplazija. Naviko plitimo nėra.     3(sarginiai limfmazgiai). Reaktyvi limfadenopatija (1 l/m).     4(Krūties sektorius). Krūties invazyvi gerai diferencijuota (G1, 4 balai pagal Nottingham) duktalinė karcinoma,   pT1a(m)(daugybiniai invazijos židiniai iki 3,3 mm mikroskopiškai)   pN0(sn)(1 l/m)    pLVI-0 (limfovaskulinė invazija neidentifikuota).   Naviko imunotipas:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 40% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 8%.    Žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1, kribriforminis ir papilinis piešinys; apie 30 mm).   DCIS struktūros siekia sektoriaus rezekcijos kraštą, invazijos židiniai nuo sektoriaus rezekcijos krašto nutolę bent 4,4 mm atstumu.  DCIS imunotipas:   Estrogenų receptoriai: stipri/vidutinė (+++/++) reakcija, 100% DCIS ląstelių branduoliuose.  Progesterono receptoriai: stipri (+++) reakcija, 30% naviko ląstelių branduoliuose.
answer:  3

 40%|███▉      | 262/661 [01:22<02:19,  2.87it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė lobulinė karcinoma (mažiausiai iki 10 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.
answer:  1

 40%|███▉      | 263/661 [01:23<02:15,  2.94it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Riebalinis (krūties) audinys.  2(2b). Riebalinis (krūties) audinys.  3(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,9 cm) pN(sn)1a (2/5 l/m, mts 0,3 cm ir 1,7 cm; ekstranodalinis plitimas). LVI2(limfovaskulinė naviko invazija). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribriforminis, komedo tipas).  4(3). Duktalinės adenokarcinomos metastazės 2/5 l/m (mts 0,3 cm ir 1,7 cm; ekstranodalinis plitimas).     Ankstesnio/pirminio naviko tyrimo (B23-17508) duomenys  Estrogenų receptoriai: vidutinė (++) reakcija, 30% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: imunohistocheminė reakcija ribinė (2+). Nustatyta HER2 geno amplifikacija (FISH).  Ki67: proliferacinis indeksas 10%. Karštame taške 30%.
answer:  3

 40%|███▉      | 264/661 [01:23<02:06,  3.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G2; 7 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.    Vidutinio laipsnio intraduktalinė neoplazija (DCIS/DIN2).
answer:  2

 40%|████      | 265/661 [01:23<02:04,  3.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 15 mm);  (G1; 5 b. pgl. Nottingham sist.) 1-me stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 5%.
answer:  1

 40%|████      | 266/661 [01:24<02:13,  2.96it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(3, ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė, židininė fibrozė (3 l/m).   2(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.    3(2b, ekstra). "Kraštai": krūties lobulinė intraepitelinė neoplazija (LCIS). Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM:   pT1c (navikas 17 mm) N0(sn) (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Intraduktalinis karcinomos plitimas (kanaliukų kancerizacija).  Imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.   Progesterono receptoriai: vidutinė-stipri (++/+++) reakcija, 60% naviko ląstelių.   HER2: reakcija neigiama (1+).   Ki67: proliferacinis indeksas ~5%.   Krūties lobulinė intraepitelinė neoplazija (LCIS; konvencinė ir pleomorfinė).  Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Invazyvus navikas nuo artimiausio krūties sektoriaus rezekcijos krašto nutolęs - 0,7 mm;   konvencinis LCIS koaguliacijos zonose.   5(4). "Papildomas kraštas": fibrozuotas riebalinis audinys; be naviko.
answer:  4

 40%|████      | 267/661 [01:24<02:07,  3.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 6%.  Žemo laipsnio intraduktalinė karcinoma (DCI; DIN1, kribriforminis tipas).
answer:  1

 41%|████      | 268/661 [01:24<02:07,  3.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Atlikti pjūviai Prosigna.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(m)(2 židiniai 17 mm, 7 mm) pN0(sn)(0/3 l/m) LVI-2(limfovaskulinė invazija).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.
answer:  1

 41%|████      | 269/661 [01:24<02:05,  3.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties intraduktalinė papiloma.  2. Krūties stulpinis epitelio pokytis.   3. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham s.) duktalinė karcinoma su mikropapilinės karcinomos komponentu (~10%), suminis Nr. 1 - 4 pTNM:   pT2 (22 mm) pN0(sn) (0/1 l/m); LVI0 (limfovaskulinės naviko invazijos patikimai neidentifikuota).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-9611, žr. pastabą.
answer:  3

 41%|████      | 270/661 [01:25<01:59,  3.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.
answer:  1

 41%|████      | 271/661 [01:25<02:03,  3.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Reaktyvi limfadenopatija (3 l/m).  2(ekstra). Riebalinis - fibrozinis audinys.  3(ekstra). Riebalinis - fibrozinis audinys.  4. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(32 mm navikas) pN1a(sn)(1/4 l/m 8 mm) LVI-2(limfovaskulinė invazija). Perineurinis. R0(radikali rezekcija).  5. Duktalinės karcinomos metastazė intramamariniame limfmazgyje (8 mm).    Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Androgenų receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 70%.
answer:  1

 41%|████      | 272/661 [01:25<01:59,  3.26it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 8%.
answer:  2

 41%|████▏     | 273/661 [01:26<01:53,  3.41it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 15%.
answer:  2

 41%|████▏     | 274/661 [01:26<01:59,  3.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTA  1(N2a). Krūties fibrocistiniai pokyčiai.  2(N2b). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (3 l/m).  4(N1). Krūties invazyvi duktalinė adenokarcinoma (gerai diferencijuota / G1 / 5 balai pagal Nottingham), TNM (Nr.1-Nr.4): pT1c(m) (ne mažiau 3 židinių: 1,6 cm, 0,5 cm, 0,4 cm) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės naviko invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 6%.
answer:  1

 42%|████▏     | 275/661 [01:26<02:03,  3.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a)  kraštai - krūties audinys be pokyčių.  2(2b) kraštai - krūties audinys be pokyčių.  3(2) kairės pažasties sarginis limfmazgis: karcinomos plitimas iki 12 mm 2-se iš 3 limfmazgiuose.  4(1) kairės krūties kvadrantas. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT1c pN1a pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 20%.    Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS; kribriforminis tipas; 0,5 mm nuo operacinio krašto).
answer:  1

 42%|████▏     | 276/661 [01:27<01:57,  3.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Limfmazgio bioptatai be naviko metastazių.  N2: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 20-25%.
answer:  3

 42%|████▏     | 277/661 [01:27<01:55,  3.31it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties audinys.  2. Krūties audinys.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 15 mm), pN0(sn)(0/2 l/n), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Fibrocistiniai krūties pokyčiai.  Dermalinis nevocitinis nevus.
answer:  1

 42%|████▏     | 278/661 [01:27<01:57,  3.25it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/4 l/m, 4,75 mm).  4. Krūties invazyvi blogai diferencijuota (G3; 9 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT2(navikas 31 mm), pN1a(1/4 l/m, metastazė iki 4,75 mm), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.
answer:  4

 42%|████▏     | 279/661 [01:28<01:58,  3.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties audinys be patologinių pokyčių.  2. Krūties intraduktalinė papiloma.   3. Reaktyvi limfadenopatija (2 l/m).   4. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma,   pT1c (14 mm) pN0(sn) (0/2 l/m); LVI0 (limfovaskulinės naviko invazijos nenustatyta).   Naviko imunofenotipas nustatytas ankstesnėje biopsijoje VPC Nr. B23-26741, žr. pastabą.   Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS, kribriforminė).   Adenozė.    5. Krūties audinys be patologinių pokyčių.
answer:  1

 42%|████▏     | 280/661 [01:28<01:54,  3.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 3%.
answer:  1

 43%|████▎     | 281/661 [01:28<01:58,  3.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/2 l/m, 2,5 mm).  2. Krūties invazyvi mišri blogai diferencijuota (G3; 9 b. pgl. Nottingham) lobulinė (75%) ir duktalinė karcinoma (25%), suminis TNM: pT2(m)(navikai 44 mm ir 21 mm), pN1a(sn)(1/2 l/m), LVI2(limfovaskulinis plitimas). II-sis naviko židinys, plinta koaguliuoatme rezekcijos krašte, ties skersaruožiu raumeniu. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).   Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai. Intraduktalinė krūties papiloma.
answer:  3

 43%|████▎     | 282/661 [01:28<01:57,  3.23it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl. Nottingham) krūties invazinė duktalinė karcinoma  pT3 pN1a pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.
answer:  1

 43%|████▎     | 283/661 [01:29<01:52,  3.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.
answer:  1

 43%|████▎     | 284/661 [01:29<01:48,  3.49it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 55%.
answer:  3

 43%|████▎     | 285/661 [01:29<01:48,  3.46it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1-2: Krūties audinys be naviko.  N3: Limfmazgiai be naviko (2 l/m); pN0(sn).  N4: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c (13mm).
answer:  1

 43%|████▎     | 286/661 [01:30<01:45,  3.56it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.
answer:  1

 43%|████▎     | 287/661 [01:30<01:43,  3.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%.
answer:  1

 44%|████▎     | 288/661 [01:30<01:49,  3.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 6%.  N2a: Žemos laipsnio intraduktalinė krūties karcinoma (DCIS/DIN1; 4mm židinys; mikropapilinis tipas).  N2b: Normalios struktūros krūties audinys.
answer:  1

 44%|████▎     | 289/661 [01:30<01:55,  3.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties invazyvi adenoidinė cistinė karcinoma (solidinis-bazaloidinis tipas) ir blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma. Žr. pastabą.  SUMINIS TNM: pT2 (2,8 cm) N0(sn)(0/1 l/m) LVI-2(limfovaskulinė invazija). Navikas nuo sektoriaus rezekcijos krašto nutolęs <0,1 mm.   Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis-kribriforminis tipas).     Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.   Her2 imuninė reakcija: neigiama (0).   Ki67 proliferacinis aktyvumas 10%, fokaliai 25%.    2. N2a kraštai - planinis tyrimas: Krūties audinys.   3. N2b kraštai - planinis tyrimas: Riebalinis fibrozinis audinys.  4. N3: kairės pažasties sarginis limfmazgis - planinis tyrimas: Reaktyvi limfadenopatija (1 l/m).
answer:  3

 44%|████▍     | 290/661 [01:31<01:53,  3.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Limfmazgio bioptatai su duktalinės karcinomos metastazėmis.   2. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 9%.
answer:  2

 44%|████▍     | 291/661 [01:31<01:50,  3.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutinio laipsnio intraduktalinė karcinoma (DCIS/DIN2, solidinis tipas).  Gerai diferencijuota invazinė duktalinė karcinoma (mikroskopinis židinys apie 0,4mm).  Estrogenų receptorių reakcija navike 100%.
answer:  2

 44%|████▍     | 292/661 [01:31<01:49,  3.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.  N2: Ryški krūties audinio fibrozė, kanaliukų atrofija, galimai sklerozuota fibroadenoma.
answer:  1

 44%|████▍     | 293/661 [01:32<01:50,  3.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 1-2%.
answer:  1

 44%|████▍     | 294/661 [01:32<01:57,  3.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20-25%.
answer:  2

 45%|████▍     | 295/661 [01:32<02:10,  2.80it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Gerai diferencijuota (G1, 4balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(16mm).  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 6%.  N2-3: Riebalinio ir krūties audinio fragmentai be naviko plitimo.
answer:  1

 45%|████▍     | 296/661 [01:33<02:25,  2.50it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai; paprasta intraduktalinė hiperplazija.  3. Fibrocistiniai krūties pokyčiai.  4. Reaktyvi limfadenopatija (1 l/m).  5. Krūties audinys.  6. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) lobulinė karcinoma, suminis tyrimo TNM: pT2(navikas - 45mm) pN0(sn)(0/1 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-44252 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  Ki67+ 8%."  Lobulinė krūties Carcinoma in situ(LCIS). Fibrocistiniai krūties pokyčiai; intraduktalinės krūties papilomos.
answer:  6

 45%|████▍     | 297/661 [01:33<02:42,  2.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Riebalinis fibrozinis audinys.  2(ekstra). Krūties audinys.  3(ekstra). Krūties karcinomos mikrometastazė limfmazgyje (microMTS 1/3 0,6 mm).    4. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) mišri duktalinė-lobulinė karcinoma, SUMINIS TNM: pT2(42 mm navikas) pN1mi(microMTS 1/3 0,6 mm). LVI-2(limfovaskulinė invazija). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 1% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+).  Ki67 proliferacinis aktyvumas 25%.  HER2 geno amplifikacija vertinta IHC kontekste, interpretuota kaip NEIGIAMA (žr. molekulinio tyrimo aprašymą ir pastabas).
answer:  3

 45%|████▌     | 298/661 [01:34<02:39,  2.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Riebalinis audinys.  2(ekstra). Riebalinis audinys.  3(ekstra). Krūties duktalinės karcinomos mikrometastazė limfmazgyje (1/3 l/m micro MTS 0,9 mm).  4. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(42 mm navikas) pN1mi(sn)(1/3 l/m microMTS 0,9 mm)LVI-4(masyvi limfovaskulinė invazija venose ir smulkiose limfagyslėse). R0(radikali rezekcija).  Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 solidinis tipas).    Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: silpna reakcija 5% naviko ląstelių.   Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 20%.
answer:  3

 45%|████▌     | 299/661 [01:34<02:53,  2.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/2 l/m, 4,75 mm, ekstranodalinis plitimas).   4. Krūties invazyvi blogai diferencijuota (G3; 8 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 19 mm), pN1a(sn)(1/2 l/m, 4,75 mm metastazė), LVI0(neidnetifikuota). Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS).  Estrogenų receptoriai: reakcijos nėra. HER2:reakcijos nėra (0). Ki67: proliferacinis indeksas 30%. Karštame taške 40%. Progesterono receptoriai: reakcijos nėra.  Androgenų receptoriai: reakcijos nėra.   Seborėjinė keratozė. Hemangioma (vyšninė angioma).
answer:  4

 45%|████▌     | 300/661 [01:35<02:39,  2.26it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Sektoriaus kraštai - krūties audinys be patologinių pokyčių.  2. Sektoriaus kraštai - krūties audinys be patologinių pokyčių.  3. Sarginiai l/m: karcinomos mikrometastazė 1-me/2 limfmazgyje; pN1mi.    4. Dešinės krūties sektorius su naviku.   Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;   pT1c pN1mi pR0.  Imunotipas (priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 40%.
answer:  3

 46%|████▌     | 301/661 [01:35<02:22,  2.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma (su mucininės diferencijacijos požymiais).  ---  Estrogenų receptoriai: stiprus(+++) branduolinis/membraninis dažymasis 100% .   Progesterono receptoriai: vidutinis(++) branduolinis dažymasis 60% .   Her2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 10%.
answer:  2

 46%|████▌     | 302/661 [01:35<02:13,  2.69it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.
answer:  1

 46%|████▌     | 303/661 [01:36<02:04,  2.89it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b(m) (53mm ir 49mm, išopėjimas).
answer:  2

 46%|████▌     | 304/661 [01:36<01:58,  3.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) karcinoma su tarpiniais lobulinės - duktalinės karcinomos požymiais.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai:  neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 1%.
answer:  1

 46%|████▌     | 305/661 [01:36<02:00,  2.96it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Riebalinis audinys.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(21 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).
answer:  3

 46%|████▋     | 306/661 [01:37<01:57,  3.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTA  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: ribinė (2+).  Ki67: 5%.  ---  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).
answer:  2

 46%|████▋     | 307/661 [01:37<01:50,  3.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Vidutiniškai diferencijuota (G2,6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  2. Vidutiniškai diferencijuota (G2,6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 98% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 7%.
answer:  2

 47%|████▋     | 308/661 [01:37<01:45,  3.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė karcinoma (su apokrinine ER-/AR+ diferenciacija ir onkocitiniu MITO+ imunofenotipu; M8401/3)    (mažiausiai iki 8,5 mm);   (G2; 7 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcijos nėra (0). HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 5%. Karštame taške 10%.
answer:  2

 47%|████▋     | 309/661 [01:37<01:40,  3.51it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (8mm navikas).  Estrogenų receptoriai: stiprus ir vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymom nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.
answer:  1

 47%|████▋     | 310/661 [01:38<01:36,  3.63it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: silpna (+) reakcija, 3% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%. Karštame taške 70%.
answer:  2

 47%|████▋     | 311/661 [01:38<01:34,  3.68it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties lobulinės karcinomos metastazės 2/3 l/m (10 mm ir 4 mm).  2. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT(m)1c(2 naviko židiniai: 11 mm ir 11 mm) pN(sn)1a(mts 2/3 l/m: 10 mm ir 4 mm), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).  Lobulinė karcinoma in situ (LCIS).
answer:  3

 47%|████▋     | 312/661 [01:38<01:31,  3.82it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.
answer:  2

 47%|████▋     | 313/661 [01:38<01:28,  3.91it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.
answer:  1

 48%|████▊     | 314/661 [01:39<01:26,  4.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2(25mm).  Aukšto laipsnio indtraduktalinė karcinoma (DCIS, komedo tipas; 7mm židinys).  N3: Limfmazgiai (3 l/m) be naviko metastazių; pN0(sn).
answer:  2

 48%|████▊     | 315/661 [01:39<01:32,  3.74it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTA (HER2 FISH TYRIMAS):  1(Extra). Krūties audinys.  2(Extra). Reaktyvi limfadenopatija (3 l/m).  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT(m)1c(2 naviko židiniai: 12 mm ir 3 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Imunofenotipas:   HER2 imuninė reakcija: ribinė (2+).  HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).  Krūties lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS) ir kolageninė sferuliozė.
answer:  3

 48%|████▊     | 316/661 [01:39<01:32,  3.72it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai.  3. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 10,5 mm), LVI0 (neidentifikuota). Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių. HER2: reakcija teigiama (3+); Ki67: proliferacinis indeksas 10%. Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių. Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS).
answer:  3

 48%|████▊     | 317/661 [01:40<01:28,  3.87it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT2(28mm).  N2ab ir N4: Krūties audinys be naviko.  N3: Limfmazgiai (9 l/m) be naviko židinių; pN0.
answer:  3

 48%|████▊     | 318/661 [01:40<01:38,  3.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a, ekstra). "Viršutinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); kalcifikatai; be naviko.   2(1b, ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija); be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": karcinomos (mikro)metastazė 1 limfmazgyje (mts 1/4 l/m; 1,45 mm skersmens).     4(3). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT2 (navikas 22 mm) N1mi(sn) (mts 1/4 l/m; 1,45 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).
answer:  1

 48%|████▊     | 319/661 [01:40<01:35,  3.59it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Po operacinės medžiagos tyrimo patikslintas naviko tipas  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.
answer:  1

 48%|████▊     | 320/661 [01:40<01:34,  3.63it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Limfmazgio bioptatai be patologinių pokyčių.  2. Krūties fibrocistiniai pokyčiai: sklerozuojanti adenozė.  3. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 12 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.
answer:  1

 49%|████▊     | 321/661 [01:41<01:29,  3.79it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) mikropapilinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: teigiama (3+).  Ki67 proliferacinis aktyvumas 10%.
answer:  2

 49%|████▊     | 322/661 [01:41<01:36,  3.50it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties audinio fibrozė.    2(ekstra). Krūties fibrocistiniai pokyčiai: įprastinė duktalinė hiperplazija, apokrininė metaplazija.    3(ekstra). Duktalinės karcinomos metastazė 1/5 limfmazgių (7 mm dydžio).     4. Krūties invazyvi gerai diferencijuota (G1, 4 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT1c (16 mm navikas)    pN1a(sn)(1/5 l/m su mts 7mm)    pLVI-0 (limfovaskulinė invazija neidentifikuota)   pR0(radikalus pašalinimas).   Naviko imunotipas nustatytas priešoperacinėje biopsijoje (nr. B23-5702):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.    Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija.
answer:  1

 49%|████▉     | 323/661 [01:41<01:32,  3.66it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma su daline mucinine diferenciacija.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 3%.
answer:  2

 49%|████▉     | 324/661 [01:41<01:29,  3.75it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties mucininė karcinoma; (G1, 5 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.
answer:  1

 49%|████▉     | 325/661 [01:42<01:57,  2.87it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai": normalios histologinės struktūros riebalinis audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.     3(1). Krūties invazyvi bent gerai diferencijuota (G1, bent 5 balai pagal Nottingham, žr. pastabą) duktalinė karcinoma,   SUMINIS TNM:   pT1a (navikas 1,35 mm), LVI-0 (limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.    Krūties žemo-aukšto laipsnio duktalinė karcinoma in situ (DIN1-3/DCIS: solidinis, kribriforminis, papilinis ir komedo tipai). Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, sklerozuojanti adenozė).   DCIS komponentas nuo sektoriaus rezekcijos krašto nutolęs - 0,35 mm.
answer:  1

 49%|████▉     | 326/661 [01:42<02:01,  2.76it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi žemo laipsnio adenoidinė cistinė karcinoma, tubulinis-trabekulinis tipas   (taikant Nottingham gradavimą, karcinoma atitinka gerai diferencijuotą; G1, 5b.).   Imunofenotipas:  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: silpna (+) reakcija, 30% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 5%.
answer:  1

 49%|████▉     | 327/661 [01:43<02:03,  2.70it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.
answer:  2

 50%|████▉     | 328/661 [01:43<02:15,  2.46it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1.(1a) Riebalinis audinys.  2.(1b) Fibrocistiniai krūties pokyčiai.  3.(2) Reaktyvi limfadenopatija (2 l/m).  4.(3) Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(m)(dauginiai naviko židiniai nuo 0,6mm iki 22mm) pN0(sn)(0/2 l/m).   IHC reakcijos atliktos VPC:B23-30662 tyrime:  "Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0)."  Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis tipas; -komedo tipo nekrozės).
answer:  1

 50%|████▉     | 329/661 [01:44<02:19,  2.39it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi duktalinė adenokarcinoma (ne mažiau kaip vidutiniškai diferencijuota / G2 / 7 balai pagal Nottingham).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).
answer:  2

 50%|████▉     | 330/661 [01:44<02:23,  2.30it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.
answer:  1

 50%|█████     | 331/661 [01:45<02:25,  2.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus ir vidutinis branduolių nusidažymas 40% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.
answer:  2

 50%|█████     | 332/661 [01:45<02:31,  2.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTA  1(2). Reaktyvi limfadenopatija (2 l/m), lipomatozė.  2(1). A) Krūties invazyvi karcinoma (galimai mikropapilinė, ne mažiau kaip vidutiniškai diferencijuota / G2 / 7 balai pagal Nottingham).  Naviko kategorizacija pagal TNM (Nr.1-Nr.2): pT1a(1,5 mm navikas) N0(sn) (0/2 l/m + 0/1 intramamarinis l/m). LVI0(limfovaskulinės invazijos nėra). R0(radikalus naviko pašalinimas).  B) Krūties aukšto laipsnio intraduktalinė karcinoma (DCIS/DIN3; mikropapilinis, kribriforminis, plokščias tipai; iki 6 cm skersmens zona).  C) Krūties fibrocistiniai pokyčiai.  D) Krūties odos arterioveninė hemangioma.  ---  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2 imunohistocheminė reakcija: teigiama (3+).  Ki67: ~10%.
answer:  1

 50%|█████     | 333/661 [01:46<03:17,  1.66it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Reaktyvi limfadenopatija (3 l/m).  2(Extra). Reaktyvi limfadenopatija (3 l/m).  3. Krūties (dešiniosios) invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(15 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).  Odos seborėjinė keratozė.  4. Krūties (kairiosios) invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(6 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: įprastinė duktalinė hiperplazija, fibroadenomatozinė hiperplazija.   Odos seborėjinė keratozė.
answer:  3

 51%|█████     | 334/661 [01:47<03:13,  1.69it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2a). Krūties žemo laipsnio duktalinės karcinoma (DCIS, kribriforminis tipas).  2(N2b). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (4 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.5): pT1c(1,5 cm) pN(sn)0 (0/4 l/m). LVI0(limfovaskulinės invazijos nėra. Krūties odos kapiliarinė hemangioma.  5(N4). Riebalinis audinys.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 10%.
answer:  1

 51%|█████     | 335/661 [01:47<03:07,  1.74it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Reaktyvi limfadenopatija (3 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) lobulinė karcinoma,   pT1b (9 mm) pN0(sn) (0/3 l/m); LVI0 (limfovaskulinės naviko invazijos neidentifikuota).   Žemo laipsnio duktalinė karcinoma in situ (DCIS, kribriforminė).   Lobulinė karcinoma in situ (LCIS).   Daugybinės intraduktalinės papilomos ir radialiniai randai.   Fibrocistiniai pokyčiai, stulpinis epitelio pokytis su apikalinės sekrecijos požymiais.   Krūties odos seborėjinė keratozė.
answer:  3

 51%|█████     | 336/661 [01:48<02:58,  1.82it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.
answer:  2

 51%|█████     | 337/661 [01:48<02:49,  1.92it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G2; 7 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    2. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 3 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se navikinio audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.
answer:  1

 51%|█████     | 338/661 [01:48<02:26,  2.20it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.
answer:  2

 51%|█████▏    | 339/661 [01:49<02:12,  2.43it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama)  karcinoma;  (G2; 6 b. pgl. Nottingham sist.);  pT2(37 mm) pLVI-2 pN1a(2/11) pR0.  Imunotipas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 20%.
answer:  3

 51%|█████▏    | 340/661 [01:49<01:58,  2.70it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.
answer:  1

 52%|█████▏    | 341/661 [01:49<01:50,  2.91it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.
answer:  1

 52%|█████▏    | 342/661 [01:50<01:41,  3.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.
answer:  1

 52%|█████▏    | 343/661 [01:50<01:40,  3.17it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(11 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).
answer:  1

 52%|█████▏    | 344/661 [01:50<01:35,  3.32it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G2; 7 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija teigiama (3+);   Ki67: proliferacinis indeksas 60%.
answer:  2

 52%|█████▏    | 345/661 [01:50<01:31,  3.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 85% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ %.
answer:  2

 52%|█████▏    | 346/661 [01:51<01:28,  3.54it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 20%.
answer:  2

 52%|█████▏    | 347/661 [01:51<01:31,  3.42it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.
answer:  1

 53%|█████▎    | 348/661 [01:51<01:44,  3.00it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Reaktyvi limfadenopatija (3 l/m).  2(Extra). Reaktyvi limfadenopatija (3 l/m).  3. Krūties (dešiniosios) invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(15 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).  Lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija, stulpinis ląstelių pokytis su apikalinės sekrecijos požymiais (CCAPSS).  Odos seborėjinė keratozė.  4. Krūties (kairiosios) invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(6 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Lobulinė karcinoma in situ (LCIS).  Krūties fibrocistiniai pokyčiai: įprastinė duktalinė hiperplazija, fibroadenomatozinė hiperplazija.   Odos seborėjinė keratozė.
answer:  3

 53%|█████▎    | 349/661 [01:52<01:38,  3.18it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.
answer:  1

 53%|█████▎    | 350/661 [01:52<01:32,  3.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6,5 mm);  (G1; 5 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 5%.
answer:  1

 53%|█████▎    | 351/661 [01:52<01:33,  3.32it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (2 l/m).  4(1). Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1b(navikas - 6mm) pN0(sn)(0/2 l/m); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-43692 tyrime:  "Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 70% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 6%."  Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis, kribriforminis tipai; -komedo tipo nekrozės).
answer:  1

 53%|█████▎    | 352/661 [01:53<01:30,  3.41it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(32 mm navikas) pNX(limfmazgiai nešalinti) LVI-3(intraveninė invazija). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35-40%.    2. Riebalinis-fibrozinis audinys.  3. Krūties audinys.
answer:  3

 53%|█████▎    | 353/661 [01:53<01:31,  3.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Kraštai. Krūties fibrocistiniai pokyčiai.  2(ekstra). Kraštai. Krūties fibrocistiniai pokyčiai.  3(ekstra). Reaktyvi limfadenopatija (7 l/m).  4. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham sistemą) duktalinė karcinoma. Suminis TNM: pT1c(15 mm), pN0 (0/7 l/m), R0(radikali rezekcija), LVI-0 (limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN23 solidinis ir kribriforminis tipas). Krūties fibrocistiniai pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).  Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35-40%.
answer:  3

 54%|█████▎    | 354/661 [01:53<01:30,  3.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a)(Extra). Krūties audinys.  2(2b)(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  3(Extra). Reaktyvi limfadenopatija (3 l/m).  4(1). Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(19 mm) N(sn)0(0/3 l/m), LVI-2(limfovaskulinė invazija).  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.
answer:  1

 54%|█████▎    | 355/661 [01:53<01:26,  3.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Papildyta HER2 FISH.  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė su apokrinine diferenciacija karcinoma.     Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Androgenų receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+).  Ki67 proliferacinis aktyvumas 3%.  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).
answer:  3

 54%|█████▍    | 356/661 [01:54<01:23,  3.63it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 7 mm);  (G1; 4 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 8%.
answer:  1

 54%|█████▍    | 357/661 [01:54<01:20,  3.77it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b (65mm, išopėjimas); pN2a (4 iš 7 l/m).
answer:  2

 54%|█████▍    | 358/661 [01:54<01:18,  3.87it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.
answer:  1

 54%|█████▍    | 359/661 [01:54<01:22,  3.68it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties audinyje du navikai:  1. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b(8mm);  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacijos FISH tyrimo rezultatas teigiamas.  Ki67+ 12%, vietomis iki 20%  2. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties lobulinė karcinoma; pT1c(20mm).  Naviko imunoprofilis biopsinėje medžiagoje B23-18396:  ER(++) 100%; PR(+) 20%; HER2(-); Ki67 mažiau 5%.  pN0 (0 iš 13 l/m).
answer:  2

 54%|█████▍    | 360/661 [01:55<01:18,  3.82it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, balai 4 pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.
answer:  1

 55%|█████▍    | 361/661 [01:55<01:22,  3.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Pjūvio kraštai: krūties audinys be patologinių pokyčių.     2. Pjūvio kraštai: Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS, komedo tipo) krūties audinyje.     3. Sarginiai l/m: limfmazgiai (2) be patologinių pokyčių; pN(sn)0(0/2).    4. Dešinios krūties sektorius.  Krūties invazyvi lobulinė karcinoma (G2, 6b. pagal Nottingham);  pT2(22 mm) pLVI-0 pR0.   Imunofenotipas (nustatytas priešoperaciname naviko biopsijos tyrime):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: ribinė (2+). HER2 geno amplifikacija NENUSTATYTA.  Ki67 proliferacinis aktyvumas 3%.    5. Papildomas kraštas. Krūties fibrocistiniai pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).
answer:  3

 55%|█████▍    | 362/661 [01:55<01:24,  3.55it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Kraštai - riebalinis audinys be patologinių pokyčių.  2(2b). Kraštai - riebalinis audinys be patologinių pokyčių.   3. Limfmazgiai - limfmazgiai (2) be patologinių pokyčių.    4(1). Kairės krūties kvadrantas.   Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT1c pLVI-0 pN0 pR0.  Imunotipas priešoperaciniame biopsijso tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 50% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.
answer:  1

 55%|█████▍    | 363/661 [01:56<01:25,  3.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Po operacinės medžiagos tyrimo patikslintas N1 naviko tipas  Dešinė  N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.  ------------  Kairė  N2: Mucininė krūties karcinoma (G2, 6 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.
answer:  1

 55%|█████▌    | 364/661 [01:56<01:20,  3.69it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.
answer:  1

 55%|█████▌    | 365/661 [01:56<01:17,  3.81it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma: pT2(23mm); pN1(mi) (metastazės intramamariniame limfmazgyje iki 1,5mm; pažasties limfmazgiai (12 l/m) be metastazių).  Intraduktalinės krūties papilomos, radialiniai randai (7 dariniai).
answer:  2

 55%|█████▌    | 366/661 [01:56<01:23,  3.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N1). Kairės krūties kvadrantas.   Krūties invazyvi vidutiniškai diferencijuota (G2, 7 b. pagal Nottingham sist.) duktalinė karcinoma,   suminis TNM: pT2 (32 mm navikas)   pN0(sn)(0/4 l/m)    pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pP1(perineurinis naviko plitimas)   pR0(radikalus pašalinimas).  Naviko imunotipas operacinėje medžiagoje: HER2: reakcija neigiama (1+).  Naviko imunotipas biopsijoje (B23-13989):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 25% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.    2(N2a). Kraštai. Krūties audinys be patologinių pokyčių.   3(N2b). Kraštai. Krūties audinys be patologinių pokyčių.     4(N3). Kairės pažasties sarginis limfmazgis. Reaktyvi limfadenopatija (4 l/m).     5(N4). Papildomas kraštas. Riebalinis fibrozinis audinys be naviko plitimo.
answer:  1

 56%|█████▌    | 367/661 [01:57<01:26,  3.39it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2, ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos (mikro)metastazė viename limfmazgyje (mts 1/3 l/m; iki 1,3 mm skersmens).    2(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) mucininė karcinoma, žr. pastabą,   SUMINIS TNM:   pT2 (navikas 30 mm) N1a (mts 2/4 l/m; iki 8,5 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+); mikrometastazėje - reakcijos nėra (0).     Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).  Krūties rezekcijos kraštas be naviko.
answer:  3

 56%|█████▌    | 368/661 [01:57<01:26,  3.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Papildyta HER2 FISH.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties fibroadenoma (0,5 cm).  3(ekstra). Krūties duktalinės karcinomos metastazė limfmazgyje su ekstranodaliniu plitimu(1/3 l/m 4 mm).   4. Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(14 mm navikas) pN1a(sn)(1/3 l/m MTS 4 mm su ekstranodaliniu plitimu) LVI-2(limfovaskulinė invazija). Perineurinis plitimas. R0(radikali rezekcija).  Vidutinio - žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1-DIN2, kribriforminis tipas). Lobulinė karcinoma in situ (LCIS).    Imunofenotipas:   Her2 reakcija: ribinė (2+).  HER2 geno amplifikacija nenustatyta.
answer:  4

 56%|█████▌    | 369/661 [01:57<01:21,  3.59it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma; pT1b (9mm).  N2ab: Audiniai be naviko.  N3: Riebalinis audinys, l/m nerasta.  N4: Limfmazgiai (2 l/m) be naviko; pN0(sn).
answer:  2

 56%|█████▌    | 370/661 [01:57<01:17,  3.74it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis iki 25%.
answer:  2

 56%|█████▌    | 371/661 [01:58<01:22,  3.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Riebalinis-fibrozinis audinys.  3. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c pN2a(5/11 l/m iki 7 mm su ekstranodaliniu plitimu) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).  4. Pažasties limfmazgiai: duktalinės karcinomos metastazės limfmazgiuose (5/11 l/m iki 7 mm su ekstranodaliniu plitimu).   Imunofenotipas(biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.
answer:  3

 56%|█████▋    | 372/661 [01:58<01:19,  3.61it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 40%.
answer:  2

 56%|█████▋    | 373/661 [01:58<01:26,  3.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a, ekstra). "Viršutinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   2(1b, ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos metastazė limfmazgyje (mts 1/3 l/m; iki 6 mm skersmens; be ekstranodalinio plitimo).  4(3). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1c (navikas 18 mm) N1a(sn) (mts 1/3 l/m; iki 6 mm skersmens), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, papilinis, komedo tipai).   Krūties sektoriaus rezekcijos kraštas normalios histologinės struktūros.
answer:  3

 57%|█████▋    | 374/661 [01:59<01:27,  3.28it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Žymėtas kraštas: fibrocistiniai pokyčiai. Dėl nežymėtos fragmento dalies ŽR.PASTABĄ.  2(2b). Žymėtas kraštas: fibrocistiniai pokyčiai. Dėl nežymėtos fragmento dalies ŽR.PASTABĄ.  3. Krūties duktalinės karcinomos mikrometastazė viename limfmazgyje (1/3 l/m, 1,3 mm).   4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mišri duktalinė (50%) ir mikropapilinė karcinoma (50%), TNM: pT1b(m)(2 židiniai: 8,5 mm ir 5,7 mm), pN1mi(sn)(1/3 l/m), LVI2(identifikuota). HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS), kribriforminis ir mikropapalinis variantai.
answer:  4

 57%|█████▋    | 375/661 [01:59<01:32,  3.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2, ekstra). "Deš. pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).  2(3). "Deš. krūties sektorius":   Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1c (navikas 13 mm) N0(sn) (0/3 l/m), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcijos nėra (0).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis tipas).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Krūties sektoriaus rezekcijos kraštas normalios histologinės struktūros.  3(4). "Papildomas viršutinis kraštas": krūties fibrocistiniai pokyčiai.  4(5). "Papildomas apaptinis kraštas": fibrozuotas riebalinis audinys; be naviko.  5(1a)."Viršutinis kraštas": fibrozuotas krūties audinys; be naviko.   6(1b). "Apatinis kraštas": fibrozuotas krūties audinys; be naviko.
answer:  1

 57%|█████▋    | 376/661 [01:59<01:27,  3.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutinės diferenciacijos duktalinė krūties karcinoma: navikas krūtyje 25mm; naviko židiniai/satelitai odoje; intravaskulinis naviko plitimas.
answer:  2

 57%|█████▋    | 377/661 [02:00<01:25,  3.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) karcinoma: galima/tikėtina krūties duktalinė ("bazinio" imunofenotipo) adenokarcinoma.     Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Her2 imuninė reakcija: neigiama (0).  Ki67: 30% (hot spot 40%).
answer:  3

 57%|█████▋    | 378/661 [02:00<01:26,  3.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys su koaguliaciniais artefaktais; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (5 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 11 mm) N0(sn) (0/5 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2:reakcijos nėra (0).    Krūties fibroadenoma (~4 mm).
answer:  4

 57%|█████▋    | 379/661 [02:00<01:20,  3.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 90% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.
answer:  2

 57%|█████▋    | 380/661 [02:00<01:16,  3.68it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%, vietomis iki 10%.
answer:  1

 58%|█████▊    | 381/661 [02:01<01:18,  3.55it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT(m)2(32 mm ir 7 mm naviko židiniai)   pN1a (2/21 l/m su mts iki 18mm)   pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pR0(radikalus pašalinimas).   Naviko imunotipas operacinėje medžiagoje (metastazės limfmazgyje): HER2:reakcijos nėra (0).  Naviko imunotipas iš biopsijos (B23-11819):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 kribriforminis, komedo tipai).  Intraduktalinė papiloma (1 mm).
answer:  2

 58%|█████▊    | 382/661 [02:01<01:14,  3.72it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis 15%.
answer:  2

 58%|█████▊    | 383/661 [02:01<01:19,  3.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Duktalinės karcinomos metastazė limfmazgyje (1/2 l/m; iki 14,6mm).  2. Krūties invazyvi, blogai diferencijuota (G3; 9 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(m)(dauginiai naviko židiniai nuo 1,33mm iki 20mm) pN1a(1/2 l/m; iki 14,6mm); LVI-2(Limfo-Vaskulinė naviko Invazija (LVI) smulkiose kraujagyslėse/limfagyslėse); PN(perineurinis naviko plitimas).   IHC reakcijos atliktos VPC:B23-489 tyrime:  "Estrogenų receptoriai: vidutinė reakcija 90% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 5% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%."  Krūties vidutinio ir aukšto laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas; -komedo tipo nekrozė). Intraduktalinės krūties papilomos. Krūties fibrocistiniai pokyčiai, paprasta intraduktalinė hiperplazija.
answer:  3

 58%|█████▊    | 384/661 [02:02<01:14,  3.71it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 35%.
answer:  3

 58%|█████▊    | 385/661 [02:02<01:16,  3.61it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Riebalinis - fibrozinis audinys.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(9,5 mm navikas) pN0(sn)(0/3 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas). R0(radikali rezekcija).    Imunofenotipas(biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 10%.
answer:  1

 58%|█████▊    | 386/661 [02:02<01:13,  3.76it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%, vietomis iki 80%.
answer:  3

 59%|█████▊    | 387/661 [02:02<01:22,  3.34it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys; be naviko.   2(1b, ekstra). "Apatinis kraštas": koaguliacijos zonoje, gilesniuose pjūviuose neišliekantis 1,9 mm židinys, kuriame histologiniai pokyčiai artimiausi žemo laipsnio duktalinės karcinomos in situ (DIN1/DCIS; kribriforminio tipo) ar inkapsuliuotos papilinės karcinomos (kuri traktuojama kaip in situ karcinoma) plitimui.     3(2). Krūties inkapsuliuota papilinė karcinoma (~22 mm) su invazyvia gerai diferencijuota (G1, 5 balai pagal Nottingham) duktaline karcinoma, pT1a(m) (keli nedideli invazijos židiniai iki 2 mm; žr. pastabą),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Invazyvaus naviko imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas iki 5%.    Krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: kribriforminis tipas).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė, apokrininė metaplazija).   Inkapsuliuotos papilinės karcinomos neinvazyvus komponentas nuo sektoriaus rezekcijos krašto nutolęs - 0,1 mm.   4(3). "Papildomas kraštas": fibrozuotas riebalinis audinys; be naviko.
answer:  3

 59%|█████▊    | 388/661 [02:03<01:21,  3.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2a). Krūties fibrocistiniai pokyčiai.  2(N2b). Krūties fibrocistiniai pokyčiai. Paprastoji duktalinė hiperplazija.  3(N3). Reaktyvi limfadenopatija (4 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,5 cm) pN(sn)0 (0/4 l/m). LVI0(limfovaskulinės invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 15% (hot spot 20%).
answer:  4

 59%|█████▉    | 389/661 [02:03<01:21,  3.32it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: pašalintas kairės krūties kvadrantas.   Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo  nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.    N2(N2a): kraštai. Krūties audinys be patologinių pokyčių.  N3(N2b): kraštai. Krūties audinys be patologinių pokyčių.  N4(N3): kairės pažasties sarginis limfmazgis. Limfmazgiai (4) be patologinių pokyčių.  N5(N4): papildomas kraštas. Krūties audinys be patologinių pokyčių.    pT1c(18 mm) pLVI-0 pL0 pR0.
answer:  1

 59%|█████▉    | 390/661 [02:03<01:18,  3.46it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.
answer:  1

 59%|█████▉    | 391/661 [02:04<01:14,  3.65it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%, vietomis iki 80%.
answer:  3

 59%|█████▉    | 392/661 [02:04<01:21,  3.29it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai": krūties audinys su koaguliuotais kanaliukais; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos metastazė dvejuose limfmazgiuose (mts 2/6 l/m; iki 9 mm skersmens).  4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma   su mikropapiliniu komponentu (~40%) ir židinine mucinų produkcija (~25%), SUMINIS TNM:   pT1c (navikas 13 mm) N1a(sn) (mts 2/6 l/m; iki 9 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose).   Gausūs naviką infiltruojantys limfocitai. Kalcifikatai.     Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 98% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 5% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%. Karštame taške 15-20%.    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis ir papilinis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).   Nuo sektoriaus rezekcijos krašto invazyvus navikas nutolęs 0,1 mm, DCIS komponentas - 0,5 mm.
answer:  3

 59%|█████▉    | 393/661 [02:04<01:16,  3.51it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 60% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 40%.
answer:  2

 60%|█████▉    | 394/661 [02:05<01:18,  3.42it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a, ekstra). "Viršutinis kraštas": fibrozuotas krūties audinys; be naviko.   2(1b, ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai; be naviko.   3(2, ekstra). "Kairės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 17 mm) N0(sn) (0/3 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Navikas nuo sektoriaus rezekcijos krašto nutolęs 0,1 mm.
answer:  1

 60%|█████▉    | 395/661 [02:05<01:13,  3.63it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Suderinama su blogai diferencijuotos duktalinės krūties karcinomos plitimu odos bioptatuose;   G3 (8 b. pgl. Nottingham sist.);  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 50%.
answer:  3

 60%|█████▉    | 396/661 [02:05<01:11,  3.72it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (3 l/m).   4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(23 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).
answer:  3

 60%|██████    | 397/661 [02:05<01:08,  3.85it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė lobulinė karcinoma (mažiausiai iki 13 mm);  (G2; 6 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 45%.
answer:  2

 60%|██████    | 398/661 [02:06<01:09,  3.77it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties lobulinė karcinoma in situ (LCIS).   2. Fibrocistiniai krūties pokyčiai: plokščia epitelio atipija, apokrininė epitelio metaplazija.  3. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 5 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1b(navikas 8 mm), pN0(sn)(0/1 l/m), LVI0 (neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Krūties lobulinė karcinoma in situ (LCIS).
answer:  3

 60%|██████    | 399/661 [02:06<01:08,  3.82it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Duktalinės karcinomos metastazė limfmazgyje (1 iš 12 l/m, 10 mm); pN1a.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1a (4mm).  Žemo laipsnio intraduktalinė karcinoma (DCIS/DIN1, mikropapilinis tipas); ryškūs fibrocistiniai pokyčiai, intraduktalinės papilomos.
answer:  3

 61%|██████    | 400/661 [02:06<01:11,  3.64it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).   2. Krūties duktalinės karcinomos metastazės 4 limfmazgiuose (4/7 l/m, iki 10 mm skersmens, ekstranodalinis plitimas).   3. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT2(m)(navikai 28 mm ir 5,5 mm), pN2a(4/10 l/m), LVI2 (limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime. HER2:reakcijos nėra (0). Ki67: proliferacinis indeksas 15%. Karštame taške 25%.  Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Fibrocistiniai krūties pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).   4. Reaktyvi limfadenopatija (3 l/m).
answer:  3

 61%|██████    | 401/661 [02:06<01:10,  3.71it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G1; 5 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%. Karštame taške 20%.
answer:  1

 61%|██████    | 402/661 [02:07<01:07,  3.85it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 7%.
answer:  2

 61%|██████    | 403/661 [02:07<01:05,  3.97it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.
answer:  1

 61%|██████    | 404/661 [02:07<01:08,  3.73it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Dešinė  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.  Aukšto laipsnio intraduktalinė karcinoma (DCIS; solidinė ir komedo).  --------------  Kairė  N2: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%, vietomis iki 30%.
answer:  2

 61%|██████▏   | 405/661 [02:07<01:06,  3.86it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 25% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.
answer:  1

 61%|██████▏   | 406/661 [02:08<01:04,  3.95it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) lobulinė karcinoma. Krūties lobulinė karcinoma in situ (LCIS).   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.  Progesterono receptoriai: stipri (+++) reakcija, 50% naviko ląstelių.
answer:  2

 62%|██████▏   | 407/661 [02:08<01:06,  3.81it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1a (3,3mm).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.  Vidutinio laipsnio papilinė intraduktalinė karcinoma DCIS/DIN2 (6mm židinys aplink invazinį naviką; krūties audinyje dar du, 6mm ir 3 mm, židiniai).  N2a: Žemo laipsnio kribriforminės intraduktalinės karcinomos 0,5mm židinys (DCIS/DIN1).  Rezekcijos kraštas be naviko.  N2b: Krūties audinys be naviko.
answer:  3

 62%|██████▏   | 408/661 [02:08<01:15,  3.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė, apokrininė metaplazija); be naviko.   2(2b, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija); kalcifikatai; be naviko.   3(2, ekstra). "Dešinės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (6 l/m).     4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma (su apokrininės diferenciacijos požymiais), SUMINIS TNM:   pT1b (navikas 9 mm) N0(sn) (0/6 l/m),   LVI-0 (definityvi limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.   HER2: reakcija neigiama (1+).   Androgenų receptoriai: stipri brand. r-ja, 100%.     Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė, gausūs apokrininės metaplazijos židiniai). Odos seborėjinė keratozė.
answer:  4

 62%|██████▏   | 409/661 [02:09<01:13,  3.42it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. (2a) kraštai -extra: krūties audinys be patologinių pokyčių.  2. (2b) - kraštai -extra: krūties audinys be patologinių pokyčių.  3. Sarginiai l/m - extra: limfmazgis (1) be patologinių pokyčių.    4. Krūties sektorius. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma;  (G3; 9 b. pgl. Nottingham sist.) pT1c pLVI-0 pN0 pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama/žema raiška (1+).  Ki67: proliferacinis indeksas 85%.
answer:  1

 62%|██████▏   | 410/661 [02:09<01:11,  3.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).   4. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma, SUMINIS TNM: pT1c(12 mm navikas) N0(sn)(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Perineurinė invazija. Radikalus pašalinimas.   Naviko imunotipas atliktas biopsijoje (žr.pastabą).
answer:  1

 62%|██████▏   | 411/661 [02:09<01:12,  3.45it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTA  1(N2A). Nežymi fokalinė krūties audinio fibrozė.  2(N2b). Nežymi fokalinė krūties audinio fibrozė.  3(N3). Reaktyvi limfadenopatija (1 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenocarcinoma, TNM (Nr.1-Nr.4): pT2(2,5 cm) pN(sn)0 (0/1 l/m). LVI0(limfovaskulinės naviko invazijos nėra).     Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: ribinė (2+).  Ki67: 5%.  ---  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).
answer:  3

 62%|██████▏   | 412/661 [02:09<01:15,  3.30it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (atipinė duktalinė hiperplazija); kalcifikatai.   2(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).    3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).   4. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,    SUMINIS TNM:   pT1b (navikas 7 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis tipas).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, sklerozuojanti adenozė, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).
answer:  3

 62%|██████▏   | 413/661 [02:10<01:10,  3.50it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 10%.
answer:  2

 63%|██████▎   | 414/661 [02:10<01:16,  3.25it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštas": duktalinės karcinomos židinys (~0,85 mm skersmens).    2(2b, ekstra). "Kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   3. "Kairės pažasties limfmazgiai": duktalinės karcinomos metastazė keturiuose limfmazgiuose (mts 4/12 l/m; iki 8,5 mm skersmens).  4. "Papildomas kraštas": fibrozuotas riebalinis audinys; be naviko.     5(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT2(m) (du židiniai: I - 30 mm; II - 0,8 mm) N2a (mts 4/12 l/m; iki 8,5 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Perineurinis plitimas.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2:reakcijos nėra (0).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Naviko struktūros sektoriaus koaguliacijos zonoje (~0,4 mm atkarpoje).
answer:  1

 63%|██████▎   | 415/661 [02:10<01:12,  3.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Pokyčiai būdingi intracistinei papilinei karcinomai (traktuojama kaip In situ karcinoma).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.
answer:  1

 63%|██████▎   | 416/661 [02:11<01:16,  3.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Koreguotas atsakymas (Indas Nr. 5).  1(ekstra). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir papilinis tipai).  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) mikropapilinė karcinoma, SUMINIS TNM: pT1c(20 mm) pN0(sn)(0/1 l/m) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir papilinis tipai). Intraduktalinės papilomos.  5. Papildomas kraštas. Riebalinis fibrozinis audinys.  Imunofenotipas (biopsijoje):   Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 25%, vietomis iki 40%.
answer:  1

 63%|██████▎   | 417/661 [02:11<01:17,  3.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Kraštai. Krūties audinys be patologinių pokyčių.    2(2b). Kraštai. Krūties audinys be patologinių pokyčių.    3(1). Markiruotas kalcinatų plotas iš kairės krūties.  Krūtyje invazinė duktalinė karcinoma G2(6 b. pgl. Nottingham sist.);    pT1c(11 mm), pLVI-0 pR0(1,5 mm).   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 50% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.    Vidutinė intraduktalinė karcinoma, DCIS/DIN2, solidinio, tinklinio ir komedo tipo.  Krūties fibrocistiniai pakitimai.    4(3). Dešinės krūties kvadrantas.   Ribotas darinys: Intraduktalinė karcinoma žemo laipsnio (DCIS/DIN1, galimai adenomoje).  DCIS/DIN1 difuzinis plitimas audinyje ir operaciniame krašte, pR(is)1.   Krūties fibrocistiniai pakitimai.
answer:  3

 63%|██████▎   | 418/661 [02:11<01:14,  3.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%, vietomis iki 10%.
answer:  1

 63%|██████▎   | 419/661 [02:12<01:18,  3.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": duktalinės karcinomos metastazė limfmazgyje (mts 1/3 l/m; iki 3 mm skersmens).    4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,  SUMINIS TNM:   pT1b (navikas 8 mm) N1a(sn) (mts 1/3 l/m; iki 3 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti ir mikroglandulinė adenozė,   stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).   Sektoriaus rezekcijos kraštas be naviko.
answer:  2

 64%|██████▎   | 420/661 [02:12<01:18,  3.08it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2). Duktalinės karcinomos mikrometastazės limfmazgyje (1/1 l/m; iki 1,93mm).  2(1). Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT2(navikas - 43mm) pN1mi(sn)(1/1 l/m; iki 1,93mm); LVI-2 (Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).  IHC reakcijos atliktos VPC:B23-4377 tyrime:  "Estrogenų receptoriai: vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%."
answer:  2

 64%|██████▎   | 421/661 [02:12<01:13,  3.25it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 50% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 7%.
answer:  2

 64%|██████▍   | 422/661 [02:12<01:09,  3.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(16mm).  N2ab: Audiniai be naviko.  N3: Limfmazgiai (3 l/m) be naviko; pN0(sn).
answer:  2

 64%|██████▍   | 423/661 [02:13<01:06,  3.57it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki  mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 35%. Karštame taške 50%.
answer:  1

 64%|██████▍   | 424/661 [02:13<01:03,  3.75it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma. Mikrokalcinatai.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 15%.
answer:  2

 64%|██████▍   | 425/661 [02:13<01:01,  3.84it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Atipinė duktalinio epitelio hiperplazija.  N2: Krūties audinys be naviko.  N3: Viename limfmazgyje (1 iš 2 l/m) duktalinės karcinomos 3mm metastazė; pN1a (sn).  N4: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(m) (du navikai 10mm ir 13mm).
answer:  3

 64%|██████▍   | 426/661 [02:13<01:01,  3.85it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1-2: Krūties daugiažidininė karcinoma:  trys židiniai (8mm, 5mm ir 5mm) gerai difencijuotos (G1, 4 balai pagal Nottingham) duktalinės karcinomos;  du židiniai (3mm ir 2mm) gerai difencijuotos (G1, 5 balai pagal Nottingham) lobulinės karcinomos;  pT1b(m); pN1a(sn) (10mm metastazė ir duktalinės ir lobulinės karcinomos).
answer:  1

 65%|██████▍   | 427/661 [02:14<00:59,  3.94it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.
answer:  2

 65%|██████▍   | 428/661 [02:14<01:14,  3.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(extra). Viršutinis kraštas, dešinė. Fibrocistiniai pokyčiai.  2(extra). Apatinis kraštas, dešinė. Krūties žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1, kribriforminis tipas).  3(extra). Sarginiai limfmazgiai, dešinė. Reaktyvi limfadenopatija (4 l/m).    4(extra). Viršutinis kraštas, kairė. Fibrocistiniai pokyčiai.  5(extra). Apatinis kraštas, kairė. Fibrocistiniai pokyčiai.  6. Kairės pažasties sarginiai limfmazgiai (planinis). Duktalinės karcinomos metastazė (1/1 l/m, 4,4 mm).    7. DEŠINĖ. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) multižidininė, mikroinvazyvi duktalinė karcinoma, SUMINIS TNM: pT1mi(m)(0,4 mm, 0,5 mm, 0,9 mm, 1 mm) pN0(sn)(0/6 l/m0 LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 DIN1 DIN2, kribriforminis, solidinis, komedo ir papilinis tipai), DCIS židinys iki 2 cm. R0(radikali rezekcija).  Imunofenotipas (biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.    8. KAIRĖ.  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(21 mm navikas) pN1a(sn)(MTS 1/1 l/m 4,4 mm) LVI-2(limfovaskulinė invazija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas). R0(radikali rezekcija).  Imunofenotipas (biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%, vietomis iki 30%.    9. Papildomas kairės krūties viršutinis kraštas. Fibrocistiniai pokyčiai.   10. Papildomas dešinės krūties apatinis kraštas. Fibrocistiniai pokyčiai.
answer:  1

 65%|██████▍   | 429/661 [02:14<01:10,  3.30it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G1; 5 b. pgl. Nottingham sist.) 3-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 7%.    2. Fibroepiteliniai pokyčiai, gali būti suderinami su krūties fibroadenoma.
answer:  1

 65%|██████▌   | 430/661 [02:15<01:08,  3.39it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Reaktyvi limfadenopatija (2 l/m). Nodalinis nevocitinis nevusas 1 limfmazgyje.   3. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1b(6 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio ir žemo laipsnio duktalinė karcinoma in situ (DIN1c/DIN2/DCIS)(kribriforminė, komedo). DCIS struktūros 0,1 mm nuo sektoriaus   rezekcijos krašto.
answer:  1

 65%|██████▌   | 431/661 [02:15<01:05,  3.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 8 mm);  (G1; 3 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 8%.
answer:  1

 65%|██████▌   | 432/661 [02:15<01:03,  3.61it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.  N2: Ryški krūties audinio fibrozė, vienas fragmentuotas žemo laipsnio intraduktalinės karcinomos mikrožidinys (0,5mm).
answer:  1

 66%|██████▌   | 433/661 [02:15<01:00,  3.78it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%. Karštame taške 15%.
answer:  2

 66%|██████▌   | 434/661 [02:16<01:08,  3.30it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). "Viršutinis kraštas": krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija); kalcifikatai; be naviko.   2(ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija, sklerozuojanti adenozė); kalcifikatai; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (1 l/m).   Fibrozuoto krūties audinio fragmentas su židininiais fibrocistiniais pokyčiais: tikėtina pridėtinė krūtis, tikslinga klinikinė koreliacija.     4. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1b (navikas 9,63 mm) N0(sn) (0/1 l/m),   LVI-0 (definityvi limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija, sklerozuojanti adenozė).
answer:  3

 66%|██████▌   | 435/661 [02:16<01:06,  3.41it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1A). Krūties fibrocistiniai pokyčiai.  2(1B). Krūties fibrocistiniai pokyčiai.  3(2). Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė adenokarcinoma, pT1c(1,6 cm) pN1a(2/17 l/m, mts 0,4 cm ir 0,5 cm). LVI2(limfovaskulinė invazija, smulkiose struktūrose).     Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 20% (hot spot 30%).
answer:  3

 66%|██████▌   | 436/661 [02:16<01:02,  3.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.
answer:  1

 66%|██████▌   | 437/661 [02:17<00:58,  3.83it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b(12cm, išopėjimas); pN2a (4 iš 8 l/m).  Krūties ir pažasties audinių nekrozė, uždegiminė infiltracija su abscesais.
answer:  2

 66%|██████▋   | 438/661 [02:17<00:56,  3.94it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(11mm).  N2a-2b: Krūties ir riebalinio audinio fragmentai be naviko.  N3: Limfmazgis be naviko metastazių; pN0(sn).
answer:  2

 66%|██████▋   | 439/661 [02:17<00:59,  3.72it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 13 mm);  (G2; 7 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    2. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 3 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se navikinio audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.
answer:  1

 67%|██████▋   | 440/661 [02:18<01:15,  2.92it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1.(2a)(kairė). Krūties audinys; pavieniai intraduktaliniai mikrokalcifikatai.  2.(2b)(kairė). Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas). Lobulinė krūties Carcinoma in situ (LCIS). Krūties fibrocistiniai pokyčiai.   3.(3)(kairė) Reaktyvi limfadenopatija (2 l/m).  4(N5a)(dešinė) Krūties audinys.  5(N5b)(dešinė) Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas). Lobulinė krūties Carcinoma in situ (LCIS). Krūties intraduktalinės papilomos. Krūties fibrocistiniai pokyčiai; paprasta intraduktalinė hiperplazija.   6(N6)(dešinė) Reaktyvi limfadenopatija (3 l/m).  7(N7)(pap. kraštas, kairė) Riebalinis audinys.  8(N1)(kairė) Krūties invazyvi, gerai diferencijuota (G1; 4 balai pagal Nottingham sis) duktalinė karcinoma su lobulinės karcinomos komponentu (~5% naviko), suminis tyrimo TNM: pT1c(m)(du naviko židiniai 16,7mm ir 10mm) pN0(sn)(0/2 l/m).   IHC reakcijos atliktos VPC:B23-29805 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%."  Krūties intraduktalinė karcinoma (DCIS; kribriforminis, mikropapilinis tipas). Lobulinė krūties Carcinoma in situ (LCIS). Intraduktalinės krūties papilomos. Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.  9(N4)(dešinė) Krūties invazyvi, gerai diferencijuota (G1; 4 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(m)(dauginiai naviko židiniai nuo 0,6mm iki 14mm) pN0(sn)(0/3 l/m).   IHC reakcijos atliktos VPC:B23-29805 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%."  Krūties žemo ir vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis, kribriforminis tipas; -komedo tipo nekrozėmis). Lobulinė krūties Carcinoma in situ (LCIS). Krūties intraduktalinės papilomos. Krūties fibrocistiniai pokyčiai; paprasta intraduktalinė hiperplazija.   10(N8)(pap. kraštas, dešinė) Krūties audinys.
answer:  3

 67%|██████▋   | 441/661 [02:18<01:08,  3.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.
answer:  1

 67%|██████▋   | 442/661 [02:18<01:04,  3.39it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) adenokarcinoma (galimai duktalinė, su neuroendokrininės diferencijacijos požymiais, ar invazyvi solidinė papilinė karcinoma).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5%.
answer:  2

 67%|██████▋   | 443/661 [02:18<01:04,  3.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinio fibrozė.  2(Extra). Krūties audinio fibrozė.  3(Extra). Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(6 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas (R0).  Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 1% naviko ląstelių.  HER2 imuninė reakcija: neigiama (1+).  Ki67: 5%.   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(kribriforminė).
answer:  1

 67%|██████▋   | 444/661 [02:19<01:02,  3.45it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a). Krūties lobulinė karcinoma in situ (LCIS).  2(1b). Krūties audinys.  3(2). Krūties duktalinės karcinomos mikrometastazė viename limfmazgyje (1/2 l/m, 1 mm skersmens).  4(3). Krūties invazyvi gerai diferencijuota (G1, 4b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 14 mm), pN1mi(sn)(1/2 l/m, 1mm), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties lobulinė karcinoma in situ (LCIS).   5(4). Krūties audinys.
answer:  4

 67%|██████▋   | 445/661 [02:19<00:59,  3.61it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 60%.
answer:  3

 67%|██████▋   | 446/661 [02:19<01:04,  3.34it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N1a, ekstra/Kraštai). Krūties audinys.  2(N1b, ekstra/Kraštai). Krūties audinys.  3(N2, ekstra/Sarginiai l/m). Lobulinės karcinomos metastazė 1/2 limfmazgių (3 mm).  4(N3, D. krūties sektorius). A) Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(11 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinė invazija neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).  B) Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1a(3,3 mm) N(sn)1a(mts 1/2 l/m: 3 mm), LVI-0(limfovaskulinė invazija neidentifikuota). Radikalus pašalinimas. Lobulinė karcinoma in situ (LCIS).  Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 5% naviko ląstelių.  HER2 imuninė reakcija: neigiama (1+).  Ki67: 2%.
answer:  1

 68%|██████▊   | 447/661 [02:20<01:04,  3.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Pjūvio kraštai. Krūties fibrocistiniai pokyčiai. Naviko plitimo nėra.     2(ekstra). Pjūvio kraštai. Krūties fibrocistiniai pokyčiai. Naviko plitimo nėra.    3(ekstra). Sarginiai l/m. Duktalinės karcinomos metastazė 1-me/3 limfmazgių, iki 2 mm skersmens.      4. Krūties sektorius.  Krūties invazyvi vidutiniškai diferencijuota (G1, 5 b. pgl Nottingham sist.) duktalinė karcinoma,   pT1c(13 mm)   pN(sn)1mi(1/3 l/m mts iki 2 mm)   pLVI-0 (limfovaskulinės invazijos nestebima)   pR0(radikalus pašalinimas).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama (0).  Ki67: proliferacinis indeksas 5%.
answer:  4

 68%|██████▊   | 448/661 [02:20<01:03,  3.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a). Riebalinis, fibrozinis audinys.  2(1b). Krūties fibrocistiniai pokyčiai.  3(2). Reaktyvi limfadenopatija (2 l/m).  4(3). Krūties invazyvi duktalinė adenokarcinoma (gerai diferencijuota / G1 / 5 balai pagal Nottingham), TNM (Nr.1-Nr.4): pT1b(0,9 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 3%.
answer:  1

 68%|██████▊   | 449/661 [02:20<01:00,  3.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 10%.
answer:  1

 68%|██████▊   | 450/661 [02:20<00:57,  3.64it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi duktalinė adenokarcinoma (tikėtina vidutiniškai diferencijuota / G2 / 6 balai pagal Nottingham sistemą), plitimas 1/1 biopsiniame stulpelyje, iki 6,8 mm ilgyje.     Estrogenų receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: 15%.
answer:  2

 68%|██████▊   | 451/661 [02:21<00:55,  3.81it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Žemo piktybiškumo metaplastinė (ištęstų ląstelių) krūties karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 1-2%.
answer:  2

 68%|██████▊   | 452/661 [02:21<00:53,  3.92it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 15%.
answer:  2

 69%|██████▊   | 453/661 [02:21<00:56,  3.71it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  2(Extra). Krūties audinys.  3. Krūties invazyvi blogai diferencijuota (G3; 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(5,5 mm) NX(limfmazgiai nešalinti), LVI-0(limfovaskulinės invazijos neidentifikuota).    Imunofenotipas:   Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2 imuninė reakcija: teigiama (3+).  Ki67: 30%.  Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS)(solidinė, kribriforminė, komedo) (30 mm židinys makro).  Invazyvi karcinoma pašalinta radikaliai, DCIS struktūros siekia sektoriaus rezekcijos kraštą.
answer:  3

 69%|██████▊   | 454/661 [02:21<00:53,  3.89it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (9mm).  N2ab: Audiniai be naviko.  N3: Limfmazgiai (2 l/m) be naviko; pN0(sn).
answer:  1

 69%|██████▉   | 455/661 [02:22<00:53,  3.82it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties adenozė.   2. Krūties adenozė.   3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma,   pT1a (17 mm) pN0(sn) (0/2 l/m); LVI2 (limfovaskulinė naviko invazija smulkiose limfagyslėse/ kraujagyslėse).   Krūties aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2-DIN3; kribriforminė, solidinė).
answer:  3

 69%|██████▉   | 456/661 [02:22<00:53,  3.83it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcja neigiama, branduolių nusidažymas mažiau 5% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; nustatyta HER2 geno amplifikacija.  Ki67+ 35%.
answer:  2

 69%|██████▉   | 457/661 [02:22<00:55,  3.67it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties audinys.  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (4 l/m).   4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham sistemą) duktalinė karcinoma, pT2 (22 mm navikas) N0(sn)(4 l/m) LVI0 (limfovaskulinė invazija neidentifikuota). Radikalus pašalinimas. Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 komedo tipas).  Stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).     Naviko imunotipas nustatytas biopsijoje:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%.
answer:  3

 69%|██████▉   | 458/661 [02:23<00:54,  3.73it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Mucininė krūties karcinoma (G1, 5 balai pgl Nottingham); pT2(21mm).  N2ab: Krūties audinys be patologijos.
answer:  1

 69%|██████▉   | 459/661 [02:23<00:53,  3.77it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.
answer:  1

 70%|██████▉   | 460/661 [02:23<00:54,  3.72it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: silpnas branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67+ 12%, vietomis iki 20%.
answer:  2

 70%|██████▉   | 461/661 [02:23<00:53,  3.75it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.
answer:  1

 70%|██████▉   | 462/661 [02:24<00:56,  3.54it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (5 l/m).   2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT2 (navikas 28 mm) N0(sn) (0/5 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).   Kalcifikatai.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis, papilinis ir komedo tipai).   Rezekcijos kraštai be naviko.   3. Fibrozuotas krūties-riebalinis audinys; be naviko.
answer:  3

 70%|███████   | 463/661 [02:24<00:56,  3.51it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: silpnas ar vidutinis branduolių nusidažymas 10% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%, vietomis iki 40%.  N2: Lobulinės karcinomos metastazė limfmazgyje.
answer:  3

 70%|███████   | 464/661 [02:24<00:56,  3.50it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Limfmazgio bioptatas be naviko plitimo.   2. Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 4%.
answer:  1

 70%|███████   | 465/661 [02:24<00:56,  3.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vyraujantis komponentas vidutinio laipsnio intraduktalinė karcinoma (DCIS/DIN2; kribriforminė).    Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.
answer:  1

 70%|███████   | 466/661 [02:25<01:00,  3.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTAS ATSAKYMAS HER2 FISH TYRIMU (HER2 geno amplifikacija nenustatyta):   1(ekstra). "Deš. pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (4 l/m).   2. Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c(m) (naviko židiniai: I - 11 mm; II - 8 mm; III - 4 mm) N0(sn) (0/4 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, papilinis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė, apokrininė metaplazija).   DCIS struktūros nuo giliojo rezekcijos krašto nutolusios - 1,45 mm.
answer:  1

 71%|███████   | 467/661 [02:25<00:55,  3.47it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) mucininė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 40% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 3%.
answer:  1

 71%|███████   | 468/661 [02:25<00:56,  3.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. pjūvio kraštai: krūties audinys be patologinių pokyčių.    2. pjūvio kraštai: krūties audinys su intraduktaline hiperplazija.    3. sarginiai l/m: limfmazgis (1) be karcinomos ląstelių.; pN(sn)0.    4. sektorius.   Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą)   duktalinė karcinoma su mucininės diferenciacijos požymiais;   pT1c(<20mm) pLVI-0 pR0.  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 1% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.
answer:  3

 71%|███████   | 469/661 [02:26<00:53,  3.57it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Limfmazgio bioptatas su lobulinės karcinomos metastaze.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%, vietomis iki 40%.
answer:  3

 71%|███████   | 470/661 [02:26<00:52,  3.64it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 4,5 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se/3 krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 5%.    Krūties fibrocistiniai pokyčiai: stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).   Kalcifikatai.
answer:  2

 71%|███████▏  | 471/661 [02:26<00:51,  3.68it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Limfmazgio bioptatas su duktalinės karcinomos metastaze.  N2: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%.  N3: Limfmazgio bioptatas be naviko židinių.
answer:  3

 71%|███████▏  | 472/661 [02:26<00:49,  3.83it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 15%.
answer:  2

 72%|███████▏  | 473/661 [02:27<00:48,  3.85it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi duktalinė karcinoma, 0,4 mm židinys (1/5 bioptatų). Žr. pastabą.   Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, solidinis tipas), (2/5 bioptatų).     Naviko imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 20%.
answer:  3

 72%|███████▏  | 474/661 [02:27<00:52,  3.54it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija); kalcifikatai; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.     3(1). Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 9,6 mm),   LVI-0 (definityvi limfovaskulinė invazija neidentifikuota). Kalcifikatai.    Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties žemo-vidutinio laipsnio duktalinė karcinoma in situ (DIN1-2/DCIS: solidinis, kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).   DCIS komponentas nuo sektoriaus rezekcijos krašto nutolęs 0,72 mm.
answer:  3

 72%|███████▏  | 475/661 [02:27<00:50,  3.70it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 90% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.
answer:  2

 72%|███████▏  | 476/661 [02:28<00:50,  3.67it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2A). Krūties fibrocistiniai pokyčiai.  2(N2B). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (1 l/m).  4(N1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,7 cm) pN(sn)0 (0/1 l/m). LVI0(limfovaskulinės invazijos nėra).    Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 5% (hot spot 10%).
answer:  1

 72%|███████▏  | 477/661 [02:28<00:49,  3.73it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 5,5 mm);  (G1; 5 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 8%.
answer:  1

 72%|███████▏  | 478/661 [02:28<00:47,  3.87it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT4b (33mm, išopėjimas).
answer:  2

 72%|███████▏  | 479/661 [02:28<00:46,  3.95it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.
answer:  1

 73%|███████▎  | 480/661 [02:28<00:45,  4.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%.
answer:  2

 73%|███████▎  | 481/661 [02:29<00:45,  3.92it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a). Viršutinis kraštas. Krūties audinys be patologinių pokyčių.   2(1b). Apatinis kraštas. Krūties audinio fibrozė.   3(2). Deš. pažasties sarginiai l/m. Reaktyvi limfadenopatija (4 l/m).   4(3). Deš. krūties sektorius. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma. SUMINIS TNM: pT1c(15 mm navikas) pN0(sn)(0/4 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikalus pašalinimas).   Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 kribriforminis tipas).
answer:  1

 73%|███████▎  | 482/661 [02:29<00:44,  4.02it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mucininė karcinoma.   Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: vidutinė reakcija 5% naviko ląstelių.   Her2 imuninė reakcija: teigiama (3+).   Ki67 proliferacinis aktyvumas 5%.
answer:  2

 73%|███████▎  | 483/661 [02:29<00:56,  3.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(extra). Viršutinis kraštas, dešinė. Fibrocistiniai pokyčiai.  2(extra). Apatinis kraštas, dešinė. Krūties žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1, kribriforminis tipas).  3(extra). Sarginiai limfmazgiai, dešinė. Reaktyvi limfadenopatija (4 l/m).    4(extra). Viršutinis kraštas, kairė. Fibrocistiniai pokyčiai.  5(extra). Apatinis kraštas, kairė. Fibrocistiniai pokyčiai.  6. Kairės pažasties sarginiai limfmazgiai (planinis). Duktalinės karcinomos metastazė (1/1 l/m, 4,4 mm).    7. DEŠINĖ. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) multižidininė, mikroinvazyvi duktalinė karcinoma, SUMINIS TNM: pT1mi(m)(0,4 mm, 0,5 mm, 0,9 mm, 1 mm) pN0(sn)(0/6 l/m0 LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 DIN1 DIN2, kribriforminis, solidinis, komedo ir papilinis tipai), DCIS židinys iki 2 cm. R0(radikali rezekcija).  Imunofenotipas (biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%.    8. KAIRĖ.  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(21 mm navikas) pN1a(sn)(MTS 1/1 l/m 4,4 mm) LVI-2(limfovaskulinė invazija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas). R0(radikali rezekcija).  Imunofenotipas (biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25%, vietomis iki 30%.    9. Papildomas kairės krūties viršutinis kraštas. Fibrocistiniai pokyčiai.   10. Papildomas dešinės krūties apatinis kraštas. Fibrocistiniai pokyčiai.
answer:  1

 73%|███████▎  | 484/661 [02:30<00:55,  3.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT3(55 mm dydžio navikas)   pN1a(3-se/18 l/m su mts iki 10 mm)   pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pP1(perineurinis naviko plitimas)   pR0(radikalus pašalinimas).   Naviko imunotipas nustatytas priešoperacinėje biopsijoje:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.    Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, komedo tipo).  Įprastinė duktalinė hiperplazija. Apokrininė metaplazija.  Odos seborėjinė keratozė; dermalinis nevusas su seborėjine keratoze.
answer:  3

 73%|███████▎  | 485/661 [02:30<00:54,  3.25it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. pjūvio kraštai. Krūties fibrocistiniai pokyčiai.  2. pjūvio kraštai. Krūties fibrocistiniai pokyčiai.    3. sarginiai l/m - karcinomos mikrometastazė (1 mm) 1-me iš 4 limfmazgyje.    4. Krūties sektorius.   Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma  pT1b pN1mi pR0.  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.    Intraduktalinė papiloma (4 mm).
answer:  1

 74%|███████▎  | 486/661 [02:30<00:56,  3.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2/deš. pažasties sarginiai limfmazgiai)(EXTRA). Duktalinės karcinomos mikrometastazė 1/5 l/m (1,4 mm).  2(3a/deš. krūties viršutinis kraštas)(EXTRA). Krūties audinys.  3(3b/deš. krūties apaptinis kraštas)(EXTRA). Krūties audinys.  4(1/kairės krūties užspenelinis audinys)(EXTRA). Krūties audinys.  5(1a/kairės pažasties sarginiai limfmazgiai)(EXTRA). Reaktyvi limfadenopatija (6 l/m).  6(4/deš. krūties audinys). Krūties (dešiniosios) invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(15 mm) N(sn)1mi(mikromts 1/5 l/m), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).  7(5/kairės krūties audinys). Krūties (kairiosios) aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS)(solidinė, kribriforminė, papilinė,  komedo), pTis. DCIS struktūros 0,25 mm nuo poodinio rezekcijos krašto.
answer:  1

 74%|███████▎  | 487/661 [02:31<00:53,  3.28it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties audinys.  2. Riebalinio audinio fragmentas.  3. Krūties duktalinės karcinomos mikrometastazė viename limfmazgyje (1/3 l/m, 1,5 mm).  4. Krūties invazyvi  mišri blogai diferencijuota (G3; 8 b. pgl. Nottingham) duktalinė (70%) ir mikropapilinė (30%) karcinoma, suminis TNM: pT1c(navikas 14 mm), pN1mi(1/3 l/m), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).
answer:  3

 74%|███████▍  | 488/661 [02:31<00:51,  3.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Krūties fibrocistiniai pokyčiai.  2(2b). Krūties fibrocistiniai pokyčiai.  3(3). Reaktyvi limfadenopatija (2 l/m).  4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT2(2,3 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės naviko invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imunohistocheminė reakcija: neigiama (0 balų).  Ki67: 10%.
answer:  1

 74%|███████▍  | 489/661 [02:31<00:48,  3.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, silpnas branduolių nusidažymas pavienėse ląstelėse.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.
answer:  1

 74%|███████▍  | 490/661 [02:32<00:48,  3.51it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties invazyvi duktalinė karcinoma (gerai diferencijuota, G1 / 4 balai pagal Nottingham);   pT1b(9 mm)   pLVI-0   pN(sn)1mi(1/2; 1,2 mm)   pR0(1,2 mm nuo krašto).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 3% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 12%.    Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS, kribrozinio tipo).    2. Krūties audinio nespecifiniai fibroziniai židiniai.   3. Krūties audinio nespecifiniai fibroziniai židiniai.   4. Karcinomos mikrometastazė 1-me/2 limfmazgyje.  5. Riebalinio audinio fragmentas be patologinių pokyčių.
answer:  1

 74%|███████▍  | 491/661 [02:32<00:45,  3.70it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.
answer:  1

 74%|███████▍  | 492/661 [02:32<00:44,  3.77it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma. Aukšto laipsnio duktalinė karcinoma in situ (DCIS, plokščias, kribriforminis tipas).     Imunofenotipas:   Estrogenų receptoriai: vidutinė reakcija 90% naviko ląstelių.    Progesterono receptoriai: vidutinė reakcija 5% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 10%.
answer:  2

 75%|███████▍  | 493/661 [02:32<00:49,  3.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(extra). Viršutinis kraštas. Krūties invazyvi karcinoma (1,3 mm židinys). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 mikropapilinis, solidinis tipai).  2(extra). Apatinis kraštas. Krūties audinys.  3(extra). Kairės krūties sarginiai limfmazgiai. Duktalinės karcinomos metastazės limfmazgiuose (4/4 l/m iki 12 mm).  4. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) mišri duktalinė - mikropapilinė karcinoma, SUMINIS TNM: pT3(56 mm navikas)  pN3a(13/24 l/m MTS iki 14 mm) LVI-2(limfovaskulinė invazija). Navikas siekia sektoriaus rezekcijos kraštą. Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 mikropapilinis, solidinis tipai).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 35%.    5. Papildomas viršutinis kraštas. Krūties invazyvi karcinoma (2,4 mm židinys).  6. Papildomas viršutinis kraštas. Krūties audinys.  7. Limfmazgiai, planinis. Duktalinės karcinomos metastazės limfmazgiuose (9/20 l/m iki 14 mm)
answer:  3

 75%|███████▍  | 494/661 [02:33<00:46,  3.61it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 5%, vietomis iki 10%.
answer:  1

 75%|███████▍  | 495/661 [02:33<00:45,  3.68it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai.  2. Krūties lobulinė karcinoma in situ (LCIS).   3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, TNM: pT1c(navikas 12 mm), pN0(sn)(0/3 l/n), LVI0(neidentifikuota). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.
answer:  4

 75%|███████▌  | 496/661 [02:33<00:46,  3.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Riebalinis - fibrozinis audinys.  2(ekstra). Krūties invazyvi karcinoma (0,4 mm židinys). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, komedo tipas).  3. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT3(m)(52 mm, 10 mm navikai) pN0(sn)(0/1 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).  4. Papildomas kraštas. Riebalinis - fibrozinis audinys. Reaktyvi limfadenopatija (1 l/m).  5. Papildomas kraštas. Krūties audinio fibrozė.    Imunofenotipas:   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 60%.
answer:  3

 75%|███████▌  | 497/661 [02:33<00:44,  3.65it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 11 mm);  (G2; 6 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 3% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 40%.
answer:  2

 75%|███████▌  | 498/661 [02:34<01:01,  2.63it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties invazyvi gerai diferencijuota (G1,  5b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(14 mm navikas) pN1a(sn)(7 mm MTS 1/1 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stipri reakcija 95% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 30% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.    2. Kraštai (N2a). Krūties audinio fibrozė.  3. Kraštai (N2a). Krūties audinio fibrozė.  4. Krūties duktalinė karcinomos metastazė limfmazgyje (1/1 l/m 7 mm MTS).
answer:  1

 75%|███████▌  | 499/661 [02:34<01:03,  2.54it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham sistemą) duktalinė karcinoma (12,5 mm mikroskopiškai).  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 plokščias, solidinis tipai).  Naviko imunofenotipas:  Estrogenų receptoriai: stipri reakcija, 90% naviko ląstelių.  Progesterono receptoriai: stipri reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 7%.
answer:  1

 76%|███████▌  | 500/661 [02:35<00:56,  2.85it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis ar silpnas branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 15%, vietomis 20%.
answer:  2

 76%|███████▌  | 501/661 [02:35<00:56,  2.81it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). "Kraštai": fibrozuotas riebalinis audinys; be naviko.    2(ekstra). "Kraštai": fibrozuotas krūties-riebalinis audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (4 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT1c (navikas ~13 mm skersmens) N0(sn) (0/4 l/m), LVI-0 (limfovaskulinė invazija neidentifikuota).   LVI-0 (definityvios limfovaskulinės invazijos nėra).   Kalcifikatai.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties lobulinė intraepitelinė neoplazija (LCIS).  Krūties žemo laipsnio duktalinė karcinoma in situ (DIN1/DCIS: kribriforminis tipas).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė duktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).
answer:  1

 76%|███████▌  | 502/661 [02:35<00:54,  2.94it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 reakcija neigiama 1+.  Ki67+ 3%.  Žemos ir vidutinio laipsnio intraduktalinė karcinom (DCIS/DIN1-2).
answer:  1

 76%|███████▌  | 503/661 [02:36<00:50,  3.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma.  2. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma.  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: silpnas(+) branduolinis dažymasis 2%.   HER2 imunohistocheminė reakcija neigiama (0 balų).  Ki67: 80%.
answer:  3

 76%|███████▌  | 504/661 [02:36<00:50,  3.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1b(10 mm navikas) pN0(sn)(0/3 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija). Vidutinio - žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1 DIN2, kribriforminis ir papilinis tipai).    Imunofenotipas:   Estrogenų receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (0+).  Ki67: 15%.
answer:  1

 76%|███████▋  | 505/661 [02:36<00:47,  3.31it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35-40%.
answer:  3

 77%|███████▋  | 506/661 [02:37<00:45,  3.42it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1-2: Krūties audinio fragmentai be naviko.  N3: Limfmazgiai (4 l/m) be naviko židinių; pN0(sn).  N4: Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (9mm).
answer:  3

 77%|███████▋  | 507/661 [02:37<00:47,  3.25it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties audinys.  2. Krūties audinys.  3. Krūties duktalinės karcinomos metastazė limfmazgyje (1/1 l/m; 11,7mm; ekstranodalinis naviko plitimas).  4. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(m)(du naviko židiniai: 12mm ir 16mm) pN1a(1/17 l/m; 11,7mm; ekstranodalinis naviko plitimas); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).  IHC reakcijos atliktos VPC:B23-115 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%."  Krūties fibrocistiniai pokyčiai; sklerozuojanti adenozė.
answer:  3

 77%|███████▋  | 508/661 [02:37<00:45,  3.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 10%.
answer:  1

 77%|███████▋  | 509/661 [02:37<00:42,  3.56it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 80% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 3%.
answer:  2

 77%|███████▋  | 510/661 [02:38<00:41,  3.64it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai.  2. Reaktyvi limfadenopatija (2 l/m).  3. Krūties invazyvi blogai diferencijuota (G3; 9 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 16 mm), pN0(sn)(0/2 l/m), LVI0(neidentifikuota). Estrogenų receptoriai: reakcijos nėra. HER2:reakcijos nėra (0). Progesterono receptoriai: reakcijos nėra. Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija.
answer:  3

 77%|███████▋  | 511/661 [02:38<00:40,  3.73it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.
answer:  1

 77%|███████▋  | 512/661 [02:38<00:39,  3.77it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+, HER2 geno amplifikacija nenustatyta.  Ki67+ 10%.
answer:  1

 78%|███████▊  | 513/661 [02:38<00:40,  3.61it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a). Viršutinis kraštas. Krūties audinys be patologinių pokyčių.    2(1b). Apatinis kraštas. Krūties audinys be patologinių pokyčių.    3(2). Dešinės pažasties sarginiai limfmazgiai. Limfmazgiai (2) be karcinomos ląstelių.    4(3). Dešinės krūties sektorius. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.    pT1b(9 mm) pLVI-0 pN(sn)0 pR0.
answer:  1

 78%|███████▊  | 514/661 [02:39<00:38,  3.78it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 2% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 25%.
answer:  2

 78%|███████▊  | 515/661 [02:39<00:37,  3.92it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.
answer:  1

 78%|███████▊  | 516/661 [02:39<00:37,  3.89it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2). Reaktyvi limfadenopatija (3 l/m).  2.  Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) lobulinė karcinoma, TNM: pT3(53 mm naviko židinys), LVI0(neidentifikuota), pN0(sn)(0/3 l/m). Krūties lobulinė karcinoma in situ (LCIS). HER2:reakcijos nėra (0). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0).  Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3). Spenelio Pageto liga.
answer:  3

 78%|███████▊  | 517/661 [02:39<00:36,  3.99it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1 , 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.
answer:  1

 78%|███████▊  | 518/661 [02:40<00:35,  4.04it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 1-2% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.
answer:  1

 79%|███████▊  | 519/661 [02:40<00:34,  4.09it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 25-30%.
answer:  2

 79%|███████▊  | 520/661 [02:40<00:37,  3.81it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a)(Extra). Krūties invazyvi duktalinė karcinoma (3,6 mm židinys). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).  2(1b)(Extra). Krūties audinys.  3(1c)(Extra). Krūties audinys.  4(2)(Extra). Duktalinės karcinomos metastazės 2/4 l/m (7 mm ir 4,5 mm).   5(3). Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(18 mm) N(sn)1a(mts 2/4 l/m), LVI-2(limfovaskulinė invazija).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).  Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.
answer:  1

 79%|███████▉  | 521/661 [02:40<00:35,  3.91it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.
answer:  1

 79%|███████▉  | 522/661 [02:41<00:35,  3.97it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 35%.
answer:  3

 79%|███████▉  | 523/661 [02:41<00:36,  3.74it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a). Krūties audinys.  2(1b). Krūties audinys.  3. Krūties duktalinės karcinomos mikrometastazė limfmazgyje (1/3 l/m; iki 1,05mm).  4. Krūties invazyvi, gerai diferencijuota (G1; 4 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(navikas - 13mm) pN1mi(sn)(1/3 l/m; iki 1,05mm); LVI-2 (Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse); perineurinis naviko plitimas (PN). Rezekcijos kraštas be naviko.  IHC reakcijos atliktos VPC:B23-19125 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: reakcija neigiama, branduolių nusidažymas 1-2% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%."
answer:  1

 79%|███████▉  | 524/661 [02:41<00:38,  3.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Fibrocistiniai krūties pokyčiai.  2(2b). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(navikas - 15mm) pT0(sn)(0/3 l/m); LVI-2(Limfo-Vaskulinė naviko Invazija smulkiose kraujagyslėse/limfagyslėse).  IHC/FISH reakcijos atliktos VPC:B23-33188 tyrime:  "Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta, FISH tyrimo rezultatas interpretuojamas įvertinus HER2 IHC tyrimą kaip neigiamas(žr. molekulinio tyrimo aprašymą ir pastabas).  Ki67: proliferacinis indeksas 15%."  Krūties žemo/vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis ir kribriforminis tipas).
answer:  3

 79%|███████▉  | 525/661 [02:42<00:37,  3.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 8 mm);  (G2; 6 b. pgl. Nottingham sist.)1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 20%.  Žemo laipsnio intraduktalinė intraepitelinė neoplazija (DIN1/DCIS).    2. Krūties fibrocistiniai pokyčiai.
answer:  1

 80%|███████▉  | 526/661 [02:42<00:38,  3.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2A). Krūties fibrocistiniai pokyčiai. Intraduktalinė papiloma (0,15 cm).  2(2B). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (1 l/m).  4(N1). Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė ("bazinio" imunofenotipo) adenokarcinoma, TNM (Nr.1-Nr.4): pT1b(0,8 cm) pN(sn)0 (0/1 l/m). LVI0(limfovaskulinės naviko invazijos nėra).  ATSKIRAS/SMULKESNIS FRAGMENTAS: Krūties fibrocistiniai pokyčiai. Krūties fibroadenoma (0,3 cm).  ---  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: silpnas(+) branduolinis dažymasis 2%.   HER2 imunohistocheminė reakcija neigiama (0 balų).  Ki67: 80%.
answer:  4

 80%|███████▉  | 527/661 [02:42<00:36,  3.69it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100 % naviko ląstelių.  Progesterono receptoriai: stipri reakcija 40 % naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 45 %.
answer:  3

 80%|███████▉  | 528/661 [02:42<00:35,  3.77it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1 ir N2: Krūties audinys be naviko.  N3: Limfmazgiai (4 l/m) be naviko metastazių; pN0(sn).  N4: Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham); pT2(22mm).  Žemo laipsnio intraduktalinė karcinoma (0,2mm židinys; DCIS/DIN1, kribriforminė).  Krūties fibrocistiniai pokyčiai, fibroadenomatozinė hiperplazija).
answer:  0

 80%|████████  | 529/661 [02:43<00:34,  3.87it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 6%.
answer:  1

 80%|████████  | 530/661 [02:43<00:34,  3.81it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a). Krūties audinys.  2(1b). Krūties audinys.   3(2). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(navikas - 17mm) pN0(sn)(0/3 l/m); LVI-0(Limfo-Vaskulinė naviko Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-29562 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 20%."
answer:  3

 80%|████████  | 531/661 [02:43<00:33,  3.91it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.
answer:  1

 80%|████████  | 532/661 [02:43<00:36,  3.56it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(2b, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė);  kalcifikatai; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 19,5 mm) N0(sn) (0/3 l/m),   LVI-0 (definityvi limfovaskulinė invazija neidentifikuota).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: kribriforminis, papilinis, komedo tipai). Krūties lobulinė intraepitelinė neoplazija (LCIS). Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė).
answer:  4

 81%|████████  | 533/661 [02:44<00:36,  3.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties audinys.  2(ekstra). Krūties audinys.  3(ekstra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(12 mm navikas) pN0(sn)(0/4 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). Aukšto - vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN3-DIN2, kribriforminis ir papilinis tipai). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.
answer:  1

 81%|████████  | 534/661 [02:44<00:34,  3.67it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.
answer:  1

 81%|████████  | 535/661 [02:44<00:33,  3.81it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė tubulinė karcinoma (mažiausiai iki 8 mm);  (G1; 3 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 3%.
answer:  1

 81%|████████  | 536/661 [02:45<00:34,  3.67it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 10%. Karštame taške 20%.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.    2. Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta.  Ki67: proliferacinis indeksas 10%.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.
answer:  2

 81%|████████  | 537/661 [02:45<00:32,  3.81it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.
answer:  2

 81%|████████▏ | 538/661 [02:45<00:32,  3.82it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Įtariama invazinė gerai diferencijuota duktalinė arba tubulinė karcinoma (G1; menkas atipinių struktūrų kiekis):  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 0%.    Kompleksinis sklerozuojantis pažeidimas: sklerozuojanti adenozė.  Atipinė duktalinė hiperplazija (ADH).
answer:  1

 82%|████████▏ | 539/661 [02:45<00:33,  3.67it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a)(Extra). Riebalinis audinys.  2(2b)(Extra). Riebalinis audinys.  3(Extra). Reaktyvi limfadenopatija (4 l/m).  4(1). Krūties invazyvi blogai diferencijuota (G3; 8 balai pagal Nottingham) metaplastinė (šeivinių ląstelių) karcinoma (su lygiųjų raumenų diferenciacija), SUMINIS TNM: pT1c(15 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Imunofenotipas:   Estrogenų receptoriai: silpnas/vidutinis branduolių nusidažymas 25% naviko ląstelių.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.   HER2 imuninė reakcija: nusidažiusių naviko ląstelių nėra.   Ki67: 2%.
answer:  3

 82%|████████▏ | 540/661 [02:46<00:32,  3.69it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties audinys.  2. Krūties lobulinė karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (1 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1c(navikas 15 mm), pN0(sn)(0/2 l/m), LVI2 (limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS).   HER2: reakcija neigiama (1+).
answer:  3

 82%|████████▏ | 541/661 [02:46<00:31,  3.84it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.   Progesterono receptoriai: stipri reakcija 25% naviko ląstelių.   Her2 imuninė reakcija: neigiama (0).   Ki67 proliferacinis aktyvumas 8%.
answer:  2

 82%|████████▏ | 542/661 [02:46<00:31,  3.82it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Limfmazgio bioptatas su duktalinės karcinomos metastaze.  N2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.
answer:  1

 82%|████████▏ | 543/661 [02:46<00:29,  3.94it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 5%.
answer:  2

 82%|████████▏ | 544/661 [02:47<00:29,  4.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5%.
answer:  2

 82%|████████▏ | 545/661 [02:47<00:28,  4.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 30%.
answer:  3

 83%|████████▎ | 546/661 [02:47<00:29,  3.89it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(3)(ekstra). Reaktyvi limfadenopatija (4 l/m).  2(1)(ekstra). Krūties audinys.   3(2)(ekstra). Krūties audinys.   4. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma, suminis TNM: pT2(22 mm navikas) N0(sn)(4 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). Gausūs intranavikiniai limfocitai (TILs). R0(radikali rezekcija).     Naviko imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  Androgenų receptoriai: silpna reakcija 5% naviko ląstelių.  Ki67: proliferacinis indeksas 80%.  HER2:reakcijos nėra (0).
answer:  1

 83%|████████▎ | 547/661 [02:47<00:31,  3.63it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties fibrocistiniai pokyčiai.  2. Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis/kribriforminis; židinys - 2,7mm).  3. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sist.) duktalinė karcinoma, pT1a(navikas - 4,5mm); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-40706 tyrime:   "Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 8%."  Krūties vidutinio laipsnio intraduktalinė karcinoma (DCIS; kribriforminis, mikropapilinis tipas; -komedo tipo nekrozės, mikrokalcifikatai).
answer:  3

 83%|████████▎ | 548/661 [02:48<00:31,  3.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 b. pgl Nottingham sist.) duktalinė karcinoma   (plitimas mažiausiai iki 16,5 mm mikroskopiškai).  Naviko imunofenotipas:  Estrogenų receptoriai: silpna (+) reakcija, 20% naviko ląstelių.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 30%.
answer:  2

 83%|████████▎ | 549/661 [02:48<00:32,  3.49it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTA  Krūties invazyvi duktalinė karcinoma (ne mažiau kaip gerai diferencijuota / G1 / 5 balai pagal Nottingham).     Estrogenų receptoriai: silpnas-vidutinis branduolių nusidažymas 80% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: ribinė (2+).  Ki67: iki 5%.  ---  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).
answer:  1

 83%|████████▎ | 550/661 [02:48<00:32,  3.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1,2(ekstra). Riebalinis audinys.  3(ekstra). Reaktyvi limfadenopatija (5 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT1c(17 mm navikas) pN0(sn)(0/5 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, solidinis tipas). Lobulinė karcinoma in situ (LCIS). Odos seborėjinė keratozė.    Imunofenotipas:   Estrogenų receptoriai: stiprus ir vidutinis branduolių nusidažymas 40% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 20% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.
answer:  1

 83%|████████▎ | 551/661 [02:49<00:31,  3.47it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Limfmazgis (1 l/m) be naviko; pN0(sn).  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c (15mm).
answer:  2

 84%|████████▎ | 552/661 [02:49<00:32,  3.30it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė-mikropapilinė karcinoma;   pT(m)1c(15 mm, 7 mm, 1 mm, 2,5 mm)   pN2a(7/16 ; ekstranodalinis plitimas)   pR0 (radikalus pašalinimas).  Karcinomos metastazės limfmazgyje imunotipas:  HER2: reakcija neigiama (1+).  Imunotipas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 8%.    Vidutinio laipsnio intraduktalinė karcinoma (DIN2/DCIS; kribrozinio tipo).  Krūties fibroadenoma.  Kapiliarinė odos hemangioma.
answer:  2

 84%|████████▎ | 553/661 [02:49<00:34,  3.12it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Duktalinės karcinomos metastazė limfmazgyje 3 mm (1/1 l/m).    4. Krūties vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma su daline mikropapiline ir mucinine diferenciacija, SUMINIS TNM: pT2(m)(25 mm, 8 mm, 7 mm, 2,3 mm, 2,2 mm, 1 mm navikai) pN1a(sn)(3/6 l/m MTS iki 5 mm) LVI-2(limfovaskulinė invazija). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3 kribriforminis, solidinis, komedo tipai), DCIS nuo priekinio rezekcijos paviršiaus nutolęs 0,8 mm, nuo giliojo - 0,6 mm.    Naviko imunofenotipas (biopsijoje):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 20%.    5. Papildomi limfmazgiai: duktalinės karcinomos metastazės limfmazgiuose (2/5 l/m iki 5 mm). Riebalinis audinys.
answer:  1

 84%|████████▍ | 554/661 [02:50<00:32,  3.25it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.
answer:  1

 84%|████████▍ | 555/661 [02:50<00:30,  3.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.
answer:  2

 84%|████████▍ | 556/661 [02:50<00:30,  3.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a, ekstra). "Viršutinis kraštas": fibrozuotas riebalinis audinys; be naviko.   2(1b, ekstra). "Apatinis kraštas": fibrozuotas krūties audinys; be naviko.   3(2, ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(3). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT2(m) (navikai: I - 27 mm; II - 7 mm) N0(sn) (0/2 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2:reakcijos nėra (0).    Krūties lobulinė intraepitelinė neoplazija (LCIS; pleomorfinis ir konvencinis variantas).  Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).
answer:  3

 84%|████████▍ | 557/661 [02:50<00:28,  3.59it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis iki 20%.
answer:  2

 84%|████████▍ | 558/661 [02:51<00:29,  3.44it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTAS ATSAKYMAS HER2 FISH TYRIMU:   1(ekstra). "Kraštas": fibrozuotas riebalinis audinys; be naviko.   2(ekstra). "Kraštas": fibrozuotas krūties audinys; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma (su tikėtinu mikropapiliniu komponentu, ~20%), SUMINIS TNM:   pT1c (mikroskopiškai navikas 15 mm, žr. pastabą) N0(sn) (0/3 l/m),    LVI-0 (definityvi limfovaskulinė invazija neidentifikuota). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.   HER2 geno amplifikacija nenustatyta (žr. molekulinio tyrimo aprašymą ir pastabas).   Navikas nuo sektoriaus rezekcijos krašto nutolęs 0,17 mm.
answer:  3

 85%|████████▍ | 559/661 [02:51<00:28,  3.63it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 9 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 8% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 30%.
answer:  3

 85%|████████▍ | 560/661 [02:51<00:26,  3.78it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 10%.
answer:  2

 85%|████████▍ | 561/661 [02:51<00:28,  3.57it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Paruošti pjūviai Prosigna tyrimui.    1(3). Kairės pažasties sarginis limfmazgis. Reaktyvi limfadenopatija (6 l/m).   2(N2a). N2a kraštai. Krūties audinys. Naviko plitimo nėra.   3(N2b). N2a kraštai. Krūties audinys. Naviko plitimo nėra.   4(1). Kairės krūties kvadrantas. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham sistemą) duktalinė karcinoma, pT4b (22 mm išopėjęs navikas) N0(sn)(6 l/m) LVI-0 (limfovaskulinė invazija neidentifikuota). Radikalus pašalinimas (R0).  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis, kribriforminis tipai).  Naviko imunofenotipas:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 20-25%.
answer:  4

 85%|████████▌ | 562/661 [02:52<00:27,  3.64it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Blogai diferencijuota (G3, 8 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;   pT(m)2(24 mm ir 14 mm) pN2a(8/12) pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%, vietomis iki 20%.
answer:  3

 85%|████████▌ | 563/661 [02:52<00:31,  3.13it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2, "Dešinės pažasties sarginis limfmazgis"). Reaktyvi limfadenopatija (3 l/m).  2(N4a, "kraštas"). Krūties fibrocistiniai pokyčiai.  3(N4b, kraštas"). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, papilinis tipas).  4(N5, "kairės pažasties sarginis l/m"). Reaktyvi limfadenopatija (2 l/m).  5(N1, "dešinė krūtis"). Krūties invazyvi multicentrinė adenokarcinoma, TNM (Nr.1, Nr.2, Nr.3, Nr.5): pT1c(m) (1,5 cm, 1 cm, 0,8 cm naviko židiniai) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės naviko invazijos nėra). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, papilinis, kribriforminis tipai). R0(radikalus navikų pašalinimas).  Navikų diferencijacijos laipsniai:  - vidutiniškai diferencijuota / G2 / 7 balai pagal Nottingham (1 cm ir 0,8 cm židiniai),  - blogai diferencijuota / G3 / 8 balai pagal Nottingham (1,5 cm židinys).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama.  Ki67: 10% (hot spot 20%).  ---  6(N3, "Kairės krūties markiruotas kvadrantas"). Krūties invazyvi duktalinės adenokarcinoma (vidutiniškai diferencijuota / G2 / 7 balai pagal Nottingham), TNM (Nr.4, Nr.6): pT1c(1,7 cm) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės naviko invazijos nėra). Krūties vidutinio ir aukšto laipsnio duktalinė karcinoma in situ (DCIS, kribriforminis tipas).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama.  Ki67: 10% (hot spot 20%).
answer:  1

 85%|████████▌ | 564/661 [02:52<00:28,  3.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) lobulinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 80% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 2%.
answer:  2

 85%|████████▌ | 565/661 [02:53<00:28,  3.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Reaktyvi limfadenopatija su dermatopatinės limfadenopatijos požymiais (4 l/m).  2. Krūties invazyvi gerai diferencijuota (G1; 4 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(31 mm) N(sn)0(0/4 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas (R0) (naviko atstumas nuo 1 mm nuo rezekcijos krašto).  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties inkapsuliuota papilinė karcinoma (11 mm) ir išplitusi vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė) (45 mm plote).  Krūties intraduktalinė papiloma.  Odos seborėjinė keratozė.
answer:  1

 86%|████████▌ | 566/661 [02:53<00:26,  3.59it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(18mm).  N2ab: Krūties audinys be naviko.  N3: Karcinomos metastazės viename limfmazgyje (iki 1mm židiniai, 1 iš 4 l/m); pN1mi(sn).
answer:  1

 86%|████████▌ | 567/661 [02:53<00:25,  3.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Limfmazgio 3 stulpeliai be patologinių pokyčių.    2. Limfmazgio 3 stulpeliai be patologinių pokyčių.    3. Krūties invazyvi gerai diferencijuota (G1) mucininė karcinoma (mažiausiai 11 mm skersmens) 5-se bioptatuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 5% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).  Ki67: proliferacinis indeksas 2%.
answer:  1

 86%|████████▌ | 568/661 [02:53<00:25,  3.64it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai.  2. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/3 l/m, 2,5 mm).  3. Krūties audinys.  4. Krūties invazyvi blogai diferencijuota (G3; 9 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT2(navikas 38 mm), pN1a(sn)(1/3 l/m, 2,5 mm), LVI2(limfovaskulinis plitimas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Progesterono receptoriai: reakcijos nėra.  Krūties fibroadenoma. Fibrocistiniai krūties pokyčiai.
answer:  3

 86%|████████▌ | 569/661 [02:54<00:26,  3.47it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(2b, ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.     3(1). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT2(m) (du naviko židiniai: I - 32 mm; II - 0,82 mm) N2a (mts 5/10 l/m; iki 8 mm skersmens),   LVI-2 (limfovaskulinė invazija smulkiose šakose). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė). Kalcifikatai.   Sektoriaus rezekcijos krašte - koaguliacinių artefaktų zonos su kalcifikatais; DCIS komponentas nutolęs 2,9 mm.
answer:  3

 86%|████████▌ | 570/661 [02:54<00:26,  3.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Fokalinė krūties audinio fibrozė.  2(2b). Fokalinė krūties audinio fibrozė.  3(3). Reaktyvi limfadenopatija (1 l/m).  4(1). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.4): pT1c(1,4 cm) pn(SN)0 (0/1 l/m). LVI0(limfovaskulinės invazijos nėra).     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5%.
answer:  1

 86%|████████▋ | 571/661 [02:54<00:25,  3.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Fibrocistiniai krūties pokyčiai.  2(2b). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (2 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT1b (navikas 7,5 mm), pN0(sn)(0/2 l/m), LVI0 (neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). HER2: reakcija paribinė (2+); HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).
answer:  3

 87%|████████▋ | 572/661 [02:55<00:24,  3.64it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė karcinoma (mažiausiai iki 13 mm; galimai lobulinė);  (G1; 5 b. pgl. Nottingham sist.) 4-se krūties audinio stulpeliuose.  Estrogenų receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 10% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 2%.
answer:  1

 87%|████████▋ | 573/661 [02:55<00:24,  3.61it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a). Krūties fibrocistiniai pokyčiai.  2(1b). Krūties fibrocistiniai pokyčiai.  3(2). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma, pT2(2,5 cm) pN1a(1/18 l/m, mts 0,7 cm; ekstranodalinis plitimas). Rezekcijos kraštų būklė: be naviko.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 98% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5% (hot spot 8%).
answer:  1

 87%|████████▋ | 574/661 [02:55<00:24,  3.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Krūties fibrocistiniai pokyčiai: paprasta intraduktalinė hiperplazija.  3(Extra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(18 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Naviko struktūros siekia koaguliuotą sektoriaus kraštą.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Židininė krūties audinio fibrozė.
answer:  3

 87%|████████▋ | 575/661 [02:55<00:24,  3.56it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Kairė  N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ar vidutinis branduolių nusidažymas 40% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.  ------------------  Dešinė  N2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 30% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.
answer:  1

 87%|████████▋ | 576/661 [02:56<00:25,  3.32it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   2. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma (su apokrininės diferenciacijos požymiais), SUMINIS TNM:   pT2(m) (du navikai: I - 30 mm; II - 11 mm) N0(sn) (0/3 l/mm), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Intraduktalinis karcinomos plitimas (kanaliukų kancerizacija). Kalcifikatai.   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).   Androgenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.   Synaptophysin/GATA3/E-Cadherin(+).     Krūties žemo-aukšto laipsnio duktalinė karcinoma in situ (DIN1c-3/DCIS: solidinis, kribriforminis, ploščias, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta ir atipinė intraduktalinė hiperplazija, sklerozuojanti ir mikroglandulinė adenozė, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija).   Krūties rezekcijos kraštas normalios histologinės struktūros.
answer:  3

 87%|████████▋ | 577/661 [02:56<00:25,  3.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Pjūvio kraštai. Krūties audinys be patologinių pokyčių.    2. Pjūvio kraštai. Krūties audinys be patologinių pokyčių.    3. Sarginiai l/m. Limfmazgiai (2) be karcinomos ląstelių.    4. Sektorius.   Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20-25%.    pT1c pN0 pLVI-0 pR0.
answer:  3

 87%|████████▋ | 578/661 [02:56<00:24,  3.41it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(extra). Reaktyvi limfadenopatija (5 l/m).  2. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, suminis TNM: pT2(38 mm navikas), pN0(0/5 l/m), R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2). Krūties fibrocistiniai pokyčiai.  Naviko imunofenotipas(biopsijoje):  Estrogenų receptoriai: stipri reakcija, 90% naviko ląstelių.  Progesterono receptoriai: stipri reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Operacinėje medžiagoje kartota: Ki67: proliferacinis indeksas 10%, fokaliai iki 20%.
answer:  3

 88%|████████▊ | 579/661 [02:57<00:22,  3.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma.  ---  Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100% .   Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 80% .   Her2 imunohistocheminė reakcija neigiama (0 balų).  Ki67: 35%.
answer:  3

 88%|████████▊ | 580/661 [02:57<00:22,  3.67it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PATAISYTAS ATSAKYMAS (naviko diferenciacijos laipsnis):  1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (5 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(15 mm) N(sn)0(0/5 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   HER2 imuninė reakcija: neigiama (1+).
answer:  1

 88%|████████▊ | 581/661 [02:57<00:25,  3.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  SUMINĖ (Nr.1-Nr.5) patologijos tyrimo išvada:  Krūties invazyvi multifokalinė karcinoma (mišrios duktalinės+lobulinės karcinomos židinys, ir dauginiai (ne mažiau 3) lobulinės karcinomos židiniai), pT1c(m) (dauginiai židiniai, didžiausias iki 1,2 cm) pN1mi(1/1 intramamarinis limfmazgis su 0,15 cm duktalinės adenokarcinomos mikromts + 0/4 sarginiai l/m). LVI0(limfovaskulinės invazijos nėra). Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribriforminis tipas). Krūties fibrocistiniai pokyčiai (paprastoji duktalinė hiperplazija, stulpinis ląstelių pokytis). Rezekcijos kraštai be patologijos.  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 15% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 5%.     1(extra). Invazyvios karcinomos židinys (iki 0,25 cm skersmens) krūties audinyje.  2(extra). Invazyvios karcinomos židinys (iki 0,7 cm skersmens) krūties audinyje.  3(extra). Reaktyvi limfadenopatija (4 l/m).  4. Krūties invazyvi mišri (lobulinė + duktalinė) karcinoma (iki 1,2 cm židinys, mikroskopiškai). Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribriforminis tipas). Krūties fibrocistiniai pokyčiai (paprastoji duktalinė hiperplazija, stulpinis ląstelių pokytis). Krūties duktalinės adenokarcinomos mikrometastazė (0,15 cm) intramamariniame limfmazgyje.  5. Krūties invazyvi lobulinė karcinoma (0,3 cm židinys). Krūties žemo ir vidutinio laipsnio duktalinė karcinoma in situ (DCIS, solidinis, kribriforminis tipas). Krūties fibrocistiniai pokyčiai (paprastoji duktalinė hiperplazija, stulpinis ląstelių pokytis).
answer:  5

 88%|████████▊ | 582/661 [02:58<00:24,  3.27it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Vidutinio laipsnio intraduktalinė karcinoma (DCIS/DIN2; solidinis tipas). Invazinė duktalinė karcinoma, navikas tokios pačios struktūros, kaip ir žemiau aprašytas; intravaskulinis naviko plitimas.  N2: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 80% naviko ląstelių.  Her2 imuninė reakcija: teigiama 3+.  Ki67+ 8%.
answer:  2

 88%|████████▊ | 583/661 [02:58<00:25,  3.03it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). DEŠINĖ. Duktalinės karcinomos mikrometastazė limfmazgyje (1/4 l/m, 0,4mm). Limfovaskulinė invazija.   2(extra). KAIRĖ. Reaktyvi limfadenopatija (3 l/m).    3. DEŠINĖ. Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma su daline neuroendokrinine diferenciacija, SUMINIS TNM: pT2(27 mm) pN1a(sn)(1/4 l/m, 0,4mm). LVI-2(limfovaskulinė invazija). Vidutinio žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas), gausūs židiniai iki 1 cm.    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    4. KAIRĖ. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma neuroendokrinine diferenciacija, SUMINIS TNM: pT2(m)(35 mm ir 7 mm navikai) pN0(sn)(0/3 l/m). LVI-2(limfovaskulinė invazija). Vidutinio žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis tipas).  Židininiai fibrocistiniai pokyčiai.    Imunofenotipas:   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 95% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.
answer:  3

 88%|████████▊ | 584/661 [02:58<00:23,  3.30it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%.
answer:  1

 89%|████████▊ | 585/661 [02:58<00:21,  3.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 7 mm);  (G1; 4 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.
answer:  1

 89%|████████▊ | 586/661 [02:59<00:20,  3.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė adenokarcinoma (su apokrininės diferencijacijos požymiais).  ---  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67: 20%.
answer:  2

 89%|████████▉ | 587/661 [02:59<00:19,  3.75it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mikropapilinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 5%.
answer:  2

 89%|████████▉ | 588/661 [02:59<00:18,  3.84it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%.
answer:  1

 89%|████████▉ | 589/661 [02:59<00:19,  3.79it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Reaktyvi limfadenopatija (2 l/m).  2. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham) duktalinė karcinoma (su minimalia mucinine diferenciacija), SUMINIS TNM: pT(m)1c(2 naviko židiniai: 19 mm ir 7 mm) N(sn)0(0/2 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties išplitusi aukšto ir vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DIN3/DCIS)(solidinė, kribriforminė, komedo) (4 židiniai).  Krūties intraduktalinės papilomos.
answer:  3

 89%|████████▉ | 590/661 [03:00<00:20,  3.43it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Pjūvio kraštai. Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.     2(ekstra). Pjūvio kraštai. Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.    3. Sektorius su pažasties l/m.   Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham sistemą) duktalinė karcinoma,   pT1c (18 mm navikas)   pN1mi(1/19 l/m su mts 0,9 mm)    pLVI-2 (limfovaskulinė invazija smulkiose gyslose)   pR0(radikalus pašalinimas).  Naviko imunotipas (iš biopsijos):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.    Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 kribriforminis tipas).  Krūties fibrocistiniai pokyčiai, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).   Lėtinė židininė granulominė (svetimkūnio tipo) uždegiminė reakcija krūties audinyje.
answer:  3

 89%|████████▉ | 591/661 [03:00<00:21,  3.28it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties audinys.  2. Vidutinio laipsnio krūties intraduktalinė karcinoma (DCIS; solidinis tipas; židinys - 1,5mm). Fibrocistiniai krūties pokyčiai.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi, gerai diferencijuota (G1, 4 balai pagal Nottingham sis.) duktalinė karcinoma, suminis tyrimo TNM: pT1a(navikas - 4mm) pN0(sn)(0/3 l/m); LVI-0(Limfo-Vaskulinė naviko Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-43421 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: vidutinis ir silpnas branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%."
answer:  1

 90%|████████▉ | 592/661 [03:00<00:20,  3.33it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma;   pT1b(9 mm) pLVI-0 pR0.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 18%. Karštame taške 50%.    2. Krūties audinys be patologinių pokyčių.
answer:  3

 90%|████████▉ | 593/661 [03:01<00:19,  3.46it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties mucininė karcinoma (G1, 5 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 4%.
answer:  1

 90%|████████▉ | 594/661 [03:01<00:19,  3.36it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Krūties duktalinės karcinomos metastazės 2/3 l/m (18 mm ir 2 mm, su ekstranodaliniu plitimu).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(22 mm) N(sn)1a(mts 2/3 l/m), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė, komedo).
answer:  1

 90%|█████████ | 595/661 [03:01<00:20,  3.25it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   2(1b, ekstra). "Kraštai": fibrozuotas krūties audinys.   3(2, ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).   4(3). Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1c (navikas 11 mm) N0(sn) (0/3 l/m), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   HER2: reakcija neigiama (1+); AR(+)100%.    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: solidinis, kribriforminis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).
answer:  1

 90%|█████████ | 596/661 [03:02<00:19,  3.38it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Gerai diferencijuota (G1 , 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1b (10mm).  N2ab: Krūties audinys be naviko.  N3: Limfmazgiai (2 l/m) be naviko židinių; pN0(sn).  N4: Krūties audinys be naviko.
answer:  1

 90%|█████████ | 597/661 [03:02<00:19,  3.35it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Reaktyvi limfadenopatija (1 l/m).  2. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė adenokarcinoma, TNM (Nr.1-Nr.2): pT1a(m) (0,4 cm ir 0,2 cm židiniai) pN(sn)0 (0/2 l/m). LVI0(limfovaskulinės invazijos nėra). Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, komedo tipas). R0(radikalus naviko pašalinimas).     Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: teigiama (3+).  Ki67: 25%.
answer:  1

 90%|█████████ | 598/661 [03:02<00:18,  3.37it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Anksčiau atliktas aktualus VPC tyrimas, B23-23353:  1. Krūties audinys.  2. Krūties audinys.  3. Fibrocistiniai krūties pokyčiai, intraduktalinė krūties papiloma.  4. Reaktyvi limfadenopatija (1 l/m).  5. Krūties invazyvi vidutiniškai diferencijuota (G2; 7 b. pgl. Nottingham) duktalinė karcinoma, suminis TNM: pT2(navikas 30 mm), pN0(sn)(0/1 l/m), LVI0(limfovaskulinis plitimas neidentifikuotas). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. HER2:reakcijos nėra (0). Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS). Postbiopsiniai pokyčiai krūties audinyje.
answer:  1

 91%|█████████ | 599/661 [03:03<00:18,  3.43it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Kraštai - riebalinis audinys be patologinių pokyčių.    2(2b). Kraštai - riebalinis audinys be patologinių pokyčių.    3. Sarginiai l/m: limfmazgis (1) be patologinių pokyčių; pN0.    4(1). Sektorius. Invazinė duktalinė (kitaip neklasifikuojama) karcinoma pT1c pLVI-0 pR0;  (G1; 4 b. pgl. Nottingham sist.).  Imunotipas nustatytas priešoperaciniame biopsijos tyrime:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 8%.
answer:  1

 91%|█████████ | 600/661 [03:03<00:16,  3.63it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Limfmazgio bioptatai su duktalinės karcinomos metastazėmis.   2. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: silpna (+) reakcija, 25% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 15%.
answer:  1

 91%|█████████ | 601/661 [03:03<00:15,  3.79it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 20-25%.
answer:  2

 91%|█████████ | 602/661 [03:03<00:16,  3.57it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Krūties fibrocistiniai pokyčiai.  2(2b). Lobulinė krūties Carcinoma in situ (LCIS). Krūties fibrocistiniai pokyčiai.  3(3). Reaktyvi limfadenopatija (3 l/m).  4(N1). Krūties invazyvi, gerai diferencijuota (G2; 5 balai pagal Nottingham sis) lobulinė karcinoma, suminis tyrimo TNM: pT1b(m)(trys naviko židiniai - 1,5mm, 1,7mm ir 8mm) pN0(sn)(0/3 l/m); LVI-0(Limfo-Vaskulinė naviko Invazija neidentifikuota).  IHC reakcijos atliktos VPC:B23-5935 tyrime:  "Estrogenų receptoriai: stiprus ar vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 4%."  Vidutinio laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas). Lobulinė krūties Carcinoma in situ (LCIS). Krūties fibroadenoma.  Krūties fibrocistiniai pokyčiai.
answer:  1

 91%|█████████ | 603/661 [03:04<00:16,  3.61it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties audinys.  2(Extra). Krūties audinys.  3(Extra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(18 mm) N(sn)0(0/3 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS)(solidinė, kribriforminė).
answer:  1

 91%|█████████▏| 604/661 [03:04<00:15,  3.77it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma, pT1c(16mm).  N2a: Gerai diferencijuotos invazinės lobulinės karcinomos židiniai (2,4mm ir 0,2mm).  N2b: Krūties audinys be naviko.  N3: Limfmazgiai be naviko (5 l/m); pN0(sn).  N4: Riebalinis audinys be naviko.
answer:  1

 92%|█████████▏| 605/661 [03:04<00:14,  3.86it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 2%.
answer:  1

 92%|█████████▏| 606/661 [03:04<00:15,  3.65it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTAS ATSAKYMAS (žr. molekuliniai):  1. Fibrocistiniai krūties pokyčiai.   2. Krūties duktalinės karcinomos metastazė viename limfmazgyje (1/3 l/m, 7,5 mm).  3. Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) lobulinė karcinoma (21 mm židinys), TNM: pT2(21 mm naviko židinys), LVI2, pN1a(1/6 l/m). Naviko imunofenotipas nustatytas (žr.klinikinius duomenis). Krūties lobulinė karcinoma in situ (LCIS). Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS). Fibrocistiniai krūties pokyčiai: plokščia epitelio atipija, apokrininė epitelio metaplazija.   HER2: reakcija paribinė (2+). HER2 geno amplifikacija NENUSTATYTA (žr. molekulinių tyrimų aprašymą).  4. Fibrocistiniai krūties pokyčiai.   5. Reaktyvi limfadenopatija (3 l/m).
answer:  3

 92%|█████████▏| 607/661 [03:05<00:15,  3.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2a) kraštai. Krūties audinys be patologinių pokyčių.  2(N2b) kraštai. Krūties audinys be patologinių pokyčių.    3. Kairės pažasties limfmazgiai. Karcinomos metastazės 2-se iš 5 limfmazgių; ekstranodulinio plitimo nestebima.    4(1). Pašalintas kairės krūties kvadrantas. Vidutiniškai diferencijuota (G2, 7 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;  pT1c pN1a pR0.  Imunotipas (nustatytas priešoperaciniame biopsijos tyrime):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacijos FISH tyrimo rezultatas neigiamas.  Ki67+ 20%.
answer:  1

 92%|█████████▏| 608/661 [03:05<00:14,  3.72it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.
answer:  2

 92%|█████████▏| 609/661 [03:05<00:13,  3.71it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6,5 mm);  (G2; 7 b. pgl. Nottingham sist.) 1-me bioptate.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: silpna (+) reakcija, 15% naviko ląstelių.  HER2: reakcija teigiama (3+);   Ki67: proliferacinis indeksas 50%. Karštame taške 70%.    Vidutinio laipsnio intraduktalinė neoplazija (DIN2/DCIS).
answer:  2

 92%|█████████▏| 610/661 [03:06<00:14,  3.51it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Krūties fibrocistiniai pokyčiai. Krūties intraduktalinė papiloma.  2(2b). Krūties fibrocistiniai pokyčiai. Krūties intraduktalinė papiloma.  3(N3). Duktalinės karcinomos metastazės limfmazgiuose (3/13 l/m; iki 27mm; ekstranodalinis naviko plitimas).  4(N1). Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) duktalinė karcinoma, pT1c(navikas - 19mm) pN1a(3/13 l/m; iki 27mm; ekstranodalinis naviko plitimas).   IHC reakcijos atliktos VPC:B23-33542 tyrime:  "Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: silpnas dalies membranos nusidažymas mažiau 10% naviko ląstelių.  Ki67+ 10%.  ECAD+."  Odos seborėjinė keratozė. Odos kapiliarinė hemangioma.
answer:  1

 92%|█████████▏| 611/661 [03:06<00:13,  3.69it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi adenokarcinoma, tikėtina lobulinė (ne mažiau kaip vidutiniškai diferencijuota /G2, 6-7 balai pagal Nottingham).  ---   Estrogenų receptoriai: stiprus(+++) branduolinis dažymasis 100% .   Progesterono receptoriai: stiprus(+++) branduolinis dažymasis 100% .   Her2 imunohistocheminė reakcija: neigiama (1+).  Ki67: 8%.
answer:  3

 93%|█████████▎| 612/661 [03:06<00:13,  3.55it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Krūties duktalinės karcinomos metastazė 1/1 limfmazgyje (7 mm).  2(Extra). Reaktyvi limfadenopatija (2 l/m).  3. Krūties invazyvi blogai diferencijuota (G3; 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(12 mm) N(sn)1a(mts 1/3 l/m: 7 mm), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.  Imunofenotipas:   Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  Androgenų receptoriai: nusidažiusių naviko ląstelių nėra.  HER2 imuninė reakcija: teigiama (3+).  Ki67: 70% (hot-spot 90%).   Krūties aukšto laipsnio duktalinė karcinoma in situ (DIN3/DCIS)(kribriforminė, komedo).  Paget`o liga spenelyje.
answer:  3

 93%|█████████▎| 613/661 [03:06<00:13,  3.45it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.  2. Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.  3. Reaktyvi limfadenopatija (4 l/m).   4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham sistemą) duktalinė karcinoma, suminis TNM: pT1c (18 mm navikas) N0(sn)(0/4 l/m) LVI-4 (limfovaskulinė invazija smulkiose ir stambiose kraujagyslėse). Radikalus pašalinimas. Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 solidinis ir kribriforminis tipai). Krūties fibroadenomos (iki 9 mm). Krūties fibrocistiniai pokyčiai, apokrininė metaplazija.    Naviko imunotipas nustatytas biopsijoje:  Estrogenų receptoriai: stipri reakcija 90% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: teigiama (3+).  Ki67 proliferacinis aktyvumas 20%.
answer:  3

 93%|█████████▎| 614/661 [03:07<00:12,  3.66it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 10%.
answer:  1

 93%|█████████▎| 615/661 [03:07<00:13,  3.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). "Kraštai": fibrozuotas krūties audinys; be naviko.   2(ekstra). "Kraštai": krūties fibrocistiniai pokyčiai; be naviko.   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (6 l/m).   4. Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM:   pT1c (navikas 20 mm) N0(sn) (0/6 l/m), LVI-2 (limfovaskulinė invazija smulkiose šakose).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2:reakcijos nėra (0).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).
answer:  3

 93%|█████████▎| 616/661 [03:07<00:12,  3.69it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.
answer:  1

 93%|█████████▎| 617/661 [03:07<00:12,  3.59it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties audinio fibrozė.  2. Krūties audinio fibrozė.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(16 mm) pN0(sn)(0/3 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir papilinis tipai). R0(radikali rezekcija).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 12% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 5%.
answer:  1

 93%|█████████▎| 618/661 [03:08<00:12,  3.53it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Krūties lobulinės karcinomos metastazės trijuose limfmazgiuose (3/3 l/m, 14 mm skersmens).   2. Krūties invazyvi vidutiniškai diferencijuota (G2; 6 b. pgl. Nottingham) lobulinė karcinoma su duktalinės karcinomos komponentu (<3%), suminis TNM: pT2(m)(5 naviko židiniai nuo 1 mm iki 33 mm), pN2a(5/16 l/m), LVI2(limfovaskulinis plitimas). Krūties lobulinė karcinoma in situ (LCIS). I naviko židinys nuo koaguliuoto rezekcijos krašto nutolęs per <0,1 mm. Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą.  3. Krūties lobulinės karcinomos metastazės dviejuose limfmazgiuose (2/10 l/m, 5 mm skersmens).
answer:  3

 94%|█████████▎| 619/661 [03:08<00:13,  3.15it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Papildytas HER2 FISH tyrimu:  1(2a, ekstra). "Kraštai": dažais žymėtoje pusėje - fibrozuotas krūties audinys; be naviko;  (dažais nežymėtoje pusėje - krūties fibrocistiniai pokyčiai: paprasta ir atipinė intraduktalinė hiperplazija).   2(2b, ekstra). "Kraštai": dažais žymėtoje pusėje - fibrozuotas krūties audinys; be naviko;   (dažais nežymėtoje pusėje - krūties fibrocistiniai pokyčiai: paprasta ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė).   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(1). Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b (navikas 7 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).   Kalcifikatai.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis ir papilinis tipai; bendra pokyčių zona su naviku ~15 mm skersmens).   Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė intraduktalinė hiperplazija, sklerozuojanti adenozė, stulpinių ląstelių pokytis su apikaline sekrecija, CCAPSS).
answer:  1

 94%|█████████▍| 620/661 [03:08<00:12,  3.16it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Krūties invazyvi, vidutiniškai diferencijuota (G2) mucininė karcinoma.  Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas).  2(2b). Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis, mikropapilinis tipas).  3. Reaktyvi limfadenopatija (1 l/m).  4(pap. kraštas). Krūties audinys.   5. Krūties invazyvi, vidutiniškai diferencijuota (G2; 6 balai pagal Nottingham sis) mucininė karcinoma, suminis tyrimo TNM: pT1c(m)(du naviko židiniai: 16mm ir 14mm) pN0(sn)(0/1 l/m).   IHC reakcijos atliktos VPC:B23-31824 tyrime:   "Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 3%."  Krūties žemo laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas).
answer:  1

 94%|█████████▍| 621/661 [03:09<00:12,  3.22it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Atlikti pjūviai Prosigna.  1(ekstra). Riebalinis audinys.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(18 mm navikas) pN0(sn)(0/3 l/m) LVI-2(limfovaskulinė invazija).   R0(radikali rezekcija). Aukšto laipsnio duktalinė karcinoma in situ (DCIS/DIN3, kribriforminis tipas).    Imunofenotipas:   Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 15%.
answer:  1

 94%|█████████▍| 622/661 [03:09<00:12,  3.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  PAPILDYTAS ATSAKYMAS HER2 FISH TYRIMU:   1(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (5 l/m).     2. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) lobulinė karcinoma,   SUMINIS TNM:   pT2 (navikas 21 mm) N0(sn) (0/5 l/m),    LVI-0 (limfovaskulinė invazija neidentifikuota).    Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija paribinė (2+); atliekamas patikslinantis HER2 FISH tyrimas.    Molekuliniai tyrimai:   HER2 geno amplifikacija nenustatyta (interpretuojama įvertinus HER2 IHC tyrimą; žr. molekulinio tyrimo aprašymą ir pastabas).    Krūties lobulinė intraepitelinė neoplazija (LCIS).  Krūties fibrocistiniai pokyčiai (paprasta, papilinė ir atipinė duktalinė hiperplazija, sklerozuojanti ir mikroglandulinė adenozė, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS), apokrininė metaplazija; fokaliai fibrocistiniai pokyčiai - kompleksiniai, sudarantys iki 10 mm skersmens židinius).   Krūties rezekcijos kraštas - be naviko.
answer:  3

 94%|█████████▍| 623/661 [03:09<00:11,  3.24it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma;   pT(m)2(22 mm, 27 mm)   pN1a(2,2 mm 1-me/10 l/m)   pR0 (0,5 mm)   pPn1(perineurinis plitimas).  Metastazės limfmazgyje imunotipas:  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).    Imunotipas priešoperaciniame naviko tyrime:  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 10% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%.
answer:  1

 94%|█████████▍| 624/661 [03:10<00:11,  3.26it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Fibrocistiniai krūties pokyčiai.  2. Fibrocistiniai krūties pokyčiai, paprasta intraduktalinė hiperplazija. Intraduktalinė krūties papiloma.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi, vidutiniškai diferencijuota (G2; 7 balai pagal Nottingham sis) duktalinė karcinoma, suminis tyrimo TNM: pT1c(navikas - 13mm) pN0(sn)(0/3 l/m); LVI-0 (Limfo-Vaskulinė naviko Invazija neidentifikuota).   IHC reakcijos atliktos VPC:B23-19620 tyrime:  "Estrogenų receptoriai: stipri (+++)  reakcija, 95% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 90% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67+ 15%."  Vidutinio laipsnio intraduktalinė karcinoma (DCIS; kribriforminis tipas).
answer:  2

 95%|█████████▍| 625/661 [03:10<00:10,  3.50it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi blogai diferencijuota (G3, 9b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: teigiama ribinė neigiama (0).  Ki67 proliferacinis aktyvumas 40%.
answer:  3

 95%|█████████▍| 626/661 [03:10<00:09,  3.60it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1-2: Gerai diferencijuota (G1, 4 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 85% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%.  N3: Limfmazgio bioptatai ne naviko.
answer:  1

 95%|█████████▍| 627/661 [03:10<00:09,  3.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Kairė  N1-2: Intraduktalinė krūties Carcinoma in situ (Din2/DCIS; solidinis/kribriforminis tipas).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 20% naviko ląstelių.  ---------  Dešinė  N3: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 10%, vietomis iki 20%.
answer:  3

 95%|█████████▌| 628/661 [03:11<00:08,  3.75it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi blogai diferencijuota (G3, 8-9 balai pagal Nottingham) duktalinė adenokarcinoma.  Estrogenų receptoriai: nusidažiusių naviko ląstelių nėra.  Progesterono receptoriai: nusidažiusių naviko ląstelių nėra.  HER2: imuninė reakcija neigiama (0 balų).  Ki67: 45%.
answer:  3

 95%|█████████▌| 629/661 [03:11<00:08,  3.61it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Po operacinės medžiagos tyrimo patikslintas N1 naviko tipas  Dešinė  N1: Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė lobulinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 2%.  ------------  Kairė  N2: Mucininė krūties karcinoma (G2, 6 balai pgl Nottingham).  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.
answer:  1

 95%|█████████▌| 630/661 [03:11<00:09,  3.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(1a, ekstra). "Viršutinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.   2(1b, ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija); be naviko.    3(2, ekstra). "Deš. pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (3 l/m).     4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) mucininė karcinoma,   SUMINIS TNM:   pT1c (navikas 12 mm) N0(sn) (0/3 l/m),   LVI-2 (limfovaskulinė invazija smulkiose šakose).     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atliktos r-jos šio tyrimo metu:  HER2: reakcija neigiama (1+).    Krūties vidutinio laipsnio duktalinė karcinoma in situ (DIN2/DCIS: kribriforminis ir papilinis tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   Nuo sektoriaus rezekcijos krašto navikas nutolęs 0,15 mm.
answer:  1

 95%|█████████▌| 631/661 [03:12<00:08,  3.62it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  N1: Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma; pT1c(20mm).  N2ab: Audiniai be naviko.  N3: Limfmazgis (1 l/m) be naviko; pN0(sn).
answer:  1

 96%|█████████▌| 632/661 [03:12<00:07,  3.71it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2)(Extra). Reaktyvi limfadenopatija (3 l/m).  2(1a)(Extra). Krūties audinys.  3(1b)(Extra). Krūties audinys.  4. Krūties invazyvi gerai diferencijuota (G1; 5 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT2(33 mm) N(sn)0(0/3 l/m), LVI-2(limfovaskulinė invazija). Radikalus pašalinimas.  Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).
answer:  1

 96%|█████████▌| 633/661 [03:12<00:07,  3.58it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(Extra). Reaktyvi limfadenopatija (6 l/m).  2(Extra). Reaktyvi limfadenopatija (1 l/m).  3. Krūties invazyvi blogai diferencijuota (G3; 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT(m)2(2 naviko židiniai: 28 mm ir 4 mm) N(sn)0(0/7 l/m), LVI-0(limfovaskulinės invazijos neidentifikuota). Radikalus pašalinimas (R0).   Naviko imunoprofilis nustatytas ankstesniame tyrime (žr. pastabą).   Odos seborėjinė keratozė.
answer:  3

 96%|█████████▌| 634/661 [03:12<00:08,  3.32it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Pjūvio kraštai. Krūties fibrocistiniai pokyčiai, apokrininė metaplazija. Naviko plitimo nėra.    2(ekstra). Pjūvio kraštai. Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.     3(ekstra). Sarginiai l/m. Duktalinės karcinomos metastazė 2-se/9 limfmazgių (iki 2,1 mm metastazė).     4. Sektorius.   Krūties invazyvi vidutiniškai diferencijuota duktalinė karcinoma   (G2, I navike - 7 balai, II navike - 6 balai pagal Nottingham sistemą) ,    pT1c(m) (12 mm ir 2 mm naviko židiniai)    pN1a(sn)(2-se/9 l/m su mts iki 2,1 mm)     pLVI-2 (limfovaskulinė invazija smulkiose gyslose)    pR0(radikalus pašalinimas).  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%. Karštame taške 20%.
answer:  3

 96%|█████████▌| 635/661 [03:13<00:07,  3.42it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 6 mm);  (G3; 9 b. pgl. Nottingham sist.) 2-se krūties audinio stulpeliuose.  Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 85%.
answer:  3

 96%|█████████▌| 636/661 [03:13<00:08,  2.99it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2a). Krūties lobulinė karcinoma (židinys 1mm). Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.   2(N2b). Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.  3(N4a). Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.  4(N4b). Fibrocistiniai krūties pokyčiai; intraduktaliniai mikrokalcifikatai.  5(N1). Krūties invazyvi, blogai diferencijuota (G3; 8 balai pagal Nottingham sis) lobulinė karcinoma (multižidininis navikas), pT2(m)(dauginiai naviko židiniai nuo 0,6mm iki 31mm); LVI-0(Limfo-Vaskulinė Invazija neidentifikuota).  Estrogenų receptoriai: reakcija teigiama (stipri branduolių r-ja, 100% naviko ląstelių).   Progesterono receptoriai: reakcija teigiama (silpna/vidutinė/stipri branduolių r-ja, 85% naviko ląstelių).   HER2: žema imunohistocheminė raiška (1+).  Ki67 proliferacinis aktyvumas ~20%, fokaliai iki 30%.   Lobulinė krūties karcinoma in situ (LCIS). Krūties aukšto laipsnio intraduktalinė karcinoma (DCIS; solidinis ir kribriforminis tipas, -komedo tipo nekrozės). Fibrocistiniai krūties pokyčiai; sklerozuojanti adenozė. LCIS struktūros - rezekcijos krašte.  6(N3). Krūties žemo ir vidutinio laipsnio intraduktalinė karcinoma (DCIS; solidinis ir kribriforminis tipas; -komedo tipo nekrozės).    IHC reakcijos atliktos VPC:B23-41914 tyrime:  "Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių."  Lobulinė krūties karcinoma in situ (LCIS). Fibrocistiniai krūties pokyčiai; sklerozuojanti adenozė; intraduktaliniai ir ekstraduktaliniai mikrokalcifikatai. Rezekcijos kraštas be naviko.
answer:  3

 96%|█████████▋| 637/661 [03:13<00:07,  3.11it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 5% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 12%, vietomis iki 15%.
answer:  2

 97%|█████████▋| 638/661 [03:14<00:07,  3.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(N2a). Krūties fibrocistiniai pokyčiai.  2(N2b). Krūties fibrocistiniai pokyčiai.  3(N3). Reaktyvi limfadenopatija (3 l/m).  4(N1). Krūties invazyvi duktalinė karcinoma (gerai diferencijuota / G1 / 5 balai pagal Nottingham), TNM (Nr.1-Nr4): pT1c(m) (1,1 cm ir 1,0 cm naviko židiniai) pN(sn)0 (0/3 l/m). LVI0(limfovaskulinės invazijos nėra).  ---  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus ir vidutinis branduolių nusidažymas 60% naviko ląstelių.  Her2 imuninė reakcija: neigiama (1+).  Ki67: 1-2%.
answer:  1

 97%|█████████▋| 639/661 [03:14<00:07,  3.10it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Paruošti pjūviai Prosigna.  1. Krūties vidutiniškai diferencijuota (G2, 6b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: T1b(9 mm navikas) pN1a(sn)(1/5 l/m MTS 16 mm) LVI-2(limfovaskulinė invazija ).  R0(radikali rezekcija).    Imunofenotipas (biopsijoje):   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 80% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 3%.    2. Krūties audinio fibrozė.  3. Krūties audinio fibrozė.  4. Duktalinės karcinomos metastazė limfmazgyje (1/5 l/m MTS 16 mm).
answer:  3

 97%|█████████▋| 640/661 [03:14<00:06,  3.26it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+; HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.
answer:  2

 97%|█████████▋| 641/661 [03:15<00:06,  3.01it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra) Dešinė užspenelinė zona: fibrocistiniai pokyčiai.   2(ekstra) Deš. pažasties sarginiai l/m. Reaktyvi limfadenopatija (2 l/m).   3. Dešinės krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(16 mm navikas) N0(sn)(2 l/m) LVI-0(limfovaskulinė invazija neidentifikuota) R0(radikali rezekcija). Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, DIN3, kribriforminis ir papilinis tipai).  Krūties fibrocistiniai pokyčiai, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).     Naviko imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 70%.  Androgenų receptoriai: reakcijos nėra.       4. Kairės krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma, pT1c(11 mm židinys) LVI-0(limfovaskulinė invazija neidentifikuota) R0(radikali rezekcija). Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, DIN3, solidinis, komedo tipai). Krūties fibrocistiniai pokyčiai, ląstelinga (florid) adenozė, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS). Lobulinė karcinoma in situ (LCIS).  Naviko imunofenotipas:   Estrogenų receptoriai: reakcijos nėra.  Progesterono receptoriai: reakcijos nėra.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 70%.
answer:  3

 97%|█████████▋| 642/661 [03:15<00:05,  3.29it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinis branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 5%.
answer:  1

 97%|█████████▋| 643/661 [03:15<00:05,  3.19it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, sklerozuojanti adenozė).   2(2b, ekstra). "Kraštai": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   3(ekstra). "Sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(1). Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1c (navikas 11 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).   Naviko nekrozė iki 15%.     Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.   Kartotinai atlikta šio tyrimo metu:   HER2: reakcija neigiama (1+).    Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis ir komedo tipai).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija ir sklerozuojanti adenozė).   Nuo sektoriaus rezekcijos krašto naviko struktūros nutolusios 0,6 mm.
answer:  3

 97%|█████████▋| 644/661 [03:16<00:05,  3.25it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a). Krūties audinys.  2(2b). Krūties audinys.  3. Reaktyvi limfadenopatija (3 l/m).  4. Krūties invazyvi vidutiniškai diferencijuota (G2 6b. pagal Nottingham) mucininė karcinoma, TNM: pT1c(navikas 20 mm), pN0(sn)(0/3 l/n), LVI0(neidentifikuota). Naviko imunofenotipas nustatytas ankstesniame tyrime, žr.pastabą. Ki67: proliferacinis indeksas 5%. Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  Krūties hamartoma (1,5 cm). Fibrocistiniai krūties pokyčiai: intraduktalinė krūties papiloma. Atipinė duktalinė hiperplazija (ADH).  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).
answer:  1

 98%|█████████▊| 645/661 [03:16<00:04,  3.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 7 balai pagal Nottingham) duktalinė karcinoma;  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: silpna (+) reakcija, 3% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67: proliferacinis indeksas 10%.    Vidutinio laipsnio intraduktalinė karcinoma (DCIS/DIN2 su plitimu operaciniame krašte).    pT2(30 mm ir 5 mm), pLVI-2, pN1a, pR0.
answer:  2

 98%|█████████▊| 646/661 [03:16<00:04,  3.14it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a, ekstra). "Kraštai": krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai; ~15 mm skersmens židinys).  2(2b, ekstra). "Kraštai": krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai; ~12 mm skersmens židinys).  3(ekstra). "Kairės pažasties sarginiai limfmazgiai": reaktyvi limfadenopatija ir lipomatozė (2 l/m).     4(1). Krūties invazyvi blogai diferencijuota (G3, 8 balai pagal Nottingham) duktalinė karcinoma,   SUMINIS TNM:   pT1b(m) (naviko židiniai: I - 5,2 mm; II - 0,4 mm; III - 0,35 mm) N0(sn) (0/2 l/m),   LVI-0 (limfovaskulinė invazija neidentifikuota).   Imunofenotipas: nustatytas ankstesnio tyrimo metu, žr. pastabą.     Krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, komedo tipai; ~50 mm zona su išskiriančiu ~16 mm židiniu aplink didžiausiąjį I naviką).   Krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija, apokrininė metaplazija).   Incidentinė krūties fibroadenoma (4,35 mm).   DCIS komponentas sektoriaus rezekcijos krašte.    5(4). "Papildomi kraštai": fibrozuotas riebalinis audinys.
answer:  1

 98%|█████████▊| 647/661 [03:17<00:04,  3.21it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. Pjūvio kraštai. Krūties audinys su židinine lėtine uždegimine infiltracija. Naviko plitimo nėra.     2. Pjūvio kraštai. Krūties audinys be patologinių pokyčių. Naviko plitimo nėra.      3. Sarginis l/m. Reaktyvi limfadenopatija (3 l/m).     4. Sektorius. Krūties invazyvi blogai diferencijuota (G3, 9 balai pagal Nottingham sistemą) duktalinė karcinoma,    suminis TNM: pT1c (16 mm navikas)   pN0(sn)(3 l/m)    pLVI-0(limfovaskulinė invazija neidentifikuota).   pR0(radikalus pašalinimas).  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 85% naviko ląstelių.  HER2: reakcija neigiama (0/1+).  Ki67: proliferacinis indeksas 30%.
answer:  3

 98%|█████████▊| 648/661 [03:17<00:03,  3.41it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 12% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 15%.
answer:  2

 98%|█████████▊| 649/661 [03:17<00:03,  3.49it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G2; 7 b. pgl. Nottingham sist.) 1-me krūties audinio stulpelyje.  Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2: reakcija paribinė (2+); HER2 geno amplifikacija nenustatyta (galutinai interpretuota įvertinus HER2 IHC rezultatą; žr. molekulinio tyrimo aprašymą ir pastabą).  Ki67: proliferacinis indeksas 40%.
answer:  2

 98%|█████████▊| 650/661 [03:17<00:03,  3.52it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Invazinė duktalinė (kitaip neklasifikuojama) karcinoma (mažiausiai iki 9 mm);  (G2; 6 b. pgl. Nottingham sist.) 3-se stulpeliuose.  Ki67: proliferacinis indeksas 55%.  HER2 geno amplifikacija nenustatyta (žr. molekulinių tyrimų aprašymą).    Išoriniai IHC:  Estrogenų receptorių raišką teigiama (stipri raiška 100 proc. naviko ląstelių branduoliuose).  Progesteronų receptorių raišką teigiama (vidutinė raiška 50 proc. naviko ląstelių branduoliuose).  HER2 raiška paribinė (2+: silpna cirkuliari raiška 30 proc. naviko ląstelių membranoje).  CK5: raiškos nestebima.
answer:  2

 98%|█████████▊| 651/661 [03:18<00:02,  3.41it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Paruošti pjūviai Prosigna.  1(ekstra). Krūties audinio fibrozė.  2(ekstra). Krūties audinio fibrozė.  3(ekstra). Reaktyvi limfadenopatija (1 l/m).    4. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(10,5 mm navikas) pN0(sn)(0/1 l/m) LVI-2(limfovaskulinė invazija). R0(radikali rezekcija). Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2, kribriforminis ir solidinis tipai). Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija.    Imunofenotipas:(biopsijoje):  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.
answer:  1

 99%|█████████▊| 652/661 [03:18<00:02,  3.63it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G, balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Her2 imuninė reakcija: neigiama 1+.  Ki67+ 6%.
answer:  1

 99%|█████████▉| 653/661 [03:18<00:02,  3.63it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(2a) Kraštai. Krūties audinys, naviko plitimo nėra.    2(2b) Kraštai. Krūties audinys, naviko plitimo nėra.     3 Sarginiai l/m. Reaktyvi limfadenopatija (2 l/m).     4(1) Sektorius.   Krūties invazyvi vidutiniškai diferencijuota (G2, 7 b. pgl Nottingham) duktalinė karcinoma,   pT2(22 mm)   pN(sn)0(0/2 l/m)   pLVI-0 (limfovaskulinės invazijos nestebima)  Naviko imunotipas nustatytas biopsijoje (žr.pastabą).  Vidutinio laipsnio duktalinė karcinoma in situ (DCIS/DIN2 kribriforminis tipas).
answer:  1

 99%|█████████▉| 654/661 [03:18<00:01,  3.78it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 100% naviko ląstelių.  Progesterono receptoriai: branduolių nusidažymo nėra, 0% naviko ląstelių.  Her2 imuninė reakcija: neigiama 0+.  Ki67+ 8%.
answer:  1

 99%|█████████▉| 655/661 [03:19<00:01,  3.45it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1. N2 - retroareoliarinė sritis: Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, tinklinis tipas) / (DIN3).    2. N3 -  sarginiai limfmazgiai: viename iš 3 limfmazgių karcinomos plitimo daugybiniai židiniai iki 3 mm; pN(sn)1a.      3. N4 papildomai keliuose kanaliukuose: Krūties aukšto laipsnio duktalinė karcinoma in situ (DCIS, tinklinis tipas) / (DIN3).    4. N5- papildomai - dalis areolės su oda ir poodžiu: be patologinių pokyčių.     5. N1 - pašalinta dešinė krūtis.  Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) mikropapilinė karcinoma;  pT(m)1c(15 mm, 8 mm) pR0.   Imunofenotipas (nustatytas priešoperaciniame naviko biopsijos tyrime):   Estrogenų receptoriai: neigiama reakcija.  Progesterono receptoriai: neigiama reakcija.  Her2 imuninė reakcija: teigiama (3+).  Ki67 proliferacinis aktyvumas 10%.    Krūties daugybiniai aukšto laipsnio duktalinės karcinomos in situ (DCIS, tinklinis tipas) / (DIN3) židiniai.  Krūties fibrocistiniai pokyčiai:  sklerozuojanti adenozė.
answer:  1

 99%|█████████▉| 656/661 [03:19<00:01,  3.40it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(ekstra). Reaktyvi limfadenopatija (2 l/m).  2. Krūties invazyvi gerai diferencijuota (G1, 5b. pagal Nottingham) duktalinė karcinoma, SUMINIS TNM: pT1c(m)(11 mm ir 9 mm navikai) pN0(sn)(0/2 l/m) LVI-0(limfovaskulinė invazija neidentifikuota). R0(radikali rezekcija).   Žemo laipsnio duktalinė karcinoma in situ (DCIS/DIN1, kribriforminis ir papilinis tipai). Lobulinė karcinoma in situ (LCIS). Fibroadenoma (6 mm).  Krūties fibrocistiniai pokyčiai: paprastoji intraduktalinė hiperplazija, stulpinių ląstelių pokytis su apikaline sekrecija (CCAPSS).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 10% naviko ląstelių.    Her2 imuninė reakcija: neigiama (1+).  Ki67 proliferacinis aktyvumas 3%.
answer:  1

 99%|█████████▉| 657/661 [03:19<00:01,  3.07it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  1(intraoperative margin). Invasive lobular carcinoma.  2.(intraoperative margin). Invasive lobular carcinoma (1.3 mm focus).  3.(intraoperative) lymph node. Breast lobular carcinoma metastasis in a lymph node (1/4 l/n, MTS 3.2 mm).  4.(intraoperative margin). Invasive lobular carcinoma (2 mm focus in marked margin).    5. Breast invasive moderately differentiated (G2, 7b. Nottingham syst.) lobular carcinoma. TNM: pT2(m)(31 mm, 1.3 mm tumors) pN1a(sn)(1/4 l/n, MTs 3.2 mm) LVI-2 (lymphovascular invasion). R1 (carcinoma reaches the edge of the sector, spreads in additional edges No. 1, 2, 4). Lobular carcinoma in situ (LCIS).    Immunophenotype:  Estrogen receptors: strong reaction in 95% of tumor cells.  Progesterone receptors: strong reaction in 100% of tumor cells.  Her2 immunoreaction: negative (0).  Ki67 proliferative activity 5%.        LT  1(ekstra). Invazyvi lobulinė karcinoma.  2(ekstra). Invazyvi lobulinė karcinoma (1,3 mm židinys).  3(ekstra). Krūties lobulinės karcinomos metastazė limfmazgyje (1/4 l/m, MTS 3,2 mm).  4. Papildomas kraštas. Invazyvi lobulinė karcinoma (2 mm židinys žymėtame krašte).    5. Krūties invazyvi vidutiniškai diferencijuota (G2, 7b. pagal Nottingham) lobulinė karcinoma, SUMINIS TNM: pT2(m)(31 mm, 1,3 mm navikai) pN1a(sn)(1/4 l/m, MTs 3,2 mm) LVI-2(limfovaskulinė invazija). R1(karcinoma siekia sektoriaus kraštą, plinta papildomuose Nr.1,2,4 kraštuose). Lobulinė karcinoma in situ (LCIS).    Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 95% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 100% naviko ląstelių.    Her2 imuninė reakcija: neigiama (0).  Ki67 proliferacinis aktyvumas 5%.
answer:  1

100%|█████████▉| 658/661 [03:20<00:00,  3.32it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham sistemą) duktalinė karcinoma su mucininės diferenciacijos požymiais   Estrogenų receptoriai: stipri (+++)  reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 15%.  Progesterono receptoriai: stipri (+++) reakcija, 1% naviko ląstelių.
answer:  2

100%|█████████▉| 659/661 [03:20<00:00,  3.48it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Vidutiniškai diferencijuota (G2, 6 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: stiprus branduolių nusidažymas 95% naviko ląstelių.  Progesterono receptoriai: stiprus branduolių nusidažymas 90% naviko ląstelių.  Her2 imuninė reakcija: ribinė 2+, HER2 geno amplifikacija nenustatyta.  Ki67+ 12%.
answer:  2

100%|█████████▉| 660/661 [03:20<00:00,  3.66it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

PatologijosDiag:  Krūties invazyvi blogai diferencijuota (G3, 8b. pagal Nottingham) duktalinė karcinoma.     Imunofenotipas:   Estrogenų receptoriai: stipri reakcija 100% naviko ląstelių.    Progesterono receptoriai: stipri reakcija 95% naviko ląstelių.    Her2 imuninė reakcija: teigiama (3+).  Ki67 proliferacinis aktyvumas 60%.
answer:  3

100%|██████████| 661/661 [03:20<00:00,  3.29it/s]

PatologijosDiag:  1. Duktalinės karcinomos metastazė limfmazgyje.   2. Gerai diferencijuota (G1, 5 balai pgl Nottingham) krūties invazinė duktalinė karcinoma.  Estrogenų receptoriai: vidutinė (++) reakcija, 95% naviko ląstelių.  Progesterono receptoriai: vidutinė (++) reakcija, 80% naviko ląstelių.  HER2: reakcija neigiama (1+).  Ki67+ 10%.
answer:  1

In [ ]:
evaluateWeighted(g_labels, g_pred) # weighted

Accuracy: 0.546142208774584
Precision: 0.36453451067017484
Recall: 0.3859607652130658
F1 Score: 0.33597760165522794
------
Accuracy: 0.546142208774584
Precision: 0.6969215180559006
Recall: 0.546142208774584
F1 Score: 0.5385293160140388

# Fine Tuning

In [ ]:
!pip install trl
!pip install evaluate

In [ ]:
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    BitsAndBytesConfig,
    HfArgumentParser,
    TrainingArguments,
    pipeline,
    logging,
)
from peft import (
    LoraConfig,
    PeftModel,
    prepare_model_for_kbit_training,
    get_peft_model,
)
import os, torch
from trl import SFTTrainer
from datasets import Dataset
from transformers import DataCollatorWithPadding
import evaluate
import numpy as np
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

os.environ["WANDB_MODE"] = "disabled"

torch_dtype = torch.float16
attn_implementation = "eager"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch_dtype,
    bnb_4bit_use_double_quant=True,
)

# for accessing models
login(token="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")

# "microsoft/Phi-4-mini-instruct"
# "google/gemma-2-2b"
# "meta-llama/Llama-3.2-1B"
modelName = "meta-llama/Llama-3.2-1B"

tokenizer = AutoTokenizer.from_pretrained(model)
tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.pad_token = tokenizer.eos_token

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

lora_config = LoraConfig(
    r = 16,
    lora_alpha = 8,
    target_modules = ['q_proj', 'k_proj', 'v_proj', 'o_proj'],
    lora_dropout = 0.05,
    bias = 'none',
    task_type = 'SEQ_CLS'
)

In [ ]:
accuracy = evaluate.load("accuracy")

def compute_metrics_binary(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average='binary')

    accuracy_metric = accuracy.compute(predictions=predictions, references=labels)
    return {
        'accuracy': accuracy_metric['accuracy'],
        'precision': precision,
        'recall': recall,
        'f1': f1
    }

def compute_metrics_weighted(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average='weighted')

    accuracy_metric = accuracy.compute(predictions=predictions, references=labels)
    return {
        'accuracy': accuracy_metric['accuracy'],
        'precision': precision,
        'recall': recall,
        'f1': f1
    }

In [10]:
def getMetrics(dataset, weighted):
  true_labels = []
  predicted_labels = []

  for data in dataset:
      text = data["text"]
      true_label = data["label"]

      result = classifier(text)
      predicted_label = result[0]["label"]

      true_label_mapped = true_label

      true_labels.append(true_label_mapped)
      predicted_labels.append(predicted_label)

  if(weighted):
    accuracy = accuracy_score(true_labels, predicted_labels)
    precision = precision_score(true_labels, predicted_labels, average='weighted')
    recall = recall_score(true_labels, predicted_labels, average='weighted')
    f1 = f1_score(true_labels, predicted_labels, average='weighted')
  else:
    accuracy = accuracy_score(true_labels, predicted_labels)
    precision = precision_score(true_labels, predicted_labels, pos_label=1)
    recall = recall_score(true_labels, predicted_labels, pos_label=1)
    f1 = f1_score(true_labels, predicted_labels, pos_label=1)

  return {
      "accuracy": accuracy,
      "precision": precision,
      "recall": recall,
      "f1": f1
  }

## cTNM != pTNM

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(
    modelName,
    quantization_config=bnb_config,
    device_map="auto",
    attn_implementation=attn_implementation,
    num_labels=2)

model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, lora_config)

model.config.pad_token_id = tokenizer.pad_token_id
model.config.use_cache = False
model.config.pretraining_tp = 1

# so it generates labels as 0 and 1 instead of LABEL_0 and LABEL_1
model.config.label2id = {0: 0, 1: 1}
model.config.id2label = {0: 0, 1: 1}

In [ ]:
trainC = train.dropna(subset=['cTNM'])
valC = val.dropna(subset=['cTNM'])
testC = test.dropna(subset=['cTNM'])

trainC['text'] = 'klasifikacija: ' + trainC['cTNM'] + ' pagal tekstą: ' + trainC['input']
valC['text'] = "klasifikacija: " + valC['cTNM'] + "pagal tekstą: " + valC['input']
testC['text'] = "klasifikacija: " + testC['cTNM'] + "pagal tekstą: " + testC['input']

trainF = trainC.rename(columns={"ctnm eq ptnm": "label"})
valF = valC.rename(columns={"ctnm eq ptnm": "label"})
testF = testC.rename(columns={"ctnm eq ptnm": "label"})

train_datasetF = Dataset.from_pandas(trainF)
val_datasetF = Dataset.from_pandas(valF)
test_datasetF = Dataset.from_pandas(testF)

def preprocess_function(row):
  return tokenizer(row["text"])

tokenized_train_dataF = train_datasetF.map(preprocess_function, batched=True)
tokenized_val_dataF = val_datasetF.map(preprocess_function, batched=True)

In [7]:
training_args = TrainingArguments(
    output_dir = 'finetune_mini',
    learning_rate = 1e-5,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 16,
    num_train_epochs = 20,
    weight_decay = 0.01,
    evaluation_strategy = 'epoch',
    save_strategy = 'epoch',
    load_best_model_at_end = True,
    report_to=None
)

trainer = SFTTrainer(
    model=model,
    train_dataset=tokenized_train_dataF,
    eval_dataset=tokenized_val_dataF,
    peft_config=lora_config,
    tokenizer=tokenizer,
    args=training_args,
    data_collator=data_collator,
    compute_metrics=compute_metrics_binary
)
trainer.train()

Converting train dataset to ChatML:   0%|          | 0/180 [00:00<?, ? examples/s]

Applying chat template to train dataset:   0%|          | 0/180 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/180 [00:00<?, ? examples/s]

Converting eval dataset to ChatML:   0%|          | 0/26 [00:00<?, ? examples/s]

Applying chat template to eval dataset:   0%|          | 0/26 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/26 [00:00<?, ? examples/s]

No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.

TrainOutput(global_step=460, training_loss=0.6688599296238111, metrics={'train_runtime': 9462.698, 'train_samples_per_second': 0.38, 'train_steps_per_second': 0.049, 'total_flos': 6.08919953301504e+16, 'train_loss': 0.6688599296238111})

In [8]:
trainer.save_model("finetune_mini")
adapter_path = "./finetune_mini"
model_with_adapter = PeftModel.from_pretrained(model, adapter_path)
classifier = pipeline("text-classification", model=model_with_adapter, tokenizer=tokenizer)

Device set to use cuda:0
The model 'PeftModelForSequenceClassification' is not supported for text-classification. Supported models are ['AlbertForSequenceClassification', 'BartForSequenceClassification', 'BertForSequenceClassification', 'BigBirdForSequenceClassification', 'BigBirdPegasusForSequenceClassification', 'BioGptForSequenceClassification', 'BloomForSequenceClassification', 'CamembertForSequenceClassification', 'CanineForSequenceClassification', 'LlamaForSequenceClassification', 'ConvBertForSequenceClassification', 'CTRLForSequenceClassification', 'Data2VecTextForSequenceClassification', 'DebertaForSequenceClassification', 'DebertaV2ForSequenceClassification', 'DiffLlamaForSequenceClassification', 'DistilBertForSequenceClassification', 'ElectraForSequenceClassification', 'ErnieForSequenceClassification', 'ErnieMForSequenceClassification', 'EsmForSequenceClassification', 'FalconForSequenceClassification', 'FlaubertForSequenceClassification', 'FNetForSequenceClassification', 'FunnelForSequenceClassification', 'GemmaForSequenceClassification', 'Gemma2ForSequenceClassification', 'GlmForSequenceClassification', 'GPT2ForSequenceClassification', 'GPT2ForSequenceClassification', 'GPTBigCodeForSequenceClassification', 'GPTNeoForSequenceClassification', 'GPTNeoXForSequenceClassification', 'GPTJForSequenceClassification', 'HeliumForSequenceClassification', 'IBertForSequenceClassification', 'JambaForSequenceClassification', 'JetMoeForSequenceClassification', 'LayoutLMForSequenceClassification', 'LayoutLMv2ForSequenceClassification', 'LayoutLMv3ForSequenceClassification', 'LEDForSequenceClassification', 'LiltForSequenceClassification', 'LlamaForSequenceClassification', 'LongformerForSequenceClassification', 'LukeForSequenceClassification', 'MarkupLMForSequenceClassification', 'MBartForSequenceClassification', 'MegaForSequenceClassification', 'MegatronBertForSequenceClassification', 'MistralForSequenceClassification', 'MixtralForSequenceClassification', 'MobileBertForSequenceClassification', 'ModernBertForSequenceClassification', 'MPNetForSequenceClassification', 'MptForSequenceClassification', 'MraForSequenceClassification', 'MT5ForSequenceClassification', 'MvpForSequenceClassification', 'NemotronForSequenceClassification', 'NezhaForSequenceClassification', 'NystromformerForSequenceClassification', 'OpenLlamaForSequenceClassification', 'OpenAIGPTForSequenceClassification', 'OPTForSequenceClassification', 'PerceiverForSequenceClassification', 'PersimmonForSequenceClassification', 'PhiForSequenceClassification', 'Phi3ForSequenceClassification', 'PhimoeForSequenceClassification', 'PLBartForSequenceClassification', 'QDQBertForSequenceClassification', 'Qwen2ForSequenceClassification', 'Qwen2MoeForSequenceClassification', 'ReformerForSequenceClassification', 'RemBertForSequenceClassification', 'RobertaForSequenceClassification', 'RobertaPreLayerNormForSequenceClassification', 'RoCBertForSequenceClassification', 'RoFormerForSequenceClassification', 'SqueezeBertForSequenceClassification', 'StableLmForSequenceClassification', 'Starcoder2ForSequenceClassification', 'T5ForSequenceClassification', 'TapasForSequenceClassification', 'TransfoXLForSequenceClassification', 'UMT5ForSequenceClassification', 'XLMForSequenceClassification', 'XLMRobertaForSequenceClassification', 'XLMRobertaXLForSequenceClassification', 'XLNetForSequenceClassification', 'XmodForSequenceClassification', 'YosoForSequenceClassification', 'ZambaForSequenceClassification', 'Zamba2ForSequenceClassification'].

In [ ]:
def getMetrics(dataset, weighted):
  true_labels = []
  predicted_labels = []

  for data in dataset:
      text = data["text"]
      true_label = data["label"]

      result = classifier(text)
      predicted_label = result[0]["label"]

      true_label_mapped = true_label

      true_labels.append(true_label_mapped)
      predicted_labels.append(predicted_label)

  if(weighted):
    accuracy = accuracy_score(true_labels, predicted_labels)
    precision = precision_score(true_labels, predicted_labels, average='weighted')
    recall = recall_score(true_labels, predicted_labels, average='weighted')
    f1 = f1_score(true_labels, predicted_labels, average='weighted')
  else:
    accuracy = accuracy_score(true_labels, predicted_labels)
    precision = precision_score(true_labels, predicted_labels, pos_label=1)
    recall = recall_score(true_labels, predicted_labels, pos_label=1)
    f1 = f1_score(true_labels, predicted_labels, pos_label=1)

  return {
      "accuracy": accuracy,
      "precision": precision,
      "recall": recall,
      "f1": f1
  }

In [35]:
getMetrics(test_datasetF, weighted=False)

{'accuracy': 0.3617021276595745,
 'precision': 0.38461538461538464,
 'recall': 0.4166666666666667,
 'f1': 0.4}

In [ ]:
!zip -r /content/finetune_mini.zip /content/finetune_mini

In [34]:
text = test_datasetF[5]
print(text["text"])
print("label", text["label"])
classifier(text["text"])

klasifikacija: is00pagal tekstą: 1(1a)- viršutinis kraštas, skubu  2(1b)- apatinis kraštas, skubu  3(2)- Kairės krūties navikas, planinis. 3. Krūties sektorius 8,5x6,5x5 cm, su odos lopu 7x3,5 cm. Krūties audinyje, pjūvyje pilkšvas, neaiškių ribų plotas 32x25 mm, nuo giliojo rezekcijos krašto nutolęs 0,6 cm, nuo odos - 2,7 cm.. 1(1a, ekstra). "Viršutinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).   2(1b, ekstra). "Apatinis kraštas": krūties fibrocistiniai pokyčiai (paprasta intraduktalinė hiperplazija).      3(2). Kompleksiniai krūties  audinio pokyčiai (~32 mm skersmens židinys):   - krūties invazyvi bent vidutiniškai diferencijuota (G2, 6 balai pagal Nottingham, žr. pastabą) duktalinė (kitaip neklasifikuojama) karcinoma, pT1a(m) daugybiniai smulkūs (mikro)invazyvūs židiniai, didžiausias ~2 mm), LVI-0 (definityvi limfovaskulinė invazija neidentifikuota). Kalcifikatai. Imunofenotipas:    Estrogenų receptoriai: reakcijos nėra.   Progesterono receptoriai: reakcijos nėra.   HER2: reakcijos nėra (0).  Ki67: proliferacinis indeksas ~5%;    - krūties vidutinio-aukšto laipsnio duktalinė karcinoma in situ (DIN2-3/DCIS: solidinis, kribriforminis, papilinis ir komedo tipai);   - krūties fibrocistiniai pokyčiai (paprasta ir atipinė duktalinė hiperplazija, sklerozuojanti adenozė, apokrininė metaplazija).   Židininė lėtinė menkai aktyvi ksantominė-svetimkūnio tipo uždegiminė reakcija.. 1(1a, ekstra). "Viršutinis kraštas": ryškiai fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar fokaliai hiperplastišku epiteliu; latakuose "putoti" makrofagai; be naviko.   2(1b, ekstra). "Apatinis kraštas": ryškiai fibrozuotas krūties audinys su dilatuotais kanaliukais, klotais dvisluoksniu ar fokaliai hiperplastišku epiteliu; latakuose "putoti" makrofagai; be naviko.   3(2). POKYČIŲ PLOTAS (~ 32 mm židinys):   - dominuojantys dilatuoti latakai/kanaliukai ir pseudo-/cistinės ertmės su fokaliai išlikusiomis pavienėmis (CK14+) mioepitelinėmis ląstelėmis, spindžiuose - pseudo-/mikro- ir fokaliniai negausūs papiliniai intraliuminaliniai proliferatai, suformuoti ląstelių vidutinio gausumo šviesiai eozinofiliška citoplazma, vidutinio kalibro ir stambiais, apvaliais/ovaliais, vidutiniškai polimorfiškais branduoliais, fokaliai su aiškia nukleole; spindžiuose nekrotinis dedritas, negausios PAS+ ar AB+ mucinų užuominos. Šalia proliferatų nedideli invazyvūs "nubyrančių" pavienių ląstelių, jų grupių ir nedidelių besiliejančių trabekulių suformuoti židiniai iki 1,95 mm skersmens; ląstelės vidutiniškai polimorfiškos vidutinio gausumo citoplazma, su smulkiomis nukleolėmis, be žymesnio mitotinio aktyvumo. Aplink stambiausius kompleksus - židininė gausi limfocitinė, plazmocitinė, fokaliai ksantominių makrofagų reakcija, tretinės limfoidinės struktūros. Kalcifikatai. Svetimkūnio tipo gigantų reakcija. Šalia nedideli solidiniai, kribriforminiai, papiliniai intraduktaliniai naviko ląstelių proliferatai su centrinėmis nekrozės zonomis. Kai kur įsiterpiančios zonos, kuriose - vidutinio kalibro ir dilatuoti kanaliukai, kloti dvisluoksniu ar hiperplastišku epiteliu, fokaliai su ryškesne atipija, apokrinės metaplazijos zonomis, fokaliai smulkūs suspausti kanaliukai, kloti dvisluoksniu epiteliu.   SEKTORIAUS REZEKCIJOS KRAŠTAS: fibrozuotas krūties audinys.. 3(2). Navikas (blokas 12):  GATA3(+)(brand.r-ja)15%(ryškesnė r-ja in situ komponente);   CK14(+) fokaliai išlikęs atenuotas miopitelinis sl. stambiuose kompleksuose; (-)smulkiuose invazyviuose kompleksuose;   CK7(+++)(citopl.membr.r-ja)100% abiejuose komp
label 1

[{'label': 0, 'score': 0.960358738899231}]

## Tumor

In [41]:
model = AutoModelForSequenceClassification.from_pretrained(
    modelName,
    quantization_config=bnb_config,
    device_map="auto",
    attn_implementation=attn_implementation,
    num_labels=15)

model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, lora_config)

model.config.pad_token_id = tokenizer.pad_token_id
model.config.use_cache = False
model.config.pretraining_tp = 1

model.config.label2id = {i: i for i in range(15)}
model.config.id2label = {i: i for i in range(15)}

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-3.2-1B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
label_map = {
    "0": 0,
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "x": 5,
    "is": 6,
    "1mi": 7,
    "1a": 8,
    "1b": 9,
    "1c": 10,
    "4a": 11,
    "4b": 12,
    "4c": 13,
    "4d": 14
}

trainF = train.rename(columns={"Tumor (T)": "label", "input": "text"})
valF = val.rename(columns={"Tumor (T)": "label", "input": "text"})
testF = test.rename(columns={"Tumor (T)": "label", "input": "text"})

trainF['label'] = trainF['label'].map(label_map)
valF['label'] = valF['label'].map(label_map)
testF['label'] = testF['label'].map(label_map)

train_datasetF = Dataset.from_pandas(trainF)
val_datasetF = Dataset.from_pandas(valF)
test_datasetF = Dataset.from_pandas(testF)

def preprocess_function(row):
  return tokenizer(row["text"])

tokenized_train_dataF = train_datasetF.map(preprocess_function, batched=True)
tokenized_val_dataF = val_datasetF.map(preprocess_function, batched=True)

In [51]:
training_args = TrainingArguments(
    output_dir = 'finetune_T',
    learning_rate = 1e-5,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 16,
    num_train_epochs = 20,
    weight_decay = 0.01,
    evaluation_strategy = 'epoch',
    save_strategy = 'epoch',
    load_best_model_at_end = True,
    report_to=None
)

trainer = SFTTrainer(
    model=model,
    train_dataset=tokenized_train_dataF,
    eval_dataset=tokenized_val_dataF,
    peft_config=lora_config,
    tokenizer=tokenizer,
    args=training_args,
    data_collator=data_collator,
    compute_metrics=compute_metrics_weighted
)
trainer.train()

Converting train dataset to ChatML:   0%|          | 0/661 [00:00<?, ? examples/s]

Applying chat template to train dataset:   0%|          | 0/661 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/661 [00:00<?, ? examples/s]

Converting eval dataset to ChatML:   0%|          | 0/94 [00:00<?, ? examples/s]

Applying chat template to eval dataset:   0%|          | 0/94 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/94 [00:00<?, ? examples/s]

No label_names provided for model class `PeftModelForSequenceClassification`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
A ConfigError was raised whilst setting the number of model parameters in Weights & Biases config.

TrainOutput(global_step=1660, training_loss=1.3686214584902108, metrics={'train_runtime': 14337.6087, 'train_samples_per_second': 0.922, 'train_steps_per_second': 0.116, 'total_flos': 7.80548197311529e+16, 'train_loss': 1.3686214584902108})

In [52]:
trainer.save_model("finetune_T")
adapter_path = "./finetune_T"
model_with_adapter = PeftModel.from_pretrained(model, adapter_path)
classifier = pipeline("text-classification", model=model_with_adapter, tokenizer=tokenizer)

Device set to use cuda:0
The model 'PeftModelForSequenceClassification' is not supported for text-classification. Supported models are ['AlbertForSequenceClassification', 'BartForSequenceClassification', 'BertForSequenceClassification', 'BigBirdForSequenceClassification', 'BigBirdPegasusForSequenceClassification', 'BioGptForSequenceClassification', 'BloomForSequenceClassification', 'CamembertForSequenceClassification', 'CanineForSequenceClassification', 'LlamaForSequenceClassification', 'ConvBertForSequenceClassification', 'CTRLForSequenceClassification', 'Data2VecTextForSequenceClassification', 'DebertaForSequenceClassification', 'DebertaV2ForSequenceClassification', 'DiffLlamaForSequenceClassification', 'DistilBertForSequenceClassification', 'ElectraForSequenceClassification', 'ErnieForSequenceClassification', 'ErnieMForSequenceClassification', 'EsmForSequenceClassification', 'FalconForSequenceClassification', 'FlaubertForSequenceClassification', 'FNetForSequenceClassification', 'FunnelForSequenceClassification', 'GemmaForSequenceClassification', 'Gemma2ForSequenceClassification', 'GlmForSequenceClassification', 'GPT2ForSequenceClassification', 'GPT2ForSequenceClassification', 'GPTBigCodeForSequenceClassification', 'GPTNeoForSequenceClassification', 'GPTNeoXForSequenceClassification', 'GPTJForSequenceClassification', 'HeliumForSequenceClassification', 'IBertForSequenceClassification', 'JambaForSequenceClassification', 'JetMoeForSequenceClassification', 'LayoutLMForSequenceClassification', 'LayoutLMv2ForSequenceClassification', 'LayoutLMv3ForSequenceClassification', 'LEDForSequenceClassification', 'LiltForSequenceClassification', 'LlamaForSequenceClassification', 'LongformerForSequenceClassification', 'LukeForSequenceClassification', 'MarkupLMForSequenceClassification', 'MBartForSequenceClassification', 'MegaForSequenceClassification', 'MegatronBertForSequenceClassification', 'MistralForSequenceClassification', 'MixtralForSequenceClassification', 'MobileBertForSequenceClassification', 'ModernBertForSequenceClassification', 'MPNetForSequenceClassification', 'MptForSequenceClassification', 'MraForSequenceClassification', 'MT5ForSequenceClassification', 'MvpForSequenceClassification', 'NemotronForSequenceClassification', 'NezhaForSequenceClassification', 'NystromformerForSequenceClassification', 'OpenLlamaForSequenceClassification', 'OpenAIGPTForSequenceClassification', 'OPTForSequenceClassification', 'PerceiverForSequenceClassification', 'PersimmonForSequenceClassification', 'PhiForSequenceClassification', 'Phi3ForSequenceClassification', 'PhimoeForSequenceClassification', 'PLBartForSequenceClassification', 'QDQBertForSequenceClassification', 'Qwen2ForSequenceClassification', 'Qwen2MoeForSequenceClassification', 'ReformerForSequenceClassification', 'RemBertForSequenceClassification', 'RobertaForSequenceClassification', 'RobertaPreLayerNormForSequenceClassification', 'RoCBertForSequenceClassification', 'RoFormerForSequenceClassification', 'SqueezeBertForSequenceClassification', 'StableLmForSequenceClassification', 'Starcoder2ForSequenceClassification', 'T5ForSequenceClassification', 'TapasForSequenceClassification', 'TransfoXLForSequenceClassification', 'UMT5ForSequenceClassification', 'XLMForSequenceClassification', 'XLMRobertaForSequenceClassification', 'XLMRobertaXLForSequenceClassification', 'XLNetForSequenceClassification', 'XmodForSequenceClassification', 'YosoForSequenceClassification', 'ZambaForSequenceClassification', 'Zamba2ForSequenceClassification'].

In [53]:
getMetrics(test_datasetF, weighted=True)

{'accuracy': 0.031578947368421054,
 'precision': 0.09326315789473684,
 'recall': 0.031578947368421054,
 'f1': 0.03295415959252971}

In [66]:
text = test_datasetF[8]
print(text["text"])
print("label", text["label"])
classifier(text["text"])

1 ėminio aprašas: 2 biopsiniai stulpleiai. 2 biopsiniai stulpeliai: I - 12 mm; II - 8 mm.. Krūties invazyvi gerai diferencijuota (G1, 5 balai pagal Nottingham sistemą) duktalinė karcinoma   (plitimas 2/2 biopsiniuose stulpeliuose, iki 11,5 mm mikroskopiškai).  Naviko imunofenotipas:  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  Progesterono receptoriai: stipri (+++) reakcija, 100% naviko ląstelių.  HER2:reakcijos nėra (0).  Ki67: proliferacinis indeksas 2%. Karštame taške 5%.. Krūties audinyje (2/2 biopsiniuose stulpeliuose, iki 11,5 mm ilgyje) - trabekulės ir grandinėlės, iš ląstelių su negausia citoplazma, vidutinio kalibro, kiek netaisyklingo kontūro, hiperchromiškais, švelniai, nežymiai polimorfiškais branduoliais. Mitozių navike <1/10DPRL.. Blokas 1:  E-Cadherin: stipri (+++) reakcija, 100% naviko ląstelių membranose.  Estrogenų receptoriai: stipri (+++) reakcija, 100% naviko ląstelių branduoliuose.  HER2: reakcijos naviko ląstelių membranoje nėra.  Ki67: reakcija branduoliuose, 2% naviko lą
label 2

[{'label': 11, 'score': 0.2775099277496338}]

In [ ]:
!zip -r /content/finetune_T.zip /content/finetune_T

## Node

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(
    modelName,
    quantization_config=bnb_config,
    device_map="auto",
    attn_implementation=attn_implementation,
    num_labels=14)

model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, lora_config)

model.config.pad_token_id = tokenizer.pad_token_id
model.config.use_cache = False
model.config.pretraining_tp = 1

model.config.label2id = {i: i for i in range(14)}
model.config.id2label = {i: i for i in range(14)}

In [ ]:
label_map = {
    "0": 0,
    "1": 1,
    "2": 2,
    "3": 3,
    "x": 4,
    "1mi": 5,
    "1a": 6,
    "1b": 7,
    "1c": 8,
    "2a": 9,
    "2b": 10,
    "3a": 11,
    "3b": 12,
    "3c": 13
}

trainF = train.rename(columns={"Node (N)": "label", "input": "text"})
valF = val.rename(columns={"Node (N)": "label", "input": "text"})
testF = test.rename(columns={"Node (N)": "label", "input": "text"})

trainF['label'] = trainF['label'].map(label_map)
valF['label'] = valF['label'].map(label_map)
testF['label'] = testF['label'].map(label_map)

train_datasetF = Dataset.from_pandas(trainF)
val_datasetF = Dataset.from_pandas(valF)
test_datasetF = Dataset.from_pandas(testF)

def preprocess_function(row):
  return tokenizer(row["text"])

tokenized_train_dataF = train_datasetF.map(preprocess_function, batched=True)
tokenized_val_dataF = val_datasetF.map(preprocess_function, batched=True)

In [ ]:
training_args = TrainingArguments(
    output_dir = 'finetune_N',
    learning_rate = 1e-5,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 16,
    num_train_epochs = 20,
    weight_decay = 0.01,
    evaluation_strategy = 'epoch',
    save_strategy = 'epoch',
    load_best_model_at_end = True,
    report_to=None
)

trainer = SFTTrainer(
    model=model,
    train_dataset=tokenized_train_dataF,
    eval_dataset=tokenized_val_dataF,
    peft_config=lora_config,
    tokenizer=tokenizer,
    args=training_args,
    data_collator=data_collator,
    compute_metrics=compute_metrics_weighted
)
trainer.train()

In [ ]:
trainer.save_model("finetune_N")
adapter_path = "./finetune_N"
model_with_adapter = PeftModel.from_pretrained(model, adapter_path)
classifier = pipeline("text-classification", model=model_with_adapter, tokenizer=tokenizer)

In [ ]:
getMetrics(test_datasetF, weighted=True)

## Metastasis

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(
modelName    quantization_config=bnb_config,
    device_map="auto",
    attn_implementation=attn_implementation,
    num_labels=2)

model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, lora_config)

model.config.pad_token_id = tokenizer.pad_token_id
model.config.use_cache = False
model.config.pretraining_tp = 1

model.config.label2id = {0: 0, 1: 1}
model.config.id2label = {0: 0, 1: 1}

In [ ]:
trainF = train.rename(columns={"Metastasis (M)": "label", "input": "text"})
valF = val.rename(columns={"Metastasis (M)": "label", "input": "text"})
testF = test.rename(columns={"Metastasis (M)": "label", "input": "text"})

train_datasetF = Dataset.from_pandas(trainF)
val_datasetF = Dataset.from_pandas(valF)
test_datasetF = Dataset.from_pandas(testF)

def preprocess_function(row):
  return tokenizer(row["text"])

tokenized_train_dataF = train_datasetF.map(preprocess_function, batched=True)
tokenized_val_dataF = val_datasetF.map(preprocess_function, batched=True)

In [ ]:
training_args = TrainingArguments(
    output_dir = 'finetune_M',
    learning_rate = 1e-5,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 16,
    num_train_epochs = 20,
    weight_decay = 0.01,
    evaluation_strategy = 'epoch',
    save_strategy = 'epoch',
    load_best_model_at_end = True,
    report_to=None
)

trainer = SFTTrainer(
    model=model,
    train_dataset=tokenized_train_dataF,
    eval_dataset=tokenized_val_dataF,
    peft_config=lora_config,
    tokenizer=tokenizer,
    args=training_args,
    data_collator=data_collator,
    compute_metrics=compute_metrics_binary
)
trainer.train()

In [ ]:
trainer.save_model("finetune_M")
adapter_path = "./finetune_M"
model_with_adapter = PeftModel.from_pretrained(model, adapter_path)
classifier = pipeline("text-classification", model=model_with_adapter, tokenizer=tokenizer)

In [ ]:
getMetrics(test_datasetF, weighted=False)

## Grade

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(
    modelName,
    quantization_config=bnb_config,
    device_map="auto",
    attn_implementation=attn_implementation,
    num_labels=5)

model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, lora_config)

model.config.pad_token_id = tokenizer.pad_token_id
model.config.use_cache = False
model.config.pretraining_tp = 1

model.config.label2id = {i: i for i in range(5)}
model.config.id2label = {i: i for i in range(5)}

In [ ]:
label_map = {
    "0": 0,
    "1": 1,
    "2": 2,
    "3": 3,
    "x": 4
}

trainF = train.rename(columns={"G": "label", "PatologijosDiag": "text"})
valF = val.rename(columns={"G": "label", "PatologijosDiag": "text"})
testF = test.rename(columns={"G": "label", "PatologijosDiag": "text"})

trainF['label'] = trainF['label'].map(label_map)
valF['label'] = valF['label'].map(label_map)
testF['label'] = testF['label'].map(label_map)

train_datasetF = Dataset.from_pandas(trainF)
val_datasetF = Dataset.from_pandas(valF)
test_datasetF = Dataset.from_pandas(testF)

def preprocess_function(row):
  return tokenizer(row["text"])

tokenized_train_dataF = train_datasetF.map(preprocess_function, batched=True)
tokenized_val_dataF = val_datasetF.map(preprocess_function, batched=True)

In [ ]:
training_args = TrainingArguments(
    output_dir = 'finetune_G',
    learning_rate = 1e-5,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 16,
    num_train_epochs = 20,
    weight_decay = 0.01,
    evaluation_strategy = 'epoch',
    save_strategy = 'epoch',
    load_best_model_at_end = True,
    report_to=None
)

trainer = SFTTrainer(
    model=model,
    train_dataset=tokenized_train_dataF,
    eval_dataset=tokenized_val_dataF,
    peft_config=lora_config,
    tokenizer=tokenizer,
    args=training_args,
    data_collator=data_collator,
    compute_metrics=compute_metrics_weighted
)
trainer.train()

In [ ]:
trainer.save_model("finetune_G")
adapter_path = "./finetune_G"
model_with_adapter = PeftModel.from_pretrained(model, adapter_path)
classifier = pipeline("text-classification", model=model_with_adapter, tokenizer=tokenizer)

In [ ]:
getMetrics(test_datasetF, weighted=True)